Repository openshift/release, pull requests merged in 2018-10, with the labels that each got.

#1762 Remove the `dockerless-build-temporary` branch
  ci-operator/jobs/openshift/image-registry/openshift-image-registry-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-master-presubmits.yaml
  ci-operator/jobs/openshift/origin-web-console-server/openshift-origin-web-console-server-master-presubmits.yaml
  ci-operator/jobs/openshift/origin-web-console/openshift-origin-web-console-master-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-cli-pre-rebase-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
Labels: approved, lgtm, size/M

#1763 script for populate ci-operator-configs cm
  ci-operator/populate-ci-operator-configs.sh
Labels: approved, lgtm, size/M

#1758 cluster-network-operator: add to prow and registries
  ci-operator/config/openshift/cluster-network-operator/OWNERS
  ci-operator/jobs/openshift/cluster-network-operator/OWNERS
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/M

#1765 Add cluster-logging-operator configuration
  cluster/ci/config/prow/plugins.yaml
Labels: approved, do-not-merge/hold, lgtm, size/XS

#1766 Add elasticsearch-operator configuration
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#1767 Remove router gate on AWS installer PRs for now
  ci-operator/templates/cluster-launch-installer-e2e.yaml
Labels: approved, lgtm, size/S

#1771 Add debugging and a retry to oc wait
  ci-operator/templates/cluster-launch-installer-e2e.yaml
Labels: approved, lgtm, size/M

#1773 templates: add retry on oc wait command
  ci-operator/templates/cluster-launch-installer-e2e.yaml
Labels: approved, lgtm, size/S

#1772 ci-operator/jobs/openshift/installer: update regex
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#1582 Rename "openshift-ansible-aws-rhel" to "aws-centos" and add release-3.11 job
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-3.11-presubmits.yaml
  cluster/ci/config/prow/plugins.yaml
  cluster/test-deploy/aws-centos/.gitignore
  cluster/test-deploy/aws-centos/.type
  cluster/test-deploy/aws-centos/OWNERS
  cluster/test-deploy/aws-centos/vars-origin.yaml
  cluster/test-deploy/aws-centos/vars.yaml
Labels: approved, lgtm, size/M

#1775 make extended cluster up optional
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#1777 teardown should wait indefinitely for creation of /tmp/shared/exit file
  ci-operator/templates/openshift/openshift-azure/build-azure-image.yaml
Labels: approved, lgtm, sig/azure, size/XS

#1779 revert waiting indefinitely for /tmp/shared/exit file from teardown
  ci-operator/templates/openshift/openshift-azure/build-azure-image.yaml
Labels: approved, lgtm, sig/azure, size/XS

#1780 Rename OSA node image build template
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-periodics.yaml
  ci-operator/templates/openshift/openshift-azure/build-node-image.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, do-not-merge/hold, lgtm, sig/azure, size/S

#1769 populate-owners: Also populate ci-operator/templates/{org}/{repo}
  tools/populate-owners/README.md
  tools/populate-owners/main.go
  tools/populate-owners/main_test.go
Labels: approved, lgtm, size/M

#1784 Fix sorting to apply only to args for ci-operator jobs
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
Labels: approved, size/XS

#1782 openshift-ansible AWS: terminate instances
  cluster/test-deploy/aws-atomic/vars.yaml
  cluster/test-deploy/aws-centos/vars.yaml
Labels: approved, lgtm, size/XS

#1788 Minimal validation fix requiring no status migrations
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-3.11-presubmits.yaml
  hack/validate-prow-job-semantics.py
Labels: approved, lgtm, size/M

#1790 openshift-ansible: add more nodes and skip some tests in aws-centos
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-3.11-presubmits.yaml
  cluster/test-deploy/aws-centos/vars.yaml
Labels: approved, lgtm, size/M

#1787 service catalog 311 /test service-catalog
  ci-operator/jobs/openshift/service-catalog/openshift-service-catalog-master-presubmits.yaml
  ci-operator/jobs/openshift/service-catalog/openshift-service-catalog-release-3.11-presubmits.yaml
Labels: approved, lgtm, size/S

#1792 cluster-launch-installer-e2e: Move into installer subdirectory
  Makefile
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#1706 Auto-generate jobs for openshift/openshift-ansible
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-master-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-3.10-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-3.10-presubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-3.11-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-3.11-presubmits.yaml
  hack/validate-generated-config.sh
Labels: approved, lgtm, size/L

#1696 Auto-generate jobs for openshift/cluster-operator
  ci-operator/config/openshift/cluster-operator/tools.yaml
  ci-operator/jobs/openshift/cluster-operator/openshift-cluster-operator-master-presubmits.yaml
  hack/validate-generated-config.sh
Labels: approved, lgtm, size/M

#1701 Auto-generate jobs for openshift/builder
  ci-operator/config/openshift/builder/master.yaml
  ci-operator/jobs/openshift/builder/openshift-builder-master-postsubmits.yaml
  ci-operator/jobs/openshift/builder/openshift-builder-master-presubmits.yaml
  hack/validate-generated-config.sh
Labels: approved, lgtm, size/M

#1793 Use RELEASE_IMAGE_LATEST for CVO payload
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
Labels: approved, lgtm, size/XS

#1699 Auto-generate jobs for openshift/origin
  ci-operator/jobs/openshift/origin/openshift-origin-master-postsubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-3.10-postsubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-3.10-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-3.11-postsubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-3.11-presubmits.yaml
  hack/validate-generated-config.sh
Labels: approved, lgtm, size/L

#1794 Update CI Operator config with a simpler approach
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#1798 Installer image shouldn't use LOCAL_IMAGE_INSTALLER
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
Labels: approved, lgtm, size/XS

#1800 openshift-ansible: make sure RPM building code is consistent
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-master.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-3.10.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-3.11.yaml
Labels: approved, lgtm, size/XS

#1805 don't run service-catalog ci tests for cluster up
  ci-operator/jobs/openshift/origin/openshift-origin-cli-pre-rebase-presubmits.yaml
Labels: approved, lgtm, size/S

#1761 cluster-launch-installer-e2e: Start setting expirationDate again
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
Labels: approved, lgtm, sig/azure, size/S

#1786 Fix validator, add some new checks
  ci-operator/jobs/openshift/builder/openshift-builder-master-presubmits.yaml
  ci-operator/jobs/openshift/image-registry/openshift-image-registry-master-presubmits.yaml
  ci-operator/jobs/openshift/image-registry/openshift-image-registry-release-3.11-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/jobs/openshift/jenkins/openshift-jenkins-master-presubmits.yaml
  ci-operator/jobs/openshift/jenkins/openshift-jenkins-openshift-3.10-presubmits.yaml
  ci-operator/jobs/openshift/jenkins/openshift-jenkins-openshift-3.11-presubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-3.11-presubmits.yaml
  ci-operator/jobs/openshift/origin-web-console-server/openshift-origin-web-console-server-master-presubmits.yaml
  ci-operator/jobs/openshift/origin-web-console-server/openshift-origin-web-console-server-release-3.11-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-3.10-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-3.11-presubmits.yaml
  ci-operator/jobs/tnozicka/openshift-acme/tnozicka-openshift-acme-master-presubmits.yaml
  hack/validate-prow-job-semantics.py
Labels: approved, lgtm, size/L

#1799 Create and use a test entrypoint in templatized e2e
  ci-operator/jobs/openshift/builder/openshift-builder-master-presubmits.yaml
  ci-operator/jobs/openshift/image-registry/openshift-image-registry-master-presubmits.yaml
  ci-operator/jobs/openshift/image-registry/openshift-image-registry-release-3.10-presubmits.yaml
  ci-operator/jobs/openshift/image-registry/openshift-image-registry-release-3.11-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/jobs/openshift/jenkins/openshift-jenkins-master-presubmits.yaml
  ci-operator/jobs/openshift/jenkins/openshift-jenkins-openshift-3.10-presubmits.yaml
  ci-operator/jobs/openshift/jenkins/openshift-jenkins-openshift-3.11-presubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-3.10-presubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-3.11-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
  ci-operator/jobs/openshift/origin-web-console-server/openshift-origin-web-console-server-master-presubmits.yaml
  ci-operator/jobs/openshift/origin-web-console-server/openshift-origin-web-console-server-release-3.10-presubmits.yaml
  ci-operator/jobs/openshift/origin-web-console-server/openshift-origin-web-console-server-release-3.11-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-3.11-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  ci-operator/templates/cluster-launch-e2e-gmontero-testing.yaml
  ci-operator/templates/cluster-launch-e2e-openshift-ansible.yaml
  ci-operator/templates/cluster-launch-e2e-upgrade.yaml
  ci-operator/templates/cluster-launch-e2e.yaml
  ci-operator/templates/cluster-launch-src.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure-conformance.yaml
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure.yaml
Labels: approved, lgtm, sig/azure, size/L

#1810 Update the doc on ci-operator/ file layout
  ci-operator/README.md
Labels: approved, lgtm, size/XS

#1808 Add ci-op config filename validation job
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  hack/validate-ci-operator-config-filename.py
Labels: approved, lgtm, size/M

#1811 nil fixes
  hack/validate-ci-operator-config-filename.py
Labels: approved, lgtm, size/S

#1804 add OS_TEST=1 environment variable
  ci-operator/config/containers/libpod/containers-libpod-master.yaml
Labels: approved, lgtm, size/XS

#1754 add simple test suite for Heketi to openshift-ci
  ci-operator/config/heketi/heketi/heketi-heketi-master.yaml
  ci-operator/jobs/heketi/heketi/heketi-heketi-master-presubmits.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/M

#1781 Add a template for OSA base image builds
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-periodics.yaml
  ci-operator/templates/openshift/openshift-azure/build-base-image.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, sig/azure, size/L

#1595 Add e2e tests to configuration files, generate jobs
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-3.10.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-3.11.yaml
  ci-operator/config/tnozicka/openshift-acme/tnozicka-openshift-acme-master.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-3.11-presubmits.yaml
  ci-operator/jobs/tnozicka/openshift-acme/tnozicka-openshift-acme-master-presubmits.yaml
Labels: approved, lgtm, size/L

#1813 e2e-aws master: remove extra space in TEST_SKIP
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-3.11-presubmits.yaml
Labels: approved, lgtm, size/XS

#1814 Test path was unintentionally broken by a refactor
  ci-operator/templates/cluster-launch-e2e-openshift-ansible.yaml
  ci-operator/templates/cluster-launch-e2e-upgrade.yaml
  ci-operator/templates/cluster-launch-e2e.yaml
  ci-operator/templates/cluster-launch-src.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
Labels: approved, lgtm, size/M

#1816 RELEASE_IMAGE_LATEST can be explicit (either via target or template)
  ci-operator/templates/cluster-launch-e2e-upgrade.yaml
  ci-operator/templates/cluster-launch-e2e.yaml
  ci-operator/templates/cluster-launch-src.yaml
Labels: approved, lgtm, size/XS

#1817 cluster-launch-installer-e2e: Pull all logs in parallel
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
Labels: approved, lgtm, size/M

#1818 pull-ci-openshift-openshift-ansible-release-3.11-e2e-atomic: fix incorrect renames
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-3.11-presubmits.yaml
Labels: approved, lgtm, size/XS

#1822 rename secrets in ci-operator templates
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-periodics.yaml
  ci-operator/templates/openshift/openshift-azure/build-base-image.yaml
  ci-operator/templates/openshift/openshift-azure/build-node-image.yaml
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure-conformance.yaml
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure-upgrade.yaml
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure.yaml
Labels: approved, lgtm, sig/azure, size/M

#1823 disable artifact gathering for build base image
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-periodics.yaml
Labels: approved, lgtm, sig/azure, size/XS

#1807 osa add conformance
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-postsubmits.yaml
Labels: approved, lgtm, sig/azure, size/M

#1826 More ci-operator cmd/args splits
  ci-operator/jobs/openshift/image-registry/openshift-image-registry-master-presubmits.yaml
  ci-operator/jobs/openshift/image-registry/openshift-image-registry-release-3.11-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-3.11-presubmits.yaml
  ci-operator/jobs/openshift/origin-web-console-server/openshift-origin-web-console-server-master-presubmits.yaml
  ci-operator/jobs/openshift/origin-web-console-server/openshift-origin-web-console-server-release-3.11-presubmits.yaml
Labels: approved, lgtm, size/L

#1829 Add ruby-25 dependency for the logging team
  Makefile
Labels: approved, lgtm, size/XS

#1802 Make the gcp serial job always on in CI
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#1830 use ruby-25 scl base image for fluentd
  ci-operator/config/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-master.yaml
Labels: approved, lgtm, size/XS

#1831 Gate merges to openshift-apiserver-operator with e2e-aws
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
Labels: approved, lgtm, size/XS

#1836 Move TEST_PARALLELISM to TEST_COMMAND
  ci-operator/jobs/openshift/builder/openshift-builder-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#1837 Add openshift_ansible tests to ci-operator config
  ci-operator/config/openshift/builder/openshift-builder-master.yaml
  ci-operator/config/openshift/image-registry/openshift-image-registry-master.yaml
  ci-operator/config/openshift/image-registry/openshift-image-registry-release-3.11.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-master.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-3.11.yaml
  ci-operator/config/openshift/origin-web-console-server/openshift-origin-web-console-server-master.yaml
  ci-operator/config/openshift/origin-web-console-server/openshift-origin-web-console-server-release-3.11.yaml
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-3.11.yaml
Labels: approved, lgtm, size/M

#1838 Add openshift_installer e2e tests
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
Labels: approved, lgtm, size/S

#1835 Run gcp-major-upgrade test on openshift-ansible's release-3.11 and -3.10
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-3.10-presubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-3.11-presubmits.yaml
Labels: approved, lgtm, size/XS

#1776 Enable testing for private-preview branch
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-private-preview-1.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-private-preview-1-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-private-preview-1-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/L

#1839 Use sync private preview tag in e2e targets
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-private-preview-1-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-private-preview-1-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/S

#1828 aws-atomic: provision 3 nodes
  cluster/test-deploy/aws-atomic/vars.yaml
Labels: approved, lgtm, size/S

#1843 Collect ginkgo logs in artifacts
  ci-operator/templates/openshift/openshift-azure/build-node-image.yaml
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure-upgrade.yaml
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure.yaml
Labels: approved, lgtm, sig/azure, size/S

#1841 reduce parallelism some more, pipeline tests are still failing
  ci-operator/config/openshift/builder/openshift-builder-master.yaml
  ci-operator/jobs/openshift/builder/openshift-builder-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#1845 Revert sync tag changes
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-private-preview-1.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-private-preview-1-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-private-preview-1-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/S

#1848 fix target publish of cluster-logging-operator
  ci-operator/config/openshift/cluster-logging-operator/openshift-cluster-logging-operator-master.yaml
Labels: approved, lgtm, size/XS

#1850 Add a gating job to operator framework
  ci-operator/jobs/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-master-presubmits.yaml
Labels: approved, lgtm, size/M

#1851 Gate all top priority operators on successful install
  ci-operator/jobs/openshift/cluster-dns-operator/openshift-cluster-dns-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-kube-apiserver-operator/openshift-cluster-kube-apiserver-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-kube-controller-manager-operator/openshift-cluster-kube-controller-manager-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-kube-scheduler-operator/openshift-cluster-kube-scheduler-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-openshift-apiserver-operator/openshift-cluster-openshift-apiserver-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-openshift-controller-manager-operator/openshift-cluster-openshift-controller-manager-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/service-ca-operator/openshift-service-ca-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/service-serving-cert-signer/openshift-service-serving-cert-signer-master-presubmits.yaml
Labels: approved, lgtm, size/XL

#1852 Gate CVO merge on successful AWS install
  ci-operator/jobs/openshift/cluster-version-operator/openshift-cluster-version-operator-master-presubmits.yaml
Labels: approved, lgtm, size/M

#1854 Gate publishing origin releases by verifying the payload
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
Labels: approved, lgtm, size/M

#1853 Openshift-azure needs mockgen in the test image
  projects/azure/base-images/test-base.yaml
Labels: approved, lgtm, sig/azure, size/XS

#1849 update monitoring install variable
  cluster/test-deploy/aws-atomic/vars-origin.yaml
  cluster/test-deploy/aws-centos/vars-origin.yaml
  cluster/test-deploy/gcp-crio-dev/vars-origin.yaml
  cluster/test-deploy/gcp-crio/vars-origin.yaml
  cluster/test-deploy/gcp-dev-ha-static/vars-origin.yaml
  cluster/test-deploy/gcp-dev-ha/vars-origin.yaml
  cluster/test-deploy/gcp-dev/vars-origin.yaml
  cluster/test-deploy/gcp-ha-static/vars-origin.yaml
  cluster/test-deploy/gcp-ha/vars-origin.yaml
  cluster/test-deploy/gcp/vars-origin.yaml
Labels: approved, lgtm, size/S

#1840 libvirt-actuator: reproducible build system
  ci-operator/config/openshift/cluster-api-provider-libvirt/openshift-cluster-api-provider-libvirt-master.yaml
Labels: approved, lgtm, size/XS

#1855 Add new e2e tests to ci-operator configs
  ci-operator/config/openshift/cluster-dns-operator/openshift-cluster-dns-operator-master.yaml
  ci-operator/config/openshift/cluster-kube-apiserver-operator/openshift-cluster-kube-apiserver-operator-master.yaml
  ci-operator/config/openshift/cluster-kube-controller-manager-operator/openshift-cluster-kube-controller-manager-operator-master.yaml
  ci-operator/config/openshift/cluster-kube-scheduler-operator/openshift-cluster-kube-scheduler-operator-master.yaml
  ci-operator/config/openshift/cluster-openshift-apiserver-operator/openshift-cluster-openshift-apiserver-operator-master.yaml
  ci-operator/config/openshift/cluster-openshift-controller-manager-operator/openshift-cluster-openshift-controller-manager-operator-master.yaml
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-master.yaml
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-master.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-master.yaml
  ci-operator/config/openshift/service-ca-operator/openshift-service-ca-operator-master.yaml
  ci-operator/config/openshift/service-serving-cert-signer/openshift-service-serving-cert-signer-master.yaml
  ci-operator/config/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-master.yaml
Labels: approved, lgtm, size/M

#1809 Update docs on using ci-operator to build azure vm images and run e2e tests
  projects/azure/README.md
Labels: approved, lgtm, sig/azure, size/L, ¯\_(ツ)_/¯

#1834 move all azure vm image jobs from jenkins to ci-operator
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-periodics.yaml
  ci-operator/templates/openshift/openshift-azure/build-base-image.yaml
Labels: approved, lgtm, sig/azure, size/L

#1859 Copy e2e logs if they exist
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure-upgrade.yaml
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure.yaml
Labels: approved, lgtm, sig/azure, size/XS

#1548 don't build/publish docker-builder from origin
  ci-operator/config/openshift/builder/openshift-builder-master.yaml
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/jobs/openshift/builder/openshift-builder-master-postsubmits.yaml
  ci-operator/jobs/openshift/builder/openshift-builder-master-presubmits.yaml
Labels: approved, lgtm, size/S

#1861 Use cluster profile instead of target cloud
  ci-operator/config/containers/libpod/containers-libpod-master.yaml
  ci-operator/config/openshift/builder/openshift-builder-master.yaml
  ci-operator/config/openshift/cluster-dns-operator/openshift-cluster-dns-operator-master.yaml
  ci-operator/config/openshift/cluster-kube-apiserver-operator/openshift-cluster-kube-apiserver-operator-master.yaml
  ci-operator/config/openshift/cluster-kube-controller-manager-operator/openshift-cluster-kube-controller-manager-operator-master.yaml
  ci-operator/config/openshift/cluster-kube-scheduler-operator/openshift-cluster-kube-scheduler-operator-master.yaml
  ci-operator/config/openshift/cluster-openshift-apiserver-operator/openshift-cluster-openshift-apiserver-operator-master.yaml
  ci-operator/config/openshift/cluster-openshift-controller-manager-operator/openshift-cluster-openshift-controller-manager-operator-master.yaml
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-master.yaml
  ci-operator/config/openshift/image-registry/openshift-image-registry-master.yaml
  ci-operator/config/openshift/image-registry/openshift-image-registry-release-3.11.yaml
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-master.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-master.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-master.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-3.11.yaml
  ci-operator/config/openshift/origin-web-console-server/openshift-origin-web-console-server-master.yaml
  ci-operator/config/openshift/origin-web-console-server/openshift-origin-web-console-server-release-3.11.yaml
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-3.10.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-3.11.yaml
  ci-operator/config/openshift/service-ca-operator/openshift-service-ca-operator-master.yaml
  ci-operator/config/openshift/service-serving-cert-signer/openshift-service-serving-cert-signer-master.yaml
  ci-operator/config/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-master.yaml
  ci-operator/config/tnozicka/openshift-acme/tnozicka-openshift-acme-master.yaml
Labels: approved, do-not-merge/hold, lgtm, size/L

#1863 Revert "use ruby-25 scl base image for fluentd"
  ci-operator/config/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-master.yaml
Labels: approved, lgtm, size/XS

#1865 Turn on branch protection for all repos
  cluster/ci/config/prow/config.yaml
Labels: approved, size/L

#1868 Re-add tag specification for Hive.
  ci-operator/config/openshift/hive/openshift-hive-master.yaml
  ci-operator/jobs/openshift/hive/openshift-hive-master-postsubmits.yaml
Labels: approved, lgtm, size/XS

#1869 Move the operator framework repo
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/S

#1870 Add a branchprotector build and periodic
  ci-operator/jobs/infra-periodics.yaml
  cluster/ci/config/prow/openshift/build/branchprotector.yaml
Labels: approved, lgtm, size/M

#1871 osa - add logbridge promotion
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-master.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
  projects/azure/image-mirror/image-mirror.yaml
Labels: approved, lgtm, sig/azure, size/S

#1867 disable self approval for cloud team repos
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#1874 Stop requiring branches to be up to date
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/S

#1876 Reorder approve configuration
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#1875 rollback osa logbridge
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/S

#1877 Use promotion instead of tag_specification for Hive.
  ci-operator/config/openshift/hive/openshift-hive-master.yaml
Labels: approved, lgtm, size/XS

#1883 remove unnecessary gcp-crio job for builder repo
  ci-operator/config/openshift/builder/openshift-builder-master.yaml
  ci-operator/jobs/openshift/builder/openshift-builder-master-presubmits.yaml
Labels: approved, lgtm, size/M

#1176 Jenkins e2e postop
  Makefile
  ci-operator/jobs/openshift/jenkins/openshift-jenkins-master-presubmits.yaml
  ci-operator/jobs/openshift/jenkins/openshift-jenkins-openshift-3.10-presubmits.yaml
  ci-operator/jobs/openshift/jenkins/openshift-jenkins-openshift-3.11-presubmits.yaml
  ci-operator/templates/cluster-launch-e2e-openshift-jenkins.yaml
Labels: approved, lgtm, size/M

#1885 ci-operator/heketi: add flag variables to make invocation
  ci-operator/config/heketi/heketi/heketi-heketi-master.yaml
Labels: approved, lgtm, size/XS

#1884 update logging isnames
  ci-operator/config/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-master.yaml
Labels: approved, lgtm, size/XS

#1887 new repo - cluster-api-actuator-pkg
  ci-operator/config/openshift/cluster-api-actuator-pkg/OWNERS
  ci-operator/config/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-master.yaml
  ci-operator/jobs/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#1888 Fix configuration issues for branch protection
  ci-operator/jobs/openshift/ci-ns-ttl-controller/openshift-ci-ns-ttl-controller-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-3.10-presubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-3.6-presubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-3.7-presubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-3.9-presubmits.yaml
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/M

#1889 cluster-api-provider-aws: Update tooling
  ci-operator/config/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-master.yaml
Labels: approved, lgtm, size/XS

#1890 make aws-all job non-blocking
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#1891 skip reporting on aws-all
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#1893 update plugins.yaml for jenkins cm name change
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#1897 machine-api-operator: change test name
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#1898 Fix branchprotector arg
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm, size/XS

#1899 Update resource to make ci/prow/images test job
  ci-operator/config/openshift/origin/openshift-origin-release-3.10.yaml
Labels: approved, lgtm, size/XS

#1901 Replace `from` with `container` in tests
  ci-operator/config/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-master.yaml
Labels: approved, lgtm, size/S

#1896 Start gathering openshift-azure unit coverage
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-master.yaml
Labels: approved, lgtm, sig/azure, size/XS

#1907 add bins to output olm image
  ci-operator/config/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-master.yaml
Labels: approved, lgtm, size/XS

#1908 Protect all branches of openshift-ansible
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/S

#1909 remove unnessacary fields.
  ci-operator/config/openshift/cluster-kube-apiserver-operator/openshift-cluster-kube-apiserver-operator-master.yaml
  ci-operator/config/openshift/cluster-kube-controller-manager-operator/openshift-cluster-kube-controller-manager-operator-master.yaml
  ci-operator/config/openshift/cluster-openshift-apiserver-operator/openshift-cluster-openshift-apiserver-operator-master.yaml
  ci-operator/config/openshift/cluster-openshift-controller-manager-operator/openshift-cluster-openshift-controller-manager-operator-master.yaml
  ci-operator/config/tnozicka/openshift-acme/tnozicka-openshift-acme-master.yaml
Labels: approved, lgtm, size/M

#1872 Cleanup azure make target
  Makefile
Labels: approved, lgtm, size/XS

#1894 openshift-ansible 3.11: don't run jenkins install for all PRs
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-3.11-presubmits.yaml
Labels: approved, lgtm, size/XS

#1892 disable branch protection on openshift/library
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/XS

#1916 openshift-ansible: correct rpms location
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-master.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-3.10.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-3.11.yaml
Labels: approved, lgtm, size/XS

#1917 openshift-ansible: make sure RPM dir exists before moving rpms there
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-master.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-3.10.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-3.11.yaml
Labels: approved, lgtm, size/XS

#1915 Update mirrors
  cluster/ci/config/mirroring/origin_v3_10
  cluster/ci/config/mirroring/origin_v3_11
  cluster/ci/config/mirroring/origin_v3_11_quay
  cluster/ci/config/mirroring/origin_v4_0
  cluster/ci/config/mirroring/origin_v4_0_quay
Labels: approved, lgtm, size/M

#1920 fix extended test presubmit jobs for 3.11
  ci-operator/jobs/openshift/origin/openshift-origin-release-3.11-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/XS

#1918 openshift-ansible: add new tests to master using prowgen
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-master.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-master-presubmits.yaml
Labels: approved, lgtm, size/L

#1922 libvirt-actuator: add optional e2e job
  ci-operator/jobs/openshift/cluster-api-provider-libvirt/openshift-cluster-api-provider-libvirt-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#1923 openshift-ansible: generate more jobs for master and release-3.11
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-master.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-3.11.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-3.11-presubmits.yaml
Labels: approved, lgtm, size/L

#1926 Fix the pylint presubmit for openshift/release
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#1927 Disable bp for admins in azure-related repos
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/XS

#1930 Add more repos to the PR gate for e2e-aws
  ci-operator/config/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-master.yaml
  ci-operator/config/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-master.yaml
  ci-operator/config/openshift/cluster-ingress-operator/openshift-cluster-ingress-operator-master.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-master.yaml
  ci-operator/config/openshift/cluster-samples-operator/openshift-cluster-samples-operator-master.yaml
  ci-operator/config/openshift/console-operator/openshift-console-operator-master.yaml
  ci-operator/config/openshift/coredns/openshift-coredns-master.yaml
  ci-operator/jobs/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-ingress-operator/openshift-cluster-ingress-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-samples-operator/openshift-cluster-samples-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/console-operator/openshift-console-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/coredns/openshift-coredns-master-presubmits.yaml
Labels: approved, lgtm, size/L

#1931 Azure: add support for defining the logbridge image instead of :latest
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure-conformance.yaml
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure-upgrade.yaml
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure.yaml
Labels: approved, lgtm, sig/azure, size/S

#1932 register master-operator-sdk repo to prow
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#1902 mimic builders setting of env vars in ci-operator cfg
  ci-operator/jobs/openshift/jenkins/openshift-jenkins-master-presubmits.yaml
  ci-operator/jobs/openshift/jenkins/openshift-jenkins-openshift-3.10-presubmits.yaml
  ci-operator/jobs/openshift/jenkins/openshift-jenkins-openshift-3.11-presubmits.yaml
Labels: approved, lgtm, size/M

#1933 disable enforce admin for logging 3.6 and 3.7
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/XS

#1929 Openshift-ansible: don't run gluster and logging tests for all PRs
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-3.11-presubmits.yaml
Labels: approved, lgtm, size/XS

#1942 gcp-logging: update logging vars
  cluster/test-deploy/gcp-logging/vars-origin.yaml
  cluster/test-deploy/gcp-logging/vars.yaml
Labels: approved, lgtm, size/M

#1944 Mirror 3.10 metrics images
  cluster/ci/config/mirroring/origin_v3_10
Labels: approved, lgtm, size/XS

#1946 Make crio on 3.11 optional until we get more green
  ci-operator/jobs/openshift/origin/openshift-origin-release-3.11-presubmits.yaml
Labels: approved, lgtm, size/XS

#1943 unprotect jenkins plugin repos
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/S

#1741 Added CI Job for Origin
  ci-operator/jobs/openshift/origin/openshift-origin-periodics.yaml
Labels: approved, lgtm, size/XS

#1936 Add csi-operator to CI/CD
  ci-operator/config/openshift/csi-operator/openshift-csi-operator-master.yaml
  ci-operator/jobs/openshift/csi-operator/openshift-csi-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/csi-operator/openshift-csi-operator-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#1947 Show all container log in failed azure e2es
  ci-operator/templates/openshift/openshift-azure/build-base-image.yaml
  ci-operator/templates/openshift/openshift-azure/build-node-image.yaml
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure-conformance.yaml
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure-upgrade.yaml
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure.yaml
Labels: approved, lgtm, sig/azure, size/XS

#1949 disable aws-e2e job for aws-actuator feature branch
  ci-operator/config/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-crd.yaml
  ci-operator/jobs/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-crd-presubmits.yaml
Labels: approved, lgtm, size/M

#1950 Enable a DNS e2e test
  ci-operator/config/openshift/cluster-dns-operator/openshift-cluster-dns-operator-master.yaml
  ci-operator/config/openshift/coredns/openshift-coredns-master.yaml
  ci-operator/jobs/openshift/cluster-dns-operator/openshift-cluster-dns-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/coredns/openshift-coredns-master-presubmits.yaml
Labels: approved, lgtm, size/S

#1952 Update router namespace check for daemonset started by the cluster ingress operator
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
Labels: approved, size/XS

#1948 osa: add daily job that tests production deployments
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-periodics.yaml
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure.yaml
Labels: approved, lgtm, sig/azure, size/M

#1959 Show container output for e2e, upgrade and openshift-ansible templates
  ci-operator/templates/cluster-launch-e2e-openshift-ansible.yaml
  ci-operator/templates/cluster-launch-e2e-upgrade.yaml
  ci-operator/templates/cluster-launch-e2e.yaml
Labels: approved, lgtm, size/XS

#1951 Add openshift-tuned to CI/CD
  ci-operator/config/openshift/openshift-tuned/openshift-openshift-tuned-master.yaml
  ci-operator/jobs/openshift/openshift-tuned/openshift-openshift-tuned-master-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-tuned/openshift-openshift-tuned-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#1953 Revert registration of deleted repo and register library-go
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS, ¯\_(ツ)_/¯

#1961 Fix azure e2e template and prod rp job
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-periodics.yaml
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure.yaml
Labels: approved, lgtm, sig/azure, size/XS

#1963 Fix ci-operator flags in azure periodic pod spec
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-periodics.yaml
Labels: approved, lgtm, sig/azure, size/XS

#1964 Remove redundant branchprotector config
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/XS

#1960 Add cluster-node-tuning-operator to CI/CD
  ci-operator/config/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-master.yaml
  ci-operator/jobs/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#1965 Add openshift/csi-* repos
  ci-operator/config/openshift/csi-driver-registrar/openshift-csi-driver-registrar-master.yaml
  ci-operator/config/openshift/csi-external-attacher/openshift-csi-external-attacher-master.yaml
  ci-operator/config/openshift/csi-external-provisioner/openshift-csi-external-provisioner-master.yaml
  ci-operator/config/openshift/csi-livenessprobe/openshift-csi-livenessprobe-master.yaml
  ci-operator/jobs/openshift/csi-driver-registrar/openshift-csi-driver-registrar-master-postsubmits.yaml
  ci-operator/jobs/openshift/csi-driver-registrar/openshift-csi-driver-registrar-master-presubmits.yaml
  ci-operator/jobs/openshift/csi-external-attacher/openshift-csi-external-attacher-master-postsubmits.yaml
  ci-operator/jobs/openshift/csi-external-attacher/openshift-csi-external-attacher-master-presubmits.yaml
  ci-operator/jobs/openshift/csi-external-provisioner/openshift-csi-external-provisioner-master-postsubmits.yaml
  ci-operator/jobs/openshift/csi-external-provisioner/openshift-csi-external-provisioner-master-presubmits.yaml
  ci-operator/jobs/openshift/csi-livenessprobe/openshift-csi-livenessprobe-master-postsubmits.yaml
  ci-operator/jobs/openshift/csi-livenessprobe/openshift-csi-livenessprobe-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XL

#1966 openshift-ansible: disable gcp-major-upgrade for master branch
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-master.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-master-presubmits.yaml
Labels: approved, lgtm, size/M

#1972 Remove ci-operator azure image config
  projects/azure/base-images/ci-operator.yaml
Labels: approved, lgtm, sig/azure, size/M

#1973 Do not try to apply nonexistent build.yaml
  Makefile
Labels: approved, lgtm, size/XS

#1974 Build `python-validation` image for openshift/release presubmits
  Makefile
  projects/origin-release/python-validation/python-validation.yaml
Labels: approved, lgtm, size/M

#1970 add pod-checkpointer-operator repo config and jobs
  ci-operator/config/openshift/pod-checkpointer-operator/OWNERS
  ci-operator/config/openshift/pod-checkpointer-operator/openshift-pod-checkpointer-operator-master.yaml
  ci-operator/jobs/openshift/pod-checkpointer-operator/openshift-pod-checkpointer-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/pod-checkpointer-operator/openshift-pod-checkpointer-operator-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#1977 Fix azure test base image
  projects/azure/base-images/test-base.yaml
  projects/azure/base-images/test-base/entrypoint
  projects/azure/base-images/test-base/root/usr/local/bin/user_setup
Labels: approved, lgtm, sig/azure, size/M

#1979 Add periodics for azure images
  ci-operator/jobs/openshift/azure-misc/openshift-azure-misc-periodics.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-periodics.yaml
Labels: approved, lgtm, sig/azure, size/M
