Repository openshift/release, pull requests merged in 2018-02, with the labels that each got.

#595 Extended issue closer jobs interval
  cluster/ci/config/prow/config.yaml
Labels: size/XS

#564 projects/prometheus: updates for prometheus 2.1.0 and alertmanager 0.…
  projects/prometheus/node_exporter.yaml
  projects/prometheus/prometheus.yaml
Labels: size/S

#598 [WIP] Move ose tests to sjb
  cluster/ci/config/prow/config.yaml
Labels: do-not-merge/work-in-progress, size/M

#600 Don't require system-containers until atomic-1.22.1 lands
  cluster/ci/config/submit-queue/submit_queue_openshift_ansible_config.yaml
Labels: size/XS

#601 Update Jenkins prow config to use new status id
  cluster/ci/config/prow/config.yaml
Labels: size/S

#602 Revert "Update Jenkins prow config to use new status id"
  cluster/ci/config/prow/config.yaml
Labels: size/S

#603 Revert "Revert "Update Jenkins prow config to use new status id""
  cluster/ci/config/prow/config.yaml
Labels: size/S

#604 Unwind build manifests
  Makefile
  cluster/ci/config/prow/openshift/build/deck.yaml
  cluster/ci/config/prow/openshift/build/hook.yaml
  cluster/ci/config/prow/openshift/build/horologium.yaml
  cluster/ci/config/prow/openshift/build/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/build/plank.yaml
  cluster/ci/config/prow/openshift/build/sinker.yaml
  cluster/ci/config/prow/openshift/build/splice.yaml
  cluster/ci/config/prow/openshift/build/tide.yaml
Labels: size/XL

#608 Use gnu tar when available on Mac OS, or error if unavailable
  cluster/bin/ansible.sh
Labels: size/S

#610 Add tot statefulset
  Makefile
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/tot.yaml
Labels: size/M

#607 Rename config-updater plugin config
  cluster/ci/config/prow/openshift/config-updater/build.yaml
  cluster/ci/config/prow/openshift/config-updater/config-ci-openshift-ansible.yaml
  cluster/ci/config/prow/openshift/config-updater/config-ci.yaml
  cluster/ci/config/prow/openshift/config-updater/config-origin-ci.yaml
  cluster/ci/config/prow/openshift/config-updater/deployment.yaml
  cluster/ci/config/prow/openshift/jenkins-config-updater/config-origin-ci.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: size/M

#612 Remove config updater wherever unused
  cluster/ci/config/prow/openshift/config-updater/build.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: size/S

#618 update jobs for logging releases 3.6 and 3.7
  cluster/ci/config/prow/config.yaml
Labels: size/M

#620 Add release-3.9 branches to prow
  cluster/ci/config/prow/config.yaml
Labels: size/S
