Repository openshift/release, pull requests merged in 2018-04, with the labels that each got.

#742 Allow REF to target which branch and ansible image to use
  cluster/bin/ansible.sh
  cluster/test-deploy/Makefile
Labels: size/S

#745 Add a 39 conformance job and an a test upgrade target for the makefile
  cluster/ci/config/prow/config.yaml
  cluster/test-deploy/Makefile
Labels: size/S

#746 Logging PR is currently too flaky
  cluster/ci/config/prow/config.yaml
Labels: size/XS

#657 Add RPM based CRIO jobs to submit queue
  cluster/ci/config/prow/config.yaml
Labels: size/S

#739 Bring autoscaler YAML in sync with the deployed objects
  Makefile
  projects/kubernetes/autoscaler.yaml
Labels: size/S

#737 remove test_branch_online_registration from prow/config.yaml
  cluster/ci/config/prow/config.yaml
Labels: size/XS

#671 Update CI cluster roles
  cluster/ci/config/roles.yaml
Labels: size/S

#749 autoscaler: update image name, golang version, and maintainer
  projects/kubernetes/autoscaler.yaml
Labels: size/S

#750 add descheduler image build
  Makefile
  projects/kubernetes/descheduler.yaml
Labels: size/M

#751 add node-problem-detector image build
  Makefile
  projects/kubernetes/node-problem-detector.yaml
Labels: size/M

#730 Add publishing-bot ssd storage class
  Makefile
  projects/publishing-bot/storage-class.yaml
Labels: size/S

#740 Add service-catalog to prow and submit queue
  cluster/ci/config/prow/config.yaml
Labels: size/S

#754 Allow image change triggers to work as intended
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/config-updater/deployment.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  cluster/ci/config/prow/openshift/tracer.yaml
Labels: size/M

#761 Exclude merging to openshift/origin#master
  cluster/ci/config/prow/config.yaml
Labels: size/S

#763 Re-enable merges to master
  cluster/ci/config/prow/config.yaml
Labels: size/XS

#765 add cluster-capacity image build
  projects/kubernetes/cluster-capacity.yaml
Labels: size/M

#766 add cluster-capacity to Makefile
  Makefile
Labels: size/XS

#767 Add new static HA configuration for GCP without bootstrapping
  cluster/test-deploy/gcp-dev-ha-static/.gitignore
  cluster/test-deploy/gcp-dev-ha-static/.type
  cluster/test-deploy/gcp-dev-ha-static/vars-origin.yaml
  cluster/test-deploy/gcp-dev-ha-static/vars.yaml
  cluster/test-deploy/gcp-dev/bootstrap-script.sh
  cluster/test-deploy/gcp-dev/vars.yaml
  cluster/test-deploy/gcp-ha-static/.gitignore
  cluster/test-deploy/gcp-ha-static/.type
  cluster/test-deploy/gcp-ha-static/vars-origin.yaml
  cluster/test-deploy/gcp-ha-static/vars.yaml
  cluster/test-deploy/gcp-ha/bootstrap-script.sh
  cluster/test-deploy/gcp-ha/vars.yaml
  cluster/test-deploy/gcp/bootstrap-script.sh
  cluster/test-deploy/gcp/vars.yaml
Labels: size/L

#768 Add an ansible PR job for installing and upgrading a GCP cluster
  cluster/ci/config/prow/config.yaml
Labels: size/S

#769 Update prometheus ci rules; remove prom targets
  Makefile
  projects/prometheus/prometheus.rules.yaml
Labels: size/M

#770 system-containers openshift-ansible branched
  cluster/ci/config/prow/config.yaml
Labels: size/M

#771 Point tide statuses at the PR overview page
  cluster/ci/config/prow/config.yaml
Labels: size/XS

#772 run extended builds when start-build is changed
  cluster/ci/config/prow/config.yaml
Labels: size/XS

#773 Add openshift/descheduler CI
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: size/S

#778 Add Azure periodic jobs in prow
  cluster/ci/config/prow/config.yaml
Labels: do-not-merge/hold, size/S

#779 add new kube projects to updater config
  cluster/ci/config/prow/openshift/config-updater/config-ci.yaml
Labels: size/XS

#780 Prepare for multi-stage builds
  projects/origin-release/Makefile
  projects/origin-release/base/Dockerfile
  projects/origin-release/fake-rpm.sh
  projects/origin-release/golang-1.10/Dockerfile
  projects/origin-release/golang-1.10/cbs-paas7-openshift-multiarch-el7-build.repo
  projects/origin-release/golang-1.10/golang-v1.10.0-1.el7.centos.noarch.rpm
  projects/origin-release/golang-1.10/golang.spec
  projects/origin-release/golang-1.8/Dockerfile
  projects/origin-release/golang-1.8/cbs-paas7-openshift-multiarch-el7-build.repo
  projects/origin-release/golang-1.9/Dockerfile
  projects/origin-release/golang-1.9/cbs-paas7-openshift-multiarch-el7-build.repo
  projects/origin-release/golang-1.9/golang-v1.9.0-1.el7.centos.noarch.rpm
  projects/origin-release/golang-1.9/golang.spec
  projects/origin-release/pipeline.yaml
  projects/test-bases/common/base.yaml
  projects/test-bases/common/golang-1.10.yaml
  projects/test-bases/common/golang-1.10/Dockerfile
  projects/test-bases/common/golang-1.8.yaml
  projects/test-bases/common/golang-1.9.yaml
  projects/test-bases/common/golang-1.9/Dockerfile
  projects/test-bases/openshift/image-registry.yaml
  projects/test-bases/openshift/origin.yaml
Labels: size/XL

#777 Add Azure PR/branch jobs in prow
  cluster/ci/config/prow/config.yaml
Labels: size/M

#781 Drop acs-engine testing
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: size/M

#782 Add 3.9 test image for acs-engine
  Makefile
  projects/acs-engine/Dockerfile
  projects/acs-engine/run-tests.sh
  projects/acs-engine/test-image-build.yaml
  projects/acs-engine/test-image-v3.9/Dockerfile
Labels: size/M

#784 Add stable image streams for origin
  Makefile
  cluster/ci/jobs/image-pruner.yaml
  projects/origin-stable/stable-3.10.yaml
  projects/origin-stable/stable-3.11.yaml
  projects/origin-stable/stable-3.9.yaml
Labels: size/L

#785 Have PRs of more openshift repos merged on lgtm label
  cluster/ci/config/prow/config.yaml
Labels: size/XS

#786 Make gcp-upgrade run on all master openshift-ansible PRs
  cluster/ci/config/prow/config.yaml
Labels: size/XS

#787 Add monitoring components
  cluster/ci/config/prow/config.yaml
Labels: size/XS

#789 Disable install_update because it hasn't worked forever
  cluster/ci/config/prow/config.yaml
Labels: size/S

#791 merge PRs on lgtm for autoscaler project
  cluster/ci/config/prow/config.yaml
Labels: size/XS

#790 catalog: use separate sjb configs for different branches
  cluster/ci/config/prow/config.yaml
Labels: size/S

#792 catalog: add openshift/service-catalog job
  cluster/ci/config/prow/config.yaml
Labels: size/S

#794 catalog: add additional directory path for master
  cluster/ci/config/prow/config.yaml
Labels: size/XS

#793 Azure periodic jobs for rhel and centos image builds
  cluster/ci/config/prow/config.yaml
Labels: size/S

#795 Track the base origin image as well
  projects/origin-stable/stable-3.10.yaml
  projects/origin-stable/stable-3.11.yaml
  projects/origin-stable/stable-3.9.yaml
Labels: size/S

#796 Add kata-containers Jenkins integration for CRI-O
  Makefile
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
Labels: size/M

#797 Fix kata-jenkins-operator SA name
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
Labels: size/XS

#798 Add the ci-operator as a multi-stage build to OpenShift
  Makefile
  cluster/ci/config/prow/openshift/ci-operator/build.yaml
Labels: size/M

#800 Use empty image name in kata operator
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
Labels: size/XS

#803 Add a decorated job for ci-operator unit tests
  cluster/ci/config/prow/config.yaml
Labels: size/M

#801 Add cluster-monitoring-operator
  cluster/ci/config/prow/config.yaml
Labels: lgtm, size/XS

#809 Point plaank logs to Gubernator
  cluster/ci/config/prow/config.yaml
Labels: size/XS

#810 Explicitly set GOPATH for ci-operator test
  cluster/ci/config/prow/config.yaml
Labels: size/XS

#811 Fix ci-operator GOPATH setting
  cluster/ci/config/prow/config.yaml
Labels: size/XS

#812 Turn on approvers automation for o-a repo
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: size/XS

#805 Remove the default 'ci-' prefix, it is redundant for some cases
  cluster/test-deploy/gcp-dev-ha-static/vars-origin.yaml
  cluster/test-deploy/gcp-dev-ha/vars-origin.yaml
  cluster/test-deploy/gcp-dev/vars-origin.yaml
  cluster/test-deploy/gcp-ha-static/vars-origin.yaml
  cluster/test-deploy/gcp-ha/vars-origin.yaml
  cluster/test-deploy/gcp/vars-origin.yaml
Labels: size/S

#816 remove azure jobs
  cluster/ci/config/prow/config.yaml
Labels: size/M

#817 make image_ecosytem unblocking for now
  cluster/ci/config/prow/config.yaml
Labels: size/XS

#819 Prepare for ci-operator jobs with config and web-console image
  Makefile
  cluster/ci/config/prow/jobs/cluster-launch-e2e.yaml
  projects/origin-stable/stable-3.10.yaml
  projects/origin-stable/stable-3.11.yaml
  projects/origin-stable/stable-3.9.yaml
Labels: size/L
