Repository openshift/release, pull requests merged in 2018-03, with the labels that each got.

#623 Decomission hosted Jenkins operator
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
Labels: size/M

#624 Expose ci.dev logs in private instance
  cluster/ci/config/prow/config.yaml
Labels: size/XS

#625 tot builds from our fork now
  cluster/ci/config/prow/openshift/build/tot.yaml
Labels: size/XS

#622 Disable containerized builds in master
  cluster/ci/config/prow/config.yaml
Labels: size/XS

#627 Revert config-updater image to origin-release
  cluster/ci/config/prow/openshift/config-updater/build.yaml
Labels: size/XS

#628 Test upstream tot PR
  cluster/ci/config/prow/openshift/build/tot.yaml
Labels: size/XS

#629 Fallback to old config-updater Dockerfile
  cluster/ci/config/prow/openshift/config-updater/build.yaml
Labels: size/XS

#632 Disable CRIO and system container jobs in 3.10 temporarily
  cluster/ci/config/prow/config.yaml
Labels: size/S

#621 Adding the es5.x branch for aggregated-logging repo tests
  cluster/ci/config/prow/config.yaml
Labels: size/XS

#634 update logging jobs for 3.9
  cluster/ci/config/prow/config.yaml
Labels: size/M

#637 Adding es5.x branch for origin logging json-file test
  cluster/ci/config/prow/config.yaml
Labels: size/XS

#636 ci for online-registration
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: size/S

#635 internal operator already runs the updated code
  cluster/ci/config/prow/config.yaml
Labels: size/XS

#630 Bring ose plugins on par with origin
  cluster/ci/config/prow/plugins.yaml
Labels: size/XS

#638 Temporarily take networking_minimal out of required
  cluster/ci/config/submit-queue/submit_queue_config.yaml
Labels: size/XS

#642 Update traceprow to use new tracer backend endpoint
  tools/traceprow/main.go
Labels: size/XS

#643 Add acs-engine minimal test job
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
  projects/acs-engine/Dockerfile
  projects/acs-engine/build.yaml
  projects/acs-engine/run-tests.sh
Labels: size/M

#647 acs-engine job needs to run at all times
  cluster/ci/config/prow/config.yaml
Labels: size/XS

#649 Goodies for acs-engine
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: size/S

#648 Add targets for applying roles and desired namespace
  Makefile
Labels: size/S

#652 Tracer builds need to mount /static
  cluster/ci/config/prow/openshift/build/tracer.yaml
Labels: size/XS

#654 needs-rebase plugin builds from a new location
  cluster/ci/config/prow/openshift/build/needs_rebase.yaml
Labels: size/XS

#655 Enable needs-rebase for acs-engine
  cluster/ci/config/prow/plugins.yaml
Labels: size/XS

#656 Fetch origin/master before checking out PR branch
  projects/acs-engine/run-tests.sh
Labels: size/XS

#661 Use Prow to trigger and merge for jenkins repos
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: lgtm, size/L

#662 Use Prow and Tide on the WildFly repo
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: size/S

#664 Add logging postsubmits for OpenShift Ansible
  cluster/ci/config/prow/config.yaml
Labels: size/S

#665 Run origin extended non-conformance tests daily
  cluster/ci/config/prow/config.yaml
Labels: size/M

#666 Add webconsole tests to origin postsubmits
  cluster/ci/config/prow/config.yaml
Labels: size/M

#669 Run different jobs for openshift-ansible install based on the branch
  cluster/ci/config/prow/config.yaml
Labels: size/M

#674 Fix a typo in release-specific install jobs for openshift-ansible
  cluster/ci/config/prow/config.yaml
Labels: size/XS

#675 Move push jobs to periodic
  cluster/ci/config/prow/config.yaml
Labels: size/M

#676 Drop lgtm-after-commit munger
  cluster/ci/config/submit-queue/submit_queue_config.yaml
  cluster/ci/config/submit-queue/submit_queue_openshift_ansible_config.yaml
  cluster/ci/config/submit-queue/submit_queue_origin_aggregated_logging_config.yaml
  cluster/ci/config/submit-queue/submit_queue_origin_web_console_config.yaml
Labels: size/XS

#678 Revert "Merge pull request #675 from stevekuznetsov/skuznets/push-ima…
  cluster/ci/config/prow/config.yaml
Labels: size/M

#679 add online-console-extensions to prow/plugin.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: size/XS

#680 Make GCP temporarily non blocking
  cluster/ci/config/submit-queue/submit_queue_config.yaml
  cluster/ci/config/submit-queue/submit_queue_openshift_ansible_config.yaml
Labels: size/XS

#681 Re-enable crio and system-container ansible jobs for PRs
  cluster/ci/config/prow/config.yaml
Labels: size/S

#683 Prow meet descheduler, descheduler meet Prow
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: size/S

#685 Specify which Jenkins master to use for descheduler jobs
  cluster/ci/config/prow/config.yaml
Labels: size/XS

#686 rename logging jobs
  cluster/ci/config/prow/config.yaml
Labels: size/S

#609 link up ovn-kubernetes jobs
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: size/S

#688 Revert "link up ovn-kubernetes jobs"
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: size/S

#691 Add push origin release and PR jobs for specific origin branches
  cluster/ci/config/prow/config.yaml
Labels: size/M

#692 Fix web console repository jobs
  cluster/ci/config/prow/config.yaml
Labels: size/M

#690 link up ovn-kubernetes jobs : redone
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: size/S

#687 Drop extended_networking_minimal
  cluster/ci/config/prow/config.yaml
Labels: size/S

#682 Move crio and kubernetes jobs from rosie
  cluster/ci/config/prow/config.yaml
Labels: size/S

#694 Make GCP blocking again
  cluster/ci/config/submit-queue/submit_queue_config.yaml
  cluster/ci/config/submit-queue/submit_queue_openshift_ansible_config.yaml
Labels: size/XS

#697 Move logging and metrics push jobs as postsubmits
  cluster/ci/config/prow/config.yaml
Labels: size/S

#698 Move kubernetes metrics and cluster operator jobs
  cluster/ci/config/prow/config.yaml
Labels: size/S

#701 Add postsubmits for OpenShift Ansible jobs
  cluster/ci/config/prow/config.yaml
Labels: size/M

#702 Add branch jobs for gce ansible
  cluster/ci/config/prow/config.yaml
Labels: size/S

#703 Publish install release branch jobs
  cluster/ci/config/prow/config.yaml
Labels: size/M

#706 Add the OAuth bits for Prow PR dashboard
  Makefile
  cluster/ci/config/prow/openshift/deck.yaml
Labels: size/S

#708 Remove garish background color override for deck
  cluster/ci/config/prow/config.yaml
Labels: size/XS

#713 Compare Go versions numerically
  tools/hack/golang/hack/lib/build/binaries.sh
Labels: size/XS

#594 Update latest images going forward
  projects/oauth-proxy/pipeline.yaml
Labels: lgtm, size/XS

#714 Update golang and oauth-proxy versions in prow manifests
  cluster/ci/config/prow/openshift/build/cherrypick.yaml
  cluster/ci/config/prow/openshift/build/deck.yaml
  cluster/ci/config/prow/openshift/build/hook.yaml
  cluster/ci/config/prow/openshift/build/horologium.yaml
  cluster/ci/config/prow/openshift/build/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/build/needs_rebase.yaml
  cluster/ci/config/prow/openshift/build/plank.yaml
  cluster/ci/config/prow/openshift/build/refresh.yaml
  cluster/ci/config/prow/openshift/build/sinker.yaml
  cluster/ci/config/prow/openshift/build/splice.yaml
  cluster/ci/config/prow/openshift/build/tide.yaml
  cluster/ci/config/prow/openshift/build/tot.yaml
  cluster/ci/config/prow/openshift/build/tracer.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/tracer.yaml
Labels: size/M

#715 Automate creation of acs-engine job
  Makefile
Labels: size/XS

#717 Update golang versions for some builds
  Makefile
  projects/prometheus/alert-buffer.yaml
  projects/prometheus/node_exporter.yaml
  projects/prometheus/prometheus.yaml
  projects/prometheus/test/build.yaml
Labels: size/S

#718 gpgchecking doesn't work on dockertested
  cluster/ci/config/mirroring/origin_v3_10
  cluster/ci/config/mirroring/origin_v3_9
  cluster/test-deploy/api.ci/vars.yaml
  cluster/test-deploy/gcp-ha/vars-origin.yaml
  cluster/test-deploy/gcp/vars-origin.yaml
Labels: size/M

#719 Stop posting status from containerized job
  cluster/ci/config/prow/config.yaml
Labels: size/XS

#722 Logging and web-console repos do not use approvals
  cluster/ci/config/prow/config.yaml
Labels: size/XS

#723 o-a and the k8s metric server don't use approvals too
  cluster/ci/config/prow/config.yaml
Labels: size/XS

#726 Update GCSWeb build and route for upstream changes
  projects/gcsweb/pipeline.yaml
Labels: size/XS

#728 rename kubernetes-autoscaler to origin-cluster-autoscaler
  projects/kubernetes/autoscaler.yaml
Labels: size/S

#729 narrow the regex for running image ecosystem
  cluster/ci/config/prow/config.yaml
Labels: size/XS

#731 Disable reporting service_catalog status in Github
  cluster/ci/config/prow/config.yaml
Labels: size/XS

#735 Remove submit-queue/splice config
  Makefile
  cluster/ci/config/prow/openshift/build/splice.yaml
  cluster/ci/config/prow/openshift/config-updater/config-ci.yaml
  cluster/ci/config/prow/openshift/splice.yaml
  cluster/ci/config/prow/openshift/splice_rbac.yaml
  cluster/ci/config/submit-queue/README.md
  cluster/ci/config/submit-queue/submit_queue.yaml
  cluster/ci/config/submit-queue/submit_queue_config.yaml
  cluster/ci/config/submit-queue/submit_queue_openshift_ansible.yaml
  cluster/ci/config/submit-queue/submit_queue_openshift_ansible_config.yaml
  cluster/ci/config/submit-queue/submit_queue_origin_aggregated_logging.yaml
  cluster/ci/config/submit-queue/submit_queue_origin_aggregated_logging_config.yaml
  cluster/ci/config/submit-queue/submit_queue_origin_web_console.yaml
  cluster/ci/config/submit-queue/submit_queue_origin_web_console_config.yaml
Labels: size/XXL

#736 Drive deployments from merges
  cluster/ci/config/prow/openshift/config-updater/config-ci.yaml
Labels: size/S

#734 Label tide under prow
  cluster/ci/config/prow/openshift/tide.yaml
Labels: size/XS

#738 Turn on automatic update for autoscaler builds
  cluster/ci/config/prow/openshift/config-updater/config-ci.yaml
Labels: size/XS

#741 Disable extended_conformance_install_crio status posting
  cluster/ci/config/prow/config.yaml
Labels: size/XS
