Repository openshift/release, pull requests merged in 2018-09, with the labels that each got.

#1345 Sync test-flake label across openshift
  cluster/ci/config/prow/labels.yaml
Labels: size/XS

#1346 Remove deprecated merge queue labels
  cluster/ci/config/prow/labels.yaml
Labels: approved, lgtm, size/S

#1348 Everything that is part of origin should use go 1.10 to build
  ci-operator/config/kubernetes/autoscaler/master.json
  ci-operator/config/kubernetes/cluster-capacity/master.json
  ci-operator/config/kubernetes/coredns/master.json
  ci-operator/config/kubernetes/descheduler/master.json
  ci-operator/config/kubernetes/metrics-server/master.json
  ci-operator/config/openshift/openshift-ansible/master.json
  ci-operator/config/openshift/openshift-ansible/release-3.11.json
  ci-operator/config/openshift/origin-aggregated-logging/master.json
  ci-operator/config/openshift/origin-aggregated-logging/release-3.11.json
  ci-operator/config/openshift/origin-metrics/master.json
  ci-operator/config/openshift/origin-metrics/release-3.11.json
  ci-operator/config/openshift/origin-web-console-server/master.json
  ci-operator/config/openshift/origin-web-console-server/release-3.11.json
Labels: approved, lgtm, size/S

#1349 Update rules when extended builds tests are triggered
  ci-operator/jobs/openshift/origin/openshift-origin-presubmits-release-3.11.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-presubmits.yaml
Labels: approved, lgtm, size/XS

#1344 ci-operator/templates/cluster-launch-installer-e2e.yaml: modern RHCOS
  ci-operator/templates/cluster-launch-installer-e2e.yaml
Labels: approved, lgtm, size/XS

#1340 Build images for components of machine-config-operator
  ci-operator/config/openshift/machine-config-operator/master.json
Labels: approved, lgtm, size/S

#1351 openshift-installer-presubmits: Conformance serial focus for e2e-aws-all
  ci-operator/jobs/openshift/installer/openshift-installer-presubmits.yaml
Labels: approved, lgtm, size/XS

#1353 Generate URLs using library, not template
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/XS

#1354 openshift-installer-presubmits: Normalize job names
  ci-operator/jobs/openshift/installer/openshift-installer-presubmits.yaml
Labels: approved, lgtm, size/S

#1359 Revert "Merge pull request #1358 from stevekuznetsov/skuznets/revert-…
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/XS

#1357 Fix PR history template for other repositories
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm, size/XS

#1298 Add jobs to test GCP cluster updates
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-presubmits.yaml
  ci-operator/templates/cluster-launch-e2e-upgrade.yaml
Labels: approved, lgtm, size/XL

#1360 Add a fast forward script for release branches
  ci-operator/jobs/openshift/azure-misc/openshift-azure-misc-postsubmits-release-3.11.yaml
  ci-operator/jobs/openshift/azure-misc/openshift-azure-misc-postsubmits.yaml
  hack/branch
  hack/lib/repos_with_job_labels.py
Labels: approved, lgtm, size/M

#1364 Add remaining ci-operator fork configs
  ci-operator/config/kubernetes/autoscaler/release-3.11.json
  ci-operator/config/kubernetes/cluster-capacity/release-3.11.json
  ci-operator/config/kubernetes/coredns/release-3.11.json
  ci-operator/config/kubernetes/descheduler/release-3.11.json
  ci-operator/config/kubernetes/metrics-server/release-3.11.json
  ci-operator/config/openshift/api/release-3.11.json
  ci-operator/config/openshift/configmap-reload/release-3.11.json
  ci-operator/config/openshift/kube-rbac-proxy/release-3.11.json
  ci-operator/config/openshift/kube-state-metrics/release-3.11.json
  ci-operator/config/openshift/prometheus-operator/release-3.11.json
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-postsubmits-release-3.11.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-postsubmits.yaml
Labels: approved, lgtm, size/L

#1365 Update release image
  projects/origin-release/golang-1.11/Dockerfile
  projects/origin-release/golang-1.9/Dockerfile
Labels: approved, lgtm, size/XS

#1361 Openshift ansible: rename job names for GCP update tests
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-presubmits.yaml
Labels: approved, lgtm, size/S

#1369 Start gathering artifacts for azure e2e tests
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-presubmits.yaml
  ci-operator/templates/cluster-launch-e2e-azure.yaml
Labels: approved, lgtm, sig/azure, size/S

#1372 Temporarily add PR author access to GCP upgrade namespaces
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-presubmits.yaml
Labels: approved, lgtm, size/XS

#1373 Update projected secret names in GCP upgrade jobs
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-presubmits.yaml
Labels: approved, lgtm, size/S

#1375 Add the entire DPTP team to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#1377 azure: use ARTIFACTS in o-a jobs
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/XS

#1379 run jenkins job on every PR in aws actuator repo
  ci-operator/jobs/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-presubmits.yaml
Labels: approved, lgtm, size/XS

#1366 Switch master branches to build from 4.0 images
  ci-operator/config/kubernetes/autoscaler/master.json
  ci-operator/config/kubernetes/cluster-capacity/master.json
  ci-operator/config/kubernetes/coredns/master.json
  ci-operator/config/kubernetes/descheduler/master.json
  ci-operator/config/kubernetes/metrics-server/master.json
  ci-operator/config/openshift/cluster-api-provider-aws/master.json
  ci-operator/config/openshift/cluster-dns-operator/master.json
  ci-operator/config/openshift/cluster-ingress-operator/master.json
  ci-operator/config/openshift/cluster-monitoring-operator/master.json
  ci-operator/config/openshift/cluster-operator/master.json
  ci-operator/config/openshift/cluster-samples-operator/master.json
  ci-operator/config/openshift/cluster-version-operator/master.json
  ci-operator/config/openshift/configmap-reload/master.json
  ci-operator/config/openshift/console/master.json
  ci-operator/config/openshift/image-registry/master.json
  ci-operator/config/openshift/installer/master.json
  ci-operator/config/openshift/jenkins/master.json
  ci-operator/config/openshift/kube-rbac-proxy/master.json
  ci-operator/config/openshift/kube-state-metrics/master.json
  ci-operator/config/openshift/machine-api-operator/master.json
  ci-operator/config/openshift/machine-config-operator/master.json
  ci-operator/config/openshift/openshift-ansible/master.json
  ci-operator/config/openshift/origin-aggregated-logging/master.json
  ci-operator/config/openshift/origin-metrics/master.json
  ci-operator/config/openshift/origin-web-console-server/master.json
  ci-operator/config/openshift/origin-web-console/master.json
  ci-operator/config/openshift/origin/master.json
  ci-operator/config/openshift/prometheus-operator/master.json
  ci-operator/config/openshift/service-catalog/master.json
  ci-operator/config/openshift/service-serving-cert-signer/master.json
  ci-operator/config/openshift/telemeter/master.json
Labels: approved, lgtm, size/L

#1384 Mirror 4.0 images
  Makefile
  cluster/ci/config/mirroring/origin_v3_11_quay
  cluster/ci/config/mirroring/origin_v4_0
  cluster/ci/config/mirroring/origin_v4_0_quay
  cluster/ci/jobs/image-mirror.yaml
Labels: approved, lgtm, size/L

#1385 Fixup cri-o repository path to new kubernetes-sigs organization
  ci-operator/jobs/kubernetes-sigs/cri-o/OWNERS
  ci-operator/jobs/kubernetes-sigs/cri-o/kubernetes-sigs-cri-o-periodics.yaml
  ci-operator/jobs/kubernetes-sigs/cri-o/kubernetes-sigs-cri-o-postsubmits.yaml
  ci-operator/jobs/kubernetes-sigs/cri-o/kubernetes-sigs-cri-o-presubmits.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#1380 Scale up hook
  cluster/ci/config/prow/openshift/hook.yaml
Labels: size/XS

#1371 upgrade template: make PREVIOUS_IMAGE_TAG optional and fix issues
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-presubmits.yaml
  ci-operator/templates/cluster-launch-e2e-upgrade.yaml
Labels: approved, lgtm, size/S

#1367 Openshift ansible: add runs on AWS CI
  ci-operator/config/openshift/openshift-ansible/master.json
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-presubmits.yaml
  ci-operator/templates/cluster-launch-e2e-openshift-ansible.yaml
  cluster/ci/config/prow/plugins.yaml
  cluster/test-deploy/openshift-ansible-aws/.gitignore
  cluster/test-deploy/openshift-ansible-aws/.type
  cluster/test-deploy/openshift-ansible-aws/vars-origin.yaml
  cluster/test-deploy/openshift-ansible-aws/vars.yaml
Labels: approved, lgtm, size/XL

#1388 Remove redundant branced ci config for openshift-azure
  ci-operator/config/openshift/openshift-azure/release-3.11.json
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-postsubmits-release-3.11.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-presubmits-release-3.11.yaml
Labels: approved, lgtm, sig/azure, size/L

#1387 gcp upgrade: use single quotes for oreg_url
  ci-operator/templates/cluster-launch-e2e-upgrade.yaml
Labels: approved, lgtm, size/XS

#1386 Add test_base_image to cluster-operator config
  ci-operator/config/openshift/cluster-operator/master.json
Labels: approved, lgtm, size/S

#1378 add config for cluster-api-provider-libvirt repo
  ci-operator/config/openshift/cluster-api-provider-libvirt/OWNERS
  ci-operator/config/openshift/cluster-api-provider-libvirt/master.json
  ci-operator/config/openshift/cluster-api-provider-libvirt/release-3.11.json
  ci-operator/jobs/openshift/cluster-api-provider-libvirt/OWNERS
  ci-operator/jobs/openshift/cluster-api-provider-libvirt/openshift-cluster-api-provider-libvirt-presubmits-release-3.11.yaml
  ci-operator/jobs/openshift/cluster-api-provider-libvirt/openshift-cluster-api-provider-libvirt-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#1381 openshift/os: use coreos-assembler container and cleanup
  ci-operator/jobs/openshift/os/openshift-os-presubmits.yaml
Labels: approved, lgtm, size/M

#1390 GCP upgrade: remove single quotes so that oreg_url would be substituted correctly
  ci-operator/templates/cluster-launch-e2e-upgrade.yaml
Labels: approved, lgtm, size/S

#1392 Add openshift-azure upgrade test
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-presubmits.yaml
  ci-operator/templates/cluster-launch-e2e-azure-upgrade.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: sig/azure, size/L

#1394 Fix subpath in azure upgrade job
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-presubmits.yaml
Labels: approved, size/XS

#1391 Split azure job into separate self-contained jobs
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/M

#1389 add lints for mao
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-presubmits.yaml
Labels: approved, lgtm, size/M

#1398 add origin tag spec
  ci-operator/config/openshift/azure-misc/master.json
  ci-operator/config/openshift/azure-misc/release-3.11.json
  ci-operator/config/openshift/openshift-azure/master.json
Labels: approved, lgtm, size/M

#1399 Enable release payload building on three repos
  ci-operator/jobs/openshift/cluster-ingress-operator/openshift-cluster-ingress-operator-presubmits.yaml
  ci-operator/jobs/openshift/cluster-version-operator/openshift-cluster-version-operator-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-presubmits.yaml
Labels: approved, lgtm, size/XS

#1395 Fix target in upgrade job
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-presubmits.yaml
Labels: approved, sig/azure, size/XS

#1393 GCP upgrade: use single quotes when setting template param in update tempalte
  ci-operator/templates/cluster-launch-e2e-upgrade.yaml
Labels: approved, lgtm, size/XS

#1397 Set PREVIOUS_IMAGE_TAG param as optionable
  ci-operator/templates/cluster-launch-e2e-upgrade.yaml
Labels: approved, lgtm, size/XS

#1402 Update CoreDNS job
  ci-operator/config/kubernetes/coredns/master.json
Labels: approved, lgtm, size/XS

#1404 azure: fix upgrade job
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-presubmits.yaml
Labels: approved, size/XS

#1406 add sync image build
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/XS

#1408 Promoting to wrong repo
  ci-operator/jobs/openshift/origin/openshift-origin-postsubmits.yaml
Labels: approved, lgtm, size/XS

#1409 Add 4.0 origin images to mirror
  cluster/ci/config/mirroring/origin_v4_0
  cluster/ci/config/mirroring/origin_v4_0_quay
Labels: approved, lgtm, size/M

#1410 Ansible image postsubmit has the wrong name
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-postsubmits.yaml
Labels: approved, lgtm, size/XS

#1413 reorder create logic for proper teardown
  ci-operator/templates/cluster-launch-e2e-azure-upgrade.yaml
  ci-operator/templates/cluster-launch-e2e-azure.yaml
Labels: approved, lgtm, size/M

#1400 add linting to aws-provider presubmits
  ci-operator/jobs/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-presubmits.yaml
Labels: approved, lgtm, size/M

#1414 move to sub-folder
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-presubmits.yaml
  ci-operator/templates/openshift-azure/OWNERS
  ci-operator/templates/openshift-azure/cluster-launch-e2e-azure-upgrade.yaml
  ci-operator/templates/openshift-azure/cluster-launch-e2e-azure.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/S

#1412 GCP upgrade: copy admin.kubeconfig to a shared tmp
  ci-operator/templates/cluster-launch-e2e-upgrade.yaml
Labels: approved, lgtm, size/XS

#1382 Fix trigger regexes
  ci-operator/jobs/openshift/ci-operator-prowgen/openshift-ci-operator-prowgen-presubmits.yaml
  ci-operator/jobs/openshift/ci-operator/openshift-ci-operator-presubmits.yaml
  ci-operator/jobs/openshift/cluster-dns-operator/openshift-cluster-dns-operator-presubmits.yaml
  ci-operator/jobs/openshift/cluster-ingress-operator/openshift-cluster-ingress-operator-presubmits.yaml
  ci-operator/jobs/openshift/cluster-operator/openshift-cluster-operator-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-presubmits.yaml
  ci-operator/jobs/tnozicka/openshift-acme/tnozicka-openshift-acme-presubmits.yaml
Labels: approved, lgtm, size/M

#1417 Change Dockerfile location
  ci-operator/config/openshift/cluster-api-provider-aws/master.json
Labels: approved, lgtm, size/XS

#1418 GCP upgrade: admin.kubeconfig is created in setup container
  ci-operator/templates/cluster-launch-e2e-upgrade.yaml
Labels: approved, lgtm, size/XS

#1419 Setup correct environment for upgrades
  ci-operator/templates/openshift-azure/cluster-launch-e2e-azure-upgrade.yaml
  ci-operator/templates/openshift-azure/cluster-launch-e2e-azure.yaml
Labels: approved, lgtm, sig/azure, size/S

#1420 Add missing quotes around PREVIOUS_IMAGE_ANSIBLE to fix gcp minor upgrades
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-presubmits.yaml
Labels: approved, lgtm, size/XS

#1421 Reformat the ugly
  ci-operator/infra/openshift/origin/artifacts-master.yaml
  ci-operator/infra/openshift/origin/artifacts-release-3.11.yaml
Labels: approved, lgtm, size/M

#1424 Mount azure credentials in test container
  ci-operator/templates/openshift-azure/cluster-launch-e2e-azure-upgrade.yaml
Labels: approved, lgtm, sig/azure, size/XS

#1317 openshift/install e2e-aws add run smoke tests
  ci-operator/config/openshift/installer/master.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-presubmits.yaml
  ci-operator/templates/cluster-launch-installer-e2e-smoke.yaml
  projects/origin-release/bazel/Dockerfile
  projects/origin-release/pipeline.yaml
Labels: approved, lgtm, size/L

#1427 add trigger plugin to kubernetes-sigs
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#1428 edit 'origin-release' to 'release' in is name
  ci-operator/config/openshift/installer/master.yaml
Labels: approved, lgtm, size/XS

#1430 Unsaved content on the publish
  ci-operator/config/openshift/builder/master.yaml
Labels: approved, lgtm, size/XS

#1431 use origin-release:golang-1.10 Dockerfile to build origin-release:bazel
  projects/origin-release/pipeline.yaml
Labels: approved, lgtm, size/XS

#1433 change master.json to master.yaml for e2e-aws-smoke
  ci-operator/jobs/openshift/installer/openshift-installer-presubmits.yaml
Labels: approved, lgtm, size/XS

#1434 add configMap for e2e-aws-smoke
  Makefile
  ci-operator/jobs/openshift/installer/openshift-installer-presubmits.yaml
Labels: approved, lgtm, size/XS

#1442 Run upgrade test on merged commits
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-postsubmits.yaml
Labels: approved, lgtm, sig/azure, size/M

#1416 Run openshift-azure e2e tests in e2e job
  ci-operator/templates/openshift-azure/cluster-launch-e2e-azure.yaml
Labels: approved, lgtm, sig/azure, size/XS

#1443 use redhat tooling image
  ci-operator/jobs/openshift/installer/openshift-installer-presubmits.yaml
Labels: approved, lgtm, size/XS

#1444 use official rh tooling image
  ci-operator/jobs/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-presubmits.yaml
Labels: approved, lgtm, size/S

#1425 Change repo path
  ci-operator/config/openshift/cluster-api-provider-aws/master.yaml
Labels: approved, lgtm, size/XS

#1437 Run gcp upgrade 3.9 -> 3.10 upgrade on release-3.10
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-presubmits.yaml
Labels: approved, lgtm, size/M

#1440 Openshift-ansible AWS RHEL: update config name and mount openshift-ansible config
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-presubmits.yaml
  cluster/ci/config/prow/plugins.yaml
  cluster/test-deploy/openshift-ansible-aws-rhel/.gitignore
  cluster/test-deploy/openshift-ansible-aws-rhel/.type
  cluster/test-deploy/openshift-ansible-aws-rhel/vars-origin.yaml
  cluster/test-deploy/openshift-ansible-aws-rhel/vars.yaml
Labels: approved, lgtm, size/XS

#1415 install libvirt devel libraries for libvirt-actuator
  ci-operator/config/openshift/cluster-api-provider-libvirt/master.yaml
  ci-operator/config/openshift/cluster-api-provider-libvirt/release-3.11.yaml
Labels: approved, lgtm, size/XS

#1441 Continue testing upgrades in e2e
  ci-operator/templates/openshift-azure/cluster-launch-e2e-azure-upgrade.yaml
Labels: approved, lgtm, size/XS

#1436 cluster-launch-installer-e2e*: Drop AMI override
  ci-operator/templates/cluster-launch-installer-e2e-smoke.yaml
  ci-operator/templates/cluster-launch-installer-e2e.yaml
  cluster/test-deploy/aws/openshift.yaml
Labels: approved, lgtm, size/XS

#1449 cluster/ci/config/prow/plugins: Auto-update the installer e2e-smoke config
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#1450 add/update CI jobs for samples operator
  ci-operator/config/openshift/cluster-samples-operator/master.yaml
  ci-operator/jobs/openshift/cluster-samples-operator/openshift-cluster-samples-operator-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-samples-operator/openshift-cluster-samples-operator-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#1426 add libvirt-devel package to tooling images
  projects/origin-release/golang-1.10/Dockerfile
  projects/origin-release/golang-1.11/Dockerfile
Labels: approved, lgtm, size/XS

#1435 openshift-installer-presubmits: Normalize e2e-aws-smoke name
  ci-operator/jobs/openshift/installer/openshift-installer-presubmits.yaml
Labels: approved, lgtm, size/XS

#1411 add linters to libvirt actuator
  ci-operator/jobs/openshift/cluster-api-provider-libvirt/openshift-cluster-api-provider-libvirt-presubmits.yaml
Labels: approved, lgtm, size/M

#1439 azure: use same nested structure for templates as elsewhere
  ci-operator/templates/openshift-azure/README.md
  ci-operator/templates/openshift/openshift-azure/OWNERS
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure-conformance.yaml
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure-upgrade.yaml
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, sig/azure, size/XS

#1347 update secret names and doc for osa
  Makefile
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-presubmits.yaml
  projects/azure/README.md
  projects/azure/azure-purge/cronjob.yaml
Labels: approved, lgtm, sig/azure, size/M

#1452 osa - add prometheus-sidecar
  ci-operator/config/openshift/azure-misc/master.yaml
Labels: approved, lgtm, size/S

#1454 typo
  ci-operator/config/openshift/azure-misc/master.yaml
Labels: approved, lgtm, size/XS

#1451 Avoid installing loganalytics in CI tests
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure-conformance.yaml
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure-upgrade.yaml
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure.yaml
Labels: approved, lgtm, sig/azure, size/XS

#1455 osa - change base image
  ci-operator/config/openshift/azure-misc/master.yaml
Labels: approved, lgtm, size/XS

#1459 Give PR authors access to installer jobs
  ci-operator/jobs/openshift/installer/openshift-installer-presubmits-release-3.11.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-presubmits.yaml
Labels: approved, lgtm, size/L

#1462 Enable tide for tnozicka/openshift-acme
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/XS

#1465 Move plugin-specific configuration to the bottom of plugins.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#1466 turn on approval for builder repo
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#1458 add libvirt-actuator image creation and publishing
  ci-operator/config/openshift/cluster-api-provider-libvirt/master.yaml
  ci-operator/config/openshift/cluster-api-provider-libvirt/release-3.11.yaml
  ci-operator/jobs/openshift/cluster-api-provider-libvirt/openshift-cluster-api-provider-libvirt-postsubmits-release-3.11.yaml
  ci-operator/jobs/openshift/cluster-api-provider-libvirt/openshift-cluster-api-provider-libvirt-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-libvirt/openshift-cluster-api-provider-libvirt-presubmits-release-3.11.yaml
  ci-operator/jobs/openshift/cluster-api-provider-libvirt/openshift-cluster-api-provider-libvirt-presubmits.yaml
Labels: approved, lgtm, size/L

#1467 Fix openshift-acme e2e
  ci-operator/config/tnozicka/openshift-acme/master.yaml
  ci-operator/jobs/tnozicka/openshift-acme/tnozicka-openshift-acme-postsubmits.yaml
  ci-operator/jobs/tnozicka/openshift-acme/tnozicka-openshift-acme-presubmits.yaml
Labels: approved, lgtm, size/M

#1471 Revert ci-operator to known-good commit for promotion
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-postsubmits.yaml
  projects/azure/base-images/ci-operator.yaml
  projects/azure/config-updater/config-updater.yaml
Labels: approved, lgtm, sig/azure, size/M

#1473 Run osa e2e tests after cluster upgrade
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure-upgrade.yaml
Labels: approved, lgtm, sig/azure, size/XS

#1453 Fix upgrade template to allow 3.9 -> 3.10 upgrades
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-presubmits.yaml
  ci-operator/templates/cluster-launch-e2e-upgrade.yaml
Labels: approved, lgtm, size/L

#1476 No more need to install dependencies as base image contains them
  ci-operator/config/openshift/cluster-api-provider-libvirt/master.yaml
Labels: approved, lgtm, size/XS

#1472 Update JOB_NAME in gcp-ha job for openshift-ansible
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-presubmits.yaml
Labels: approved, lgtm, size/S

#1477 tnozicka/openshift-acme: Auto-update ci-operator-tnozicka-openshift-acme ConfigMap when ci-operator config is changed
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#1480 openshift-ansible: remove wrong references to gcp-ha in gcp jobs
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-presubmits.yaml
Labels: approved, lgtm, size/XS

#1482 prow: fix job_url_template for kubernetes-sigs org
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/XS

#1488 Fix plugin enablement to match tide configurations
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#1490 Add a test base image to make tests happy
  ci-operator/config/openshift/cluster-operator/tools.yaml
Labels: approved, lgtm, size/XS

#1486 openshift-installer-presubmits: Drop the go-lint min confidence to 0.3
  ci-operator/jobs/openshift/installer/openshift-installer-presubmits.yaml
Labels: approved, lgtm, size/XS

#1487 make installer smoke_test images optional in config
  ci-operator/config/openshift/installer/master.yaml
Labels: approved, lgtm, size/XS

#1481 openshift-ansible: remove wrong references to -ha from volumes in 3.10
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-presubmits.yaml
Labels: approved, lgtm, size/XS

#1489 Remove no longer used branch jobs
  ci-operator/jobs/openshift/origin/openshift-origin-postsubmits.yaml
Labels: approved, lgtm, size/S

#1484 remove 3.11 from cluster-api-provider-libvirt
  ci-operator/config/openshift/cluster-api-provider-libvirt/release-3.11.yaml
  ci-operator/jobs/openshift/cluster-api-provider-libvirt/openshift-cluster-api-provider-libvirt-postsubmits-release-3.11.yaml
  ci-operator/jobs/openshift/cluster-api-provider-libvirt/openshift-cluster-api-provider-libvirt-presubmits-release-3.11.yaml
Labels: approved, lgtm, size/L

#1492 Scope conformance test artifacts so they don't collide with gcp
  ci-operator/jobs/openshift/origin/openshift-origin-presubmits-release-3.11.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-presubmits.yaml
Labels: approved, lgtm, size/M

#1493 Enable spyglass viewer
  cluster/ci/config/prow/openshift/deck.yaml
Labels: approved, lgtm, size/XS

#1494 Enable private-preview labeling
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#1475 Mount commit id in sync image
  ci-operator/config/openshift/openshift-azure/master.yaml
Labels: approved, lgtm, sig/azure, size/XS

#1456 add mirror for Prometheus
  ci-operator/jobs/openshift/azure-misc/openshift-azure-misc-postsubmits-release-3.11.yaml
  ci-operator/jobs/openshift/azure-misc/openshift-azure-misc-presubmits-release-3.11.yaml
  projects/azure/image-mirror/image-mirror.yaml
Labels: approved, lgtm, sig/azure, size/M

#1468 osa - add overrides
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure-conformance.yaml
Labels: approved, lgtm, size/XS

#1483 Upgrade template: skip package check
  ci-operator/templates/cluster-launch-e2e-upgrade.yaml
Labels: approved, lgtm, size/XS

#1498 tnozicka/openshift-acme: Fix JOB_NAME_SAFE dependants
  ci-operator/jobs/tnozicka/openshift-acme/manual-presubmits.yaml
Labels: approved, lgtm, size/S

#1495 remove 3.11 from cloud team repos and change image names
  ci-operator/config/openshift/cluster-api-provider-aws/master.yaml
  ci-operator/config/openshift/cluster-api-provider-aws/release-3.11.yaml
  ci-operator/config/openshift/cluster-api-provider-libvirt/master.yaml
  ci-operator/config/openshift/machine-api-operator/release-3.11.yaml
  ci-operator/jobs/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-postsubmits-release-3.11.yaml
  ci-operator/jobs/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-presubmits-release-3.11.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-postsubmits-release-3.11.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-presubmits-release-3.11.yaml
Labels: approved, lgtm, size/L

#1457 Test GCP upgrade for 3.10 -> 3.11
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-presubmits-release-3.11.yaml
Labels: approved, lgtm, size/M

#1503 openshift-ansible: use PREVIOUS_ANSIBLE_VERSION for 3.11 gcp upgrade
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-presubmits-release-3.11.yaml
Labels: approved, lgtm, size/XS

#1502 azure: add image node build job
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-periodics.yaml
  ci-operator/templates/openshift/openshift-azure/build-azure-image.yaml
Labels: approved, lgtm, sig/azure, size/L

#1501 Add openshift-azure test image
  projects/azure/base-images/openshift-azure.yaml
  projects/azure/config-updater/config-updater.yaml
Labels: approved, lgtm, sig/azure, size/M

#1505 Fix node build template job
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-periodics.yaml
Labels: approved, lgtm, size/S

#1506 Revert "Mount commit id in sync image"
  ci-operator/config/openshift/openshift-azure/master.yaml
Labels: approved, size/XS

#1507 Fix azure secret in build node template
  ci-operator/templates/openshift/openshift-azure/build-azure-image.yaml
Labels: approved, size/XS

#1508 Update build node template automatically
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#1509 Fix sourcing credentials in build node job
  ci-operator/templates/openshift/openshift-azure/build-azure-image.yaml
Labels: size/XS

#1510 promote libvirt-actuator to 4.0
  ci-operator/config/openshift/cluster-api-provider-libvirt/master.yaml
Labels: approved, lgtm, size/XS

#1511 fix 3.11 where it should say 4.0
  ci-operator/config/openshift/cluster-api-provider-libvirt/master.yaml
Labels: approved, lgtm, size/XS

#1512 enable tide for library
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#1504 openshift-ansible: use old url for 3.10 repos
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-presubmits-release-3.11.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-presubmits.yaml
Labels: approved, lgtm, size/S

#1517 installer smoke_tests use LOCAL_IMAGE for optional installer-smoke image
  ci-operator/templates/cluster-launch-installer-e2e-smoke.yaml
Labels: approved, lgtm, size/S

#1491 Regular jobs shouldn't be using registry/serial
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-presubmits-release-3.11.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-presubmits.yaml
Labels: approved, lgtm, size/M

#1518 Revert recent installer smoke-test changes
  ci-operator/config/openshift/installer/master.yaml
  ci-operator/templates/cluster-launch-installer-e2e-smoke.yaml
Labels: approved, lgtm, size/S

#1513 enable auto merging and approval for logging operators
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#1499 Periodic job for autoscaler
  ci-operator/jobs/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-periodics.yaml
Labels: approved, lgtm, size/XS

#1461 add test blacklist
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-presubmits.yaml
Labels: approved, lgtm, size/S

#1522 add make vet to our ci-operator tests config for openshift-azure
  ci-operator/config/openshift/openshift-azure/master.yaml
Labels: approved, lgtm, size/XS

#1520 osa- skip-tests determinize-prow-jobs jobs invalidates skip regexp
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-presubmits.yaml
Labels: approved, lgtm, size/XS

#1515 Bump Terraform from 0.11.7 to 0.11.8
  ci-operator/jobs/openshift/installer/openshift-installer-presubmits.yaml
Labels: approved, lgtm, size/XS

#1485 turn on extended tests for builder repo
  ci-operator/config/openshift/builder/OWNERS
  ci-operator/config/openshift/builder/master.yaml
  ci-operator/jobs/openshift/builder/OWNERS
  ci-operator/jobs/openshift/builder/openshift-builder-presubmits.yaml
Labels: approved, lgtm, size/L

#1525 add missing rpm repo arg
  ci-operator/jobs/openshift/builder/openshift-builder-presubmits.yaml
Labels: approved, lgtm, size/S

#1526 Push spec overrides into the config files
  ci-operator/config/openshift/origin/master.yaml
  ci-operator/config/openshift/origin/release-3.11.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-periodics.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-postsubmits-release-3.11.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-postsubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-presubmits-release-3.11.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-presubmits.yaml
Labels: approved, lgtm, size/M

#1523 add binary value to the path
  ci-operator/config/openshift/azure-misc/master.yaml
Labels: approved, lgtm, size/XS

#1528 Source azure credentials that ansible expects
  ci-operator/templates/openshift/openshift-azure/build-azure-image.yaml
Labels: approved, lgtm, sig/azure, size/S

#1519 Fix pull-ci-openshift-openshift-ansible-3.11-gcp-major-upgrade
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-presubmits-release-3.11.yaml
Labels: approved, lgtm, size/S

#1532 Remove skip_collaborators for openshift-azure
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, sig/azure, size/XS

#1531 Add OLM prow config and unit tests
  ci-operator/config/operator-framework/operator-lifecycle-manager/master.yaml
  ci-operator/config/operator-framework/operator-lifecycle-manager/release-3.11.yaml
  ci-operator/jobs/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-postsubmits.yaml
  ci-operator/jobs/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#1534 olm config: use same set of plugins as origin
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/S

#1538 Initial commit for containers/libpod
  ci-operator/config/containers/libpod/master.yaml
  ci-operator/jobs/containers/libpod/containers-libpod-postsubmits.yaml
  ci-operator/jobs/containers/libpod/containers-libpod-presubmits.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/M
