Repository openshift/release, pull requests merged in 2018-08, with the labels that each got.

#1133 Run unit tests for openshift-azure jobs
  ci-operator/config/openshift/openshift-azure/master.json
  cluster/ci/config/prow/config.yaml
Labels: sig/azure, size/XS

#1134 Use the report template in plank and sinker
  cluster/ci/config/prow/config.yaml
Labels: lgtm, size/XS

#1135 Disable gcp-upgrade job for release-3.10
  cluster/ci/config/prow/config.yaml
Labels: size/XS

#1138 Added prow yaml-lint job description for installer repo
  cluster/ci/config/prow/config.yaml
Labels: lgtm, size/S

#1140 Set up CI for the TTL controller
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: lgtm, size/M

#1139 Bump Go version for image-registry master
  ci-operator/config/openshift/image-registry/master.json
Labels: lgtm, size/XS

#1142 Automatically upload job config
  cluster/ci/config/prow/plugins.yaml
Labels: lgtm, size/XS

#1143 Add Origin presubmits to their own file
  ci-operator/jobs/openshift/origin/openshift-origin-presubmits.yaml
Labels: approved, lgtm, size/XL

#1146 Dummy update to config to trigger config-updater
  ci-operator/jobs/openshift/origin/openshift-origin-presubmits.yaml
Labels: lgtm, size/XS

#1147 Use job configuration in prow deployments
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
Labels: lgtm, size/M

#1145 Make config job run on split out configs
  Makefile
  cluster/ci/config/prow/config.yaml
Labels: lgtm, size/XL

#1148 Use latest image for jenkins-operator
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
Labels: size/XS

#1149 Don't use `tot` for build IDs
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
Labels: lgtm

#1150 Use the Jenkins build ID for links
  cluster/ci/config/prow/config.yaml
Labels: size/XS

#1128 deprecate 3.9 prow
  ci-operator/jobs/openshift/origin/openshift-origin-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  projects/azure/acs-engine/test-image-builds/Dockerfiles/3.9/Dockerfile
  projects/azure/acs-engine/test-image-builds/build-3.9.yaml
Labels: lgtm, sig/azure, size/M

#1154 Remove stale build
  projects/azure/config-updater/config-updater.yaml
Labels: size/XS

#1155 Remove redundant azure-misc plugin config
  cluster/ci/config/prow/plugins.yaml
Labels: size/XS

#1156 Gate openshift-azure on an extra needs-signoff label
  cluster/ci/config/prow/config.yaml
Labels: lgtm, sig/azure, size/S

#1157 Automate adding/removing needs-signoff label
  cluster/ci/config/prow/plugins.yaml
Labels: sig/azure, size/XS

#1124 Prow: Add terraform lintern to openshift/installer
  cluster/ci/config/prow/config.yaml
Labels: lgtm, size/S

#1141 Add RBAC to allow ci-operator to annotate namespaces
  cluster/ci/config/prow/openshift/ci-operator/roles.yaml
Labels: size/S

#1158 Install libseccomp-devel in the origin-release:golang-1.{10,11} image
  projects/origin-release/golang-1.10/Dockerfile
  projects/origin-release/golang-1.11/Dockerfile
Labels: lgtm, size/XS

#1131 Prow: Add shell check to openshift/installer
  cluster/ci/config/prow/config.yaml
Labels: lgtm, size/S

#1163 inject nodejs/maven agent images into jenkins e2e
  ci-operator/config/openshift/jenkins/master.json
  ci-operator/templates/cluster-launch-e2e-gmontero-testing.yaml
Labels: lgtm, size/M

#1165 Allow MSFT to lgtm/approve PRs in openshift-azure
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: size/XS

#1170 Add more ci-admins
  cluster/ci/config/roles.yaml
Labels: lgtm, size/XS

#1172 Remove hacky job check script
  Makefile
  hack/lib/check_jobs.py
Labels: approved, lgtm, size/S

#1164 e2e tests for OSA Template
  Makefile
  ci-operator/config/openshift/openshift-azure/master.json
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-postsubmits.yaml
  ci-operator/templates/cluster-launch-e2e-azure.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
  cluster/test-deploy/azure/.gitignore
  cluster/test-deploy/azure/secret_example
  projects/azure/README.md
  projects/azure/azure-purge/cronjob.yaml
  projects/azure/base-images/test-base.yaml
  projects/azure/config-updater/config-updater.yaml
Labels: lgtm, sig/azure, size/L

#1174 Ensure multiple jobs don't compete for the same template instance name
  ci-operator/jobs/openshift/origin/openshift-origin-presubmits.yaml
Labels: lgtm, size/S

#1095 Machine api operator
  ci-operator/config/openshift/machine-api-operator/master.json
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-postsubmits.yml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-presubmits.yml
  cluster/ci/config/prow/plugins.yaml
Labels: lgtm, size/L

#1113 E2E docs
  ci-operator/README.md
Labels: lgtm, size/L

#1152 openshift installer: add terraform fmt
  ci-operator/jobs/openshift/installer/openshift-installer-presubmits.yaml
Labels: lgtm, size/S

#1179 If install succeeds, guarantee we grab output even if it doesn't stabilize
  ci-operator/templates/cluster-launch-installer-e2e.yaml
Labels: lgtm, size/XS

#1178 add openshift/installer 'bazel build tarball' test to prow
  ci-operator/jobs/openshift/installer/openshift-installer-presubmits.yaml
Labels: lgtm, size/S

#1180 Add a tagging script
  hack/tag
Labels: lgtm, size/M

#1175 add prow to configure e2e for azure
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-presubmits.yaml
  ci-operator/templates/cluster-launch-e2e-azure.yaml
Labels: lgtm, sig/azure, size/M

#1182 Fix azure jobs configmap names
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-presubmits.yaml
Labels: size/XS

#1183 Add cluster version operator job definitions
  ci-operator/config/openshift/cluster-version-operator/master.json
  ci-operator/jobs/openshift/cluster-version-operator/openshift-cluster-version-operator-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-version-operator/openshift-cluster-version-operator-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: lgtm, size/L

#1186 Fix CVO jobs
  ci-operator/jobs/openshift/cluster-version-operator/openshift-cluster-version-operator-postsubmits.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: lgtm, size/XS

#1187 Add a presubmit for openshift/api
  ci-operator/config/openshift/api/master.json
  ci-operator/jobs/openshift/api/openshift-api-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: lgtm, size/M

#1181 Added go-vet prow job
  ci-operator/jobs/openshift/installer/openshift-installer-presubmits.yaml
Labels: lgtm, size/S

#1185 openshift-installer-presubmits: Set HOME and USER for bazel-build-tarball
  ci-operator/jobs/openshift/installer/openshift-installer-presubmits.yaml
Labels: lgtm, size/XS

#1190 openshift-installer-presubmits: Separate sequence entry for --action_env
  ci-operator/jobs/openshift/installer/openshift-installer-presubmits.yaml
Labels: lgtm, size/XS

#1191 Don't run the E2E tests on installer documentation
  ci-operator/jobs/openshift/installer/openshift-installer-presubmits.yaml
Labels: lgtm, size/XS

#1184 add 3.10 config for jenkins e2e testing
  ci-operator/config/openshift/jenkins/openshift-3.10.json
  ci-operator/jobs/openshift/jenkins/openshift-jenkins-presubmits.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: lgtm, size/L

#1193 Document configuration loading rules for e2e tests
  ci-operator/README.md
Labels: lgtm, size/XS, ¯\_(ツ)_/¯

#1177 Prow: Add golint to openshift/installer
  ci-operator/jobs/openshift/installer/openshift-installer-presubmits.yaml
Labels: lgtm, size/S

#1192 simplify machine-api-operator build process
  ci-operator/config/openshift/machine-api-operator/master.json
Labels: lgtm, size/S

#1195 Add machine config operator job definitions
  ci-operator/config/openshift/machine-config-operator/master.json
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-postsubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: lgtm, size/L

#1136 Add profile for gcp-crio-dev
  cluster/test-deploy/gcp-crio-dev/.gitignore
  cluster/test-deploy/gcp-crio-dev/.type
  cluster/test-deploy/gcp-crio-dev/vars-origin.yaml
  cluster/test-deploy/gcp-crio-dev/vars.yaml
Labels: lgtm, size/L

#1197 Add cluster-ingress-operator
  cluster/ci/config/prow/plugins.yaml
Labels: lgtm, size/XS

#1198 Add cluster-dns-operator
  cluster/ci/config/prow/plugins.yaml
Labels: lgtm, size/XS

#1199 Enable automerge for edge operators
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: lgtm, size/XS

#1196 Sync shrug label
  cluster/ci/config/prow/labels.yaml
Labels: lgtm, size/XS, ¯\_(ツ)_/¯

#1202 verify test fix for glide
  projects/azure/base-images/test-base.yaml
Labels: lgtm, sig/azure, size/XS

#1203 Fix markdown headers
  ci-operator/README.md
Labels: lgtm, size/XS

#1206 cluster/test-deploy/aws/openshift: Move sshKey to the admin block
  ci-operator/templates/cluster-launch-installer-e2e.yaml
  cluster/test-deploy/aws/openshift.yaml
Labels: lgtm, size/XS

#1207 Capture inputs.yaml first
  ci-operator/templates/cluster-launch-installer-e2e.yaml
Labels: lgtm, size/XS

#1208 Automatically sync the job profiles to their configmap
  cluster/ci/config/prow/plugins.yaml
Labels: lgtm, size/S

#1209 cluster/test-deploy/aws/openshift: Fix = -> : for extraTags
  cluster/test-deploy/aws/openshift.yaml
Labels: lgtm, size/XS

#1210 Sync correct profiles directory
  cluster/ci/config/prow/plugins.yaml
Labels: lgtm

#1201 Auto-generate OWNERS
  ci-operator/config/openshift/azure-misc/OWNERS
  ci-operator/config/openshift/cluster-monitoring-operator/OWNERS
  ci-operator/config/openshift/image-registry/OWNERS
  ci-operator/config/openshift/installer/OWNERS
  ci-operator/config/openshift/jenkins/OWNERS
  ci-operator/config/openshift/kube-state-metrics/OWNERS
  ci-operator/config/openshift/machine-api-operator/OWNERS
  ci-operator/config/openshift/openshift-ansible/OWNERS
  ci-operator/config/openshift/openshift-azure/OWNERS
  ci-operator/config/openshift/origin/OWNERS
  ci-operator/config/openshift/service-catalog/OWNERS
  ci-operator/config/openshift/service-serving-cert-signer/OWNERS
  ci-operator/jobs/kubernetes-incubator/cri-o/OWNERS
  ci-operator/jobs/kubernetes-incubator/descheduler/OWNERS
  ci-operator/jobs/openshift-s2i/s2i-wildfly/OWNERS
  ci-operator/jobs/openshift/autoheal/OWNERS
  ci-operator/jobs/openshift/azure-misc/OWNERS
  ci-operator/jobs/openshift/ci-ns-ttl-controller/OWNERS
  ci-operator/jobs/openshift/ci-operator/OWNERS
  ci-operator/jobs/openshift/ci-vm-operator/OWNERS
  ci-operator/jobs/openshift/cluster-capacity/OWNERS
  ci-operator/jobs/openshift/cluster-monitoring-operator/OWNERS
  ci-operator/jobs/openshift/coredns/OWNERS
  ci-operator/jobs/openshift/descheduler/OWNERS
  ci-operator/jobs/openshift/image-registry/OWNERS
  ci-operator/jobs/openshift/installer/OWNERS
  ci-operator/jobs/openshift/jenkins-client-plugin/OWNERS
  ci-operator/jobs/openshift/jenkins-openshift-login-plugin/OWNERS
  ci-operator/jobs/openshift/jenkins-plugin/OWNERS
  ci-operator/jobs/openshift/jenkins-sync-plugin/OWNERS
  ci-operator/jobs/openshift/jenkins/OWNERS
  ci-operator/jobs/openshift/kube-state-metrics/OWNERS
  ci-operator/jobs/openshift/machine-api-operator/OWNERS
  ci-operator/jobs/openshift/online-console-extensions/OWNERS
  ci-operator/jobs/openshift/online-hibernation/OWNERS
  ci-operator/jobs/openshift/online-registration/OWNERS
  ci-operator/jobs/openshift/openshift-ansible/OWNERS
  ci-operator/jobs/openshift/openshift-azure/OWNERS
  ci-operator/jobs/openshift/origin/OWNERS
  ci-operator/jobs/openshift/ose/OWNERS
  ci-operator/jobs/openshift/service-catalog/OWNERS
  ci-operator/jobs/openshift/service-serving-cert-signer/OWNERS
  ci-operator/populate-owners.sh
Labels: lgtm, size/L

#1212 Gather node logs in parallel on shutdown, time bound fetch
  ci-operator/templates/cluster-launch-e2e-gmontero-testing.yaml
  ci-operator/templates/cluster-launch-e2e.yaml
  ci-operator/templates/cluster-launch-installer-e2e.yaml
  ci-operator/templates/cluster-launch-src.yaml
Labels: lgtm, size/L

#1220 Add the invalid OWNERS label to our sync
  cluster/ci/config/prow/labels.yaml
Labels: lgtm, size/XS

#1204 Add network edge component ci-operator support
  ci-operator/config/openshift/cluster-dns-operator/master.json
  ci-operator/config/openshift/cluster-ingress-operator/master.json
  ci-operator/jobs/openshift/cluster-dns-operator/openshift-cluster-dns-operator-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-dns-operator/openshift-cluster-dns-operator-presubmits.yaml
  ci-operator/jobs/openshift/cluster-ingress-operator/openshift-cluster-ingress-operator-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-ingress-operator/openshift-cluster-ingress-operator-presubmits.yaml
Labels: lgtm, size/L

#1216 Build openshift-ansible for 3.10 and run gcp tests
  ci-operator/config/openshift/openshift-ansible/release-3.10.json
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-presubmits.yaml
Labels: lgtm, size/L

#1205 cluster/ci/config/prow/plugins: Add golint for openshift/installer
  cluster/ci/config/prow/plugins.yaml
Labels: lgtm, size/XS

#1162 ci-operator config for cluster operator
  ci-operator/config/openshift/cluster-operator/OWNERS
  ci-operator/config/openshift/cluster-operator/master.json
  ci-operator/jobs/openshift/cluster-operator/openshift-cluster-operator-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-operator/openshift-cluster-operator-presubmits.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: lgtm, size/L

#1221 Check for router in all possible namespaces until we converge
  ci-operator/templates/cluster-launch-installer-e2e.yaml
Labels: lgtm, size/S

#1219 add OWNERS for logging
  ci-operator/config/openshift/origin-aggregated-logging/OWNERS
  ci-operator/jobs/openshift/origin-aggregated-logging/OWNERS
Labels: lgtm, size/M

#1227 Use the new blunderbuss algorithms
  cluster/ci/config/prow/plugins.yaml
Labels: lgtm, size/XS

#1228 Require approval on openshift/release
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: lgtm, size/S

#1230 Seed OWNERS for the repo root
  OWNERS
Labels: approved, lgtm, size/XS

#1223 Add coutil to cluster-operator image build
  ci-operator/config/openshift/cluster-operator/master.json
Labels: approved, lgtm, size/XS

#1222 introduce ci-operator/prow wiring for cluster-sample-operator
  ci-operator/config/openshift/cluster-samples-operator/master.json
  ci-operator/jobs/openshift/cluster-samples-operator/OWNERS
  ci-operator/jobs/openshift/cluster-samples-operator/openshift-cluster-samples-operator-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-samples-operator/openshift-cluster-samples-operator-presubmits.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/M

#1236 Relocate cluster-ingress-operator Dockerfile
  ci-operator/config/openshift/cluster-ingress-operator/master.json
Labels: approved, lgtm, size/XS

#1234 Update test-deploy README
  cluster/test-deploy/README.md
Labels: approved, lgtm, size/XS

#1237 Update Cluster Operator config owners
  ci-operator/config/openshift/cluster-operator/OWNERS
Labels: approved, lgtm, size/XS

#1239 ci-operator is not part of the origin release
  ci-operator/config/openshift/ci-operator/master.json
  ci-operator/jobs/openshift/ci-operator/openshift-ci-operator-postsubmits.yaml
Labels: approved, lgtm, size/M

#1242 Update image mirror for recent changes
  cluster/ci/config/mirroring/origin_v3_10
  cluster/ci/config/mirroring/origin_v3_11
  cluster/ci/config/mirroring/origin_v3_11_quay
Labels: approved, lgtm, size/XS

#1240 openshift-ansible's gcp-310 job should use 3.10 images
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-presubmits.yaml
Labels: approved, lgtm, size/XS

#1241 Set up autoconfig and OWNERS for ingress components
  ci-operator/config/openshift/cluster-dns-operator/OWNERS
  ci-operator/config/openshift/cluster-ingress-operator/OWNERS
  ci-operator/jobs/openshift/cluster-dns-operator/OWNERS
  ci-operator/jobs/openshift/cluster-ingress-operator/OWNERS
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/M

#1243 Fix job syntax error
  ci-operator/config/openshift/cluster-dns-operator/master.json
  ci-operator/config/openshift/cluster-ingress-operator/master.json
Labels: approved, lgtm, size/XS

#1244 crio jobs should use a different template name than gcp
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-presubmits.yaml
Labels: approved, lgtm, size/XS

#1231 do not self approve PRs from creators
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#1246 hook jenkins job for machine-api-operator
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-presubmits.yml
Labels: approved, lgtm, size/XS

#1249 Make it a bit easier to debug installer e2e-aws
  ci-operator/templates/cluster-launch-installer-e2e.yaml
Labels: approved, lgtm, size/S

#1229 DRY plugin config
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#1248 openshift-ansible: remove test_pull_request_openshift_ansible_extended_conformance_gce_310
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-presubmits.yaml
Labels: approved, lgtm, size/S

#1247 Add machine-api-operator repo to tide
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/XS

#1250 Fix plugin config to not dupe plugins
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm

#1252 Add a CI Operator configuration check job
  ci-operator/config/openshift/ci-operator/master.json
  ci-operator/jobs/openshift/release/openshift-release-presubmits.yaml
Labels: approved, size/M

#1256 Use correct argument formatting for config jobs
  ci-operator/jobs/openshift/release/openshift-release-presubmits.yaml
Labels: approved

#1257 Relocate cluster-dns-operator Dockerfile
  ci-operator/config/openshift/cluster-dns-operator/master.json
Labels: approved, lgtm, size/XS

#1255 Relocate cluster-ingress-operator Dockerfile
  ci-operator/config/openshift/cluster-ingress-operator/master.json
Labels: approved, lgtm, size/XS

#1259 Base all Prow builds off of one binary build, use lists
  Makefile
  cluster/ci/config/prow/openshift/build/binaries.yaml
  cluster/ci/config/prow/openshift/build/checkconfig.yaml
  cluster/ci/config/prow/openshift/build/cherrypick.yaml
  cluster/ci/config/prow/openshift/build/deck.yaml
  cluster/ci/config/prow/openshift/build/hook.yaml
  cluster/ci/config/prow/openshift/build/horologium.yaml
  cluster/ci/config/prow/openshift/build/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/build/needs_rebase.yaml
  cluster/ci/config/prow/openshift/build/plank.yaml
  cluster/ci/config/prow/openshift/build/refresh.yaml
  cluster/ci/config/prow/openshift/build/sinker.yaml
  cluster/ci/config/prow/openshift/build/tide.yaml
  cluster/ci/config/prow/openshift/build/tot.yaml
  cluster/ci/config/prow/openshift/build/tracer.yaml
Labels: approved, size/XL

#1260 Update location of ci-op checkconfig
  ci-operator/jobs/openshift/release/openshift-release-presubmits.yaml
Labels: approved, size/XS

#1233 Image building and unit tests for cluster-api-provider-aws
  ci-operator/config/openshift/cluster-api-provider-aws/master.json
  ci-operator/jobs/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-presubmits.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#1262 move yml to yaml as prow/config.go expects yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-postsubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-presubmits.yaml
Labels: approved, lgtm, size/XS

#1160 Add a ci-operator Prow job generator
  tools/ci-operator-prowgen/Gopkg.lock
  tools/ci-operator-prowgen/Gopkg.toml
  tools/ci-operator-prowgen/README.md
  tools/ci-operator-prowgen/main.go
  tools/ci-operator-prowgen/main_test.go
Labels: approved, lgtm, size/XXL

#1267 Use tollbooth for telemetry
  Makefile
  ci-operator/templates/cluster-launch-e2e.yaml
  ci-operator/templates/cluster-launch-installer-e2e.yaml
  ci-operator/templates/cluster-launch-src.yaml
Labels: approved, lgtm, size/S

#1268 Set up CI for the Prow config generator
  ci-operator/config/openshift/ci-operator-prowgen/master.json
  ci-operator/jobs/openshift/ci-operator-prowgen/openshift-ci-operator-prowgen-postsubmits.yaml
  ci-operator/jobs/openshift/ci-operator-prowgen/openshift-ci-operator-prowgen-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#1269 Allow the ci-operator to promote to the CI namespace
  cluster/ci/config/prow/openshift/ci-operator/roles.yaml
Labels: approved, lgtm, size/M

#1270 Add scripts to run the generator and a presubmit for it
  ci-operator/jobs/openshift/release/openshift-release-presubmits.yaml
  hack/update-generated-config.sh
  hack/validate-generated-config.sh
Labels: approved, lgtm, size/M

#1271 Add a new full run of the presubmits and change the e2e-aws focus
  ci-operator/jobs/openshift/installer/openshift-installer-presubmits.yaml
Labels: approved, lgtm, size/M

#1272 Allow ci-operator to create imagestream tags in the output ns
  cluster/ci/config/prow/openshift/ci-operator/roles.yaml
Labels: approved, lgtm, size/XS

#1273 Make generator presubmit report but not run
  ci-operator/jobs/openshift/release/openshift-release-presubmits.yaml
Labels: approved, lgtm, size/XS

#1276 Change e2e test context name
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-presubmits.yaml
Labels: approved, lgtm, size/XS

#1214 hook jenkins job for aws-actuator
  ci-operator/config/openshift/cluster-api-provider-aws/OWNERS
  ci-operator/jobs/openshift/cluster-api-provider-aws/OWNERS
  ci-operator/jobs/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/M

#1278 split unit tests and image build
  ci-operator/jobs/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-presubmits.yaml
Labels: approved, lgtm, size/S

#1275 OSA sync image in e2e
  ci-operator/templates/cluster-launch-e2e-azure.yaml
Labels: approved, lgtm, sig/azure, size/XS

#1280 include gcc in azure test image
  projects/azure/base-images/test-base.yaml
Labels: size/XS

#1281 fix typo in cluster-api-provider-aws repo name
  ci-operator/jobs/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-postsubmits.yaml
Labels: approved, lgtm, size/XS

#1282 e2e-aws-all cluster info also has to be scoped
  ci-operator/jobs/openshift/installer/openshift-installer-presubmits.yaml
Labels: approved, lgtm, size/XS

#1274 cluster-launch-installer-e2e: remove etcd nodes
  cluster/test-deploy/aws/openshift.yaml
Labels: approved, lgtm, size/M

#1284 Revert "cluster-launch-installer-e2e: remove etcd nodes"
  cluster/test-deploy/aws/openshift.yaml
Labels: size/M

#1283 openshift-installer-presubmits: Add go-fmt
  ci-operator/jobs/openshift/installer/openshift-installer-presubmits.yaml
Labels: approved, lgtm, size/S

#1286 Storage class should be delete, not retain
  cluster/test-deploy/gcp-crio-dev/vars-origin.yaml
  cluster/test-deploy/gcp-crio/vars-origin.yaml
  cluster/test-deploy/gcp-dev-ha-static/vars-origin.yaml
  cluster/test-deploy/gcp-dev-ha/vars-origin.yaml
  cluster/test-deploy/gcp-dev/vars-origin.yaml
  cluster/test-deploy/gcp-ha-static/vars-origin.yaml
  cluster/test-deploy/gcp-ha/vars-origin.yaml
  cluster/test-deploy/gcp/vars-origin.yaml
Labels: approved, lgtm, size/S

#1287 Do not run ci/prow/generated-config on '/test all'
  ci-operator/jobs/openshift/release/openshift-release-presubmits.yaml
Labels: approved, lgtm, size/XS

#1291 include systemd-devel in azure test image
  projects/azure/base-images/test-base.yaml
Labels: sig/azure, size/XS

#1290 Revert "Revert "cluster-launch-installer-e2e: remove etcd nodes""
  cluster/test-deploy/aws/.gitignore
  cluster/test-deploy/aws/OWNERS
  cluster/test-deploy/aws/openshift.yaml
Labels: approved, lgtm, size/M

#1293 OSA: add aad vars
  ci-operator/templates/cluster-launch-e2e-azure.yaml
Labels: lgtm, sig/azure, size/XS

#1300 Build 'determinize-prow-config' image for ci-operator-prowgen
  ci-operator/config/openshift/ci-operator-prowgen/master.json
Labels: approved, lgtm, size/S

#1302 Provide better copy for openshift/release Prow config format checker
  hack/validate-prow-job-ordering.sh
Labels: approved, lgtm, size/S

#1303 More friendly error messages for users
  hack/validate-generated-config.sh
  hack/validate-prow-job-ordering.sh
Labels: approved, lgtm, size/S

#1305 Exit with an error when generated jobs are wrong
  hack/validate-generated-config.sh
Labels: approved, lgtm, size/XS

#1306 Require approval for merges in openshift/api
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/XS

#1309 Point to the correct bucket in Gubernator links
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm

#1311 Fix tide configuration mistakes
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/S

#1316 azure: give PR authors access to namespace
  ci-operator/jobs/openshift/azure-misc/OWNERS
  ci-operator/jobs/openshift/azure-misc/openshift-azure-misc-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/OWNERS
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/S

#1318 update roles for events.
  cluster/ci/config/prow/openshift/ci-operator/roles.yaml
Labels: approved, lgtm, size/S

#1315 Remove `tools/ci-operator-prowgen
  tools/ci-operator-prowgen/Gopkg.lock
  tools/ci-operator-prowgen/Gopkg.toml
  tools/ci-operator-prowgen/README.md
  tools/ci-operator-prowgen/main.go
  tools/ci-operator-prowgen/main_test.go
Labels: approved, lgtm, size/XXL

#1289 openshift-installer-presubmits: Run go-lint on cmd/... and pkg/...
  ci-operator/config/openshift/installer/master.json
  ci-operator/jobs/openshift/installer/openshift-installer-presubmits.yaml
Labels: approved, lgtm, size/XS

#1320 Use nodes as infra instead of master
  cluster/test-deploy/gcp-crio-dev/vars-origin.yaml
  cluster/test-deploy/gcp-crio-dev/vars.yaml
  cluster/test-deploy/gcp-crio/vars-origin.yaml
  cluster/test-deploy/gcp-crio/vars.yaml
  cluster/test-deploy/gcp-dev-ha-static/vars-origin.yaml
  cluster/test-deploy/gcp-dev-ha-static/vars.yaml
  cluster/test-deploy/gcp-dev-ha/vars-origin.yaml
  cluster/test-deploy/gcp-dev-ha/vars.yaml
  cluster/test-deploy/gcp-dev/vars-origin.yaml
  cluster/test-deploy/gcp-dev/vars.yaml
  cluster/test-deploy/gcp-ha-static/vars-origin.yaml
  cluster/test-deploy/gcp-ha-static/vars.yaml
  cluster/test-deploy/gcp-ha/vars-origin.yaml
  cluster/test-deploy/gcp-ha/vars.yaml
  cluster/test-deploy/gcp/vars-origin.yaml
  cluster/test-deploy/gcp/vars.yaml
Labels: approved, lgtm, size/M

#1292 OSA: move to rhel image testing
  ci-operator/templates/cluster-launch-e2e-azure.yaml
Labels: approved, lgtm, sig/azure, size/XS

#1319 Run the re-tester on everything
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm, size/XS

#1312 Enable strict configuration validation
  ci-operator/jobs/openshift/release/openshift-release-presubmits.yaml
Labels: approved, lgtm, size/XS

#1322 Fix to compile from the correct branch job definition
  ci-operator/jobs/openshift/azure-misc/openshift-azure-misc-postsubmits-release-3.11.yaml
  ci-operator/jobs/openshift/azure-misc/openshift-azure-misc-presubmits-release-3.11.yaml
  ci-operator/jobs/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-postsubmits-release-3.11.yaml
  ci-operator/jobs/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-presubmits-release-3.11.yaml
  ci-operator/jobs/openshift/cluster-capacity/openshift-cluster-capacity-postsubmits-release-3.11.yaml
  ci-operator/jobs/openshift/cluster-capacity/openshift-cluster-capacity-presubmits-release-3.11.yaml
  ci-operator/jobs/openshift/cluster-monitoring-operator/openshift-cluster-monitoring-operator-postsubmits-release-3.11.yaml
  ci-operator/jobs/openshift/cluster-version-operator/openshift-cluster-version-operator-postsubmits-release-3.11.yaml
  ci-operator/jobs/openshift/cluster-version-operator/openshift-cluster-version-operator-presubmits-release-3.11.yaml
  ci-operator/jobs/openshift/console/openshift-console-postsubmits-release-3.11.yaml
  ci-operator/jobs/openshift/console/openshift-console-presubmits-release-3.11.yaml
  ci-operator/jobs/openshift/coredns/openshift-coredns-postsubmits-release-3.11.yaml
  ci-operator/jobs/openshift/coredns/openshift-coredns-presubmits-release-3.11.yaml
  ci-operator/jobs/openshift/descheduler/openshift-descheduler-postsubmits-release-3.11.yaml
  ci-operator/jobs/openshift/descheduler/openshift-descheduler-presubmits-release-3.11.yaml
  ci-operator/jobs/openshift/image-registry/openshift-image-registry-postsubmits-release-3.11.yaml
  ci-operator/jobs/openshift/image-registry/openshift-image-registry-presubmits-release-3.11.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-postsubmits-release-3.11.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-presubmits-release-3.11.yaml
  ci-operator/jobs/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-postsubmits-release-3.11.yaml
  ci-operator/jobs/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-presubmits-release-3.11.yaml
  ci-operator/jobs/openshift/kubernetes-metrics-server/openshift-kubernetes-metrics-server-postsubmits-release-3.11.yaml
  ci-operator/jobs/openshift/kubernetes-metrics-server/openshift-kubernetes-metrics-server-presubmits-release-3.11.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-postsubmits-release-3.11.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-presubmits-release-3.11.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-postsubmits-release-3.11.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-presubmits-release-3.11.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-postsubmits-release-3.11.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-presubmits-release-3.11.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-postsubmits-release-3.11.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-presubmits-release-3.11.yaml
  ci-operator/jobs/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-postsubmits-release-3.11.yaml
  ci-operator/jobs/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-presubmits-release-3.11.yaml
  ci-operator/jobs/openshift/origin-metrics/openshift-origin-metrics-postsubmits-release-3.11.yaml
  ci-operator/jobs/openshift/origin-metrics/openshift-origin-metrics-presubmits-release-3.11.yaml
  ci-operator/jobs/openshift/origin-web-console-server/openshift-origin-web-console-server-postsubmits-release-3.11.yaml
  ci-operator/jobs/openshift/origin-web-console-server/openshift-origin-web-console-server-presubmits-release-3.11.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-postsubmits-release-3.11.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-presubmits-release-3.11.yaml
  ci-operator/jobs/openshift/service-catalog/openshift-service-catalog-postsubmits-release-3.11.yaml
  ci-operator/jobs/openshift/service-catalog/openshift-service-catalog-presubmits-release-3.11.yaml
  ci-operator/jobs/openshift/service-serving-cert-signer/openshift-service-serving-cert-signer-postsubmits-release-3.11.yaml
  ci-operator/jobs/openshift/service-serving-cert-signer/openshift-service-serving-cert-signer-presubmits-release-3.11.yaml
  ci-operator/jobs/openshift/telemeter/openshift-telemeter-postsubmits-release-3.11.yaml
  ci-operator/jobs/openshift/telemeter/openshift-telemeter-presubmits-release-3.11.yaml
  hack/branch
  hack/lib/clone_jobs.py
Labels: approved, lgtm, size/L

#1325 Uncollapse mistakenly collapsed inline bash
  ci-operator/jobs/openshift/jenkins/openshift-jenkins-presubmits.yaml
Labels: approved, lgtm, size/S

#1313 Ignore comments in config-ordering checks
  ci-operator/jobs/openshift/installer/openshift-installer-presubmits.yaml
  hack/validate-prow-job-ordering.sh
Labels: approved, lgtm, size/XS, ¯\_(ツ)_/¯

#1285 populate-owners: Also slurp OWNERS_ALIASES
  OWNERS_ALIASES
  ci-operator/jobs/kubernetes-incubator/cri-o/OWNERS
  ci-operator/jobs/kubernetes-incubator/descheduler/OWNERS
  ci-operator/jobs/openshift-s2i/s2i-wildfly/OWNERS
  ci-operator/jobs/openshift/api/OWNERS
  ci-operator/jobs/openshift/autoheal/OWNERS
  ci-operator/jobs/openshift/azure-misc/OWNERS
  ci-operator/jobs/openshift/ci-ns-ttl-controller/OWNERS
  ci-operator/jobs/openshift/ci-operator-prowgen/OWNERS
  ci-operator/jobs/openshift/ci-operator/OWNERS
  ci-operator/jobs/openshift/ci-vm-operator/OWNERS
  ci-operator/jobs/openshift/cluster-api-provider-aws/OWNERS
  ci-operator/jobs/openshift/cluster-capacity/OWNERS
  ci-operator/jobs/openshift/cluster-dns-operator/OWNERS
  ci-operator/jobs/openshift/cluster-ingress-operator/OWNERS
  ci-operator/jobs/openshift/cluster-monitoring-operator/OWNERS
  ci-operator/jobs/openshift/cluster-samples-operator/OWNERS
  ci-operator/jobs/openshift/cluster-version-operator/OWNERS
  ci-operator/jobs/openshift/coredns/OWNERS
  ci-operator/jobs/openshift/descheduler/OWNERS
  ci-operator/jobs/openshift/image-registry/OWNERS
  ci-operator/jobs/openshift/installer/OWNERS
  ci-operator/jobs/openshift/jenkins-client-plugin/OWNERS
  ci-operator/jobs/openshift/jenkins-openshift-login-plugin/OWNERS
  ci-operator/jobs/openshift/jenkins-plugin/OWNERS
  ci-operator/jobs/openshift/jenkins-sync-plugin/OWNERS
  ci-operator/jobs/openshift/jenkins/OWNERS
  ci-operator/jobs/openshift/kube-state-metrics/OWNERS
  ci-operator/jobs/openshift/machine-api-operator/OWNERS
  ci-operator/jobs/openshift/machine-config-operator/OWNERS
  ci-operator/jobs/openshift/online-console-extensions/OWNERS
  ci-operator/jobs/openshift/online-hibernation/OWNERS
  ci-operator/jobs/openshift/online-registration/OWNERS
  ci-operator/jobs/openshift/openshift-ansible/OWNERS
  ci-operator/jobs/openshift/openshift-azure/OWNERS
  ci-operator/jobs/openshift/origin-aggregated-logging/OWNERS
  ci-operator/jobs/openshift/origin/OWNERS
  ci-operator/jobs/openshift/ose/OWNERS
  ci-operator/jobs/openshift/release/OWNERS
  ci-operator/jobs/openshift/service-catalog/OWNERS
  ci-operator/jobs/openshift/service-serving-cert-signer/OWNERS
  ci-operator/jobs/openshift/telemeter/OWNERS
  ci-operator/populate-owners.sh
  tools/populate-owners/OWNERS
  tools/populate-owners/README.md
  tools/populate-owners/main.go
  tools/populate-owners/main_test.go
Labels: approved, lgtm, size/XXL, ¯\_(ツ)_/¯

#1329 Revert "Add OWNERS for templates"
  ci-operator/templates/OWNERS
Labels: approved, lgtm, size/S, ¯\_(ツ)_/¯

#1327 tools/populate-owners: Also populate ci-operator/config/{org}/{repo}/OWNERS
  ci-operator/config/openshift/api/OWNERS
  ci-operator/config/openshift/azure-misc/OWNERS
  ci-operator/config/openshift/ci-operator-prowgen/OWNERS
  ci-operator/config/openshift/ci-operator/OWNERS
  ci-operator/config/openshift/cluster-api-provider-aws/OWNERS
  ci-operator/config/openshift/cluster-dns-operator/OWNERS
  ci-operator/config/openshift/cluster-ingress-operator/OWNERS
  ci-operator/config/openshift/cluster-monitoring-operator/OWNERS
  ci-operator/config/openshift/cluster-operator/OWNERS
  ci-operator/config/openshift/cluster-samples-operator/OWNERS
  ci-operator/config/openshift/cluster-version-operator/OWNERS
  ci-operator/config/openshift/image-registry/OWNERS
  ci-operator/config/openshift/installer/OWNERS
  ci-operator/config/openshift/jenkins/OWNERS
  ci-operator/config/openshift/kube-state-metrics/OWNERS
  ci-operator/config/openshift/machine-api-operator/OWNERS
  ci-operator/config/openshift/machine-config-operator/OWNERS
  ci-operator/config/openshift/openshift-ansible/OWNERS
  ci-operator/config/openshift/openshift-azure/OWNERS
  ci-operator/config/openshift/origin-aggregated-logging/OWNERS
  ci-operator/config/openshift/origin/OWNERS
  ci-operator/config/openshift/service-catalog/OWNERS
  ci-operator/config/openshift/service-serving-cert-signer/OWNERS
  ci-operator/config/openshift/telemeter/OWNERS
  ci-operator/jobs/kubernetes-incubator/cri-o/OWNERS
  ci-operator/jobs/openshift/api/OWNERS
  ci-operator/jobs/openshift/ci-operator/OWNERS
  ci-operator/jobs/openshift/cluster-api-provider-aws/OWNERS
  ci-operator/jobs/openshift/cluster-ingress-operator/OWNERS
  ci-operator/jobs/openshift/cluster-samples-operator/OWNERS
  ci-operator/jobs/openshift/installer/OWNERS
  ci-operator/jobs/openshift/jenkins-client-plugin/OWNERS
  ci-operator/jobs/openshift/jenkins-plugin/OWNERS
  ci-operator/jobs/openshift/machine-api-operator/OWNERS
  ci-operator/jobs/openshift/machine-config-operator/OWNERS
  ci-operator/jobs/openshift/online-registration/OWNERS
  ci-operator/jobs/openshift/openshift-ansible/OWNERS
  ci-operator/jobs/openshift/openshift-azure/OWNERS
  ci-operator/jobs/openshift/origin-aggregated-logging/OWNERS
  ci-operator/jobs/openshift/origin/OWNERS
  ci-operator/jobs/openshift/release/OWNERS
  tools/populate-owners/README.md
  tools/populate-owners/main.go
  tools/populate-owners/main_test.go
Labels: approved, lgtm, size/L

#1330 Add an issue template
  ISSUE_TEMPLATE.md
Labels: lgtm

#1331 Bump label_sync, add labels for openshift/release only
  ci-operator/jobs/infra-periodics.yaml
  cluster/ci/config/prow/labels.yaml
Labels: approved, lgtm, size/L

#1332 Use pod-utils on periodics
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm, size/M

#1333 Decorate last jobs
  ci-operator/jobs/openshift/release/openshift-release-presubmits.yaml
Labels: approved, lgtm, size/XS

#1324 move to dynamic images for OSA
  ci-operator/templates/cluster-launch-e2e-azure.yaml
Labels: lgtm, sig/azure, size/XS

#1323 osa - add secret rotation doc
  projects/azure/README.md
Labels: approved, lgtm, sig/azure, size/M

#1299 Add github.com/tnozicka/openshift-acme
  ci-operator/config/tnozicka/openshift-acme/OWNERS
  ci-operator/config/tnozicka/openshift-acme/master.json
  ci-operator/jobs/tnozicka/openshift-acme/OWNERS
  ci-operator/jobs/tnozicka/openshift-acme/manual-presubmits.yaml
  ci-operator/jobs/tnozicka/openshift-acme/tnozicka-openshift-acme-postsubmits.yaml
  ci-operator/jobs/tnozicka/openshift-acme/tnozicka-openshift-acme-presubmits.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L
