Repository openshift/release, pull requests merged in 2019-10, with the labels that each got.

#5222 Mirrors knative-client nightly built container image to quay
  core-services/image-mirroring/knative/OWNERS
  core-services/image-mirroring/knative/mapping_knative_nightly_quay
Labels: approved, lgtm, ok-to-test, size/XS

#5233 Add integreatly post submit e2e test.
  ci-operator/jobs/integr8ly/integreatly-operator/integr8ly-integreatly-operator-master-postsubmits.yaml
Labels: approved, lgtm, size/M

#5229 Add openshift/cluster-api 4.3 promotion for automated fast forward
  ci-operator/config/openshift/cluster-api/openshift-cluster-api-master.yaml
  ci-operator/jobs/openshift/cluster-api/openshift-cluster-api-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#5239 Rebuild must-gather on oc PRs
  ci-operator/config/openshift/oc/openshift-oc-master.yaml
Labels: approved, lgtm, size/S

#5238 Use image stream base image for build root
  ci-operator/config/integr8ly/integreatly-operator/integr8ly-integreatly-operator-master.yaml
Labels: approved, lgtm, size/XS

#5090 Use ubi 8 as base image for ironic
  ci-operator/config/openshift/ironic-image/openshift-ironic-image-release-4.3.yaml
Labels: approved, lgtm, size/S

#5242 Remove cluster stanza from image stream tag
  ci-operator/config/integr8ly/integreatly-operator/integr8ly-integreatly-operator-master.yaml
Labels: approved, lgtm, size/XS

#5232 Bug 1756298: use master-sidecar-4.3 to run image-registry integration tests
  ci-operator/jobs/openshift/image-registry/openshift-image-registry-master-presubmits.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#5241 Switching main job to 4.3 for ironic
  ci-operator/config/openshift/ironic-image/openshift-ironic-image-master.yaml
Labels: approved, lgtm, size/S

#5237 Add tekton catalog images
  ci-operator/config/openshift/tektoncd-catalog/openshift-tektoncd-catalog-release-next.yaml
  ci-operator/jobs/openshift/tektoncd-catalog/openshift-tektoncd-catalog-release-next-postsubmits.yaml
  ci-operator/jobs/openshift/tektoncd-catalog/openshift-tektoncd-catalog-release-next-presubmits.yaml
  core-services/image-mirroring/tekton/mapping_tekton_catalog_nightly_quay
Labels: approved, lgtm, size/L

#5245 core-services: Add coreos/rpm-ostree to Tide
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm, size/XS

#5185 operator-framework/operator-sdk: update make commands for e2e tests
  ci-operator/config/operator-framework/operator-sdk/operator-framework-operator-sdk-master.yaml
  ci-operator/config/operator-framework/operator-sdk/operator-framework-operator-sdk-release-4.2.yaml
  ci-operator/config/operator-framework/operator-sdk/operator-framework-operator-sdk-release-4.3.yaml
  ci-operator/config/operator-framework/operator-sdk/operator-framework-operator-sdk-release-4.4.yaml
  ci-operator/jobs/operator-framework/operator-sdk/operator-framework-operator-sdk-master-presubmits.yaml
  ci-operator/jobs/operator-framework/operator-sdk/operator-framework-operator-sdk-release-4.2-presubmits.yaml
  ci-operator/jobs/operator-framework/operator-sdk/operator-framework-operator-sdk-release-4.3-presubmits.yaml
  ci-operator/jobs/operator-framework/operator-sdk/operator-framework-operator-sdk-release-4.4-presubmits.yaml
Labels: approved, lgtm, size/M

#5250 Graduate canaries to release
  ci-operator/infra/openshift/release-controller/releases/release-ocp-4.2.json
  ci-operator/infra/openshift/release-controller/releases/release-ocp-4.3.json
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
Labels: approved, lgtm, size/L

#5178 Add red-hat-storage/ocs-ci e2e job to ocs-operator
  ci-operator/config/openshift/ocs-operator/openshift-ocs-operator-master.yaml
  ci-operator/config/openshift/ocs-operator/openshift-ocs-operator-release-4.2.yaml
  ci-operator/config/openshift/ocs-operator/openshift-ocs-operator-release-4.3.yaml
  ci-operator/config/openshift/ocs-operator/openshift-ocs-operator-release-4.4.yaml
  ci-operator/jobs/openshift/ocs-operator/openshift-ocs-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/ocs-operator/openshift-ocs-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/ocs-operator/openshift-ocs-operator-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/ocs-operator/openshift-ocs-operator-release-4.4-presubmits.yaml
Labels: approved, lgtm, size/L

#5251 prow: Use rebase merge method for rpm-ostree
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm, size/XS

#5240 Use ubi 8 as base image for ironic-inspector
  ci-operator/config/openshift/ironic-inspector-image/openshift-ironic-inspector-image-master.yaml
  ci-operator/config/openshift/ironic-inspector-image/openshift-ironic-inspector-image-release-4.3.yaml
Labels: approved, lgtm, size/S

#5249 projects/coreos: Really add OWNERS
  projects/coreos/OWNERS
Labels: approved, lgtm, size/S

#5256 cluster-api: base master on 4.3
  ci-operator/config/openshift/cluster-api/openshift-cluster-api-master.yaml
Labels: approved, lgtm, size/XS

#5257 controller-manager was renamed to kube-controller-manager in 4.3
  ci-operator/templates/master-sidecar-4.3.yaml
Labels: approved, lgtm, size/XS

#5253 Add runtime-utils to prow
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/XS

#5258 ci-operator: Run e2e suite after disruptive suite
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.1.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.2.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.3.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.4.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.4-presubmits.yaml
Labels: approved, lgtm, size/S

#5217 upgrade oper images to use ubi8
  ci-operator/config/operator-framework/operator-sdk/operator-framework-operator-sdk-master.yaml
  ci-operator/config/operator-framework/operator-sdk/operator-framework-operator-sdk-release-4.2.yaml
  ci-operator/config/operator-framework/operator-sdk/operator-framework-operator-sdk-release-4.4.yaml
Labels: approved, lgtm, size/S

#4989 add release-v1.3.x branch for kie-cloud-operator
  ci-operator/config/kiegroup/kie-cloud-operator/kiegroup-kie-cloud-operator-release-v1.3.x.yaml
  ci-operator/jobs/kiegroup/kie-cloud-operator/kiegroup-kie-cloud-operator-release-v1.3.x-postsubmits.yaml
  ci-operator/jobs/kiegroup/kie-cloud-operator/kiegroup-kie-cloud-operator-release-v1.3.x-presubmits.yaml
Labels: approved, lgtm, size/L

#5260 Determinize periodic jobs
  ci-operator/jobs/cri-o/cri-o/cri-o-cri-o-periodics.yaml
  ci-operator/jobs/openshift/cluster-autoscaler-operator/openshift-cluster-autoscaler-operator-periodics.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-periodics.yaml
  ci-operator/jobs/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-periodics.yaml
  ci-operator/jobs/openshift/library/openshift-library-periodics.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-periodics.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.1-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
  ci-operator/jobs/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-periodics.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-periodics.yaml
  ci-operator/jobs/redhat-cop/org/redhat-cop-org-periodics.yaml
Labels: approved, lgtm, sig/azure, size/XL

#5266 ci-operator: Set release informing labels
  ci-operator/jobs/openshift/release/openshift-release-release-4.1-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
Labels: approved, size/L

#5268 ci-operator: Run ssh bastion in a non openshift-* namespace
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
Labels: approved, lgtm, size/XS

#5270 ci-operator: Fix bastion script error
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
Labels: approved, lgtm, size/XS

#5274 Update periodic filenames
  ci-operator/jobs/cri-o/cri-o/cri-o-cri-o-master-periodics.yaml
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/cluster-autoscaler-operator/openshift-cluster-autoscaler-operator-master-periodics.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.6.0-periodics.yaml
  ci-operator/jobs/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-periodics.yaml
  ci-operator/jobs/openshift/library/openshift-library-master-periodics.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-infra-periodics.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-periodics.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-master-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-infra-periodics.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
  ci-operator/jobs/redhat-cop/org/redhat-cop-org-master-periodics.yaml
  core-services/prow/02_config/_plugins.yaml
  core-services/prow/03_deployment/deck.yaml
  core-services/prow/03_deployment/hook.yaml
  core-services/prow/03_deployment/horologium.yaml
  core-services/prow/03_deployment/jenkins_operator.yaml
  core-services/prow/03_deployment/plank.yaml
  core-services/prow/03_deployment/sinker.yaml
  core-services/prow/03_deployment/statusreconciler.yaml
  core-services/prow/03_deployment/tide.yaml
  core-services/prow/03_deployment/tot.yaml
Labels: approved, lgtm, sig/azure, size/XL

#5275 Fix label_sync graphql parameter
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm, size/XS

#5272 Increasing the requests for Image Registry tests.
  ci-operator/config/openshift/image-registry/openshift-image-registry-release-4.3.yaml
Labels: approved, lgtm, size/XS

#4936 cincinnati: add rustfmt test
  ci-operator/config/openshift/cincinnati/openshift-cincinnati-master.yaml
  ci-operator/jobs/openshift/cincinnati/openshift-cincinnati-master-presubmits.yaml
Labels: approved, lgtm, size/L

#5263 config: Add an rpm-ostree prow job
  ci-operator/config/coreos/rpm-ostree/OWNERS
  ci-operator/config/coreos/rpm-ostree/coreos-rpm-ostree-master.yaml
  ci-operator/jobs/coreos/rpm-ostree/OWNERS
  ci-operator/jobs/coreos/rpm-ostree/coreos-rpm-ostree-master-presubmits.yaml
Labels: approved, lgtm, size/L

#5279 Bump memory limits for image-registry integration tests
  ci-operator/config/openshift/image-registry/openshift-image-registry-master.yaml
  ci-operator/config/openshift/image-registry/openshift-image-registry-release-4.3.yaml
  ci-operator/config/openshift/image-registry/openshift-image-registry-release-4.4.yaml
Labels: approved, lgtm, size/S

#5284 enable tide merge automation for openshift/kube-storage-version-migrator
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/XS

#5283 enable ci for openshift/kube-storage-version-migrator
  core-services/prow/02_config/_plugins.yaml
Labels: size/XS

#5278 SDAR-33. Add osde2e secrets.
  core-services/secret-mirroring/_mapping.yaml
Labels: approved, lgtm, size/XS

#5281 remove y-cote, pweil- from azure team
  projects/azure/OWNERS
  projects/azure/cluster-wide.yaml
Labels: approved, lgtm, sig/azure, size/XS

#5287 chat-bot/release-controller: Update job-config mounts
  ci-operator/infra/openshift/release-controller/deploy-ocp-controller.yaml
  ci-operator/infra/openshift/release-controller/deploy-origin-controller.yaml
  core-services/ci-chat-bot/deploy.yaml
Labels: approved, lgtm, size/L

#5288 ci-operator: bump azure/gcp upgrade jobs to 4h
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
Labels: approved, lgtm, size/XS

#5289 bump openshift/router to go-1.12
  ci-operator/config/openshift/router/openshift-router-master.yaml
  ci-operator/config/openshift/router/openshift-router-release-4.3.yaml
  ci-operator/config/openshift/router/openshift-router-release-4.4.yaml
Labels: approved, lgtm, size/XS

#5244 Add jobs handling non-core services config
  ci-operator/config/openshift/release/openshift-release-master.yaml
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
Labels: approved, lgtm, size/L

#5291 Allow top-level OWNERS to /override
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/XS

#5292 Add support for azure and gcp on custom template
  ci-operator/templates/openshift/installer/cluster-launch-installer-custom-test-image.yaml
Labels: approved, lgtm, size/M

#5293 Bring custom template in sync with others
  ci-operator/templates/openshift/installer/cluster-launch-installer-custom-test-image.yaml
Labels: approved, lgtm, size/L

#5276 Setup CI job for Tektoncd Pipeline release v0.7.0
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.7.0.yaml
  ci-operator/jobs/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.7.0-postsubmits.yaml
  ci-operator/jobs/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.7.0-presubmits.yaml
Labels: approved, lgtm, size/L

#5294 Add quay image mirroring map
  core-services/image-mirroring/tekton/mapping_tekton_v0_7_quay
Labels: approved, lgtm, size/S

#5296 Fixes image mirroring
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.7.0.yaml
Labels: approved, lgtm, size/XS

#5299 Debug image mirroring for Tekton Pipeline
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.7.0.yaml
Labels: approved, lgtm, size/XS

#5300 Update PR jobs to use the disruptive test, 4.2 and older are optional
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.2.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.3.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.4.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-master.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.1.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.2.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.3.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.4.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.4-presubmits.yaml
Labels: approved, lgtm, size/XXL

#5301 Update secret mirroring key name
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/XS

#5305 Use 4.3 CLI in CI jobs
  ci-operator/infra/openshift/release-controller/releases/release-ocp-4.y-stable.json
Labels: approved, lgtm, size/XS

#5303 Disruptive tests are still optional on some repos
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.4-presubmits.yaml
Labels: approved, lgtm, size/S

#5264 Deploy prow-exporter
  cluster/ci/monitoring/Makefile
  cluster/ci/monitoring/exporter_service_monitor.yaml
  core-services/prow/03_deployment/admin_exporter_rbac.yaml
  core-services/prow/03_deployment/exporter.yaml
Labels: approved, lgtm, size/L

#5304 Add disruptive release informing job
  ci-operator/infra/openshift/release-controller/releases/release-ocp-4.1-ci.json
  ci-operator/infra/openshift/release-controller/releases/release-ocp-4.1.json
  ci-operator/infra/openshift/release-controller/releases/release-ocp-4.2-ci.json
  ci-operator/infra/openshift/release-controller/releases/release-ocp-4.2.json
  ci-operator/infra/openshift/release-controller/releases/release-ocp-4.3-ci.json
  ci-operator/infra/openshift/release-controller/releases/release-ocp-4.3.json
  ci-operator/jobs/openshift/release/openshift-release-release-4.1-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
Labels: approved, lgtm, size/L

#5306 Use golang 1.12 for mdns-publisher testing
  ci-operator/config/openshift/mdns-publisher/openshift-mdns-publisher-master.yaml
  ci-operator/config/openshift/mdns-publisher/openshift-mdns-publisher-release-4.2.yaml
  ci-operator/config/openshift/mdns-publisher/openshift-mdns-publisher-release-4.3.yaml
  ci-operator/config/openshift/mdns-publisher/openshift-mdns-publisher-release-4.4.yaml
Labels: approved, lgtm, size/XS

#5307 Adding config updater support for release controller development
  core-services/prow/02_config/_plugins.yaml
  core-services/prow/03_deployment/admin_config_updater_rbac.yaml
Labels: approved, lgtm, size/M

#5273 Update jenkins-agent-nodejs-8 to nodejs-10
  ci-operator/config/openshift/jenkins/openshift-jenkins-master.yaml
  ci-operator/config/openshift/jenkins/openshift-jenkins-release-4.3.yaml
  ci-operator/config/openshift/jenkins/openshift-jenkins-release-4.4.yaml
Labels: approved, lgtm, size/XS

#5317 Adding new namespaces for release controller testing environment
  services/release-controller-test/OWNERS
  services/release-controller-test/README.md
  services/release-controller-test/admin_01_ns.yaml
Labels: approved, lgtm, size/S

#5318 add configmaps rbacs for sinker sa
  core-services/prow/03_deployment/admin_sinker_rbac.yaml
Labels: approved, lgtm, size/XS

#5319 sinker rbac fix
  core-services/prow/03_deployment/admin_sinker_rbac.yaml
Labels: approved, lgtm, size/S

#5320 add watch/get verbs on sinker rbacs for prowjobs
  core-services/prow/03_deployment/admin_sinker_rbac.yaml
Labels: approved, lgtm, size/XS

#5321 ci-tools: build ci-operator-configresolver
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
Labels: approved, lgtm, size/XS

#5123 ci-operator/config: operator-courier integration
  ci-operator/config/operator-framework/operator-courier/OWNERS
  ci-operator/config/operator-framework/operator-courier/operator-framework-operator-courier-master.yaml
  ci-operator/jobs/operator-framework/operator-courier/OWNERS
  ci-operator/jobs/operator-framework/operator-courier/operator-framework-operator-courier-master-presubmits.yaml
Labels: approved, lgtm, size/L

#5322 core-services: add ci-operator-configresolver
  core-services/ci-operator-configresolver/OWNERS
  core-services/ci-operator-configresolver/README.md
  core-services/ci-operator-configresolver/ci-operator-configresolver.yaml
Labels: approved, lgtm, size/L

#5323 add all architects + group leads as ci job approvers
  ci-operator/config/OWNERS
  ci-operator/jobs/OWNERS
Labels: approved, lgtm, size/S

#5326 core-services: bump replicas of ci-operator-configresolver to 3
  core-services/ci-operator-configresolver/ci-operator-configresolver.yaml
Labels: approved, lgtm, size/XS

#5328 Add periodic job to run Knative Serving on vSphere.
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-v0.8.1-periodics.yaml
Labels: approved, lgtm, size/M

#5332 config-updater: create role and rolebinding for promecieus
  core-services/prow/03_deployment/admin_config_updater_rbac.yaml
Labels: approved, lgtm, size/M

#5333 config-updater rbac: fix apigroups for promecieus dcs
  core-services/prow/03_deployment/admin_config_updater_rbac.yaml
Labels: approved, lgtm, size/S

#5331 services: add promecieus
  services/promecieus/02-imagestream.yaml
  services/promecieus/03-buildconfig-src.yaml
  services/promecieus/04-buildconfig-bin.yaml
  services/promecieus/05-deploymentconfig.yaml
  services/promecieus/06-service.yaml
  services/promecieus/07-route.yaml
  services/promecieus/08-serviceaccount.yaml
  services/promecieus/09-role.yaml
  services/promecieus/10-rolebinding.yaml
  services/promecieus/11-config-updater-rolebinding.yaml
  services/promecieus/12-vrutkovs-rolebinding.yaml
  services/promecieus/OWNERS
  services/promecieus/README.md
  services/promecieus/admin_01_namespace.yaml
Labels: approved, lgtm, size/L

#5335 Promecieus: add resource quota to limit a number of created instances
  services/promecieus/13-resource-quota.yaml
Labels: approved, lgtm, size/XS

#5336 ci-operator/../telemeter: Adjust telemeter CI for generate
  ci-operator/config/openshift/telemeter/openshift-telemeter-release-4.1.yaml
  ci-operator/jobs/openshift/telemeter/openshift-telemeter-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/telemeter/openshift-telemeter-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/telemeter/openshift-telemeter-release-4.3-presubmits.yaml
Labels: approved, lgtm, size/L

#5337 Allow changing resourcequota for config-updater in promecieus
  core-services/prow/03_deployment/admin_config_updater_rbac.yaml
Labels: approved, lgtm, size/XS

#5338 ci-operator/jobs/openshift/telemeter: Add release version to name
  ci-operator/jobs/openshift/telemeter/openshift-telemeter-master-presubmits.yaml
  ci-operator/jobs/openshift/telemeter/openshift-telemeter-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/telemeter/openshift-telemeter-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/telemeter/openshift-telemeter-release-4.3-presubmits.yaml
Labels: approved, lgtm, size/L

#5202 SDAR-33. Intro osde2e jobs.
  ci-operator/config/openshift/osde2e/OWNERS
  ci-operator/config/openshift/osde2e/openshift-osde2e-master.yaml
  ci-operator/jobs/openshift/osde2e/OWNERS
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-master-periodics.yaml
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-master-presubmits.yaml
Labels: approved, lgtm, size/L

#5339 add openshift/cluster-policy-controller to prow config
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm, size/XS

#5325 Add pannels/alerts for plank-job-with-infra-role
  cluster/ci/monitoring/mixins/grafana_dashboards/dptp.jsonnet
  cluster/ci/monitoring/mixins/grafana_dashboards_out/dptp.json
  cluster/ci/monitoring/mixins/prometheus/dptp_alerts.libsonnet
  cluster/ci/monitoring/mixins/prometheus_out/prometheus_rule_prow.yaml
Labels: approved, lgtm, size/L

#5340 ci-operator/jobs/openshift/telemeter: Change command to test-generate
  ci-operator/jobs/openshift/telemeter/openshift-telemeter-release-4.1-presubmits.yaml
Labels: approved, lgtm, size/XS

#5334 Generate periodic vsphere job for Knative.
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-v0.8.1__vsphere.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-v0.8.1-periodics.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-v0.8.1-presubmits.yaml
Labels: approved, lgtm, size/L

#5314 Fix golang 1.13 RPM and add its image to the pipeline.
  projects/origin-release/golang-1.13/golang-v1.13.0-1.noarch.rpm
  projects/origin-release/pipeline.yaml
Labels: approved, lgtm, size/M

#5302 Adding a release controller test environment
  core-services/secret-mirroring/_mapping.yaml
  services/release-controller-test/admin_02_rbac.yaml
  services/release-controller-test/deploy.yaml
Labels: approved, lgtm, size/L

#5342 jobs/cluster-version-operator: update integration to use 4.3 sidecar
  ci-operator/jobs/openshift/cluster-version-operator/openshift-cluster-version-operator-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#5343 SDAR-48: Add 4.2-4.2 osde2e periodics
  ci-operator/config/openshift/osde2e/openshift-osde2e-master.yaml
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-master-periodics.yaml
Labels: approved, lgtm, size/L

#5267 Add a test for spinning up OVN Kubernetes Cluster
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-master.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.2.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.3.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.4.yaml
  ci-operator/jobs/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.4-presubmits.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
Labels: approved, lgtm, size/L

#5348 Remove BP config for kubernetes-incubator/descheduler
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm, size/XS

#5347 Add grafana dashboard to ci-operator-configresolver
  cluster/ci/monitoring/mixins/Makefile
  cluster/ci/monitoring/mixins/config.libsonnet
  cluster/ci/monitoring/mixins/grafana_dashboards/configresolver.jsonnet
  cluster/ci/monitoring/mixins/grafana_dashboards_out/configresolver.json
Labels: approved, lgtm, size/XL

#5341 Use jsonnet for alertmanager.yaml
  cluster/ci/monitoring/Makefile
  cluster/ci/monitoring/README.md
  cluster/ci/monitoring/alertmanager.yaml
  cluster/ci/monitoring/mixins/Makefile
  cluster/ci/monitoring/mixins/config.libsonnet
  cluster/ci/monitoring/mixins/prometheus/alertmanager.jsonnet
  cluster/ci/monitoring/mixins/prometheus/alertmanager.libsonnet
  cluster/ci/monitoring/mixins/prometheus/alertmanager_default_receivers.libsonnet
  cluster/ci/monitoring/mixins/prometheus/alertmanager_other_receivers.libsonnet
  cluster/ci/monitoring/mixins/prometheus/alertmanager_routes.libsonnet
  cluster/ci/monitoring/mixins/prometheus/build_cop_alerts.libsonnet
  cluster/ci/monitoring/mixins/prometheus/job_failures_alerts.libsonnet
  cluster/ci/monitoring/mixins/prometheus/job_failures_config.libsonnet
  cluster/ci/monitoring/mixins/prometheus/prometheus.libsonnet
  cluster/ci/monitoring/mixins/prometheus_out/alertmanager.yaml
  cluster/ci/monitoring/mixins/prometheus_out/prometheus_rule_prow.yaml
Labels: approved, lgtm, size/L

#5349 Fix alermanager's config file
  cluster/ci/monitoring/mixins/prometheus/alertmanager.jsonnet
  cluster/ci/monitoring/mixins/prometheus/alertmanager_routes.libsonnet
  cluster/ci/monitoring/mixins/prometheus_out/alertmanager.yaml
Labels: approved, lgtm, size/XS

#5350 osde2e upgrade jobs should match up to testgrid prefix
  ci-operator/config/openshift/osde2e/openshift-osde2e-master.yaml
Labels: approved, lgtm, size/XS

#5316 Make openstack repos for 4.3 use osp16
  ci-operator/infra/openshift/release-controller/repos/ocp-4.3-openstack.repo
Labels: approved, lgtm, size/XS

#5353 Add a new new image build spec to openshift/tektoncd-pipeline config
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-next.yaml
  core-services/image-mirroring/tekton/mapping_tekton_v0_7_quay
Labels: approved, lgtm, size/XS

#5358 Add a new new image build spec to openshift/tektoncd-pipeline config
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.7.0.yaml
Labels: approved, lgtm, size/XS

#5355 Switch ironic images to osp16 based repos
  ci-operator/config/openshift/ironic-image/openshift-ironic-image-master.yaml
  ci-operator/config/openshift/ironic-image/openshift-ironic-image-release-4.3.yaml
  ci-operator/config/openshift/ironic-image/openshift-ironic-image-release-4.4.yaml
  ci-operator/config/openshift/ironic-inspector-image/openshift-ironic-inspector-image-master.yaml
  ci-operator/config/openshift/ironic-inspector-image/openshift-ironic-inspector-image-release-4.3.yaml
  ci-operator/config/openshift/ironic-inspector-image/openshift-ironic-inspector-image-release-4.4.yaml
Labels: approved, lgtm, size/S

#5134 Add e2e-gcp-upi
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
Labels: approved, lgtm, size/L

#5363 Adding another secret for secret mirroring
  core-services/secret-mirroring/_mapping.yaml
  services/release-controller-test/deploy.yaml
Labels: approved, lgtm, size/S

#5351 SDAR-57. Adjust roles and tide config for osde2e.
  cluster/ci/config/roles.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/XS

#5366 Add CI to Knative Serving 0.9.0 release branch.
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-v0.9.0.yaml
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-v0.9.0__variant.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-v0.9.0-postsubmits.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-v0.9.0-presubmits.yaml
Labels: approved, lgtm, size/XL

#5357 Add job name into deck URL for infra job alerts
  cluster/ci/monitoring/mixins/prometheus/dptp_alerts.libsonnet
  cluster/ci/monitoring/mixins/prometheus_out/prometheus_rule_prow.yaml
Labels: approved, lgtm, size/XS

#5364 Add integr8ly/installation to CI.
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/M

#5370 Remove infra label from job periodic-owners-check
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm, size/XS

#5247 coreos: Copy project, team structure from metering/, add cosa buildroot
  core-services/prow/03_deployment/admin_config_updater_rbac.yaml
  projects/coreos/coreos.yaml
  services/coreos/OWNERS
  services/coreos/README.md
  services/coreos/admin_group.yaml
  services/coreos/admin_project.yaml
  services/coreos/admin_rbac.yaml
  services/coreos/cosa-buildroot.yaml
  services/coreos/cosa-upstream-is.yaml
Labels: approved, lgtm, size/L

#5312 Drop verify-deps in ks-o 4.3 since we're switching to go.mod
  ci-operator/config/openshift/cluster-kube-scheduler-operator/openshift-cluster-kube-scheduler-operator-master.yaml
  ci-operator/jobs/openshift/cluster-kube-scheduler-operator/openshift-cluster-kube-scheduler-operator-master-presubmits.yaml
Labels: approved, lgtm, size/M

#5313 Drop verify-deps in kcm-o 4.3 since we're switching to go.mod
  ci-operator/config/openshift/cluster-kube-controller-manager-operator/openshift-cluster-kube-controller-manager-operator-master.yaml
  ci-operator/jobs/openshift/cluster-kube-controller-manager-operator/openshift-cluster-kube-controller-manager-operator-master-presubmits.yaml
Labels: approved, lgtm, size/M

#5380 Let deck create ProwJobs for reruns
  core-services/prow/03_deployment/admin_deck_rbac.yaml
Labels: approved, lgtm, size/XS

#5381 Import the golang-1.13 tag as well
  projects/origin-stable/release.yaml
Labels: approved, lgtm, size/XS

#5377 Updating to a much newer version of GO
  ci-operator/config/openshift/release-controller/openshift-release-controller-master.yaml
Labels: approved, lgtm, size/XS

#5261 Add CI tests for openshift/runtime-utils repo
  ci-operator/config/openshift/runtime-utils/OWNERS
  ci-operator/config/openshift/runtime-utils/openshift-runtime-utils-master.yaml
  ci-operator/jobs/openshift/runtime-utils/OWNERS
  ci-operator/jobs/openshift/runtime-utils/openshift-runtime-utils-master-presubmits.yaml
Labels: approved, lgtm, size/L

#5315 ARO - Add API testing
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/M

#5385 core-services: Update prow plugins config to set configs for metering feature branch jobs
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/XS

#5378 onboard toolchain-operator
  ci-operator/config/codeready-toolchain/toolchain-operator/OWNERS
  ci-operator/config/codeready-toolchain/toolchain-operator/codeready-toolchain-toolchain-operator-master.yaml
  ci-operator/jobs/codeready-toolchain/toolchain-operator/OWNERS
  ci-operator/jobs/codeready-toolchain/toolchain-operator/codeready-toolchain-toolchain-operator-master-postsubmits.yaml
  ci-operator/jobs/codeready-toolchain/toolchain-operator/codeready-toolchain-toolchain-operator-master-presubmits.yaml
  core-services/image-mirroring/codeready-toolchain/mapping_codeready_toolchain_v0_1_quay
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/XL

#5371 ocs-operator: Nightly images
  ci-operator/config/openshift/ocs-operator/openshift-ocs-operator-master.yaml
  ci-operator/config/openshift/ocs-operator/openshift-ocs-operator-release-4.2.yaml
  ci-operator/config/openshift/ocs-operator/openshift-ocs-operator-release-4.3.yaml
  ci-operator/config/openshift/ocs-operator/openshift-ocs-operator-release-4.4.yaml
  ci-operator/jobs/openshift/ocs-operator/openshift-ocs-operator-master-periodics.yaml
Labels: approved, lgtm, size/L

#5390 Uses only 4.2 jobs for knative-client release-next
  ci-operator/config/openshift/knative-client/openshift-knative-client-release-next.yaml
  ci-operator/config/openshift/knative-client/openshift-knative-client-release-next__variant.yaml
  ci-operator/jobs/openshift/knative-client/openshift-knative-client-release-next-postsubmits.yaml
  ci-operator/jobs/openshift/knative-client/openshift-knative-client-release-next-presubmits.yaml
Labels: approved, lgtm, size/L

#5372 ocs-operator: Add davidvossel to OWNERS
  ci-operator/config/openshift/ocs-operator/OWNERS
  ci-operator/jobs/openshift/ocs-operator/OWNERS
Labels: approved, lgtm, size/XS

#5383 ci-operator: Add ci-operator config that tests feature branches
  ci-operator/config/operator-framework/operator-metering/operator-framework-operator-metering-feature.yaml
  ci-operator/jobs/operator-framework/operator-metering/operator-framework-operator-metering-feature-presubmits.yaml
Labels: approved, lgtm, size/L

#5394 Add the e2e-openstack-* jobs to release-4.2
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.2-presubmits.yaml
Labels: approved, lgtm, size/L

#5398 Build ci-tools with go-1.13
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
Labels: approved, lgtm, size/XS

#5399 Upgrade to go1.13 in ci-tools' build_root
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
Labels: approved, lgtm, size/XS

#5400 Enable goose plugin for openshift
  ci-operator/populate-secrets-from-bitwarden.sh
  core-services/prow/02_config/_plugins.yaml
  core-services/prow/03_deployment/hook.yaml
Labels: approved, lgtm, size/S

#5397 SDCICD-31. Write junit.xml files into artifact directory.
  ci-operator/config/openshift/osde2e/openshift-osde2e-master.yaml
Labels: approved, lgtm, size/XS

#5402 Add upgrade-minor jobs
  ci-operator/infra/openshift/release-controller/releases/release-ocp-4.2-ci.json
  ci-operator/infra/openshift/release-controller/releases/release-ocp-4.2.json
  ci-operator/infra/openshift/release-controller/releases/release-ocp-4.3-ci.json
  ci-operator/infra/openshift/release-controller/releases/release-ocp-4.3.json
  ci-operator/infra/openshift/release-controller/releases/release-ocp-4.y-stable.json
Labels: approved, lgtm, size/S

#5403 osde2e prod 4.2 -> 4.2 upgrades disabled.
  ci-operator/config/openshift/osde2e/openshift-osde2e-master.yaml
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-master-periodics.yaml
Labels: approved, lgtm, size/M

#5404 Prepare for monitor split
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm, size/S

#5361 Bug 1759299: Fix RHEL7 workers release job
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#5406 Add a mapping file for knative 0.9 images.
  core-services/image-mirroring/knative/mapping_knative_v0_9_quay
Labels: approved, lgtm, size/XS

#5356 Use new `default_decoration_configs` stanza in Plank config
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm, size/M

#5345 Add e2e-olm test target
  ci-operator/config/integr8ly/integreatly-operator/integr8ly-integreatly-operator-master.yaml
  ci-operator/jobs/integr8ly/integreatly-operator/integr8ly-integreatly-operator-master-presubmits.yaml
Labels: approved, lgtm, size/M

#5389 Set up image mirroring for ocs-operator nightly images
  ci-operator/jobs/infra-image-mirroring.yaml
  core-services/image-mirroring/README.md
  core-services/image-mirroring/ocs-operator/OWNERS
  core-services/image-mirroring/ocs-operator/mapping_ocs-operator_quay
  core-services/secret-mirroring/_mapping.yaml
Labels: approved, lgtm, size/M

#5405 fix oc client path on 4.2 to 4.3 upgrade periodic job
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
Labels: approved, lgtm, size/XS

#5073 Update multitenant test jobs, add multitenant and ovn-kubernetes tests to origin
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
  ci-operator/jobs/openshift/sdn/openshift-sdn-master-presubmits.yaml
Labels: approved, lgtm, size/L

#5409 Ensure skew test for 4.2->4.3 uses the right source
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
Labels: approved, lgtm, size/XS

#5411 promecieus: promecieus-robot should be able to read resourcequotas
  services/promecieus/09-role.yaml
Labels: approved, lgtm, size/XS

#5412 Allow approving reviews to act as approval and LGTM
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/XS

#5392 Onboard ostreedev/ostree to Prow
  ci-operator/config/ostreedev/ostree/OWNERS
  ci-operator/config/ostreedev/ostree/ostreedev-ostree-master.yaml
  ci-operator/jobs/ostreedev/ostree/OWNERS
  ci-operator/jobs/ostreedev/ostree/ostreedev-ostree-master-presubmits.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/L

#5414 ci-tools: regenerate ci-tools jobs with configresolver support
  ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
  ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
Labels: approved, lgtm, size/M

#5413 Add configs for openshift-azure release-v10
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-release-v10.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v10-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/L

#5419 Increase the grace period in prow's config.
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm, size/XS

#5420 Improve LGTM UX for DPTP
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/XS

#5415 fix the oc path for custom test template
  ci-operator/templates/openshift/installer/cluster-launch-installer-custom-test-image.yaml
Labels: approved, lgtm, size/S

#5410 Update UPI E2E template to contain improvements from the SRC template.
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
Labels: approved, lgtm, size/M

#5422 Add v10.0 upgrade jobs to openshift-azure
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v10-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/M

#5426 Bump golang version for CSI images
  ci-operator/config/openshift/csi-external-attacher/openshift-csi-external-attacher-master.yaml
  ci-operator/config/openshift/csi-external-attacher/openshift-csi-external-attacher-release-4.3.yaml
  ci-operator/config/openshift/csi-external-attacher/openshift-csi-external-attacher-release-4.4.yaml
  ci-operator/config/openshift/csi-external-provisioner/openshift-csi-external-provisioner-master.yaml
  ci-operator/config/openshift/csi-external-provisioner/openshift-csi-external-provisioner-release-4.3.yaml
  ci-operator/config/openshift/csi-external-provisioner/openshift-csi-external-provisioner-release-4.4.yaml
  ci-operator/config/openshift/csi-external-resizer/openshift-csi-external-resizer-master.yaml
  ci-operator/config/openshift/csi-external-snapshotter/openshift-csi-external-snapshotter-master.yaml
  ci-operator/config/openshift/csi-external-snapshotter/openshift-csi-external-snapshotter-release-4.3.yaml
  ci-operator/config/openshift/csi-external-snapshotter/openshift-csi-external-snapshotter-release-4.4.yaml
  ci-operator/config/openshift/csi-livenessprobe/openshift-csi-livenessprobe-master.yaml
  ci-operator/config/openshift/csi-livenessprobe/openshift-csi-livenessprobe-release-4.3.yaml
  ci-operator/config/openshift/csi-livenessprobe/openshift-csi-livenessprobe-release-4.4.yaml
  ci-operator/config/openshift/csi-node-driver-registrar/openshift-csi-node-driver-registrar-master.yaml
  ci-operator/config/openshift/csi-node-driver-registrar/openshift-csi-node-driver-registrar-release-4.3.yaml
  ci-operator/config/openshift/csi-node-driver-registrar/openshift-csi-node-driver-registrar-release-4.4.yaml
Labels: approved, lgtm, size/M

#5428 Remove verify deps
  ci-operator/config/openshift/cluster-kube-apiserver-operator/openshift-cluster-kube-apiserver-operator-master.yaml
  ci-operator/config/openshift/openshift-apiserver/openshift-openshift-apiserver-master.yaml
  ci-operator/jobs/openshift/cluster-kube-apiserver-operator/openshift-cluster-kube-apiserver-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-apiserver/openshift-openshift-apiserver-master-presubmits.yaml
Labels: approved, lgtm, size/L

#5417 add 4.3 jobs to grafana dashboards and alerts
  cluster/ci/monitoring/mixins/config.libsonnet
  cluster/ci/monitoring/mixins/grafana_dashboards/build_cop.jsonnet
  cluster/ci/monitoring/mixins/grafana_dashboards_out/build_cop.json
  cluster/ci/monitoring/mixins/prometheus/build_cop_alerts.libsonnet
  cluster/ci/monitoring/mixins/prometheus_out/prometheus_rule_prow.yaml
Labels: approved, lgtm, size/M

#5388 Add a UPI based src template.
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-src.yaml
Labels: approved, lgtm, size/XXL

#5346 Add infra-role label to job branch-ci-openshift-release-master-core-apply
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
Labels: approved, lgtm, size/XS

#5407 ocs-operator: Fix excluded images for release-4.2
  ci-operator/config/openshift/ocs-operator/openshift-ocs-operator-release-4.2.yaml
Labels: approved, lgtm, size/XS

#5436 Increase mem limits due to 3.11 unit test OOMKilled
  ci-operator/config/openshift/origin/openshift-origin-release-3.11.yaml
Labels: approved, lgtm, size/XS

#5432 Testing 3 master only clusters on cloud
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
Labels: approved, lgtm, size/L

#5441 installer: Compact clusters must set 0 compute replicas
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
Labels: approved, lgtm, size/M

#5435 vSphere CI: Lower vSphere Quota further
  core-services/prow/02_config/_boskos.yaml
Labels: approved, lgtm, size/XS
