Repository openshift/release, pull requests merged in 2019-07, with the labels that each got.

#4244 Temporarily disable e2e CI
  ci-operator/config/redhat-developer/service-binding-operator/redhat-developer-service-binding-operator-master.yaml
  ci-operator/jobs/redhat-developer/service-binding-operator/redhat-developer-service-binding-operator-master-presubmits.yaml
Labels: approved, lgtm, size/M

#4234 Onboading sriov-network-operator for CI
  ci-operator/config/openshift/sriov-network-operator/OWNERS
  ci-operator/config/openshift/sriov-network-operator/openshift-sriov-network-operator-master.yaml
  ci-operator/config/openshift/sriov-network-operator/openshift-sriov-network-operator-release-4.2.yaml
  ci-operator/config/openshift/sriov-network-operator/openshift-sriov-network-operator-release-4.3.yaml
  ci-operator/jobs/openshift/sriov-network-operator/OWNERS
  ci-operator/jobs/openshift/sriov-network-operator/openshift-sriov-network-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/sriov-network-operator/openshift-sriov-network-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/sriov-network-operator/openshift-sriov-network-operator-release-4.2-postsubmits.yaml
  ci-operator/jobs/openshift/sriov-network-operator/openshift-sriov-network-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/sriov-network-operator/openshift-sriov-network-operator-release-4.3-postsubmits.yaml
  ci-operator/jobs/openshift/sriov-network-operator/openshift-sriov-network-operator-release-4.3-presubmits.yaml
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/XL

#4239 Add openshift/ocs-operator
  ci-operator/config/openshift/ocs-operator/OWNERS
  ci-operator/config/openshift/ocs-operator/openshift-ocs-operator-master.yaml
  ci-operator/jobs/openshift/ocs-operator/OWNERS
  ci-operator/jobs/openshift/ocs-operator/openshift-ocs-operator-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, ok-to-test, size/L

#4246 updating the config for having all recent images
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next.yaml
Labels: approved, lgtm, size/L

#4215 add CI for origin oauth-server
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
Labels: approved, lgtm, size/XS

#4247 Add sriov-network-operator image
  cluster/ci/config/mirroring/origin_4_2
Labels: approved, lgtm, size/XS

#4249 Ignore OWNERS files under vendor/
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/XS

#4248 Fix mount subpath for the kubefed-image-mirror cronjob config.
  cluster/ci/jobs/kubefed-image-mirror.yaml
Labels: approved, lgtm, size/XS

#4251 [01-07-2019 22:58:27] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  hack/images.sh
Labels: approved, lgtm, size/L

#4252 Link BZ bugs back to GitHub via external trackers
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#4254 Prune stale generated jobs better
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-openshift-v4-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v4-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v5-postsubmits.yaml
Labels: approved, lgtm, sig/azure, size/M

#4255 Add m1kola into the CI cluster
  projects/azure/cluster-wide.yaml
Labels: approved, lgtm, sig/azure, size/XS

#4253 Update RHEL7 scaleup template and tests
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-master.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-4.1.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-4.2.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-4.3.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-4.3-presubmits.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-scaleup-e2e-40.yaml
Labels: approved, lgtm, size/M

#4260 [02-07-2019 17:10:59] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  hack/images.sh
Labels: approved, lgtm, size/L

#4262 [02-07-2019 19:31:08] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  hack/bump-prow-images.sh
  hack/images.sh
Labels: approved, lgtm, size/L

#4263 Validate Bugzilla bugs by default on release branches
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#4250 ci-operator/config: Update metering-reporting-operator to use OCP 4.2 base image and OKD Dockerfile
  ci-operator/config/operator-framework/operator-metering/operator-framework-operator-metering-master.yaml
Labels: approved, lgtm, size/XS

#4224 Have mdns-publisher be mirrored to quay.io
  cluster/ci/config/mirroring/origin_4_2
Labels: approved, lgtm, size/XS

#4261 Allow ci-chat-bot to teardown launched clusters
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-libvirt-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-metal-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-scaleup-e2e-40.yaml
Labels: approved, lgtm, size/M

#4264 [03-07-2019 00:15:58] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  hack/images.sh
Labels: approved, lgtm, size/L

#4265 Knative eventing (and contrib) release-v0.7.1
  ci-operator/config/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-v0.7.1.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.7.1.yaml
  ci-operator/jobs/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-v0.7.1-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-v0.7.1-presubmits.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.7.1-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.7.1-presubmits.yaml
  cluster/ci/config/mirroring/knative/knative_v0_7_quay
Labels: approved, lgtm, size/XL

#4266 use more explicit goals when testing on codeready-toolchain repos
  ci-operator/config/codeready-toolchain/host-operator/codeready-toolchain-host-operator-master.yaml
  ci-operator/config/codeready-toolchain/member-operator/codeready-toolchain-member-operator-master.yaml
  ci-operator/config/codeready-toolchain/toolchain-common/codeready-toolchain-toolchain-common-master.yaml
Labels: approved, lgtm, size/XS

#4257 Force OpenShiftSDN on openstack-e2e runs
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e.yaml
Labels: approved, do-not-merge/hold, lgtm, size/S

#4270 MCO: bump memory to 8G
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-master.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.2.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.3.yaml
Labels: approved, lgtm, size/XS

#4272 update source path for binary to copy in image
  ci-operator/config/codeready-toolchain/member-operator/codeready-toolchain-member-operator-master.yaml
Labels: approved, lgtm, size/XS

#4273 machine-config-operator: download gosec for verify tests
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-master.yaml
Labels: approved, do-not-merge/hold, lgtm, size/XS

#4256 Mirroring: Docs & scaffolding for new image mirroring jobs
  ci-operator/jobs/infra-image-mirroring.yaml
  cluster/ci/config/prow/plugins.yaml
  core-services/quay-mirroring/OWNERS
  core-services/quay-mirroring/README.md
  core-services/quay-mirroring/knative/OWNERS
  core-services/quay-mirroring/kubefed/OWNERS
  core-services/quay-mirroring/openshift/OWNERS
  core-services/quay-mirroring/tekton/OWNERS
  core-services/quay-mirroring/toolchain/OWNERS
  hack/validate-prow-job-semantics.py
Labels: approved, lgtm, size/L

#4274 [03-07-2019 15:27:28] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  hack/images.sh
Labels: approved, lgtm, size/L

#4276 Validate dependent bug statuses
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#4277 Update tide CPU requests
  cluster/ci/config/prow/openshift/tide.yaml
Labels: approved, lgtm, size/XS

#4280 Add support for rc3 mirroring
  ci-operator/config/openshift/kubefed-operator/openshift-kubefed-operator-release-0.1.0-rc3.yaml
  ci-operator/jobs/openshift/kubefed-operator/openshift-kubefed-operator-release-0.1.0-rc3-postsubmits.yaml
  ci-operator/jobs/openshift/kubefed-operator/openshift-kubefed-operator-release-0.1.0-rc3-presubmits.yaml
  cluster/ci/config/mirroring/kubefed/kubefed-v0_1_0_rc3_quay
  cluster/ci/jobs/kubefed-image-mirror.yaml
Labels: approved, lgtm, size/L

#4281 update mirroring config for codeready-toolchain under prow plugins config
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#4282 MCO master: use github.com/go-bindata/go-bindata/ for bindata
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-master.yaml
Labels: approved, lgtm, size/XS

#4284 Switch toolchain image mirroring jobs to Prowjobs
  Makefile
  ci-operator/jobs/infra-image-mirroring.yaml
  cluster/ci/config/mirroring/toolchain/OWNERS
  cluster/ci/config/mirroring/toolchain/toolchain_v0_0_1_quay
  cluster/ci/config/prow/plugins.yaml
  cluster/ci/jobs/toolchain-image-mirror.yaml
Labels: approved, lgtm, size/M

#4285 Switch kubefed image mirroring jobs to Prowjobs
  Makefile
  ci-operator/jobs/infra-image-mirroring.yaml
  cluster/ci/config/mirroring/kubefed/OWNERS
  cluster/ci/config/mirroring/kubefed/kubefed-v0_1_0_rc2_quay
  cluster/ci/jobs/kubefed-image-mirror.yaml
  core-services/quay-mirroring/kubefed/mapping_kubefed-v0_1_0_rc3_quay
Labels: approved, lgtm, size/L

#4288 Fix an internal link to image mirroring jobs
  core-services/quay-mirroring/README.md
Labels: approved, lgtm, size/XS

#4287 Switch tekton image mirroring jobs to Prowjobs
  Makefile
  ci-operator/jobs/infra-image-mirroring.yaml
  ci-operator/populate-secrets-from-bitwarden.sh
  cluster/ci/config/mirroring/tekton/OWNERS
  cluster/ci/config/mirroring/tekton/tekton_v0_3_quay
  cluster/ci/config/mirroring/tekton/tekton_v0_4_quay
  cluster/ci/jobs/tekton-image-mirror.yaml
  core-services/quay-mirroring/tekton/mapping_tekton_v0_3_quay
  core-services/quay-mirroring/tekton/mapping_tekton_v0_4_quay
Labels: approved, lgtm, size/L

#4290 add e2e stanza for member operator
  ci-operator/config/codeready-toolchain/member-operator/codeready-toolchain-member-operator-master.yaml
  ci-operator/jobs/codeready-toolchain/member-operator/codeready-toolchain-member-operator-master-presubmits.yaml
Labels: approved, lgtm, size/M

#4291 add e2e stanza for host
  ci-operator/config/codeready-toolchain/host-operator/codeready-toolchain-host-operator-master.yaml
  ci-operator/jobs/codeready-toolchain/host-operator/codeready-toolchain-host-operator-master-presubmits.yaml
Labels: approved, lgtm, size/M

#4296 Enable image building
  ci-operator/config/redhat-developer/service-binding-operator/redhat-developer-service-binding-operator-master.yaml
Labels: approved, lgtm, size/XS

#4293 Show the current value in the build-cop alerts
  cluster/ci/monitoring/mixins/config.libsonnet
  cluster/ci/monitoring/mixins/grafana_dashboards/build_cop.jsonnet
  cluster/ci/monitoring/mixins/prometheus/build_cop_alerts.libsonnet
  cluster/ci/monitoring/mixins/prometheus/prometheus.libsonnet
  cluster/ci/monitoring/prometheus_rule_prow.yaml
Labels: approved, lgtm, size/M

#4299 Sort targets in build-cop dashboard
  cluster/ci/monitoring/build_cop.json
  cluster/ci/monitoring/mixins/grafana_dashboards/build_cop.jsonnet
Labels: approved, lgtm, size/S

#4297 Add Knative Serving release v0.7.1
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-v0.7.1.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-v0.7.1-postsubmits.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-v0.7.1-presubmits.yaml
Labels: approved, lgtm, size/L

#4298 Removes OpenShift Azure release v4 from CI
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-release-v4.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-periodics.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v4-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v5-presubmits.yaml
  projects/azure/RELEASES.md
Labels: approved, lgtm, sig/azure, size/XXL

#4303 Fix tekton image mirroring
  ci-operator/jobs/infra-image-mirroring.yaml
  core-services/quay-mirroring/tekton/mapping_tekton_v0_4_quay
Labels: approved, lgtm, size/S

#4305 Add serving images v0.7.1 to mirror job
  cluster/ci/config/mirroring/knative/knative_v0_7_quay
Labels: approved, lgtm, size/XS

#4301 Use 4.1 version
  ci-operator/config/redhat-developer/service-binding-operator/redhat-developer-service-binding-operator-master.yaml
Labels: approved, lgtm, size/XS

#4286 Switch knative image mirroring jobs to Prowjobs
  Makefile
  ci-operator/jobs/infra-image-mirroring.yaml
  cluster/ci/config/mirroring/knative/OWNERS
  cluster/ci/config/mirroring/knative/knative_v0_4_quay
  cluster/ci/config/mirroring/knative/knative_v0_5_quay
  cluster/ci/config/mirroring/knative/knative_v0_6_quay
  cluster/ci/config/mirroring/knative/knative_v0_7_quay
  cluster/ci/config/prow/plugins.yaml
  cluster/ci/jobs/knative-image-mirror.yaml
  core-services/quay-mirroring/knative/mapping_knative_v0_7_quay
Labels: approved, lgtm, size/L

#4309 add ci-op cpu/memory usage/requests rules
  core-services/openshift-monitoring/cfg_prometheus-prow-rules_prometheusrule.yaml
Labels: approved, lgtm, size/S

#4311 change ci-op rules severity
  core-services/openshift-monitoring/cfg_prometheus-prow-rules_prometheusrule.yaml
Labels: approved, lgtm, size/XS

#4312 Better wording in build-cop alerts
  cluster/ci/monitoring/mixins/prometheus/build_cop_alerts.libsonnet
  cluster/ci/monitoring/prometheus_rule_prow.yaml
Labels: approved, lgtm, size/S

#4306 Fix secret paths in mirroring jobs
  ci-operator/jobs/infra-image-mirroring.yaml
Labels: approved, lgtm, size/XS

#4316 CoreDNS's been bumped to a release that needs go 1.12
  ci-operator/config/openshift/coredns/openshift-coredns-master.yaml
  ci-operator/config/openshift/coredns/openshift-coredns-release-4.1.yaml
  ci-operator/config/openshift/coredns/openshift-coredns-release-4.2.yaml
  ci-operator/config/openshift/coredns/openshift-coredns-release-4.3.yaml
Labels: approved, lgtm, size/XS

#4304 Add e2e-aws job for cluster-nfd-operator
  ci-operator/config/openshift/cluster-nfd-operator/OWNERS
  ci-operator/config/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-master.yaml
  ci-operator/config/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-release-4.1.yaml
  ci-operator/config/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-release-4.2.yaml
  ci-operator/config/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-release-4.3.yaml
  ci-operator/jobs/openshift/cluster-nfd-operator/OWNERS
  ci-operator/jobs/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-release-4.1-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-release-4.2-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-release-4.3-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-release-4.3-presubmits.yaml
Labels: approved, lgtm, size/XXL

#4275 disable branch protection for repos under codeready-toolchain org
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/S

#4289 Add sriov-network-config-daemon image from sriov-network-operator repo
  ci-operator/config/openshift/sriov-network-operator/openshift-sriov-network-operator-master.yaml
  ci-operator/config/openshift/sriov-network-operator/openshift-sriov-network-operator-release-4.2.yaml
  ci-operator/config/openshift/sriov-network-operator/openshift-sriov-network-operator-release-4.3.yaml
  cluster/ci/config/mirroring/origin_4_2
Labels: approved, lgtm, size/S

#4318 ci-operator/config/openshift/cluster-etcd-operator: add hexfusion to OWNERS
  ci-operator/config/openshift/cluster-etcd-operator/OWNERS
Labels: approved, lgtm, size/XS

#4231 Use new s2i Jenkins test suite
  ci-operator/jobs/openshift/source-to-image/openshift-source-to-image-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#4317 ci-operator/config/openshift/cluster-etcd-operator: bump golang to 1.12
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-master.yaml
Labels: approved, lgtm, size/XS

#4278 Move ci-chat-bot config from ci-operator/infra to core-services
  Makefile
  core-services/ci-chat-bot/OWNERS
  core-services/ci-chat-bot/README.md
  core-services/ci-chat-bot/admin_rbac.yaml
  core-services/ci-chat-bot/deploy.yaml
Labels: approved, lgtm, size/M

#4320 ci-operator/config/openshift/cluster-etcd-operator: enable GO111MODULE
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-master.yaml
Labels: approved, lgtm, size/XS

#4315 Make e2e libvirt test to run for each PR.
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#4322 [09-07-2019 19:56:39] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  hack/images.sh
Labels: approved, lgtm, size/L

#4324 Enable OLM based e2e test
  ci-operator/config/redhat-developer/service-binding-operator/redhat-developer-service-binding-operator-master.yaml
  ci-operator/jobs/redhat-developer/service-binding-operator/redhat-developer-service-binding-operator-master-presubmits.yaml
Labels: approved, lgtm, size/M

#4314 ci-operator/mco: rename mco dockerfile
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-master.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.2.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.3.yaml
Labels: approved, lgtm, size/XS

#4321 ci-operator/config/openshift/etcd: bump golang to 1.11 for 4.2
  ci-operator/config/openshift/etcd/openshift-etcd-openshift-4.2.yaml
Labels: approved, lgtm, size/XS

#4326 mirroring: fix template cronspec to @hourly
  ci-operator/jobs/infra-image-mirroring.yaml
Labels: approved, lgtm, size/XS

#4327 Don't run `e2e-libvirt` job on doc-only changes
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#4337 [10-07-2019 18:50:11] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  hack/images.sh
Labels: approved, lgtm, size/L

#4338 Fix Makefile in cluster/ci/monitoring
  cluster/ci/monitoring/Makefile
Labels: approved, lgtm, size/XS

#4307 kubefed-operator: run olm-e2e tests on a cluster
  ci-operator/config/openshift/kubefed-operator/openshift-kubefed-operator-master.yaml
  ci-operator/config/openshift/kubefed-operator/openshift-kubefed-operator-release-0.1.0-rc2.yaml
  ci-operator/config/openshift/kubefed-operator/openshift-kubefed-operator-release-0.1.0-rc3.yaml
  ci-operator/config/openshift/kubefed-operator/openshift-kubefed-operator-release-4.2.yaml
  ci-operator/config/openshift/kubefed-operator/openshift-kubefed-operator-release-4.3.yaml
  ci-operator/jobs/openshift/kubefed-operator/openshift-kubefed-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/kubefed-operator/openshift-kubefed-operator-release-0.1.0-rc2-presubmits.yaml
  ci-operator/jobs/openshift/kubefed-operator/openshift-kubefed-operator-release-0.1.0-rc3-presubmits.yaml
  ci-operator/jobs/openshift/kubefed-operator/openshift-kubefed-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/kubefed-operator/openshift-kubefed-operator-release-4.3-presubmits.yaml
Labels: approved, lgtm, size/L

#4334 Condense container networking plugins into single image
  cluster/ci/config/mirroring/origin_4_2
Labels: approved, lgtm, size/XS

#4329 change source path for host-operator
  ci-operator/config/codeready-toolchain/host-operator/codeready-toolchain-host-operator-master.yaml
Labels: approved, lgtm, size/XS

#4271 promote host-operator and member-operator
  ci-operator/config/codeready-toolchain/host-operator/codeready-toolchain-host-operator-master.yaml
  ci-operator/config/codeready-toolchain/member-operator/codeready-toolchain-member-operator-master.yaml
  ci-operator/jobs/codeready-toolchain/host-operator/codeready-toolchain-host-operator-master-postsubmits.yaml
  ci-operator/jobs/codeready-toolchain/member-operator/codeready-toolchain-member-operator-master-postsubmits.yaml
  ci-operator/jobs/infra-image-mirroring.yaml
  ci-operator/populate-secrets-from-bitwarden.sh
  cluster/ci/config/prow/openshift/ci-operator/roles.yaml
  cluster/ci/config/roles.yaml
  core-services/quay-mirroring/codeready-toolchain/OWNERS
  core-services/quay-mirroring/codeready-toolchain/mapping_codeready_toolchain_v0_1_quay
Labels: approved, lgtm, size/L

#4342 Disable OLM based e2e test
  ci-operator/config/redhat-developer/service-binding-operator/redhat-developer-service-binding-operator-master.yaml
  ci-operator/jobs/redhat-developer/service-binding-operator/redhat-developer-service-binding-operator-master-presubmits.yaml
Labels: approved, lgtm, size/M

#4028 Add separate jobs to run machine-api-operator tech preview features
  ci-operator/config/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-master.yaml
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-master.yaml
  ci-operator/jobs/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-master-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-master-presubmits.yaml
Labels: approved, lgtm, size/L

#4346 Fix RBAC on ns prow-monitoring-stage
  cluster/ci/monitoring/Makefile
Labels: approved, lgtm, size/XS

#4339 mirroring: make the docs about secrets less vague
  ci-operator/SECRETS.md
  ci-operator/jobs/infra-image-mirroring.yaml
  core-services/quay-mirroring/README.md
Labels: approved, lgtm, size/S

#4335 Configure e2e tests for local-storage operator
  ci-operator/config/openshift/local-storage-operator/openshift-local-storage-operator-master.yaml
  ci-operator/config/openshift/local-storage-operator/openshift-local-storage-operator-release-4.2.yaml
  ci-operator/config/openshift/local-storage-operator/openshift-local-storage-operator-release-4.3.yaml
  ci-operator/jobs/openshift/local-storage-operator/openshift-local-storage-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/local-storage-operator/openshift-local-storage-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/local-storage-operator/openshift-local-storage-operator-release-4.3-presubmits.yaml
Labels: approved, lgtm, size/L

#4350 [11-07-2019 18:17:06] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  hack/images.sh
Labels: approved, lgtm, size/L

#4347 Needed by the openshift build process
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-periodics.yaml
Labels: approved, lgtm, sig/azure, size/XS

#4330 Adds m1kola as a reviewer into the Azure project
  projects/azure/OWNERS
Labels: approved, lgtm, sig/azure, size/XS

#4336 Add a dashboard for configmap sizes
  cluster/ci/config/roles.yaml
  cluster/ci/monitoring/hook.json
  cluster/ci/monitoring/mixins/grafana_dashboards/hook.jsonnet
Labels: approved, lgtm, size/L

#4353 Remove some knative images from ci-operator config
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-next.yaml
Labels: approved, lgtm, size/M

#4361 CI configuration for openshift/baremetal-runtimecfg
  ci-operator/config/openshift/baremetal-runtimecfg/OWNERS
  ci-operator/config/openshift/baremetal-runtimecfg/openshift-baremetal-runtimecfg-master.yaml
  ci-operator/jobs/openshift/baremetal-runtimecfg/OWNERS
  ci-operator/jobs/openshift/baremetal-runtimecfg/openshift-baremetal-runtimecfg-master-postsubmits.yaml
  ci-operator/jobs/openshift/baremetal-runtimecfg/openshift-baremetal-runtimecfg-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#4356 Add prow config for ironic-ipa-downloader
  ci-operator/config/openshift/ironic-ipa-downloader/OWNERS
  ci-operator/config/openshift/ironic-ipa-downloader/openshift-ironic-ipa-downloader-master.yaml
  ci-operator/jobs/openshift/ironic-ipa-downloader/OWNERS
  ci-operator/jobs/openshift/ironic-ipa-downloader/openshift-ironic-ipa-downloader-master-postsubmits.yaml
  ci-operator/jobs/openshift/ironic-ipa-downloader/openshift-ironic-ipa-downloader-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#4368 Add a dashboard for number of running clusters
  cluster/ci/monitoring/build_cop.json
  cluster/ci/monitoring/mixins/grafana_dashboards/build_cop.jsonnet
Labels: approved, lgtm, size/L

#4015 openstack: Add optional e2e-openstack job to CIRO
  ci-operator/jobs/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-master-presubmits.yaml
Labels: approved, lgtm, size/M

#4343 use correct branch for verify-client-go checks
  ci-operator/config/openshift/api/openshift-api-release-4.1.yaml
  ci-operator/config/openshift/api/openshift-api-release-4.2.yaml
  ci-operator/config/openshift/api/openshift-api-release-4.3.yaml
Labels: approved, lgtm, size/XS

#4333 Use robot credentials for Bugzilla API
  ci-operator/populate-secrets-from-bitwarden.sh
  cluster/ci/config/prow/openshift/hook.yaml
Labels: approved, lgtm, size/XS

#4351 Move Bugs to MODIFIED after linked PRs merge
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#4370 [12-07-2019 21:44:56] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  hack/images.sh
Labels: approved, lgtm, size/L

#4371 ci-operator/jobs/openshift/cluster-etcd-operator: add hexfusion to OWNERS
  ci-operator/jobs/openshift/cluster-etcd-operator/OWNERS
Labels: approved, lgtm, size/XS

#4345 ci-operator/config/openshift/cluster-etcd-operator: add release-4.2
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-master.yaml
  ci-operator/jobs/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#4372 Replace canonical_go_repository github.com/knative/serving with knative.dev/serving
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-next.yaml
Labels: approved, lgtm, size/XS

#4235 use separate Dockerfile for forked repositories managed by monitoring team
  ci-operator/config/openshift/configmap-reload/openshift-configmap-reload-master.yaml
  ci-operator/config/openshift/grafana/openshift-grafana-master.yaml
  ci-operator/config/openshift/k8s-prometheus-adapter/openshift-k8s-prometheus-adapter-master.yaml
  ci-operator/config/openshift/kube-rbac-proxy/openshift-kube-rbac-proxy-master.yaml
  ci-operator/config/openshift/kube-state-metrics/openshift-kube-state-metrics-master.yaml
  ci-operator/config/openshift/node_exporter/openshift-node_exporter-master.yaml
  ci-operator/config/openshift/prometheus-alertmanager/openshift-prometheus-alertmanager-master.yaml
  ci-operator/config/openshift/prometheus-operator/openshift-prometheus-operator-master.yaml
  ci-operator/config/openshift/prometheus/openshift-prometheus-master.yaml
Labels: approved, lgtm, size/S

#4373 Revert "Condense container networking plugins into single image"
  cluster/ci/config/mirroring/origin_4_2
Labels: approved, lgtm, size/XS

#4375 Bug 1728313: add oauth-server image build to origin config 4.2, 4.3
  ci-operator/config/openshift/origin/openshift-origin-release-4.2.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.3.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#3707 Create e2e job for SDN multitenant mode
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
Labels: approved, lgtm, size/M

#4313 operator-sdk: add helm e2e tests to ci
  ci-operator/config/operator-framework/operator-sdk/operator-framework-operator-sdk-master.yaml
  ci-operator/jobs/operator-framework/operator-sdk/operator-framework-operator-sdk-master-presubmits.yaml
Labels: approved, lgtm, size/M

#4376 Remove travis check from openshift/imagebuilder
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/XS

#4379 Requesting for more resources
  ci-operator/config/openshift/odo/openshift-odo-master.yaml
Labels: approved, lgtm, size/XS

#4364 Mirror baremetal-runtimecfg to quay.io
  cluster/ci/config/mirroring/origin_4_2
Labels: approved, lgtm, size/XS

#4383 config/openshift/cluster-etcd-operator: promote to 4.2
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-master.yaml
Labels: approved, lgtm, size/XS

#4362 Add job to test application of security patches to ARO clusters
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-periodics.yaml
Labels: approved, lgtm, sig/azure, size/M

#4377 Back up k8s_prometheus.yaml
  cluster/ci/config/prow/openshift/config_updater_rbac.yaml
  core-services/openshift-monitoring/k8s_prometheus.yaml
Labels: approved, lgtm, size/M

#4178 Add CI for published oauth-server repository
  ci-operator/config/openshift/oauth-server/OWNERS
  ci-operator/config/openshift/oauth-server/openshift-oauth-server-master.yaml
  ci-operator/jobs/openshift/oauth-server/OWNERS
  ci-operator/jobs/openshift/oauth-server/openshift-oauth-server-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#4386 [16-07-2019 18:05:23] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  hack/images.sh
Labels: approved, lgtm, size/L

#4385 Add manual steps for updating openshift-monitoring/k8s prometheus
  core-services/openshift-monitoring/k8s_prometheus.yaml
Labels: approved, lgtm, size/XS

#4390 Setup staging repos
  ci-operator/config/openshift/openshift-apiserver/OWNERS
  ci-operator/config/openshift/openshift-apiserver/openshift-openshift-apiserver-master.yaml
  ci-operator/config/openshift/openshift-controller-manager/OWNERS
  ci-operator/config/openshift/openshift-controller-manager/openshift-openshift-controller-manager-master.yaml
  ci-operator/config/openshift/template-service-broker/OWNERS
  ci-operator/config/openshift/template-service-broker/openshift-template-service-broker-master.yaml
  ci-operator/jobs/openshift/openshift-apiserver/OWNERS
  ci-operator/jobs/openshift/openshift-apiserver/openshift-openshift-apiserver-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-controller-manager/OWNERS
  ci-operator/jobs/openshift/openshift-controller-manager/openshift-openshift-controller-manager-master-presubmits.yaml
  ci-operator/jobs/openshift/template-service-broker/OWNERS
  ci-operator/jobs/openshift/template-service-broker/openshift-template-service-broker-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XXL

#4391 Add tekton pullrequest-init
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-next.yaml
Labels: approved, lgtm, size/S

#4394 Readd imagedigestexporter
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-next.yaml
Labels: approved, lgtm, size/XS

#4397 openshift-apiserver: move Dockerfile.rhel
  ci-operator/config/openshift/openshift-apiserver/openshift-openshift-apiserver-master.yaml
Labels: approved, lgtm, size/XS

#4398 New SDN images
  ci-operator/config/openshift/sdn/openshift-sdn-master.yaml
Labels: approved, lgtm, size/XS

#4392 postsubmit job for codeready-toolchain/toolchain-common
  ci-operator/jobs/codeready-toolchain/toolchain-common/codeready-toolchain-toolchain-common-master-postsubmits.yaml
Labels: approved, lgtm, size/M

#4400 Fix sdn image name
  ci-operator/config/openshift/sdn/openshift-sdn-master.yaml
Labels: approved, lgtm, size/XS

#4399 Setup oc repo
  ci-operator/config/openshift/oc/OWNERS
  ci-operator/config/openshift/oc/openshift-oc-master.yaml
  ci-operator/jobs/openshift/oc/OWNERS
  ci-operator/jobs/openshift/oc/openshift-oc-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#4393 Promote new images
  ci-operator/config/openshift/openshift-apiserver/openshift-openshift-apiserver-master.yaml
  ci-operator/config/openshift/openshift-controller-manager/openshift-openshift-controller-manager-master.yaml
  ci-operator/jobs/openshift/openshift-apiserver/openshift-openshift-apiserver-master-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-apiserver/openshift-openshift-apiserver-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-controller-manager/openshift-openshift-controller-manager-master-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-controller-manager/openshift-openshift-controller-manager-master-presubmits.yaml
Labels: approved, lgtm, size/L

#4283 Switch OpenShift image mirroring jobs to Prowjobs
  Makefile
  ci-operator/jobs/infra-image-mirroring.yaml
  cluster/ci/config/mirroring/OWNERS
  cluster/ci/config/mirroring/origin_4_1
  cluster/ci/config/mirroring/origin_4_2
  cluster/ci/config/mirroring/origin_v3_10
  cluster/ci/config/mirroring/origin_v3_11
  cluster/ci/config/mirroring/origin_v3_11_quay
  cluster/ci/config/mirroring/origin_v3_9
  cluster/ci/config/prow/plugins.yaml
  cluster/ci/jobs/image-mirror.yaml
  core-services/quay-mirroring/openshift/Makefile
  core-services/quay-mirroring/openshift/mapping_origin_4_2
Labels: approved, lgtm, size/XL

#3876 Add openstack repos mirror
  Makefile
  ci-operator/infra/openshift/release-controller/repos/ocp-4.2-openstack.repo
  ci-operator/infra/openshift/release-controller/repos/ocp-4.3-openstack.repo
  ci-operator/infra/openshift/release-controller/rpms-ocp-4.2.yaml
  ci-operator/infra/openshift/release-controller/rpms-ocp-4.3.yaml
Labels: approved, lgtm, size/L

#4404 Move oauth-server image and promotion to its own repo
  ci-operator/config/openshift/oauth-server/openshift-oauth-server-master.yaml
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/jobs/openshift/oauth-server/openshift-oauth-server-master-postsubmits.yaml
  ci-operator/jobs/openshift/oauth-server/openshift-oauth-server-master-presubmits.yaml
Labels: approved, lgtm, size/M

#4401 Do not tightly couple docs and naming to Quay
  cluster/ci/config/prow/plugins.yaml
  core-services/image-mirroring/OWNERS
  core-services/image-mirroring/README.md
  core-services/image-mirroring/codeready-toolchain/OWNERS
  core-services/image-mirroring/codeready-toolchain/mapping_codeready_toolchain_v0_1_quay
  core-services/image-mirroring/knative/OWNERS
  core-services/image-mirroring/knative/mapping_knative_v0_4_quay
  core-services/image-mirroring/knative/mapping_knative_v0_5_quay
  core-services/image-mirroring/knative/mapping_knative_v0_6_quay
  core-services/image-mirroring/knative/mapping_knative_v0_7_quay
  core-services/image-mirroring/kubefed/OWNERS
  core-services/image-mirroring/kubefed/mapping_kubefed-v0_1_0_rc2_quay
  core-services/image-mirroring/kubefed/mapping_kubefed-v0_1_0_rc3_quay
  core-services/image-mirroring/openshift/Makefile
  core-services/image-mirroring/openshift/OWNERS
  core-services/image-mirroring/openshift/mapping_origin_4_1
  core-services/image-mirroring/openshift/mapping_origin_4_2
  core-services/image-mirroring/openshift/mapping_origin_v3_10
  core-services/image-mirroring/openshift/mapping_origin_v3_11
  core-services/image-mirroring/openshift/mapping_origin_v3_11_quay
  core-services/image-mirroring/openshift/origin_v3_9
  core-services/image-mirroring/tekton/OWNERS
  core-services/image-mirroring/tekton/mapping_tekton_v0_4_quay
  core-services/image-mirroring/toolchain/OWNERS
  core-services/image-mirroring/toolchain/mapping_toolchain_v0_0_1_quay
Labels: approved, lgtm, size/S

#4408 update path to template-service-broker Dockerfile.rhel
  ci-operator/config/openshift/template-service-broker/openshift-template-service-broker-master.yaml
Labels: approved, lgtm, size/XS

#4407 produce template-service-broker images from openshift/template-servic…
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/config/openshift/template-service-broker/openshift-template-service-broker-master.yaml
  ci-operator/jobs/openshift/template-service-broker/openshift-template-service-broker-master-postsubmits.yaml
  ci-operator/jobs/openshift/template-service-broker/openshift-template-service-broker-master-presubmits.yaml
Labels: approved, lgtm, size/M

#4413 [18-07-2019 09:39:41] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  hack/images.sh
Labels: approved, lgtm, size/L

#4414 Requesting memory resource to 5Gi
  ci-operator/config/openshift/odo/openshift-odo-master.yaml
Labels: approved, lgtm, size/XS

#4403 Promote separated sdn
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/config/openshift/sdn/openshift-sdn-master.yaml
  ci-operator/jobs/openshift/sdn/openshift-sdn-master-postsubmits.yaml
  ci-operator/jobs/openshift/sdn/openshift-sdn-master-presubmits.yaml
Labels: approved, lgtm, size/M

#4354 Update tide config to exlude unknown contexts for CRI-O
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, ok-to-test, size/S

#4419 remove uid and unnecessary fields from prometheus crd
  core-services/openshift-monitoring/k8s_prometheus.yaml
Labels: approved, lgtm, size/XS

#4420 postsubmit job for codeready-toolchain/member-operator
  ci-operator/jobs/codeready-toolchain/member-operator/codeready-toolchain-member-operator-master-postsubmits.yaml
Labels: approved, lgtm, size/M

#4416 add cookie-secret to deck-internal
  cluster/ci/config/prow/openshift/deck.yaml
Labels: approved, lgtm, size/XS

#4421 postsubmit job for codeready-toolchain/host-operator
  ci-operator/jobs/codeready-toolchain/host-operator/codeready-toolchain-host-operator-master-postsubmits.yaml
Labels: approved, lgtm, size/L

#4422 postsubmit e2e tests job for codeready-toolchain/member-operator
  ci-operator/jobs/codeready-toolchain/member-operator/codeready-toolchain-member-operator-master-postsubmits.yaml
Labels: approved, lgtm, size/M

#4423 Add new oc images
  ci-operator/config/openshift/oc/openshift-oc-master.yaml
Labels: approved, lgtm, size/S

#4405 Update 4.2 repo file to use 4.2 mirrors
  ci-operator/infra/openshift/release-controller/repos/ocp-4.2-default.repo
Labels: approved, lgtm, size/S

#4402 Promote cli image from oc repo instead of origin
  ci-operator/config/openshift/oc/openshift-oc-master.yaml
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/jobs/openshift/oc/openshift-oc-master-postsubmits.yaml
  ci-operator/jobs/openshift/oc/openshift-oc-master-presubmits.yaml
Labels: approved, lgtm, size/M

#4406 libvirt provider should use its own config
  ci-operator/jobs/openshift/cluster-api-provider-libvirt/openshift-cluster-api-provider-libvirt-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#4426 Update console limits
  ci-operator/config/openshift/console/openshift-console-master.yaml
Labels: approved, lgtm, size/S

#4428 Add some documentation on external repositories we mirror to
  core-services/image-mirroring/README.md
Labels: approved, lgtm, size/S

#4430 Add an alert for ConfigMap sizes getting close to full
  cluster/ci/monitoring/mixins/prometheus/configmap_alerts.libsonnet
  cluster/ci/monitoring/mixins/prometheus/prometheus.libsonnet
  cluster/ci/monitoring/prometheus_rule_prow.yaml
Labels: approved, lgtm, size/M

#4433 Import cli image into origin from oc
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
Labels: approved, lgtm, size/XS

#4435 [18-07-2019 21:17:58] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  hack/images.sh
Labels: approved, lgtm, size/L

#4434 Use the appropriate linear prediction in alert
  cluster/ci/monitoring/mixins/prometheus/configmap_alerts.libsonnet
  cluster/ci/monitoring/prometheus_rule_prow.yaml
Labels: approved, lgtm, size/XS

#4432 Add deck-internal into prow-monitoring
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/monitoring/Makefile
  cluster/ci/monitoring/deck-internal_service_monitor.yaml
  cluster/ci/monitoring/mixins/prometheus/ci_absent_alerts.libsonnet
  cluster/ci/monitoring/prometheus_rule_prow.yaml
Labels: approved, lgtm, size/M

#4031 ci-operator: add golang e2e tests for operator-sdk
  ci-operator/config/operator-framework/operator-sdk/operator-framework-operator-sdk-master.yaml
  ci-operator/jobs/operator-framework/operator-sdk/operator-framework-operator-sdk-master-presubmits.yaml
Labels: approved, lgtm, size/M

#4441 Fix oc images
  ci-operator/config/openshift/oc/openshift-oc-master.yaml
Labels: approved, lgtm, size/S

#4443 increase tide's cpu requests
  cluster/ci/config/prow/openshift/tide.yaml
Labels: approved, lgtm, size/XS

#4431 Add CI to the rbac-permissions-operator repo
  ci-operator/config/openshift/rbac-permissions-operator/OWNERS
  ci-operator/config/openshift/rbac-permissions-operator/openshift-rbac-permissions-operator-master.yaml
  ci-operator/jobs/openshift/rbac-permissions-operator/OWNERS
  ci-operator/jobs/openshift/rbac-permissions-operator/openshift-rbac-permissions-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/rbac-permissions-operator/openshift-rbac-permissions-operator-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#4440 Prepare tests for ARO plugin release-v6 branch
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-release-v6.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v6-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/L

#4424 Setup CI job for Tektoncd Pipeline release v0.5.2
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.5.2.yaml
  ci-operator/jobs/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.5.2-postsubmits.yaml
  ci-operator/jobs/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.5.2-presubmits.yaml
Labels: approved, lgtm, size/L
