Repository openshift/release, pull requests merged in 2019-01, with the labels that each got.

#2475 Disable e2e-gcp* on openshift/origin master
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#2476 osa node build: export resource group for e2e tests
  ci-operator/templates/openshift/openshift-azure/build-node-image.yaml
Labels: approved, lgtm, sig/azure, size/XS

#2464 Enable knative nightly builds
  ci-operator/jobs/openshift/knative-build/openshift-knative-build-periodics.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-periodics.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-periodics.yaml
Labels: approved, lgtm, size/L

#2477 Get container logs out of osa periodics
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-periodics.yaml
Labels: approved, lgtm, sig/azure, size/XS

#2479 Get cluster-monitoring operator log from OSA clusters
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure.yaml
Labels: approved, lgtm, sig/azure, size/XS

#2480 Revert "change gating tests name and make them mandatory"
  ci-operator/config/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-master.yaml
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-master.yaml
  ci-operator/jobs/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-master-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-master-presubmits.yaml
Labels: approved, lgtm, size/M

#2484 Revert "Allow resources in the src template to be customized"
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
Labels: approved, lgtm, size/S

#2483 osa - move to make targets
  ci-operator/templates/openshift/openshift-azure/build-node-image.yaml
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure.yaml
Labels: approved, lgtm, sig/azure, size/S

#2472 make aws builds+image-registry jobs enforced
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#2489 order for unbind vars
  ci-operator/templates/openshift/openshift-azure/build-node-image.yaml
Labels: approved, lgtm, sig/azure, size/XS

#2488 enable more aws versions of jobs on devex repos
  ci-operator/config/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-master.yaml
  ci-operator/config/openshift/image-registry/openshift-image-registry-master.yaml
  ci-operator/jobs/openshift/builder/openshift-builder-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/image-registry/openshift-image-registry-master-presubmits.yaml
Labels: approved, lgtm, size/L

#2490 Revert "Revert "Allow resources in the src template to be customized""
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
Labels: approved, lgtm

#2491 Add quotes around memory
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
Labels: approved, lgtm, size/XS

#2493 [02-04-2019 17:04:31] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  cluster/ci/config/prow/openshift/tracer.yaml
Labels: approved, lgtm, size/M

#2492 Add columns to the CRD output
  cluster/ci/config/prow/prow_crd.yaml
Labels: approved, lgtm, size/M

#2421 Build OSA e2e image in CI
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-master.yaml
  projects/azure/README.md
  projects/azure/image-mirror/image-mirror.yaml
Labels: approved, lgtm, sig/azure, size/M

#2495 Fake rp is started in make e2e now
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure.yaml
Labels: approved, lgtm, sig/azure, size/XS

#2496 [03-26-2019 18:26:37] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  cluster/ci/config/prow/openshift/tracer.yaml
Labels: approved, lgtm, size/M

#2497 Use month, not seconds, for date label
  hack/bump-prow-images.sh
Labels: approved, lgtm, size/XS

#2498 Set AWS creds in test container so AWS e2e tests can pass
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
Labels: approved, lgtm, size/XS

#2500 Authenticated users should also be able to pull ci-operator images
  ci-operator/templates/cluster-launch-e2e-openshift-ansible.yaml
  ci-operator/templates/cluster-launch-e2e-openshift-jenkins.yaml
  ci-operator/templates/cluster-launch-e2e-upgrade.yaml
  ci-operator/templates/cluster-launch-e2e.yaml
  ci-operator/templates/cluster-launch-src.yaml
  ci-operator/templates/master-sidecar.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-libvirt-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e-40.yaml
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure.yaml
Labels: approved, lgtm, sig/azure, size/S

#2501 Allow admins to watch ProwJobs
  cluster/ci/config/prow/prowjob_access.yaml
Labels: approved, lgtm, size/XS

#2478 Run bushslicer suite daily
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-periodics.yaml
Labels: approved, lgtm, sig/azure, size/XS

#2482 Add config and jobs for openshift/cloud-credential-operator
  ci-operator/config/openshift/cloud-credential-operator/OWNERS
  ci-operator/config/openshift/cloud-credential-operator/openshift-cloud-credential-operator-master.yaml
  ci-operator/jobs/openshift/cloud-credential-operator/OWNERS
  ci-operator/jobs/openshift/cloud-credential-operator/openshift-cloud-credential-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/cloud-credential-operator/openshift-cloud-credential-operator-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#2502 Add Luke Meyer and Tim Bielawa to ci-admins group
  cluster/ci/config/roles.yaml
Labels: approved, lgtm, size/XS

#2503 remove prom sidecar
  ci-operator/config/openshift/azure-misc/openshift-azure-misc-master.yaml
Labels: approved, lgtm, sig/azure, size/S

#2507 AWS e2e provider should identify zone and master and multizone
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
Labels: approved, lgtm, size/XS

#2508 New test images for knative-serving
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-master.yaml
Labels: approved, lgtm, size/M

#2510 Add e2e serial test suite
  ci-operator/config/openshift/cluster-kube-scheduler-operator/openshift-cluster-kube-scheduler-operator-master.yaml
  ci-operator/jobs/openshift/cluster-kube-scheduler-operator/openshift-cluster-kube-scheduler-operator-master-presubmits.yaml
Labels: approved, lgtm, size/M

#2509 BYOR 3.x AWS: create SG per test
  cluster/test-deploy/aws-atomic/vars.yaml
  cluster/test-deploy/aws-centos/vars.yaml
  cluster/test-deploy/aws-gluster/vars.yaml
Labels: approved, lgtm, size/S

#2513 Update osin image name to cluster-authentication-operator
  ci-operator/config/openshift/cluster-osin-operator/openshift-cluster-osin-operator-master.yaml
Labels: approved, lgtm, size/XS

#2515 Revert "Revert "Enable jenkins for origin-web-console branch enterprise-3.11""
  ci-operator/jobs/openshift/origin-web-console/openshift-origin-web-console-enterprise-3.11-presubmits.yml
Labels: approved, lgtm, size/S

#2516 Enable Jenkins for openshift/origin-web-console@enterprise-3.11
  ci-operator/jobs/openshift/origin-web-console/openshift-origin-web-console-enterprise-3.11-presubmits.yaml
Labels: approved, lgtm, size/XS

#2517 Forbid .yml file extensions
  hack/validate-ci-operator-config-filename.py
  hack/validate-prow-job-semantics.py
Labels: approved, lgtm, size/XS

#2520 add image build for pj-rehearse
  ci-operator/config/openshift/ci-operator-prowgen/openshift-ci-operator-prowgen-master.yaml
Labels: approved, lgtm, size/XS

#2523 BYOR 4.0: specify machineCIDR in openshift-ansible install config
  ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e-40.yaml
Labels: approved, lgtm, size/XS

#2524 Remove apparently unused jobs
  ci-operator/jobs/openshift/cincinnati/openshift-cincinnati-master-presubmit-presubmits.yaml
Labels: approved, lgtm, size/M

#2526 change pj-rehearse image link.
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#2511 add oauth-proxy CI config
  ci-operator/config/openshift/oauth-proxy/OWNERS
  ci-operator/config/openshift/oauth-proxy/openshift-oauth-proxy-master.yaml
  ci-operator/jobs/openshift/oauth-proxy/OWNERS
  ci-operator/jobs/openshift/oauth-proxy/openshift-oauth-proxy-master-postsubmits.yaml
  ci-operator/jobs/openshift/oauth-proxy/openshift-oauth-proxy-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#2532 Add ravi & Seth to OWNERS
  ci-operator/config/openshift/cluster-kube-scheduler-operator/OWNERS
  ci-operator/jobs/openshift/cluster-kube-scheduler-operator/OWNERS
Labels: approved, lgtm, size/XS

#2528 Fix e2e job def
  ci-operator/config/openshift/cluster-kube-scheduler-operator/openshift-cluster-kube-scheduler-operator-master.yaml
  ci-operator/jobs/openshift/cluster-kube-scheduler-operator/openshift-cluster-kube-scheduler-operator-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#2531 Update image mirror setup
  cluster/ci/config/mirroring/origin_v4_0_quay
Labels: approved, lgtm, size/XS

#2533 Fix csi-operator test suite name
  ci-operator/config/openshift/csi-operator/openshift-csi-operator-master.yaml
  ci-operator/jobs/openshift/csi-operator/openshift-csi-operator-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#2529 add config for k8s-prometheus-adapter
  ci-operator/config/openshift/k8s-prometheus-adapter/OWNERS
  ci-operator/config/openshift/k8s-prometheus-adapter/openshift-k8s-prometheus-adapter-master.yaml
  ci-operator/jobs/openshift/k8s-prometheus-adapter/OWNERS
  ci-operator/jobs/openshift/k8s-prometheus-adapter/openshift-k8s-prometheus-adapter-master-postsubmits.yaml
  ci-operator/jobs/openshift/k8s-prometheus-adapter/openshift-k8s-prometheus-adapter-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#2536 Sync azure secrets from azure ns
  cluster/ci/config/secret-mirroring/mapping.yaml
  projects/azure/README.md
Labels: approved, lgtm, sig/azure, size/M

#2537 add config for prom-label-proxy
  ci-operator/config/openshift/prom-label-proxy/OWNERS
  ci-operator/config/openshift/prom-label-proxy/openshift-prom-label-proxy-master.yaml
  ci-operator/jobs/openshift/prom-label-proxy/OWNERS
  ci-operator/jobs/openshift/prom-label-proxy/openshift-prom-label-proxy-master-postsubmits.yaml
  ci-operator/jobs/openshift/prom-label-proxy/openshift-prom-label-proxy-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#2538 Add more OSA docs
  projects/azure/README.md
Labels: approved, kind/documentation, lgtm, sig/azure, size/L

#2539 Fix broken link
  projects/azure/README.md
Labels: approved, lgtm, sig/azure, size/XS

#2542 Remove olm from mirroring due to rename
  cluster/ci/config/mirroring/origin_v4_0
Labels: approved, lgtm, size/XS

#2543 Fix osa config-updater
  projects/azure/config-updater/config-updater.yaml
Labels: approved, lgtm, sig/azure, size/XS

#2544 Mirror the new prometheus adapter images
  Makefile
  cluster/ci/config/mirroring/origin_v4_0_quay
Labels: approved, lgtm, size/XS

#2545 [09-01-2019 17:54:15] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  cluster/ci/config/prow/openshift/tracer.yaml
  hack/bump-prow-images.sh
Labels: approved, lgtm, size/M

#2541 Setup cluster-config-operator
  ci-operator/config/openshift/cluster-config-operator/OWNERS
  ci-operator/config/openshift/cluster-config-operator/openshift-cluster-config-operator-master.yaml
  ci-operator/jobs/openshift/cluster-config-operator/OWNERS
  ci-operator/jobs/openshift/cluster-config-operator/openshift-cluster-config-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-config-operator/openshift-cluster-config-operator-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#2546 add /test e2e-aws to logging repos
  .gitignore
  ci-operator/config/openshift/cluster-logging-operator/openshift-cluster-logging-operator-master.yaml
  ci-operator/config/openshift/elasticsearch-operator/openshift-elasticsearch-operator-master.yaml
  ci-operator/config/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-master.yaml
  ci-operator/jobs/openshift/cluster-logging-operator/openshift-cluster-logging-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/elasticsearch-operator/openshift-elasticsearch-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-master-presubmits.yaml
Labels: approved, lgtm, size/L

#2550 OSA doc fixes
  projects/azure/README.md
Labels: approved, lgtm, sig/azure, size/S

#2551 Owners
  ci-operator/config/openshift/azure-misc/OWNERS
  ci-operator/config/openshift/openshift-azure/OWNERS
  ci-operator/jobs/openshift/azure-misc/OWNERS
  ci-operator/jobs/openshift/openshift-azure/OWNERS
  ci-operator/templates/openshift/openshift-azure/OWNERS
  projects/azure/OWNERS
  projects/azure/cluster-wide.yaml
Labels: approved, lgtm, sig/azure, size/S

#2553 cincinnati: add lucab to approvers
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#2540 ci-operator/config: monitoring image config cleanup
  ci-operator/config/openshift/cluster-monitoring-operator/openshift-cluster-monitoring-operator-master.yaml
  ci-operator/config/openshift/cluster-monitoring-operator/openshift-cluster-monitoring-operator-release-3.11.yaml
  ci-operator/config/openshift/configmap-reload/openshift-configmap-reload-master.yaml
  ci-operator/config/openshift/grafana/openshift-grafana-master.yaml
  ci-operator/config/openshift/k8s-prometheus-adapter/openshift-k8s-prometheus-adapter-master.yaml
  ci-operator/config/openshift/kube-rbac-proxy/openshift-kube-rbac-proxy-master.yaml
  ci-operator/config/openshift/kube-state-metrics/openshift-kube-state-metrics-master.yaml
  ci-operator/config/openshift/node_exporter/openshift-node_exporter-master.yaml
  ci-operator/config/openshift/oauth-proxy/openshift-oauth-proxy-master.yaml
  ci-operator/config/openshift/prometheus-alertmanager/openshift-prometheus-alertmanager-master.yaml
  ci-operator/config/openshift/prometheus-alertmanager/openshift-prometheus-alertmanager-release-3.11.yaml
  ci-operator/config/openshift/prometheus-operator/openshift-prometheus-operator-master.yaml
  ci-operator/config/openshift/prometheus/openshift-prometheus-master.yaml
  ci-operator/config/openshift/prometheus/openshift-prometheus-release-3.11.yaml
  ci-operator/jobs/openshift/prom-label-proxy/OWNERS
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/M

#2549 ci-operator/templates/openshift: Finish machineCIDR transition
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e-40.yaml
Labels: approved, lgtm, size/XS

#2547 Add e2e-aws for cloud-credential-operator.
  ci-operator/config/openshift/cloud-credential-operator/openshift-cloud-credential-operator-master.yaml
  ci-operator/jobs/openshift/cloud-credential-operator/openshift-cloud-credential-operator-master-presubmits.yaml
Labels: approved, lgtm, size/L

#2558 [10-01-2019 17:40:07] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  cluster/ci/config/prow/openshift/tracer.yaml
Labels: approved, lgtm, size/M

#2561 Drop non-existent e2e-aws-operator tests.
  ci-operator/config/openshift/cloud-credential-operator/openshift-cloud-credential-operator-master.yaml
Labels: approved, lgtm, size/XS

#2562 Drop missed pre-submit job.
  ci-operator/jobs/openshift/cloud-credential-operator/openshift-cloud-credential-operator-master-presubmits.yaml
Labels: approved, lgtm, size/M

#2563 BYOR 4.0: provision n1-highcpu-8 for masters
  cluster/test-deploy/gcp-4.0/vars.yaml
Labels: approved, lgtm, size/XS

#2559 ci-operator/templates/openshift: specify version
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e-40.yaml
Labels: approved, lgtm, size/XS

#2554 promote 0.2 releases to a different tag to distinguish from master
  ci-operator/config/openshift/knative-build/openshift-knative-build-release-0.2.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-0.2.yaml
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-0.2.yaml
Labels: approved, lgtm, size/XS

#2565 OSA docs updates
  projects/azure/README.md
Labels: approved, lgtm, sig/azure, size/M

#2566 More OSA docs
  Makefile
  projects/azure/README.md
  projects/azure/cluster-wide.yaml
Labels: approved, lgtm, sig/azure, size/S

#2548 add e2e-aws tests for all monitoring images
  ci-operator/config/openshift/configmap-reload/openshift-configmap-reload-master.yaml
  ci-operator/config/openshift/grafana/openshift-grafana-master.yaml
  ci-operator/config/openshift/k8s-prometheus-adapter/openshift-k8s-prometheus-adapter-master.yaml
  ci-operator/config/openshift/kube-rbac-proxy/openshift-kube-rbac-proxy-master.yaml
  ci-operator/config/openshift/kube-state-metrics/openshift-kube-state-metrics-master.yaml
  ci-operator/config/openshift/node_exporter/openshift-node_exporter-master.yaml
  ci-operator/config/openshift/oauth-proxy/openshift-oauth-proxy-master.yaml
  ci-operator/config/openshift/prom-label-proxy/openshift-prom-label-proxy-master.yaml
  ci-operator/config/openshift/prometheus-alertmanager/openshift-prometheus-alertmanager-master.yaml
  ci-operator/config/openshift/prometheus-operator/openshift-prometheus-operator-master.yaml
  ci-operator/config/openshift/prometheus/openshift-prometheus-master.yaml
  ci-operator/config/openshift/telemeter/openshift-telemeter-master.yaml
  ci-operator/jobs/openshift/configmap-reload/openshift-configmap-reload-master-presubmits.yaml
  ci-operator/jobs/openshift/grafana/openshift-grafana-master-presubmits.yaml
  ci-operator/jobs/openshift/k8s-prometheus-adapter/openshift-k8s-prometheus-adapter-master-presubmits.yaml
  ci-operator/jobs/openshift/kube-rbac-proxy/openshift-kube-rbac-proxy-master-presubmits.yaml
  ci-operator/jobs/openshift/kube-state-metrics/openshift-kube-state-metrics-master-presubmits.yaml
  ci-operator/jobs/openshift/node_exporter/openshift-node_exporter-master-presubmits.yaml
  ci-operator/jobs/openshift/oauth-proxy/openshift-oauth-proxy-master-presubmits.yaml
  ci-operator/jobs/openshift/prom-label-proxy/openshift-prom-label-proxy-master-presubmits.yaml
  ci-operator/jobs/openshift/prometheus-alertmanager/openshift-prometheus-alertmanager-master-presubmits.yaml
  ci-operator/jobs/openshift/prometheus-operator/openshift-prometheus-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/prometheus/openshift-prometheus-master-presubmits.yaml
  ci-operator/jobs/openshift/telemeter/openshift-telemeter-master-presubmits.yaml
Labels: approved, lgtm, size/XL

#2568 Another doc fix
  projects/azure/README.md
Labels: approved, lgtm, sig/azure, size/XS

#2569 Update location for tsb-operator Dockerfile
  ci-operator/config/openshift/template-service-broker-operator/openshift-template-service-broker-operator-master.yaml
Labels: approved, lgtm, size/XS

#2567 Prow jobs and ci-operator configs for openshift-knative-eventing-sources
  OWNERS_ALIASES
  ci-operator/config/openshift/knative-eventing-sources/OWNERS
  ci-operator/config/openshift/knative-eventing-sources/openshift-knative-eventing-sources-master.yaml
  ci-operator/jobs/openshift/knative-eventing-sources/OWNERS
  ci-operator/jobs/openshift/knative-eventing-sources/openshift-knative-eventing-sources-master-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing-sources/openshift-knative-eventing-sources-master-presubmits.yaml
  ci-operator/jobs/openshift/knative-eventing-sources/openshift-knative-eventing-sources-periodics.yaml
Labels: approved, lgtm, size/L

#2575 Fix knative-eventing-sources image names
  ci-operator/config/openshift/knative-eventing-sources/openshift-knative-eventing-sources-master.yaml
Labels: approved, lgtm, size/S

#2576 ci-operator/jobs/openshift/machine-config-operator: skip docs/ changes
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#2578 Update OSA docs
  projects/azure/README.md
Labels: approved, lgtm, sig/azure, size/M

#2573 BYOR 4.0: add missing exit 0 when TEST_SKIP is specified
  ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e-40.yaml
Labels: approved, lgtm, size/XS

#2574 Use origin-v3.11:base as the base image for knative images
  ci-operator/config/openshift/knative-build/openshift-knative-build-master.yaml
  ci-operator/config/openshift/knative-build/openshift-knative-build-release-0.2.yaml
  ci-operator/config/openshift/knative-eventing-sources/openshift-knative-eventing-sources-master.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-master.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-0.2.yaml
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-master.yaml
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-0.2.yaml
Labels: approved, lgtm, size/L

#2588 Use getting started docs for linking to prow
  projects/azure/README.md
Labels: approved, kind/documentation, lgtm, sig/azure, size/XS

#2585 Add codecov job for openshift-azure
  Makefile
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
  cluster/ci/config/secret-mirroring/mapping.yaml
  projects/azure/README.md
Labels: approved, lgtm, sig/azure, size/M

#2589 Fix codecov job pullspec
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/XS

#2590 Pass --candidate-path to rehearse tool
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#2591 Sync ConfigMaps in the staging namespace
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/S

#2582 remove gitlab as a required check on OLM
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/XS

#2597 Add a trigger-only job to demo rehearsals
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
Labels: approved, lgtm, size/M

#2599 Format additional namespaces correctly
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/M

#2598 Add a new required job for ci-operator
  ci-operator/config/openshift/ci-operator/openshift-ci-operator-master.yaml
  ci-operator/jobs/openshift/ci-operator/openshift-ci-operator-master-presubmits.yaml
Labels: approved, lgtm, size/M

#2584 Adding new secret for registry.redhat.io
  Makefile
  ci-operator/SECRETS.md
  cluster/test-deploy/azure/.gitignore
  projects/azure/README.md
Labels: approved, lgtm, sig/azure, size/M

#2602 More codecov job fixes
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
  projects/azure/base-images/test-base.yaml
Labels: approved, lgtm, sig/azure, size/XS

#2603 Rename configmap-reload output image to configmap-reloader
  ci-operator/config/openshift/configmap-reload/openshift-configmap-reload-master.yaml
Labels: approved, lgtm, size/XS

#2604 Remove systemd-devel test dependency
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
  projects/azure/base-images/test-base.yaml
Labels: approved, lgtm, sig/azure, size/XS

#2605 Switch to configmap-reloader
  cluster/ci/config/mirroring/origin_v3_10
  cluster/ci/config/mirroring/origin_v4_0_quay
Labels: approved, lgtm, size/XS

#2607 Use `oc adm node-logs` to gather logs from the cluster in 4.0 on
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e-40.yaml
Labels: approved, lgtm, size/M

#2580 [KIECLOUD-93] Add kie-cloud-operator config and jobs
  ci-operator/config/kiegroup/kie-cloud-operator/OWNERS
  ci-operator/config/kiegroup/kie-cloud-operator/kiegroup-kie-cloud-operator-master.yaml
  ci-operator/jobs/kiegroup/kie-cloud-operator/OWNERS
  ci-operator/jobs/kiegroup/kie-cloud-operator/kiegroup-kie-cloud-operator-master-postsubmits.yaml
  ci-operator/jobs/kiegroup/kie-cloud-operator/kiegroup-kie-cloud-operator-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#2610 Add gburges to cluster-wide.yaml
  projects/azure/cluster-wide.yaml
Labels: approved, lgtm, sig/azure, size/XS

#2600 Prow jobs and ci-operator config for knative-eventing-sources release…
  ci-operator/config/openshift/knative-eventing-sources/openshift-knative-eventing-sources-release-0.2.yaml
  ci-operator/jobs/openshift/knative-eventing-sources/openshift-knative-eventing-sources-periodics.yaml
  ci-operator/jobs/openshift/knative-eventing-sources/openshift-knative-eventing-sources-release-0.2-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing-sources/openshift-knative-eventing-sources-release-0.2-presubmits.yaml
Labels: approved, lgtm, size/L

#2606 machine-config-operator: Use `make test-unit`
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-master.yaml
Labels: approved, lgtm, size/XS

#2611 add kiegroup in triggers
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#2560 update tsb operator merge method
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/XS

#2612 [16-01-2019 17:01:53] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  cluster/ci/config/prow/openshift/tracer.yaml
  hack/bump-prow-images.sh
Labels: approved, lgtm, size/M

#2577 machine-config-operator: Add e2e-aws-op job
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-master.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-master-presubmits.yaml
Labels: approved, lgtm, size/M

#2614 Grab the prometheus database in teardown
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e-40.yaml
Labels: approved, lgtm, size/S

#2615 Additional Prow config for knative-eventing-sources repo
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#2579 rename cluster-osin-operator to cluster-authentication-operator
  ci-operator/config/openshift/cluster-authentication-operator/OWNERS
  ci-operator/config/openshift/cluster-authentication-operator/openshift-cluster-authentication-operator-master.yaml
  ci-operator/jobs/openshift/cluster-authentication-operator/OWNERS
  ci-operator/jobs/openshift/cluster-authentication-operator/openshift-cluster-authentication-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-authentication-operator/openshift-cluster-authentication-operator-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/M

#2617 [KIECLOUD-93] Update kie-cloud-operator config
  ci-operator/config/kiegroup/kie-cloud-operator/kiegroup-kie-cloud-operator-master.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/S

#2620 Copying new secret to src location
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure.yaml
Labels: approved, lgtm, sig/azure, size/S

#2622 Fixing typo
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure.yaml
Labels: approved, lgtm, sig/azure, size/XS

#2623 noop
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure.yaml
Labels: approved, lgtm, sig/azure, size/XS

#2282 Initial CI operator configuration for openshift/federation-v2-operator
  ci-operator/config/openshift/federation-v2-operator/OWNERS
  ci-operator/config/openshift/federation-v2-operator/openshift-federation-v2-operator-master.yaml
  ci-operator/jobs/openshift/federation-v2-operator/OWNERS
  ci-operator/jobs/openshift/federation-v2-operator/openshift-federation-v2-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/federation-v2-operator/openshift-federation-v2-operator-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, sig/azure, size/L

#2618 [KIECLOUD-93] Use inputs
  ci-operator/config/kiegroup/kie-cloud-operator/kiegroup-kie-cloud-operator-master.yaml
  ci-operator/jobs/kiegroup/kie-cloud-operator/kiegroup-kie-cloud-operator-master-postsubmits.yaml
  ci-operator/jobs/kiegroup/kie-cloud-operator/kiegroup-kie-cloud-operator-master-presubmits.yaml
Labels: approved, lgtm, size/S

#2587 autoscaler: add e2e tests execution
  ci-operator/config/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-master.yaml
  ci-operator/jobs/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-master-presubmits.yaml
Labels: approved, lgtm, size/M

#2570 Configs for Multus CNI, SR-IOV device plugins and ancillary components
  ci-operator/config/openshift/containernetworking-plugins/OWNERS
  ci-operator/config/openshift/containernetworking-plugins/openshift-containernetworking-plugins-master.yaml
  ci-operator/config/openshift/multus-admission-controller/OWNERS
  ci-operator/config/openshift/multus-admission-controller/openshift-multus-admission-controller-master.yaml
  ci-operator/config/openshift/multus-cni/OWNERS
  ci-operator/config/openshift/multus-cni/openshift-multus-cni-master.yaml
  ci-operator/config/openshift/sriov-cni/OWNERS
  ci-operator/config/openshift/sriov-cni/openshift-sriov-cni-master.yaml
  ci-operator/config/openshift/sriov-dp-admission-controller/OWNERS
  ci-operator/config/openshift/sriov-dp-admission-controller/openshift-sriov-dp-admission-controller-master.yaml
  ci-operator/config/openshift/sriov-network-device-plugin/OWNERS
  ci-operator/config/openshift/sriov-network-device-plugin/openshift-sriov-network-device-plugin-master.yaml
  ci-operator/jobs/openshift/containernetworking-plugins/OWNERS
  ci-operator/jobs/openshift/containernetworking-plugins/openshift-containernetworking-plugins-master-postsubmits.yaml
  ci-operator/jobs/openshift/containernetworking-plugins/openshift-containernetworking-plugins-master-presubmits.yaml
  ci-operator/jobs/openshift/multus-admission-controller/OWNERS
  ci-operator/jobs/openshift/multus-admission-controller/openshift-multus-admission-controller-master-postsubmits.yaml
  ci-operator/jobs/openshift/multus-admission-controller/openshift-multus-admission-controller-master-presubmits.yaml
  ci-operator/jobs/openshift/multus-cni/OWNERS
  ci-operator/jobs/openshift/multus-cni/openshift-multus-cni-master-postsubmits.yaml
  ci-operator/jobs/openshift/multus-cni/openshift-multus-cni-master-presubmits.yaml
  ci-operator/jobs/openshift/sriov-cni/OWNERS
  ci-operator/jobs/openshift/sriov-cni/openshift-sriov-cni-master-postsubmits.yaml
  ci-operator/jobs/openshift/sriov-cni/openshift-sriov-cni-master-presubmits.yaml
  ci-operator/jobs/openshift/sriov-dp-admission-controller/OWNERS
  ci-operator/jobs/openshift/sriov-dp-admission-controller/openshift-sriov-dp-admission-controller-master-postsubmits.yaml
  ci-operator/jobs/openshift/sriov-dp-admission-controller/openshift-sriov-dp-admission-controller-master-presubmits.yaml
  ci-operator/jobs/openshift/sriov-network-device-plugin/OWNERS
  ci-operator/jobs/openshift/sriov-network-device-plugin/openshift-sriov-network-device-plugin-master-postsubmits.yaml
  ci-operator/jobs/openshift/sriov-network-device-plugin/openshift-sriov-network-device-plugin-master-presubmits.yaml
Labels: approved, lgtm, size/XXL

#2626 [KIECLOUD-93] Add more tests and fix build
  ci-operator/config/kiegroup/kie-cloud-operator/kiegroup-kie-cloud-operator-master.yaml
  ci-operator/jobs/kiegroup/kie-cloud-operator/kiegroup-kie-cloud-operator-master-presubmits.yaml
Labels: approved, lgtm, size/L

#2627 [KIECLOUD-93] Fix build
  ci-operator/config/kiegroup/kie-cloud-operator/kiegroup-kie-cloud-operator-master.yaml
Labels: approved, lgtm, size/XS

#2628 [KIECLOUD-93] Fix build
  ci-operator/config/kiegroup/kie-cloud-operator/kiegroup-kie-cloud-operator-master.yaml
Labels: approved, lgtm, size/XS

#2629 Allow users to see logs in the staging namespace
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
Labels: approved, lgtm, size/XS

#2625 OWNERS file refs change osin|authentication in comment
  ci-operator/config/openshift/cluster-authentication-operator/OWNERS
  ci-operator/jobs/openshift/cluster-authentication-operator/OWNERS
Labels: approved, lgtm, size/XS

#2572 populate-owners: resolve owner aliases
  ci-operator/populate-owners.sh
  tools/populate-owners/README.md
  tools/populate-owners/main.go
  tools/populate-owners/main_test.go
Labels: approved, lgtm, size/L

#2369 Installer: collect CSRs in artifacts
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e-40.yaml
Labels: approved, lgtm, size/XS

#2634 tnozicka/openshift-acme: Customize build_root
  ci-operator/config/tnozicka/openshift-acme/tnozicka-openshift-acme-master.yaml
Labels: approved, lgtm, size/S

#2639 Point to forum-testplatform for infra-related issues
  projects/azure/README.md
Labels: approved, lgtm, sig/azure, size/XS

#2636 knative-serving release-0.2 branch on OKD 4
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-0.2__v4.0.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-0.2-postsubmits.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-0.2-presubmits.yaml
Labels: approved, lgtm, size/L

#2640 Document all OSA secrets
  projects/azure/README.md
Labels: approved, lgtm, sig/azure, size/S

#2642 Better markdown and image build instructions
  projects/azure/README.md
Labels: approved, lgtm, sig/azure, size/M

#2641 Enabling admission webhooks is now optional
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-0.2__v4.0.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-0.2-presubmits.yaml
Labels: approved, lgtm, size/XS

#2644 BYOR: specify RPM_REPO_DEPENDENCIES in upgrade tests
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-3.10-presubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-3.11-presubmits.yaml
  ci-operator/templates/cluster-launch-e2e-upgrade.yaml
Labels: approved, lgtm, size/XS

#2646 Add kiegroup namespace and permissions
  cluster/ci/config/roles.yaml
Labels: approved, lgtm, size/M

#2647 Grab the clusters kube-apiserver audit log
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e-40.yaml
Labels: approved, lgtm, size/S

#2630 [KIECLOUD-93] Promote kie-cloud-operator images
  ci-operator/config/kiegroup/kie-cloud-operator/kiegroup-kie-cloud-operator-master.yaml
Labels: approved, lgtm, size/XS

#2657 fix jenkins rhel images job
  ci-operator/config/openshift/jenkins/openshift-jenkins-master__rhel.yaml
Labels: approved, lgtm, size/XS

#2659 make jenkins rhel imag job optional
  ci-operator/config/openshift/jenkins/openshift-jenkins-master__rhel.yaml
  ci-operator/jobs/openshift/jenkins/openshift-jenkins-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#2654 Fed-v2: comment config
  ci-operator/config/openshift/federation-v2-operator/openshift-federation-v2-operator-master.yaml
Labels: approved, lgtm, size/S

#2633 templates/openshift: grab bootstrap log on failure
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
Labels: approved, lgtm, size/M

#2661 Mirror jenkins
  cluster/ci/config/mirroring/origin_v4_0_quay
Labels: approved, lgtm, size/XS

#2662 make jenkins slave base non-optional
  ci-operator/config/openshift/jenkins/openshift-jenkins-master.yaml
Labels: approved, lgtm

#2643 Remove OSA config-updater
  Makefile
  cluster/ci/config/prow/plugins.yaml
  projects/azure/README.md
  projects/azure/config-updater/config-updater.yaml
Labels: approved, lgtm, sig/azure, size/L

#2665 Quay robot needs write perms to mirrored images
  projects/azure/README.md
Labels: approved, lgtm, sig/azure, size/S

#2637 BYOR 4.0: test RHEL nodes scaleup in AWS
  Makefile
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-devel-40-presubmits.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-scaleup-e2e-40.yaml
  cluster/test-deploy/aws-4.0/vars-origin.yaml
  cluster/test-deploy/aws-4.0/vars.yaml
Labels: approved, lgtm, size/XL

#2667 BYOR 4.0 scaleup: use matching template name
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-devel-40-presubmits.yaml
Labels: approved, lgtm, size/XS

#2668 BYOR 4.0: Skip more tests to make mco --once-from branch pass tests
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-devel-40.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-devel-40-presubmits.yaml
Labels: approved, lgtm, size/XS

#2671 BYOR 4.0 scaleup: fix cluster profile secret name
  ci-operator/templates/openshift/openshift-ansible/cluster-scaleup-e2e-40.yaml
Labels: approved, lgtm, size/XS

#2674 Improve OSA docs
  projects/azure/README.md
Labels: approved, lgtm, sig/azure, size/S

#2675 Use common base image for knative-serving variants
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-0.2__v4.0.yaml
Labels: approved, lgtm, size/XS

#2660 fed-v2: add managed e2e tests
  ci-operator/config/openshift/federation-v2-operator/openshift-federation-v2-operator-master.yaml
  ci-operator/jobs/openshift/federation-v2-operator/openshift-federation-v2-operator-master-presubmits.yaml
Labels: approved, lgtm, size/M

#2380 Move console e2e tests to prow from jenkins
  ci-operator/config/openshift/console/openshift-console-master.yaml
  ci-operator/jobs/openshift/console/openshift-console-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/M

#2677 make agent names consistent
  ci-operator/config/openshift/jenkins/openshift-jenkins-master.yaml
  ci-operator/config/openshift/jenkins/openshift-jenkins-master__rhel.yaml
Labels: approved, lgtm, size/S

#2678 jenkins agent renames
  ci-operator/config/openshift/jenkins/openshift-jenkins-master.yaml
  ci-operator/config/openshift/jenkins/openshift-jenkins-master__rhel.yaml
Labels: approved, lgtm, size/S

#2679 Mirror new jenkins images
  cluster/ci/config/mirroring/origin_v4_0_quay
Labels: approved, lgtm, size/XS

#2650 add more resources to get collected
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e-40.yaml
Labels: approved, lgtm, size/S

#2664 autoscaler: enable e2e tests
  ci-operator/config/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-master.yaml
  ci-operator/jobs/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#2685 Document OSA templates
  projects/azure/README.md
Labels: approved, lgtm, sig/azure, size/XS
