Repository openshift/release, pull requests merged in 2019-05, with the labels that each got.

#3649 The release promotion periodic can be conditional and no-op if no change
  ci-operator/infra/openshift/release-controller/releases/release-ocp-4.1-ci.json
  ci-operator/infra/openshift/release-controller/releases/release-ocp-4.1.json
  ci-operator/jobs/openshift/release/openshift-release-release-4.1-periodics.yaml
Labels: approved, lgtm, size/M

#3650 Reduce promote to something copy and pastable
  ci-operator/jobs/openshift/release/openshift-release-release-4.1-periodics.yaml
Labels: approved, lgtm, size/S

#3646 openstack: update flavor to have larger disk
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e.yaml
Labels: approved, lgtm, size/XS

#3651 aro - fix periodic
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-periodics.yaml
Labels: approved, lgtm, sig/azure, size/M

#3615 ci-operator/templates/openshift: Drop us-east-1c
  ci-operator/templates/openshift/installer/cluster-launch-installer-console.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-scaleup-e2e-40.yaml
Labels: approved, lgtm, size/XS

#3652 Add PVC for prometheus in prow-monitoring
  cluster/ci/monitoring/prometheus_crd.yaml
Labels: approved, lgtm, size/S

#3658 Request a more reasonable amount of memory for pruning images on api.ci
  cluster/ci/jobs/image-pruner.yaml
Labels: approved, lgtm, size/XS

#3659 azure: HACK: duplicate template for v4 to work around brokenness
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v4-presubmits.yaml
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure-v4.yaml
Labels: approved, lgtm, sig/azure, size/L

#3660 Revert "azure: HACK: duplicate template for v4 to work around brokenness"
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v4-presubmits.yaml
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure-v4.yaml
Labels: approved, lgtm, sig/azure, size/L

#3661 azure: HACK: deal with release-v4 build brokenness after move to single image
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v3-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v4-presubmits.yaml
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure.yaml
Labels: approved, lgtm, sig/azure, size/M

#3662 fix test order
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure.yaml
Labels: approved, lgtm, sig/azure, size/XS

#3656 azure: add v4.3 to release
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-periodics.yaml
  projects/azure/RELEASES.md
Labels: approved, lgtm, sig/azure, size/M

#3640 openshift/cluster-kube-apiserver-operator: raise memory for unit tests compilation
  ci-operator/config/openshift/cluster-kube-apiserver-operator/openshift-cluster-kube-apiserver-operator-master.yaml
  ci-operator/config/openshift/cluster-kube-apiserver-operator/openshift-cluster-kube-apiserver-operator-release-4.1.yaml
Labels: approved, lgtm, sig/master, size/XS

#3665 Add labels on tide servcie
  cluster/ci/config/prow/openshift/tide.yaml
Labels: approved, lgtm, size/XS

#3655 Update setup in rhel scaleup template to match e2e-aws template.
  ci-operator/templates/openshift/openshift-ansible/cluster-scaleup-e2e-40.yaml
Labels: approved, lgtm, size/L

#3591 e2e-vsphere: use vm template built from ova
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
Labels: approved, lgtm, size/S

#3667 [02-05-2019 15:52:28] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
Labels: approved, lgtm, size/L

#3668 Enable pushing metrics for tide
  cluster/ci/config/prow/openshift/tide.yaml
Labels: approved, lgtm, size/XS

#3670 Revert "Enable pushing metrics for tide"
  cluster/ci/config/prow/openshift/tide.yaml
Labels: approved, lgtm, size/XS

#3625 network-operator: Don't run upgrade tests on docs changes.
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#3669 add ghproxy grafana dashboard
  cluster/ci/config/prow/plugins.yaml
  cluster/ci/monitoring/Makefile
  cluster/ci/monitoring/dashboards.yaml
  cluster/ci/monitoring/ghproxy.json
  cluster/ci/monitoring/grafana_deploy.yaml
Labels: approved, lgtm, size/XL

#3672 Add push_gateway section into prow config
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/XS

#3666 Use operator-registry base image
  ci-operator/config/redhat-developer/devconsole-operator/redhat-developer-devconsole-operator-master.yaml
Labels: approved, lgtm, size/S

#3673 Build dashboards-validation image
  Makefile
  projects/origin-release/dashboards-validation/Dockerfile
  projects/origin-release/dashboards-validation/dashboards-validation.yaml
Labels: approved, lgtm, size/M

#3671 update CNO owners
  ci-operator/config/openshift/cluster-network-operator/OWNERS
  ci-operator/jobs/openshift/cluster-network-operator/OWNERS
Labels: approved, lgtm, size/S

#3664 Enable mixins in prow-monitoring
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  cluster/ci/monitoring/Makefile
  cluster/ci/monitoring/README.md
  cluster/ci/monitoring/mixins/.gitignore
  cluster/ci/monitoring/mixins/Makefile
  cluster/ci/monitoring/mixins/grafana_dashboards/sinker.jsonnet
  cluster/ci/monitoring/mixins/jsonnetfile.json
  cluster/ci/monitoring/sinker.json
  hack/validate-generated-dashboards.sh
Labels: approved, lgtm, size/XL

#3644 openstack: Add openstack-e2e job to search
  ci-operator/infra/openshift/ci-search/config.yaml
Labels: approved, lgtm, size/XS

#3677 Remove debug logging from org sync
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
Labels: approved, lgtm, size/XS

#3674 configs/installer: add verify-vendor test
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
Labels: approved, lgtm, size/M

#3676 Add serviceMonitor pushgateway to prow-monitoring
  cluster/ci/monitoring/Makefile
  cluster/ci/monitoring/pushgateway_service_monitor.yaml
Labels: approved, lgtm, size/S

#3637 onboard toolchain-operator to use openshift ci
  ci-operator/config/fabric8-services/toolchain-operator/OWNERS
  ci-operator/config/fabric8-services/toolchain-operator/fabric8-services-toolchain-operator-master.yaml
  ci-operator/jobs/fabric8-services/toolchain-operator/OWNERS
  ci-operator/jobs/fabric8-services/toolchain-operator/fabric8-services-toolchain-operator-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#3680 Remove nightly for eventing 0.2 and fix 0.5
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-periodics.yaml
Labels: approved, lgtm, size/M

#3681 Generate debug-grafana password on the fly
  cluster/ci/monitoring/Makefile
  cluster/ci/monitoring/README.md
Labels: approved, lgtm, size/XS

#3684 Add a custom OAuth error page with links to docs
  cluster/ci/config/page-templates/oauth-error.html
Labels: approved, lgtm, size/M

#3682 Add ci config for knative-serving release v0.5.2
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-v0.5.2.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-v0.5.2-postsubmits.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-v0.5.2-presubmits.yaml
Labels: approved, lgtm, size/L

#3634 Create target to run OLM e2e test
  ci-operator/config/redhat-developer/devconsole-operator/redhat-developer-devconsole-operator-master.yaml
  ci-operator/jobs/redhat-developer/devconsole-operator/redhat-developer-devconsole-operator-master-presubmits.yaml
Labels: approved, lgtm, ok-to-test, size/M

#3686 Make the custom OAuth message prettier
  cluster/ci/config/page-templates/oauth-error.html
Labels: approved, lgtm, size/XXL

#3690 Fix master-sidecar-4 after SCC changes to localup
  ci-operator/infra/openshift/release-controller/deploy-ocp-publish-art.yaml
  ci-operator/templates/master-sidecar-4.yaml
Labels: approved, lgtm

#3685 Adding release next jobs and config for knatve-evening "next" branch
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-next-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-next-presubmits.yaml
Labels: approved, lgtm, size/L

#3693 BUG 1706400 : ci-operator/config/openshift/etcd: use coreos org for canonical
  ci-operator/config/openshift/etcd/openshift-etcd-openshift-4.0.yaml
  ci-operator/config/openshift/etcd/openshift-etcd-openshift-4.1.yaml
  ci-operator/config/openshift/etcd/openshift-etcd-openshift-4.2.yaml
Labels: approved, lgtm, size/XS

#3689 Add tide dashboard
  cluster/ci/config/prow/plugins.yaml
  cluster/ci/monitoring/Makefile
  cluster/ci/monitoring/dashboards.yaml
  cluster/ci/monitoring/grafana_deploy.yaml
  cluster/ci/monitoring/mixins/Makefile
  cluster/ci/monitoring/mixins/grafana_dashboards/tide.jsonnet
  cluster/ci/monitoring/tide.json
Labels: approved, lgtm, size/XL

#3696 Remove build as a distinct test target
  ci-operator/config/redhat-developer/devconsole-operator/redhat-developer-devconsole-operator-master.yaml
  ci-operator/jobs/redhat-developer/devconsole-operator/redhat-developer-devconsole-operator-master-presubmits.yaml
Labels: approved, lgtm, size/M

#3695 For now, we use Openshift 4.0
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next.yaml
Labels: approved, lgtm

#3699 [06-05-2019 16:23:45] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
Labels: approved, lgtm, size/L

#3182 Remove stale generated postsubmits
  ci-operator/jobs/openshift/cluster-capacity/openshift-cluster-capacity-release-3.10-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-capacity/openshift-cluster-capacity-release-3.11-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-monitoring-operator/openshift-cluster-monitoring-operator-release-3.11-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-version-operator/openshift-cluster-version-operator-release-3.11-postsubmits.yaml
  ci-operator/jobs/openshift/console/openshift-console-release-3.11-postsubmits.yaml
  ci-operator/jobs/openshift/descheduler/openshift-descheduler-release-3.10-postsubmits.yaml
  ci-operator/jobs/openshift/descheduler/openshift-descheduler-release-3.11-postsubmits.yaml
  ci-operator/jobs/openshift/image-registry/openshift-image-registry-release-3.10-postsubmits.yaml
  ci-operator/jobs/openshift/image-registry/openshift-image-registry-release-3.11-postsubmits.yaml
  ci-operator/jobs/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-release-3.10-postsubmits.yaml
  ci-operator/jobs/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-release-3.11-postsubmits.yaml
  ci-operator/jobs/openshift/kubernetes-metrics-server/openshift-kubernetes-metrics-server-release-3.10-postsubmits.yaml
  ci-operator/jobs/openshift/kubernetes-metrics-server/openshift-kubernetes-metrics-server-release-3.11-postsubmits.yaml
  ci-operator/jobs/openshift/node_exporter/openshift-node_exporter-release-3.11-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-3.10-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-3.11-postsubmits.yaml
  ci-operator/jobs/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-release-3.11-postsubmits.yaml
  ci-operator/jobs/openshift/origin-metrics/openshift-origin-metrics-release-3.10-postsubmits.yaml
  ci-operator/jobs/openshift/origin-metrics/openshift-origin-metrics-release-3.11-postsubmits.yaml
  ci-operator/jobs/openshift/origin-web-console-server/openshift-origin-web-console-server-release-3.10-postsubmits.yaml
  ci-operator/jobs/openshift/origin-web-console-server/openshift-origin-web-console-server-release-3.11-postsubmits.yaml
  ci-operator/jobs/openshift/prometheus-alertmanager/openshift-prometheus-alertmanager-release-3.11-postsubmits.yaml
  ci-operator/jobs/openshift/prometheus/openshift-prometheus-release-3.11-postsubmits.yaml
  ci-operator/jobs/openshift/service-catalog/openshift-service-catalog-release-3.11-postsubmits.yaml
  ci-operator/jobs/openshift/telemeter/openshift-telemeter-release-3.11-postsubmits.yaml
  ci-operator/jobs/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-release-3.11-postsubmits.yaml
Labels: approved, lgtm, size/XL

#3692 Add more panels into sinker dashboard
  cluster/ci/monitoring/mixins/grafana_dashboards/sinker.jsonnet
  cluster/ci/monitoring/sinker.json
Labels: approved, lgtm, size/L

#3027 operator-framework/community-operators e2e
  ci-operator/config/operator-framework/community-operators/OWNERS
  ci-operator/config/operator-framework/community-operators/operator-framework-community-operators-master.yaml
  ci-operator/jobs/operator-framework/community-operators/OWNERS
  ci-operator/jobs/operator-framework/community-operators/operator-framework-community-operators-master-presubmits.yaml
Labels: approved, lgtm, size/L

#3702 Knative eventing 0.6 nightly tests
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-periodics.yaml
Labels: approved, lgtm, size/XS

#3703 Switch Plank log viewer config to Spyglass
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/XS

#3708 Revert "Switch Plank log viewer config to Spyglass"
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/XS

#3604 Add jobs for template service broker molecule e2e tests
  ci-operator/config/openshift/template-service-broker-operator/openshift-template-service-broker-operator-master.yaml
  ci-operator/jobs/openshift/template-service-broker-operator/openshift-template-service-broker-operator-master-presubmits.yaml
Labels: approved, lgtm, size/L

#3357 Promote image : devconsole operator
  ci-operator/config/redhat-developer/devconsole-operator/redhat-developer-devconsole-operator-master.yaml
  ci-operator/jobs/redhat-developer/devconsole-operator/redhat-developer-devconsole-operator-master-postsubmits.yaml
Labels: approved, lgtm, size/M

#3714 reflect image changes on upstream master
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next.yaml
Labels: approved, lgtm, size/S

#3715 Adding API k8s source image
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next.yaml
Labels: approved, lgtm, size/XS

#3719 Use prometheus in openshift-monitoring as datasource of debug-grafana
  cluster/ci/monitoring/Makefile
  cluster/ci/monitoring/mixins/Makefile
Labels: approved, lgtm, size/S

#3720 Fast forward to 4.2 branches
  ci-operator/jobs/openshift/release/openshift-release-release-4.1-periodics.yaml
Labels: approved, lgtm, size/XS

#3701 Start tide board allover with pool sizes
  cluster/ci/monitoring/mixins/grafana_dashboards/tide.jsonnet
  cluster/ci/monitoring/tide.json
Labels: approved, lgtm, size/L

#3722 [08-05-2019 15:59:32] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
Labels: approved, lgtm, size/L

#3724 [08-05-2019 18:52:11] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
Labels: approved, lgtm, size/L

#3725 [08-05-2019 20:27:32] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
Labels: approved, lgtm, size/L

#3727 Add new image to Knative Serving.
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-next.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-next-presubmits.yaml
Labels: approved, lgtm, size/S

#3691 minor diff fixes between jenkins and default template; fix passing of focus/skip into ginkgo
  ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e-openshift-jenkins.yaml
Labels: approved, lgtm, size/S

#3710 the 3 jenkins plugins' testing need to be against 4.1 ocp, not 4.0 ocp
  ci-operator/config/openshift/jenkins-client-plugin/openshift-jenkins-client-plugin-master.yaml
  ci-operator/config/openshift/jenkins-openshift-login-plugin/openshift-jenkins-openshift-login-plugin-master.yaml
  ci-operator/config/openshift/jenkins-sync-plugin/openshift-jenkins-sync-plugin-master.yaml
Labels: approved, lgtm, size/S

#3728 Image rename
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next.yaml
Labels: approved, lgtm, size/S

#3729 Adding release-next for eventing-sources
  ci-operator/config/openshift/knative-eventing-sources/openshift-knative-eventing-sources-release-next.yaml
  ci-operator/jobs/openshift/knative-eventing-sources/openshift-knative-eventing-sources-release-next-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing-sources/openshift-knative-eventing-sources-release-next-presubmits.yaml
Labels: approved, lgtm, size/L

#3716 Add CI for cluster-api-provider-gcp
  ci-operator/config/openshift/cluster-api-provider-gcp/OWNERS
  ci-operator/config/openshift/cluster-api-provider-gcp/openshift-cluster-api-provider-gcp-master.yaml
  ci-operator/jobs/openshift/cluster-api-provider-gcp/OWNERS
  ci-operator/jobs/openshift/cluster-api-provider-gcp/openshift-cluster-api-provider-gcp-master-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-gcp/openshift-cluster-api-provider-gcp-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#3723 Add `statusreconciler_rbac.yaml` in `prow_rbac`
  Makefile
Labels: approved, lgtm, needs-ok-to-test, size/XS

#3717 timeout grace_period duration format
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/XS

#3721 Add configMap for hook in prow-monitoring
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#3726 ci-operator/jobs/infra-periodics.yaml: add operator-sdk periodics
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm, size/XS

#3697 Fixup jenkins-related promoting postsubmits
  ci-operator/config/openshift/jenkins-client-plugin/openshift-jenkins-client-plugin-master.yaml
  ci-operator/config/openshift/jenkins-openshift-login-plugin/openshift-jenkins-openshift-login-plugin-master.yaml
  ci-operator/config/openshift/jenkins-sync-plugin/openshift-jenkins-sync-plugin-master.yaml
  ci-operator/jobs/openshift/jenkins-client-plugin/openshift-jenkins-client-plugin-master-postsubmits.yaml
  ci-operator/jobs/openshift/jenkins-openshift-login-plugin/openshift-jenkins-openshift-login-plugin-master-postsubmits.yaml
  ci-operator/jobs/openshift/jenkins-sync-plugin/openshift-jenkins-sync-plugin-master-postsubmits.yaml
Labels: approved, lgtm, size/L

#3730 use C++ version of jsonnet and add more tools
  projects/origin-release/dashboards-validation/Dockerfile
Labels: approved, lgtm, size/S

#3732 Add Hongkai to top-level OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#3694 Generate hook.json for prow-monitoring
  cluster/ci/monitoring/Makefile
  cluster/ci/monitoring/dashboards.yaml
  cluster/ci/monitoring/grafana_deploy.yaml
  cluster/ci/monitoring/hook.json
  cluster/ci/monitoring/mixins/Makefile
  cluster/ci/monitoring/mixins/grafana_dashboards/hook.jsonnet
Labels: approved, lgtm, size/L

#3733 Add configChange trigger on BC dashboards-validation
  projects/origin-release/dashboards-validation/dashboards-validation.yaml
Labels: approved, lgtm, size/XS

#3731 Configuring milestone plugin for odo maintainers
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#3737 Allow sa ci-hook to operate configMaps in prow-monitoring
  cluster/ci/monitoring/Makefile
  cluster/ci/monitoring/ci_hook_rbac.yaml
Labels: approved, lgtm, size/M

#3735 Still fix jenkins 311
  ci-operator/jobs/openshift/jenkins/openshift-jenkins-openshift-3.11-presubmits.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e-openshift-jenkins.yaml
Labels: approved, lgtm, size/XS

#3738 Set up configMap grafana-dashboard-plank
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#3736 Add plank dashboard to grafana in prow-monitoring
  cluster/ci/monitoring/Makefile
  cluster/ci/monitoring/dashboards.yaml
  cluster/ci/monitoring/grafana_deploy.yaml
  cluster/ci/monitoring/jenkins_operator.json
  cluster/ci/monitoring/mixins/Makefile
  cluster/ci/monitoring/mixins/grafana_dashboards/jenkins.jsonnet
  cluster/ci/monitoring/mixins/grafana_dashboards/plank.jsonnet
  cluster/ci/monitoring/plank.json
Labels: approved, lgtm, size/XXL

#3740 Enable gcc env for jsonnet
  projects/origin-release/dashboards-validation/Dockerfile
Labels: approved, lgtm, size/XS

#3743 Remove no longer used image.
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-next.yaml
Labels: approved, lgtm, size/XS

#3741 Update ARO periodic e2e test script to e2e-prod.sh
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-periodics.yaml
Labels: approved, lgtm, sig/azure, size/XS

#3746 Remove moved out image
  ci-operator/config/openshift/knative-eventing-sources/openshift-knative-eventing-sources-release-next.yaml
Labels: approved, lgtm, size/XS

#3742 Adding project plugin config for odo.
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#3745 Populate Sentry DSN secrets from BitWarden
  ci-operator/populate-secrets-from-bitwarden.sh
Labels: approved, lgtm, size/XS

#3747 Enable Console e2e tests on Console Operator
  ci-operator/config/openshift/console-operator/openshift-console-operator-master.yaml
  ci-operator/jobs/openshift/console-operator/openshift-console-operator-master-presubmits.yaml
Labels: approved, lgtm, size/M

#3440 ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e: Initial AWS UPI template
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
Labels: approved, lgtm, size/L

#3754 update to catch up w/ latest master
  ci-operator/config/openshift/knative-eventing-sources/openshift-knative-eventing-sources-release-next.yaml
Labels: approved, lgtm, size/XS

#3757 Use yum to install jsonnet
  projects/origin-release/dashboards-validation/Dockerfile
Labels: approved, lgtm, size/XS

#3744 Artifacts upload logic moved to teardown process
  ci-operator/templates/openshift/installer/cluster-launch-installer-libvirt-e2e.yaml
Labels: approved, lgtm, size/M

#3762 Fix pull spec for 4.1 RPMs
  ci-operator/infra/openshift/origin/artifacts-release-4.1.yaml
Labels: approved, lgtm, size/XS

#3763 Add config updater entries for 4.3 configs
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/S

#3756 Populate slack-api-url with bitwarden script
  ci-operator/populate-secrets-from-bitwarden.sh
Labels: approved, lgtm, size/XS

#3768 Update fast-forwarding for dev branch cutover
  ci-operator/jobs/openshift/release/openshift-release-release-4.1-periodics.yaml
Labels: approved, lgtm, size/XS

#3769 Rename secret slack-api-url to ci-slack-api-url
  ci-operator/populate-secrets-from-bitwarden.sh
Labels: approved, lgtm, size/XS

#3749 Increase memory limit for console build
  ci-operator/config/openshift/console/openshift-console-master.yaml
Labels: approved, lgtm, size/XS

#3774 Actually mount new configs into components
  ci-operator/jobs/infra-periodics.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
Labels: approved, lgtm, size/L

#3776 Add test image for Knative Serving.
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-next.yaml
Labels: approved, lgtm, size/XS

#3683 openstack: cleaner resource nuking
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e.yaml
Labels: approved, lgtm, size/S

#3778 openshift-ansible: remove devel-40 tests
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-devel-40.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-devel-40-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-devel-40-presubmits.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#3755 Add alert ServiceLostHA in prow-monitoring
  cluster/ci/monitoring/Makefile
  cluster/ci/monitoring/alertmanager.yaml
  cluster/ci/monitoring/msg.tmpl
  cluster/ci/monitoring/prometheus_rule_prow.yaml
  cluster/ci/monitoring/prometheus_rule_sinker.yaml
Labels: approved, lgtm, size/M

#3641 CI configuration for openshift/kuryr-kubernetes
  ci-operator/config/openshift/kuryr-kubernetes/OWNERS
  ci-operator/config/openshift/kuryr-kubernetes/openshift-kuryr-kubernetes-master.yaml
  ci-operator/jobs/openshift/kuryr-kubernetes/OWNERS
  ci-operator/jobs/openshift/kuryr-kubernetes/openshift-kuryr-kubernetes-master-postsubmits.yaml
  ci-operator/jobs/openshift/kuryr-kubernetes/openshift-kuryr-kubernetes-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#3780 Add Knative Serving release 0.6.0.
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-v0.6.0.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-v0.6.0-postsubmits.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-v0.6.0-presubmits.yaml
Labels: approved, lgtm, size/L

#3779 Add RoleBindingRestriction to master-sidecar-4
  ci-operator/templates/master-sidecar-4.yaml
Labels: approved, lgtm, size/L

#3777 Update repo urls in openshift.repo
  ci-operator/infra/openshift/origin/artifacts-rpms.yaml
Labels: approved, lgtm, size/XS

#3752 ci-operator: Change metering-helm-operator base to origin base
  ci-operator/config/operator-framework/operator-metering/operator-framework-operator-metering-master.yaml
Labels: approved, lgtm, size/XS

#3782 Add service monitors for all components
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/monitoring/Makefile
  cluster/ci/monitoring/ghproxy_service_monitor.yaml
  cluster/ci/monitoring/hook_service_monitor.yaml
  cluster/ci/monitoring/jenkins-operator_service_monitor.yaml
  cluster/ci/monitoring/plank_service_monitor.yaml
  cluster/ci/monitoring/tide_service_monitor.yaml
Labels: approved, lgtm, size/L

#3783 [14-05-2019 16:45:30] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
Labels: approved, lgtm, size/L

#3785 Update metering repo OWNERS
  ci-operator/config/operator-framework/hadoop/OWNERS
  ci-operator/config/operator-framework/helm/OWNERS
  ci-operator/config/operator-framework/hive/OWNERS
  ci-operator/config/operator-framework/operator-metering/OWNERS
  ci-operator/config/operator-framework/presto/OWNERS
  ci-operator/jobs/operator-framework/hadoop/OWNERS
  ci-operator/jobs/operator-framework/helm/OWNERS
  ci-operator/jobs/operator-framework/hive/OWNERS
  ci-operator/jobs/operator-framework/operator-metering/OWNERS
  ci-operator/jobs/operator-framework/presto/OWNERS
Labels: approved, lgtm, size/M

#3784 Stop using the pushgateway for metrics
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
Labels: approved, lgtm, size/XS

#3786 Fix service port names
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/tide.yaml
Labels: approved, lgtm, size/S

#3787 Fix alert expr in ServiceDown
  cluster/ci/monitoring/prometheus_rule_prow.yaml
Labels: approved, lgtm, size/XS

#3788 Add labels to svc hook and jenkins-opr
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
Labels: approved, lgtm, size/XS

#3790 Add externalUrl for alertManager in prow-monitoring
  cluster/ci/monitoring/alert_manager_crd.yaml
Labels: approved, lgtm, size/XS

#3794 Ensure names of container ports match service ports
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/monitoring/ghproxy_service_monitor.yaml
  cluster/ci/monitoring/hook_service_monitor.yaml
  cluster/ci/monitoring/jenkins-operator_service_monitor.yaml
  cluster/ci/monitoring/plank_service_monitor.yaml
  cluster/ci/monitoring/prometheus_service_monitor.yaml
  cluster/ci/monitoring/sinker_service_monitor.yaml
  cluster/ci/monitoring/tide_service_monitor.yaml
Labels: approved, lgtm

#3795 Fix hook route
  cluster/ci/config/prow/openshift/hook.yaml
Labels: approved, lgtm, size/XS

#3758 Enable Console e2e tests on ClusterAuthenticationOperator
  ci-operator/config/openshift/cluster-authentication-operator/openshift-cluster-authentication-operator-master.yaml
  ci-operator/jobs/openshift/cluster-authentication-operator/openshift-cluster-authentication-operator-master-presubmits.yaml
Labels: approved, lgtm, size/M

#3797 Move upcoming Knative Serving releases to OCP 4.1.
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-next.yaml
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-v0.5.2.yaml
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-v0.6.0.yaml
Labels: approved, lgtm, size/S

#3791 Adding CI for 0.6.0 knative eventing sources
  ci-operator/config/openshift/knative-eventing-sources/openshift-knative-eventing-sources-release-v0.6.0.yaml
  ci-operator/jobs/openshift/knative-eventing-sources/openshift-knative-eventing-sources-release-v0.6.0-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing-sources/openshift-knative-eventing-sources-release-v0.6.0-presubmits.yaml
Labels: approved, lgtm, size/L

#3793 Updates to latest 0.6.0 release tag
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.6.0.yaml
Labels: approved, lgtm, size/M

#3781 scaleup jobs: set optional: true and always_run: false
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.0-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-release-4.0-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.0-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.3-presubmits.yaml
Labels: approved, lgtm, size/M

#3798 ARO - release v4.4 and v5.1
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-periodics.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v4-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v5-presubmits.yaml
  projects/azure/RELEASES.md
Labels: approved, lgtm, sig/azure, size/L

#3801 Using Openshift 4.1 for next releases
  ci-operator/config/openshift/knative-eventing-sources/openshift-knative-eventing-sources-release-next.yaml
  ci-operator/config/openshift/knative-eventing-sources/openshift-knative-eventing-sources-release-v0.6.0.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.6.0.yaml
Labels: approved, lgtm, size/S

#3805 ARO - rollback few jobs
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v4-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/M

#3803 Update mirroring for 4.2
  Makefile
  cluster/ci/config/mirroring/origin_4_1
  cluster/ci/config/mirroring/origin_4_2
  cluster/ci/jobs/image-mirror.yaml
Labels: approved, lgtm, size/L

#3789 bump sample operator to golang 1.11 for v4.2 and later
  ci-operator/config/openshift/cluster-samples-operator/OWNERS
  ci-operator/config/openshift/cluster-samples-operator/openshift-cluster-samples-operator-master.yaml
  ci-operator/config/openshift/cluster-samples-operator/openshift-cluster-samples-operator-release-4.2.yaml
  ci-operator/config/openshift/cluster-samples-operator/openshift-cluster-samples-operator-release-4.3.yaml
Labels: approved, lgtm, size/XS

#3804 Add alerts for other prow-components
  cluster/ci/monitoring/prometheus_rule_prow.yaml
Labels: approved, lgtm, size/M

#3760 Prepare for knative 0.6.0 release
  cluster/ci/config/mirroring/knative/knative_v0_6_quay
  cluster/ci/jobs/image-mirror.yaml
Labels: approved, lgtm, size/M

#3775 ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e: Add third AWS compute node
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
Labels: approved, lgtm, size/XS

#3806 Update forked jobs to mirror manual configs
  ci-operator/jobs/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-release-4.0-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-libvirt/openshift-cluster-api-provider-libvirt-release-4.0-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-libvirt/openshift-cluster-api-provider-libvirt-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-libvirt/openshift-cluster-api-provider-libvirt-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-libvirt/openshift-cluster-api-provider-libvirt-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/cluster-autoscaler-operator/openshift-cluster-autoscaler-operator-release-4.0-presubmits.yaml
  ci-operator/jobs/openshift/cluster-autoscaler-operator/openshift-cluster-autoscaler-operator-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/cluster-autoscaler-operator/openshift-cluster-autoscaler-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/cluster-autoscaler-operator/openshift-cluster-autoscaler-operator-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.0-presubmits.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/console/openshift-console-release-4.0-presubmits.yaml
  ci-operator/jobs/openshift/console/openshift-console-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/console/openshift-console-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/console/openshift-console-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.0-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/k8s-prometheus-adapter/openshift-k8s-prometheus-adapter-release-4.0-presubmits.yaml
  ci-operator/jobs/openshift/k8s-prometheus-adapter/openshift-k8s-prometheus-adapter-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/k8s-prometheus-adapter/openshift-k8s-prometheus-adapter-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/k8s-prometheus-adapter/openshift-k8s-prometheus-adapter-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-release-4.0-presubmits.yaml
  ci-operator/jobs/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-release-4.0-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.0-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-release-4.0-presubmits.yaml
  ci-operator/jobs/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.0-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.3-presubmits.yaml
Labels: approved, lgtm, size/L

#3802 Recover port name in svc prometheus
  cluster/ci/monitoring/prometheus_service_monitor.yaml
Labels: approved, lgtm, size/XS

#3808 Update plank dashboard
  cluster/ci/monitoring/mixins/grafana_dashboards/plank.jsonnet
  cluster/ci/monitoring/plank.json
Labels: approved, lgtm, size/S

#3792 Add serviceMonitor for jenkins-dev and kata-jenkins
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/monitoring/jenkins-operator_service_monitor.yaml
Labels: approved, lgtm, size/M

#3811 [15-05-2019 19:26:12] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
Labels: approved, lgtm, size/L

#3812 Wait 5 mins before firing alerts
  cluster/ci/monitoring/prometheus_rule_prow.yaml
Labels: approved, lgtm, size/M

#3809 Add prow.jsonnet in prow-monitoring
  cluster/ci/monitoring/mixins/Makefile
  cluster/ci/monitoring/mixins/grafana_dashboards/prow.jsonnet
  cluster/ci/monitoring/prow.json
Labels: approved, lgtm, size/L

#3807 installer: update tf-fmt to use latest tf version and mark it optional
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#3813 Expose metrics from deck
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/monitoring/Makefile
  cluster/ci/monitoring/deck_service_monitor.yaml
Labels: approved, lgtm, size/M

#3800 Improve README.md for prow-monitoring
  cluster/ci/monitoring/README.md
Labels: approved, lgtm, size/S

#3814 Add component labels to the deck service
  cluster/ci/config/prow/openshift/deck.yaml
Labels: approved, lgtm, size/XS

#3816 Explicitly set the port on both routes for deck
  cluster/ci/config/prow/openshift/deck.yaml
Labels: approved, lgtm, size/XS

#3817 Target the container port, not the service port in routes
  cluster/ci/config/prow/openshift/deck.yaml
Labels: approved, lgtm, size/XS

#3819 Export RPMs for 4.2
  ci-operator/infra/openshift/origin/artifacts-release-4.2.yaml
  ci-operator/infra/openshift/origin/artifacts-rpms.yaml
Labels: approved, lgtm, size/L

#3595 installer template: add a function to test cluster state restore
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
Labels: approved, lgtm, size/L

#3753 ci-operator: Add metering-ansible-operator image build
  ci-operator/config/operator-framework/operator-metering/operator-framework-operator-metering-master.yaml
Labels: approved, lgtm, size/XS

#3825 [16-05-2019 17:23:53] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
Labels: approved, lgtm, size/L

#3821 MCO: add a job to test etcd snapshot restore
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-master.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-master-presubmits.yaml
Labels: approved, lgtm, size/M

#3824 Jira PROD-1027: add a job to test etcd snapshot restore to MCO 4.x
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.1.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.2.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.3.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.3-presubmits.yaml
Labels: approved, lgtm, size/L

#3820 Use jsonnet to generate prometheus_rule_prow.yaml
  cluster/ci/monitoring/README.md
  cluster/ci/monitoring/mixins/Makefile
  cluster/ci/monitoring/mixins/prometheus/ci_absent_alerts.libsonnet
  cluster/ci/monitoring/mixins/prometheus/prometheus.libsonnet
  cluster/ci/monitoring/mixins/prometheus/prometheus_rule_prow.jsonnet
  cluster/ci/monitoring/mixins/prometheus/prow_monitoring_absent_alerts.libsonnet
  cluster/ci/monitoring/prometheus_rule_prow.yaml
Labels: approved, lgtm, size/L
