Repository openshift/release, pull requests merged in 2019-02, with the labels that each got.

#2700 network-operator: don't e2e on README changes
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#2759 [01-02-2019 16:08:44] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  cluster/ci/config/prow/openshift/tracer.yaml
Labels: approved, lgtm

#2761 Update prowjobs from controllers
  cluster/ci/config/prow/openshift/jenkins_operator_rbac.yaml
  cluster/ci/config/prow/openshift/plank_rbac.yaml
Labels: approved, lgtm

#2764 Fix location of credentials file
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
Labels: approved, lgtm

#2765 Stop requiring autoheal context through branchprotection
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm

#2767 [01-02-2019 22:26:47] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  cluster/ci/config/prow/openshift/tracer.yaml
Labels: approved, lgtm

#2768 Remove unused images from mirroring
  cluster/ci/config/mirroring/origin_v4_0
Labels: approved, lgtm

#2769 [02-02-2019 05:09:54] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  cluster/ci/config/prow/openshift/tracer.yaml
Labels: approved, lgtm

#2771 [02-02-2019 05:51:36] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  cluster/ci/config/prow/openshift/tracer.yaml
Labels: approved, lgtm

#2747 Allow Origin PR builds in master to inject kubelet into rhcos
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
Labels: approved, lgtm

#2774 cluster-api: change import path
  ci-operator/config/openshift/cluster-api/openshift-cluster-api-release-4.0.yaml
Labels: approved, lgtm

#2655 Add documentation on rehearsals
  ci-operator/REHEARSALS.md
Labels: approved, lgtm, size/M

#2773 fed-v2: Switch federation-v2-src image over to Dockerfile.federation
  ci-operator/config/openshift/federation-v2-operator/openshift-federation-v2-operator-master.yaml
Labels: approved, lgtm

#2758 Setup cluster etcd operator
  ci-operator/config/openshift/cluster-etcd-operator/OWNERS
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-master.yaml
  ci-operator/jobs/openshift/cluster-etcd-operator/OWNERS
  ci-operator/jobs/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm

#2760 Update prow to reflect move to new asb-operator image
  ci-operator/config/openshift/ansible-service-broker/openshift-ansible-service-broker-master.yaml
Labels: approved, lgtm

#2776 [04-02-2019 17:40:15] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  cluster/ci/config/prow/openshift/tracer.yaml
Labels: approved, lgtm

#2778 Bump ghproxy
  cluster/ci/config/prow/openshift/ghproxy.yaml
Labels: approved, lgtm, size/XS

#2779 Revert "Merge pull request #2778 from stevekuznetsov/skuznets/bump-prow"
  cluster/ci/config/prow/openshift/ghproxy.yaml
Labels: approved, lgtm

#2780 Fed-v2: rename controller image
  ci-operator/config/openshift/federation-v2-operator/openshift-federation-v2-operator-master.yaml
Labels: approved, lgtm, size/S

#2782 Add federation v2 to mirroring
  cluster/ci/config/mirroring/origin_v4_0_quay
Labels: approved, lgtm, size/XS

#2775 add secret copy for teardown
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure.yaml
Labels: approved, lgtm

#2789 [05-02-2019 20:25:54] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
Labels: approved, size/M

#2791 Remove jobs for openshift/ose
  ci-operator/jobs/openshift/ose/OWNERS
  ci-operator/jobs/openshift/ose/openshift-ose-master-presubmits.yaml
  ci-operator/jobs/openshift/ose/openshift-ose-periodics.yaml
Labels: approved, lgtm, size/L

#2790 Push more frequently again from ghproxy
  cluster/ci/config/prow/openshift/ghproxy.yaml
Labels: approved, lgtm, size/XS

#2784 cloud-team: do not take github reviews into consideration
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#2785 Collect artifacts from cluster-image-registry-operator tests
  ci-operator/config/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-master.yaml
  ci-operator/jobs/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#2792 Use a normal push interval
  cluster/ci/config/prow/openshift/ghproxy.yaml
Labels: approved, lgtm

#2793 ci-operator/jobs/infra-periodics: Temporarily disable periodic-retester
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm, size/XS

#2795 enable elasticsearch-operator e2e test
  ci-operator/config/openshift/elasticsearch-operator/openshift-elasticsearch-operator-master.yaml
  ci-operator/jobs/openshift/elasticsearch-operator/openshift-elasticsearch-operator-master-presubmits.yaml
Labels: approved, lgtm, size/M

#2796 Remove limits from remaining origin jobs, set requests
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
Labels: approved, lgtm, size/XS

#2797 cluster/ci/config/prow/plugins: Enable the override plugin
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#2772 ci-operator/templates/openshift: Bump install-config.yaml to v1beta2
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e-40.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-scaleup-e2e-40.yaml
Labels: approved, lgtm

#2801 cluster-api: download bazel to run all tests
  ci-operator/config/openshift/cluster-api/openshift-cluster-api-master.yaml
  ci-operator/config/openshift/cluster-api/openshift-cluster-api-release-4.0.yaml
Labels: approved, lgtm, size/S

#2751 add optional e2e-aws for master-post-release branch
  ci-operator/jobs/openshift/cluster-logging-operator/openshift-cluster-logging-operator-master-post-release-presubmits.yaml
  ci-operator/jobs/openshift/elasticsearch-operator/openshift-elasticsearch-operator-master-post-release-presubmits.yaml
Labels: approved, lgtm, size/XS

#2783 golang-1.10/Dockerfile: add systemd-devel for MCO journal bindings
  projects/origin-release/golang-1.10/Dockerfile
  projects/origin-release/golang-1.11/Dockerfile
Labels: approved, lgtm, size/XS

#2802 BYOR 3.11: mark some jobs as optional
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-3.11-presubmits.yaml
Labels: approved, lgtm, size/XS

#2684 BYOR 3.10: add e2e-gluster test for 3.10
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-3.10-presubmits.yaml
Labels: approved, lgtm, size/M

#2803 BYOR 3.10: mark some jobs as optional
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-3.10-presubmits.yaml
Labels: approved, lgtm, size/XS

#2804 BYOR 4.0: make gcp job optional
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-devel-40-presubmits.yaml
Labels: approved, lgtm, size/XS

#2798 ci-operator/jobs/openshift: Make launch-aws optional
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#2805 Increase console memory request
  ci-operator/config/openshift/console/openshift-console-master.yaml
Labels: approved, lgtm, size/XS

#2806 Enable running crio jobs by default
  ci-operator/jobs/kubernetes-sigs/cri-o/kubernetes-sigs-cri-o-master-presubmits.yaml
Labels: approved, lgtm, size/S

#2807 Fix hive unit test resources
  ci-operator/config/openshift/hive/openshift-hive-master.yaml
Labels: approved, lgtm, size/XS

#2809 Don't run crio ami jobs by default
  ci-operator/jobs/kubernetes-sigs/cri-o/kubernetes-sigs-cri-o-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#2812 Send rehearse debug output to $ARTIFACTS
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#2813 launch-installer: Archive machineconfigs and machineconfigpools
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
Labels: approved, lgtm, size/XS

#2815 [08-02-2019 18:52:37] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
Labels: approved, lgtm, size/M

#2816 installer: increase verbosity of terraform logs
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
Labels: approved, lgtm, size/XS

#2817 MCO: allow ssh
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-master.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#2818 Periodic jobs need to set extra_refs to clone
  ci-operator/jobs/openshift/origin/openshift-origin-periodics.yaml
  ci-operator/templates/cluster-launch-e2e-openshift-ansible.yaml
  ci-operator/templates/cluster-launch-e2e-openshift-jenkins.yaml
  ci-operator/templates/cluster-launch-e2e-upgrade.yaml
  ci-operator/templates/cluster-launch-e2e.yaml
  ci-operator/templates/cluster-launch-src.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-libvirt-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e-40.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-scaleup-e2e-40.yaml
  ci-operator/templates/openshift/openshift-azure/build-base-image.yaml
  ci-operator/templates/openshift/openshift-azure/build-node-image.yaml
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure.yaml
Labels: approved, lgtm, sig/azure, size/M

#2819 Revert "MCO: allow ssh"
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-master.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#2814 Reuse a demo rehearsal job for pre-deploy testing
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
Labels: approved, lgtm, size/S

#2820 library-go: bump memory for unit tests
  ci-operator/config/openshift/library-go/openshift-library-go-master.yaml
Labels: approved, lgtm, size/XS

#2821 library-go: remove cpu requests and limits
  ci-operator/config/openshift/library-go/openshift-library-go-master.yaml
Labels: approved, lgtm, size/XS

#2822 Add cluster-svcat-apiserver-operator
  ci-operator/config/openshift/cluster-svcat-apiserver-operator/OWNERS
  ci-operator/config/openshift/cluster-svcat-apiserver-operator/openshift-cluster-svcat-apiserver-operator-master.yaml
  ci-operator/config/openshift/cluster-svcat-apiserver-operator/openshift-cluster-svcat-apiserver-operator-master__rhel.yaml
  ci-operator/jobs/openshift/cluster-svcat-apiserver-operator/OWNERS
  ci-operator/jobs/openshift/cluster-svcat-apiserver-operator/openshift-cluster-svcat-apiserver-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-svcat-apiserver-operator/openshift-cluster-svcat-apiserver-operator-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#2825 Allow ci-chat-bot launched clusters to last for ~2.5h from start
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
Labels: approved, lgtm, size/XS

#2808 BYOR 3.10: fix syntax in e2e-gluster job
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-3.10-presubmits.yaml
Labels: approved, lgtm, size/XS

#2826 [11-02-2019 22:11:18] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
Labels: approved, lgtm, size/M

#2830 cao: add jenkins job running cao e2e test
  ci-operator/jobs/openshift/cluster-autoscaler-operator/openshift-cluster-autoscaler-operator-master-presubmits.yaml
Labels: approved, lgtm, size/S

#2810 add pre-submit for osa release
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-release-v1.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v1-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v1-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/L

#2828 Revert "Merge pull request #2826 from stevekuznetsov/skuznets/bump-prow"
  ci-operator/jobs/infra-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
Labels: lgtm, size/M

#2827 Enforce CPU requests on all jobs
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/autoheal/openshift-autoheal-master-presubmits.yaml
  ci-operator/jobs/openshift/ci-ns-ttl-controller/openshift-ci-ns-ttl-controller-master-presubmits.yaml
  ci-operator/jobs/openshift/ci-vm-operator/openshift-ci-vm-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-libvirt/openshift-cluster-api-provider-libvirt-master-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  hack/validate-prow-job-semantics.py
Labels: approved, lgtm, size/L

#2831 library-go: add cpu requests back
  ci-operator/config/openshift/library-go/openshift-library-go-master.yaml
Labels: approved, lgtm, size/XS

#2833 BYOR 4.0: use criotested repo for 1.12 builds
  cluster/test-deploy/aws-4.0/vars.yaml
Labels: approved, lgtm, size/S

#2832 make logging full-integ-aws test required
  ci-operator/jobs/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#2836 openshift/cluster-config-operator: Fix the non-reentrant generation
  ci-operator/jobs/openshift/cluster-config-operator/openshift-cluster-config-operator-master-presubmits.yaml
Labels: approved, kind/bug, lgtm, size/M

#2840 azure: do not sync images to v3.11 or v3.11.0 tags
  projects/azure/image-mirror/image-mirror.yaml
Labels: approved, lgtm, sig/azure, size/XS

#2839 Remove CPU limits from templates
  ci-operator/templates/cluster-launch-e2e-openshift-ansible.yaml
  ci-operator/templates/cluster-launch-e2e-openshift-jenkins.yaml
  ci-operator/templates/cluster-launch-e2e-upgrade.yaml
  ci-operator/templates/cluster-launch-e2e.yaml
  ci-operator/templates/cluster-launch-src.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e-40.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-scaleup-e2e-40.yaml
  ci-operator/templates/openshift/openshift-azure/build-base-image.yaml
  ci-operator/templates/openshift/openshift-azure/build-node-image.yaml
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure.yaml
Labels: approved, lgtm, sig/azure, size/S

#2841 logging - add rsyslog image
  ci-operator/config/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-master.yaml
Labels: approved, lgtm, size/XS

#2842 add configmaps and secrets to debug info
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e-40.yaml
Labels: approved, lgtm, size/S

#2844 add namespaces, services, rolebindings, and roles
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e-40.yaml
Labels: approved, lgtm, size/M

#2843 fed-v2: refactor source image
  ci-operator/config/openshift/federation-v2-operator/openshift-federation-v2-operator-master.yaml
Labels: approved, lgtm, size/S

#2837 Make OSA scaleupdown prow job optional
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/XS

#2851 knative-serving Release 0.3.
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-0.3.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-0.3-postsubmits.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-0.3-presubmits.yaml
Labels: approved, lgtm, size/L

#2852 Remove knative-serving manifest for 0.2 on OpenShift 4.0.
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-0.2__v4.0.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-0.2-postsubmits.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-0.2-presubmits.yaml
Labels: approved, lgtm, size/L

#2847 Fully enable rehearsals
  ci-operator/REHEARSALS.md
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
Labels: approved, lgtm, size/M

#2854 Azure release updates
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-private-preview-1.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-private-preview-1-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-private-preview-1-presubmits.yaml
  projects/azure/base-images/plugin-base.yaml
Labels: approved, lgtm, sig/azure, size/L

#2823 service account for QE Jenkins
  cluster/ci/config/roles.yaml
Labels: approved, lgtm, size/S

#2859 Allow authenticated users to view the staging ns
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
Labels: approved, lgtm, size/XS

#2858 Revert "logging - add rsyslog image"
  ci-operator/config/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-master.yaml
Labels: approved, lgtm, size/XS

#2850 enable cluster-logging-operator unit tests
  ci-operator/config/openshift/cluster-logging-operator/openshift-cluster-logging-operator-master.yaml
  ci-operator/jobs/openshift/cluster-logging-operator/openshift-cluster-logging-operator-master-presubmits.yaml
Labels: approved, lgtm, size/M

#2860 Move integration tests to run on tmpfs disks
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-3.11.yaml
Labels: approved, lgtm, size/XS

#2861 Increase master integration size
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-3.11.yaml
Labels: approved, lgtm, size/XS

#2756 azure upgrade scripts
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-master.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
  ci-operator/templates/openshift/openshift-azure/rbac.yaml
  cluster/ci/config/prow/plugins.yaml
  projects/azure/README.md
  projects/azure/base-images/test-base.yaml
  projects/azure/base-images/test-base/Dockerfile
  projects/azure/base-images/test-base/prow_mock.sh
Labels: approved, lgtm, sig/azure, size/L

#2863 remove always run from osa upgrade job
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/XS

#2865 osa - make job optional and delete not used job
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/M

#2866 osa - rename targets
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/XS

#2867 Add helper script to bootstrap the config-updater
  hack/config-bootstrapper.sh
Labels: approved, lgtm, size/XS

#2855 Revert "Enable private-preview labeling"
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#2871 Integration uses more memory with more CPUs
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-3.11.yaml
Labels: approved, lgtm, size/S

#2869 make optional to avoid cache failures
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/XS

#2864 Do not block merges on unknown contexts in openshift/release
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/XS

#2872 OSA v2 release
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-release-v2.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v2-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v2-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/L

#2873 Further increase memory and limit GOMAXPROCS for integration
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
Labels: approved, lgtm, size/XS

#2874 remove cluster-logging post-release jobs
  ci-operator/config/openshift/cluster-logging-operator/openshift-cluster-logging-operator-master-post-release.yaml
  ci-operator/config/openshift/elasticsearch-operator/openshift-elasticsearch-operator-master-post-release.yaml
  ci-operator/jobs/openshift/cluster-logging-operator/openshift-cluster-logging-operator-master-post-release-presubmits.yaml
  ci-operator/jobs/openshift/elasticsearch-operator/openshift-elasticsearch-operator-master-post-release-presubmits.yaml
Labels: approved, lgtm, size/L

#2875 Split some core images out into their own repo to reduce build times
  ci-operator/config/openshift/images/OWNERS
  ci-operator/config/openshift/images/openshift-images-master.yaml
  ci-operator/jobs/openshift/images/OWNERS
  ci-operator/jobs/openshift/images/openshift-images-master-postsubmits.yaml
  ci-operator/jobs/openshift/images/openshift-images-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#2877 Cache more of the origin repo to reduce size of next layer
  ci-operator/infra/src-cache-origin.yaml
Labels: approved, lgtm, size/XS

#2880 Allow release-controller-ocp to publish origin images to openshift/origin-v4.0
  Makefile
  ci-operator/infra/openshift/release-controller/deploy-ocp-4.0.yaml
  ci-operator/infra/openshift/release-controller/ocp-4.0-ci.json
  hack/build
  hack/lib/find_defs.py
Labels: approved, lgtm

#2883 add osa v2.0 release testing
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-master.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/M

#2881 Configs for knative-build release-0.3 branch
  ci-operator/config/openshift/knative-build/openshift-knative-build-release-0.3.yaml
  ci-operator/jobs/openshift/knative-build/openshift-knative-build-release-0.3-postsubmits.yaml
  ci-operator/jobs/openshift/knative-build/openshift-knative-build-release-0.3-presubmits.yaml
Labels: approved, lgtm, size/L

#2882 Add e2e-aws job for cluster-node-tuning-operator.
  ci-operator/config/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-master.yaml
  ci-operator/jobs/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-master-presubmits.yaml
Labels: approved, lgtm, size/M

#2870 Prow jobs and ci-operator config for knative-build-pipeline master...
  OWNERS_ALIASES
  ci-operator/config/openshift/knative-build-pipeline/OWNERS
  ci-operator/config/openshift/knative-build-pipeline/openshift-knative-build-pipeline-master.yaml
  ci-operator/jobs/openshift/knative-build-pipeline/OWNERS
  ci-operator/jobs/openshift/knative-build-pipeline/openshift-knative-build-pipeline-master-postsubmits.yaml
  ci-operator/jobs/openshift/knative-build-pipeline/openshift-knative-build-pipeline-master-presubmits.yaml
  ci-operator/jobs/openshift/knative-build-pipeline/openshift-knative-build-pipeline-periodics.yaml
Labels: approved, lgtm, size/L

#2888 osa - add v2.1 release
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-master.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/M

#2890 osa - always run false
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/XS

#2886 must use ClusterRole for QE group
  cluster/ci/config/roles.yaml
Labels: approved, lgtm, size/XS

#2889 Use ocp image streams in knative-build
  ci-operator/config/openshift/knative-build/openshift-knative-build-release-0.3.yaml
Labels: approved, lgtm, size/S

#2892 Split origin and ocp release runs into their own jobs
  ci-operator/infra/openshift/origin/images-ocp-images.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
Labels: approved, lgtm, size/L

#2893 Switch to ocp periodic jobs
  ci-operator/infra/openshift/release-controller/ocp-4.0.json
Labels: approved, lgtm, size/XS

#2894 Fix origin test-cmd - bin command no longer builds oc binary
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
Labels: approved, lgtm, size/XS

#2895 origin bin cache be broader, increase memory, use mem volume for cmd
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
Labels: approved, lgtm, size/S

#2897 Temporarily disable machine-os-content PR override for origin
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
Labels: approved, lgtm, size/S

#2896 Switch to the UBI base image instead of minimal
  ci-operator/config/openshift/images/openshift-images-master.yaml
Labels: approved, lgtm, size/XS

#2898 Typo in bin command
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
Labels: approved, lgtm, size/XS

#2899 Config updater job is broken
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
Labels: approved, lgtm, size/XS

#2902 Add environmental settings for Knative Serving 0.3 tests.
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-0.3.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-0.3-presubmits.yaml
Labels: approved, lgtm, size/XS

#2846 Add force update job
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-periodics.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v1-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/L

#2903 osa - tide.up
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
  projects/azure/base-images/test-base/prow_mock.sh
Labels: approved, lgtm, sig/azure, size/L

#2906 osa - add optional to prowgen
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/XS

#2787 Modify install-config.yaml to use controlPlane and compute instead of master and worker
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e-40.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-scaleup-e2e-40.yaml
Labels: approved, lgtm, size/M

#2909 Enforce branch protection and tide on multus-cni
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#2912 osa - target typos
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/XS

#2884 BYOR 4.0 scaleup: don't copy install config
  ci-operator/templates/openshift/openshift-ansible/cluster-scaleup-e2e-40.yaml
Labels: approved, lgtm, size/XS

#2916 cluster-api-actuator-pkg: add optional e2e test
  ci-operator/config/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-master.yaml
  ci-operator/jobs/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-master-presubmits.yaml
Labels: approved, lgtm, size/M

#2915 azure: don't hard-code wrong RPM repo for node build
  ci-operator/templates/openshift/openshift-azure/build-node-image.yaml
Labels: approved, lgtm, sig/azure, size/XS

#2921 Use go-1.11 for prowgen
  ci-operator/config/openshift/ci-operator-prowgen/openshift-ci-operator-prowgen-master.yaml
Labels: approved, lgtm, size/XS

#2923 Change to 1.11.5 in golang
  projects/origin-release/golang-1.11/Dockerfile
Labels: approved, lgtm, size/XS

#2924 [21-02-2019 21:49:17] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/M

#2922 use new network type of OpenShiftSDN in install-config.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e-40.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-scaleup-e2e-40.yaml
Labels: approved, lgtm, size/S

#2918 ci-operator configs for knative-eventing release-0.3 branch
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-0.3.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-0.3-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-0.3-presubmits.yaml
Labels: approved, lgtm, size/L

#2920 knative-eventing-sources release-0.3
  ci-operator/config/openshift/knative-eventing-sources/openshift-knative-eventing-sources-release-0.3.yaml
  ci-operator/jobs/openshift/knative-eventing-sources/openshift-knative-eventing-sources-release-0.3-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing-sources/openshift-knative-eventing-sources-release-0.3-presubmits.yaml
Labels: approved, lgtm, size/L

#2919 cluster-api: remove release-4.0 branch jobs
  ci-operator/config/openshift/cluster-api/openshift-cluster-api-release-4.0.yaml
  ci-operator/jobs/openshift/cluster-api/openshift-cluster-api-release-4.0-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-api/openshift-cluster-api-release-4.0-presubmits.yaml
Labels: approved, lgtm, size/L

#2929 Add monitor_prow script
  hack/monitor_prow.py
Labels: approved, lgtm, size/M

#2932 Some builds were being oomkilled or capped, raise requests/limits
  ci-operator/config/openshift/console/openshift-console-master.yaml
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
Labels: approved, lgtm, size/M

#2931 Add helm CI operator jobs
  ci-operator/config/operator-framework/helm/OWNERS
  ci-operator/config/operator-framework/helm/operator-framework-helm-metering-master.yaml
  ci-operator/jobs/operator-framework/helm/OWNERS
  ci-operator/jobs/operator-framework/helm/operator-framework-helm-metering-master-postsubmits.yaml
  ci-operator/jobs/operator-framework/helm/operator-framework-helm-metering-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#2933 Add trigger config for libpod
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#2934 Explicitly add operator-framework/helm to triggers
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#2938 Add trigger config for operator framework org
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#2939 Run on 1.11 for ci-operator
  ci-operator/config/openshift/ci-operator/openshift-ci-operator-master.yaml
Labels: approved, lgtm, size/XS

#2942 azure: remove v2.0 references, it was never released to prod.
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-master.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/L

#2885 Adding azure-sop to prow.
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
  projects/azure/README.md
Labels: approved, lgtm, sig/azure, size/S

#2944 Increase unit and integration CPU to debug starvation
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
Labels: approved, lgtm

#2930 Remove image-registry publishing bot
  Makefile
  cluster/ci/config/publishingbots/image-registry/config.yaml
  cluster/ci/config/publishingbots/image-registry/rules.yaml
  cluster/ci/config/publishingbots/image-registry/statefulset.yaml
  cluster/ci/config/roles.yaml
Labels: approved, lgtm, size/L

#2943 Rename helm config file
  ci-operator/config/operator-framework/helm/operator-framework-helm-master.yaml
  ci-operator/jobs/operator-framework/helm/operator-framework-helm-master-postsubmits.yaml
  ci-operator/jobs/operator-framework/helm/operator-framework-helm-master-presubmits.yaml
Labels: approved, lgtm, size/S

#2945 Limit number of CPUs used by unit test run and use mem volume
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
Labels: approved, lgtm, size/XS

#2947 cluster-api-actuator-pkg: add pure k8s e2e test
  ci-operator/jobs/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-master-presubmits.yaml
Labels: approved, lgtm, size/S

#2940 Use centos base for helm
  ci-operator/config/operator-framework/helm/operator-framework-helm-master.yaml
Labels: approved, lgtm, size/XS

#2948 Add ci-monitoring-viewer Group
  cluster/ci/config/roles.yaml
Labels: approved, lgtm, size/S

#2950 don't validate TLS when collecting from CI
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e-40.yaml
Labels: approved, lgtm, size/L

#2936 Add presto ci-operator configuration
  ci-operator/config/operator-framework/presto/OWNERS
  ci-operator/config/operator-framework/presto/operator-framework-presto-master.yaml
  ci-operator/jobs/operator-framework/presto/OWNERS
  ci-operator/jobs/operator-framework/presto/operator-framework-presto-master-postsubmits.yaml
  ci-operator/jobs/operator-framework/presto/operator-framework-presto-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#2937 Add hadoop ci-operator config
  ci-operator/config/operator-framework/hadoop/OWNERS
  ci-operator/config/operator-framework/hadoop/operator-framework-hadoop-master.yaml
  ci-operator/jobs/operator-framework/hadoop/OWNERS
  ci-operator/jobs/operator-framework/hadoop/operator-framework-hadoop-master-postsubmits.yaml
  ci-operator/jobs/operator-framework/hadoop/operator-framework-hadoop-master-presubmits.yaml
Labels: approved, lgtm, size/L
