Repository openshift/release, pull requests merged in 2019-12, with the labels that each got.

#6181 MCO FCOS: don't inject binaries in os-content
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-fcos.yaml
Labels: approved, lgtm, size/S

#6182 allow ci-operator service account to get groups
  cluster/ci/config/prow/openshift/ci-operator/roles.yaml
Labels: approved, lgtm, size/M

#6033 ci-operator: Update the metering-operator approvers.
  ci-operator/config/operator-framework/ghostunnel/OWNERS
  ci-operator/config/operator-framework/hadoop/OWNERS
  ci-operator/config/operator-framework/helm/OWNERS
  ci-operator/config/operator-framework/hive/OWNERS
  ci-operator/config/operator-framework/operator-metering/OWNERS
  ci-operator/config/operator-framework/presto/OWNERS
  ci-operator/jobs/operator-framework/ghostunnel/OWNERS
  ci-operator/jobs/operator-framework/hadoop/OWNERS
  ci-operator/jobs/operator-framework/helm/OWNERS
  ci-operator/jobs/operator-framework/hive/OWNERS
  ci-operator/jobs/operator-framework/operator-metering/OWNERS
  ci-operator/jobs/operator-framework/presto/OWNERS
Labels: approved, lgtm, size/M

#5769 remove console e2e template, use custom test image template everywhere
  Makefile
  ci-operator/config/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-master.yaml
  ci-operator/config/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-release-4.1.yaml
  ci-operator/config/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-release-4.2.yaml
  ci-operator/config/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-release-4.3.yaml
  ci-operator/config/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-release-4.4.yaml
  ci-operator/config/operator-framework/operator-marketplace/operator-framework-operator-marketplace-master.yaml
  ci-operator/config/operator-framework/operator-marketplace/operator-framework-operator-marketplace-release-4.1.yaml
  ci-operator/config/operator-framework/operator-marketplace/operator-framework-operator-marketplace-release-4.2.yaml
  ci-operator/config/operator-framework/operator-marketplace/operator-framework-operator-marketplace-release-4.3.yaml
  ci-operator/config/operator-framework/operator-marketplace/operator-framework-operator-marketplace-release-4.4.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
  ci-operator/jobs/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-master-presubmits.yaml
  ci-operator/jobs/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-release-4.1-presubmits.yaml
  ci-operator/jobs/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-release-4.2-presubmits.yaml
  ci-operator/jobs/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-release-4.3-presubmits.yaml
  ci-operator/jobs/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-release-4.4-presubmits.yaml
  ci-operator/jobs/operator-framework/operator-marketplace/operator-framework-operator-marketplace-master-presubmits.yaml
  ci-operator/jobs/operator-framework/operator-marketplace/operator-framework-operator-marketplace-release-4.1-presubmits.yaml
  ci-operator/jobs/operator-framework/operator-marketplace/operator-framework-operator-marketplace-release-4.2-presubmits.yaml
  ci-operator/jobs/operator-framework/operator-marketplace/operator-framework-operator-marketplace-release-4.3-presubmits.yaml
  ci-operator/jobs/operator-framework/operator-marketplace/operator-framework-operator-marketplace-release-4.4-presubmits.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-console.yaml
Labels: approved, lgtm, size/XL

#6053 Periodics to promote s390x machine-os-content to ART
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
Labels: approved, lgtm, size/XL

#6188 Run jobs and config updater after new repo
  Makefile
Labels: approved, lgtm, size/XS

#5521 Rename e2e-aws-ovn-kubernetes to e2e-aws-ovn
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
  core-services/release-controller/_releases/release-ocp-4.3.json
  core-services/release-controller/_releases/release-ocp-4.4.json
Labels: approved, lgtm, size/L

#6034 Add e2e-metal 4.2 presubmit
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.2-presubmits.yaml
Labels: approved, lgtm, size/M

#6166 Add `component/git-service` label for openshift/console
  core-services/prow/02_config/_labels.yaml
Labels: approved, lgtm, size/XS

#6174 Use session scret correctly
  cluster/ci/monitoring/Makefile
  cluster/ci/monitoring/alert_manager_expose.yaml
  cluster/ci/monitoring/alert_manager_proxy_secret.yaml
  cluster/ci/monitoring/grafana_expose.yaml
  cluster/ci/monitoring/grafana_proxy_secret.yaml
  cluster/ci/monitoring/prometheus_expose.yaml
  cluster/ci/monitoring/prometheus_proxy_secret.yaml
  core-services/prow/03_deployment/admin_config_updater_rbac.yaml
Labels: approved, lgtm, size/L

#6185 Update branch protection rules for tektoncd-pipeline-operator
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm, size/XS

#5962 Bootstrap step registry with cluster-launch-e2e items
  ci-operator/step-registry/ipi/deprovision/artifacts/artifacts/ipi-deprovision-artifacts-artifacts-commands.sh
  ci-operator/step-registry/ipi/deprovision/artifacts/artifacts/ipi-deprovision-artifacts-artifacts-ref.yaml
  ci-operator/step-registry/ipi/deprovision/artifacts/bootstrap/ipi-deprovision-artifacts-bootstrap-commands.sh
  ci-operator/step-registry/ipi/deprovision/artifacts/bootstrap/ipi-deprovision-artifacts-bootstrap-ref.yaml
  ci-operator/step-registry/ipi/deprovision/artifacts/ipi-deprovision-artifacts-chain.yaml
  ci-operator/step-registry/ipi/deprovision/artifacts/must-gather/ipi-deprovision-artifacts-must-gather-commands.sh
  ci-operator/step-registry/ipi/deprovision/artifacts/must-gather/ipi-deprovision-artifacts-must-gather-ref.yaml
  ci-operator/step-registry/ipi/deprovision/deprovision/ipi-deprovision-deprovision-commands.sh
  ci-operator/step-registry/ipi/deprovision/deprovision/ipi-deprovision-deprovision-ref.yaml
  ci-operator/step-registry/ipi/deprovision/ipi-deprovision-chain.yaml
  ci-operator/step-registry/ipi/install/install/ipi-install-install-commands.sh
  ci-operator/step-registry/ipi/install/install/ipi-install-install-ref.yaml
  ci-operator/step-registry/ipi/install/ipi-install-chain.yaml
  ci-operator/step-registry/ipi/install/rbac/ipi-install-rbac-commands.sh
  ci-operator/step-registry/ipi/install/rbac/ipi-install-rbac-ref.yaml
  ci-operator/step-registry/ipi/ipi-workflow.yaml
Labels: approved, lgtm, size/L

#6190 ci-operator/templates/openshift/installer/cluster-launch-installer-e2e: Error-catching for Google OAuth pokes
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
Labels: approved, lgtm, size/XS

#6191 Bring ci-operator-configresolver up to latest, deploy registry
  core-services/ci-operator-configresolver/ci-operator-configresolver.yaml
Labels: approved, lgtm, size/S

#6193 Revert "Merge pull request #6191 from stevekuznetsov/skuznets/deploy-…
  core-services/ci-operator-configresolver/ci-operator-configresolver.yaml
Labels: size/S

#6195 Gather logs from boskos, not proxy
  hack/monitor_prow.py
Labels: approved, lgtm, size/XS

#6196 Deploy latest ci-operator-configresolver
  core-services/ci-operator-configresolver/ci-operator-configresolver.yaml
Labels: approved, lgtm, size/S

#6194 Add openshift-kni/baremetal-deploy repo to prow plugins config
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/XS

#6201 Remove POC branch for Serverless.
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.2.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.2__4.2.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.2-postsubmits.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.2-presubmits.yaml
Labels: approved, lgtm, size/L

#6162 Use shared E2E image for cluster-machine-approver
  ci-operator/config/openshift/cluster-machine-approver/openshift-cluster-machine-approver-master.yaml
  ci-operator/config/openshift/cluster-machine-approver/openshift-cluster-machine-approver-release-4.3.yaml
  ci-operator/config/openshift/cluster-machine-approver/openshift-cluster-machine-approver-release-4.4.yaml
  ci-operator/config/openshift/cluster-machine-approver/openshift-cluster-machine-approver-release-4.5.yaml
  ci-operator/jobs/openshift/cluster-machine-approver/openshift-cluster-machine-approver-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-machine-approver/openshift-cluster-machine-approver-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/cluster-machine-approver/openshift-cluster-machine-approver-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/cluster-machine-approver/openshift-cluster-machine-approver-release-4.5-presubmits.yaml
Labels: approved, lgtm, size/L

#5802 e2e: use lease client
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
Labels: approved, lgtm, sig/azure, size/M

#6205 TektonCD pipeline v0.9.0 release
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.9.0.yaml
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.9.0__variant.yaml
  ci-operator/jobs/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.9.0-postsubmits.yaml
  ci-operator/jobs/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.9.0-presubmits.yaml
  core-services/image-mirroring/tekton/mapping_tekton_v0_9_quay
Labels: approved, lgtm, size/XL

#6210 Handle image versions with multiple colons
  hack/monitor_prow.py
Labels: approved, lgtm, size/XS

#6211 Fix origin release publishing
  core-services/release-controller/_releases/release-ocp-4.3.json
  core-services/release-controller/_releases/release-ocp-4.4.json
  core-services/release-controller/admin_deploy-ocp-controller.yaml
Labels: approved, lgtm, size/S

#6208 Update Makefile for origin definitions
  Makefile
Labels: approved, lgtm, size/XS

#6192 ci-operator/templates/openshift/installer: Bump AWS UPI to RHCOS 43.81.201911221453.0
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-src.yaml
Labels: approved, lgtm, size/XS

#6212 Turn of re-testing for MCO PRs
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm, size/XS

#6214 mirror: Regenerate mirror for latest, switch from origin to ocp
  core-services/image-mirroring/openshift/Makefile
  core-services/image-mirroring/openshift/mapping_origin_4_1
  core-services/image-mirroring/openshift/mapping_origin_4_2
  core-services/image-mirroring/openshift/mapping_origin_4_3
  core-services/image-mirroring/openshift/mapping_origin_4_4
  core-services/image-mirroring/openshift/mapping_origin_4_5
  hack/mirror-file
Labels: approved, lgtm, size/XXL

#6215 mirror: Give openshift mirror a token
  ci-operator/jobs/infra-image-mirroring.yaml
Labels: approved, lgtm, size/XS

#6216 Revert "MCD RPM and os container builds for 4.2+ branches"
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-master.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.2.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.3.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.4.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.2-postsubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.3-postsubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.4-postsubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.4-presubmits.yaml
Labels: approved, lgtm, size/L

#6133 Add job periodic-acme-cert-issuer-build01
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/populate-secrets-from-bitwarden.sh
  clusters/build-clusters/01_cluster/prow/03_deployment/admin_ca-cert-issuer_rbac.yaml
Labels: approved, lgtm, size/L

#6217 Revert "Turn of re-testing for MCO PRs"
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm, size/XS

#6231 add group-auto-updater image in ci-tools ci-op config
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
Labels: approved, lgtm, size/XS

#6183 Add label area/test-and-release to repo knative-serving
  core-services/prow/02_config/_labels.yaml
Labels: approved, lgtm, size/XS

#6233 Group auto updater rbacs
  cluster/ci/config/prow/openshift/ci-operator/roles.yaml
  core-services/group-auto-updater/OWNERS
  core-services/group-auto-updater/README.md
  core-services/group-auto-updater/admin_rbac.yaml
Labels: approved, lgtm, size/M

#6232 Don't protect 0.9.0 tekton
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm, size/XS

#6189 ci-operator/templates/openshift/installer/cluster-launch-installer-e2e: Gather node console logs on AWS
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
Labels: approved, lgtm, size/S

#6237 SDCICD-56. Remove dependency management from openshift/release.
  ci-operator/config/openshift/osde2e/openshift-osde2e-master.yaml
Labels: approved, lgtm, size/S

#6074 prow/bugzilla: Remove dependent bug config for ocs-operator
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/XS

#6221 ci-operator needs to be able to tag in ocp-arch
  cluster/ci/config/prow/openshift/ci-operator/roles.yaml
Labels: approved, lgtm, size/M

#6240 SDCICD-56. Use go 1.13 for osde2e tests.
  ci-operator/config/openshift/osde2e/openshift-osde2e-master.yaml
Labels: approved, lgtm, size/XS

#6243 Add 4.5 release jobs & configuration
  Makefile
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
  core-services/release-controller/_releases/release-ocp-4.5-ci.json
  core-services/release-controller/_releases/release-ocp-4.5-ppc64le.json
  core-services/release-controller/_releases/release-ocp-4.5-s390x.json
  core-services/release-controller/_releases/release-ocp-4.5.json
  core-services/release-controller/_repos/ocp-4.5-default.repo
  core-services/release-controller/_repos/ocp-4.5-openstack-beta.repo
  core-services/release-controller/_repos/ocp-4.5-openstack.repo
  core-services/release-controller/_repos/ocp-4.5-ppc64le.repo
  core-services/release-controller/_repos/ocp-4.5-rhel8.repo
  core-services/release-controller/_repos/ocp-4.5-s390x.repo
  core-services/release-controller/images-ocp-4.5.yaml
  core-services/release-controller/rpms-ocp-4.5.yaml
Labels: approved, lgtm, size/XXL

#6244 ci-operator/jobs/openshift/release: Fix e2e-aws-console subPath -> cluster-launch-installer-custom-test-image.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
Labels: approved, lgtm, size/XS

#6223 template: Use a more correct kill command
  ci-operator/templates/master-sidecar-3.yaml
  ci-operator/templates/master-sidecar-4.2.yaml
  ci-operator/templates/master-sidecar-4.3.yaml
  ci-operator/templates/master-sidecar-4.yaml
  ci-operator/templates/openshift/endurance/endurance-install.yaml
  ci-operator/templates/openshift/endurance/endurance-test.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-custom-test-image.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-libvirt-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-metal-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-src.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e-openshift-ansible.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e-openshift-jenkins.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e-upgrade.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-launch-src.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-scaleup-e2e-40.yaml
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure.yaml
  cluster/ci/config/service-ca.yaml
  core-services/ci-rpms/artifacts-rpms.yaml
  projects/gc-daemonset/daemonset.yaml
Labels: approved, lgtm, size/L

#6245 ci-operator/jobs/openshift/release: Add TEST_IMAGESTREAM_TAG to console for 4.4 and 4.5
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
Labels: approved, lgtm, size/XS

#6230 Tekton readd nop move knative tekton
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-next.yaml
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-next__variant.yaml
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.9.0.yaml
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.9.0__variant.yaml
Labels: approved, lgtm, size/M

#6236 Add postsubmit/periodic to auto update the openshift-priv-admins group
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
Labels: approved, lgtm, size/M

#6250 Run serverless upgrade tests separately
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.3__4.2.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.3__4.3.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.3-presubmits.yaml
Labels: approved, lgtm, size/L

#5887 cluster-openshift-apiserver-operator: remove make verify-deps
  ci-operator/config/openshift/cluster-openshift-apiserver-operator/openshift-cluster-openshift-apiserver-operator-master.yaml
  ci-operator/jobs/openshift/cluster-openshift-apiserver-operator/openshift-cluster-openshift-apiserver-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-openshift-apiserver-operator/openshift-cluster-openshift-apiserver-operator-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/cluster-openshift-apiserver-operator/openshift-cluster-openshift-apiserver-operator-release-4.4-presubmits.yaml
Labels: approved, lgtm, size/M

#6256 Fix the alert msg with @-mentioning the team
  cluster/ci/monitoring/mixins/prometheus/job_failures_alerts.libsonnet
  cluster/ci/monitoring/mixins/prometheus_out/prometheus_rule_prow.yaml
Labels: approved, lgtm, size/S

#6249 a/ci-operator/templates/openshift/installer/cluster-launch-installer-e2e: Set AWS_DEFAULT_REGION
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
Labels: approved, lgtm, size/XS

#6226 Enforce vendoring mode for OpenShift org
  projects/origin-release/golang-1.13/Dockerfile
  projects/origin-release/rhel-7-golang-1.13/Dockerfile
Labels: approved, lgtm, sig/master, size/XS

#6255 Remove lease container from remaining templates
  ci-operator/templates/openshift/installer/cluster-launch-installer-custom-test-image.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-src.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-scaleup-e2e-40.yaml
Labels: approved, lgtm, size/L

#6261 ci-operator: fcos branches should point to 4.4 now
  ci-operator/config/openshift/installer/openshift-installer-fcos.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-fcos.yaml
Labels: approved, lgtm, size/S

#6262 mirror: Update mappings to prefer origin and ocp
  core-services/image-mirroring/openshift/mapping_origin_4_1
  core-services/image-mirroring/openshift/mapping_origin_4_2
  core-services/image-mirroring/openshift/mapping_origin_4_3
  core-services/image-mirroring/openshift/mapping_origin_4_4
  hack/mirror-file
Labels: approved, lgtm, size/XXL

#6263 Remove code that waits for a lease from templates
  ci-operator/templates/openshift/installer/cluster-launch-installer-custom-test-image.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-src.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-scaleup-e2e-40.yaml
Labels: approved, lgtm, size/M

#6265 Wire job-config-4.5 jobs into services
  ci-operator/jobs/infra-periodics.yaml
  core-services/ci-chat-bot/deploy.yaml
  core-services/prow/03_deployment/deck.yaml
  core-services/prow/03_deployment/hook.yaml
  core-services/prow/03_deployment/horologium.yaml
  core-services/prow/03_deployment/jenkins_operator.yaml
  core-services/prow/03_deployment/plank.yaml
  core-services/prow/03_deployment/sinker.yaml
  core-services/prow/03_deployment/statusreconciler.yaml
  core-services/prow/03_deployment/tide.yaml
  core-services/prow/03_deployment/tot.yaml
  core-services/release-controller/deploy-ocp-controller-ppc64le.yaml
  core-services/release-controller/deploy-ocp-controller-s390x.yaml
  core-services/release-controller/deploy-ocp-controller.yaml
  core-services/release-controller/deploy-origin-controller.yaml
Labels: approved, lgtm, size/L

#6209 Minimal configuration for openshift-priv
  ci-operator/jobs/infra-periodics.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/M

#6147 Configure the first job for the openshift-kni/baremetal-deploy repository
  ci-operator/config/openshift-kni/baremetal-deploy/OWNERS
  ci-operator/config/openshift-kni/baremetal-deploy/openshift-kni-baremetal-deploy-master.yaml
  ci-operator/jobs/openshift-kni/baremetal-deploy/OWNERS
  ci-operator/jobs/openshift-kni/baremetal-deploy/openshift-kni-baremetal-deploy-master-presubmits.yaml
Labels: approved, lgtm, size/L

#6269 Fix boskos router's timeout
  core-services/prow/03_deployment/boskos.yaml
Labels: approved, lgtm, size/XS

#6264 Fix the breaking change on ci-secret-mirroring-controller jobs
  ci-operator/jobs/openshift/ci-secret-mirroring-controller/openshift-ci-secret-mirroring-controller-master-presubmits.yaml
Labels: approved, lgtm, size/S

#6274 Give release admins access to edit the multi arch ocp namespaces
  cluster/ci/config/roles.yaml
Labels: approved, lgtm, size/S

#6280 Inject build01_ci_reg_auth_value from env. var.
  core-services/build-farm/regcred_secret_template.yaml
Labels: approved, lgtm, size/XS

#6278 Fix the breaking changes for ci-secret-mirroring-controller jobs
  ci-operator/jobs/openshift/ci-secret-mirroring-controller/openshift-ci-secret-mirroring-controller-master-postsubmits.yaml
  ci-operator/jobs/openshift/ci-secret-mirroring-controller/openshift-ci-secret-mirroring-controller-master-presubmits.yaml
Labels: approved, lgtm, size/M

#6242 Add configs for openshift/file-integrity-operator
  ci-operator/config/openshift/file-integrity-operator/OWNERS
  ci-operator/config/openshift/file-integrity-operator/openshift-file-integrity-operator-master.yaml
  ci-operator/jobs/openshift/file-integrity-operator/OWNERS
  ci-operator/jobs/openshift/file-integrity-operator/openshift-file-integrity-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/file-integrity-operator/openshift-file-integrity-operator-master-presubmits.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/L

#6054 Add the steps for build01 CA certs in README
  clusters/build-clusters/01_cluster/openshift-ingress-operator/REAME.md
Labels: approved, lgtm, size/M

#6282 Enable review_acts_as_lgtm for 2 more dptp repos
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/XS

#6276 ci-operator/config/openshift/cluster-etcd-operator: add e2e-azure and e2e-gcp
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-master.yaml
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.4.yaml
  ci-operator/jobs/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.4-presubmits.yaml
Labels: approved, lgtm, size/L

#6285 boskos: gather metrics and expose a dashboard
  cluster/ci/monitoring/boskos_http_service_monitor.yaml
  cluster/ci/monitoring/mixins/Makefile
  cluster/ci/monitoring/mixins/config.libsonnet
  cluster/ci/monitoring/mixins/grafana_dashboards/boskos_http.jsonnet
  cluster/ci/monitoring/mixins/grafana_dashboards_out/boskos_http.json
  core-services/prow/03_deployment/boskos.yaml
Labels: approved, lgtm, size/XL

#6286 prow: remove deprecated allow_cancellations message
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm, size/S

#6288 boskos dashboard: add request latency by path
  cluster/ci/monitoring/mixins/grafana_dashboards/boskos_http.jsonnet
  cluster/ci/monitoring/mixins/grafana_dashboards/ghproxy.jsonnet
  cluster/ci/monitoring/mixins/grafana_dashboards_out/boskos_http.json
  cluster/ci/monitoring/mixins/grafana_dashboards_out/ghproxy.json
Labels: approved, lgtm, size/L

#6258 Add auto-merge and some additional plugins for openshift-kni/baremetal-deploy
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/M

#5996 Added e2e tests for insights-operator
  ci-operator/config/openshift/insights-operator/openshift-insights-operator-master.yaml
  ci-operator/config/openshift/insights-operator/openshift-insights-operator-release-4.2.yaml
  ci-operator/config/openshift/insights-operator/openshift-insights-operator-release-4.3.yaml
  ci-operator/config/openshift/insights-operator/openshift-insights-operator-release-4.4.yaml
  ci-operator/jobs/openshift/insights-operator/openshift-insights-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/insights-operator/openshift-insights-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/insights-operator/openshift-insights-operator-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/insights-operator/openshift-insights-operator-release-4.4-presubmits.yaml
Labels: approved, lgtm, size/L

#6292 Tekton version 0.9.1
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.9.1.yaml
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.9.1__variant.yaml
  ci-operator/jobs/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.9.1-postsubmits.yaml
  ci-operator/jobs/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.9.1-presubmits.yaml
  core-services/image-mirroring/tekton/mapping_tekton_v0_9_quay
Labels: approved, lgtm, size/XL

#6277 Add protobuf-devel to golang images
  projects/origin-release/golang-1.12/Dockerfile
  projects/origin-release/golang-1.13/Dockerfile
Labels: approved, lgtm, size/XS

#6268 Remove non-production ARO versions
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-release-v11.yaml
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-release-v9.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v11-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v9-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/XL

#6296 adds ci job for origin-4.4-kubernetes-1.17.0-rc.2
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-origin-4.4-kubernetes-1.17.0-rc.2.yaml
  ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-origin-4.4-kubernetes-1.17.0-rc.2-presubmits.yaml
Labels: approved, lgtm, size/L

#6299 Use shared E2E image for kubernetes-autoscaler
  ci-operator/config/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-master.yaml
  ci-operator/config/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-release-4.1.yaml
  ci-operator/config/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-release-4.2.yaml
  ci-operator/config/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-release-4.3.yaml
  ci-operator/config/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-release-4.4.yaml
  ci-operator/config/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-release-4.5.yaml
  ci-operator/jobs/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-master-presubmits.yaml
  ci-operator/jobs/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-release-4.5-presubmits.yaml
Labels: approved, lgtm, size/L

#6294 OKD: don't promote machine-os-content from OCP
  core-services/release-controller/_releases/release-ocp-4.3-ci.json
  core-services/release-controller/_releases/release-ocp-4.4-ci.json
  core-services/release-controller/_releases/release-ocp-4.5-ci.json
Labels: approved, lgtm, size/XS

#6301 Add openshift/oauth-apiserver repo
  ci-operator/config/openshift/oauth-apiserver/OWNERS
  ci-operator/config/openshift/oauth-apiserver/openshift-oauth-apiserver-master.yaml
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/oauth-apiserver/OWNERS
  ci-operator/jobs/openshift/oauth-apiserver/openshift-oauth-apiserver-master-postsubmits.yaml
  ci-operator/jobs/openshift/oauth-apiserver/openshift-oauth-apiserver-master-presubmits.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/L

#6305 Auto-rotate CA certs for apiserver of build01
  ci-operator/jobs/infra-periodics.yaml
  clusters/build-clusters/01_cluster/openshift-apiserver/REAME.md
  clusters/build-clusters/01_cluster/openshift-ingress-operator/REAME.md
  clusters/build-clusters/01_cluster/prow/03_deployment/admin_ca-cert-issuer_rbac.yaml
Labels: approved, lgtm, size/L

#6306 Remove erroneous spaces
  ci-operator/populate-secrets-from-bitwarden.sh
Labels: approved, lgtm, size/XS

#6307 add aws creds to upgrade job
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
Labels: approved, lgtm, size/XS

#6308 boskos server dashboard: quote query
  cluster/ci/monitoring/mixins/grafana_dashboards/boskos_http.jsonnet
  cluster/ci/monitoring/mixins/grafana_dashboards_out/boskos_http.json
Labels: approved, lgtm, size/S

#6310 boskos dashboard: count the amount of reuqests, not time
  cluster/ci/monitoring/mixins/grafana_dashboards/boskos_http.jsonnet
  cluster/ci/monitoring/mixins/grafana_dashboards_out/boskos_http.json
Labels: approved, lgtm, size/XS

#6304 periodics: Add a network stress test to 4.4
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
Labels: approved, lgtm, size/L

#6312 simply rely on the build target when building origin
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
Labels: approved, lgtm, size/XS

#6297 Bump golang to 1.13.5
  projects/origin-release/golang-1.13/Dockerfile
  projects/origin-release/rhel-7-golang-1.13/Dockerfile
Labels: approved, lgtm, size/XS

#6254 CNV CI - adding ci operator config files
  ci-operator/config/openshift-cnv/cnv-ci/OWNERS
  ci-operator/config/openshift-cnv/cnv-ci/openshift-cnv-cnv-ci-master.yaml
  ci-operator/jobs/openshift-cnv/cnv-ci/OWNERS
  ci-operator/jobs/openshift-cnv/cnv-ci/openshift-cnv-cnv-ci-master-presubmits.yaml
Labels: approved, lgtm, needs-ok-to-test, size/L

#6316 preinstalls gotestsum that is required in order to execute k8s unit tests
  projects/origin-release/golang-1.13/Dockerfile
  projects/origin-release/rhel-7-golang-1.13/Dockerfile
Labels: approved, lgtm, size/XS

#6318 Serverless on OCP 4.1 CI
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.3__4.1.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.3-postsubmits.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.3-presubmits.yaml
Labels: approved, lgtm, size/L

#6323 prow/plugins/bugzilla: Don't require any dependent bugs on master
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/S

#6325 Fix time of job periodic-acme-cert-issuer-for-build01
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm, size/XS

#6327 Sync labels for openshift-kni
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm, size/XS

#6328 sshd: update bastion connection script
  core-services/sshd-bastion/README.md
Labels: approved, lgtm, size/XS

#6329 Add --lease-server to more non-generated jobs
  ci-operator/jobs/openshift/release/openshift-release-infra-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.1-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
Labels: approved, lgtm, size/M

#5919 add fips_check to cluster-launch-installer-e2e.yaml template, for all jobs running that template
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
Labels: approved, lgtm, size/L

#6332 Populate 2 more configMaps to build01
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/XS

#6330 Enable CI for cluster-resource-override-admission-operator repo
  ci-operator/config/openshift/cluster-resource-override-admission-operator/OWNERS
  ci-operator/config/openshift/cluster-resource-override-admission-operator/openshift-cluster-resource-override-admission-operator-master.yaml
  ci-operator/jobs/openshift/cluster-resource-override-admission-operator/OWNERS
  ci-operator/jobs/openshift/cluster-resource-override-admission-operator/openshift-cluster-resource-override-admission-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-resource-override-admission-operator/openshift-cluster-resource-override-admission-operator-master-presubmits.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/L

#6339 Add a secret for cloning private repos
  ci-operator/populate-secrets-from-bitwarden.sh
Labels: approved, lgtm, size/XS

#6340 Add a local job for running unit tests
  ci-operator/config/openshift-kni/baremetal-deploy/openshift-kni-baremetal-deploy-master.yaml
  ci-operator/jobs/openshift-kni/baremetal-deploy/openshift-kni-baremetal-deploy-master-presubmits.yaml
Labels: approved, lgtm, size/M

#6341 Adding secret for registry login
  core-services/secret-mirroring/_mapping.yaml
Labels: approved, lgtm, size/S

#6198 odo enable lgtm_acts_as_approve and disable sticky lgtm
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/XS

#5976 Rename ironic-rhcos to ironic-machine-os
  ci-operator/config/openshift/ironic-rhcos-downloader/openshift-ironic-rhcos-downloader-master.yaml
  ci-operator/config/openshift/ironic-rhcos-downloader/openshift-ironic-rhcos-downloader-release-4.3.yaml
  ci-operator/config/openshift/ironic-rhcos-downloader/openshift-ironic-rhcos-downloader-release-4.4.yaml
  ci-operator/config/openshift/ironic-rhcos-downloader/openshift-ironic-rhcos-downloader-release-4.5.yaml
  ci-operator/jobs/openshift/ironic-rhcos-downloader/openshift-ironic-rhcos-downloader-release-4.5-postsubmits.yaml
  ci-operator/jobs/openshift/ironic-rhcos-downloader/openshift-ironic-rhcos-downloader-release-4.5-presubmits.yaml
  core-services/image-mirroring/openshift/mapping_origin_4_3
  core-services/release-controller/_releases/release-ocp-4.3-ci.json
  core-services/release-controller/_releases/release-ocp-4.4-ci.json
Labels: approved, lgtm, size/L

#6346 Add explicit namespaces to all ci-operator-misc-configs patterns
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/XS

#6345 Allow 4.4 repos to resolve from 4.4 mirror locations
  core-services/release-controller/_repos/ocp-4.4-default.repo
  core-services/release-controller/_repos/ocp-4.4-openstack-beta.repo
  core-services/release-controller/_repos/ocp-4.4-openstack.repo
  core-services/release-controller/_repos/ocp-4.4-ppc64le.repo
  core-services/release-controller/_repos/ocp-4.4-rhel8.repo
  core-services/release-controller/_repos/ocp-4.4-s390x.repo
Labels: approved, lgtm, size/M

#6315 mirroring: skip empty files
  ci-operator/jobs/infra-image-mirroring.yaml
Labels: approved, lgtm, size/XS

#6343 Turn on UseStatusAvailability in blunderbuss
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/XS

#6344 openshift/installer: Add e2e-metal presumbit for 4.3
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.3-presubmits.yaml
Labels: approved, lgtm, size/M

#6313 Add GCP tests to ocm
  ci-operator/config/openshift/openshift-controller-manager/openshift-openshift-controller-manager-master.yaml
  ci-operator/config/openshift/openshift-controller-manager/openshift-openshift-controller-manager-release-4.3.yaml
  ci-operator/config/openshift/openshift-controller-manager/openshift-openshift-controller-manager-release-4.4.yaml
  ci-operator/config/openshift/openshift-controller-manager/openshift-openshift-controller-manager-release-4.5.yaml
  ci-operator/jobs/openshift/openshift-controller-manager/openshift-openshift-controller-manager-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-controller-manager/openshift-openshift-controller-manager-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/openshift-controller-manager/openshift-openshift-controller-manager-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/openshift-controller-manager/openshift-openshift-controller-manager-release-4.5-presubmits.yaml
Labels: approved, lgtm, size/XL

#6350 Make the sctp-e2e job optional
  ci-operator/jobs/openshift-kni/baremetal-deploy/openshift-kni-baremetal-deploy-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#6349 add openshift-kubernetes-oc-4.4-kubernetes-1.17.0
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-oc-4.4-kubernetes-1.17.0.yaml
  ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-oc-4.4-kubernetes-1.17.0-presubmits.yaml
Labels: approved, lgtm, size/M

#6348 mirroring: skip mapping file when its empty
  ci-operator/jobs/infra-image-mirroring.yaml
Labels: approved, lgtm, size/XS

#6353 Add nilsanderselde
  projects/azure/OWNERS
Labels: approved, lgtm, sig/azure, size/XS

#6335 Populate template CMs to build01
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/S

#6355 Populate CM base-repos to build01
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/XS

#6356 Add shellcheck validation image
  services/validation-images/README.md
  services/validation-images/shellcheck/Dockerfile
  services/validation-images/shellcheck/shellcheck.yaml
Labels: approved, lgtm, size/M

#6351 Fix master release image to pull 4.4 rpms
  ci-operator/config/openshift/images/openshift-images-master.yaml
  ci-operator/config/openshift/images/openshift-images-release-4.4.yaml
  ci-operator/config/openshift/images/openshift-images-release-4.5.yaml
Labels: approved, lgtm, size/XS

#6352 Add more validation of step registry
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/step-registry/ipi/OWNERS
  ci-operator/step-registry/ipi/deprovision/OWNERS
  ci-operator/step-registry/ipi/deprovision/artifacts/OWNERS
  ci-operator/step-registry/ipi/deprovision/artifacts/artifacts/OWNERS
  ci-operator/step-registry/ipi/deprovision/artifacts/artifacts/ipi-deprovision-artifacts-artifacts-commands.sh
  ci-operator/step-registry/ipi/deprovision/artifacts/bootstrap/OWNERS
  ci-operator/step-registry/ipi/deprovision/artifacts/bootstrap/ipi-deprovision-artifacts-bootstrap-commands.sh
  ci-operator/step-registry/ipi/deprovision/artifacts/must-gather/OWNERS
  ci-operator/step-registry/ipi/deprovision/deprovision/OWNERS
  ci-operator/step-registry/ipi/install/OWNERS
  ci-operator/step-registry/ipi/install/install/OWNERS
  ci-operator/step-registry/ipi/install/rbac/OWNERS
  ci-operator/step-registry/ipi/install/rbac/ipi-install-rbac-commands.sh
  hack/validate-owners.sh
  hack/validate-registry-commands.sh
Labels: approved, lgtm, size/L

#6359 Add findutils to shellcheck image
  services/validation-images/shellcheck/Dockerfile
  services/validation-images/shellcheck/shellcheck.yaml
Labels: approved, lgtm, size/XS

#6363 Use golang1.13 as build base
  ci-operator/config/openshift/tektoncd-triggers/openshift-tektoncd-triggers-release-next.yaml
Labels: approved, lgtm, size/XS

#5904 sdn: stop building the old images
  ci-operator/config/openshift/sdn/openshift-sdn-master.yaml
  ci-operator/config/openshift/sdn/openshift-sdn-release-4.3.yaml
  ci-operator/config/openshift/sdn/openshift-sdn-release-4.4.yaml
Labels: approved, lgtm, size/M

#6357 boskos: emit debug logging
  core-services/prow/03_deployment/boskos.yaml
Labels: approved, lgtm, size/XS

#6260 INTLY-4201
  ci-operator/config/integr8ly/heimdall/OWNERS
  ci-operator/config/integr8ly/heimdall/integr8ly-heimdall-master.yaml
  ci-operator/jobs/integr8ly/heimdall/OWNERS
  ci-operator/jobs/integr8ly/heimdall/integr8ly-heimdall-master-postsubmits.yaml
  ci-operator/jobs/integr8ly/heimdall/integr8ly-heimdall-master-presubmits.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/L

#6369 Add RBAC for hook on NS OCP of build01
  clusters/build-clusters/01_cluster/prow/03_deployment/admin_hook_rbac.yaml
Labels: approved, lgtm, size/S

#6326 remove verify-deps job for library-go repo
  ci-operator/config/openshift/library-go/openshift-library-go-master.yaml
  ci-operator/jobs/openshift/library-go/openshift-library-go-master-presubmits.yaml
Labels: approved, lgtm, size/M

#6175 update private jobs to use OAuth token
  ci-operator/jobs/openshift/private-ci-testing/openshift-private-ci-testing-master-presubmits.yaml
Labels: approved, lgtm, size/S

#6367 Rework the baremetal kni sctp e2e tests command
  ci-operator/config/openshift-kni/baremetal-deploy/openshift-kni-baremetal-deploy-master.yaml
  ci-operator/jobs/openshift-kni/baremetal-deploy/openshift-kni-baremetal-deploy-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#6372 Add nilsanderselde
  projects/azure/cluster-wide.yaml
Labels: approved, lgtm, sig/azure, size/XS

#6358 Add integr8ly installation jobs
  ci-operator/config/integr8ly/installation/OWNERS
  ci-operator/config/integr8ly/installation/integr8ly-installation-master.yaml
  ci-operator/jobs/integr8ly/installation/OWNERS
  ci-operator/jobs/integr8ly/installation/integr8ly-installation-master-presubmits.yaml
Labels: approved, lgtm, size/M

#6337 Force vendoring mode for golang-1.13
  ci-operator/config/integr8ly/cloud-resource-operator/integr8ly-cloud-resource-operator-master.yaml
  ci-operator/config/openshift/file-integrity-operator/openshift-file-integrity-operator-master.yaml
  ci-operator/jobs/integr8ly/cloud-resource-operator/integr8ly-cloud-resource-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/file-integrity-operator/openshift-file-integrity-operator-master-presubmits.yaml
  projects/origin-release/golang-1.13/Dockerfile
  projects/origin-release/rhel-7-golang-1.13/Dockerfile
Labels: approved, lgtm, sig/master, size/S

#6364 Switch origin to golang-1.13
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
Labels: approved, lgtm, size/XS

#6321 Remove csi-driver-registrar image
  core-services/image-mirroring/openshift/mapping_origin_4_2
  core-services/image-mirroring/openshift/mapping_origin_4_3
  core-services/image-mirroring/openshift/mapping_origin_4_4
Labels: approved, lgtm, size/XS

#6370 Move logging config under core-services
  core-services/cluster/logging/admin_fluentd-configmap.yaml
  core-services/cluster/logging/admin_fluentd-daemonset.yaml
Labels: approved, lgtm, size/XS

#6374 Revert "Don't force vendoring for openshift/file-integrity-operator"
  ci-operator/config/openshift/file-integrity-operator/openshift-file-integrity-operator-master.yaml
  ci-operator/jobs/openshift/file-integrity-operator/openshift-file-integrity-operator-master-presubmits.yaml
Labels: approved, lgtm, size/S

#6362 require explicit approve from approvers on openshift/installer repo
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/XS

#6360 update golang version for clo and eo
  ci-operator/config/openshift/cluster-logging-operator/openshift-cluster-logging-operator-master.yaml
  ci-operator/config/openshift/elasticsearch-operator/openshift-elasticsearch-operator-master.yaml
Labels: approved, lgtm, size/XS

#6354 Deploy yum SVCs on build01
  Makefile
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  clusters/build-clusters/01_cluster/openshift/release-controller/content-mirror_imagestream.yaml
  clusters/build-clusters/01_cluster/openshift/release-controller/ocp_namespace.yaml
  clusters/build-clusters/01_cluster/openshift/release-controller/rpms-ocp-4.1.yaml
  clusters/build-clusters/01_cluster/openshift/release-controller/rpms-ocp-4.2.yaml
  clusters/build-clusters/01_cluster/openshift/release-controller/rpms-ocp-4.3.yaml
  clusters/build-clusters/01_cluster/openshift/release-controller/rpms-ocp-4.4.yaml
  clusters/build-clusters/01_cluster/openshift/release-controller/rpms-ocp-4.5.yaml
  clusters/build-clusters/01_cluster/prow/03_deployment/admin_config_updater_rbac.yaml
Labels: approved, lgtm, size/XXL

#6377 Don't force venfdorign for openshift/managed-velero-operator
  ci-operator/config/openshift/managed-velero-operator/openshift-managed-velero-operator-master.yaml
Labels: approved, lgtm, size/XS

#6378 Bootstrapping secret mirroring for new multi-arch release-controllers
  core-services/prow/03_deployment/admin_config_updater_rbac.yaml
  core-services/release-controller/admin_deploy-ocp-controller-ppc64le.yaml
  core-services/release-controller/admin_deploy-ocp-controller-s390x.yaml
Labels: approved, lgtm, size/M

#6291 Enable openshift/hypershift-toolkit repository
  ci-operator/config/openshift/hypershift-toolkit/OWNERS
  ci-operator/config/openshift/hypershift-toolkit/openshift-hypershift-toolkit-master.yaml
  ci-operator/jobs/openshift/hypershift-toolkit/OWNERS
  ci-operator/jobs/openshift/hypershift-toolkit/openshift-hypershift-toolkit-master-postsubmits.yaml
  ci-operator/jobs/openshift/hypershift-toolkit/openshift-hypershift-toolkit-master-presubmits.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/L

#6381 PromeCIeus: bump quota to 11 (10 prom instances)
  services/promecieus/13-resource-quota.yaml
Labels: approved, lgtm, size/XS

#6387 Add triggers and pipelines-tutorial
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm, size/XS

#6235 Migrate initial repos to golang-1.13 for 1.17 rebase
  ci-operator/config/openshift/apiserver-library-go/openshift-apiserver-library-go-master.yaml
  ci-operator/config/openshift/client-go/openshift-client-go-master.yaml
  ci-operator/config/openshift/cluster-authentication-operator/openshift-cluster-authentication-operator-master.yaml
  ci-operator/config/openshift/cluster-bootstrap/openshift-cluster-bootstrap-master.yaml
  ci-operator/config/openshift/cluster-config-operator/openshift-cluster-config-operator-master.yaml
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-master.yaml
  ci-operator/config/openshift/cluster-kube-apiserver-operator/openshift-cluster-kube-apiserver-operator-master.yaml
  ci-operator/config/openshift/cluster-kube-controller-manager-operator/openshift-cluster-kube-controller-manager-operator-master.yaml
  ci-operator/config/openshift/cluster-kube-scheduler-operator/openshift-cluster-kube-scheduler-operator-master.yaml
  ci-operator/config/openshift/cluster-kube-storage-version-migrator-operator/openshift-cluster-kube-storage-version-migrator-operator-master.yaml
  ci-operator/config/openshift/cluster-openshift-apiserver-operator/openshift-cluster-openshift-apiserver-operator-master.yaml
  ci-operator/config/openshift/cluster-openshift-controller-manager-operator/openshift-cluster-openshift-controller-manager-operator-master.yaml
  ci-operator/config/openshift/cluster-policy-controller/openshift-cluster-policy-controller-master.yaml
  ci-operator/config/openshift/cluster-resource-override-admission/openshift-cluster-resource-override-admission-master.yaml
  ci-operator/config/openshift/kubernetes-kube-storage-version-migrator/openshift-kubernetes-kube-storage-version-migrator-master.yaml
  ci-operator/config/openshift/library-go/openshift-library-go-master.yaml
  ci-operator/config/openshift/oauth-proxy/openshift-oauth-proxy-master.yaml
  ci-operator/config/openshift/oauth-server/openshift-oauth-server-master.yaml
  ci-operator/config/openshift/oc/openshift-oc-master.yaml
  ci-operator/config/openshift/openshift-apiserver/openshift-openshift-apiserver-master.yaml
  ci-operator/config/openshift/openshift-controller-manager/openshift-openshift-controller-manager-master.yaml
Labels: approved, lgtm, sig/master, size/M

#6390 TektonCD version 0.9.2
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.9.2.yaml
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.9.2__variant.yaml
  ci-operator/jobs/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.9.2-postsubmits.yaml
  ci-operator/jobs/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.9.2-presubmits.yaml
  core-services/image-mirroring/tekton/mapping_tekton_v0_9_quay
Labels: approved, lgtm, size/XL

#6371 kn release v0.10.0
  ci-operator/config/openshift/knative-client/openshift-knative-client-release-v0.10.0.yaml
  ci-operator/jobs/openshift/knative-client/openshift-knative-client-release-v0.10.0-postsubmits.yaml
  ci-operator/jobs/openshift/knative-client/openshift-knative-client-release-v0.10.0-presubmits.yaml
  core-services/image-mirroring/knative/mapping_knative_v0_10_quay
Labels: approved, lgtm, size/L

#6392 enable spyglass in deck-internal
  core-services/prow/03_deployment/deck.yaml
Labels: approved, lgtm, size/XS

#6391 Remove OpenStack repos from Kuryr builds
  ci-operator/config/openshift/kuryr-kubernetes/openshift-kuryr-kubernetes-release-4.3.yaml
  ci-operator/config/openshift/kuryr-kubernetes/openshift-kuryr-kubernetes-release-4.4.yaml
  ci-operator/config/openshift/kuryr-kubernetes/openshift-kuryr-kubernetes-release-4.5.yaml
Labels: approved, lgtm, size/S

#6393 add deck internal job url prefix
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm, size/XS

#6399 ocs-operator: Add new owners
  ci-operator/config/openshift/ocs-operator/OWNERS
  ci-operator/jobs/openshift/ocs-operator/OWNERS
Labels: approved, lgtm, size/XS
