Repository openshift/release, pull requests merged in 2019-11, with the labels that each got.

#5698 Add rbac for SA hook on ns ci-stg at build01
  clusters/build-clusters/01_cluster/prow/03_deployment/admin_config_updater_rbac.yaml
  clusters/build-clusters/01_cluster/prow/03_deployment/admin_hook_rbac.yaml
  clusters/build-clusters/01_cluster/prow/03_deployment/ci_ns.yaml
Labels: approved, lgtm, size/L

#5724 Fix typo on ovn job name
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
Labels: approved, lgtm, size/XS

#5712 Enable dev team full access to modify prowjobs in our "job" namespace
  services/release-controller-test/admin_02_rbac.yaml
Labels: approved, lgtm, size/S

#5665 Add gofmt check for sriov-network-operator
  ci-operator/config/openshift/sriov-network-operator/openshift-sriov-network-operator-master.yaml
  ci-operator/config/openshift/sriov-network-operator/openshift-sriov-network-operator-release-4.3.yaml
  ci-operator/config/openshift/sriov-network-operator/openshift-sriov-network-operator-release-4.4.yaml
  ci-operator/jobs/openshift/sriov-network-operator/openshift-sriov-network-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/sriov-network-operator/openshift-sriov-network-operator-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/sriov-network-operator/openshift-sriov-network-operator-release-4.4-presubmits.yaml
Labels: approved, lgtm, size/L

#5727 ci-operator/config/openshift/cluster-etcd-operator: add aws-e2e and gcp-upgrade
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.3.yaml
  ci-operator/jobs/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.3-presubmits.yaml
Labels: approved, lgtm, size/L

#5726 Enable build-farm for config-bootstrapper
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm, size/S

#5729 ci-operator/config/openshift/cluster-etcd-operator: add aws-e2e and gcp-upgrade to master/4.4
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-master.yaml
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.4.yaml
  ci-operator/jobs/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.4-presubmits.yaml
Labels: approved, lgtm, size/L

#5433 make changes to internal deck deployment for private repositories
  core-services/prow/02_config/_config.yaml
  core-services/prow/03_deployment/deck.yaml
Labels: approved, lgtm, size/XS

#5731 In GCP startup, check oauth2.googleapis.com for availability
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  core-services/ci-search/deploy.yaml
Labels: approved, lgtm, size/S

#5732 Send an empty body curl to check google api
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
Labels: approved, lgtm, size/XS

#5730 Add env. var. slack_api_url into applyconfig job
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
Labels: approved, lgtm, size/S

#5735 Use RHEL AMI for worker scaleup
  cluster/test-deploy/aws-4.0/vars.yaml
Labels: approved, lgtm, size/XS

#5739 Define ${build01_ci_reg_auth_value} for applyconfig
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/populate-secrets-from-bitwarden.sh
Labels: approved, lgtm, size/S

#5740 Use ci-operator image in test job on build01
  ci-operator/jobs/openshift/ci-secret-mirroring-controller/openshift-ci-secret-mirroring-controller-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#5738 Use pull secret for ci-operator SA on build01
  clusters/build-clusters/01_cluster/openshift/ci-operator/admin_ci-operator_rbac.yaml
  clusters/build-clusters/01_cluster/openshift/ci-operator/regcred_secret_template.yaml
  core-services/build-farm/OWNERS
  core-services/build-farm/README.md
  core-services/build-farm/admin_build01_rbac.yaml
Labels: approved, lgtm, size/M

#5742 RHEL Workers, add RHEL RPM mirrors
  cluster/test-deploy/aws-4.0/vars.yaml
Labels: approved, lgtm, size/M

#5705 Update images and CI files for eventing-contrib 0.10.0
  ci-operator/config/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-v0.10.0.yaml
  ci-operator/config/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-v0.10.0__4.3.yaml
  ci-operator/config/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-v0.10.0__variant.yaml
  ci-operator/jobs/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-v0.10.0-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-v0.10.0-presubmits.yaml
  core-services/image-mirroring/knative/mapping_knative_v0_10_quay
Labels: approved, lgtm, size/XL

#5746 images: Use the correct RPM repos for base images
  ci-operator/config/openshift/images/openshift-images-master.yaml
  ci-operator/config/openshift/images/openshift-images-release-4.3.yaml
  ci-operator/config/openshift/images/openshift-images-release-4.4.yaml
Labels: approved, lgtm, size/XS

#5721 OpenShift Pipelines: remove gsutil image
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-next.yaml
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-next__variant.yaml
Labels: approved, lgtm, size/S

#5748 OpenShift Pipelines: remove nop image
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-next.yaml
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-next__variant.yaml
  core-services/image-mirroring/tekton/mapping_tekton_nihghtly_quay
Labels: approved, lgtm, size/S

#5747 Prepare tests for ARO plugin release-v11 branch
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-release-v11.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v11-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/L

#5751 Update oc-kubernetes fork to use 1.16.2
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-oc-4.3-kubernetes-1.16.2.yaml
  ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-oc-4.3-kubernetes-1.16.2-presubmits.yaml
Labels: approved, lgtm, size/XS

#5753 Use origin-cli:4.3 for image mirroring jobs
  ci-operator/jobs/infra-image-mirroring.yaml
Labels: approved, lgtm, size/S

#5688 switch all console template jobs to use custom image template
  ci-operator/config/openshift/cluster-authentication-operator/openshift-cluster-authentication-operator-release-4.1.yaml
  ci-operator/config/openshift/console-operator/openshift-console-operator-master.yaml
  ci-operator/config/openshift/console-operator/openshift-console-operator-release-4.1.yaml
  ci-operator/config/openshift/console-operator/openshift-console-operator-release-4.2.yaml
  ci-operator/config/openshift/console-operator/openshift-console-operator-release-4.3.yaml
  ci-operator/config/openshift/console-operator/openshift-console-operator-release-4.4.yaml
  ci-operator/jobs/openshift/cluster-authentication-operator/openshift-cluster-authentication-operator-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/console-operator/openshift-console-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/console-operator/openshift-console-operator-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/console-operator/openshift-console-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/console-operator/openshift-console-operator-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/console-operator/openshift-console-operator-release-4.4-presubmits.yaml
Labels: approved, lgtm, size/M

#5761 Exclude machine-config-operator-rpms from OKD sync
  ci-operator/infra/openshift/release-controller/releases/release-ocp-4.3-ci.json
Labels: approved, lgtm, size/XS

#5716 Reconfigure RPM repos to use separate mounts
  core-services/prow/03_deployment/admin_config_updater_rbac.yaml
  core-services/release-controller/_repos/ocp-4.1-default.repo
  core-services/release-controller/_repos/ocp-4.2-default.repo
  core-services/release-controller/_repos/ocp-4.2-openstack.repo
  core-services/release-controller/_repos/ocp-4.2-s390x.repo
  core-services/release-controller/_repos/ocp-4.3-default.repo
  core-services/release-controller/_repos/ocp-4.3-openstack-beta.repo
  core-services/release-controller/_repos/ocp-4.3-openstack.repo
  core-services/release-controller/_repos/ocp-4.3-ppc64le.repo
  core-services/release-controller/_repos/ocp-4.3-rhel8.repo
  core-services/release-controller/_repos/ocp-4.3-s390x.repo
  core-services/release-controller/admin_config_updater_rbac.yaml
  core-services/release-controller/rpms-ocp-4.1.yaml
  core-services/release-controller/rpms-ocp-4.2.yaml
  core-services/release-controller/rpms-ocp-4.3.yaml
Labels: approved, lgtm, size/XL

#5762 Correct input machine-os-content from FCoS
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-fcos.yaml
Labels: approved, lgtm, size/XS

#5766 Remove old release configurations
  Makefile
  ci-operator/infra/openshift/release-controller/releases/release-ocp-4.1-ci.json
  ci-operator/infra/openshift/release-controller/releases/release-ocp-4.1.json
  ci-operator/infra/openshift/release-controller/releases/release-ocp-4.2-ci.json
  ci-operator/infra/openshift/release-controller/releases/release-ocp-4.2-s390x.json
  ci-operator/infra/openshift/release-controller/releases/release-ocp-4.2.json
  ci-operator/infra/openshift/release-controller/releases/release-ocp-4.3-ci.json
  ci-operator/infra/openshift/release-controller/releases/release-ocp-4.3-ppc64le.json
  ci-operator/infra/openshift/release-controller/releases/release-ocp-4.3-s390x.json
  ci-operator/infra/openshift/release-controller/releases/release-ocp-4.3.json
  ci-operator/infra/openshift/release-controller/releases/release-ocp-4.y-stable.json
  ci-operator/infra/openshift/release-controller/releases/release-origin-4.3.json
Labels: approved, lgtm, size/L

#5765 Remove old repository configurations
  ci-operator/infra/openshift/release-controller/repos/ocp-4.1-default.repo
  ci-operator/infra/openshift/release-controller/repos/ocp-4.2-default.repo
  ci-operator/infra/openshift/release-controller/repos/ocp-4.2-openstack.repo
  ci-operator/infra/openshift/release-controller/repos/ocp-4.2-s390x.repo
  ci-operator/infra/openshift/release-controller/repos/ocp-4.3-default.repo
  ci-operator/infra/openshift/release-controller/repos/ocp-4.3-openstack-beta.repo
  ci-operator/infra/openshift/release-controller/repos/ocp-4.3-openstack.repo
  ci-operator/infra/openshift/release-controller/repos/ocp-4.3-ppc64le.repo
  ci-operator/infra/openshift/release-controller/repos/ocp-4.3-rhel8.repo
  ci-operator/infra/openshift/release-controller/repos/ocp-4.3-s390x.repo
Labels: approved, lgtm, size/L

#5760 knative-client release v0.9.0 setup
  ci-operator/config/openshift/knative-client/openshift-knative-client-release-v0.9.0.yaml
  ci-operator/jobs/openshift/knative-client/openshift-knative-client-release-v0.9.0-postsubmits.yaml
  ci-operator/jobs/openshift/knative-client/openshift-knative-client-release-v0.9.0-presubmits.yaml
  core-services/image-mirroring/knative/mapping_knative_v0_9_quay
Labels: approved, lgtm, size/L

#5764 ci-operator: Add build and run tests for Presto feature branches
  ci-operator/config/operator-framework/presto/operator-framework-presto-feature.yaml
  ci-operator/jobs/operator-framework/presto/operator-framework-presto-feature-presubmits.yaml
Labels: approved, lgtm, size/L

#5736 Switch to the rhel golang builder
  ci-operator/config/openshift/origin/openshift-origin-release-4.3.yaml
Labels: approved, lgtm, size/XS

#5773 bump deck-internal resources request
  core-services/prow/03_deployment/deck.yaml
Labels: approved, lgtm, size/XS

#5754 Use origin-cli:4.3 for image pruning job
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm, size/XS

#5743 ci-operator/templates/openshift/installer/cluster-launch-installer-console: Add must-gather
  ci-operator/templates/openshift/installer/cluster-launch-installer-console.yaml
Labels: approved, lgtm

#5774 allow deck sa to watch prowjobs
  core-services/prow/03_deployment/admin_deck_rbac.yaml
Labels: approved, lgtm, size/XS

#5775 Revert "Use origin-cli:4.3 for image pruning job"
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm, size/XS

#5612 Make conformance e2e test mandatory on OVN-kube repo
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#5776 fix prow memory usage grafana dashboard
  cluster/ci/monitoring/mixins/grafana_dashboards/prow.jsonnet
  cluster/ci/monitoring/mixins/grafana_dashboards_out/prow.json
  core-services/openshift-monitoring/cfg_prometheus-prow-rules_prometheusrule.yaml
Labels: approved, lgtm, size/S

#5723 Increase resource requests for image registry 3.11.
  ci-operator/config/openshift/image-registry/openshift-image-registry-release-3.11.yaml
  ci-operator/config/openshift/image-registry/openshift-image-registry-release-4.1.yaml
  ci-operator/config/openshift/image-registry/openshift-image-registry-release-4.2.yaml
Labels: approved, lgtm, size/S

#5770 openshift/release-4.3: add ovn release informers
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
  core-services/release-controller/_releases/release-ocp-4.3.json
Labels: approved, lgtm, size/L

#5780 Add the multi-arch annotations back for ART builds
  Makefile
Labels: approved, lgtm, size/XS

#4719 Creating squid AMI in VPC for CI aws proxy testing
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
Labels: approved, lgtm, size/XL

#5782 Allow ci-admins to update secrets in ci-release without impersonating
  services/ci-release/OWNERS
  services/ci-release/README.md
  services/ci-release/admin_ci-admin_rbac.yaml
Labels: approved, lgtm, size/M

#5757 Set always_run to true for integr8ly/integreatly-operator e2e job
  ci-operator/jobs/integr8ly/integreatly-operator/integr8ly-integreatly-operator-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#5785 Configures protection for release-v0.9.0 branch of knative-client
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm, size/XS

#5783 enable tide for PTP repos
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm, size/XS

#5701 Update configmap ci-operator-master-configs to build01
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/XS

#5786 FOR test only: will be reverted
  ci-operator/config/openshift/ci-secret-mirroring-controller/openshift-ci-secret-mirroring-controller-master.yaml
  ci-operator/jobs/openshift/ci-secret-mirroring-controller/openshift-ci-secret-mirroring-controller-master-presubmits.yaml
Labels: approved, lgtm, size/M

#5787 Revert "FOR test only: will be reverted"
  ci-operator/config/openshift/ci-secret-mirroring-controller/openshift-ci-secret-mirroring-controller-master.yaml
  ci-operator/jobs/openshift/ci-secret-mirroring-controller/openshift-ci-secret-mirroring-controller-master-presubmits.yaml
Labels: approved, lgtm, size/M

#5709 Adding placeholder for rhel8 release image
  projects/origin-release/pipeline.yaml
  projects/origin-release/rhel-8-golang-1.12/CentOS-Base.repo
  projects/origin-release/rhel-8-golang-1.12/Dockerfile
  projects/origin-release/rhel-8-golang-1.12/RPM-GPG-KEY-centosofficial
  projects/origin-release/rhel-8-golang-1.12/cbs-paas7-openshift-multiarch-el7-build.repo
Labels: approved, lgtm, size/L

#5788 Use configmap for env var CONFIG_SPEC on build01
  ci-operator/jobs/openshift/ci-secret-mirroring-controller/openshift-ci-secret-mirroring-controller-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#5621 OpenStack: Collect nodes console logs
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e.yaml
Labels: approved, lgtm, size/XS

#5789 Add multi-arch stubs to core-services
  core-services/release-controller/images-ocp-4.2.yaml
  core-services/release-controller/images-ocp-4.3.yaml
Labels: approved, lgtm, size/S

#5791 Specify cluster for ci-secret-mirroring-controller's base image
  ci-operator/config/openshift/ci-secret-mirroring-controller/openshift-ci-secret-mirroring-controller-master.yaml
Labels: approved, lgtm, size/XS

#5792 Specify cluster for ci-secret-mirroring-controller's os image
  ci-operator/config/openshift/ci-secret-mirroring-controller/openshift-ci-secret-mirroring-controller-master.yaml
Labels: approved, lgtm, size/XS

#5793 Stop using the source cache for Origin
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.1.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.2.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.3.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.4.yaml
Labels: approved, lgtm, size/M

#5794 Add rbac for SA ci-operator on build01
  clusters/build-clusters/01_cluster/openshift/ci-operator/admin_ci-operator_rbac.yaml
Labels: approved, lgtm, size/M

#5795 Specify cluster to promote secret-mirroring image
  ci-operator/config/openshift/ci-secret-mirroring-controller/openshift-ci-secret-mirroring-controller-master.yaml
Labels: approved, lgtm, size/XS

#5728 Add original alertmanager-main_secret on build01
  clusters/build-clusters/01_cluster/openshift-monitoring/alertmanager-main_secret_template.yaml
  clusters/build-clusters/01_cluster/openshift-monitoring/cluster-monitoring-config_configmap.yaml
  clusters/build-clusters/01_cluster/prow/03_deployment/admin_config_updater_rbac.yaml
Labels: approved, lgtm, size/M, ¯\_(ツ)_/¯

#5668 Make Tripleo based zuul jobs non-blocking on libpod PRs
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#5799 Adding squid-helpers package to squid Dockerfile
  services/squid-egress-proxy/Dockerfile
Labels: approved, lgtm, size/XS

#5749 ci-operator/templates: Pull AWS region and zone from the cluster for TEST_PROVIDER
  ci-operator/templates/openshift/installer/cluster-launch-installer-console.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-custom-test-image.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-src.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-scaleup-e2e-40.yaml
Labels: approved, lgtm, size/S

#5781 Bumping 4.2 and 4.3 proxy canary to use upi test instead
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
Labels: approved, lgtm, size/XS

#5803 dashboards: Add OpenStack to Boskos "Running Clusters" chart
  cluster/ci/monitoring/mixins/grafana_dashboards/boskos.jsonnet
  cluster/ci/monitoring/mixins/grafana_dashboards_out/boskos.json
Labels: approved, lgtm, size/S

#5801 Update integr8ly/integreatly-operator tag_specification to 4.2
  ci-operator/config/integr8ly/integreatly-operator/integr8ly-integreatly-operator-master.yaml
Labels: approved, lgtm, size/XS

#4555 Capture Webpack bundle analysis for console in CI
  ci-operator/config/openshift/console/openshift-console-master.yaml
  ci-operator/jobs/openshift/console/openshift-console-master-presubmits.yaml
Labels: approved, lgtm, size/M

#5805 Add openshift-priv crd and rbacs
  core-services/prow/01_crd/admin_03_openshift-priv_crd.yaml
  core-services/prow/01_crd/admin_04_openshift-priv_rbac.yaml
Labels: approved, lgtm, size/M

#5808 fix apigroup in openshift-priv crd and rbacs
  core-services/prow/01_crd/admin_03_openshift-priv_crd.yaml
  core-services/prow/01_crd/admin_04_openshift-priv_rbac.yaml
Labels: approved, lgtm, size/XS

#5806 Uses correct tag for kn v0.9.0 image
  core-services/image-mirroring/knative/mapping_knative_v0_9_quay
Labels: approved, lgtm, size/XS

#5807 change deck-internal SAR configuration
  core-services/prow/03_deployment/deck.yaml
Labels: approved, lgtm, size/XS

#5798 CI configuration for openshift/coredns-mdns
  ci-operator/config/openshift/coredns-mdns/openshift-coredns-mdns-master.yaml
  ci-operator/jobs/openshift/coredns-mdns/openshift-coredns-mdns-master-presubmits.yaml
Labels: approved, lgtm, size/M

#5809 Remove the deprecated fields in plugins.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/L

#5812 openstack: Explain the Smoke test filter
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e.yaml
Labels: approved, lgtm, size/XS

#5810 remove openshift-privs crd and add namespace,group and rbacs
  cluster/ci/config/roles.yaml
  core-services/prow/01_crd/admin_03_openshift-priv_crd.yaml
  core-services/prow/01_crd/admin_04_openshift-priv_rbac.yaml
Labels: approved, lgtm, size/M

#5811 Add a presubmit that ensures prow config is formatted
  Makefile
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
  hack/validate-prow-config-formatting.sh
Labels: approved, lgtm, size/XXL

#5817 Fix the script name in the new presubmit
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#5818 Remove the prow config job
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
Labels: needs-rebase, size/S

#5758 Add fast-datapath-beta repos
  core-services/release-controller/_repos/ocp-4.3-default.repo
  core-services/release-controller/_repos/ocp-4.3-ppc64le.repo
  core-services/release-controller/_repos/ocp-4.3-rhel8.repo
  core-services/release-controller/_repos/ocp-4.3-s390x.repo
Labels: approved, lgtm, size/M

#5815 change SAR configuration in deck-internal
  core-services/prow/03_deployment/deck.yaml
Labels: approved, lgtm, size/XS

#5819 Revert "Remove the prow config job"
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  hack/validate-prow-config-formatting.sh
Labels: approved, lgtm, size/S

#5790 Add a job: pull-ci-openshift-ci-secret-mirroring-controller-master-images-build01
  ci-operator/jobs/openshift/ci-secret-mirroring-controller/openshift-ci-secret-mirroring-controller-master-presubmits.yaml
Labels: approved, lgtm, size/M

#5816 Remove redundant trigger configuration
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/S

#5604 SDCICD-68. Reintroduce prod-4.2 and prod-4.2-4.2 osde2e jobs.
  ci-operator/config/openshift/osde2e/openshift-osde2e-master.yaml
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-master-periodics.yaml
Labels: approved, lgtm, size/L

#5797 Run job ci-secret-mirroring-controller-master-images on build01
  ci-operator/jobs/openshift/ci-secret-mirroring-controller/openshift-ci-secret-mirroring-controller-master-postsubmits.yaml
Labels: approved, lgtm, size/XS

#5820 Add a make target to branch-cut a single repo
  Makefile
Labels: approved, lgtm, size/XS

#5756 Use custom build_root
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-master.yaml
Labels: approved, lgtm, size/XS

#5822 Generate private jobs as hidden
  ci-operator/jobs/openshift/private-ci-testing/openshift-private-ci-testing-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#5827 Prepare 4.4 release controller resources
  Makefile
  ci-operator/config/openshift/images/openshift-images-release-4.4.yaml
  core-services/release-controller/_releases/release-ocp-4.4-ci.json
  core-services/release-controller/_releases/release-ocp-4.4-ppc64le.json
  core-services/release-controller/_releases/release-ocp-4.4-s390x.json
  core-services/release-controller/_releases/release-ocp-4.4.json
  core-services/release-controller/_repos/ocp-4.4-default.repo
  core-services/release-controller/_repos/ocp-4.4-openstack-beta.repo
  core-services/release-controller/_repos/ocp-4.4-openstack.repo
  core-services/release-controller/_repos/ocp-4.4-ppc64le.repo
  core-services/release-controller/_repos/ocp-4.4-rhel8.repo
  core-services/release-controller/_repos/ocp-4.4-s390x.repo
  core-services/release-controller/images-ocp-4.4.yaml
  core-services/release-controller/rpms-ocp-4.4.yaml
Labels: approved, lgtm, size/XL

#5831 fix prow-config in Makefile
  Makefile
Labels: approved, lgtm, size/XS

#5755 Add integr8ly/cloud-resource-operator to CI
  ci-operator/config/integr8ly/cloud-resource-operator/OWNERS
  ci-operator/config/integr8ly/cloud-resource-operator/integr8ly-cloud-resource-operator-master.yaml
  ci-operator/jobs/integr8ly/cloud-resource-operator/OWNERS
  ci-operator/jobs/integr8ly/cloud-resource-operator/integr8ly-cloud-resource-operator-master-postsubmits.yaml
  ci-operator/jobs/integr8ly/cloud-resource-operator/integr8ly-cloud-resource-operator-master-presubmits.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/L

#5828 fast-datapath-beta: disable repos by default
  core-services/release-controller/_repos/ocp-4.3-default.repo
  core-services/release-controller/_repos/ocp-4.3-ppc64le.repo
  core-services/release-controller/_repos/ocp-4.3-rhel8.repo
  core-services/release-controller/_repos/ocp-4.3-s390x.repo
Labels: approved, lgtm, size/XS

#5830 Expose ci-operator-configresolver
  core-services/ci-operator-configresolver/ci-operator-configresolver.yaml
Labels: approved, lgtm, size/S

#5796 Do not push to docker.io
  core-services/base-ci-images/images-ocp.yaml
  core-services/base-ci-images/images-origin.yaml
  projects/origin-release/pipeline.yaml
  projects/origin-stable/release.yaml
Labels: approved, lgtm, size/L

#5804 Enable e2e-*-operator machine api suite to always run on mao, machine-approver and autoscaler
  ci-operator/config/openshift/cluster-machine-approver/openshift-cluster-machine-approver-master.yaml
  ci-operator/config/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-master.yaml
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-master.yaml
  ci-operator/jobs/openshift/cluster-machine-approver/openshift-cluster-machine-approver-master-presubmits.yaml
  ci-operator/jobs/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-master-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-master-presubmits.yaml
Labels: approved, lgtm, size/XL

#5825 Sync ci-operator image to build01
  clusters/build-clusters/01_cluster/openshift-image-registry/README.md
  clusters/build-clusters/01_cluster/openshift/ci-operator/admin_ci-operator_rbac.yaml
  clusters/build-clusters/01_cluster/openshift/ci-operator/ci-operator_imagestream.yaml
Labels: approved, lgtm, size/M

#5834 Revert "Merge pull request #5796 from jupierce/quiet"
  core-services/base-ci-images/images-ocp.yaml
  core-services/base-ci-images/images-origin.yaml
  projects/origin-release/pipeline.yaml
  projects/origin-stable/release.yaml
Labels: approved, lgtm, size/L

#5843 ci-operator: Update metering to use 4.4 for fast-forwards/promotions from master
  ci-operator/config/operator-framework/operator-metering/operator-framework-operator-metering-master.yaml
  ci-operator/config/operator-framework/operator-metering/operator-framework-operator-metering-release-4.3.yaml
  ci-operator/config/operator-framework/operator-metering/operator-framework-operator-metering-release-4.4.yaml
  ci-operator/jobs/operator-framework/operator-metering/operator-framework-operator-metering-release-4.3-presubmits.yaml
  ci-operator/jobs/operator-framework/operator-metering/operator-framework-operator-metering-release-4.4-presubmits.yaml
Labels: approved, lgtm, size/S

#5844 Generate aws-openshift-llc-account-credentials from BW
  ci-operator/populate-secrets-from-bitwarden.sh
Labels: approved, lgtm, size/XS

#5824 Switch fips e2e jobs to use day 1 support
  ci-operator/templates/openshift/installer/cluster-launch-installer-custom-test-image.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-metal-e2e.yaml
Labels: approved, lgtm, size/L

#5845 Fix jobs for ci-secret-mirroring-controller
  ci-operator/jobs/openshift/ci-secret-mirroring-controller/openshift-ci-secret-mirroring-controller-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#5841 Revert "Specify cluster to promote secret-mirroring image"
  ci-operator/config/openshift/ci-secret-mirroring-controller/openshift-ci-secret-mirroring-controller-master.yaml
Labels: approved, lgtm, size/XS

#5850 Remove 4.1 config from nightly and 0.10 build targets
  ci-operator/config/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-next.yaml
  ci-operator/config/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-next__variant.yaml
  ci-operator/config/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-v0.10.0.yaml
  ci-operator/config/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-v0.10.0__variant.yaml
  ci-operator/jobs/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-next-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-next-presubmits.yaml
  ci-operator/jobs/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-v0.10.0-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-v0.10.0-presubmits.yaml
Labels: approved, lgtm, size/XL

#5725 openshift/sdn: build new consolidated image
  ci-operator/config/openshift/sdn/openshift-sdn-master.yaml
  ci-operator/config/openshift/sdn/openshift-sdn-release-4.3.yaml
  ci-operator/config/openshift/sdn/openshift-sdn-release-4.4.yaml
Labels: approved, lgtm, size/S

#5852 Revert build_root changes
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-master.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.3.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.4.yaml
Labels: approved, lgtm

#5854 Enable lgtm as approval on 2 ci repos
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/XS

#5849 Use ci-operator to build ci-ns-ttl-controller
  ci-operator/config/openshift/ci-ns-ttl-controller/OWNERS
  ci-operator/config/openshift/ci-ns-ttl-controller/openshift-ci-ns-ttl-controller-master.yaml
  ci-operator/jobs/openshift/ci-ns-ttl-controller/openshift-ci-ns-ttl-controller-master-postsubmits.yaml
  ci-operator/jobs/openshift/ci-ns-ttl-controller/openshift-ci-ns-ttl-controller-master-presubmits.yaml
  clusters/build-clusters/01_cluster/openshift/ci-ns-ttl-controller/admin_ci-ns-ttl-controller_rbac.yaml
  clusters/build-clusters/01_cluster/openshift/ci-ns-ttl-controller/ci-ns-ttl-controller_dc.yaml
  clusters/build-clusters/01_cluster/openshift/ci-ns-ttl-controller/ci-ns-ttl-controller_imagestream.yaml
  clusters/build-clusters/01_cluster/prow/03_deployment/admin_config_updater_rbac.yaml
  core-services/ci-ns-ttl-controller/OWNERS
  core-services/ci-ns-ttl-controller/README.md
  core-services/ci-ns-ttl-controller/admin_ci-ns-ttl-controller_rbac.yaml
  core-services/ci-ns-ttl-controller/ci-ns-ttl-controller_dc.yaml
Labels: approved, lgtm, size/L

#5842 Create image to run wsu tests with
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-master.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.3.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.4.yaml
  ci-operator/jobs/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.3-postsubmits.yaml
  ci-operator/jobs/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.4-postsubmits.yaml
  ci-operator/jobs/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.4-presubmits.yaml
Labels: approved, lgtm, size/L

#5859 boskos: introduce oVirt provider to boskos configuration
  core-services/prow/02_config/_boskos.yaml
Labels: approved, lgtm, size/XS

#5860 Adding secrets mirroring for CCX
  core-services/secret-mirroring/_mapping.yaml
Labels: approved, lgtm, size/S

#5861 cincinnati: run rustfmt on 1.39
  ci-operator/config/openshift/cincinnati/openshift-cincinnati-master.yaml
  ci-operator/jobs/openshift/cincinnati/openshift-cincinnati-master-presubmits.yaml
Labels: approved, lgtm, size/M

#5862 OKD 4.3 periodics: install glusterfs-fuse
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
Labels: approved, lgtm, size/XS

#5868 Revert "Merge pull request #5856 from openshift-bot/autobump"
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/redhat-cop/org/redhat-cop-org-master-periodics.yaml
  ci-operator/jobs/redhat-cop/org/redhat-cop-org-master-postsubmits.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/03_deployment/adapter_imagestreams.yaml
  core-services/prow/03_deployment/artifact-uploader.yaml
  core-services/prow/03_deployment/cherrypick.yaml
  core-services/prow/03_deployment/deck.yaml
  core-services/prow/03_deployment/exporter.yaml
  core-services/prow/03_deployment/ghproxy.yaml
  core-services/prow/03_deployment/hook.yaml
  core-services/prow/03_deployment/horologium.yaml
  core-services/prow/03_deployment/jenkins_operator.yaml
  core-services/prow/03_deployment/needs_rebase.yaml
  core-services/prow/03_deployment/plank.yaml
  core-services/prow/03_deployment/refresh.yaml
  core-services/prow/03_deployment/sinker.yaml
  core-services/prow/03_deployment/statusreconciler.yaml
  core-services/prow/03_deployment/tide.yaml
  core-services/prow/03_deployment/tot.yaml
  hack/images.sh
Labels: approved, lgtm, size/L

#5870 Fix ghproxy alerts
  cluster/ci/monitoring/mixins/prometheus/ghproxy_alerts.libsonnet
  cluster/ci/monitoring/mixins/prometheus_out/prometheus_rule_prow.yaml
Labels: approved, lgtm, size/XS

#5872 Add RHCOS promotion jobs for 4.4
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
Labels: approved, lgtm, size/L

#5876 Remove duration check from ghproxy status code alerts
  cluster/ci/monitoring/mixins/prometheus/ghproxy_alerts.libsonnet
  cluster/ci/monitoring/mixins/prometheus_out/prometheus_rule_prow.yaml
Labels: approved, lgtm, size/S

#5877 Stop setting unnecessary flags on docker commands
  Makefile
Labels: approved, lgtm, size/XS

#5885 Move 3.11 build to aws
  ci-operator/jobs/openshift/jenkins/openshift-jenkins-openshift-3.11-presubmits.yaml
Labels: approved, lgtm, size/S

#5886 revert jenkins for 3.11 tests to gcp
  ci-operator/jobs/openshift/jenkins/openshift-jenkins-openshift-3.11-presubmits.yaml
Labels: approved, lgtm, size/S

#5685 Initial configuration of (unit) tests for helm release to be added under OpenShift CI
  ci-operator/config/redhat-developer/helm/OWNERS
  ci-operator/config/redhat-developer/helm/redhat-developer-helm-master.yaml
  ci-operator/jobs/redhat-developer/helm/OWNERS
  ci-operator/jobs/redhat-developer/helm/redhat-developer-helm-master-presubmits.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/L

#5866 Publish src image for cluster-api-actuator-pkg
  ci-operator/config/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-master.yaml
Labels: approved, lgtm, size/XS

#5888 Revert "Update prow to v20191113-cce53531b, and other images as necessary."
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/redhat-cop/org/redhat-cop-org-master-periodics.yaml
  ci-operator/jobs/redhat-cop/org/redhat-cop-org-master-postsubmits.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/03_deployment/adapter_imagestreams.yaml
  core-services/prow/03_deployment/artifact-uploader.yaml
  core-services/prow/03_deployment/cherrypick.yaml
  core-services/prow/03_deployment/deck.yaml
  core-services/prow/03_deployment/exporter.yaml
  core-services/prow/03_deployment/ghproxy.yaml
  core-services/prow/03_deployment/hook.yaml
  core-services/prow/03_deployment/horologium.yaml
  core-services/prow/03_deployment/jenkins_operator.yaml
  core-services/prow/03_deployment/needs_rebase.yaml
  core-services/prow/03_deployment/plank.yaml
  core-services/prow/03_deployment/refresh.yaml
  core-services/prow/03_deployment/sinker.yaml
  core-services/prow/03_deployment/statusreconciler.yaml
  core-services/prow/03_deployment/tide.yaml
  core-services/prow/03_deployment/tot.yaml
  hack/images.sh
Labels: approved, lgtm, size/L

#5890 periodics: OKD promotion should guard against missing image streams
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
Labels: approved, lgtm, size/S

#5878 Prepare tests for ARO plugin release-v12 branch
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-release-v12.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v12-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/L

#5833 Add e2e test to integr8ly/cloud-resource-operator
  ci-operator/config/integr8ly/cloud-resource-operator/integr8ly-cloud-resource-operator-master.yaml
  ci-operator/jobs/integr8ly/cloud-resource-operator/integr8ly-cloud-resource-operator-master-presubmits.yaml
Labels: approved, lgtm, size/M

#5879 Add upgrade-v12.0 jobs to openshift-azure master presubmits
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/M

#5897 Improve the GitHub cache alerts
  cluster/ci/monitoring/mixins/grafana_dashboards/ghproxy.jsonnet
  cluster/ci/monitoring/mixins/grafana_dashboards_out/ghproxy.json
  cluster/ci/monitoring/mixins/prometheus/ghproxy_alerts.libsonnet
  cluster/ci/monitoring/mixins/prometheus_out/prometheus_rule_prow.yaml
Labels: approved, lgtm, size/L

#5880 SDCICD-80. Remove 4.1 osde2e jobs, add in initial 4.3 osde2e jobs.
  ci-operator/config/openshift/osde2e/openshift-osde2e-master.yaml
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-master-periodics.yaml
  cluster/ci/monitoring/mixins/grafana_dashboards/osde2e.jsonnet
  cluster/ci/monitoring/mixins/grafana_dashboards_out/osde2e.json
Labels: approved, lgtm, size/XL

#5881 Revert "fast-datapath-beta: disable repos by default"
  core-services/release-controller/_repos/ocp-4.3-default.repo
  core-services/release-controller/_repos/ocp-4.3-ppc64le.repo
  core-services/release-controller/_repos/ocp-4.3-rhel8.repo
  core-services/release-controller/_repos/ocp-4.3-s390x.repo
Labels: approved, lgtm, size/XS

#5900 Fix legend in ghproxy dashboard
  cluster/ci/monitoring/mixins/config.libsonnet
  cluster/ci/monitoring/mixins/grafana_dashboards/ghproxy.jsonnet
  cluster/ci/monitoring/mixins/grafana_dashboards_out/ghproxy.json
  cluster/ci/monitoring/mixins/prometheus/ghproxy_alerts.libsonnet
  cluster/ci/monitoring/mixins/prometheus_out/prometheus_rule_prow.yaml
Labels: approved, lgtm, size/S

#5892 ocs-operator: Make e2e tests required
  ci-operator/jobs/openshift/ocs-operator/openshift-ocs-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/ocs-operator/openshift-ocs-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/ocs-operator/openshift-ocs-operator-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/ocs-operator/openshift-ocs-operator-release-4.4-presubmits.yaml
Labels: approved, lgtm, size/XS

#5905 Fix a typo in a ghproxy alert
  cluster/ci/monitoring/mixins/prometheus/ghproxy_alerts.libsonnet
  cluster/ci/monitoring/mixins/prometheus_out/prometheus_rule_prow.yaml
Labels: approved, lgtm, size/XS

#5901 Adding the overrideCLIImage flag to specify the correct cli image to the release-controller
  core-services/release-controller/_releases/release-ocp-4.2-s390x.json
  core-services/release-controller/_releases/release-ocp-4.3-ppc64le.json
  core-services/release-controller/_releases/release-ocp-4.3-s390x.json
  core-services/release-controller/_releases/release-ocp-4.4-ppc64le.json
  core-services/release-controller/_releases/release-ocp-4.4-s390x.json
Labels: approved, lgtm, size/XS

#5906 Use function humanize in ghproxy alerts
  cluster/ci/monitoring/mixins/prometheus/ghproxy_alerts.libsonnet
  cluster/ci/monitoring/mixins/prometheus_out/prometheus_rule_prow.yaml
Labels: approved, lgtm, size/S

#5911 Add ciaranRoche to integr8ly/cloud-resource-operator OWNERS
  ci-operator/config/integr8ly/cloud-resource-operator/OWNERS
Labels: approved, lgtm, size/XS

#5912 Bump PRs selected for retest from 1 to 5
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm, size/XS

#5864 Add CI runs every six hours and clean up naming conventions.
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-next__4.2.yaml
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-v0.8.1__4.1.yaml
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-v0.8.1__4.2.yaml
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-v0.8.1__vsphere.yaml
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-v0.9.0__4.1.yaml
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-v0.9.0__4.2.yaml
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-v0.9.0__4.3.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-next-postsubmits.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-next-presubmits.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-v0.8.1-periodics.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-v0.8.1-postsubmits.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-v0.8.1-presubmits.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-v0.9.0-periodics.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-v0.9.0-postsubmits.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-v0.9.0-presubmits.yaml
Labels: approved, lgtm, size/XL

#5907 Set accessTokenMaxAgeSeconds on build01
  clusters/build-clusters/01_cluster/assets/admin_cluster_oauth_template.yaml
Labels: approved, lgtm, size/XS

#5658 remove stale codecov info
  Makefile
  core-services/secret-mirroring/_mapping.yaml
  projects/azure/README.md
Labels: approved, lgtm, sig/azure, size/S

#5835 Add fips e2e aws
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
Labels: approved, lgtm, size/L

#5915 Added bamachrn to owners list for helm
  ci-operator/config/redhat-developer/helm/OWNERS
  ci-operator/jobs/redhat-developer/helm/OWNERS
Labels: approved, lgtm, size/XS

#5889 add ci checks for v1 branch of hive
  ci-operator/config/openshift/hive/openshift-hive-v1.yaml
  ci-operator/jobs/openshift/hive/openshift-hive-v1-postsubmits.yaml
  ci-operator/jobs/openshift/hive/openshift-hive-v1-presubmits.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/XL

#5902 SDCICD-63. Add in osde2e scale tests.
  ci-operator/config/openshift/osde2e/openshift-osde2e-master.yaml
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-master-periodics.yaml
Labels: approved, lgtm, size/L

#5918 add e2e-gcp to openshift/sdn
  ci-operator/config/openshift/sdn/openshift-sdn-master.yaml
  ci-operator/config/openshift/sdn/openshift-sdn-release-4.3.yaml
  ci-operator/config/openshift/sdn/openshift-sdn-release-4.4.yaml
  ci-operator/jobs/openshift/sdn/openshift-sdn-master-presubmits.yaml
  ci-operator/jobs/openshift/sdn/openshift-sdn-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/sdn/openshift-sdn-release-4.4-presubmits.yaml
Labels: approved, lgtm, size/L

#5916 openstack: Fix bootstrap nova log gathering
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e.yaml
Labels: approved, lgtm, size/S

#5722 Add CNO ovn upgrade jobs
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-master.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.3.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.3-presubmits.yaml
Labels: approved, lgtm, size/L

#5894 OKD 4.3: skip baremetal IPI operators and sig-storage when mirrored to origin
  core-services/release-controller/_releases/release-ocp-4.3-ci.json
  core-services/release-controller/_releases/release-ocp-4.4-ci.json
Labels: approved, lgtm, size/S

#5922 OKD 4.x: don't sync kuryr images to origin
  core-services/release-controller/_releases/release-ocp-4.3-ci.json
  core-services/release-controller/_releases/release-ocp-4.4-ci.json
Labels: approved, lgtm, size/XS

#5923 origin: Prevent excessive rebuilds of OKD
  core-services/release-controller/_releases/release-origin-4.3.json
Labels: approved, lgtm, size/XS

#3887 add long lived cluster management job and e2e test
  Makefile
  ci-operator/jobs/openshift/release/openshift-release-release-4.1-periodics.yaml
  ci-operator/templates/openshift/endurance/endurance-install.yaml
  ci-operator/templates/openshift/endurance/endurance-test.yaml
Labels: approved, lgtm, sig/azure, size/XL
