Repository openshift/release, pull requests merged in 2019-06, with the labels that each got.

#3937 Enable tide/prow plugins on pipelines-catalog repository
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#3926 Fixing knative image mirror jobs
  Makefile
  cluster/ci/jobs/image-mirror.yaml
  cluster/ci/jobs/knative-image-mirror.yaml
Labels: approved, lgtm, size/L

#3909 cluster-monitoring-operator: enable go modules support
  ci-operator/jobs/openshift/cluster-monitoring-operator/openshift-cluster-monitoring-operator-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#3943 cluster/ci/config/secrets: mirror cincinnati-ci
  cluster/ci/config/secret-mirroring/mapping.yaml
Labels: approved, lgtm, size/XS

#3945 [03-06-2019 17:28:30] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
Labels: approved, lgtm, size/L

#3832 Add image builds for Vertical Pod Autoscaler
  ci-operator/config/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-master.yaml
  ci-operator/config/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-release-4.2.yaml
  ci-operator/config/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-release-4.3.yaml
Labels: approved, lgtm, size/S

#3942 cluster-monitoring-operator: enable go 1.12 support
  ci-operator/config/openshift/cluster-monitoring-operator/openshift-cluster-monitoring-operator-master.yaml
  ci-operator/jobs/openshift/cluster-monitoring-operator/openshift-cluster-monitoring-operator-master-presubmits.yaml
Labels: approved, lgtm, size/M

#3940 telemeter: enable go modules support
  ci-operator/jobs/openshift/telemeter/openshift-telemeter-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#3944 Fix a typo in deck dashboard
  cluster/ci/monitoring/deck.json
  cluster/ci/monitoring/mixins/grafana_dashboards/deck.jsonnet
Labels: approved, lgtm, size/M

#3946 dns-operator: upgrade to go 1.12
  ci-operator/config/openshift/cluster-dns-operator/openshift-cluster-dns-operator-master.yaml
  ci-operator/config/openshift/cluster-dns-operator/openshift-cluster-dns-operator-release-4.2.yaml
  ci-operator/config/openshift/cluster-dns-operator/openshift-cluster-dns-operator-release-4.3.yaml
Labels: approved, lgtm, size/XS

#3877 configs/openshift/installer: Add jobs for Azure testing
  Makefile
  ci-operator/SECRETS.md
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
  cluster/ci/config/secret-mirroring/mapping.yaml
  cluster/test-deploy/azure4/.gitignore
  cluster/test-deploy/azure4/.type
  cluster/test-deploy/azure4/secret_example
Labels: approved, lgtm, size/L

#3950 [04-06-2019 14:42:38] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
Labels: approved, lgtm, size/L

#3949 Update deck http metric names
  cluster/ci/monitoring/deck.json
  cluster/ci/monitoring/mixins/grafana_dashboards/deck.jsonnet
Labels: approved, lgtm, size/L

#3952 [04-06-2019 16:35:44] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
Labels: approved, lgtm, size/L

#3951 Deploy support-operator into all CI clusters to report live data
  ci-operator/populate-secrets-from-bitwarden.sh
  ci-operator/templates/openshift/installer/cluster-launch-installer-console.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-metal-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
Labels: approved, lgtm, size/M

#3953 Add others as path in deck panel
  cluster/ci/monitoring/deck.json
  cluster/ci/monitoring/mixins/grafana_dashboards/deck.jsonnet
Labels: approved, lgtm, size/S

#3954 Fix syntax error in cluster-launch-installer-src.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
Labels: approved, lgtm, size/XS

#3955 Restrict deck job for deck panel
  cluster/ci/monitoring/deck.json
  cluster/ci/monitoring/mixins/grafana_dashboards/deck.jsonnet
Labels: approved, lgtm, size/L

#3956 Grant release admins access to the ocp namespace
  cluster/ci/config/roles.yaml
Labels: approved, lgtm, size/S

#3958 Change machine-os-content promotion source from :latest to :4.1
  ci-operator/jobs/openshift/release/openshift-release-release-4.1-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
Labels: approved, lgtm, size/S

#3959 Add openshift/prometheus-client_golang to prow
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#3960 Create Namespace and Service Account for osde2e
  cluster/ci/config/roles.yaml
Labels: approved, lgtm, size/M

#3428 Setup openshift/crd-schema-gen
  ci-operator/config/openshift/crd-schema-gen/OWNERS
  ci-operator/config/openshift/crd-schema-gen/openshift-crd-schema-gen-master.yaml
  ci-operator/jobs/openshift/crd-schema-gen/OWNERS
  ci-operator/jobs/openshift/crd-schema-gen/openshift-crd-schema-gen-master-postsubmits.yaml
  ci-operator/jobs/openshift/crd-schema-gen/openshift-crd-schema-gen-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#3929 MCO: bump golang to 1.12
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-master.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.2.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.3.yaml
Labels: approved, lgtm, size/XS

#3938 move toolchain image mirror in separate file
  Makefile
  ci-operator/populate-secrets-from-bitwarden.sh
  cluster/ci/jobs/image-mirror.yaml
  cluster/ci/jobs/toolchain-image-mirror.yaml
Labels: approved, lgtm, size/L

#3948 enable prow-monitoring deploy in postsubmit updates
  cluster/ci/config/prow/plugins.yaml
  cluster/ci/monitoring/Makefile
Labels: approved, lgtm, size/XS

#3919 DR snapshot restore: assemble etcd connection string on first master
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
Labels: approved, lgtm, size/S

#3947 DR: always set etcd initial cluster connstring in quorum restore test
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
Labels: approved, lgtm, size/S

#3935 cincinnati: add quay secrets
  Makefile
  ci-operator/config/openshift/cincinnati/openshift-cincinnati-master.yaml
  ci-operator/jobs/openshift/cincinnati/openshift-cincinnati-master-presubmits.yaml
  projects/cincinnati/cincinnati.yaml
Labels: approved, lgtm, size/M

#3963 Retire the `test-infra:binaries` image
  ci-operator/README.md
  hack/manual-trigger.sh
  hack/mkpjpod.sh
Labels: approved, lgtm, size/S

#3966 [05-06-2019 20:12:12] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
Labels: approved, lgtm, size/L

#3968 cincinnati: remove `skip_cloning: true` decoration
  ci-operator/jobs/openshift/cincinnati/openshift-cincinnati-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#3969 buildconfig/cincinnati: add github trigger
  projects/cincinnati/cincinnati.yaml
Labels: approved, lgtm, size/XS

#3965 Fix 4.2 machine-os-content to use the 4.2 input
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
Labels: approved, lgtm, size/XS

#3973 Update repos to have bugzilla labels
  cluster/ci/config/prow/labels.yaml
Labels: approved, lgtm, size/S

#3974 Fix namespace for ART role for ocp publishing
  ci-operator/infra/openshift/release-controller/deploy-ocp-publish-art.yaml
Labels: approved, lgtm, size/XS

#3972 Fix a typo in `_rbac` filename
  cluster/ci/monitoring/Makefile
  cluster/ci/monitoring/grafana_rbac.yaml
Labels: approved, lgtm, size/XS

#3975 [05-06-2019 22:11:58] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
Labels: approved, lgtm, size/L

#3970 Turn on Bugzilla verification
  ci-operator/populate-secrets-from-bitwarden.sh
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#3971 Remove some legacy cruft
  cluster/ci/origin/project-viewer.yaml
  hack/apply-jjb-configmaps.sh
Labels: approved, lgtm, size/M

#3976 [05-06-2019 23:57:58] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
Labels: approved, lgtm, size/L

#3977 Remove RBAC of getting ns to access prometheus
  cluster/ci/monitoring/prometheus_crd.yaml
Labels: approved, lgtm, size/XS

#3980 telemeter: cmo: add env USER to workaround problems with downloading libraries
  ci-operator/jobs/openshift/cluster-monitoring-operator/openshift-cluster-monitoring-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/telemeter/openshift-telemeter-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#3979 Fix mirror mount and remove odd images
  cluster/ci/config/mirroring/knative/knative_v0_6_quay
  cluster/ci/jobs/knative-image-mirror.yaml
Labels: approved, lgtm, size/S

#3984 Delete unused DNF repo file
  cluster/ci/config/prow/openshift/rpm-mirrors/docker.repo
Labels: approved, lgtm, size/XS

#3985 Remove old unused Prometheus config
  cluster/ci/config/prometheus-federate/.gitignore
  cluster/ci/config/prometheus-federate/alerting.rules
  cluster/ci/config/prometheus-federate/alertmanager.yml
  cluster/ci/config/prometheus-federate/bin/config.sh
  cluster/ci/config/prometheus-federate/bin/each.sh
  cluster/ci/config/prometheus-federate/prometheus.yml
Labels: approved, lgtm, size/L

#3982 Sync scripts with bump-prow-images.sh
  hack/bump-prow-images.sh
  hack/images.sh
  hack/manual-trigger.sh
  hack/mkpjpod.sh
Labels: approved, lgtm, size/S

#3986 projects/origin-release/golang-1.12: add 'bzr' to preinstalled packages
  projects/origin-release/golang-1.12/Dockerfile
Labels: approved, lgtm, size/XS

#3987 Run kubemark e2e over github.com/openshift/autoscaler@master
  ci-operator/jobs/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-master-presubmits.yaml
Labels: approved, lgtm, size/S

#3988 Add jobs for openshift/csi-external-resizer
  ci-operator/config/openshift/csi-external-resizer/OWNERS
  ci-operator/config/openshift/csi-external-resizer/openshift-csi-external-resizer-master.yaml
  ci-operator/jobs/openshift/csi-external-resizer/OWNERS
  ci-operator/jobs/openshift/csi-external-resizer/openshift-csi-external-resizer-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#3989 Ci job updates for new images in knative master branch
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next.yaml
Labels: approved, lgtm, size/S

#3991 Run the right JJ for kubernetes-autoscaler
  ci-operator/jobs/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#3993 Add cherry-pick-approved label, require it for release branches
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/labels.yaml
Labels: approved, lgtm, size/XS

#3994 cluster/ci/monitoring/mixins/grafana_dashboards/build_cop: Drop e2e from "by platform"
  cluster/ci/monitoring/build_cop.json
  cluster/ci/monitoring/mixins/grafana_dashboards/build_cop.jsonnet
Labels: approved, lgtm, size/M

#3983 Update CSI jobs for 4.2
  ci-operator/config/openshift/csi-cluster-driver-registrar/openshift-csi-cluster-driver-registrar-master.yaml
  ci-operator/config/openshift/csi-cluster-driver-registrar/openshift-csi-cluster-driver-registrar-release-4.2.yaml
  ci-operator/config/openshift/csi-cluster-driver-registrar/openshift-csi-cluster-driver-registrar-release-4.3.yaml
  ci-operator/config/openshift/csi-external-attacher/openshift-csi-external-attacher-master.yaml
  ci-operator/config/openshift/csi-external-attacher/openshift-csi-external-attacher-release-4.2.yaml
  ci-operator/config/openshift/csi-external-attacher/openshift-csi-external-attacher-release-4.3.yaml
  ci-operator/config/openshift/csi-external-provisioner/openshift-csi-external-provisioner-master.yaml
  ci-operator/config/openshift/csi-external-provisioner/openshift-csi-external-provisioner-release-4.2.yaml
  ci-operator/config/openshift/csi-external-provisioner/openshift-csi-external-provisioner-release-4.3.yaml
  ci-operator/config/openshift/csi-external-snapshotter/openshift-csi-external-snapshotter-master.yaml
  ci-operator/config/openshift/csi-external-snapshotter/openshift-csi-external-snapshotter-release-4.2.yaml
  ci-operator/config/openshift/csi-external-snapshotter/openshift-csi-external-snapshotter-release-4.3.yaml
  ci-operator/config/openshift/csi-livenessprobe/openshift-csi-livenessprobe-master.yaml
  ci-operator/config/openshift/csi-livenessprobe/openshift-csi-livenessprobe-release-4.2.yaml
  ci-operator/config/openshift/csi-livenessprobe/openshift-csi-livenessprobe-release-4.3.yaml
  ci-operator/config/openshift/csi-node-driver-registrar/openshift-csi-node-driver-registrar-master.yaml
  ci-operator/config/openshift/csi-node-driver-registrar/openshift-csi-node-driver-registrar-release-4.2.yaml
  ci-operator/config/openshift/csi-node-driver-registrar/openshift-csi-node-driver-registrar-release-4.3.yaml
  ci-operator/jobs/openshift/csi-cluster-driver-registrar/openshift-csi-cluster-driver-registrar-master-postsubmits.yaml
  ci-operator/jobs/openshift/csi-cluster-driver-registrar/openshift-csi-cluster-driver-registrar-master-presubmits.yaml
  ci-operator/jobs/openshift/csi-cluster-driver-registrar/openshift-csi-cluster-driver-registrar-release-4.2-postsubmits.yaml
  ci-operator/jobs/openshift/csi-cluster-driver-registrar/openshift-csi-cluster-driver-registrar-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/csi-cluster-driver-registrar/openshift-csi-cluster-driver-registrar-release-4.3-postsubmits.yaml
  ci-operator/jobs/openshift/csi-cluster-driver-registrar/openshift-csi-cluster-driver-registrar-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/csi-external-snapshotter/openshift-csi-external-snapshotter-master-postsubmits.yaml
  ci-operator/jobs/openshift/csi-external-snapshotter/openshift-csi-external-snapshotter-master-presubmits.yaml
  ci-operator/jobs/openshift/csi-external-snapshotter/openshift-csi-external-snapshotter-release-4.2-postsubmits.yaml
  ci-operator/jobs/openshift/csi-external-snapshotter/openshift-csi-external-snapshotter-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/csi-external-snapshotter/openshift-csi-external-snapshotter-release-4.3-postsubmits.yaml
  ci-operator/jobs/openshift/csi-external-snapshotter/openshift-csi-external-snapshotter-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/csi-node-driver-registrar/openshift-csi-node-driver-registrar-master-postsubmits.yaml
  ci-operator/jobs/openshift/csi-node-driver-registrar/openshift-csi-node-driver-registrar-master-presubmits.yaml
  ci-operator/jobs/openshift/csi-node-driver-registrar/openshift-csi-node-driver-registrar-release-4.2-postsubmits.yaml
  ci-operator/jobs/openshift/csi-node-driver-registrar/openshift-csi-node-driver-registrar-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/csi-node-driver-registrar/openshift-csi-node-driver-registrar-release-4.3-postsubmits.yaml
  ci-operator/jobs/openshift/csi-node-driver-registrar/openshift-csi-node-driver-registrar-release-4.3-presubmits.yaml
Labels: approved, lgtm, size/XL

#3996 cincinnati/OWNERS: add shiywang
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#3997 ci-operator: use new make target
  ci-operator/config/openshift/ci-operator/openshift-ci-operator-master.yaml
Labels: approved, lgtm, size/XS

#3995 Configure tide for new CSI repos
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/XS

#3990 Adding the entire openshift-knative eventing team...
  OWNERS_ALIASES
Labels: approved, lgtm, size/S

#3957 baremetal-operator: Reflect metal3-io org rename.
  ci-operator/config/openshift/baremetal-operator/openshift-baremetal-operator-master.yaml
  ci-operator/config/openshift/baremetal-operator/openshift-baremetal-operator-release-4.2.yaml
  ci-operator/config/openshift/baremetal-operator/openshift-baremetal-operator-release-4.3.yaml
Labels: approved, lgtm, size/XS

#4001 projects/cincinnati: change dockerfilePath
  projects/cincinnati/cincinnati.yaml
Labels: approved, lgtm, size/XS, ¯\_(ツ)_/¯

#3999 changing timeout for the change log level test
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-periodics.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v5-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/XS

#3992 ci: Stop building metering-helm-operator
  ci-operator/config/operator-framework/operator-metering/operator-framework-operator-metering-master.yaml
Labels: approved, lgtm, size/XS

#3978 configure local storage static provisioner
  ci-operator/config/openshift/sig-storage-local-static-provisioner/OWNERS
  ci-operator/config/openshift/sig-storage-local-static-provisioner/openshift-sig-storage-local-static-provisioner-master.yaml
  ci-operator/config/openshift/sig-storage-local-static-provisioner/openshift-sig-storage-local-static-provisioner-release-4.2.yaml
  ci-operator/config/openshift/sig-storage-local-static-provisioner/openshift-sig-storage-local-static-provisioner-release-4.3.yaml
  ci-operator/jobs/openshift/sig-storage-local-static-provisioner/OWNERS
  ci-operator/jobs/openshift/sig-storage-local-static-provisioner/openshift-sig-storage-local-static-provisioner-master-postsubmits.yaml
  ci-operator/jobs/openshift/sig-storage-local-static-provisioner/openshift-sig-storage-local-static-provisioner-master-presubmits.yaml
  ci-operator/jobs/openshift/sig-storage-local-static-provisioner/openshift-sig-storage-local-static-provisioner-release-4.2-postsubmits.yaml
  ci-operator/jobs/openshift/sig-storage-local-static-provisioner/openshift-sig-storage-local-static-provisioner-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/sig-storage-local-static-provisioner/openshift-sig-storage-local-static-provisioner-release-4.3-postsubmits.yaml
  ci-operator/jobs/openshift/sig-storage-local-static-provisioner/openshift-sig-storage-local-static-provisioner-release-4.3-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XL

#4005 Add s2i to ci-operator
  ci-operator/config/openshift/source-to-image/OWNERS
  ci-operator/config/openshift/source-to-image/openshift-source-to-image-master.yaml
  ci-operator/jobs/openshift/source-to-image/OWNERS
  ci-operator/jobs/openshift/source-to-image/openshift-source-to-image-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#4008 [07-06-2019 20:51:33] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  hack/images.sh
Labels: approved, lgtm, size/L

#4010 [08-06-2019 01:31:43] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  hack/images.sh
Labels: approved, lgtm, size/L

#4012 [08-06-2019 01:59:12] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  hack/images.sh
Labels: approved, lgtm, size/L

#4011 Rename deck HTTP metrics to have the deck prefix
  cluster/ci/monitoring/deck.json
  cluster/ci/monitoring/mixins/grafana_dashboards/deck.jsonnet
Labels: approved, lgtm, size/M

#4007 allow ci-operator SA to create+edit secrets in the ci namespace
  cluster/ci/config/prow/openshift/ci-operator/roles.yaml
Labels: approved, lgtm, size/M

#3941 add priority class to prow components
  Makefile
  cluster/ci/config/prow/openshift/config_updater_rbac.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/prow-priority-class.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
Labels: approved, lgtm, size/M

#4016 fix priority class name prefix
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/prow-priority-class.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
Labels: approved, lgtm, size/S

#4017 fix prow priority class value
  cluster/ci/config/prow/openshift/prow-priority-class.yaml
Labels: approved, lgtm, size/XS

#4018 [10-06-2019 16:08:18] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  hack/images.sh
Labels: approved, lgtm, size/L

#4019 Turn on retitle plugin
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#4004 build hivebase and use it for final hive image
  ci-operator/config/openshift/hive/openshift-hive-master.yaml
Labels: approved, lgtm, size/S

#4021 [10-06-2019 17:32:35] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  hack/images.sh
Labels: approved, lgtm, size/L

#4022 Update metrics name in deck board
  cluster/ci/monitoring/deck.json
  cluster/ci/monitoring/mixins/grafana_dashboards/deck.jsonnet
Labels: approved, lgtm, size/L

#4024 create initial empty secret for longlived aws cluster creds
  cluster/ci/config/prow/openshift/ci-operator/roles.yaml
Labels: approved, lgtm, size/S

#4013 ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e: WorkerSubnet -> Subnet
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
Labels: approved, lgtm, size/XS

#4029 Remove populate-templates.sh
  ci-operator/populate-templates.sh
Labels: approved, lgtm, size/S

#4027 ci-operator/templates/openshift: m4.xlarge compute nodes
  ci-operator/templates/openshift/installer/cluster-launch-installer-console.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-scaleup-e2e-40.yaml
Labels: approved, lgtm, size/XS

#4032 DR: don't run quorum loss test for all MCO PRs
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#4014 DR: add quorum loss tests to MCO 4.x branches
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.1.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.2.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.3.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.3-presubmits.yaml
Labels: approved, lgtm, size/L

#4009 templates/openshift/installer: update setup for installer to gather logs on bootstrap failure
  ci-operator/templates/openshift/installer/cluster-launch-installer-console.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
Labels: approved, lgtm, size/S

#3939 add CPU/Memory/Storage metrics in prow dashboard
  cluster/ci/config/prow/openshift/config_updater_rbac.yaml
  cluster/ci/monitoring/Makefile
  cluster/ci/monitoring/datasources.yaml
  cluster/ci/monitoring/mixins/grafana_dashboards/prow.jsonnet
  cluster/ci/monitoring/prow.json
Labels: approved, lgtm, size/XL

#4039 add openshift-monitoring configuration
  cluster/ci/openshift-monitoring/Makefile
  cluster/ci/openshift-monitoring/prometheus-k8s-rules_prometheusrule.yaml
Labels: approved, lgtm, size/XXL

#4040 fix prometheus rules
  cluster/ci/openshift-monitoring/prometheus-k8s-rules_prometheusrule.yaml
Labels: approved, lgtm, size/XS

#4033 Update image registry operator to use go 1.12
  ci-operator/config/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-master.yaml
  ci-operator/config/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-release-4.2.yaml
  ci-operator/config/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-release-4.3.yaml
Labels: approved, lgtm, size/XS

#4041 Allow setting platform/libvirt via command
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#4043 remove default prometheus rules, add only prow's
  cluster/ci/openshift-monitoring/Makefile
  cluster/ci/openshift-monitoring/prometheus-k8s-rules_prometheusrule.yaml
  cluster/ci/openshift-monitoring/prometheus-prow-rules_prometheusrule.yaml
Labels: approved, lgtm, size/XXL

#4023 Run Jenkins s2i tests on every PR
  ci-operator/jobs/openshift/source-to-image/openshift-source-to-image-master-presubmits.yaml
Labels: approved, lgtm, size/S

#4038 Remove dep check for 4.1 branch
  ci-operator/config/openshift/cluster-kube-scheduler-operator/openshift-cluster-kube-scheduler-operator-release-4.1.yaml
Labels: approved, lgtm, size/XS

#4044 add v4 branch to plugin
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#4042 bumps golang version to 1.12 for master team's components
  ci-operator/config/openshift/cluster-kube-apiserver-operator/openshift-cluster-kube-apiserver-operator-master.yaml
  ci-operator/config/openshift/cluster-kube-controller-manager-operator/openshift-cluster-kube-controller-manager-operator-master.yaml
  ci-operator/config/openshift/cluster-kube-scheduler-operator/openshift-cluster-kube-scheduler-operator-master.yaml
  ci-operator/config/openshift/cluster-openshift-apiserver-operator/openshift-cluster-openshift-apiserver-operator-master.yaml
  ci-operator/config/openshift/cluster-openshift-controller-manager-operator/openshift-cluster-openshift-controller-manager-operator-master.yaml
  ci-operator/config/openshift/library-go/openshift-library-go-master.yaml
Labels: approved, lgtm, size/S

#4045 Remove unused Makefile target `test-bases`
  Makefile
Labels: approved, lgtm, size/XS

#4046 Revert "add v4 branch to plugin"
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#4048 add aro v4 dev branch
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#4050 machine-api-operator: add optional Azure CI job
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-master.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-master-presubmits.yaml
Labels: approved, lgtm, size/M

#3711 create origin-kube-proxy image
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.1.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.2.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.3.yaml
  cluster/ci/config/mirroring/origin_4_1
Labels: approved, lgtm, size/M, ¯\_(ツ)_/¯

#4037 Add configuration for openshift/ci-tools
  README.md
  ci-operator/README.md
  ci-operator/config/openshift/ci-tools/OWNERS
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
  ci-operator/jobs/openshift/ci-tools/OWNERS
  ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
  ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
  projects/azure/README.md
Labels: approved, lgtm, size/L

#4053 knative-eventing ci-updates with new images
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next.yaml
Labels: approved, lgtm, size/L

#4052 Remove ci-operator, ci-operator-prowgen
  ci-operator/config/openshift/ci-operator-prowgen/OWNERS
  ci-operator/config/openshift/ci-operator-prowgen/openshift-ci-operator-prowgen-master.yaml
  ci-operator/config/openshift/ci-operator/OWNERS
  ci-operator/config/openshift/ci-operator/openshift-ci-operator-master.yaml
  ci-operator/jobs/openshift/ci-operator-prowgen/OWNERS
  ci-operator/jobs/openshift/ci-operator-prowgen/openshift-ci-operator-prowgen-master-postsubmits.yaml
  ci-operator/jobs/openshift/ci-operator-prowgen/openshift-ci-operator-prowgen-master-presubmits.yaml
  ci-operator/jobs/openshift/ci-operator/OWNERS
  ci-operator/jobs/openshift/ci-operator/openshift-ci-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/ci-operator/openshift-ci-operator-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XL

#4054 Add glide
  projects/origin-release/golang-1.12/Dockerfile
Labels: approved, lgtm, size/XS

#4057 [13-06-2019 20:56:34] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  hack/images.sh
Labels: approved, lgtm, size/L

#4058 Accept any XML anywhere for jUnit in Spyglass
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/XS

#4059 Revert "Merge pull request #3708 from petr-muller/revert-spyglass"
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/XS

#4034 onboard member-operator to use openshift-ci
  ci-operator/config/codeready-toolchain/member-operator/OWNERS
  ci-operator/config/codeready-toolchain/member-operator/codeready-toolchain-member-operator-master.yaml
  ci-operator/jobs/codeready-toolchain/member-operator/OWNERS
  ci-operator/jobs/codeready-toolchain/member-operator/codeready-toolchain-member-operator-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#4051 onboard codeready-toolchain/api to use Openshift CI
  ci-operator/config/codeready-toolchain/api/OWNERS
  ci-operator/config/codeready-toolchain/api/codeready-toolchain-api-master.yaml
  ci-operator/jobs/codeready-toolchain/api/OWNERS
  ci-operator/jobs/codeready-toolchain/api/codeready-toolchain-api-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#4049 bumps golang version to 1.12 for auth components
  ci-operator/config/openshift/cluster-authentication-operator/openshift-cluster-authentication-operator-master.yaml
  ci-operator/config/openshift/cluster-config-operator/openshift-cluster-config-operator-master.yaml
  ci-operator/config/openshift/cluster-machine-approver/openshift-cluster-machine-approver-master.yaml
  ci-operator/config/openshift/kube-rbac-proxy/openshift-kube-rbac-proxy-master.yaml
  ci-operator/config/openshift/oauth-proxy/openshift-oauth-proxy-master.yaml
  ci-operator/config/openshift/service-ca-operator/openshift-service-ca-operator-master.yaml
Labels: approved, lgtm, size/S

#4025 onboard host-operator to use openshift-ci
  ci-operator/config/codeready-toolchain/host-operator/OWNERS
  ci-operator/config/codeready-toolchain/host-operator/codeready-toolchain-host-operator-master.yaml
  ci-operator/jobs/codeready-toolchain/host-operator/OWNERS
  ci-operator/jobs/codeready-toolchain/host-operator/codeready-toolchain-host-operator-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#4060 Remove actuator-pkg-staleness job for aws, mao and cao
  ci-operator/config/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-master.yaml
  ci-operator/config/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-release-4.1.yaml
  ci-operator/config/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-release-4.2.yaml
  ci-operator/config/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-release-4.3.yaml
  ci-operator/config/openshift/cluster-autoscaler-operator/openshift-cluster-autoscaler-operator-master.yaml
  ci-operator/config/openshift/cluster-autoscaler-operator/openshift-cluster-autoscaler-operator-release-4.1.yaml
  ci-operator/config/openshift/cluster-autoscaler-operator/openshift-cluster-autoscaler-operator-release-4.2.yaml
  ci-operator/config/openshift/cluster-autoscaler-operator/openshift-cluster-autoscaler-operator-release-4.3.yaml
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-master.yaml
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-release-4.1.yaml
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-release-4.2.yaml
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-release-4.3.yaml
  ci-operator/jobs/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/cluster-autoscaler-operator/openshift-cluster-autoscaler-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-autoscaler-operator/openshift-cluster-autoscaler-operator-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/cluster-autoscaler-operator/openshift-cluster-autoscaler-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/cluster-autoscaler-operator/openshift-cluster-autoscaler-operator-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-release-4.3-presubmits.yaml
Labels: approved, lgtm, size/XL

#4062 remove unneeded promotion step for 3.11 jenkins image
  ci-operator/config/openshift/jenkins/openshift-jenkins-openshift-3.11.yaml
  ci-operator/jobs/openshift/jenkins/openshift-jenkins-openshift-3.11-postsubmits.yaml
Labels: approved, lgtm, size/M

#4063 Search config must be updated for 4.1 and 4.2
  ci-operator/infra/openshift/ci-search/config.yaml
Labels: approved, lgtm, size/M

#4067 Allow ci/hook to update configmaps in ci-search
  ci-operator/infra/openshift/ci-search/deploy.yaml
Labels: approved, lgtm, size/S

#4035 add gates to ARO v4 branch
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-openshift-v4.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-openshift-v4-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-openshift-v4-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/L

#4070 ci-stg: mirror sentry-dsn
  cluster/ci/config/secret-mirroring/mapping.yaml
Labels: approved, lgtm, size/XS

#4056 Making asb based on ubi image and container first
  ci-operator/config/openshift/ansible-service-broker/openshift-ansible-service-broker-master.yaml
Labels: approved, lgtm, size/S

#4068 Knative eventing contrib update
  ci-operator/config/openshift/knative-eventing-contrib/OWNERS
  ci-operator/config/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-next.yaml
  ci-operator/jobs/openshift/knative-eventing-contrib/OWNERS
  ci-operator/jobs/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-next-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-next-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/M

#4071 Enable auth.anonymous on grafana staging
  cluster/ci/monitoring/Makefile
  cluster/ci/monitoring/debug/grafana.ini
  cluster/ci/monitoring/debug/grafana_deploy.yaml
  cluster/ci/monitoring/debug/grafana_secret.yaml
Labels: approved, lgtm, size/S

#4073 Add openshift/kubefed-operator to plugins.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#4074 Enable tide on the kubefed-operator repository.
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/XS

#4064 origin/kube-proxy: correct base
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.1.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.2.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.3.yaml
Labels: approved, lgtm, size/XS

#4075 [17-06-2019 21:42:46] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  hack/images.sh
Labels: approved, lgtm, size/L

#4077 [18-06-2019 00:17:46] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  hack/images.sh
Labels: approved, lgtm, size/L

#4072 Update openshift/tektoncd-pipeline-operator config
  ci-operator/config/openshift/tektoncd-pipeline-operator/openshift-tektoncd-pipeline-operator-master.yaml
Labels: approved, lgtm, size/S

#3961 Request to add monstorak-operator into Openshift-CI framework
  ci-operator/config/monstorak/monstorak-operator/OWNERS
  ci-operator/config/monstorak/monstorak-operator/monstorak-monstorak-operator-master.yaml
  ci-operator/jobs/monstorak/monstorak-operator/OWNERS
  ci-operator/jobs/monstorak/monstorak-operator/monstorak-monstorak-operator-master-postsubmits.yaml
  ci-operator/jobs/monstorak/monstorak-operator/monstorak-monstorak-operator-master-presubmits.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, ok-to-test, size/L

#4026 On board openshift/knative-client to use OpenShift CI
  OWNERS_ALIASES
  ci-operator/config/openshift/knative-client/OWNERS
  ci-operator/config/openshift/knative-client/openshift-knative-client-release-next.yaml
  ci-operator/config/openshift/knative-client/openshift-knative-client-release-v0.1.0.yaml
  ci-operator/jobs/openshift/knative-client/OWNERS
  ci-operator/jobs/openshift/knative-client/openshift-knative-client-release-next-presubmits.yaml
  ci-operator/jobs/openshift/knative-client/openshift-knative-client-release-v0.1.0-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, ok-to-test, size/L

#4078 add ARO create job
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-openshift-v4-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/S

#4079 reorder
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-openshift-v4-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/M

#4084 [18-06-2019 14:40:20] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  hack/images.sh
Labels: approved, lgtm, size/L

#4082 Add cri-o job and config to config-updater
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#4083 DPTP-360: Config cleanup kick-off
  Makefile
  README.md
  core-services/Makefile
  core-services/README.md
  core-services/_TEMPLATE/Makefile
  core-services/_TEMPLATE/OWNERS
  core-services/_TEMPLATE/README.md
  core-services/_TEMPLATE/resource.yaml
  core-services/_hack/validate-core-service.sh
Labels: approved, lgtm, size/L

#3962 Add ci-operator config and job for cri-o
  ci-operator/config/cri-o/cri-o/OWNERS
  ci-operator/config/cri-o/cri-o/cri-o-cri-o-release-1.13.yaml
  ci-operator/jobs/cri-o/cri-o/cri-o-cri-o-release-1.13-presubmits.yaml
Labels: approved, lgtm, size/L

#3653 Add folder tekton for automated mirror jobs
  Makefile
  cluster/ci/config/mirroring/tekton/OWNERS
  cluster/ci/config/mirroring/tekton/tekton_v0_3_quay
  cluster/ci/config/mirroring/tekton/tekton_v0_4_quay
  cluster/ci/jobs/tekton-image-mirror.yaml
Labels: approved, lgtm, size/L

#4036 golang-1.12: set USER env variable to prevent bzr errors
  projects/origin-release/golang-1.12/Dockerfile
Labels: approved, lgtm, size/XS

#4088 cluster-api-provider-azure: add optional Azure CI job
  ci-operator/config/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-master.yaml
  ci-operator/jobs/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-master-presubmits.yaml
Labels: approved, lgtm, size/M

#4047 Add e2e libvirt to cluster-api-provider-libvirt
  ci-operator/jobs/openshift/cluster-api-provider-libvirt/openshift-cluster-api-provider-libvirt-master-presubmits.yaml
Labels: approved, lgtm, size/M

#4091 Add imagedigestexporter image to the tektoncd/pipeline image mirror
  cluster/ci/config/mirroring/tekton/tekton_v0_4_quay
Labels: approved, lgtm, size/XS

#4090 merge method set to 'squash' on the codeready-toolchain repos
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/XS

#4092 [18-06-2019 17:23:25] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  hack/images.sh
Labels: approved, lgtm, size/L

#4093 Run e2e-aws-builds on origin staging directories
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.3-presubmits.yaml
Labels: approved, lgtm, size/XS

#4094 Enable tide configuration for kubefed repository.
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#4097 [18-06-2019 23:40:24] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  hack/images.sh
Labels: approved, lgtm, size/L

#4096 update the build-cop dashboard to reflect our new monitored jobs+targets
  cluster/ci/monitoring/build_cop.json
  cluster/ci/monitoring/mixins/grafana_dashboards/build_cop.jsonnet
Labels: approved, lgtm, size/M

#4100 ARO - add 5.2 release
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v5-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/M

#4086 DPTP-360: Prow jobs for new config structure
  ci-operator/config/openshift/release/OWNERS
  ci-operator/config/openshift/release/openshift-release-master.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
Labels: approved, lgtm, size/L

#4103 Fix legend format on build-cop board
  cluster/ci/monitoring/build_cop.json
  cluster/ci/monitoring/mixins/grafana_dashboards/build_cop.jsonnet
Labels: approved, lgtm, size/S

#4080 Sync CSI images to quay.io
  cluster/ci/config/mirroring/origin_4_2
Labels: approved, lgtm, size/XS

#4105 Break `job-config-master` CM into two smaller
  ci-operator/jobs/infra-periodics.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L
