Repository openshift/release, pull requests merged in 2019-09, with the labels that each got.

#4906 Promote oc rpms as oc-rpms for consumption in origin artifacts
  ci-operator/config/openshift/oc/openshift-oc-master.yaml
  ci-operator/jobs/openshift/oc/openshift-oc-master-postsubmits.yaml
Labels: approved, lgtm, size/XS

#4908 Fix oc-rpms image
  ci-operator/config/openshift/oc/openshift-oc-master.yaml
  ci-operator/jobs/openshift/oc/openshift-oc-master-postsubmits.yaml
Labels: approved, lgtm, size/XS

#4838 Add more checks on populate-secrets-from-bitwarden.sh
  ci-operator/populate-secrets-from-bitwarden.sh
Labels: approved, lgtm, size/S

#4912 cincinnati: +trking +vrutkovs -shiywang
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#4911 Enable the sinker alerts
  cluster/ci/monitoring/mixins/prometheus/configmap_alerts.libsonnet
  cluster/ci/monitoring/mixins/prometheus/prometheus.libsonnet
  cluster/ci/monitoring/mixins/prometheus/sinker_alerts.libsonnet
  cluster/ci/monitoring/mixins/prometheus_out/prometheus_rule_prow.yaml
Labels: approved, lgtm, size/M

#4913 ocs-operator: Fix verify-latest-csv
  ci-operator/config/openshift/ocs-operator/openshift-ocs-operator-master.yaml
Labels: approved, lgtm, size/XS

#4916 Increase from 2 to 4 due to still hitting timeouts
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next__variant.yaml
Labels: approved, lgtm, size/XS

#4904 Upload configs having version info
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#4909 Switch base image to fedora:30
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.2.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.3.yaml
Labels: approved, lgtm, size/S

#4919 Revert "Switch base image to fedora:30"
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.2.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.3.yaml
Labels: approved, lgtm, size/S

#4923 Run k8s e2e only over machine-api-operator master branch
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#4776 add e2e-cmd jobs to oc, openshift-apiserver repositories
  ci-operator/config/openshift/oc/openshift-oc-master.yaml
  ci-operator/config/openshift/oc/openshift-oc-release-4.2.yaml
  ci-operator/config/openshift/openshift-apiserver/openshift-openshift-apiserver-master.yaml
  ci-operator/config/openshift/openshift-apiserver/openshift-openshift-apiserver-release-4.2.yaml
  ci-operator/jobs/openshift/oc/openshift-oc-master-presubmits.yaml
  ci-operator/jobs/openshift/oc/openshift-oc-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/openshift-apiserver/openshift-openshift-apiserver-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-apiserver/openshift-openshift-apiserver-release-4.2-presubmits.yaml
Labels: approved, lgtm, size/L

#4921 Add launch jobs for azure, gcp, and vsphere
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
Labels: approved, lgtm, size/L

#4926 [ocp-release-operator-sdk] Ensure that the sanity check makes use of the vendored dependency
  ci-operator/config/openshift/ocp-release-operator-sdk/openshift-ocp-release-operator-sdk-master.yaml
Labels: approved, lgtm, size/S

#4918 Add RHEL7 scaleup canary release informer
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
Labels: approved, lgtm, size/M

#4927 [4.1.z] image-registry: Remove GCP and Azure tests
  ci-operator/config/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-release-4.1.yaml
  ci-operator/jobs/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-release-4.1-presubmits.yaml
Labels: approved, lgtm, size/L

#4928 updating uname and pw to match proxy
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
Labels: approved, lgtm, size/XS

#4929 Remove v6 from repository
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-release-v6.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v6-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v7-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/L

#4932 Increase rhel scaleup periodic interval
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
Labels: approved, lgtm, size/XS

#4935 Fix ocp-aws-serial-4.2 to run the correct tests
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
Labels: approved, lgtm, size/S

#4857 Replace gofmt with goimports
  ci-operator/config/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-master.yaml
  ci-operator/config/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-release-4.2.yaml
  ci-operator/config/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-release-4.3.yaml
  ci-operator/config/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-master.yaml
  ci-operator/config/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-release-4.2.yaml
  ci-operator/config/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-release-4.3.yaml
  ci-operator/config/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-master.yaml
  ci-operator/config/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-release-4.2.yaml
  ci-operator/config/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-release-4.3.yaml
  ci-operator/config/openshift/cluster-api-provider-gcp/openshift-cluster-api-provider-gcp-master.yaml
  ci-operator/config/openshift/cluster-api-provider-gcp/openshift-cluster-api-provider-gcp-release-4.2.yaml
  ci-operator/config/openshift/cluster-api-provider-gcp/openshift-cluster-api-provider-gcp-release-4.3.yaml
  ci-operator/config/openshift/cluster-api/openshift-cluster-api-openshift-4.2.yaml
  ci-operator/config/openshift/cluster-autoscaler-operator/openshift-cluster-autoscaler-operator-master.yaml
  ci-operator/config/openshift/cluster-autoscaler-operator/openshift-cluster-autoscaler-operator-release-4.2.yaml
  ci-operator/config/openshift/cluster-autoscaler-operator/openshift-cluster-autoscaler-operator-release-4.3.yaml
  ci-operator/config/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-master.yaml
  ci-operator/config/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-release-4.2.yaml
  ci-operator/config/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-release-4.3.yaml
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-master.yaml
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-release-4.2.yaml
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-release-4.3.yaml
  ci-operator/jobs/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-gcp/openshift-cluster-api-provider-gcp-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-gcp/openshift-cluster-api-provider-gcp-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-gcp/openshift-cluster-api-provider-gcp-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api/openshift-cluster-api-openshift-4.2-presubmits.yaml
  ci-operator/jobs/openshift/cluster-autoscaler-operator/openshift-cluster-autoscaler-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-autoscaler-operator/openshift-cluster-autoscaler-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/cluster-autoscaler-operator/openshift-cluster-autoscaler-operator-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-master-presubmits.yaml
  ci-operator/jobs/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-release-4.3-presubmits.yaml
Labels: approved, lgtm, size/L

#4937 OWNERS: add AlexNPavel
  OWNERS
Labels: approved, lgtm, size/XS

#4924 openstack: add 4.2 serial canary job
  ci-operator/infra/openshift/release-controller/releases/release-ocp-4.2.json
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
Labels: approved, lgtm, size/M

#4871 Remove jenkins tox test from OpenShift-Ansible release-3.10 presubmits.
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-3.10-presubmits.yaml
Labels: approved, lgtm, size/S

#4930 Prow config for windows-machine-config-operator
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#4942 Reduce FIPS release jobs to AWS only for now
  ci-operator/infra/openshift/release-controller/releases/release-ocp-4.2.json
Labels: approved, lgtm, size/XS

#4914 Sync branched configs
  ci-operator/config/openshift/cluster-authentication-operator/openshift-cluster-authentication-operator-master.yaml
  ci-operator/config/openshift/cluster-authentication-operator/openshift-cluster-authentication-operator-release-4.2.yaml
  ci-operator/config/openshift/cluster-authentication-operator/openshift-cluster-authentication-operator-release-4.3.yaml
  ci-operator/config/openshift/oc/openshift-oc-master.yaml
  ci-operator/config/openshift/oc/openshift-oc-release-4.2.yaml
  ci-operator/config/openshift/oc/openshift-oc-release-4.3.yaml
  ci-operator/jobs/openshift/oc/openshift-oc-release-4.2-postsubmits.yaml
  ci-operator/jobs/openshift/oc/openshift-oc-release-4.3-postsubmits.yaml
Labels: approved, lgtm, size/M

#4925 Allow retitling closed/merged PRs and issues
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#4931 ocs operator e2e CI job
  ci-operator/config/openshift/ocs-operator/openshift-ocs-operator-master.yaml
  ci-operator/jobs/openshift/ocs-operator/openshift-ocs-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/ocs-operator/openshift-ocs-operator-master-presubmits.yaml
Labels: approved, lgtm, size/L

#4943 Add approvals to openshift/community
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/S

#4439 Adding build support for archs other than amd64
  projects/origin-release/golang-1.10/Dockerfile
  projects/origin-release/golang-1.11/Dockerfile
  projects/origin-release/golang-1.12/Dockerfile
  projects/origin-release/golang-1.8/Dockerfile
  projects/origin-release/golang-1.9/Dockerfile
Labels: approved, lgtm, ok-to-test, size/S

#4944 Add repository for stale issue labeling for openshift-azure
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm, sig/azure, size/XS

#4915 Add job periodic-prow-image-autobump
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm, size/M

#4948 Fix params in autobumper job
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm, size/XS

#4950 Remove RESOURCES_TEST variable from templates. update origin's config
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-periodics.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-console.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-custom-test-image.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
Labels: approved, lgtm, size/M

#4945 Adding enhancements to prow config
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#4951 Just make verify is sufficient
  ci-operator/config/openshift/cluster-kube-scheduler-operator/openshift-cluster-kube-scheduler-operator-master.yaml
Labels: approved, lgtm, size/XS

#4953 (codeready-toolchain): run api tests with coverage
  ci-operator/config/codeready-toolchain/api/codeready-toolchain-api-master.yaml
Labels: approved, lgtm, size/XS

#4878 openstack: Add optional e2e-openstack job to cloud-credential-operator
  ci-operator/jobs/openshift/cloud-credential-operator/openshift-cloud-credential-operator-master-presubmits.yaml
Labels: approved, lgtm, size/M

#4732 openstack: drop invalid bootstrap_ip log code from CI templates
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e.yaml
Labels: approved, lgtm, size/M

#4899 Enable ci for jenkins operator as olm
  ci-operator/config/redhat-developer/openshift-jenkins-operator/OWNERS
  ci-operator/config/redhat-developer/openshift-jenkins-operator/redhat-developer-openshift-jenkins-operator-master.yaml
  ci-operator/jobs/redhat-developer/openshift-jenkins-operator/OWNERS
  ci-operator/jobs/redhat-developer/openshift-jenkins-operator/redhat-developer-openshift-jenkins-operator-master-presubmits.yaml
Labels: approved, lgtm, size/L

#4955 Download golangci-lint as a binary
  ci-operator/config/openshift/managed-velero-operator/openshift-managed-velero-operator-master.yaml
  ci-operator/config/openshift/managed-velero-operator/openshift-managed-velero-operator-release-4.2.yaml
  ci-operator/config/openshift/managed-velero-operator/openshift-managed-velero-operator-release-4.3.yaml
Labels: approved, lgtm, size/S

#4954 openstack: copy openshift-tests to /tmp/shared/
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e.yaml
Labels: approved, lgtm, size/S

#4957 openstack: cp kubectl into /tmp/shared
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e.yaml
Labels: approved, lgtm, size/XS

#4939 Fixing e2e vs integration test naming
  ci-operator/config/openshift/odo/openshift-odo-master.yaml
  ci-operator/jobs/openshift/odo/openshift-odo-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#4956 Add nscert image to knative serving
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-next.yaml
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-next__variant.yaml
Labels: approved, lgtm, size/S

#4949 Add promotion to tekton cli release next
  ci-operator/config/openshift/tektoncd-cli/openshift-tektoncd-cli-release-next.yaml
Labels: approved, lgtm, size/XS

#4962 openshift-cluster-autoscaler-operator: Rename AWS periodic job
  ci-operator/jobs/openshift/cluster-autoscaler-operator/openshift-cluster-autoscaler-operator-periodics.yaml
Labels: approved, lgtm, size/XS

#4963 Drop k8s jenkins jobs
  ci-operator/jobs/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-kubemark/openshift-cluster-api-provider-kubemark-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-autoscaler-operator/openshift-cluster-autoscaler-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-master-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-master-presubmits.yaml
Labels: approved, lgtm, size/M

#4960 [openshift-jenkins-operator] Switch to golang 1.12
  ci-operator/config/redhat-developer/openshift-jenkins-operator/redhat-developer-openshift-jenkins-operator-master.yaml
Labels: approved, lgtm, size/XS

#4965 Remove job periodic-prow-image-autobump
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm, size/M

#4835 Add openstack beta repos mirror
  Makefile
  ci-operator/infra/openshift/release-controller/repos/ocp-4.3-openstack-beta.repo
  ci-operator/infra/openshift/release-controller/rpms-ocp-4.3.yaml
Labels: approved, lgtm, size/M

#4968 remove unneeded jobs
  ci-operator/config/containers/libpod/containers-libpod-master.yaml
  ci-operator/jobs/containers/libpod/containers-libpod-master-presubmits.yaml
Labels: approved, lgtm, size/M

#4964 openstack: add optional parallel tests job on installer
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
Labels: approved, lgtm, size/M

#4905 Add dependancies for verification-tests (bushslicer) to Azure CI base image
  projects/azure/base-images/ci-base.yaml
Labels: approved, lgtm, sig/azure, size/S

#4972 Add boskos Pods to the Prow priority class
  cluster/ci/config/prow/openshift/boskos.yaml
  cluster/ci/config/prow/openshift/boskos_metrics.yaml
  cluster/ci/config/prow/openshift/boskos_reaper.yaml
Labels: approved, lgtm, size/XS

#4952 Add CI configuration for integr8ly/integreatly-operator
  ci-operator/config/integr8ly/integreatly-operator/OWNERS
  ci-operator/config/integr8ly/integreatly-operator/integr8ly-integreatly-operator-master.yaml
  ci-operator/jobs/integr8ly/integreatly-operator/OWNERS
  ci-operator/jobs/integr8ly/integreatly-operator/integr8ly-integreatly-operator-master-postsubmits.yaml
  ci-operator/jobs/integr8ly/integreatly-operator/integr8ly-integreatly-operator-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/ci-operator/roles.yaml
  cluster/ci/config/prow/plugins.yaml
  cluster/ci/config/roles.yaml
Labels: approved, lgtm, size/L

#4973 Update machine approver to require self approval
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#4974 Restore build suc.-rate to 100 for branch-.*-images jobs
  cluster/ci/monitoring/mixins/config.libsonnet
  cluster/ci/monitoring/mixins/prometheus/build_cop_alerts.libsonnet
  cluster/ci/monitoring/mixins/prometheus_out/prometheus_rule_prow.yaml
Labels: approved, lgtm, size/S

#4975 Bump Golang version for CAO to 1.12
  ci-operator/config/openshift/cluster-autoscaler-operator/openshift-cluster-autoscaler-operator-master.yaml
  ci-operator/config/openshift/cluster-autoscaler-operator/openshift-cluster-autoscaler-operator-release-4.2.yaml
  ci-operator/config/openshift/cluster-autoscaler-operator/openshift-cluster-autoscaler-operator-release-4.3.yaml
Labels: approved, lgtm, size/XS

#4969 remove v8 release, it was not to be
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-release-v8.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v8-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/L

#4967 Add tide to tektoncd-cli
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/XS

#4883 Enable tests against 4.2 cluster
  ci-operator/config/openshift/odo/openshift-odo-master__v4.1.yaml
  ci-operator/config/openshift/odo/openshift-odo-master__v4.2.yaml
  ci-operator/jobs/openshift/odo/openshift-odo-master-presubmits.yaml
Labels: approved, lgtm, ok-to-test, size/L

#4922 presubmit e2e job & configuration for codeready-toolchain/toolchain-e2e repo
  ci-operator/config/codeready-toolchain/toolchain-e2e/OWNERS
  ci-operator/config/codeready-toolchain/toolchain-e2e/codeready-toolchain-toolchain-e2e-master.yaml
  ci-operator/jobs/codeready-toolchain/toolchain-e2e/OWNERS
  ci-operator/jobs/codeready-toolchain/toolchain-e2e/codeready-toolchain-toolchain-e2e-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#4971 create a period job to import openshift sample imagestreams
  ci-operator/jobs/openshift/library/openshift-library-periodics.yaml
Labels: approved, lgtm, size/M

#4978 fix up periodic samples import job
  ci-operator/jobs/openshift/library/openshift-library-periodics.yaml
Labels: approved, lgtm, size/S

#4970 openstack: setup test credentials
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e.yaml
Labels: approved, lgtm, size/S

#4961 ci-operator: add jobs for oauth-proxy 3.11 branch
  ci-operator/config/openshift/oauth-proxy/openshift-oauth-proxy-release-3.11.yaml
  ci-operator/jobs/openshift/oauth-proxy/openshift-oauth-proxy-release-3.11-postsubmits.yaml
  ci-operator/jobs/openshift/oauth-proxy/openshift-oauth-proxy-release-3.11-presubmits.yaml
  projects/oauth-proxy/pipeline.yaml
Labels: approved, lgtm, size/L

#4977 Add pullrequest init to 0.5 tekton release
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.5.2.yaml
  core-services/image-mirroring/tekton/mapping_tekton_v0_5_quay
Labels: approved, lgtm, size/XS

#4982 e2e-aws: increase memory for test runner for 1.16 rebase
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
Labels: approved, lgtm, size/XS

#4985 Make build-cop-target-low alerts more sensitive
  cluster/ci/monitoring/mixins/prometheus/build_cop_alerts.libsonnet
  cluster/ci/monitoring/mixins/prometheus_out/prometheus_rule_prow.yaml
Labels: approved, lgtm, size/S

#4988 [11-09-2019 15:42:10] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  ci-operator/jobs/redhat-cop/org/redhat-cop-org-master-postsubmits.yaml
  ci-operator/jobs/redhat-cop/org/redhat-cop-org-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/boskos.yaml
  cluster/ci/config/prow/openshift/boskos_metrics.yaml
  cluster/ci/config/prow/openshift/boskos_reaper.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  hack/images.sh
Labels: approved, lgtm, size/L

#4907 Include oc rpms in origin artifacts
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
Labels: approved, lgtm, size/M

#5013 CI config for windows-machine-config-operator
  ci-operator/config/openshift/windows-machine-config-operator/OWNERS
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-master.yaml
  ci-operator/jobs/openshift/windows-machine-config-operator/OWNERS
  ci-operator/jobs/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-master-presubmits.yaml
Labels: approved, lgtm, size/M

#5022 OpenStack: set unique cluster names
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e.yaml
Labels: approved, lgtm, size/S

#5024 Enable tide for master: windows-machine-config-operator
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm, size/XS

#5019 make jobs that using gcr.io images, rehearseable
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#5027 Update cluster-api golang version
  ci-operator/config/openshift/cluster-api/openshift-cluster-api-openshift-4.2.yaml
Labels: approved, lgtm, size/XS

#5028 Update golang version in machine-api repos to 1.12
  ci-operator/config/openshift/cluster-api-provider-kubemark/openshift-cluster-api-provider-kubemark-master.yaml
  ci-operator/config/openshift/cluster-api-provider-kubemark/openshift-cluster-api-provider-kubemark-release-4.2.yaml
  ci-operator/config/openshift/cluster-api-provider-kubemark/openshift-cluster-api-provider-kubemark-release-4.3.yaml
  ci-operator/config/openshift/cluster-api-provider-libvirt/openshift-cluster-api-provider-libvirt-master.yaml
  ci-operator/config/openshift/cluster-api-provider-libvirt/openshift-cluster-api-provider-libvirt-release-4.2.yaml
  ci-operator/config/openshift/cluster-api-provider-libvirt/openshift-cluster-api-provider-libvirt-release-4.3.yaml
  ci-operator/config/openshift/cluster-api/openshift-cluster-api-master.yaml
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-master.yaml
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-release-4.2.yaml
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-release-4.3.yaml
Labels: approved, lgtm, size/S

#5030 Backport changes from branched configs to master
  ci-operator/config/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-master.yaml
  ci-operator/config/openshift/openshift-tuned/openshift-openshift-tuned-master.yaml
Labels: approved, lgtm, size/S

#4984 [ARO] add 7.1 jobs
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v7-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/M

#5034 bz plugin: configure states instead of statuses
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/S

#5035 ci-operator: Use return from nested bash functions
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-libvirt-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-metal-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e-openshift-ansible.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e-openshift-jenkins.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e-upgrade.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-scaleup-e2e-40.yaml
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure.yaml
Labels: approved, lgtm, sig/azure, size/M

#5010 [3/x] Remove Prow config files from their old location
  cluster/ci/config/prow/boskos.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/labels.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#5026 Add stub test-e2e-encryption suite
  ci-operator/config/openshift/cluster-kube-apiserver-operator/openshift-cluster-kube-apiserver-operator-master.yaml
  ci-operator/config/openshift/cluster-kube-apiserver-operator/openshift-cluster-kube-apiserver-operator-release-4.2.yaml
  ci-operator/config/openshift/cluster-kube-apiserver-operator/openshift-cluster-kube-apiserver-operator-release-4.3.yaml
  ci-operator/jobs/openshift/cluster-kube-apiserver-operator/openshift-cluster-kube-apiserver-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-kube-apiserver-operator/openshift-cluster-kube-apiserver-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/cluster-kube-apiserver-operator/openshift-cluster-kube-apiserver-operator-release-4.3-presubmits.yaml
Labels: approved, lgtm, size/L

#5031 [4/x] Store deck extensions in configmap
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/XS

#5032 [5/x] Make deck load extensions from the CM and get rid of the secret
  Makefile
  cluster/ci/config/prow/openshift/deck.yaml
  core-services/prow/02_config/deck-extensions/favicon.ico
  core-services/prow/02_config/deck-extensions/logo.png
  core-services/prow/02_config/deck-extensions/script.js
  core-services/prow/02_config/deck-extensions/style.css
Labels: approved, lgtm, size/S

#5039 OpenStack: increase test image memory quota
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e.yaml
Labels: approved, lgtm, size/XS

#5040 ci-operator: 4.2 OCP e2e-aws is running the wrong tests
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
Labels: approved, lgtm, size/XS

#5043 Add CI for oc-4.3-kubernetes-1.16.0-rc.2 k8s branches
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-oc-4.3-kubernetes-1.16.0-rc.2.yaml
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-origin-4.3-kubernetes-1.16.0-beta.2.yaml
  ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-oc-4.3-kubernetes-1.16.0-rc.2-presubmits.yaml
  ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-origin-4.3-kubernetes-1.16.0-beta.2-presubmits.yaml
Labels: approved, lgtm, size/L

#5048 ci-operator: 4.1 serial and parallel OCP jobs were flipped
  ci-operator/jobs/openshift/release/openshift-release-release-4.1-periodics.yaml
Labels: approved, lgtm, size/S

#5038 Bumping proxy ca to match newly generated certs
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
Labels: approved, lgtm, size/M

#5049 Document self-service secret injection
  ci-operator/SECRETS.md
Labels: approved, lgtm, size/M

#5051 ci-operator: Add a release periodic that tests 4.1 nodes with 4.2 clusters
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
Labels: approved, lgtm, size/L

#5052 ci-operator: Add a GCP upgrade job from 4.2 ci to 4.2 ci
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
Labels: approved, lgtm, size/M

#5059 ci-operator: Most periodics can be rehearsed
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
Labels: approved, lgtm, size/M

#5055 Adding myself to the prowjob-readers role
  cluster/ci/config/roles.yaml
Labels: approved, lgtm, size/XS

#5053 Add integr8ly-ci-secrets to secret mirroring config
  cluster/ci/config/secret-mirroring/mapping.yaml
Labels: approved, lgtm, size/S

#5056 ci-operator: Add an Azure upgrade job from 4.2 ci to 4.2 ci
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
Labels: approved, lgtm, size/M

#5045 Updating path for openstack beta repo
  ci-operator/infra/openshift/release-controller/repos/ocp-4.3-openstack-beta.repo
Labels: approved, lgtm, size/XS

#5014 Add periodic job: periodic-prow-image-autoowners
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm, size/M

#5065 remove bumg-prow-images.sh, we now use autobumper
  hack/bump-prow-images.sh
Labels: approved, lgtm, size/M

#5063 Adding cfg for eventing core 0.9.0 release branch
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.9.0.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.9.0-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.9.0-presubmits.yaml
Labels: approved, lgtm, size/L

#5064 Move Prow manifests under core-services
  Makefile
  core-services/prow/03_deployment/PROW_RESOURCES.md
  core-services/prow/03_deployment/adapter_imagestreams.yaml
  core-services/prow/03_deployment/admin_artifact-uploader_rbac.yaml
  core-services/prow/03_deployment/admin_boskos_rbac.yaml
  core-services/prow/03_deployment/admin_config_updater_rbac.yaml
  core-services/prow/03_deployment/admin_deck_rbac.yaml
  core-services/prow/03_deployment/admin_hook_rbac.yaml
  core-services/prow/03_deployment/admin_horologium_rbac.yaml
  core-services/prow/03_deployment/admin_jenkins_operator_rbac.yaml
  core-services/prow/03_deployment/admin_plank_rbac.yaml
  core-services/prow/03_deployment/admin_sinker_rbac.yaml
  core-services/prow/03_deployment/admin_statusreconciler_rbac.yaml
  core-services/prow/03_deployment/admin_tide_rbac.yaml
  core-services/prow/03_deployment/admin_tracer_rbac.yaml
  core-services/prow/03_deployment/artifact-uploader.yaml
  core-services/prow/03_deployment/boskos.yaml
  core-services/prow/03_deployment/boskos_metrics.yaml
  core-services/prow/03_deployment/boskos_reaper.yaml
  core-services/prow/03_deployment/cherrypick.yaml
  core-services/prow/03_deployment/deck.yaml
  core-services/prow/03_deployment/ghproxy.yaml
  core-services/prow/03_deployment/hook.yaml
  core-services/prow/03_deployment/horologium.yaml
  core-services/prow/03_deployment/jenkins_operator.yaml
  core-services/prow/03_deployment/needs_rebase.yaml
  core-services/prow/03_deployment/plank.yaml
  core-services/prow/03_deployment/prow-priority-class.yaml
  core-services/prow/03_deployment/refresh.yaml
  core-services/prow/03_deployment/sinker.yaml
  core-services/prow/03_deployment/statusreconciler.yaml
  core-services/prow/03_deployment/tide.yaml
  core-services/prow/03_deployment/tot.yaml
  core-services/prow/03_deployment/tracer.yaml
  hack/bump-pr.sh
Labels: approved, lgtm, size/L

#5066 chaning to 4.2
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.9.0.yaml
Labels: approved, lgtm, size/XS

#5069 remove e2e-aws test from logging repos
  ci-operator/config/openshift/cluster-logging-operator/openshift-cluster-logging-operator-master.yaml
  ci-operator/config/openshift/cluster-logging-operator/openshift-cluster-logging-operator-release-4.1.yaml
  ci-operator/config/openshift/cluster-logging-operator/openshift-cluster-logging-operator-release-4.2.yaml
  ci-operator/config/openshift/cluster-logging-operator/openshift-cluster-logging-operator-release-4.3.yaml
  ci-operator/config/openshift/elasticsearch-operator/openshift-elasticsearch-operator-master.yaml
  ci-operator/config/openshift/elasticsearch-operator/openshift-elasticsearch-operator-release-4.1.yaml
  ci-operator/config/openshift/elasticsearch-operator/openshift-elasticsearch-operator-release-4.2.yaml
  ci-operator/config/openshift/elasticsearch-operator/openshift-elasticsearch-operator-release-4.3.yaml
  ci-operator/config/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-master.yaml
  ci-operator/config/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-release-4.1.yaml
  ci-operator/config/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-release-4.2.yaml
  ci-operator/config/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-release-4.3.yaml
  ci-operator/jobs/openshift/cluster-logging-operator/openshift-cluster-logging-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-logging-operator/openshift-cluster-logging-operator-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/cluster-logging-operator/openshift-cluster-logging-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/cluster-logging-operator/openshift-cluster-logging-operator-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/elasticsearch-operator/openshift-elasticsearch-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/elasticsearch-operator/openshift-elasticsearch-operator-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/elasticsearch-operator/openshift-elasticsearch-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/elasticsearch-operator/openshift-elasticsearch-operator-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-master-presubmits.yaml
  ci-operator/jobs/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-release-4.3-presubmits.yaml
Labels: approved, lgtm, size/XL

#5070 ocs-operator: Make e2e tests optional
  ci-operator/jobs/openshift/ocs-operator/openshift-ocs-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/ocs-operator/openshift-ocs-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/ocs-operator/openshift-ocs-operator-release-4.3-presubmits.yaml
Labels: approved, lgtm, size/XS

#5074 Prow: drop max azure CI clusters to 5
  core-services/prow/02_config/_boskos.yaml
Labels: approved, lgtm, size/XS

#5060 Bug 1753032: cluster-launch-installer-upi-e2e: vsphere upi: Add bootstrap gather
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#5071 add 4.2 periodic e2e-gcp w release from origin/release-4.2
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
Labels: approved, lgtm, size/M

#5078 Add OpenStack team to approvers of their CI workflow
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/templates/openshift/installer/OWNERS
Labels: approved, lgtm, size/XS

#5076 OpenStack: Execute purge of dns records after all log collection is done
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e.yaml
Labels: approved, lgtm, size/XS

#5077 Adding myself to the ci-admins group
  cluster/ci/config/roles.yaml
Labels: approved, lgtm, size/XS

#5058 ci-operator/templates/openshift/installer/cluster-launch-installer-e2e: 'set -e' in setup
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
Labels: approved, lgtm, size/XS

#5079 ci-operator/templates/openshift/installer/cluster-launch-installer-*: Drop *_REGION from teardown
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
Labels: approved, lgtm, size/XS

#5084 Prow: increase max Azure CI clusters to 20
  core-services/prow/02_config/_boskos.yaml
Labels: approved, lgtm, size/XS

#5085 ci-operator/infra: add ubi8 imagestream
  ci-operator/infra/openshift/release-controller/images-ocp.yaml
  ci-operator/infra/openshift/release-controller/images-origin.yaml
Labels: approved, lgtm, size/M

#5083 Add secrets to unit test job
  ci-operator/config/integr8ly/integreatly-operator/integr8ly-integreatly-operator-master.yaml
  ci-operator/jobs/integr8ly/integreatly-operator/integr8ly-integreatly-operator-master-presubmits.yaml
Labels: approved, lgtm, size/S

#5062 Add Knative Serving release v0.8.1
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-v0.8.1.yaml
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-v0.8.1__variant.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-v0.8.1-postsubmits.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-v0.8.1-presubmits.yaml
Labels: approved, lgtm, size/XL

#5091 ocs-operator: Add test to verify if generated files have been committed
  ci-operator/config/openshift/ocs-operator/openshift-ocs-operator-master.yaml
  ci-operator/config/openshift/ocs-operator/openshift-ocs-operator-release-4.2.yaml
  ci-operator/config/openshift/ocs-operator/openshift-ocs-operator-release-4.3.yaml
  ci-operator/jobs/openshift/ocs-operator/openshift-ocs-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/ocs-operator/openshift-ocs-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/ocs-operator/openshift-ocs-operator-release-4.3-presubmits.yaml
Labels: approved, lgtm, size/L

#5087 Build image auto-config-brancher
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
Labels: approved, lgtm, size/S

#5093 get rid of image
  ci-operator/config/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-next.yaml
  ci-operator/config/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-next__variant.yaml
Labels: approved, lgtm, size/S

#5094 ocs-operator: Fix verify-operator-sdk-gen
  ci-operator/config/openshift/ocs-operator/openshift-ocs-operator-master.yaml
  ci-operator/config/openshift/ocs-operator/openshift-ocs-operator-release-4.2.yaml
  ci-operator/config/openshift/ocs-operator/openshift-ocs-operator-release-4.3.yaml
Labels: approved, lgtm, size/XS

#5095 Run the canary on metal every hour
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
Labels: approved, lgtm, size/XS

#5096 Update CPU and memory requests
  core-services/prow/03_deployment/artifact-uploader.yaml
  core-services/prow/03_deployment/hook.yaml
  core-services/prow/03_deployment/needs_rebase.yaml
Labels: approved, lgtm, size/S

#5080 Added bot-merge for NFD
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/XS

#5081 ci-operator/templates/openshift/installer/cluster-launch-installer-*: Random Azure regions
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
Labels: approved, lgtm, size/S

#5098 creating proxy canary job for 4.2
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
Labels: approved, lgtm, size/M

#5099 Use make targets for all ocs tests
  ci-operator/config/openshift/ocs-operator/openshift-ocs-operator-master.yaml
  ci-operator/config/openshift/ocs-operator/openshift-ocs-operator-release-4.2.yaml
  ci-operator/config/openshift/ocs-operator/openshift-ocs-operator-release-4.3.yaml
  ci-operator/jobs/openshift/ocs-operator/openshift-ocs-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/ocs-operator/openshift-ocs-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/ocs-operator/openshift-ocs-operator-release-4.3-presubmits.yaml
Labels: approved, lgtm, size/XXL

#5104 ci-operator/azure: schedule azure-serial runs in 4h intervals
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
Labels: approved, lgtm, size/XS

#5107 Change toolchain-member tag_specification to ocp 4.2
  ci-operator/config/codeready-toolchain/member-operator/codeready-toolchain-member-operator-master.yaml
Labels: approved, lgtm, size/XS

#5108 Change toolchain-common tag_specification to ocp 4.2
  ci-operator/config/codeready-toolchain/toolchain-common/codeready-toolchain-toolchain-common-master.yaml
Labels: approved, lgtm, size/XS

#5109 Change toolchain-host tag_specification to ocp 4.2
  ci-operator/config/codeready-toolchain/host-operator/codeready-toolchain-host-operator-master.yaml
Labels: approved, lgtm, size/XS

#5110 Change toolchain-api tag_specification to ocp 4.2
  ci-operator/config/codeready-toolchain/api/codeready-toolchain-api-master.yaml
Labels: approved, lgtm, size/XS

#5111 Change toolchain-e2e tag_specification to ocp 4.2
  ci-operator/config/codeready-toolchain/toolchain-e2e/codeready-toolchain-toolchain-e2e-master.yaml
Labels: approved, lgtm, size/XS

#5117 Add tremes to integr8ly owners
  ci-operator/config/integr8ly/integreatly-operator/OWNERS
  ci-operator/jobs/integr8ly/integreatly-operator/OWNERS
Labels: approved, lgtm, size/XS

#5103 Stop rehearsing owners check
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm, size/XS

#5114 core-services: add base-ci-images
  core-services/base-ci-images/OWNERS
  core-services/base-ci-images/README.md
  core-services/base-ci-images/images-ocp.yaml
  core-services/base-ci-images/images-origin.yaml
Labels: approved, lgtm, size/XS

#5118 Move secret-mirroring config to core-services
  Makefile
  ci-operator/SECRETS.md
  core-services/prow/02_config/_plugins.yaml
  core-services/secret-mirroring/OWNERS
  core-services/secret-mirroring/README.md
  core-services/secret-mirroring/_mapping.yaml
  core-services/secret-mirroring/admin_rbac.yaml
  core-services/secret-mirroring/deployment.yaml
  projects/azure/README.md
Labels: approved, lgtm, sig/azure, size/L

#5100 OpenStack: Add performance volumes to control plane instances
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e.yaml
Labels: approved, lgtm, size/XS

#4637 Refreshed openstack-approvers
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#4788 logging - add simple upgrade job
  ci-operator/config/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-master.yaml
  ci-operator/jobs/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-master-presubmits.yaml
Labels: approved, lgtm, size/M

#5119 Upload test secrets for Operator SDK
  ci-operator/populate-secrets-from-bitwarden.sh
Labels: approved, lgtm, size/XS

#5120 Add a new image for the config-change-trigger
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
Labels: approved, lgtm, size/XS

#5105 Copy binary autoconfigbrancher in image
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
Labels: approved, lgtm, size/XS

#4901 Adds a new periodic Azure Red Hat OpenShift job
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-periodics.yaml
Labels: approved, lgtm, sig/azure, size/S

#5121 Allow Prow services to fall back to GitHub API when ghproxy is down
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/redhat-cop/org/redhat-cop-org-master-postsubmits.yaml
  ci-operator/jobs/redhat-cop/org/redhat-cop-org-periodics.yaml
  core-services/prow/03_deployment/hook.yaml
  core-services/prow/03_deployment/needs_rebase.yaml
  core-services/prow/03_deployment/plank.yaml
  core-services/prow/03_deployment/tide.yaml
Labels: approved, lgtm, size/S

#5122 Add a job to trigger images postsubmits on config changes
  Makefile
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
Labels: approved, lgtm, size/M

#5115 Clean up deprecated tool: populate-owners
  ci-operator/populate-owners.sh
  tools/populate-owners/OWNERS
  tools/populate-owners/README.md
  tools/populate-owners/main.go
  tools/populate-owners/main_test.go
Labels: approved, lgtm, size/XL

#4585 Add support for testing installs from mirrored repositories
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
Labels: approved, lgtm, size/L
