Repository openshift/release, pull requests merged in 2019-03, with the labels that each got.

#2951 Add reimage vm and update cluster jobs
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-periodics.yaml
Labels: approved, lgtm, sig/azure, size/L

#2984 Accidentally removed cvo integration test, restore
  ci-operator/jobs/openshift/cluster-version-operator/openshift-cluster-version-operator-master-presubmits.yaml
Labels: approved, lgtm, size/M

#2983 Add IMAGE_FORMAT and ARTIFACT_DIR as env vars to test container in ansible openshift templates
  ci-operator/templates/cluster-launch-e2e.yaml
  ci-operator/templates/cluster-launch-src.yaml
Labels: approved, lgtm, size/XS

#2811 Remove juanvallejo from OWNERS files
  ci-operator/config/openshift/must-gather/OWNERS
  ci-operator/jobs/openshift/must-gather/OWNERS
Labels: approved, lgtm, size/XS

#2981 ci-operator/templates/openshift/openshift-ansible/cluster-scaleup-e2e-40: Drop IMAGE_FORMAT
  ci-operator/templates/openshift/openshift-ansible/cluster-scaleup-e2e-40.yaml
Labels: approved, lgtm, size/XS

#2985 BYOR 3.11: retry oc login command
  ci-operator/templates/cluster-launch-e2e-openshift-ansible.yaml
Labels: approved, lgtm, size/XS

#2986 machine-api-operator: job name change
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#2987 machine-api-operator: partial revert of #2986
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#2988 Add trigger config for odo
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#2989 azure: move Dockerfiles to suit ART standards
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-master.yaml
Labels: approved, lgtm, sig/azure, size/S

#2982 Move ansible openshift templates templates/openshift-ansible/
  Makefile
  ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e-openshift-ansible.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e-openshift-jenkins.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e-upgrade.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-launch-src.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/S

#2992 Enable the prow plugin: release-note
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/labels.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/M

#2993 Set Metering unit TEST_OUTPUT_PATH to allow storing junit test report results and coverage results in artifacts dir
  ci-operator/config/operator-framework/operator-metering/operator-framework-operator-metering-master.yaml
Labels: approved, lgtm, size/XS

#2994 Set artifact_dir for metering unit tests
  ci-operator/config/operator-framework/operator-metering/operator-framework-operator-metering-master.yaml
Labels: approved, lgtm, size/XS

#2995 Bump deck to get histogram and filter to test
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/deck.yaml
Labels: approved, lgtm, size/XS

#2996 Prepare the cluster-installer-e2e template for upgrades
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
Labels: approved, lgtm, size/M

#2968 azure: update release update jobs to v2.4
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-master.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/S

#2998 BYOR 4.0: fix secret name in scaleup template
  ci-operator/templates/openshift/openshift-ansible/cluster-scaleup-e2e-40.yaml
Labels: approved, lgtm, size/XS

#2990 Adding initial configuration for testing redhat-developer/odo on prow
  ci-operator/config/redhat-developer/odo/OWNERS
  ci-operator/config/redhat-developer/odo/redhat-developer-odo-master.yaml
  ci-operator/jobs/redhat-developer/odo/OWNERS
  ci-operator/jobs/redhat-developer/odo/redhat-developer-odo-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, ok-to-test, size/L

#2999 Update knative-build-pipelines
  ci-operator/config/openshift/knative-build-pipeline/openshift-knative-build-pipeline-master.yaml
  ci-operator/jobs/openshift/knative-build-pipeline/openshift-knative-build-pipeline-master-presubmits.yaml
Labels: approved, lgtm, size/S

#3003 Disabling self approval and lgtm_as_approve for redhat-developer odo
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#3004 Fixing spacing for circle ci name
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/XS

#2928 mkpjpod demos
  ci-operator/README.md
  hack/mkpjpod.sh
Labels: approved, lgtm, size/M

#3001 Output data for Pod status and phase
  hack/monitor_prow.py
Labels: approved, lgtm, size/S

#3007 Add new image builds to the prowgen repo
  ci-operator/config/openshift/ci-operator-prowgen/openshift-ci-operator-prowgen-master.yaml
Labels: approved, lgtm, size/M

#3002 Federation: run make targets instead of inlined scripts
  ci-operator/config/openshift/federation-v2-operator/openshift-federation-v2-operator-master.yaml
Labels: approved, lgtm, size/S

#3008 Add a job to validate configuration shards
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
Labels: approved, lgtm, size/S

#3010 Change the names for config volume mounts
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  cluster/ci/config/prow/plugins.yaml
  hack/validate-config-sharding.sh
Labels: approved, lgtm, size/L

#2976 BYOR 4.0: run RHEL scaleup as an additional test in machine-api-operator
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-master.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-master-presubmits.yaml
Labels: approved, lgtm, size/M

#3015 Regenerate machine-api-operator jobs
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#2975 BYOR 4.0: run RHEL scaleup as an additional test in MCO PRs
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-master.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-master-presubmits.yaml
Labels: approved, lgtm, size/M

#3016 Change to use AWS for 4.0 clusters
  ci-operator/config/openshift/knative-build-pipeline/openshift-knative-build-pipeline-master.yaml
  ci-operator/jobs/openshift/knative-build-pipeline/openshift-knative-build-pipeline-master-presubmits.yaml
Labels: approved, lgtm, size/S

#3017 Add a PVC for the release controller to use as a git cache
  ci-operator/infra/openshift/release-controller/deploy-ocp-4.0.yaml
Labels: approved, lgtm, size/S

#3018 The override repo is incorrect in origin machine-os-content
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
Labels: approved, lgtm, size/XS

#3019 hive: make external jobs non-blocking
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/XS

#3020 Actually load jobs into tide
  cluster/ci/config/prow/openshift/tide.yaml
Labels: approved, lgtm, size/S

#3011 Create a git-credentials secret in ci-release for release-controller
  ci-operator/populate-secrets-from-bitwarden.sh
Labels: approved, lgtm, size/S

#3023 update OWNERS files for machine-config-operator
  ci-operator/config/openshift/machine-config-operator/OWNERS
  ci-operator/jobs/openshift/machine-config-operator/OWNERS
Labels: approved, lgtm, size/S

#3022 Adding AAD group sync id to cluster build.
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure.yaml
Labels: approved, lgtm, sig/azure, size/XS

#3025 Properly layer the content for machine-os-content
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
Labels: approved, lgtm, size/XS

#3024 Add registry viewers
  cluster/ci/config/roles.yaml
Labels: approved, lgtm, size/M

#3026 Update origin to reuse the bin directory correctly
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
Labels: approved, lgtm, size/S

#3029 Remove the installer upgrade variables
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
Labels: approved, lgtm, size/XS

#2974 BYOR 4.0: run RHEL scaleup test as an additional test in installer PRs
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
Labels: approved, lgtm, size/M

#3006 osa - add v1.2-to-v2.4,5 upgrade test
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-master.yaml
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-release-v2.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v2-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/L

#3033 cluster-api: fix canonical repo path
  ci-operator/config/openshift/cluster-api/openshift-cluster-api-master.yaml
Labels: approved, lgtm, size/XS

#3012 Update install config to match v1beta4 schema.
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e-40.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-scaleup-e2e-40.yaml
Labels: approved, lgtm, size/L

#3035 Fix invalid roles yaml
  Makefile
  cluster/ci/config/prow/openshift/ci-operator/roles.yaml
  cluster/ci/config/roles.yaml
Labels: approved, lgtm, size/M

#3036 Add an image with `make` and `oc`, use it
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  projects/origin-release/cli.yaml
Labels: approved, lgtm, size/M

#3037 Add an hourly fast-forward
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/M

#3038 Fix secret mount
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
Labels: approved, lgtm, size/XS

#3039 osa deprecate 1.2 testing
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-master.yaml
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-release-v1.yaml
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-release-v2.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v1-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v1-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/L

#3040 fix new config map names
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-periodics.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v2-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/L

#3041 typos
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-periodics.yaml
Labels: approved, lgtm, sig/azure, size/XS

#3028 rename e2e binary to e2e-tests
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-master.yaml
Labels: approved, lgtm, sig/azure, size/XS

#3043 osa - e2e test location
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-master.yaml
Labels: approved, lgtm, sig/azure, size/XS

#3045 [08-03-2019 17:30:53] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
Labels: approved, lgtm, size/M

#3048 Remove system-containers test from openshift-ansible:release-39 presub
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-3.9-presubmits.yaml
Labels: approved, lgtm, size/S

#3030 Add one of the new style upgrade tests to ci-operator
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-master.yaml
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/infra/openshift/release-controller/ocp-4.0-ci.json
  ci-operator/jobs/openshift/cluster-version-operator/openshift-cluster-version-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  cluster/ci/config/prow/openshift/ci-operator/roles.yaml
Labels: approved, lgtm, size/L

#3049 Correct incorrect --target in aws-upgrade job
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
Labels: approved, lgtm, size/S

#3050 Update release periodic shard config to match new config maps
  ci-operator/infra/openshift/ci-chat-bot/deploy.yaml
  ci-operator/infra/openshift/release-controller/deploy-ocp-4.0.yaml
  ci-operator/infra/openshift/release-controller/deploy-origin-4.0.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
Labels: approved, lgtm, size/S

#3051 Release jobs use the misc sharded config map
  ci-operator/infra/openshift/ci-chat-bot/deploy.yaml
  ci-operator/infra/openshift/release-controller/deploy-ocp-4.0.yaml
  ci-operator/infra/openshift/release-controller/deploy-origin-4.0.yaml
Labels: approved, lgtm, size/XS

#3052 Remove release- prefix from jobs
  Makefile
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
Labels: approved, lgtm, size/M

#2901 Build Jenkins on top of the UBI image instead of centos
  ci-operator/config/openshift/jenkins/openshift-jenkins-master.yaml
  cluster/ci/config/prow/openshift/rpm-mirrors/ocp-4.0-default.repo
Labels: approved, lgtm, size/M

#3054 Update job names to be shorter
  ci-operator/infra/openshift/release-controller/ocp-4.0-ci.json
  ci-operator/infra/openshift/release-controller/ocp-4.0.json
Labels: approved, lgtm, size/S

#3053 increase azure memory limit, we're getting OOMs
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-master.yaml
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-release-v2.yaml
Labels: approved, lgtm, sig/azure, size/XS

#3021 ci-operator: add kubecsr
  ci-operator/config/openshift/kubecsr/OWNERS
  ci-operator/config/openshift/kubecsr/openshift-kubecsr-openshift-4.0.yaml
  ci-operator/jobs/openshift/kubecsr/OWNERS
  ci-operator/jobs/openshift/kubecsr/openshift-kubecsr-openshift-4.0-postsubmits.yaml
  ci-operator/jobs/openshift/kubecsr/openshift-kubecsr-openshift-4.0-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#3046 Update docs for running test jobs in a cluster
  ci-operator/README.md
  hack/mkpjpod.sh
Labels: approved, lgtm, size/M

#3056 Empty env var is incorrect for ci-chat-bot (which doesn't set it)
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
Labels: approved, lgtm, size/XS

#3000 add /test/e2e-aws-opearator job to cluster-kube-apiserver-operator
  ci-operator/config/openshift/cluster-kube-apiserver-operator/openshift-cluster-kube-apiserver-operator-master.yaml
  ci-operator/jobs/openshift/cluster-kube-apiserver-operator/openshift-cluster-kube-apiserver-operator-master-presubmits.yaml
Labels: approved, lgtm, size/M

#3057 Ensure status reconciler is updated after merges
  Makefile
Labels: approved, lgtm, size/XS

#3061 ci-operator/templates: Make BASE_DOMAIN a parameter
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-scaleup-e2e-40.yaml
Labels: approved, lgtm, size/S

#3055 Add CI to cluster-api-provider-baremetal
  ci-operator/config/openshift/cluster-api-provider-baremetal/OWNERS
  ci-operator/config/openshift/cluster-api-provider-baremetal/openshift-cluster-api-provider-baremetal-master.yaml
  ci-operator/jobs/openshift/cluster-api-provider-baremetal/OWNERS
  ci-operator/jobs/openshift/cluster-api-provider-baremetal/openshift-cluster-api-provider-baremetal-master-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-baremetal/openshift-cluster-api-provider-baremetal-master-presubmits.yaml
Labels: approved, lgtm, size/L

#3059 Capture higher log level output on oc failures
  hack/monitor_prow.py
Labels: approved, lgtm, size/M

#3064 Add metering integration tests to metering job
  ci-operator/config/operator-framework/operator-metering/operator-framework-operator-metering-master.yaml
  ci-operator/jobs/operator-framework/operator-metering/operator-framework-operator-metering-master-presubmits.yaml
Labels: approved, lgtm, size/M

#3065 config/prow: updates for cluster-api-provider-baremetal.
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#3068 cluster-api: Increase memory limit on unit tests
  ci-operator/config/openshift/cluster-api/openshift-cluster-api-master.yaml
Labels: approved, lgtm, size/XS

#3066 Mirror baremetal-machine-controller images
  cluster/ci/config/mirroring/origin_v4_0
  cluster/ci/config/mirroring/origin_v4_0_quay
Labels: approved, lgtm, size/XS

#3070 Revert "Mirror baremetal-machine-controller images"
  cluster/ci/config/mirroring/origin_v4_0
  cluster/ci/config/mirroring/origin_v4_0_quay
Labels: approved, lgtm, size/XS

#3073 azure: add missing target
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/XS

#3072 Everyone should be able to pull from rhcos
  Makefile
  cluster/ci/config/roles.yaml
Labels: approved, lgtm, size/M

#3060 adding 4.0 promotion tag
  ci-operator/config/openshift/ansible-service-broker/openshift-ansible-service-broker-master.yaml
  ci-operator/jobs/openshift/ansible-service-broker/openshift-ansible-service-broker-master-postsubmits.yaml
  ci-operator/jobs/openshift/ansible-service-broker/openshift-ansible-service-broker-master-presubmits.yaml
Labels: approved, lgtm, size/S

#3075 adding 4.0 promotion tag for tsb operator
  ci-operator/config/openshift/template-service-broker-operator/openshift-template-service-broker-operator-master.yaml
  ci-operator/jobs/openshift/template-service-broker-operator/openshift-template-service-broker-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/template-service-broker-operator/openshift-template-service-broker-operator-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#3058 openshift/hive - enable integration tests
  ci-operator/config/openshift/hive/openshift-hive-master.yaml
  ci-operator/jobs/openshift/hive/openshift-hive-master-presubmits.yaml
Labels: approved, lgtm, size/M

#3081 ci-operator/config/openshift/service-ca-operator: Name image "service-ca-operator"
  ci-operator/config/openshift/service-ca-operator/openshift-service-ca-operator-master.yaml
Labels: approved, lgtm, size/XS

#3082 Revert "ci-operator/config/openshift/service-ca-operator: Name image "service-ca-operator""
  ci-operator/config/openshift/service-ca-operator/openshift-service-ca-operator-master.yaml
Labels: approved, lgtm, size/XS

#3083 Restore the service-ca-operator rename
  ci-operator/config/openshift/service-ca-operator/openshift-service-ca-operator-master.yaml
  cluster/ci/config/mirroring/origin_v4_0
  cluster/ci/config/mirroring/origin_v4_0_quay
Labels: approved, lgtm, size/XS

#3077 Add a new optional job that tests the latest machine-os-content
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
Labels: approved, lgtm, size/M

#3080 Add approve to openshift/console
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#3084 [13-03-2019 02:36:25] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
Labels: approved, lgtm, size/M

#3085 Fix up tot PV, add probes to deck
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/tot.yaml
Labels: approved, lgtm, size/S

#3031 Updating config to use custom image and adding image for e2e tests
  ci-operator/config/redhat-developer/odo/redhat-developer-odo-master.yaml
  ci-operator/jobs/redhat-developer/odo/redhat-developer-odo-master-presubmits.yaml
Labels: approved, lgtm, size/M

#3086 Adding tag_specification for redhat-developer odo
  ci-operator/config/redhat-developer/odo/redhat-developer-odo-master.yaml
Labels: approved, lgtm, size/XS

#3087 Updating OpenShift CI to use aws cluster profile
  ci-operator/config/redhat-developer/odo/redhat-developer-odo-master.yaml
  ci-operator/jobs/redhat-developer/odo/redhat-developer-odo-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#3063 Add e2e-aws job for console
  ci-operator/config/openshift/console/openshift-console-master.yaml
  ci-operator/jobs/openshift/console/openshift-console-master-presubmits.yaml
Labels: approved, lgtm, size/M

#3089 Adding CI param to test script in redhat developer odo
  ci-operator/config/redhat-developer/odo/redhat-developer-odo-master.yaml
  ci-operator/jobs/redhat-developer/odo/redhat-developer-odo-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#3092 Fix remaining shard issues with configmaps
  Makefile
  ci-operator/README.md
  ci-operator/infra/openshift/ci-chat-bot/deploy.yaml
  ci-operator/jobs/containers/libpod/containers-libpod-master-postsubmits.yaml
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/azure-misc/openshift-azure-misc-periodics.yaml
  ci-operator/jobs/openshift/builder/openshift-builder-master-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-authentication-operator/openshift-cluster-authentication-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-capacity/openshift-cluster-capacity-release-3.10-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-capacity/openshift-cluster-capacity-release-3.11-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-dns-operator/openshift-cluster-dns-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-monitoring-operator/openshift-cluster-monitoring-operator-release-3.11-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-version-operator/openshift-cluster-version-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-version-operator/openshift-cluster-version-operator-release-3.11-postsubmits.yaml
  ci-operator/jobs/openshift/console/openshift-console-release-3.11-postsubmits.yaml
  ci-operator/jobs/openshift/descheduler/openshift-descheduler-release-3.10-postsubmits.yaml
  ci-operator/jobs/openshift/descheduler/openshift-descheduler-release-3.10-presubmits.yaml
  ci-operator/jobs/openshift/descheduler/openshift-descheduler-release-3.11-postsubmits.yaml
  ci-operator/jobs/openshift/image-registry/openshift-image-registry-master-presubmits.yaml
  ci-operator/jobs/openshift/image-registry/openshift-image-registry-release-3.10-postsubmits.yaml
  ci-operator/jobs/openshift/image-registry/openshift-image-registry-release-3.10-presubmits.yaml
  ci-operator/jobs/openshift/image-registry/openshift-image-registry-release-3.11-postsubmits.yaml
  ci-operator/jobs/openshift/image-registry/openshift-image-registry-release-3.11-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-3.11-postsubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-3.11-presubmits.yaml
  ci-operator/jobs/openshift/jenkins/openshift-jenkins-openshift-3.10-presubmits.yaml
  ci-operator/jobs/openshift/jenkins/openshift-jenkins-openshift-3.11-presubmits.yaml
  ci-operator/jobs/openshift/knative-build-pipeline/openshift-knative-build-pipeline-periodics.yaml
  ci-operator/jobs/openshift/knative-build/openshift-knative-build-periodics.yaml
  ci-operator/jobs/openshift/knative-eventing-sources/openshift-knative-eventing-sources-periodics.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-periodics.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-periodics.yaml
  ci-operator/jobs/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-release-3.10-postsubmits.yaml
  ci-operator/jobs/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-release-3.11-postsubmits.yaml
  ci-operator/jobs/openshift/kubernetes-metrics-server/openshift-kubernetes-metrics-server-release-3.10-postsubmits.yaml
  ci-operator/jobs/openshift/kubernetes-metrics-server/openshift-kubernetes-metrics-server-release-3.11-postsubmits.yaml
  ci-operator/jobs/openshift/node_exporter/openshift-node_exporter-release-3.11-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-3.10-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-3.10-presubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-3.11-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-3.11-presubmits.yaml
  ci-operator/jobs/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-release-3.11-postsubmits.yaml
  ci-operator/jobs/openshift/origin-metrics/openshift-origin-metrics-release-3.10-postsubmits.yaml
  ci-operator/jobs/openshift/origin-metrics/openshift-origin-metrics-release-3.11-postsubmits.yaml
  ci-operator/jobs/openshift/origin-web-console-server/openshift-origin-web-console-server-release-3.10-postsubmits.yaml
  ci-operator/jobs/openshift/origin-web-console-server/openshift-origin-web-console-server-release-3.10-presubmits.yaml
  ci-operator/jobs/openshift/origin-web-console-server/openshift-origin-web-console-server-release-3.11-postsubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-3.10-postsubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-3.11-presubmits.yaml
  ci-operator/jobs/openshift/prometheus-alertmanager/openshift-prometheus-alertmanager-release-3.11-postsubmits.yaml
  ci-operator/jobs/openshift/prometheus/openshift-prometheus-release-3.11-postsubmits.yaml
  ci-operator/jobs/openshift/service-catalog/openshift-service-catalog-release-3.11-postsubmits.yaml
  ci-operator/jobs/openshift/service-serving-cert-signer/openshift-service-serving-cert-signer-release-3.11-postsubmits.yaml
  ci-operator/jobs/openshift/telemeter/openshift-telemeter-release-3.11-postsubmits.yaml
  ci-operator/jobs/openshift/telemeter/openshift-telemeter-release-3.11-presubmits.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-periodics.yaml
  ci-operator/jobs/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-release-3.11-postsubmits.yaml
  ci-operator/populate-ci-operator-configs.sh
Labels: approved, lgtm, sig/azure, size/L

#3094 Update mirrors
  cluster/ci/config/mirroring/origin_v4_0_quay
Labels: approved, lgtm, size/S

#3093 Fixing typo of make target in redhat-developer odo
  ci-operator/config/redhat-developer/odo/redhat-developer-odo-master.yaml
  ci-operator/jobs/redhat-developer/odo/redhat-developer-odo-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#3095 Fix periodic ci-op config mounts
  ci-operator/jobs/openshift/azure-misc/openshift-azure-misc-periodics.yaml
  ci-operator/jobs/openshift/knative-build-pipeline/openshift-knative-build-pipeline-periodics.yaml
  ci-operator/jobs/openshift/knative-build/openshift-knative-build-periodics.yaml
  ci-operator/jobs/openshift/knative-eventing-sources/openshift-knative-eventing-sources-periodics.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-periodics.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-periodics.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-periodics.yaml
Labels: approved, lgtm, sig/azure, size/S

#3096 Create an origin branding image for use in OKD only
  ci-operator/config/openshift/origin-branding/OWNERS
  ci-operator/config/openshift/origin-branding/openshift-origin-branding-master.yaml
  ci-operator/jobs/openshift/origin-branding/OWNERS
  ci-operator/jobs/openshift/origin-branding/openshift-origin-branding-master-postsubmits.yaml
  ci-operator/jobs/openshift/origin-branding/openshift-origin-branding-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#3098 image-mirror should capture termination error
  cluster/ci/jobs/image-mirror.yaml
Labels: approved, lgtm, size/XS

#3097 Add metering e2e tests to ci-operator
  ci-operator/config/operator-framework/operator-metering/operator-framework-operator-metering-master.yaml
  ci-operator/jobs/operator-framework/operator-metering/operator-framework-operator-metering-master-presubmits.yaml
Labels: approved, lgtm, size/M

#3100 Adding make bin to e2e tests
  ci-operator/config/redhat-developer/odo/redhat-developer-odo-master.yaml
  ci-operator/jobs/redhat-developer/odo/redhat-developer-odo-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#3102 Make cluster-autoscaler-operator Jenkins e2e tests required
  ci-operator/jobs/openshift/cluster-autoscaler-operator/openshift-cluster-autoscaler-operator-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#3088 Add separate e2e-aws-console-olm suite
  ci-operator/config/openshift/console/OWNERS
  ci-operator/config/openshift/console/openshift-console-master.yaml
  ci-operator/jobs/openshift/console/OWNERS
  ci-operator/jobs/openshift/console/openshift-console-master-presubmits.yaml
  hack/validate-owners.sh
Labels: approved, lgtm, size/L

#3101 Add CI for cluster-api-provider-azure
  ci-operator/config/openshift/cluster-api-provider-azure/OWNERS
  ci-operator/config/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-master.yaml
  ci-operator/jobs/openshift/cluster-api-provider-azure/OWNERS
  ci-operator/jobs/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-master-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-master-presubmits.yaml
Labels: approved, lgtm, size/L

#3106 Add config and plugins for cluster-api-provider-azure
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#3107 Update cluste-api-provider-azure image name
  ci-operator/config/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-master.yaml
Labels: approved, lgtm, size/XS

#3109 Fixup branchprotector configs
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/S

#3110 Remove branch protection for redhat-developer/odo
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/S

#3111 RHEL scaleup: update secret name in cluster-scaleup-e2e-40 template
  ci-operator/templates/openshift/openshift-ansible/cluster-scaleup-e2e-40.yaml
Labels: approved, lgtm, size/XS

#3112 Add pull credentials to release jobs to unblock OCP
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  ci-operator/populate-secrets-from-bitwarden.sh
Labels: approved, lgtm, size/L

#3113 Adding odo java and e2e test scenario
  ci-operator/config/redhat-developer/odo/redhat-developer-odo-master.yaml
  ci-operator/jobs/redhat-developer/odo/redhat-developer-odo-master-presubmits.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#3032 cluster-api: Always run unit tests
  ci-operator/jobs/openshift/cluster-api/openshift-cluster-api-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#3114 openstack: Update vars for new environment
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-scaleup-e2e-40.yaml
Labels: approved, lgtm, size/S

#3108 Add my github userid for access to the Azure namespace
  projects/azure/cluster-wide.yaml
Labels: approved, lgtm, sig/azure, size/XS

#3103 osa - add tlsproxy targets
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-master.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-periodics.yaml
  projects/azure/README.md
Labels: approved, lgtm, sig/azure, size/S

#3122 autoscaler: synchronize owners file
  ci-operator/config/openshift/kubernetes-autoscaler/OWNERS
Labels: approved, lgtm, size/S

#3123 Add ConfigMap powers to ci-operator serviceaccounts
  cluster/ci/config/prow/openshift/ci-operator/roles.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
Labels: approved, lgtm, size/M

#3124 Add an emptydir to tide's tmp for git clones
  cluster/ci/config/prow/openshift/tide.yaml
Labels: approved, lgtm, size/XS

#3118 RHEL8 should promote
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
Labels: approved, lgtm, size/L

#3125 Run RHEL scaleup test for openshift-ansible master branch
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-master.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-master-presubmits.yaml
Labels: approved, lgtm, size/M

#3126 [15-03-2019 18:00:00] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
Labels: approved, lgtm, size/M

#3119 Migrate openshift-acme to v4 CI
  ci-operator/config/tnozicka/openshift-acme/tnozicka-openshift-acme-master.yaml
  ci-operator/jobs/tnozicka/openshift-acme/tnozicka-openshift-acme-master-presubmits.yaml
Labels: approved, lgtm, size/M

#3127 Increasing CPU limit and setting up env var for odo
  ci-operator/config/redhat-developer/odo/redhat-developer-odo-master.yaml
  ci-operator/jobs/redhat-developer/odo/redhat-developer-odo-master-presubmits.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#3128 openstack: Add missing computeFlavor key to the OpenStack platform
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
Labels: approved, lgtm, size/XS

#3129 Create the stable release stream definitions for 4.0
  Makefile
  ci-operator/infra/openshift/release-controller/deploy-ocp-4.0.yaml
  ci-operator/infra/openshift/release-controller/ocp-4.0-ci.json
  ci-operator/infra/openshift/release-controller/ocp-4.0-stable.json
  ci-operator/infra/openshift/release-controller/ocp-4.0.json
  ci-operator/infra/openshift/release-controller/origin-4.0.json
  cluster/ci/config/mirroring/origin_v4_0
  cluster/ci/config/mirroring/origin_v4_0_quay
Labels: approved, lgtm

#3130 Adding odo source test file
  ci-operator/config/redhat-developer/odo/redhat-developer-odo-master.yaml
  ci-operator/jobs/redhat-developer/odo/redhat-developer-odo-master-presubmits.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#3131 allow volumes in pj-rehearse jobs
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
Labels: approved, size/XS

#3133 Remove libpod images postsubmits
  ci-operator/jobs/containers/libpod/containers-libpod-master-postsubmits.yaml
Labels: approved, lgtm, size/M

#3135 tnozicka/openshift-acme: Remove cluster from tag_specification to fix RBAC issues
  ci-operator/config/tnozicka/openshift-acme/tnozicka-openshift-acme-master.yaml
Labels: approved, lgtm, size/XS

#3136 tnozicka/openhift-acme: Fix template
  ci-operator/config/tnozicka/openshift-acme/tnozicka-openshift-acme-master.yaml
  ci-operator/jobs/tnozicka/openshift-acme/tnozicka-openshift-acme-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#3137 ci-operator/config/.../operator-sdk: update to go 1.11
  ci-operator/config/operator-framework/operator-sdk/operator-framework-operator-sdk-master.yaml
Labels: approved, lgtm, size/XS

#3138 Check that origin and OCP images match
  ci-operator/infra/openshift/release-controller/ocp-4.0.json
Labels: approved, lgtm

#3139 ci-operator/config: Rename helm image name to match OCP names
  ci-operator/config/operator-framework/helm/operator-framework-helm-master.yaml
Labels: approved, lgtm, size/XS

#3116 cluster-api: validate git history
  ci-operator/config/openshift/cluster-api/openshift-cluster-api-master.yaml
  ci-operator/jobs/openshift/cluster-api/openshift-cluster-api-master-presubmits.yaml
Labels: approved, lgtm, size/M

#3104 bitwarden: add Openstack cluster secrets
  ci-operator/SECRETS.md
  ci-operator/populate-secrets-from-bitwarden.sh
Labels: approved, lgtm, size/S

#3121 autoscaler: validate git history
  ci-operator/config/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-master.yaml
  ci-operator/jobs/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-master-presubmits.yaml
Labels: approved, lgtm, size/M, ¯\_(ツ)_/¯

#3142 Add external-storage to CI
  ci-operator/config/openshift/external-storage/OWNERS
  ci-operator/config/openshift/external-storage/openshift-external-storage-master.yaml
  ci-operator/jobs/openshift/external-storage/OWNERS
  ci-operator/jobs/openshift/external-storage/openshift-external-storage-master-postsubmits.yaml
  ci-operator/jobs/openshift/external-storage/openshift-external-storage-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#3146 Remove csi-operator image job
  ci-operator/config/openshift/csi-operator/openshift-csi-operator-master.yaml
  ci-operator/jobs/openshift/csi-operator/openshift-csi-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/csi-operator/openshift-csi-operator-master-presubmits.yaml
Labels: approved, lgtm, size/M

#3140 Update metering images to match OCP image names
  ci-operator/config/operator-framework/operator-metering/operator-framework-operator-metering-master.yaml
Labels: approved, lgtm, size/S

#3150 hive: require external context for merge
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/XS

#3115 bitwarden: add `--overwrite` to `oc label` calls
  ci-operator/populate-secrets-from-bitwarden.sh
Labels: approved, lgtm, size/S

#3067 azure: replace node build job
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-master.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-periodics.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v2-presubmits.yaml
  ci-operator/templates/openshift/openshift-azure/build-base-image.yaml
  ci-operator/templates/openshift/openshift-azure/build-node-image.yaml
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure.yaml
  ci-operator/templates/openshift/openshift-azure/rbac.yaml
  projects/azure/README.md
  projects/azure/base-images/alpine.yaml
  projects/azure/base-images/test-base.yaml
  projects/azure/base-images/test-base/Dockerfile
  projects/azure/base-images/test-base/prow_mock.sh
  projects/azure/image-mirror/image-mirror.yaml
Labels: approved, lgtm, sig/azure, size/XXL

#3145 Bug 1690194 - Updating names to match downstream
  ci-operator/config/openshift/ansible-service-broker/openshift-ansible-service-broker-master.yaml
  ci-operator/config/openshift/template-service-broker-operator/openshift-template-service-broker-operator-master.yaml
Labels: approved, lgtm, size/XS

#3141 Update metering hive, hadoop, presto images to have metering- prefix on output image tags
  ci-operator/config/operator-framework/hadoop/operator-framework-hadoop-master.yaml
  ci-operator/config/operator-framework/hive/operator-framework-hive-master.yaml
  ci-operator/config/operator-framework/presto/operator-framework-presto-master.yaml
Labels: approved, lgtm, size/S

#3154 Label release periodics for chat bot
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
Labels: approved, lgtm, size/S

#3155 fix up openshift-azure after 3.0 release and previous changes
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-master.yaml
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-release-v2.yaml
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-release-v3.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-periodics.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v2-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v3-presubmits.yaml
  ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure.yaml
  ci-operator/templates/openshift/openshift-azure/rbac-azure.yaml
Labels: approved, lgtm, sig/azure, size/XL

#3147 Add cloud-provider-openstack repo
  ci-operator/config/openshift/cloud-provider-openstack/OWNERS
  ci-operator/config/openshift/cloud-provider-openstack/openshift-cloud-provider-openstack-master.yaml
  ci-operator/jobs/openshift/cloud-provider-openstack/OWNERS
  ci-operator/jobs/openshift/cloud-provider-openstack/openshift-cloud-provider-openstack-master-postsubmits.yaml
  ci-operator/jobs/openshift/cloud-provider-openstack/openshift-cloud-provider-openstack-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L
