Repository openshift/release, pull requests merged in 2019-08, with the labels that each got.

#4599 Revert "Add a AWS quota leasing stage to e2e jobs"
  ci-operator/templates/openshift/installer/cluster-launch-installer-console.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-custom-test-image.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
Labels: approved, lgtm, size/L

#4357 Add prow config for ironic-rhcos-downloader
  ci-operator/config/openshift/ironic-rhcos-downloader/OWNERS
  ci-operator/config/openshift/ironic-rhcos-downloader/openshift-ironic-rhcos-downloader-master.yaml
  ci-operator/config/openshift/ironic-rhcos-downloader/openshift-ironic-rhcos-downloader-release-4.2.yaml
  ci-operator/jobs/openshift/ironic-rhcos-downloader/OWNERS
  ci-operator/jobs/openshift/ironic-rhcos-downloader/openshift-ironic-rhcos-downloader-master-postsubmits.yaml
  ci-operator/jobs/openshift/ironic-rhcos-downloader/openshift-ironic-rhcos-downloader-master-presubmits.yaml
  ci-operator/jobs/openshift/ironic-rhcos-downloader/openshift-ironic-rhcos-downloader-release-4.2-postsubmits.yaml
  ci-operator/jobs/openshift/ironic-rhcos-downloader/openshift-ironic-rhcos-downloader-release-4.2-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#4600 Add the autoscaler-hpa image to Knative Serving.
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-next.yaml
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-next__variant.yaml
Labels: approved, lgtm, size/S

#4601 Use tide for ci-secret-mirroring-controller
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/XS

#4595 remove the yum-config-manager binary entirely to ensure no openshift dockerfiles rely on it
  ci-operator/config/openshift/images/openshift-images-master.yaml
Labels: approved, lgtm, size/XS

#4603 Use approve-plugin for ci-secret-mirroring-controller
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#4348 Add prow config for ironic-image
  ci-operator/config/openshift/ironic-image/OWNERS
  ci-operator/config/openshift/ironic-image/openshift-ironic-image-master.yaml
  ci-operator/config/openshift/ironic-image/openshift-ironic-image-release-4.2.yaml
  ci-operator/jobs/openshift/ironic-image/OWNERS
  ci-operator/jobs/openshift/ironic-image/openshift-ironic-image-master-postsubmits.yaml
  ci-operator/jobs/openshift/ironic-image/openshift-ironic-image-master-presubmits.yaml
  ci-operator/jobs/openshift/ironic-image/openshift-ironic-image-release-4.2-postsubmits.yaml
  ci-operator/jobs/openshift/ironic-image/openshift-ironic-image-release-4.2-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#4583 Add prowjobs for ci-secret-mirroring-controller
  ci-operator/config/openshift/ci-secret-mirroring-controller/OWNERS
  ci-operator/config/openshift/ci-secret-mirroring-controller/openshift-ci-secret-mirroring-controller-master.yaml
  ci-operator/jobs/openshift/ci-secret-mirroring-controller/OWNERS
  ci-operator/jobs/openshift/ci-secret-mirroring-controller/openshift-ci-secret-mirroring-controller-master-postsubmits.yaml
  ci-operator/jobs/openshift/ci-secret-mirroring-controller/openshift-ci-secret-mirroring-controller-master-presubmits.yaml
  core-services/supplemental-ci-images/README.md
  core-services/supplemental-ci-images/alpine_is.yaml
Labels: approved, lgtm, size/L

#4359 Add prow config for ironic-static-ip-manager
  ci-operator/config/openshift/ironic-static-ip-manager/OWNERS
  ci-operator/config/openshift/ironic-static-ip-manager/openshift-ironic-static-ip-manager-master.yaml
  ci-operator/config/openshift/ironic-static-ip-manager/openshift-ironic-static-ip-manager-release-4.2.yaml
  ci-operator/jobs/openshift/ironic-static-ip-manager/OWNERS
  ci-operator/jobs/openshift/ironic-static-ip-manager/openshift-ironic-static-ip-manager-master-postsubmits.yaml
  ci-operator/jobs/openshift/ironic-static-ip-manager/openshift-ironic-static-ip-manager-master-presubmits.yaml
  ci-operator/jobs/openshift/ironic-static-ip-manager/openshift-ironic-static-ip-manager-release-4.2-postsubmits.yaml
  ci-operator/jobs/openshift/ironic-static-ip-manager/openshift-ironic-static-ip-manager-release-4.2-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#4602 Remove verify-deps from ocm-o 4.1 branch
  ci-operator/config/openshift/cluster-openshift-controller-manager-operator/openshift-cluster-openshift-controller-manager-operator-release-4.1.yaml
  ci-operator/jobs/openshift/cluster-openshift-controller-manager-operator/openshift-cluster-openshift-controller-manager-operator-release-4.1-presubmits.yaml
Labels: approved, lgtm, size/M

#4604 cluster-monitoring-operator shellcheck should only be for master branch
  ci-operator/jobs/openshift/cluster-monitoring-operator/openshift-cluster-monitoring-operator-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#4552 update openshift/sdn OWNERS
  ci-operator/config/openshift/sdn/OWNERS
  ci-operator/jobs/openshift/sdn/OWNERS
Labels: approved, lgtm, size/M

#4607 Add an optional e2e-aws-multitenant test to cluster-network-operator
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-master.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-master-presubmits.yaml
Labels: approved, lgtm, size/M

#4609 Add OpenStack repos to Kuryr images
  ci-operator/config/openshift/kuryr-kubernetes/openshift-kuryr-kubernetes-master.yaml
  ci-operator/config/openshift/kuryr-kubernetes/openshift-kuryr-kubernetes-release-4.2.yaml
Labels: approved, lgtm, size/S

#4610 Adjust cluster-openshift-controller-manager-operator memory so it compiles
  ci-operator/config/openshift/cluster-openshift-controller-manager-operator/openshift-cluster-openshift-controller-manager-operator-master.yaml
  ci-operator/config/openshift/cluster-openshift-controller-manager-operator/openshift-cluster-openshift-controller-manager-operator-release-4.2.yaml
Labels: approved, lgtm, size/XS

#4612 enable owners-label for community-operators
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#4613 Make `e2e-libvirt` mandatory for libvirt provider
  ci-operator/jobs/openshift/cluster-api-provider-libvirt/openshift-cluster-api-provider-libvirt-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#4365 Add prow config for metal3-smart-exporter
  ci-operator/config/openshift/metal3-smart-exporter/OWNERS
  ci-operator/config/openshift/metal3-smart-exporter/openshift-metal3-smart-exporter-master.yaml
  ci-operator/config/openshift/metal3-smart-exporter/openshift-metal3-smart-exporter-release-4.2.yaml
  ci-operator/jobs/openshift/metal3-smart-exporter/OWNERS
  ci-operator/jobs/openshift/metal3-smart-exporter/openshift-metal3-smart-exporter-master-postsubmits.yaml
  ci-operator/jobs/openshift/metal3-smart-exporter/openshift-metal3-smart-exporter-master-presubmits.yaml
  ci-operator/jobs/openshift/metal3-smart-exporter/openshift-metal3-smart-exporter-release-4.2-postsubmits.yaml
  ci-operator/jobs/openshift/metal3-smart-exporter/openshift-metal3-smart-exporter-release-4.2-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#4615 Use centos as base image for secret-mirroring-controller
  ci-operator/config/openshift/ci-secret-mirroring-controller/openshift-ci-secret-mirroring-controller-master.yaml
Labels: approved, lgtm, size/S

#4331 Add GCP cluster type to e2e test templates
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
Labels: approved, lgtm, size/L

#4619 Rename the support operator to insights-operator
  ci-operator/config/openshift/insights-operator/OWNERS
  ci-operator/config/openshift/insights-operator/openshift-insights-operator-master.yaml
  ci-operator/config/openshift/insights-operator/openshift-insights-operator-release-4.2.yaml
  ci-operator/config/openshift/insights-operator/openshift-insights-operator-release-4.3.yaml
  ci-operator/jobs/openshift/insights-operator/OWNERS
  ci-operator/jobs/openshift/insights-operator/openshift-insights-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/insights-operator/openshift-insights-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/insights-operator/openshift-insights-operator-release-4.2-postsubmits.yaml
  ci-operator/jobs/openshift/insights-operator/openshift-insights-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/insights-operator/openshift-insights-operator-release-4.3-postsubmits.yaml
  ci-operator/jobs/openshift/insights-operator/openshift-insights-operator-release-4.3-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/M

#4606 Build cli-artifacts from oc repo
  ci-operator/config/openshift/oc/openshift-oc-master.yaml
Labels: approved, lgtm, size/XS

#4620 mirror: Remove support-operator from 4.1 mirroring, rename 4.2 repos
  core-services/image-mirroring/openshift/mapping_origin_4_1
  core-services/image-mirroring/openshift/mapping_origin_4_2
Labels: approved, lgtm, size/XS

#4622 Add a very small script to populate COMET correctly
  hack/comet.sh
Labels: approved, lgtm, size/S

#4623 Correct names for ironic images
  ci-operator/config/openshift/ironic-image/openshift-ironic-image-master.yaml
  ci-operator/config/openshift/ironic-image/openshift-ironic-image-release-4.2.yaml
  ci-operator/config/openshift/ironic-inspector-image/openshift-ironic-inspector-image-master.yaml
  ci-operator/config/openshift/ironic-inspector-image/openshift-ironic-inspector-image-release-4.2.yaml
Labels: approved, lgtm, size/XS

#4624 build applyconfig from ci-tools
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
Labels: approved, lgtm, size/XS

#4626 Base applyconfig jobs on an image built from ci-tools
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
Labels: approved, lgtm, size/S

#4631 ci-tools: add oc to applyconfig image
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
Labels: approved, size/XS

#4633 [06-08-2019 00:34:17] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/boskos.yaml
  cluster/ci/config/prow/openshift/boskos_reaper.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  hack/images.sh
Labels: approved, lgtm, size/L

#4634 Explicitly give deck the github token
  cluster/ci/config/prow/openshift/deck.yaml
Labels: approved, lgtm, size/XS

#4635 Mount the correct tokens into deck pods
  cluster/ci/config/prow/openshift/deck.yaml
Labels: approved, lgtm, size/S

#4636 [06-08-2019 03:59:00] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/boskos.yaml
  cluster/ci/config/prow/openshift/boskos_reaper.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  hack/images.sh
Labels: approved, lgtm, size/L

#4628 Promote cli-artifacts image from oc repo
  ci-operator/config/openshift/oc/openshift-oc-master.yaml
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
Labels: approved, lgtm, size/S

#4611 Add OpenStack base to 4.3 Kuryr
  ci-operator/config/openshift/kuryr-kubernetes/openshift-kuryr-kubernetes-release-4.3.yaml
Labels: approved, lgtm, size/S

#4629 openstack: Add FIP to apps port and DNS record for it
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e.yaml
Labels: approved, lgtm, size/S

#4632 Added vikaslaad to rerun_auth_config
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/XS

#4638 Make e2e-azure-operator CI job required for cluster-api-provider-azure and cluster-api-actuator-pkg
  ci-operator/config/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-master.yaml
  ci-operator/config/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-release-4.2.yaml
  ci-operator/config/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-release-4.3.yaml
  ci-operator/jobs/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-release-4.3-presubmits.yaml
Labels: approved, lgtm, size/L

#4639 Drop bazel from Azure jobs
  ci-operator/config/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-master.yaml
  ci-operator/config/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-release-4.2.yaml
  ci-operator/config/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-release-4.3.yaml
  ci-operator/jobs/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-release-4.3-presubmits.yaml
Labels: approved, lgtm, size/L

#4582 cluster-ingress-operator: add an optional job for e2e-azure
  ci-operator/config/openshift/cluster-ingress-operator/openshift-cluster-ingress-operator-master.yaml
  ci-operator/jobs/openshift/cluster-ingress-operator/openshift-cluster-ingress-operator-master-presubmits.yaml
Labels: approved, lgtm, size/M

#4642 make breaking changes job optional.
  ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#4535 ARO Add secret rotator job
  Makefile
  cluster/ci/config/prow/labels.yaml
  projects/azure/README.md
  projects/azure/azure-purge/cronjob.yaml
  projects/azure/azure-team-rbac.yaml
  projects/azure/cluster-wide.yaml
  projects/azure/rbac.yaml
  projects/azure/secret-refresh/secret-refresh.yaml
  projects/azure/token-refresh/token-refresh.yaml
Labels: approved, lgtm, sig/azure, size/L

#4630 Add support for rc5 of the operator in the CI system
  ci-operator/config/openshift/kubefed-operator/openshift-kubefed-operator-release-0.1.0-rc5.yaml
  ci-operator/jobs/openshift/kubefed-operator/openshift-kubefed-operator-release-0.1.0-rc5-postsubmits.yaml
  ci-operator/jobs/openshift/kubefed-operator/openshift-kubefed-operator-release-0.1.0-rc5-presubmits.yaml
  core-services/image-mirroring/kubefed/mapping_kubefed-v0_1_0_rc5_quay
Labels: approved, lgtm, size/L

#4644 [06-08-2019 17:08:07] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  hack/images.sh
Labels: approved, lgtm, size/L

#4645 Add the boskos metrics server and scrape it
  Makefile
  cluster/ci/config/prow/boskos.yaml
  cluster/ci/config/prow/openshift/boskos_metrics.yaml
  cluster/ci/config/prow/openshift/boskos_reaper.yaml
  cluster/ci/monitoring/Makefile
  cluster/ci/monitoring/boskos_service_monitor.yaml
Labels: approved, lgtm, size/M

#4647 Appropriately label the boskos metrics service for discovery
  cluster/ci/config/prow/openshift/boskos_metrics.yaml
Labels: approved, lgtm, size/XS

#4648 [06-08-2019 18:20:38] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/boskos_metrics.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  hack/images.sh
Labels: approved, lgtm, size/L

#4646 deck: correct indentation
  cluster/ci/config/prow/openshift/deck.yaml
Labels: approved, lgtm, size/S

#4627 Remove applyconfig from the repo
  Makefile
  tools/applyconfig/README.md
  tools/applyconfig/applyconfig.go
  tools/applyconfig/applyconfig_test.go
Labels: approved, lgtm, size/L

#4649 Reintroduce AWS Leasing
  ci-operator/templates/openshift/installer/cluster-launch-installer-console.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-custom-test-image.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
Labels: approved, lgtm, size/L

#4643 [gcp] Add gcloud sdk to test container for gcp e2e tests
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
Labels: approved, lgtm, size/S

#4651 Add a panel to the build-cop dashboard for quota leases
  cluster/ci/monitoring/build_cop.json
  cluster/ci/monitoring/mixins/grafana_dashboards/build_cop.jsonnet
Labels: approved, lgtm, size/L

#4650 Add ci for managed-velero-operator repo
  ci-operator/config/openshift/managed-velero-operator/OWNERS
  ci-operator/config/openshift/managed-velero-operator/openshift-managed-velero-operator-master.yaml
  ci-operator/jobs/openshift/managed-velero-operator/OWNERS
  ci-operator/jobs/openshift/managed-velero-operator/openshift-managed-velero-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/managed-velero-operator/openshift-managed-velero-operator-master-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#4621 remove obsolete community-operators tests
  ci-operator/config/operator-framework/community-operators/OWNERS
  ci-operator/config/operator-framework/community-operators/operator-framework-community-operators-master.yaml
  ci-operator/jobs/operator-framework/community-operators/OWNERS
  ci-operator/jobs/operator-framework/community-operators/operator-framework-community-operators-master-presubmits.yaml
Labels: approved, lgtm, size/L

#4652 azure: run verify commit and require it
  ci-operator/config/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-master.yaml
  ci-operator/config/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-release-4.2.yaml
  ci-operator/config/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-release-4.3.yaml
  ci-operator/jobs/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-release-4.3-presubmits.yaml
Labels: approved, lgtm, size/L

#4654 change golang version in ci-tools jobs
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
Labels: approved, lgtm, size/XS, ¯\_(ツ)_/¯

#4653 Update release next config
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next__variant.yaml
Labels: approved, lgtm, size/M

#4657 Setup HOME for glide cache
  ci-operator/config/openshift/library-go/openshift-library-go-master.yaml
  ci-operator/config/openshift/library-go/openshift-library-go-release-4.1.yaml
  ci-operator/config/openshift/library-go/openshift-library-go-release-4.2.yaml
  ci-operator/config/openshift/library-go/openshift-library-go-release-4.3.yaml
Labels: approved, lgtm, size/XS

#4598 Add new optional release blocking jobs for GCP and Azure
  ci-operator/infra/openshift/release-controller/releases/release-ocp-4.2.json
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
Labels: approved, lgtm, size/L

#4661 Auto-update SIG Azure OWNERS files
  ci-operator/config/openshift/openshift-azure/OWNERS
  ci-operator/jobs/openshift/openshift-azure/OWNERS
  ci-operator/templates/openshift/openshift-azure/OWNERS
Labels: approved, lgtm, sig/azure, size/S

#4663 Allow 10G of memory for ci-tools builds
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
Labels: approved, lgtm, size/XS

#4665 Add managed-cluster-config to tide query for master branch
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/XS

#4658 Require leases for scaleup tests
  ci-operator/templates/openshift/openshift-ansible/cluster-scaleup-e2e-40.yaml
Labels: approved, lgtm, size/M

#4667 disable branch protection for community operators
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/XS

#4670 openshift/cluster-autoscaler-operator: add GCP periodic job
  ci-operator/jobs/openshift/cluster-autoscaler-operator/openshift-cluster-autoscaler-operator-periodics.yaml
Labels: approved, lgtm, size/M

#4666 Add knative-eventing-v0.8.0 release to CI, Image Mirroring
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.8.0.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.8.0-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.8.0-presubmits.yaml
  core-services/image-mirroring/knative/mapping_knative_v0_8_quay
Labels: approved, lgtm, size/L

#4671 Upstream removed images release-next
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next__variant.yaml
Labels: approved, lgtm, size/M

#4675 [08-08-2019 15:41:26] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/boskos.yaml
  cluster/ci/config/prow/openshift/boskos_metrics.yaml
  cluster/ci/config/prow/openshift/boskos_reaper.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  hack/images.sh
Labels: approved, lgtm, size/L

#4673 update upstream go repo to knative-eventing move to knative.dev
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next__variant.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-next-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-next-presubmits.yaml
Labels: approved, lgtm, size/S

#4676 [08-08-2019 17:09:13] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  hack/images.sh
Labels: approved, lgtm, size/L

#4678 Change canary release informers from origin to ocp
  ci-operator/infra/openshift/release-controller/releases/release-ocp-4.2.json
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
Labels: approved, lgtm, size/M

#4679 Add a panel to show IPI-deprovision failures
  cluster/ci/monitoring/build_cop.json
  cluster/ci/monitoring/mixins/grafana_dashboards/build_cop.jsonnet
Labels: approved, lgtm, size/L

#4660 Add e2e-gcp as an optional job to origin
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
Labels: approved, lgtm, size/M

#4680 Make smaller and more precise queries for Prow usage
  cluster/ci/monitoring/mixins/grafana_dashboards/prow.jsonnet
  cluster/ci/monitoring/prow.json
Labels: approved, lgtm, size/XL

#4681 Alert when ipi-deprovision fails
  cluster/ci/monitoring/mixins/prometheus/build_cop_alerts.libsonnet
  cluster/ci/monitoring/prometheus_rule_prow.yaml
Labels: approved, lgtm, size/S

#4682 Add apavel to ci-admins role
  cluster/ci/config/roles.yaml
Labels: approved, lgtm, size/XS

#4591 Phase 1 proxy testing
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
Labels: approved, lgtm, size/M

#4683 ci/roles: apavel -> AlexNPavel
  cluster/ci/config/roles.yaml
Labels: size/XS

#4672 ci-operator: add openshift/loki build
  ci-operator/config/openshift/loki/OWNERS
  ci-operator/config/openshift/loki/openshift-loki-master.yaml
  ci-operator/config/openshift/loki/openshift-loki-release-4.2.yaml
  ci-operator/config/openshift/loki/openshift-loki-release-4.3.yaml
  ci-operator/jobs/openshift/loki/OWNERS
  ci-operator/jobs/openshift/loki/openshift-loki-master-postsubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-master-presubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-release-4.2-postsubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-release-4.3-postsubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-release-4.3-presubmits.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#4668 Get real status of e2e-openstack install task
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e.yaml
Labels: approved, lgtm, size/XS

#4687 Going back to original job names...
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.8.0.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.8.0-presubmits.yaml
Labels: approved, lgtm, size/S

#4677 [gcp] Fix installer-src template GCP region
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
Labels: approved, lgtm, size/S

#4565 Openstack must gather
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e.yaml
Labels: approved, lgtm, size/S

#4689 Add e2e gcp operator
  ci-operator/config/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-master.yaml
  ci-operator/config/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-release-4.2.yaml
  ci-operator/config/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-release-4.3.yaml
  ci-operator/jobs/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-release-4.3-presubmits.yaml
Labels: approved, lgtm, size/L

#4690 infra: add a periodic check for OWNERS file presence
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm, size/M

#4691 cluster-api-provider-gcp: add e2e-gcp-operator job
  ci-operator/config/openshift/cluster-api-provider-gcp/openshift-cluster-api-provider-gcp-master.yaml
  ci-operator/config/openshift/cluster-api-provider-gcp/openshift-cluster-api-provider-gcp-release-4.2.yaml
  ci-operator/config/openshift/cluster-api-provider-gcp/openshift-cluster-api-provider-gcp-release-4.3.yaml
  ci-operator/jobs/openshift/cluster-api-provider-gcp/openshift-cluster-api-provider-gcp-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-gcp/openshift-cluster-api-provider-gcp-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-gcp/openshift-cluster-api-provider-gcp-release-4.3-presubmits.yaml
Labels: approved, lgtm, size/L

#4692 Use prowjob_state_transitions metric in ipi-deprovision panel and alert
  cluster/ci/monitoring/build_cop.json
  cluster/ci/monitoring/mixins/grafana_dashboards/build_cop.jsonnet
  cluster/ci/monitoring/mixins/prometheus/build_cop_alerts.libsonnet
  cluster/ci/monitoring/prometheus_rule_prow.yaml
Labels: approved, lgtm, size/S

#4696 Run make verify job for image-registry
  ci-operator/config/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-master.yaml
  ci-operator/config/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-release-4.1.yaml
  ci-operator/config/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-release-4.2.yaml
  ci-operator/config/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-release-4.3.yaml
  ci-operator/jobs/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-release-4.3-presubmits.yaml
Labels: approved, lgtm, size/L

#4694 Add a make target for generating jobs
  Makefile
  hack/validate-generated-config.sh
Labels: approved, lgtm, size/XS

#4662 ci-operator: add operator-sdk e2e subcommand tests
  ci-operator/config/operator-framework/operator-sdk/operator-framework-operator-sdk-master.yaml
  ci-operator/jobs/operator-framework/operator-sdk/operator-framework-operator-sdk-master-presubmits.yaml
Labels: approved, lgtm, size/M

#4699 Add quota leasing to all jobs
  ci-operator/templates/openshift/installer/cluster-launch-installer-console.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-custom-test-image.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-scaleup-e2e-40.yaml
  cluster/ci/config/prow/boskos.yaml
  cluster/ci/config/prow/openshift/boskos_metrics.yaml
  cluster/ci/config/prow/openshift/boskos_reaper.yaml
  cluster/ci/monitoring/build_cop.json
  cluster/ci/monitoring/mixins/grafana_dashboards/build_cop.jsonnet
Labels: approved, lgtm, size/L

#4700 Add configMap grafana-dashboard-dptp for prow-monitoring
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#4701 Move ipi-deprovision panel to its own board
  cluster/ci/monitoring/build_cop.json
  cluster/ci/monitoring/dptp.json
  cluster/ci/monitoring/grafana_deploy.yaml
  cluster/ci/monitoring/mixins/Makefile
  cluster/ci/monitoring/mixins/config.libsonnet
  cluster/ci/monitoring/mixins/grafana_dashboards/build_cop.jsonnet
  cluster/ci/monitoring/mixins/grafana_dashboards/dptp.jsonnet
  cluster/ci/monitoring/mixins/grafana_dashboards/jenkins_operator.jsonnet
  cluster/ci/monitoring/mixins/prometheus/build_cop_alerts.libsonnet
  cluster/ci/monitoring/mixins/prometheus/dptp.libsonnet
  cluster/ci/monitoring/mixins/prometheus/prometheus.libsonnet
  cluster/ci/monitoring/prometheus_rule_prow.yaml
Labels: approved, lgtm, size/L

#4693 Add test to validate ci-tools' vendor
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
  ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
Labels: approved, lgtm, size/M

#4704 reflecting latest changes from eventing-contrib's master and renamings
  ci-operator/config/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-next.yaml
  ci-operator/config/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-next__variant.yaml
  ci-operator/jobs/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-next-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-next-presubmits.yaml
Labels: approved, lgtm, size/L

#4640 config/openshift/installer: add baremetal-installer image
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
Labels: approved, lgtm, size/S

#4608 Fix cluster-network-operator e2e-aws-multitenant job
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-master.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/sdn/openshift-sdn-master-presubmits.yaml
Labels: approved, lgtm, size/M

#4669 ci-operator/jobs/openshift/machine-api-operator: add e2e-azure-operator
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-master.yaml
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-release-4.2.yaml
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-release-4.3.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-release-4.3-presubmits.yaml
Labels: approved, lgtm, size/L

#4709 Run the config bootstrapper more often
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
Labels: approved, lgtm, size/XS

#4710 fix master core apply periodic job
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
Labels: approved, lgtm, size/XS

#4711 openshift-release-release-4.2-periodics.yaml: increase cadence for azure and gcp jobs to every 4hrs
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
Labels: approved, lgtm

#4718 [12-08-2019 20:47:33] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  hack/images.sh
Labels: approved, lgtm, size/L

#4703 [gcp] Fix ssh user for e2e template
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
Labels: approved, lgtm, size/XS

#4720 Revert "config/openshift/installer: add baremetal-installer image"
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
Labels: approved, lgtm, size/S

#4723 Split off resource leases into separate dashboard
  cluster/ci/monitoring/Makefile
  cluster/ci/monitoring/boskos.json
  cluster/ci/monitoring/build_cop.json
  cluster/ci/monitoring/mixins/Makefile
  cluster/ci/monitoring/mixins/config.libsonnet
  cluster/ci/monitoring/mixins/grafana_dashboards/boskos.jsonnet
  cluster/ci/monitoring/mixins/grafana_dashboards/build_cop.jsonnet
Labels: approved, lgtm, size/XXL

#4725 Add boskos configMap used by grafana
  cluster/ci/config/prow/plugins.yaml
  cluster/ci/monitoring/grafana_deploy.yaml
Labels: approved, lgtm, size/XS

#4717 Fix Disk Usage in ghproxy board
  cluster/ci/monitoring/ghproxy.json
  cluster/ci/monitoring/mixins/grafana_dashboards/ghproxy.jsonnet
Labels: approved, lgtm, size/M

#4724 Add the commands for dptp in prow-monitoring Makefile
  cluster/ci/monitoring/Makefile
Labels: approved, lgtm, size/XS

#4697 Add verify ci job to image-registry repo
  ci-operator/config/openshift/image-registry/openshift-image-registry-master.yaml
  ci-operator/config/openshift/image-registry/openshift-image-registry-release-4.1.yaml
  ci-operator/config/openshift/image-registry/openshift-image-registry-release-4.2.yaml
  ci-operator/config/openshift/image-registry/openshift-image-registry-release-4.3.yaml
  ci-operator/jobs/openshift/image-registry/openshift-image-registry-master-presubmits.yaml
  ci-operator/jobs/openshift/image-registry/openshift-image-registry-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/image-registry/openshift-image-registry-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/image-registry/openshift-image-registry-release-4.3-presubmits.yaml
Labels: approved, lgtm, size/L

#4713 add promotion step for cluster-monitoring-operator v3.11
  ci-operator/config/openshift/cluster-monitoring-operator/openshift-cluster-monitoring-operator-release-3.11.yaml
  ci-operator/jobs/openshift/cluster-monitoring-operator/openshift-cluster-monitoring-operator-release-3.11-postsubmits.yaml
Labels: approved, lgtm, size/M

#4726 add view to azure-team
  projects/azure/rbac.yaml
Labels: approved, lgtm, sig/azure, size/S

#4727 aro clean ci-image
  projects/azure/base-images/ci-base.yaml
Labels: approved, lgtm, sig/azure, size/S

#4081 Remove csi-driver-registrar jobs
  ci-operator/config/openshift/csi-driver-registrar/openshift-csi-driver-registrar-master.yaml
  ci-operator/config/openshift/csi-driver-registrar/openshift-csi-driver-registrar-release-4.2.yaml
  ci-operator/config/openshift/csi-driver-registrar/openshift-csi-driver-registrar-release-4.3.yaml
  ci-operator/jobs/openshift/csi-driver-registrar/openshift-csi-driver-registrar-master-postsubmits.yaml
  ci-operator/jobs/openshift/csi-driver-registrar/openshift-csi-driver-registrar-master-presubmits.yaml
  ci-operator/jobs/openshift/csi-driver-registrar/openshift-csi-driver-registrar-release-4.2-postsubmits.yaml
  ci-operator/jobs/openshift/csi-driver-registrar/openshift-csi-driver-registrar-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/csi-driver-registrar/openshift-csi-driver-registrar-release-4.3-postsubmits.yaml
  ci-operator/jobs/openshift/csi-driver-registrar/openshift-csi-driver-registrar-release-4.3-presubmits.yaml
  core-services/image-mirroring/openshift/mapping_origin_4_2
Labels: approved, lgtm, size/XL

#4695 Adding additional optional ci jobs
  ci-operator/config/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-master.yaml
  ci-operator/config/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-release-4.1.yaml
  ci-operator/config/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-release-4.2.yaml
  ci-operator/config/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-release-4.3.yaml
  ci-operator/jobs/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-release-4.3-presubmits.yaml
Labels: approved, lgtm, size/XXL

#4729 config/openshift/installer: reinstate baremetal-installer image
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
Labels: approved, lgtm, size/S

#4714 templates/openshift: add build id to invoker
  ci-operator/templates/openshift/installer/cluster-launch-installer-console.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-custom-test-image.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-libvirt-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-metal-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-scaleup-e2e-40.yaml
Labels: approved, lgtm, size/M

#4730 Add upgrade-v7.0 job to openshift-azure presubmits
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/S

#4733 config/openshift/installer: add baremetal-installer to 4.2
  ci-operator/config/openshift/installer/openshift-installer-release-4.2.yaml
Labels: approved, lgtm, size/S

#4735 templates: set multizone true for gcp test
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
Labels: approved, lgtm, size/XS

#4736 aro - add missing binaries
  projects/azure/base-images/ci-base.yaml
Labels: approved, lgtm, sig/azure, size/XS

#4738 Make codecov jobs not blocking
  cluster/ci/config/prow/config.yaml
Labels: approved, lgtm, size/XS

#4740 upgrade stage grafana to 6.3.2
  cluster/ci/monitoring/debug/grafana_deploy.yaml
Labels: approved, lgtm, size/XS

#4742 Revert "upgrade stage grafana to 6.3.2"
  cluster/ci/monitoring/debug/grafana_deploy.yaml
Labels: approved, lgtm, size/XS

#4743 Adding support for contrib_081 branch
  ci-operator/config/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-v0.8.1.yaml
  ci-operator/jobs/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-v0.8.1-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-v0.8.1-presubmits.yaml
Labels: approved, lgtm, size/L

#4739 mirror: add baremetal-installer image mapping
  core-services/image-mirroring/openshift/mapping_origin_4_2
Labels: approved, lgtm, size/XS

#4279 rhel scaleup: update other repos
  ci-operator/config/openshift/installer/OWNERS
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.1.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.2.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.3.yaml
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-master.yaml
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-release-4.1.yaml
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-release-4.2.yaml
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-release-4.3.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-master.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.1.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.2.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.3.yaml
  ci-operator/jobs/openshift/installer/OWNERS
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.3-presubmits.yaml
  ci-operator/templates/openshift/installer/OWNERS
Labels: approved, lgtm, size/M

#4707 Add panel of token usage into ghproxy board
  cluster/ci/monitoring/ghproxy.json
  cluster/ci/monitoring/mixins/grafana_dashboards/ghproxy.jsonnet
Labels: approved, lgtm, size/XL

#4715 service-ca-operator: run make verify
  ci-operator/config/openshift/service-ca-operator/openshift-service-ca-operator-master.yaml
  ci-operator/config/openshift/service-ca-operator/openshift-service-ca-operator-release-4.2.yaml
  ci-operator/config/openshift/service-ca-operator/openshift-service-ca-operator-release-4.3.yaml
  ci-operator/jobs/openshift/service-ca-operator/openshift-service-ca-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/service-ca-operator/openshift-service-ca-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/service-ca-operator/openshift-service-ca-operator-release-4.3-presubmits.yaml
Labels: approved, lgtm, size/L

#4746 [14-08-2019 20:54:12] Bumping Prow component images
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
  cluster/ci/config/prow/config.yaml
  cluster/ci/config/prow/openshift/adapter_imagestreams.yaml
  cluster/ci/config/prow/openshift/artifact-uploader.yaml
  cluster/ci/config/prow/openshift/cherrypick.yaml
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  cluster/ci/config/prow/openshift/deck.yaml
  cluster/ci/config/prow/openshift/ghproxy.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/horologium.yaml
  cluster/ci/config/prow/openshift/jenkins_operator.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/refresh.yaml
  cluster/ci/config/prow/openshift/sinker.yaml
  cluster/ci/config/prow/openshift/statusreconciler.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  cluster/ci/config/prow/openshift/tot.yaml
  hack/images.sh
Labels: approved, lgtm, size/L

#4745 plugins: add configmap for canary grafana dashboard
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#4722 monitoring: add release informing jobs dashboard
  cluster/ci/monitoring/Makefile
  cluster/ci/monitoring/canary.json
  cluster/ci/monitoring/grafana_deploy.yaml
  cluster/ci/monitoring/mixins/Makefile
  cluster/ci/monitoring/mixins/config.libsonnet
  cluster/ci/monitoring/mixins/grafana_dashboards/canary.jsonnet
Labels: approved, lgtm, size/L

#4747 Update Bugzilla configuration
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#4749 Fix filename: dptp_alerts.libsonnet
  cluster/ci/monitoring/mixins/prometheus/dptp_alerts.libsonnet
  cluster/ci/monitoring/mixins/prometheus/prometheus.libsonnet
Labels: approved, lgtm, size/XS

#4751 Grafana stage upgrade
  cluster/ci/monitoring/debug/grafana_deploy.yaml
Labels: approved, lgtm, size/XS

#4752 Adding contrib sources
  core-services/image-mirroring/knative/mapping_knative_v0_8_quay
Labels: approved, lgtm, size/S

#4737 Azure actuator CI: accomodate the latest changes in Makefile
  ci-operator/config/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-master.yaml
  ci-operator/config/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-release-4.2.yaml
  ci-operator/config/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-release-4.3.yaml
Labels: approved, lgtm, size/M

#4753 Fixing incorrect promotion name of eventing-contrib imagez :fire:
  ci-operator/config/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-v0.8.1.yaml
Labels: approved, lgtm, size/XS

#4754 Adding Kafka CCP images
  ci-operator/config/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-v0.8.1.yaml
Labels: approved, lgtm, size/S

#4756 Update legends on lease dashboards
  cluster/ci/monitoring/boskos.json
  cluster/ci/monitoring/mixins/grafana_dashboards/boskos.jsonnet
Labels: approved, lgtm, size/M

#4728 ci-operator e2e template jobs dashboard
  cluster/ci/monitoring/e2e_template_jobs.json
  cluster/ci/monitoring/mixins/config.libsonnet
  cluster/ci/monitoring/mixins/grafana_dashboards/e2e_template_jobs.jsonnet
Labels: approved, lgtm, size/L

#4759 add e2e template jobs dashboard configmap
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#4757 Bump golang version for operator-sdk builds
  ci-operator/config/openshift/ocp-release-operator-sdk/openshift-ocp-release-operator-sdk-master.yaml
Labels: approved, lgtm, size/XS

#4760 fix e2e template jobs dashboard in config updater
  cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#4731 Add alerts for ghproxy
  cluster/ci/monitoring/mixins/prometheus/ghproxy_alerts.libsonnet
  cluster/ci/monitoring/mixins/prometheus/prometheus.libsonnet
  cluster/ci/monitoring/prometheus_rule_prow.yaml
Labels: approved, lgtm, size/M

#4761 Enable gomod in sanity check for ocp-operator-sdk
  ci-operator/config/openshift/ocp-release-operator-sdk/openshift-ocp-release-operator-sdk-master.yaml
Labels: approved, lgtm, size/XS

#4763 Fix ghproxy-status-code-abnormal-%sXX alert
  cluster/ci/monitoring/mixins/prometheus/ghproxy_alerts.libsonnet
  cluster/ci/monitoring/prometheus_rule_prow.yaml
Labels: approved, lgtm, size/S

#4765 Setup for 082 branch
  ci-operator/config/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-v0.8.2.yaml
  ci-operator/jobs/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-v0.8.2-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-v0.8.2-presubmits.yaml
Labels: approved, lgtm, size/L

#4758 Update azure presubmit tests
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v7-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/M

#4764 mount e2e template jobs dashboard to grafana
  cluster/ci/monitoring/grafana_deploy.yaml
Labels: approved, lgtm, size/XS

#4766 Adding 082 contrib images
  core-services/image-mirroring/knative/mapping_knative_v0_8_quay
Labels: approved, lgtm, size/S

#4755 Route tide ghv4 traffic to ghproxy
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  cluster/ci/config/prow/openshift/hook.yaml
  cluster/ci/config/prow/openshift/needs_rebase.yaml
  cluster/ci/config/prow/openshift/plank.yaml
  cluster/ci/config/prow/openshift/tide.yaml
  core-services/ci-chat-bot/deploy.yaml
Labels: approved, lgtm, size/XS
