Repository openshift/release, pull requests merged in 2020-09, with the labels that each got.

#11379 fast-forward registration - disable 2.1 promotion
  ci-operator/config/open-cluster-management/registration/open-cluster-management-registration-release-2.1.yaml
Labels: approved, lgtm

#11478 temporarily do not require vsphere-dry to pass
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
Labels: approved, lgtm

#11477 prow: temporarily remove vsphere from prow-cm
  clusters/app.ci/prow/03_deployment/prow-controller-manager.yaml
Labels: approved, lgtm

#11446 OpenStack: gather nova logs for all provisioned servers
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-upi-e2e.yaml
Labels: approved, lgtm

#11456 Exclude failing tests because of hardcoded arch
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
Labels: approved, lgtm

#11461 Update apiserver-library-go master to use golang 1.14
  ci-operator/config/openshift/apiserver-library-go/openshift-apiserver-library-go-master.yaml
Labels: approved, lgtm

#11464 fast-forward registration - master promote 2.1
  ci-operator/config/open-cluster-management/registration/open-cluster-management-registration-master.yaml
  ci-operator/jobs/open-cluster-management/registration/open-cluster-management-registration-master-postsubmits.yaml
Labels: approved, lgtm

#11466 Remove config for deleted image
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next__45.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next__46.yaml
Labels: approved, lgtm

#11474 OKD promotion: remove 4.5 beta repo
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.6-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml
Labels: approved, lgtm

#11482 config/cluster-etcd-operator: bump build_root to 1.14
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-master.yaml
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.6.yaml
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.7.yaml
Labels: approved, lgtm

#11262 chore: Add test image build configuration
  ci-operator/config/openshift/knative-client/openshift-knative-client-release-next__45.yaml
  core-services/image-mirroring/knative/mapping_knative_nightly_quay
Labels: approved, lgtm

#11489 Add CI to oc-4.5-kubernetes-1.18.8 branch
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-oc-4.5-kubernetes-1.18.8.yaml
  ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-oc-4.5-kubernetes-1.18.8-presubmits.yaml
Labels: approved, lgtm

#11488 Add an OAuth token in the gcsweb-private deployment.
  clusters/app.ci/prow/03_deployment/gcsweb-private.yaml
  core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#11476 bp: disable for kubevirt/kubevirt-ssp-operator@master
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#11475 add different gcs browser prefix for the private org
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#11495 Bumping to the 4.6:tests image to pick up the latest version of oc
  core-services/release-controller/deploy-ocp-controller.yaml
  core-services/release-controller/deploy-ocp-ppc64le-controller.yaml
  core-services/release-controller/deploy-ocp-ppc64le-priv-controller.yaml
  core-services/release-controller/deploy-ocp-priv-controller.yaml
  core-services/release-controller/deploy-ocp-s390x-controller.yaml
  core-services/release-controller/deploy-ocp-s390x-priv-controller.yaml
  hack/generators/release-controllers/content/redirect_and_files_cache_resources.py
Labels: approved, lgtm

#11493 Testgrid: Add an allow-list to replace release-type annotation
  core-services/testgrid-config-generator/OWNERS
  core-services/testgrid-config-generator/README.md
  core-services/testgrid-config-generator/_allow-list.yaml
Labels: approved, lgtm

#11499 ci-release* namespace cleanup
  clusters/app.ci/prow/03_deployment/00_namespaces.yaml
  clusters/build-clusters/common/00_namespaces.yaml
  core-services/secret-mirroring/_mapping.yaml
Labels: approved, lgtm

#11453 Bug 1874252: pinning image to rhcos 4.5 for step registry proxy config
  ci-operator/step-registry/ipi/conf/aws/proxy/ipi-conf-aws-proxy-ref.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#11496 rename the gcsweb private oauth token secret
  clusters/app.ci/prow/03_deployment/gcsweb-private.yaml
  core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#11485 Revert "temporarily do not require vsphere-dry to pass"
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
Labels: approved, lgtm

#11486 Revert "prow: temporarily remove vsphere from prow-cm"
  clusters/app.ci/prow/03_deployment/prow-controller-manager.yaml
Labels: approved, lgtm

#11511 Revert "Bumping to the 4.6:tests image to pick up the latest version of oc"
  core-services/release-controller/deploy-ocp-controller.yaml
  core-services/release-controller/deploy-ocp-ppc64le-controller.yaml
  core-services/release-controller/deploy-ocp-ppc64le-priv-controller.yaml
  core-services/release-controller/deploy-ocp-priv-controller.yaml
  core-services/release-controller/deploy-ocp-s390x-controller.yaml
  core-services/release-controller/deploy-ocp-s390x-priv-controller.yaml
  hack/generators/release-controllers/content/redirect_and_files_cache_resources.py
Labels: approved, lgtm

#11501 Use cluster_groups in secret tool's config
  core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#11512 Build0{1,2}: Make audit log indexable
  clusters/build-clusters/01_cluster/openshift/api_audit_log/vector-audit-log-config_configmap.yaml
  clusters/build-clusters/01_cluster/openshift/api_audit_log/vector-audit-log_daemonset.yaml
  clusters/build-clusters/02_cluster/openshift/api_audit_log/vector-audit-log-config_configmap.yaml
  clusters/build-clusters/02_cluster/openshift/api_audit_log/vector-audit-log_daemonset.yaml
Labels: approved, lgtm

#11513 Apply pidsLimit=-1 to all workers
  clusters/build-clusters/02_cluster/openshift-machine-api/pthread-debug_machineset.yaml
  clusters/build-clusters/02_cluster/openshift-machine-api/pthread-debug_mcp.yaml
  clusters/build-clusters/02_cluster/openshift-machine-api/set-pids-limit_crc.yaml
Labels: approved, lgtm

#11103 add prow configuration for cluster-baremetal-operator repository
  ci-operator/config/openshift/cluster-baremetal-operator/OWNERS
  ci-operator/config/openshift/cluster-baremetal-operator/openshift-cluster-baremetal-operator-master.yaml
  ci-operator/jobs/openshift/cluster-baremetal-operator/OWNERS
  ci-operator/jobs/openshift/cluster-baremetal-operator/openshift-cluster-baremetal-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-baremetal-operator/openshift-cluster-baremetal-operator-master-presubmits.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#11514 Boskos: Fix repository
  clusters/app.ci/prow/03_deployment/boskos.yaml
  clusters/app.ci/prow/03_deployment/boskos_cleaner.yaml
  clusters/app.ci/prow/03_deployment/boskos_reaper.yaml
  core-services/prow/03_deployment/adapter_imagestreams.yaml
  core-services/prow/03_deployment/boskos.yaml
  core-services/prow/03_deployment/boskos_cleaner.yaml
  core-services/prow/03_deployment/boskos_reaper.yaml
Labels: approved, lgtm

#11521 OpenStack: Mark openstack job optional in CIRO
  ci-operator/jobs/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-master-presubmits.yaml
Labels: approved, lgtm

#11517 fast-forward work
  ci-operator/config/open-cluster-management/work/open-cluster-management-work-master.yaml
  ci-operator/config/open-cluster-management/work/open-cluster-management-work-release-2.1.yaml
  ci-operator/jobs/open-cluster-management/work/open-cluster-management-work-master-postsubmits.yaml
Labels: approved, lgtm

#11524 Drop `--lease-server=` from upgrade and cluster-bot jobs
  ci-operator/jobs/openshift/release/openshift-release-infra-periodics.yaml
Labels: approved, lgtm

#11518 core-services/prow/02_config/_config: Highlight Boskos lease failures
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#11525 Change to build from Dockerfile.rhel7
  ci-operator/config/openshift/cluster-openshift-apiserver-operator/openshift-cluster-openshift-apiserver-operator-master.yaml
Labels: approved, lgtm

#11520 oVirt: use boskosctl command
  ci-operator/templates/openshift/installer/cluster-launch-installer-ovirt-e2e.yaml
Labels: approved, lgtm

#11534 vsphere - Increase disk space
  ci-operator/step-registry/ipi/conf/vsphere/ipi-conf-vsphere-commands.sh
Labels: approved, lgtm

#11527 Remove boskos redirect on api.ci
  core-services/prow/03_deployment/admin_boskos_rbac.yaml
  core-services/prow/03_deployment/boskos-redirect.yaml
Labels: approved, lgtm

#11542 revert quoted things
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#10233 oVirt e2e: add ovirt-csi-driver{,-operator} tests suite
  ci-operator/jobs/openshift/ovirt-csi-driver-operator/openshift-ovirt-csi-driver-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/ovirt-csi-driver-operator/openshift-ovirt-csi-driver-operator-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/ovirt-csi-driver-operator/openshift-ovirt-csi-driver-operator-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/ovirt-csi-driver/openshift-ovirt-csi-driver-master-presubmits.yaml
  ci-operator/jobs/openshift/ovirt-csi-driver/openshift-ovirt-csi-driver-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/ovirt-csi-driver/openshift-ovirt-csi-driver-release-4.7-presubmits.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-ovirt-e2e.yaml
Labels: approved, lgtm

#11490 Adding our own CI run for the fork of the Knative Operator 0.17 release
  ci-operator/config/openshift-knative/operator/openshift-knative-operator-release-0.17.yaml
  ci-operator/jobs/openshift-knative/operator/openshift-knative-operator-release-0.17-postsubmits.yaml
  ci-operator/jobs/openshift-knative/operator/openshift-knative-operator-release-0.17-presubmits.yaml
Labels: approved, lgtm

#11333 Create a new GCP upgrade workflow w/ Loki collector and use it in CVO upgrade tests
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-master.yaml
  ci-operator/step-registry/metadata.json
  ci-operator/step-registry/openshift/e2e/test/openshift-e2e-test-commands.sh
  ci-operator/step-registry/openshift/e2e/test/openshift-e2e-test-ref.yaml
  ci-operator/step-registry/openshift/upgrade/gcp/OWNERS
  ci-operator/step-registry/openshift/upgrade/gcp/loki/OWNERS
  ci-operator/step-registry/openshift/upgrade/gcp/loki/openshift-upgrade-gcp-loki-workflow.yaml
Labels: approved, lgtm

#11536 Bootstrap openshift-config/pull-secret on build clusters
  core-services/ci-secret-bootstrap/_config.yaml
  core-services/ci-secret-bootstrap/openshift-config_namespace.yaml
Labels: approved, lgtm

#10919 Add optional on-demand e2e-aws job to origin master
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
Labels: approved, lgtm

#11522 Revert "OpenStack: Mark openstack job optional in CIRO"
  ci-operator/jobs/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-master-presubmits.yaml
Labels: approved, lgtm

#11509 steps/workers-rhel7: Wait for cluster to stabilize
  ci-operator/step-registry/workers-rhel7/scaleup/workers-rhel7-scaleup-commands.sh
Labels: approved, lgtm

#11558 Update CAO master to golang 1.14
  ci-operator/config/openshift/cluster-authentication-operator/openshift-cluster-authentication-operator-master.yaml
Labels: approved, lgtm

#11556 Separating out proxy deprovision from gather to ensure tear down can occur
  ci-operator/step-registry/gather/proxy/gather-proxy-commands.sh
  ci-operator/step-registry/gather/proxy/gather-proxy-ref.yaml
  ci-operator/step-registry/ipi/aws/post/proxy/ipi-aws-post-proxy-chain.yaml
  ci-operator/step-registry/ipi/deprovision/proxy/OWNERS
  ci-operator/step-registry/ipi/deprovision/proxy/ipi-deprovision-proxy-commands.sh
  ci-operator/step-registry/ipi/deprovision/proxy/ipi-deprovision-proxy-ref.yaml
  ci-operator/step-registry/metadata.json
Labels: approved, lgtm

#10875 Fixing openshift-jenkins-master.yaml to use dockerfile from ocp-build-data
  ci-operator/config/openshift/jenkins/openshift-jenkins-master.yaml
Labels: approved

#10852 Fixing kube-reporting-metering-operator-master.yaml to use dockerfile from ocp-build-data
  ci-operator/config/kube-reporting/metering-operator/kube-reporting-metering-operator-master.yaml
Labels: approved, lgtm

#11516 fast-forward foundation
  ci-operator/config/open-cluster-management/multicloud-operators-foundation/open-cluster-management-multicloud-operators-foundation-release-2.1.yaml
Labels: approved, lgtm

#11563 ci-operator/config/openshift/release/openshift-release-master__ocp-4.4: Return to 4.4 upi-installer
  ci-operator/config/openshift/release/openshift-release-master__ocp-4.4.yaml
Labels: approved, lgtm

#11573 enable servicemesh integration tests in serverless-operator tests
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master__4.5-azure.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master__4.5-gcp.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master__4.5-vsphere.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master__4.5.yaml
Labels: approved, lgtm

#11571 promecieus: remove ImageChange trigger in buildconfig
  services/promecieus/03-buildconfig-src.yaml
Labels: approved, lgtm

#11543 router e2e-metal-ipi add dev-scripts image base definition
  ci-operator/config/openshift/router/openshift-router-master.yaml
  ci-operator/config/openshift/router/openshift-router-release-4.6.yaml
  ci-operator/config/openshift/router/openshift-router-release-4.7.yaml
Labels: approved, lgtm

#11584 build oauth-{proxy,server} with golang-1.14
  ci-operator/config/openshift/oauth-proxy/openshift-oauth-proxy-master.yaml
  ci-operator/config/openshift/oauth-server/openshift-oauth-server-master.yaml
Labels: approved, lgtm

#11540 temporarily disable bugzilla requirement for cluster-baremetal-operator
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#11589 OpenStack: Reduce quota slice for Vexxhost
  core-services/prow/02_config/_boskos.yaml
Labels: approved, lgtm

#11593 oauth-apiserver: bump golang to 1.14
  ci-operator/config/openshift/oauth-apiserver/openshift-oauth-apiserver-master.yaml
Labels: approved, lgtm

#11562 services/ocs: Add myself and Andrew Schoen
  services/ocs/OWNERS
  services/ocs/admin_rbac.yaml
Labels: approved, lgtm

#11588 gather: Ensure detection of log symptoms is present in step registry
  ci-operator/step-registry/gather/extra/gather-extra-commands.sh
Labels: approved, lgtm

#11594 Base all ci-tools on centos8
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
Labels: approved, lgtm

#11492 ocp-edge qe: add puller account
  services/edge/OWNERS
  services/edge/README.md
  services/edge/admin_rbac.yaml
Labels: approved, lgtm

#11598 config/openshift/release: Add workers-rhel7 job to release periodics
  ci-operator/config/openshift/release/openshift-release-master__ocp-4.6.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: approved, lgtm

#11295 make the windows testing blocking for ovn and cno testing
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master-presubmits.yaml
Labels: approved, lgtm

#11297 adding testing for hybrid networking custom vxlan port to networking repos
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-master.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master-presubmits.yaml
Labels: approved, lgtm

#11498 Sync ci-release*-priv secrets only within api.ci
  core-services/secret-mirroring/_mapping.yaml
Labels: approved, lgtm

#11552 Migrate presubmits of the release repo
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: approved, lgtm

#11599 Create initial admin RBAC for CNV-QE
  services/cnv-qe/OWNERS
  services/cnv-qe/README.md
  services/cnv-qe/admin_rbac.yaml
Labels: approved, lgtm, tide/merge-method-squash

#11601 serviceaccounts: correct RBAC YAML
  services/interop-qe/admin_rbac.yaml
  services/ocs/admin_rbac.yaml
Labels: approved, lgtm

#11602 Highlight pod didn't start running within messages
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#11609 services/ocs: Correct usernames
  services/ocs/OWNERS
  services/ocs/admin_rbac.yaml
Labels: approved, lgtm

#11607 Publishing non-product images for the cluster-baremetal-operator repo
  ci-operator/config/openshift/cluster-baremetal-operator/openshift-cluster-baremetal-operator-master.yaml
Labels: approved, lgtm

#11613 Populate secret/pj-rehearse on build_farm
  core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#11606 run periodic 'perf' job daily
  ci-operator/config/codeready-toolchain/toolchain-e2e/codeready-toolchain-toolchain-e2e-master.yaml
  ci-operator/jobs/codeready-toolchain/toolchain-e2e/codeready-toolchain-toolchain-e2e-master-periodics.yaml
Labels: approved, lgtm

#11612 Had set binding namespace to cnv-qe, should be ocp
  services/cnv-qe/admin_rbac.yaml
Labels: approved, lgtm

#11549 Fixed broken leasing for multi-arch e2e jobs
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.6-periodics.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-remote-libvirt-e2e.yaml
Labels: approved, lgtm

#11597 Add Windows repositories to platform specific repositories
  ci-operator/platform-balance/step-jobs-by-platform.py
Labels: approved, lgtm

#10992 add 4.6 libvirt-ppc64le job
  ci-operator/jobs/openshift/release/openshift-release-release-4.6-periodics.yaml
Labels: approved, lgtm

#11500 add a unit test job for cluster-baremetal-operator
  ci-operator/config/openshift/cluster-baremetal-operator/openshift-cluster-baremetal-operator-master.yaml
  ci-operator/jobs/openshift/cluster-baremetal-operator/openshift-cluster-baremetal-operator-master-presubmits.yaml
Labels: approved, lgtm

#11569 fast-forward foundation - promotion master
  ci-operator/config/open-cluster-management/multicloud-operators-foundation/open-cluster-management-multicloud-operators-foundation-master.yaml
  ci-operator/jobs/open-cluster-management/multicloud-operators-foundation/open-cluster-management-multicloud-operators-foundation-master-postsubmits.yaml
Labels: approved, lgtm

#11617 Revert "Drop promoter registry override"
  ci-operator/templates/openshift/installer/cluster-launch-installer-remote-libvirt-e2e.yaml
Labels: approved, lgtm

#11616 Promote assisted-test-infra
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-presubmits.yaml
Labels: approved, lgtm

#11634 config/openshift/release: Add ansible image to periodics
  ci-operator/config/openshift/release/openshift-release-master__ocp-4.6.yaml
Labels: approved, lgtm

#11610 Add telco bastion ssh secret to the mirror
  core-services/secret-mirroring/_mapping.yaml
Labels: approved, lgtm

#11632 steps/workers-rhel7: Add fast-datapath repo
  ci-operator/step-registry/workers-rhel7/repos/workers-rhel7-repos-commands.sh
Labels: approved, lgtm

#11244 Add more e2e-metal-ipi tests for 4.7
  ci-operator/step-registry/baremetalds/e2e/conf/baremetalds-e2e-conf-commands.sh
Labels: approved, lgtm

#11621 Disable tests for multi-arch since that depend on x86 fedora image
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
Labels: approved, lgtm

#11637 Bug 1875900: stop promoting svcat*operators beyond 4.5
  ci-operator/config/openshift/cluster-svcat-apiserver-operator/openshift-cluster-svcat-apiserver-operator-master.yaml
  ci-operator/config/openshift/cluster-svcat-apiserver-operator/openshift-cluster-svcat-apiserver-operator-release-4.6.yaml
  ci-operator/config/openshift/cluster-svcat-apiserver-operator/openshift-cluster-svcat-apiserver-operator-release-4.7.yaml
  ci-operator/config/openshift/cluster-svcat-controller-manager-operator/openshift-cluster-svcat-controller-manager-operator-master.yaml
  ci-operator/config/openshift/cluster-svcat-controller-manager-operator/openshift-cluster-svcat-controller-manager-operator-release-4.6.yaml
  ci-operator/config/openshift/cluster-svcat-controller-manager-operator/openshift-cluster-svcat-controller-manager-operator-release-4.7.yaml
  ci-operator/jobs/openshift/cluster-svcat-apiserver-operator/openshift-cluster-svcat-apiserver-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-svcat-apiserver-operator/openshift-cluster-svcat-apiserver-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-svcat-apiserver-operator/openshift-cluster-svcat-apiserver-operator-release-4.6-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-svcat-apiserver-operator/openshift-cluster-svcat-apiserver-operator-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/cluster-svcat-apiserver-operator/openshift-cluster-svcat-apiserver-operator-release-4.7-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-svcat-apiserver-operator/openshift-cluster-svcat-apiserver-operator-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/cluster-svcat-controller-manager-operator/openshift-cluster-svcat-controller-manager-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-svcat-controller-manager-operator/openshift-cluster-svcat-controller-manager-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-svcat-controller-manager-operator/openshift-cluster-svcat-controller-manager-operator-release-4.6-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-svcat-controller-manager-operator/openshift-cluster-svcat-controller-manager-operator-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/cluster-svcat-controller-manager-operator/openshift-cluster-svcat-controller-manager-operator-release-4.7-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-svcat-controller-manager-operator/openshift-cluster-svcat-controller-manager-operator-release-4.7-presubmits.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#11640 Fix api.ci boskos repo
  core-services/prow/03_deployment/boskos.yaml
  core-services/prow/03_deployment/boskos_cleaner.yaml
  core-services/prow/03_deployment/boskos_reaper.yaml
Labels: approved, lgtm

#11408 Bump go version for NFD
  ci-operator/config/openshift/node-feature-discovery/openshift-node-feature-discovery-master.yaml
  ci-operator/config/openshift/node-feature-discovery/openshift-node-feature-discovery-release-4.6.yaml
  ci-operator/config/openshift/node-feature-discovery/openshift-node-feature-discovery-release-4.7.yaml
Labels: approved, lgtm

#11655 Re-enable the promotion of nightly for contrib
  ci-operator/config/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-next.yaml
Labels: approved, lgtm

#11658 We did remove the test images, by accident
  core-services/image-mirroring/knative/mapping_knative_nightly_quay
Labels: approved, lgtm

#11472 feat(route-monitor-operator): add release
  ci-operator/config/openshift/route-monitor-operator/OWNERS
  ci-operator/config/openshift/route-monitor-operator/openshift-route-monitor-operator-master.yaml
  ci-operator/jobs/openshift/route-monitor-operator/OWNERS
  ci-operator/jobs/openshift/route-monitor-operator/openshift-route-monitor-operator-master-presubmits.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#11675 Bug 1844471: updates golang to 1.14 for openshift-apiserver
  ci-operator/config/openshift/openshift-apiserver/openshift-openshift-apiserver-master.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#11667 Bump external-attacher golang version in 4.6
  ci-operator/config/openshift/csi-external-attacher/openshift-csi-external-attacher-master.yaml
  ci-operator/config/openshift/csi-external-attacher/openshift-csi-external-attacher-release-4.6.yaml
  ci-operator/config/openshift/csi-external-attacher/openshift-csi-external-attacher-release-4.7.yaml
Labels: approved, lgtm

#11669 Bump golang in external-provisioner
  ci-operator/config/openshift/csi-external-provisioner/openshift-csi-external-provisioner-master.yaml
  ci-operator/config/openshift/csi-external-provisioner/openshift-csi-external-provisioner-release-4.6.yaml
  ci-operator/config/openshift/csi-external-provisioner/openshift-csi-external-provisioner-release-4.7.yaml
Labels: approved, lgtm

#11670 Bump golang in external-resizer
  ci-operator/config/openshift/csi-external-resizer/openshift-csi-external-resizer-master.yaml
  ci-operator/config/openshift/csi-external-resizer/openshift-csi-external-resizer-release-4.6.yaml
  ci-operator/config/openshift/csi-external-resizer/openshift-csi-external-resizer-release-4.7.yaml
Labels: approved, lgtm

#11671 Bump golang in external-snapshotter
  ci-operator/config/openshift/csi-external-snapshotter/openshift-csi-external-snapshotter-master.yaml
  ci-operator/config/openshift/csi-external-snapshotter/openshift-csi-external-snapshotter-release-4.6.yaml
  ci-operator/config/openshift/csi-external-snapshotter/openshift-csi-external-snapshotter-release-4.7.yaml
Labels: approved, lgtm

#11672 Bump golang in node-driver-registrar
  ci-operator/config/openshift/csi-node-driver-registrar/openshift-csi-node-driver-registrar-master.yaml
  ci-operator/config/openshift/csi-node-driver-registrar/openshift-csi-node-driver-registrar-release-4.6.yaml
  ci-operator/config/openshift/csi-node-driver-registrar/openshift-csi-node-driver-registrar-release-4.7.yaml
Labels: approved, lgtm

#11643 Jenkins url template: Don't access refs field for periodics
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#11630 [redhat-developer/service-binding-operator] Remove obsolete e2e jobs.
  ci-operator/config/redhat-developer/service-binding-operator/redhat-developer-service-binding-operator-master__4.5.yaml
  ci-operator/jobs/redhat-developer/service-binding-operator/redhat-developer-service-binding-operator-master-presubmits.yaml
Labels: approved, lgtm

#11678 Bug 1868439: e2e-openstack-upi: Ignition files to v3 spec
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-upi-e2e.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#11691 Sync api.ci kubeconfig to pj-rehearse secret
  core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#11688 optional operators: steps and workflows consuming indices built by ci-operator
  ci-operator/step-registry/metadata.json
  ci-operator/step-registry/optional-operators/ci/OWNERS
  ci-operator/step-registry/optional-operators/ci/aws/OWNERS
  ci-operator/step-registry/optional-operators/ci/aws/optional-operators-ci-aws-workflow.yaml
  ci-operator/step-registry/optional-operators/ci/azure/OWNERS
  ci-operator/step-registry/optional-operators/ci/azure/optional-operators-ci-azure-workflow.yaml
  ci-operator/step-registry/optional-operators/ci/gcp/OWNERS
  ci-operator/step-registry/optional-operators/ci/gcp/optional-operators-ci-gcp-workflow.yaml
  ci-operator/step-registry/optional-operators/ci/subscribe/OWNERS
  ci-operator/step-registry/optional-operators/ci/subscribe/optional-operators-ci-subscribe-commands.sh
  ci-operator/step-registry/optional-operators/ci/subscribe/optional-operators-ci-subscribe-ref.yaml
Labels: approved, lgtm

#11557 Fix server search URL in slack leaks report
  ci-operator/step-registry/baremetalds/packet/check/baremetalds-packet-check-commands.sh
Labels: approved, lgtm

#11698 Chore/testgrid/remove releasetype annotation
  ci-operator/jobs/openshift/origin/openshift-origin-release-3.11-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.1-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.6-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml
  core-services/testgrid-config-generator/_allow-list.yaml
Labels: approved, lgtm

#11693 steps/workers-rhel7: Use ephemeral cluster version for configuring repos
  ci-operator/step-registry/workers-rhel7/repos/workers-rhel7-repos-commands.sh
Labels: approved, lgtm

#11700 vsphere - too many concurrent jobs; periodic freq change
  ci-operator/config/openshift/release/openshift-release-master__ocp-4.4.yaml
  ci-operator/config/openshift/release/openshift-release-master__ocp-4.5.yaml
  ci-operator/config/openshift/release/openshift-release-master__ocp-4.6.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  core-services/prow/02_config/_boskos.yaml
Labels: approved, lgtm

#11696 Adding Knative eventing contrib 0.17.1 CI setup
  ci-operator/config/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-v0.17.1.yaml
  ci-operator/config/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-v0.17.1__46.yaml
  ci-operator/jobs/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-v0.17.1-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-v0.17.1-presubmits.yaml
  core-services/image-mirroring/knative/mapping_knative_v0_17_quay
Labels: approved, lgtm

#11645 add docs/cee/qe approval labels for console repo
  core-services/prow/02_config/_labels.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#11660 cluster-network-operator: use multistep job for e2e-upgrade
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-master.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.3.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.4.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.5.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.6.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.7.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.7-presubmits.yaml
Labels: approved, lgtm

#11546 openshift-upgrade-gcp-loki: persist monitoring metrics via PVC
  ci-operator/step-registry/ipi/install/monitoringpvc/OWNERS
  ci-operator/step-registry/ipi/install/monitoringpvc/ipi-install-monitoringpvc-commands.sh
  ci-operator/step-registry/ipi/install/monitoringpvc/ipi-install-monitoringpvc-ref.yaml
  ci-operator/step-registry/metadata.json
  ci-operator/step-registry/openshift/upgrade/gcp/loki/openshift-upgrade-gcp-loki-workflow.yaml
Labels: approved, lgtm

#11692 Provide api.ci kubecofig to pj-rehearse job
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
Labels: approved, lgtm

#11661 console-operator: use multistep job for e2e-upgrade
  ci-operator/config/openshift/console-operator/openshift-console-operator-master.yaml
  ci-operator/config/openshift/console-operator/openshift-console-operator-release-4.2.yaml
  ci-operator/config/openshift/console-operator/openshift-console-operator-release-4.3.yaml
  ci-operator/config/openshift/console-operator/openshift-console-operator-release-4.4.yaml
  ci-operator/config/openshift/console-operator/openshift-console-operator-release-4.5.yaml
  ci-operator/config/openshift/console-operator/openshift-console-operator-release-4.6.yaml
  ci-operator/config/openshift/console-operator/openshift-console-operator-release-4.7.yaml
  ci-operator/jobs/openshift/console-operator/openshift-console-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/console-operator/openshift-console-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/console-operator/openshift-console-operator-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/console-operator/openshift-console-operator-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/console-operator/openshift-console-operator-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift/console-operator/openshift-console-operator-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/console-operator/openshift-console-operator-release-4.7-presubmits.yaml
Labels: approved, lgtm

#11695 Increasing the requested resource cpu
  ci-operator/config/openshift/odo/openshift-odo-master__v4.2.yaml
  ci-operator/config/openshift/odo/openshift-odo-master__v4.3.yaml
  ci-operator/config/openshift/odo/openshift-odo-master__v4.4.yaml
  ci-operator/config/openshift/odo/openshift-odo-master__v4.5.yaml
Labels: approved, lgtm

#11713 openstack UPI: Only replace inventory assignments once
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-upi-e2e.yaml
Labels: approved, lgtm

#11701 Enable optional k8s-e2e-gcp-serial job
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-master.yaml
  ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-master-presubmits.yaml
  ci-operator/step-registry/metadata.json
  ci-operator/step-registry/openshift/kubernetes/e2e/gcp/openshift-kubernetes-e2e-gcp-workflow.yaml
  ci-operator/step-registry/openshift/kubernetes/e2e/gcp/serial/OWNERS
  ci-operator/step-registry/openshift/kubernetes/e2e/gcp/serial/openshift-kubernetes-e2e-gcp-serial-workflow.yaml
  ci-operator/step-registry/openshift/kubernetes/e2e/test/openshift-kubernetes-e2e-test-ref.yaml
Labels: approved, lgtm

#11668 operator-lifecycle-manager: use multistep job for e2e-upgrade
  ci-operator/config/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-master.yaml
  ci-operator/config/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-release-4.3.yaml
  ci-operator/config/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-release-4.4.yaml
  ci-operator/config/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-release-4.5.yaml
  ci-operator/config/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-release-4.6.yaml
  ci-operator/config/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-release-4.7.yaml
  ci-operator/jobs/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-master-presubmits.yaml
  ci-operator/jobs/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-release-4.3-presubmits.yaml
  ci-operator/jobs/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-release-4.4-presubmits.yaml
  ci-operator/jobs/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-release-4.5-presubmits.yaml
  ci-operator/jobs/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-release-4.6-presubmits.yaml
  ci-operator/jobs/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-release-4.7-presubmits.yaml
Labels: approved, lgtm

#11710 Cleanup legacy prometheus stuff
  Makefile
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  projects/prometheus/alert-buffer.yaml
  projects/prometheus/alertmanager.yml
  projects/prometheus/node_exporter.yaml
  projects/prometheus/prometheus.rules.yaml
  projects/prometheus/prometheus.yaml
  projects/prometheus/test/Dockerfile
  projects/prometheus/test/build.yaml
  projects/prometheus/test/entrypoint.sh
Labels: approved, lgtm

#11714 vsphere change time vs type; fix rhel scale
  ci-operator/config/openshift/release/openshift-release-master__ocp-4.5.yaml
  ci-operator/config/openshift/release/openshift-release-master__ocp-4.6.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: approved, lgtm

#11717 e2e-openstack-upi: Delete cluster tokens
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-upi-e2e.yaml
Labels: approved, lgtm

#11721 vsphere - change vcenter url for new sddc
  ci-operator/step-registry/ipi/conf/vsphere/ipi-conf-vsphere-commands.sh
  ci-operator/step-registry/upi/conf/vsphere/upi-conf-vsphere-commands.sh
Labels: approved, lgtm

#11718 Do not require valid owners on openshift/kubernetes master
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#11724 vsphere - dns server change
  ci-operator/step-registry/upi/conf/vsphere/upi-conf-vsphere-commands.sh
Labels: approved, lgtm

#11725 releases: 4.3 and 4.4 OKD were only temporary and are removed
  core-services/release-controller/_releases/release-origin-4.3.json
  core-services/release-controller/_releases/release-origin-4.4.json
Labels: approved, lgtm

#11711 Adding Serverless 1.9 branch
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.9.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.9__4.5.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.9-periodics.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.9-postsubmits.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.9-presubmits.yaml
Labels: approved, lgtm

#11519 fast-forward registration-operator
  ci-operator/config/open-cluster-management/registration-operator/open-cluster-management-registration-operator-master.yaml
  ci-operator/config/open-cluster-management/registration-operator/open-cluster-management-registration-operator-release-2.1.yaml
  ci-operator/jobs/open-cluster-management/registration-operator/open-cluster-management-registration-operator-master-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/registration-operator/open-cluster-management-registration-operator-release-2.1-presubmits.yaml
Labels: approved, lgtm

#11728 OKD promotion: use GCP
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.6-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml
Labels: approved, lgtm

#11707 Add ovirt csi job to csi repos
  ci-operator/jobs/openshift/csi-external-attacher/openshift-csi-external-attacher-master-presubmits.yaml
  ci-operator/jobs/openshift/csi-external-attacher/openshift-csi-external-attacher-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/csi-external-attacher/openshift-csi-external-attacher-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/csi-external-provisioner/openshift-csi-external-provisioner-master-presubmits.yaml
  ci-operator/jobs/openshift/csi-external-provisioner/openshift-csi-external-provisioner-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/csi-external-provisioner/openshift-csi-external-provisioner-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/csi-external-resizer/openshift-csi-external-resizer-master-presubmits.yaml
  ci-operator/jobs/openshift/csi-external-resizer/openshift-csi-external-resizer-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/csi-external-resizer/openshift-csi-external-resizer-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/csi-external-snapshotter/openshift-csi-external-snapshotter-master-presubmits.yaml
  ci-operator/jobs/openshift/csi-external-snapshotter/openshift-csi-external-snapshotter-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/csi-external-snapshotter/openshift-csi-external-snapshotter-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/csi-livenessprobe/openshift-csi-livenessprobe-master-presubmits.yaml
  ci-operator/jobs/openshift/csi-livenessprobe/openshift-csi-livenessprobe-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/csi-livenessprobe/openshift-csi-livenessprobe-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/csi-node-driver-registrar/openshift-csi-node-driver-registrar-master-presubmits.yaml
  ci-operator/jobs/openshift/csi-node-driver-registrar/openshift-csi-node-driver-registrar-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/csi-node-driver-registrar/openshift-csi-node-driver-registrar-release-4.7-presubmits.yaml
Labels: approved, lgtm

#11665 oauth-server: use multistep job for e2e-upgrade
  ci-operator/config/openshift/oauth-server/openshift-oauth-server-master.yaml
  ci-operator/config/openshift/oauth-server/openshift-oauth-server-release-4.6.yaml
  ci-operator/config/openshift/oauth-server/openshift-oauth-server-release-4.7.yaml
  ci-operator/jobs/openshift/oauth-server/openshift-oauth-server-master-presubmits.yaml
  ci-operator/jobs/openshift/oauth-server/openshift-oauth-server-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/oauth-server/openshift-oauth-server-release-4.7-presubmits.yaml
Labels: approved, lgtm

#11628 cluster-authentication: use upgrade workflow with Loki
  ci-operator/config/openshift/cluster-authentication-operator/openshift-cluster-authentication-operator-master.yaml
  ci-operator/config/openshift/cluster-authentication-operator/openshift-cluster-authentication-operator-release-4.7.yaml
Labels: approved, lgtm

#11523 cincinnati: run rustfmt tests for Rust 1.46 only
  ci-operator/config/openshift/cincinnati/openshift-cincinnati-master.yaml
  ci-operator/jobs/openshift/cincinnati/openshift-cincinnati-master-presubmits.yaml
Labels: approved, lgtm

#11734 Bump go version of CSO
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-master.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.6.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.7.yaml
Labels: approved, lgtm

#11733 Bump go version of CSI driver operators
  ci-operator/config/openshift/aws-ebs-csi-driver-operator/openshift-aws-ebs-csi-driver-operator-master.yaml
  ci-operator/config/openshift/aws-ebs-csi-driver-operator/openshift-aws-ebs-csi-driver-operator-release-4.6.yaml
  ci-operator/config/openshift/aws-ebs-csi-driver-operator/openshift-aws-ebs-csi-driver-operator-release-4.7.yaml
  ci-operator/config/openshift/csi-driver-manila-operator/openshift-csi-driver-manila-operator-master.yaml
  ci-operator/config/openshift/csi-driver-manila-operator/openshift-csi-driver-manila-operator-release-4.6.yaml
  ci-operator/config/openshift/csi-driver-manila-operator/openshift-csi-driver-manila-operator-release-4.7.yaml
  ci-operator/config/openshift/ovirt-csi-driver-operator/openshift-ovirt-csi-driver-operator-master.yaml
  ci-operator/config/openshift/ovirt-csi-driver-operator/openshift-ovirt-csi-driver-operator-release-4.6.yaml
  ci-operator/config/openshift/ovirt-csi-driver-operator/openshift-ovirt-csi-driver-operator-release-4.7.yaml
Labels: approved, lgtm

#11174 Cincinnati: avoid using artifact_dir
  ci-operator/config/openshift/cincinnati/openshift-cincinnati-master.yaml
  ci-operator/jobs/openshift/cincinnati/openshift-cincinnati-master-presubmits.yaml
Labels: approved, lgtm

#11744 ci-secret-generator: update config, Makefile
  Makefile
  core-services/ci-secret-generator/_config.yaml
Labels: approved, lgtm

#11746 ci-secret-generator: update registry values to be simple
  core-services/ci-secret-generator/_config.yaml
Labels: approved, lgtm

#11726 Added multi-arch cluster-samples-operator jobs to 4.6 periodics file
  ci-operator/jobs/openshift/release/openshift-release-release-4.6-periodics.yaml
Labels: approved, lgtm

#11748 extend the three upgrade plus e2e timeout to six hours
  ci-operator/jobs/openshift/release/openshift-release-release-4.6-periodics.yaml
Labels: approved, lgtm

#11749 Add gettext to the release image
  hack/generators/release-controllers/content/resources/rhel-7/release/Dockerfile
  hack/generators/release-controllers/content/resources/rhel-8/release/Dockerfile
Labels: approved, lgtm

#11751 Revert "Merge pull request #11746 from stevekuznetsov/skuznets/refact…
  core-services/ci-secret-generator/_config.yaml
Labels: approved, lgtm

#11732 mirror-2.1 to latest
  core-services/image-mirroring/open-cluster-management/mapping_open_cluster_management_latest_quay
Labels: approved, lgtm

#11757 Allow ART to dynamically create buildconfigs for ART equivalent images
  core-services/release-controller/admin_deploy-ocp-publish-art.yaml
  hack/generators/release-controllers/content/art_publish_permissions.py
Labels: approved, lgtm

#11763 chore: Add grpc-ping test image to knative-client config
  ci-operator/config/openshift/knative-client/openshift-knative-client-release-next__45.yaml
  core-services/image-mirroring/knative/mapping_knative_nightly_quay
Labels: approved, lgtm

#11023 ci-operator: Add metering-ansible-operator index image build step.
  ci-operator/config/kube-reporting/metering-operator/kube-reporting-metering-operator-master.yaml
  ci-operator/config/kube-reporting/metering-operator/kube-reporting-metering-operator-release-4.6.yaml
  ci-operator/config/kube-reporting/metering-operator/kube-reporting-metering-operator-release-4.7.yaml
  ci-operator/jobs/kube-reporting/metering-operator/kube-reporting-metering-operator-master-presubmits.yaml
  ci-operator/jobs/kube-reporting/metering-operator/kube-reporting-metering-operator-release-4.6-periodics.yaml
  ci-operator/jobs/kube-reporting/metering-operator/kube-reporting-metering-operator-release-4.6-presubmits.yaml
  ci-operator/jobs/kube-reporting/metering-operator/kube-reporting-metering-operator-release-4.7-presubmits.yaml
Labels: approved, lgtm

#11716 add functional test jobs to clo and oal
  ci-operator/config/openshift/cluster-logging-operator/openshift-cluster-logging-operator-master.yaml
  ci-operator/config/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-master.yaml
  ci-operator/jobs/openshift/cluster-logging-operator/openshift-cluster-logging-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-master-presubmits.yaml
Labels: approved, lgtm

#11638 OKD machine-os-promotion: rework composed image
  ci-operator/jobs/openshift/release/openshift-release-release-4.6-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml
Labels: approved, lgtm

#11770 Expose 6443 api port for telco sshd bastion
  core-services/sshd-bastion/telco/deployment.yaml
Labels: approved, lgtm

#11773 Set default python interpreter for rhel-8 release image
  hack/generators/release-controllers/content/resources/rhel-8/release/Dockerfile
Labels: approved

#11653 Add extra documentation for CONTAINER_ENGINE env var
  Makefile
  ci-operator/README.md
Labels: approved, kind/documentation, lgtm

#11780 ci-tools: seed the slack-bot image
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
Labels: approved, lgtm
