Repository openshift/release, pull requests merged in 2020-08, with the labels that each got.

#10410 ci-operator/config/openshift/cluster-version-operator: Add gofmt job
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-master.yaml
  ci-operator/jobs/openshift/cluster-version-operator/openshift-cluster-version-operator-master-presubmits.yaml
Labels: approved, lgtm

#10365 Serverless - operator tests required, other tests optional
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master__4.5.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master-presubmits.yaml
Labels: approved, lgtm

#10568 OpenStack: add e2e-openstack to cluster-storage-operator
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-master-presubmits.yaml
Labels: approved, lgtm

#10331 Setting assisted e2e workflow
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-presubmits.yaml
  ci-operator/step-registry/baremetalds/assisted/OWNERS
  ci-operator/step-registry/baremetalds/assisted/baremetalds-assisted-workflow.yaml
  ci-operator/step-registry/baremetalds/assisted/setup/OWNERS
  ci-operator/step-registry/baremetalds/assisted/setup/baremetalds-assisted-setup-commands.sh
  ci-operator/step-registry/baremetalds/assisted/setup/baremetalds-assisted-setup-ref.yaml
  ci-operator/step-registry/metadata.json
Labels: approved, lgtm

#10500 Adding whitelisting for release-2.* branches
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#10605 add publicize image build in ci-tools config
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
Labels: approved, lgtm

#10599 create the publicize deployment and service
  clusters/app.ci/prow/03_deployment/publicize.yaml
Labels: approved, lgtm

#10606 Set e2e-metal-ipi to be IPv4
  ci-operator/step-registry/baremetalds/devscripts/setup/baremetalds-devscripts-setup-commands.sh
Labels: approved, lgtm

#10337 add multicloud-operators-foundation repo
  ci-operator/config/open-cluster-management/multicloud-operators-foundation/OWNERS
  ci-operator/config/open-cluster-management/multicloud-operators-foundation/open-cluster-management-multicloud-operators-foundation-master.yaml
  ci-operator/jobs/open-cluster-management/multicloud-operators-foundation/OWNERS
  ci-operator/jobs/open-cluster-management/multicloud-operators-foundation/open-cluster-management-multicloud-operators-foundation-master-presubmits.yaml
  core-services/image-mirroring/open-cluster-management/mapping_open_cluster_management_latest_quay
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm, tide/merge-method-squash

#10229 Fix typo in CSI override name
  ci-operator/templates/openshift/installer/cluster-launch-installer-remote-libvirt-e2e.yaml
Labels: approved, lgtm

#10492 Migrate all presubmits of the origin repo to build01
  ci-operator/jobs/openshift/origin/openshift-origin-release-3.10-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-3.11-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.7-presubmits.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: approved, lgtm

#10636 Serverless improvements for periodic jobs
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master__4.3.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master__4.4.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master-periodics.yaml
Labels: approved, lgtm

#10633 Add tekton release 0.15.0
  ci-operator/config/openshift/tektoncd-catalog/openshift-tektoncd-catalog-release-v0.15__4.3.yaml
  ci-operator/config/openshift/tektoncd-catalog/openshift-tektoncd-catalog-release-v0.15__4.4.yaml
  ci-operator/config/openshift/tektoncd-catalog/openshift-tektoncd-catalog-release-v0.15__4.5.yaml
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.15.0__4.3.yaml
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.15.0__4.4.yaml
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.15.0__4.5.yaml
  ci-operator/jobs/openshift/tektoncd-catalog/openshift-tektoncd-catalog-release-v0.15-postsubmits.yaml
  ci-operator/jobs/openshift/tektoncd-catalog/openshift-tektoncd-catalog-release-v0.15-presubmits.yaml
  ci-operator/jobs/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.15.0-postsubmits.yaml
  ci-operator/jobs/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.15.0-presubmits.yaml
  core-services/image-mirroring/tekton/mapping_tekton_catalog_v0_15_quay
  core-services/image-mirroring/tekton/mapping_tekton_v0_15_quay
Labels: approved, lgtm

#10560 oVirt e2e: fix broken e2e job on 4.6 and master
  ci-operator/templates/openshift/installer/cluster-launch-installer-ovirt-e2e.yaml
Labels: approved, lgtm

#10641 Move certs objects to cert-manager folder
  clusters/build-clusters/01_cluster/README.md
  clusters/build-clusters/01_cluster/openshift-apiserver/README.md
  clusters/build-clusters/01_cluster/openshift-ingress-operator/README.md
  clusters/build-clusters/02_cluster/cert-manager/apiserver-build02_certificate.yaml
  clusters/build-clusters/02_cluster/cert-manager/apps-build02_certificate.yaml
  clusters/build-clusters/02_cluster/cert-manager/registry-build02_certificate.yaml
Labels: approved, lgtm

#10621 Move pdb to the common folder
  clusters/build-clusters/common/assets/pdb.yaml
Labels: approved, lgtm

#10638 ci-operator: Add periodic testing for the metering-operator.
  ci-operator/config/kube-reporting/metering-operator/kube-reporting-metering-operator-master.yaml
  ci-operator/config/kube-reporting/metering-operator/kube-reporting-metering-operator-release-4.5.yaml
  ci-operator/config/kube-reporting/metering-operator/kube-reporting-metering-operator-release-4.6.yaml
  ci-operator/config/kube-reporting/metering-operator/kube-reporting-metering-operator-release-4.7.yaml
  ci-operator/jobs/kube-reporting/metering-operator/kube-reporting-metering-operator-master-periodics.yaml
  ci-operator/jobs/kube-reporting/metering-operator/kube-reporting-metering-operator-release-4.5-periodics.yaml
  ci-operator/jobs/kube-reporting/metering-operator/kube-reporting-metering-operator-release-4.6-periodics.yaml
  ci-operator/jobs/kube-reporting/metering-operator/kube-reporting-metering-operator-release-4.7-periodics.yaml
Labels: approved, lgtm

#10642 add pj-rehearse repo in the whitelist for testing purposes
  core-services/openshift-priv/_whitelist.yaml
Labels: approved, lgtm

#10647 make periodic-auto-private-org-peribolos-sync job hidden
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm

#10643 baremetalds: use defaults for image mirroring
  ci-operator/step-registry/baremetalds/devscripts/setup/baremetalds-devscripts-setup-commands.sh
Labels: approved, lgtm

#10650 ci-operator/jobs: Add slack notification configuration for the metering periodic jobs.
  ci-operator/jobs/kube-reporting/metering-operator/kube-reporting-metering-operator-release-4.5-periodics.yaml
  ci-operator/jobs/kube-reporting/metering-operator/kube-reporting-metering-operator-release-4.6-periodics.yaml
  ci-operator/jobs/kube-reporting/metering-operator/kube-reporting-metering-operator-release-4.7-periodics.yaml
Labels: approved, lgtm

#10485 Test skipping must-gather for Serverless
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master__4.5.yaml
Labels: approved, lgtm

#10658 add build image for acm-foundation
  ci-operator/config/open-cluster-management/multicloud-operators-foundation/open-cluster-management-multicloud-operators-foundation-master.yaml
  ci-operator/jobs/open-cluster-management/multicloud-operators-foundation/open-cluster-management-multicloud-operators-foundation-master-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/multicloud-operators-foundation/open-cluster-management-multicloud-operators-foundation-master-presubmits.yaml
Labels: approved, lgtm

#10652 add CI for hive ocm-2.1 branch
  ci-operator/config/openshift/hive/openshift-hive-ocm-2.1.yaml
  ci-operator/jobs/openshift/hive/openshift-hive-ocm-2.1-postsubmits.yaml
  ci-operator/jobs/openshift/hive/openshift-hive-ocm-2.1-presubmits.yaml
Labels: approved, lgtm

#10634 Add new repository openshift/assisted-service
  ci-operator/jobs/openshift/assisted-service/OWNERS
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#10662 update WildFly Operator CI to use new Makefile target
  ci-operator/config/wildfly/wildfly-operator/wildfly-wildfly-operator-master.yaml
  ci-operator/jobs/wildfly/wildfly-operator/wildfly-wildfly-operator-master-presubmits.yaml
Labels: approved, lgtm

#10656 Generate buildconfigs for art->ci images
  Makefile
  core-services/release-controller/_builds/ci-builder-images.yaml
  core-services/release-controller/_builds/ci-release-images.yaml
  hack/generators/release-controllers/content/__init__.py
  hack/generators/release-controllers/content/art_input_images.py
  hack/generators/release-controllers/content/resources/Dockerfile.rhel-7-golang
  hack/generators/release-controllers/content/resources/Dockerfile.rhel-7-release
  hack/generators/release-controllers/content/resources/Dockerfile.rhel-8-golang
  hack/generators/release-controllers/content/resources/Dockerfile.rhel-8-release
  hack/generators/release-controllers/generate-release-controllers.py
Labels: approved, lgtm

#10668 Drop unsupported versions for CI of Serverless.
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.8__4.3.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.8__4.4.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.8__4.5.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.8-periodics.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.8-postsubmits.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.8-presubmits.yaml
Labels: approved, lgtm

#10669 Migrate installer's presubmits to build01
  ci-operator/jobs/openshift/installer/openshift-installer-fcos-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.7-presubmits.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: approved, lgtm

#10666 Build a bundle image for the Serverless Operator.
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.8__4.5.yaml
Labels: approved, lgtm

#10573 Enable stale issue close across openshift org
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm

#10653 fips_check: Don't hardcode number of nodes
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
Labels: approved, lgtm

#10671 Add generated buildconfigs for ART base images
  core-services/release-controller/ci-base-images.yaml
  core-services/release-controller/ci-builder-images.yaml
  core-services/release-controller/ci-release-images.yaml
  hack/generators/release-controllers/content/__init__.py
  hack/generators/release-controllers/content/art_input_images.py
  hack/generators/release-controllers/content/resources/Dockerfile.rhel-7-base
  hack/generators/release-controllers/content/resources/Dockerfile.rhel-8-base
  hack/generators/release-controllers/generate-release-controllers.py
Labels: approved, lgtm

#10674 Fix contextDir; only permits directory/Dockerfile
  core-services/release-controller/ci-base-images.yaml
  core-services/release-controller/ci-builder-images.yaml
  core-services/release-controller/ci-release-images.yaml
  hack/generators/release-controllers/content/art_input_images.py
  hack/generators/release-controllers/content/resources/rhel-7/base/Dockerfile
  hack/generators/release-controllers/content/resources/rhel-7/golang/Dockerfile
  hack/generators/release-controllers/content/resources/rhel-7/release/Dockerfile
  hack/generators/release-controllers/content/resources/rhel-8/base/Dockerfile
  hack/generators/release-controllers/content/resources/rhel-8/golang/Dockerfile
  hack/generators/release-controllers/content/resources/rhel-8/release/Dockerfile
Labels: approved, lgtm

#8108 Add RHEL7 worker steps
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.6.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.7.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-master.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-4.6.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-4.7.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-4.7-presubmits.yaml
  ci-operator/step-registry/ipi/aws/pre/workers-rhel7/OWNERS
  ci-operator/step-registry/ipi/aws/pre/workers-rhel7/ipi-aws-pre-workers-rhel7-chain.yaml
  ci-operator/step-registry/metadata.json
  ci-operator/step-registry/openshift/e2e/aws/workers-rhel7/OWNERS
  ci-operator/step-registry/openshift/e2e/aws/workers-rhel7/openshift-e2e-aws-workers-rhel7-workflow.yaml
  ci-operator/step-registry/ssh-bastion/OWNERS
  ci-operator/step-registry/ssh-bastion/ssh-bastion-commands.sh
  ci-operator/step-registry/ssh-bastion/ssh-bastion-ref.yaml
  ci-operator/step-registry/workers-rhel7/OWNERS
  ci-operator/step-registry/workers-rhel7/aws-provision/OWNERS
  ci-operator/step-registry/workers-rhel7/aws-provision/workers-rhel7-aws-provision-commands.sh
  ci-operator/step-registry/workers-rhel7/aws-provision/workers-rhel7-aws-provision-ref.yaml
  ci-operator/step-registry/workers-rhel7/repos/OWNERS
  ci-operator/step-registry/workers-rhel7/repos/workers-rhel7-repos-commands.sh
  ci-operator/step-registry/workers-rhel7/repos/workers-rhel7-repos-ref.yaml
  ci-operator/step-registry/workers-rhel7/scaleup/OWNERS
  ci-operator/step-registry/workers-rhel7/scaleup/workers-rhel7-scaleup-commands.sh
  ci-operator/step-registry/workers-rhel7/scaleup/workers-rhel7-scaleup-ref.yaml
  ci-operator/step-registry/workers-rhel7/workers-rhel7-chain.yaml
Labels: approved, lgtm

#10676 Add rolebinding/configmap-pruner-ci-operator to common folder
  clusters/build-clusters/common/ci-operator/admin_ci-operator_rbac.yaml
Labels: approved, lgtm

#10679 openshift/installer: workers-rhel7 is optional
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.7-presubmits.yaml
Labels: approved, lgtm

#10680 Workaround for FROM must be first bug in OCP
  hack/generators/release-controllers/content/resources/rhel-7/base/Dockerfile
  hack/generators/release-controllers/content/resources/rhel-7/golang/Dockerfile
  hack/generators/release-controllers/content/resources/rhel-7/release/Dockerfile
  hack/generators/release-controllers/content/resources/rhel-8/base/Dockerfile
  hack/generators/release-controllers/content/resources/rhel-8/golang/Dockerfile
  hack/generators/release-controllers/content/resources/rhel-8/release/Dockerfile
Labels: approved, lgtm

#10673 Add config for e2e-metal-ipi to MAO release config
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-master.yaml
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-release-4.6.yaml
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-release-4.7.yaml
Labels: approved, lgtm

#10657 Bug 1859260: use matchbox service running on build01
  ci-operator/templates/openshift/installer/cluster-launch-installer-metal-e2e.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#10685 Clean up pdb.yaml
  clusters/app.ci/assets/pdb.yaml
  clusters/build-clusters/02_cluster/assets/pdb.yaml
Labels: approved, lgtm

#10667 Run assisted-test-infra without e2e-test
  ci-operator/config/openshift/assisted-test-infra/OWNERS
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/jobs/openshift/assisted-service/OWNERS
  ci-operator/step-registry/baremetalds/assisted/OWNERS
  ci-operator/step-registry/baremetalds/assisted/setup/OWNERS
  ci-operator/step-registry/metadata.json
Labels: approved, lgtm

#10691 make periodic-openshift-release-private-org-sync job hidden
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm

#10675 Revert "adding new leases for use with new system"
  core-services/prow/02_config/_boskos.yaml
Labels: approved, lgtm

#10670 Configure for release-1.1 branch on kubevirt/hyperconverged-cluster-operator
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-1.1.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-1.1-postsubmits.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-1.1-presubmits.yaml
Labels: approved, lgtm

#10689 Serverless: CI updates for master branch of serverless-operator
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master__4.3-azure.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master__4.3-gcp.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master__4.3-vsphere.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master__4.5-azure.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master__4.5-gcp.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master__4.5-vsphere.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master__4.5.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master-periodics.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master-presubmits.yaml
Labels: approved, lgtm

#10693 Serverless: Do not run image builds in pre-submit for GCP,Azure,vSphere
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master-presubmits.yaml
Labels: approved, lgtm

#10688 fix acm-foundation image name
  core-services/image-mirroring/open-cluster-management/mapping_open_cluster_management_latest_quay
Labels: approved, lgtm

#10686 Explain why we need rolebinding/configmap-pruner-ci-operator
  clusters/build-clusters/common/ci-operator/admin_ci-operator_rbac.yaml
Labels: approved, lgtm

#10694 Added missing operator e2e tests.
  ci-operator/config/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-master.yaml
  ci-operator/config/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-release-4.6.yaml
  ci-operator/config/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-release-4.7.yaml
  ci-operator/jobs/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-release-4.7-presubmits.yaml
Labels: approved, lgtm

#10696 release: Rate limit to 2 simultaneous builds in controller
  core-services/release-controller/_releases/priv/release-ocp-4.1.json
  core-services/release-controller/_releases/priv/release-ocp-4.2.json
  core-services/release-controller/_releases/priv/release-ocp-4.3.json
  core-services/release-controller/_releases/priv/release-ocp-4.4.json
  core-services/release-controller/_releases/release-ocp-4.1-ci.json
  core-services/release-controller/_releases/release-ocp-4.1.json
  core-services/release-controller/_releases/release-ocp-4.2-ci.json
  core-services/release-controller/_releases/release-ocp-4.2.json
  core-services/release-controller/_releases/release-ocp-4.3.json
  core-services/release-controller/_releases/release-ocp-4.4.json
  core-services/release-controller/_releases/release-ocp-4.6-ci.json
Labels: approved, lgtm

#10695 Enable additional lanes on kubevirt/hyperconverged-cluster-operator
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-1.1.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-1.1-presubmits.yaml
Labels: approved, lgtm

#10698 Remove line number from generated content
  clusters/app.ci/release-controller/deploy-ocp-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-ppc64le-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-ppc64le-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-s390x-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-s390x-priv-controller.yaml
  clusters/app.ci/release-controller/serviceaccount.yaml
  core-services/release-controller/admin_config_updater_rbac-ppc64le-priv.yaml
  core-services/release-controller/admin_config_updater_rbac-ppc64le.yaml
  core-services/release-controller/admin_config_updater_rbac-priv.yaml
  core-services/release-controller/admin_config_updater_rbac-s390x-priv.yaml
  core-services/release-controller/admin_config_updater_rbac-s390x.yaml
  core-services/release-controller/admin_config_updater_rbac.yaml
  core-services/release-controller/admin_deploy-ocp-controller.yaml
  core-services/release-controller/admin_deploy-ocp-ppc64le-controller.yaml
  core-services/release-controller/admin_deploy-ocp-ppc64le-priv-controller.yaml
  core-services/release-controller/admin_deploy-ocp-priv-controller.yaml
  core-services/release-controller/admin_deploy-ocp-publish-art.yaml
  core-services/release-controller/admin_deploy-ocp-s390x-controller.yaml
  core-services/release-controller/admin_deploy-ocp-s390x-priv-controller.yaml
  core-services/release-controller/ci-base-images.yaml
  core-services/release-controller/ci-builder-images.yaml
  core-services/release-controller/ci-release-images.yaml
  core-services/release-controller/deploy-ocp-controller.yaml
  core-services/release-controller/deploy-ocp-ppc64le-controller.yaml
  core-services/release-controller/deploy-ocp-ppc64le-priv-controller.yaml
  core-services/release-controller/deploy-ocp-priv-controller.yaml
  core-services/release-controller/deploy-ocp-s390x-controller.yaml
  core-services/release-controller/deploy-ocp-s390x-priv-controller.yaml
  core-services/release-controller/rpms-ocp-4.1.yaml
  core-services/release-controller/rpms-ocp-4.2.yaml
  core-services/release-controller/rpms-ocp-4.3.yaml
  core-services/release-controller/rpms-ocp-4.4.yaml
  core-services/release-controller/rpms-ocp-4.5.yaml
  core-services/release-controller/rpms-ocp-4.6.yaml
  core-services/release-controller/rpms-ocp-4.7.yaml
  hack/generators/lib/genlib/__init__.py
Labels: approved, lgtm

#10682 Removing unnecessary go env vars
  hack/generators/release-controllers/content/resources/rhel-7/golang/Dockerfile
  hack/generators/release-controllers/content/resources/rhel-8/golang/Dockerfile
  hack/generators/release-controllers/content/resources/rhel-8/release/Dockerfile
Labels: approved, lgtm

#10701 add publicize endpoint to external plugins for openshift-priv org
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#10703 remove dry run mode from the publicize plugin deployment
  clusters/app.ci/prow/03_deployment/publicize.yaml
Labels: approved, lgtm

#10704 remove dry run from publicize plugin deployment
  clusters/app.ci/prow/03_deployment/publicize.yaml
Labels: approved, lgtm

#10705 RHEL-8 renamed createrepo to createrepo_c
  hack/generators/release-controllers/content/resources/rhel-8/release/Dockerfile
Labels: approved, lgtm

#10470 [wmcb] Stop running WSU e2e tests on 4.5+ clusters
  ci-operator/config/openshift/windows-machine-config-bootstrapper/openshift-windows-machine-config-bootstrapper-master.yaml
  ci-operator/config/openshift/windows-machine-config-bootstrapper/openshift-windows-machine-config-bootstrapper-release-4.6.yaml
  ci-operator/config/openshift/windows-machine-config-bootstrapper/openshift-windows-machine-config-bootstrapper-release-4.7.yaml
  ci-operator/jobs/openshift/windows-machine-config-bootstrapper/openshift-windows-machine-config-bootstrapper-master-presubmits.yaml
  ci-operator/jobs/openshift/windows-machine-config-bootstrapper/openshift-windows-machine-config-bootstrapper-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/windows-machine-config-bootstrapper/openshift-windows-machine-config-bootstrapper-release-4.7-presubmits.yaml
  ci-operator/step-registry/windows/e2e/playbook/test/windows-e2e-playbook-test-ref.yaml
Labels: approved, lgtm

#10707 Stop mirroring into ci-stg, that ns doesn't exist in most build clusters
  core-services/secret-mirroring/_mapping.yaml
Labels: approved, lgtm

#10390 Update openshift/kubernetes master to build with golang 1.14
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-master.yaml
Labels: approved, lgtm

#10710 ci-tools: remove the build of our old image
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
Labels: approved, lgtm

#10702 Drop the tests for knative-eventing release-nexts on 4.3 and 4.4
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next__44.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next__45.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next__46.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-next-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-next-presubmits.yaml
Labels: approved, lgtm

#10664 Add job to tests olm nightly files in OCP 4.5
  ci-operator/config/eclipse/che-operator/OWNERS
  ci-operator/config/eclipse/che-operator/eclipse-che-operator-master__v5.yaml
  ci-operator/jobs/che-incubator/chectl/OWNERS
  ci-operator/jobs/eclipse/che-operator/OWNERS
  ci-operator/jobs/eclipse/che-operator/eclipse-che-operator-master-presubmits.yaml
Labels: approved, lgtm

#10700 baremetalds: Revert "Use timestamp instead of the BUILD_ID for Packet hostname"
  ci-operator/step-registry/baremetalds/packet/setup/baremetalds-packet-setup-commands.sh
  ci-operator/step-registry/baremetalds/packet/teardown/baremetalds-packet-teardown-commands.sh
Labels: approved, lgtm

#10590 Use golang 1.14 in AWS EBS CSI Driver operator jobs
  ci-operator/config/openshift/aws-ebs-csi-driver-operator/openshift-aws-ebs-csi-driver-operator-master.yaml
  ci-operator/config/openshift/aws-ebs-csi-driver-operator/openshift-aws-ebs-csi-driver-operator-release-4.6.yaml
  ci-operator/config/openshift/aws-ebs-csi-driver-operator/openshift-aws-ebs-csi-driver-operator-release-4.7.yaml
Labels: approved, lgtm

#10716 Remove old intly operator branch config
  ci-operator/config/integr8ly/integreatly-operator/integr8ly-integreatly-operator-amq-online-next-1.5.1.yaml
  ci-operator/config/integr8ly/integreatly-operator/integr8ly-integreatly-operator-apicurito-next-7.7.0.yaml
  ci-operator/config/integr8ly/integreatly-operator/integr8ly-integreatly-operator-fuse-online-next-7.7.0.yaml
  ci-operator/jobs/integr8ly/integreatly-operator/integr8ly-integreatly-operator-amq-online-next-1.5.1-postsubmits.yaml
  ci-operator/jobs/integr8ly/integreatly-operator/integr8ly-integreatly-operator-amq-online-next-1.5.1-presubmits.yaml
  ci-operator/jobs/integr8ly/integreatly-operator/integr8ly-integreatly-operator-apicurito-next-7.7.0-postsubmits.yaml
  ci-operator/jobs/integr8ly/integreatly-operator/integr8ly-integreatly-operator-apicurito-next-7.7.0-presubmits.yaml
  ci-operator/jobs/integr8ly/integreatly-operator/integr8ly-integreatly-operator-fuse-online-next-7.7.0-postsubmits.yaml
  ci-operator/jobs/integr8ly/integreatly-operator/integr8ly-integreatly-operator-fuse-online-next-7.7.0-presubmits.yaml
  core-services/image-mirroring/integr8ly/mapping_integr8ly_operator_amq_online_next-1_5_1
  core-services/image-mirroring/integr8ly/mapping_integr8ly_operator_apicurito-next-7_7_0
  core-services/image-mirroring/integr8ly/mapping_integr8ly_operator_fuse-online-next-7_7_0
Labels: approved, lgtm

#10406 Remove openshift-tuned for 4.4+ branches.
  ci-operator/config/openshift/openshift-tuned/openshift-openshift-tuned-master.yaml
  ci-operator/config/openshift/openshift-tuned/openshift-openshift-tuned-release-4.4.yaml
  ci-operator/config/openshift/openshift-tuned/openshift-openshift-tuned-release-4.5.yaml
  ci-operator/config/openshift/openshift-tuned/openshift-openshift-tuned-release-4.6.yaml
  ci-operator/config/openshift/openshift-tuned/openshift-openshift-tuned-release-4.7.yaml
  ci-operator/jobs/openshift/openshift-tuned/openshift-openshift-tuned-master-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-tuned/openshift-openshift-tuned-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-tuned/openshift-openshift-tuned-release-4.4-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-tuned/openshift-openshift-tuned-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/openshift-tuned/openshift-openshift-tuned-release-4.5-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-tuned/openshift-openshift-tuned-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift/openshift-tuned/openshift-openshift-tuned-release-4.6-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-tuned/openshift-openshift-tuned-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/openshift-tuned/openshift-openshift-tuned-release-4.7-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-tuned/openshift-openshift-tuned-release-4.7-presubmits.yaml
Labels: approved, lgtm

#10731 Revert "Extend tolerance of the probing alert"
  clusters/app.ci/prow-monitoring/mixins/_prometheus/dptp_alerts.libsonnet
  clusters/app.ci/prow-monitoring/mixins/prometheus_out/prometheus-prow-rules_prometheusrule.yaml
Labels: approved, lgtm

#10732 Create the namepaces required by secret-mirroring
  clusters/build-clusters/common/00_namespaces.yaml
Labels: approved, lgtm

#10706 Keep ssh bastion jobs on api.ci
  core-services/sanitize-prow-jobs/_config.yaml
Labels: approved, lgtm

#10660 add multicloud operator foundation 2.1
  ci-operator/config/open-cluster-management/multicloud-operators-foundation/open-cluster-management-multicloud-operators-foundation-release-2.1.yaml
  ci-operator/jobs/open-cluster-management/multicloud-operators-foundation/open-cluster-management-multicloud-operators-foundation-release-2.1-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/multicloud-operators-foundation/open-cluster-management-multicloud-operators-foundation-release-2.1-presubmits.yaml
Labels: approved, lgtm

#10734 enable multicloud-operator-foundation e2e test
  ci-operator/config/open-cluster-management/multicloud-operators-foundation/open-cluster-management-multicloud-operators-foundation-master.yaml
  ci-operator/jobs/open-cluster-management/multicloud-operators-foundation/open-cluster-management-multicloud-operators-foundation-master-presubmits.yaml
Labels: approved, lgtm, needs-ok-to-test

#10729 Add eclipse che credentials to test-credentials namespace
  core-services/secret-mirroring/_mapping.yaml
Labels: approved, lgtm

#10739 Only 4.5 at this point
  ci-operator/config/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-next.yaml
  ci-operator/config/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-next__44.yaml
  ci-operator/config/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-next__45.yaml
  ci-operator/jobs/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-next-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-next-presubmits.yaml
Labels: approved, lgtm

#10661 add versions check
  ci-operator/config/integr8ly/integreatly-operator/integr8ly-integreatly-operator-master.yaml
  ci-operator/jobs/integr8ly/integreatly-operator/integr8ly-integreatly-operator-master-presubmits.yaml
Labels: approved, lgtm

#10503 Add CI config for RHMI operator branch release-v2.6
  ci-operator/config/integr8ly/integreatly-operator/integr8ly-integreatly-operator-release-v2.6.yaml
  ci-operator/jobs/integr8ly/integreatly-operator/integr8ly-integreatly-operator-release-v2.6-postsubmits.yaml
  ci-operator/jobs/integr8ly/integreatly-operator/integr8ly-integreatly-operator-release-v2.6-presubmits.yaml
  core-services/image-mirroring/integr8ly/mapping_integr8ly_operator_2_6
Labels: approved, lgtm, ok-to-test

#10742 Adding aliok and devguyio as knative eventing approvers & reviewers
  ci-operator/config/openshift/knative-eventing-contrib/OWNERS
  ci-operator/config/openshift/knative-eventing/OWNERS
  ci-operator/jobs/openshift/knative-eventing-contrib/OWNERS
  ci-operator/jobs/openshift/knative-eventing/OWNERS
Labels: approved, lgtm

#10743 For 0.14.0 we go only w/ 4.5...
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.14.2.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.14.2__4.4.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.14.2__4.5.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.14.2-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.14.2-presubmits.yaml
Labels: approved, lgtm

#10744 Knative Eventing: some clean ups
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.6.0-periodics.yaml
Labels: approved, lgtm

#10737 Raise CKSO golang version to match kube 1.19
  ci-operator/config/openshift/cluster-kube-scheduler-operator/openshift-cluster-kube-scheduler-operator-master.yaml
Labels: approved, lgtm

#10750 Modify che operator images and job name
  ci-operator/config/eclipse/che-operator/eclipse-che-operator-master__v5.yaml
  ci-operator/jobs/eclipse/che-operator/eclipse-che-operator-master-presubmits.yaml
Labels: approved, lgtm

#10753 Eventing for now, just 4.5
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next__46.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-next-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-next-presubmits.yaml
Labels: approved, lgtm

#10735 add image mirroring for foundation 2.1 branch
  core-services/image-mirroring/open-cluster-management/mapping_open_cluster_management_2_1_quay
Labels: approved, lgtm

#10723 adding jobs for openshift/projected-resource-csi-driver
  ci-operator/config/openshift/projected-resource-csi-driver/OWNERS
  ci-operator/config/openshift/projected-resource-csi-driver/openshift-projected-resource-csi-driver-master.yaml
  ci-operator/jobs/openshift/projected-resource-csi-driver/OWNERS
  ci-operator/jobs/openshift/projected-resource-csi-driver/openshift-projected-resource-csi-driver-master-presubmits.yaml
Labels: approved, lgtm

#10740 Add label to s390x jobs that use ssh bastion
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
Labels: approved, lgtm

#10576 Re-enable passing tests for 4.5 s390x
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
Labels: approved, lgtm

#10763 prow: run multiple instances of deck
  clusters/app.ci/prow/03_deployment/deck.yaml
Labels: approved, lgtm

#10761 Add optional flag to router e2e-metal-ipi
  ci-operator/jobs/openshift/router/openshift-router-master-presubmits.yaml
Labels: approved, lgtm

#10764 Increase replicas for backporter
  clusters/app.ci/assets/bugzilla-backporter.yaml
Labels: approved, lgtm

#10767 Scale up MachineSet/build01-9hdwj-worker-us-east-1a-search to 2
  clusters/build-clusters/01_cluster/openshift-machine-api/admin_build01-9hdwj-worker-us-east-1a-search_machine_set.yaml
Labels: approved, lgtm

#10677 Migrate MAO/MCO to workers-rhel7 steps
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-master.yaml
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-release-4.6.yaml
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-release-4.7.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-master.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.6.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.7.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.7-presubmits.yaml
Labels: approved, lgtm

#10768 Disable all private release controller tests
  core-services/release-controller/_releases/priv/release-ocp-4.1.json
  core-services/release-controller/_releases/priv/release-ocp-4.2.json
  core-services/release-controller/_releases/priv/release-ocp-4.3.json
  core-services/release-controller/_releases/priv/release-ocp-4.4.json
  core-services/release-controller/_releases/priv/release-ocp-4.5.json
  core-services/release-controller/_releases/priv/release-ocp-4.6.json
  core-services/release-controller/_releases/priv/release-ocp-4.7.json
  hack/generators/release-controllers/generate-release-controllers.py
Labels: approved, lgtm

#10771 Add alert ETCD_OOMKilled_Soon
  core-services/openshift-monitoring/cfg_prometheus-prow-rules_prometheusrule.yaml
Labels: approved, lgtm

#10773 Add label to ppc64le libvirt jobs that use ssh bastion
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
Labels: approved, lgtm

#10721 oVirt e2e: fix update image registy condition
  ci-operator/templates/openshift/installer/cluster-launch-installer-ovirt-e2e.yaml
Labels: approved, lgtm

#10592 [e2e-crc/installer/test] Don't run story_registry test on GCP
  ci-operator/step-registry/openshift/e2e/crc/test/openshift-e2e-crc-test-commands.sh
Labels: approved, lgtm

#10775 Add OpenShift/assisted-installer repository
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#10777 enable multicloud-operator-foundation e2e test
  ci-operator/config/open-cluster-management/multicloud-operators-foundation/open-cluster-management-multicloud-operators-foundation-master.yaml
  ci-operator/jobs/open-cluster-management/multicloud-operators-foundation/open-cluster-management-multicloud-operators-foundation-master-presubmits.yaml
Labels: approved, lgtm, ok-to-test

#10760 Create cm/ci-secret-bootstrap on app.ci
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#10783 Keep ovirt jobs on api.ci
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.7-presubmits.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: approved, lgtm

#10757 ci-operator: Attempt to build the bundle image before running any e2e tests.
  ci-operator/config/kube-reporting/metering-operator/kube-reporting-metering-operator-release-4.6.yaml
  ci-operator/config/kube-reporting/metering-operator/kube-reporting-metering-operator-release-4.7.yaml
Labels: approved, lgtm

#10697 Populate secret/ci-pull-credentials to build01/2
  core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#10765 Enable controller: secret_syncer
  ci-operator/jobs/infra-periodics.yaml
  clusters/app.ci/assets/dptp-controller-manager.yaml
Labels: approved, lgtm

#10770 SDCICD-326. All MOA clusters will be provisioned in random regions.
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: approved, lgtm

#10789 Remove acm-sonarcloud-token from secret-mirroring
  core-services/secret-mirroring/_mapping.yaml
Labels: approved, lgtm

#10787 Add the missing RBAC of dptp-cm on app.ci
  core-services/dptp-controller-manager-serviceaccount/rbac.yaml
Labels: approved, lgtm

#10730 Undeploy secret-mirroring
  clusters/build-clusters/01_cluster/openshift/secret-mirroring/OWNERS
  clusters/build-clusters/01_cluster/openshift/secret-mirroring/README.md
  clusters/build-clusters/01_cluster/openshift/secret-mirroring/admin_rbac.yaml
  clusters/build-clusters/01_cluster/openshift/secret-mirroring/deployment.yaml
  clusters/build-clusters/02_cluster/openshift/secret-mirroring/OWNERS
  clusters/build-clusters/02_cluster/openshift/secret-mirroring/README.md
  clusters/build-clusters/02_cluster/openshift/secret-mirroring/admin_rbac.yaml
  clusters/build-clusters/02_cluster/openshift/secret-mirroring/deployment.yaml
  core-services/secret-mirroring/README.md
  core-services/secret-mirroring/admin_rbac.yaml
  core-services/secret-mirroring/deployment.yaml
Labels: approved, lgtm

#10788 fixing ci jobs for openshift/projected-resource-csi-driver
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#10791 Update which Dockerfile to use for Node Problem Detector CI
  ci-operator/config/openshift/node-problem-detector/openshift-node-problem-detector-master.yaml
  ci-operator/config/openshift/node-problem-detector/openshift-node-problem-detector-release-4.6.yaml
  ci-operator/config/openshift/node-problem-detector/openshift-node-problem-detector-release-4.7.yaml
Labels: approved, lgtm

#10792 Update ocs-operator Prow settings
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#10795 Remove jobs and configs for ci-secret-mirroring-controller
  ci-operator/config/openshift/ci-secret-mirroring-controller/OWNERS
  ci-operator/config/openshift/ci-secret-mirroring-controller/openshift-ci-secret-mirroring-controller-master.yaml
  ci-operator/jobs/openshift/ci-secret-mirroring-controller/OWNERS
  ci-operator/jobs/openshift/ci-secret-mirroring-controller/openshift-ci-secret-mirroring-controller-master-postsubmits.yaml
  ci-operator/jobs/openshift/ci-secret-mirroring-controller/openshift-ci-secret-mirroring-controller-master-presubmits.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#10785 add optional e2e-aws-upgrade job
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
Labels: approved, lgtm

#10800 upi-e2e template: display oc version prior to approving csr.
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
Labels: approved, lgtm

#10803 Switch toolchain configs to ocp 4.5
  ci-operator/config/codeready-toolchain/api/codeready-toolchain-api-master.yaml
  ci-operator/config/codeready-toolchain/host-operator/codeready-toolchain-host-operator-master.yaml
  ci-operator/config/codeready-toolchain/member-operator/codeready-toolchain-member-operator-master.yaml
  ci-operator/config/codeready-toolchain/registration-service/codeready-toolchain-registration-service-master.yaml
  ci-operator/config/codeready-toolchain/toolchain-common/codeready-toolchain-toolchain-common-master.yaml
  ci-operator/config/codeready-toolchain/toolchain-e2e/codeready-toolchain-toolchain-e2e-master.yaml
  ci-operator/config/codeready-toolchain/toolchain-operator/codeready-toolchain-toolchain-operator-master.yaml
Labels: approved, lgtm

#10797 alert: Update text to describe gather process for new alert
  core-services/openshift-monitoring/cfg_prometheus-prow-rules_prometheusrule.yaml
Labels: approved, lgtm

#10891 Add OpenShift/assisted-installer-agent and OpenShift/assisted-ignitio…
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#10897 Enabling the promotion for the images, they got turned off by accident
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next__45.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.14.2.yaml
Labels: approved, lgtm

#10798 Move the presubmits of 3 repos to build02
  ci-operator/jobs/cri-o/cri-o/cri-o-cri-o-master-presubmits.yaml
  ci-operator/jobs/cri-o/cri-o/cri-o-cri-o-release-1.13-presubmits.yaml
  ci-operator/jobs/cri-o/cri-o/cri-o-cri-o-release-1.14-presubmits.yaml
  ci-operator/jobs/cri-o/cri-o/cri-o-cri-o-release-1.16-presubmits.yaml
  ci-operator/jobs/cri-o/cri-o/cri-o-cri-o-release-1.17-presubmits.yaml
  ci-operator/jobs/cri-o/cri-o/cri-o-cri-o-release-1.18-presubmits.yaml
  ci-operator/jobs/cri-o/cri-o/cri-o-cri-o-release-1.19-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/console/openshift-console-master-presubmits.yaml
  ci-operator/jobs/openshift/console/openshift-console-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/console/openshift-console-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/console/openshift-console-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/console/openshift-console-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/console/openshift-console-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift/console/openshift-console-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/console/openshift-console-release-4.7-presubmits.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: approved, lgtm

#10581 Update doc of joining the CI build farm
  clusters/JoinBuildFarm.md
Labels: approved, lgtm

#10850 Fixing kube-reporting-helm-master.yaml to use dockerfile from ocp-build-data
  ci-operator/config/kube-reporting/helm/kube-reporting-helm-master.yaml
Labels: approved, lgtm

#10758 Onboarding node-maintenance-operator
  ci-operator/config/kubevirt/node-maintenance-operator/OWNERS
  ci-operator/config/kubevirt/node-maintenance-operator/kubevirt-node-maintenance-operator-master.yaml
  ci-operator/jobs/kubevirt/node-maintenance-operator/OWNERS
  ci-operator/jobs/kubevirt/node-maintenance-operator/kubevirt-node-maintenance-operator-master-postsubmits.yaml
  ci-operator/jobs/kubevirt/node-maintenance-operator/kubevirt-node-maintenance-operator-master-presubmits.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#10646 Remove ppc64le OpenStack 4.5 and 4.6 CI
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.6-periodics.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e-ppc64le.yaml
Labels: approved, lgtm

#10902 add ghproxy flags in publicize deployment
  clusters/app.ci/prow/03_deployment/publicize.yaml
Labels: approved, lgtm

#10904 fast-forward: remove duplicate `--future-release=4.7`
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm

#10906 Move more presubmits to build01
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-master-presubmits.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-1.1-presubmits.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.3-presubmits.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.4-presubmits.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.5-presubmits.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.6-presubmits.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-fcos-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-feature-es6x-presubmits.yaml
  ci-operator/jobs/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-master-presubmits.yaml
  ci-operator/jobs/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-presubmits.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: approved, lgtm

#10121 e2e-metal: Switch to live-initramfs and live-kernel if set in rhcos.json
  ci-operator/templates/openshift/installer/cluster-launch-installer-metal-e2e.yaml
Labels: approved, lgtm

#10908 Fix the URL of deck-internal in alert messages
  ci-operator/jobs/infra-periodics.yaml
  clusters/app.ci/prow-monitoring/mixins/_prometheus/dptp_alerts.libsonnet
  clusters/app.ci/prow-monitoring/mixins/prometheus_out/prometheus-prow-rules_prometheusrule.yaml
Labels: approved, lgtm

#10881 Fixing openshift-machine-config-operator-master.yaml to use dockerfile from ocp-build-data
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-master.yaml
Labels: approved, lgtm

#10910 alerts: bump etcd oom alert
  core-services/openshift-monitoring/cfg_prometheus-prow-rules_prometheusrule.yaml
Labels: approved, lgtm

#10909 Fix a typo in an alert's link
  clusters/app.ci/prow-monitoring/mixins/_prometheus/dptp_alerts.libsonnet
  clusters/app.ci/prow-monitoring/mixins/prometheus_out/prometheus-prow-rules_prometheusrule.yaml
Labels: approved, lgtm

#10903 Adding testing for opendatahub-io/manifests
  ci-operator/config/opendatahub-io/manifests/OWNERS
  ci-operator/config/opendatahub-io/manifests/opendatahub-io-manifests-v1.0-branch-openshift.yaml
  ci-operator/jobs/opendatahub-io/manifests/OWNERS
  ci-operator/jobs/opendatahub-io/manifests/opendatahub-io-manifests-v1.0-branch-openshift-periodics.yaml
  ci-operator/jobs/opendatahub-io/manifests/opendatahub-io-manifests-v1.0-branch-openshift-presubmits.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, tide/merge-method-squash

#10866 Fixing openshift-cluster-version-operator-master.yaml to use dockerfile from ocp-build-data
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-master.yaml
Labels: approved, lgtm

#10912 ci-tools: use `regcred` credentials for `e2e` test
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
Labels: approved, lgtm

#10926 clusters: add regcred to `test-credentials` namespace
  clusters/build-clusters/01_cluster/openshift/ci-operator/regcred_secret_test_credentials_template.yaml
  clusters/build-clusters/02_cluster/openshift/ci-operator/regcred_secret_test_credentials_template.yaml
  clusters/build-clusters/vsphere/ci-operator/regcred_secret_test_credentials_template.yaml
  core-services/build-farm/regcred_secret_test_credentials_template.yaml
Labels: approved, lgtm

#10736 add ut and e2e for release 2.1
  ci-operator/config/open-cluster-management/multicloud-operators-foundation/open-cluster-management-multicloud-operators-foundation-release-2.1.yaml
  ci-operator/jobs/open-cluster-management/multicloud-operators-foundation/open-cluster-management-multicloud-operators-foundation-release-2.1-presubmits.yaml
Labels: approved, lgtm

#10848 Fixing kube-reporting-ghostunnel-master.yaml to use dockerfile from ocp-build-data
  ci-operator/config/kube-reporting/ghostunnel/kube-reporting-ghostunnel-master.yaml
Labels: approved, lgtm

#10858 Fixing openshift-cluster-autoscaler-operator-master.yaml to use dockerfile from ocp-build-data
  ci-operator/config/openshift/cluster-autoscaler-operator/openshift-cluster-autoscaler-operator-master.yaml
Labels: approved, lgtm

#10864 Fixing openshift-cluster-samples-operator-master.yaml to use dockerfile from ocp-build-data
  ci-operator/config/openshift/cluster-samples-operator/openshift-cluster-samples-operator-master.yaml
Labels: approved, lgtm

#10865 Fixing openshift-cluster-update-keys-master.yaml to use dockerfile from ocp-build-data
  ci-operator/config/openshift/cluster-update-keys/openshift-cluster-update-keys-master.yaml
Labels: approved, lgtm

#10896 OpenStack: add e2e-openstack to csi-driver-manila-operator
  ci-operator/jobs/openshift/csi-driver-manila-operator/openshift-csi-driver-manila-operator-master-presubmits.yaml
Labels: approved, lgtm

#10872 Fixing openshift-csi-livenessprobe-master.yaml to use dockerfile from ocp-build-data
  ci-operator/config/openshift/csi-livenessprobe/openshift-csi-livenessprobe-master.yaml
Labels: approved, lgtm

#10854 Fixing openshift-aws-ebs-csi-driver-master.yaml to use dockerfile from ocp-build-data
  ci-operator/config/openshift/aws-ebs-csi-driver/openshift-aws-ebs-csi-driver-master.yaml
Labels: approved, lgtm

#10377 ci-operator/config/openshift/cluster-monitoring-operator: Generic e2e-aws -> e2e for 4.6+
  ci-operator/config/openshift/cluster-monitoring-operator/openshift-cluster-monitoring-operator-master.yaml
  ci-operator/config/openshift/cluster-monitoring-operator/openshift-cluster-monitoring-operator-release-4.6.yaml
  ci-operator/config/openshift/cluster-monitoring-operator/openshift-cluster-monitoring-operator-release-4.7.yaml
  ci-operator/jobs/openshift/cluster-monitoring-operator/openshift-cluster-monitoring-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-monitoring-operator/openshift-cluster-monitoring-operator-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/cluster-monitoring-operator/openshift-cluster-monitoring-operator-release-4.7-presubmits.yaml
Labels: approved, lgtm

#10869 Fixing openshift-csi-external-attacher-master.yaml to use dockerfile from ocp-build-data
  ci-operator/config/openshift/csi-external-attacher/openshift-csi-external-attacher-master.yaml
Labels: approved, lgtm

#10870 Fixing openshift-csi-external-provisioner-master.yaml to use dockerfile from ocp-build-data
  ci-operator/config/openshift/csi-external-provisioner/openshift-csi-external-provisioner-master.yaml
Labels: approved, lgtm

#10871 Fixing openshift-csi-external-snapshotter-master.yaml to use dockerfile from ocp-build-data
  ci-operator/config/openshift/csi-external-snapshotter/openshift-csi-external-snapshotter-master.yaml
Labels: approved, lgtm

#10907 mirror psap namespace secret to ci
  core-services/secret-mirroring/_mapping.yaml
Labels: approved, lgtm

#10859 Fixing openshift-cluster-capacity-master.yaml to use dockerfile from ocp-build-data
  ci-operator/config/openshift/cluster-capacity/openshift-cluster-capacity-master.yaml
Labels: approved, lgtm

#10911 Use ubi8 as input image for ironic-static-ip-manager
  ci-operator/config/openshift/ironic-static-ip-manager/openshift-ironic-static-ip-manager-master.yaml
Labels: approved
