Repository openshift/release, pull requests merged in 2020-07, with the labels that each got.

#9994 Skip flaky test test_id:1631 for now
  ci-operator/config/kubevirt/kubevirt/kubevirt-kubevirt-master.yaml
  ci-operator/jobs/kubevirt/kubevirt/kubevirt-kubevirt-master-periodics.yaml
Labels: approved, lgtm

#9991 Ensure the creation of openshift/kubernetes e2e reporting path
  ci-operator/step-registry/openshift/kubernetes/e2e/test/openshift-kubernetes-e2e-test-commands.sh
Labels: approved, lgtm

#10016 openshift-release-release-4.5-periodics: re-enable OKD 4.5 machine-os-content promotion
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
Labels: approved, lgtm

#9824 core-services/release-controller add retries to OKD 4.5+ nightlies tests
  core-services/release-controller/_releases/release-origin-4.5.json
  core-services/release-controller/_releases/release-origin-4.6.json
Labels: approved, lgtm

#10010 installer-fcos-presubmits: remove run_if_changed for opentack
  ci-operator/jobs/openshift/installer/openshift-installer-fcos-presubmits.yaml
Labels: approved, lgtm

#10018 Bump openshift-monitoring prometheus storage 400G->700G
  core-services/openshift-monitoring/k8s_prometheus.yaml
Labels: approved, lgtm

#10004 added to prow openshift-docs size
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#9587 baremetalds: Use timestamp instead of BUILD_ID for packet_hostname
  ci-operator/step-registry/baremetalds/packet/setup/baremetalds-packet-setup-commands.sh
  ci-operator/step-registry/baremetalds/packet/teardown/baremetalds-packet-teardown-commands.sh
Labels: approved, lgtm

#10020 Remove intly operator post submit e2e job
  ci-operator/jobs/integr8ly/integreatly-operator/integr8ly-integreatly-operator-master-postsubmits.yaml
Labels: approved, lgtm

#10017 Fix OLM test run for release 4.4
  ci-operator/jobs/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-release-4.4-periodics.yaml
Labels: approved, lgtm

#10002 Add main branch support.
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#10006 Enable validation of hyperkube transition in origin repo
  ci-operator/config/openshift/origin/openshift-origin-marun-testing.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-marun-testing-postsubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-marun-testing-presubmits.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#10028 Fix openshift/origin:marun-testing image configuration
  ci-operator/config/openshift/origin/openshift-origin-marun-testing.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-marun-testing-postsubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-marun-testing-presubmits.yaml
Labels: approved, lgtm

#10029 Enabel artifact collection openshift/kubernetes test branch
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-marun-testing13.yaml
Labels: approved, lgtm

#10030 Fix image configuration for openshift/origin:marun-testing
  ci-operator/config/openshift/origin/openshift-origin-marun-testing.yaml
Labels: approved, lgtm

#10024 Change CI job name for tektoncd-pipeline
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-next__4.3.yaml
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-next__4.4.yaml
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-next__4.5.yaml
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.13.2__4.3.yaml
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.13.2__4.4.yaml
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.13.2__4.5.yaml
  ci-operator/jobs/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-next-postsubmits.yaml
  ci-operator/jobs/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-next-presubmits.yaml
  ci-operator/jobs/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.13.2-postsubmits.yaml
  ci-operator/jobs/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.13.2-presubmits.yaml
Labels: approved, lgtm

#10032 Update kubernetes-e2e workflow to rely script sourced from image
  ci-operator/step-registry/openshift/kubernetes/OWNERS
  ci-operator/step-registry/openshift/kubernetes/e2e/test/openshift-kubernetes-e2e-test-commands.sh
Labels: approved, lgtm

#10037 Change CI job name for tektoncd components
  ci-operator/config/openshift/tektoncd-catalog/openshift-tektoncd-catalog-release-next__4.3.yaml
  ci-operator/config/openshift/tektoncd-catalog/openshift-tektoncd-catalog-release-next__4.4.yaml
  ci-operator/config/openshift/tektoncd-catalog/openshift-tektoncd-catalog-release-next__4.5.yaml
  ci-operator/config/openshift/tektoncd-catalog/openshift-tektoncd-catalog-release-v0.11__4.3.yaml
  ci-operator/config/openshift/tektoncd-cli/openshift-tektoncd-cli-release-next__4.3.yaml
  ci-operator/config/openshift/tektoncd-cli/openshift-tektoncd-cli-release-next__4.4.yaml
  ci-operator/config/openshift/tektoncd-cli/openshift-tektoncd-cli-release-next__4.5.yaml
  ci-operator/config/openshift/tektoncd-pipeline-operator/openshift-tektoncd-pipeline-operator-master__4.3.yaml
  ci-operator/config/openshift/tektoncd-pipeline-operator/openshift-tektoncd-pipeline-operator-master__4.4.yaml
  ci-operator/config/openshift/tektoncd-pipeline-operator/openshift-tektoncd-pipeline-operator-master__4.5.yaml
  ci-operator/config/openshift/tektoncd-pipeline-operator/openshift-tektoncd-pipeline-operator-release-next__4.3.yaml
  ci-operator/config/openshift/tektoncd-pipeline-operator/openshift-tektoncd-pipeline-operator-release-next__4.4.yaml
  ci-operator/config/openshift/tektoncd-pipeline-operator/openshift-tektoncd-pipeline-operator-release-next__4.5.yaml
  ci-operator/config/openshift/tektoncd-pipeline-operator/openshift-tektoncd-pipeline-operator-v0.11.x__4.3.yaml
  ci-operator/config/openshift/tektoncd-pipeline-operator/openshift-tektoncd-pipeline-operator-v0.11.x__4.4.yaml
  ci-operator/config/openshift/tektoncd-pipeline-operator/openshift-tektoncd-pipeline-operator-v0.11.x__4.5.yaml
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-next__4.3.yaml
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-next__4.4.yaml
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-next__4.5.yaml
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.13.2__4.3.yaml
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.13.2__4.4.yaml
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.13.2__4.5.yaml
  ci-operator/config/openshift/tektoncd-triggers/openshift-tektoncd-triggers-release-next__4.3.yaml
  ci-operator/config/openshift/tektoncd-triggers/openshift-tektoncd-triggers-release-next__4.4.yaml
  ci-operator/config/openshift/tektoncd-triggers/openshift-tektoncd-triggers-release-next__4.5.yaml
  ci-operator/config/openshift/tektoncd-triggers/openshift-tektoncd-triggers-release-v0.5.0__4.4.yaml
  ci-operator/jobs/openshift/tektoncd-catalog/openshift-tektoncd-catalog-release-next-postsubmits.yaml
  ci-operator/jobs/openshift/tektoncd-catalog/openshift-tektoncd-catalog-release-next-presubmits.yaml
  ci-operator/jobs/openshift/tektoncd-catalog/openshift-tektoncd-catalog-release-v0.11-postsubmits.yaml
  ci-operator/jobs/openshift/tektoncd-catalog/openshift-tektoncd-catalog-release-v0.11-presubmits.yaml
  ci-operator/jobs/openshift/tektoncd-cli/openshift-tektoncd-cli-release-next-presubmits.yaml
  ci-operator/jobs/openshift/tektoncd-pipeline-operator/openshift-tektoncd-pipeline-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/tektoncd-pipeline-operator/openshift-tektoncd-pipeline-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/tektoncd-pipeline-operator/openshift-tektoncd-pipeline-operator-release-next-postsubmits.yaml
  ci-operator/jobs/openshift/tektoncd-pipeline-operator/openshift-tektoncd-pipeline-operator-release-next-presubmits.yaml
  ci-operator/jobs/openshift/tektoncd-pipeline-operator/openshift-tektoncd-pipeline-operator-v0.11.x-postsubmits.yaml
  ci-operator/jobs/openshift/tektoncd-pipeline-operator/openshift-tektoncd-pipeline-operator-v0.11.x-presubmits.yaml
  ci-operator/jobs/openshift/tektoncd-triggers/openshift-tektoncd-triggers-release-next-postsubmits.yaml
  ci-operator/jobs/openshift/tektoncd-triggers/openshift-tektoncd-triggers-release-next-presubmits.yaml
  ci-operator/jobs/openshift/tektoncd-triggers/openshift-tektoncd-triggers-release-v0.5.0-postsubmits.yaml
  ci-operator/jobs/openshift/tektoncd-triggers/openshift-tektoncd-triggers-release-v0.5.0-presubmits.yaml
Labels: approved, lgtm

#10025 Disable BP for code-ready/snc
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#10026 Bug 1853070: line up samples operator master/4.6 branch config use of origin with other operators
  ci-operator/config/openshift/cluster-samples-operator/openshift-cluster-samples-operator-master.yaml
  ci-operator/config/openshift/cluster-samples-operator/openshift-cluster-samples-operator-release-4.5.yaml
  ci-operator/config/openshift/cluster-samples-operator/openshift-cluster-samples-operator-release-4.6.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#9428 switch node_exporter to golang 1.14
  ci-operator/config/openshift/node_exporter/openshift-node_exporter-master.yaml
  ci-operator/config/openshift/node_exporter/openshift-node_exporter-release-4.6.yaml
  ci-operator/config/openshift/node_exporter/openshift-node_exporter-release-4.7.yaml
Labels: approved, lgtm

#10038 Set SNC_VALIDATE_CERT bool to false
  ci-operator/step-registry/code-ready/snc/e2e/test/code-ready-snc-e2e-test-commands.sh
Labels: approved, lgtm

#9136 [origin-aggregated-logging] Migrate base images to ubi7
  ci-operator/config/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-master.yaml
Labels: approved, lgtm

#8953 ci-operator/step-registry/manifests: Factor day-2 manifests into own step
  ci-operator/step-registry/ipi/aws/pre/ipi-aws-pre-chain.yaml
  ci-operator/step-registry/ipi/azure/pre/ipi-azure-pre-chain.yaml
  ci-operator/step-registry/ipi/azure/pre/sharednetwork/ipi-azure-pre-sharednetwork-chain.yaml
  ci-operator/step-registry/ipi/gcp/pre/ipi-gcp-pre-chain.yaml
  ci-operator/step-registry/ipi/gcp/pre/sharednetwork/ipi-gcp-pre-sharednetwork-chain.yaml
  ci-operator/step-registry/ipi/vsphere/pre/ipi-vsphere-pre-chain.yaml
  ci-operator/step-registry/manifests/OWNERS
  ci-operator/step-registry/manifests/manifests-commands.sh
  ci-operator/step-registry/manifests/manifests-ref.yaml
  ci-operator/step-registry/openshift/e2e/aws/loki/openshift-e2e-aws-loki-workflow.yaml
  ci-operator/step-registry/openshift/e2e/aws/ovn/hybrid/openshift-e2e-aws-ovn-hybrid-workflow.yaml
  ci-operator/step-registry/openshift/e2e/aws/ovn/openshift-e2e-aws-ovn-workflow.yaml
  ci-operator/step-registry/openshift/e2e/aws/sdn/multi/openshift-e2e-aws-sdn-multi-workflow.yaml
  ci-operator/step-registry/openshift/e2e/aws/sdn/single/openshift-e2e-aws-sdn-single-workflow.yaml
  ci-operator/step-registry/openshift/e2e/azure/ovn/openshift-e2e-azure-ovn-workflow.yaml
  ci-operator/step-registry/openshift/e2e/gcp/loki/openshift-e2e-gcp-loki-workflow.yaml
  ci-operator/step-registry/openshift/e2e/test/openshift-e2e-test-commands.sh
  ci-operator/step-registry/openshift/e2e/vsphere/ovn/openshift-e2e-vsphere-ovn-workflow.yaml
  ci-operator/step-registry/upi/gcp/pre/upi-gcp-pre-chain.yaml
Labels: approved, lgtm

#10039 Revert "ci-operator/step-registry/manifests: Factor day-2 manifests into own step"
  ci-operator/step-registry/ipi/aws/pre/ipi-aws-pre-chain.yaml
  ci-operator/step-registry/ipi/azure/pre/ipi-azure-pre-chain.yaml
  ci-operator/step-registry/ipi/azure/pre/sharednetwork/ipi-azure-pre-sharednetwork-chain.yaml
  ci-operator/step-registry/ipi/gcp/pre/ipi-gcp-pre-chain.yaml
  ci-operator/step-registry/ipi/gcp/pre/sharednetwork/ipi-gcp-pre-sharednetwork-chain.yaml
  ci-operator/step-registry/ipi/vsphere/pre/ipi-vsphere-pre-chain.yaml
  ci-operator/step-registry/manifests/OWNERS
  ci-operator/step-registry/manifests/manifests-commands.sh
  ci-operator/step-registry/manifests/manifests-ref.yaml
  ci-operator/step-registry/openshift/e2e/aws/loki/openshift-e2e-aws-loki-workflow.yaml
  ci-operator/step-registry/openshift/e2e/aws/ovn/hybrid/openshift-e2e-aws-ovn-hybrid-workflow.yaml
  ci-operator/step-registry/openshift/e2e/aws/ovn/openshift-e2e-aws-ovn-workflow.yaml
  ci-operator/step-registry/openshift/e2e/aws/sdn/multi/openshift-e2e-aws-sdn-multi-workflow.yaml
  ci-operator/step-registry/openshift/e2e/aws/sdn/single/openshift-e2e-aws-sdn-single-workflow.yaml
  ci-operator/step-registry/openshift/e2e/azure/ovn/openshift-e2e-azure-ovn-workflow.yaml
  ci-operator/step-registry/openshift/e2e/gcp/loki/openshift-e2e-gcp-loki-workflow.yaml
  ci-operator/step-registry/openshift/e2e/test/openshift-e2e-test-commands.sh
  ci-operator/step-registry/openshift/e2e/vsphere/ovn/openshift-e2e-vsphere-ovn-workflow.yaml
  ci-operator/step-registry/upi/gcp/pre/upi-gcp-pre-chain.yaml
Labels: approved, lgtm

#10000 SDCICD-361. Migrate osde2e to main branch.
  ci-operator/config/openshift/osde2e/openshift-osde2e-main.yaml
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-presubmits.yaml
Labels: approved, lgtm

#10044 Bump plank global max concurrency to 1k
  core-services/prow/02_config/_config.yaml
Labels: approved

#10013 Add CI config for RHMI operator branch release-v2.4
  ci-operator/config/integr8ly/integreatly-operator/integr8ly-integreatly-operator-release-v2.4.yaml
  ci-operator/jobs/integr8ly/integreatly-operator/integr8ly-integreatly-operator-release-v2.4-postsubmits.yaml
  ci-operator/jobs/integr8ly/integreatly-operator/integr8ly-integreatly-operator-release-v2.4-presubmits.yaml
  core-services/image-mirroring/integr8ly/mapping_integr8ly_operator_2_4
Labels: approved, lgtm, ok-to-test

#10031 increase ibm create-cluster job timeout
  ci-operator/jobs/openshift/ibm-roks-toolkit/openshift-ibm-roks-toolkit-release-4.3-periodics.yaml
  ci-operator/jobs/openshift/ibm-roks-toolkit/openshift-ibm-roks-toolkit-release-4.4-periodics.yaml
Labels: approved, lgtm

#9949 Add a new UBI 8 base image for applications to test with (keep the base as 7)
  ci-operator/config/openshift/images/openshift-images-master.yaml
  ci-operator/config/openshift/images/openshift-images-release-4.1.yaml
  ci-operator/config/openshift/images/openshift-images-release-4.2.yaml
  ci-operator/config/openshift/images/openshift-images-release-4.3.yaml
  ci-operator/config/openshift/images/openshift-images-release-4.4.yaml
  ci-operator/config/openshift/images/openshift-images-release-4.5.yaml
  ci-operator/config/openshift/images/openshift-images-release-4.6.yaml
  ci-operator/config/openshift/images/openshift-images-release-4.7.yaml
  ci-operator/jobs/openshift/images/openshift-images-master-postsubmits.yaml
  ci-operator/jobs/openshift/images/openshift-images-master-presubmits.yaml
  ci-operator/jobs/openshift/images/openshift-images-release-4.6-postsubmits.yaml
  ci-operator/jobs/openshift/images/openshift-images-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/images/openshift-images-release-4.7-postsubmits.yaml
  ci-operator/jobs/openshift/images/openshift-images-release-4.7-presubmits.yaml
  hack/build
Labels: approved, lgtm

#10045 Set resource requests for dptp-controller-manager
  clusters/app.ci/assets/dptp-controller-manager.yaml
Labels: approved, lgtm

#10047 Disable auto-upgrade of build01
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm

#10049 Remove the debug node on buidl01
  clusters/build-clusters/01_cluster/openshift-machine-api/admin_build01-9hdwj-worker-us-east-1a-debug_machine_set.yaml
Labels: approved, lgtm

#9870 Replace acme.sh by cert-manager on build01
  ci-operator/jobs/infra-periodics.yaml
  clusters/app.ci/prow-monitoring/additional-scrape-configs_secret.yaml
  clusters/build-clusters/01_cluster/cert-manager/apiserver-build01_certificate.yaml
  clusters/build-clusters/01_cluster/cert-manager/apps-build01_certificate.yaml
  clusters/build-clusters/01_cluster/cert-manager/cert-issuer-aws-staging_clusterissuer.yaml
  clusters/build-clusters/01_cluster/cert-manager/cert-issuer-aws_clusterissuer.yaml
  clusters/build-clusters/01_cluster/hack/generate-bw-items.sh
  clusters/build-clusters/01_cluster/openshift-apiserver/README.md
  clusters/build-clusters/01_cluster/openshift-ingress-operator/README.md
  clusters/build-clusters/01_cluster/prow/03_deployment/admin_ca-cert-issuer_rbac.yaml
  core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#10040 Add openshift/egress-router-cni to tide
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#10050 GCP account is provisioned for 150 networks, bump to 120 clusters
  core-services/prow/02_config/_boskos.yaml
Labels: approved, lgtm

#10033 ci-operator/jobs/openshift/release: fix output istag for OKD machine-os-content promotion
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.6-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml
Labels: approved, lgtm

#9985 Move RBACs for api.ci to core-services/various_rbac
  Makefile
  cluster/ci/config/prow/openshift/ci-operator/roles.yaml
  cluster/ci/config/roles.yaml
  core-services/various_rbac/OWNERS
  core-services/various_rbac/README.md
  core-services/various_rbac/admin_ci-operator_roles.yaml
  core-services/various_rbac/admin_user_roles.yaml
Labels: approved, lgtm

#10054 Add egress-router-cni to tide
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#10048 Revert "Disable auto-upgrade of build01"
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm

#10036 release-controller: Fix typos in README
  core-services/release-controller/README.md
Labels: approved, lgtm

#10057 Revert "Remove the debug node on buidl01"
  clusters/build-clusters/01_cluster/openshift-machine-api/admin_build01-9hdwj-worker-us-east-1a-debug_machine_set.yaml
Labels: approved, lgtm

#10034 Assisted-test-infra multistage docker
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-postsubmits.yaml
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#9524 add ib-sriov-cni
  ci-operator/config/openshift/ib-sriov-cni/OWNERS
  ci-operator/config/openshift/ib-sriov-cni/openshift-ib-sriov-cni-master.yaml
  ci-operator/jobs/openshift/ib-sriov-cni/OWNERS
  ci-operator/jobs/openshift/ib-sriov-cni/openshift-ib-sriov-cni-master-postsubmits.yaml
  ci-operator/jobs/openshift/ib-sriov-cni/openshift-ib-sriov-cni-master-presubmits.yaml
  core-services/image-mirroring/openshift/mapping_origin_4_6
  core-services/image-mirroring/openshift/mapping_origin_4_7
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#10062 Add alexanderConstantinescu as clusterviewer on build02
  clusters/build-clusters/02_cluster/assets/admin_cluster-reader-0_list.yaml
Labels: approved, lgtm

#10042 Bug 1811184: Fix password replace code
  ci-operator/templates/openshift/installer/cluster-launch-installer-custom-test-image.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-metal-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e-ppc64le.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-upi-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-ovirt-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-remote-libvirt-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-src.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#10021 Add plugins.yaml to the volume for bz-backporter
  clusters/app.ci/assets/bugzilla-backporter.yaml
Labels: approved, lgtm

#10068 Switch some uses of release controller --release-namespace to a new flag
  core-services/release-controller/deploy-ocp-controller-ppc64le.yaml
  core-services/release-controller/deploy-ocp-controller-s390x.yaml
  core-services/release-controller/deploy-ocp-controller.yaml
  core-services/release-controller/deploy-origin-controller.yaml
Labels: approved, lgtm

#10069 Add pre and postsubmit job for managed-upgrade-operator codecov
  ci-operator/config/openshift/managed-upgrade-operator/openshift-managed-upgrade-operator-master.yaml
  ci-operator/jobs/openshift/managed-upgrade-operator/openshift-managed-upgrade-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/managed-upgrade-operator/openshift-managed-upgrade-operator-master-presubmits.yaml
  core-services/secret-mirroring/_mapping.yaml
Labels: approved, lgtm

#8969 openshift/installer: add verify-codegen test
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
Labels: approved, lgtm

#10035 switch CMO to golang 1.14
  ci-operator/config/openshift/cluster-monitoring-operator/openshift-cluster-monitoring-operator-master.yaml
  ci-operator/config/openshift/cluster-monitoring-operator/openshift-cluster-monitoring-operator-release-4.6.yaml
  ci-operator/config/openshift/cluster-monitoring-operator/openshift-cluster-monitoring-operator-release-4.7.yaml
Labels: approved, lgtm

#10023 use golang 1.14 in all monitoring stack builds
  ci-operator/config/openshift/configmap-reload/openshift-configmap-reload-master.yaml
  ci-operator/config/openshift/configmap-reload/openshift-configmap-reload-release-4.6.yaml
  ci-operator/config/openshift/configmap-reload/openshift-configmap-reload-release-4.7.yaml
  ci-operator/config/openshift/grafana/openshift-grafana-master.yaml
  ci-operator/config/openshift/grafana/openshift-grafana-release-4.6.yaml
  ci-operator/config/openshift/grafana/openshift-grafana-release-4.7.yaml
  ci-operator/config/openshift/k8s-prometheus-adapter/openshift-k8s-prometheus-adapter-master.yaml
  ci-operator/config/openshift/k8s-prometheus-adapter/openshift-k8s-prometheus-adapter-release-4.6.yaml
  ci-operator/config/openshift/k8s-prometheus-adapter/openshift-k8s-prometheus-adapter-release-4.7.yaml
  ci-operator/config/openshift/kube-rbac-proxy/openshift-kube-rbac-proxy-master.yaml
  ci-operator/config/openshift/kube-rbac-proxy/openshift-kube-rbac-proxy-release-4.6.yaml
  ci-operator/config/openshift/kube-rbac-proxy/openshift-kube-rbac-proxy-release-4.7.yaml
  ci-operator/config/openshift/kube-state-metrics/openshift-kube-state-metrics-master.yaml
  ci-operator/config/openshift/kube-state-metrics/openshift-kube-state-metrics-release-4.6.yaml
  ci-operator/config/openshift/kube-state-metrics/openshift-kube-state-metrics-release-4.7.yaml
  ci-operator/config/openshift/openshift-state-metrics/openshift-openshift-state-metrics-master.yaml
  ci-operator/config/openshift/openshift-state-metrics/openshift-openshift-state-metrics-release-4.6.yaml
  ci-operator/config/openshift/openshift-state-metrics/openshift-openshift-state-metrics-release-4.7.yaml
  ci-operator/config/openshift/prom-label-proxy/openshift-prom-label-proxy-master.yaml
  ci-operator/config/openshift/prom-label-proxy/openshift-prom-label-proxy-release-4.6.yaml
  ci-operator/config/openshift/prom-label-proxy/openshift-prom-label-proxy-release-4.7.yaml
  ci-operator/config/openshift/prometheus-alertmanager/openshift-prometheus-alertmanager-master.yaml
  ci-operator/config/openshift/prometheus-alertmanager/openshift-prometheus-alertmanager-release-4.6.yaml
  ci-operator/config/openshift/prometheus-alertmanager/openshift-prometheus-alertmanager-release-4.7.yaml
  ci-operator/config/openshift/prometheus-operator/openshift-prometheus-operator-master.yaml
  ci-operator/config/openshift/prometheus-operator/openshift-prometheus-operator-release-4.6.yaml
  ci-operator/config/openshift/prometheus-operator/openshift-prometheus-operator-release-4.7.yaml
  ci-operator/config/openshift/prometheus/openshift-prometheus-master.yaml
  ci-operator/config/openshift/prometheus/openshift-prometheus-release-4.6.yaml
  ci-operator/config/openshift/prometheus/openshift-prometheus-release-4.7.yaml
  ci-operator/config/openshift/thanos/openshift-thanos-master.yaml
  ci-operator/config/openshift/thanos/openshift-thanos-release-4.6.yaml
  ci-operator/config/openshift/thanos/openshift-thanos-release-4.7.yaml
Labels: approved, lgtm

#9935 Adding 1.8 branch CI runs
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.8.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.8__4.3.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.8__4.4.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.8__4.5.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.8-periodics.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.8-postsubmits.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.8-presubmits.yaml
Labels: approved, lgtm

#10065 OKD: use stable FCOS stream for 4.3 - 4.5 releases
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
Labels: approved, lgtm

#10076 Match the golang versions used in NTO repo.
  ci-operator/config/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-master.yaml
  ci-operator/config/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-release-4.4.yaml
  ci-operator/config/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-release-4.5.yaml
  ci-operator/config/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-release-4.6.yaml
  ci-operator/config/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-release-4.7.yaml
Labels: approved, lgtm

#10078 Remove snc from auto merge config
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#10075 enable build of the performance-addon-operator must-gather image
  ci-operator/config/openshift-kni/performance-addon-operators/openshift-kni-performance-addon-operators-master.yaml
  core-services/image-mirroring/openshift-kni/mapping_openshift-kni_quay
Labels: approved, lgtm

#10083 app.ci: Remove old release controller flags
  clusters/app.ci/release-controller/deploy-ocp-controller-ppc64le.yaml
  clusters/app.ci/release-controller/deploy-ocp-controller-s390x.yaml
  clusters/app.ci/release-controller/deploy-ocp-controller.yaml
  clusters/app.ci/release-controller/deploy-origin-controller.yaml
Labels: approved, lgtm

#9979 cnv nightly bundle test: add tests focus filter
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.5.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.5-periodics.yaml
Labels: approved, lgtm

#10085 follow redirects in endurance upgrade version fetch
  ci-operator/templates/openshift/endurance/endurance-test.yaml
Labels: approved, lgtm

#10086 Add config-updater config for marun's custom branches in o/o
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#10087 Fix ci-cluster-readers' RBACs on build01/2
  clusters/build-clusters/01_cluster/assets/admin_cluster-reader-0_list.yaml
  clusters/build-clusters/02_cluster/assets/admin_cluster-reader-0_list.yaml
Labels: approved, lgtm

#10088 app.ci: Add release signer to app.ci
  clusters/app.ci/release-controller/deploy-ci-signer.yaml
  core-services/ci-secret-bootstrap/_config.yaml
  core-services/release-controller/deploy-files-cache.yaml
  core-services/release-controller/deploy-ocp-controller-ppc64le.yaml
  core-services/release-controller/deploy-ocp-controller-s390x.yaml
  core-services/release-controller/deploy-ocp-controller.yaml
  core-services/release-controller/deploy-origin-controller.yaml
Labels: approved, lgtm

#10089 Add a new ci-admin on build02
  clusters/build-clusters/02_cluster/assets/admin_cluster-admin-0_list.yaml
  clusters/build-clusters/02_cluster/assets/admin_cluster-reader-0_list.yaml
Labels: approved, lgtm

#10070 Add Tekton Triggers v0.6.0 Release
  ci-operator/config/openshift/tektoncd-triggers/openshift-tektoncd-triggers-release-v0.6.0__4.3.yaml
  ci-operator/config/openshift/tektoncd-triggers/openshift-tektoncd-triggers-release-v0.6.0__4.4.yaml
  ci-operator/config/openshift/tektoncd-triggers/openshift-tektoncd-triggers-release-v0.6.0__4.5.yaml
  ci-operator/jobs/openshift/tektoncd-triggers/openshift-tektoncd-triggers-release-v0.6.0-postsubmits.yaml
  ci-operator/jobs/openshift/tektoncd-triggers/openshift-tektoncd-triggers-release-v0.6.0-presubmits.yaml
  core-services/image-mirroring/tekton/mapping_tekton_triggers_v0_4_rc1_quay
  core-services/image-mirroring/tekton/mapping_tekton_triggers_v0_5_quay
  core-services/image-mirroring/tekton/mapping_tekton_triggers_v0_6_quay
Labels: approved, lgtm

#10092 app.ci: Allow release signer to access api.ci cluster
  clusters/app.ci/release-controller/deploy-ci-signer.yaml
Labels: approved, lgtm

#10094 Add RBAC for ci-operator to CRD CMs on build0x
  clusters/build-clusters/01_cluster/openshift/ci-operator/admin_ci-operator_rbac.yaml
  clusters/build-clusters/02_cluster/openshift/ci-operator/admin_ci-operator_rbac.yaml
Labels: approved, lgtm

#10077 add private github credentials secret in app.ci
  core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#10095 release-controller: add previousRelease for bugzilla automation
  core-services/release-controller/_releases/release-ocp-4.1.json
  core-services/release-controller/_releases/release-ocp-4.2.json
  core-services/release-controller/_releases/release-ocp-4.3.json
  core-services/release-controller/_releases/release-ocp-4.4.json
  core-services/release-controller/_releases/release-ocp-4.5.json
  core-services/release-controller/_releases/release-ocp-4.6.json
  core-services/release-controller/_releases/release-ocp-4.7.json
Labels: approved, lgtm

#10099 Add new nightly images for knative-eventing ci
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next__44.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next__45.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next__46.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-next-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-next-presubmits.yaml
Labels: approved, lgtm

#10101 Repo-brancher: Use same go version as everything else
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
Labels: approved, lgtm

#10066 bump go to 1.13 for cluster-api-provider-libvirt
  ci-operator/config/openshift-priv/cluster-api-provider-libvirt/openshift-priv-cluster-api-provider-libvirt-master.yaml
  ci-operator/config/openshift-priv/cluster-api-provider-libvirt/openshift-priv-cluster-api-provider-libvirt-release-4.6.yaml
  ci-operator/config/openshift-priv/cluster-api-provider-libvirt/openshift-priv-cluster-api-provider-libvirt-release-4.7.yaml
  ci-operator/config/openshift/cluster-api-provider-libvirt/openshift-cluster-api-provider-libvirt-master.yaml
  ci-operator/config/openshift/cluster-api-provider-libvirt/openshift-cluster-api-provider-libvirt-release-4.6.yaml
  ci-operator/config/openshift/cluster-api-provider-libvirt/openshift-cluster-api-provider-libvirt-release-4.7.yaml
Labels: approved, lgtm

#10102 bring sippy under prow control
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#10061 Onboard Eclipse Organization and run che operator e2e
  ci-operator/config/eclipse/che-operator/eclipse-che-operator-master__v4.yaml
  ci-operator/config/eclipse/che-operator/eclipse-che-operator-master__v5.yaml
  ci-operator/jobs/eclipse/che-operator/eclipse-che-operator-master-periodics.yaml
  ci-operator/jobs/eclipse/che-operator/eclipse-che-operator-master-presubmits.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#10100 Build registry replacer
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
Labels: approved, lgtm

#10096 Alert when jobs fail to acquire a lease
  clusters/app.ci/prow-monitoring/mixins/_prometheus/dptp_alerts.libsonnet
  clusters/app.ci/prow-monitoring/mixins/prometheus_out/prometheus-prow-rules_prometheusrule.yaml
Labels: approved, lgtm

#10104 Clean up unused ARO jobs
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
Labels: approved, lgtm, sig/azure

#10105 ci-operator/step-registry/ipi/conf/*/sharednetwork: Quote CONFIG
  ci-operator/step-registry/ipi/conf/aws/sharednetwork/ipi-conf-aws-sharednetwork-commands.sh
  ci-operator/step-registry/ipi/conf/azure/sharednetwork/ipi-conf-azure-sharednetwork-commands.sh
Labels: approved, lgtm

#10093 Include all files in cluster profile CMs
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#10109 Enabling app-sre pipeline for managed-upgrade-operator
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#10081 Add test lanes to test upgrades also from HCO Y-1 version
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-master.yaml
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.5.yaml
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.6.yaml
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.7.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-master-presubmits.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.5-presubmits.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.6-presubmits.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.7-presubmits.yaml
Labels: approved, lgtm

#10074 Drop no longer needed configuration from serverless-operator.
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master__4.3.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master__4.4.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master__4.5.yaml
Labels: approved, lgtm

#10082 projects/cincinnati-ci: add public namespace
  services/cincinnati-ci/README.md
  services/cincinnati-ci/admin_rbac.yaml
Labels: approved, lgtm

#10110 updating owners for rhi-operator
  ci-operator/config/redhat-integration/rhi-operator/OWNERS
  ci-operator/jobs/redhat-integration/rhi-operator/OWNERS
Labels: approved, lgtm

#10046 ci-operator/jobs/openshift/cluster-version-operator: Move master presubmits to GCP
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-master.yaml
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-release-4.4.yaml
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-release-4.5.yaml
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-release-4.6.yaml
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-release-4.7.yaml
  ci-operator/jobs/openshift/cluster-version-operator/openshift-cluster-version-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-version-operator/openshift-cluster-version-operator-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/cluster-version-operator/openshift-cluster-version-operator-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift/cluster-version-operator/openshift-cluster-version-operator-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/cluster-version-operator/openshift-cluster-version-operator-release-4.7-presubmits.yaml
Labels: approved, lgtm

#10117 Lease acquire timeout alert: Trigger on increase rather on existence of metric
  clusters/app.ci/prow-monitoring/mixins/_prometheus/dptp_alerts.libsonnet
  clusters/app.ci/prow-monitoring/mixins/prometheus_out/prometheus-prow-rules_prometheusrule.yaml
Labels: approved, lgtm

#10116 Deploy ci-search tool on app.ci
  clusters/app.ci/cert-manager/search_ingress.yaml
  clusters/app.ci/ci-search/OWNERS
  clusters/app.ci/ci-search/README.md
  clusters/app.ci/ci-search/deploy.yaml
  core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#10084 Fix openshift-ansible scaleup keypair
  cluster/test-deploy/aws-4.0/vars.yaml
Labels: approved, lgtm

#10118 Undeploy ci-search on build01
  clusters/build-clusters/01_cluster/ci-search/OWNERS
  clusters/build-clusters/01_cluster/ci-search/README.md
  clusters/build-clusters/01_cluster/ci-search/deploy.yaml
  core-services/ci-search/deploy.yaml
Labels: approved, lgtm

#10122 Check search-tool with blackbox-prober
  clusters/app.ci/prow-monitoring/additional-scrape-configs_secret.yaml
Labels: approved, lgtm

#10123 release-controller: fix incorrect json fields
  core-services/release-controller/_releases/release-ocp-4.1.json
  core-services/release-controller/_releases/release-ocp-4.2.json
  core-services/release-controller/_releases/release-ocp-4.3.json
  core-services/release-controller/_releases/release-ocp-4.4.json
  core-services/release-controller/_releases/release-ocp-4.5.json
  core-services/release-controller/_releases/release-ocp-4.6.json
  core-services/release-controller/_releases/release-ocp-4.7.json
Labels: approved, lgtm

#10111 adding eo and clo gating jobs to elasticsearch-proxy
  ci-operator/config/openshift/elasticsearch-proxy/openshift-elasticsearch-proxy-master.yaml
  ci-operator/config/openshift/elasticsearch-proxy/openshift-elasticsearch-proxy-release-4.5.yaml
  ci-operator/config/openshift/elasticsearch-proxy/openshift-elasticsearch-proxy-release-4.6.yaml
  ci-operator/config/openshift/elasticsearch-proxy/openshift-elasticsearch-proxy-release-4.7.yaml
  ci-operator/jobs/openshift/elasticsearch-proxy/openshift-elasticsearch-proxy-master-presubmits.yaml
  ci-operator/jobs/openshift/elasticsearch-proxy/openshift-elasticsearch-proxy-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift/elasticsearch-proxy/openshift-elasticsearch-proxy-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/elasticsearch-proxy/openshift-elasticsearch-proxy-release-4.7-presubmits.yaml
Labels: approved, lgtm

#10112 Prepare CI jobs for containers/libpod repository move
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#10126 Improve blackbox probing
  clusters/app.ci/prow-monitoring/additional-scrape-configs_secret.yaml
  clusters/app.ci/prow-monitoring/mixins/_prometheus/dptp_alerts.libsonnet
  clusters/app.ci/prow-monitoring/mixins/prometheus_out/prometheus-prow-rules_prometheusrule.yaml
Labels: approved, lgtm

#10124 Add v19 branch CI, remove v18
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-release-v19.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v19-presubmits.yaml
Labels: approved, lgtm, sig/azure

#10103 Add registry-replacer periodic
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm

#10130 add a verify test to run golangci-lint on splunk-forwarder-operator
  ci-operator/config/openshift/splunk-forwarder-operator/openshift-splunk-forwarder-operator-master.yaml
  ci-operator/jobs/openshift/splunk-forwarder-operator/openshift-splunk-forwarder-operator-master-presubmits.yaml
Labels: approved, lgtm

#9904 moving proxy setup from UPI to multi-step
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/step-registry/gather/proxy/OWNERS
  ci-operator/step-registry/gather/proxy/gather-proxy-commands.sh
  ci-operator/step-registry/gather/proxy/gather-proxy-ref.yaml
  ci-operator/step-registry/ipi/aws/post/proxy/OWNERS
  ci-operator/step-registry/ipi/aws/post/proxy/ipi-aws-post-proxy-chain.yaml
  ci-operator/step-registry/ipi/aws/pre/proxy/OWNERS
  ci-operator/step-registry/ipi/aws/pre/proxy/ipi-aws-pre-proxy-chain.yaml
  ci-operator/step-registry/ipi/conf/aws/proxy/OWNERS
  ci-operator/step-registry/ipi/conf/aws/proxy/ipi-conf-aws-proxy-chain.yaml
  ci-operator/step-registry/ipi/conf/aws/proxy/ipi-conf-aws-proxy-commands.sh
  ci-operator/step-registry/ipi/conf/aws/proxy/ipi-conf-aws-proxy-ref.yaml
  ci-operator/step-registry/openshift/e2e/aws/proxy/OWNERS
  ci-operator/step-registry/openshift/e2e/aws/proxy/openshift-e2e-aws-proxy-workflow.yaml
Labels: approved, lgtm

#10131 Finish name changes for libpod -> podman
  ci-operator/config/containers/libpod/containers-libpod-v1.6.yaml
  ci-operator/config/containers/podman/OWNERS
  ci-operator/jobs/containers/libpod/containers-libpod-v1.6-presubmits.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#10132 Revert "Remove serviceMonitorSelector, we default to our own namespace"
  clusters/app.ci/prow-monitoring/prow_prometheus.yaml
Labels: approved, lgtm

#10134 Stop using the deprecated serviceMonitorSelector
  clusters/app.ci/prow-monitoring/prow_prometheus.yaml
Labels: approved, lgtm

#10125 add knative-eventing release-v0.16.0
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.16.0.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.16.0__44.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.16.0__45.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.16.0__46.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.16.0-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.16.0-presubmits.yaml
Labels: approved, lgtm

#10137 Cleanup job configuration for hyperkube transition test branches
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-marun-testing13.yaml
  ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-marun-testing13-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-marun-testing-presubmits.yaml
Labels: approved, lgtm

#7455 Enable release-note plugin for CRI-O
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, ok-to-test

#10058 adding azure lane to HCO openshift-ci prow jobs
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-master.yaml
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.5.yaml
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.6.yaml
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.7.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-master-presubmits.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.5-presubmits.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.6-presubmits.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.7-presubmits.yaml
Labels: approved, lgtm, ok-to-test

#10022 prow/bugzilla: Switch to 4.5 post GA rules
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#10139 Enable ci config for master branch of openshift/kubernetes
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-master.yaml
  ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-master-postsubmits.yaml
  ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-master-presubmits.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#10115 service/cincinnati-ci: fix RBAC
  services/cincinnati-ci/admin_rbac.yaml
Labels: approved, lgtm

#9960 e2e-metal: add pxe_kernel_args to tf vars
  ci-operator/templates/openshift/installer/cluster-launch-installer-metal-e2e.yaml
Labels: approved, lgtm

#10146 Remove test branch plugin config for openshift-priv/kubernetes
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#10144 Remove `launch` jobs
  ci-operator/config/cri-o/cri-o/cri-o-cri-o-master.yaml
  ci-operator/config/cri-o/cri-o/cri-o-cri-o-release-1.13.yaml
  ci-operator/config/cri-o/cri-o/cri-o-cri-o-release-1.14.yaml
  ci-operator/config/cri-o/cri-o/cri-o-cri-o-release-1.16.yaml
  ci-operator/config/cri-o/cri-o/cri-o-cri-o-release-1.17.yaml
  ci-operator/config/cri-o/cri-o/cri-o-cri-o-release-1.18.yaml
  ci-operator/config/cri-o/cri-o/cri-o-cri-o-release-1.19.yaml
  ci-operator/config/openshift-priv/kubernetes/openshift-priv-kubernetes-master.yaml
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-master.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-3.11.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-3.11.yaml
  ci-operator/jobs/cri-o/cri-o/cri-o-cri-o-master-presubmits.yaml
  ci-operator/jobs/cri-o/cri-o/cri-o-cri-o-release-1.13-presubmits.yaml
  ci-operator/jobs/cri-o/cri-o/cri-o-cri-o-release-1.14-presubmits.yaml
  ci-operator/jobs/cri-o/cri-o/cri-o-cri-o-release-1.16-presubmits.yaml
  ci-operator/jobs/cri-o/cri-o/cri-o-cri-o-release-1.17-presubmits.yaml
  ci-operator/jobs/cri-o/cri-o/cri-o-cri-o-release-1.18-presubmits.yaml
  ci-operator/jobs/cri-o/cri-o/cri-o-cri-o-release-1.19-presubmits.yaml
  ci-operator/jobs/openshift-priv/kubernetes/openshift-priv-kubernetes-master-presubmits.yaml
  ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-3.11-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-3.11-presubmits.yaml
Labels: approved

#10080 make e2e-openstack jobs always run for ovnkube and cno repos
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master-presubmits.yaml
Labels: approved, lgtm

#10151 services/cincinnati-ci: add case sensitive user for steveeJ
  services/cincinnati-ci/admin_rbac.yaml
Labels: approved, lgtm

#10149 Tune down OKD release controller rates
  core-services/release-controller/_releases/release-origin-4.3.json
  core-services/release-controller/_releases/release-origin-4.4.json
  core-services/release-controller/_releases/release-origin-4.5.json
  core-services/release-controller/_releases/release-origin-4.6.json
  core-services/release-controller/_releases/release-origin-4.y-stable.json
Labels: approved, lgtm

#10152 ci-operator/config/openshift/cluster-version-operator: Generic e2e-gcp -> e2e for 4.4+
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-master.yaml
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-release-4.4.yaml
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-release-4.5.yaml
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-release-4.6.yaml
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-release-4.7.yaml
  ci-operator/jobs/openshift/cluster-version-operator/openshift-cluster-version-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-version-operator/openshift-cluster-version-operator-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/cluster-version-operator/openshift-cluster-version-operator-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift/cluster-version-operator/openshift-cluster-version-operator-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/cluster-version-operator/openshift-cluster-version-operator-release-4.7-presubmits.yaml
Labels: approved, lgtm

#10153 OKD: remove upgrade minor test
  core-services/release-controller/_releases/release-origin-4.5.json
  core-services/release-controller/_releases/release-origin-4.6.json
  core-services/release-controller/_releases/release-origin-4.y-stable.json
Labels: approved, lgtm

#10154 OKD: don't mirror 4.3 to origin
  core-services/release-controller/_releases/release-ocp-4.3-ci.json
Labels: approved, lgtm

#10160 Disable branch-protection on eclipse/che-operator
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#9552 vSphere UPI: Migrate to steps
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.4.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.4-presubmits.yaml
  ci-operator/step-registry/openshift/e2e/vsphere/upi/OWNERS
  ci-operator/step-registry/openshift/e2e/vsphere/upi/openshift-e2e-vsphere-upi-workflow.yaml
  ci-operator/step-registry/upi/conf/vsphere/OWNERS
  ci-operator/step-registry/upi/conf/vsphere/ova/OWNERS
  ci-operator/step-registry/upi/conf/vsphere/ova/upi-conf-vsphere-ova-commands.sh
  ci-operator/step-registry/upi/conf/vsphere/ova/upi-conf-vsphere-ova-ref.yaml
  ci-operator/step-registry/upi/conf/vsphere/upi-conf-vsphere-chain.yaml
  ci-operator/step-registry/upi/conf/vsphere/upi-conf-vsphere-commands.sh
  ci-operator/step-registry/upi/conf/vsphere/upi-conf-vsphere-ref.yaml
  ci-operator/step-registry/upi/deprovision/vsphere/OWNERS
  ci-operator/step-registry/upi/deprovision/vsphere/upi-deprovision-vsphere-commands.sh
  ci-operator/step-registry/upi/deprovision/vsphere/upi-deprovision-vsphere-ref.yaml
  ci-operator/step-registry/upi/install/vsphere/OWNERS
  ci-operator/step-registry/upi/install/vsphere/upi-install-vsphere-commands.sh
  ci-operator/step-registry/upi/install/vsphere/upi-install-vsphere-ref.yaml
  ci-operator/step-registry/upi/vsphere/OWNERS
  ci-operator/step-registry/upi/vsphere/post/OWNERS
  ci-operator/step-registry/upi/vsphere/post/upi-vsphere-post-chain.yaml
  ci-operator/step-registry/upi/vsphere/pre/OWNERS
  ci-operator/step-registry/upi/vsphere/pre/upi-vsphere-pre-chain.yaml
  ci-operator/step-registry/upi/vsphere/upi-vsphere-workflow.yaml
Labels: approved, lgtm

#10140 OpenStack: add e2e-openstack to baremetal-runtimecfg
  ci-operator/jobs/openshift/baremetal-runtimecfg/openshift-baremetal-runtimecfg-master-presubmits.yaml
Labels: approved, lgtm

#10161 Reduce knative-eventing release-v0.13.0 requests to 2 and 1 CPU
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.13.0.yaml
Labels: approved, lgtm

#10162 services/cincinnati-ci: temporarily disable RoleBinding
  services/cincinnati-ci/admin_rbac.yaml
Labels: approved, lgtm

#10156 Registry-Replacer: Self-Approve PRs
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm

#10168 Enable separate job for commit verification
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-master.yaml
  ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-master-presubmits.yaml
Labels: approved, lgtm

#10165 ci-operator/step-registry/openshift/kubernetes/e2e/aws: Include "aws" in workflow name
  ci-operator/config/openshift-priv/kubernetes/openshift-priv-kubernetes-master.yaml
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-master.yaml
  ci-operator/step-registry/openshift/kubernetes/e2e/aws/OWNERS
  ci-operator/step-registry/openshift/kubernetes/e2e/aws/openshift-kubernetes-e2e-aws-workflow.yaml
Labels: approved, lgtm

#9556 ppc64le periodic job for OCP 4.5
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
Labels: approved, lgtm

#10173 services/cincinnati-ci: rename RoleBindings
  services/cincinnati-ci/admin_rbac.yaml
Labels: approved, lgtm

#10174 OKD: update promotion intervals for 4.5 and 4.6
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.6-periodics.yaml
Labels: approved, lgtm

#10175 Extend tolerance of the probing alert
  clusters/app.ci/prow-monitoring/mixins/_prometheus/dptp_alerts.libsonnet
  clusters/app.ci/prow-monitoring/mixins/prometheus_out/prometheus-prow-rules_prometheusrule.yaml
Labels: approved, lgtm

#10176 OKD 4.5 periodics: exit early if candidate hash matches with latest hash
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.6-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml
Labels: approved, lgtm

#10171 Onboard che incubator organization and chectl
  ci-operator/config/che-incubator/chectl/OWNERS
  ci-operator/config/che-incubator/chectl/che-incubator-chectl-master__v4.yaml
  ci-operator/config/che-incubator/chectl/che-incubator-chectl-master__v5.yaml
  ci-operator/jobs/che-incubator/chectl/OWNERS
  ci-operator/jobs/che-incubator/chectl/che-incubator-chectl-master-presubmits.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#10178 Add optional job for metal ipi dualstack setup
  ci-operator/config/openshift-metal3/dev-scripts/openshift-metal3-dev-scripts-master.yaml
  ci-operator/jobs/openshift-metal3/dev-scripts/openshift-metal3-dev-scripts-master-presubmits.yaml
Labels: approved, lgtm

#10159 Correct AWS key pair for 3.11
  cluster/test-deploy/aws-atomic/vars.yaml
  cluster/test-deploy/aws-centos/vars.yaml
  cluster/test-deploy/aws-gluster/vars.yaml
Labels: approved, lgtm

#10181 Remove skip_report
  ci-operator/jobs/openshift-metal3/dev-scripts/openshift-metal3-dev-scripts-master-presubmits.yaml
Labels: approved, lgtm

#10179 ci-operator/config/openshift/router: Generic e2e-aws -> e2e for 4.6+
  ci-operator/config/openshift/router/openshift-router-master.yaml
  ci-operator/config/openshift/router/openshift-router-release-4.6.yaml
  ci-operator/config/openshift/router/openshift-router-release-4.7.yaml
  ci-operator/jobs/openshift/router/openshift-router-master-presubmits.yaml
  ci-operator/jobs/openshift/router/openshift-router-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/router/openshift-router-release-4.7-presubmits.yaml
Labels: approved, lgtm

#10185 Update CSI images override for s390x
  ci-operator/templates/openshift/installer/cluster-launch-installer-remote-libvirt-e2e.yaml
Labels: approved, lgtm

#10192 Add linter to assisted-test-infra prow config
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-presubmits.yaml
Labels: approved, lgtm

#10108 Add gather step to snc e2e
  ci-operator/step-registry/code-ready/snc/e2e/code-ready-snc-e2e-workflow.yaml
  ci-operator/step-registry/gather/snc/OWNERS
  ci-operator/step-registry/gather/snc/gather-snc-commands.sh
  ci-operator/step-registry/gather/snc/gather-snc-ref.yaml
Labels: approved, lgtm

#10194 Add jobs for pipeline v0.14.1 release
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.14.1__4.3.yaml
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.14.1__4.4.yaml
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.14.1__4.5.yaml
  ci-operator/jobs/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.14.1-postsubmits.yaml
  ci-operator/jobs/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.14.1-presubmits.yaml
  core-services/image-mirroring/tekton/mapping_tekton_v0_14_quay
Labels: approved, lgtm

#10198 Add Guillaume for crc and snc projects
  ci-operator/step-registry/code-ready/OWNERS
  ci-operator/step-registry/code-ready/crc/OWNERS
  ci-operator/step-registry/code-ready/crc/e2e/OWNERS
  ci-operator/step-registry/code-ready/crc/e2e/test/OWNERS
  ci-operator/step-registry/code-ready/snc/OWNERS
  ci-operator/step-registry/code-ready/snc/e2e/OWNERS
  ci-operator/step-registry/code-ready/snc/e2e/test/OWNERS
  ci-operator/step-registry/gather/crc/OWNERS
  ci-operator/step-registry/upi/gcp/nested/OWNERS
  ci-operator/step-registry/upi/gcp/nested/post/OWNERS
  ci-operator/step-registry/upi/gcp/nested/pre/OWNERS
Labels: approved, lgtm

#10195 Add Tekton Triggers v0.6.1 Release
  ci-operator/config/openshift/tektoncd-triggers/openshift-tektoncd-triggers-release-v0.6.1__4.3.yaml
  ci-operator/config/openshift/tektoncd-triggers/openshift-tektoncd-triggers-release-v0.6.1__4.4.yaml
  ci-operator/config/openshift/tektoncd-triggers/openshift-tektoncd-triggers-release-v0.6.1__4.5.yaml
  ci-operator/jobs/openshift/tektoncd-triggers/openshift-tektoncd-triggers-release-v0.6.1-postsubmits.yaml
  ci-operator/jobs/openshift/tektoncd-triggers/openshift-tektoncd-triggers-release-v0.6.1-presubmits.yaml
  core-services/image-mirroring/tekton/mapping_tekton_triggers_v0_6_1_quay
Labels: approved, lgtm

#10196 Fix image mirroring jo tektoncd jobs
  ci-operator/config/openshift/tektoncd-catalog/openshift-tektoncd-catalog-release-next__4.5.yaml
  ci-operator/config/openshift/tektoncd-catalog/openshift-tektoncd-catalog-release-v0.11__4.3.yaml
  ci-operator/config/openshift/tektoncd-cli/openshift-tektoncd-cli-release-next__4.4.yaml
  ci-operator/config/openshift/tektoncd-cli/openshift-tektoncd-cli-release-next__4.5.yaml
  ci-operator/config/openshift/tektoncd-pipeline-operator/openshift-tektoncd-pipeline-operator-master__4.5.yaml
  ci-operator/config/openshift/tektoncd-pipeline-operator/openshift-tektoncd-pipeline-operator-release-next__4.5.yaml
  ci-operator/config/openshift/tektoncd-pipeline-operator/openshift-tektoncd-pipeline-operator-v0.11.x__4.5.yaml
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-next__4.5.yaml
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.13.2__4.5.yaml
  ci-operator/config/openshift/tektoncd-triggers/openshift-tektoncd-triggers-release-next__4.5.yaml
  ci-operator/jobs/openshift/tektoncd-cli/openshift-tektoncd-cli-release-next-presubmits.yaml
Labels: approved, lgtm

#8238 Add OpenStack cloud with ppc64le compute nodes for CI
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e-ppc64le.yaml
Labels: approved, lgtm

#10188 Remove all refs of prow-monitoring on api.ci
  Makefile
  clusters/app.ci/prow-monitoring/admin_user_roles.yaml
  clusters/app.ci/prow-monitoring/debug/admin_user_roles.yaml
  clusters/app.ci/prow-monitoring/prometheus-cache.yaml
  core-services/monitoring/OWNERS
  core-services/monitoring/README.md
  core-services/prow/02_config/_plugins.yaml
  core-services/prow/03_deployment/admin_config_updater_rbac.yaml
  core-services/prow/03_deployment/admin_hook_rbac.yaml
  core-services/various_rbac/admin_user_roles.yaml
Labels: approved, lgtm

#10169 Switch all periodic jobs to use ovn sdn.
  ci-operator/config/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-master.yaml
  ci-operator/config/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.4.yaml
  ci-operator/config/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.5.yaml
  ci-operator/jobs/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-master-periodics.yaml
  ci-operator/jobs/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.4-periodics.yaml
  ci-operator/jobs/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.5-periodics.yaml
Labels: approved, lgtm

#10202 metal-e2e: fix variable expansion
  ci-operator/templates/openshift/installer/cluster-launch-installer-metal-e2e.yaml
Labels: approved, lgtm

#10183 Reduce dptp-cm mem requests to 2gig so it can be scheduled
  clusters/app.ci/assets/dptp-controller-manager.yaml
Labels: approved, lgtm

#10207 Bump prow's grace_period to 30m
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#10043 add e2e test for registration-operator
  ci-operator/config/open-cluster-management/registration-operator/open-cluster-management-registration-operator-master.yaml
Labels: approved, lgtm

#10205 [wmco] Stop excluding WMCO image while promoting
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-master.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.5.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.6.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.7.yaml
Labels: approved, lgtm
