Repository openshift/release, pull requests merged in 2020-03, with the labels that each got.

#7397 adding images
  core-services/image-mirroring/knative/mapping_knative_nightly_quay
Labels: approved, lgtm, size/XS

#7362 Add a 4.3 periodic job to test sctp on OCP 4.3
  ci-operator/config/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-sctpci-release-v4.3.yaml
  ci-operator/jobs/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-sctpci-release-v4.3-periodics.yaml
  ci-operator/jobs/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-sctpci-release-v4.3-postsubmits.yaml
  ci-operator/jobs/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-sctpci-release-v4.3-presubmits.yaml
Labels: approved, lgtm, size/L

#7400 Update openshift-acme for v2
  ci-operator/config/tnozicka/openshift-acme/tnozicka-openshift-acme-master.yaml
  ci-operator/jobs/tnozicka/openshift-acme/tnozicka-openshift-acme-master-presubmits.yaml
Labels: approved, lgtm, size/L

#7398 Crier: Enable prowjob and kubernetes reporter
  core-services/prow/02_config/_config.yaml
  core-services/prow/03_deployment/admin_crier_rbac.yaml
  core-services/prow/03_deployment/crier.yaml
Labels: approved, lgtm, size/M

#7406 ci-operator: simplify telemeter image opts
  ci-operator/config/openshift/telemeter/openshift-telemeter-master.yaml
  ci-operator/config/openshift/telemeter/openshift-telemeter-release-4.5.yaml
  ci-operator/config/openshift/telemeter/openshift-telemeter-release-4.6.yaml
Labels: approved, lgtm, size/S

#7407 Fix crier flags, only one of -build-cluster/-kubeconfig must be set
  core-services/prow/03_deployment/crier.yaml
Labels: approved, lgtm, size/XS

#7396 Test Openshift Serverless on Openshift 4.4.
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master__4.4.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master-periodics.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master-presubmits.yaml
Labels: approved, lgtm, size/L

#7395 Add a periodic job: periodic-ci-image-import-to-build01
  ci-operator/jobs/infra-periodics.yaml
  clusters/build-clusters/01_cluster/openshift/ci-operator/admin_image-importer_rbac.yaml
Labels: approved, lgtm, size/M

#7399 Update repos for Ironic image
  ci-operator/config/openshift/ironic-image/openshift-ironic-image-master.yaml
  ci-operator/config/openshift/ironic-image/openshift-ironic-image-release-4.4.yaml
  ci-operator/config/openshift/ironic-image/openshift-ironic-image-release-4.5.yaml
  ci-operator/config/openshift/ironic-image/openshift-ironic-image-release-4.6.yaml
Labels: approved, lgtm, size/S

#7402 Update base repos for ironic images
  ci-operator/config/openshift/ironic-hardware-inventory-recorder-image/openshift-ironic-hardware-inventory-recorder-image-master.yaml
  ci-operator/config/openshift/ironic-hardware-inventory-recorder-image/openshift-ironic-hardware-inventory-recorder-image-release-4.4.yaml
  ci-operator/config/openshift/ironic-hardware-inventory-recorder-image/openshift-ironic-hardware-inventory-recorder-image-release-4.5.yaml
  ci-operator/config/openshift/ironic-hardware-inventory-recorder-image/openshift-ironic-hardware-inventory-recorder-image-release-4.6.yaml
  ci-operator/config/openshift/ironic-inspector-image/openshift-ironic-inspector-image-master.yaml
  ci-operator/config/openshift/ironic-inspector-image/openshift-ironic-inspector-image-release-4.4.yaml
  ci-operator/config/openshift/ironic-inspector-image/openshift-ironic-inspector-image-release-4.5.yaml
  ci-operator/config/openshift/ironic-inspector-image/openshift-ironic-inspector-image-release-4.6.yaml
  ci-operator/config/openshift/ironic-ipa-downloader/openshift-ironic-ipa-downloader-master.yaml
  ci-operator/config/openshift/ironic-ipa-downloader/openshift-ironic-ipa-downloader-release-4.4.yaml
  ci-operator/config/openshift/ironic-ipa-downloader/openshift-ironic-ipa-downloader-release-4.5.yaml
  ci-operator/config/openshift/ironic-ipa-downloader/openshift-ironic-ipa-downloader-release-4.6.yaml
Labels: approved, lgtm, size/M

#7411 Fix openshift/api config and migrate from travis
  ci-operator/config/openshift/api/openshift-api-master.yaml
  ci-operator/jobs/openshift/api/openshift-api-master-presubmits.yaml
Labels: approved, lgtm, size/L

#7394 Create the csi-driver-manila-operator repository
  ci-operator/config/openshift/csi-driver-manila-operator/OWNERS
  ci-operator/config/openshift/csi-driver-manila-operator/openshift-csi-driver-manila-operator-master.yaml
  ci-operator/jobs/openshift/csi-driver-manila-operator/OWNERS
  ci-operator/jobs/openshift/csi-driver-manila-operator/openshift-csi-driver-manila-operator-master-presubmits.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/L

#7408 Import `oc-rpms` in private imagestreams
  core-services/openshift-priv/4.2-priv-is.yaml
  core-services/openshift-priv/4.3-priv-is.yaml
  core-services/openshift-priv/4.4-priv-is.yaml
  core-services/openshift-priv/4.5-priv-is.yaml
  core-services/openshift-priv/4.6-priv-is.yaml
Labels: approved, lgtm, size/M

#7421 assembler: Run build *and* test
  ci-operator/config/coreos/coreos-assembler/coreos-coreos-assembler-master.yaml
Labels: approved, lgtm, size/XS

#7305 SRVKE-334 Images for upstream Knative eventing operator
  ci-operator/config/openshift-knative/eventing-operator/OWNERS
  ci-operator/config/openshift-knative/eventing-operator/openshift-knative-eventing-operator-release-0.12.yaml
  ci-operator/jobs/openshift-knative/eventing-operator/OWNERS
  ci-operator/jobs/openshift-knative/eventing-operator/openshift-knative-eventing-operator-release-0.12-postsubmits.yaml
  ci-operator/jobs/openshift-knative/eventing-operator/openshift-knative-eventing-operator-release-0.12-presubmits.yaml
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm, size/L

#7422 Migrate presubmits for installer repo
  ci-operator/jobs/openshift/installer/openshift-installer-fcos-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.6-presubmits.yaml
Labels: approved, lgtm, size/L

#7423 allow the SA in the mirroring job for psap ns
  core-services/image-mirroring/admin_openshift-psap_list.yaml
Labels: approved, lgtm, size/M

#7425 Revert "Import `oc-rpms` in private imagestreams"
  core-services/openshift-priv/4.2-priv-is.yaml
  core-services/openshift-priv/4.3-priv-is.yaml
  core-services/openshift-priv/4.4-priv-is.yaml
  core-services/openshift-priv/4.5-priv-is.yaml
  core-services/openshift-priv/4.6-priv-is.yaml
Labels: approved, lgtm, size/M

#7427 add RBAC for psap ns
  cluster/ci/config/prow/openshift/ci-operator/roles.yaml
Labels: approved, lgtm, size/M

#7428 Mark functional tests optional
  ci-operator/jobs/openshift/ocs-operator/openshift-ocs-operator-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#7203 Add special-resource-operator to the OpenShift CI
  ci-operator/config/openshift-psap/special-resource-operator/OWNERS
  ci-operator/config/openshift-psap/special-resource-operator/openshift-psap-special-resource-operator-master.yaml
  ci-operator/jobs/openshift-psap/special-resource-operator/OWNERS
  ci-operator/jobs/openshift-psap/special-resource-operator/openshift-psap-special-resource-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift-psap/special-resource-operator/openshift-psap-special-resource-operator-master-presubmits.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/XL

#7310 build01: add a job to run upgrades daily
  ci-operator/jobs/infra-periodics.yaml
  clusters/build-clusters/01_cluster/openshift/upgrader/README.md
  clusters/build-clusters/01_cluster/openshift/upgrader/admin_rbac.yaml
Labels: approved, lgtm, size/M

#7430 Add --rm to remove zombie container
  Makefile
Labels: approved, lgtm, size/S

#7426 Migrate presubmits of origin repo
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-3.10-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-3.11-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.6-presubmits.yaml
Labels: approved, lgtm, size/L

#7410 Use OSP16 repos again in Kuryr builds
  ci-operator/config/openshift/kuryr-kubernetes/openshift-kuryr-kubernetes-master.yaml
  ci-operator/config/openshift/kuryr-kubernetes/openshift-kuryr-kubernetes-release-4.4.yaml
Labels: approved, lgtm, size/XS

#7435 Use apps/v1 for all Deployments
  cluster/ci/monitoring/debug/grafana_deploy.yaml
  cluster/ci/monitoring/grafana_deploy.yaml
  cluster/ci/monitoring/prometheus_operator_deploy.yaml
  core-services/prow/03_deployment/boskos_reaper.yaml
Labels: approved, lgtm, size/S

#7437 switch integreatly base iamge to ubi
  ci-operator/config/integr8ly/integreatly-operator/integr8ly-integreatly-operator-master.yaml
Labels: approved, lgtm, size/XS

#7438 add manifest check to pr
  ci-operator/config/integr8ly/integreatly-operator/integr8ly-integreatly-operator-master.yaml
  ci-operator/jobs/integr8ly/integreatly-operator/integr8ly-integreatly-operator-master-presubmits.yaml
Labels: approved, lgtm, size/M

#7413 Restore OpenStack boskos lease to its original value
  core-services/prow/02_config/_boskos.yaml
Labels: approved, lgtm, size/XS

#7441 Import `oc-rpms` in private imagestreams
  core-services/openshift-priv/4.2-priv-is.yaml
  core-services/openshift-priv/4.3-priv-is.yaml
  core-services/openshift-priv/4.4-priv-is.yaml
  core-services/openshift-priv/4.5-priv-is.yaml
  core-services/openshift-priv/4.6-priv-is.yaml
Labels: approved, lgtm, size/M

#7424 add 4.4 endurance cluster
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
  ci-operator/templates/openshift/endurance/endurance-install.yaml
Labels: approved, lgtm, size/L

#7448 Add more reviewers for build01
  clusters/build-clusters/01_cluster/assets/admin_cluster-reader-0_list.yaml
Labels: approved, lgtm, size/XS

#7450 fix indent level for service account on upgrade
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm, size/XS

#7451 removal of the libpod project
  ci-operator/config/containers/libpod/OWNERS
  ci-operator/config/containers/libpod/containers-libpod-master.yaml
  ci-operator/jobs/containers/libpod/OWNERS
  ci-operator/jobs/containers/libpod/containers-libpod-master-presubmits.yaml
  projects/libpod/libpod.yaml
Labels: approved, lgtm, size/L

#7449 Fix secret's mount_path for cincinnati jobs
  ci-operator/config/openshift/cincinnati/openshift-cincinnati-master.yaml
  ci-operator/jobs/openshift/cincinnati/openshift-cincinnati-master-presubmits.yaml
Labels: approved, lgtm, size/S

#7144 Add node-feature-discovery to openshift-psap
  core-services/image-mirroring/openshift-psap/OWNERS
  core-services/image-mirroring/openshift-psap/mapping_openshift-psap_4_2
  core-services/image-mirroring/openshift-psap/mapping_openshift-psap_4_3
  core-services/image-mirroring/openshift-psap/mapping_openshift-psap_master
Labels: approved, lgtm, size/XS

#7452 release: Add a stub job for building payloads
  ci-operator/jobs/openshift/release/openshift-release-infra-periodics.yaml
Labels: approved, lgtm, size/M

#7322 Add new jobs for the openshift network metrics daemon
  ci-operator/config/openshift/network-metrics-daemon/OWNERS
  ci-operator/config/openshift/network-metrics-daemon/openshift-network-metrics-daemon-master.yaml
  ci-operator/jobs/openshift/network-metrics-daemon/OWNERS
  ci-operator/jobs/openshift/network-metrics-daemon/openshift-network-metrics-daemon-master-presubmits.yaml
Labels: approved, lgtm, size/L

#7440 Crier: Use own SA rather than abusing planks
  core-services/ci-secret-bootstrap/_config.yaml
  core-services/prow/03_deployment/crier.yaml
Labels: approved, lgtm, size/XS

#7312 Adds 4.3 items for route-override-cni and whereabouts-cni
  ci-operator/config/openshift/route-override-cni/openshift-route-override-cni-release-4.3.yaml
  ci-operator/config/openshift/whereabouts-cni/openshift-whereabouts-cni-release-4.3.yaml
  ci-operator/jobs/openshift/route-override-cni/openshift-route-override-cni-release-4.3-postsubmits.yaml
  ci-operator/jobs/openshift/route-override-cni/openshift-route-override-cni-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/whereabouts-cni/openshift-whereabouts-cni-release-4.3-postsubmits.yaml
  ci-operator/jobs/openshift/whereabouts-cni/openshift-whereabouts-cni-release-4.3-presubmits.yaml
Labels: approved, lgtm, size/XL

#6558 OKD 4.4: run e2e test on machine-os-content promotion
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
Labels: approved, lgtm, size/L

#7458 Adding Knative eventing 0.13 jobs
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.13.0.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.13.0-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.13.0-presubmits.yaml
  core-services/image-mirroring/knative/mapping_knative_v0_13_quay
Labels: approved, lgtm, size/L

#7466 Temporarily delete osde2e integration tests.
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-master-periodics.yaml
Labels: approved, lgtm, size/L

#7460 enable approver plugin for openshift/coredns
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/XS

#7464 ignore cluster check failures during initial install for endurance cluster
  ci-operator/templates/openshift/endurance/endurance-install.yaml
Labels: approved, lgtm, size/XS

#7461 Remove obsolete targets from Makefile
  Makefile
Labels: approved, lgtm, size/S

#7465 Add aws console link to build01's readme
  clusters/build-clusters/01_cluster/README.md
Labels: approved, lgtm, size/XS

#7471 promote nfd images to psap ns
  ci-operator/config/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-master.yaml
  ci-operator/config/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-release-4.1.yaml
  ci-operator/config/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-release-4.2.yaml
  ci-operator/config/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-release-4.3.yaml
  ci-operator/config/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-release-4.4.yaml
  ci-operator/config/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-release-4.6.yaml
  ci-operator/jobs/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-release-4.6-presubmits.yaml
Labels: approved, lgtm, size/S

#7476 eventing update: remove cronjob image
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next.yaml
Labels: approved, lgtm, size/XS

#7474 alert on endurance 4.4 failures
  cluster/ci/monitoring/mixins/prometheus/job_failures_config.libsonnet
  cluster/ci/monitoring/mixins/prometheus_out/prometheus_rule_prow.yaml
Labels: approved, lgtm, size/S

#7477 Use dedicated GCP serviceaccount for crier
  core-services/ci-secret-bootstrap/_config.yaml
  core-services/prow/03_deployment/crier.yaml
Labels: approved, lgtm, size/S

#7463 Use reasonable pod pending and unscheduled timeout
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm, size/XS

#7479 Make the OpenStack cloud options configurable
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e.yaml
Labels: approved, lgtm, size/S

#7481 use Squash merge strategy
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm, size/XS

#7480 Remove artifact uploader
  core-services/prow/03_deployment/admin_artifact-uploader_rbac.yaml
  core-services/prow/03_deployment/artifact-uploader.yaml
Labels: approved, lgtm, size/L

#7442 Autoowners: Run daily
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm, size/XS

#7483 mirror: Stop mirroring support-operator
  core-services/image-mirroring/openshift/mapping_origin_4_1
  core-services/image-mirroring/openshift/mapping_origin_4_4
  core-services/image-mirroring/openshift/mapping_origin_4_5
  core-services/image-mirroring/openshift/mapping_origin_4_6
Labels: approved, lgtm

#7484 Revert "Merge pull request #7466 from meowfaceman/disable-osde2e-int"
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-master-periodics.yaml
Labels: approved, lgtm, size/L

#7487 semantics: ignore generated jobs
  hack/validate-prow-job-semantics.py
Labels: approved, lgtm, size/XS

#7486 prow: add default requests and limits for pod-utils containers
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm, size/S

#7492 Revert "Merge pull request #7486 from stevekuznetsov/skuznets/add-def…
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm, size/S

#7439 oauth-proxy: add imagestream tag we want to publish
  ci-operator/config/openshift/oauth-proxy/openshift-oauth-proxy-samples-operator-4.4.yaml
  ci-operator/jobs/openshift/oauth-proxy/openshift-oauth-proxy-samples-operator-4.4-postsubmits.yaml
  ci-operator/jobs/openshift/oauth-proxy/openshift-oauth-proxy-samples-operator-4.4-presubmits.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/L

#7416 Move base ironic images to 4.5 repos
  ci-operator/config/openshift/ironic-hardware-inventory-recorder-image/openshift-ironic-hardware-inventory-recorder-image-master.yaml
  ci-operator/config/openshift/ironic-hardware-inventory-recorder-image/openshift-ironic-hardware-inventory-recorder-image-release-4.5.yaml
  ci-operator/config/openshift/ironic-hardware-inventory-recorder-image/openshift-ironic-hardware-inventory-recorder-image-release-4.6.yaml
  ci-operator/config/openshift/ironic-image/openshift-ironic-image-master.yaml
  ci-operator/config/openshift/ironic-image/openshift-ironic-image-release-4.5.yaml
  ci-operator/config/openshift/ironic-image/openshift-ironic-image-release-4.6.yaml
  ci-operator/config/openshift/ironic-inspector-image/openshift-ironic-inspector-image-master.yaml
  ci-operator/config/openshift/ironic-inspector-image/openshift-ironic-inspector-image-release-4.5.yaml
  ci-operator/config/openshift/ironic-inspector-image/openshift-ironic-inspector-image-release-4.6.yaml
  ci-operator/config/openshift/ironic-ipa-downloader/openshift-ironic-ipa-downloader-master.yaml
  ci-operator/config/openshift/ironic-ipa-downloader/openshift-ironic-ipa-downloader-release-4.5.yaml
  ci-operator/config/openshift/ironic-ipa-downloader/openshift-ironic-ipa-downloader-release-4.6.yaml
Labels: approved, lgtm, size/M

#7355 remove all tags from the private imagestreams
  core-services/openshift-priv/4.1-priv-is.yaml
  core-services/openshift-priv/4.2-priv-is.yaml
  core-services/openshift-priv/4.3-priv-is.yaml
  core-services/openshift-priv/4.4-priv-is.yaml
  core-services/openshift-priv/4.5-priv-is.yaml
  core-services/openshift-priv/4.6-priv-is.yaml
Labels: approved, lgtm, size/XXL

#7502 change config_updater regexes for oauth-proxy-samples-operator
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/XS

#7503 prow: Use a sidecar debug image temporarily
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm, size/XS

#7504 prow: Test with a fixed version of the sidecar
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm, size/XS

#7501 sidecar: set absurdly high mem limits
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm, size/S

#7482 Adding contrib 0.13 jobs
  ci-operator/config/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-v0.13.0.yaml
  ci-operator/config/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-v0.13.0__4.4.yaml
  ci-operator/jobs/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-v0.13.0-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-v0.13.0-presubmits.yaml
  core-services/image-mirroring/knative/mapping_knative_v0_13_quay
Labels: approved, lgtm, size/XL

#7507 Revert "Merge pull request #7278 from stevekuznetsov/skuznets/no-cher…
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/L

#7514 Remove netwroking-istio from release-next
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-next__4.3.yaml
Labels: approved, lgtm, size/XS

#7509 remove temporary experimental private jobs
  ci-operator/config/openshift-priv/ci-experiment-origin/OWNERS
  ci-operator/config/openshift-priv/ci-experiment-origin/README.md
  ci-operator/config/openshift-priv/ci-experiment-origin/openshift-priv-ci-experiment-origin-master.yaml
  ci-operator/jobs/openshift-priv/ci-experiment-origin/OWNERS
  ci-operator/jobs/openshift-priv/ci-experiment-origin/openshift-priv-ci-experiment-origin-master-presubmits.yaml
Labels: approved, lgtm, size/XXL

#7516 Make gcp actuator jobs required
  ci-operator/jobs/openshift/cluster-api-provider-gcp/openshift-cluster-api-provider-gcp-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#7469 Remove monitoring for boskos-metrics
  cluster/ci/monitoring/Makefile
  cluster/ci/monitoring/boskos_service_monitor.yaml
  hack/monitor_prow.py
Labels: approved, lgtm, size/S

#7511 Autoowners periodic: Stop bothering humans
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm, size/XS

#7488 Adding the ability for config-updater to get routes in the multi arch release namespaces
  core-services/prow/03_deployment/admin_config_updater_rbac.yaml
Labels: approved, lgtm, size/S

#7517 Validate SBO releases
  ci-operator/config/redhat-developer/service-binding-operator/redhat-developer-service-binding-operator-master.yaml
  ci-operator/config/redhat-developer/service-binding-operator/redhat-developer-service-binding-operator-master__4.4.yaml
  ci-operator/jobs/redhat-developer/service-binding-operator/redhat-developer-service-binding-operator-master-periodics.yaml
Labels: approved, lgtm, size/L

#7499 Send build01 alerts to #ops-testplatform-spam
  clusters/build-clusters/01_cluster/openshift-monitoring/alertmanager-main_secret_template.yaml
Labels: approved, lgtm, size/XS

#7510 Remove canary prefix from cnv periodic jobs
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#7523 bugzilla: require verified dependent bugs for 4.5
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/S

#7521 Remove branch-protector for containers org
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm, size/XS

#7526 mirroring: Update all image mirrors to latest
  core-services/image-mirroring/openshift/mapping_origin_4_3
  core-services/image-mirroring/openshift/mapping_origin_4_4
  core-services/image-mirroring/openshift/mapping_origin_4_5
  core-services/image-mirroring/openshift/mapping_origin_4_6
Labels: approved, lgtm, size/L

#7289 Make DPTP assigned as top-level reviewers for jobs
  ci-operator/config/OWNERS
  ci-operator/jobs/OWNERS
Labels: approved, lgtm, size/M

#7373 Move dont-gc-me-bro under core-services
  core-services/prevent-image-gc/OWNERS
  core-services/prevent-image-gc/README.md
  core-services/prevent-image-gc/daemonset.yaml
Labels: approved, lgtm, size/M

#7529 fall back into ocp ns
  ci-operator/config/openshift-psap/special-resource-operator/openshift-psap-special-resource-operator-master.yaml
  ci-operator/config/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-master.yaml
  ci-operator/config/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-release-4.1.yaml
  ci-operator/config/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-release-4.2.yaml
  ci-operator/config/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-release-4.3.yaml
  ci-operator/config/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-release-4.4.yaml
  ci-operator/config/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-release-4.6.yaml
  ci-operator/jobs/openshift-psap/special-resource-operator/openshift-psap-special-resource-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-release-4.6-presubmits.yaml
  core-services/image-mirroring/openshift-psap/mapping_openshift-psap_master
Labels: approved, lgtm, size/M

#7519 Add bugzilla rules for ocs-operator release-4.3
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/XS

#7538 Update app.ci data
  clusters/app.ci/.diff
  clusters/app.ci/prow/02_config/_config.yaml
  clusters/app.ci/prow/02_config/_plugins.yaml
  clusters/app.ci/prow/03_deployment/PROW_RESOURCES.md
  clusters/app.ci/prow/03_deployment/adapter_imagestreams.yaml
  clusters/app.ci/prow/03_deployment/boskos.yaml
  clusters/app.ci/prow/03_deployment/boskos_cleaner.yaml
  clusters/app.ci/prow/03_deployment/boskos_reaper.yaml
  clusters/app.ci/prow/03_deployment/cherrypick.yaml
  clusters/app.ci/prow/03_deployment/crier.yaml
  clusters/app.ci/prow/03_deployment/deck.yaml
  clusters/app.ci/prow/03_deployment/exporter.yaml
  clusters/app.ci/prow/03_deployment/ghproxy.yaml
  clusters/app.ci/prow/03_deployment/hook.yaml
  clusters/app.ci/prow/03_deployment/horologium.yaml
  clusters/app.ci/prow/03_deployment/jenkins_operator.yaml
  clusters/app.ci/prow/03_deployment/needs_rebase.yaml
  clusters/app.ci/prow/03_deployment/plank.yaml
  clusters/app.ci/prow/03_deployment/refresh.yaml
  clusters/app.ci/prow/03_deployment/sinker.yaml
  clusters/app.ci/prow/03_deployment/statusreconciler.yaml
  clusters/app.ci/prow/03_deployment/tide.yaml
  clusters/app.ci/prow/03_deployment/tot.yaml
  core-services/prow/03_deployment/PROW_RESOURCES.md
  core-services/prow/03_deployment/adapter_imagestreams.yaml
Labels: approved, lgtm, size/L

#7536 label_sync: add labels to openshift-psap
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm, size/XS

#7534 infra-periodic: remove duplicate 'cron'
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm, size/XS

#7539 set automountServiceAccountToken: true
  ci-operator/jobs/infra-image-mirroring.yaml
Labels: approved, lgtm, size/XS

#7528 Cincinnati: explicitely set artifacts dir for e2e tests
  ci-operator/config/openshift/cincinnati/openshift-cincinnati-master.yaml
  ci-operator/jobs/openshift/cincinnati/openshift-cincinnati-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#7546 openshift-kni: make e2e tests mandatory
  ci-operator/jobs/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-master-presubmits.yaml
  ci-operator/jobs/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift-kni/performance-addon-operators/openshift-kni-performance-addon-operators-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#7527 Setup CI for Serverless release 1.5.
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.5.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.5__4.3.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.5__4.4.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.5-postsubmits.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.5-presubmits.yaml
Labels: approved, lgtm, size/XL

#7549 Rename app-ci-job and label to clarify its a canary
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
Labels: approved, lgtm, size/XS

#7325 Periodic job for Serverless on GCP
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master__4.3-azure.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master__4.3-gcp.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master__4.3-vsphere.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master-periodics.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master-presubmits.yaml
Labels: approved, lgtm, size/L

#7456 Update nfsplugin tests
  ci-operator/config/openshift-priv/csi-driver-nfs/openshift-priv-csi-driver-nfs-master.yaml
  ci-operator/config/openshift-priv/csi-driver-nfs/openshift-priv-csi-driver-nfs-release-4.4.yaml
  ci-operator/config/openshift-priv/csi-driver-nfs/openshift-priv-csi-driver-nfs-release-4.5.yaml
  ci-operator/config/openshift-priv/csi-driver-nfs/openshift-priv-csi-driver-nfs-release-4.6.yaml
  ci-operator/config/openshift/csi-driver-nfs/openshift-csi-driver-nfs-master.yaml
  ci-operator/config/openshift/csi-driver-nfs/openshift-csi-driver-nfs-release-4.4.yaml
  ci-operator/config/openshift/csi-driver-nfs/openshift-csi-driver-nfs-release-4.5.yaml
  ci-operator/config/openshift/csi-driver-nfs/openshift-csi-driver-nfs-release-4.6.yaml
  ci-operator/jobs/openshift-priv/csi-driver-nfs/openshift-priv-csi-driver-nfs-master-presubmits.yaml
  ci-operator/jobs/openshift-priv/csi-driver-nfs/openshift-priv-csi-driver-nfs-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift-priv/csi-driver-nfs/openshift-priv-csi-driver-nfs-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift-priv/csi-driver-nfs/openshift-priv-csi-driver-nfs-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/csi-driver-nfs/openshift-csi-driver-nfs-master-presubmits.yaml
  ci-operator/jobs/openshift/csi-driver-nfs/openshift-csi-driver-nfs-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/csi-driver-nfs/openshift-csi-driver-nfs-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift/csi-driver-nfs/openshift-csi-driver-nfs-release-4.6-presubmits.yaml
Labels: approved, lgtm, size/XXL

#7548 refactor: Parametrize container engine in Makefile
  Makefile
Labels: approved, lgtm, size/S

#7393 Revert "Make check_prometheus_rules can-be-rehearsed"
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#7525 build01: bump system reserved for kubelets
  clusters/build-clusters/01_cluster/kubelet/admin_config.yaml
Labels: approved, lgtm, size/S

#7553 add plugins for open-cluster-management org
  clusters/app.ci/.diff
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/M

#7554 endurance job/template refinement
  ci-operator/templates/openshift/endurance/endurance-install.yaml
Labels: approved, lgtm, size/S

#7555 Fix flags for branch-ci-openshift-release-master-app-ci-apply-canary
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
Labels: approved, lgtm, size/S

#7557 Remove stage jobs temporarily for hive-stage migration
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-master-periodics.yaml
Labels: approved, lgtm, size/L

#7518 remove buildcop alerts for everything except periodic mirroring job
  cluster/ci/monitoring/mixins/prometheus/build_cop_alerts.libsonnet
  cluster/ci/monitoring/mixins/prometheus_out/prometheus_rule_prow.yaml
Labels: approved, lgtm, size/L

#7540 installer: upi-e2e template to enable modified gcp upi workflow.
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
Labels: approved, lgtm, size/M

#7559 Fix promotion name of the serverless 1.5 release.
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.5__4.3.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.5__4.4.yaml
Labels: approved, lgtm, size/XS

#7567 Add prow configs for gcp-project-operator
  ci-operator/config/openshift/gcp-project-operator/OWNERS
  ci-operator/config/openshift/gcp-project-operator/openshift-gcp-project-operator-master.yaml
  ci-operator/jobs/openshift/gcp-project-operator/OWNERS
  ci-operator/jobs/openshift/gcp-project-operator/openshift-gcp-project-operator-master-presubmits.yaml
  clusters/app.ci/.diff
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/L

#7436 Add csi-driver-manila-operator image
  ci-operator/config/openshift/csi-driver-manila-operator/openshift-csi-driver-manila-operator-master.yaml
  ci-operator/config/openshift/csi-driver-manila-operator/openshift-csi-driver-manila-operator-release-4.5.yaml
  ci-operator/config/openshift/csi-driver-manila-operator/openshift-csi-driver-manila-operator-release-4.6.yaml
  ci-operator/jobs/openshift/csi-driver-manila-operator/openshift-csi-driver-manila-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/csi-driver-manila-operator/openshift-csi-driver-manila-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/csi-driver-manila-operator/openshift-csi-driver-manila-operator-release-4.5-postsubmits.yaml
  ci-operator/jobs/openshift/csi-driver-manila-operator/openshift-csi-driver-manila-operator-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift/csi-driver-manila-operator/openshift-csi-driver-manila-operator-release-4.6-postsubmits.yaml
  ci-operator/jobs/openshift/csi-driver-manila-operator/openshift-csi-driver-manila-operator-release-4.6-presubmits.yaml
Labels: approved, lgtm, size/XL

#7569 Add gcp-project-operator jenkins context
  clusters/app.ci/.diff
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm, size/S

#7575 Add adduarte to openstack approvers
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#7564 Run tests and create images for Knative Serving 0.13.
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-v0.13.0__4.3.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-v0.13.0-postsubmits.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-v0.13.0-presubmits.yaml
Labels: approved, lgtm, size/L

#7561 Fix statusreconciler deployment to be valid
  clusters/app.ci/prow/03_deployment/statusreconciler.yaml
  core-services/prow/03_deployment/statusreconciler.yaml
Labels: approved, lgtm, size/S

#7562 Prow: Remove references to the prowjobs/status subresource
  clusters/app.ci/prow/03_deployment/admin_exporter_rbac.yaml
  clusters/app.ci/prow/03_deployment/admin_jenkins_operator_rbac.yaml
  clusters/app.ci/prow/03_deployment/admin_plank_rbac.yaml
  core-services/prow/03_deployment/admin_exporter_rbac.yaml
  core-services/prow/03_deployment/admin_jenkins_operator_rbac.yaml
  core-services/prow/03_deployment/admin_plank_rbac.yaml
Labels: approved, lgtm, size/M

#7576 Jenkins operator: Do not report
  clusters/app.ci/prow/03_deployment/jenkins_operator.yaml
  core-services/prow/03_deployment/jenkins_operator.yaml
Labels: approved, lgtm, size/XS

#7577 Keep app.ci config in sync with api.ci
  clusters/app.ci/.diff
  clusters/app.ci/prow/02_config/_config.yaml
  clusters/app.ci/prow/02_config/_plugins.yaml
  hack/verify-app-ci.sh
Labels: approved, lgtm, size/L

#7581 Fix ghproxy deployment
  clusters/app.ci/prow/03_deployment/ghproxy.yaml
  core-services/prow/03_deployment/ghproxy.yaml
Labels: approved, lgtm, size/XS

#7583 cluster-api-provider-azure: Use makefile for unit tests
  ci-operator/config/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-master.yaml
  ci-operator/config/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-release-4.5.yaml
  ci-operator/config/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-release-4.6.yaml
Labels: approved, lgtm, size/XS

#7584 add login lines to mirror job
  ci-operator/jobs/infra-image-mirroring.yaml
Labels: approved, lgtm, size/XS

#7498 OKD 4.4: use origin's "4.4:machine-os-content" as latest
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
Labels: approved, lgtm, size/XS

#7582 Add openshift-kubernetes-oc-4.5-kubernetes-1.18.0
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-oc-4.5-kubernetes-1.18.0-beta.2.yaml
  ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-oc-4.5-kubernetes-1.18.0-beta.2-presubmits.yaml
Labels: approved, lgtm, size/L

#7563 Add csi-driver-nfs image
  ci-operator/config/openshift/csi-driver-nfs/openshift-csi-driver-nfs-master.yaml
  ci-operator/config/openshift/csi-driver-nfs/openshift-csi-driver-nfs-release-4.5.yaml
  ci-operator/config/openshift/csi-driver-nfs/openshift-csi-driver-nfs-release-4.6.yaml
  ci-operator/jobs/openshift/csi-driver-nfs/openshift-csi-driver-nfs-master-postsubmits.yaml
  ci-operator/jobs/openshift/csi-driver-nfs/openshift-csi-driver-nfs-master-presubmits.yaml
  ci-operator/jobs/openshift/csi-driver-nfs/openshift-csi-driver-nfs-release-4.5-postsubmits.yaml
  ci-operator/jobs/openshift/csi-driver-nfs/openshift-csi-driver-nfs-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift/csi-driver-nfs/openshift-csi-driver-nfs-release-4.6-postsubmits.yaml
  ci-operator/jobs/openshift/csi-driver-nfs/openshift-csi-driver-nfs-release-4.6-presubmits.yaml
Labels: approved, lgtm, size/XL

#7558 Undo Hive stage pause
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-master-periodics.yaml
Labels: approved, lgtm, size/L

#7591 Add CI for ARO 3.11 release-v16
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-release-v16.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v16-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/L

#7593 Adding Openshift 4.4 runs to 0.13
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.13.0__44.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.13.0-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.13.0-presubmits.yaml
Labels: approved, lgtm, size/L

#7594 Add openshift/api release-3.11 to prow
  clusters/app.ci/prow/02_config/_config.yaml
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm, size/S

#7595 Add ARO 3.11 v16.0 upgrade jobs
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v16-presubmits.yaml
Labels: approved, lgtm, sig/azure, size/L

#7587 [redhat-developer/helm] Add prow job for acceptance tests.
  ci-operator/config/redhat-developer/helm/redhat-developer-helm-release-next.yaml
  ci-operator/jobs/redhat-developer/helm/redhat-developer-helm-release-next-presubmits.yaml
Labels: approved, lgtm, size/L

#7585 Fix setting up OVN via CLUSTER_VARIANT instead of CLUSTER_NETWORK_TYPE.
  ci-operator/jobs/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-master-presubmits.yaml
  ci-operator/jobs/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-sctpci-release-v4.3-periodics.yaml
Labels: approved, lgtm, size/S

#7600 Add team members to openstack approvers
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#7603 Add 44 run to release-next
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next__44.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-next-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-next-presubmits.yaml
Labels: approved, lgtm, size/L

#7543 Update job names
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-next.yaml
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-next__variant.yaml
  ci-operator/config/openshift/tektoncd-triggers/openshift-tektoncd-triggers-release-next.yaml
  ci-operator/jobs/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-next-presubmits.yaml
  ci-operator/jobs/openshift/tektoncd-triggers/openshift-tektoncd-triggers-release-next-presubmits.yaml
Labels: approved, lgtm, size/M

#7556 Fix branch-ci-openshift-release-master-app-ci-apply-canary
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  clusters/app.ci/.diff
  clusters/app.ci/prow/03_deployment/admin_config_updater_app_ci_rbac.yaml
  clusters/app.ci/prow/03_deployment/deck.yaml
  clusters/app.ci/prow/03_deployment/prow-priority-class.yaml
Labels: approved, lgtm, size/XL

#7596 add audit-logs step to gather step
  ci-operator/step-registry/gather/audit-logs/OWNERS
  ci-operator/step-registry/gather/audit-logs/gather-audit-logs-commands.sh
  ci-operator/step-registry/gather/audit-logs/gather-audit-logs-ref.yaml
  ci-operator/step-registry/gather/gather-chain.yaml
Labels: approved, lgtm, size/S

#7513 openstack: Add lease client to 4.5 canaries
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
Labels: approved, lgtm, size/S

#7605 Build image for the Serving Operator 0.13.
  ci-operator/config/openshift-knative/serving-operator/openshift-knative-serving-operator-release-0.13.yaml
  ci-operator/jobs/openshift-knative/serving-operator/openshift-knative-serving-operator-release-0.13-postsubmits.yaml
  ci-operator/jobs/openshift-knative/serving-operator/openshift-knative-serving-operator-release-0.13-presubmits.yaml
Labels: approved, lgtm, size/L

#7609 Make sure we use custom image while testing the operator
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-master.yaml
  ci-operator/jobs/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-master-presubmits.yaml
Labels: approved, lgtm, size/S

#7404 Add kn-cli-artifacts image
  ci-operator/config/openshift/knative-client/openshift-knative-client-release-next.yaml
  core-services/image-mirroring/knative/mapping_knative_nightly_quay
Labels: approved, lgtm, size/S

#7598 Add plugins for bentitopolis org
  clusters/app.ci/prow/02_config/_plugins.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, size/M

#7607 Remove tracer
  clusters/app.ci/prow/03_deployment/admin_tracer_rbac.yaml
  clusters/app.ci/prow/03_deployment/tracer.yaml
  core-services/prow/03_deployment/admin_tracer_rbac.yaml
  core-services/prow/03_deployment/tracer.yaml
  tools/traceprow/README.md
  tools/traceprow/main.go
Labels: approved, lgtm, size/L

#7613 Adding 4.5 run for NEXT
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next__45.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-next-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-next-presubmits.yaml
Labels: approved, lgtm, size/L

#7610 Use git diff --no-index for app.ci diffing
  .gitignore
  clusters/app.ci/.diff
  hack/verify-app-ci.sh
Labels: approved, lgtm, size/L

#7615 Use container to generate mixins
  Makefile
  cluster/ci/monitoring/README.md
Labels: approved, lgtm, size/XS

#7571 e2e-upi template: gcp enable 02_lb_int.py workflow
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
Labels: approved, lgtm, size/L

#7606 Add basic secrets for app.ci cluster
  core-services/ci-secret-bootstrap/README.md
  core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm, size/S

#7506 Ensure cluster in prow jobs
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  hack/ensure_job_cluster.py
Labels: approved, lgtm, size/L

#7617 SDCICD-202. Adopt default/next strategy for stage.
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-master-periodics.yaml
Labels: approved, lgtm, size/M

#7570 Remove inputs from manila operator image
  ci-operator/config/openshift/csi-driver-manila-operator/openshift-csi-driver-manila-operator-master.yaml
  ci-operator/config/openshift/csi-driver-manila-operator/openshift-csi-driver-manila-operator-release-4.5.yaml
  ci-operator/config/openshift/csi-driver-manila-operator/openshift-csi-driver-manila-operator-release-4.6.yaml
Labels: approved, lgtm, size/S

#7608 Do not use a priorityClass on app.ci
  clusters/app.ci/.diff
  clusters/app.ci/prow/03_deployment/boskos.yaml
  clusters/app.ci/prow/03_deployment/boskos_cleaner.yaml
  clusters/app.ci/prow/03_deployment/boskos_reaper.yaml
  clusters/app.ci/prow/03_deployment/crier.yaml
  clusters/app.ci/prow/03_deployment/deck.yaml
  clusters/app.ci/prow/03_deployment/exporter.yaml
  clusters/app.ci/prow/03_deployment/hook.yaml
  clusters/app.ci/prow/03_deployment/horologium.yaml
  clusters/app.ci/prow/03_deployment/plank.yaml
  clusters/app.ci/prow/03_deployment/sinker.yaml
  clusters/app.ci/prow/03_deployment/tide.yaml
  clusters/app.ci/prow/03_deployment/tot.yaml
Labels: approved, lgtm, size/L

#7611 alerting: improve github token exhaustion alert
  cluster/ci/monitoring/mixins/prometheus/ghproxy_alerts.libsonnet
  cluster/ci/monitoring/mixins/prometheus_out/prometheus_rule_prow.yaml
Labels: approved, lgtm, size/S

#7601 Pull golangci-lint version from repo
  ci-operator/config/openshift/managed-velero-operator/openshift-managed-velero-operator-master.yaml
Labels: approved, lgtm, size/XS
