Repository openshift/release, pull requests merged in 2020-12, with the labels that each got.

#13932 disable fast-forward from master branch
  ci-operator/config/open-cluster-management/grafana/open-cluster-management-grafana-master.yaml
  ci-operator/config/open-cluster-management/grafana/open-cluster-management-grafana-release-2.2.yaml
  ci-operator/jobs/open-cluster-management/grafana/open-cluster-management-grafana-master-postsubmits.yaml
Labels: approved, lgtm

#13958 Disable grafana image mirror temporarily
  ci-operator/jobs/open-cluster-management/grafana/open-cluster-management-grafana-release-2.2-postsubmits.yaml
Labels: approved, lgtm

#13944 bumping integreatly cluster nodes
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: approved, lgtm

#13959 Add serverless 1.12 branch
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.12.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.12__4.6.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.12-periodics.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.12-postsubmits.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.12-presubmits.yaml
Labels: approved, lgtm

#13892 Add e2e-agnostic-image-registry job to image-registry
  ci-operator/config/openshift/image-registry/openshift-image-registry-master.yaml
  ci-operator/config/openshift/image-registry/openshift-image-registry-release-4.7.yaml
  ci-operator/config/openshift/image-registry/openshift-image-registry-release-4.8.yaml
  ci-operator/jobs/openshift/image-registry/openshift-image-registry-master-presubmits.yaml
  ci-operator/jobs/openshift/image-registry/openshift-image-registry-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/image-registry/openshift-image-registry-release-4.8-presubmits.yaml
Labels: approved, lgtm

#13965 knative-client: Fix test image bin path
  ci-operator/config/openshift/knative-client/openshift-knative-client-release-v0.18.4.yaml
Labels: approved, lgtm

#13963 Make vSphere tests optional
  ci-operator/jobs/openshift/vsphere-problem-detector/openshift-vsphere-problem-detector-master-presubmits.yaml
Labels: approved, lgtm

#13579 Upgrade: use hosted loki for stable 4.5 -> 4.6 ci upgrade job
  ci-operator/jobs/openshift/release/openshift-release-release-4.6-periodics.yaml
Labels: approved, lgtm

#13938 Migrate insights operator jobs to multi stage
  ci-operator/config/openshift-priv/insights-operator/openshift-priv-insights-operator-master.yaml
  ci-operator/config/openshift-priv/insights-operator/openshift-priv-insights-operator-release-4.2.yaml
  ci-operator/config/openshift-priv/insights-operator/openshift-priv-insights-operator-release-4.3.yaml
  ci-operator/config/openshift-priv/insights-operator/openshift-priv-insights-operator-release-4.4.yaml
  ci-operator/config/openshift-priv/insights-operator/openshift-priv-insights-operator-release-4.5.yaml
  ci-operator/config/openshift-priv/insights-operator/openshift-priv-insights-operator-release-4.6.yaml
  ci-operator/config/openshift-priv/insights-operator/openshift-priv-insights-operator-release-4.7.yaml
  ci-operator/config/openshift-priv/insights-operator/openshift-priv-insights-operator-release-4.8.yaml
  ci-operator/config/openshift/insights-operator/openshift-insights-operator-master.yaml
  ci-operator/config/openshift/insights-operator/openshift-insights-operator-release-4.2.yaml
  ci-operator/config/openshift/insights-operator/openshift-insights-operator-release-4.3.yaml
  ci-operator/config/openshift/insights-operator/openshift-insights-operator-release-4.4.yaml
  ci-operator/config/openshift/insights-operator/openshift-insights-operator-release-4.5.yaml
  ci-operator/config/openshift/insights-operator/openshift-insights-operator-release-4.6.yaml
  ci-operator/config/openshift/insights-operator/openshift-insights-operator-release-4.7.yaml
  ci-operator/config/openshift/insights-operator/openshift-insights-operator-release-4.8.yaml
  ci-operator/jobs/openshift-priv/insights-operator/openshift-priv-insights-operator-master-periodics.yaml
  ci-operator/jobs/openshift-priv/insights-operator/openshift-priv-insights-operator-master-presubmits.yaml
  ci-operator/jobs/openshift-priv/insights-operator/openshift-priv-insights-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift-priv/insights-operator/openshift-priv-insights-operator-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift-priv/insights-operator/openshift-priv-insights-operator-release-4.4-periodics.yaml
  ci-operator/jobs/openshift-priv/insights-operator/openshift-priv-insights-operator-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift-priv/insights-operator/openshift-priv-insights-operator-release-4.5-periodics.yaml
  ci-operator/jobs/openshift-priv/insights-operator/openshift-priv-insights-operator-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift-priv/insights-operator/openshift-priv-insights-operator-release-4.6-periodics.yaml
  ci-operator/jobs/openshift-priv/insights-operator/openshift-priv-insights-operator-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift-priv/insights-operator/openshift-priv-insights-operator-release-4.7-periodics.yaml
  ci-operator/jobs/openshift-priv/insights-operator/openshift-priv-insights-operator-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift-priv/insights-operator/openshift-priv-insights-operator-release-4.8-periodics.yaml
  ci-operator/jobs/openshift-priv/insights-operator/openshift-priv-insights-operator-release-4.8-presubmits.yaml
  ci-operator/jobs/openshift/insights-operator/openshift-insights-operator-master-periodics.yaml
  ci-operator/jobs/openshift/insights-operator/openshift-insights-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/insights-operator/openshift-insights-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/insights-operator/openshift-insights-operator-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/insights-operator/openshift-insights-operator-release-4.4-periodics.yaml
  ci-operator/jobs/openshift/insights-operator/openshift-insights-operator-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/insights-operator/openshift-insights-operator-release-4.5-periodics.yaml
  ci-operator/jobs/openshift/insights-operator/openshift-insights-operator-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift/insights-operator/openshift-insights-operator-release-4.6-periodics.yaml
  ci-operator/jobs/openshift/insights-operator/openshift-insights-operator-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/insights-operator/openshift-insights-operator-release-4.7-periodics.yaml
  ci-operator/jobs/openshift/insights-operator/openshift-insights-operator-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/insights-operator/openshift-insights-operator-release-4.8-periodics.yaml
  ci-operator/jobs/openshift/insights-operator/openshift-insights-operator-release-4.8-presubmits.yaml
  core-services/template-deprecation/_allowlist.yaml
Labels: approved, lgtm

#13946 Secret mirroring configuration for ocs operator addon for osde2d
  core-services/secret-mirroring/_mapping.yaml
Labels: approved, lgtm

#13970 kubevirt-kubevirt-tekton-tasks: build execute-in-vm image
  ci-operator/config/kubevirt/kubevirt-tekton-tasks/kubevirt-kubevirt-tekton-tasks-main.yaml
Labels: approved, lgtm

#13984 templates: document a blocker for AWS UPI jobs
  core-services/template-deprecation/_allowlist.yaml
Labels: approved, lgtm

#13985 Imported image with insights-operator tests
  core-services/supplemental-ci-images/insights-operator-tests.yaml
Labels: approved, lgtm

#13875 Disable cluster autoscaler limits, we configure this on machine autoscaler
  clusters/build-clusters/01_cluster/assets/admin_default_clusterautoscaler.yaml
  clusters/build-clusters/02_cluster/openshift-machine-api/admin_default_clusterautoscaler.yaml
Labels: approved, lgtm

#12309 Add telco-bastion performance-addon-operators job
  ci-operator/config/openshift-kni/performance-addon-operators/openshift-kni-performance-addon-operators-master.yaml
  ci-operator/jobs/openshift-kni/performance-addon-operators/openshift-kni-performance-addon-operators-master-periodics.yaml
  ci-operator/step-registry/telco-bastion/setup/telco-bastion-setup-commands.sh
  core-services/sanitize-prow-jobs/_config.yaml
Labels: approved, lgtm

#13972 Add blockers for migrating promote-* jobs
  core-services/template-deprecation/_allowlist.yaml
Labels: approved, lgtm

#13973 Remove template CMs from jobs that do not use it
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.6-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.8-periodics.yaml
Labels: approved, lgtm

#13976 templates: document a blocker for scaleup template
  core-services/template-deprecation/_allowlist.yaml
Labels: approved, lgtm

#13979 CI tools: Run tests with -race
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
Labels: approved, lgtm

#13996 Update _allow-list to pick up 4.7 ppc64le job.
  core-services/testgrid-config-generator/_allow-list.yaml
Labels: approved, lgtm

#13997 Revert "Disable promotionreconciler"
  clusters/app.ci/assets/dptp-controller-manager.yaml
Labels: approved, lgtm

#13995 SDCICD-528: Add OSD 4.7-nightly periodic to OCP informing
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml
  core-services/release-controller/_releases/priv/release-ocp-4.7.json
  core-services/release-controller/_releases/release-ocp-4.7.json
  core-services/testgrid-config-generator/_allow-list.yaml
Labels: approved, lgtm

#14002 defines e2e-aws-operator-encryption-perf job for cluster-authentication-operator
  ci-operator/config/openshift/cluster-authentication-operator/openshift-cluster-authentication-operator-master.yaml
  ci-operator/config/openshift/cluster-authentication-operator/openshift-cluster-authentication-operator-release-4.7.yaml
  ci-operator/jobs/openshift/cluster-authentication-operator/openshift-cluster-authentication-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-authentication-operator/openshift-cluster-authentication-operator-release-4.7-presubmits.yaml
Labels: approved, lgtm

#13969 Run w/ OCP 4.7 for 0.18.x
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.18.6__47.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.18.6-periodics.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.18.6-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.18.6-presubmits.yaml
Labels: approved, lgtm

#14004 removes e2e-aws-operator-encryption-perf job for openshift-apiserver-operator
  ci-operator/config/openshift/cluster-openshift-apiserver-operator/openshift-cluster-openshift-apiserver-operator-master.yaml
  ci-operator/config/openshift/cluster-openshift-apiserver-operator/openshift-cluster-openshift-apiserver-operator-release-4.7.yaml
  ci-operator/jobs/openshift/cluster-openshift-apiserver-operator/openshift-cluster-openshift-apiserver-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-openshift-apiserver-operator/openshift-cluster-openshift-apiserver-operator-release-4.7-presubmits.yaml
Labels: approved, lgtm

#13834 [revert] Old template for eventing-contrib 0.18
  ci-operator/config/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-v0.18.0__46.yaml
  ci-operator/jobs/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-v0.18.0-periodics.yaml
  ci-operator/jobs/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-v0.18.0-presubmits.yaml
  core-services/template-deprecation/_allowlist.yaml
Labels: approved, lgtm

#14007 Remove oc download from assisted-setup
  ci-operator/step-registry/baremetalds/assisted/setup/baremetalds-assisted-setup-commands.sh
Labels: approved, lgtm

#14010 kubevirt: ssp: Add an upgrade test lane for ssp-operator
  ci-operator/config/kubevirt/ssp-operator/kubevirt-ssp-operator-master.yaml
  ci-operator/jobs/kubevirt/ssp-operator/kubevirt-ssp-operator-master-presubmits.yaml
Labels: approved, lgtm

#14014 Fix promotion name for knative v0.18.4
  ci-operator/config/openshift/knative-client/openshift-knative-client-release-v0.18.4.yaml
Labels: approved, lgtm

#13975 o/cluster-network-operator: get rid of template-based jobs
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-master.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-master-presubmits.yaml
Labels: approved, lgtm

#14012 baremetalds: don't download oc tools outside of dev-scripts
  ci-operator/step-registry/baremetalds/devscripts/setup/baremetalds-devscripts-setup-commands.sh
Labels: approved, lgtm

#13988 Add cluster-secrets-kubevirt to _config file
  core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#13956 Add openshift/special-resource-operator to the OpenShift CI.
  ci-operator/config/openshift/special-resource-operator/OWNERS
  ci-operator/config/openshift/special-resource-operator/openshift-special-resource-operator-master.yaml
  ci-operator/jobs/openshift/special-resource-operator/OWNERS
  ci-operator/jobs/openshift/special-resource-operator/openshift-special-resource-operator-master-presubmits.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
  core-services/template-deprecation/_allowlist.yaml
Labels: approved, lgtm

#14005 Remove the webhook binary from HCO operator image
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-master.yaml
Labels: approved, lgtm

#14018 template allowlist: make adding blockers easier
  Makefile
  hack/generate-template-allowlist.sh
Labels: approved, lgtm

#14016 templates: document a blocker for FIPS jobs
  core-services/template-deprecation/_allowlist.yaml
Labels: approved, lgtm

#14032 core-services/prow/02_config: Drop GCP Boskos leases to 80
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: approved, lgtm

#14027 config-updater: remove patterns for nonexistent (and unused) templates
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#14024 deadmanssnitch-operator: Remove origin shims
  ci-operator/config/openshift/deadmanssnitch-operator/openshift-deadmanssnitch-operator-master.yaml
Labels: approved, lgtm

#13957 Move upgrade-rollback job to use step registry
  ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml
Labels: approved, lgtm

#14011 Adding 4.7 old template, for now
  ci-operator/config/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-v0.18.0__47.yaml
  ci-operator/jobs/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-v0.18.0-periodics.yaml
  ci-operator/jobs/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-v0.18.0-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-v0.18.0-presubmits.yaml
  core-services/template-deprecation/_allowlist.yaml
Labels: approved, lgtm

#14036 Aligning 1.12 pre jobs w/ those from master
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.12-presubmits.yaml
Labels: approved, lgtm

#14037 Fixing a generator error
  core-services/image-mirroring/knative/mapping_knative_v0_19_quay
Labels: approved, lgtm

#14039 Change the namespace used for openshift-kni images.
  ci-operator/config/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-master.yaml
  ci-operator/config/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.4.yaml
  ci-operator/config/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.5.yaml
  ci-operator/config/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.6.yaml
  ci-operator/config/openshift-kni/performance-addon-operators/openshift-kni-performance-addon-operators-master.yaml
  ci-operator/config/openshift-kni/performance-addon-operators/openshift-kni-performance-addon-operators-release-4.4.yaml
  ci-operator/config/openshift-kni/performance-addon-operators/openshift-kni-performance-addon-operators-release-4.5.yaml
  ci-operator/config/openshift-kni/performance-addon-operators/openshift-kni-performance-addon-operators-release-4.6.yaml
  core-services/image-mirroring/openshift-kni/mapping_openshift-kni_quay
Labels: approved, lgtm

#14040 kubevirt: ssp: Run unittests and run e2e tests on gcp
  ci-operator/config/kubevirt/ssp-operator/kubevirt-ssp-operator-master.yaml
  ci-operator/jobs/kubevirt/ssp-operator/kubevirt-ssp-operator-master-presubmits.yaml
Labels: approved, lgtm

#14042 Adding 4.7 CI run for 0.19.2
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.19.2__47.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.19.2-periodics.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.19.2-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.19.2-presubmits.yaml
Labels: approved, lgtm

#13983 Serverless: CI on OCP 4.7 for release-1.12 branch
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.12__4.7.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.12-periodics.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.12-postsubmits.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.12-presubmits.yaml
Labels: approved, lgtm

#14044 bump RHOAM osde2e nodes to 6
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: approved, lgtm

#14025 modified source namespace for ocs addon for osde2e
  core-services/secret-mirroring/_mapping.yaml
Labels: approved, lgtm

#14051 fix --export usage in endurance job
  ci-operator/jobs/openshift/release/openshift-release-release-4.6-periodics.yaml
Labels: approved, lgtm

#14033 Bump packet boskos leases limit
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: approved, lgtm

#14045 Serverless: CI on OCP 4.7 for master branch
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master__4.7.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master-periodics.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master-presubmits.yaml
Labels: approved, lgtm

#14048 Add cluster-secret for remote libvirt CI
  core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#14052 Rename openshift-kni to ocp-kni
  clusters/app.ci/assets/dptp-controller-manager.yaml
  clusters/app.ci/ocp-kni/admin_ocp-kni_list.yaml
Labels: approved, lgtm

#14047 Promote assisted-test-infra image to openshift-kni namespace
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-release-4.6.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-release-4.7.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-release-4.8.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-presubmits.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-4.6-periodics.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-4.6-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-4.7-periodics.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-4.7-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-4.8-periodics.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-4.8-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-4.8-presubmits.yaml
Labels: approved, lgtm

#13998 wmco: Increase memory limit
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-community-4.6.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-community-4.6__okd.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-master.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.6.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.7.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.8.yaml
  ci-operator/step-registry/windows/e2e/operator/test/windows-e2e-operator-test-ref.yaml
  ci-operator/step-registry/windows/e2e/operator/test/with-custom-vxlan-port/windows-e2e-operator-test-with-custom-vxlan-port-ref.yaml
Labels: approved, lgtm

#13994 Added multi-arch cluster-samples jobs to 4.7 periodics file
  ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml
  core-services/template-deprecation/_allowlist.yaml
Labels: approved, lgtm

#14022 Enable testing of OVNKubernetes IPsec support
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-master.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-master-presubmits.yaml
  ci-operator/step-registry/openshift/e2e/aws/ovn/ipsec/OWNERS
  ci-operator/step-registry/openshift/e2e/aws/ovn/ipsec/openshift-e2e-aws-ovn-ipsec-workflow.metadata.json
  ci-operator/step-registry/openshift/e2e/aws/ovn/ipsec/openshift-e2e-aws-ovn-ipsec-workflow.yaml
  ci-operator/step-registry/ovn/conf/ipsec-manifest/OWNERS
  ci-operator/step-registry/ovn/conf/ipsec-manifest/ovn-conf-ipsec-manifest-commands.sh
  ci-operator/step-registry/ovn/conf/ipsec-manifest/ovn-conf-ipsec-manifest-ref.metadata.json
  ci-operator/step-registry/ovn/conf/ipsec-manifest/ovn-conf-ipsec-manifest-ref.yaml
Labels: approved, lgtm

#14049 Fix openshift/build-machinery-go build images
  ci-operator/config/openshift/build-machinery-go/openshift-build-machinery-go-master.yaml
  ci-operator/config/openshift/build-machinery-go/openshift-build-machinery-go-release-4.6.yaml
Labels: approved, lgtm

#13737 Add initial devfile tests with ODO
  ci-operator/config/devfile/integration-tests/devfile-integration-tests-master.yaml
  ci-operator/config/devfile/integration-tests/devfile-integration-tests-master__v4.5.yaml
  ci-operator/jobs/devfile/integration-tests/devfile-integration-tests-master-presubmits.yaml
Labels: approved, lgtm

#14062 installer: only run one metal-ipi job
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
Labels: approved, lgtm

#14065 Add 4.6 4.7 upgrade-rollback to release controller
  ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml
  core-services/release-controller/_releases/release-ocp-4.7-ci.json
Labels: approved, lgtm

#14067 Disable the e2e-aws tests for the SRIOV network operator
  ci-operator/config/openshift/sriov-network-operator/openshift-sriov-network-operator-master.yaml
  ci-operator/config/openshift/sriov-network-operator/openshift-sriov-network-operator-release-4.3.yaml
  ci-operator/config/openshift/sriov-network-operator/openshift-sriov-network-operator-release-4.4.yaml
  ci-operator/config/openshift/sriov-network-operator/openshift-sriov-network-operator-release-4.5.yaml
  ci-operator/config/openshift/sriov-network-operator/openshift-sriov-network-operator-release-4.6.yaml
  ci-operator/config/openshift/sriov-network-operator/openshift-sriov-network-operator-release-4.7.yaml
  ci-operator/config/openshift/sriov-network-operator/openshift-sriov-network-operator-release-4.8.yaml
  ci-operator/jobs/openshift/sriov-network-operator/openshift-sriov-network-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/sriov-network-operator/openshift-sriov-network-operator-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/sriov-network-operator/openshift-sriov-network-operator-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/sriov-network-operator/openshift-sriov-network-operator-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift/sriov-network-operator/openshift-sriov-network-operator-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/sriov-network-operator/openshift-sriov-network-operator-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/sriov-network-operator/openshift-sriov-network-operator-release-4.8-presubmits.yaml
Labels: approved, lgtm

#14068 cno: ipsec job should be optional until all dependencies merge
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-master-presubmits.yaml
Labels: approved, lgtm

#14053 Log unit test result
  ci-operator/config/redhat-developer/kam/redhat-developer-kam-master.yaml
Labels: approved, lgtm

#14008 openshift/enhancements: disable auto-approval
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#13934 Enable unit tests for sriov-network-operator
  ci-operator/config/openshift/sriov-network-operator/openshift-sriov-network-operator-master.yaml
  ci-operator/config/openshift/sriov-network-operator/openshift-sriov-network-operator-release-4.7.yaml
  ci-operator/config/openshift/sriov-network-operator/openshift-sriov-network-operator-release-4.8.yaml
  ci-operator/jobs/openshift/sriov-network-operator/openshift-sriov-network-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/sriov-network-operator/openshift-sriov-network-operator-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/sriov-network-operator/openshift-sriov-network-operator-release-4.8-presubmits.yaml
Labels: approved, lgtm

#14075 Serverless: Remove upgrade tests on OCP4.7 from presubmits
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master__4.7.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master-presubmits.yaml
Labels: approved, lgtm

#14078 Copy osde2e-credentials secret into the test-credentials namespace also
  core-services/secret-mirroring/_mapping.yaml
Labels: approved, lgtm

#14083 CMO: always regenerate all assets
  ci-operator/config/openshift/cluster-monitoring-operator/openshift-cluster-monitoring-operator-master.yaml
Labels: approved, lgtm

#14084 update RHOAM configuration
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: approved, lgtm

#14080 Add GCP PD CSI Driver Operator test image to step registry
  ci-operator/config/openshift/gcp-pd-csi-driver-operator/openshift-gcp-pd-csi-driver-operator-master.yaml
  ci-operator/config/openshift/gcp-pd-csi-driver-operator/openshift-gcp-pd-csi-driver-operator-release-4.7.yaml
  ci-operator/config/openshift/gcp-pd-csi-driver-operator/openshift-gcp-pd-csi-driver-operator-release-4.8.yaml
  ci-operator/step-registry/openshift/e2e/gcp/csi/OWNERS
  ci-operator/step-registry/openshift/e2e/gcp/csi/openshift-e2e-gcp-csi-workflow.metadata.json
  ci-operator/step-registry/openshift/e2e/gcp/csi/openshift-e2e-gcp-csi-workflow.yaml
  ci-operator/step-registry/storage/conf/csi-gcp-pd/OWNERS
  ci-operator/step-registry/storage/conf/csi-gcp-pd/storage-conf-csi-gcp-pd-commands.sh
  ci-operator/step-registry/storage/conf/csi-gcp-pd/storage-conf-csi-gcp-pd-ref.metadata.json
  ci-operator/step-registry/storage/conf/csi-gcp-pd/storage-conf-csi-gcp-pd-ref.yaml
Labels: approved, lgtm

#14098 rbac-permissions-operator: codecov secret mapping
  core-services/secret-mirroring/_mapping.yaml
Labels: approved, lgtm

#13664 Migrate to app.ci: periodic-image-mirroring-openshift
  ci-operator/jobs/infra-image-mirroring.yaml
  core-services/image-mirroring/openshift/mapping_origin_4_1
  core-services/image-mirroring/openshift/mapping_origin_4_2
  core-services/image-mirroring/openshift/mapping_origin_4_3
  core-services/image-mirroring/openshift/mapping_origin_4_4
  core-services/image-mirroring/openshift/mapping_origin_4_5
  core-services/image-mirroring/openshift/mapping_origin_4_6
  core-services/image-mirroring/openshift/mapping_origin_4_7
  core-services/image-mirroring/openshift/mapping_origin_4_8
  core-services/sanitize-prow-jobs/_config.yaml
  hack/mirror-file
Labels: approved, lgtm

#14059 Collect vCenter performance metrics, alerts, and events prior to deprovisioning cluster
  ci-operator/step-registry/upi/deprovision/vsphere/upi-deprovision-vsphere-commands.sh
Labels: approved, lgtm

#14097 bump timeout for gather-hosted-loki-ref.yaml to 30m
  ci-operator/step-registry/gather/hosted-loki/gather-hosted-loki-ref.yaml
Labels: approved, lgtm

#14029 [WMCB] Remove WNI tests
  ci-operator/config/openshift/windows-machine-config-bootstrapper/openshift-windows-machine-config-bootstrapper-master.yaml
  ci-operator/config/openshift/windows-machine-config-bootstrapper/openshift-windows-machine-config-bootstrapper-release-4.6.yaml
  ci-operator/config/openshift/windows-machine-config-bootstrapper/openshift-windows-machine-config-bootstrapper-release-4.7.yaml
  ci-operator/config/openshift/windows-machine-config-bootstrapper/openshift-windows-machine-config-bootstrapper-release-4.8.yaml
  ci-operator/jobs/openshift/windows-machine-config-bootstrapper/openshift-windows-machine-config-bootstrapper-master-presubmits.yaml
  ci-operator/jobs/openshift/windows-machine-config-bootstrapper/openshift-windows-machine-config-bootstrapper-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/windows-machine-config-bootstrapper/openshift-windows-machine-config-bootstrapper-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/windows-machine-config-bootstrapper/openshift-windows-machine-config-bootstrapper-release-4.8-presubmits.yaml
Labels: approved, lgtm

#14102 Move registry-replacer to app.ci
  ci-operator/jobs/infra-periodics.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: approved

#14105 Revert "Disable ns ttl controller"
  clusters/build-clusters/common/ci-ns-ttl-controller/ci-ns-ttl-controller_deployment.yaml
Labels: approved, lgtm

#14106 Create secret/registry-push-credentials-openshift on app.ci
  ci-operator/jobs/infra-image-mirroring.yaml
  core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#14090 Move openshift-acme to 4.6 CI
  ci-operator/config/tnozicka/openshift-acme/tnozicka-openshift-acme-master.yaml
Labels: approved, lgtm

#13953 Run CSI certification test suite for GCE PD driver/operator
  ci-operator/config/openshift/gcp-pd-csi-driver-operator/openshift-gcp-pd-csi-driver-operator-master.yaml
  ci-operator/config/openshift/gcp-pd-csi-driver-operator/openshift-gcp-pd-csi-driver-operator-release-4.7.yaml
  ci-operator/config/openshift/gcp-pd-csi-driver-operator/openshift-gcp-pd-csi-driver-operator-release-4.8.yaml
  ci-operator/jobs/openshift/gcp-pd-csi-driver-operator/openshift-gcp-pd-csi-driver-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/gcp-pd-csi-driver-operator/openshift-gcp-pd-csi-driver-operator-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/gcp-pd-csi-driver-operator/openshift-gcp-pd-csi-driver-operator-release-4.8-presubmits.yaml
Labels: approved, lgtm

#14117 cluster-baremetal-operator uses openshift-kni/assisted-test
  ci-operator/config/openshift/cluster-baremetal-operator/openshift-cluster-baremetal-operator-master.yaml
Labels: approved, lgtm

#14121 oc --config is deprecated, use --kubeconfig instead
  ci-operator/templates/master-sidecar-4.6.yaml
Labels: approved, lgtm

#14071 Add domain-mapping and domain-mapping-webhook images to Knative Serving nightly build
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-next__4.6.yaml
Labels: approved, lgtm

#14125 Update golang version in insight-operator 4.5 image
  ci-operator/config/openshift/insights-operator/openshift-insights-operator-release-4.5.yaml
Labels: approved, lgtm

#14131 Revert "Update golang version in insight-operator 4.5 image"
  ci-operator/config/openshift/insights-operator/openshift-insights-operator-release-4.5.yaml
Labels: approved, lgtm

#14076 Migrating unit test to multistage to collect logs in artifacts
  ci-operator/config/openshift/odo/openshift-odo-master.yaml
Labels: approved, lgtm

#13977 ipi/install/hosted-loki: replace python script with golang-based refresher
  ci-operator/step-registry/ipi/install/hosted-loki/ipi-install-hosted-loki-commands.sh
Labels: approved, lgtm

#14126 [cluster-logging-operator] Disconnect from hosted loki
  ci-operator/config/openshift/cluster-logging-operator/openshift-cluster-logging-operator-master.yaml
Labels: approved, lgtm

#13978 Add e2e-metal-assisted to TestGrid
  ci-operator/config/openshift/release/openshift-release-master__ocp-4.6.yaml
  ci-operator/config/openshift/release/openshift-release-master__ocp-4.7.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  core-services/release-controller/_releases/priv/release-ocp-4.7.json
  core-services/release-controller/_releases/release-ocp-4.7.json
  core-services/testgrid-config-generator/_allow-list.yaml
Labels: approved, lgtm

#13982 knative-serving setup CI on OCP 4.7
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-v0.18.2__4.7.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-v0.18.2-postsubmits.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-v0.18.2-presubmits.yaml
Labels: approved, lgtm

#14116 cluster-etcd-operator uses openshift-kni/assisted-test
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-master.yaml
Labels: approved, lgtm

#14088 build02: use 600Gb disks on workers
  clusters/build-clusters/02_cluster/openshift-machine-api/build0-gstfj-w-b_machineset.yaml
  clusters/build-clusters/02_cluster/openshift-machine-api/build0-gstfj-w-c_machineset.yaml
  clusters/build-clusters/02_cluster/openshift-machine-api/build0-gstfj-w-d_machineset.yaml
Labels: approved, lgtm

#14120 Add e2e-metal-assisted-onprem test to assisted-test-infra
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-presubmits.yaml
  ci-operator/step-registry/baremetalds/assisted/gather/baremetalds-assisted-gather-commands.sh
  ci-operator/step-registry/baremetalds/assisted/setup/baremetalds-assisted-setup-commands.sh
  ci-operator/step-registry/baremetalds/assisted/setup/baremetalds-assisted-setup-ref.yaml
Labels: approved, lgtm

#14136 OO Subscribe step - sync the changes from the OO CI subscribe commands
  ci-operator/step-registry/optional-operators/subscribe/optional-operators-subscribe-commands.sh
Labels: approved, lgtm

#14119 cluster-version-operator uses openshift-kni/assisted-test
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-master.yaml
Labels: approved, lgtm

#14100 clonerefs: periodically manage the image
  ci-operator/jobs/infra-periodics.yaml
  core-services/supplemental-ci-images/manage-clonerefs.yaml
Labels: approved, lgtm

#14137 Run CSI certification test suite for GCE PD CSI Driver
  ci-operator/config/openshift/gcp-pd-csi-driver/openshift-gcp-pd-csi-driver-master.yaml
  ci-operator/config/openshift/gcp-pd-csi-driver/openshift-gcp-pd-csi-driver-release-4.7.yaml
  ci-operator/config/openshift/gcp-pd-csi-driver/openshift-gcp-pd-csi-driver-release-4.8.yaml
  ci-operator/jobs/openshift/gcp-pd-csi-driver/openshift-gcp-pd-csi-driver-master-presubmits.yaml
  ci-operator/jobs/openshift/gcp-pd-csi-driver/openshift-gcp-pd-csi-driver-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/gcp-pd-csi-driver/openshift-gcp-pd-csi-driver-release-4.8-presubmits.yaml
Labels: approved, lgtm

#14127 cincinnati-graph-data: deprecate graph-util test
  ci-operator/config/openshift/cincinnati-graph-data/openshift-cincinnati-graph-data-master.yaml
  ci-operator/jobs/openshift/cincinnati-graph-data/openshift-cincinnati-graph-data-master-presubmits.yaml
Labels: approved, lgtm

#14145 generators: ignore periodics for priv release-controllers
  hack/generators/release-controllers/generate-release-controllers.py
Labels: approved, lgtm

#14149 Add sd-scale-credentials secret mirror
  core-services/secret-mirroring/_mapping.yaml
Labels: approved, lgtm

#14142 [DPTP-1678] release-controller: run release upgrades jobs via release-controller
  ci-operator/jobs/openshift/release/openshift-release-release-4.1-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.6-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.8-periodics.yaml
  core-services/release-controller/_releases/release-ocp-4.1-ci.json
  core-services/release-controller/_releases/release-ocp-4.1.json
  core-services/release-controller/_releases/release-ocp-4.2-ci.json
  core-services/release-controller/_releases/release-ocp-4.2.json
  core-services/release-controller/_releases/release-ocp-4.3-ci.json
  core-services/release-controller/_releases/release-ocp-4.3.json
  core-services/release-controller/_releases/release-ocp-4.4-ci.json
  core-services/release-controller/_releases/release-ocp-4.4.json
  core-services/release-controller/_releases/release-ocp-4.5-ci.json
  core-services/release-controller/_releases/release-ocp-4.6-ci.json
  core-services/release-controller/_releases/release-ocp-4.7-ci.json
  core-services/release-controller/_releases/release-ocp-4.8-ci.json
Labels: approved, lgtm

#14151 openshift/release yamllint: Request a whole cpu
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
Labels: approved, lgtm

#14099 rbac-permissions-operator: Standardize prow config
  ci-operator/config/openshift/rbac-permissions-operator/openshift-rbac-permissions-operator-master.yaml
  ci-operator/jobs/openshift/rbac-permissions-operator/openshift-rbac-permissions-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/rbac-permissions-operator/openshift-rbac-permissions-operator-master-presubmits.yaml
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#14111 cluster-etcd-operator: move agnostic tests to aws for 4.7
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-master.yaml
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.7.yaml
  ci-operator/jobs/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.7-presubmits.yaml
Labels: approved, lgtm

#14153 SDCICD-541: Add osde2e prod canary job
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: approved, lgtm

#14150 mirroring: openstack-cinder-csi-driver-openstack does not exist
  core-services/image-mirroring/openshift/mapping_origin_4_6
  core-services/image-mirroring/openshift/mapping_origin_4_7
  core-services/image-mirroring/openshift/mapping_origin_4_8
Labels: approved, lgtm

#13767 Remove unused 1.7 tests
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.7__4.3.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.7__4.4.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.7__4.5.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.7-periodics.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.7-postsubmits.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.7-presubmits.yaml
Labels: approved, lgtm

#14031 Onboard devfile registry operator
  ci-operator/config/devfile/registry-operator/OWNERS
  ci-operator/config/devfile/registry-operator/devfile-registry-operator-main.yaml
  ci-operator/jobs/devfile/registry-operator/OWNERS
  ci-operator/jobs/devfile/registry-operator/devfile-registry-operator-main-presubmits.yaml
Labels: approved, lgtm

#14158 Remove raw steps from ironic images in 4.6
  ci-operator/config/openshift/ironic-image/openshift-ironic-image-release-4.6.yaml
  ci-operator/config/openshift/ironic-inspector-image/openshift-ironic-inspector-image-release-4.6.yaml
  ci-operator/config/openshift/ironic-ipa-downloader/openshift-ironic-ipa-downloader-release-4.6.yaml
Labels: approved, lgtm

#13884 ci-operator/step-registry/ipi/deprovision: 25m active_deadline_seconds
  ci-operator/step-registry/ipi/deprovision/deprovision/ipi-deprovision-deprovision-ref.yaml
Labels: approved, lgtm

#14148 Add optional CSI jobs to CSO and origin repos
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-master.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.6.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.7.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.8.yaml
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.7.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.8.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.8-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.8-presubmits.yaml
Labels: approved, lgtm

#13855 Moves base image to RHEL 8
  ci-operator/config/openshift/aws-ebs-csi-driver/openshift-aws-ebs-csi-driver-master.yaml
  ci-operator/config/openshift/aws-ebs-csi-driver/openshift-aws-ebs-csi-driver-release-4.7.yaml
  ci-operator/config/openshift/aws-ebs-csi-driver/openshift-aws-ebs-csi-driver-release-4.8.yaml
Labels: approved, lgtm

#14081 Release Controller: soft delete release tags
  clusters/app.ci/release-controller/deploy-ocp-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-ppc64le-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-ppc64le-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-s390x-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-s390x-priv-controller.yaml
  hack/generators/release-controllers/content/osd_rc_deployments.py
Labels: approved, lgtm

#14169 Align cluster size of build02 to build01
  clusters/build-clusters/02_cluster/openshift-machine-api/build0-gstfj-w-b_machineautoscaler.yaml
  clusters/build-clusters/02_cluster/openshift-machine-api/build0-gstfj-w-c_machineautoscaler.yaml
  clusters/build-clusters/02_cluster/openshift-machine-api/build0-gstfj-w-d_machineautoscaler.yaml
Labels: approved, lgtm

#14139 Remove unused KubeVirt builder image stream
  core-services/supplemental-ci-images/kubevirt_builder_is.yaml
Labels: approved, lgtm

#14135 Setup CI for Knative Serving v0.19.0
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-v0.19.0__4.6.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-v0.19.0-postsubmits.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-v0.19.0-presubmits.yaml
Labels: approved, lgtm, tide/merge-method-squash

#14170 Updates AWS EBS CSI Driver image
  ci-operator/config/openshift/aws-ebs-csi-driver/openshift-aws-ebs-csi-driver-master.yaml
  ci-operator/config/openshift/aws-ebs-csi-driver/openshift-aws-ebs-csi-driver-release-4.7.yaml
  ci-operator/config/openshift/aws-ebs-csi-driver/openshift-aws-ebs-csi-driver-release-4.8.yaml
Labels: approved, lgtm

#14094 Migrating unit test to multistage to collect logs in artifacts for devfile integration tests
  ci-operator/config/devfile/integration-tests/devfile-integration-tests-master.yaml
Labels: approved, lgtm

#14173 Apply soft-delete-release-tags to RC of origin
  clusters/app.ci/release-controller/deploy-origin-controller.yaml
Labels: approved, lgtm

#14174 Disable denied IS: ocp/release
  clusters/app.ci/assets/dptp-controller-manager.yaml
Labels: approved, lgtm

#14176 CSO: Only trigger CSI certification jobs when requested
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.8-presubmits.yaml
Labels: approved, lgtm

#14181 Use 1200G disk for build02
  clusters/build-clusters/02_cluster/openshift-machine-api/build0-gstfj-w-b_machineset.yaml
  clusters/build-clusters/02_cluster/openshift-machine-api/build0-gstfj-w-c_machineset.yaml
  clusters/build-clusters/02_cluster/openshift-machine-api/build0-gstfj-w-d_machineset.yaml
Labels: approved, lgtm

#14182 Remove annotations from machinesets
  clusters/build-clusters/01_cluster/openshift-machine-api/admin_build01-9hdwj-worker-us-east-1a_machine_set.yaml
  clusters/build-clusters/01_cluster/openshift-machine-api/admin_build01-9hdwj-worker-us-east-1b_machine_set.yaml
  clusters/build-clusters/01_cluster/openshift-machine-api/admin_build01-9hdwj-worker-us-east-1c_machine_set.yaml
  clusters/build-clusters/02_cluster/openshift-machine-api/build0-gstfj-w-b_machineset.yaml
  clusters/build-clusters/02_cluster/openshift-machine-api/build0-gstfj-w-c_machineset.yaml
  clusters/build-clusters/02_cluster/openshift-machine-api/build0-gstfj-w-d_machineset.yaml
Labels: approved, lgtm

#14172 ci-operator/config/openshift/cluster-version-operator: Remove much of base_images for 4.6 and later
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-master.yaml
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-release-4.6.yaml
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-release-4.7.yaml
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-release-4.8.yaml
Labels: approved, lgtm

#14179 Rename moactl to rosa
  ci-operator/config/openshift/rosa/OWNERS
  ci-operator/config/openshift/rosa/openshift-rosa-master.yaml
  ci-operator/jobs/openshift/rosa/OWNERS
  ci-operator/jobs/openshift/rosa/openshift-rosa-master-presubmits.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: approved, lgtm

#14192 Exclude openshift/origin release-4.6 and greater from bz process
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#14185 Setup image promotion for Kourier 0.19.1
  ci-operator/config/openshift-knative/net-kourier/openshift-knative-net-kourier-release-0.19.yaml
  ci-operator/jobs/openshift-knative/net-kourier/openshift-knative-net-kourier-release-0.19-postsubmits.yaml
  ci-operator/jobs/openshift-knative/net-kourier/openshift-knative-net-kourier-release-0.19-presubmits.yaml
Labels: approved, lgtm

#13950 openstack: Run the manifest-generation test suite
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/step-registry/openshift/manifests/OWNERS
  ci-operator/step-registry/openshift/manifests/openstack/OWNERS
  ci-operator/step-registry/openshift/manifests/openstack/openshift-manifests-openstack-workflow.metadata.json
  ci-operator/step-registry/openshift/manifests/openstack/openshift-manifests-openstack-workflow.yaml
  ci-operator/step-registry/openstack/test/OWNERS
  ci-operator/step-registry/openstack/test/manifests/OWNERS
  ci-operator/step-registry/openstack/test/manifests/openstack-test-manifests-commands.sh
  ci-operator/step-registry/openstack/test/manifests/openstack-test-manifests-ref.metadata.json
  ci-operator/step-registry/openstack/test/manifests/openstack-test-manifests-ref.yaml
Labels: approved, lgtm

#14194 Adding knative eventing kafka CI runs
  ci-operator/config/openshift-knative/eventing-kafka/OWNERS
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.19.1__46.yaml
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.19.1__47.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka/OWNERS
  ci-operator/jobs/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.19.1-periodics.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.19.1-postsubmits.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.19.1-presubmits.yaml
Labels: approved, lgtm

#8487 Add CI job for testing vsphere IPI in MAO
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-master.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-master-presubmits.yaml
Labels: approved, lgtm

#14073 feat: Add new nightly bundle tests
  ci-operator/config/eclipse/che-operator/eclipse-che-operator-master__v3.yaml
  ci-operator/config/eclipse/che-operator/eclipse-che-operator-master__v4.yaml
  ci-operator/config/eclipse/che-operator/eclipse-che-operator-master__v5.yaml
  ci-operator/config/eclipse/che-operator/eclipse-che-operator-master__v6.yaml
  ci-operator/config/eclipse/che-operator/eclipse-che-operator-master__v7.yaml
  ci-operator/jobs/eclipse/che-operator/eclipse-che-operator-master-presubmits.yaml
Labels: approved, lgtm

#14200 kubevirt: ssp: Deploy Kubevirt and CDI before e2e tests
  ci-operator/config/kubevirt/ssp-operator/kubevirt-ssp-operator-master.yaml
Labels: approved, lgtm

#14191 Add e2e-gcp-disruptive (as optional/on-demand) to origin/master
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  core-services/template-deprecation/_allowlist.yaml
Labels: approved, lgtm

#14064 baremetal-operator: metal ipi job consistency
  ci-operator/config/openshift/baremetal-operator/openshift-baremetal-operator-master.yaml
  ci-operator/jobs/openshift/baremetal-operator/openshift-baremetal-operator-master-presubmits.yaml
Labels: approved, lgtm

#14184 Add env vars to 4.6->4.7 upgrade-rollback job
  ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml
Labels: approved, lgtm

#14156 Add px/docs/qe approval labels for ocp-release-operator-sdk repo
  core-services/prow/02_config/_labels.yaml
Labels: approved, lgtm

#14206 Remove all denined imagestreams flags in DPTP-CM
  clusters/app.ci/assets/dptp-controller-manager.yaml
Labels: approved, lgtm

#13745 ci-operator/config/openshift/cluster-version-operator: Multi-step operator tests
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-master.yaml
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-release-4.4.yaml
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-release-4.5.yaml
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-release-4.6.yaml
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-release-4.7.yaml
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-release-4.8.yaml
  ci-operator/jobs/openshift/cluster-version-operator/openshift-cluster-version-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-version-operator/openshift-cluster-version-operator-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/cluster-version-operator/openshift-cluster-version-operator-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift/cluster-version-operator/openshift-cluster-version-operator-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/cluster-version-operator/openshift-cluster-version-operator-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/cluster-version-operator/openshift-cluster-version-operator-release-4.8-presubmits.yaml
Labels: approved, lgtm

#14177 regSyncer: remove image-stream-namespace args
  clusters/app.ci/assets/dptp-controller-manager.yaml
Labels: approved, lgtm

#14063 Update to test the built operator with e2e tests
  ci-operator/config/opendatahub-io/opendatahub-operator/opendatahub-io-opendatahub-operator-master.yaml
  ci-operator/jobs/opendatahub-io/opendatahub-operator/opendatahub-io-opendatahub-operator-master-presubmits.yaml
Labels: approved, lgtm

#14233 initial CI job config for sippy repo
  ci-operator/config/openshift/sippy/OWNERS
  ci-operator/config/openshift/sippy/openshift-sippy-master.yaml
  ci-operator/jobs/openshift/sippy/OWNERS
  ci-operator/jobs/openshift/sippy/openshift-sippy-master-presubmits.yaml
Labels: approved, lgtm

#14235 Add some knative serving images
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-v0.19.0__4.6.yaml
Labels: approved, lgtm

#14228 Add secretsyncer config for openshift prow github app
  core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#14239 Many test are failing in HCO. Check that this is not because a change in 4.7 by moving back to 4.6
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-master.yaml
Labels: approved, lgtm

#14241 fixing incorrect promotion version
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.19.1__46.yaml
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.19.1__47.yaml
Labels: approved, lgtm

#14242 Use 4.7 for dev-scripts CI builds
  ci-operator/config/openshift-metal3/dev-scripts/openshift-metal3-dev-scripts-master.yaml
Labels: approved, lgtm

#14245 ci-operator: add telemeter format test
  ci-operator/config/openshift/telemeter/openshift-telemeter-master.yaml
  ci-operator/jobs/openshift/telemeter/openshift-telemeter-master-presubmits.yaml
Labels: approved, lgtm

#13646 Bug 1897737: Censor Terraform secrets
  ci-operator/step-registry/ipi/install/install/ipi-install-install-commands.sh
  ci-operator/step-registry/upi/install/gcp/upi-install-gcp-commands.sh
  ci-operator/step-registry/upi/install/vsphere/upi-install-vsphere-commands.sh
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-upi-e2e.yaml
Labels: approved, lgtm
