Repository openshift/release, pull requests merged in 2020-06, with the labels that each got.

#9382 add tide query to require group-lead-approved label in realease-4.5
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#9386 remove the master requirements in tide queries
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#9401 vsphere quota bump by one
  core-services/prow/02_config/_boskos.yaml
Labels: approved, lgtm

#9182 [core-services] Provide supplemental UBI 7 & 8 images for origin-aggregated-logging
  core-services/supplemental-ci-images/README.md
  core-services/supplemental-ci-images/ubi-nodejs-10.yaml
  core-services/supplemental-ci-images/ubi-python-36.yaml
  core-services/supplemental-ci-images/ubi-ruby-25.yaml
Labels: approved, lgtm

#9414 bugzilla: require verified dependent bugs for 4.6
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#9417 change target release to 4.6 in master bugzilla settings
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#9116 Bug 1808579: scale back e2e-aws-upgrade,e2e-gcp-upgrade jobs to 48hr
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#9416 Re-Enable promotionreconciler
  clusters/app.ci/assets/dptp-controller-manager.yaml
Labels: approved, lgtm

#9418 Fix kubeconfigs for dptp-controller-manager
  clusters/app.ci/assets/dptp-controller-manager.yaml
Labels: approved, lgtm

#9419 Set timeout=365d for route/prometheus of prow-monitoring
  clusters/app.ci/prow-monitoring/prometheus-expose_template.yaml
Labels: approved, lgtm

#9420 Disabling release branching for managed-cluster-config
  ci-operator/config/openshift/managed-cluster-config/openshift-managed-cluster-config-master.yaml
  ci-operator/config/openshift/managed-cluster-config/openshift-managed-cluster-config-release-4.6.yaml
  ci-operator/config/openshift/managed-cluster-config/openshift-managed-cluster-config-release-4.7.yaml
  ci-operator/jobs/openshift/managed-cluster-config/openshift-managed-cluster-config-release-4.6-postsubmits.yaml
  ci-operator/jobs/openshift/managed-cluster-config/openshift-managed-cluster-config-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/managed-cluster-config/openshift-managed-cluster-config-release-4.7-postsubmits.yaml
  ci-operator/jobs/openshift/managed-cluster-config/openshift-managed-cluster-config-release-4.7-presubmits.yaml
Labels: approved, lgtm

#9179 Fix skip test list
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
Labels: approved, lgtm

#9405 Add config for openshift/kubernetes marun-testing branch
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-marun-testing.yaml
  ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-marun-testing-postsubmits.yaml
  ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-marun-testing-presubmits.yaml
Labels: approved, lgtm

#9355 Onboard openshift/aws-efs-operator
  ci-operator/config/openshift/aws-efs-operator/OWNERS
  ci-operator/config/openshift/aws-efs-operator/openshift-aws-efs-operator-master.yaml
  ci-operator/jobs/openshift/aws-efs-operator/OWNERS
  ci-operator/jobs/openshift/aws-efs-operator/openshift-aws-efs-operator-master-presubmits.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#9238 Produce knative-serving-src image
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-v0.13.3__4.3.yaml
Labels: approved, lgtm

#9432 services/promecieus: use golang 1.13 and UBI8 as a base
  services/promecieus/02-imagestream.yaml
  services/promecieus/03-buildconfig-src.yaml
  services/promecieus/04-buildconfig-bin.yaml
Labels: approved, lgtm

#9410 ovirt: always run presubmits of cluster-api-provider-ovirt
  ci-operator/jobs/openshift/cluster-api-provider-ovirt/openshift-cluster-api-provider-ovirt-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-ovirt/openshift-cluster-api-provider-ovirt-release-4.4-presubmits.yaml
Labels: approved, lgtm

#9433 Add nodejs10 and 12 images construction for 3.11
  ci-operator/config/openshift/jenkins/openshift-jenkins-openshift-3.11.yaml
Labels: approved, lgtm

#9437 increase periodic intervals for 4.6 jobs
  ci-operator/jobs/openshift/release/openshift-release-release-4.6-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml
Labels: approved, lgtm

#9441 Update doc on secrets
  ci-operator/SECRETS.md
  core-services/ci-secret-bootstrap/README.md
  core-services/secret-mirroring/README.md
Labels: approved, lgtm

#9438 aws-efs-operator: Add secret mapping
  core-services/secret-mirroring/_mapping.yaml
Labels: approved, lgtm

#9388 Add metal-ipi 4.4 and 4.5 to openshift release informing
  core-services/release-controller/_releases/release-ocp-4.4.json
  core-services/release-controller/_releases/release-ocp-4.5.json
Labels: approved, lgtm

#9413 Enable oc adm must-gather tests
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
Labels: approved, lgtm

#9421 Add secrets for enabling basic auth on prometheus
  core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#9292 Use bosko to obtain lease for one of bastion interfaces
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e-ppc64le.yaml
Labels: approved, lgtm

#9423 Enable user/password on prow-monitoring/prometheus
  clusters/app.ci/prow-monitoring/prow_prometheus.yaml
Labels: approved, lgtm

#9440 Mount step registry config into dptp-controller-manager
  clusters/app.ci/assets/dptp-controller-manager.yaml
Labels: approved, lgtm

#9444 Remove requirement for jenkins PR check
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#9430 [redhat-developer/service-binding-operator] Update OCP to 4.4 and 4.5
  ci-operator/config/redhat-developer/service-binding-operator/redhat-developer-service-binding-operator-master.yaml
  ci-operator/config/redhat-developer/service-binding-operator/redhat-developer-service-binding-operator-master__4.5.yaml
  ci-operator/jobs/redhat-developer/service-binding-operator/redhat-developer-service-binding-operator-master-periodics.yaml
  ci-operator/jobs/redhat-developer/service-binding-operator/redhat-developer-service-binding-operator-master-presubmits.yaml
Labels: approved, lgtm

#9442 Add Calico e2e tests to 4.3 and 4.4 periodics
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
Labels: approved, lgtm

#9143 Reuse knative-serving-src image to run E2E tests
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master__4.3.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master__4.4.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master__4.5.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master-periodics.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master-presubmits.yaml
Labels: approved, lgtm

#9426 Remove broker images
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next__44.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next__45.yaml
Labels: approved, lgtm

#9439 baremetal: collect additional logs
  ci-operator/step-registry/baremetalds/devscripts/gather/baremetalds-devscripts-gather-commands.sh
Labels: approved, lgtm

#9453 Add e2e-aws and e2e-aws-upgrade jobs for Thanos
  ci-operator/config/openshift/thanos/openshift-thanos-master.yaml
  ci-operator/config/openshift/thanos/openshift-thanos-release-4.6.yaml
  ci-operator/config/openshift/thanos/openshift-thanos-release-4.7.yaml
  ci-operator/jobs/openshift/thanos/openshift-thanos-master-presubmits.yaml
  ci-operator/jobs/openshift/thanos/openshift-thanos-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/thanos/openshift-thanos-release-4.7-presubmits.yaml
Labels: approved, lgtm

#9436 Add periodic CSI job to 4.6 and 4.7
  ci-operator/jobs/openshift/release/openshift-release-release-4.6-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml
Labels: approved, lgtm

#9449 Add Tekton Triggers v0.5.0 Release
  ci-operator/config/openshift/tektoncd-triggers/openshift-tektoncd-triggers-release-v0.5.0.yaml
  ci-operator/jobs/openshift/tektoncd-triggers/openshift-tektoncd-triggers-release-v0.5.0-postsubmits.yaml
  ci-operator/jobs/openshift/tektoncd-triggers/openshift-tektoncd-triggers-release-v0.5.0-presubmits.yaml
  core-services/image-mirroring/tekton/mapping_tekton_triggers_v0_5_quay
Labels: approved, lgtm

#9456 4.5 branches: accept upstream MODIFIED, ON_QA, VERIFIED
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#9458 Ci-Search: Use two replicas and add PDB
  clusters/build-clusters/01_cluster/ci-search/deploy.yaml
Labels: approved, lgtm

#9459 Add env variable to generate e2e result for prow
  ci-operator/config/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-master.yaml
  ci-operator/jobs/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-master-presubmits.yaml
Labels: approved, lgtm

#9464 Add postsubmit job for aws-efs-operator codecov
  ci-operator/jobs/openshift/aws-efs-operator/openshift-aws-efs-operator-master-postsubmits.yaml
Labels: approved, lgtm

#9466 release-controller: use ocp 4.6 images for caches
  core-services/release-controller/deploy-ocp-controller.yaml
  core-services/release-controller/deploy-origin-controller.yaml
Labels: approved, lgtm

#9471 Reflect removal of images
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next__44.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next__45.yaml
Labels: approved, lgtm

#9462 Add e2e-metal-ipi to cluster-api-provider-baremetal 4.4
  ci-operator/config/openshift/cluster-api-provider-baremetal/openshift-cluster-api-provider-baremetal-release-4.4.yaml
  ci-operator/jobs/openshift/cluster-api-provider-baremetal/openshift-cluster-api-provider-baremetal-release-4.4-presubmits.yaml
Labels: approved, lgtm

#9470 Enable 'approve' plugin for all sriov operator related repos
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#9480 Add missing dev-scripts image to baremetal-operator release-4.4
  ci-operator/config/openshift/baremetal-operator/openshift-baremetal-operator-release-4.4.yaml
Labels: approved, lgtm

#9140 OpenStack: Move 4.5 periodic jobs to Vexxhost
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
Labels: approved, lgtm

#9477 fix ovirt org name in plugins
  ci-operator/config/oVirt/csi-driver/OWNERS
  ci-operator/config/oVirt/csi-driver/oVirt-csi-driver-master.yaml
  ci-operator/jobs/oVirt/csi-driver/OWNERS
  ci-operator/jobs/oVirt/csi-driver/oVirt-csi-driver-master-postsubmits.yaml
  ci-operator/jobs/oVirt/csi-driver/oVirt-csi-driver-master-presubmits.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#8065 OpenStack: fix binaries in test image
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e.yaml
Labels: approved, lgtm

#9301 Add ovirt/cluster-api-provider-ovirt to CI
  ci-operator/config/oVirt/cluster-api-provider-ovirt/OWNERS
  ci-operator/config/oVirt/cluster-api-provider-ovirt/oVirt-cluster-api-provider-ovirt-master.yaml
  ci-operator/jobs/oVirt/cluster-api-provider-ovirt/OWNERS
  ci-operator/jobs/oVirt/cluster-api-provider-ovirt/oVirt-cluster-api-provider-ovirt-master-postsubmits.yaml
  ci-operator/jobs/oVirt/cluster-api-provider-ovirt/oVirt-cluster-api-provider-ovirt-master-presubmits.yaml
Labels: approved, lgtm

#8667 Modify upi template test to work on release-4.4
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.4-presubmits.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-upi-e2e.yaml
Labels: approved, lgtm

#9485 ci-operator: Disable the metering e2e aws upgrade test.
  ci-operator/config/kube-reporting/metering-operator/kube-reporting-metering-operator-release-4.5.yaml
  ci-operator/config/kube-reporting/metering-operator/kube-reporting-metering-operator-release-4.6.yaml
  ci-operator/config/kube-reporting/metering-operator/kube-reporting-metering-operator-release-4.7.yaml
  ci-operator/jobs/kube-reporting/metering-operator/kube-reporting-metering-operator-release-4.5-presubmits.yaml
  ci-operator/jobs/kube-reporting/metering-operator/kube-reporting-metering-operator-release-4.6-presubmits.yaml
  ci-operator/jobs/kube-reporting/metering-operator/kube-reporting-metering-operator-release-4.7-presubmits.yaml
Labels: approved, lgtm

#9492 ovirt: configure tide and image mirroring
  core-services/image-mirroring/ovirt/mapping_cluster-api-provider-ovirt_quay
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#9174 enable open-cluster-management nucleus integration test
  ci-operator/config/open-cluster-management/nucleus/open-cluster-management-nucleus-master.yaml
  ci-operator/jobs/open-cluster-management/nucleus/open-cluster-management-nucleus-master-presubmits.yaml
Labels: approved, lgtm, ok-to-test

#9502 Removing evneting operator 0.14 builds and image promotion
  ci-operator/config/openshift-knative/eventing-operator/openshift-knative-eventing-operator-release-0.14.yaml
  ci-operator/jobs/openshift-knative/eventing-operator/openshift-knative-eventing-operator-release-0.14-postsubmits.yaml
  ci-operator/jobs/openshift-knative/eventing-operator/openshift-knative-eventing-operator-release-0.14-presubmits.yaml
Labels: approved, lgtm

#9504 Narrow down Packet failure message content
  ci-operator/step-registry/baremetalds/packet/setup/baremetalds-packet-setup-commands.sh
  ci-operator/step-registry/baremetalds/packet/teardown/baremetalds-packet-teardown-commands.sh
Labels: approved, lgtm

#9465 Knative operator
  ci-operator/config/openshift-knative/operator/OWNERS
  ci-operator/config/openshift-knative/operator/openshift-knative-operator-release-0.14.yaml
  ci-operator/jobs/openshift-knative/operator/OWNERS
  ci-operator/jobs/openshift-knative/operator/openshift-knative-operator-release-0.14-postsubmits.yaml
  ci-operator/jobs/openshift-knative/operator/openshift-knative-operator-release-0.14-presubmits.yaml
Labels: approved, lgtm

#8905 update openshift-apiserver-release-4.4 to use go-1.13
  ci-operator/config/openshift/openshift-apiserver/openshift-openshift-apiserver-release-4.4.yaml
Labels: approved, lgtm

#9500 ovirt: Add presubmits to machine-config-operator 4.5
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.5-presubmits.yaml
Labels: approved, lgtm

#9491 Spyglass: Highlight namespace deletion message
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#9494 CI-Tools: Use go 1.14
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
Labels: approved, lgtm

#9488 Test images distributor: Distribute the clonerefs image
  clusters/app.ci/assets/dptp-controller-manager.yaml
Labels: approved, lgtm

#9506 Adding images for master to the CI operator
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next__44.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next__45.yaml
Labels: approved, lgtm

#9484 SDCICD-297. Introduce moa pipelines.
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-master-periodics.yaml
Labels: approved, lgtm

#9507 Revert "Merge pull request #9487 from alvaroaleman/prow-cm"
  clusters/app.ci/hack/generate-bw-items.sh
  clusters/app.ci/prow-monitoring/plank_servicemonitor.yaml
  clusters/app.ci/prow/03_deployment/admin_prow_controller_manager_rbac.yaml
  clusters/app.ci/prow/03_deployment/plank.yaml
  clusters/app.ci/prow/03_deployment/prow-controller-manager.yaml
  clusters/build-clusters/01_cluster/hack/generate-bw-items.sh
  clusters/build-clusters/01_cluster/prow/03_deployment/admin_prow_controller_manager_rbac.yaml
  clusters/build-clusters/02_cluster/hack/generate-bw-items.sh
  clusters/build-clusters/02_cluster/prow/03_deployment/admin_prow_controller_manager_rbac.yaml
  core-services/ci-secret-bootstrap/_config.yaml
  core-services/prow/03_deployment/admin_prow_controller_manager_rbac.yaml
Labels: approved, lgtm

#9509 add openshift/kubernetes-autoscaler to release-3.11 branch
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#8993 Add openshift release testing for 4.4 on ppc64le OpenStack cloud
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
Labels: approved, lgtm

#9510 acm mco-app: add publish postsubmit job
  ci-operator/jobs/open-cluster-management/multicloud-operators-application/open-cluster-management-multicloud-operators-application-openshiftci-postsubmits.yaml
Labels: approved, lgtm

#9282 Create CI for openshift-tests-private repo
  ci-operator/config/openshift/openshift-tests-private/.config.prowgen
  ci-operator/config/openshift/openshift-tests-private/OWNERS
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-master.yaml
  ci-operator/jobs/openshift/openshift-tests-private/OWNERS
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-master-presubmits.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#9473 Ovirt e2e: Add ovirt test provider and increase CPUs of test pod
  ci-operator/templates/openshift/installer/cluster-launch-installer-ovirt-e2e.yaml
Labels: approved, lgtm

#9452 Update kuryr master to use 4.6 repos
  ci-operator/config/openshift/kuryr-kubernetes/openshift-kuryr-kubernetes-master.yaml
Labels: approved, lgtm

#9455 Produce image with eventing sources
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.13.0.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.13.0__44.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.13.0__45.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.14.0.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.14.0__4.4.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.14.0__4.5.yaml
Labels: approved, lgtm

#9513 Add dev-scripts image to baremetal-operator 4.5
  ci-operator/config/openshift/baremetal-operator/openshift-baremetal-operator-release-4.5.yaml
Labels: approved, lgtm

#9531 ci-operator/jobs/openshift/cmo: update jsonnet tooling image
  ci-operator/jobs/openshift/cluster-monitoring-operator/openshift-cluster-monitoring-operator-master-presubmits.yaml
Labels: approved, lgtm

#9530 Setup image building and CI for Knative Serving 0.14.1.
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-v0.14.1__4.3.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-v0.14.1-postsubmits.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-v0.14.1-presubmits.yaml
Labels: approved, lgtm

#9534 Adding 0.14.2 for eventing
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.14.2.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.14.2__4.4.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.14.2__4.5.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.14.2-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.14.2-presubmits.yaml
  core-services/image-mirroring/knative/mapping_knative_v0_14_quay
Labels: approved, lgtm

#9490 upi-gcp-install: enable 'master' name for control plane
  ci-operator/step-registry/upi/install/gcp/upi-install-gcp-commands.sh
Labels: approved, lgtm

#9415 config: add openshift 4.6
  ci-operator/config/openshift/release/openshift-release-master__ocp-4.6.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  core-services/release-controller/_releases/release-ocp-4.6.json
Labels: approved, lgtm

#9533 Modify cron for e2e-metal-ipi 4.4 and 4.5 periodic jobs
  ci-operator/config/openshift/release/openshift-release-master__ocp-4.4.yaml
  ci-operator/config/openshift/release/openshift-release-master__ocp-4.5.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: approved, lgtm

#9496 installer: bump go version to 1.14
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
Labels: approved, lgtm

#9483 Create presubmit configuration for kubevirt/kubevirt, fix nightly
  ci-operator/config/kubevirt/kubevirt/kubevirt-kubevirt-master.yaml
  ci-operator/jobs/kubevirt/kubevirt/kubevirt-kubevirt-master-periodics.yaml
  ci-operator/jobs/kubevirt/kubevirt/kubevirt-kubevirt-master-presubmits.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-custom-test-image.yaml
Labels: approved, lgtm

#9516 Add CI for ocm/registration-operator
  ci-operator/config/open-cluster-management/registration-operator/OWNERS
  ci-operator/config/open-cluster-management/registration-operator/open-cluster-management-registration-operator-master.yaml
  ci-operator/jobs/open-cluster-management/registration-operator/OWNERS
  ci-operator/jobs/open-cluster-management/registration-operator/open-cluster-management-registration-operator-master-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/registration-operator/open-cluster-management-registration-operator-master-presubmits.yaml
  core-services/image-mirroring/open-cluster-management/mapping_open_cluster_management_latest_quay
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#9542 Upgrade tag specs for dev-scripts
  ci-operator/config/openshift-metal3/dev-scripts/openshift-metal3-dev-scripts-master.yaml
Labels: approved, lgtm

#9406 okd-4.5+: use cri-o:1.18
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.6-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml
Labels: approved, lgtm

#9407 ci-operator/config/openshift: promote fcos branches to 4.5
  ci-operator/config/openshift/installer/openshift-installer-fcos.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-fcos.yaml
Labels: approved, lgtm

#9544 ci-operator: Disable metering upgrade e2e aws test for the master branch.
  ci-operator/config/kube-reporting/metering-operator/kube-reporting-metering-operator-master.yaml
  ci-operator/jobs/kube-reporting/metering-operator/kube-reporting-metering-operator-master-presubmits.yaml
Labels: approved, lgtm

#9538 ovn-kubernetes: add CI to release-4.5, bump to go-1.13
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.5.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.6.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.7.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.5-presubmits.yaml
Labels: approved, lgtm

#9551 Add iostat to the debug daemon set
  clusters/build-clusters/01_cluster/machine_config/bpf-sync-ds_daemonset.yaml
Labels: approved, lgtm

#9549 ocm/registration-operator: promote src image
  ci-operator/config/open-cluster-management/registration-operator/open-cluster-management-registration-operator-master.yaml
  ci-operator/jobs/open-cluster-management/registration-operator/open-cluster-management-registration-operator-master-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/registration-operator/open-cluster-management-registration-operator-master-presubmits.yaml
Labels: approved, lgtm

#9475 Explicitly schedule 4.4 periodic jobs 4 hours apart.
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
Labels: approved, lgtm

#9540 Change e2e-metal-ipi periodic 4.6 scheduling
  ci-operator/config/openshift/release/openshift-release-master__ocp-4.6.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: approved, lgtm

#9548 Scheduling 4.5 periodic jobs to 6 times per day 4 hours apart
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
Labels: approved, lgtm

#9499 Remove extra images from compliance-operator
  ci-operator/config/openshift/compliance-operator/openshift-compliance-operator-master.yaml
Labels: approved, lgtm

#9560 prow config: temporarily remove branch protection for fcos branches on installer/mco
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#9559 Setup Kourier image promotion for 0.14.
  ci-operator/config/openshift-knative/net-kourier/openshift-knative-net-kourier-release-0.14.yaml
  ci-operator/jobs/openshift-knative/net-kourier/openshift-knative-net-kourier-release-0.14-postsubmits.yaml
  ci-operator/jobs/openshift-knative/net-kourier/openshift-knative-net-kourier-release-0.14-presubmits.yaml
Labels: approved, lgtm

#9514 Add missing dev-scripts image for ovn-kubernetes 4.5
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.5.yaml
Labels: approved, lgtm

#9537 Add ci config and job to run e2e-aws on crio-1.19
  ci-operator/config/cri-o/cri-o/cri-o-cri-o-release-1.19.yaml
  ci-operator/jobs/cri-o/cri-o/cri-o-cri-o-release-1.19-presubmits.yaml
Labels: approved, lgtm

#9572 Fix incorrect cluster field
  ci-operator/config/cri-o/cri-o/cri-o-cri-o-release-1.19.yaml
  ci-operator/config/openshift-priv/ovn-kubernetes/openshift-priv-ovn-kubernetes-release-4.5.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.5.yaml
  ci-operator/step-registry/gather/loki/gather-loki-ref.yaml
Labels: approved, lgtm

#9561 Stop using deprecated GCS workers options in Crier
  clusters/app.ci/prow/03_deployment/crier.yaml
Labels: approved, lgtm

#9398 services: add cincinnati-ci
  services/cincinnati-ci/OWNERS
  services/cincinnati-ci/README.md
  services/cincinnati-ci/admin_rbac.yaml
Labels: approved, lgtm

#9568 Dockerfilez for src added
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.14.2.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.14.2__4.4.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.14.2__4.5.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.14.2-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.14.2-presubmits.yaml
Labels: approved, lgtm

#9577 plugins: add review_act_as_lgtm for release-controller repo
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#9550 upi-gcp-install: enable 'worker' name for compute nodes
  ci-operator/step-registry/upi/install/gcp/upi-install-gcp-commands.sh
Labels: approved, lgtm

#9545 vsphere increase compute nodes CPU and memory capacity
  ci-operator/step-registry/ipi/conf/vsphere/ipi-conf-vsphere-commands.sh
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
Labels: approved, lgtm

#9554 Add 4.4, 4.5 for openshift-tests-private
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.4.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.5.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.5-presubmits.yaml
Labels: approved, lgtm

#9536 Serverless reuse knative eventing src image
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master__4.3.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master__4.4.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-master__4.5.yaml
Labels: approved, lgtm

#8964 Add 4.4 remote-libvirt job for s390x
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
Labels: approved, lgtm, ok-to-test

#9591 oVirt: increase worker and master mem for minimal jobs
  ci-operator/templates/openshift/installer/cluster-launch-installer-ovirt-e2e.yaml
Labels: approved, lgtm

#9191 Added alert for openshift-kni/cnf-features-deploy release-4.5
  clusters/app.ci/prow-monitoring/mixins/_prometheus/job_failures_config.libsonnet
  clusters/app.ci/prow-monitoring/mixins/prometheus_out/prometheus-prow-rules_prometheusrule.yaml
Labels: approved, lgtm

#9621 Add Jawed Khelil to Jenkins Operator OWNERS
  ci-operator/jobs/redhat-developer/jenkins-operator/OWNERS
Labels: approved, lgtm

#9622 Install GolangCI Lint for Jenkins Operator tests
  ci-operator/config/redhat-developer/jenkins-operator/redhat-developer-jenkins-operator-master.yaml
Labels: approved, lgtm

#9624 Build dpdk image for release 4.4
  ci-operator/config/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.4.yaml
  ci-operator/jobs/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.4-postsubmits.yaml
  core-services/image-mirroring/openshift-kni/mapping_openshift-kni_quay
Labels: approved, lgtm

#9613 Removed unused secret mapping
  core-services/secret-mirroring/_mapping.yaml
Labels: approved, lgtm

#9626 e2e-openstack-upi: run down_containers if exists
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-upi-e2e.yaml
Labels: approved, lgtm

#9583 update open-cluster-management base image
  ci-operator/config/open-cluster-management/registration-operator/open-cluster-management-registration-operator-master.yaml
  ci-operator/config/open-cluster-management/registration/open-cluster-management-registration-master.yaml
  ci-operator/config/open-cluster-management/work/open-cluster-management-work-master.yaml
Labels: approved, lgtm, ok-to-test

#9628 ComplianceAsCode: add platform-specific names to test and add ocp4 paltform test
  ci-operator/config/ComplianceAsCode/content/ComplianceAsCode-content-master.yaml
  ci-operator/jobs/ComplianceAsCode/content/ComplianceAsCode-content-master-presubmits.yaml
Labels: approved, lgtm

#9592 origin-4.5: create machine-os-content imagestream
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.6-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml
  core-services/release-controller/images-origin-4.5.yaml
Labels: approved, lgtm

#9598 OKD: promote installer to 4.5 imagestream
  ci-operator/config/openshift/installer/openshift-installer-fcos.yaml
Labels: approved, lgtm

#9589 ci-operator/jobs/openshift/release: use "4.x" tag for OKD jobs
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.6-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml
Labels: approved, lgtm

#9604 baremetalds: Use "bash strict mode"
  ci-operator/step-registry/baremetalds/devscripts/setup/baremetalds-devscripts-setup-commands.sh
Labels: approved, lgtm

#9635 Disable tot in plank
  clusters/app.ci/prow/03_deployment/prow-controller-manager.yaml
Labels: approved, lgtm

#9517 installer: use steps for e2e-{aws,azure,gcp}-shared-vpc
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/step-registry/ipi/aws/pre/sharednetwork/OWNERS
  ci-operator/step-registry/ipi/aws/pre/sharednetwork/ipi-aws-pre-sharednetwork-chain.yaml
  ci-operator/step-registry/ipi/azure/pre/sharednetwork/OWNERS
  ci-operator/step-registry/ipi/azure/pre/sharednetwork/ipi-azure-pre-sharednetwork-chain.yaml
  ci-operator/step-registry/ipi/conf/aws/sharednetwork/OWNERS
  ci-operator/step-registry/ipi/conf/aws/sharednetwork/ipi-conf-aws-sharednetwork-chain.yaml
  ci-operator/step-registry/ipi/conf/aws/sharednetwork/ipi-conf-aws-sharednetwork-commands.sh
  ci-operator/step-registry/ipi/conf/aws/sharednetwork/ipi-conf-aws-sharednetwork-ref.yaml
  ci-operator/step-registry/ipi/conf/azure/sharednetwork/OWNERS
  ci-operator/step-registry/ipi/conf/azure/sharednetwork/ipi-conf-azure-sharednetwork-chain.yaml
  ci-operator/step-registry/ipi/conf/azure/sharednetwork/ipi-conf-azure-sharednetwork-commands.sh
  ci-operator/step-registry/ipi/conf/azure/sharednetwork/ipi-conf-azure-sharednetwork-ref.yaml
  ci-operator/step-registry/ipi/conf/gcp/sharednetwork/OWNERS
  ci-operator/step-registry/ipi/conf/gcp/sharednetwork/ipi-conf-gcp-sharednetwork-chain.yaml
  ci-operator/step-registry/ipi/conf/gcp/sharednetwork/ipi-conf-gcp-sharednetwork-commands.sh
  ci-operator/step-registry/ipi/conf/gcp/sharednetwork/ipi-conf-gcp-sharednetwork-ref.yaml
  ci-operator/step-registry/ipi/gcp/pre/sharednetwork/OWNERS
  ci-operator/step-registry/ipi/gcp/pre/sharednetwork/ipi-gcp-pre-sharednetwork-chain.yaml
  ci-operator/step-registry/openshift/e2e/aws/sharednetwork/OWNERS
  ci-operator/step-registry/openshift/e2e/aws/sharednetwork/openshift-e2e-aws-sharednetwork-workflow.yaml
  ci-operator/step-registry/openshift/e2e/azure/sharednetwork/OWNERS
  ci-operator/step-registry/openshift/e2e/azure/sharednetwork/openshift-e2e-azure-sharednetwork-workflow.yaml
  ci-operator/step-registry/openshift/e2e/gcp/sharednetwork/OWNERS
  ci-operator/step-registry/openshift/e2e/gcp/sharednetwork/openshift-e2e-gcp-sharednetwork-workflow.yaml
Labels: approved, lgtm

#9632 Remove fast-datapath-beta repos for RHEL7 & 8
  core-services/release-controller/_repos/ocp-4.3-default.repo
  core-services/release-controller/_repos/ocp-4.3-ppc64le.repo
  core-services/release-controller/_repos/ocp-4.3-rhel8.repo
  core-services/release-controller/_repos/ocp-4.3-s390x.repo
  core-services/release-controller/_repos/ocp-4.4-default.repo
  core-services/release-controller/_repos/ocp-4.4-ppc64le.repo
  core-services/release-controller/_repos/ocp-4.4-rhel8.repo
  core-services/release-controller/_repos/ocp-4.4-s390x.repo
  core-services/release-controller/_repos/ocp-4.5-default.repo
  core-services/release-controller/_repos/ocp-4.5-ppc64le.repo
  core-services/release-controller/_repos/ocp-4.5-rhel8.repo
  core-services/release-controller/_repos/ocp-4.5-s390x.repo
  core-services/release-controller/_repos/ocp-4.6-default.repo
  core-services/release-controller/_repos/ocp-4.6-ppc64le.repo
  core-services/release-controller/_repos/ocp-4.6-rhel8.repo
  core-services/release-controller/_repos/ocp-4.6-s390x.repo
  core-services/release-controller/_repos/ocp-4.7-default.repo
  core-services/release-controller/_repos/ocp-4.7-ppc64le.repo
  core-services/release-controller/_repos/ocp-4.7-rhel8.repo
  core-services/release-controller/_repos/ocp-4.7-s390x.repo
Labels: approved, lgtm

#9532 Onboard managed-upgrade-operator to CI
  ci-operator/config/openshift/managed-upgrade-operator/OWNERS
  ci-operator/config/openshift/managed-upgrade-operator/openshift-managed-upgrade-operator-master.yaml
  ci-operator/jobs/openshift/managed-upgrade-operator/OWNERS
  ci-operator/jobs/openshift/managed-upgrade-operator/openshift-managed-upgrade-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/managed-upgrade-operator/openshift-managed-upgrade-operator-master-presubmits.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#9642 configs: remove branched configurations that shouldnt exist
  ci-operator/config/openshift/aws-account-operator/openshift-aws-account-operator-release-4.6.yaml
  ci-operator/config/openshift/aws-account-operator/openshift-aws-account-operator-release-4.7.yaml
  ci-operator/config/openshift/deadmanssnitch-operator/openshift-deadmanssnitch-operator-release-4.6.yaml
  ci-operator/config/openshift/deadmanssnitch-operator/openshift-deadmanssnitch-operator-release-4.7.yaml
  ci-operator/config/openshift/dedicated-admin-operator/openshift-dedicated-admin-operator-release-4.6.yaml
  ci-operator/config/openshift/dedicated-admin-operator/openshift-dedicated-admin-operator-release-4.7.yaml
  ci-operator/config/openshift/pagerduty-operator/openshift-pagerduty-operator-release-4.6.yaml
  ci-operator/config/openshift/pagerduty-operator/openshift-pagerduty-operator-release-4.7.yaml
  ci-operator/config/openshift/rbac-permissions-operator/openshift-rbac-permissions-operator-release-4.6.yaml
  ci-operator/config/openshift/rbac-permissions-operator/openshift-rbac-permissions-operator-release-4.7.yaml
  ci-operator/jobs/openshift/aws-account-operator/openshift-aws-account-operator-release-4.6-postsubmits.yaml
  ci-operator/jobs/openshift/aws-account-operator/openshift-aws-account-operator-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/aws-account-operator/openshift-aws-account-operator-release-4.7-postsubmits.yaml
  ci-operator/jobs/openshift/aws-account-operator/openshift-aws-account-operator-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/deadmanssnitch-operator/openshift-deadmanssnitch-operator-release-4.6-postsubmits.yaml
  ci-operator/jobs/openshift/deadmanssnitch-operator/openshift-deadmanssnitch-operator-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/deadmanssnitch-operator/openshift-deadmanssnitch-operator-release-4.7-postsubmits.yaml
  ci-operator/jobs/openshift/deadmanssnitch-operator/openshift-deadmanssnitch-operator-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/dedicated-admin-operator/openshift-dedicated-admin-operator-release-4.6-postsubmits.yaml
  ci-operator/jobs/openshift/dedicated-admin-operator/openshift-dedicated-admin-operator-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/dedicated-admin-operator/openshift-dedicated-admin-operator-release-4.7-postsubmits.yaml
  ci-operator/jobs/openshift/dedicated-admin-operator/openshift-dedicated-admin-operator-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/pagerduty-operator/openshift-pagerduty-operator-release-4.6-postsubmits.yaml
  ci-operator/jobs/openshift/pagerduty-operator/openshift-pagerduty-operator-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/pagerduty-operator/openshift-pagerduty-operator-release-4.7-postsubmits.yaml
  ci-operator/jobs/openshift/pagerduty-operator/openshift-pagerduty-operator-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/rbac-permissions-operator/openshift-rbac-permissions-operator-release-4.6-postsubmits.yaml
  ci-operator/jobs/openshift/rbac-permissions-operator/openshift-rbac-permissions-operator-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/rbac-permissions-operator/openshift-rbac-permissions-operator-release-4.7-postsubmits.yaml
  ci-operator/jobs/openshift/rbac-permissions-operator/openshift-rbac-permissions-operator-release-4.7-presubmits.yaml
Labels: approved, lgtm

#9580 Move the aws-efs-operator-codecov-token
  core-services/secret-mirroring/_mapping.yaml
Labels: approved, lgtm

#9638 Replace whitelist/blacklist terminology
  ci-operator/templates/master-sidecar-4.2.yaml
  ci-operator/templates/master-sidecar-4.3.yaml
  ci-operator/templates/master-sidecar-4.4.yaml
  hack/validate-owners.sh
  tools/hack/golang/hack/verify-govet.sh
Labels: approved, lgtm

#9648 Update intervals for OKD machine-os-content promotion jobs
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
Labels: approved, lgtm

#9651 Add prow configurations for private-cluster-rhapi-apischeme-updater
  ci-operator/config/openshift/private-cluster-rhapi-apischeme-updater/OWNERS
  ci-operator/config/openshift/private-cluster-rhapi-apischeme-updater/openshift-private-cluster-rhapi-apischeme-updater-master.yaml
  ci-operator/jobs/openshift/private-cluster-rhapi-apischeme-updater/OWNERS
  ci-operator/jobs/openshift/private-cluster-rhapi-apischeme-updater/openshift-private-cluster-rhapi-apischeme-updater-master-presubmits.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#9593 Revert "prow config: temporarily remove branch protection for fcos branches on installer/mco"
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#9627 Poc to run periodics in eclipse org
  ci-operator/config/eclipse/che-operator/OWNERS
  ci-operator/config/eclipse/che-operator/eclipse-che-operator-master.yaml
  ci-operator/jobs/eclipse/che-operator/OWNERS
  ci-operator/jobs/eclipse/che-operator/eclipse-che-operator-master-periodics.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#9631 Fix post-submit in registration-operator
  ci-operator/jobs/open-cluster-management/registration-operator/open-cluster-management-registration-operator-master-postsubmits.yaml
Labels: approved, lgtm, ok-to-test

#9660 All simonpasquier to view openshift-monitoring stack
  clusters/build-clusters/01_cluster/openshift-monitoring/admin_cluster-monitoring-viewer_list.yaml
Labels: approved, lgtm

#9650 ci-operator/jobs/openshift/release: add 4.5-beta repo for OKD
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.6-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml
Labels: approved, lgtm

#9661 Fix rhel8-fast-datapath urls to point to correct CDN location
  core-services/release-controller/_repos/ocp-4.3-rhel8.repo
  core-services/release-controller/_repos/ocp-4.4-rhel8.repo
  core-services/release-controller/_repos/ocp-4.5-rhel8.repo
  core-services/release-controller/_repos/ocp-4.6-rhel8.repo
  core-services/release-controller/_repos/ocp-4.7-rhel8.repo
Labels: approved, lgtm

#9663 Change image promotion to 0.14.2
  ci-operator/config/openshift-knative/operator/openshift-knative-operator-release-0.14.yaml
Labels: approved, lgtm

#9662 Adding knative-eventing release v0.15.0
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.15.0.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.15.0__4.4.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.15.0__4.5.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.15.0-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.15.0-presubmits.yaml
Labels: approved, lgtm

#9664 machine-config-operator: make 4.5 ci job consistent with master branch
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.5-presubmits.yaml
Labels: approved, lgtm

#9588 oVirt e2e: add ovirt missing jobs
  ci-operator/jobs/openshift/cluster-api-provider-ovirt/openshift-cluster-api-provider-ovirt-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-ovirt/openshift-cluster-api-provider-ovirt-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-ovirt/openshift-cluster-api-provider-ovirt-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.5-presubmits.yaml
Labels: approved, lgtm

#9612 ci-operator/step-registry/openshift: Push e2e flavors under e2e/
  ci-operator/step-registry/gather/network/OWNERS
  ci-operator/step-registry/gather/network/gather-network-chain.yaml
  ci-operator/step-registry/gather/network/gather-network-commands.sh
  ci-operator/step-registry/gather/network/gather-network-ref.yaml
  ci-operator/step-registry/openshift/e2e-aws-ovn/OWNERS
  ci-operator/step-registry/openshift/e2e-aws-sdn-single/OWNERS
  ci-operator/step-registry/openshift/e2e/aws/loki/OWNERS
  ci-operator/step-registry/openshift/e2e/aws/loki/openshift-e2e-aws-loki-workflow.yaml
  ci-operator/step-registry/openshift/e2e/aws/ovn/OWNERS
  ci-operator/step-registry/openshift/e2e/aws/ovn/hybrid/OWNERS
  ci-operator/step-registry/openshift/e2e/aws/ovn/hybrid/openshift-e2e-aws-ovn-hybrid-workflow.yaml
  ci-operator/step-registry/openshift/e2e/aws/ovn/openshift-e2e-aws-ovn-workflow.yaml
  ci-operator/step-registry/openshift/e2e/aws/sdn/OWNERS
  ci-operator/step-registry/openshift/e2e/aws/sdn/multi/OWNERS
  ci-operator/step-registry/openshift/e2e/aws/sdn/multi/openshift-e2e-aws-sdn-multi-workflow.yaml
  ci-operator/step-registry/openshift/e2e/aws/sdn/single/OWNERS
  ci-operator/step-registry/openshift/e2e/aws/sdn/single/openshift-e2e-aws-sdn-single-workflow.yaml
  ci-operator/step-registry/openshift/e2e/vsphere/ovn/OWNERS
  ci-operator/step-registry/openshift/e2e/vsphere/ovn/openshift-e2e-vsphere-ovn-workflow.yaml
Labels: approved, lgtm

#9646 Add crd and rbac for testimagestreamtagimports
  clusters/app.ci/assets/dptp-controller-manager.yaml
Labels: approved, lgtm

#9637 More presubmits build01
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-3.10-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-3.11-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.7-presubmits.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: approved, lgtm

#9673 Revert "More presubmits build01"
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-3.10-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-3.11-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.7-presubmits.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: approved, lgtm

#9674 config: update replace names to match builder
  ci-operator/config/openshift-priv/cluster-config-operator/openshift-priv-cluster-config-operator-master.yaml
  ci-operator/config/openshift-priv/cluster-config-operator/openshift-priv-cluster-config-operator-release-4.4.yaml
  ci-operator/config/openshift-priv/cluster-config-operator/openshift-priv-cluster-config-operator-release-4.5.yaml
  ci-operator/config/openshift-priv/cluster-config-operator/openshift-priv-cluster-config-operator-release-4.6.yaml
  ci-operator/config/openshift-priv/cluster-config-operator/openshift-priv-cluster-config-operator-release-4.7.yaml
  ci-operator/config/openshift-priv/cluster-policy-controller/openshift-priv-cluster-policy-controller-release-4.4.yaml
  ci-operator/config/openshift-priv/cluster-policy-controller/openshift-priv-cluster-policy-controller-release-4.5.yaml
  ci-operator/config/openshift-priv/kubernetes/openshift-priv-kubernetes-marun-testing.yaml
  ci-operator/config/openshift-priv/oc/openshift-priv-oc-master.yaml
  ci-operator/config/openshift-priv/oc/openshift-priv-oc-release-4.4.yaml
  ci-operator/config/openshift-priv/oc/openshift-priv-oc-release-4.5.yaml
  ci-operator/config/openshift-priv/oc/openshift-priv-oc-release-4.6.yaml
  ci-operator/config/openshift-priv/oc/openshift-priv-oc-release-4.7.yaml
  ci-operator/config/openshift-priv/openshift-apiserver/openshift-priv-openshift-apiserver-release-4.5.yaml
  ci-operator/config/openshift-priv/openshift-controller-manager/openshift-priv-openshift-controller-manager-release-4.4.yaml
  ci-operator/config/openshift-priv/origin/openshift-priv-origin-master.yaml
  ci-operator/config/openshift-priv/origin/openshift-priv-origin-release-4.4.yaml
  ci-operator/config/openshift-priv/origin/openshift-priv-origin-release-4.5.yaml
  ci-operator/config/openshift-priv/origin/openshift-priv-origin-release-4.6.yaml
  ci-operator/config/openshift-priv/origin/openshift-priv-origin-release-4.7.yaml
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
  ci-operator/config/openshift/cluster-config-operator/openshift-cluster-config-operator-master.yaml
  ci-operator/config/openshift/cluster-config-operator/openshift-cluster-config-operator-release-4.4.yaml
  ci-operator/config/openshift/cluster-config-operator/openshift-cluster-config-operator-release-4.5.yaml
  ci-operator/config/openshift/cluster-config-operator/openshift-cluster-config-operator-release-4.6.yaml
  ci-operator/config/openshift/cluster-config-operator/openshift-cluster-config-operator-release-4.7.yaml
  ci-operator/config/openshift/cluster-policy-controller/openshift-cluster-policy-controller-release-4.4.yaml
  ci-operator/config/openshift/cluster-policy-controller/openshift-cluster-policy-controller-release-4.5.yaml
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-marun-testing.yaml
  ci-operator/config/openshift/oc/openshift-oc-master.yaml
  ci-operator/config/openshift/oc/openshift-oc-release-4.4.yaml
  ci-operator/config/openshift/oc/openshift-oc-release-4.5.yaml
  ci-operator/config/openshift/oc/openshift-oc-release-4.6.yaml
  ci-operator/config/openshift/oc/openshift-oc-release-4.7.yaml
  ci-operator/config/openshift/openshift-apiserver/openshift-openshift-apiserver-release-4.5.yaml
  ci-operator/config/openshift/openshift-controller-manager/openshift-openshift-controller-manager-release-4.4.yaml
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.4.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.5.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.6.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.7.yaml
Labels: approved, lgtm

#9498 Upgrade go to 1.14 for Telemeter
  ci-operator/config/openshift/telemeter/openshift-telemeter-master.yaml
Labels: approved, lgtm

#9634 monitoring: match non-user errors for dashboard
  clusters/app.ci/prow-monitoring/mixins/_grafana_dashboards/dptp.jsonnet
  clusters/app.ci/prow-monitoring/mixins/_grafana_dashboards_out/dptp.json
Labels: approved, lgtm

#9679 Fix cluster-config-operator dockerfile name
  ci-operator/config/openshift/cluster-config-operator/openshift-cluster-config-operator-master.yaml
Labels: approved, lgtm

#9680 [4.5] Fix cluster-config-operator dockerfile name
  ci-operator/config/openshift/cluster-config-operator/openshift-cluster-config-operator-release-4.5.yaml
Labels: approved, lgtm

#9682 [4.4] Fix cluster-config-operator dockerfile name
  ci-operator/config/openshift/cluster-config-operator/openshift-cluster-config-operator-release-4.4.yaml
Labels: approved, lgtm

#9683 [4.3] Fix cluster-config-operator dockerfile name
  ci-operator/config/openshift/cluster-config-operator/openshift-cluster-config-operator-release-4.3.yaml
Labels: approved, lgtm

#9693 mount all cluster kubeconfigs in pj-rehearse job
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
Labels: approved, lgtm
