Repository openshift/release, pull requests merged in 2020-05, with the labels that each got.

#8699 Remove m5d machineautoscaler temporarily
  clusters/build-clusters/01_cluster/assets/build01-9hdwj-worker-us-east-1a-m5d4x_machineautoscaler.yaml
  clusters/build-clusters/01_cluster/assets/build01-9hdwj-worker-us-east-1a_machineautoscaler.yaml
  clusters/build-clusters/01_cluster/assets/build01-9hdwj-worker-us-east-1b-m5d4x_machineautoscaler.yaml
  clusters/build-clusters/01_cluster/assets/build01-9hdwj-worker-us-east-1b_machineautoscaler.yaml
  clusters/build-clusters/01_cluster/assets/build01-9hdwj-worker-us-east-1c_machineautoscaler.yaml
Labels: approved, lgtm

#8706 baremetal: Log output so that it's indexed by CI
  ci-operator/step-registry/baremetalds/devscripts/gather/baremetalds-devscripts-gather-commands.sh
  ci-operator/step-registry/baremetalds/devscripts/setup/baremetalds-devscripts-setup-commands.sh
Labels: approved, lgtm

#8700 Fix minReplicas in machineautoscalers
  clusters/build-clusters/01_cluster/assets/build01-9hdwj-worker-us-east-1a_machineautoscaler.yaml
  clusters/build-clusters/01_cluster/assets/build01-9hdwj-worker-us-east-1b_machineautoscaler.yaml
  clusters/build-clusters/01_cluster/assets/build01-9hdwj-worker-us-east-1c_machineautoscaler.yaml
Labels: approved, lgtm

#8709 SDCICD-276. Add 4.3.0->next test.
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-master-periodics.yaml
Labels: approved, lgtm

#8713 presubmits: differentiate metadata check by name
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
Labels: approved, lgtm

#8710 prow/bugzilla: release-4.4 now requires 4.4.z
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#8715 Use gp2 400g for m5 instances on build01
  clusters/build-clusters/01_cluster/openshift-machine-api/admin_build01-9hdwj-worker-us-east-1a_machine_set.yaml
  clusters/build-clusters/01_cluster/openshift-machine-api/admin_build01-9hdwj-worker-us-east-1b_machine_set.yaml
  clusters/build-clusters/01_cluster/openshift-machine-api/admin_build01-9hdwj-worker-us-east-1c_machine_set.yaml
Labels: approved, lgtm

#8681 Clean up temp clusterrolebindings on build01
  clusters/build-clusters/01_cluster/assets/admin_cluster-admin-0_list.yaml
  clusters/build-clusters/01_cluster/assets/admin_cluster-reader-0_list.yaml
Labels: approved, lgtm

#8696 Add prow recording rules to build01
  clusters/build-clusters/01_cluster/assets/prom_prow_rules.yaml
Labels: approved, lgtm

#8631 ci-operator/step-registry/ipi/install: Remove ClusterVersion channel
  ci-operator/step-registry/ipi/install/install/ipi-install-install-commands.sh
  ci-operator/templates/openshift/installer/cluster-launch-installer-custom-test-image.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-metal-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-upi-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-ovirt-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-remote-libvirt-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-src.yaml
Labels: approved, lgtm

#8718 Fix deletePolicy: Oldest
  clusters/build-clusters/01_cluster/openshift-machine-api/admin_build01-9hdwj-worker-us-east-1a_machine_set.yaml
  clusters/build-clusters/01_cluster/openshift-machine-api/admin_build01-9hdwj-worker-us-east-1b_machine_set.yaml
  clusters/build-clusters/01_cluster/openshift-machine-api/admin_build01-9hdwj-worker-us-east-1c_machine_set.yaml
Labels: approved, lgtm

#8716 baremetal: bump to c3.medium and 2 workers
  ci-operator/step-registry/baremetalds/devscripts/setup/baremetalds-devscripts-setup-commands.sh
  ci-operator/step-registry/baremetalds/packet/setup/baremetalds-packet-setup-commands.sh
Labels: approved, lgtm

#8173 Periodic process to clear Packet leaks
  ci-operator/config/openshift-metal3/dev-scripts/openshift-metal3-dev-scripts-master.yaml
  ci-operator/jobs/openshift-metal3/dev-scripts/openshift-metal3-dev-scripts-master-periodics.yaml
  ci-operator/step-registry/baremetalds/packet/check/OWNERS
  ci-operator/step-registry/baremetalds/packet/check/baremetalds-packet-check-commands.sh
  ci-operator/step-registry/baremetalds/packet/check/baremetalds-packet-check-ref.yaml
Labels: approved, lgtm

#8721 services/coreos: update CoreOS membership
  services/coreos/OWNERS
  services/coreos/admin_group.yaml
Labels: approved, lgtm

#8723 Fix jobs that report to the same context
  ci-operator/jobs/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-libvirt/openshift-cluster-api-provider-libvirt-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-monitoring-operator/openshift-cluster-monitoring-operator-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/telemeter/openshift-telemeter-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/telemeter/openshift-telemeter-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/telemeter/openshift-telemeter-release-4.3-presubmits.yaml
Labels: approved, lgtm

#8665 ci-search: Move to build01
  ci-operator/config/openshift/ci-chat-bot/openshift-ci-chat-bot-master.yaml
  clusters/build-clusters/01_cluster/ci-search/OWNERS
  clusters/build-clusters/01_cluster/ci-search/README.md
  clusters/build-clusters/01_cluster/ci-search/deploy.yaml
  core-services/ci-search/README.md
  core-services/ci-search/_config.yaml
  core-services/ci-search/deploy.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#8752 build01: use 600gb drives for more IOPS
  clusters/build-clusters/01_cluster/openshift-machine-api/admin_build01-9hdwj-worker-us-east-1a_machine_set.yaml
  clusters/build-clusters/01_cluster/openshift-machine-api/admin_build01-9hdwj-worker-us-east-1b_machine_set.yaml
  clusters/build-clusters/01_cluster/openshift-machine-api/admin_build01-9hdwj-worker-us-east-1c_machine_set.yaml
Labels: approved, lgtm

#8724 Add secrets for ci-secret-bootstrap
  core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#8786 Remove knative-build
  ci-operator/config/openshift/knative-build/OWNERS
  ci-operator/config/openshift/knative-build/openshift-knative-build-release-0.2.yaml
  ci-operator/config/openshift/knative-build/openshift-knative-build-release-0.3.yaml
  ci-operator/config/openshift/knative-build/openshift-knative-build-release-v0.4.0.yaml
  ci-operator/config/openshift/knative-build/openshift-knative-build-release-v0.5.0.yaml
  ci-operator/jobs/openshift/knative-build/OWNERS
  ci-operator/jobs/openshift/knative-build/openshift-knative-build-release-0.2-postsubmits.yaml
  ci-operator/jobs/openshift/knative-build/openshift-knative-build-release-0.2-presubmits.yaml
  ci-operator/jobs/openshift/knative-build/openshift-knative-build-release-0.3-postsubmits.yaml
  ci-operator/jobs/openshift/knative-build/openshift-knative-build-release-0.3-presubmits.yaml
  ci-operator/jobs/openshift/knative-build/openshift-knative-build-release-v0.4.0-postsubmits.yaml
  ci-operator/jobs/openshift/knative-build/openshift-knative-build-release-v0.4.0-presubmits.yaml
  ci-operator/jobs/openshift/knative-build/openshift-knative-build-release-v0.5.0-postsubmits.yaml
  ci-operator/jobs/openshift/knative-build/openshift-knative-build-release-v0.5.0-presubmits.yaml
Labels: approved, lgtm

#8623 Move to using step registry in WMCB
  ci-operator/config/openshift/windows-machine-config-bootstrapper/openshift-windows-machine-config-bootstrapper-master.yaml
  ci-operator/config/openshift/windows-machine-config-bootstrapper/openshift-windows-machine-config-bootstrapper-release-4.4.yaml
  ci-operator/config/openshift/windows-machine-config-bootstrapper/openshift-windows-machine-config-bootstrapper-release-4.5.yaml
  ci-operator/config/openshift/windows-machine-config-bootstrapper/openshift-windows-machine-config-bootstrapper-release-4.6.yaml
  ci-operator/config/openshift/windows-machine-config-bootstrapper/openshift-windows-machine-config-bootstrapper-release-4.7.yaml
  ci-operator/jobs/openshift/windows-machine-config-bootstrapper/openshift-windows-machine-config-bootstrapper-master-presubmits.yaml
  ci-operator/jobs/openshift/windows-machine-config-bootstrapper/openshift-windows-machine-config-bootstrapper-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/windows-machine-config-bootstrapper/openshift-windows-machine-config-bootstrapper-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift/windows-machine-config-bootstrapper/openshift-windows-machine-config-bootstrapper-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/windows-machine-config-bootstrapper/openshift-windows-machine-config-bootstrapper-release-4.7-presubmits.yaml
  ci-operator/step-registry/windows/e2e/playbook/OWNERS
  ci-operator/step-registry/windows/e2e/playbook/test/OWNERS
  ci-operator/step-registry/windows/e2e/playbook/test/windows-e2e-playbook-test-commands.sh
  ci-operator/step-registry/windows/e2e/playbook/test/windows-e2e-playbook-test-ref.yaml
Labels: approved, lgtm

#8521 move openshift/os into more relaxed ruleset
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#8793 Adding back 4.5...
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next__45.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-next-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-next-presubmits.yaml
Labels: approved, lgtm

#8796 search: Use the latest ci-search image in build01
  clusters/build-clusters/01_cluster/ci-search/deploy.yaml
Labels: approved, lgtm

#8698 Add job periodic-ci-secret-bootstrap
  ci-operator/jobs/infra-periodics.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: approved, lgtm

#8602 Collect loki logs in openshift/origin
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
Labels: approved, lgtm

#8633 Updating odo test name in prow
  ci-operator/config/openshift/odo/openshift-odo-master__v4.2.yaml
  ci-operator/config/openshift/odo/openshift-odo-master__v4.3.yaml
  ci-operator/config/openshift/odo/openshift-odo-master__v4.4.yaml
  ci-operator/jobs/openshift/odo/openshift-odo-master-presubmits.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: approved, lgtm

#8799 Decreased the duration between CI job runs for compact metal from 48h…
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
Labels: approved, lgtm

#8795 Update app.ci monitoring jobs
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  core-services/sanitize-prow-jobs/_config.yaml
  core-services/supplemental-ci-images/cli-make.yaml
Labels: approved, lgtm

#8804 Add files for ARO v17 release branch
  ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-release-v17.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v17-presubmits.yaml
Labels: approved, lgtm, sig/azure

#8802 Add ports for OpenShift releases 4.4 and 4.5
  core-services/sshd-bastion/ppc64le/deployment.yaml
Labels: approved, lgtm

#8812 Use 700g gp2 device for the workers of build01
  clusters/build-clusters/01_cluster/hack/generate-worker-user-data-m5d4x.sh
  clusters/build-clusters/01_cluster/machine_config/m5d4x_machineconfig.yaml
  clusters/build-clusters/01_cluster/machine_config/worker-m5d4x_machineconfigpool.yaml
  clusters/build-clusters/01_cluster/openshift-machine-api/admin_build01-9hdwj-worker-us-east-1a-m5d4x_machine_set.yaml
  clusters/build-clusters/01_cluster/openshift-machine-api/admin_build01-9hdwj-worker-us-east-1a_machine_set.yaml
  clusters/build-clusters/01_cluster/openshift-machine-api/admin_build01-9hdwj-worker-us-east-1b-m5d4x_machine_set.yaml
  clusters/build-clusters/01_cluster/openshift-machine-api/admin_build01-9hdwj-worker-us-east-1b_machine_set.yaml
  clusters/build-clusters/01_cluster/openshift-machine-api/admin_build01-9hdwj-worker-us-east-1c-m5d4x_machine_set.yaml
  clusters/build-clusters/01_cluster/openshift-machine-api/admin_build01-9hdwj-worker-us-east-1c_machine_set.yaml
Labels: approved, lgtm

#8814 Scale up redirect deployments
  clusters/app.ci/.diff
  core-services/prow/03_deployment/boskos-redirect.yaml
  core-services/prow/03_deployment/deck-redirect.yaml
  core-services/prow/03_deployment/hook-redirect.yaml
Labels: approved, lgtm

#8817 App.ci monitoring postsubmit: use cli-make image from ci namespace
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  core-services/supplemental-ci-images/cli-make.yaml
Labels: approved, lgtm

#8816 Redirect deck and hook to app.ci
  clusters/app.ci/.diff
  core-services/prow/03_deployment/deck-redirect.yaml
  core-services/prow/03_deployment/deck.yaml
  core-services/prow/03_deployment/hook-redirect.yaml
  core-services/prow/03_deployment/hook.yaml
  core-services/prow/03_deployment/horologium.yaml
Labels: approved, lgtm

#8821 Move PrometheusRule/prow-rules to openshift-monitoring folder
  clusters/build-clusters/01_cluster/openshift-monitoring/prow-rules_prometheusrule.yaml
Labels: approved, lgtm

#8792 Config for performance addon operator release-4.5
  ci-operator/config/openshift-kni/performance-addon-operators/openshift-kni-performance-addon-operators-release-4.5.yaml
  ci-operator/jobs/openshift-kni/performance-addon-operators/openshift-kni-performance-addon-operators-release-4.5-postsubmits.yaml
  ci-operator/jobs/openshift-kni/performance-addon-operators/openshift-kni-performance-addon-operators-release-4.5-presubmits.yaml
  core-services/image-mirroring/openshift-kni/mapping_openshift-kni_quay
Labels: approved, lgtm

#8828 Adding Eventing Contrib 0.14.1
  ci-operator/config/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-v0.14.1.yaml
  ci-operator/config/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-v0.14.1__44.yaml
  ci-operator/config/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-v0.14.1__45.yaml
  ci-operator/jobs/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-v0.14.1-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing-contrib/openshift-knative-eventing-contrib-release-v0.14.1-presubmits.yaml
  core-services/image-mirroring/knative/mapping_knative_v0_14_quay
Labels: approved, lgtm

#8826 Enable 4.5 CI for the Serverless GA release.
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.7__4.5.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.7-periodics.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.7-presubmits.yaml
Labels: approved, lgtm

#8668 OpenStack: Add e2e-openstack to CAPO stable branches
  ci-operator/jobs/openshift/cluster-api-provider-openstack/openshift-cluster-api-provider-openstack-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-openstack/openshift-cluster-api-provider-openstack-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-openstack/openshift-cluster-api-provider-openstack-release-4.5-presubmits.yaml
Labels: approved, lgtm

#8810 update with artifact directory
  ci-operator/config/openshift/ibm-roks-toolkit/openshift-ibm-roks-toolkit-release-4.3.yaml
  ci-operator/config/openshift/ibm-roks-toolkit/openshift-ibm-roks-toolkit-release-4.4.yaml
Labels: approved, lgtm

#8842 replace deprecated build01 name in plugins config
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#8271 Add OpenStack cloud with ppc64le compute nodes inside Red Hat for 4.3 CI testing
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e-ppc64le.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#8840 Update for hive ocm-4.4.0 rename to ocm-1.0.
  ci-operator/config/openshift/hive/openshift-hive-ocm-1.0.yaml
  ci-operator/jobs/openshift/hive/openshift-hive-ocm-1.0-postsubmits.yaml
  ci-operator/jobs/openshift/hive/openshift-hive-ocm-1.0-presubmits.yaml
Labels: approved, lgtm

#8848 Fix image replacement
  ci-operator/config/openshift/openshift-apiserver/openshift-openshift-apiserver-master.yaml
Labels: approved, lgtm

#8850 acm: track openshiftci branch for open-cluster-managment org repos
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#8806 Add ARO v17.0 upgrade jobs
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v17-presubmits.yaml
Labels: approved, lgtm, sig/azure

#8846 Makefile: use `prowgen --{from,to}-release-repo`
  Makefile
Labels: approved, lgtm

#8866 build01: increase gp2 size further
  clusters/build-clusters/01_cluster/openshift-machine-api/admin_build01-9hdwj-worker-us-east-1a_machine_set.yaml
  clusters/build-clusters/01_cluster/openshift-machine-api/admin_build01-9hdwj-worker-us-east-1b_machine_set.yaml
  clusters/build-clusters/01_cluster/openshift-machine-api/admin_build01-9hdwj-worker-us-east-1c_machine_set.yaml
Labels: approved, lgtm

#8870 App ci: Bump token timeout
  clusters/app.ci/assets/oauth.yaml
Labels: approved, lgtm

#8867 Proxy hook requests rather than redirecting
  clusters/app.ci/.diff
  core-services/prow/03_deployment/hook-redirect.yaml
Labels: approved, lgtm

#8868 Deploy metrics-cache on app.ci
  Makefile
Labels: approved, lgtm

#8873 O/release postsubmits: Set max_concurrency: 1
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
Labels: approved, lgtm

#8856 Switch toolchain jobs to ocp 4.4
  ci-operator/config/codeready-toolchain/api/codeready-toolchain-api-master.yaml
  ci-operator/config/codeready-toolchain/host-operator/codeready-toolchain-host-operator-master.yaml
  ci-operator/config/codeready-toolchain/member-operator/codeready-toolchain-member-operator-master.yaml
  ci-operator/config/codeready-toolchain/registration-service/codeready-toolchain-registration-service-master.yaml
  ci-operator/config/codeready-toolchain/toolchain-common/codeready-toolchain-toolchain-common-master.yaml
  ci-operator/config/codeready-toolchain/toolchain-e2e/codeready-toolchain-toolchain-e2e-master.yaml
  ci-operator/config/codeready-toolchain/toolchain-operator/codeready-toolchain-toolchain-operator-master.yaml
Labels: approved, lgtm

#8791 oVirt: add boskos leases
  clusters/app.ci/.diff
  clusters/app.ci/prow/03_deployment/boskos_reaper.yaml
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/03_deployment/boskos_reaper.yaml
Labels: approved, lgtm

#8849 Don't require dependent bugs on release-3.11
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#8233 gcp upi: migrates the gcp upi jobs to steps.
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.5.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.6.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.7.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.7-presubmits.yaml
  ci-operator/step-registry/ipi/conf/gcp/OWNERS
  ci-operator/step-registry/ipi/conf/gcp/ipi-conf-gcp-chain.yaml
  ci-operator/step-registry/ipi/conf/gcp/ipi-conf-gcp-commands.sh
  ci-operator/step-registry/ipi/conf/gcp/ipi-conf-gcp-ref.yaml
  ci-operator/step-registry/origin/e2e/gcp/OWNERS
  ci-operator/step-registry/origin/e2e/gcp/upi/OWNERS
  ci-operator/step-registry/origin/e2e/gcp/upi/origin-e2e-gcp-upi-workflow.yaml
  ci-operator/step-registry/upi/OWNERS
  ci-operator/step-registry/upi/conf/OWNERS
  ci-operator/step-registry/upi/conf/gcp/OWNERS
  ci-operator/step-registry/upi/conf/gcp/upi-conf-gcp-chain.yaml
  ci-operator/step-registry/upi/conf/gcp/upi-conf-gcp-commands.sh
  ci-operator/step-registry/upi/conf/gcp/upi-conf-gcp-ref.yaml
  ci-operator/step-registry/upi/deprovision/OWNERS
  ci-operator/step-registry/upi/deprovision/gcp/OWNERS
  ci-operator/step-registry/upi/deprovision/gcp/upi-deprovision-gcp-commands.sh
  ci-operator/step-registry/upi/deprovision/gcp/upi-deprovision-gcp-ref.yaml
  ci-operator/step-registry/upi/gcp/OWNERS
  ci-operator/step-registry/upi/gcp/post/OWNERS
  ci-operator/step-registry/upi/gcp/post/upi-gcp-post-chain.yaml
  ci-operator/step-registry/upi/gcp/pre/OWNERS
  ci-operator/step-registry/upi/gcp/pre/upi-gcp-pre-chain.yaml
  ci-operator/step-registry/upi/gcp/upi-gcp-workflow.yaml
  ci-operator/step-registry/upi/install/OWNERS
  ci-operator/step-registry/upi/install/gcp/OWNERS
  ci-operator/step-registry/upi/install/gcp/upi-install-gcp-commands.sh
  ci-operator/step-registry/upi/install/gcp/upi-install-gcp-ref.yaml
Labels: approved, lgtm

#8800 Moving packet check periodic to variant
  ci-operator/config/openshift-metal3/dev-scripts/openshift-metal3-dev-scripts-master.yaml
  ci-operator/config/openshift-metal3/dev-scripts/openshift-metal3-dev-scripts-master__packetcheck.yaml
  ci-operator/config/openshift-metal3/dev-scripts/openshift-metal3-dev-scripts-release-4.6.yaml
  ci-operator/jobs/openshift-metal3/dev-scripts/openshift-metal3-dev-scripts-master-periodics.yaml
  ci-operator/jobs/openshift-metal3/dev-scripts/openshift-metal3-dev-scripts-release-4.6-periodics.yaml
  ci-operator/step-registry/baremetalds/packet/check/baremetalds-packet-check-commands.sh
Labels: approved, lgtm

#8888 [OCS] adds 4.5.0 and 4.6.0 tags to image & updates latest
  core-services/image-mirroring/ocs-operator/mapping_ocs-operator_quay
Labels: approved, lgtm

#8890 adds bz config for release 4.4 & 4.5 branches
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#8891 adds me to owners of ocs image-mirroring
  core-services/image-mirroring/ocs-operator/OWNERS
Labels: approved, lgtm

#8878 Add user hamzy to have administrator privileges for bastion-ppc64le
  core-services/sshd-bastion/ppc64le/admin_owners_rbac.yaml
Labels: approved, lgtm

#8857 acm: add multicloud-operators-application repo
  ci-operator/config/open-cluster-management/multicloud-operators-application/OWNERS
  ci-operator/config/open-cluster-management/multicloud-operators-application/open-cluster-management-multicloud-operators-application-openshiftci.yaml
  ci-operator/jobs/open-cluster-management/multicloud-operators-application/OWNERS
  ci-operator/jobs/open-cluster-management/multicloud-operators-application/open-cluster-management-multicloud-operators-application-openshiftci-presubmits.yaml
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm, tide/merge-method-squash

#7865 Add ci step for network must gather
  ci-operator/step-registry/gather-network/OWNERS
  ci-operator/step-registry/gather-network/gather-network-chain.yaml
  ci-operator/step-registry/gather-network/gather-network-commands.sh
  ci-operator/step-registry/gather-network/gather-network-ref.yaml
  ci-operator/step-registry/origin/e2e-aws-ovn-hybrid/origin-e2e-aws-ovn-hybrid-workflow.yaml
  ci-operator/step-registry/origin/e2e-aws-ovn/origin-e2e-aws-ovn-workflow.yaml
Labels: approved, lgtm

#8904 Added run_if_changed to delorean tests to igonre docs updates
  ci-operator/jobs/integr8ly/delorean/integr8ly-delorean-master-presubmits.yaml
Labels: approved, lgtm

#8900 Enable image mirroring for ocm/{work,registration}
  core-services/image-mirroring/open-cluster-management/OWNERS
  core-services/image-mirroring/open-cluster-management/mapping_open_cluster_management_latest_quay
Labels: approved, lgtm

#8906 Build dptp-controller-manager
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
Labels: approved, lgtm

#8564 add clnperez as sshd bastion owner for p libvirt
  core-services/sshd-bastion/ppc64le-libvirt/admin_owners_rbac.yaml
Labels: approved, lgtm

#8909 Enable tide for ocm/nucleus
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#8916 Change command used to invoke coverage
  ci-operator/config/openshift/managed-velero-operator/openshift-managed-velero-operator-master.yaml
Labels: approved, lgtm

#8902 Adding the missing upgrader image
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next__44.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next__45.yaml
Labels: approved, lgtm

#8936 Adding the missing upgrader image for kn eventing 0.14
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.14.0.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.14.0__4.4.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.14.0__4.5.yaml
Labels: approved, lgtm

#8938 Adding upgrade images...
  core-services/image-mirroring/knative/mapping_knative_nightly_quay
  core-services/image-mirroring/knative/mapping_knative_v0_14_quay
Labels: approved, lgtm

#8939 add the group-lead-approved label in the configuration
  core-services/prow/02_config/_labels.yaml
Labels: approved, lgtm

#8941 fixing broker quay.io link :fire:
  core-services/image-mirroring/knative/mapping_knative_nightly_quay
  core-services/image-mirroring/knative/mapping_knative_v0_14_quay
Labels: approved, lgtm

#8920 Update the golang version to 1.13
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-master.yaml
Labels: approved, lgtm

#8571 enable open-cluster-management registration integration test
  ci-operator/config/open-cluster-management/registration/open-cluster-management-registration-master.yaml
  ci-operator/jobs/open-cluster-management/registration/open-cluster-management-registration-master-presubmits.yaml
Labels: approved, lgtm, ok-to-test

#8910 acm: mco-app add image
  ci-operator/config/open-cluster-management/multicloud-operators-application/OWNERS
  ci-operator/config/open-cluster-management/multicloud-operators-application/open-cluster-management-multicloud-operators-application-openshiftci.yaml
  ci-operator/jobs/open-cluster-management/multicloud-operators-application/OWNERS
  ci-operator/jobs/open-cluster-management/multicloud-operators-application/open-cluster-management-multicloud-operators-application-openshiftci-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/multicloud-operators-application/open-cluster-management-multicloud-operators-application-openshiftci-presubmits.yaml
Labels: approved, lgtm

#8946 Adding tide query for odh-manifests
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#8947 Enforce jenkins PR check on managed-cluster-validating-webhooks
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#8922 Add deployment for dptp-controller-manager
  clusters/app.ci/assets/dptp-controller-manager.yaml
  core-services/_hack/validate-core-services.sh
  core-services/ci-secret-bootstrap/_config.yaml
  core-services/dptp-controller-manager-serviceaccount/OWNERS
  core-services/dptp-controller-manager-serviceaccount/README.md
  core-services/dptp-controller-manager-serviceaccount/rbac.yaml
Labels: approved, lgtm

#8561 CI Artifacts - add output from "oc get"
  ci-operator/step-registry/gather/extra/gather-extra-commands.sh
Labels: approved, lgtm

#8961 Make kni/cnf-features-deploy 4.5 origin job optional
  ci-operator/jobs/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.5-presubmits.yaml
Labels: approved, lgtm

#8363 ci-operator/jobs: move release-openshift-origin-installer-e2e-azure-compact-4.4 to broken bucket
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
Labels: approved, lgtm

#8935 test spec to verify latest ocs csv
  ci-operator/config/openshift/ocs-operator/openshift-ocs-operator-master.yaml
  ci-operator/config/openshift/ocs-operator/openshift-ocs-operator-release-4.5.yaml
  ci-operator/jobs/openshift/ocs-operator/openshift-ocs-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/ocs-operator/openshift-ocs-operator-release-4.5-presubmits.yaml
Labels: approved, lgtm

#8942 reverts config to use OCP 4.5
  ci-operator/config/openshift/ocs-operator/openshift-ocs-operator-master.yaml
Labels: approved, lgtm

#8934 Promote dev-scripts image to openshift-kni namespace
  ci-operator/config/openshift-metal3/dev-scripts/openshift-metal3-dev-scripts-master.yaml
  ci-operator/config/openshift-metal3/dev-scripts/openshift-metal3-dev-scripts-release-4.6.yaml
  ci-operator/jobs/openshift-metal3/dev-scripts/openshift-metal3-dev-scripts-master-presubmits.yaml
  ci-operator/jobs/openshift-metal3/dev-scripts/openshift-metal3-dev-scripts-release-4.6-postsubmits.yaml
  ci-operator/jobs/openshift-metal3/dev-scripts/openshift-metal3-dev-scripts-release-4.6-presubmits.yaml
Labels: approved, lgtm

#8968 Add imagestreams for origin 4.6 / 4.7
  core-services/release-controller/images-origin-4.6.yaml
  core-services/release-controller/images-origin-4.7.yaml
Labels: approved, lgtm

#8970 baremetal ipi release periodics: fetch dev-script image from openshift-kni/test image stream
  ci-operator/config/openshift/release/openshift-release-master__ocp-4.4.yaml
  ci-operator/config/openshift/release/openshift-release-master__ocp-4.5.yaml
Labels: approved, lgtm

#8720 Adding test for opendatahub-io/odh-manifests
  ci-operator/config/opendatahub-io/odh-manifests/OWNERS
  ci-operator/config/opendatahub-io/odh-manifests/opendatahub-io-odh-manifests-master.yaml
  ci-operator/jobs/opendatahub-io/odh-manifests/OWNERS
  ci-operator/jobs/opendatahub-io/odh-manifests/opendatahub-io-odh-manifests-master-presubmits.yaml
Labels: approved, lgtm, tide/merge-method-squash

#8963 Setting merge method to squash for opendatahub/odh-manifests
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#8950 bump golang version to 1.13
  ci-operator/config/openshift/cluster-api-provider-openstack/openshift-cluster-api-provider-openstack-release-4.4.yaml
Labels: approved, lgtm

#8966 template: Add calico and multisocket variants
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
Labels: approved, lgtm

#8954 ci-operator/step-registry: Pivot to CLUSTER_PROFILE_DIR
  ci-operator/step-registry/ipi/conf/ipi-conf-commands.sh
  ci-operator/step-registry/ipi/conf/vsphere/dns/ipi-conf-vsphere-dns-commands.sh
  ci-operator/step-registry/ipi/deprovision/deprovision/ipi-deprovision-deprovision-commands.sh
  ci-operator/step-registry/ipi/deprovision/vsphere/dns/ipi-deprovision-vsphere-dns-commands.sh
  ci-operator/step-registry/ipi/deprovision/vsphere/vips/ipi-deprovision-vsphere-vips-commands.sh
  ci-operator/step-registry/ipi/install/install/ipi-install-install-commands.sh
  ci-operator/step-registry/origin/e2e/test/origin-e2e-test-commands.sh
  ci-operator/step-registry/windows/e2e/operator/test/windows-e2e-operator-test-commands.sh
  ci-operator/step-registry/windows/e2e/playbook/test/windows-e2e-playbook-test-commands.sh
Labels: approved, lgtm

#8951 Add periodics for ocm image mirroring
  ci-operator/jobs/infra-image-mirroring.yaml
Labels: approved, lgtm

#8952 Bug 1833372: Remove installation of golang dep, because CNO is moving to Go Modules and dep is not required.
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-master.yaml
Labels: approved, lgtm

#8948 Windows step registry tests
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-master.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master-presubmits.yaml
Labels: approved, lgtm

#8967 Add open cluster management push secret
  core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#8978 Remove unnecessary image from cnf-deploy repo
  ci-operator/config/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-master.yaml
  ci-operator/config/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.5.yaml
  core-services/image-mirroring/openshift-kni/mapping_openshift-kni_quay
Labels: approved, lgtm

#8917 Use sshd-43.bastion-ppc64le as hostAliases
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e-ppc64le.yaml
Labels: approved, lgtm

#8958 core-services/prow/02_config/_config: skip valid-bug requirement for fcos branch of MCO
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#8388 rhi operator
  ci-operator/config/redhat-integration/rhi-operator/OWNERS
  ci-operator/config/redhat-integration/rhi-operator/redhat-integration-rhi-operator-master.yaml
  ci-operator/jobs/redhat-integration/rhi-operator/OWNERS
  ci-operator/jobs/redhat-integration/rhi-operator/redhat-integration-rhi-operator-master-postsubmits.yaml
  ci-operator/jobs/redhat-integration/rhi-operator/redhat-integration-rhi-operator-master-presubmits.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, ok-to-test

#8959 openshift/baremetal-operator: fetch dev-scripts image from openshfit-kni/test image stream
  ci-operator/config/openshift/baremetal-operator/openshift-baremetal-operator-master.yaml
Labels: approved, lgtm

#8899 Fix wrong ConfigMap for prow-job-cluster…openstack-e2e-ppc64le
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
Labels: approved, lgtm

#8982 openshift/ironic: fetch dev-scripts image from openshfit-kni/test image stream
  ci-operator/config/openshift/ironic-hardware-inventory-recorder-image/openshift-ironic-hardware-inventory-recorder-image-master.yaml
  ci-operator/config/openshift/ironic-hardware-inventory-recorder-image/openshift-ironic-hardware-inventory-recorder-image-release-4.5.yaml
  ci-operator/config/openshift/ironic-hardware-inventory-recorder-image/openshift-ironic-hardware-inventory-recorder-image-release-4.6.yaml
  ci-operator/config/openshift/ironic-hardware-inventory-recorder-image/openshift-ironic-hardware-inventory-recorder-image-release-4.7.yaml
  ci-operator/config/openshift/ironic-image/openshift-ironic-image-master.yaml
  ci-operator/config/openshift/ironic-image/openshift-ironic-image-release-4.5.yaml
  ci-operator/config/openshift/ironic-image/openshift-ironic-image-release-4.6.yaml
  ci-operator/config/openshift/ironic-image/openshift-ironic-image-release-4.7.yaml
  ci-operator/config/openshift/ironic-inspector-image/openshift-ironic-inspector-image-master.yaml
  ci-operator/config/openshift/ironic-inspector-image/openshift-ironic-inspector-image-release-4.5.yaml
  ci-operator/config/openshift/ironic-inspector-image/openshift-ironic-inspector-image-release-4.6.yaml
  ci-operator/config/openshift/ironic-inspector-image/openshift-ironic-inspector-image-release-4.7.yaml
  ci-operator/config/openshift/ironic-ipa-downloader/openshift-ironic-ipa-downloader-master.yaml
  ci-operator/config/openshift/ironic-ipa-downloader/openshift-ironic-ipa-downloader-release-4.5.yaml
  ci-operator/config/openshift/ironic-ipa-downloader/openshift-ironic-ipa-downloader-release-4.6.yaml
  ci-operator/config/openshift/ironic-ipa-downloader/openshift-ironic-ipa-downloader-release-4.7.yaml
  ci-operator/config/openshift/ironic-rhcos-downloader/openshift-ironic-rhcos-downloader-master.yaml
  ci-operator/config/openshift/ironic-rhcos-downloader/openshift-ironic-rhcos-downloader-release-4.5.yaml
  ci-operator/config/openshift/ironic-rhcos-downloader/openshift-ironic-rhcos-downloader-release-4.6.yaml
  ci-operator/config/openshift/ironic-rhcos-downloader/openshift-ironic-rhcos-downloader-release-4.7.yaml
  ci-operator/config/openshift/ironic-static-ip-manager/openshift-ironic-static-ip-manager-master.yaml
  ci-operator/config/openshift/ironic-static-ip-manager/openshift-ironic-static-ip-manager-release-4.5.yaml
  ci-operator/config/openshift/ironic-static-ip-manager/openshift-ironic-static-ip-manager-release-4.6.yaml
  ci-operator/config/openshift/ironic-static-ip-manager/openshift-ironic-static-ip-manager-release-4.7.yaml
Labels: approved, lgtm

#8977 add boskos lease config for jobs that are missing it
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.6-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml
Labels: approved, lgtm

#8844 add whitelist configuration file
  core-services/openshift-priv/_whitelist.yaml
Labels: approved, lgtm

#8995 openshift/ovn-kubernetes: fetch dev-scripts image from openshfit-kni/test image stream
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.4.yaml
Labels: approved, lgtm

#9003 Revert "Add file-integrity-logcollector image"
  ci-operator/config/openshift/file-integrity-operator/openshift-file-integrity-operator-master.yaml
Labels: approved, lgtm

#8876 Add ms/build01-9hdwj-worker-us-east-1a-debug
  clusters/build-clusters/01_cluster/machine_config/debug_ctrcfg.yaml
  clusters/build-clusters/01_cluster/machine_config/debug_mcp.yaml
  clusters/build-clusters/01_cluster/machine_config/kubelet-debug_machineconfig.yaml
  clusters/build-clusters/01_cluster/openshift-machine-api/admin_build01-9hdwj-worker-us-east-1a-debug_machine_set.yaml
Labels: approved, lgtm

#9001 baremetal: collect logs even if gather fails
  ci-operator/step-registry/baremetalds/devscripts/gather/baremetalds-devscripts-gather-commands.sh
Labels: approved, lgtm

#9006 add ppc64le-libvirt to boskos resources
  clusters/app.ci/.diff
  clusters/app.ci/prow/03_deployment/boskos_reaper.yaml
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/03_deployment/boskos_reaper.yaml
Labels: approved, lgtm

#8996 Parameterize the installer image used for ppc64le OpenStack testing
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e-ppc64le.yaml
Labels: approved, lgtm

#9012 Increase the app.ci ghproxy pvc so it matches the live one
  clusters/app.ci/.diff
  clusters/app.ci/prow/03_deployment/ghproxy.yaml
Labels: approved, lgtm

#9008 Add do-not-merge/product-pre-release to intly missing labels
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#9013 result-aggregator: use TLS and redirect http traffic
  core-services/result-aggregator/result-aggregator.yaml
Labels: approved, lgtm

#9020 secrets: add result-aggregator password
  core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#9021 dptp-dashboard: filter failure reasons to exclude user input
  cluster/ci/monitoring/mixins/grafana_dashboards/dptp.jsonnet
  cluster/ci/monitoring/mixins/grafana_dashboards_out/dptp.json
Labels: approved, lgtm

#9022 ci-tools: use production-install
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
Labels: approved, lgtm

#9007 Redirect to app.ci and turn off prow on api.ci
  clusters/app.ci/.diff
  core-services/prow/03_deployment/deck.yaml
  core-services/prow/03_deployment/hook.yaml
  core-services/prow/03_deployment/horologium.yaml
  core-services/prow/03_deployment/jenkins_operator.yaml
  core-services/prow/03_deployment/plank.yaml
  core-services/prow/03_deployment/sinker.yaml
  core-services/prow/03_deployment/statusreconciler.yaml
  core-services/prow/03_deployment/tide.yaml
Labels: approved, do-not-merge/hold, lgtm

#9018 Redirect requests to boskos
  clusters/app.ci/.diff
  core-services/prow/03_deployment/boskos-redirect.yaml
  core-services/prow/03_deployment/boskos.yaml
Labels: approved, lgtm

#9019 Scale up prow on app.ci
  clusters/app.ci/.diff
  clusters/app.ci/prow/03_deployment/horologium.yaml
  clusters/app.ci/prow/03_deployment/plank.yaml
  clusters/app.ci/prow/03_deployment/sinker.yaml
  clusters/app.ci/prow/03_deployment/statusreconciler.yaml
  clusters/app.ci/prow/03_deployment/tide.yaml
Labels: approved, do-not-merge/hold

#9015 Monitor app.ci prow only
  cluster/ci/monitoring/Makefile
Labels: approved, lgtm

#9014 Use app.ci as prowjob cluster for release-controller
  clusters/app.ci/assets/release-controller.yaml
  core-services/ci-secret-bootstrap/_config.yaml
  core-services/release-controller/deploy-ocp-controller-ppc64le.yaml
  core-services/release-controller/deploy-ocp-controller-s390x.yaml
  core-services/release-controller/deploy-ocp-controller.yaml
  core-services/release-controller/deploy-origin-controller.yaml
Labels: approved, lgtm

#9016 Move ci-chat-bot to app.ci
  clusters/app.ci/ci-chat-bot.yaml
  clusters/app.ci/ci-chat-bot/OWNERS
  clusters/app.ci/ci-chat-bot/README.md
  clusters/app.ci/ci-chat-bot/ci-chat-bot.yaml
  core-services/ci-chat-bot/admin_rbac.yaml
  core-services/ci-chat-bot/deploy.yaml
Labels: approved, lgtm

#9026 update monitor script for app.ci
  hack/monitor_prow.py
Labels: approved, lgtm

#9027 Deploy chat bot token on app.ci
  core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#8670 dashboards: Add OpenStack Vexxhost to boskos
  cluster/ci/monitoring/mixins/grafana_dashboards/boskos.jsonnet
  cluster/ci/monitoring/mixins/grafana_dashboards_out/boskos.json
Labels: approved, lgtm

#9031 Scale plank up and deck down
  clusters/app.ci/.diff
  core-services/prow/03_deployment/deck.yaml
  core-services/prow/03_deployment/plank.yaml
Labels: approved, lgtm

#9004 console: update to tectonic-console-builder:v20
  ci-operator/config/openshift/console/openshift-console-master.yaml
  ci-operator/config/openshift/console/openshift-console-release-4.5.yaml
  ci-operator/config/openshift/console/openshift-console-release-4.6.yaml
  ci-operator/config/openshift/console/openshift-console-release-4.7.yaml
  projects/origin-stable/release.yaml
Labels: approved, lgtm

#9034 Giving the ci-chat-bot the ability to read ocp imagestreams and imagestream tags
  clusters/app.ci/ci-chat-bot/ci-chat-bot.yaml
Labels: approved, lgtm

#9035 Disable updating prow-monitoring on api.ci
  Makefile
Labels: approved, lgtm

#9023 result-aggregator: enforce basic auth
  core-services/result-aggregator/result-aggregator.yaml
Labels: approved, lgtm

#9032 Fix deck-internal redirect
  clusters/app.ci/.diff
  core-services/prow/03_deployment/deck.yaml
Labels: approved, lgtm

#9036 Use a dedicated prowjob kubeconfig for pj-rehearse
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  clusters/app.ci/assets/pj-rehearse.yaml
  core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#7800 Fixes ci for jenkins operator
  ci-operator/config/redhat-developer/jenkins-operator/OWNERS
  ci-operator/config/redhat-developer/jenkins-operator/redhat-developer-jenkins-operator-master.yaml
Labels: approved, lgtm

#9044 Fix deployment result-aggregator
  core-services/result-aggregator/result-aggregator.yaml
Labels: approved, lgtm

#9046 Fix a typo in result-aggregator deployment
  core-services/result-aggregator/result-aggregator.yaml
Labels: approved

#9047 Add a calico release periodic
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
Labels: approved, lgtm

#9043 SDCICD-283. Add prod default minus 1-4 automation jobs.
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-master-periodics.yaml
Labels: approved, lgtm

#9041 Allow ci-admins to read asserts on app.ci
  clusters/app.ci/assets/admin_cluster-admin-0_list.yaml
Labels: approved, lgtm

#9048 ci-chat-bot image is promoting to wrong spot
  ci-operator/config/openshift/ci-chat-bot/openshift-ci-chat-bot-master.yaml
Labels: approved, lgtm

#8984 openshift/cluster-api-provider-baremetal: fetch dev-scripts image from openshfit-kni/test image stream
  ci-operator/config/openshift/cluster-api-provider-baremetal/openshift-cluster-api-provider-baremetal-master.yaml
  ci-operator/config/openshift/cluster-api-provider-baremetal/openshift-cluster-api-provider-baremetal-release-4.5.yaml
  ci-operator/config/openshift/cluster-api-provider-baremetal/openshift-cluster-api-provider-baremetal-release-4.6.yaml
  ci-operator/config/openshift/cluster-api-provider-baremetal/openshift-cluster-api-provider-baremetal-release-4.7.yaml
Labels: approved, lgtm

#9045 Configure ci-chat bot with build-cluster-kubeconfig
  clusters/app.ci/ci-chat-bot/ci-chat-bot.yaml
  core-services/ci-chat-bot/OWNERS
  core-services/ci-chat-bot/README.md
  core-services/ci-chat-bot/ci-chat-bot.yaml
  core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#8983 openshift/baremetal-runtimecfg: fetch dev-scripts image from openshfit-kni/test image stream
  ci-operator/config/openshift/baremetal-runtimecfg/openshift-baremetal-runtimecfg-master.yaml
  ci-operator/config/openshift/baremetal-runtimecfg/openshift-baremetal-runtimecfg-release-4.5.yaml
  ci-operator/config/openshift/baremetal-runtimecfg/openshift-baremetal-runtimecfg-release-4.6.yaml
  ci-operator/config/openshift/baremetal-runtimecfg/openshift-baremetal-runtimecfg-release-4.7.yaml
Labels: approved, lgtm

#8986 openshift/cluster-network-operator: fetch dev-scripts image from openshfit-kni/test image stream
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-master.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.4.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.5.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.6.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.7.yaml
Labels: approved, lgtm

#9049 Add umohnani8 as a cluster-reader on build01
  clusters/build-clusters/01_cluster/assets/admin_cluster-reader-0_list.yaml
Labels: approved, lgtm

#8985 openshift/openshift-cluster-etcd-operator: fetch dev-scripts image from openshfit-kni/test image stream
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-master.yaml
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.4.yaml
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.5.yaml
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.6.yaml
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.7.yaml
Labels: approved, lgtm

#9052 Periodics for ibm-roks-toolkit
  ci-operator/jobs/openshift/ibm-roks-toolkit/openshift-ibm-roks-toolkit-release-4.3-periodics.yaml
  ci-operator/jobs/openshift/ibm-roks-toolkit/openshift-ibm-roks-toolkit-release-4.4-periodics.yaml
Labels: approved, lgtm

#9055 Add few missing job YAML to app.ci configmaps
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#8988 openshift/installer: fetch dev-scripts image from openshfit-kni/test image stream
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.4.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.5.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.6.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.7.yaml
Labels: approved, lgtm
