Repository openshift/release, pull requests merged in 2021-01, with the labels that each got.

#14515 Add test job to Alertmanager
  ci-operator/config/openshift/prometheus-alertmanager/openshift-prometheus-alertmanager-master.yaml
  ci-operator/jobs/openshift/prometheus-alertmanager/openshift-prometheus-alertmanager-master-presubmits.yaml
Labels: approved, lgtm

#14558 Add e2e-metal-assisted-onprem to TestGrid
  ci-operator/config/openshift/release/openshift-release-master__ocp-4.6.yaml
  ci-operator/config/openshift/release/openshift-release-master__ocp-4.7.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  core-services/release-controller/_releases/priv/release-ocp-4.6.json
  core-services/release-controller/_releases/priv/release-ocp-4.7.json
  core-services/release-controller/_releases/release-ocp-4.6.json
  core-services/release-controller/_releases/release-ocp-4.7.json
  core-services/testgrid-config-generator/_allow-list.yaml
Labels: approved, lgtm

#14560 livenessprobe: Bump golang to 1.15
  ci-operator/config/openshift/csi-livenessprobe/openshift-csi-livenessprobe-master.yaml
  ci-operator/config/openshift/csi-livenessprobe/openshift-csi-livenessprobe-release-4.7.yaml
  ci-operator/config/openshift/csi-livenessprobe/openshift-csi-livenessprobe-release-4.8.yaml
Labels: approved, lgtm

#14559 Adding KNI-EDGE project to app.ci
  clusters/app.ci/kni-edge/OWNERS
  clusters/app.ci/kni-edge/README.md
  clusters/app.ci/kni-edge/admin_rbac.yaml
Labels: approved, lgtm

#14565 Use a dedicated role for ppl managing their pull secrets
  clusters/app.ci/assets/secrets-manager-role.yaml
  clusters/app.ci/codeready-toolchain/admin_codeready-toolchain.yaml
  clusters/app.ci/fabric8-services/admin_fabric8-services_list.yaml
  clusters/app.ci/images-openshift-acme/admin_images-openshift-acme_list.yaml
  clusters/app.ci/integr8ly/admin_integr8ly.yaml
  clusters/app.ci/ocp-kni/admin_ocp-kni_list.yaml
  clusters/app.ci/ocs/admin_rbac.yaml
  clusters/app.ci/open-cluster-management/admin_open-cluster-management.yaml
  clusters/app.ci/ovirt/admin_ovirt_list.yaml
  clusters/app.ci/redht-developer/admin_redht-developer_list.yaml
Labels: approved, lgtm

#14539 Update oVirt team on admin_ovirt_list.yaml
  clusters/app.ci/ovirt/admin_ovirt_list.yaml
Labels: approved, lgtm

#14566 Add RBAC to read SA's credentials
  clusters/app.ci/kni-edge/README.md
  clusters/app.ci/kni-edge/admin_rbac.yaml
Labels: approved, lgtm

#14568 Annotate rc configs on app.ci
  hack/annotate.sh
Labels: approved, lgtm

#14571 supplemental-ci-images: Add Ubuntu image
  clusters/app.ci/supplemental-ci-images/README.md
  clusters/app.ci/supplemental-ci-images/ubuntu.yaml
Labels: approved, lgtm

#14569 Remove services/ca-cert-issuer folder
  services/ca-cert-issuer/Dockerfile
  services/ca-cert-issuer/OWNERS
  services/ca-cert-issuer/README.md
  services/ca-cert-issuer/ca-cert-issuer_list.yaml
Labels: approved, lgtm

#14572 Use the new registry in jobs: namespace/azure
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-infra-periodics.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-periodics.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v15-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v16-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v17-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v19-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v20-presubmits.yaml
Labels: approved, lgtm

#14576 Revert failed context change and set in postsubmit
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  core-services/sanitize-prow-jobs/_config.yaml
  hack/annotate.sh
Labels: approved, lgtm

#14305 OKD: build cluster-update-keys from Dockerfile
  ci-operator/config/openshift/cluster-update-keys/openshift-cluster-update-keys-master__okd.yaml
  ci-operator/config/openshift/cluster-update-keys/openshift-cluster-update-keys-release-4.6__okd.yaml
  ci-operator/config/openshift/cluster-update-keys/openshift-cluster-update-keys-release-4.7__okd.yaml
  ci-operator/jobs/openshift/cluster-update-keys/openshift-cluster-update-keys-master-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-update-keys/openshift-cluster-update-keys-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-update-keys/openshift-cluster-update-keys-release-4.6-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-update-keys/openshift-cluster-update-keys-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/cluster-update-keys/openshift-cluster-update-keys-release-4.7-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-update-keys/openshift-cluster-update-keys-release-4.7-presubmits.yaml
  core-services/release-controller/_releases/release-ocp-4.6-ci.json
  core-services/release-controller/_releases/release-ocp-4.7-ci.json
Labels: approved, lgtm

#14570 [wmcb] Remove make build-tools from config
  ci-operator/config/openshift/windows-machine-config-bootstrapper/openshift-windows-machine-config-bootstrapper-master.yaml
  ci-operator/config/openshift/windows-machine-config-bootstrapper/openshift-windows-machine-config-bootstrapper-release-4.6.yaml
  ci-operator/config/openshift/windows-machine-config-bootstrapper/openshift-windows-machine-config-bootstrapper-release-4.7.yaml
  ci-operator/config/openshift/windows-machine-config-bootstrapper/openshift-windows-machine-config-bootstrapper-release-4.8.yaml
Labels: approved, lgtm

#14573 Fix rbac list and enable secret backups
  core-services/release-controller/admin_deploy-ocp-publish-art.yaml
  hack/generators/release-controllers/content/__init__.py
  hack/generators/release-controllers/content/art_namespaces_rbac.py
  hack/generators/release-controllers/content/art_publish_permissions.py
  hack/generators/release-controllers/content/bump_versioned_resources.py
  hack/generators/release-controllers/content/osd_files_cache_rbac.py
  hack/generators/release-controllers/content/osd_rc_deployments.py
  hack/generators/release-controllers/generate-release-controllers.py
  hack/validate-prow-job-semantics.py
  hack/validate-release-jobs.py
Labels: lgtm

#14575 Use apps auth for kubevirt org
  clusters/app.ci/prow/03_deployment/crier.yaml
Labels: approved, lgtm

#14584 Updating the cli-jq image location to app.ci
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
Labels: approved, lgtm

#14587 Fix pullspec for branch-ci-openshift-release-master-release-controller annotate
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
Labels: approved, lgtm

#14590 Move app.ci mirror configs into common folder
  clusters/app.ci/registry-access/cnv/admin_01_rbac.yaml
  clusters/app.ci/registry-access/codeready-toolchain/admin_codeready-toolchain.yaml
  clusters/app.ci/registry-access/fabric8-services/admin_fabric8-services_list.yaml
  clusters/app.ci/registry-access/images-openshift-acme/admin_images-openshift-acme_list.yaml
  clusters/app.ci/registry-access/integr8ly/admin_integr8ly.yaml
  clusters/app.ci/registry-access/kni-edge/OWNERS
  clusters/app.ci/registry-access/kni-edge/README.md
  clusters/app.ci/registry-access/kni-edge/admin_rbac.yaml
  clusters/app.ci/registry-access/ocp-kni/admin_ocp-kni_list.yaml
  clusters/app.ci/registry-access/ocs/OWNERS
  clusters/app.ci/registry-access/ocs/README.md
  clusters/app.ci/registry-access/ocs/admin_rbac.yaml
  clusters/app.ci/registry-access/open-cluster-management/admin_open-cluster-management.yaml
  clusters/app.ci/registry-access/ovirt/admin_ovirt_list.yaml
  clusters/app.ci/registry-access/redht-developer/admin_redht-developer_list.yaml
Labels: approved, lgtm

#14588 DPTP cm: Name pull secret volume after secret
  clusters/app.ci/assets/dptp-controller-manager.yaml
Labels: approved, lgtm

#14589 Use apps auth crier for app-sre organization
  clusters/app.ci/prow/03_deployment/crier.yaml
Labels: approved, lgtm

#14591 release: disseminate pull credentials
  Makefile
  ci-operator/jobs/openshift/release/openshift-release-release-4.1-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.6-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.8-periodics.yaml
Labels: approved, lgtm

#14562 remove cincinnati buildconfig from o/release postsubmit-update
  Makefile
  projects/cincinnati/cincinnati.yaml
Labels: approved, lgtm

#14467 ci-operator/step-registry/gather: Exclude empty-string "instance IDs"
  ci-operator/step-registry/gather/gcp-console/gather-gcp-console-commands.sh
Labels: approved, lgtm

#14598 dptp-cm deployment: fix credentials mount
  clusters/app.ci/assets/dptp-controller-manager.yaml
Labels: approved, lgtm

#14446 openshift-release-release-4.6-periodics: use stable stream in OKD 4.6 promotions
  ci-operator/jobs/openshift/release/openshift-release-release-4.6-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml
Labels: approved, lgtm

#14605 Adding missing images for 0.19 test runs
  core-services/image-mirroring/knative/mapping_knative_v0_19_quay
Labels: approved, lgtm

#14412 Insights Operator 4.5 image update
  ci-operator/config/openshift/insights-operator/openshift-insights-operator-release-4.5.yaml
Labels: approved, lgtm

#14604 Drop secret-reader role according to latest docs
  clusters/app.ci/registry-access/kni-edge/admin_rbac.yaml
Labels: approved, lgtm

#14600 v1beta1 -> v1 API versions for RBAC and CRDs
  clusters/app.ci/assets/admin_cluster-admin-0_list.yaml
  clusters/app.ci/assets/dptp-controller-manager.yaml
  clusters/app.ci/cert-manager/_cert-manager.yaml
  clusters/app.ci/prow-monitoring/admin_user_roles.yaml
  clusters/app.ci/prow/01_crd/admin_01_prowjob_crd.yaml
  clusters/app.ci/prow/01_crd/admin_02_prowjob_rbac.yaml
  clusters/app.ci/prow/01_crd/admin_03_boskos_crds.yaml
  clusters/app.ci/registry-access/codeready-toolchain/admin_codeready-toolchain.yaml
  clusters/app.ci/registry-access/fabric8-services/admin_fabric8-services_list.yaml
  clusters/app.ci/registry-access/integr8ly/admin_integr8ly.yaml
  clusters/app.ci/registry-access/open-cluster-management/admin_open-cluster-management.yaml
  clusters/build-clusters/01_cluster/cert-manager/_cert-manager.yaml
Labels: approved, lgtm

#14603 Create admin_manifest.yaml for cnf-qe
  clusters/app.ci/registry-access/cnf-qe/admin_manifest.yaml
Labels: approved, lgtm

#14609 Distribute ci-pull-secret to multi-arch release controllers
  core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#14613 Create a token for programmatic access for cnf-ci
  clusters/app.ci/registry-access/cnf-ci/OWNERS
  clusters/app.ci/registry-access/cnf-ci/README.md
  clusters/app.ci/registry-access/cnf-ci/admin_manifest.yaml
Labels: approved, lgtm

#14607 Add the new common-templates release branch
  ci-operator/config/kubevirt/common-templates/kubevirt-common-templates-release-v0.13.yaml
  ci-operator/jobs/kubevirt/common-templates/kubevirt-common-templates-release-v0.13-presubmits.yaml
Labels: approved, lgtm

#14612 ARO jobs secret mounting(1)
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
Labels: approved, lgtm

#14619 dptp-cm: Sync images openshift/origin-v4.0*
  clusters/app.ci/assets/dptp-controller-manager.yaml
Labels: approved, lgtm

#14621 Bug 1909853: Remove metal IPI periodics for 4.4
  ci-operator/config/openshift/release/openshift-release-master__ocp-4.4.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  core-services/release-controller/_releases/priv/release-ocp-4.4.json
  core-services/release-controller/_releases/release-ocp-4.4.json
Labels: approved, lgtm

#14595 Sync ovirt upgrade jobs
  core-services/release-controller/_releases/release-ocp-4.5-ci.json
  core-services/release-controller/_releases/release-ocp-4.6-ci.json
  core-services/release-controller/_releases/release-ocp-4.7-ci.json
  core-services/release-controller/_releases/release-ocp-4.8-ci.json
Labels: approved, lgtm

#14620 crds: update manifests for v1
  clusters/app.ci/assets/dptp-controller-manager.yaml
  clusters/app.ci/cert-manager/_cert-manager.yaml
Labels: approved, lgtm

#14614 ci-operator: Remove metering 4.6+ nightly testing jobs
  ci-operator/config/kube-reporting/metering-operator/kube-reporting-metering-operator-master.yaml
  ci-operator/config/kube-reporting/metering-operator/kube-reporting-metering-operator-release-4.5.yaml
  ci-operator/config/kube-reporting/metering-operator/kube-reporting-metering-operator-release-4.6.yaml
  ci-operator/config/kube-reporting/metering-operator/kube-reporting-metering-operator-release-4.7.yaml
  ci-operator/config/kube-reporting/metering-operator/kube-reporting-metering-operator-release-4.8.yaml
  ci-operator/jobs/kube-reporting/metering-operator/kube-reporting-metering-operator-master-periodics.yaml
  ci-operator/jobs/kube-reporting/metering-operator/kube-reporting-metering-operator-release-4.5-periodics.yaml
  ci-operator/jobs/kube-reporting/metering-operator/kube-reporting-metering-operator-release-4.6-periodics.yaml
  ci-operator/jobs/kube-reporting/metering-operator/kube-reporting-metering-operator-release-4.7-periodics.yaml
  ci-operator/jobs/kube-reporting/metering-operator/kube-reporting-metering-operator-release-4.8-periodics.yaml
Labels: approved, lgtm

#14623 Updating the CLI override string for all multi-arch controllers
  core-services/release-controller/_releases/priv/release-ocp-4.2-ppc64le.json
  core-services/release-controller/_releases/priv/release-ocp-4.2-s390x.json
  core-services/release-controller/_releases/priv/release-ocp-4.3-ppc64le.json
  core-services/release-controller/_releases/priv/release-ocp-4.3-s390x.json
  core-services/release-controller/_releases/priv/release-ocp-4.4-ppc64le.json
  core-services/release-controller/_releases/priv/release-ocp-4.4-s390x.json
  core-services/release-controller/_releases/priv/release-ocp-4.5-ppc64le.json
  core-services/release-controller/_releases/priv/release-ocp-4.5-s390x.json
  core-services/release-controller/_releases/priv/release-ocp-4.6-ppc64le.json
  core-services/release-controller/_releases/priv/release-ocp-4.6-s390x.json
  core-services/release-controller/_releases/priv/release-ocp-4.7-ppc64le.json
  core-services/release-controller/_releases/priv/release-ocp-4.7-s390x.json
  core-services/release-controller/_releases/priv/release-ocp-4.8-ppc64le.json
  core-services/release-controller/_releases/priv/release-ocp-4.8-s390x.json
  core-services/release-controller/_releases/release-ocp-4.2-ppc64le.json
  core-services/release-controller/_releases/release-ocp-4.2-s390x.json
  core-services/release-controller/_releases/release-ocp-4.3-ppc64le.json
  core-services/release-controller/_releases/release-ocp-4.3-s390x.json
  core-services/release-controller/_releases/release-ocp-4.4-ppc64le.json
  core-services/release-controller/_releases/release-ocp-4.4-s390x.json
  core-services/release-controller/_releases/release-ocp-4.5-ppc64le.json
  core-services/release-controller/_releases/release-ocp-4.5-s390x.json
  core-services/release-controller/_releases/release-ocp-4.6-ppc64le.json
  core-services/release-controller/_releases/release-ocp-4.6-s390x.json
  core-services/release-controller/_releases/release-ocp-4.7-ppc64le.json
  core-services/release-controller/_releases/release-ocp-4.7-s390x.json
  core-services/release-controller/_releases/release-ocp-4.8-ppc64le.json
  core-services/release-controller/_releases/release-ocp-4.8-s390x.json
  core-services/release-controller/_releases/release-ocp-4.y-stable-ppc64le.json
  core-services/release-controller/_releases/release-ocp-4.y-stable-s390x.json
  core-services/release-controller/_releases/release-ocp-4.y-stable.json
  core-services/release-controller/_releases/release-origin-4.y-stable.json
  core-services/release-controller/deploy-ocp-controller.yaml
  core-services/release-controller/deploy-ocp-ppc64le-controller.yaml
  core-services/release-controller/deploy-ocp-ppc64le-priv-controller.yaml
  core-services/release-controller/deploy-ocp-priv-controller.yaml
  core-services/release-controller/deploy-ocp-s390x-controller.yaml
  core-services/release-controller/deploy-ocp-s390x-priv-controller.yaml
  hack/generators/release-controllers/content/redirect_resources.py
Labels: approved, lgtm

#14617 Adding a few test images we vendor from knative/eventing repo
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-next__46.yaml
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-next__47.yaml
Labels: approved, lgtm

#14618 fix OAL master and 4.6 jobs to have larger compute nodes
  ci-operator/config/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-master.yaml
  ci-operator/config/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-release-4.6.yaml
Labels: approved, lgtm

#14437 Add a job for the ci-secret generator
  ci-operator/jobs/infra-periodics.yaml
  core-services/ci-secret-generator/_config.yaml
  core-services/prow/02_config/_plugins.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: approved, lgtm

#14552 Add e2e-metal-sno-live-iso presubmit workflow to assisted-test-infra
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-presubmits.yaml
  ci-operator/step-registry/baremetalds/sno/OWNERS
  ci-operator/step-registry/baremetalds/sno/baremetalds-sno-workflow.metadata.json
  ci-operator/step-registry/baremetalds/sno/baremetalds-sno-workflow.yaml
  ci-operator/step-registry/baremetalds/sno/gather/OWNERS
  ci-operator/step-registry/baremetalds/sno/gather/baremetalds-sno-gather-commands.sh
  ci-operator/step-registry/baremetalds/sno/gather/baremetalds-sno-gather-ref.metadata.json
  ci-operator/step-registry/baremetalds/sno/gather/baremetalds-sno-gather-ref.yaml
  ci-operator/step-registry/baremetalds/sno/setup/OWNERS
  ci-operator/step-registry/baremetalds/sno/setup/baremetalds-sno-setup-commands.sh
  ci-operator/step-registry/baremetalds/sno/setup/baremetalds-sno-setup-ref.metadata.json
  ci-operator/step-registry/baremetalds/sno/setup/baremetalds-sno-setup-ref.yaml
Labels: approved, lgtm

#14597 Add e2e-openstack-ipi job to mdns-publisher
  ci-operator/config/openshift/mdns-publisher/openshift-mdns-publisher-master.yaml
  ci-operator/jobs/openshift/mdns-publisher/openshift-mdns-publisher-master-presubmits.yaml
Labels: approved, lgtm

#14625 Move folder services/cincinnati-ci to app.ci
  clusters/app.ci/supplemental-ci-images/cincinnati-ci/OWNERS
  clusters/app.ci/supplemental-ci-images/cincinnati-ci/README.md
  clusters/app.ci/supplemental-ci-images/cincinnati-ci/admin_rbac.yaml
  clusters/app.ci/supplemental-ci-images/cincinnati-ci/imagestream-release-4.4.yaml
  clusters/app.ci/supplemental-ci-images/cincinnati-ci/imagestream-release-4.6.yaml
  clusters/app.ci/supplemental-ci-images/cincinnati-ci/imagestream-release-4.7.yaml
  clusters/app.ci/supplemental-ci-images/cincinnati-ci/imagestream.yaml
Labels: approved, lgtm

#14627 Move folder services/coreos to app.ci
  clusters/app.ci/supplemental-ci-images/coreos/OWNERS
  clusters/app.ci/supplemental-ci-images/coreos/README.md
  clusters/app.ci/supplemental-ci-images/coreos/admin_group.yaml
  clusters/app.ci/supplemental-ci-images/coreos/admin_project.yaml
  clusters/app.ci/supplemental-ci-images/coreos/admin_rbac.yaml
  clusters/app.ci/supplemental-ci-images/coreos/cosa-buildroot.yaml
  clusters/app.ci/supplemental-ci-images/coreos/cosa-exttests.yaml
  clusters/app.ci/supplemental-ci-images/coreos/cosa-upstream-is.yaml
Labels: approved, lgtm

#14628 Crier: Use apps auth for integr8ly
  clusters/app.ci/prow/03_deployment/crier.yaml
Labels: approved, lgtm

#14631 Enable the secret refresher controller for the ci namespace
  clusters/app.ci/assets/dptp-controller-manager.yaml
  clusters/build-clusters/common/assets/admin_dptp-controller-manager_rbac.yaml
Labels: approved, lgtm

#14630 Move folder services/squid-egress-proxy to app.ci
  clusters/app.ci/supplemental-ci-images/squid-egress-proxy/Dockerfile
  clusters/app.ci/supplemental-ci-images/squid-egress-proxy/OWNERS
  clusters/app.ci/supplemental-ci-images/squid-egress-proxy/README.md
  clusters/app.ci/supplemental-ci-images/squid-egress-proxy/build.yaml
  clusters/app.ci/supplemental-ci-images/squid-egress-proxy/entrypoint.sh
  clusters/app.ci/supplemental-ci-images/squid-egress-proxy/squid.repo
Labels: approved, lgtm

#14643 Being faster, just use 4.7 CI runs for nightly
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-next__46.yaml
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-next__47.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next__46.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next__47.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-next-postsubmits.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-next-presubmits.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-next-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-next-presubmits.yaml
Labels: approved, lgtm

#14645 Mount secret to aro jobs
  ci-operator/config/openshift/openshift-azure/OWNERS
  ci-operator/jobs/openshift/openshift-azure/OWNERS
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-infra-periodics.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-periodics.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v15-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v16-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v17-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v19-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v20-presubmits.yaml
  projects/azure/OWNERS
Labels: approved, lgtm, sig/azure

#14644 oVirt: add admin_list to app.ci cluster
  clusters/app.ci/registry-access/ovirt/admin_list.yaml
  clusters/app.ci/registry-access/ovirt/admin_ovirt_list.yaml
Labels: approved, lgtm

#14549 Kam test secrets mapping
  core-services/secret-mirroring/_mapping.yaml
Labels: approved, lgtm

#14647 Update the command to generate a pull secret for registry.ci.openshif…
  clusters/app.ci/registry-access/cnf-ci/README.md
Labels: approved, lgtm

#14648 image-puller rbacs: use rbac.authorization.k8s.io/v1
  clusters/app.ci/azure/admin_azure_list.yaml
  clusters/app.ci/registry-access/images-openshift-acme/admin_images-openshift-acme_list.yaml
  clusters/app.ci/registry-access/ocp-kni/admin_ocp-kni_list.yaml
  clusters/app.ci/registry-access/ovirt/admin_list.yaml
  clusters/app.ci/registry-access/redht-developer/admin_redht-developer_list.yaml
Labels: approved, lgtm

#14420 Add test-unit job to kube-rbac-proxy
  ci-operator/config/openshift/kube-rbac-proxy/openshift-kube-rbac-proxy-master.yaml
  ci-operator/jobs/openshift/kube-rbac-proxy/openshift-kube-rbac-proxy-master-presubmits.yaml
Labels: approved, lgtm

#14646 Change occurrences of 'sno' to 'single-node'
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-presubmits.yaml
  ci-operator/step-registry/baremetalds/sno/baremetalds-sno-workflow.yaml
  ci-operator/step-registry/baremetalds/sno/gather/baremetalds-sno-gather-commands.sh
  ci-operator/step-registry/baremetalds/sno/setup/baremetalds-sno-setup-commands.sh
  ci-operator/step-registry/baremetalds/sno/setup/baremetalds-sno-setup-ref.yaml
Labels: approved, lgtm

#14510 Use the new registry in jobs: namespace/openshift
  ci-operator/jobs/openshift/ci-vm-operator/openshift-ci-vm-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/library/openshift-library-master-periodics.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-src.yaml
Labels: approved, lgtm

#14639 Doc the usage of cincinnati images
  clusters/app.ci/supplemental-ci-images/README.md
Labels: approved, lgtm

#14653 [rhd-sbo] Move failed job notifications to reporter_config of prow job.
  ci-operator/jobs/redhat-developer/service-binding-operator/redhat-developer-service-binding-operator-master-periodics.yaml
  clusters/app.ci/prow-monitoring/mixins/_prometheus/job_failures_config.libsonnet
  clusters/app.ci/prow-monitoring/mixins/config.libsonnet
  clusters/app.ci/prow-monitoring/mixins/prometheus_out/_alertmanager.yaml
  clusters/app.ci/prow-monitoring/mixins/prometheus_out/alertmanager-prow-secret_template.yaml
  clusters/app.ci/prow-monitoring/mixins/prometheus_out/prometheus-prow-rules_prometheusrule.yaml
Labels: approved, lgtm

#14658 Moving the release-controller-bootstap imagestream to app.ci
  clusters/app.ci/release-controller/deploy-ocp-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-ppc64le-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-ppc64le-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-s390x-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-s390x-priv-controller.yaml
  core-services/release-controller/deploy-ocp-controller.yaml
  core-services/release-controller/deploy-ocp-ppc64le-controller.yaml
  core-services/release-controller/deploy-ocp-ppc64le-priv-controller.yaml
  core-services/release-controller/deploy-ocp-priv-controller.yaml
  core-services/release-controller/deploy-ocp-s390x-controller.yaml
  core-services/release-controller/deploy-ocp-s390x-priv-controller.yaml
  hack/generators/release-controllers/content/osd_rc_deployments.py
  hack/generators/release-controllers/content/redirect_resources.py
Labels: approved, lgtm

#14556 enable configuring 'single-node' variant
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  core-services/template-deprecation/_allowlist.yaml
Labels: approved, lgtm

#14626 steps/openshift-e2e-test: Use TEST_TYPE instead of generic TEST_COMMAND
  ci-operator/config/openshift-priv/cluster-version-operator/openshift-priv-cluster-version-operator-master.yaml
  ci-operator/config/openshift-priv/cluster-version-operator/openshift-priv-cluster-version-operator-release-4.5.yaml
  ci-operator/config/openshift-priv/cluster-version-operator/openshift-priv-cluster-version-operator-release-4.6.yaml
  ci-operator/config/openshift-priv/cluster-version-operator/openshift-priv-cluster-version-operator-release-4.7.yaml
  ci-operator/config/openshift-priv/cluster-version-operator/openshift-priv-cluster-version-operator-release-4.8.yaml
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-master.yaml
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-release-4.5.yaml
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-release-4.6.yaml
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-release-4.7.yaml
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-release-4.8.yaml
  ci-operator/config/openshift/release/openshift-release-master__ocp-4.5-ci.yaml
  ci-operator/jobs/openshift/release/openshift-release-infra-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.1-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.6-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.8-periodics.yaml
  ci-operator/step-registry/openshift/e2e/test/openshift-e2e-test-commands.sh
  ci-operator/step-registry/openshift/e2e/test/openshift-e2e-test-ref.yaml
  ci-operator/step-registry/openshift/upgrade/aws/hosted-loki/openshift-upgrade-aws-hosted-loki-workflow.yaml
  ci-operator/step-registry/openshift/upgrade/aws/openshift-upgrade-aws-workflow.yaml
  ci-operator/step-registry/openshift/upgrade/azure/openshift-upgrade-azure-workflow.yaml
  ci-operator/step-registry/openshift/upgrade/gcp/hosted-loki/openshift-upgrade-gcp-hosted-loki-workflow.yaml
  ci-operator/step-registry/openshift/upgrade/gcp/openshift-upgrade-gcp-workflow.yaml
  ci-operator/templates/openshift/endurance/endurance-test.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-custom-test-image.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-metal-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-upi-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-ovirt-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-remote-libvirt-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
Labels: approved, lgtm

#14659 Add alert when component fails to construct a client
  clusters/app.ci/prow-monitoring/mixins/_prometheus/dptp_alerts.libsonnet
  clusters/app.ci/prow-monitoring/mixins/prometheus_out/prometheus-prow-rules_prometheusrule.yaml
Labels: approved, lgtm

#14660 Maintain repo configmap on app.ci
  core-services/ci-secret-bootstrap/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#14594 request token for ocp-qe team
  clusters/app.ci/registry-access/ocp-qe/OWNERS
  clusters/app.ci/registry-access/ocp-qe/README.md
  clusters/app.ci/registry-access/ocp-qe/admin_manifest.yaml
Labels: approved, lgtm

#14665 steps/openshift-e2e-test: Allow a test to configure the bastion
  ci-operator/step-registry/openshift/e2e/test/openshift-e2e-test-commands.sh
  ci-operator/step-registry/openshift/e2e/test/openshift-e2e-test-ref.yaml
Labels: approved, lgtm

#14670 Ignoring all release-controller-bootstrap imagestreams
  clusters/app.ci/assets/dptp-controller-manager.yaml
Labels: approved, lgtm

#14662 Skipped multi-arch tests that depend on external dns resolution working on the 3.11 cluster.
  ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml
Labels: approved, lgtm

#14656 console: add kind/i18n label to repo
  core-services/prow/02_config/_labels.yaml
Labels: approved, lgtm

#14668 steps/openshift-e2e-test: Allow suite-conformance as a TEST_TYPE
  ci-operator/step-registry/openshift/e2e/test/openshift-e2e-test-commands.sh
  ci-operator/step-registry/openshift/e2e/test/openshift-e2e-test-ref.yaml
Labels: approved, lgtm

#14637 Fix BCs for coreos
  clusters/app.ci/supplemental-ci-images/README.md
  clusters/app.ci/supplemental-ci-images/coreos/cosa-buildroot.yaml
  clusters/app.ci/supplemental-ci-images/coreos/cosa-exttests.yaml
  clusters/app.ci/supplemental-ci-images/coreos/cosa-upstream-is.yaml
Labels: approved, lgtm

#14674 steps/openshift-e2e-test: e2e tests can take longer than 2h
  ci-operator/step-registry/openshift/e2e/test/openshift-e2e-test-ref.yaml
Labels: approved, lgtm

#14676 release: Switch 4.7-ci to block on GCP instead of Azure
  core-services/release-controller/_releases/release-ocp-4.7-ci.json
Labels: approved, lgtm

#14675 update extrac token command
  clusters/app.ci/registry-access/ocp-qe/README.md
Labels: approved, lgtm

#14577 Migrate azure jobs away from api.ci
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v15-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v16-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v17-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v19-presubmits.yaml
  ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-release-v20-presubmits.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: approved, lgtm

#14680 remove duplicated secret from ci-secret-bootstrap config
  core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#14679 periodics: use images from registry.ci.openshift.org
  ci-operator/jobs/openshift/release/openshift-release-release-4.1-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.6-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.8-periodics.yaml
Labels: approved, lgtm

#14649 Fix ci-pull-credentials to be consistently dockerconfigjson
  core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#14681 Remove KubeVirt master vs OCP 4.4
  ci-operator/config/kubevirt/kubevirt/kubevirt-kubevirt-master__4.4.yaml
  ci-operator/jobs/kubevirt/kubevirt/kubevirt-kubevirt-master-periodics.yaml
Labels: approved, lgtm

#14580 Change assisted DEPLOY_TARGET from podman-localhost to onprem
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/config/openshift/release/openshift-release-master__ocp-4.6.yaml
  ci-operator/config/openshift/release/openshift-release-master__ocp-4.7.yaml
  ci-operator/step-registry/baremetalds/assisted/gather/baremetalds-assisted-gather-commands.sh
Labels: approved, lgtm

#14368 MON-1208: add test-unit job to kube-state-metrics
  ci-operator/config/openshift/kube-state-metrics/openshift-kube-state-metrics-master.yaml
  ci-operator/jobs/openshift/kube-state-metrics/openshift-kube-state-metrics-master-presubmits.yaml
Labels: approved, lgtm

#14372 MON-1208: add test-unit job to prometheus-operator
  ci-operator/config/openshift/prometheus-operator/openshift-prometheus-operator-master.yaml
  ci-operator/jobs/openshift/prometheus-operator/openshift-prometheus-operator-master-presubmits.yaml
Labels: approved, lgtm

#14650 Use app.ci registry to get CI tools
  Makefile
  hack/generate-template-allowlist.sh
Labels: approved, lgtm

#14419 Add tests jobs to Thanos
  ci-operator/config/openshift/thanos/openshift-thanos-master.yaml
  ci-operator/jobs/openshift/thanos/openshift-thanos-master-presubmits.yaml
Labels: approved, lgtm

#14585 Adding ci for red-hat-data-services opendatahub-operator
  ci-operator/config/red-hat-data-services/opendatahub-operator/OWNERS
  ci-operator/config/red-hat-data-services/opendatahub-operator/red-hat-data-services-opendatahub-operator-master.yaml
  ci-operator/jobs/red-hat-data-services/opendatahub-operator/OWNERS
  ci-operator/jobs/red-hat-data-services/opendatahub-operator/red-hat-data-services-opendatahub-operator-master-periodics.yaml
  ci-operator/jobs/red-hat-data-services/opendatahub-operator/red-hat-data-services-opendatahub-operator-master-presubmits.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: approved, lgtm

#14606 OO proxy step - fix setting the node state result
  ci-operator/step-registry/optional-operators/configure-proxy-registry/optional-operators-configure-proxy-registry-commands.sh
Labels: approved, lgtm

#14671 Crier: Use apps auth for some more orgs
  clusters/app.ci/prow/03_deployment/crier.yaml
Labels: approved, lgtm

#14685 Remove obsolete config for openvswitch github org
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openvswitch/ovn-kubernetes/openvswitch-ovn-kubernetes-master-postsubmits.yaml
  ci-operator/jobs/openvswitch/ovn-kubernetes/openvswitch-ovn-kubernetes-master-presubmits.yaml
  core-services/prow/02_config/_plugins.yaml
  core-services/sanitize-prow-jobs/_config.yaml
  hack/missing-owners-whitelist
Labels: approved, lgtm

#14550 Kam secrets mount
  ci-operator/config/redhat-developer/kam/redhat-developer-kam-master__v4.6.yaml
Labels: approved, lgtm

#14663 doc update: slack notifications for a job
  clusters/app.ci/prow-monitoring/README.md
Labels: approved, lgtm

#14683 steps/openshift-e2e-test: Sequential test suites limit overlap
  ci-operator/step-registry/openshift/e2e/test/openshift-e2e-test-commands.sh
Labels: approved, lgtm

#14687 skipping fsGroup ppc64le test
  ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml
Labels: approved, lgtm

#14694 Secret generator: Disable dry-run
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm

#14697 Use app.ci's registry in mapping files for azure
  clusters/app.ci/registry-access/azure/admin_azure_list.yaml
  core-services/image-mirroring/openshift-azure/mapping_openshift_azure_v1_0_quay
Labels: approved, lgtm

#14698 Remove azure manifests from common_except_app.ci folder
  clusters/build-clusters/common_except_app.ci/azure-team_rbac.yaml
  clusters/build-clusters/common_except_app.ci/azure_groups.yaml
  clusters/build-clusters/common_except_app.ci/azure_namespaces.yaml
  clusters/build-clusters/common_except_app.ci/azure_rbac.yaml
Labels: approved, lgtm

#14700 Improve the chances of origin master's e2e disruptive jobs passing
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
Labels: approved, lgtm

#14703 Add new image for interceptor in ci
  ci-operator/config/openshift/tektoncd-triggers/openshift-tektoncd-triggers-release-next__4.6.yaml
  ci-operator/config/openshift/tektoncd-triggers/openshift-tektoncd-triggers-release-next__4.7.yaml
  core-services/image-mirroring/tekton/mapping_tekton_triggers_nightly_quay
Labels: approved, lgtm

#14701 turn off branch protection for service-binding-operator
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#14706 Update CI for oc k8s 1.20.1 branches
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-oc-4.7-kubernetes-1.20.1.yaml
  ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-oc-4.7-kubernetes-1.20.1-presubmits.yaml
Labels: approved, lgtm

#14638 Revert "Move folder services/squid-egress-proxy to app.ci"
  services/squid-egress-proxy/Dockerfile
  services/squid-egress-proxy/OWNERS
  services/squid-egress-proxy/README.md
  services/squid-egress-proxy/build.yaml
  services/squid-egress-proxy/entrypoint.sh
  services/squid-egress-proxy/squid.repo
Labels: approved, lgtm

#14632 core-services: Onboard WMCB community-4.6 branch
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#14642 Add secret for OCM AWS access for CRW-QE
  core-services/secret-mirroring/_mapping.yaml
Labels: approved, lgtm

#14664 request token for ocp-perfscale
  clusters/app.ci/registry-access/ocp-perfscale/OWNERS
  clusters/app.ci/registry-access/ocp-perfscale/README.md
  clusters/app.ci/registry-access/ocp-perfscale/admin_manifest.yaml
Labels: approved, lgtm

#14689 Update ibm-roks 4.6 base image
  ci-operator/config/openshift/ibm-roks-toolkit/openshift-ibm-roks-toolkit-release-4.6.yaml
Labels: approved, lgtm

#14714 periodics: Multi-Arch use images from registry.ci
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.6-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml
Labels: approved, lgtm

#14717 Tide: disable '--history-uri' which breaks tide start
  clusters/app.ci/prow/03_deployment/tide.yaml
Labels: approved, lgtm

#14719 request token for interop QE
  clusters/app.ci/registry-access/interop-qe/OWNERS
  clusters/app.ci/registry-access/interop-qe/README.md
  clusters/app.ci/registry-access/interop-qe/admin_manifest.yaml
Labels: approved, lgtm, tide/merge-method-squash

#14720 Pull secret generation: Cope with multiple secrets and use newest
  core-services/ci-secret-generator/_config.yaml
Labels: approved, lgtm

#14696 SDCICD-563: moa -> rosa project rename
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
  core-services/secret-mirroring/_mapping.yaml
Labels: approved, lgtm

#14723 Re-Enable tide history
  clusters/app.ci/prow/03_deployment/tide.yaml
  core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#14726 Use app.ci's registry in ci-operator folder
  ci-operator/infra/openshift/origin/standard-golang.yaml
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/open-cluster-management/multicloud-operators-foundation/open-cluster-management-multicloud-operators-foundation-release-2.1-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/multicloud-operators-foundation/open-cluster-management-multicloud-operators-foundation-release-2.2-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/observatorium-operator/open-cluster-management-observatorium-operator-release-2.1-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/observatorium-operator/open-cluster-management-observatorium-operator-release-2.2-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/registration-operator/open-cluster-management-registration-operator-release-2.0-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/registration-operator/open-cluster-management-registration-operator-release-2.1-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/registration-operator/open-cluster-management-registration-operator-release-2.2-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/registration/open-cluster-management-registration-release-2.0-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/registration/open-cluster-management-registration-release-2.1-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/registration/open-cluster-management-registration-release-2.2-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/submariner-addon/open-cluster-management-submariner-addon-release-2.2-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/work/open-cluster-management-work-release-2.0-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/work/open-cluster-management-work-release-2.1-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/work/open-cluster-management-work-release-2.2-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.6-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.8-periodics.yaml
  ci-operator/step-registry/ipi/conf/aws/proxy/ipi-conf-aws-proxy-commands.sh
  ci-operator/templates/openshift/installer/cluster-launch-installer-custom-test-image.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-metal-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-remote-libvirt-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
Labels: approved, lgtm

#14458 Adding the user to bastion for P/Z
  core-services/sshd-bastion/ppc64le-libvirt/OWNERS
  core-services/sshd-bastion/ppc64le-libvirt/admin_owners_rbac.yaml
  core-services/sshd-bastion/ppc64le/OWNERS
  core-services/sshd-bastion/z/OWNERS
  core-services/sshd-bastion/z/admin_owners_rbac.yaml
Labels: approved, lgtm

#13502 LOG-905: adding elasticsearch-operator upgrade test target
  ci-operator/config/openshift/elasticsearch-operator/openshift-elasticsearch-operator-master.yaml
  ci-operator/jobs/openshift/elasticsearch-operator/openshift-elasticsearch-operator-master-presubmits.yaml
Labels: approved, lgtm

#14735 Changes in ipi-conf-kubevirt-commands to work against an ocp over IBM
  ci-operator/step-registry/ipi/conf/kubevirt/ipi-conf-kubevirt-commands.sh
Labels: approved, lgtm

#14739 MGMT-3574 Add e2e-metal-assisted-single-node-periodic test to assisted-test-infra
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-periodics.yaml
  ci-operator/step-registry/baremetalds/assisted/setup/baremetalds-assisted-setup-commands.sh
Labels: approved, lgtm

#14740 Add reporter_config to ocp e2e-metal-assisted jobs on failures
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: approved, lgtm

#14253 Add test steps to assisted workflow
  ci-operator/step-registry/baremetalds/assisted/baremetalds-assisted-workflow.yaml
Labels: approved, lgtm

#14738 Adding e2e-kubevirt to cluster-api-provider-kubevirt repo
  ci-operator/config/openshift/cluster-api-provider-kubevirt/openshift-cluster-api-provider-kubevirt-master.yaml
  ci-operator/config/openshift/cluster-api-provider-kubevirt/openshift-cluster-api-provider-kubevirt-release-4.7.yaml
  ci-operator/config/openshift/cluster-api-provider-kubevirt/openshift-cluster-api-provider-kubevirt-release-4.8.yaml
  ci-operator/jobs/openshift/cluster-api-provider-kubevirt/openshift-cluster-api-provider-kubevirt-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-kubevirt/openshift-cluster-api-provider-kubevirt-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-kubevirt/openshift-cluster-api-provider-kubevirt-release-4.8-presubmits.yaml
Labels: approved, lgtm

#14736 Add ssp-operator release branch
  ci-operator/config/kubevirt/ssp-operator/kubevirt-ssp-operator-release-v0.1.0.yaml
  ci-operator/jobs/kubevirt/ssp-operator/kubevirt-ssp-operator-release-v0.1.0-presubmits.yaml
Labels: approved, lgtm

#14727 Use app.ci's registry almost everywhere
  cluster/ci/config/prow/openshift/ci-operator/stage.yaml
  clusters/JoinBuildFarm.md
  clusters/app.ci/assets/slack-bot-alpha.yaml
  clusters/app.ci/supplemental-ci-images/validation-images/dashboards/Dockerfile
  core-services/sshd-bastion/README.md
  core-services/sshd-bastion/ppc64le-libvirt/deployment.yaml
  core-services/sshd-bastion/ppc64le/deployment.yaml
  core-services/sshd-bastion/telco/deployment.yaml
  core-services/sshd-bastion/z/deployment.yaml
  hack/lib/dockerfiles.py
  hack/mirror-in
  hack/mirror-out
Labels: approved, lgtm

#14746 steps: allow skipping gather-loki step
  ci-operator/step-registry/gather/loki/gather-loki-ref.yaml
  ci-operator/step-registry/openshift/e2e/aws/loki/openshift-e2e-aws-loki-workflow.yaml
  ci-operator/step-registry/openshift/e2e/gcp/loki/openshift-e2e-gcp-loki-workflow.yaml
  ci-operator/step-registry/openshift/kubernetes/e2e/gcp/openshift-kubernetes-e2e-gcp-workflow.yaml
  ci-operator/step-registry/openshift/kubernetes/e2e/gcp/serial/openshift-kubernetes-e2e-gcp-serial-workflow.yaml
  ci-operator/step-registry/openshift/upgrade/aws/openshift-upgrade-aws-workflow.yaml
  ci-operator/step-registry/openshift/upgrade/azure/openshift-upgrade-azure-workflow.yaml
  ci-operator/step-registry/openshift/upgrade/gcp/openshift-upgrade-gcp-workflow.yaml
Labels: approved, lgtm

#14751 OO proxy step - handle node state errors
  ci-operator/step-registry/optional-operators/OWNERS
  ci-operator/step-registry/optional-operators/configure-proxy-registry/optional-operators-configure-proxy-registry-commands.sh
  ci-operator/step-registry/optional-operators/configure-proxy-registry/optional-operators-configure-proxy-registry-ref.metadata.json
  ci-operator/step-registry/optional-operators/subscribe/optional-operators-subscribe-ref.metadata.json
Labels: approved, lgtm

#14753 Reducing the retention of older releases to 3 days
  core-services/release-controller/_releases/priv/release-ocp-4.1.json
  core-services/release-controller/_releases/priv/release-ocp-4.2-ppc64le.json
  core-services/release-controller/_releases/priv/release-ocp-4.2-s390x.json
  core-services/release-controller/_releases/priv/release-ocp-4.2.json
  core-services/release-controller/_releases/priv/release-ocp-4.3-ppc64le.json
  core-services/release-controller/_releases/priv/release-ocp-4.3-s390x.json
  core-services/release-controller/_releases/priv/release-ocp-4.3.json
  core-services/release-controller/_releases/priv/release-ocp-4.4-ppc64le.json
  core-services/release-controller/_releases/priv/release-ocp-4.4-s390x.json
  core-services/release-controller/_releases/priv/release-ocp-4.4.json
  core-services/release-controller/_releases/priv/release-ocp-4.5-ppc64le.json
  core-services/release-controller/_releases/priv/release-ocp-4.5-s390x.json
  core-services/release-controller/_releases/priv/release-ocp-4.5.json
  core-services/release-controller/_releases/release-ocp-4.1.json
  core-services/release-controller/_releases/release-ocp-4.2-ppc64le.json
  core-services/release-controller/_releases/release-ocp-4.2-s390x.json
  core-services/release-controller/_releases/release-ocp-4.2.json
  core-services/release-controller/_releases/release-ocp-4.3-ppc64le.json
  core-services/release-controller/_releases/release-ocp-4.3-s390x.json
  core-services/release-controller/_releases/release-ocp-4.3.json
  core-services/release-controller/_releases/release-ocp-4.4-ppc64le.json
  core-services/release-controller/_releases/release-ocp-4.4-s390x.json
  core-services/release-controller/_releases/release-ocp-4.4.json
  core-services/release-controller/_releases/release-ocp-4.5-ppc64le.json
  core-services/release-controller/_releases/release-ocp-4.5-s390x.json
  core-services/release-controller/_releases/release-ocp-4.5.json
Labels: approved, lgtm

#14754 Updated release branch of ssp-operator
  ci-operator/config/kubevirt/ssp-operator/kubevirt-ssp-operator-release-v0.1.yaml
  ci-operator/jobs/kubevirt/ssp-operator/kubevirt-ssp-operator-release-v0.1-presubmits.yaml
Labels: approved, lgtm

#14748 [rhd-sbo] Add Quay.io token for acceptance testing with bundle
  core-services/secret-mirroring/_mapping.yaml
Labels: approved, lgtm

#14464 Adding logs for SSHD
  core-services/sshd-bastion/ppc64le-libvirt/sshd_config
  core-services/sshd-bastion/z/sshd_config
Labels: approved, lgtm

#14629 Add WMCB tests for 4.6 community branch
  ci-operator/config/openshift/windows-machine-config-bootstrapper/openshift-windows-machine-config-bootstrapper-community-4.6__okd.yaml
  ci-operator/jobs/openshift/windows-machine-config-bootstrapper/openshift-windows-machine-config-bootstrapper-community-4.6-postsubmits.yaml
  ci-operator/jobs/openshift/windows-machine-config-bootstrapper/openshift-windows-machine-config-bootstrapper-community-4.6-presubmits.yaml
Labels: approved, lgtm

#14737 Duplicate install and deprovision steps for e2e-kubevirt workflow
  ci-operator/step-registry/ipi/deprovision/deprovision/kubevirt/OWNERS
  ci-operator/step-registry/ipi/deprovision/deprovision/kubevirt/ipi-deprovision-deprovision-kubevirt-commands.sh
  ci-operator/step-registry/ipi/deprovision/deprovision/kubevirt/ipi-deprovision-deprovision-kubevirt-ref.metadata.json
  ci-operator/step-registry/ipi/deprovision/deprovision/kubevirt/ipi-deprovision-deprovision-kubevirt-ref.yaml
  ci-operator/step-registry/ipi/deprovision/kubevirt/OWNERS
  ci-operator/step-registry/ipi/deprovision/kubevirt/ipi-deprovision-kubevirt-chain.metadata.json
  ci-operator/step-registry/ipi/deprovision/kubevirt/ipi-deprovision-kubevirt-chain.yaml
  ci-operator/step-registry/ipi/install/kubevirt/OWNERS
  ci-operator/step-registry/ipi/install/kubevirt/install/OWNERS
  ci-operator/step-registry/ipi/install/kubevirt/install/ipi-install-kubevirt-install-commands.sh
  ci-operator/step-registry/ipi/install/kubevirt/install/ipi-install-kubevirt-install-ref.metadata.json
  ci-operator/step-registry/ipi/install/kubevirt/install/ipi-install-kubevirt-install-ref.yaml
  ci-operator/step-registry/ipi/install/kubevirt/ipi-install-kubevirt-chain.metadata.json
  ci-operator/step-registry/ipi/install/kubevirt/ipi-install-kubevirt-chain.yaml
  ci-operator/step-registry/ipi/kubevirt/post/ipi-kubevirt-post-chain.yaml
  ci-operator/step-registry/ipi/kubevirt/pre/ipi-kubevirt-pre-chain.yaml
Labels: approved, lgtm

#14752 Add image import pull secret to endurance maintenance job
  ci-operator/jobs/openshift/release/openshift-release-release-4.6-periodics.yaml
Labels: approved, lgtm

#14761 Update ibm-roks base image
  ci-operator/config/openshift/ibm-roks-toolkit/openshift-ibm-roks-toolkit-master.yaml
  ci-operator/config/openshift/ibm-roks-toolkit/openshift-ibm-roks-toolkit-release-4.3.yaml
  ci-operator/config/openshift/ibm-roks-toolkit/openshift-ibm-roks-toolkit-release-4.4.yaml
  ci-operator/config/openshift/ibm-roks-toolkit/openshift-ibm-roks-toolkit-release-4.5.yaml
Labels: approved, lgtm

#14435 step-registry: don't use `base` as image
  ci-operator/step-registry/ipi/conf/aws/blackholenetwork/ipi-conf-aws-blackholenetwork-ref.yaml
  ci-operator/step-registry/ipi/conf/aws/sharednetwork/ipi-conf-aws-sharednetwork-ref.yaml
  ci-operator/step-registry/ipi/conf/azure/ipi-conf-azure-ref.yaml
  ci-operator/step-registry/ipi/conf/azure/sharednetwork/ipi-conf-azure-sharednetwork-ref.yaml
  ci-operator/step-registry/ipi/conf/kubevirt/ipi-conf-kubevirt-ref.yaml
  ci-operator/step-registry/ovn/conf/hybrid-manifest-with-custom-vxlan-port/ovn-conf-hybrid-manifest-with-custom-vxlan-port-ref.yaml
  ci-operator/step-registry/ovn/conf/hybrid-manifest/ovn-conf-hybrid-manifest-ref.yaml
  ci-operator/step-registry/ovn/conf/ipsec-manifest/ovn-conf-ipsec-manifest-ref.yaml
  ci-operator/step-registry/ovn/conf/ovn-conf-ref.yaml
  ci-operator/step-registry/sdn/conf/multi-manifest/sdn-conf-multi-manifest-ref.yaml
  ci-operator/step-registry/sdn/conf/sdn-conf-ref.yaml
Labels: approved, lgtm

#14710 Bug 1909864: add missing /usr/local/e2e-aws mount
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
  core-services/template-deprecation/_allowlist.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#14767 Remove credsinit from tektoncd-pipeline
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-next__4.5.yaml
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-next__4.6.yaml
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-next__4.7.yaml
  core-services/image-mirroring/tekton/mapping_tekton_nightly_quay
Labels: approved, lgtm

#14763 [rhd-sbo] Shorten name of test credentials for acceptance tests
  core-services/secret-mirroring/_mapping.yaml
Labels: approved, lgtm

#14768 Secret{Generator,Bootstrapper} periodic: Fix job url
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm

#14762 Make manifests pass `--validate=true --dry-run=server`
  clusters/app.ci/prow/01_crd/admin_01_prowjob_crd.yaml
  clusters/app.ci/prow/01_crd/admin_03_boskos_crds.yaml
  clusters/app.ci/registry-access/open-cluster-management/admin_open-cluster-management.yaml
  clusters/app.ci/release-controller/admin_deploy-ocp-publish-art.yaml
  clusters/app.ci/release-controller/deploy-ocp-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-ppc64le-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-ppc64le-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-s390x-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-s390x-priv-controller.yaml
  clusters/app.ci/supplemental-ci-images/azure/base-images/ci-base.yaml
  clusters/app.ci/supplemental-ci-images/azure/base-images/test-base.yaml
  clusters/app.ci/supplemental-ci-images/cli-jq.yaml
  clusters/app.ci/supplemental-ci-images/coreos/admin_rbac.yaml
  clusters/app.ci/supplemental-ci-images/coreos/cosa-buildroot.yaml
  clusters/app.ci/supplemental-ci-images/coreos/cosa-exttests.yaml
  clusters/app.ci/supplemental-ci-images/coreos/cosa-upstream-is.yaml
  clusters/app.ci/supplemental-ci-images/validation-images/dashboards/dashboards-validation.yaml
  clusters/app.ci/supplemental-ci-images/validation-images/python/python-validation.yaml
  clusters/app.ci/supplemental-ci-images/validation-images/shellcheck/shellcheck.yaml
  clusters/build-clusters/01_cluster/openshift-image-registry/cluster_config.yaml
  clusters/build-clusters/01_cluster/openshift-machine-api/admin_build01-9hdwj-worker-us-east-1a-infra_machine_set.yaml
  clusters/build-clusters/01_cluster/openshift-machine-api/admin_build01-9hdwj-worker-us-east-1a-search_machine_set.yaml
  clusters/build-clusters/01_cluster/openshift-machine-api/admin_build01-9hdwj-worker-us-east-1a_machine_set.yaml
  clusters/build-clusters/01_cluster/openshift-machine-api/admin_build01-9hdwj-worker-us-east-1b_machine_set.yaml
  clusters/build-clusters/01_cluster/openshift-machine-api/admin_build01-9hdwj-worker-us-east-1c_machine_set.yaml
  clusters/build-clusters/02_cluster/openshift-image-registry/cluster_config.yaml
  clusters/build-clusters/common/ci-operator/admin_ci-operator_rbac.yaml
  core-services/release-controller/admin_deploy-ocp-controller.yaml
  core-services/release-controller/admin_deploy-ocp-ppc64le-controller.yaml
  core-services/release-controller/admin_deploy-ocp-ppc64le-priv-controller.yaml
  core-services/release-controller/admin_deploy-ocp-priv-controller.yaml
  core-services/release-controller/admin_deploy-ocp-publish-art.yaml
  core-services/release-controller/admin_deploy-ocp-s390x-controller.yaml
  core-services/release-controller/admin_deploy-ocp-s390x-priv-controller.yaml
  hack/generators/release-controllers/content/art_namespaces_rbac.py
  hack/generators/release-controllers/content/art_publish_permissions.py
  hack/generators/release-controllers/content/osd_files_cache_rbac.py
Labels: approved, lgtm

#14769 Calling the release-controller with the --release-architecture flag specified
  clusters/app.ci/release-controller/deploy-ocp-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-ppc64le-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-ppc64le-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-s390x-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-s390x-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-origin-controller.yaml
  hack/generators/release-controllers/content/osd_rc_deployments.py
  hack/generators/release-controllers/generate-release-controllers.py
Labels: approved, lgtm

#14772 Set nss wrapper for assisted-setup and assisted-gather
  ci-operator/step-registry/baremetalds/assisted/gather/baremetalds-assisted-gather-commands.sh
  ci-operator/step-registry/baremetalds/assisted/setup/baremetalds-assisted-setup-commands.sh
Labels: approved, lgtm

#14742 Remove openshift/assisted-test-infra required Jenkins status check
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#14704 Add job to test KubeVirt 0.36 vs. OCP 4.7
  ci-operator/config/kubevirt/kubevirt/kubevirt-kubevirt-master__0.36_4.7.yaml
  ci-operator/jobs/kubevirt/kubevirt/kubevirt-kubevirt-master-periodics.yaml
Labels: approved, lgtm

#14750 cnv: ssp: Update Go version in test image
  ci-operator/config/kubevirt/ssp-operator/kubevirt-ssp-operator-master.yaml
Labels: approved, lgtm

#14776 update the allowlist in ci-secret-bootstraper job
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm

#14783 Build images for Kourier's 0.20 release
  ci-operator/config/openshift-knative/net-kourier/openshift-knative-net-kourier-release-0.20.yaml
  ci-operator/jobs/openshift-knative/net-kourier/openshift-knative-net-kourier-release-0.20-postsubmits.yaml
  ci-operator/jobs/openshift-knative/net-kourier/openshift-knative-net-kourier-release-0.20-presubmits.yaml
Labels: approved, lgtm

#14771 Parameterize ipi-azure compute node type
  ci-operator/step-registry/ipi/conf/azure/ipi-conf-azure-commands.sh
  ci-operator/step-registry/ipi/conf/azure/ipi-conf-azure-ref.yaml
Labels: approved, lgtm, ok-to-test

#14784 Enable secrets for cluster-bot OSD integration
  core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#14790 Remove config for redhat-integration
  ci-operator/config/redhat-integration/rhi-operator/OWNERS
  ci-operator/config/redhat-integration/rhi-operator/redhat-integration-rhi-operator-master.yaml
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/redhat-integration/rhi-operator/OWNERS
  ci-operator/jobs/redhat-integration/rhi-operator/redhat-integration-rhi-operator-master-postsubmits.yaml
  ci-operator/jobs/redhat-integration/rhi-operator/redhat-integration-rhi-operator-master-presubmits.yaml
  core-services/prow/02_config/_plugins.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: approved

#14789 [wmcb/wmco] Remove requirement of bugzilla labels for community branches
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm
