Repository openshift/release, pull requests merged in 2021-12, with the labels that each got.

#24123 Move postgres image to edge-infrastructure namespace
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_edge_infrastructure
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_ocp_kni
Labels: lgtm, approved

#24126 ci-operator/config/openshift/release: Add an oldest-supported-credential-request job
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.9.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  ci-operator/step-registry/openshift/credentials-request-freeze/OWNERS
  ci-operator/step-registry/openshift/credentials-request-freeze/openshift-credentials-request-freeze-commands.sh
  ci-operator/step-registry/openshift/credentials-request-freeze/openshift-credentials-request-freeze-ref.metadata.json
  ci-operator/step-registry/openshift/credentials-request-freeze/openshift-credentials-request-freeze-ref.yaml
  ci-operator/step-registry/openshift/credentials-request-freeze/openshift-credentials-request-freeze-workflow.metadata.json
  ci-operator/step-registry/openshift/credentials-request-freeze/openshift-credentials-request-freeze-workflow.yaml
Labels: lgtm, approved

#24053 Re-enable QE Test Jobs
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__ocp-4.10.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
  ci-operator/step-registry/cucushift/e2e/cucushift-e2e-commands.sh
  ci-operator/step-registry/cucushift/pre/cucushift-pre-commands.sh
Labels: lgtm, approved

#24059 OpenStack: save redacted install-config for debugging
  ci-operator/step-registry/openstack/conf/generateconfig/openstack-conf-generateconfig-commands.sh
Labels: lgtm, approved

#24141 Bump cluster-api-actuator-pkg to Go 1.17
  ci-operator/config/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-master.yaml
  ci-operator/config/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-release-4.10.yaml
  ci-operator/config/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-release-4.11.yaml
Labels: lgtm, approved

#24078 b04: take some load of KVM jobs
  ci-operator/jobs/coreos/rpm-ostree/coreos-rpm-ostree-main-presubmits.yaml
  ci-operator/jobs/openshift-priv/os/openshift-priv-os-c9s-presubmits.yaml
  ci-operator/jobs/openshift-priv/os/openshift-priv-os-release-4.9-presubmits.yaml
  ci-operator/jobs/openshift/os/openshift-os-master-presubmits.yaml
  ci-operator/jobs/openshift/os/openshift-os-release-4.10-presubmits.yaml
  ci-operator/jobs/openshift/os/openshift-os-release-4.11-presubmits.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: lgtm, approved

#24099 Add verify and unit tests to SRO upstream prow
  ci-operator/config/openshift-psap/special-resource-operator/openshift-psap-special-resource-operator-master.yaml
  ci-operator/jobs/openshift-psap/special-resource-operator/openshift-psap-special-resource-operator-master-presubmits.yaml
Labels: lgtm, approved

#24145 ci-tools: build job-run-aggregator
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
Labels: lgtm, approved, tide/merge-method-squash

#23832 move odo-init-image to redhat-developer org
  core-services/prow/02_config/redhat-developer/odo-init-image/OWNERS
  core-services/prow/02_config/redhat-developer/odo-init-image/_pluginconfig.yaml
  core-services/prow/02_config/redhat-developer/odo-init-image/_prowconfig.yaml
Labels: lgtm, approved

#24131 ci-operator/step-registry/gather: cluster:version:updates:seconds for Prom outages
  ci-operator/step-registry/gather/extra/gather-extra-commands.sh
  ci-operator/step-registry/gather/libvirt/gather-libvirt-commands.sh
Labels: lgtm, approved

#24149 k8s fork: use build_root from -ci-operator.yaml
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-master.yaml
  ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-master-periodics.yaml
  ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-master-postsubmits.yaml
  ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-master-presubmits.yaml
Labels: lgtm, approved

#24094 Add metadata-webhook image
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main__4.6.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main__4.7.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main__4.8.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main__4.9-aws-ovn.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main__4.9-azure.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main__4.9-gcp.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main__4.9-osd.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main__4.9-vsphere.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main__4.9.yaml
  core-services/image-mirroring/knative/mapping_knative_nightly_quay
Labels: lgtm, approved

#24152 Update unit-test as part of dependancy update
  ci-operator/config/open-cluster-management/multiclusterhub-operator/open-cluster-management-multiclusterhub-operator-main.yaml
  ci-operator/config/open-cluster-management/multiclusterhub-operator/open-cluster-management-multiclusterhub-operator-release-2.5.yaml
  ci-operator/config/open-cluster-management/multiclusterhub-operator/open-cluster-management-multiclusterhub-operator-release-9.9.yaml
Labels: lgtm, approved

#24154 disable branch protection on smg247/ci-docs
  core-services/prow/02_config/smg247/ci-docs/_prowconfig.yaml
Labels: lgtm, approved, tide/merge-method-squash

#24157 Updating cron for compact jobs based on requirements
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.10.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.8.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.9.yaml
  ci-operator/jobs/openshift/multiarch/openshift-multiarch-master-periodics.yaml
Labels: lgtm, approved

#24160 Popolate secret/app.ci-secret in ns/dex
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved

#24114 Update delorean config to build from Dockerfile.tools
  ci-operator/config/integr8ly/delorean/integr8ly-delorean-master.yaml
Labels: lgtm, approved, ok-to-test

#24144 add jobs for assisted-test-infra v1 branch
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-v1.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-v1-presubmits.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: lgtm, approved

#24162 dex: proxy app.ci
  clusters/app.ci/dex/manifests.yaml
Labels: lgtm, approved

#24165 postsubmit job and promotion for gpu-add init container
  ci-operator/config/rh-ecosystem-edge/NVIDIA-gpu-add-on-init-container/rh-ecosystem-edge-NVIDIA-gpu-add-on-init-container-main.yaml
  ci-operator/jobs/rh-ecosystem-edge/NVIDIA-gpu-add-on-init-container/rh-ecosystem-edge-NVIDIA-gpu-add-on-init-container-main-postsubmits.yaml
Labels: lgtm, approved

#24172 IDP disable promotion to stable
  ci-operator/config/identitatem/dex-operator/identitatem-dex-operator-main.yaml
  ci-operator/config/identitatem/idp-client-api/identitatem-idp-client-api-main.yaml
  ci-operator/config/identitatem/idp-mgmt-operator/identitatem-idp-mgmt-operator-main.yaml
Labels: lgtm, approved

#24173 Hypershift conformance tests: Add management cluster creds
  ci-operator/config/openshift/hypershift/openshift-hypershift-main.yaml
Labels: lgtm, approved

#24179 Remove publish stanza for multi nightlies
  core-services/release-controller/_releases/release-ocp-4.10-multi.json
  core-services/release-controller/_releases/release-ocp-4.2-multi.json
  core-services/release-controller/_releases/release-ocp-4.3-multi.json
  core-services/release-controller/_releases/release-ocp-4.4-multi.json
  core-services/release-controller/_releases/release-ocp-4.5-multi.json
  core-services/release-controller/_releases/release-ocp-4.6-multi.json
  core-services/release-controller/_releases/release-ocp-4.7-multi.json
  core-services/release-controller/_releases/release-ocp-4.8-multi.json
  core-services/release-controller/_releases/release-ocp-4.9-multi.json
Labels: lgtm, approved

#24184 Add back cucushift tests
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__ocp-4.10-upgrade-from-eus-4.8.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__ocp-4.10-upgrade-from-stable-4.9.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__ocp-4.10.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
Labels: lgtm, approved

#24186 Enable BP on upstream SRO
  core-services/prow/02_config/openshift-psap/special-resource-operator/_prowconfig.yaml
Labels: lgtm, approved

#23840 move odo to redhat-developer org
  ci-operator/config/redhat-developer/odo/OWNERS
  ci-operator/config/redhat-developer/odo/redhat-developer-odo-main.yaml
  ci-operator/config/redhat-developer/odo/redhat-developer-odo-main__psi.yaml
  ci-operator/config/redhat-developer/odo/redhat-developer-odo-main__v4.7.yaml
  ci-operator/config/redhat-developer/odo/redhat-developer-odo-main__v4.8.yaml
  ci-operator/config/redhat-developer/odo/redhat-developer-odo-main__v4.9.yaml
  ci-operator/jobs/redhat-developer/odo/OWNERS
  ci-operator/jobs/redhat-developer/odo/redhat-developer-odo-main-periodics.yaml
  ci-operator/jobs/redhat-developer/odo/redhat-developer-odo-main-presubmits.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
  core-services/prow/02_config/redhat-developer/odo/OWNERS
  core-services/prow/02_config/redhat-developer/odo/_pluginconfig.yaml
  core-services/prow/02_config/redhat-developer/odo/_prowconfig.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: lgtm, approved

#23838 openstack-tests: Add an e2e presubmit to master
  ci-operator/config/openshift/openstack-test/openshift-openstack-test-main.yaml
  ci-operator/jobs/openshift/openstack-test/openshift-openstack-test-main-presubmits.yaml
  ci-operator/step-registry/openstack/test/openstack/OWNERS
  ci-operator/step-registry/openstack/test/openstack/openstack-test-openstack-commands.sh
  ci-operator/step-registry/openstack/test/openstack/openstack-test-openstack-ref.metadata.json
  ci-operator/step-registry/openstack/test/openstack/openstack-test-openstack-ref.yaml
Labels: lgtm, approved

#24138 scheduler-plugins: enable quay.io mirroring
  core-services/image-mirroring/openshift-kni/mapping_openshift-kni_quay
Labels: lgtm, approved

#24197 OCP CI pools: optimize sizes and cap install attempts"
  clusters/hive/pools/openshift-ci/ci-ocp-4-6-0-amd64-aws-us-east-1_clusterpool.yaml
  clusters/hive/pools/openshift-ci/ci-ocp-4-7-0-amd64-aws-us-east-1_clusterpool.yaml
  clusters/hive/pools/openshift-ci/ci-ocp-4-8-0-amd64-aws-us-east-1_clusterpool.yaml
  clusters/hive/pools/openshift-ci/ci-ocp-4-8-0-amd64-aws-us-west-1_clusterpool.yaml
  clusters/hive/pools/openshift-ci/ci-ocp-4-9-0-amd64-aws-us-west-1_clusterpool.yaml
Labels: lgtm, approved

#24166 ci-operator/config/openshift/release: Add credentials-request-freeze for 4.7 and 4.8
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.7.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.8.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  ci-operator/step-registry/openshift/credentials-request-freeze/openshift-credentials-request-freeze-commands.sh
Labels: lgtm, approved

#24192 openstack-tests: Add the base images to Release
  ci-operator/config/openshift/release/openshift-release-master__ci-4.10-upgrade-from-stable-4.9.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.10.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.6.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.7-upgrade-from-stable-4.6.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.7.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.8-upgrade-from-stable-4.7.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.8.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.9-upgrade-from-stable-4.8.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.9.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.10.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.9.yaml
Labels: lgtm, approved

#24132 Add z stream approvers for baremetal-runtimecfg
  core-services/prow/02_config/openshift/baremetal-runtimecfg/_pluginconfig.yaml
Labels: lgtm, approved

#24151 Adding ci to osd-network-verifier
  ci-operator/config/openshift/osd-network-verifier/OWNERS
  ci-operator/config/openshift/osd-network-verifier/openshift-osd-network-verifier-main.yaml
  ci-operator/jobs/openshift/osd-network-verifier/OWNERS
  ci-operator/jobs/openshift/osd-network-verifier/openshift-osd-network-verifier-main-presubmits.yaml
  core-services/prow/02_config/openshift/osd-network-verifier/_pluginconfig.yaml
Labels: lgtm, approved

#24195 Make 4.8 and 4.9 jobs required
  ci-operator/config/openshift/kuryr-kubernetes/openshift-kuryr-kubernetes-release-4.8.yaml
  ci-operator/config/openshift/kuryr-kubernetes/openshift-kuryr-kubernetes-release-4.9.yaml
  ci-operator/jobs/openshift/kuryr-kubernetes/openshift-kuryr-kubernetes-release-4.8-presubmits.yaml
  ci-operator/jobs/openshift/kuryr-kubernetes/openshift-kuryr-kubernetes-release-4.9-presubmits.yaml
Labels: lgtm, approved

#24206 Updating the Imagestream apiVersion to `image.openshift.io/v1`
  clusters/app.ci/release-controller/admin_deploy-ocp-publish-art.yaml
  hack/generators/release-controllers/content/art_publish_permissions.py
Labels: lgtm, approved

#24209 release: Add OpenStack approver
  ci-operator/config/openshift/release/OWNERS
Labels: lgtm, approved

#23978 Gather audit logs in gather-extra CI step
  ci-operator/step-registry/gather/extra/gather-extra-commands.sh
Labels: lgtm, approved

#24204 Revert rename periodic-ci-openshift-hypershift-main-e2e-aws-pooled-periodic-conformance to fix testgrid
  ci-operator/config/openshift/hypershift/openshift-hypershift-main.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-main-periodics.yaml
Labels: lgtm, approved

#24201 library-go: use build_root from -ci-operator.yaml
  ci-operator/config/openshift/library-go/openshift-library-go-master.yaml
  ci-operator/jobs/openshift/library-go/openshift-library-go-master-presubmits.yaml
Labels: lgtm, approved

#23899 wmco/wmcb: Add CI jobs for community-4.9
  ci-operator/config/openshift/windows-machine-config-bootstrapper/openshift-windows-machine-config-bootstrapper-community-4.9__okd.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-community-4.9__okd.yaml
  ci-operator/jobs/openshift/windows-machine-config-bootstrapper/openshift-windows-machine-config-bootstrapper-community-4.9-postsubmits.yaml
  ci-operator/jobs/openshift/windows-machine-config-bootstrapper/openshift-windows-machine-config-bootstrapper-community-4.9-presubmits.yaml
  ci-operator/jobs/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-community-4.9-presubmits.yaml
  core-services/prow/02_config/openshift/windows-machine-config-bootstrapper/_pluginconfig.yaml
  core-services/prow/02_config/openshift/windows-machine-config-operator/_pluginconfig.yaml
Labels: lgtm, approved

#24169 Add a ContainerRuntimeConfig to enable debug logging.
  ci-operator/config/openshift/release/openshift-release-master__ci-4.10-upgrade-from-stable-4.9.yaml
Labels: lgtm, approved

#24205 ocm - Enable Bluderbuss for GRC repos
  core-services/prow/02_config/open-cluster-management/cert-policy-controller/_pluginconfig.yaml
  core-services/prow/02_config/open-cluster-management/config-policy-controller/_pluginconfig.yaml
  core-services/prow/02_config/open-cluster-management/go-template-utils/_pluginconfig.yaml
  core-services/prow/02_config/open-cluster-management/governance-policy-framework/_pluginconfig.yaml
  core-services/prow/02_config/open-cluster-management/governance-policy-propagator/_pluginconfig.yaml
  core-services/prow/02_config/open-cluster-management/governance-policy-spec-sync/_pluginconfig.yaml
  core-services/prow/02_config/open-cluster-management/governance-policy-status-sync/_pluginconfig.yaml
  core-services/prow/02_config/open-cluster-management/governance-policy-template-sync/_pluginconfig.yaml
  core-services/prow/02_config/open-cluster-management/grc-chart/_pluginconfig.yaml
  core-services/prow/02_config/open-cluster-management/iam-policy-controller/_pluginconfig.yaml
  core-services/prow/02_config/open-cluster-management/policy-collection/_pluginconfig.yaml
  core-services/prow/02_config/open-cluster-management/policy-generator-plugin/_pluginconfig.yaml
  core-services/prow/02_config/open-cluster-management/security-middleware/_pluginconfig.yaml
Labels: lgtm, approved

#24218 Add prow label config for osd-network-verifier
  core-services/prow/02_config/openshift/osd-network-verifier/_prowconfig.yaml
Labels: lgtm, approved

#24142 disaster recovery first test2
  ci-operator/config/openshift-qe/ocp-dr-testing/OWNERS
  ci-operator/config/openshift-qe/ocp-dr-testing/openshift-qe-ocp-dr-testing-master.yaml
  ci-operator/jobs/openshift-qe/ocp-dr-testing/OWNERS
  ci-operator/jobs/openshift-qe/ocp-dr-testing/openshift-qe-ocp-dr-testing-master-periodics.yaml
  ci-operator/step-registry/dr/OWNERS
  ci-operator/step-registry/dr/backup-check/OWNERS
  ci-operator/step-registry/dr/backup-check/dr-backup-check-commands.sh
  ci-operator/step-registry/dr/backup-check/dr-backup-check-ref.metadata.json
  ci-operator/step-registry/dr/backup-check/dr-backup-check-ref.yaml
  ci-operator/step-registry/dr/backup/OWNERS
  ci-operator/step-registry/dr/backup/dr-backup-commands.sh
  ci-operator/step-registry/dr/backup/dr-backup-ref.metadata.json
  ci-operator/step-registry/dr/backup/dr-backup-ref.yaml
  ci-operator/step-registry/dr/ocp42183/OWNERS
  ci-operator/step-registry/dr/ocp42183/dr-ocp42183-workflow.metadata.json
  ci-operator/step-registry/dr/ocp42183/dr-ocp42183-workflow.yaml
Labels: lgtm, approved

#21548 Use first eight cores on a single node for workload partitioning
  ci-operator/step-registry/single-node/conf/e2e/single-node-conf-e2e-commands.sh
Labels: lgtm, approved

#24159 Don't install addon-operator as part of e2e tests for reference-addon
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: lgtm, approved

#24225 Test custom machine-os-content image in machine-config-operator@mcbs
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-mcbs.yaml
Labels: lgtm, approved

#24228 ci-chat-bot: add workflow-configs.yaml configmap
  clusters/app.ci/ci-chat-bot/ci-chat-bot.yaml
Labels: lgtm, approved

#24233 Avoid using a same test user account for E2E and upgrade at the same time
  ci-operator/step-registry/cucushift/upgrade/check/cucushift-upgrade-check-commands.sh
  ci-operator/step-registry/cucushift/upgrade/pre/cucushift-upgrade-pre-commands.sh
Labels: lgtm, approved

#24219 etcd-on-ramfs: add openstack reviewers
  ci-operator/step-registry/ipi/conf/etcd/on-ramfs/OWNERS
  ci-operator/step-registry/ipi/conf/etcd/on-ramfs/ipi-conf-etcd-on-ramfs-ref.metadata.json
Labels: lgtm, approved

#24210 Bug 1998035: Fix race mounting etcd on ramfs
  ci-operator/step-registry/ipi/conf/etcd/on-ramfs/ipi-conf-etcd-on-ramfs-commands.sh
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#24232 Correcting the mount point for workflow configs
  clusters/app.ci/ci-chat-bot/ci-chat-bot.yaml
Labels: lgtm, approved

#24220 Update api, client-go, apiserver-library-go to use CI config from repo
  ci-operator/config/openshift/api/openshift-api-master.yaml
  ci-operator/config/openshift/apiserver-library-go/openshift-apiserver-library-go-master.yaml
  ci-operator/config/openshift/client-go/openshift-client-go-master.yaml
  ci-operator/jobs/openshift/api/openshift-api-master-presubmits.yaml
  ci-operator/jobs/openshift/apiserver-library-go/openshift-apiserver-library-go-master-presubmits.yaml
  ci-operator/jobs/openshift/client-go/openshift-client-go-master-presubmits.yaml
Labels: lgtm, approved

#24199 Move Eclipse Che Operator tests for main branch from v7 to v9
  ci-operator/config/eclipse-che/che-operator/eclipse-che-che-operator-main__v9.yaml
  ci-operator/jobs/eclipse-che/che-operator/eclipse-che-che-operator-main-periodics.yaml
  ci-operator/jobs/eclipse-che/che-operator/eclipse-che-che-operator-main-presubmits.yaml
Labels: lgtm, approved, ok-to-test

#24239 GPU Operator: include v1.9 nightly testing and a bit of cleanup
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-master.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-master__4.7.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-release-4.7.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-release-4.8.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-release-4.9.yaml
  ci-operator/jobs/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-release-4.7-periodics.yaml
  ci-operator/jobs/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-release-4.8-periodics.yaml
  ci-operator/jobs/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-release-4.9-periodics.yaml
Labels: lgtm, approved

#24237 Netobserv: update console plugin CI script
  ci-operator/config/netobserv/network-observability-console-plugin/netobserv-network-observability-console-plugin-main.yaml
Labels: lgtm, approved

#24155 Restructuring skip lists for unsupported tests
  ci-operator/step-registry/openshift/e2e/libvirt/conf/openshift-e2e-libvirt-conf-commands.sh
Labels: lgtm, approved

#24245 bring aws-pod-identity-webhook config in line with CCO
  core-services/prow/02_config/openshift/aws-pod-identity-webhook/_pluginconfig.yaml
Labels: lgtm, approved

#24243 Revert "Add a ContainerRuntimeConfig to enable debug logging."
  ci-operator/config/openshift/release/openshift-release-master__ci-4.10-upgrade-from-stable-4.9.yaml
Labels: lgtm, approved

#24247 Bump volume size for openshift/kubernetes unit tests
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-master.yaml
Labels: lgtm, approved

#24198 Adding myself as an approver to support cluster-bot's templates
  ci-operator/templates/openshift/installer/OWNERS
Labels: lgtm, approved

#24249 Add nvidia gpu init addon container to hourly image mirroring
  core-services/image-mirroring/edge-infrastructure/mapping_edge_infrastructure_latest
Labels: lgtm, approved

#23610 Add crun variant to e2e installer
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
Labels: lgtm, approved

#24251 Fix an odd char in filename
  core-services/prow/02_config/openshift/machine-api-provider-gcp/_prowconfig.yaml
Labels: lgtm, approved

#24253 Update OADP operator channels to stable
  ci-operator/config/openshift/oadp-operator/openshift-oadp-operator-master.yaml
Labels: lgtm, approved

#24252 ci-operator: Fix permission denied error when running unit tests
  ci-operator/config/openshift/operator-framework-olm/openshift-operator-framework-olm-release-4.8.yaml
Labels: lgtm, approved

#23980 coreos/coreos-assembler: run RHCOS tests on rhcos-4.9 and rhcos-4.8
  ci-operator/config/coreos/coreos-assembler/coreos-coreos-assembler-main.yaml
  ci-operator/config/coreos/coreos-assembler/coreos-coreos-assembler-rhcos-4.8.yaml
  ci-operator/config/coreos/coreos-assembler/coreos-coreos-assembler-rhcos-4.9.yaml
  ci-operator/jobs/coreos/coreos-assembler/coreos-coreos-assembler-main-presubmits.yaml
  ci-operator/jobs/coreos/coreos-assembler/coreos-coreos-assembler-rhcos-4.8-presubmits.yaml
  ci-operator/jobs/coreos/coreos-assembler/coreos-coreos-assembler-rhcos-4.9-presubmits.yaml
Labels: lgtm, approved

#24191 openstack-tests: Add the base images to Installer
  ci-operator/config/openshift/installer/openshift-installer-fcos.yaml
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
  ci-operator/config/openshift/installer/openshift-installer-master__okd.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.1.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.10.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.10__okd.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.2.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.3.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.4.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.5.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.6.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.7.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.8.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.9.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.9__okd.yaml
Labels: lgtm, approved

#24217 Microshift: wait for infra pods to start
  ci-operator/config/redhat-et/microshift/redhat-et-microshift-main.yaml
  ci-operator/jobs/redhat-et/microshift/redhat-et-microshift-main-presubmits.yaml
  ci-operator/step-registry/redhat-et/microshift/e2e/wait-for-cluster-up/redhat-et-microshift-e2e-wait-for-cluster-up-commands.sh
Labels: lgtm, approved

#24259 enable branch promotion for placement repo
  ci-operator/config/open-cluster-management/placement/open-cluster-management-placement-backplane-1.0.yaml
  ci-operator/config/open-cluster-management/placement/open-cluster-management-placement-release-2.4.yaml
Labels: lgtm, approved

#24260 enable branch promotion for provider-credential repo
  ci-operator/config/open-cluster-management/provider-credential-controller/open-cluster-management-provider-credential-controller-release-2.4.yaml
Labels: lgtm, approved

#24263 Add the secret for the dptp jira access token
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved

#24230 upgrade to go1.17
  ci-operator/config/open-cluster-management/clusterlifecycle-state-metrics/open-cluster-management-clusterlifecycle-state-metrics-main.yaml
  ci-operator/config/open-cluster-management/clusterlifecycle-state-metrics/open-cluster-management-clusterlifecycle-state-metrics-release-2.3.yaml
  ci-operator/config/open-cluster-management/clusterlifecycle-state-metrics/open-cluster-management-clusterlifecycle-state-metrics-release-2.4.yaml
  ci-operator/config/open-cluster-management/clusterlifecycle-state-metrics/open-cluster-management-clusterlifecycle-state-metrics-release-2.5.yaml
  ci-operator/jobs/open-cluster-management/clusterlifecycle-state-metrics/open-cluster-management-clusterlifecycle-state-metrics-release-2.3-postsubmits.yaml
Labels: lgtm, approved

#24264 change jira arguments to use a bearer token instead
  clusters/app.ci/assets/slack-bot.yaml
  clusters/app.ci/prow/03_deployment/hook.yaml
Labels: lgtm, approved

#24265 disable bastion periodic
  ci-operator/config/openshift-kni/cnf-features-deploy/OWNERS
  ci-operator/config/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-master.yaml
  ci-operator/jobs/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-master-periodics.yaml
Labels: lgtm, approved

#22589 openstack-test step
  ci-operator/step-registry/openshift/e2e/openstack/byon/openshift-e2e-openstack-byon-workflow.yaml
  ci-operator/step-registry/openshift/e2e/openstack/ccm/install/openshift-e2e-openstack-ccm-install-workflow.yaml
  ci-operator/step-registry/openshift/e2e/openstack/ccm/openshift-e2e-openstack-ccm-workflow.yaml
  ci-operator/step-registry/openshift/e2e/openstack/csi/cinder/openshift-e2e-openstack-csi-cinder-workflow.yaml
  ci-operator/step-registry/openshift/e2e/openstack/csi/manila/openshift-e2e-openstack-csi-manila-workflow.yaml
  ci-operator/step-registry/openshift/e2e/openstack/ipi/openshift-e2e-openstack-ipi-workflow.yaml
  ci-operator/step-registry/openshift/e2e/openstack/ovn/openshift-e2e-openstack-ovn-workflow.yaml
  ci-operator/step-registry/openshift/e2e/openstack/proxy/openshift-e2e-openstack-proxy-workflow.yaml
  ci-operator/step-registry/openshift/e2e/openstack/techpreview/openshift-e2e-openstack-techpreview-workflow.yaml
  ci-operator/step-registry/openshift/upgrade/openstack/loki/openshift-upgrade-openstack-loki-workflow.yaml
  ci-operator/step-registry/openstack/test/e2e/OWNERS
  ci-operator/step-registry/openstack/test/e2e/openstack-test-e2e-chain.metadata.json
  ci-operator/step-registry/openstack/test/e2e/openstack-test-e2e-chain.yaml
Labels: lgtm, approved

#24058 chore(rmo): use pooling
  ci-operator/config/openshift/route-monitor-operator/openshift-route-monitor-operator-master.yaml
  ci-operator/jobs/openshift/route-monitor-operator/openshift-route-monitor-operator-master-presubmits.yaml
Labels: lgtm, approved

#23762 Lower frequency of CSI driver tests
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.10.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.8.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.9.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: lgtm, approved

#24276 Test Serverless UI only on latest OCP
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main__4.6.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main__4.7.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main__4.8.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main-periodics.yaml
Labels: lgtm, approved

#24268 Update golang to 1.17.4
  clusters/build-clusters/01_cluster/ci/_origin-release-build/golang-1.17/Dockerfile
  clusters/build-clusters/01_cluster/ci/_origin-release-build/golang-1.17/golang.spec
Labels: lgtm, approved

#24273 authenticate with jira via personal access token
  ci-operator/step-registry/baremetalds/assisted/tools/report/baremetalds-assisted-tools-report-commands.sh
Labels: lgtm, approved

#24278 assisted-day2: added presubmit test to agent
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master-presubmits.yaml
Labels: lgtm, approved

#24275 ipi-install-hosted-loki: bump promtail to 2.4.1
  ci-operator/step-registry/ipi/install/hosted-loki/ipi-install-hosted-loki-commands.sh
Labels: lgtm, approved

#24274 openstack-tests: Add presubmits for 4.6+ branches
  ci-operator/config/openshift/openstack-test/openshift-openstack-test-release-4.6.yaml
  ci-operator/config/openshift/openstack-test/openshift-openstack-test-release-4.7.yaml
  ci-operator/config/openshift/openstack-test/openshift-openstack-test-release-4.8.yaml
  ci-operator/config/openshift/openstack-test/openshift-openstack-test-release-4.9.yaml
  ci-operator/jobs/openshift/openstack-test/openshift-openstack-test-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/openstack-test/openshift-openstack-test-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/openstack-test/openshift-openstack-test-release-4.8-presubmits.yaml
  ci-operator/jobs/openshift/openstack-test/openshift-openstack-test-release-4.9-presubmits.yaml
Labels: lgtm, approved

#24283 [vsphere] shift 6 leases to IBM Cloud vCenter
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: lgtm, approved

#24284 periodic-sprint-automation: use jira token
  ci-operator/jobs/infra-periodics.yaml
Labels: lgtm, approved

#24168 Adds multus-networkpolicy to the config for the merge robot and adds …
  core-services/prow/02_config/openshift/multus-networkpolicy/_pluginconfig.yaml
  core-services/prow/02_config/openshift/multus-networkpolicy/_prowconfig.yaml
Labels: lgtm, approved

#24288 filter pods
  ci-operator/step-registry/redhat-et/microshift/e2e/wait-for-cluster-up/redhat-et-microshift-e2e-wait-for-cluster-up-commands.sh
Labels: lgtm, approved

#24028 Add CAPI e2e aws
  ci-operator/config/openshift/cluster-capi-operator/openshift-cluster-capi-operator-main.yaml
  ci-operator/jobs/openshift/cluster-capi-operator/openshift-cluster-capi-operator-main-presubmits.yaml
  ci-operator/step-registry/capi/OWNERS
  ci-operator/step-registry/capi/conf/OWNERS
  ci-operator/step-registry/capi/conf/apply-feature-gate/OWNERS
  ci-operator/step-registry/capi/conf/apply-feature-gate/capi-conf-apply-feature-gate-commands.sh
  ci-operator/step-registry/capi/conf/apply-feature-gate/capi-conf-apply-feature-gate-ref.metadata.json
  ci-operator/step-registry/capi/conf/apply-feature-gate/capi-conf-apply-feature-gate-ref.yaml
  ci-operator/step-registry/openshift/e2e/aws/capi/OWNERS
  ci-operator/step-registry/openshift/e2e/aws/capi/openshift-e2e-aws-capi-workflow.metadata.json
  ci-operator/step-registry/openshift/e2e/aws/capi/openshift-e2e-aws-capi-workflow.yaml
Labels: lgtm, approved

#24290 gather-extra: update query for cluster:version:updates:seconds
  ci-operator/step-registry/gather/extra/gather-extra-commands.sh
  ci-operator/step-registry/gather/libvirt/gather-libvirt-commands.sh
Labels: lgtm, approved

#24294 [vsphere] remove channel from cvo-overrides
  ci-operator/step-registry/upi/conf/vsphere/upi-conf-vsphere-commands.sh
Labels: lgtm, approved

#24293 ocm: use Go v1.17 in release-2.3
  ci-operator/config/open-cluster-management/discovery/open-cluster-management-discovery-release-2.3.yaml
  ci-operator/config/open-cluster-management/multiclusterhub-operator/open-cluster-management-multiclusterhub-operator-release-2.3.yaml
  ci-operator/config/open-cluster-management/multiclusterhub-repo/open-cluster-management-multiclusterhub-repo-release-2.3.yaml
  ci-operator/jobs/open-cluster-management/discovery/open-cluster-management-discovery-release-2.3-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/multiclusterhub-operator/open-cluster-management-multiclusterhub-operator-release-2.3-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/multiclusterhub-repo/open-cluster-management-multiclusterhub-repo-release-2.3-postsubmits.yaml
Labels: lgtm, approved

#23342 Revert "Add e2e-gcp to openshift-console-master.yaml config"
  ci-operator/config/openshift/console/openshift-console-master.yaml
  ci-operator/jobs/openshift/console/openshift-console-master-presubmits.yaml
Labels: lgtm, approved

#24286 Add ibm-vpc-node-label-updater repo
  ci-operator/config/openshift/ibm-vpc-node-label-updater/OWNERS
  ci-operator/config/openshift/ibm-vpc-node-label-updater/openshift-ibm-vpc-node-label-updater-master.yaml
  ci-operator/jobs/openshift/ibm-vpc-node-label-updater/OWNERS
  ci-operator/jobs/openshift/ibm-vpc-node-label-updater/openshift-ibm-vpc-node-label-updater-master-postsubmits.yaml
  ci-operator/jobs/openshift/ibm-vpc-node-label-updater/openshift-ibm-vpc-node-label-updater-master-presubmits.yaml
  core-services/image-mirroring/openshift/mapping_origin_4_10
  core-services/prow/02_config/openshift/ibm-vpc-node-label-updater/OWNERS
  core-services/prow/02_config/openshift/ibm-vpc-node-label-updater/_pluginconfig.yaml
Labels: lgtm, approved

#24304 Adding `build02` back into the pool
  clusters/app.ci/release-controller/deploy-ocp-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-priv-controller.yaml
  hack/generators/release-controllers/content/osd_rc_deployments.py
Labels: lgtm, approved

#24300 Need the go version for kind to match the build
  ci-operator/jobs/open-cluster-management/cert-policy-controller/open-cluster-management-cert-policy-controller-main-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/cert-policy-controller/open-cluster-management-cert-policy-controller-release-2.3-postsubmits.yaml
  core-services/prow/02_config/open-cluster-management/cert-policy-controller/_prowconfig.yaml
Labels: lgtm, approved

#24261 Add GCP IPI upgrade test job
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__ocp-4.10-upgrade-from-stable-4.9.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
Labels: lgtm, approved

#24298 assisted-installer: Update the bundle to the correct image
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__bundle.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-ocm-2.3__bundle.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.4__bundle.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-ocm-2.3-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-ocm-2.3-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.4-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.4-presubmits.yaml
Labels: lgtm, approved

#24258 medik8s/nhc: rename master to main, add release-0.1
  ci-operator/config/medik8s/node-healthcheck-operator/medik8s-node-healthcheck-operator-main.yaml
  ci-operator/config/medik8s/node-healthcheck-operator/medik8s-node-healthcheck-operator-release-0.1.yaml
  ci-operator/jobs/medik8s/node-healthcheck-operator/medik8s-node-healthcheck-operator-main-presubmits.yaml
  ci-operator/jobs/medik8s/node-healthcheck-operator/medik8s-node-healthcheck-operator-release-0.1-presubmits.yaml
Labels: lgtm, approved

#23938 Renable jenkins e2e basic smoke tests
  ci-operator/config/openshift/jenkins/openshift-jenkins-master.yaml
  ci-operator/jobs/openshift/jenkins/openshift-jenkins-master-presubmits.yaml
Labels: lgtm, approved

#24280 upgrade go to 1.17
  ci-operator/config/open-cluster-management/klusterlet-addon-controller/open-cluster-management-klusterlet-addon-controller-release-2.3.yaml
  ci-operator/config/open-cluster-management/klusterlet-addon-operator/open-cluster-management-klusterlet-addon-operator-main.yaml
  ci-operator/config/open-cluster-management/klusterlet-addon-operator/open-cluster-management-klusterlet-addon-operator-release-2.3.yaml
  ci-operator/config/open-cluster-management/klusterlet-addon-operator/open-cluster-management-klusterlet-addon-operator-release-2.4.yaml
  ci-operator/config/open-cluster-management/klusterlet-addon-operator/open-cluster-management-klusterlet-addon-operator-release-2.5.yaml
Labels: lgtm, approved

#24193 Add cucushift tests to testgrid
  core-services/testgrid-config-generator/_allow-list.yaml
Labels: lgtm, approved

#24279 Basic pre-submit jobs for openshift-knative/kn-plugin-event
  ci-operator/config/openshift-knative/kn-plugin-event/OWNERS
  ci-operator/config/openshift-knative/kn-plugin-event/openshift-knative-kn-plugin-event-release-0.26.yaml
  ci-operator/config/openshift-knative/kn-plugin-event/openshift-knative-kn-plugin-event-release-1.0.yaml
  ci-operator/config/openshift-knative/kn-plugin-event/openshift-knative-kn-plugin-event-release-next.yaml
  ci-operator/jobs/openshift-knative/kn-plugin-event/OWNERS
  ci-operator/jobs/openshift-knative/kn-plugin-event/openshift-knative-kn-plugin-event-release-0.26-presubmits.yaml
  ci-operator/jobs/openshift-knative/kn-plugin-event/openshift-knative-kn-plugin-event-release-1.0-presubmits.yaml
  ci-operator/jobs/openshift-knative/kn-plugin-event/openshift-knative-kn-plugin-event-release-next-presubmits.yaml
Labels: lgtm, approved

#24320 [4.11] Start syncing 4.11 configs with master
  ci-operator/jobs/infra-periodics.yaml
Labels: lgtm, approved

#24322 Tide for openshift-knative/kn-plugin-event
  core-services/prow/02_config/openshift-knative/kn-plugin-event/OWNERS
  core-services/prow/02_config/openshift-knative/kn-plugin-event/_prowconfig.yaml
Labels: lgtm, approved

#24246 SD AppSRE CI add ServiceAccount for pulling images
  clusters/app.ci/registry-access/sd-app-sre/OWNERS
  clusters/app.ci/registry-access/sd-app-sre/admin_manifest.yaml
Labels: lgtm, approved

#23996 b04: set up oauth accessTokenMaxAgeSeconds
  clusters/build-clusters/build04/assets/oauth.yaml
Labels: lgtm, approved

#24214 [knative-client] Update OCP version in test setup
  ci-operator/config/openshift/knative-client/openshift-knative-client-release-next__49.yaml
  ci-operator/jobs/openshift/knative-client/openshift-knative-client-release-next-postsubmits.yaml
  ci-operator/jobs/openshift/knative-client/openshift-knative-client-release-next-presubmits.yaml
Labels: lgtm, approved

#24326 Prune outdated ci jobs knative eventing
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.22.0__47.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.23__47.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.23__48.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.22.0-periodics.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.22.0-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.22.0-presubmits.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.23-periodics.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.23-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.23-presubmits.yaml
Labels: lgtm, approved

#24224 ci-operator/config/openshift/release: Monthly intervals for 4.5 jobs
  ci-operator/config/openshift/release/openshift-release-master__ci-4.5.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.6-upgrade-from-stable-4.5.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.5.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.6-upgrade-from-stable-4.5.yaml
  ci-operator/config/openshift/release/openshift-release-master__okd-4.5.yaml
  ci-operator/config/openshift/release/openshift-release-master__stable-4.7-upgrade-from-stable-4.6-from-stable-4.5.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: lgtm, approved

#23965 adding in e2e-aws test workflow for presubmit CI tests
  ci-operator/config/openshift/network-metrics-daemon/openshift-network-metrics-daemon-master.yaml
  ci-operator/jobs/openshift/network-metrics-daemon/openshift-network-metrics-daemon-master-presubmits.yaml
Labels: lgtm, approved

#24327 openstack-test-nfv: simplify rawCNIConfig
  ci-operator/step-registry/openstack/test/nfv/openstack-test-nfv-commands.sh
Labels: lgtm, approved

#24328 Remove the jobs from unsupported knative-eventing-kafka completely
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.22.0__47.yaml
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.23__47.yaml
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.23__48.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.22.0-periodics.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.22.0-postsubmits.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.22.0-presubmits.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.23-periodics.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.23-postsubmits.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.23-presubmits.yaml
Labels: lgtm, approved

#24296 Update prow to use the 1.17 go version
  ci-operator/config/open-cluster-management/iam-policy-controller/open-cluster-management-iam-policy-controller-main.yaml
  ci-operator/config/open-cluster-management/iam-policy-controller/open-cluster-management-iam-policy-controller-release-2.3.yaml
  ci-operator/config/open-cluster-management/iam-policy-controller/open-cluster-management-iam-policy-controller-release-2.4.yaml
  ci-operator/config/open-cluster-management/iam-policy-controller/open-cluster-management-iam-policy-controller-release-2.5.yaml
  ci-operator/jobs/open-cluster-management/iam-policy-controller/open-cluster-management-iam-policy-controller-main-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/iam-policy-controller/open-cluster-management-iam-policy-controller-release-2.3-postsubmits.yaml
  core-services/prow/02_config/open-cluster-management/iam-policy-controller/_prowconfig.yaml
Labels: lgtm, approved

#24291 Added necessary yaml file that was missing
  ci-operator/step-registry/network/calico/network-calico-commands.sh
Labels: lgtm, approved

#24171 dispatcher: take load to b04
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: lgtm, approved

#24336 add new restricted-label assign-on config to my test repo
  core-services/prow/02_config/smg247/ci-docs/_pluginconfig.yaml
Labels: lgtm, approved

#24315 baremetalds: Include link to failed job
  ci-operator/step-registry/baremetalds/packet/setup/baremetalds-packet-setup-commands.sh
  ci-operator/step-registry/baremetalds/packet/teardown/baremetalds-packet-teardown-commands.sh
Labels: lgtm, approved

#24340 fix notification for job mirroring
  ci-operator/jobs/infra-image-mirroring.yaml
Labels: lgtm, approved

#24343 add myself to rerun users
  core-services/prow/02_config/_config.yaml
Labels: lgtm, approved

#24161 [CVP-2389] Modify scorecard step to run MSP test cases
  ci-operator/config/redhat-openshift-ecosystem/cvp/redhat-openshift-ecosystem-cvp-ocp-4.6.yaml
  ci-operator/config/redhat-openshift-ecosystem/cvp/redhat-openshift-ecosystem-cvp-ocp-4.7.yaml
  ci-operator/config/redhat-openshift-ecosystem/cvp/redhat-openshift-ecosystem-cvp-ocp-4.8.yaml
  ci-operator/config/redhat-openshift-ecosystem/cvp/redhat-openshift-ecosystem-cvp-ocp-4.9.yaml
  ci-operator/config/redhat-openshift-ecosystem/msp/redhat-openshift-ecosystem-msp-ocp-4.8.yaml
  ci-operator/config/redhat-openshift-ecosystem/msp/redhat-openshift-ecosystem-msp-ocp-4.9.yaml
  ci-operator/step-registry/optional-operators/cvp-common/aws/optional-operators-cvp-common-aws-workflow.yaml
  ci-operator/step-registry/optional-operators/cvp-common/ibmz-eco/optional-operators-cvp-common-ibmz-eco-workflow.yaml
  ci-operator/step-registry/optional-operators/cvp-common/powervs/optional-operators-cvp-common-powervs-workflow.yaml
  ci-operator/step-registry/optional-operators/cvp-common/scorecard/optional-operators-cvp-common-scorecard-commands.sh
  ci-operator/step-registry/optional-operators/cvp-common/scorecard/optional-operators-cvp-common-scorecard-ref.yaml
Labels: lgtm, approved

#24212 openstack: set correct TEST_PROVIDER in e2e-test-commands
  ci-operator/step-registry/openshift/e2e/openstack/proxy/openshift-e2e-openstack-proxy-workflow.yaml
  ci-operator/step-registry/openshift/e2e/test/openshift-e2e-test-commands.sh
Labels: lgtm, approved

#24344 use existing additional label to trigger auto-assign
  core-services/prow/02_config/smg247/ci-docs/_pluginconfig.yaml
Labels: lgtm, approved

#24345 Bug 2024190: Fix rhcos.json location for later OpenShift UPI metal jobs
  ci-operator/templates/openshift/installer/cluster-launch-installer-metal-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#24346 assisted-installer: Define IMAGE_REPO for image publishing jobs
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-master.yaml
  ci-operator/step-registry/baremetalds/assisted/images/publish/baremetalds-assisted-images-publish-ref.yaml
Labels: lgtm, approved

#24353 prometheus: Add fallback target for react-app-test
  ci-operator/config/openshift/prometheus/openshift-prometheus-master.yaml
Labels: lgtm, approved

#24355 ocm clc e2e add 2.2
  ci-operator/config/open-cluster-management/cluster-lifecycle-e2e/open-cluster-management-cluster-lifecycle-e2e-release-2.2.yaml
  ci-operator/jobs/open-cluster-management/cluster-lifecycle-e2e/open-cluster-management-cluster-lifecycle-e2e-release-2.2-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/cluster-lifecycle-e2e/open-cluster-management-cluster-lifecycle-e2e-release-2.2-presubmits.yaml
Labels: lgtm, approved

#24356 Set timeout to 4h for cucushift-upgrade-pre
  ci-operator/step-registry/cucushift/upgrade/pre/cucushift-upgrade-pre-ref.yaml
Labels: lgtm, approved

#23812 Move OpenStack periodics from release to shiftstack
  ci-operator/config/openshift/release/openshift-release-master__ci-4.10-upgrade-from-stable-4.9.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.10.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.6.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.7-upgrade-from-stable-4.6.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.7.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.8-upgrade-from-stable-4.7.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.8.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.9-upgrade-from-stable-4.8.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.9.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.10.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.7.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.8.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.9.yaml
  ci-operator/config/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main__periodic-4.10-upgrade-from-stable-4.9.yaml
  ci-operator/config/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main__periodic-4.10.yaml
  ci-operator/config/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main__periodic-4.6.yaml
  ci-operator/config/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main__periodic-4.7-upgrade-from-stable-4.6.yaml
  ci-operator/config/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main__periodic-4.7.yaml
  ci-operator/config/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main__periodic-4.8-upgrade-from-stable-4.7.yaml
  ci-operator/config/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main__periodic-4.8.yaml
  ci-operator/config/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main__periodic-4.9-upgrade-from-stable-4.8.yaml
  ci-operator/config/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main__periodic-4.9.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  ci-operator/jobs/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main-periodics.yaml
Labels: lgtm, approved

#24338 cluster-api-provider-gcp: disable 4.11 promotion
  ci-operator/config/openshift/cluster-api-provider-gcp/openshift-cluster-api-provider-gcp-release-4.11.yaml
  ci-operator/jobs/openshift/cluster-api-provider-gcp/openshift-cluster-api-provider-gcp-release-4.11-presubmits.yaml
Labels: lgtm, approved

#24354 GPU Operator: remove 4.6->4.7 'master' upgrade testing
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-release-4.7__upgrade.yaml
  ci-operator/jobs/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-release-4.7-periodics.yaml
Labels: lgtm, approved

#24366 prometheus: bump node version to 16 LTS
  ci-operator/config/openshift/prometheus/openshift-prometheus-master.yaml
Labels: lgtm, approved

#24362 Add the installAttemptsLimit to all MSP cluster pools
  clusters/hive/pools/msp/msp-ocp-4-8-medium-single-az-amd64-aws-us-east-1_clusterpool.yaml
  clusters/hive/pools/msp/msp-ocp-4-8-small-single-az-amd64-aws-us-east-2_clusterpool.yaml
  clusters/hive/pools/msp/msp-ocp-4-9-medium-single-az-amd64-aws-us-east-1_clusterpool.yaml
  clusters/hive/pools/msp/msp-ocp-4-9-small-single-az-amd64-aws-us-east-2_clusterpool.yaml
Labels: lgtm, approved

#24367 Remove the customtest1 test case for msp clusters
  ci-operator/config/redhat-openshift-ecosystem/msp/redhat-openshift-ecosystem-msp-ocp-4.8.yaml
  ci-operator/config/redhat-openshift-ecosystem/msp/redhat-openshift-ecosystem-msp-ocp-4.9.yaml
Labels: lgtm, approved

#24256 remove dead periodic releases
  ci-operator/jobs/openshift/ibm-roks-toolkit/openshift-ibm-roks-toolkit-release-4.4-periodics.yaml
  ci-operator/jobs/openshift/ibm-roks-toolkit/openshift-ibm-roks-toolkit-release-4.5-periodics.yaml
  ci-operator/jobs/openshift/ibm-roks-toolkit/openshift-ibm-roks-toolkit-release-4.6-periodics.yaml
  ci-operator/jobs/openshift/ibm-roks-toolkit/openshift-ibm-roks-toolkit-release-4.7-periodics.yaml
Labels: lgtm, approved

#24371 disable fast-forward of main to stable
  ci-operator/config/identitatem/dex-operator/identitatem-dex-operator-main.yaml
  ci-operator/config/identitatem/idp-client-api/identitatem-idp-client-api-main.yaml
  ci-operator/config/identitatem/idp-mgmt-operator/identitatem-idp-mgmt-operator-main.yaml
  ci-operator/jobs/identitatem/dex-operator/identitatem-dex-operator-main-postsubmits.yaml
  ci-operator/jobs/identitatem/idp-client-api/identitatem-idp-client-api-main-postsubmits.yaml
  ci-operator/jobs/identitatem/idp-mgmt-operator/identitatem-idp-mgmt-operator-main-postsubmits.yaml
Labels: lgtm, approved

#24347 Alibaba Cloud Provider: rename to alibabacloud
  core-services/ci-secret-bootstrap/_config.yaml
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: lgtm, approved

#24381 openstack: re-enable slack notifications
  ci-operator/jobs/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main-periodics.yaml
Labels: lgtm, approved

#24330 [ironic] Do not run duplicate production jobs on packages upgrade
  ci-operator/config/openshift/ironic-image/openshift-ironic-image-master.yaml
  ci-operator/config/openshift/ironic-image/openshift-ironic-image-release-4.10.yaml
  ci-operator/config/openshift/ironic-image/openshift-ironic-image-release-4.11.yaml
  ci-operator/config/openshift/ironic-image/openshift-ironic-image-release-4.6.yaml
  ci-operator/config/openshift/ironic-image/openshift-ironic-image-release-4.7.yaml
  ci-operator/config/openshift/ironic-image/openshift-ironic-image-release-4.8.yaml
  ci-operator/config/openshift/ironic-image/openshift-ironic-image-release-4.9.yaml
  ci-operator/jobs/openshift/ironic-image/openshift-ironic-image-master-presubmits.yaml
  ci-operator/jobs/openshift/ironic-image/openshift-ironic-image-release-4.10-presubmits.yaml
  ci-operator/jobs/openshift/ironic-image/openshift-ironic-image-release-4.11-presubmits.yaml
  ci-operator/jobs/openshift/ironic-image/openshift-ironic-image-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/ironic-image/openshift-ironic-image-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/ironic-image/openshift-ironic-image-release-4.8-presubmits.yaml
  ci-operator/jobs/openshift/ironic-image/openshift-ironic-image-release-4.9-presubmits.yaml
Labels: lgtm, approved

#24333 [agent] Do not run duplicate production jobs on packages upgrade
  ci-operator/config/openshift/ironic-agent-image/openshift-ironic-agent-image-main.yaml
  ci-operator/config/openshift/ironic-agent-image/openshift-ironic-agent-image-release-4.10.yaml
  ci-operator/config/openshift/ironic-agent-image/openshift-ironic-agent-image-release-4.11.yaml
  ci-operator/config/openshift/ironic-agent-image/openshift-ironic-agent-image-release-4.8.yaml
  ci-operator/config/openshift/ironic-agent-image/openshift-ironic-agent-image-release-4.9.yaml
  ci-operator/jobs/openshift/ironic-agent-image/openshift-ironic-agent-image-main-presubmits.yaml
  ci-operator/jobs/openshift/ironic-agent-image/openshift-ironic-agent-image-release-4.10-presubmits.yaml
  ci-operator/jobs/openshift/ironic-agent-image/openshift-ironic-agent-image-release-4.11-presubmits.yaml
  ci-operator/jobs/openshift/ironic-agent-image/openshift-ironic-agent-image-release-4.8-presubmits.yaml
  ci-operator/jobs/openshift/ironic-agent-image/openshift-ironic-agent-image-release-4.9-presubmits.yaml
Labels: lgtm, approved

#24387 Add canary job notifications back in after they were removed inadvertently
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: lgtm, approved

#24305 Effectively disable EOL rhcos promotion
  ci-operator/jobs/openshift/release/openshift-release-release-4.1-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
Labels: lgtm, approved

#24391 Ocm observability pr image mirror
  ci-operator/config/open-cluster-management/insights-metrics/open-cluster-management-insights-metrics-release-2.4.yaml
  ci-operator/config/open-cluster-management/insights-metrics/open-cluster-management-insights-metrics-release-2.5.yaml
  ci-operator/config/open-cluster-management/search-aggregator/open-cluster-management-search-aggregator-release-2.4.yaml
  ci-operator/config/open-cluster-management/search-aggregator/open-cluster-management-search-aggregator-release-2.5.yaml
  ci-operator/config/open-cluster-management/search-api/open-cluster-management-search-api-release-2.4.yaml
  ci-operator/config/open-cluster-management/search-api/open-cluster-management-search-api-release-2.5.yaml
  ci-operator/config/open-cluster-management/search-collector/open-cluster-management-search-collector-release-2.5.yaml
  ci-operator/config/open-cluster-management/search-operator/open-cluster-management-search-operator-release-2.4.yaml
  ci-operator/config/open-cluster-management/search-operator/open-cluster-management-search-operator-release-2.5.yaml
  ci-operator/jobs/open-cluster-management/insights-metrics/open-cluster-management-insights-metrics-release-2.4-presubmits.yaml
  ci-operator/jobs/open-cluster-management/insights-metrics/open-cluster-management-insights-metrics-release-2.5-presubmits.yaml
  ci-operator/jobs/open-cluster-management/search-aggregator/open-cluster-management-search-aggregator-release-2.4-presubmits.yaml
  ci-operator/jobs/open-cluster-management/search-aggregator/open-cluster-management-search-aggregator-release-2.5-presubmits.yaml
  ci-operator/jobs/open-cluster-management/search-api/open-cluster-management-search-api-release-2.4-presubmits.yaml
  ci-operator/jobs/open-cluster-management/search-api/open-cluster-management-search-api-release-2.5-presubmits.yaml
  ci-operator/jobs/open-cluster-management/search-collector/open-cluster-management-search-collector-release-2.5-presubmits.yaml
  ci-operator/jobs/open-cluster-management/search-operator/open-cluster-management-search-operator-release-2.4-presubmits.yaml
  ci-operator/jobs/open-cluster-management/search-operator/open-cluster-management-search-operator-release-2.5-presubmits.yaml
Labels: lgtm, approved

#24370 telco-bastion: remove localhost workaround
  ci-operator/step-registry/telco-bastion/setup/telco-bastion-setup-commands.sh
Labels: lgtm, approved

#24335 openshift/builder: Add RHEL7 builds variant
  ci-operator/config/openshift/builder/openshift-builder-master.yaml
  ci-operator/config/openshift/builder/openshift-builder-release-4.10.yaml
  ci-operator/config/openshift/builder/openshift-builder-release-4.11.yaml
  ci-operator/config/openshift/builder/openshift-builder-release-4.9.yaml
  ci-operator/jobs/openshift/builder/openshift-builder-master-presubmits.yaml
  ci-operator/jobs/openshift/builder/openshift-builder-release-4.10-presubmits.yaml
  ci-operator/jobs/openshift/builder/openshift-builder-release-4.11-presubmits.yaml
  ci-operator/jobs/openshift/builder/openshift-builder-release-4.9-presubmits.yaml
Labels: lgtm, approved

#24395 add tide configuration to cloud-event-proxy and hw-event-proxy
  core-services/prow/02_config/redhat-cne/cloud-event-proxy/_prowconfig.yaml
  core-services/prow/02_config/redhat-cne/hw-event-proxy/_prowconfig.yaml
Labels: lgtm, approved

#24399 reduce resources
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-master.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.7.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.8.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.9.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-master-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.7-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.8-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.9-periodics.yaml
Labels: lgtm, approved

#24403 upgrade to go 1.17
  ci-operator/config/open-cluster-management/endpoint-metrics-operator/open-cluster-management-endpoint-metrics-operator-release-2.3.yaml
Labels: lgtm, approved

#24411 Serverless: remove old periodic runs
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.10__4.5.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.13__4.6.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.13__4.7.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.14__4.6.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.14__4.7.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.15__4.6.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.15__4.7.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.16__4.6.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.16__4.7.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.16__4.8.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.17__4.6.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.17__4.7.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.17__4.8.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.18__4.6.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.18__4.7.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.18__4.8.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.18__4.9.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.19__4.6.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.19__4.7.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.19__4.8.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.19__4.9.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.10-periodics.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.13-periodics.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.14-periodics.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.15-periodics.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.16-periodics.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.17-periodics.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.18-periodics.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.19-periodics.yaml
Labels: lgtm, approved

#24208 Manually skip proxy related tests only for parallel suite
  ci-operator/step-registry/baremetalds/e2e/test/baremetalds-e2e-test-commands.sh
Labels: lgtm, approved
