Repository openshift/release, pull requests merged in 2021-10, with the labels that each got.

#22413 override bugzilla prow repo settings for Assisted
  core-services/prow/02_config/openshift/assisted-image-service/_pluginconfig.yaml
  core-services/prow/02_config/openshift/assisted-installer-agent/_pluginconfig.yaml
  core-services/prow/02_config/openshift/assisted-installer/_pluginconfig.yaml
  core-services/prow/02_config/openshift/assisted-service/_pluginconfig.yaml
Labels: lgtm, approved

#22414 Add sa/github-ldap-mapping-updater
  clusters/app.ci/assets/admin_github-ldap-mapping-updater_rbac.yaml
Labels: lgtm, approved

#22419 use @odo-team for odo-notifications
  ci-operator/jobs/openshift/odo/openshift-odo-main-periodics.yaml
Labels: lgtm, approved

#22423 fix spelling issue
  ci-operator/config/openshift-priv/openldap/openshift-priv-openldap-master.yaml
  ci-operator/config/openshift-priv/openldap/openshift-priv-openldap-release-4.10.yaml
  ci-operator/config/openshift/openldap/openshift-openldap-master.yaml
  ci-operator/config/openshift/openldap/openshift-openldap-release-4.10.yaml
Labels: lgtm, approved

#22424 assisted: fix target_release to include `rhacm`
  core-services/prow/02_config/openshift/assisted-image-service/_pluginconfig.yaml
  core-services/prow/02_config/openshift/assisted-installer-agent/_pluginconfig.yaml
  core-services/prow/02_config/openshift/assisted-installer/_pluginconfig.yaml
  core-services/prow/02_config/openshift/assisted-service/_pluginconfig.yaml
Labels: lgtm, approved

#22409 Add job: periodic-github-ldap-user-group-creator
  ci-operator/jobs/infra-periodics.yaml
Labels: lgtm, approved

#22420 Update root OWNERS
  OWNERS
  OWNERS_ALIASES
Labels: lgtm, approved

#22426 periodic-github-ldap-user-group-creator: --dry-run=false
  Makefile
  ci-operator/jobs/infra-periodics.yaml
  clusters/build-clusters/common/assets/admin_github-ldap-user-group-creator_rbac.yaml
Labels: lgtm, approved

#20663 Replace run_if_changed with skip_if_only_changed
  ci-operator/config/openshift/cluster-api-provider-openstack/openshift-cluster-api-provider-openstack-master.yaml
  ci-operator/config/openshift/cluster-api-provider-openstack/openshift-cluster-api-provider-openstack-release-4.10.yaml
  ci-operator/config/openshift/cluster-api-provider-openstack/openshift-cluster-api-provider-openstack-release-4.9.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.1.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.2.yaml
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-master.yaml
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-release-4.10.yaml
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-release-4.9.yaml
  ci-operator/jobs/openshift/cluster-api-provider-openstack/openshift-cluster-api-provider-openstack-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-openstack/openshift-cluster-api-provider-openstack-release-4.10-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-openstack/openshift-cluster-api-provider-openstack-release-4.9-presubmits.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-release-4.10-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-release-4.9-presubmits.yaml
Labels: lgtm, approved

#22428 run e2e after azure upgrade
  ci-operator/config/openshift/release/openshift-release-master__ci-4.10-upgrade-from-stable-4.9.yaml
Labels: lgtm, approved

#22285 Add openshift/ibm-vpc-block-csi-driver-operator repo
  ci-operator/config/openshift/ibm-vpc-block-csi-driver-operator/OWNERS
  ci-operator/config/openshift/ibm-vpc-block-csi-driver-operator/openshift-ibm-vpc-block-csi-driver-operator-master.yaml
  ci-operator/jobs/openshift/ibm-vpc-block-csi-driver-operator/OWNERS
  ci-operator/jobs/openshift/ibm-vpc-block-csi-driver-operator/openshift-ibm-vpc-block-csi-driver-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/ibm-vpc-block-csi-driver-operator/openshift-ibm-vpc-block-csi-driver-operator-master-presubmits.yaml
  core-services/image-mirroring/openshift/mapping_origin_4_10
  core-services/prow/02_config/openshift/ibm-vpc-block-csi-driver-operator/OWNERS
  core-services/prow/02_config/openshift/ibm-vpc-block-csi-driver-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/ibm-vpc-block-csi-driver-operator/_prowconfig.yaml
Labels: lgtm, approved

#20036 volsync-operator e2e
  ci-operator/config/backube/volsync/backube-volsync-main.yaml
  ci-operator/jobs/backube/volsync/backube-volsync-main-postsubmits.yaml
  ci-operator/jobs/backube/volsync/backube-volsync-main-presubmits.yaml
  ci-operator/step-registry/ipi/aws/volsync-csi/OWNERS
  ci-operator/step-registry/ipi/aws/volsync-csi/ipi-aws-volsync-csi-workflow.metadata.json
  ci-operator/step-registry/ipi/aws/volsync-csi/ipi-aws-volsync-csi-workflow.yaml
  ci-operator/step-registry/volsync-csi/OWNERS
  ci-operator/step-registry/volsync-csi/conf/OWNERS
  ci-operator/step-registry/volsync-csi/conf/aws/OWNERS
  ci-operator/step-registry/volsync-csi/conf/aws/volsync-csi-conf-aws-commands.sh
  ci-operator/step-registry/volsync-csi/conf/aws/volsync-csi-conf-aws-ref.metadata.json
  ci-operator/step-registry/volsync-csi/conf/aws/volsync-csi-conf-aws-ref.yaml
  clusters/app.ci/registry-access/volsync/OWNERS
  clusters/app.ci/registry-access/volsync/admin_manifest.yaml
Labels: lgtm, approved

#22434 ci-operator/step-registry/openshift/e2e/test: Wait for Progressing=False ClusterVersion
  ci-operator/step-registry/openshift/e2e/test/openshift-e2e-test-commands.sh
Labels: lgtm, approved

#21632 Change the azure release periodic jobs to run on the 2nd subscription
  ci-operator/config/openshift/release/openshift-release-master__ci-4.10.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.6.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.7.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.8.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.9.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: lgtm, approved

#22377 adding cucushift tests for vsphere-ipi
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__4.9.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
  ci-operator/step-registry/cucushift/vsphere/OWNERS
  ci-operator/step-registry/cucushift/vsphere/ipi/OWNERS
  ci-operator/step-registry/cucushift/vsphere/ipi/cucushift-vsphere-ipi-commands.sh
  ci-operator/step-registry/cucushift/vsphere/ipi/cucushift-vsphere-ipi-ref.metadata.json
  ci-operator/step-registry/cucushift/vsphere/ipi/cucushift-vsphere-ipi-ref.yaml
  ci-operator/step-registry/cucushift/vsphere/ipi/cucushift-vsphere-ipi-workflow.metadata.json
  ci-operator/step-registry/cucushift/vsphere/ipi/cucushift-vsphere-ipi-workflow.yaml
Labels: lgtm, approved

#21895 shiftstack monitor: Add Vexxhost
  ci-operator/config/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main.yaml
  ci-operator/jobs/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main-periodics.yaml
  clusters/app.ci/prow-monitoring/additional-scrape-configs_secret.yaml
Labels: lgtm, approved

#22446 hco: drop obsolete upgrade lanes on release-1.4
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-1.4.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-1.4-presubmits.yaml
Labels: lgtm, approved

#21117 cloud-provider-openstack: Add CCM presubmits
  ci-operator/config/openshift/cloud-provider-openstack/openshift-cloud-provider-openstack-master.yaml
  ci-operator/jobs/openshift/cloud-provider-openstack/openshift-cloud-provider-openstack-master-presubmits.yaml
  ci-operator/step-registry/openshift/e2e/openstack/ccm/install/OWNERS
  ci-operator/step-registry/openshift/e2e/openstack/ccm/install/openshift-e2e-openstack-ccm-install-workflow.metadata.json
  ci-operator/step-registry/openshift/e2e/openstack/ccm/install/openshift-e2e-openstack-ccm-install-workflow.yaml
Labels: lgtm, approved

#22447 dashboards: add Azure-2 dashboard
  clusters/app.ci/prow-monitoring/mixins/_grafana_dashboards/boskos.jsonnet
  clusters/app.ci/prow-monitoring/mixins/_grafana_dashboards_out/boskos.json
Labels: lgtm, approved

#21780 openstack-test: Add repository
  ci-operator/config/openshift/openstack-test/OWNERS
  ci-operator/config/openshift/openstack-test/openshift-openstack-test-main.yaml
  ci-operator/jobs/openshift/openstack-test/OWNERS
  ci-operator/jobs/openshift/openstack-test/openshift-openstack-test-main-presubmits.yaml
  core-services/prow/02_config/openshift/openstack-test/_pluginconfig.yaml
Labels: lgtm, approved

#22455 Added envtest assests directory as environment variable
  ci-operator/config/openshift/external-dns-operator/openshift-external-dns-operator-main.yaml
Labels: lgtm, approved

#22421 remove ibm k8s tests
  ci-operator/config/openshift/odo/openshift-odo-main__psi.yaml
  ci-operator/jobs/openshift/odo/openshift-odo-main-presubmits.yaml
Labels: lgtm, approved

#22355 Add CNV informing jobs for OCP v4.10 nightly builds
  ci-operator/config/openshift-cnv/cnv-ci/openshift-cnv-cnv-ci-release-4.10.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.10.yaml
  ci-operator/jobs/openshift-cnv/cnv-ci/openshift-cnv-cnv-ci-release-4.10-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  core-services/release-controller/_releases/release-ocp-4.10.json
Labels: lgtm, approved

#22441 ocm: run search e2e with clusterpool
  ci-operator/config/open-cluster-management/search-e2e-test/open-cluster-management-search-e2e-test-main.yaml
Labels: lgtm, approved

#20134 Remove OKD promote jobs for 4.7 -> 4.9
  ci-operator/jobs/openshift/release/openshift-release-release-4.10-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.8-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.9-periodics.yaml
Labels: lgtm, approved

#21461 Add golangci-lint job to OCM/submariner-addon
  ci-operator/config/open-cluster-management/submariner-addon/open-cluster-management-submariner-addon-main.yaml
  ci-operator/jobs/open-cluster-management/submariner-addon/open-cluster-management-submariner-addon-main-presubmits.yaml
Labels: lgtm, approved

#22458 Change channel of live-iso periodic job to #edge-group-single-node
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-periodics.yaml
Labels: lgtm, approved

#22457 make aws upgrade jobs required for 4.10
  core-services/release-controller/_releases/release-ocp-4.10-ci.json
  core-services/release-controller/_releases/release-ocp-4.10.json
Labels: lgtm, approved

#22234 Set up deprovision job for aws osd hypershift
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-infra-periodics.yaml
  clusters/app.ci/ipi-deprovision/ipi-deprovision-bc.yaml
  core-services/ipi-deprovision/aws.sh
Labels: lgtm, approved

#22461 Update go version of runtime-utils ci config
  ci-operator/config/openshift/runtime-utils/openshift-runtime-utils-master.yaml
  ci-operator/config/openshift/runtime-utils/openshift-runtime-utils-release-4.10.yaml
Labels: lgtm, approved

#22444 ci: skip kata/cri-o integration tests on unsupported branches
  ci-operator/jobs/cri-o/cri-o/cri-o-cri-o-main-presubmits.yaml
Labels: lgtm, approved, ok-to-test

#22464 hco: drop obsolete upgrade lane on release-1.4
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-1.4.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-1.4-presubmits.yaml
Labels: lgtm, approved

#22431 Add storage-migrate image for eventing-kafka
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-next__47.yaml
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-next__48.yaml
Labels: lgtm, approved

#22459 Register cluster-api-provider-alibaba in OpenShift CI
  ci-operator/config/openshift/cluster-api-provider-alibaba/OWNERS
  ci-operator/config/openshift/cluster-api-provider-alibaba/openshift-cluster-api-provider-alibaba-main.yaml
  ci-operator/jobs/openshift/cluster-api-provider-alibaba/OWNERS
  ci-operator/jobs/openshift/cluster-api-provider-alibaba/openshift-cluster-api-provider-alibaba-main-presubmits.yaml
  core-services/prow/02_config/openshift/cluster-api-provider-alibaba/OWNERS
  core-services/prow/02_config/openshift/cluster-api-provider-alibaba/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-api-provider-alibaba/_prowconfig.yaml
Labels: lgtm, approved

#22468 Update logging e2e jobs to allow runtime of 3hours
  ci-operator/config/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-master.yaml
Labels: lgtm, approved

#22185 Update entrypoints to use the 'nightly' command group
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-master.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-master__4.10.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-master__4.6.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-master__4.7.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-master__4.8.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-master__4.9.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-master__nfd.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-master__nto.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-master__sro.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-master__upgrade.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-release-4.6.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-release-4.7.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-release-4.7__sro.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-release-4.7__upgrade.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-release-4.8.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-release-4.8__nfd.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-release-4.8__nto.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-release-4.8__sro.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-release-4.9.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-release-4.9__nfd.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-release-4.9__nto.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-release-4.9__sro.yaml
  ci-operator/jobs/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-master-presubmits.yaml
Labels: lgtm, approved

#22466 Review baremetalds steps registry owners list
  ci-operator/step-registry/baremetalds/OWNERS
  ci-operator/step-registry/baremetalds/devscripts/conf/ipv4/baremetalds-devscripts-conf-ipv4-ref.metadata.json
  ci-operator/step-registry/baremetalds/devscripts/conf/virtualmedia/baremetalds-devscripts-conf-virtualmedia-ref.metadata.json
  ci-operator/step-registry/baremetalds/devscripts/gather/baremetalds-devscripts-gather-ref.metadata.json
  ci-operator/step-registry/baremetalds/e2e/baremetalds-e2e-workflow.metadata.json
  ci-operator/step-registry/baremetalds/e2e/conf/baremetalds-e2e-conf-ref.metadata.json
  ci-operator/step-registry/baremetalds/e2e/test/baremetalds-e2e-test-ref.metadata.json
  ci-operator/step-registry/baremetalds/packet/check/baremetalds-packet-check-ref.metadata.json
  ci-operator/step-registry/baremetalds/packet/setup/baremetalds-packet-setup-ref.metadata.json
  ci-operator/step-registry/baremetalds/packet/teardown/baremetalds-packet-teardown-ref.metadata.json
Labels: lgtm, approved

#22472 ocm: run search e2e on clusters with ACM
  ci-operator/config/open-cluster-management/search-e2e-test/open-cluster-management-search-e2e-test-main.yaml
Labels: lgtm, approved

#22471 Add z-stream approvers for OLM components
  core-services/prow/02_config/openshift/operator-framework-olm/_pluginconfig.yaml
  core-services/prow/02_config/operator-framework/operator-lifecycle-manager/_pluginconfig.yaml
  core-services/prow/02_config/operator-framework/operator-marketplace/_pluginconfig.yaml
  core-services/prow/02_config/operator-framework/operator-registry/_pluginconfig.yaml
Labels: lgtm, approved

#22476 OWNERS_ALIASES: Remove no-longer-auto-maintained cruft
  OWNERS_ALIASES
Labels: lgtm, approved

#22478 add more aggregated jobs for 4.10 upgrades
  ci-operator/config/openshift/release/openshift-release-master__ci-4.10.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  core-services/release-controller/_releases/release-ocp-4.10-ci.json
  core-services/release-controller/_releases/release-ocp-4.10.json
Labels: lgtm, approved

#21804 Add tracking of etcdGRPCRequestsSlow
  ci-operator/step-registry/openshift/e2e/libvirt/test/openshift-e2e-libvirt-test-commands.sh
Labels: lgtm, approved

#22479 Skip more tests for openshift-e2e-openstack-proxy
  ci-operator/step-registry/openshift/e2e/openstack/proxy/openshift-e2e-openstack-proxy-workflow.yaml
Labels: lgtm, approved

#22480 NFD-Operator moves to channel stable
  ci-operator/config/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-master.yaml
  ci-operator/config/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-release-4.10.yaml
Labels: lgtm, approved

#22481 4.10 Updates for NFD Operator
  ci-operator/config/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-master.yaml
  ci-operator/config/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-release-4.10.yaml
Labels: lgtm, approved

#22485 ocm : use clusterclaim name for e2e
  ci-operator/config/open-cluster-management/search-e2e-test/open-cluster-management-search-e2e-test-main.yaml
Labels: lgtm, approved

#22433 Onboard StackRox CI image
  ci-operator/config/stackrox/rox-ci-image/.config.prowgen
  ci-operator/config/stackrox/rox-ci-image/OWNERS
  ci-operator/config/stackrox/rox-ci-image/stackrox-rox-ci-image-master.yaml
  ci-operator/jobs/stackrox/rox-ci-image/OWNERS
  ci-operator/jobs/stackrox/rox-ci-image/stackrox-rox-ci-image-master-postsubmits.yaml
  ci-operator/jobs/stackrox/rox-ci-image/stackrox-rox-ci-image-master-presubmits.yaml
  core-services/prow/02_config/stackrox/rox-ci-image/_pluginconfig.yaml
Labels: lgtm, approved, tide/merge-method-squash

#22486 [OHSS-6587] Remove godell from OWNERS files
  core-services/prow/02_config/openshift/azure-sop/OWNERS
  projects/azure/OWNERS
Labels: lgtm, approved, sig/azure

#22493 Bump number of workers to 3 in ipi jobs
  ci-operator/step-registry/baremetalds/devscripts/setup/baremetalds-devscripts-setup-commands.sh
Labels: lgtm, approved

#22474 ci-operator: add job for coreos-assembler:4.9
  ci-operator/config/coreos/coreos-assembler/coreos-coreos-assembler-rhcos-4.9.yaml
  ci-operator/jobs/coreos/coreos-assembler/coreos-coreos-assembler-rhcos-4.9-presubmits.yaml
Labels: lgtm, approved

#22449 CPROD-81: Create a definition with another cluster flavour
  clusters/hive/pools/msp/install-config-aws-medium-us-east-1_secret.yaml
  clusters/hive/pools/msp/install-config-aws-small-us-east-2_secret.yaml
  clusters/hive/pools/msp/msp-ocp-4-8-medium-single-az-amd64-aws-us-east-1_clusterpool.yaml
  clusters/hive/pools/msp/msp-ocp-4-8-small-single-az-amd64-aws-us-east-2_clusterpool.yaml
Labels: lgtm, approved

#22491 Set temp dir to XDG_CACHE_HOME instead of ENV_ASSETS_DIR for env tests
  ci-operator/config/openshift/external-dns-operator/openshift-external-dns-operator-main.yaml
Labels: lgtm, approved

#22450 Move the rest of the azure release periodics to run on the 2nd subscription
  ci-operator/config/openshift/release/openshift-release-master__ci-4.10-upgrade-from-stable-4.9.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.4.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.5-upgrade-from-stable-4.4.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.5.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.6-upgrade-from-stable-4.5.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.7-upgrade-from-stable-4.6.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.8-upgrade-from-stable-4.7.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.9-upgrade-from-stable-4.8.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.10.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.2.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.3.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.4.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.5.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.6.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.7.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.8.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.9.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: lgtm, approved

#22494 jobs: shard job-config-master further
  core-services/prow/02_config/_plugins.yaml
Labels: lgtm, approved

#22384 Increase SSHOPTS log level to error to suppress warnings
  ci-operator/step-registry/baremetalds/packet/setup/baremetalds-packet-setup-commands.sh
Labels: lgtm, approved

#22496 jobs: use master job config shards
  clusters/app.ci/assets/dptp-controller-manager.yaml
  clusters/app.ci/assets/slack-bot.yaml
  clusters/app.ci/ci-chat-bot/ci-chat-bot.yaml
  clusters/app.ci/prow/03_deployment/crier.yaml
  clusters/app.ci/prow/03_deployment/deck.yaml
  clusters/app.ci/prow/03_deployment/hook.yaml
  clusters/app.ci/prow/03_deployment/horologium.yaml
  clusters/app.ci/prow/03_deployment/jenkins_operator.yaml
  clusters/app.ci/prow/03_deployment/prow-controller-manager.yaml
  clusters/app.ci/prow/03_deployment/sinker.yaml
  clusters/app.ci/prow/03_deployment/statusreconciler.yaml
  clusters/app.ci/prow/03_deployment/tide.yaml
  clusters/app.ci/prow/03_deployment/tot.yaml
  clusters/app.ci/release-controller/deploy-ocp-arm64-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-arm64-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-ppc64le-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-ppc64le-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-s390x-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-s390x-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-origin-controller.yaml
  hack/generators/release-controllers/content/utils.py
Labels: lgtm, approved

#22489 Add z-stream approvers for Infrastructure Security & Compliance components
  core-services/prow/02_config/openshift/compliance-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/file-integrity-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/oc-compliance/_pluginconfig.yaml
Labels: lgtm, approved

#22345 Updates Azure Red Hat OpenShift team
  clusters/app.ci/registry-access/azure/admin_azure_list.yaml
  core-services/image-mirroring/openshift-azure/OWNERS
  projects/azure/OWNERS
Labels: lgtm, approved, sig/azure

#22498 Set backport-risk-assessed for shiftstack owned repos
  core-services/prow/02_config/openshift/cloud-provider-openstack/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-api-provider-openstack/_pluginconfig.yaml
  core-services/prow/02_config/openshift/csi-driver-manila-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/csi-driver-nfs/_pluginconfig.yaml
  core-services/prow/02_config/openshift/openstack-cinder-csi-driver-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/openstack-test/_pluginconfig.yaml
Labels: lgtm, approved

#22107 Remove TechPreviewNoUpgrade from Azure CSI workflow
  ci-operator/step-registry/openshift/e2e/azure/csi/OWNERS
  ci-operator/step-registry/openshift/e2e/azure/csi/migration/OWNERS
  ci-operator/step-registry/openshift/e2e/azure/csi/migration/openshift-e2e-azure-csi-migration-workflow.metadata.json
  ci-operator/step-registry/openshift/e2e/azure/csi/openshift-e2e-azure-csi-workflow.metadata.json
  ci-operator/step-registry/openshift/e2e/azure/csi/openshift-e2e-azure-csi-workflow.yaml
Labels: lgtm, approved

#22500 Add Krunoslav Pavic to MSP Cluster Pool admins
  clusters/hive/pools/msp/admins_msp-cluster-pool_rbac.yaml
Labels: lgtm, approved

#22483 Add verify check for ibm-vpc-block-csi-driver-operator
  ci-operator/config/openshift/ibm-vpc-block-csi-driver-operator/openshift-ibm-vpc-block-csi-driver-operator-master.yaml
  ci-operator/jobs/openshift/ibm-vpc-block-csi-driver-operator/openshift-ibm-vpc-block-csi-driver-operator-master-presubmits.yaml
Labels: lgtm, approved

#22495 Redact some info from metal-ipi step registry setup
  ci-operator/step-registry/baremetalds/devscripts/setup/baremetalds-devscripts-setup-commands.sh
Labels: lgtm, approved

#22505 ocm : using search pool for e2e tests
  ci-operator/config/open-cluster-management/search-e2e-test/open-cluster-management-search-e2e-test-main.yaml
Labels: lgtm, approved

#22501 Add e2e-metal-assisted-ipv4v6 job
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-periodics.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-presubmits.yaml
Labels: lgtm, approved

#22504 Fix Dockerfile locations
  ci-operator/config/kubevirt/node-maintenance-operator/kubevirt-node-maintenance-operator-master.yaml
Labels: lgtm, approved

#22482 NFD Operand 4.10 updates
  ci-operator/config/openshift/node-feature-discovery/openshift-node-feature-discovery-master.yaml
  ci-operator/config/openshift/node-feature-discovery/openshift-node-feature-discovery-release-4.10.yaml
Labels: lgtm, approved

#22507 Remove slash to fix sed command in metal-ipi setup
  ci-operator/step-registry/baremetalds/devscripts/setup/baremetalds-devscripts-setup-commands.sh
Labels: lgtm, approved

#22506 Set GOLANGCI_LINT_CACHE for verify target
  ci-operator/config/openshift/external-dns-operator/openshift-external-dns-operator-main.yaml
Labels: lgtm, approved

#22509 Update NFD-O images for 4.10
  ci-operator/config/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-master.yaml
  ci-operator/config/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-release-4.10.yaml
Labels: lgtm, approved

#22511 ocm: remove the log printing COMPONENT_IMAGE_REF
  ci-operator/config/open-cluster-management/search-e2e-test/open-cluster-management-search-e2e-test-main.yaml
Labels: lgtm, approved

#22465 add z-stream-approver for OpenShift installer repo
  core-services/prow/02_config/openshift/installer/_pluginconfig.yaml
Labels: lgtm, approved

#22445 Enable no-feature-freeze labels for the Insights operator
  core-services/prow/02_config/openshift/insights-operator/_prowconfig.yaml
Labels: lgtm, approved

#22470 Add z-stream approvers for OCP Storage components
  core-services/prow/02_config/openshift/alibaba-cloud-csi-driver/_pluginconfig.yaml
  core-services/prow/02_config/openshift/alibaba-disk-csi-driver-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/aws-ebs-csi-driver-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/aws-ebs-csi-driver/_pluginconfig.yaml
  core-services/prow/02_config/openshift/aws-efs-csi-driver-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/aws-efs-csi-driver/_pluginconfig.yaml
  core-services/prow/02_config/openshift/aws-efs-utils/_pluginconfig.yaml
  core-services/prow/02_config/openshift/azure-disk-csi-driver-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/azure-disk-csi-driver/_pluginconfig.yaml
  core-services/prow/02_config/openshift/azure-file-csi-driver-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/azure-file-csi-driver/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-csi-snapshot-controller-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-storage-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/csi-cluster-driver-registrar/_pluginconfig.yaml
  core-services/prow/02_config/openshift/csi-driver-registrar/_pluginconfig.yaml
  core-services/prow/02_config/openshift/csi-external-attacher/_pluginconfig.yaml
  core-services/prow/02_config/openshift/csi-external-provisioner/_pluginconfig.yaml
  core-services/prow/02_config/openshift/csi-external-resizer/_pluginconfig.yaml
  core-services/prow/02_config/openshift/csi-external-snapshotter/_pluginconfig.yaml
  core-services/prow/02_config/openshift/csi-livenessprobe/_pluginconfig.yaml
  core-services/prow/02_config/openshift/csi-node-driver-registrar/_pluginconfig.yaml
  core-services/prow/02_config/openshift/gcp-pd-csi-driver-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/gcp-pd-csi-driver/_pluginconfig.yaml
  core-services/prow/02_config/openshift/ibm-vpc-block-csi-driver-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/ibm-vpc-block-csi-driver/_pluginconfig.yaml
  core-services/prow/02_config/openshift/local-storage-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/sig-storage-local-static-provisioner/_pluginconfig.yaml
  core-services/prow/02_config/openshift/vmware-vsphere-csi-driver-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/vmware-vsphere-csi-driver/_pluginconfig.yaml
  core-services/prow/02_config/openshift/vsphere-problem-detector/_pluginconfig.yaml
Labels: lgtm, approved

#22513 Use rebase merge strategy for OCM/Submariner
  core-services/prow/02_config/open-cluster-management/submariner-addon/_prowconfig.yaml
Labels: lgtm, approved

#22359 make openshift-tests wait on a clean image import for images that are used
  ci-operator/step-registry/openshift/e2e/test/openshift-e2e-test-commands.sh
Labels: lgtm, approved

#22514 change rook org from openshift to red-hat-storage
  ci-operator/config/red-hat-storage/rook/OWNERS
  ci-operator/config/red-hat-storage/rook/red-hat-storage-rook-master.yaml
  ci-operator/config/red-hat-storage/rook/red-hat-storage-rook-release-4.6.yaml
  ci-operator/config/red-hat-storage/rook/red-hat-storage-rook-release-4.7.yaml
  ci-operator/config/red-hat-storage/rook/red-hat-storage-rook-release-4.8.yaml
  ci-operator/jobs/red-hat-storage/rook/OWNERS
  ci-operator/jobs/red-hat-storage/rook/red-hat-storage-rook-master-presubmits.yaml
  ci-operator/jobs/red-hat-storage/rook/red-hat-storage-rook-release-4.6-presubmits.yaml
  ci-operator/jobs/red-hat-storage/rook/red-hat-storage-rook-release-4.7-presubmits.yaml
  ci-operator/jobs/red-hat-storage/rook/red-hat-storage-rook-release-4.8-presubmits.yaml
  core-services/prow/02_config/red-hat-storage/rook/_pluginconfig.yaml
  core-services/prow/02_config/red-hat-storage/rook/_prowconfig.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: lgtm, approved, tide/merge-method-squash

#22516 Add coreydaley as z-stream approver
  core-services/prow/02_config/openshift/builder/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-openshift-controller-manager-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/csi-driver-shared-resource-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/csi-driver-shared-resource/_pluginconfig.yaml
  core-services/prow/02_config/openshift/jenkins-client-plugin/_pluginconfig.yaml
  core-services/prow/02_config/openshift/jenkins-openshift-login-plugin/_pluginconfig.yaml
  core-services/prow/02_config/openshift/jenkins-plugin/_pluginconfig.yaml
  core-services/prow/02_config/openshift/jenkins-sync-plugin/_pluginconfig.yaml
  core-services/prow/02_config/openshift/jenkins/_pluginconfig.yaml
  core-services/prow/02_config/openshift/openshift-controller-manager/_pluginconfig.yaml
  core-services/prow/02_config/openshift/source-to-image/_pluginconfig.yaml
Labels: lgtm, approved

#22517 OCM: Increase claim timeout
  ci-operator/config/open-cluster-management/application-ui/open-cluster-management-application-ui-main.yaml
  ci-operator/step-registry/ocm/e2e/clusterpool/checkout/ocm-e2e-clusterpool-checkout-ref.yaml
Labels: lgtm, approved

#22477 crio: bump jobs on main to base on 4.10
  ci-operator/config/cri-o/cri-o/cri-o-cri-o-main.yaml
Labels: lgtm, approved

#22523 Use 'main' branch for assisted-image-service plugins
  core-services/prow/02_config/openshift/assisted-image-service/_pluginconfig.yaml
Labels: lgtm, approved

#22520 ocm : updated sonar creds for search-collector
  ci-operator/config/open-cluster-management/search-collector/open-cluster-management-search-collector-main.yaml
  ci-operator/jobs/open-cluster-management/search-collector/open-cluster-management-search-collector-main-postsubmits.yaml
Labels: lgtm, approved

#22340 Bump Eventing core to 0.25.1 release
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.25__47.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.25__48.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.25__49.yaml
Labels: lgtm, approved

#22510 assisted: allow MODIFIED, ON_QE before code freeze
  core-services/prow/02_config/openshift/assisted-image-service/_pluginconfig.yaml
  core-services/prow/02_config/openshift/assisted-installer-agent/_pluginconfig.yaml
  core-services/prow/02_config/openshift/assisted-installer/_pluginconfig.yaml
  core-services/prow/02_config/openshift/assisted-service/_pluginconfig.yaml
Labels: lgtm, approved

#22533 change the images to 0.25.1 manually for eventing
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main__4.6.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main__4.7.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main__4.8-aws-ovn.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main__4.8-azure.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main__4.8-gcp.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main__4.8-vsphere.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main__4.8.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main__4.9.yaml
Labels: lgtm, approved

#22537 Allow monitoring users to use `backport-risk-assessed`
  core-services/prow/02_config/openshift/cluster-monitoring-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/configmap-reload/_pluginconfig.yaml
  core-services/prow/02_config/openshift/grafana/_pluginconfig.yaml
  core-services/prow/02_config/openshift/k8s-prometheus-adapter/_pluginconfig.yaml
  core-services/prow/02_config/openshift/kube-state-metrics/_pluginconfig.yaml
  core-services/prow/02_config/openshift/node_exporter/_pluginconfig.yaml
  core-services/prow/02_config/openshift/openshift-state-metrics/_pluginconfig.yaml
  core-services/prow/02_config/openshift/procfs/_pluginconfig.yaml
  core-services/prow/02_config/openshift/prom-label-proxy/_pluginconfig.yaml
  core-services/prow/02_config/openshift/prometheus-alertmanager/_pluginconfig.yaml
  core-services/prow/02_config/openshift/prometheus-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/prometheus/_pluginconfig.yaml
  core-services/prow/02_config/openshift/telemeter/_pluginconfig.yaml
  core-services/prow/02_config/openshift/thanos/_pluginconfig.yaml
Labels: lgtm, approved

#22473 [CVP-2414] Add timeout for catalogsource creation
  ci-operator/step-registry/optional-operators/TROUBLESHOOTING.md
  ci-operator/step-registry/optional-operators/subscribe/optional-operators-subscribe-commands.sh
Labels: lgtm, approved

#22550 ci-chat-bot: Add aravindhp to admin_rbac list
  clusters/app.ci/ci-chat-bot/admin_rbac.yaml
Labels: lgtm, approved

#22557 kubevirt: stop using IMAGE_FORMAT for must-gather
  ci-operator/config/kubevirt/must-gather/kubevirt-must-gather-main.yaml
Labels: lgtm, approved

#22549 NFD: Designate z-stream approvers
  core-services/prow/02_config/openshift/cluster-nfd-operator/_pluginconfig.yaml
Labels: lgtm, approved

#22566 ocm: add upstream generator repo
  core-services/prow/02_config/open-cluster-management-io/ocm-kustomize-generator-plugins/OWNERS
  core-services/prow/02_config/open-cluster-management-io/ocm-kustomize-generator-plugins/_pluginconfig.yaml
  core-services/prow/02_config/open-cluster-management-io/ocm-kustomize-generator-plugins/_prowconfig.yaml
Labels: lgtm, approved

#22502 Prevent failing when skipping test not exist in TEST_SKIPS
  ci-operator/step-registry/baremetalds/e2e/test/baremetalds-e2e-test-commands.sh
Labels: lgtm, approved

#22593 Add automatic merge configuration for openshift/image-customization-controller
  core-services/prow/02_config/openshift/image-customization-controller/_prowconfig.yaml
Labels: lgtm, approved

#22569 Cluster Infrastructure: Add backport approvers
  core-services/prow/02_config/openshift/cloud-provider-alibaba-cloud/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cloud-provider-aws/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cloud-provider-azure/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cloud-provider-gcp/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cloud-provider-ibm/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cloud-provider-vpc-controller/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cloud-provider-vsphere/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-api-actuator-pkg/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-api-provider-alibaba/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-api-provider-aws/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-api-provider-azure/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-api-provider-gcp/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-api-provider-ibmcloud/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-api/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-autoscaler-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-cloud-controller-manager-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-machine-approver/_pluginconfig.yaml
  core-services/prow/02_config/openshift/kubernetes-autoscaler/_pluginconfig.yaml
  core-services/prow/02_config/openshift/machine-api-operator/_pluginconfig.yaml
Labels: lgtm, approved

#22564 Allow Net Edge to set the backport-risk-assessed label
  core-services/prow/02_config/openshift/cluster-dns-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-ingress-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/contour-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/contour/_pluginconfig.yaml
  core-services/prow/02_config/openshift/coredns/_pluginconfig.yaml
  core-services/prow/02_config/openshift/external-dns-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/external-dns/_pluginconfig.yaml
  core-services/prow/02_config/openshift/images/_pluginconfig.yaml
  core-services/prow/02_config/openshift/router/_pluginconfig.yaml
Labels: lgtm, approved

#22524 Upgrade go version for cluster-logging-operator from the 1.14 to the 1.16
  ci-operator/config/openshift/cluster-logging-operator/openshift-cluster-logging-operator-master.yaml
Labels: lgtm, approved

#22339 Add GCP CCM jobs for CCCMO
  ci-operator/config/openshift/cluster-cloud-controller-manager-operator/openshift-cluster-cloud-controller-manager-operator-master.yaml
  ci-operator/jobs/openshift/cluster-cloud-controller-manager-operator/openshift-cluster-cloud-controller-manager-operator-master-presubmits.yaml
  ci-operator/step-registry/openshift/e2e/gcp/ccm/OWNERS
  ci-operator/step-registry/openshift/e2e/gcp/ccm/install/OWNERS
  ci-operator/step-registry/openshift/e2e/gcp/ccm/install/openshift-e2e-gcp-ccm-install-workflow.metadata.json
  ci-operator/step-registry/openshift/e2e/gcp/ccm/install/openshift-e2e-gcp-ccm-install-workflow.yaml
  ci-operator/step-registry/openshift/e2e/gcp/ccm/openshift-e2e-gcp-ccm-workflow.metadata.json
  ci-operator/step-registry/openshift/e2e/gcp/ccm/openshift-e2e-gcp-ccm-workflow.yaml
Labels: lgtm, approved

#22605 Add z-stream-approver for cluster version operator
  core-services/prow/02_config/openshift/cluster-version-operator/_pluginconfig.yaml
Labels: lgtm, approved

#22462 Add z-stream approvers for all baremetal repos
  core-services/prow/02_config/openshift/baremetal-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-api-provider-baremetal/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-baremetal-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/ironic-agent-image/_pluginconfig.yaml
  core-services/prow/02_config/openshift/ironic-hardware-inventory-recorder-image/_pluginconfig.yaml
  core-services/prow/02_config/openshift/ironic-image/_pluginconfig.yaml
  core-services/prow/02_config/openshift/ironic-inspector-image/_pluginconfig.yaml
  core-services/prow/02_config/openshift/ironic-ipa-downloader/_pluginconfig.yaml
  core-services/prow/02_config/openshift/ironic-rhcos-downloader/_pluginconfig.yaml
  core-services/prow/02_config/openshift/ironic-static-ip-manager/_pluginconfig.yaml
Labels: lgtm, approved

#22613 add missing component name
  ci-operator/config/open-cluster-management/governance-policy-framework/open-cluster-management-governance-policy-framework-release-2.4.yaml
Labels: lgtm, approved

#22561 openshift-e2e-ovirt-clusterbot: hardcode sleep duration
  ci-operator/step-registry/openshift/e2e/ovirt/clusterbot/openshift-e2e-ovirt-clusterbot-workflow.yaml
Labels: lgtm, approved

#22615 Rename to add QE's e2e tests into testgrid
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__ocp-4.10.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__ocp-4.9.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
Labels: lgtm, approved

#21564 Annotate monitoring PVCs for deletion before running the upgrade tests
  ci-operator/step-registry/ipi/install/monitoringpvc-annotate/OWNERS
  ci-operator/step-registry/ipi/install/monitoringpvc-annotate/ipi-install-monitoringpvc-annotate-commands.sh
  ci-operator/step-registry/ipi/install/monitoringpvc-annotate/ipi-install-monitoringpvc-annotate-ref.metadata.json
  ci-operator/step-registry/ipi/install/monitoringpvc-annotate/ipi-install-monitoringpvc-annotate-ref.yaml
  ci-operator/step-registry/openshift/upgrade/aws/latestinstaller/openshift-upgrade-aws-latestinstaller-workflow.yaml
  ci-operator/step-registry/openshift/upgrade/aws/openshift-upgrade-aws-workflow.yaml
  ci-operator/step-registry/openshift/upgrade/aws/ovn/openshift-upgrade-aws-ovn-workflow.yaml
  ci-operator/step-registry/openshift/upgrade/aws/pausedworkers/openshift-upgrade-aws-pausedworkers-workflow.yaml
  ci-operator/step-registry/openshift/upgrade/azure/openshift-upgrade-azure-workflow.yaml
  ci-operator/step-registry/openshift/upgrade/azure/ovn/openshift-upgrade-azure-ovn-workflow.yaml
  ci-operator/step-registry/openshift/upgrade/gcp/latestinstaller/openshift-upgrade-gcp-latestinstaller-workflow.yaml
  ci-operator/step-registry/openshift/upgrade/gcp/openshift-upgrade-gcp-workflow.yaml
  ci-operator/step-registry/openshift/upgrade/gcp/ovn/openshift-upgrade-gcp-ovn-workflow.yaml
  ci-operator/step-registry/openshift/upgrade/openstack/loki/openshift-upgrade-openstack-loki-workflow.yaml
  ci-operator/step-registry/openshift/upgrade/ovirt/openshift-upgrade-ovirt-workflow.yaml
  ci-operator/step-registry/openshift/upgrade/vsphere/openshift-upgrade-vsphere-workflow.yaml
Labels: lgtm, approved

#22600 Azure Stack: Add Support for Internal LB
  ci-operator/step-registry/upi/install/azurestack/upi-install-azurestack-commands.sh
Labels: lgtm, approved

#22616 Add QE's e2e tests to testgrid for informing
  core-services/testgrid-config-generator/_allow-list.yaml
Labels: lgtm, approved

#22641 Renamed secret to a unique value for RHODA
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: lgtm, approved, ok-to-test

#22595 add z-stream approvers for openshift/os
  core-services/prow/02_config/openshift/os/_pluginconfig.yaml
Labels: lgtm, approved

#22648 mco add allowed users for label cherry-pick-approved
  core-services/prow/02_config/openshift/machine-config-operator/_pluginconfig.yaml
Labels: lgtm, approved

#22652 Add tide config for MAPO
  core-services/prow/02_config/openshift/machine-api-provider-openstack/_prowconfig.yaml
Labels: lgtm, approved

#22660 tag the image with name `grc-policy-framework-tests`
  ci-operator/config/open-cluster-management/governance-policy-framework/open-cluster-management-governance-policy-framework-main.yaml
  ci-operator/config/open-cluster-management/governance-policy-framework/open-cluster-management-governance-policy-framework-release-2.4.yaml
Labels: lgtm, approved

#22432 Add CentOS 8 Stream-based OKD 4.10 ironic image builds
  ci-operator/config/openshift/ironic-agent-image/openshift-ironic-agent-image-main__okd.yaml
  ci-operator/config/openshift/ironic-agent-image/openshift-ironic-agent-image-release-4.10__okd.yaml
  ci-operator/config/openshift/ironic-image/openshift-ironic-image-master__okd.yaml
  ci-operator/config/openshift/ironic-image/openshift-ironic-image-release-4.10__okd.yaml
  ci-operator/config/openshift/ironic-ipa-downloader/openshift-ironic-ipa-downloader-master__okd.yaml
  ci-operator/config/openshift/ironic-ipa-downloader/openshift-ironic-ipa-downloader-release-4.10__okd.yaml
  ci-operator/config/openshift/ironic-rhcos-downloader/openshift-ironic-rhcos-downloader-master__okd.yaml
  ci-operator/config/openshift/ironic-rhcos-downloader/openshift-ironic-rhcos-downloader-release-4.10__okd.yaml
  ci-operator/config/openshift/ironic-static-ip-manager/openshift-ironic-static-ip-manager-master__okd.yaml
  ci-operator/config/openshift/ironic-static-ip-manager/openshift-ironic-static-ip-manager-release-4.10__okd.yaml
  ci-operator/jobs/openshift/ironic-agent-image/openshift-ironic-agent-image-main-postsubmits.yaml
  ci-operator/jobs/openshift/ironic-agent-image/openshift-ironic-agent-image-main-presubmits.yaml
  ci-operator/jobs/openshift/ironic-agent-image/openshift-ironic-agent-image-release-4.10-postsubmits.yaml
  ci-operator/jobs/openshift/ironic-agent-image/openshift-ironic-agent-image-release-4.10-presubmits.yaml
  ci-operator/jobs/openshift/ironic-image/openshift-ironic-image-master-postsubmits.yaml
  ci-operator/jobs/openshift/ironic-image/openshift-ironic-image-master-presubmits.yaml
  ci-operator/jobs/openshift/ironic-image/openshift-ironic-image-release-4.10-postsubmits.yaml
  ci-operator/jobs/openshift/ironic-image/openshift-ironic-image-release-4.10-presubmits.yaml
  ci-operator/jobs/openshift/ironic-ipa-downloader/openshift-ironic-ipa-downloader-master-postsubmits.yaml
  ci-operator/jobs/openshift/ironic-ipa-downloader/openshift-ironic-ipa-downloader-master-presubmits.yaml
  ci-operator/jobs/openshift/ironic-ipa-downloader/openshift-ironic-ipa-downloader-release-4.10-postsubmits.yaml
  ci-operator/jobs/openshift/ironic-ipa-downloader/openshift-ironic-ipa-downloader-release-4.10-presubmits.yaml
  ci-operator/jobs/openshift/ironic-rhcos-downloader/openshift-ironic-rhcos-downloader-master-postsubmits.yaml
  ci-operator/jobs/openshift/ironic-rhcos-downloader/openshift-ironic-rhcos-downloader-master-presubmits.yaml
  ci-operator/jobs/openshift/ironic-rhcos-downloader/openshift-ironic-rhcos-downloader-release-4.10-postsubmits.yaml
  ci-operator/jobs/openshift/ironic-rhcos-downloader/openshift-ironic-rhcos-downloader-release-4.10-presubmits.yaml
  ci-operator/jobs/openshift/ironic-static-ip-manager/openshift-ironic-static-ip-manager-master-postsubmits.yaml
  ci-operator/jobs/openshift/ironic-static-ip-manager/openshift-ironic-static-ip-manager-master-presubmits.yaml
  ci-operator/jobs/openshift/ironic-static-ip-manager/openshift-ironic-static-ip-manager-release-4.10-postsubmits.yaml
  ci-operator/jobs/openshift/ironic-static-ip-manager/openshift-ironic-static-ip-manager-release-4.10-presubmits.yaml
  core-services/image-mirroring/openshift/mapping_origin_4_10
  core-services/release-controller/_releases/release-ocp-4.10-ci.json
Labels: lgtm, approved

#22668 release: add config-type label to ci-chat-bot jobs
  ci-operator/jobs/openshift/release/openshift-release-infra-periodics.yaml
Labels: lgtm, approved

#22630 Add the requestion backport label configuration for CNF projects
  core-services/prow/02_config/openshift/linuxptp-daemon/_pluginconfig.yaml
  core-services/prow/02_config/openshift/metallb-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/metallb/_pluginconfig.yaml
  core-services/prow/02_config/openshift/ptp-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/sriov-cni/_pluginconfig.yaml
  core-services/prow/02_config/openshift/sriov-dp-admission-controller/_pluginconfig.yaml
  core-services/prow/02_config/openshift/sriov-network-device-plugin/_pluginconfig.yaml
  core-services/prow/02_config/openshift/sriov-network-operator/_pluginconfig.yaml
Labels: lgtm, approved

#22683 Replace ocs-converged-dev configs with ocs-converged-qe configs for osde2e job
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: lgtm, approved

#22690 MGMT-7927 - Set assisted_service ocm_2.3 and ocm_2.4 work with proper test_infra branch
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-ocm-2.3.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.4.yaml
Labels: lgtm, approved

#22704 Addng SRC image for the components
  core-services/image-mirroring/knative/mapping_knative_v0_25_quay
Labels: lgtm, approved

#22693 Add z-strem-approver for descheduler repo
  core-services/prow/02_config/openshift/descheduler/_pluginconfig.yaml
Labels: lgtm, approved

#22701 ci-operator: hypershift: redirect remote write metrics
  ci-operator/config/openshift/hypershift/openshift-hypershift-main.yaml
Labels: lgtm, approved

#22674 Add driver-toolkit z-stream approvers
  core-services/prow/02_config/openshift/driver-toolkit/_pluginconfig.yaml
Labels: lgtm, approved

#22291 Add cucushift tests for gcp-upi
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__ocp-4.9.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
  ci-operator/step-registry/cucushift/gcp/upi/OWNERS
  ci-operator/step-registry/cucushift/gcp/upi/cucushift-gcp-upi-commands.sh
  ci-operator/step-registry/cucushift/gcp/upi/cucushift-gcp-upi-ref.metadata.json
  ci-operator/step-registry/cucushift/gcp/upi/cucushift-gcp-upi-ref.yaml
  ci-operator/step-registry/cucushift/gcp/upi/cucushift-gcp-upi-workflow.metadata.json
  ci-operator/step-registry/cucushift/gcp/upi/cucushift-gcp-upi-workflow.yaml
Labels: lgtm, approved

#22671 Migrate removed betav1 objects in future releases
  cluster/ci/config/metrics-server.yaml
  clusters/app.ci/grafana-loki/admin_grafana.yaml
  clusters/app.ci/hypershift-toolkit/rbac.yaml
  clusters/app.ci/okd/admin_okd.yaml
  clusters/app.ci/supplemental-ci-images/cincinnati-ci/admin_rbac.yaml
  clusters/build-clusters/01_cluster/sshd-bastion/coredns/admin_owners_rbac.yaml
  clusters/build-clusters/01_cluster/sshd-bastion/coredns/admin_rbac.yaml
  clusters/build-clusters/01_cluster/sshd-bastion/ppc64le-libvirt/admin_owners_rbac.yaml
  clusters/build-clusters/01_cluster/sshd-bastion/ppc64le-libvirt/admin_rbac.yaml
  clusters/build-clusters/01_cluster/sshd-bastion/ppc64le/admin_owners_rbac.yaml
  clusters/build-clusters/01_cluster/sshd-bastion/ppc64le/admin_rbac.yaml
  clusters/build-clusters/01_cluster/sshd-bastion/telco/admin_owners_rbac.yaml
  clusters/build-clusters/01_cluster/sshd-bastion/telco/admin_rbac.yaml
  clusters/build-clusters/01_cluster/sshd-bastion/z/admin_owners_rbac.yaml
  clusters/build-clusters/01_cluster/sshd-bastion/z/admin_rbac.yaml
  clusters/build-clusters/common/assets/admin_dptp-controller-manager_rbac.yaml
  clusters/build-clusters/common/ci-ns-ttl-controller/admin_ci-ns-ttl-controller_rbac.yaml
Labels: lgtm, approved

#22727 mirroring our knative eventing 0.26 bits to quay.io
  core-services/image-mirroring/knative/mapping_knative_v0_26_quay
Labels: lgtm, approved

#22723 Add several cucushift tests into testgrid
  core-services/testgrid-config-generator/_allow-list.yaml
Labels: lgtm, approved

#22724 Revert "Add CPU limit for kubernetes-nmstate"
  ci-operator/config/openshift/kubernetes-nmstate/openshift-kubernetes-nmstate-master.yaml
  ci-operator/config/openshift/kubernetes-nmstate/openshift-kubernetes-nmstate-release-4.10.yaml
  ci-operator/config/openshift/kubernetes-nmstate/openshift-kubernetes-nmstate-release-4.5.yaml
  ci-operator/config/openshift/kubernetes-nmstate/openshift-kubernetes-nmstate-release-4.6.yaml
  ci-operator/config/openshift/kubernetes-nmstate/openshift-kubernetes-nmstate-release-4.7.yaml
  ci-operator/config/openshift/kubernetes-nmstate/openshift-kubernetes-nmstate-release-4.8.yaml
  ci-operator/config/openshift/kubernetes-nmstate/openshift-kubernetes-nmstate-release-4.9.yaml
Labels: lgtm, approved

#22730 Update the scorecard container to v4
  clusters/app.ci/supplemental-ci-images/cvp-operator-scorecard.yaml
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_ci
Labels: lgtm, approved, ok-to-test

#22740 Add new step registry step to update the OCM manifest for Assisted Installer
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.4.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.4.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.4.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.4.yaml
  ci-operator/step-registry/ocm/ci/manifest-update/OWNERS
  ci-operator/step-registry/ocm/ci/manifest-update/ocm-ci-manifest-update-commands.sh
  ci-operator/step-registry/ocm/ci/manifest-update/ocm-ci-manifest-update-ref.metadata.json
  ci-operator/step-registry/ocm/ci/manifest-update/ocm-ci-manifest-update-ref.yaml
  ci-operator/step-registry/ocm/ci/manifest-update/ocm-ci-manifest-update-workflow.metadata.json
  ci-operator/step-registry/ocm/ci/manifest-update/ocm-ci-manifest-update-workflow.yaml
Labels: lgtm, approved

#22745 scale down the boskos deployment to 1 replica
  clusters/app.ci/prow/03_deployment/boskos.yaml
Labels: lgtm, approved

#22737 Update the OCP cluster 4.7 to quay.io/openshift-release-dev/ocp-release:4.7.34-x86_64
  clusters/hive/pools/ocp-4.7.0-amd64_clusterimageset.yaml
Labels: lgtm, approved

#22655 Add e2e-openstack job to MAPO
  ci-operator/config/openshift/machine-api-provider-openstack/openshift-machine-api-provider-openstack-master.yaml
  ci-operator/jobs/openshift/machine-api-provider-openstack/openshift-machine-api-provider-openstack-master-presubmits.yaml
Labels: lgtm, approved

#22751 Add e2e-aws to cluster-capi-operator
  ci-operator/config/openshift/cluster-capi-operator/openshift-cluster-capi-operator-main.yaml
  ci-operator/jobs/openshift/cluster-capi-operator/openshift-cluster-capi-operator-main-presubmits.yaml
Labels: lgtm, approved

#22731 GPU Operator: add more optional presubmit upgrade tests
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-master__4.7.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-master__4.8.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-master__4.9.yaml
  ci-operator/jobs/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-master-presubmits.yaml
Labels: lgtm, approved

#22767 [boskos] Add the boskos-leader label in service selector and add pod antiaffinity in deployment
  clusters/app.ci/prow/03_deployment/boskos.yaml
Labels: lgtm, approved

#22774 stackrox: fix the renamed yaml
  ci-operator/jobs/stackrox/rox-ci-image-openshift-ci-mirror/stackrox-rox-ci-image-openshift-ci-mirror-master-presubmits.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: lgtm, approved

#22664 Change CoreOS team permissions using an alias
  OWNERS_ALIASES
  ci-operator/config/coreos/coreos-assembler/OWNERS
  ci-operator/config/coreos/rpm-ostree/OWNERS
  ci-operator/jobs/coreos/coreos-assembler/OWNERS
  ci-operator/jobs/coreos/rpm-ostree/OWNERS
  clusters/app.ci/registry-access/rhcos-devel/OWNERS
  clusters/app.ci/registry-access/rhcos/OWNERS
  clusters/app.ci/supplemental-ci-images/coreos/OWNERS
  core-services/prow/02_config/coreos/coreos-assembler/OWNERS
  core-services/prow/02_config/coreos/rpm-ostree/OWNERS
Labels: lgtm, approved

#22776 Fix mco's plugin's configuration
  core-services/prow/02_config/openshift/machine-config-operator/_pluginconfig.yaml
Labels: lgtm, approved

#22779 release-controllers: use bearer auth method for release-controller
  clusters/app.ci/release-controller/deploy-ocp-arm64-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-arm64-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-ppc64le-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-ppc64le-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-s390x-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-s390x-priv-controller.yaml
  hack/generators/release-controllers/content/osd_rc_deployments.py
Labels: lgtm, approved

#22085 Additional test suites for ARM - Cluster sample operator and serial e2e
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.10.yaml
  ci-operator/jobs/openshift/multiarch/openshift-multiarch-master-periodics.yaml
Labels: lgtm, approved

#22780 Build cluster resource override v4.8 with go 1.16
  ci-operator/config/openshift-priv/cluster-resource-override-admission/openshift-priv-cluster-resource-override-admission-release-4.8.yaml
  ci-operator/config/openshift/cluster-resource-override-admission/openshift-cluster-resource-override-admission-release-4.8.yaml
Labels: lgtm, approved

#22783 stackrox: set to managed
  core-services/prow/02_config/stackrox/rox-ci-image-openshift-ci-mirror/_prowconfig.yaml
Labels: lgtm, approved

#22789 MGMT-7985 - Fix base ref of PRs to use the correct code of `assisted-test-infra`
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-ocm-2.3.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.4.yaml
Labels: lgtm, approved

#22722 Fix tests baremetal-cucushift-ipi
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__ocp-4.9.yaml
  ci-operator/step-registry/cucushift/baremetal/ipi/cucushift-baremetal-ipi-commands.sh
Labels: lgtm, approved

#22614 Report triage tickets status daily
  ci-operator/config/openshift-assisted/assisted-installer-deployment/openshift-assisted-assisted-installer-deployment-master.yaml
  ci-operator/jobs/openshift-assisted/assisted-installer-deployment/openshift-assisted-assisted-installer-deployment-master-periodics.yaml
  ci-operator/step-registry/baremetalds/assisted/tools/OWNERS
  ci-operator/step-registry/baremetalds/assisted/tools/report/OWNERS
  ci-operator/step-registry/baremetalds/assisted/tools/report/baremetalds-assisted-tools-report-commands.sh
  ci-operator/step-registry/baremetalds/assisted/tools/report/baremetalds-assisted-tools-report-ref.metadata.json
  ci-operator/step-registry/baremetalds/assisted/tools/report/baremetalds-assisted-tools-report-ref.yaml
Labels: lgtm, approved

#22728 test-platform: rename team in various configs
  core-services/prow/02_config/_bumper.yaml
  core-services/prow/02_config/openshift/ci-docs/_pluginconfig.yaml
  core-services/prow/02_config/openshift/ci-ns-ttl-controller/_pluginconfig.yaml
  core-services/prow/02_config/openshift/ci-tools/_pluginconfig.yaml
  core-services/prow/02_config/openshift/release-controller/_pluginconfig.yaml
  core-services/prow/02_config/openshift/release/_pluginconfig.yaml
  core-services/prow/02_config/redhat-openshift-ecosystem/release/_pluginconfig.yaml
Labels: lgtm, approved

#22715 Add allowed users for label cherry-pick-approved for nfd nto dtk sro
  core-services/prow/02_config/openshift/cluster-nfd-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-node-tuning-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/driver-toolkit/_pluginconfig.yaml
  core-services/prow/02_config/openshift/node-feature-discovery/_pluginconfig.yaml
  core-services/prow/02_config/openshift/special-resource-operator/_pluginconfig.yaml
Labels: lgtm, approved

#22810 Switch CodeReady Toolchain to OCP 4.9
  ci-operator/config/codeready-toolchain/api/codeready-toolchain-api-master.yaml
  ci-operator/config/codeready-toolchain/host-operator/codeready-toolchain-host-operator-master.yaml
  ci-operator/config/codeready-toolchain/member-operator/codeready-toolchain-member-operator-master.yaml
  ci-operator/config/codeready-toolchain/registration-service/codeready-toolchain-registration-service-master.yaml
  ci-operator/config/codeready-toolchain/toolchain-e2e/codeready-toolchain-toolchain-e2e-master.yaml
Labels: lgtm, approved

#22804 Stop applying cert-manager objects
  clusters/build-clusters/01_cluster/_cert-manager/README.md
  clusters/build-clusters/01_cluster/_cert-manager/apiserver-build01_certificate.yaml
  clusters/build-clusters/01_cluster/_cert-manager/apps-build01_certificate.yaml
  clusters/build-clusters/01_cluster/_cert-manager/cert-issuer-aws-staging_clusterissuer.yaml
  clusters/build-clusters/01_cluster/_cert-manager/cert-issuer-aws_clusterissuer.yaml
  clusters/build-clusters/01_cluster/_cert-manager/cert-issuer-staging_clusterissuer.yaml
  clusters/build-clusters/01_cluster/_cert-manager/cert-issuer_clusterissuer.yaml
  clusters/build-clusters/01_cluster/_cert-manager/cert-manager_deployment.yaml
  clusters/build-clusters/01_cluster/_cert-manager/console-build01_certificate.yaml
  clusters/build-clusters/01_cluster/_cert-manager/registry-build01_certificate.yaml
  clusters/build-clusters/01_cluster/_cert-manager/search_ingress.yaml
  clusters/build-clusters/02_cluster/_cert-manager/README.md
  clusters/build-clusters/02_cluster/_cert-manager/apiserver-build02_certificate.yaml
  clusters/build-clusters/02_cluster/_cert-manager/apps-build02_certificate.yaml
  clusters/build-clusters/02_cluster/_cert-manager/cert-issuer-ci-build-farm-staging_clusterissuer.yaml
  clusters/build-clusters/02_cluster/_cert-manager/cert-issuer-ci-build-farm_clusterissuer.yaml
  clusters/build-clusters/02_cluster/_cert-manager/cert-issuer-staging_clusterissuer.yaml
  clusters/build-clusters/02_cluster/_cert-manager/cert-issuer_clusterissuer.yaml
  clusters/build-clusters/02_cluster/_cert-manager/cert-manager_deployment.yaml
  clusters/build-clusters/02_cluster/_cert-manager/console-build02_certificate.yaml
  clusters/build-clusters/02_cluster/_cert-manager/registry-build02_certificate.yaml
  clusters/build-clusters/arm01/common_cert_manager
  clusters/build-clusters/common_cert_manager/_cert-manager.yaml
  clusters/build-clusters/common_cert_manager/_cert-manager_ns.yaml
Labels: lgtm, approved

#22811 Stop applying cert-manager objects on app.ci
  clusters/app.ci/_cert-manager/README.md
  clusters/app.ci/_cert-manager/cert-issuer-staging_clusterissuer.yaml
  clusters/app.ci/_cert-manager/cert-issuer_clusterissuer.yaml
  clusters/app.ci/_cert-manager/cert-manager_deployment.yaml
  clusters/app.ci/_cert-manager/console-app-ci_certificate.yaml
  clusters/app.ci/_cert-manager/grafana-loki_ingress.yaml
  clusters/app.ci/_cert-manager/prow_ingress.yaml
  clusters/app.ci/_cert-manager/registry-ci-openshift-org_certificate.yaml
  clusters/app.ci/_cert-manager/release-controller-priv_ingress.yaml
  clusters/app.ci/_cert-manager/release-controller_ingress.yaml
  clusters/app.ci/_cert-manager/rhcos-redirector_ingress.yaml
Labels: lgtm, approved

#22813 ci-operator/step-registry/ipi/install/monitoringpvc: Debugging config print
  ci-operator/step-registry/ipi/install/monitoringpvc/ipi-install-monitoringpvc-commands.sh
Labels: lgtm, approved

#22754 add cherry-pick approvers for console and console-operator
  core-services/prow/02_config/openshift/console-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/console/_pluginconfig.yaml
Labels: lgtm, approved

#22830 notify when triage status report job is failing
  ci-operator/jobs/openshift-assisted/assisted-installer-deployment/openshift-assisted-assisted-installer-deployment-master-periodics.yaml
Labels: lgtm, approved
