Repository openshift/release, pull requests merged in 2021-02, with the labels that each got.

#15294 [oVirt] port release jobs to workflows
  ci-operator/config/openshift/release/openshift-release-master__ocp-4.4.yaml
  ci-operator/config/openshift/release/openshift-release-master__ocp-4.5.yaml
  ci-operator/config/openshift/release/openshift-release-master__ocp-4.6.yaml
  ci-operator/config/openshift/release/openshift-release-master__ocp-4.7.yaml
  ci-operator/config/openshift/release/openshift-release-master__ocp-4.8.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  core-services/release-controller/_releases/priv/release-ocp-4.4.json
  core-services/release-controller/_releases/priv/release-ocp-4.5.json
  core-services/release-controller/_releases/priv/release-ocp-4.6.json
  core-services/release-controller/_releases/priv/release-ocp-4.7.json
  core-services/release-controller/_releases/priv/release-ocp-4.8.json
  core-services/release-controller/_releases/release-ocp-4.4.json
  core-services/release-controller/_releases/release-ocp-4.5.json
  core-services/release-controller/_releases/release-ocp-4.6.json
  core-services/release-controller/_releases/release-ocp-4.7.json
  core-services/release-controller/_releases/release-ocp-4.8.json
Labels: approved, lgtm

#14959 Add e2e-metal-assisted workflow to openshift/assisted-installer
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-master.yaml
  ci-operator/config/openshift/release/openshift-release-master__ocp-4.6.yaml
  ci-operator/config/openshift/release/openshift-release-master__ocp-4.7.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-master-presubmits.yaml
  ci-operator/step-registry/baremetalds/assisted/setup/baremetalds-assisted-setup-commands.sh
  ci-operator/step-registry/baremetalds/assisted/setup/baremetalds-assisted-setup-ref.yaml
Labels: approved, lgtm

#15397 kubevirt: ssp: Same names of tests between branches
  ci-operator/config/kubevirt/ssp-operator/kubevirt-ssp-operator-release-v0.1.yaml
  ci-operator/jobs/kubevirt/ssp-operator/kubevirt-ssp-operator-release-v0.1-presubmits.yaml
Labels: approved, lgtm

#15403 Revert "Remove the deployment of ci-rpms on api.ci"
  core-services/ci-rpms/README.md
  core-services/ci-rpms/admin_01_ns.yaml
  core-services/ci-rpms/artifacts-master.yaml
  core-services/ci-rpms/artifacts-release-3.11.yaml
  core-services/ci-rpms/artifacts-release-4.1.yaml
  core-services/ci-rpms/artifacts-release-4.2.yaml
  core-services/ci-rpms/artifacts-rpms.yaml
Labels: approved, lgtm

#15404 cluster-network-operator: fix 4.6 ovn gcp upgrades
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.6.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.6-periodics.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.6-presubmits.yaml
Labels: approved, lgtm

#15412 Ensure o[-priv]/kubernetes prow conf can be automatically updated
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#15415 Update o/origin to follow standard process for all branches
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#15413 Put artifacts-release-4.0.yaml into git-ops
  clusters/app.ci/ci-rpms/artifacts-release-4.0.yaml
  core-services/ci-rpms/artifacts-release-4.0.yaml
Labels: approved, lgtm

#15419 Remove the host on 4.0 ci-rpms' route on app.ci
  clusters/app.ci/ci-rpms/artifacts-release-4.0.yaml
Labels: approved, lgtm

#15000 Use the ci-rpms' routes on app.ci
  clusters/app.ci/ci-rpms/artifacts-rpms.yaml
Labels: approved, lgtm

#15421 Adding secret for the Azure Arc Conformance suite blob step
  core-services/secrets/arcconformance-secrets/OWNERS
  core-services/secrets/arcconformance-secrets/arcconformance-secrets.yaml
Labels: approved, lgtm

#15416 Remove JUNIT parameter from compliance operator
  ci-operator/config/openshift/compliance-operator/openshift-compliance-operator-master.yaml
  ci-operator/config/openshift/compliance-operator/openshift-compliance-operator-release-4.6.yaml
Labels: approved, lgtm

#15423 config/openshift-ansible: Fix tox redirect
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-master.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-3.11.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-4.1.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-4.2.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-4.3.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-4.4.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-4.5.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-4.6.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-4.7.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-4.8.yaml
Labels: approved, lgtm

#15427 Correctly deploy secret-namespace-manager to api.ci, not app.ci
  clusters/app.ci/assets/secrets-manager-role.yaml
  core-services/secrets/rbac.yaml
Labels: approved, lgtm

#15401 Add priority to prevalidation repos for prevalidation jobs for ironic
  ci-operator/config/openshift/ironic-image/openshift-ironic-image-master__prevalidation.yaml
  ci-operator/config/openshift/ironic-image/openshift-ironic-image-release-4.6__prevalidation.yaml
  ci-operator/config/openshift/ironic-inspector-image/openshift-ironic-inspector-image-master__prevalidation.yaml
  ci-operator/config/openshift/ironic-inspector-image/openshift-ironic-inspector-image-release-4.6__prevalidation.yaml
  ci-operator/config/openshift/ironic-ipa-downloader/openshift-ironic-ipa-downloader-master__prevalidation.yaml
  ci-operator/config/openshift/ironic-ipa-downloader/openshift-ironic-ipa-downloader-release-4.6__prevalidation.yaml
Labels: approved, lgtm

#15431 Add probing for ci-rpms endpoints
  clusters/app.ci/prow-monitoring/additional-scrape-configs_secret.yaml
Labels: approved, lgtm

#15432 Fix artifact dir for o/api@release-4.5
  ci-operator/config/openshift/api/openshift-api-release-4.5.yaml
Labels: approved, lgtm

#15433 Expose Azure Arc Conformance secrets to steps
  core-services/secret-mirroring/_mapping.yaml
Labels: approved, lgtm

#15430 ci-rpms: redirect to the deployment on app.ci
  core-services/ci-rpms/artifacts-master.yaml
  core-services/ci-rpms/artifacts-release-3.11.yaml
  core-services/ci-rpms/artifacts-release-4.0.yaml
  core-services/ci-rpms/artifacts-release-4.1.yaml
  core-services/ci-rpms/artifacts-release-4.2.yaml
  core-services/ci-rpms/artifacts-rpms.yaml
Labels: approved, lgtm

#15426 openshift/assisted-installer: require image build success
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-master-presubmits.yaml
Labels: approved, lgtm

#15288 Fix make target calls
  ci-operator/config/openshift-cnv/cnv-ci/openshift-cnv-cnv-ci-master__4.6.yaml
  ci-operator/config/openshift-cnv/cnv-ci/openshift-cnv-cnv-ci-master__4.7.yaml
  ci-operator/config/openshift-cnv/cnv-ci/openshift-cnv-cnv-ci-release-4.6.yaml
  ci-operator/config/openshift-cnv/cnv-ci/openshift-cnv-cnv-ci-release-4.7.yaml
  ci-operator/jobs/openshift-cnv/cnv-ci/openshift-cnv-cnv-ci-master-presubmits.yaml
Labels: approved, lgtm

#15441 [oVirt] fix ovirt tests step
  ci-operator/step-registry/openshift/e2e/ovirt/minimal/test/openshift-e2e-ovirt-minimal-test-commands.sh
Labels: approved, lgtm

#15444 Mirror Knative Serving 0.20 images to Quay
  core-services/image-mirroring/knative/mapping_knative_v0_20_quay
Labels: approved, lgtm

#15398 [DPTP-1737] Migrate openshift-console release-* e2e tests to multi-stage
  ci-operator/config/openshift/console/openshift-console-release-4.1.yaml
  ci-operator/config/openshift/console/openshift-console-release-4.2.yaml
  ci-operator/config/openshift/console/openshift-console-release-4.3.yaml
  ci-operator/config/openshift/console/openshift-console-release-4.4.yaml
  ci-operator/config/openshift/console/openshift-console-release-4.5.yaml
  ci-operator/config/openshift/console/openshift-console-release-4.6.yaml
  ci-operator/jobs/openshift/console/openshift-console-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/console/openshift-console-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/console/openshift-console-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/console/openshift-console-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/console/openshift-console-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift/console/openshift-console-release-4.6-presubmits.yaml
Labels: approved, lgtm

#13887 Add open-cluster-management website
  ci-operator/config/open-cluster-management/website/OWNERS
  ci-operator/config/open-cluster-management/website/open-cluster-management-website-main.yaml
  ci-operator/jobs/open-cluster-management/website/OWNERS
  ci-operator/jobs/open-cluster-management/website/open-cluster-management-website-main-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/website/open-cluster-management-website-main-presubmits.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#15448 Turn on baremetalds-assisted-gather with best_effort and optional_on_success
  ci-operator/step-registry/baremetalds/assisted/baremetalds-assisted-workflow.yaml
  ci-operator/step-registry/baremetalds/assisted/gather/baremetalds-assisted-gather-ref.yaml
Labels: approved, lgtm

#14543 Add e2e-metal-assisted-ipv6 test to assisted-test-infra
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-presubmits.yaml
Labels: approved, lgtm

#15400 oVirt remove release template jobs
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.6-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.8-periodics.yaml
  core-services/release-controller/_releases/priv/release-ocp-4.4.json
  core-services/release-controller/_releases/release-ocp-4.4.json
  core-services/testgrid-config-generator/_allow-list.yaml
Labels: approved, lgtm

#15365 Expose osd-ephemeral cluster_profile secret
  core-services/ci-secret-bootstrap/_config.yaml
Labels: approved

#15442 Add base image stream to assisted-service conf
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
Labels: approved, lgtm

#15458 Rename integration to e2e re:PR#1855 in code-ready/crc
  ci-operator/step-registry/openshift/e2e/gcp/crc/test/openshift-e2e-gcp-crc-test-commands.sh
Labels: approved, lgtm, ok-to-test

#15468 cluster-config-operator: bump golang version to 1.15
  ci-operator/config/openshift/cluster-config-operator/openshift-cluster-config-operator-master.yaml
  ci-operator/config/openshift/cluster-config-operator/openshift-cluster-config-operator-release-4.7.yaml
  ci-operator/config/openshift/cluster-config-operator/openshift-cluster-config-operator-release-4.8.yaml
Labels: approved, lgtm

#15452 labels: set *-approved on all openshift repos
  core-services/prow/02_config/_labels.yaml
Labels: approved, lgtm

#15473 core-services/prow/02_config/_config: Drop redundant okd-machine-os Tide query
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#15460 disable mastervertical scale tests
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: approved, lgtm

#15485 Change package name of HCO to 'community-kubevirt-hyperconverged'.
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-master.yaml
Labels: approved, lgtm

#15482 ComplianceAsCode: Set up CI for ocp4's e8 profile
  ci-operator/config/ComplianceAsCode/content/ComplianceAsCode-content-master.yaml
  ci-operator/jobs/ComplianceAsCode/content/ComplianceAsCode-content-master-presubmits.yaml
Labels: approved, lgtm

#15163 Add a new lane that validates the ran profile
  ci-operator/config/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-master.yaml
  ci-operator/jobs/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-master-presubmits.yaml
Labels: approved, lgtm

#15474 core-services/prow/02_config/_config: Drop redundant openshift/config Tide query
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#15476 core-services/prow/02_config/_config: Drop redundant openshift/console Tide query
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#15489 Rename integration to e2e for code-ready PR checks
  ci-operator/step-registry/code-ready/crc/e2e/test/code-ready-crc-e2e-test-commands.sh
Labels: approved, lgtm, ok-to-test

#15354 Build image: ci-tools/prow-job-dispatcher
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
Labels: approved, lgtm

#15328 config/ci-artifacts/release-next: add presubmits hook to run gpu-operator-e2e tests on demand
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-release-next.yaml
  ci-operator/jobs/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-release-next-presubmits.yaml
Labels: approved, lgtm

#15493 Change integration to e2e in a fixed path
  ci-operator/step-registry/gather/crc/gather-crc-commands.sh
Labels: approved, lgtm, ok-to-test

#13684 Adds prow config for AWS Account Operator
  ci-operator/config/openshift/aws-account-operator/openshift-aws-account-operator-master.yaml
  ci-operator/jobs/openshift/aws-account-operator/openshift-aws-account-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/aws-account-operator/openshift-aws-account-operator-master-presubmits.yaml
Labels: approved, lgtm

#15465 vsphere - Reverting PR 15367 due to lease timeouts
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: approved, lgtm

#15477 SDCICD-574: Add channel option to osde2e upgrade jobs
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: approved, lgtm

#15455 core-services/testgrid-config-generator: Add 4.7 workers-rhel7
  core-services/testgrid-config-generator/_allow-list.yaml
Labels: approved, lgtm

#15315 4.7 hotfix for failing HCO tests
  ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml
Labels: approved, lgtm

#15377 Run CLO logforwarding es managed test only in EO
  ci-operator/config/openshift/elasticsearch-operator/openshift-elasticsearch-operator-master.yaml
  ci-operator/config/openshift/elasticsearch-operator/openshift-elasticsearch-operator-release-4.5.yaml
  ci-operator/config/openshift/elasticsearch-operator/openshift-elasticsearch-operator-release-4.6.yaml
  ci-operator/config/openshift/elasticsearch-proxy/openshift-elasticsearch-proxy-master.yaml
  ci-operator/config/openshift/elasticsearch-proxy/openshift-elasticsearch-proxy-release-4.5.yaml
  ci-operator/config/openshift/elasticsearch-proxy/openshift-elasticsearch-proxy-release-4.6.yaml
Labels: approved, lgtm

#15498 image-mirror: Regen image mappings
  core-services/image-mirroring/openshift/mapping_origin_4_6
  core-services/image-mirroring/openshift/mapping_origin_4_7
  core-services/image-mirroring/openshift/mapping_origin_4_8
Labels: approved, lgtm

#15499 Add config to allow janoszen to read pjs
  clusters/app.ci/assets/janoszen-pj-reader.yaml
Labels: approved, lgtm

#15502 Imports html-proofer and hugo images
  clusters/app.ci/supplemental-ci-images/README.md
  clusters/app.ci/supplemental-ci-images/html-proofer_is.yaml
  clusters/app.ci/supplemental-ci-images/hugo_is.yaml
Labels: approved, lgtm

#15506 dptp-cm: disable registry_syncer
  clusters/app.ci/assets/dptp-controller-manager.yaml
Labels: approved, lgtm

#15226 pin pip to less than 21, which dropped support for python2
  ci-operator/step-registry/ipi/conf/vsphere/dns/ipi-conf-vsphere-dns-commands.sh
  ci-operator/step-registry/ipi/deprovision/vsphere/dns/ipi-deprovision-vsphere-dns-commands.sh
  ci-operator/templates/openshift/endurance/endurance-test.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-src.yaml
Labels: approved, lgtm

#15467 Add job/pull-ci-openshift-ci-docs-master-links
  ci-operator/config/openshift/ci-docs/openshift-ci-docs-master.yaml
  ci-operator/jobs/openshift/ci-docs/openshift-ci-docs-master-presubmits.yaml
Labels: approved, lgtm

#15507 ocm: clean up entries in _config.yaml and _plugins.yaml
  ci-operator/config/open-cluster-management/multicloud-operators-application/open-cluster-management-multicloud-operators-application-openshiftci.yaml
  ci-operator/jobs/open-cluster-management/multicloud-operators-application/open-cluster-management-multicloud-operators-application-openshiftci-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/multicloud-operators-application/open-cluster-management-multicloud-operators-application-openshiftci-presubmits.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#15183 releases: migrate e2e-gcp jobs to generated
  ci-operator/config/openshift/release/openshift-release-master__ocp-4.4.yaml
  ci-operator/config/openshift/release/openshift-release-master__ocp-4.5.yaml
  ci-operator/config/openshift/release/openshift-release-master__ocp-4.6.yaml
  ci-operator/config/openshift/release/openshift-release-master__origin-4.4.yaml
  ci-operator/config/openshift/release/openshift-release-master__origin-4.5.yaml
  ci-operator/config/openshift/release/openshift-release-master__origin-4.6.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.6-periodics.yaml
  core-services/release-controller/_releases/priv/release-ocp-4.4.json
  core-services/release-controller/_releases/priv/release-ocp-4.5.json
  core-services/release-controller/_releases/priv/release-ocp-4.6.json
  core-services/release-controller/_releases/release-ocp-4.4-ci.json
  core-services/release-controller/_releases/release-ocp-4.4.json
  core-services/release-controller/_releases/release-ocp-4.5-ci.json
  core-services/release-controller/_releases/release-ocp-4.5.json
  core-services/release-controller/_releases/release-ocp-4.6.json
  core-services/testgrid-config-generator/_allow-list.yaml
Labels: approved, lgtm

#15515 Revert "ocm: enable dco plugin for entire org"
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#15453 core-services/prow/02_config/_config.yaml: openshift-psap/ci-artifacts merge with rebase
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#15487 tide: enforce OCP merge criteria on o/elasticsearch-proxy
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#15488 tide: enforce OCP merge criteria on o/cluster-cloud-controller-manage…
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#14331 Add kubernetes-sigs/security-profiles-operator e2e test
  ci-operator/config/kubernetes-sigs/security-profiles-operator/OWNERS
  ci-operator/config/kubernetes-sigs/security-profiles-operator/kubernetes-sigs-security-profiles-operator-master.yaml
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/kubernetes-sigs/security-profiles-operator/OWNERS
  ci-operator/jobs/kubernetes-sigs/security-profiles-operator/kubernetes-sigs-security-profiles-operator-master-postsubmits.yaml
  ci-operator/jobs/kubernetes-sigs/security-profiles-operator/kubernetes-sigs-security-profiles-operator-master-presubmits.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#15461 rpm-ostree: Move more CI here
  ci-operator/config/coreos/rpm-ostree/coreos-rpm-ostree-master.yaml
  ci-operator/jobs/coreos/rpm-ostree/coreos-rpm-ostree-master-presubmits.yaml
Labels: approved, lgtm

#15532 Remove promotion section from k-sigs/security-profiles-operator
  ci-operator/config/kubernetes-sigs/security-profiles-operator/kubernetes-sigs-security-profiles-operator-master.yaml
  ci-operator/jobs/kubernetes-sigs/security-profiles-operator/kubernetes-sigs-security-profiles-operator-master-postsubmits.yaml
  ci-operator/jobs/kubernetes-sigs/security-profiles-operator/kubernetes-sigs-security-profiles-operator-master-presubmits.yaml
Labels: approved, lgtm

#15490 Add jenkins maven36 image
  ci-operator/config/openshift/jenkins/openshift-jenkins-openshift-3.11.yaml
Labels: approved, lgtm

#15517 htmlproofer: ingore sippy.ci.openshift.org
  ci-operator/config/openshift/ci-docs/openshift-ci-docs-master.yaml
Labels: approved, lgtm

#14757 Run E2E AWS single node variant on cluster-etcd-operator presubmit
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-master.yaml
  ci-operator/jobs/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-master-presubmits.yaml
Labels: approved, lgtm

#15539 template: Gather journal previous for older upgrade tests
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-src.yaml
Labels: approved, lgtm

#15336 [DPTP-1892] Migrate cluster-scaleup template jobs to multi-stage
  ci-operator/config/openshift/installer/openshift-installer-release-4.1.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.2.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.3.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.4.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.5.yaml
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-release-4.1.yaml
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-release-4.2.yaml
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-release-4.3.yaml
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-release-4.4.yaml
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-release-4.5.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.1.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.2.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.3.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.4.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.5.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-4.1.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-4.2.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-4.3.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-4.4.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-4.5.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-4.5-presubmits.yaml
Labels: approved, lgtm

#15531 Remove creds init image build
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.20.1__4.5.yaml
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.20.1__4.6.yaml
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-v0.20.1__4.7.yaml
  core-services/image-mirroring/tekton/mapping_tekton_v0_20_quay
Labels: approved, lgtm

#15546 kubevirt provider CI: changing number of resource-lease for kubevirt …
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: approved, lgtm

#15550 periodics: Allow cluster-bot to launch bigger jobs
  ci-operator/jobs/openshift/release/openshift-release-infra-periodics.yaml
Labels: approved, lgtm

#15529 Add functest container to hyperconverged-cluster-operator
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-master.yaml
Labels: approved, lgtm

#15552 periodics: All future periodic jobs may use more memory
  ci-operator/jobs/openshift/release/openshift-release-infra-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.8-periodics.yaml
Labels: approved, lgtm

#15551 steps/openshift/e2e/test: Provider needs to be passed to skip
  ci-operator/step-registry/openshift/e2e/test/openshift-e2e-test-commands.sh
Labels: approved, lgtm

#15563 Adding the ci-chat-bot ClusterRole to the Build Clusters
  clusters/build-clusters/common/ci-chat-bot/ci-chat-bot.yaml
Labels: approved, lgtm

#15457 Add assets upload step to Azure Arc Conformance tests
  ci-operator/step-registry/ipi/azure/arcconformance/ipi-azure-arcconformance-workflow.yaml
  ci-operator/step-registry/ipi/conf/azure/arcconformance/ipi-conf-azure-arcconformance-commands.sh
  ci-operator/step-registry/ipi/conf/azure/arcconformance/ipi-conf-azure-arcconformance-ref.yaml
  ci-operator/step-registry/ipi/conf/azure/arcconformance/region/OWNERS
  ci-operator/step-registry/ipi/conf/azure/arcconformance/region/ipi-conf-azure-arcconformance-region-commands.sh
  ci-operator/step-registry/ipi/conf/azure/arcconformance/region/ipi-conf-azure-arcconformance-region-ref.metadata.json
  ci-operator/step-registry/ipi/conf/azure/arcconformance/region/ipi-conf-azure-arcconformance-region-ref.yaml
Labels: approved, lgtm

#14764 Run single node live CD flow on installer presubmit
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
Labels: approved, lgtm

#14760 Run E2E AWS single node variant on cluster-authentication-operator presubmit
  ci-operator/config/openshift/cluster-authentication-operator/openshift-cluster-authentication-operator-master.yaml
  ci-operator/jobs/openshift/cluster-authentication-operator/openshift-cluster-authentication-operator-master-presubmits.yaml
Labels: approved, lgtm

#15528 Bug 1903107: Make vpshere tests mandatory for vpshere-problem-detector PRs
  ci-operator/jobs/openshift/vsphere-problem-detector/openshift-vsphere-problem-detector-master-presubmits.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#15572 core-services/ci-secret-generator/_config: Document AWS service account rotation
  core-services/ci-secret-generator/_config.yaml
Labels: approved, lgtm

#15576 disable prow autobumper to avoid broken deck
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm

#15577 Revert "Update Prow to v20210204-b06ec788ea, Boskos to v20210203-17d4b61"
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  clusters/app.ci/prow/03_deployment/cherrypick.yaml
  clusters/app.ci/prow/03_deployment/crier.yaml
  clusters/app.ci/prow/03_deployment/deck.yaml
  clusters/app.ci/prow/03_deployment/exporter.yaml
  clusters/app.ci/prow/03_deployment/gcsweb-private.yaml
  clusters/app.ci/prow/03_deployment/gcsweb.yaml
  clusters/app.ci/prow/03_deployment/ghproxy.yaml
  clusters/app.ci/prow/03_deployment/hook.yaml
  clusters/app.ci/prow/03_deployment/horologium.yaml
  clusters/app.ci/prow/03_deployment/jenkins_operator.yaml
  clusters/app.ci/prow/03_deployment/needs_rebase.yaml
  clusters/app.ci/prow/03_deployment/prow-controller-manager.yaml
  clusters/app.ci/prow/03_deployment/refresh.yaml
  clusters/app.ci/prow/03_deployment/sinker.yaml
  clusters/app.ci/prow/03_deployment/statusreconciler.yaml
  clusters/app.ci/prow/03_deployment/tide.yaml
  clusters/app.ci/prow/03_deployment/tot.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/03_deployment/adapter_imagestreams.yaml
  core-services/prow/03_deployment/gcsweb.yaml
  hack/images.sh
Labels: approved, lgtm

#15545 Update release-openshift-origin-installer-launch-{aws,vsphere} to use workflows
  ci-operator/jobs/openshift/release/openshift-release-infra-periodics.yaml
Labels: approved, lgtm

#15568 Adding build cluster kubeconfigs for ci-chat-bot
  core-services/ci-secret-bootstrap/_config.yaml
  core-services/ci-secret-generator/_config.yaml
Labels: approved, lgtm

#15500 managed-upgrade-operator: Remove ci.ext job requirement
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#15581 Revert "Update release-openshift-origin-installer-launch-aws to use workflows"
  ci-operator/jobs/openshift/release/openshift-release-infra-periodics.yaml
Labels: approved, lgtm

#15574 ci-docs: ignore checking github-edit links
  ci-operator/config/openshift/ci-docs/openshift-ci-docs-master.yaml
Labels: approved, lgtm

#15541 Replace the nginx-unprivileged image with a local import
  ci-operator/config/openshift/ci-docs/openshift-ci-docs-master.yaml
  clusters/app.ci/supplemental-ci-images/README.md
  clusters/app.ci/supplemental-ci-images/nginx-unprivileged_is.yaml
Labels: approved, lgtm

#15584 periodics: Invalid CONFIG_SPEC in launch-aws
  ci-operator/jobs/openshift/release/openshift-release-infra-periodics.yaml
Labels: approved, lgtm

#15580 Add Azure CSI driver & operator repo
  ci-operator/config/openshift/azure-disk-csi-driver-operator/OWNERS
  ci-operator/config/openshift/azure-disk-csi-driver-operator/openshift-azure-disk-csi-driver-operator-master.yaml
  ci-operator/config/openshift/azure-disk-csi-driver/OWNERS
  ci-operator/config/openshift/azure-disk-csi-driver/openshift-azure-disk-csi-driver-master.yaml
  ci-operator/jobs/openshift/azure-disk-csi-driver-operator/OWNERS
  ci-operator/jobs/openshift/azure-disk-csi-driver-operator/openshift-azure-disk-csi-driver-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/azure-disk-csi-driver/OWNERS
  ci-operator/jobs/openshift/azure-disk-csi-driver/openshift-azure-disk-csi-driver-master-presubmits.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#15586 Revert "Run E2E AWS single node variant on cluster-etcd-operator presubmit"
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-master.yaml
  ci-operator/jobs/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-master-presubmits.yaml
Labels: approved, lgtm

#15587 Make job/pull-ci-openshift-ci-docs-master-links mandatory
  ci-operator/jobs/openshift/ci-docs/openshift-ci-docs-master-presubmits.yaml
Labels: approved, lgtm

#15589 ci-operator-config: resolve configurations
  ci-operator/config/openshift-priv/cluster-authentication-operator/openshift-priv-cluster-authentication-operator-master.yaml
  ci-operator/config/openshift-priv/cluster-authentication-operator/openshift-priv-cluster-authentication-operator-release-4.7.yaml
  ci-operator/config/openshift-priv/cluster-authentication-operator/openshift-priv-cluster-authentication-operator-release-4.8.yaml
  ci-operator/config/openshift-priv/cluster-etcd-operator/openshift-priv-cluster-etcd-operator-master.yaml
  ci-operator/config/openshift-priv/cluster-etcd-operator/openshift-priv-cluster-etcd-operator-release-4.7.yaml
  ci-operator/config/openshift-priv/cluster-etcd-operator/openshift-priv-cluster-etcd-operator-release-4.8.yaml
  ci-operator/config/openshift/cluster-authentication-operator/openshift-cluster-authentication-operator-master.yaml
  ci-operator/config/openshift/cluster-authentication-operator/openshift-cluster-authentication-operator-release-4.7.yaml
  ci-operator/config/openshift/cluster-authentication-operator/openshift-cluster-authentication-operator-release-4.8.yaml
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.7.yaml
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.8.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
Labels: approved, lgtm

#15585 Extend the Azure Arc conformance suite to 4.5
  ci-operator/config/openshift/release/openshift-release-master__ocp-4.5.yaml
  ci-operator/config/openshift/release/openshift-release-master__ocp-4.6.yaml
  ci-operator/config/openshift/release/openshift-release-master__ocp-4.7.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: approved, lgtm

#15600 ocm: create ocm secrets manifest
  core-services/secrets/ocm-secrets/ocm-secrets.yaml
Labels: approved, lgtm

#15606 ocm: add secret mirroring
  core-services/secret-mirroring/_mapping.yaml
Labels: approved, lgtm

#15607 Secrets and testgrid docs: Refer to ci-docs
  core-services/secret-mirroring/README.md
  core-services/testgrid-config-generator/README.md
Labels: approved, lgtm

#15603 Build serviceaccount-secret-rotation-trigger image
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
Labels: approved, lgtm

#15579 Revert "disable prow autobumper to avoid broken deck"
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm

#15598 [4.7 cut] Stop fast forwarding 4.7 to master content
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm

#15599 [4.7 cut] Add tide query to require group-lead-approved
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#15604 [4.7 cut] Update bugzilla config
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#15605 [4.7 cut] Make remaining infra jobs treat master as 4.8
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm

#15583 Bug 1924358: Fix approve-csr script to not abort test on failure
  ci-operator/templates/openshift/installer/cluster-launch-installer-metal-e2e.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#15557 release: machine-os-content not being mirrored after promotion
  ci-operator/jobs/openshift/release/openshift-release-release-4.1-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.6-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.8-periodics.yaml
Labels: approved, lgtm

#15629 Remove hardcoded artifact dir for work repo
  ci-operator/config/open-cluster-management/work/open-cluster-management-work-master.yaml
  ci-operator/config/open-cluster-management/work/open-cluster-management-work-release-2.2.yaml
Labels: approved, lgtm

#15631 security-profiles-operator: remove release config
  ci-operator/config/kubernetes-sigs/security-profiles-operator/kubernetes-sigs-security-profiles-operator-release-4.7.yaml
  ci-operator/config/kubernetes-sigs/security-profiles-operator/kubernetes-sigs-security-profiles-operator-release-4.8.yaml
  ci-operator/jobs/kubernetes-sigs/security-profiles-operator/kubernetes-sigs-security-profiles-operator-release-4.7-postsubmits.yaml
  ci-operator/jobs/kubernetes-sigs/security-profiles-operator/kubernetes-sigs-security-profiles-operator-release-4.7-presubmits.yaml
  ci-operator/jobs/kubernetes-sigs/security-profiles-operator/kubernetes-sigs-security-profiles-operator-release-4.8-postsubmits.yaml
  ci-operator/jobs/kubernetes-sigs/security-profiles-operator/kubernetes-sigs-security-profiles-operator-release-4.8-presubmits.yaml
Labels: approved, lgtm

#15538 labels: org-level configuration
  core-services/prow/02_config/_labels.yaml
Labels: approved, lgtm

#15594 add labels to define components in openshift/console
  core-services/prow/02_config/_labels.yaml
Labels: approved, lgtm

#15537 Add test for virsh connection early in setup
  ci-operator/templates/openshift/installer/cluster-launch-installer-remote-libvirt-e2e.yaml
Labels: approved, lgtm

#15638 Fix app.ci push secret generation
  core-services/ci-secret-generator/_config.yaml
Labels: approved, lgtm

#15626 Switching secret to the updated secret with multiple kubeconfigs
  clusters/app.ci/ci-chat-bot/ci-chat-bot.yaml
Labels: approved, lgtm

#15595 Use secret-bootstrap for secret/github-client-secret
  clusters/build-clusters/01_cluster/assets/github-client-secret_secret_template.yaml
  clusters/build-clusters/02_cluster/assets/github-client-secret_secret_template.yaml
  core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#15632 workflows: add azure OVN upgrade workflow
  ci-operator/step-registry/openshift/upgrade/azure/ovn/OWNERS
  ci-operator/step-registry/openshift/upgrade/azure/ovn/openshift-upgrade-azure-ovn-workflow.metadata.json
  ci-operator/step-registry/openshift/upgrade/azure/ovn/openshift-upgrade-azure-ovn-workflow.yaml
Labels: approved, lgtm

#15596 Remove env. var. github_client_secret in applyconfig jobs
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
Labels: approved, lgtm

#15621 Tide: Disable throttling for status controller as well
  clusters/app.ci/prow/03_deployment/tide.yaml
Labels: approved, lgtm

#15625 Correcting the OCP release-controllers serviceaccount names
  clusters/app.ci/release-controller/deploy-ocp-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-ppc64le-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-ppc64le-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-s390x-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-s390x-priv-controller.yaml
  hack/generators/release-controllers/content/osd_rc_deployments.py
Labels: approved, lgtm

#15642 Update release-controller configs for 4.8
  ci-operator/config/openshift/release/openshift-release-master__ocp-4.8.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.8-periodics.yaml
  core-services/release-controller/_releases/priv/release-ocp-4.8-ppc64le.json
  core-services/release-controller/_releases/priv/release-ocp-4.8-s390x.json
  core-services/release-controller/_releases/priv/release-ocp-4.8.json
  core-services/release-controller/_releases/release-ocp-4.8-ci.json
  core-services/release-controller/_releases/release-ocp-4.8-ppc64le.json
  core-services/release-controller/_releases/release-ocp-4.8-s390x.json
  core-services/release-controller/_releases/release-ocp-4.8.json
  core-services/template-deprecation/_allowlist.yaml
Labels: approved, lgtm

#15648 Fixed username for OSD CLO group
  core-services/secrets/osd-clo-e2e/osd-clo-e2e-secrets.yaml
Labels: approved, lgtm

#15608 registry-access: setup SA for pushing machine-os-content images
  clusters/app.ci/registry-access/rhcos-devel/OWNERS
  clusters/app.ci/registry-access/rhcos-devel/admin_manifest.yaml
Labels: approved, lgtm

#15504 aws-efs-operator: Remove ci.ext job requirement
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#15654 vsphere - add debugging for govc vm.info command
  ci-operator/step-registry/upi/conf/vsphere/ova/upi-conf-vsphere-ova-commands.sh
Labels: approved, lgtm

#15653 tide: don't require valid-bug on master
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#15655 Fixed CLO E2E secret RoleBinding
  core-services/secrets/osd-clo-e2e/osd-clo-e2e-secrets.yaml
Labels: approved, lgtm

#15652 Add admin permissions to logging namespace
  clusters/app.ci/registry-access/openshift-logging/admin_manifest.yaml
Labels: approved, lgtm

#15637 Move machine-os-content-e2e jobs in release repo
  ci-operator/jobs/openshift/release/openshift-release-release-4.1-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.6-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.8-periodics.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: approved, lgtm

#15657 Allow RHCOS pipeline to publish to app.ci registry
  clusters/app.ci/registry-access/rhcos/OWNERS
  clusters/app.ci/registry-access/rhcos/admin_manifest.yaml
Labels: approved, lgtm

#15561 steps/gather: Also gather node audit logs
  ci-operator/step-registry/gather/extra/gather-extra-commands.sh
Labels: approved, lgtm

#12910 OKD: sync ironic-machine-os-downloader and ironic-static-ip-manager
  core-services/release-controller/_releases/release-ocp-4.5-ci.json
  core-services/release-controller/_releases/release-ocp-4.6-ci.json
  core-services/release-controller/_releases/release-ocp-4.7-ci.json
Labels: approved, lgtm

#15640 Remove github client id/secret from secret/build_farm
  core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#15659 Added OSD CLO E2E secret propagating
  core-services/secret-mirroring/_mapping.yaml
Labels: approved, lgtm

#14758 Run E2E AWS single node variant on cluster-ingress-operator presubmit
  ci-operator/config/openshift/cluster-ingress-operator/openshift-cluster-ingress-operator-master.yaml
  ci-operator/jobs/openshift/cluster-ingress-operator/openshift-cluster-ingress-operator-master-presubmits.yaml
Labels: approved, lgtm

#15593 coreos/rpm-ostree: Add clang-analyzer job
  ci-operator/config/coreos/rpm-ostree/coreos-rpm-ostree-master.yaml
  ci-operator/jobs/coreos/rpm-ostree/coreos-rpm-ostree-master-presubmits.yaml
Labels: approved, lgtm

#15656 Add daemonset to gather data on upgrade
  clusters/build-clusters/01_cluster/openshift/scc/ci-privileged_scc.yaml
  clusters/build-clusters/01_cluster/openshift/upgrade-debug-data/iostat-vmstat_daemonset.yaml
Labels: approved, lgtm

#15660 ROSA: Update required golang version
  ci-operator/config/openshift/rosa/openshift-rosa-master.yaml
Labels: approved, lgtm

#15665 update admin user group for integr8ly project
  clusters/app.ci/registry-access/integr8ly/OWNERS
  clusters/app.ci/registry-access/integr8ly/admin_integr8ly.yaml
Labels: approved, lgtm

#15663 Remove leftovers from node-debugging
  clusters/build-clusters/01_cluster/openshift/scc/ci-privileged_scc.yaml
Labels: approved, lgtm

#15670 Jira: Disable enterprise org
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#15677 steps: All IPI platforms should put prometheus on a PV
  ci-operator/step-registry/ipi/conf/aws/sharednetwork/ipi-conf-aws-sharednetwork-chain.yaml
  ci-operator/step-registry/ipi/conf/azure/sharednetwork/ipi-conf-azure-sharednetwork-chain.yaml
  ci-operator/step-registry/ipi/conf/gcp/sharednetwork/ipi-conf-gcp-sharednetwork-chain.yaml
  ci-operator/step-registry/ipi/install/monitoringpvc/ipi-install-monitoringpvc-commands.sh
Labels: approved, lgtm

#15630 Updating prow configs with psi job
  ci-operator/config/openshift/odo/openshift-odo-master__v4.6.yaml
  ci-operator/jobs/openshift/odo/openshift-odo-master-presubmits.yaml
Labels: approved, lgtm

#15335 Integrate configmap-scale in master and release-4.6 branches
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-master.yaml
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-release-4.6.yaml
  ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-master-presubmits.yaml
  ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-release-4.6-presubmits.yaml
  ci-operator/step-registry/openshift-perfscale/configmap-scale/openshift-perfscale-configmap-scale-commands.sh
Labels: approved, lgtm

#15535 Remove source fix_uid.sh from packet-teardown step
  ci-operator/step-registry/baremetalds/packet/teardown/baremetalds-packet-teardown-commands.sh
Labels: approved, lgtm

#15695 Revert "Update Prow to v20210209-ed3f510f45, Boskos to v20210203-17d4b61"
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  clusters/app.ci/prow/03_deployment/cherrypick.yaml
  clusters/app.ci/prow/03_deployment/crier.yaml
  clusters/app.ci/prow/03_deployment/deck.yaml
  clusters/app.ci/prow/03_deployment/exporter.yaml
  clusters/app.ci/prow/03_deployment/gcsweb-private.yaml
  clusters/app.ci/prow/03_deployment/gcsweb.yaml
  clusters/app.ci/prow/03_deployment/ghproxy.yaml
  clusters/app.ci/prow/03_deployment/hook.yaml
  clusters/app.ci/prow/03_deployment/horologium.yaml
  clusters/app.ci/prow/03_deployment/jenkins_operator.yaml
  clusters/app.ci/prow/03_deployment/needs_rebase.yaml
  clusters/app.ci/prow/03_deployment/prow-controller-manager.yaml
  clusters/app.ci/prow/03_deployment/refresh.yaml
  clusters/app.ci/prow/03_deployment/sinker.yaml
  clusters/app.ci/prow/03_deployment/statusreconciler.yaml
  clusters/app.ci/prow/03_deployment/tide.yaml
  clusters/app.ci/prow/03_deployment/tot.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/03_deployment/adapter_imagestreams.yaml
  core-services/prow/03_deployment/gcsweb.yaml
  hack/images.sh
Labels: approved, lgtm

#15699 disable prow autobumper to avoid broken deck
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm

#15611 ocm: add view role binding to secrets manifest
  core-services/secrets/ocm-secrets/ocm-secrets.yaml
Labels: approved, lgtm

#15614 Add maketarget for serviceaccount-secret-rotation
  Makefile
  ci-operator/jobs/infra-periodics.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: approved, lgtm

#15675 ci-operator: Update the metering OWNERS file
  ci-operator/config/kube-reporting/OWNERS
  ci-operator/config/kube-reporting/ghostunnel/OWNERS
  ci-operator/config/kube-reporting/hadoop/OWNERS
  ci-operator/config/kube-reporting/helm/OWNERS
  ci-operator/config/kube-reporting/hive/OWNERS
  ci-operator/config/kube-reporting/metering-operator/OWNERS
  ci-operator/config/kube-reporting/presto/OWNERS
  ci-operator/jobs/kube-reporting/ghostunnel/OWNERS
  ci-operator/jobs/kube-reporting/hadoop/OWNERS
  ci-operator/jobs/kube-reporting/helm/OWNERS
  ci-operator/jobs/kube-reporting/hive/OWNERS
  ci-operator/jobs/kube-reporting/metering-operator/OWNERS
  ci-operator/jobs/kube-reporting/presto/OWNERS
  ci-operator/jobs/openshift-priv/ghostunnel/OWNERS
  ci-operator/jobs/openshift-priv/hadoop/OWNERS
  ci-operator/jobs/openshift-priv/hive/OWNERS
  ci-operator/jobs/openshift-priv/presto/OWNERS
Labels: approved, lgtm, ok-to-test

#15643 Update to have opendatahub-io tests use ocp 4.7 and 4.6
  ci-operator/config/opendatahub-io/manifests/opendatahub-io-manifests-v1.0-branch-openshift.yaml
  ci-operator/config/opendatahub-io/odh-manifests/opendatahub-io-odh-manifests-master.yaml
  ci-operator/config/opendatahub-io/odh-manifests/opendatahub-io-odh-manifests-master__46.yaml
  ci-operator/config/opendatahub-io/opendatahub-operator/opendatahub-io-opendatahub-operator-master.yaml
  ci-operator/jobs/opendatahub-io/odh-manifests/opendatahub-io-odh-manifests-master-periodics.yaml
  ci-operator/jobs/opendatahub-io/odh-manifests/opendatahub-io-odh-manifests-master-presubmits.yaml
Labels: approved, lgtm
