Repository openshift/release, pull requests merged in 2021-11, with the labels that each got.

#23154 Increase timeout for the baremetalds-assisted-setup step
  ci-operator/step-registry/baremetalds/assisted/setup/baremetalds-assisted-setup-ref.yaml
Labels: lgtm, approved

#23152 Add CI config for RHMI operator branch rhoam-release-v1.14
  ci-operator/config/integr8ly/integreatly-operator/integr8ly-integreatly-operator-rhoam-release-v1.14.yaml
  ci-operator/jobs/integr8ly/integreatly-operator/integr8ly-integreatly-operator-rhoam-release-v1.14-postsubmits.yaml
  ci-operator/jobs/integr8ly/integreatly-operator/integr8ly-integreatly-operator-rhoam-release-v1.14-presubmits.yaml
  core-services/image-mirroring/integr8ly/mapping_integr8ly_operator_1_14
Labels: lgtm, approved, ok-to-test

#23155 Add cluster-api prowconfig
  core-services/prow/02_config/openshift/cluster-api/_prowconfig.yaml
Labels: lgtm, approved

#23156 Fix rte-operator images build
  ci-operator/config/openshift-kni/rte-operator/openshift-kni-rte-operator-main.yaml
Labels: lgtm, approved

#23158 Add a member of kubevirt-plugin as risk assesser
  core-services/prow/02_config/openshift/console/_pluginconfig.yaml
Labels: lgtm, approved

#23159 chore(osdctl): bump to go1.16
  ci-operator/config/openshift/osdctl/openshift-osdctl-master.yaml
Labels: lgtm, approved

#23160 Bump metallb-operator main lane to 4.10
  ci-operator/config/openshift/metallb-operator/openshift-metallb-operator-main.yaml
Labels: lgtm, approved

#23157 Add upgrade to ovn presubmits
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master-presubmits.yaml
Labels: lgtm, approved

#23138 Add new step baremetalds-assisted-images-vcsref to step registry
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-main.yaml
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.4.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.4.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-master.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.4.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.4.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-main-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.4-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.4-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-master-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.4-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.4-postsubmits.yaml
  ci-operator/step-registry/baremetalds/assisted/images/OWNERS
  ci-operator/step-registry/baremetalds/assisted/images/vcsref/OWNERS
  ci-operator/step-registry/baremetalds/assisted/images/vcsref/baremetalds-assisted-images-vcsref-commands.sh
  ci-operator/step-registry/baremetalds/assisted/images/vcsref/baremetalds-assisted-images-vcsref-ref.metadata.json
  ci-operator/step-registry/baremetalds/assisted/images/vcsref/baremetalds-assisted-images-vcsref-ref.yaml
Labels: lgtm, approved

#23105 Migrate github-ldap-mapping-updater-credentials job to psi
  clusters/psi/Makefile
  clusters/psi/README.md
  clusters/psi/github-ldap-mapping-update_cronjob.yaml
Labels: lgtm, approved

#22743 Fix: We should only look for middle/oldest versions in the stable channel
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: lgtm, approved

#23145 updated NUM_WORKER_NODES to 2 in gpu-addon osde2e job
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: lgtm, approved

#22985 Add more OCP versions for preflight jobs
  ci-operator/config/redhat-openshift-ecosystem/preflight/redhat-openshift-ecosystem-preflight-ocp-4.9.yaml
  ci-operator/jobs/redhat-openshift-ecosystem/preflight/redhat-openshift-ecosystem-preflight-ocp-4.9-periodics.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: lgtm, approved

#23027 Update the imageset for 4.8 clusterpools to 4.8.14
  clusters/hive/pools/hypershift/hypershift-ocp-4-8-0-amd64-aws-us-east-1_clusterpool.yaml
Labels: lgtm, approved

#23166 Update skip_if_only_changed settings for shared resource csi driver
  ci-operator/config/openshift/csi-driver-shared-resource-operator/openshift-csi-driver-shared-resource-operator-master.yaml
  ci-operator/config/openshift/csi-driver-shared-resource-operator/openshift-csi-driver-shared-resource-operator-release-4.10.yaml
  ci-operator/config/openshift/csi-driver-shared-resource-operator/openshift-csi-driver-shared-resource-operator-release-4.9.yaml
  ci-operator/config/openshift/csi-driver-shared-resource/openshift-csi-driver-shared-resource-master.yaml
  ci-operator/jobs/openshift/csi-driver-shared-resource-operator/openshift-csi-driver-shared-resource-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/csi-driver-shared-resource-operator/openshift-csi-driver-shared-resource-operator-release-4.10-presubmits.yaml
  ci-operator/jobs/openshift/csi-driver-shared-resource-operator/openshift-csi-driver-shared-resource-operator-release-4.9-presubmits.yaml
  ci-operator/jobs/openshift/csi-driver-shared-resource/openshift-csi-driver-shared-resource-master-presubmits.yaml
Labels: lgtm, approved

#23170 Updates CNO/SDN plugins for backport-risk-assessed
  core-services/prow/02_config/openshift/cluster-network-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/sdn/_pluginconfig.yaml
Labels: lgtm, approved

#23067 payload-testing-prow-plugin: mount ci-operator configs
  clusters/app.ci/prow/03_deployment/payload-testing-prow-plugin.yaml
Labels: lgtm, approved

#23172 [vsphere] scale down IBM Cloud leases due to infrastructure outage
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: lgtm, approved

#23173 Hypershift: Increase worker size and count for conformance tests
  ci-operator/config/openshift/hypershift/openshift-hypershift-main.yaml
Labels: lgtm, approved

#23169 Add machine-os-images repo
  ci-operator/config/openshift/machine-os-images/OWNERS
  ci-operator/config/openshift/machine-os-images/openshift-machine-os-images-main.yaml
  ci-operator/jobs/openshift/machine-os-images/OWNERS
  ci-operator/jobs/openshift/machine-os-images/openshift-machine-os-images-main-presubmits.yaml
  core-services/prow/02_config/openshift/machine-os-images/_pluginconfig.yaml
Labels: lgtm, approved

#23153 remove assisted-test-infra related jobs for ocm-2.3
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-ocm-2.3.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-ocm-2.3-presubmits.yaml
Labels: lgtm, approved

#23194 Setup CI for the Serverless 1.19 release
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.19.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.19__4.6.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.19__4.7.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.19__4.8.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.19__4.9.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.19-periodics.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.19-postsubmits.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.19-presubmits.yaml
Labels: lgtm, approved

#23196 Deploy the e2e-test lane with the latest image
  ci-operator/config/openshift-kni/resource-topology-exporter/openshift-kni-resource-topology-exporter-master.yaml
Labels: lgtm, approved

#23168 BUILD-256: add optional shared resource e2e to cso to validate shared resource related updates
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-master.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.10.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.10-presubmits.yaml
Labels: lgtm, approved

#23164 Add supplemetal images for centos 7 & 8
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_coreos
Labels: lgtm, approved

#23195 ISC: Add Vincent to relevant repos
  core-services/prow/02_config/openshift/compliance-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/file-integrity-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/oc-compliance/_pluginconfig.yaml
Labels: lgtm, approved

#23192 [rhd-sbo] Fix acceptance tests for 4.10
  ci-operator/config/redhat-developer/service-binding-operator/redhat-developer-service-binding-operator-master__4.10.yaml
Labels: lgtm, approved

#23199 [rhd-sbo] Switch acceptance tests OCP to nightly
  ci-operator/config/redhat-developer/service-binding-operator/redhat-developer-service-binding-operator-master__4.10.yaml
  ci-operator/config/redhat-developer/service-binding-operator/redhat-developer-service-binding-operator-master__4.7.yaml
  ci-operator/config/redhat-developer/service-binding-operator/redhat-developer-service-binding-operator-master__4.8.yaml
  ci-operator/config/redhat-developer/service-binding-operator/redhat-developer-service-binding-operator-master__4.9.yaml
  ci-operator/jobs/redhat-developer/service-binding-operator/redhat-developer-service-binding-operator-master-periodics.yaml
  ci-operator/jobs/redhat-developer/service-binding-operator/redhat-developer-service-binding-operator-master-presubmits.yaml
Labels: lgtm, approved

#23142 assisted-service: mirror operator images to hold image sha
  ci-operator/step-registry/baremetalds/assisted/operator/publish/baremetalds-assisted-operator-publish-commands.sh
  ci-operator/step-registry/baremetalds/assisted/operator/publish/baremetalds-assisted-operator-publish-ref.yaml
Labels: lgtm, approved

#23161 ocm: add release-2.5 branch
  core-services/prow/02_config/_plugins.yaml
Labels: lgtm, approved

#23201 Update dptp's CRDs
  clusters/app.ci/prow/01_crd/pullrequestpayloadqualificationruns.yaml
Labels: lgtm, approved

#23049 Onboard Red Hat AppStudio in Openshift CI
  ci-operator/config/redhat-appstudio/infra-deployments/OWNERS
  ci-operator/config/redhat-appstudio/infra-deployments/redhat-appstudio-infra-deployments-main.yaml
  ci-operator/jobs/redhat-appstudio/infra-deployments/OWNERS
  ci-operator/jobs/redhat-appstudio/infra-deployments/redhat-appstudio-infra-deployments-main-periodics.yaml
  ci-operator/jobs/redhat-appstudio/infra-deployments/redhat-appstudio-infra-deployments-main-presubmits.yaml
  core-services/prow/02_config/redhat-appstudio/infra-deployments/_pluginconfig.yaml
  core-services/prow/02_config/redhat-appstudio/infra-deployments/_prowconfig.yaml
Labels: lgtm, approved, tide/merge-method-squash

#23082 kata-containers: skip unidling tests
  ci-operator/config/kata-containers/kata-containers/kata-containers-kata-containers-main.yaml
Labels: lgtm, approved

#23176 Change test step of dynamic-plugin-sdk reop to use yarn
  ci-operator/config/openshift/dynamic-plugin-sdk/openshift-dynamic-plugin-sdk-main.yaml
Labels: lgtm, approved

#23209 add image configuration for the schedule-generator tool
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
Labels: lgtm, approved

#23190 Cinder CSI: add jobs to stable branches
  ci-operator/config/openshift/openstack-cinder-csi-driver-operator/openshift-openstack-cinder-csi-driver-operator-release-4.7.yaml
  ci-operator/config/openshift/openstack-cinder-csi-driver-operator/openshift-openstack-cinder-csi-driver-operator-release-4.8.yaml
  ci-operator/jobs/openshift/openstack-cinder-csi-driver-operator/openshift-openstack-cinder-csi-driver-operator-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/openstack-cinder-csi-driver-operator/openshift-openstack-cinder-csi-driver-operator-release-4.8-presubmits.yaml
Labels: lgtm, approved

#23208 propagating REPO_NAME and JOB_TYPE so that assisted-test-infra can clone relevent code
  ci-operator/step-registry/baremetalds/assisted/setup/baremetalds-assisted-setup-commands.sh
Labels: lgtm, approved

#23198 Remove env variables from the dependencies field
  ci-operator/config/openshift-kni/resource-topology-exporter/openshift-kni-resource-topology-exporter-master.yaml
Labels: lgtm, approved

#23047 OCPQE-6256: Add job to run destructive cucushift tests on aws ipi
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__ocp-4.10.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
  ci-operator/step-registry/cucushift/aws/ipi/destructive/OWNERS
  ci-operator/step-registry/cucushift/aws/ipi/destructive/cucushift-aws-ipi-destructive-commands.sh
  ci-operator/step-registry/cucushift/aws/ipi/destructive/cucushift-aws-ipi-destructive-ref.metadata.json
  ci-operator/step-registry/cucushift/aws/ipi/destructive/cucushift-aws-ipi-destructive-ref.yaml
  ci-operator/step-registry/cucushift/aws/ipi/destructive/cucushift-aws-ipi-destructive-workflow.metadata.json
  ci-operator/step-registry/cucushift/aws/ipi/destructive/cucushift-aws-ipi-destructive-workflow.yaml
Labels: lgtm, approved

#23215 Adding Knative KAfka Broker Receiver image
  ci-operator/config/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v0.26__49.yaml
Labels: lgtm, approved

#23217 Adding the Knative Kafka Broker's Data Plane images to the mirror process
  core-services/image-mirroring/knative/mapping_knative_v0_26_quay
Labels: lgtm, approved

#23213 Add prow config for backube/pvc-transfer
  core-services/prow/02_config/backube/pvc-transfer/OWNERS
  core-services/prow/02_config/backube/pvc-transfer/_pluginconfig.yaml
  core-services/prow/02_config/backube/pvc-transfer/_prowconfig.yaml
Labels: lgtm, approved

#23207 Add Prow config for machine-os-images
  core-services/prow/02_config/openshift/machine-os-images/_prowconfig.yaml
Labels: lgtm, approved

#23222 Revert "Change test step of dynamic-plugin-sdk reop to use yarn"
  ci-operator/config/openshift/dynamic-plugin-sdk/openshift-dynamic-plugin-sdk-main.yaml
Labels: lgtm, approved

#23013 Add configurations and Jobs for frr repo
  ci-operator/config/openshift/frr/OWNERS
  ci-operator/config/openshift/frr/openshift-frr-master.yaml
  ci-operator/jobs/openshift/frr/OWNERS
  ci-operator/jobs/openshift/frr/openshift-frr-master-postsubmits.yaml
  ci-operator/jobs/openshift/frr/openshift-frr-master-presubmits.yaml
  core-services/image-mirroring/openshift/mapping_origin_4_10
  core-services/prow/02_config/openshift/frr/OWNERS
  core-services/prow/02_config/openshift/frr/_pluginconfig.yaml
  core-services/prow/02_config/openshift/frr/_prowconfig.yaml
Labels: lgtm, approved

#23221 Update base image for dynamic-plugin-sdk repo
  ci-operator/config/openshift/dynamic-plugin-sdk/openshift-dynamic-plugin-sdk-main.yaml
Labels: lgtm, approved

#23223 assisted-operator-publish: add oc binary
  ci-operator/step-registry/baremetalds/assisted/operator/publish/baremetalds-assisted-operator-publish-ref.yaml
Labels: lgtm, approved

#23228 Update baremetalds-assisted-images-publish step to be generic
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-main.yaml
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.4.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.4.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-master.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.4.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.4.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-main-periodics.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.4-periodics.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master-periodics.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.4-periodics.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-master-periodics.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.4-periodics.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-periodics.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.4-periodics.yaml
  ci-operator/step-registry/baremetalds/assisted/images/publish/OWNERS
  ci-operator/step-registry/baremetalds/assisted/images/publish/baremetalds-assisted-images-publish-commands.sh
  ci-operator/step-registry/baremetalds/assisted/images/publish/baremetalds-assisted-images-publish-ref.metadata.json
  ci-operator/step-registry/baremetalds/assisted/images/publish/baremetalds-assisted-images-publish-ref.yaml
  ci-operator/step-registry/baremetalds/assisted/images/vcsref/baremetalds-assisted-images-vcsref-ref.metadata.json
Labels: lgtm, approved

#23214 Setup CI for Serving 0.26 and friends
  ci-operator/config/openshift-knative/net-istio/openshift-knative-net-istio-release-0.26.yaml
  ci-operator/config/openshift-knative/net-kourier/openshift-knative-net-kourier-release-0.26.yaml
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-v0.26.0__4.6.yaml
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-v0.26.0__4.7.yaml
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-v0.26.0__4.8.yaml
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-v0.26.0__4.9.yaml
  ci-operator/jobs/openshift-knative/net-istio/openshift-knative-net-istio-release-0.26-postsubmits.yaml
  ci-operator/jobs/openshift-knative/net-istio/openshift-knative-net-istio-release-0.26-presubmits.yaml
  ci-operator/jobs/openshift-knative/net-kourier/openshift-knative-net-kourier-release-0.26-postsubmits.yaml
  ci-operator/jobs/openshift-knative/net-kourier/openshift-knative-net-kourier-release-0.26-presubmits.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-v0.26.0-postsubmits.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-v0.26.0-presubmits.yaml
Labels: lgtm, approved

#23185 Refactor cucushift e2e tests
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__ocp-4.10.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__ocp-4.9.yaml
  ci-operator/step-registry/cucushift/baremetal/OWNERS
  ci-operator/step-registry/cucushift/baremetal/ipi/OWNERS
  ci-operator/step-registry/cucushift/baremetal/ipi/cucushift-baremetal-ipi-ref.metadata.json
  ci-operator/step-registry/cucushift/baremetal/ipi/cucushift-baremetal-ipi-ref.yaml
  ci-operator/step-registry/cucushift/baremetal/ipi/cucushift-baremetal-ipi-workflow.metadata.json
  ci-operator/step-registry/cucushift/baremetal/ipi/cucushift-baremetal-ipi-workflow.yaml
  ci-operator/step-registry/cucushift/e2e/OWNERS
  ci-operator/step-registry/cucushift/e2e/cucushift-e2e-commands.sh
  ci-operator/step-registry/cucushift/e2e/cucushift-e2e-ref.metadata.json
  ci-operator/step-registry/cucushift/e2e/cucushift-e2e-ref.yaml
  ci-operator/step-registry/cucushift/e2e/cucushift-e2e-workflow.metadata.json
  ci-operator/step-registry/cucushift/e2e/cucushift-e2e-workflow.yaml
  ci-operator/step-registry/cucushift/gcp/OWNERS
  ci-operator/step-registry/cucushift/gcp/ipi/OWNERS
  ci-operator/step-registry/cucushift/gcp/ipi/cucushift-gcp-ipi-commands.sh
  ci-operator/step-registry/cucushift/gcp/ipi/cucushift-gcp-ipi-ref.metadata.json
  ci-operator/step-registry/cucushift/gcp/ipi/cucushift-gcp-ipi-workflow.metadata.json
  ci-operator/step-registry/cucushift/gcp/ipi/cucushift-gcp-ipi-workflow.yaml
  ci-operator/step-registry/cucushift/gcp/upi/OWNERS
  ci-operator/step-registry/cucushift/gcp/upi/cucushift-gcp-upi-commands.sh
  ci-operator/step-registry/cucushift/gcp/upi/cucushift-gcp-upi-ref.metadata.json
  ci-operator/step-registry/cucushift/gcp/upi/cucushift-gcp-upi-ref.yaml
  ci-operator/step-registry/cucushift/gcp/upi/cucushift-gcp-upi-workflow.metadata.json
  ci-operator/step-registry/cucushift/gcp/upi/cucushift-gcp-upi-workflow.yaml
Labels: lgtm, approved

#23236 Actually run the Knative Serving 4.9 jobs on 4.9 clusters
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-next__4.9.yaml
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-v0.26.0__4.9.yaml
Labels: lgtm, approved

#23238 Update image mirror for knative
  core-services/image-mirroring/knative/mapping_knative_v0_25_quay
  core-services/image-mirroring/knative/mapping_knative_v0_26_quay
Labels: lgtm, approved

#23239 Add z stream approvers for must-gather repo
  core-services/prow/02_config/openshift/must-gather/_pluginconfig.yaml
Labels: lgtm, approved

#22698 Snapshot oldest prometheus data
  ci-operator/step-registry/gather/extra/gather-extra-commands.sh
  ci-operator/step-registry/gather/libvirt/gather-libvirt-commands.sh
  ci-operator/templates/openshift/installer/cluster-launch-installer-custom-test-image.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-metal-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-upi-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-remote-libvirt-e2e.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
  ci-operator/templates/openshift/openshift-ansible/cluster-scaleup-e2e-40.yaml
Labels: lgtm, approved, tide/merge-method-squash

#23233 OCPQE-6636: Refactor cucushift e2e tests (continue-1)
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__ocp-4.10.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__ocp-4.9.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
  ci-operator/step-registry/cucushift/e2e/cucushift-e2e-ref.yaml
  ci-operator/step-registry/cucushift/openstack/OWNERS
  ci-operator/step-registry/cucushift/openstack/ipi/OWNERS
  ci-operator/step-registry/cucushift/openstack/ipi/cucushift-openstack-ipi-commands.sh
  ci-operator/step-registry/cucushift/openstack/ipi/cucushift-openstack-ipi-ref.metadata.json
  ci-operator/step-registry/cucushift/openstack/ipi/cucushift-openstack-ipi-ref.yaml
  ci-operator/step-registry/cucushift/openstack/ipi/cucushift-openstack-ipi-workflow.metadata.json
  ci-operator/step-registry/cucushift/openstack/ipi/cucushift-openstack-ipi-workflow.yaml
  ci-operator/step-registry/cucushift/openstack/upi/OWNERS
  ci-operator/step-registry/cucushift/openstack/upi/cucushift-openstack-upi-commands.sh
  ci-operator/step-registry/cucushift/openstack/upi/cucushift-openstack-upi-ref.metadata.json
  ci-operator/step-registry/cucushift/openstack/upi/cucushift-openstack-upi-ref.yaml
  ci-operator/step-registry/cucushift/openstack/upi/cucushift-openstack-upi-workflow.metadata.json
  ci-operator/step-registry/cucushift/openstack/upi/cucushift-openstack-upi-workflow.yaml
Labels: lgtm, approved

#23246 Fix vsphere csi migration feature gate for CCM install job
  ci-operator/step-registry/ccm/conf/pre-create-feature-gate/ccm-conf-pre-create-feature-gate-commands.sh
Labels: lgtm, approved

#23248 Populate configMaps to build03
  core-services/prow/02_config/_plugins.yaml
Labels: lgtm, approved

#23245 Fix openstack cluster profile for the cluster-bot
  ci-operator/jobs/openshift/release/openshift-release-infra-periodics.yaml
Labels: lgtm, approved

#23229 Add the release schedule configmap update cronjob to psi cluster
  clusters/psi/Makefile
  clusters/psi/release-schedules-update_cronjob.yaml
Labels: lgtm, approved

#23205 Remove several unused templates and related config
  ci-operator/templates/master-sidecar-4.6.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-remote-libvirt-e2e.yaml
  core-services/prow/02_config/_plugins.yaml
  core-services/template-deprecation/_allowlist.yaml
Labels: lgtm, approved

#23250 Enable CSIMigrationGCE for CCM jobs
  ci-operator/step-registry/ccm/conf/apply-feature-gate/ccm-conf-apply-feature-gate-commands.sh
  ci-operator/step-registry/ccm/conf/pre-create-feature-gate/ccm-conf-pre-create-feature-gate-commands.sh
Labels: lgtm, approved

#23240 install addon-operator in the provisioned cluster
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: lgtm, approved

#23252 assisted-operator-publish: create the docker config dir
  ci-operator/step-registry/baremetalds/assisted/operator/publish/baremetalds-assisted-operator-publish-commands.sh
Labels: lgtm, approved

#23204 Adding compute machine type for modh operator test
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: lgtm, approved

#23137 Add prow config for cloud-provider-alibaba-cloud
  core-services/prow/02_config/openshift/cloud-provider-alibaba-cloud/_prowconfig.yaml
Labels: lgtm, approved

#23257 Adding proper version mirrored images
  core-services/image-mirroring/knative/mapping_knative_v0_25_quay
Labels: lgtm, approved

#22878 GPU Operator: 4.9: use cluster-pool for PR testing and enable 1.7 and 1.8 nightly testing
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-master__4.9.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-release-4.9.yaml
  ci-operator/jobs/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-master-presubmits.yaml
  ci-operator/jobs/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-release-4.9-periodics.yaml
Labels: lgtm, approved

#23227 Dispatch no-builds jobs to build03
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: lgtm, approved

#23216 vSphere: enable IBM - 8 concurrent
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: lgtm, approved

#23255 Add prow config for machine-api-provider-aws
  core-services/prow/02_config/openshift/machine-api-provider-aws/OWNERS
  core-services/prow/02_config/openshift/machine-api-provider-aws/_pluginconfig.yaml
  core-services/prow/02_config/openshift/machine-api-provider-aws/_prowconfig.yaml
Labels: lgtm, approved

#23259 Add IPI 4.6 clusters for preflight jobs
  ci-operator/config/redhat-openshift-ecosystem/preflight/redhat-openshift-ecosystem-preflight-ocp-4.6.yaml
  ci-operator/jobs/redhat-openshift-ecosystem/preflight/redhat-openshift-ecosystem-preflight-ocp-4.6-periodics.yaml
  ci-operator/step-registry/operator-pipelines/preflight-common/aws/OWNERS
  ci-operator/step-registry/operator-pipelines/preflight-common/aws/operator-pipelines-preflight-common-aws-workflow.metadata.json
  ci-operator/step-registry/operator-pipelines/preflight-common/aws/operator-pipelines-preflight-common-aws-workflow.yaml
Labels: lgtm, approved

#23271 Simplify bootstrap's config
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved

#23275 Adding `build03` to the release-controller cluster group
  clusters/app.ci/release-controller/deploy-ocp-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-priv-controller.yaml
  hack/generators/release-controllers/content/osd_rc_deployments.py
Labels: lgtm, approved

#23265 Utilize build.sh and test.sh for dyanmic-plugin-sdk repo
  ci-operator/config/openshift/dynamic-plugin-sdk/openshift-dynamic-plugin-sdk-main.yaml
  ci-operator/jobs/openshift/dynamic-plugin-sdk/openshift-dynamic-plugin-sdk-main-presubmits.yaml
Labels: lgtm, approved

#23274 Hypershift: Use maketarget from repo for CI installation
  ci-operator/config/openshift/hypershift/openshift-hypershift-main.yaml
Labels: lgtm, approved

#23272 Add IPI 4.7 clusters for preflight jobs
  ci-operator/config/redhat-openshift-ecosystem/preflight/redhat-openshift-ecosystem-preflight-ocp-4.7.yaml
  ci-operator/jobs/redhat-openshift-ecosystem/preflight/redhat-openshift-ecosystem-preflight-ocp-4.7-periodics.yaml
Labels: lgtm, approved

#23280 Add default value to BUMP_MINOR in baremetalds-assisted-operator-publish
  ci-operator/step-registry/baremetalds/assisted/operator/publish/baremetalds-assisted-operator-publish-commands.sh
Labels: lgtm, approved

#23283 OCPQE-6636: Correct TAG_VERSION for 4.9 OpenStack
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__ocp-4.10.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__ocp-4.9.yaml
Labels: lgtm, approved

#23282 release: add upgrade tests to chatbot jobs
  ci-operator/jobs/openshift/release/openshift-release-infra-periodics.yaml
Labels: lgtm, approved

#23285 OCPQE-6636: Refactor cucushift e2e tests (continue-2)
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__ocp-4.10.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__ocp-4.9.yaml
  ci-operator/step-registry/cucushift/vsphere/OWNERS
  ci-operator/step-registry/cucushift/vsphere/ipi/OWNERS
  ci-operator/step-registry/cucushift/vsphere/ipi/cucushift-vsphere-ipi-commands.sh
  ci-operator/step-registry/cucushift/vsphere/ipi/cucushift-vsphere-ipi-ref.metadata.json
  ci-operator/step-registry/cucushift/vsphere/ipi/cucushift-vsphere-ipi-ref.yaml
  ci-operator/step-registry/cucushift/vsphere/ipi/cucushift-vsphere-ipi-workflow.metadata.json
  ci-operator/step-registry/cucushift/vsphere/ipi/cucushift-vsphere-ipi-workflow.yaml
  ci-operator/step-registry/cucushift/vsphere/upi/OWNERS
  ci-operator/step-registry/cucushift/vsphere/upi/cucushift-vsphere-upi-commands.sh
  ci-operator/step-registry/cucushift/vsphere/upi/cucushift-vsphere-upi-ref.metadata.json
  ci-operator/step-registry/cucushift/vsphere/upi/cucushift-vsphere-upi-ref.yaml
  ci-operator/step-registry/cucushift/vsphere/upi/cucushift-vsphere-upi-workflow.metadata.json
  ci-operator/step-registry/cucushift/vsphere/upi/cucushift-vsphere-upi-workflow.yaml
Labels: lgtm, approved

#23289 MGMT-7983 - Change networking cron job to run every 4 hours
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-periodics.yaml
Labels: lgtm, approved

#22958 Change metal-ipi workflows to new metal-ipi steps
  ci-operator/config/openshift-metal3/dev-scripts/openshift-metal3-dev-scripts-master.yaml
Labels: lgtm, approved

#23287 OCPQE-6636: Refactor cucushift e2e tests (continue-3)
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__ocp-4.10.yaml
Labels: lgtm, approved

#23249 make live-iso job a required presubmit job for assisted-test-infra
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-presubmits.yaml
Labels: lgtm, approved

#23267 add approve label for both ptp operator components
  core-services/prow/02_config/openshift/linuxptp-daemon/_prowconfig.yaml
  core-services/prow/02_config/openshift/ptp-operator/_prowconfig.yaml
Labels: lgtm, approved

#23292 Make all presubmit jobs but the operator leg optional again
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main-presubmits.yaml
Labels: lgtm, approved

#23293 Revert "release: add upgrade tests to chatbot jobs"
  ci-operator/jobs/openshift/release/openshift-release-infra-periodics.yaml
Labels: lgtm, approved

#23278 Adapt config to bumping tools to test-infra 3f7904a7d1e9
  core-services/prow/02_config/_plugins.yaml
Labels: lgtm, approved

#23254 Allow peberanek to run tests and do operations with run bots
  OWNERS_ALIASES
Labels: lgtm, approved

#23273 Remove backube/scribe repo
  ci-operator/config/backube/scribe/OWNERS
  ci-operator/config/backube/scribe/backube-scribe-master.yaml
  ci-operator/jobs/backube/scribe/OWNERS
  ci-operator/jobs/backube/scribe/backube-scribe-master-presubmits.yaml
  core-services/prow/02_config/backube/scribe/OWNERS
  core-services/prow/02_config/backube/scribe/_pluginconfig.yaml
  core-services/prow/02_config/backube/scribe/_prowconfig.yaml
Labels: lgtm, approved

#22081 Add cluster-api jobs
  ci-operator/config/openshift/cluster-api/openshift-cluster-api-master.yaml
  ci-operator/jobs/openshift/cluster-api/openshift-cluster-api-master-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-api/openshift-cluster-api-master-presubmits.yaml
  core-services/image-mirroring/openshift/mapping_origin_4_10
  core-services/prow/02_config/openshift/cluster-api/OWNERS
  core-services/prow/02_config/openshift/cluster-api/_pluginconfig.yaml
Labels: lgtm, approved

#23206 Add config for building capi 1.0.0 into hypershift namespace
  ci-operator/config/openshift/cluster-api/openshift-cluster-api-release-1.0.yaml
  ci-operator/jobs/openshift/cluster-api/openshift-cluster-api-release-1.0-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-api/openshift-cluster-api-release-1.0-presubmits.yaml
Labels: lgtm, approved

#23297 Update admin_cluster-admin-0_list.yaml
  clusters/build-clusters/common/assets/admin_cluster-admin-0_list.yaml
Labels: lgtm, approved

#23256 Hypershift: Use latest tests image to get test fixes
  ci-operator/config/openshift/hypershift/openshift-hypershift-main.yaml
Labels: lgtm, approved

#23262 add jenkins client e2e to jenkins repo; delete obsolete e2e-aws-jenkins
  ci-operator/config/openshift/jenkins/openshift-jenkins-master.yaml
  ci-operator/config/openshift/jenkins/openshift-jenkins-release-4.10.yaml
  ci-operator/jobs/openshift/jenkins/openshift-jenkins-master-presubmits.yaml
  ci-operator/jobs/openshift/jenkins/openshift-jenkins-release-4.10-presubmits.yaml
Labels: lgtm, approved

#23298 Rename rte-operator configuration to numaresources-operator
  ci-operator/config/openshift-kni/numaresources-operator/OWNERS
  ci-operator/config/openshift-kni/numaresources-operator/openshift-kni-numaresources-operator-main.yaml
  ci-operator/jobs/openshift-kni/numaresources-operator/OWNERS
  ci-operator/jobs/openshift-kni/numaresources-operator/openshift-kni-numaresources-operator-main-postsubmits.yaml
  ci-operator/jobs/openshift-kni/numaresources-operator/openshift-kni-numaresources-operator-main-presubmits.yaml
  core-services/prow/02_config/openshift-kni/numaresources-operator/OWNERS
  core-services/prow/02_config/openshift-kni/numaresources-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift-kni/numaresources-operator/_prowconfig.yaml
Labels: lgtm, approved

#23247 Onboarding assisted-events-scrap repository
  ci-operator/config/openshift-assisted/assisted-events-scrap/OWNERS
  ci-operator/config/openshift-assisted/assisted-events-scrap/openshift-assisted-assisted-events-scrap-master.yaml
  ci-operator/jobs/openshift-assisted/assisted-events-scrap/OWNERS
  ci-operator/jobs/openshift-assisted/assisted-events-scrap/openshift-assisted-assisted-events-scrap-master-postsubmits.yaml
  ci-operator/jobs/openshift-assisted/assisted-events-scrap/openshift-assisted-assisted-events-scrap-master-presubmits.yaml
  core-services/prow/02_config/openshift-assisted/assisted-events-scrap/OWNERS
  core-services/prow/02_config/openshift-assisted/assisted-events-scrap/_pluginconfig.yaml
  core-services/prow/02_config/openshift-assisted/assisted-events-scrap/_prowconfig.yaml
Labels: lgtm, approved

#23303 Use different install step for vsphere-ccm-install job
  ci-operator/step-registry/openshift/e2e/vsphere/ccm/install/openshift-e2e-vsphere-ccm-install-workflow.yaml
Labels: lgtm, approved

#23279 HAC 83: Initialize configuration for hac-infra repo
  ci-operator/config/openshift/hac-infra/OWNERS
  ci-operator/config/openshift/hac-infra/openshift-hac-infra-main.yaml
  ci-operator/jobs/openshift/hac-infra/OWNERS
  ci-operator/jobs/openshift/hac-infra/openshift-hac-infra-main-presubmits.yaml
  core-services/prow/02_config/openshift/hac-infra/_pluginconfig.yaml
  core-services/prow/02_config/openshift/hac-infra/_prowconfig.yaml
Labels: lgtm, approved

#23230 HAC 83: Initialize configuration for hac-dev repo
  ci-operator/config/openshift/hac-dev/OWNERS
  ci-operator/config/openshift/hac-dev/openshift-hac-dev-main.yaml
  ci-operator/jobs/openshift/hac-dev/OWNERS
  ci-operator/jobs/openshift/hac-dev/openshift-hac-dev-main-presubmits.yaml
  core-services/prow/02_config/openshift/hac-dev/_pluginconfig.yaml
  core-services/prow/02_config/openshift/hac-dev/_prowconfig.yaml
Labels: lgtm, approved

#22784 Add OSD Conformance test in stage env
  ci-operator/config/openshift/osde2e/openshift-osde2e-main.yaml
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: lgtm, approved

#23307 opendatahub: Use the rolling OLM channel for CI runs
  ci-operator/config/opendatahub-io/opendatahub-operator/opendatahub-io-opendatahub-operator-master.yaml
Labels: lgtm, approved

#23316 baremetalds-assisted-images-publish: Fix bug with nightly publishes
  ci-operator/step-registry/baremetalds/assisted/images/publish/baremetalds-assisted-images-publish-commands.sh
Labels: lgtm, approved

#23320 assisted-service: Update postgres image in bundle
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.4.yaml
Labels: lgtm, approved

#23322 ci-operator/config/openshift/release: Drop 4.6->4.8 and 4.7->4.9 paused jobs
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.9-upgrade-from-stable-4.7.yaml
  ci-operator/config/openshift/release/openshift-release-master__stable-4.8-upgrade-from-stable-4.6.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: lgtm, approved

#23318 add weshayutin to oadp-operator OWNERS
  ci-operator/config/openshift/oadp-operator/OWNERS
Labels: lgtm, approved

#22903 Add openshift/dpu-network-operator repo
  ci-operator/config/openshift/dpu-network-operator/OWNERS
  ci-operator/config/openshift/dpu-network-operator/openshift-dpu-network-operator-master.yaml
  ci-operator/jobs/openshift/dpu-network-operator/OWNERS
  ci-operator/jobs/openshift/dpu-network-operator/openshift-dpu-network-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/dpu-network-operator/openshift-dpu-network-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  core-services/image-mirroring/openshift/mapping_origin_4_10
  core-services/prow/02_config/openshift/dpu-network-operator/OWNERS
  core-services/prow/02_config/openshift/dpu-network-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/dpu-network-operator/_prowconfig.yaml
Labels: lgtm, approved

#23327 stackrox: e2e test
  ci-operator/config/stackrox/rox-openshift-ci-mirror/stackrox-rox-openshift-ci-mirror-master.yaml
  ci-operator/jobs/stackrox/rox-openshift-ci-mirror/stackrox-rox-openshift-ci-mirror-master-presubmits.yaml
Labels: lgtm, approved

#23317 Hypershift: Add periodic for serial conformance test suite
  ci-operator/config/openshift/hypershift/openshift-hypershift-main.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-main-periodics.yaml
Labels: lgtm, approved

#23328 Adjust test freqeuncy for 4.10 cucushift
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__ocp-4.10.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
Labels: lgtm, approved

#23330 Add QE approvers for library repos, and other component repos that should have QE approvers
  core-services/prow/02_config/openshift/apiserver-library-go/_pluginconfig.yaml
  core-services/prow/02_config/openshift/client-go/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-bootstrap/_pluginconfig.yaml
  core-services/prow/02_config/openshift/library-go/_pluginconfig.yaml
  core-services/prow/02_config/openshift/origin/_pluginconfig.yaml
Labels: lgtm, approved

#23189 origin: Allow mandre to label for backport
  core-services/prow/02_config/openshift/origin/_pluginconfig.yaml
Labels: lgtm, approved

#23315 Restore `installAttemptsLimit` on CVP pools
  clusters/hive/pools/cvp/cvp-ocp-4-6-amd64-aws-us-west-1_clusterpool.yaml
  clusters/hive/pools/cvp/cvp-ocp-4-8-amd64-aws-us-east-2_clusterpool.yaml
Labels: lgtm, approved

#23007 Add launch-ovn option into cluster-bot for metal-ipi clusters
  ci-operator/jobs/openshift/release/openshift-release-infra-periodics.yaml
Labels: lgtm, approved

#23186 Move metal-ipi workflows to new steps
  ci-operator/jobs/openshift/release/openshift-release-infra-periodics.yaml
Labels: lgtm, approved

#22944 Move metal-ipi workflows to new steps
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.10.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.8.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.9.yaml
Labels: lgtm, approved

#23339 Cleaning up job for our outdated repos
  ci-operator/config/openshift-knative/eventing-operator/OWNERS
  ci-operator/config/openshift-knative/eventing-operator/openshift-knative-eventing-operator-release-0.12.yaml
  ci-operator/config/openshift-knative/eventing-operator/openshift-knative-eventing-operator-release-0.13.1.yaml
  ci-operator/config/openshift-knative/eventing-operator/openshift-knative-eventing-operator-release-0.13.2.yaml
  ci-operator/config/openshift-knative/eventing-operator/openshift-knative-eventing-operator-release-0.13.yaml
  ci-operator/config/openshift-knative/eventing-operator/openshift-knative-eventing-operator-release-v0.13.yaml
  ci-operator/config/openshift-knative/serving-operator/OWNERS
  ci-operator/config/openshift-knative/serving-operator/openshift-knative-serving-operator-release-0.11.yaml
  ci-operator/config/openshift-knative/serving-operator/openshift-knative-serving-operator-release-0.12.yaml
  ci-operator/config/openshift-knative/serving-operator/openshift-knative-serving-operator-release-0.13.yaml
  ci-operator/jobs/openshift-knative/eventing-operator/OWNERS
  ci-operator/jobs/openshift-knative/eventing-operator/openshift-knative-eventing-operator-release-0.12-postsubmits.yaml
  ci-operator/jobs/openshift-knative/eventing-operator/openshift-knative-eventing-operator-release-0.12-presubmits.yaml
  ci-operator/jobs/openshift-knative/eventing-operator/openshift-knative-eventing-operator-release-0.13-postsubmits.yaml
  ci-operator/jobs/openshift-knative/eventing-operator/openshift-knative-eventing-operator-release-0.13-presubmits.yaml
  ci-operator/jobs/openshift-knative/eventing-operator/openshift-knative-eventing-operator-release-0.13.1-postsubmits.yaml
  ci-operator/jobs/openshift-knative/eventing-operator/openshift-knative-eventing-operator-release-0.13.1-presubmits.yaml
  ci-operator/jobs/openshift-knative/eventing-operator/openshift-knative-eventing-operator-release-0.13.2-postsubmits.yaml
  ci-operator/jobs/openshift-knative/eventing-operator/openshift-knative-eventing-operator-release-0.13.2-presubmits.yaml
  ci-operator/jobs/openshift-knative/eventing-operator/openshift-knative-eventing-operator-release-v0.13-postsubmits.yaml
  ci-operator/jobs/openshift-knative/eventing-operator/openshift-knative-eventing-operator-release-v0.13-presubmits.yaml
  ci-operator/jobs/openshift-knative/serving-operator/OWNERS
  ci-operator/jobs/openshift-knative/serving-operator/openshift-knative-serving-operator-release-0.11-postsubmits.yaml
  ci-operator/jobs/openshift-knative/serving-operator/openshift-knative-serving-operator-release-0.11-presubmits.yaml
  ci-operator/jobs/openshift-knative/serving-operator/openshift-knative-serving-operator-release-0.12-postsubmits.yaml
  ci-operator/jobs/openshift-knative/serving-operator/openshift-knative-serving-operator-release-0.12-presubmits.yaml
  ci-operator/jobs/openshift-knative/serving-operator/openshift-knative-serving-operator-release-0.13-postsubmits.yaml
  ci-operator/jobs/openshift-knative/serving-operator/openshift-knative-serving-operator-release-0.13-presubmits.yaml
Labels: lgtm, approved

#23258 Add wait conditions (from openshift-e2e-test) before triggering the tests
  ci-operator/step-registry/baremetalds/devscripts/setup/baremetalds-devscripts-setup-commands.sh
  ci-operator/step-registry/baremetalds/e2e/test/baremetalds-e2e-test-commands.sh
Labels: lgtm, approved

#23333 Refactor the upgrade job to use unified steps
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__ocp-4.10-upgrade-from-stable-4.9.yaml
  ci-operator/step-registry/cucushift/aws/ipi/upgrade/cucushift-aws-ipi-upgrade-ref.metadata.json
  ci-operator/step-registry/cucushift/upgrade/check/OWNERS
  ci-operator/step-registry/cucushift/upgrade/check/cucushift-upgrade-check-commands.sh
  ci-operator/step-registry/cucushift/upgrade/check/cucushift-upgrade-check-ref.metadata.json
  ci-operator/step-registry/cucushift/upgrade/check/cucushift-upgrade-check-ref.yaml
  ci-operator/step-registry/cucushift/upgrade/cucushift-upgrade-workflow.metadata.json
  ci-operator/step-registry/cucushift/upgrade/cucushift-upgrade-workflow.yaml
  ci-operator/step-registry/cucushift/upgrade/pre/cucushift-upgrade-pre-commands.sh
  ci-operator/step-registry/cucushift/upgrade/pre/cucushift-upgrade-pre-ref.yaml
Labels: lgtm, approved

#23325 Add the job-trigger-controller-manager deployment, rbacs and image configuration
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
  clusters/app.ci/job-trigger-controller-manager/README.md
  clusters/app.ci/job-trigger-controller-manager/admin_job-trigger-controller-manager_rbac.yaml
  clusters/app.ci/job-trigger-controller-manager/job-trigger-controller-manager_deploy.yaml
Labels: lgtm, approved

#23309 microshift- add reboot e2e and workflow
  ci-operator/config/redhat-et/microshift/redhat-et-microshift-main.yaml
  ci-operator/jobs/redhat-et/microshift/redhat-et-microshift-main-presubmits.yaml
  ci-operator/step-registry/redhat-et/microshift/e2e/reboot-tests/OWNERS
  ci-operator/step-registry/redhat-et/microshift/e2e/reboot-tests/redhat-et-microshift-e2e-reboot-tests-chain.metadata.json
  ci-operator/step-registry/redhat-et/microshift/e2e/reboot-tests/redhat-et-microshift-e2e-reboot-tests-chain.yaml
  ci-operator/step-registry/redhat-et/microshift/e2e/reboot-tests/redhat-et-microshift-e2e-reboot-tests-commands.sh
  ci-operator/step-registry/redhat-et/microshift/e2e/reboot-tests/redhat-et-microshift-e2e-reboot-tests-ref.metadata.json
  ci-operator/step-registry/redhat-et/microshift/e2e/reboot-tests/redhat-et-microshift-e2e-reboot-tests-ref.yaml
  ci-operator/step-registry/redhat-et/microshift/e2e/reboot-tests/redhat-et-microshift-e2e-reboot-tests-workflow.metadata.json
  ci-operator/step-registry/redhat-et/microshift/e2e/reboot-tests/redhat-et-microshift-e2e-reboot-tests-workflow.yaml
  ci-operator/step-registry/redhat-et/microshift/e2e/wait-for-deployment-up/OWNERS
  ci-operator/step-registry/redhat-et/microshift/e2e/wait-for-deployment-up/redhat-et-microshift-e2e-wait-for-deployment-up-commands.sh
  ci-operator/step-registry/redhat-et/microshift/e2e/wait-for-deployment-up/redhat-et-microshift-e2e-wait-for-deployment-up-ref.metadata.json
  ci-operator/step-registry/redhat-et/microshift/e2e/wait-for-deployment-up/redhat-et-microshift-e2e-wait-for-deployment-up-ref.yaml
Labels: lgtm, approved

#23296 Add e2e-metal-ipi-serial into origin repo
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
Labels: lgtm, approved

#23305 [CVP-2489] Increase the wait time for custom operator scorecard tests
  ci-operator/step-registry/optional-operators/cvp-common/scorecard/optional-operators-cvp-common-scorecard-commands.sh
Labels: lgtm, approved

#23332 extract ipi-vsphere-proxy installation as a chain
  ci-operator/step-registry/ipi/vsphere/proxy/OWNERS
  ci-operator/step-registry/ipi/vsphere/proxy/ipi-vsphere-proxy-chain.metadata.json
  ci-operator/step-registry/ipi/vsphere/proxy/ipi-vsphere-proxy-chain.yaml
  ci-operator/step-registry/openshift/e2e/vsphere/proxy/openshift-e2e-vsphere-proxy-workflow.yaml
Labels: lgtm, approved

#23340 make checkconfig: validate sharded Prow config
  Makefile
Labels: lgtm, approved

#22956 Change metal-ipi workflows to new metal-ipi steps
  ci-operator/config/openshift/baremetal-runtimecfg/openshift-baremetal-runtimecfg-master.yaml
  ci-operator/config/openshift/baremetal-runtimecfg/openshift-baremetal-runtimecfg-release-4.10.yaml
  ci-operator/config/openshift/baremetal-runtimecfg/openshift-baremetal-runtimecfg-release-4.8.yaml
  ci-operator/config/openshift/baremetal-runtimecfg/openshift-baremetal-runtimecfg-release-4.9.yaml
Labels: lgtm, approved

#23324 ci-operator/config/openshift/release: Monthly intervals for 4.(y < 5) jobs
  ci-operator/config/openshift/release/openshift-release-master__ci-4.1.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.2.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.3.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.4-upgrade-from-stable-4.4.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.4.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.5-upgrade-from-stable-4.4.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.1.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.2.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.3.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.4.yaml
  ci-operator/config/openshift/release/openshift-release-master__okd-4.3.yaml
  ci-operator/config/openshift/release/openshift-release-master__okd-4.4.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: lgtm, approved

#23344 allow job-trigger-controller-manager to update prpqr objects
  clusters/app.ci/job-trigger-controller-manager/admin_job-trigger-controller-manager_rbac.yaml
Labels: lgtm, approved

#23306 Add runningCount for 4.9 ClusterPool
  clusters/hive/pools/openshift-ci/ci-ocp-4-9-0-amd64-aws-us-west-1_clusterpool.yaml
Labels: lgtm, approved

#23346 [DPTP-2605] kubevirt-template-validator: enable trigger plugin
  core-services/prow/02_config/kubevirt/kubevirt-template-validator/_pluginconfig.yaml
Labels: lgtm, approved

#23323 Hive: Disable managed DNS for e2e-pool
  ci-operator/config/openshift/hive/openshift-hive-master.yaml
Labels: lgtm, approved

#22968 Change metal-ipi workflows to new metal-ipi steps
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.10.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.8.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.9.yaml
Labels: lgtm, approved

#23356 stackrox: update OWNERS
  ci-operator/config/stackrox/rox-ci-image-openshift-ci-mirror/OWNERS
  ci-operator/config/stackrox/rox-openshift-ci-mirror/OWNERS
  ci-operator/jobs/stackrox/rox-ci-image-openshift-ci-mirror/OWNERS
  ci-operator/jobs/stackrox/rox-openshift-ci-mirror/OWNERS
  clusters/app.ci/registry-access/stackrox/OWNERS
  core-services/prow/02_config/stackrox/rox-ci-image-openshift-ci-mirror/OWNERS
  core-services/prow/02_config/stackrox/rox-openshift-ci-mirror/OWNERS
Labels: lgtm, approved

#23348 stackrox/rox-openshift-ci-mirror: fix prow config
  core-services/prow/02_config/stackrox/rox-openshift-ci-mirror/_prowconfig.yaml
Labels: lgtm, approved

#23350 Stop using empty string as label
  core-services/prow/02_config/openshift/cluster-monitoring-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/configmap-reload/_pluginconfig.yaml
  core-services/prow/02_config/openshift/grafana/_pluginconfig.yaml
  core-services/prow/02_config/openshift/k8s-prometheus-adapter/_pluginconfig.yaml
  core-services/prow/02_config/openshift/kube-state-metrics/_pluginconfig.yaml
  core-services/prow/02_config/openshift/node_exporter/_pluginconfig.yaml
  core-services/prow/02_config/openshift/openshift-state-metrics/_pluginconfig.yaml
  core-services/prow/02_config/openshift/prom-label-proxy/_pluginconfig.yaml
  core-services/prow/02_config/openshift/prometheus-alertmanager/_pluginconfig.yaml
  core-services/prow/02_config/openshift/prometheus-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/prometheus/_pluginconfig.yaml
  core-services/prow/02_config/openshift/telemeter/_pluginconfig.yaml
  core-services/prow/02_config/openshift/thanos/_pluginconfig.yaml
Labels: lgtm, approved

#23352 [DPTP-2605] Fix approve plugin's config
  core-services/prow/02_config/openshift-priv/containernetworking-plugins/_prowconfig.yaml
  core-services/prow/02_config/openshift-priv/descheduler/_prowconfig.yaml
  core-services/prow/02_config/openshift-priv/multus-admission-controller/_prowconfig.yaml
  core-services/prow/02_config/openshift-priv/ocp-release-operator-sdk/_prowconfig.yaml
  core-services/prow/02_config/openshift/containernetworking-plugins/_prowconfig.yaml
  core-services/prow/02_config/openshift/descheduler/_prowconfig.yaml
  core-services/prow/02_config/openshift/multus-admission-controller/_prowconfig.yaml
Labels: lgtm, approved

#23354 [DPTP-2605] Fix bugzilla plugin's config
  core-services/prow/02_config/netobserv/network-observability-operator/_prowconfig.yaml
  core-services/prow/02_config/openshift-assisted/assisted-events-scrap/_pluginconfig.yaml
  core-services/prow/02_config/openshift-assisted/assisted-installer-deployment/_pluginconfig.yaml
  core-services/prow/02_config/openshift/dynamic-plugin-sdk/_prowconfig.yaml
  core-services/prow/02_config/openshift/hac-dev/_prowconfig.yaml
  core-services/prow/02_config/openshift/hac-infra/_prowconfig.yaml
  core-services/prow/02_config/openshift/pagerduty-short-circuiter/_prowconfig.yaml
Labels: lgtm, approved

#23357 Add presubmit job to oc-mirror
  core-services/prow/02_config/openshift/oc-mirror/prerelease.yaml
Labels: lgtm, approved

#23177 machine-os-images: Add an output image
  ci-operator/config/openshift/machine-os-images/openshift-machine-os-images-main.yaml
  ci-operator/jobs/openshift/machine-os-images/openshift-machine-os-images-main-presubmits.yaml
Labels: lgtm, approved

#23359 stackrox: switch to a cluster pool
  ci-operator/config/stackrox/rox-openshift-ci-mirror/stackrox-rox-openshift-ci-mirror-master.yaml
  ci-operator/jobs/stackrox/rox-openshift-ci-mirror/stackrox-rox-openshift-ci-mirror-master-presubmits.yaml
Labels: lgtm, approved

#23290 OCPQE-6636: Refactor cucushift e2e tests (continue-4)
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.9.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__ocp-4.9.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
  ci-operator/step-registry/cucushift/aws/ipi/cucushift-aws-ipi-commands.sh
  ci-operator/step-registry/cucushift/aws/ipi/cucushift-aws-ipi-ref.metadata.json
  ci-operator/step-registry/cucushift/aws/ipi/cucushift-aws-ipi-ref.yaml
  ci-operator/step-registry/cucushift/aws/ipi/cucushift-aws-ipi-workflow.metadata.json
  ci-operator/step-registry/cucushift/aws/ipi/cucushift-aws-ipi-workflow.yaml
Labels: lgtm, approved

#22957 Change metal-ipi workflows to new metal-ipi steps
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-master.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.10.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.7.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.8.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.9.yaml
Labels: lgtm, approved

#23052 Inject telemeter image into the benchmark job
  ci-operator/config/openshift/telemeter/openshift-telemeter-master.yaml
  ci-operator/config/openshift/telemeter/openshift-telemeter-release-4.10.yaml
  ci-operator/config/openshift/telemeter/openshift-telemeter-release-4.6.yaml
  ci-operator/config/openshift/telemeter/openshift-telemeter-release-4.7.yaml
  ci-operator/config/openshift/telemeter/openshift-telemeter-release-4.8.yaml
  ci-operator/config/openshift/telemeter/openshift-telemeter-release-4.9.yaml
Labels: lgtm, approved

#23165 Azure File: optional CSI workflow and unit test fix
  ci-operator/config/openshift/azure-file-csi-driver-operator/openshift-azure-file-csi-driver-operator-main.yaml
  ci-operator/config/openshift/azure-file-csi-driver-operator/openshift-azure-file-csi-driver-operator-release-4.10.yaml
  ci-operator/config/openshift/azure-file-csi-driver/openshift-azure-file-csi-driver-master.yaml
  ci-operator/config/openshift/azure-file-csi-driver/openshift-azure-file-csi-driver-release-4.10.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-master.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.10.yaml
  ci-operator/jobs/openshift/azure-file-csi-driver-operator/openshift-azure-file-csi-driver-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/azure-file-csi-driver-operator/openshift-azure-file-csi-driver-operator-release-4.10-presubmits.yaml
  ci-operator/jobs/openshift/azure-file-csi-driver/openshift-azure-file-csi-driver-master-presubmits.yaml
  ci-operator/jobs/openshift/azure-file-csi-driver/openshift-azure-file-csi-driver-release-4.10-presubmits.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.10-presubmits.yaml
Labels: lgtm, approved

#22993 Fix vSphere storage jobs
  ci-operator/config/openshift/vmware-vsphere-csi-driver-operator/openshift-vmware-vsphere-csi-driver-operator-master.yaml
  ci-operator/config/openshift/vmware-vsphere-csi-driver-operator/openshift-vmware-vsphere-csi-driver-operator-release-4.10.yaml
  ci-operator/config/openshift/vmware-vsphere-csi-driver/openshift-vmware-vsphere-csi-driver-master.yaml
  ci-operator/config/openshift/vmware-vsphere-csi-driver/openshift-vmware-vsphere-csi-driver-release-4.10.yaml
  ci-operator/jobs/openshift/vmware-vsphere-csi-driver-operator/openshift-vmware-vsphere-csi-driver-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/vmware-vsphere-csi-driver-operator/openshift-vmware-vsphere-csi-driver-operator-release-4.10-presubmits.yaml
  ci-operator/jobs/openshift/vmware-vsphere-csi-driver/openshift-vmware-vsphere-csi-driver-master-presubmits.yaml
  ci-operator/jobs/openshift/vmware-vsphere-csi-driver/openshift-vmware-vsphere-csi-driver-release-4.10-presubmits.yaml
  ci-operator/step-registry/openshift/e2e/test/openshift-e2e-test-commands.sh
  ci-operator/step-registry/openshift/e2e/vsphere/csi/migration/OWNERS
  ci-operator/step-registry/openshift/e2e/vsphere/csi/migration/openshift-e2e-vsphere-csi-migration-workflow.metadata.json
  ci-operator/step-registry/openshift/e2e/vsphere/csi/migration/openshift-e2e-vsphere-csi-migration-workflow.yaml
Labels: lgtm, approved

#23381 Generate explicit brancher stanza on cluster-init jobs
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
Labels: lgtm, approved

#23301 remove e2e-aws-jenkins from jenkins plugin e2es; switch login plugin to sync plugin e2e
  ci-operator/config/openshift/jenkins-client-plugin/openshift-jenkins-client-plugin-master.yaml
  ci-operator/config/openshift/jenkins-client-plugin/openshift-jenkins-client-plugin-release-4.10.yaml
  ci-operator/config/openshift/jenkins-openshift-login-plugin/openshift-jenkins-openshift-login-plugin-master.yaml
  ci-operator/config/openshift/jenkins-openshift-login-plugin/openshift-jenkins-openshift-login-plugin-release-4.10.yaml
  ci-operator/config/openshift/jenkins-sync-plugin/openshift-jenkins-sync-plugin-master.yaml
  ci-operator/config/openshift/jenkins-sync-plugin/openshift-jenkins-sync-plugin-release-4.10.yaml
  ci-operator/jobs/openshift/jenkins-client-plugin/openshift-jenkins-client-plugin-master-presubmits.yaml
  ci-operator/jobs/openshift/jenkins-client-plugin/openshift-jenkins-client-plugin-release-4.10-presubmits.yaml
  ci-operator/jobs/openshift/jenkins-openshift-login-plugin/openshift-jenkins-openshift-login-plugin-master-presubmits.yaml
  ci-operator/jobs/openshift/jenkins-openshift-login-plugin/openshift-jenkins-openshift-login-plugin-release-4.10-presubmits.yaml
  ci-operator/jobs/openshift/jenkins-sync-plugin/openshift-jenkins-sync-plugin-master-presubmits.yaml
  ci-operator/jobs/openshift/jenkins-sync-plugin/openshift-jenkins-sync-plugin-release-4.10-presubmits.yaml
Labels: lgtm, approved

#23295 Add QE cherry-pick approvers for OCP on OSP repos
  core-services/prow/02_config/openshift/cloud-provider-openstack/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-api-provider-openstack/_pluginconfig.yaml
  core-services/prow/02_config/openshift/csi-driver-manila-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/csi-driver-nfs/_pluginconfig.yaml
  core-services/prow/02_config/openshift/installer/_pluginconfig.yaml
  core-services/prow/02_config/openshift/kuryr-kubernetes/_pluginconfig.yaml
  core-services/prow/02_config/openshift/machine-api-provider-openstack/_pluginconfig.yaml
  core-services/prow/02_config/openshift/openstack-cinder-csi-driver-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/openstack-test/_pluginconfig.yaml
Labels: lgtm, approved

#22870 Change metal-ipi workflows to new metal-ipi steps
  ci-operator/config/openshift/cluster-api-provider-baremetal/openshift-cluster-api-provider-baremetal-master.yaml
  ci-operator/config/openshift/cluster-api-provider-baremetal/openshift-cluster-api-provider-baremetal-release-4.10.yaml
  ci-operator/config/openshift/cluster-api-provider-baremetal/openshift-cluster-api-provider-baremetal-release-4.8.yaml
  ci-operator/config/openshift/cluster-api-provider-baremetal/openshift-cluster-api-provider-baremetal-release-4.9.yaml
Labels: lgtm, approved

#23376 [CVP-2275] Set the serviceaccount explicitly for custom scorecard tests
  ci-operator/step-registry/optional-operators/cvp-common/scorecard/optional-operators-cvp-common-scorecard-commands.sh
Labels: lgtm, approved
