Repository openshift/release, pull requests merged in 2021-06, with the labels that each got.

#18930 Revert "assisted-service: use scratch image for bundle"
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master.yaml
Labels: approved, lgtm

#18932 Update metal-ipi ironic-agent jobs definitions
  ci-operator/config/openshift/ironic-agent-image/openshift-ironic-agent-image-main.yaml
  ci-operator/config/openshift/ironic-agent-image/openshift-ironic-agent-image-main__prevalidation.yaml
Labels: approved, lgtm

#18820 Disable openstack release 4.3 periodics
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
Labels: approved, lgtm

#18935 (chore) [thanos] bump node used in react test to 12.22.1
  ci-operator/config/openshift/thanos/openshift-thanos-master.yaml
Labels: approved, lgtm

#18941 Add 4.9 TRT members to technical-release-team alias
  OWNERS_ALIASES
Labels: approved, lgtm

#18913 use one workflow for ztp builds
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-ocm-2.3.yaml
  ci-operator/step-registry/baremetalds/assisted/operator/ztp/baremetalds-assisted-operator-ztp-commands.sh
  ci-operator/step-registry/baremetalds/assisted/operator/ztp/baremetalds-assisted-operator-ztp-workflow.metadata.json
  ci-operator/step-registry/baremetalds/assisted/operator/ztp/baremetalds-assisted-operator-ztp-workflow.yaml
Labels: approved, lgtm

#18937 Add 4.9 CI release jobs
  ci-operator/config/openshift/release/openshift-release-master__ci-4.9-upgrade-from-stable-4.8-from-stable-4.7.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.9-upgrade-from-stable-4.8.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.9.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: approved, lgtm

#18938 Revert "work with default version (4.8.0-fc.3) for now"
  ci-operator/step-registry/baremetalds/assisted/operator/ztp/baremetalds-assisted-operator-ztp-commands.sh
Labels: approved, lgtm

#18849 periodic-installer-s390x job changes
  ci-operator/jobs/openshift/release/openshift-release-release-4.8-periodics.yaml
  core-services/release-controller/_releases/release-ocp-4.8-s390x.json
  core-services/template-deprecation/_allowlist.yaml
Labels: approved, lgtm

#18925 Skip more tests and miscelaneous improvement
  ci-operator/config/kata-containers/kata-containers/kata-containers-kata-containers-main.yaml
Labels: approved, lgtm

#18952 Adding Kafkas 0.23 CI jobs
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.23__47.yaml
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.23__48.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.23-periodics.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.23-postsubmits.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.23-presubmits.yaml
Labels: approved, lgtm

#18838 shiftstack/ci-configs: Add repository to Prow
  ci-operator/config/shiftstack/OWNERS
  ci-operator/config/shiftstack/ci-configs/OWNERS
  ci-operator/config/shiftstack/ci-configs/shiftstack-ci-configs-main.yaml
  ci-operator/jobs/shiftstack/OWNERS
  ci-operator/jobs/shiftstack/ci-configs/OWNERS
  ci-operator/jobs/shiftstack/ci-configs/shiftstack-ci-configs-main-presubmits.yaml
  ci-operator/step-registry/openstack/provision/OWNERS
  ci-operator/step-registry/openstack/provision/virtual/OWNERS
  ci-operator/step-registry/openstack/provision/virtual/openstack-provision-virtual-commands.sh
  ci-operator/step-registry/openstack/provision/virtual/openstack-provision-virtual-ref.metadata.json
  ci-operator/step-registry/openstack/provision/virtual/openstack-provision-virtual-ref.yaml
  ci-operator/step-registry/openstack/provision/virtual/openstack-provision-virtual-workflow.metadata.json
  ci-operator/step-registry/openstack/provision/virtual/openstack-provision-virtual-workflow.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
  core-services/prow/02_config/shiftstack/OWNERS
  core-services/prow/02_config/shiftstack/ci-configs/OWNERS
  core-services/prow/02_config/shiftstack/ci-configs/_pluginconfig.yaml
Labels: approved, lgtm

#18945 CI enablement for the 0.23 branch
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.23__47.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.23__48.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.23-periodics.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.23-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.23-presubmits.yaml
  core-services/image-mirroring/knative/mapping_knative_v0_23_quay
Labels: approved, lgtm

#18950 Alert while the triggered Prow jobs has been accumulating
  clusters/app.ci/prow-monitoring/mixins/_prometheus/prow_alerts.libsonnet
  clusters/app.ci/prow-monitoring/mixins/prometheus_out/prometheus-prow-rules_prometheusrule.yaml
Labels: approved, lgtm

#18951 Add a distinct branch protector job for the openshift org
  ci-operator/jobs/infra-periodics.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: approved, lgtm

#18928 gather logs URL, infraenv and BMH objects
  ci-operator/step-registry/baremetalds/assisted/operator/gather/baremetalds-assisted-operator-gather-commands.sh
Labels: approved, lgtm

#18960 Increasing timeout for our jobs on OCP CI platform
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next__47.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next__48.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.23__47.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.23__48.yaml
Labels: approved, lgtm

#18947 Add openshift/assisted-test-infra system-test-periodic and system-test-operator-periodic
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-periodics.yaml
Labels: approved, lgtm

#18284 Enable optional disruptive job for machine approver
  ci-operator/config/openshift/cluster-machine-approver/openshift-cluster-machine-approver-master.yaml
  ci-operator/jobs/openshift/cluster-machine-approver/openshift-cluster-machine-approver-master-presubmits.yaml
Labels: approved, lgtm

#18954 Bug 1963912: vSphere - network segment name change
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#18948 add openshift/kubevirt-csi-driver repo
  ci-operator/config/openshift/kubevirt-csi-driver/OWNERS
  ci-operator/config/openshift/kubevirt-csi-driver/openshift-kubevirt-csi-driver-master.yaml
  ci-operator/jobs/openshift/kubevirt-csi-driver/OWNERS
  ci-operator/jobs/openshift/kubevirt-csi-driver/openshift-kubevirt-csi-driver-master-postsubmits.yaml
  ci-operator/jobs/openshift/kubevirt-csi-driver/openshift-kubevirt-csi-driver-master-presubmits.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/openshift/kubevirt-csi-driver/OWNERS
  core-services/prow/02_config/openshift/kubevirt-csi-driver/_pluginconfig.yaml
  core-services/prow/02_config/openshift/kubevirt-csi-driver/_prowconfig.yaml
Labels: approved, lgtm

#18953 Update community.okd config to account for the org move
  ci-operator/config/openshift/community.okd/OWNERS
  ci-operator/config/openshift/community.okd/openshift-community.okd-main.yaml
  ci-operator/jobs/openshift/community.okd/OWNERS
  ci-operator/jobs/openshift/community.okd/openshift-community.okd-main-presubmits.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
  core-services/prow/02_config/ansible-collections/community.okd/_pluginconfig.yaml
  core-services/prow/02_config/ansible-collections/community.okd/_prowconfig.yaml
  core-services/prow/02_config/openshift/community.okd/OWNERS
  core-services/prow/02_config/openshift/community.okd/_pluginconfig.yaml
  core-services/prow/02_config/openshift/community.okd/_prowconfig.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: approved, lgtm

#18712 Remove gluster and passing tests from baremetal skip list
  ci-operator/step-registry/baremetalds/e2e/test/baremetalds-e2e-test-ref.yaml
Labels: approved, lgtm

#18963 [rhd-sbo] Move daily cluster slack notifications to #forum-appsvc-notify channel
  ci-operator/jobs/redhat-developer/service-binding-operator/redhat-developer-service-binding-operator-master-periodics.yaml
Labels: approved, lgtm

#18818 enable require_self_approval for openshift/odo repos
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#18856 Change permissions of extracted operator bundle
  ci-operator/step-registry/optional-operators/cvp-common/scorecard/optional-operators-cvp-common-scorecard-commands.sh
Labels: approved, lgtm

#18966 origin/centos:7 -> openshift/centos:7
  ci-operator/step-registry/upi/conf/ibmz-eco/upi-conf-ibmz-eco-ref.yaml
  clusters/app.ci/supplemental-ci-images/sshd_build.yaml
Labels: approved, lgtm

#18375 Add configurations and Jobs for metallb
  ci-operator/config/openshift/metallb/OWNERS
  ci-operator/config/openshift/metallb/openshift-metallb-master.yaml
  ci-operator/jobs/openshift/metallb/OWNERS
  ci-operator/jobs/openshift/metallb/openshift-metallb-master-postsubmits.yaml
  ci-operator/jobs/openshift/metallb/openshift-metallb-master-presubmits.yaml
Labels: approved, lgtm

#18944 Bump builders to 1.16
  ci-operator/config/openshift/ocp-release-operator-sdk/openshift-ocp-release-operator-sdk-master.yaml
Labels: approved, lgtm

#18970 ocm: remove amd64 linux image references
  ci-operator/config/open-cluster-management/multicloud-operators-application/open-cluster-management-multicloud-operators-application-main.yaml
  ci-operator/config/open-cluster-management/multicloud-operators-application/open-cluster-management-multicloud-operators-application-release-2.3.yaml
  ci-operator/config/open-cluster-management/multicloud-operators-channel/open-cluster-management-multicloud-operators-channel-main.yaml
  ci-operator/config/open-cluster-management/multicloud-operators-channel/open-cluster-management-multicloud-operators-channel-release-2.3.yaml
  ci-operator/config/open-cluster-management/multicloud-operators-deployable/open-cluster-management-multicloud-operators-deployable-main.yaml
  ci-operator/config/open-cluster-management/multicloud-operators-deployable/open-cluster-management-multicloud-operators-deployable-release-2.3.yaml
  ci-operator/config/open-cluster-management/multicloud-operators-placementrule/open-cluster-management-multicloud-operators-placementrule-main.yaml
  ci-operator/config/open-cluster-management/multicloud-operators-placementrule/open-cluster-management-multicloud-operators-placementrule-release-2.3.yaml
  ci-operator/config/open-cluster-management/multicloud-operators-subscription-release/open-cluster-management-multicloud-operators-subscription-release-main.yaml
  ci-operator/config/open-cluster-management/multicloud-operators-subscription-release/open-cluster-management-multicloud-operators-subscription-release-release-2.3.yaml
  ci-operator/config/open-cluster-management/multicloud-operators-subscription/open-cluster-management-multicloud-operators-subscription-main.yaml
  ci-operator/config/open-cluster-management/multicloud-operators-subscription/open-cluster-management-multicloud-operators-subscription-release-2.3.yaml
Labels: approved, lgtm

#18640 Bug 1910113: disable 4.5 rollback jobs as they are permfailing due to kubelet limitations
  ci-operator/config/openshift/release/openshift-release-master__ci-4.4-upgrade-from-stable-4.4.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.4.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  core-services/release-controller/_releases/release-ocp-4.4-ci.json
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#18323 openstack: Add e2e-openstack-ipi to origin
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.6.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.7.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.8.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.9.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.8-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.9-presubmits.yaml
Labels: approved, lgtm

#18975 CI-Tools: Get build_root from repository
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
  ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
  ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
Labels: approved, lgtm

#18972 Rely on periodic peribolos only
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
Labels: approved, lgtm

#18982 Revert "Add configurations and Jobs for metallb"
  ci-operator/config/openshift-priv/metallb/openshift-priv-metallb-master.yaml
  ci-operator/config/openshift-priv/metallb/openshift-priv-metallb-release-4.8.yaml
  ci-operator/config/openshift-priv/metallb/openshift-priv-metallb-release-4.9.yaml
  ci-operator/config/openshift/metallb/OWNERS
  ci-operator/config/openshift/metallb/openshift-metallb-master.yaml
  ci-operator/config/openshift/metallb/openshift-metallb-release-4.8.yaml
  ci-operator/config/openshift/metallb/openshift-metallb-release-4.9.yaml
  ci-operator/jobs/openshift-priv/metallb/openshift-priv-metallb-master-postsubmits.yaml
  ci-operator/jobs/openshift-priv/metallb/openshift-priv-metallb-master-presubmits.yaml
  ci-operator/jobs/openshift-priv/metallb/openshift-priv-metallb-release-4.8-postsubmits.yaml
  ci-operator/jobs/openshift-priv/metallb/openshift-priv-metallb-release-4.8-presubmits.yaml
  ci-operator/jobs/openshift-priv/metallb/openshift-priv-metallb-release-4.9-postsubmits.yaml
  ci-operator/jobs/openshift-priv/metallb/openshift-priv-metallb-release-4.9-presubmits.yaml
  ci-operator/jobs/openshift/metallb/OWNERS
  ci-operator/jobs/openshift/metallb/openshift-metallb-master-postsubmits.yaml
  ci-operator/jobs/openshift/metallb/openshift-metallb-master-presubmits.yaml
  ci-operator/jobs/openshift/metallb/openshift-metallb-release-4.8-postsubmits.yaml
  ci-operator/jobs/openshift/metallb/openshift-metallb-release-4.8-presubmits.yaml
  ci-operator/jobs/openshift/metallb/openshift-metallb-release-4.9-postsubmits.yaml
  ci-operator/jobs/openshift/metallb/openshift-metallb-release-4.9-presubmits.yaml
Labels: approved, lgtm

#18957 e2e-openstack-ipi: Gather openstack extra data
  ci-operator/step-registry/ipi/openstack/post/ipi-openstack-post-chain.yaml
  ci-operator/step-registry/openstack/gather/OWNERS
  ci-operator/step-registry/openstack/gather/openstack-gather-commands.sh
  ci-operator/step-registry/openstack/gather/openstack-gather-ref.metadata.json
  ci-operator/step-registry/openstack/gather/openstack-gather-ref.yaml
Labels: approved, lgtm

#18987 Use ARTIFACTS_DIR in openshift/assisted-installer-agent unit-test job
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master.yaml
Labels: approved, lgtm

#18870 Configure real-time workers with tuned profile
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.6.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.7.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.8.yaml
  ci-operator/step-registry/openshift/e2e/gcp/realtime/OWNERS
  ci-operator/step-registry/openshift/e2e/gcp/realtime/openshift-e2e-gcp-realtime-workflow.metadata.json
  ci-operator/step-registry/openshift/e2e/gcp/realtime/openshift-e2e-gcp-realtime-workflow.yaml
  ci-operator/step-registry/optional-operators/configure-realtime-tuned-profile/OWNERS
  ci-operator/step-registry/optional-operators/configure-realtime-tuned-profile/optional-operators-configure-realtime-tuned-profile-commands.sh
  ci-operator/step-registry/optional-operators/configure-realtime-tuned-profile/optional-operators-configure-realtime-tuned-profile-ref.metadata.json
  ci-operator/step-registry/optional-operators/configure-realtime-tuned-profile/optional-operators-configure-realtime-tuned-profile-ref.yaml
Labels: approved, lgtm

#18989 openstack-gather: Fix order of steps
  ci-operator/step-registry/ipi/openstack/post/ipi-openstack-post-chain.yaml
  ci-operator/step-registry/openstack/gather/openstack-gather-ref.yaml
Labels: approved, lgtm

#18968 Remove isTag centos:7 in origin
  clusters/app.ci/supplemental-ci-images/base-ci-images/images-origin.yaml
Labels: approved, lgtm

#18984 specify specs for extra nodes only, instead for all workers
  ci-operator/step-registry/baremetalds/assisted/operator/ztp/baremetalds-assisted-operator-ztp-workflow.yaml
Labels: approved, lgtm

#18991 bp: throttle openshift's branchprotector more
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm

#18684 vsphere upgrade - decrease interval
  ci-operator/config/openshift/release/openshift-release-master__ci-4.6-upgrade-from-stable-4.5.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.7-upgrade-from-stable-4.6.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.8-upgrade-from-stable-4.7.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: approved, lgtm

#18980 remove amd64 instance
  ci-operator/config/open-cluster-management/application-ui/open-cluster-management-application-ui-main.yaml
  ci-operator/config/open-cluster-management/application-ui/open-cluster-management-application-ui-release-2.3.yaml
  ci-operator/config/open-cluster-management/console-api/open-cluster-management-console-api-main.yaml
  ci-operator/config/open-cluster-management/console-api/open-cluster-management-console-api-release-2.3.yaml
  ci-operator/jobs/open-cluster-management/application-ui/open-cluster-management-application-ui-release-2.3-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/console-api/open-cluster-management-console-api-release-2.3-postsubmits.yaml
Labels: approved, lgtm

#18815 Serverless: Period jobs on OCP 4.8 nightly
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main__4.8.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main-periodics.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main-postsubmits.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main-presubmits.yaml
Labels: approved, lgtm

#18997 Revert "temporarily change the cron time of the prowjob dispatch periodic job"
  ci-operator/jobs/infra-periodics.yaml
Labels: approved, lgtm

#18999 shellcheck: Add git
  clusters/app.ci/supplemental-ci-images/validation-images/shellcheck/Dockerfile
Labels: approved, lgtm

#18979 Mirror ci images instead of importing
  ci-operator/jobs/infra-image-mirroring.yaml
  clusters/app.ci/supplemental-ci-images/ansible-runner-imagestream.yaml
  clusters/app.ci/supplemental-ci-images/ansible-runner-ovirt-imagestream.yaml
  clusters/app.ci/supplemental-ci-images/azure/base-images/plugin-base.yaml
  clusters/app.ci/supplemental-ci-images/base-ci-images/images-ocp.yaml
  clusters/app.ci/supplemental-ci-images/base-ci-images/images-origin.yaml
  clusters/app.ci/supplemental-ci-images/boskos.yaml
  clusters/app.ci/supplemental-ci-images/coreos/coreos-centos8-buildroot.yaml
  clusters/app.ci/supplemental-ci-images/coreos/coreos-stream8-buildroot.yaml
  clusters/app.ci/supplemental-ci-images/coreos/cosa-upstream-is.yaml
  clusters/app.ci/supplemental-ci-images/coreos/fcos-builroot.yaml
  clusters/app.ci/supplemental-ci-images/coreos/fedora-is.yaml
  clusters/app.ci/supplemental-ci-images/cvp-operator-scorecard.yaml
  clusters/app.ci/supplemental-ci-images/hyperconverged-cluster-index.yaml
  clusters/app.ci/supplemental-ci-images/ibm-roks-toolkit-testing-is.yaml
  clusters/app.ci/supplemental-ci-images/insights-operator-tests.yaml
  clusters/app.ci/supplemental-ci-images/ocpmetal-postgresql-12-centos7.yaml
  clusters/app.ci/supplemental-ci-images/operatorhub-index.yaml
  clusters/app.ci/supplemental-ci-images/ovirt/prfinder-ovirt-imagestream.yaml
  clusters/app.ci/supplemental-ci-images/powervs/container-host.yaml
  clusters/app.ci/supplemental-ci-images/redhat-operator-index.yaml
  clusters/app.ci/supplemental-ci-images/rhscl-nodejs10.yaml
  clusters/app.ci/supplemental-ci-images/rhscl-rust.yaml
  clusters/build-clusters/01_cluster/ci/origin-release_pipeline_template.yaml
  core-services/image-mirroring/supplemental-ci-images/OWNERS
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_azure
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_ci
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_coreos
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_ocp
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_ocp_kni
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_ocp_on_powervs
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_openshift
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_origin
Labels: approved, lgtm

#18998 Update cloud-provider-aws Dockerfile
  ci-operator/config/openshift/cloud-provider-aws/openshift-cloud-provider-aws-master.yaml
Labels: approved, lgtm

#18959 e2e-openstack-ipi: Use self-managed clouds.yaml
  ci-operator/step-registry/ipi/conf/openstack/ipi-conf-openstack-ref.yaml
  ci-operator/step-registry/ipi/deprovision/deprovision/ipi-deprovision-deprovision-commands.sh
  ci-operator/step-registry/ipi/install/install/ipi-install-install-commands.sh
  ci-operator/step-registry/openshift/e2e/openstack/minimal/openshift-e2e-openstack-minimal-workflow.yaml
  ci-operator/step-registry/openshift/manifests/openstack/openshift-manifests-openstack-workflow.yaml
  ci-operator/step-registry/openstack/conf/createfips/openstack-conf-createfips-commands.sh
  ci-operator/step-registry/openstack/conf/createfips/openstack-conf-createfips-ref.yaml
  ci-operator/step-registry/openstack/conf/exportcindercredentials/openstack-conf-exportcindercredentials-commands.sh
  ci-operator/step-registry/openstack/conf/exportcindercredentials/openstack-conf-exportcindercredentials-ref.yaml
  ci-operator/step-registry/openstack/deprovision/deletefips/openstack-deprovision-deletefips-commands.sh
  ci-operator/step-registry/openstack/test/manifests/openstack-test-manifests-commands.sh
  ci-operator/step-registry/openstack/test/manifests/openstack-test-manifests-ref.yaml
Labels: approved, lgtm

#19002 Make the shellcheck buildable again
  clusters/app.ci/supplemental-ci-images/validation-images/shellcheck/Dockerfile
  clusters/app.ci/supplemental-ci-images/validation-images/shellcheck/shellcheck.yaml
Labels: approved, lgtm

#18976 Remove non-apps auth hook and crier
  clusters/app.ci/prow/03_deployment/crier.yaml
  clusters/app.ci/prow/03_deployment/hook.yaml
Labels: approved, lgtm

#19005 Remove alerts for non-apps hook
  clusters/app.ci/prow-monitoring/additional-scrape-configs_secret.yaml
  clusters/app.ci/prow-monitoring/mixins/_prometheus/ci_absent_alerts.libsonnet
  clusters/app.ci/prow-monitoring/mixins/prometheus_out/prometheus-prow-rules_prometheusrule.yaml
Labels: approved, lgtm

#19006 Fix: make stage pipelines actually use stage config
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: approved, lgtm

#18990 shiftstack-ci: Add repository
  ci-operator/config/shiftstack/shiftstack-ci/OWNERS
  ci-operator/config/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main.yaml
  ci-operator/jobs/shiftstack/shiftstack-ci/OWNERS
  ci-operator/jobs/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main-presubmits.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
  core-services/prow/02_config/shiftstack/shiftstack-ci/OWNERS
  core-services/prow/02_config/shiftstack/shiftstack-ci/_pluginconfig.yaml
Labels: approved, lgtm

#19004 Fix job/periodic-image-mirroring-supplemental-ci-images
  ci-operator/jobs/infra-image-mirroring.yaml
  core-services/ci-secret-bootstrap/_config.yaml
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_ci
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_ocp
  core-services/image-mirroring/supplemental-ci-private-images-redhat/mapping_supplemental_ci_private_images_redhat_ci
Labels: approved, lgtm

#18995 Add image mirroring for aws and azure cloud controller managers
  core-services/image-mirroring/openshift/mapping_origin_4_8
  core-services/image-mirroring/openshift/mapping_origin_4_9
Labels: approved, lgtm

#19012 Add configurations and Jobs for metallb repo
  ci-operator/config/openshift/metallb/OWNERS
  ci-operator/config/openshift/metallb/openshift-metallb-main.yaml
  ci-operator/jobs/openshift/metallb/OWNERS
  ci-operator/jobs/openshift/metallb/openshift-metallb-main-presubmits.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
  core-services/prow/02_config/openshift/metallb/OWNERS
  core-services/prow/02_config/openshift/metallb/_pluginconfig.yaml
Labels: approved, lgtm

#18983 update management-ingress to use multiarch go builder
  ci-operator/config/open-cluster-management/management-ingress/open-cluster-management-management-ingress-main.yaml
  ci-operator/config/open-cluster-management/management-ingress/open-cluster-management-management-ingress-release-2.3.yaml
  ci-operator/jobs/open-cluster-management/management-ingress/open-cluster-management-management-ingress-release-2.3-postsubmits.yaml
Labels: approved, lgtm

#19017 ComplianceAsCode/ocp4e2e: Add rhcos4 moderate to the test matrix
  ci-operator/config/ComplianceAsCode/ocp4e2e/ComplianceAsCode-ocp4e2e-main.yaml
  ci-operator/jobs/ComplianceAsCode/ocp4e2e/ComplianceAsCode-ocp4e2e-main-presubmits.yaml
Labels: approved, lgtm

#19021 Add addon parameter for ocs-converged ci job
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: approved, lgtm

#19023 using the new --case-id option instead of the deprecated one
  ci-operator/step-registry/baremetalds/assisted/gather/baremetalds-assisted-gather-commands.sh
  ci-operator/step-registry/baremetalds/assisted/operator/gather/baremetalds-assisted-operator-gather-commands.sh
  ci-operator/step-registry/baremetalds/sno/gather/baremetalds-sno-gather-commands.sh
Labels: approved, lgtm

#18943 Add CI config for RHMI operator branch rhoam-release-v1.7
  ci-operator/config/integr8ly/integreatly-operator/integr8ly-integreatly-operator-rhoam-release-v1.7.yaml
  ci-operator/jobs/integr8ly/integreatly-operator/integr8ly-integreatly-operator-rhoam-release-v1.7-postsubmits.yaml
  ci-operator/jobs/integr8ly/integreatly-operator/integr8ly-integreatly-operator-rhoam-release-v1.7-presubmits.yaml
  core-services/image-mirroring/integr8ly/mapping_integr8ly_operator_1_7
Labels: approved, lgtm, ok-to-test

#19015 fix: Hard code rosa jobs to prevent creds stomping on each other
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: approved, lgtm

#19026 Maintaining separate coredns for step-registry
  clusters/build-clusters/01_cluster/sshd-bastion/coredns/OWNERS
  clusters/build-clusters/01_cluster/sshd-bastion/coredns/admin_owners_rbac.yaml
  clusters/build-clusters/01_cluster/sshd-bastion/coredns/admin_rbac.yaml
  clusters/build-clusters/01_cluster/sshd-bastion/coredns/coredns_config.yaml
  clusters/build-clusters/01_cluster/sshd-bastion/coredns/deployment.yaml
  clusters/build-clusters/01_cluster/sshd-bastion/ppc64le-libvirt/coredns_config.yaml
  clusters/build-clusters/01_cluster/sshd-bastion/ppc64le-libvirt/deployment.yaml
  clusters/build-clusters/01_cluster/sshd-bastion/z/deployment.yaml
Labels: approved, lgtm

#19028 Push origin-release images to CI registry instead of docker.io
  clusters/build-clusters/01_cluster/ci/origin-release_pipeline_template.yaml
  core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#19031 assisted-installer: Fix prow/ci/images job on ocm branch
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-ocm-2.3.yaml
Labels: approved, lgtm

#19033 set osde2e canary job to use stable channel
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: approved, lgtm

#19011 Remove DPTP-1640 workaround
  ci-operator/config/openshift/boilerplate/openshift-boilerplate-master.yaml
Labels: approved, lgtm

#19029 Stop mirroring origin-release images from docker.io
  clusters/app.ci/supplemental-ci-images/base-ci-images/images-ocp.yaml
  clusters/app.ci/supplemental-ci-images/base-ci-images/images-origin.yaml
  clusters/app.ci/supplemental-ci-images/origin-stable/release.yaml
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_ci
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_ocp
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_origin
Labels: approved, lgtm

#19034 rhcos-redirect on app.ci points to the art deployment
  clusters/app.ci/rhcos-redirector/03-deployment.yaml
Labels: approved, lgtm

#19037 Make periodic-installer-s390x optional
  core-services/release-controller/_releases/release-ocp-4.8-s390x.json
Labels: approved, lgtm

#19036 enable prow build for thanos branch release-2.2
  ci-operator/config/open-cluster-management/thanos/open-cluster-management-thanos-release-2.2.yaml
  ci-operator/jobs/open-cluster-management/thanos/open-cluster-management-thanos-release-2.2-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/thanos/open-cluster-management-thanos-release-2.2-presubmits.yaml
Labels: approved, lgtm

#19030 vSphere - Change VMC segments
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: approved, lgtm

#19035 Proxy releases-art-rhcos.svc.ci on app.ci
  clusters/app.ci/cert-manager/rhcos-redirector_ingress.yaml
  clusters/app.ci/prow-monitoring/additional-scrape-configs_secret.yaml
Labels: approved, lgtm

#19042 Fix single-node-live-cd hardcoded VM IP address
  ci-operator/step-registry/baremetalds/sno/setup/baremetalds-sno-setup-commands.sh
Labels: approved, lgtm

#18965 Fix assisted-installer and assisted-installer-agent lint job
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-master.yaml
Labels: approved, lgtm

#19045 Changing the slack imojies for assisted jobs.
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-periodics.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: approved, lgtm

#19024 change the boolean to a string for addon-resource-required
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: approved, lgtm

#19046 Enable thanos build for 2.1
  ci-operator/config/open-cluster-management/thanos/open-cluster-management-thanos-release-2.1.yaml
  ci-operator/jobs/open-cluster-management/thanos/open-cluster-management-thanos-release-2.1-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/thanos/open-cluster-management-thanos-release-2.1-presubmits.yaml
Labels: approved, lgtm

#18939 Update openshift-multiarch-release-4.8-periodics.yaml
  ci-operator/jobs/openshift/multiarch/openshift-multiarch-release-4.8-periodics.yaml
Labels: approved, lgtm

#19058 Add docs for build cluster logs
  docs/dptp-triage-sop/build-cluster-logs.md
Labels: approved, lgtm

#19060 Fix sosreport deprecated argument in bare metal
  ci-operator/step-registry/baremetalds/devscripts/gather/baremetalds-devscripts-gather-commands.sh
Labels: approved, lgtm

#19059 Hive: Remove integration test (temporarily)
  ci-operator/config/openshift/hive/openshift-hive-master.yaml
  ci-operator/jobs/openshift/hive/openshift-hive-master-presubmits.yaml
Labels: approved, lgtm

#18971 Collect to coverage lens any file including 'coverage' with html or xml extension
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#19061 Bugzilla: Duplicate master config for main
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#19063 Bumping some timepout for eventing kafkas
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-next__47.yaml
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-next__48.yaml
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.23__47.yaml
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.23__48.yaml
Labels: approved, lgtm

#19007 adding dco enable for rhacm hub install team
  core-services/prow/02_config/open-cluster-management/discovery/_pluginconfig.yaml
  core-services/prow/02_config/open-cluster-management/hub-crds/_pluginconfig.yaml
  core-services/prow/02_config/open-cluster-management/multiclusterhub-operator/_pluginconfig.yaml
  core-services/prow/02_config/open-cluster-management/multiclusterhub-repo/_pluginconfig.yaml
Labels: approved, lgtm

#19053 4.9 CI release jobs: use fc7 as upgrade base
  ci-operator/config/openshift/release/openshift-release-master__ci-4.9-upgrade-from-stable-4.8-from-stable-4.7.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.9-upgrade-from-stable-4.8.yaml
Labels: approved, lgtm

#19054 4.9 nightly release jobs
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.9-upgrade-from-stable-4.8.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.9.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: approved, lgtm

#19069 Triage SOP for logs: Recommend dnf installation isntead of pip
  docs/dptp-triage-sop/logs/README.md
Labels: approved, lgtm

#19071 Remove config for emilvberglind, as the GH app is not installed
  ci-operator/config/emilvberglind/go-rilla/OWNERS
  ci-operator/config/emilvberglind/go-rilla/emilvberglind-go-rilla-master.yaml
  ci-operator/jobs/emilvberglind/go-rilla/OWNERS
  ci-operator/jobs/emilvberglind/go-rilla/emilvberglind-go-rilla-master-presubmits.yaml
  core-services/prow/02_config/_plugins.yaml
  core-services/prow/02_config/emilvberglind/_prowconfig.yaml
  core-services/prow/02_config/emilvberglind/go-rilla/_pluginconfig.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: approved, lgtm

#19072 Cloudwatch error query: Remove exceptions for fixed issues
  docs/dptp-triage-sop/logs/errors.txt
Labels: approved, lgtm

#18973 cvp: replace rehearsal defaults with proper multi-stage params
  ci-operator/config/redhat-operator-ecosystem/cvp/redhat-operator-ecosystem-cvp-ocp-4.7.yaml
  ci-operator/config/redhat-operator-ecosystem/cvp/redhat-operator-ecosystem-cvp-ocp-4.8.yaml
  ci-operator/step-registry/optional-operators/cvp-common/aws/optional-operators-cvp-common-aws-workflow.yaml
  ci-operator/step-registry/optional-operators/cvp-common/ibmz-eco/optional-operators-cvp-common-ibmz-eco-workflow.yaml
  ci-operator/step-registry/optional-operators/cvp-common/powervs/optional-operators-cvp-common-powervs-workflow.yaml
  ci-operator/step-registry/optional-operators/cvp-common/probe/optional-operators-cvp-common-probe-commands.sh
  ci-operator/step-registry/optional-operators/cvp-common/probe/optional-operators-cvp-common-probe-ref.yaml
  ci-operator/step-registry/optional-operators/cvp-common/scorecard/optional-operators-cvp-common-scorecard-commands.sh
  ci-operator/step-registry/optional-operators/cvp-common/scorecard/optional-operators-cvp-common-scorecard-ref.yaml
  ci-operator/step-registry/optional-operators/subscribe/optional-operators-subscribe-commands.sh
  ci-operator/step-registry/optional-operators/subscribe/optional-operators-subscribe-ref.yaml
Labels: approved, lgtm

#19065 Disable scheduled imports of images from docker.io
  clusters/app.ci/supplemental-ci-images/origin-stable/release.yaml
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_openshift
Labels: approved, lgtm

#19074 fetch.sh: adjust for Mac
  docs/dptp-triage-sop/logs/README.md
  docs/dptp-triage-sop/logs/fetch.sh
Labels: approved, lgtm

#19078 Fix go mod tidy: go.mod file indicates go 1.16, but maximum supported…
  ci-operator/config/open-cluster-management/metrics-collector/open-cluster-management-metrics-collector-main.yaml
  ci-operator/config/open-cluster-management/metrics-collector/open-cluster-management-metrics-collector-release-2.3.yaml
Labels: approved, lgtm

#18808 add new rhel 9 test lane for common-templates
  ci-operator/config/kubevirt/common-templates/kubevirt-common-templates-master.yaml
  ci-operator/jobs/kubevirt/common-templates/kubevirt-common-templates-master-presubmits.yaml
Labels: approved, lgtm

#19027 Install Prow on shiftstack/bugwatcher
  ci-operator/config/shiftstack/bugwatcher/OWNERS
  ci-operator/config/shiftstack/bugwatcher/shiftstack-bugwatcher-main.yaml
  ci-operator/jobs/shiftstack/bugwatcher/OWNERS
  ci-operator/jobs/shiftstack/bugwatcher/shiftstack-bugwatcher-main-periodics.yaml
  ci-operator/jobs/shiftstack/bugwatcher/shiftstack-bugwatcher-main-presubmits.yaml
  ci-operator/step-registry/shiftstack/OWNERS
  ci-operator/step-registry/shiftstack/bugwatcher/OWNERS
  ci-operator/step-registry/shiftstack/bugwatcher/shiftstack-bugwatcher-commands.sh
  ci-operator/step-registry/shiftstack/bugwatcher/shiftstack-bugwatcher-ref.metadata.json
  ci-operator/step-registry/shiftstack/bugwatcher/shiftstack-bugwatcher-ref.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
  core-services/prow/02_config/shiftstack/bugwatcher/OWNERS
  core-services/prow/02_config/shiftstack/bugwatcher/_pluginconfig.yaml
Labels: approved, lgtm

#18961 Adds lint step to Insights Operator tests
  ci-operator/config/openshift/insights-operator/openshift-insights-operator-master.yaml
  ci-operator/config/openshift/insights-operator/openshift-insights-operator-release-4.8.yaml
  ci-operator/config/openshift/insights-operator/openshift-insights-operator-release-4.9.yaml
  ci-operator/jobs/openshift/insights-operator/openshift-insights-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/insights-operator/openshift-insights-operator-release-4.8-presubmits.yaml
  ci-operator/jobs/openshift/insights-operator/openshift-insights-operator-release-4.9-presubmits.yaml
Labels: approved, lgtm

#19085 Remove --keep-manifest-list from mirroring jobs to CI registry
  ci-operator/jobs/infra-image-mirroring.yaml
Labels: approved, lgtm

#19087 openstack/ci-configs: Add plugins
  core-services/prow/02_config/shiftstack/ci-configs/_pluginconfig.yaml
Labels: approved, lgtm

#19083 Fix PAO release-4.8 jobs
  ci-operator/config/openshift-kni/performance-addon-operators/openshift-kni-performance-addon-operators-release-4.8.yaml
  ci-operator/jobs/openshift-kni/performance-addon-operators/openshift-kni-performance-addon-operators-release-4.8-presubmits.yaml
Labels: approved, lgtm

#18942 step-registry: Fix unbound variable error on oo-subscribe-commands
  ci-operator/step-registry/optional-operators/ci/subscribe/optional-operators-ci-subscribe-commands.sh
Labels: approved, lgtm

#18958 gather must-gather data after we run tests
  ci-operator/step-registry/baremetalds/sno/gather/baremetalds-sno-gather-commands.sh
Labels: approved, lgtm

#19090 Add ocp-4.8 jobs for tektoncd-pipeline
  ci-operator/config/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-next__4.8.yaml
  ci-operator/jobs/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-next-postsubmits.yaml
  ci-operator/jobs/openshift/tektoncd-pipeline/openshift-tektoncd-pipeline-release-next-presubmits.yaml
Labels: approved, lgtm

#19094 Add ci-operator-yaml-creator to autoconfigbrancher
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
Labels: approved, lgtm

#19097 Stop mirroring images from docker.io
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_openshift
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_origin
Labels: approved, lgtm

#19105 Serve origin-release.ci.openshift.org
  clusters/app.ci/cert-manager/release-controller_ingress.yaml
Labels: approved, lgtm

#19088 mao: use correct configurations for metal-ipi jobs
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-master.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-master-presubmits.yaml
Labels: approved, lgtm

#19108 Remove kubernetes-sigs jobs
  ci-operator/config/kubernetes-sigs/security-profiles-operator/OWNERS
  ci-operator/config/kubernetes-sigs/security-profiles-operator/kubernetes-sigs-security-profiles-operator-master.yaml
  ci-operator/jobs/kubernetes-sigs/security-profiles-operator/OWNERS
  ci-operator/jobs/kubernetes-sigs/security-profiles-operator/kubernetes-sigs-security-profiles-operator-master-presubmits.yaml
  core-services/prow/02_config/kubernetes-sigs/_prowconfig.yaml
  core-services/prow/02_config/kubernetes-sigs/security-profiles-operator/_pluginconfig.yaml
Labels: approved, lgtm

#19009 GPU Operator: add "/test gpu-operator-commit"
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-master.yaml
  ci-operator/jobs/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-master-presubmits.yaml
Labels: approved, lgtm

#19113 gpu-operator-test-commit: specify ipi-aws workflow
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-master.yaml
Labels: approved, lgtm

#19110 Enforce bugzilla link for ocm-2.3 branches on assisted repos
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#19114 o/console: move e2e jobs to 2nd GCP account
  ci-operator/config/openshift/console/openshift-console-master.yaml
  ci-operator/jobs/openshift/console/openshift-console-master-presubmits.yaml
Labels: approved, lgtm

#19102 Port OKD okd-machine-os to cosa-based manifest
  ci-operator/config/openshift/okd-machine-os/openshift-okd-machine-os-release-4.7.yaml
Labels: approved, lgtm

#19119 Remove open-cluster-management website
  ci-operator/config/open-cluster-management/website/OWNERS
  ci-operator/config/open-cluster-management/website/open-cluster-management-website-main.yaml
  ci-operator/jobs/open-cluster-management/website/OWNERS
  ci-operator/jobs/open-cluster-management/website/open-cluster-management-website-main-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/website/open-cluster-management-website-main-presubmits.yaml
Labels: approved, lgtm

#19121 Add OWNERS for ocm prow config shard
  core-services/prow/02_config/open-cluster-management-io/OWNERS
  core-services/prow/02_config/open-cluster-management/OWNERS
Labels: approved, lgtm

#19116 o/kube: move GCP jobs to 2nd GCP account
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-master.yaml
  ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-master-presubmits.yaml
Labels: approved, lgtm

#19055 4.9 handcrafted release jobs
  ci-operator/jobs/openshift/release/openshift-release-release-4.9-periodics.yaml
  core-services/template-deprecation/_allowlist.yaml
Labels: approved, lgtm

#19104 Add open-cluster-management projects' initial prow configurations
  core-services/prow/02_config/open-cluster-management/bootstrap-ks/OWNERS
  core-services/prow/02_config/open-cluster-management/bootstrap-ks/_prowconfig.yaml
  core-services/prow/02_config/open-cluster-management/build-harness-extensions/OWNERS
  core-services/prow/02_config/open-cluster-management/build-harness-extensions/_prowconfig.yaml
  core-services/prow/02_config/open-cluster-management/canary-reporting/OWNERS
  core-services/prow/02_config/open-cluster-management/canary-reporting/_prowconfig.yaml
  core-services/prow/02_config/open-cluster-management/deploy/OWNERS
  core-services/prow/02_config/open-cluster-management/deploy/_prowconfig.yaml
  core-services/prow/02_config/open-cluster-management/lifeguard/OWNERS
  core-services/prow/02_config/open-cluster-management/lifeguard/_prowconfig.yaml
Labels: approved, lgtm

#19123 pod-scaler: turn things back on
  clusters/app.ci/pod-scaler/pod-scaler.yaml
Labels: approved, lgtm

#19128 ibm-roks-toolkit: Fix promotion and tags for 4.8 release
  ci-operator/config/openshift/ibm-roks-toolkit/openshift-ibm-roks-toolkit-master.yaml
Labels: approved, lgtm

#19125 Add DEVSCRIPTS_CONFIG for the e2e-metal-ipi job run for ironic-rhcos-downloader
  ci-operator/config/openshift/ironic-rhcos-downloader/openshift-ironic-rhcos-downloader-master.yaml
Labels: approved, lgtm

#19056 4.9 gate releases on all jobs that gated 4.8
  core-services/release-controller/_releases/release-ocp-4.9-ci.json
  core-services/release-controller/_releases/release-ocp-4.9-s390x.json
  core-services/release-controller/_releases/release-ocp-4.9.json
Labels: approved, lgtm

#19134 shiftstack/bugwatcher: Output logs
  ci-operator/step-registry/shiftstack/bugwatcher/shiftstack-bugwatcher-commands.sh
Labels: approved, lgtm

#18657 LOG-1357: Setup OpenShift CI to build file exporter
  ci-operator/config/ViaQ/log-file-metric-exporter/OWNERS
  ci-operator/config/ViaQ/log-file-metric-exporter/ViaQ-log-file-metric-exporter-main.yaml
  ci-operator/jobs/ViaQ/log-file-metric-exporter/OWNERS
  ci-operator/jobs/ViaQ/log-file-metric-exporter/ViaQ-log-file-metric-exporter-main-postsubmits.yaml
  ci-operator/jobs/ViaQ/log-file-metric-exporter/ViaQ-log-file-metric-exporter-main-presubmits.yaml
  core-services/image-mirroring/openshift-logging/mapping_logging_5_2_quay
  core-services/prow/02_config/ViaQ/log-file-metric-exporter/_pluginconfig.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: approved, lgtm

#19124 4.9 release jobs: keep custom reporter configs
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: approved, lgtm

#19041 Make assisted-test step to work with a directory of kubeconfigs
  ci-operator/step-registry/baremetalds/assisted/test/baremetalds-assisted-test-commands.sh
Labels: approved, lgtm

#19137 shiftstack/bugwatcher: Rename image
  ci-operator/config/shiftstack/bugwatcher/shiftstack-bugwatcher-main.yaml
  ci-operator/step-registry/shiftstack/bugwatcher/shiftstack-bugwatcher-commands.sh
  ci-operator/step-registry/shiftstack/bugwatcher/shiftstack-bugwatcher-ref.yaml
Labels: approved, lgtm

#19138 Hive: Skip tests for docs-only changes
  ci-operator/jobs/openshift/hive/openshift-hive-master-presubmits.yaml
Labels: approved, lgtm

#19136 Make OVN dualstack jobs optional
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.8-presubmits.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.9-presubmits.yaml
Labels: approved, lgtm

#19131 Do not override wathola images from eventing core
  core-services/image-mirroring/knative/mapping_knative_v0_21_quay
Labels: approved, lgtm

#19129 Adding nightly NTO e2e test runs in ci-artifacts
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-master__nto.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-release-4.8__nto.yaml
  ci-operator/jobs/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-master-presubmits.yaml
  ci-operator/jobs/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-release-4.8-periodics.yaml
  ci-operator/jobs/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-release-4.8-presubmits.yaml
Labels: approved, lgtm

#19089 Make kubernetes job optional until we fix make issue
  ci-operator/jobs/openshift/odo/openshift-odo-main-presubmits.yaml
Labels: approved, lgtm

#18993 Switch assisted-test-infra none-platform jobs to use pytest workflow
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
Labels: approved, lgtm

#19149 Set run_if_changed for assisted-test-infra none platform jobs
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-presubmits.yaml
Labels: approved, lgtm

#19064 shiftstack/shiftstack-ci: Add a cleanup periodic
  ci-operator/config/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main.yaml
  ci-operator/jobs/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main-periodics.yaml
  ci-operator/jobs/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main-presubmits.yaml
  ci-operator/step-registry/ipi/conf/openstack/ipi-conf-openstack-commands.sh
  ci-operator/step-registry/ipi/conf/openstack/ipi-conf-openstack-ref.yaml
  ci-operator/step-registry/shiftstack/cleanup/OWNERS
  ci-operator/step-registry/shiftstack/cleanup/shiftstack-cleanup-commands.sh
  ci-operator/step-registry/shiftstack/cleanup/shiftstack-cleanup-ref.metadata.json
  ci-operator/step-registry/shiftstack/cleanup/shiftstack-cleanup-ref.yaml
  ci-operator/step-registry/shiftstack/cleanup/shiftstack-cleanup-workflow.metadata.json
  ci-operator/step-registry/shiftstack/cleanup/shiftstack-cleanup-workflow.yaml
Labels: approved, lgtm

#19146 Add DEVSCRIPTS_CONFIG for the e2e-metal-ipi job run
  ci-operator/config/openshift/ironic-static-ip-manager/openshift-ironic-static-ip-manager-master.yaml
Labels: approved, lgtm

#19153 Make windows job as optional
  ci-operator/jobs/openshift/odo/openshift-odo-main-presubmits.yaml
Labels: approved, lgtm

#19068 kata-containers: Run post steps on best effort mode and Slack notification
  ci-operator/config/kata-containers/kata-containers/kata-containers-kata-containers-main.yaml
  ci-operator/jobs/kata-containers/kata-containers/kata-containers-kata-containers-main-periodics.yaml
Labels: approved, lgtm

#19157 ci-tools: require test-infra job
  ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
Labels: approved, lgtm

#19139 Add configurations and Jobs for metallb-operator repo
  ci-operator/config/openshift/metallb-operator/OWNERS
  ci-operator/config/openshift/metallb-operator/openshift-metallb-operator-main.yaml
  ci-operator/jobs/openshift/metallb-operator/OWNERS
  ci-operator/jobs/openshift/metallb-operator/openshift-metallb-operator-main-presubmits.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
  core-services/prow/02_config/openshift/metallb-operator/OWNERS
  core-services/prow/02_config/openshift/metallb-operator/_pluginconfig.yaml
Labels: approved, lgtm

#18638 Refactor ipi-conf-aws to run under different accounts
  ci-operator/step-registry/ipi/conf/aws/blackholenetwork/ipi-conf-aws-blackholenetwork-commands.sh
  ci-operator/step-registry/ipi/conf/aws/blackholenetwork/ipi-conf-aws-blackholenetwork-ref.yaml
  ci-operator/step-registry/ipi/conf/aws/ipi-conf-aws-commands.sh
  ci-operator/step-registry/ipi/conf/aws/ipi-conf-aws-ref.yaml
  ci-operator/step-registry/ipi/conf/aws/sharednetwork/ipi-conf-aws-sharednetwork-commands.sh
  ci-operator/step-registry/ipi/conf/aws/sharednetwork/ipi-conf-aws-sharednetwork-ref.yaml
  ci-operator/step-registry/ipi/deprovision/aws/OWNERS
  ci-operator/step-registry/ipi/deprovision/aws/blackholenetwork/OWNERS
  ci-operator/step-registry/ipi/deprovision/aws/blackholenetwork/ipi-deprovision-aws-blackholenetwork-commands.sh
  ci-operator/step-registry/ipi/deprovision/aws/blackholenetwork/ipi-deprovision-aws-blackholenetwork-ref.metadata.json
  ci-operator/step-registry/ipi/deprovision/aws/blackholenetwork/ipi-deprovision-aws-blackholenetwork-ref.yaml
  ci-operator/step-registry/ipi/deprovision/aws/sharednetwork/OWNERS
  ci-operator/step-registry/ipi/deprovision/aws/sharednetwork/ipi-deprovision-aws-sharednetwork-commands.sh
  ci-operator/step-registry/ipi/deprovision/aws/sharednetwork/ipi-deprovision-aws-sharednetwork-ref.metadata.json
  ci-operator/step-registry/ipi/deprovision/aws/sharednetwork/ipi-deprovision-aws-sharednetwork-ref.yaml
  ci-operator/step-registry/openshift/e2e/aws/proxy/openshift-e2e-aws-proxy-workflow.yaml
  ci-operator/step-registry/openshift/e2e/aws/sharednetwork/openshift-e2e-aws-sharednetwork-workflow.yaml
Labels: approved, lgtm

#19095 shiftstack/merge-bot: Add repository
  ci-operator/config/shiftstack/merge-bot/OWNERS
  ci-operator/config/shiftstack/merge-bot/shiftstack-merge-bot-main.yaml
  ci-operator/jobs/shiftstack/merge-bot/OWNERS
  ci-operator/jobs/shiftstack/merge-bot/shiftstack-merge-bot-main-presubmits.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
  core-services/prow/02_config/shiftstack/merge-bot/OWNERS
  core-services/prow/02_config/shiftstack/merge-bot/_pluginconfig.yaml
Labels: approved, lgtm

#19160 ocm: Add publish delay (GRC)
  ci-operator/jobs/open-cluster-management/cert-policy-controller/open-cluster-management-cert-policy-controller-release-2.3-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/config-policy-controller/open-cluster-management-config-policy-controller-release-2.3-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/governance-policy-propagator/open-cluster-management-governance-policy-propagator-release-2.3-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/governance-policy-spec-sync/open-cluster-management-governance-policy-spec-sync-release-2.3-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/governance-policy-status-sync/open-cluster-management-governance-policy-status-sync-release-2.3-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/governance-policy-template-sync/open-cluster-management-governance-policy-template-sync-release-2.3-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/grc-ui-api/open-cluster-management-grc-ui-api-release-2.3-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/iam-policy-controller/open-cluster-management-iam-policy-controller-release-2.3-postsubmits.yaml
Labels: approved, lgtm

#19165 Vault subpath proxy: Also mount kubeconfigs
  clusters/app.ci/vault/manifests.yaml
  core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#19133 Adding wathola-kafka-sender test image for 0.22 release
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.22.0__47.yaml
  core-services/image-mirroring/knative/mapping_knative_v0_22_quay
Labels: approved, lgtm

#19010 enable release note and require label plugins for shipwright-io/cli
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/shipwright-io/cli/_pluginconfig.yaml
Labels: approved, lgtm

#19154 Makefile: update the list of phony targets
  Makefile
Labels: approved, lgtm
