Repository openshift/release, pull requests merged in 2021-04, with the labels that each got.

#17374 update alertmgr test
  ci-operator/config/open-cluster-management/prometheus-alertmanager/open-cluster-management-prometheus-alertmanager-release-2.3.yaml
  ci-operator/jobs/open-cluster-management/prometheus-alertmanager/open-cluster-management-prometheus-alertmanager-release-2.3-presubmits.yaml
Labels: approved, lgtm

#17319 Include image building for Azure Disk CSI Driver and Operator
  ci-operator/config/openshift/azure-disk-csi-driver-operator/openshift-azure-disk-csi-driver-operator-master.yaml
  ci-operator/config/openshift/azure-disk-csi-driver-operator/openshift-azure-disk-csi-driver-operator-release-4.8.yaml
  ci-operator/config/openshift/azure-disk-csi-driver-operator/openshift-azure-disk-csi-driver-operator-release-4.9.yaml
  ci-operator/config/openshift/azure-disk-csi-driver/openshift-azure-disk-csi-driver-master.yaml
  ci-operator/config/openshift/azure-disk-csi-driver/openshift-azure-disk-csi-driver-release-4.8.yaml
  ci-operator/config/openshift/azure-disk-csi-driver/openshift-azure-disk-csi-driver-release-4.9.yaml
  ci-operator/jobs/openshift/azure-disk-csi-driver-operator/openshift-azure-disk-csi-driver-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/azure-disk-csi-driver-operator/openshift-azure-disk-csi-driver-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/azure-disk-csi-driver-operator/openshift-azure-disk-csi-driver-operator-release-4.8-postsubmits.yaml
  ci-operator/jobs/openshift/azure-disk-csi-driver-operator/openshift-azure-disk-csi-driver-operator-release-4.8-presubmits.yaml
  ci-operator/jobs/openshift/azure-disk-csi-driver-operator/openshift-azure-disk-csi-driver-operator-release-4.9-postsubmits.yaml
  ci-operator/jobs/openshift/azure-disk-csi-driver-operator/openshift-azure-disk-csi-driver-operator-release-4.9-presubmits.yaml
  ci-operator/jobs/openshift/azure-disk-csi-driver/openshift-azure-disk-csi-driver-master-postsubmits.yaml
  ci-operator/jobs/openshift/azure-disk-csi-driver/openshift-azure-disk-csi-driver-master-presubmits.yaml
  ci-operator/jobs/openshift/azure-disk-csi-driver/openshift-azure-disk-csi-driver-release-4.8-postsubmits.yaml
  ci-operator/jobs/openshift/azure-disk-csi-driver/openshift-azure-disk-csi-driver-release-4.8-presubmits.yaml
  ci-operator/jobs/openshift/azure-disk-csi-driver/openshift-azure-disk-csi-driver-release-4.9-postsubmits.yaml
  ci-operator/jobs/openshift/azure-disk-csi-driver/openshift-azure-disk-csi-driver-release-4.9-presubmits.yaml
Labels: approved, lgtm

#17373 Only run kube-api e2e test if changes are detected in the controller
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
Labels: approved, lgtm

#17381 secret-mirroring: `s/namepsace/namespace/`
  core-services/secret-mirroring/_mapping.yaml
Labels: approved, lgtm

#17386 bump go to 1.16
  ci-operator/config/open-cluster-management/applifecycle-backend-e2e/open-cluster-management-applifecycle-backend-e2e-main.yaml
  ci-operator/config/open-cluster-management/applifecycle-backend-e2e/open-cluster-management-applifecycle-backend-e2e-release-2.3.yaml
Labels: approved, lgtm

#17385 ocm step deploy: check for /dev/tty before exec
  ci-operator/step-registry/ocm/e2e/clusterpool/cluster/deploy/ocm-e2e-clusterpool-cluster-deploy-commands.sh
Labels: approved, lgtm

#17378 fix kube-api presubmit job to not running conformance tests
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
Labels: approved, lgtm

#17389 Set assisted images jobs as non-optional
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
Labels: approved, lgtm

#17397 Add YAML for syncing vsphere syncer images
  ci-operator/config/openshift/vmware-vsphere-csi-driver/openshift-vmware-vsphere-csi-driver-master.yaml
  ci-operator/config/openshift/vmware-vsphere-csi-driver/openshift-vmware-vsphere-csi-driver-release-4.8.yaml
  ci-operator/config/openshift/vmware-vsphere-csi-driver/openshift-vmware-vsphere-csi-driver-release-4.9.yaml
Labels: approved, lgtm

#17401 operator-framework/operator-lib: update config's build_root go version to 1.15
  ci-operator/config/operator-framework/operator-lib/operator-framework-operator-lib-main.yaml
Labels: approved, lgtm

#17390 ocm step deploy: add debugging output to wait for mcho pod
  ci-operator/step-registry/ocm/e2e/clusterpool/cluster/deploy/ocm-e2e-clusterpool-cluster-deploy-commands.sh
Labels: approved, lgtm

#17400 vSphere UPI: Don't exit openshift-install coreos
  ci-operator/step-registry/upi/conf/vsphere/upi-conf-vsphere-commands.sh
Labels: approved, lgtm

#17404 Ocm step deploy
  ci-operator/step-registry/ocm/e2e/clusterpool/cluster/deploy/ocm-e2e-clusterpool-cluster-deploy-commands.sh
Labels: approved, lgtm

#16863 Enabling the network related tests in CI 4.8
  ci-operator/jobs/openshift/multiarch/openshift-multiarch-release-4.8-periodics.yaml
Labels: approved, lgtm

#17241 Update openshift-multiarch-release-4.7-periodics.yaml
  ci-operator/jobs/openshift/multiarch/openshift-multiarch-release-4.7-periodics.yaml
Labels: approved, lgtm

#17407 Add v4.8 to ci-search bz version list
  clusters/build-clusters/01_cluster/ci-search/deploy.yaml
Labels: approved, lgtm

#17382 Propogate run-tests return code
  ci-operator/templates/openshift/installer/cluster-launch-installer-remote-libvirt-e2e.yaml
Labels: approved, lgtm

#17394 cluster-network-operator: Enable testing for IPv6 with IPsec enabled
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-master.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-master-presubmits.yaml
  ci-operator/step-registry/baremetalds/e2e/ovn/OWNERS
  ci-operator/step-registry/baremetalds/e2e/ovn/ipsec/OWNERS
  ci-operator/step-registry/baremetalds/e2e/ovn/ipsec/baremetalds-e2e-ovn-ipsec-workflow.metadata.json
  ci-operator/step-registry/baremetalds/e2e/ovn/ipsec/baremetalds-e2e-ovn-ipsec-workflow.yaml
Labels: approved, lgtm

#17421 MGMT-4852 enable kube-api by default
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
Labels: approved, lgtm

#17395 Move KUBECONFIG assignment after assisted-setup workflow is successful
  ci-operator/step-registry/baremetalds/assisted/setup/baremetalds-assisted-setup-commands.sh
Labels: approved, lgtm

#17334 [SNC] Add created bundle to crc-bundle bucket
  ci-operator/step-registry/gather/snc/gather-snc-commands.sh
Labels: approved, lgtm

#17426 Enable periodic job for ocp 4.8 cluster
  ci-operator/config/openshift/odo/openshift-odo-master__v4.8.yaml
  ci-operator/jobs/openshift/odo/openshift-odo-master-periodics.yaml
  ci-operator/jobs/openshift/odo/openshift-odo-master-presubmits.yaml
Labels: approved, lgtm

#17372 ocm: Update config and image-mirroring (GRC)
  ci-operator/config/open-cluster-management/governance-policy-spec-sync/open-cluster-management-governance-policy-spec-sync-main.yaml
  ci-operator/config/open-cluster-management/governance-policy-spec-sync/open-cluster-management-governance-policy-spec-sync-release-2.3.yaml
  ci-operator/config/open-cluster-management/governance-policy-status-sync/open-cluster-management-governance-policy-status-sync-main.yaml
  ci-operator/config/open-cluster-management/governance-policy-status-sync/open-cluster-management-governance-policy-status-sync-release-2.3.yaml
  ci-operator/config/open-cluster-management/governance-policy-template-sync/open-cluster-management-governance-policy-template-sync-main.yaml
  ci-operator/config/open-cluster-management/governance-policy-template-sync/open-cluster-management-governance-policy-template-sync-release-2.3.yaml
  ci-operator/jobs/open-cluster-management/governance-policy-spec-sync/open-cluster-management-governance-policy-spec-sync-main-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/governance-policy-spec-sync/open-cluster-management-governance-policy-spec-sync-main-presubmits.yaml
  ci-operator/jobs/open-cluster-management/governance-policy-spec-sync/open-cluster-management-governance-policy-spec-sync-release-2.3-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/governance-policy-spec-sync/open-cluster-management-governance-policy-spec-sync-release-2.3-presubmits.yaml
  ci-operator/jobs/open-cluster-management/governance-policy-status-sync/open-cluster-management-governance-policy-status-sync-main-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/governance-policy-status-sync/open-cluster-management-governance-policy-status-sync-main-presubmits.yaml
  ci-operator/jobs/open-cluster-management/governance-policy-status-sync/open-cluster-management-governance-policy-status-sync-release-2.3-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/governance-policy-status-sync/open-cluster-management-governance-policy-status-sync-release-2.3-presubmits.yaml
  ci-operator/jobs/open-cluster-management/governance-policy-template-sync/open-cluster-management-governance-policy-template-sync-main-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/governance-policy-template-sync/open-cluster-management-governance-policy-template-sync-main-presubmits.yaml
  ci-operator/jobs/open-cluster-management/governance-policy-template-sync/open-cluster-management-governance-policy-template-sync-release-2.3-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/governance-policy-template-sync/open-cluster-management-governance-policy-template-sync-release-2.3-presubmits.yaml
  core-services/image-mirroring/open-cluster-management/mapping_open_cluster_management_latest_quay
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#17427 ocm: Add branch protection for grc-ui/api
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#16645 [Azure ARC] Enable allowed regions for ARC conformance testing
  ci-operator/step-registry/ipi/conf/azure/arcconformance/region/ipi-conf-azure-arcconformance-region-commands.sh
  ci-operator/step-registry/ipi/conf/azure/arcconformance/region/ipi-conf-azure-arcconformance-region-ref.yaml
Labels: approved, lgtm

#17429 Modifying to check the tunnel Alive connection
  clusters/build-clusters/01_cluster/sshd-bastion/ppc64le-libvirt/sshd_config
  clusters/build-clusters/01_cluster/sshd-bastion/z/sshd_config
Labels: approved, lgtm

#17430 ocm step deploy: change YAML creation to use timeout
  ci-operator/step-registry/ocm/e2e/clusterpool/cluster/deploy/ocm-e2e-clusterpool-cluster-deploy-commands.sh
Labels: approved, lgtm

#17432 ocm step deploy: refactor check mcho pod name
  ci-operator/step-registry/ocm/e2e/clusterpool/cluster/deploy/ocm-e2e-clusterpool-cluster-deploy-commands.sh
Labels: approved, lgtm

#17391 Include Azure Disk image mirroring to quay
  core-services/image-mirroring/openshift/mapping_origin_4_8
  core-services/image-mirroring/openshift/mapping_origin_4_9
Labels: approved, lgtm

#17435 ci-operator/config/openshift/cincinnati-operator: Set RELATED_IMAGE_*
  ci-operator/config/openshift/cincinnati-operator/openshift-cincinnati-operator-master.yaml
  ci-operator/config/openshift/cincinnati-operator/openshift-cincinnati-operator-release-4.6.yaml
  ci-operator/config/openshift/cincinnati-operator/openshift-cincinnati-operator-release-4.7.yaml
  ci-operator/config/openshift/cincinnati-operator/openshift-cincinnati-operator-release-4.8.yaml
  ci-operator/config/openshift/cincinnati-operator/openshift-cincinnati-operator-release-4.9.yaml
Labels: approved, lgtm

#17434 ocs-operator: add must-gather post job
  ci-operator/config/openshift/ocs-operator/openshift-ocs-operator-master.yaml
Labels: approved, lgtm

#17439 update grafana env
  ci-operator/jobs/open-cluster-management/grafana/open-cluster-management-grafana-release-2.3-postsubmits.yaml
Labels: approved, lgtm

#17431 baremetal: fix test matches and move 4.7 to minimal
  ci-operator/step-registry/baremetalds/e2e/test/baremetalds-e2e-test-commands.sh
  ci-operator/step-registry/baremetalds/e2e/test/baremetalds-e2e-test-ref.yaml
Labels: approved, lgtm

#17443 Add test images with Azure Disk and vSphere
  ci-operator/config/openshift/azure-disk-csi-driver-operator/openshift-azure-disk-csi-driver-operator-master.yaml
  ci-operator/config/openshift/azure-disk-csi-driver-operator/openshift-azure-disk-csi-driver-operator-release-4.8.yaml
  ci-operator/config/openshift/azure-disk-csi-driver-operator/openshift-azure-disk-csi-driver-operator-release-4.9.yaml
  ci-operator/config/openshift/vmware-vsphere-csi-driver-operator/openshift-vmware-vsphere-csi-driver-operator-master.yaml
  ci-operator/config/openshift/vmware-vsphere-csi-driver-operator/openshift-vmware-vsphere-csi-driver-operator-release-4.8.yaml
  ci-operator/config/openshift/vmware-vsphere-csi-driver-operator/openshift-vmware-vsphere-csi-driver-operator-release-4.9.yaml
Labels: approved, lgtm

#17447 Add boilerplate image-v0.5.0
  ci-operator/config/openshift/boilerplate/openshift-boilerplate-master.yaml
  clusters/app.ci/supplemental-ci-images/boilerplate/boilerplate.yaml
Labels: approved, lgtm

#17448 Fix deck-internal to work with google chrome
  clusters/app.ci/prow/03_deployment/deck.yaml
Labels: approved, lgtm

#16377 OKD: sync baremetal-machine-controllers and baremetal-operator
  core-services/release-controller/_releases/release-ocp-4.7-ci.json
  core-services/release-controller/_releases/release-ocp-4.8-ci.json
  core-services/release-controller/_releases/release-ocp-4.9-ci.json
Labels: approved, lgtm

#17449 CI-Tools: Use 4.8 CLI to get openapi download dedup fixes
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
Labels: approved, lgtm

#17463 Remove invalid duplicate blacklist setting
  core-services/prow/02_config/_plugins.yaml
Labels: approved

#17456 Revert "Add boilerplate image-v0.5.0"
  ci-operator/config/openshift/boilerplate/openshift-boilerplate-master.yaml
  clusters/app.ci/supplemental-ci-images/boilerplate/boilerplate.yaml
Labels: approved, lgtm

#17465 ocm helloprow: change from integration to edge stage
  ci-operator/config/open-cluster-management/helloprow-go/open-cluster-management-helloprow-go-main.yaml
Labels: approved, lgtm

#17467 ocm image-builder: unify amd64 and s390x docker files
  ci-operator/config/open-cluster-management/image-builder/open-cluster-management-image-builder-master.yaml
Labels: approved, lgtm

#17468 uuse go1.16 base image
  ci-operator/config/open-cluster-management/applifecycle-backend-e2e/open-cluster-management-applifecycle-backend-e2e-main.yaml
  ci-operator/config/open-cluster-management/applifecycle-backend-e2e/open-cluster-management-applifecycle-backend-e2e-release-2.3.yaml
Labels: approved, lgtm

#17470 ci-operator/core-services: Enable tide for the operator-framework/api repository
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#17254 Apply nothing but secrets on api.ci
  README.md
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  clusters/app.ci/common_except_api.ci
  clusters/build-clusters/01_cluster/common_except_api.ci
  clusters/build-clusters/02_cluster/common_except_api.ci
  clusters/build-clusters/common/README.md
  clusters/build-clusters/common/cert-manager.yaml
  clusters/build-clusters/common/cert-manager_ns.yaml
  clusters/build-clusters/common/ci-ns-ttl-controller_deployment.yaml
  clusters/build-clusters/vsphere/common_except_api.ci
  core-services/README.md
Labels: approved, lgtm

#17361 DPTP-1920 releases: migrate all e2e-aws-serial jobs to generated
  ci-operator/config/openshift/release/openshift-release-master__ci-4.1.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.2.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.3.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.4.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.5.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.6.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.7.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.1.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.2.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.3.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.4.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.5.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.6.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.7.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.8.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.1-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.6-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.8-periodics.yaml
  core-services/release-controller/_releases/release-ocp-4.1-ci.json
  core-services/release-controller/_releases/release-ocp-4.1.json
  core-services/release-controller/_releases/release-ocp-4.2-ci.json
  core-services/release-controller/_releases/release-ocp-4.2.json
  core-services/release-controller/_releases/release-ocp-4.3.json
  core-services/release-controller/_releases/release-ocp-4.4.json
  core-services/release-controller/_releases/release-ocp-4.5.json
  core-services/release-controller/_releases/release-ocp-4.6-ci.json
  core-services/release-controller/_releases/release-ocp-4.6.json
  core-services/release-controller/_releases/release-ocp-4.7-ci.json
  core-services/release-controller/_releases/release-ocp-4.7.json
  core-services/release-controller/_releases/release-ocp-4.8.json
Labels: approved, lgtm

#17383 Mark release-openshift-ocp-installer-e2e-aws-upi-4.8 as broken
  core-services/testgrid-config-generator/_allow-list.yaml
Labels: approved, lgtm

#17444 adding prow jobs for sku feature branch for integreatly-operator
  ci-operator/config/integr8ly/integreatly-operator/integr8ly-integreatly-operator-MGDAPI-1192-3.yaml
  ci-operator/jobs/integr8ly/integreatly-operator/integr8ly-integreatly-operator-MGDAPI-1192-3-postsubmits.yaml
  ci-operator/jobs/integr8ly/integreatly-operator/integr8ly-integreatly-operator-MGDAPI-1192-3-presubmits.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, ok-to-test

#17227 wmco: add upgrade job
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-master.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.6.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.7.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.8.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.9.yaml
  ci-operator/jobs/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.8-presubmits.yaml
  ci-operator/jobs/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.9-presubmits.yaml
Labels: approved, lgtm

#17476 remove ocp tags from co
  ci-operator/config/open-cluster-management/applifecycle-backend-e2e/open-cluster-management-applifecycle-backend-e2e-main.yaml
  ci-operator/config/open-cluster-management/applifecycle-backend-e2e/open-cluster-management-applifecycle-backend-e2e-release-2.3.yaml
Labels: approved, lgtm

#17477 ocm helloprow: use Makefile.prow for e2e test
  ci-operator/config/open-cluster-management/helloprow-go/open-cluster-management-helloprow-go-main.yaml
Labels: approved, lgtm

#17359 openshift/assisted-service: Run jobs against relevant changes
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
Labels: approved, lgtm

#17464 ci-operator: Mark all OLM non-e2e jobs as required
  ci-operator/jobs/openshift/operator-framework-olm/openshift-operator-framework-olm-master-presubmits.yaml
  ci-operator/jobs/openshift/operator-framework-olm/openshift-operator-framework-olm-release-4.8-presubmits.yaml
  ci-operator/jobs/openshift/operator-framework-olm/openshift-operator-framework-olm-release-4.9-presubmits.yaml
Labels: approved, lgtm

#17453 [CRC] Pass 'PULL_NUMBER' variable to test run to consume by ci script
  ci-operator/step-registry/code-ready/snc/e2e/test/code-ready-snc-e2e-test-commands.sh
  ci-operator/step-registry/openshift/e2e/gcp/crc/test/openshift-e2e-gcp-crc-test-commands.sh
Labels: approved, lgtm

#16682 Introduce a test job that runs only tests that have high reliability
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.8.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: approved, lgtm

#17455 Update assisted-test-infra kube-api jobs configuration to support kube-api service deployment
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
Labels: approved, lgtm

#17484 Add Knative Serving release 0.21.0
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-v0.21.0__4.6.yaml
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-v0.21.0__4.7.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-v0.21.0-postsubmits.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-v0.21.0-presubmits.yaml
Labels: approved, lgtm

#16409 Adds the local-storage-mustgather image to CI
  ci-operator/config/openshift/local-storage-operator/openshift-local-storage-operator-master.yaml
  ci-operator/config/openshift/local-storage-operator/openshift-local-storage-operator-release-4.8.yaml
  ci-operator/config/openshift/local-storage-operator/openshift-local-storage-operator-release-4.9.yaml
Labels: approved, lgtm

#17396 Add vSphere CSI driver tests
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-master.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.8.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.9.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.8-presubmits.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.9-presubmits.yaml
  ci-operator/step-registry/openshift/e2e/vsphere/csi/OWNERS
  ci-operator/step-registry/openshift/e2e/vsphere/csi/openshift-e2e-vsphere-csi-workflow.metadata.json
  ci-operator/step-registry/openshift/e2e/vsphere/csi/openshift-e2e-vsphere-csi-workflow.yaml
  ci-operator/step-registry/storage/conf/csi-vmware-vsphere/OWNERS
  ci-operator/step-registry/storage/conf/csi-vmware-vsphere/storage-conf-csi-vmware-vsphere-commands.sh
  ci-operator/step-registry/storage/conf/csi-vmware-vsphere/storage-conf-csi-vmware-vsphere-ref.metadata.json
  ci-operator/step-registry/storage/conf/csi-vmware-vsphere/storage-conf-csi-vmware-vsphere-ref.yaml
  ci-operator/step-registry/storage/conf/feature-gate/OWNERS
  ci-operator/step-registry/storage/conf/feature-gate/storage-conf-feature-gate-commands.sh
  ci-operator/step-registry/storage/conf/feature-gate/storage-conf-feature-gate-ref.metadata.json
  ci-operator/step-registry/storage/conf/feature-gate/storage-conf-feature-gate-ref.yaml
  ci-operator/step-registry/storage/conf/wait-for-csi-driver/OWNERS
  ci-operator/step-registry/storage/conf/wait-for-csi-driver/storage-conf-wait-for-csi-driver-commands.sh
  ci-operator/step-registry/storage/conf/wait-for-csi-driver/storage-conf-wait-for-csi-driver-ref.metadata.json
  ci-operator/step-registry/storage/conf/wait-for-csi-driver/storage-conf-wait-for-csi-driver-ref.yaml
Labels: approved, lgtm

#17399 Setup CI for Serverless release 1.14
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.14.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.14__4.6.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.14__4.7.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.14-periodics.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.14-postsubmits.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.14-presubmits.yaml
Labels: approved, lgtm

#17487 Serverless: Remove old periodic jobs
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.11__4.6.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.12__4.6.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.12__4.7.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.7__4.4.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.11-periodics.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.12-periodics.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.7-periodics.yaml
Labels: approved, lgtm

#17440 Serverless: remove Service Mesh from nightly tests
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main__4.6.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main__4.7.yaml
Labels: approved, lgtm

#17491 Add vSphere jobs to CSO and to the CSI driver
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-master.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.8.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.9.yaml
  ci-operator/config/openshift/vmware-vsphere-csi-driver-operator/openshift-vmware-vsphere-csi-driver-operator-master.yaml
  ci-operator/config/openshift/vmware-vsphere-csi-driver-operator/openshift-vmware-vsphere-csi-driver-operator-release-4.8.yaml
  ci-operator/config/openshift/vmware-vsphere-csi-driver-operator/openshift-vmware-vsphere-csi-driver-operator-release-4.9.yaml
  ci-operator/config/openshift/vmware-vsphere-csi-driver/openshift-vmware-vsphere-csi-driver-master.yaml
  ci-operator/config/openshift/vmware-vsphere-csi-driver/openshift-vmware-vsphere-csi-driver-release-4.8.yaml
  ci-operator/config/openshift/vmware-vsphere-csi-driver/openshift-vmware-vsphere-csi-driver-release-4.9.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.8-presubmits.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.9-presubmits.yaml
  ci-operator/jobs/openshift/vmware-vsphere-csi-driver-operator/openshift-vmware-vsphere-csi-driver-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/vmware-vsphere-csi-driver-operator/openshift-vmware-vsphere-csi-driver-operator-release-4.8-presubmits.yaml
  ci-operator/jobs/openshift/vmware-vsphere-csi-driver-operator/openshift-vmware-vsphere-csi-driver-operator-release-4.9-presubmits.yaml
  ci-operator/jobs/openshift/vmware-vsphere-csi-driver/openshift-vmware-vsphere-csi-driver-master-presubmits.yaml
  ci-operator/jobs/openshift/vmware-vsphere-csi-driver/openshift-vmware-vsphere-csi-driver-release-4.8-presubmits.yaml
  ci-operator/jobs/openshift/vmware-vsphere-csi-driver/openshift-vmware-vsphere-csi-driver-release-4.9-presubmits.yaml
Labels: approved, lgtm

#17493 Remove extra status checks from assisted-installer
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#17501 node-label-operator: Fix channel
  ci-operator/config/openshift-kni/node-label-operator/openshift-kni-node-label-operator-main.yaml
Labels: approved, lgtm

#17307 Add debug machineSet and MCP
  clusters/build-clusters/01_cluster/machine-config/debug_mcp.yaml
  clusters/build-clusters/01_cluster/machine-config/kernel_args_machineconfig.yaml
  clusters/build-clusters/01_cluster/openshift-machine-api/admin_build01-9hdwj-worker-us-east-1a-debug_machine_set.yaml
Labels: approved, lgtm

#17469 Add Azure jobs to CSI driver and CSO
  ci-operator/config/openshift/azure-disk-csi-driver-operator/openshift-azure-disk-csi-driver-operator-master.yaml
  ci-operator/config/openshift/azure-disk-csi-driver-operator/openshift-azure-disk-csi-driver-operator-release-4.8.yaml
  ci-operator/config/openshift/azure-disk-csi-driver-operator/openshift-azure-disk-csi-driver-operator-release-4.9.yaml
  ci-operator/config/openshift/azure-disk-csi-driver/openshift-azure-disk-csi-driver-master.yaml
  ci-operator/config/openshift/azure-disk-csi-driver/openshift-azure-disk-csi-driver-release-4.8.yaml
  ci-operator/config/openshift/azure-disk-csi-driver/openshift-azure-disk-csi-driver-release-4.9.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-master.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.8.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.9.yaml
  ci-operator/jobs/openshift/azure-disk-csi-driver-operator/openshift-azure-disk-csi-driver-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/azure-disk-csi-driver-operator/openshift-azure-disk-csi-driver-operator-release-4.8-presubmits.yaml
  ci-operator/jobs/openshift/azure-disk-csi-driver-operator/openshift-azure-disk-csi-driver-operator-release-4.9-presubmits.yaml
  ci-operator/jobs/openshift/azure-disk-csi-driver/openshift-azure-disk-csi-driver-master-presubmits.yaml
  ci-operator/jobs/openshift/azure-disk-csi-driver/openshift-azure-disk-csi-driver-release-4.8-presubmits.yaml
  ci-operator/jobs/openshift/azure-disk-csi-driver/openshift-azure-disk-csi-driver-release-4.9-presubmits.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.8-presubmits.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.9-presubmits.yaml
Labels: approved, lgtm

#17199 Add openshift/cloud-provider-aws repository
  ci-operator/config/openshift/cloud-provider-aws/OWNERS
  ci-operator/config/openshift/cloud-provider-aws/openshift-cloud-provider-aws-master.yaml
  ci-operator/jobs/openshift/cloud-provider-aws/OWNERS
  ci-operator/jobs/openshift/cloud-provider-aws/openshift-cloud-provider-aws-master-postsubmits.yaml
  ci-operator/jobs/openshift/cloud-provider-aws/openshift-cloud-provider-aws-master-presubmits.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#17499 Optional operators: Remove unbound var usage
  ci-operator/step-registry/optional-operators/subscribe/optional-operators-subscribe-commands.sh
Labels: approved, lgtm

#17504 Skip intel validation for DU lane
  ci-operator/config/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-master.yaml
Labels: approved, lgtm

#17505 Build images for Kourier's 0.21 release
  ci-operator/config/openshift-knative/net-kourier/openshift-knative-net-kourier-release-0.21.yaml
  ci-operator/jobs/openshift-knative/net-kourier/openshift-knative-net-kourier-release-0.21-postsubmits.yaml
  ci-operator/jobs/openshift-knative/net-kourier/openshift-knative-net-kourier-release-0.21-presubmits.yaml
Labels: approved, lgtm

#17508 ocm step deploy: wrap applying YAML files in timeout
  ci-operator/step-registry/ocm/e2e/clusterpool/cluster/deploy/ocm-e2e-clusterpool-cluster-deploy-commands.sh
Labels: approved, lgtm

#17387 ocm: Add provider-credential-controller to PROW
  ci-operator/config/open-cluster-management/provider-credential-controller/OWNERS
  ci-operator/config/open-cluster-management/provider-credential-controller/open-cluster-management-provider-credential-controller-main.yaml
  ci-operator/config/open-cluster-management/provider-credential-controller/open-cluster-management-provider-credential-controller-release-2.3.yaml
  ci-operator/jobs/open-cluster-management/provider-credential-controller/OWNERS
  ci-operator/jobs/open-cluster-management/provider-credential-controller/open-cluster-management-provider-credential-controller-main-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/provider-credential-controller/open-cluster-management-provider-credential-controller-main-presubmits.yaml
  ci-operator/jobs/open-cluster-management/provider-credential-controller/open-cluster-management-provider-credential-controller-release-2.3-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/provider-credential-controller/open-cluster-management-provider-credential-controller-release-2.3-presubmits.yaml
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#17511 Update JoinBuildFarm.md
  clusters/JoinBuildFarm.md
Labels: approved, lgtm

#17514 Make YuviGold monitoring viewer
  clusters/build-clusters/01_cluster/openshift-monitoring/admin_cluster-monitoring-viewer_list.yaml
Labels: approved, lgtm

#17507 Update test command flag names
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-master.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-release-4.5.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-release-4.6.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-release-4.7.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-release-4.8.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-release-4.9.yaml
Labels: approved, lgtm

#16346 secrets: remove outdated packet secrets
  core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#17471 Add boilerplate image-v0.5.1
  ci-operator/config/openshift/boilerplate/openshift-boilerplate-master.yaml
  clusters/app.ci/supplemental-ci-images/boilerplate/boilerplate.yaml
Labels: approved, lgtm

#17523 Change build image
  ci-operator/jobs/open-cluster-management/application-ui/open-cluster-management-application-ui-main-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/application-ui/open-cluster-management-application-ui-release-2.3-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/console-api/open-cluster-management-console-api-main-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/console-api/open-cluster-management-console-api-release-2.3-postsubmits.yaml
Labels: approved, lgtm

#17510 Needs rebase: Listen to comments in Openshift org
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#17522 ocm: Update builder images (GRC)
  ci-operator/config/open-cluster-management/cert-policy-controller/open-cluster-management-cert-policy-controller-main.yaml
  ci-operator/config/open-cluster-management/cert-policy-controller/open-cluster-management-cert-policy-controller-release-2.3.yaml
  ci-operator/config/open-cluster-management/config-policy-controller/open-cluster-management-config-policy-controller-main.yaml
  ci-operator/config/open-cluster-management/config-policy-controller/open-cluster-management-config-policy-controller-release-2.3.yaml
  ci-operator/config/open-cluster-management/governance-policy-propagator/open-cluster-management-governance-policy-propagator-main.yaml
  ci-operator/config/open-cluster-management/governance-policy-propagator/open-cluster-management-governance-policy-propagator-release-2.3.yaml
  ci-operator/config/open-cluster-management/governance-policy-spec-sync/open-cluster-management-governance-policy-spec-sync-main.yaml
  ci-operator/config/open-cluster-management/governance-policy-spec-sync/open-cluster-management-governance-policy-spec-sync-release-2.3.yaml
  ci-operator/config/open-cluster-management/governance-policy-status-sync/open-cluster-management-governance-policy-status-sync-main.yaml
  ci-operator/config/open-cluster-management/governance-policy-status-sync/open-cluster-management-governance-policy-status-sync-release-2.3.yaml
  ci-operator/config/open-cluster-management/governance-policy-template-sync/open-cluster-management-governance-policy-template-sync-main.yaml
  ci-operator/config/open-cluster-management/governance-policy-template-sync/open-cluster-management-governance-policy-template-sync-release-2.3.yaml
  ci-operator/config/open-cluster-management/iam-policy-controller/open-cluster-management-iam-policy-controller-main.yaml
  ci-operator/config/open-cluster-management/iam-policy-controller/open-cluster-management-iam-policy-controller-release-2.3.yaml
  ci-operator/config/open-cluster-management/security-middleware/open-cluster-management-security-middleware-main.yaml
  ci-operator/jobs/open-cluster-management/cert-policy-controller/open-cluster-management-cert-policy-controller-main-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/cert-policy-controller/open-cluster-management-cert-policy-controller-release-2.3-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/config-policy-controller/open-cluster-management-config-policy-controller-main-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/config-policy-controller/open-cluster-management-config-policy-controller-release-2.3-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/governance-policy-propagator/open-cluster-management-governance-policy-propagator-main-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/governance-policy-propagator/open-cluster-management-governance-policy-propagator-release-2.3-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/governance-policy-spec-sync/open-cluster-management-governance-policy-spec-sync-main-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/governance-policy-spec-sync/open-cluster-management-governance-policy-spec-sync-release-2.3-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/governance-policy-status-sync/open-cluster-management-governance-policy-status-sync-main-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/governance-policy-status-sync/open-cluster-management-governance-policy-status-sync-release-2.3-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/governance-policy-template-sync/open-cluster-management-governance-policy-template-sync-main-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/governance-policy-template-sync/open-cluster-management-governance-policy-template-sync-release-2.3-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/iam-policy-controller/open-cluster-management-iam-policy-controller-main-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/iam-policy-controller/open-cluster-management-iam-policy-controller-release-2.3-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/security-middleware/open-cluster-management-security-middleware-main-postsubmits.yaml
Labels: approved, lgtm

#17525 Update vault to 1.7.0
  clusters/app.ci/supplemental-ci-images/go-vault.yaml
  clusters/app.ci/vault/manifests.yaml
Labels: approved, lgtm

#17367 fix e2e-aws-upi tests
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
Labels: approved, lgtm

#17475 ci-operator: Update the dockerfile_path for the OLM and operator-registry images
  ci-operator/config/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-master.yaml
  ci-operator/config/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-release-4.8.yaml
  ci-operator/config/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-release-4.9.yaml
  ci-operator/config/operator-framework/operator-registry/operator-framework-operator-registry-master.yaml
  ci-operator/config/operator-framework/operator-registry/operator-framework-operator-registry-release-4.8.yaml
  ci-operator/config/operator-framework/operator-registry/operator-framework-operator-registry-release-4.9.yaml
Labels: approved, lgtm

#17529 Remove useless e2e-aws test from VPA Operator
  ci-operator/config/openshift/vertical-pod-autoscaler-operator/openshift-vertical-pod-autoscaler-operator-master.yaml
  ci-operator/config/openshift/vertical-pod-autoscaler-operator/openshift-vertical-pod-autoscaler-operator-release-4.8.yaml
  ci-operator/jobs/openshift/vertical-pod-autoscaler-operator/openshift-vertical-pod-autoscaler-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/vertical-pod-autoscaler-operator/openshift-vertical-pod-autoscaler-operator-release-4.8-presubmits.yaml
Labels: approved, lgtm

#17531 Add prow merging for openshift/managed-notifications
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#17527 core-services/prow/02_config: Restore Tide for Cincinanti release branches
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#17521 rename the ocm publish image
  ci-operator/config/open-cluster-management/endpoint-metrics-operator/open-cluster-management-endpoint-metrics-operator-main.yaml
  ci-operator/config/open-cluster-management/endpoint-metrics-operator/open-cluster-management-endpoint-metrics-operator-release-2.3.yaml
Labels: approved, lgtm

#17371 Bug 1936867: Fallback to pip2 when there is no pip3
  ci-operator/step-registry/ipi/conf/vsphere/dns/ipi-conf-vsphere-dns-commands.sh
  ci-operator/step-registry/ipi/deprovision/vsphere/dns/ipi-deprovision-vsphere-dns-commands.sh
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#17486 Modify the unit test target to insights operator
  ci-operator/config/openshift/insights-operator/openshift-insights-operator-master.yaml
  ci-operator/config/openshift/insights-operator/openshift-insights-operator-release-4.8.yaml
  ci-operator/config/openshift/insights-operator/openshift-insights-operator-release-4.9.yaml
Labels: approved, lgtm

#17497 add observatorium 2.3 and main branch to prow
  ci-operator/config/open-cluster-management/observatorium/open-cluster-management-observatorium-main.yaml
  ci-operator/config/open-cluster-management/observatorium/open-cluster-management-observatorium-release-2.3.yaml
  ci-operator/jobs/open-cluster-management/observatorium/open-cluster-management-observatorium-main-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/observatorium/open-cluster-management-observatorium-main-presubmits.yaml
  ci-operator/jobs/open-cluster-management/observatorium/open-cluster-management-observatorium-release-2.3-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/observatorium/open-cluster-management-observatorium-release-2.3-presubmits.yaml
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#17549 Bump OCP version for integr8ly/cloud-resource-operator testing
  ci-operator/config/integr8ly/cloud-resource-operator/integr8ly-cloud-resource-operator-master.yaml
Labels: approved, lgtm

#17550 extend a timeout for the encryption jobs to 4 hours
  ci-operator/config/openshift/cluster-authentication-operator/openshift-cluster-authentication-operator-master.yaml
  ci-operator/config/openshift/cluster-kube-apiserver-operator/openshift-cluster-kube-apiserver-operator-master.yaml
  ci-operator/config/openshift/cluster-openshift-apiserver-operator/openshift-cluster-openshift-apiserver-operator-master.yaml
Labels: approved, lgtm

#17548 Use proper golang-1.16 builder for openshift/origin
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
Labels: approved, lgtm

#17500 loki: monitor promtail metrics
  ci-operator/step-registry/ipi/install/hosted-loki/ipi-install-hosted-loki-commands.sh
Labels: approved, lgtm

#17542 Remove cluster-api-provider-kubevirt 4.7 release jobs
  ci-operator/config/openshift/cluster-api-provider-kubevirt/openshift-cluster-api-provider-kubevirt-release-4.7.yaml
  ci-operator/jobs/openshift/cluster-api-provider-kubevirt/openshift-cluster-api-provider-kubevirt-release-4.7-periodics.yaml
  ci-operator/jobs/openshift/cluster-api-provider-kubevirt/openshift-cluster-api-provider-kubevirt-release-4.7-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-kubevirt/openshift-cluster-api-provider-kubevirt-release-4.7-presubmits.yaml
Labels: approved, lgtm

#17164 Add serial suite configuration into baremetald step registry
  ci-operator/config/openshift/baremetal-operator/openshift-baremetal-operator-master.yaml
  ci-operator/config/openshift/cluster-baremetal-operator/openshift-cluster-baremetal-operator-master.yaml
  ci-operator/jobs/openshift/baremetal-operator/openshift-baremetal-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-baremetal-operator/openshift-cluster-baremetal-operator-master-presubmits.yaml
  ci-operator/step-registry/baremetalds/e2e/serial/OWNERS
  ci-operator/step-registry/baremetalds/e2e/serial/ipv4/OWNERS
  ci-operator/step-registry/baremetalds/e2e/serial/ipv4/baremetalds-e2e-serial-ipv4-workflow.metadata.json
  ci-operator/step-registry/baremetalds/e2e/serial/ipv4/baremetalds-e2e-serial-ipv4-workflow.yaml
  ci-operator/step-registry/baremetalds/ipi/OWNERS
  ci-operator/step-registry/baremetalds/ipi/post/OWNERS
  ci-operator/step-registry/baremetalds/ipi/post/baremetalds-ipi-post-chain.metadata.json
  ci-operator/step-registry/baremetalds/ipi/post/baremetalds-ipi-post-chain.yaml
  ci-operator/step-registry/baremetalds/ipi/pre/OWNERS
  ci-operator/step-registry/baremetalds/ipi/pre/baremetalds-ipi-pre-chain.metadata.json
  ci-operator/step-registry/baremetalds/ipi/pre/baremetalds-ipi-pre-chain.yaml
Labels: approved, lgtm

#17481 Add e2e-serial jobs to all network-edge component repos
  ci-operator/config/openshift/cluster-dns-operator/openshift-cluster-dns-operator-master.yaml
  ci-operator/config/openshift/cluster-ingress-operator/openshift-cluster-ingress-operator-master.yaml
  ci-operator/config/openshift/coredns/openshift-coredns-master.yaml
  ci-operator/config/openshift/router/openshift-router-master.yaml
  ci-operator/jobs/openshift/cluster-dns-operator/openshift-cluster-dns-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-ingress-operator/openshift-cluster-ingress-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/coredns/openshift-coredns-master-presubmits.yaml
  ci-operator/jobs/openshift/router/openshift-router-master-presubmits.yaml
Labels: approved, lgtm

#17528 Revert "Mark release-openshift-ocp-installer-e2e-aws-upi-4.8 as broken"
  core-services/testgrid-config-generator/_allow-list.yaml
Labels: approved, lgtm

#17406 kata-containers: Use centos 8 build root
  ci-operator/config/kata-containers/kata-containers/kata-containers-kata-containers-main.yaml
Labels: approved, lgtm

#17472 Remove vmware prefix from CSI operator and driver
  ci-operator/config/openshift/vmware-vsphere-csi-driver-operator/openshift-vmware-vsphere-csi-driver-operator-master.yaml
  ci-operator/config/openshift/vmware-vsphere-csi-driver-operator/openshift-vmware-vsphere-csi-driver-operator-release-4.8.yaml
  ci-operator/config/openshift/vmware-vsphere-csi-driver-operator/openshift-vmware-vsphere-csi-driver-operator-release-4.9.yaml
  ci-operator/config/openshift/vmware-vsphere-csi-driver/openshift-vmware-vsphere-csi-driver-master.yaml
  ci-operator/config/openshift/vmware-vsphere-csi-driver/openshift-vmware-vsphere-csi-driver-release-4.8.yaml
  ci-operator/config/openshift/vmware-vsphere-csi-driver/openshift-vmware-vsphere-csi-driver-release-4.9.yaml
Labels: approved, lgtm

#17560 Fix CI steps for vsphere operator
  ci-operator/step-registry/openshift/e2e/vsphere/csi/openshift-e2e-vsphere-csi-workflow.yaml
  ci-operator/step-registry/storage/conf/csi-vmware-vsphere/storage-conf-csi-vmware-vsphere-commands.sh
Labels: approved, lgtm

#17561 ocm step-registry: update e2e steps
  ci-operator/step-registry/ocm/e2e/clusterpool/checkin/ocm-e2e-clusterpool-checkin-commands.sh
  ci-operator/step-registry/ocm/e2e/clusterpool/checkin/ocm-e2e-clusterpool-checkin-ref.yaml
  ci-operator/step-registry/ocm/e2e/clusterpool/checkout/ocm-e2e-clusterpool-checkout-chain.yaml
  ci-operator/step-registry/ocm/e2e/clusterpool/checkout/ocm-e2e-clusterpool-checkout-ref.yaml
  ci-operator/step-registry/ocm/e2e/clusterpool/cluster/deploy/ocm-e2e-clusterpool-cluster-deploy-ref.yaml
  ci-operator/step-registry/ocm/e2e/clusterpool/cluster/getcreds/OWNERS
  ci-operator/step-registry/ocm/e2e/clusterpool/cluster/getcreds/ocm-e2e-clusterpool-cluster-getcreds-commands.sh
  ci-operator/step-registry/ocm/e2e/clusterpool/cluster/getcreds/ocm-e2e-clusterpool-cluster-getcreds-ref.metadata.json
  ci-operator/step-registry/ocm/e2e/clusterpool/cluster/getcreds/ocm-e2e-clusterpool-cluster-getcreds-ref.yaml
  ci-operator/step-registry/ocm/e2e/clusterpool/cluster/getkubeconfig/ocm-e2e-clusterpool-cluster-getkubeconfig-ref.metadata.json
  ci-operator/step-registry/ocm/e2e/clusterpool/cluster/getmetadata/OWNERS
  ci-operator/step-registry/ocm/e2e/clusterpool/cluster/getmetadata/ocm-e2e-clusterpool-cluster-getmetadata-commands.sh
  ci-operator/step-registry/ocm/e2e/clusterpool/cluster/getmetadata/ocm-e2e-clusterpool-cluster-getmetadata-ref.yaml
  ci-operator/step-registry/ocm/e2e/clusterpool/list/ocm-e2e-clusterpool-list-ref.yaml
  ci-operator/step-registry/ocm/e2e/clusterpool/ocm-e2e-clusterpool-workflow.yaml
  ci-operator/step-registry/ocm/e2e/rbac/ocm-e2e-rbac-ref.yaml
Labels: approved, lgtm

#17536 coreos: Port ostree, rpm-ostree, bootupd to use fcos-buildroot
  ci-operator/config/coreos/bootupd/coreos-bootupd-master.yaml
  ci-operator/config/coreos/rpm-ostree/coreos-rpm-ostree-master.yaml
  ci-operator/config/ostreedev/ostree/ostreedev-ostree-master.yaml
  clusters/app.ci/supplemental-ci-images/coreos/README.md
Labels: approved, lgtm

#17565 ci-operator: Remove the OCP e2e-related jobs from the upstream OLM/registry prow configurations
  ci-operator/config/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-master.yaml
  ci-operator/config/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-release-4.8.yaml
  ci-operator/config/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-release-4.9.yaml
  ci-operator/config/operator-framework/operator-registry/operator-framework-operator-registry-master.yaml
  ci-operator/config/operator-framework/operator-registry/operator-framework-operator-registry-release-4.8.yaml
  ci-operator/config/operator-framework/operator-registry/operator-framework-operator-registry-release-4.9.yaml
  ci-operator/jobs/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-master-presubmits.yaml
  ci-operator/jobs/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-release-4.8-presubmits.yaml
  ci-operator/jobs/operator-framework/operator-lifecycle-manager/operator-framework-operator-lifecycle-manager-release-4.9-presubmits.yaml
  ci-operator/jobs/operator-framework/operator-registry/operator-framework-operator-registry-master-presubmits.yaml
  ci-operator/jobs/operator-framework/operator-registry/operator-framework-operator-registry-release-4.8-presubmits.yaml
  ci-operator/jobs/operator-framework/operator-registry/operator-framework-operator-registry-release-4.9-presubmits.yaml
Labels: approved, lgtm

#17567 Fix ovirt cron times
  ci-operator/config/openshift/release/openshift-release-master__ci-4.5-upgrade-from-stable-4.4.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.6-upgrade-from-stable-4.5.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.7-upgrade-from-stable-4.6.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.8-upgrade-from-stable-4.7.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: approved, lgtm

#17568 ci-operators/jobs: Mark the OCP e2e-related jobs as required
  ci-operator/jobs/openshift/operator-framework-olm/openshift-operator-framework-olm-master-presubmits.yaml
  ci-operator/jobs/openshift/operator-framework-olm/openshift-operator-framework-olm-release-4.8-presubmits.yaml
  ci-operator/jobs/openshift/operator-framework-olm/openshift-operator-framework-olm-release-4.9-presubmits.yaml
Labels: approved, lgtm

#17569 ocm hellowprow: update images and test config
  ci-operator/config/open-cluster-management/helloprow-go/open-cluster-management-helloprow-go-main.yaml
  ci-operator/config/open-cluster-management/helloprow-go/open-cluster-management-helloprow-go-release-2.3.yaml
Labels: approved, lgtm

#17574 remove cicd members from ownership
  ci-operator/config/open-cluster-management/application-ui/OWNERS
  ci-operator/config/open-cluster-management/console-api/OWNERS
  ci-operator/jobs/open-cluster-management/application-ui/OWNERS
  ci-operator/jobs/open-cluster-management/console-api/OWNERS
Labels: approved, lgtm

#17573 ci-operator: Update the openshift/operator-framework-olm OWNERS
  ci-operator/config/openshift/operator-framework-olm/OWNERS
  ci-operator/jobs/openshift/operator-framework-olm/OWNERS
Labels: approved, lgtm

#17526 Include Azure Disk CSI Certification tests
  ci-operator/config/openshift/azure-disk-csi-driver-operator/openshift-azure-disk-csi-driver-operator-master.yaml
  ci-operator/config/openshift/azure-disk-csi-driver-operator/openshift-azure-disk-csi-driver-operator-release-4.8.yaml
  ci-operator/config/openshift/azure-disk-csi-driver-operator/openshift-azure-disk-csi-driver-operator-release-4.9.yaml
  ci-operator/jobs/openshift/azure-disk-csi-driver-operator/openshift-azure-disk-csi-driver-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/azure-disk-csi-driver-operator/openshift-azure-disk-csi-driver-operator-release-4.8-presubmits.yaml
  ci-operator/jobs/openshift/azure-disk-csi-driver-operator/openshift-azure-disk-csi-driver-operator-release-4.9-presubmits.yaml
  ci-operator/step-registry/openshift/e2e/azure/csi/OWNERS
  ci-operator/step-registry/openshift/e2e/azure/csi/openshift-e2e-azure-csi-workflow.metadata.json
  ci-operator/step-registry/openshift/e2e/azure/csi/openshift-e2e-azure-csi-workflow.yaml
  ci-operator/step-registry/storage/conf/csi-azure-disk/OWNERS
  ci-operator/step-registry/storage/conf/csi-azure-disk/storage-conf-csi-azure-disk-commands.sh
  ci-operator/step-registry/storage/conf/csi-azure-disk/storage-conf-csi-azure-disk-ref.metadata.json
  ci-operator/step-registry/storage/conf/csi-azure-disk/storage-conf-csi-azure-disk-ref.yaml
Labels: approved, lgtm

#17570 Fix prow job step name
  ci-operator/jobs/open-cluster-management/provider-credential-controller/open-cluster-management-provider-credential-controller-main-postsubmits.yaml
Labels: approved, lgtm

#17577 ocm step list: Add clusterpool filters, fix cluster filters
  ci-operator/config/open-cluster-management/helloprow-go/open-cluster-management-helloprow-go-main.yaml
  ci-operator/config/open-cluster-management/helloprow-go/open-cluster-management-helloprow-go-release-2.3.yaml
  ci-operator/step-registry/ocm/e2e/clusterpool/cluster/deploy/ocm-e2e-clusterpool-cluster-deploy-commands.sh
  ci-operator/step-registry/ocm/e2e/clusterpool/list/ocm-e2e-clusterpool-list-commands.sh
  ci-operator/step-registry/ocm/e2e/clusterpool/list/ocm-e2e-clusterpool-list-ref.yaml
Labels: approved, lgtm

#17575 Fix vault HA
  clusters/app.ci/vault/manifests.yaml
Labels: approved, lgtm

#17474 openshift/cbo: Update base images for baremetalds-assisted workflow
  ci-operator/config/openshift/cluster-baremetal-operator/openshift-cluster-baremetal-operator-release-4.7.yaml
Labels: approved, lgtm

#17452 Adding 3-node cluster ("compact") job to 4.8 CI
  ci-operator/jobs/openshift/multiarch/openshift-multiarch-release-4.8-periodics.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-remote-libvirt-e2e.yaml
  core-services/template-deprecation/_allowlist.yaml
Labels: approved, lgtm

#13990 Cincinnati: build OSUS using "stable" Rust version
  ci-operator/config/openshift/cincinnati/openshift-cincinnati-master__stablerust.yaml
  ci-operator/jobs/openshift/cincinnati/openshift-cincinnati-master-presubmits.yaml
Labels: approved, lgtm

#17582 Vault: Use native sd for active replica routing
  clusters/app.ci/vault/manifests.yaml
Labels: approved, lgtm

#17587 Remove 4.5 jobs for tektoncd cli
  ci-operator/config/openshift/tektoncd-cli/openshift-tektoncd-cli-release-next__4.5.yaml
  ci-operator/jobs/openshift/tektoncd-cli/openshift-tektoncd-cli-release-next-presubmits.yaml
Labels: approved, lgtm

#17595 fix base image not found issue for mco.
  ci-operator/config/open-cluster-management/multicluster-observability-operator/open-cluster-management-multicluster-observability-operator-main.yaml
  ci-operator/config/open-cluster-management/multicluster-observability-operator/open-cluster-management-multicluster-observability-operator-release-2.3.yaml
Labels: approved, lgtm

#17557 Bump go to 1.16 in storage components
  ci-operator/config/openshift/aws-ebs-csi-driver-operator/openshift-aws-ebs-csi-driver-operator-master.yaml
  ci-operator/config/openshift/aws-ebs-csi-driver-operator/openshift-aws-ebs-csi-driver-operator-release-4.8.yaml
  ci-operator/config/openshift/aws-ebs-csi-driver-operator/openshift-aws-ebs-csi-driver-operator-release-4.9.yaml
  ci-operator/config/openshift/cluster-csi-snapshot-controller-operator/openshift-cluster-csi-snapshot-controller-operator-master.yaml
  ci-operator/config/openshift/cluster-csi-snapshot-controller-operator/openshift-cluster-csi-snapshot-controller-operator-release-4.8.yaml
  ci-operator/config/openshift/cluster-csi-snapshot-controller-operator/openshift-cluster-csi-snapshot-controller-operator-release-4.9.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-master.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.8.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.9.yaml
  ci-operator/config/openshift/csi-driver-manila-operator/openshift-csi-driver-manila-operator-master.yaml
  ci-operator/config/openshift/csi-driver-manila-operator/openshift-csi-driver-manila-operator-release-4.8.yaml
  ci-operator/config/openshift/csi-driver-manila-operator/openshift-csi-driver-manila-operator-release-4.9.yaml
  ci-operator/config/openshift/csi-driver-nfs/openshift-csi-driver-nfs-master.yaml
  ci-operator/config/openshift/csi-driver-nfs/openshift-csi-driver-nfs-release-4.8.yaml
  ci-operator/config/openshift/csi-driver-nfs/openshift-csi-driver-nfs-release-4.9.yaml
  ci-operator/config/openshift/csi-external-attacher/openshift-csi-external-attacher-master.yaml
  ci-operator/config/openshift/csi-external-attacher/openshift-csi-external-attacher-release-4.8.yaml
  ci-operator/config/openshift/csi-external-attacher/openshift-csi-external-attacher-release-4.9.yaml
  ci-operator/config/openshift/csi-external-provisioner/openshift-csi-external-provisioner-master.yaml
  ci-operator/config/openshift/csi-external-provisioner/openshift-csi-external-provisioner-release-4.8.yaml
  ci-operator/config/openshift/csi-external-provisioner/openshift-csi-external-provisioner-release-4.9.yaml
  ci-operator/config/openshift/csi-external-resizer/openshift-csi-external-resizer-master.yaml
  ci-operator/config/openshift/csi-external-resizer/openshift-csi-external-resizer-release-4.8.yaml
  ci-operator/config/openshift/csi-external-resizer/openshift-csi-external-resizer-release-4.9.yaml
  ci-operator/config/openshift/csi-external-snapshotter/openshift-csi-external-snapshotter-master.yaml
  ci-operator/config/openshift/csi-external-snapshotter/openshift-csi-external-snapshotter-release-4.8.yaml
  ci-operator/config/openshift/csi-external-snapshotter/openshift-csi-external-snapshotter-release-4.9.yaml
  ci-operator/config/openshift/csi-livenessprobe/openshift-csi-livenessprobe-master.yaml
  ci-operator/config/openshift/csi-livenessprobe/openshift-csi-livenessprobe-release-4.8.yaml
  ci-operator/config/openshift/csi-livenessprobe/openshift-csi-livenessprobe-release-4.9.yaml
  ci-operator/config/openshift/csi-node-driver-registrar/openshift-csi-node-driver-registrar-master.yaml
  ci-operator/config/openshift/csi-node-driver-registrar/openshift-csi-node-driver-registrar-release-4.8.yaml
  ci-operator/config/openshift/csi-node-driver-registrar/openshift-csi-node-driver-registrar-release-4.9.yaml
  ci-operator/config/openshift/gcp-pd-csi-driver-operator/openshift-gcp-pd-csi-driver-operator-master.yaml
  ci-operator/config/openshift/gcp-pd-csi-driver-operator/openshift-gcp-pd-csi-driver-operator-release-4.8.yaml
  ci-operator/config/openshift/gcp-pd-csi-driver-operator/openshift-gcp-pd-csi-driver-operator-release-4.9.yaml
  ci-operator/config/openshift/gcp-pd-csi-driver/openshift-gcp-pd-csi-driver-master.yaml
  ci-operator/config/openshift/gcp-pd-csi-driver/openshift-gcp-pd-csi-driver-release-4.8.yaml
  ci-operator/config/openshift/gcp-pd-csi-driver/openshift-gcp-pd-csi-driver-release-4.9.yaml
  ci-operator/config/openshift/openstack-cinder-csi-driver-operator/openshift-openstack-cinder-csi-driver-operator-master.yaml
  ci-operator/config/openshift/openstack-cinder-csi-driver-operator/openshift-openstack-cinder-csi-driver-operator-release-4.8.yaml
  ci-operator/config/openshift/openstack-cinder-csi-driver-operator/openshift-openstack-cinder-csi-driver-operator-release-4.9.yaml
  ci-operator/config/openshift/ovirt-csi-driver/openshift-ovirt-csi-driver-master.yaml
  ci-operator/config/openshift/ovirt-csi-driver/openshift-ovirt-csi-driver-release-4.8.yaml
  ci-operator/config/openshift/ovirt-csi-driver/openshift-ovirt-csi-driver-release-4.9.yaml
  ci-operator/config/openshift/vsphere-problem-detector/openshift-vsphere-problem-detector-master.yaml
  ci-operator/config/openshift/vsphere-problem-detector/openshift-vsphere-problem-detector-release-4.8.yaml
  ci-operator/config/openshift/vsphere-problem-detector/openshift-vsphere-problem-detector-release-4.9.yaml
Labels: approved, lgtm

#17598 Revert "loki: monitor promtail metrics"
  ci-operator/step-registry/ipi/install/hosted-loki/ipi-install-hosted-loki-commands.sh
Labels: approved, lgtm

#17601 Update skipped tests names for P and Z
  ci-operator/jobs/openshift/multiarch/openshift-multiarch-release-4.8-periodics.yaml
Labels: approved, lgtm

#17603 Includes Azure CSI jobs
  ci-operator/config/openshift/azure-disk-csi-driver/openshift-azure-disk-csi-driver-master.yaml
  ci-operator/config/openshift/azure-disk-csi-driver/openshift-azure-disk-csi-driver-release-4.8.yaml
  ci-operator/config/openshift/azure-disk-csi-driver/openshift-azure-disk-csi-driver-release-4.9.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-master.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.8.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.9.yaml
  ci-operator/jobs/openshift/azure-disk-csi-driver/openshift-azure-disk-csi-driver-master-presubmits.yaml
  ci-operator/jobs/openshift/azure-disk-csi-driver/openshift-azure-disk-csi-driver-release-4.8-presubmits.yaml
  ci-operator/jobs/openshift/azure-disk-csi-driver/openshift-azure-disk-csi-driver-release-4.9-presubmits.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.8-presubmits.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.9-presubmits.yaml
Labels: approved, lgtm

#17605 fix incorrect image name for prow job.
  ci-operator/config/open-cluster-management/endpoint-metrics-operator/open-cluster-management-endpoint-metrics-operator-main.yaml
  ci-operator/config/open-cluster-management/endpoint-metrics-operator/open-cluster-management-endpoint-metrics-operator-release-2.3.yaml
Labels: approved, lgtm

#17533 Move scope of coreos namespace to all clusters
  clusters/build-clusters/common/coreos.yaml
Labels: approved, lgtm

#17597 Add prow merging for openshift/runbooks
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#17609 Makefile: Update the gcr.io/k8s-prow/checkconfig tag
  Makefile
Labels: approved, lgtm

#17608 Remove arch from Go builder images
  ci-operator/config/open-cluster-management/discovery/open-cluster-management-discovery-main.yaml
  ci-operator/config/open-cluster-management/discovery/open-cluster-management-discovery-release-2.3.yaml
  ci-operator/config/open-cluster-management/multicloudhub-operator/open-cluster-management-multicloudhub-operator-main.yaml
  ci-operator/config/open-cluster-management/multicloudhub-operator/open-cluster-management-multicloudhub-operator-release-2.3.yaml
  ci-operator/config/open-cluster-management/multicloudhub-repo/open-cluster-management-multicloudhub-repo-main.yaml
  ci-operator/config/open-cluster-management/multicloudhub-repo/open-cluster-management-multicloudhub-repo-release-2.3.yaml
  ci-operator/jobs/open-cluster-management/discovery/open-cluster-management-discovery-main-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/discovery/open-cluster-management-discovery-release-2.3-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/multicloudhub-operator/open-cluster-management-multicloudhub-operator-main-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/multicloudhub-operator/open-cluster-management-multicloudhub-operator-release-2.3-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/multicloudhub-repo/open-cluster-management-multicloudhub-repo-main-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/multicloudhub-repo/open-cluster-management-multicloudhub-repo-release-2.3-postsubmits.yaml
Labels: approved, lgtm

#17611 ocm: enable dco plugin for application repos
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#17610 Update broken link in README (Step registry help link)
  README.md
Labels: approved, lgtm

#17616 Move adapter_imagestreams.yaml to app.ci
  clusters/app.ci/prow/03_deployment/adapter_imagestreams.yaml
Labels: approved, lgtm

#17606 4.8 Feature Freeze
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#17586 Add optional e2e-ci tests for VPA operator
  ci-operator/config/openshift/vertical-pod-autoscaler-operator/openshift-vertical-pod-autoscaler-operator-master.yaml
  ci-operator/config/openshift/vertical-pod-autoscaler-operator/openshift-vertical-pod-autoscaler-operator-release-4.8.yaml
  ci-operator/jobs/openshift/vertical-pod-autoscaler-operator/openshift-vertical-pod-autoscaler-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/vertical-pod-autoscaler-operator/openshift-vertical-pod-autoscaler-operator-release-4.8-presubmits.yaml
Labels: approved, lgtm

#17620 release-controller: Rename 8.4 beta repos to 84
  core-services/release-controller/_repos/ocp-4.8-rhel84.repo
  core-services/release-controller/_repos/ocp-4.9-rhel84.repo
Labels: approved, lgtm

#17618 builder image updates for cluster-lifecycle images
  ci-operator/config/open-cluster-management/klusterlet-addon-controller/open-cluster-management-klusterlet-addon-controller-main.yaml
  ci-operator/config/open-cluster-management/klusterlet-addon-controller/open-cluster-management-klusterlet-addon-controller-release-2.3.yaml
  ci-operator/config/open-cluster-management/klusterlet-addon-operator/open-cluster-management-klusterlet-addon-operator-main.yaml
  ci-operator/config/open-cluster-management/klusterlet-addon-operator/open-cluster-management-klusterlet-addon-operator-release-2.3.yaml
  ci-operator/config/open-cluster-management/managedcluster-import-controller/open-cluster-management-managedcluster-import-controller-main.yaml
  ci-operator/config/open-cluster-management/managedcluster-import-controller/open-cluster-management-managedcluster-import-controller-release-2.3.yaml
  ci-operator/jobs/open-cluster-management/klusterlet-addon-controller/open-cluster-management-klusterlet-addon-controller-main-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/klusterlet-addon-controller/open-cluster-management-klusterlet-addon-controller-release-2.3-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/klusterlet-addon-operator/open-cluster-management-klusterlet-addon-operator-release-2.3-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/managedcluster-import-controller/open-cluster-management-managedcluster-import-controller-main-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/managedcluster-import-controller/open-cluster-management-managedcluster-import-controller-release-2.3-postsubmits.yaml
Labels: approved, lgtm

#17615 Add DCO and change image
  ci-operator/config/open-cluster-management/applier/open-cluster-management-applier-main.yaml
  ci-operator/config/open-cluster-management/applier/open-cluster-management-applier-prow-experiment.yaml
  ci-operator/config/open-cluster-management/library-go/open-cluster-management-library-go-main.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, tide/merge-method-squash

#17563 Add knative-eventing release-v0.22.0
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.22.0__47.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.22.0-periodics.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.22.0-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.22.0-presubmits.yaml
  core-services/image-mirroring/knative/mapping_knative_v0_22_quay
Labels: approved, lgtm

#17631 Revert "4.8 Feature Freeze"
  core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#17625 update docker image
  ci-operator/config/open-cluster-management/console/open-cluster-management-console-main.yaml
  ci-operator/config/open-cluster-management/console/open-cluster-management-console-release-2.3.yaml
  ci-operator/jobs/open-cluster-management/console/open-cluster-management-console-main-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/console/open-cluster-management-console-release-2.3-postsubmits.yaml
Labels: approved, lgtm

#17628 OCM: provider-credential-controller - Enable DCO plugin and run -short sonar
  ci-operator/jobs/open-cluster-management/provider-credential-controller/open-cluster-management-provider-credential-controller-main-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/provider-credential-controller/open-cluster-management-provider-credential-controller-release-2.3-postsubmits.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, tide/merge-method-squash

#17633 builder image update and add dco for cluster lifecycle images
  ci-operator/config/open-cluster-management/cluster-curator-controller/open-cluster-management-cluster-curator-controller-main.yaml
  ci-operator/config/open-cluster-management/cluster-curator-controller/open-cluster-management-cluster-curator-controller-release-2.3.yaml
  ci-operator/config/open-cluster-management/clusterlifecycle-state-metrics/open-cluster-management-clusterlifecycle-state-metrics-main.yaml
  ci-operator/config/open-cluster-management/clusterlifecycle-state-metrics/open-cluster-management-clusterlifecycle-state-metrics-prow-experiment.yaml
  ci-operator/config/open-cluster-management/clusterlifecycle-state-metrics/open-cluster-management-clusterlifecycle-state-metrics-release-2.3.yaml
  ci-operator/config/open-cluster-management/provider-credential-controller/open-cluster-management-provider-credential-controller-main.yaml
  ci-operator/config/open-cluster-management/provider-credential-controller/open-cluster-management-provider-credential-controller-release-2.3.yaml
  ci-operator/jobs/open-cluster-management/cluster-curator-controller/open-cluster-management-cluster-curator-controller-main-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/cluster-curator-controller/open-cluster-management-cluster-curator-controller-release-2.3-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/clusterlifecycle-state-metrics/open-cluster-management-clusterlifecycle-state-metrics-prow-experiment-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/clusterlifecycle-state-metrics/open-cluster-management-clusterlifecycle-state-metrics-prow-experiment-presubmits.yaml
  ci-operator/jobs/open-cluster-management/clusterlifecycle-state-metrics/open-cluster-management-clusterlifecycle-state-metrics-release-2.3-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/provider-credential-controller/open-cluster-management-provider-credential-controller-main-postsubmits.yaml
  ci-operator/jobs/open-cluster-management/provider-credential-controller/open-cluster-management-provider-credential-controller-release-2.3-postsubmits.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm, tide/merge-method-squash

#17629 release-controller: Add generated deployments for RHEL 8.4 repos
  clusters/build-clusters/common/release-controller/rpms-ocp-4.8.yaml
  clusters/build-clusters/common/release-controller/rpms-ocp-4.9.yaml
Labels: lgtm

#17612 Create secrets for Hive cluster pools
  clusters/app.ci/ci-cluster-pool/additional-scrape-configs_secret.yaml
  clusters/app.ci/ci-cluster-pool/ci-cluster-pool_ns.yaml
  core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#17623 Add VPA test manifest-diff
  ci-operator/config/openshift/vertical-pod-autoscaler-operator/openshift-vertical-pod-autoscaler-operator-master.yaml
  ci-operator/config/openshift/vertical-pod-autoscaler-operator/openshift-vertical-pod-autoscaler-operator-release-4.8.yaml
  ci-operator/jobs/openshift/vertical-pod-autoscaler-operator/openshift-vertical-pod-autoscaler-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/vertical-pod-autoscaler-operator/openshift-vertical-pod-autoscaler-operator-release-4.8-presubmits.yaml
Labels: approved, lgtm

#17564 Add knative-kafka release-v0.22.0
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.22.0__47.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.22.0-periodics.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.22.0-postsubmits.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.22.0-presubmits.yaml
Labels: approved, lgtm

#17641 Bug 1926816: VPA should be using ocp base image, also switch to 1.16
  ci-operator/config/openshift-priv/kubernetes-autoscaler/openshift-priv-kubernetes-autoscaler-master.yaml
  ci-operator/config/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-master.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#17646 secrets: add a GCE service account for resource data
  core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#17647 adding nmstate config creation to kube-api job
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
Labels: approved, lgtm

#17649 Horologium: Allow watching prowjobs
  clusters/app.ci/prow/03_deployment/admin_horologium_rbac.yaml
Labels: approved, lgtm
