Repository openshift/release, pull requests merged in 2022-10, with the labels that each got.

#32784 Revert "ROX-12686: Remove postgres e2e nightlies (#32533)"
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-nightlies-postsubmits.yaml
Labels: lgtm, approved, ok-to-test

#32785 stackrox: mirror rox-ci-image 0.3.50 for build-root(s)
  core-services/image-mirroring/stackrox/mapping_supplemental_ci_images_stackrox_rox_ci_image
Labels: lgtm, approved

#32749 [build05] Adds dns forwarding for the zone arm.eng.rdu2.redhat.com to an internal bind9 instance at rdu2
  clusters/build-clusters/build05/assets/dns.yaml
Labels: lgtm, approved

#32193 fix: updated go version to 1.18
  ci-operator/config/red-hat-storage/lvm-operator/red-hat-storage-lvm-operator-main.yaml
Labels: lgtm, approved, needs-ok-to-test

#32351 Refactor stackrox/collector configuration
  ci-operator/config/stackrox/collector/stackrox-collector-master.yaml
  ci-operator/jobs/stackrox/collector/stackrox-collector-master-postsubmits.yaml
  ci-operator/jobs/stackrox/collector/stackrox-collector-master-presubmits.yaml
  ci-operator/step-registry/stackrox/collector/integration-tests/setup/stackrox-collector-integration-tests-setup-ref.yaml
  ci-operator/step-registry/stackrox/collector/integration-tests/stackrox-collector-integration-tests-workflow.yaml
  ci-operator/step-registry/stackrox/collector/integration-tests/teardown/stackrox-collector-integration-tests-teardown-ref.yaml
  ci-operator/step-registry/stackrox/collector/update-support-packages/setup/stackrox-collector-update-support-packages-setup-ref.yaml
  ci-operator/step-registry/stackrox/collector/update-support-packages/stackrox-collector-update-support-packages-workflow.yaml
  ci-operator/step-registry/stackrox/collector/update-support-packages/teardown/stackrox-collector-update-support-packages-teardown-ref.yaml
Labels: lgtm, approved

#32777 supplemental-ci-images: add OpenVPN image
  clusters/app.ci/supplemental-ci-images/README.md
  clusters/app.ci/supplemental-ci-images/openvpn.yaml
Labels: lgtm, approved, tide/merge-method-merge

#32795 Disable always_run: true
  ci-operator/jobs/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-main-presubmits.yaml
  ci-operator/jobs/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-release-4.10-presubmits.yaml
  ci-operator/jobs/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-release-4.9-presubmits.yaml
Labels: lgtm, approved

#32796 openshift-e2e-aws-ccm-install: update TEST_SKIPS after apigroup labeling and renaming
  ci-operator/step-registry/openshift/e2e/aws/ccm/install/openshift-e2e-aws-ccm-install-workflow.yaml
Labels: lgtm, approved

#32621 ci-chat-bot/release-controller: use tokenFile in the kubeconfigs
  core-services/ci-secret-bootstrap/_config.yaml
  core-services/ci-secret-generator/_config.yaml
Labels: lgtm, approved

#32805 Add new ClusterPool resources for openstack-k8s-operators
  clusters/hive/pools/openstack-k8s-operators/install-config-sno_secret_osp_01.yaml
  clusters/hive/pools/openstack-k8s-operators/install-config-sno_secret_osp_02.yaml
  clusters/hive/pools/openstack-k8s-operators/install-config-sno_secret_osp_03.yaml
  clusters/hive/pools/openstack-k8s-operators/openstack-k8s-operators-4-10-vexxhost-sno_clusterpool.yaml
  clusters/hive/pools/openstack-k8s-operators/openstack-k8s-operators-4-10-vexxhost-sno_clusterpool_02.yaml
  clusters/hive/pools/openstack-k8s-operators/openstack-k8s-operators-4-10-vexxhost-sno_clusterpool_03.yaml
Labels: lgtm, approved

#32794 Change connectors addon tests runtime from OSD to ROSA
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: lgtm, approved

#32612 update ocp to 4.12 [odf-console CI]
  ci-operator/config/red-hat-storage/odf-console/red-hat-storage-odf-console-master.yaml
Labels: lgtm, approved

#32810 Adds bare folder in the step-registry for real-baremetal qe step-registry components
  ci-operator/step-registry/baremetal/OWNERS
Labels: lgtm, approved

#32802 Set the Prow jobs for stolostron/governance-policy-framework-addon
  ci-operator/config/stolostron/governance-policy-framework-addon/OWNERS
  ci-operator/config/stolostron/governance-policy-framework-addon/stolostron-governance-policy-framework-addon-main.yaml
  ci-operator/config/stolostron/governance-policy-framework-addon/stolostron-governance-policy-framework-addon-release-2.7.yaml
  ci-operator/jobs/stolostron/governance-policy-framework-addon/OWNERS
  ci-operator/jobs/stolostron/governance-policy-framework-addon/stolostron-governance-policy-framework-addon-main-postsubmits.yaml
  ci-operator/jobs/stolostron/governance-policy-framework-addon/stolostron-governance-policy-framework-addon-main-presubmits.yaml
  ci-operator/jobs/stolostron/governance-policy-framework-addon/stolostron-governance-policy-framework-addon-release-2.7-postsubmits.yaml
  ci-operator/jobs/stolostron/governance-policy-framework-addon/stolostron-governance-policy-framework-addon-release-2.7-presubmits.yaml
Labels: lgtm, approved

#32729 add upgrade rollback to origin. always_run:false
  ci-operator/config/openshift/origin/openshift-origin-master__4.12-upgrade-from-stable-4.11.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
Labels: lgtm, approved

#32807 Prow: generate token file in Kubeconfigs
  ci-operator/jobs/infra-periodics.yaml
  core-services/ci-secret-bootstrap/_config.yaml
  core-services/ci-secret-generator/_config.yaml
Labels: lgtm, approved

#32817 [vsphere] shorten datastore names and change default datastore
  ci-operator/step-registry/ipi/conf/vsphere/zones/ipi-conf-vsphere-zones-commands.sh
Labels: lgtm, approved

#32820 openshift/os: Use cosa 4.10
  ci-operator/config/openshift/os/openshift-os-release-4.10.yaml
Labels: lgtm, approved

#32041 [kubevirt] update kubevirt tekton tasks to ocp 4.12
  ci-operator/config/kubevirt/kubevirt-tekton-tasks/kubevirt-kubevirt-tekton-tasks-main.yaml
Labels: lgtm, approved

#32217 OCPBUGS-1979: update etcd build version to 1.16
  ci-operator/config/openshift/etcd/openshift-etcd-openshift-4.10.yaml
  ci-operator/config/openshift/etcd/openshift-etcd-openshift-4.11.yaml
  ci-operator/config/openshift/etcd/openshift-etcd-openshift-4.12.yaml
  ci-operator/config/openshift/etcd/openshift-etcd-openshift-4.13.yaml
  ci-operator/config/openshift/etcd/openshift-etcd-openshift-4.8.yaml
  ci-operator/config/openshift/etcd/openshift-etcd-openshift-4.9.yaml
Labels: lgtm, approved, tide/merge-method-squash, bugzilla/valid-bug, jira/valid-bug

#32824 Update TEST_SKIPS after tests renaming for ccm related suites
  ci-operator/step-registry/openshift/e2e/aws/ccm/openshift-e2e-aws-ccm-workflow.yaml
  ci-operator/step-registry/openshift/e2e/azure/ccm/install/openshift-e2e-azure-ccm-install-workflow.yaml
  ci-operator/step-registry/openshift/e2e/azure/ccm/openshift-e2e-azure-ccm-workflow.yaml
  ci-operator/step-registry/openshift/e2e/gcp/ccm/install/openshift-e2e-gcp-ccm-install-workflow.yaml
  ci-operator/step-registry/openshift/e2e/gcp/ccm/openshift-e2e-gcp-ccm-workflow.yaml
  ci-operator/step-registry/openshift/e2e/gcp/ccm/ovn/openshift-e2e-gcp-ccm-ovn-workflow.yaml
  ci-operator/step-registry/openshift/e2e/vsphere/ccm/install/openshift-e2e-vsphere-ccm-install-workflow.yaml
  ci-operator/step-registry/openshift/e2e/vsphere/ccm/openshift-e2e-vsphere-ccm-workflow.yaml
Labels: lgtm, approved

#32822 set PAS labels for reboot test
  ci-operator/step-registry/openshift/microshift/e2e/reboot-tests/openshift-microshift-e2e-reboot-tests-commands.sh
Labels: lgtm, approved

#32772 rename route-controller-manager image to be consistent with ART
  ci-operator/config/openshift/route-controller-manager/openshift-route-controller-manager-main.yaml
  ci-operator/config/openshift/route-controller-manager/openshift-route-controller-manager-release-4.12.yaml
  ci-operator/config/openshift/route-controller-manager/openshift-route-controller-manager-release-4.13.yaml
  core-services/image-mirroring/openshift/mapping_origin_4_12
Labels: lgtm, approved

#32809 [openshift/ci-tools] enable image builds for arm64 architecture
  ci-operator/config/openshift/ci-tools/.config.prowgen
  ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
Labels: lgtm, approved

#32734 Add ClusterRoleBinding/cluster-reader-extended
  clusters/build-clusters/common/admin_cluster-reader-extended_clusterrolebinding.yaml
  core-services/sync-rover-groups/_config.yaml
Labels: lgtm, approved

#32825 assisted installer events: skip if not changed
  ci-operator/config/openshift-assisted/assisted-events-scrape/openshift-assisted-assisted-events-scrape-master.yaml
  ci-operator/jobs/openshift-assisted/assisted-events-scrape/openshift-assisted-assisted-events-scrape-master-presubmits.yaml
Labels: lgtm, approved

#32607 Use quayio-pull-through-cache
  ci-operator/step-registry/ipi/conf/aws/ipi-conf-aws-commands.sh
Labels: lgtm, approved

#32813 Restore ClusterPool with Inventory data
  clusters/hive/pools/openstack-k8s-operators/openstack-k8s-operators-4-10-vexxhost-sno_clusterpool.yaml
  clusters/hive/pools/openstack-k8s-operators/openstack-k8s-operators-4-10-vexxhost-sno_clusterpool_02.yaml
  clusters/hive/pools/openstack-k8s-operators/openstack-k8s-operators-4-10-vexxhost-sno_clusterpool_03.yaml
  clusters/hive/pools/openstack-k8s-operators/openstack-k8s-operators-cdc-vexx-01.yaml
  clusters/hive/pools/openstack-k8s-operators/openstack-k8s-operators-cdc-vexx-02.yaml
  clusters/hive/pools/openstack-k8s-operators/openstack-k8s-operators-cdc-vexx-03.yaml
Labels: lgtm, approved

#32827 [openshift-loki] Add config for branch upstream-v2.7.0-pre-ec0bf70
  ci-operator/config/openshift/loki/openshift-loki-upstream-v2.7.0-pre-ec0bf70.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-upstream-v2.7.0-pre-ec0bf70-postsubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-upstream-v2.7.0-pre-ec0bf70-presubmits.yaml
Labels: lgtm, approved

#32830 [openshift-loki] Move image mirroring from v2.6.1 to v2.7.0-pre
  core-services/image-mirroring/openshift-logging/mapping_logging_loki_quay
Labels: lgtm, approved

#32832 Revert "Add quay.io pull through cache"
  ci-operator/step-registry/ipi/conf/aws/ipi-conf-aws-commands.sh
Labels: approved

#31564 Update jenkins for 4.13 branch
  ci-operator/config/openshift/jenkins/openshift-jenkins-master.yaml
  ci-operator/config/openshift/jenkins/openshift-jenkins-release-4.12.yaml
  ci-operator/jobs/openshift/jenkins/openshift-jenkins-master-postsubmits.yaml
  ci-operator/jobs/openshift/jenkins/openshift-jenkins-master-presubmits.yaml
  core-services/image-mirroring/openshift/mapping_origin_4_12
Labels: lgtm, approved, lifecycle/stale

#32829 Extend timeout for waiting CCCMO operands
  ci-operator/step-registry/ccm/conf/apply-feature-gate/ccm-conf-apply-feature-gate-commands.sh
Labels: lgtm, approved

#32828 kcp-dev/client-go: bootstrap the repo
  ci-operator/config/kcp-dev/client-go/OWNERS
  ci-operator/config/kcp-dev/client-go/kcp-dev-client-go-main.yaml
  ci-operator/jobs/kcp-dev/client-go/OWNERS
  ci-operator/jobs/kcp-dev/client-go/kcp-dev-client-go-main-presubmits.yaml
  core-services/prow/02_config/kcp-dev/client-go/_pluginconfig.yaml
  core-services/prow/02_config/kcp-dev/client-go/_prowconfig.yaml
Labels: lgtm, approved

#32843 kcp-dev/client-go: fix a dependent image
  ci-operator/config/kcp-dev/client-go/kcp-dev-client-go-main.yaml
Labels: lgtm, approved

#32833 Include token file in secret test-credentials/ci-operator
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved

#32819 stackrox: update build_root to stackrox-test-0.3.50
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-ci-perf-hacks.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__stackrox_branding.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies__stackrox_branding.yaml
Labels: lgtm, approved

#32835 MicroShift: bump everything to 4.12 & Go1.18
  ci-operator/config/openshift/microshift/openshift-microshift-main.yaml
  ci-operator/config/openshift/microshift/openshift-microshift-main__periodic-ocp-4.12.yaml
  ci-operator/config/openshift/microshift/openshift-microshift-main__periodics.yaml
  ci-operator/jobs/openshift/microshift/openshift-microshift-main-periodics.yaml
  ci-operator/jobs/openshift/microshift/openshift-microshift-main-presubmits.yaml
Labels: lgtm, approved

#32844 ci-search: add the TRT project on Jira Search
  clusters/build-clusters/01_cluster/ci-search/deploy.yaml
Labels: lgtm, approved

#31653 feat(hypershift): IBM Cloud E2E CI enablement
  ci-operator/config/openshift/hypershift/openshift-hypershift-main.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-main-presubmits.yaml
  ci-operator/step-registry/hypershift/ibmcloud/OWNERS
  ci-operator/step-registry/hypershift/ibmcloud/cluster-claim/OWNERS
  ci-operator/step-registry/hypershift/ibmcloud/cluster-claim/hypershift-ibmcloud-cluster-claim-chain.metadata.json
  ci-operator/step-registry/hypershift/ibmcloud/cluster-claim/hypershift-ibmcloud-cluster-claim-chain.yaml
  ci-operator/step-registry/hypershift/ibmcloud/create/OWNERS
  ci-operator/step-registry/hypershift/ibmcloud/create/hypershift-ibmcloud-create-chain.metadata.json
  ci-operator/step-registry/hypershift/ibmcloud/create/hypershift-ibmcloud-create-chain.yaml
  ci-operator/step-registry/hypershift/ibmcloud/destroy/OWNERS
  ci-operator/step-registry/hypershift/ibmcloud/destroy/hypershift-ibmcloud-destroy-chain.metadata.json
  ci-operator/step-registry/hypershift/ibmcloud/destroy/hypershift-ibmcloud-destroy-chain.yaml
  ci-operator/step-registry/hypershift/ibmcloud/e2e/OWNERS
  ci-operator/step-registry/hypershift/ibmcloud/e2e/hypershift-ibmcloud-e2e-workflow.metadata.json
  ci-operator/step-registry/hypershift/ibmcloud/e2e/hypershift-ibmcloud-e2e-workflow.yaml
  ci-operator/step-registry/hypershift/ibmcloud/install/OWNERS
  ci-operator/step-registry/hypershift/ibmcloud/install/hypershift-ibmcloud-install-chain.metadata.json
  ci-operator/step-registry/hypershift/ibmcloud/install/hypershift-ibmcloud-install-chain.yaml
Labels: lgtm, approved

#32836 cri-o: Update to 4.12, override rhel-coreos-8
  ci-operator/config/cri-o/cri-o/cri-o-cri-o-main.yaml
Labels: lgtm, approved

#32842 removing user dofinn
  ci-operator/jobs/openshift-priv/aws-account-operator/OWNERS
  ci-operator/jobs/openshift-priv/configure-alertmanager-operator/OWNERS
  ci-operator/jobs/openshift-priv/dedicated-admin-operator/OWNERS
  ci-operator/jobs/openshift-priv/pagerduty-operator/OWNERS
Labels: lgtm, approved

#32764 :gift: Serverless UI test for PRs
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main__4.11.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main__4.8.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main-periodics.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main-postsubmits.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main-presubmits.yaml
Labels: lgtm, approved

#32804 Add e2e jobs for cluster-api-provider-vsphere
  ci-operator/config/openshift/cluster-api-provider-vsphere/openshift-cluster-api-provider-vsphere-master.yaml
  ci-operator/jobs/openshift/cluster-api-provider-vsphere/openshift-cluster-api-provider-vsphere-master-presubmits.yaml
Labels: lgtm, approved

#32854 [openshift-loki] Switch loki branch to upstream-v2.7.0-pre
  ci-operator/config/openshift/loki/openshift-loki-upstream-v2.7.0-pre.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-upstream-v2.7.0-pre-postsubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-upstream-v2.7.0-pre-presubmits.yaml
Labels: lgtm, approved

#32859 [kubevirt-tekton-tasks] revert usage of ocp 4.12 due to tekton not able to run on 4.12 cluster
  ci-operator/config/kubevirt/kubevirt-tekton-tasks/kubevirt-kubevirt-tekton-tasks-main.yaml
  ci-operator/config/kubevirt/tekton-tasks-operator/kubevirt-tekton-tasks-operator-main.yaml
Labels: lgtm, approved

#32863 Disable stackrox/collector root build cache
  ci-operator/config/stackrox/collector/stackrox-collector-master.yaml
Labels: lgtm, approved

#32815 Attempt to use our image to run 2.3 istio jobs
  ci-operator/config/maistra/istio/maistra-istio-maistra-2.3.yaml
Labels: lgtm, approved

#32866 Bump Alibaba CCM CI memory limit to 8 Gi
  ci-operator/config/openshift/cloud-provider-alibaba-cloud/openshift-cloud-provider-alibaba-cloud-master.yaml
Labels: lgtm, approved

#32642 Prow: use token file in Kubeconfigs
  core-services/ci-secret-bootstrap/_config.yaml
  core-services/ci-secret-generator/_config.yaml
Labels: lgtm, approved

#32852 Enabling test-infra's kubeconfig loading
  clusters/app.ci/ci-chat-bot/ci-chat-bot.yaml
Labels: lgtm, approved

#32862 Update rebase script location
  ci-operator/step-registry/openshift/microshift/rebase/openshift-microshift-rebase-commands.sh
Labels: lgtm, approved

#32826 rhods: Build and mirror jupyter-minimal-ubi8-python-3-8
  ci-operator/config/red-hat-data-services/notebooks/OWNERS
  ci-operator/config/red-hat-data-services/notebooks/red-hat-data-services-notebooks-main.yaml
  ci-operator/jobs/red-hat-data-services/notebooks/OWNERS
  ci-operator/jobs/red-hat-data-services/notebooks/red-hat-data-services-notebooks-main-postsubmits.yaml
  ci-operator/jobs/red-hat-data-services/notebooks/red-hat-data-services-notebooks-main-presubmits.yaml
  ci-operator/step-registry/red-hat-data-services/OWNERS
  ci-operator/step-registry/red-hat-data-services/ci/OWNERS
  ci-operator/step-registry/red-hat-data-services/ci/image-mirror/OWNERS
  ci-operator/step-registry/red-hat-data-services/ci/image-mirror/red-hat-data-services-ci-image-mirror-workflow.metadata.json
  ci-operator/step-registry/red-hat-data-services/ci/image-mirror/red-hat-data-services-ci-image-mirror-workflow.yaml
  core-services/prow/02_config/red-hat-data-services/notebooks/OWNERS
  core-services/prow/02_config/red-hat-data-services/notebooks/_pluginconfig.yaml
  core-services/prow/02_config/red-hat-data-services/notebooks/_prowconfig.yaml
Labels: lgtm, approved

#32790 Add hypershift e2e to MCO
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-master.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-master-presubmits.yaml
  ci-operator/step-registry/hypershift/aws/e2e/external/OWNERS
  ci-operator/step-registry/hypershift/aws/e2e/external/hypershift-aws-e2e-external-workflow.metadata.json
  ci-operator/step-registry/hypershift/aws/e2e/external/hypershift-aws-e2e-external-workflow.yaml
  ci-operator/step-registry/hypershift/aws/run-e2e/external/OWNERS
  ci-operator/step-registry/hypershift/aws/run-e2e/external/hypershift-aws-run-e2e-external-chain.metadata.json
  ci-operator/step-registry/hypershift/aws/run-e2e/external/hypershift-aws-run-e2e-external-chain.yaml
  ci-operator/step-registry/hypershift/install/external/OWNERS
  ci-operator/step-registry/hypershift/install/external/hypershift-install-external-chain.metadata.json
  ci-operator/step-registry/hypershift/install/external/hypershift-install-external-chain.yaml
Labels: lgtm, approved

#32683 Enables to inject HC release image for hypershift new cluster chain
  ci-operator/jobs/openshift/release/openshift-release-infra-periodics.yaml
  ci-operator/step-registry/hypershift/aws/setup-nested-management-cluster/hypershift-aws-setup-nested-management-cluster-chain.yaml
Labels: lgtm, approved

#32870 kcp: add release-0.9 jobs
  ci-operator/config/kcp-dev/kcp/kcp-dev-kcp-release-0.9.yaml
  ci-operator/jobs/kcp-dev/kcp/kcp-dev-kcp-release-0.9-periodics.yaml
  ci-operator/jobs/kcp-dev/kcp/kcp-dev-kcp-release-0.9-postsubmits.yaml
  ci-operator/jobs/kcp-dev/kcp/kcp-dev-kcp-release-0.9-presubmits.yaml
  core-services/prow/02_config/kcp-dev/kcp/_prowconfig.yaml
Labels: lgtm, approved

#32871 rhods: Mount /secrets/red-hat-data-services-push-secret
  ci-operator/step-registry/red-hat-data-services/ci/image-mirror/red-hat-data-services-ci-image-mirror-workflow.yaml
Labels: lgtm, approved

#32857 OCPBUGS-1979: etcd 4.8 build root to 1.16
  ci-operator/config/openshift/etcd/openshift-etcd-openshift-4.8.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#32780 app.ci: Add CentOS Stream CoreOS 9 ImageStream
  OWNERS_ALIASES
  clusters/app.ci/supplemental-ci-images/okd/OWNERS
  clusters/app.ci/supplemental-ci-images/okd/scos.yaml
Labels: lgtm, approved

#32874 app.ci: Add `origin/scos-4.12` IS with `centos-stream-coreos-9` IST
  clusters/app.ci/supplemental-ci-images/okd/scos.yaml
Labels: lgtm, approved

#32876 ci: Delete Prow periodic
  ci-operator/config/openshift/os/openshift-os-master__periodic.yaml
  ci-operator/jobs/openshift/os/openshift-os-master-periodics.yaml
  ci-operator/jobs/openshift/os/openshift-os-master-postsubmits.yaml
  ci-operator/jobs/openshift/os/openshift-os-master-presubmits.yaml
Labels: lgtm, approved

#32875 SDCICD-813 Wrong AWS secrets
  ci-operator/config/openshift/osde2e/openshift-osde2e-main.yaml
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: lgtm, approved

#32865 add openshift/service-idler prow config
  core-services/prow/02_config/openshift/service-idler/OWNERS
  core-services/prow/02_config/openshift/service-idler/_pluginconfig.yaml
  core-services/prow/02_config/openshift/service-idler/_prowconfig.yaml
Labels: lgtm, approved

#32851 Add quay.io pull through cache
  ci-operator/step-registry/ipi/conf/aws/ipi-conf-aws-commands.sh
Labels: lgtm, approved

#32892 Revert "[dptp-controller-manager] enable distributing images to arm01 cluster"
  clusters/app.ci/assets/dptp-controller-manager.yaml
Labels: lgtm, approved

#32895 MGMT-11847: Assisted-Installer: Change assisted periodic jobs interval
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.5.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.6.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.5.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.6.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-periodics.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.5-periodics.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.6-periodics.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-periodics.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.5-periodics.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.6-periodics.yaml
Labels: lgtm, approved

#32762 Include optional presubmits Kuryr jobs to origin
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.12.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.13.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.13-presubmits.yaml
Labels: lgtm, approved

#32417 ViaQ/vector: added a new branch v0.23-rh
  ci-operator/config/ViaQ/vector/ViaQ-vector-v0.23-rh.yaml
  ci-operator/jobs/ViaQ/vector/ViaQ-vector-v0.23-rh-postsubmits.yaml
  ci-operator/jobs/ViaQ/vector/ViaQ-vector-v0.23-rh-presubmits.yaml
Labels: lgtm, approved

#32891 Use build_root from repository for Prometheus and Alertmanager
  ci-operator/config/openshift/prometheus-alertmanager/openshift-prometheus-alertmanager-master.yaml
  ci-operator/config/openshift/prometheus/openshift-prometheus-master.yaml
  ci-operator/jobs/openshift/prometheus-alertmanager/openshift-prometheus-alertmanager-master-postsubmits.yaml
  ci-operator/jobs/openshift/prometheus-alertmanager/openshift-prometheus-alertmanager-master-presubmits.yaml
  ci-operator/jobs/openshift/prometheus/openshift-prometheus-master-postsubmits.yaml
  ci-operator/jobs/openshift/prometheus/openshift-prometheus-master-presubmits.yaml
Labels: lgtm, approved

#32864 OKD/SCOS release-controller configuration
  ci-operator/config/openshift/cluster-samples-operator/openshift-cluster-samples-operator-master__okd-scos.yaml
  ci-operator/config/openshift/cluster-samples-operator/openshift-cluster-samples-operator-release-4.12__okd-scos.yaml
  ci-operator/config/openshift/cluster-samples-operator/openshift-cluster-samples-operator-release-4.13__okd-scos.yaml
  ci-operator/config/openshift/cluster-update-keys/openshift-cluster-update-keys-master__okd-scos.yaml
  ci-operator/config/openshift/cluster-update-keys/openshift-cluster-update-keys-release-4.12__okd-scos.yaml
  ci-operator/config/openshift/cluster-update-keys/openshift-cluster-update-keys-release-4.13__okd-scos.yaml
  ci-operator/config/openshift/installer/openshift-installer-master__okd-scos.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.12__okd-scos.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.13__okd-scos.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-master__okd-scos.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.12__okd-scos.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.13__okd-scos.yaml
  ci-operator/config/operator-framework/operator-marketplace/operator-framework-operator-marketplace-master__okd-scos.yaml
  ci-operator/config/operator-framework/operator-marketplace/operator-framework-operator-marketplace-release-4.12__okd-scos.yaml
  ci-operator/config/operator-framework/operator-marketplace/operator-framework-operator-marketplace-release-4.13__okd-scos.yaml
  ci-operator/jobs/openshift/cluster-samples-operator/openshift-cluster-samples-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-samples-operator/openshift-cluster-samples-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-samples-operator/openshift-cluster-samples-operator-release-4.12-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-samples-operator/openshift-cluster-samples-operator-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift/cluster-samples-operator/openshift-cluster-samples-operator-release-4.13-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-samples-operator/openshift-cluster-samples-operator-release-4.13-presubmits.yaml
  ci-operator/jobs/openshift/cluster-update-keys/openshift-cluster-update-keys-master-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-update-keys/openshift-cluster-update-keys-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-update-keys/openshift-cluster-update-keys-release-4.12-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-update-keys/openshift-cluster-update-keys-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift/cluster-update-keys/openshift-cluster-update-keys-release-4.13-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-update-keys/openshift-cluster-update-keys-release-4.13-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-periodics.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-postsubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.12-periodics.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.12-postsubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.13-postsubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.13-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.12-postsubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.13-postsubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.13-presubmits.yaml
  ci-operator/jobs/operator-framework/operator-marketplace/operator-framework-operator-marketplace-master-postsubmits.yaml
  ci-operator/jobs/operator-framework/operator-marketplace/operator-framework-operator-marketplace-master-presubmits.yaml
  ci-operator/jobs/operator-framework/operator-marketplace/operator-framework-operator-marketplace-release-4.12-postsubmits.yaml
  ci-operator/jobs/operator-framework/operator-marketplace/operator-framework-operator-marketplace-release-4.12-presubmits.yaml
  ci-operator/jobs/operator-framework/operator-marketplace/operator-framework-operator-marketplace-release-4.13-postsubmits.yaml
  ci-operator/jobs/operator-framework/operator-marketplace/operator-framework-operator-marketplace-release-4.13-presubmits.yaml
  core-services/release-controller/_releases/release-ocp-4.12-ci.json
  core-services/release-controller/_releases/release-okd-scos-4.12.json
  core-services/release-controller/_releases/release-okd-scos-4.y-stable.json
  hack/annotate.sh
Labels: lgtm, approved

#32902 Prevent promoted-image-governor from pruning new coreos images
  ci-operator/jobs/infra-periodics.yaml
Labels: lgtm, approved

#32879 ci-secret-generator: generate item/ci-operator on Vault
  core-services/ci-secret-bootstrap/_config.yaml
  core-services/ci-secret-generator/_config.yaml
Labels: lgtm, approved

#32898 openshift/os: Also delete 4.12 and 4.13 branched periodics
  ci-operator/config/openshift/os/openshift-os-release-4.12__periodic.yaml
  ci-operator/config/openshift/os/openshift-os-release-4.13__periodic.yaml
  ci-operator/jobs/openshift/os/openshift-os-release-4.12-periodics.yaml
  ci-operator/jobs/openshift/os/openshift-os-release-4.12-postsubmits.yaml
  ci-operator/jobs/openshift/os/openshift-os-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift/os/openshift-os-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/os/openshift-os-release-4.13-postsubmits.yaml
  ci-operator/jobs/openshift/os/openshift-os-release-4.13-presubmits.yaml
Labels: lgtm, approved

#32909 ci-chat-bot: add boskos credentials
  clusters/app.ci/ci-chat-bot/ci-chat-bot.yaml
Labels: lgtm, approved

#32573 adding more valid labels for openshift-docs
  core-services/prow/02_config/_labels.yaml
  core-services/prow/02_config/openshift/openshift-docs/_pluginconfig.yaml
Labels: lgtm, approved

#32881 Use sa.hive.hive.token.txt
  core-services/ci-secret-bootstrap/_config.yaml
  core-services/ci-secret-generator/_config.yaml
Labels: lgtm, approved

#32914 infra-periodics: remove aws-2 chat bot prowjob
  ci-operator/jobs/openshift/release/openshift-release-infra-periodics.yaml
Labels: lgtm, approved

#32911 installer: sync okd job settings to okd-scos
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.13-presubmits.yaml
Labels: lgtm, approved

#32890 Add info regarding machine type for RHOC tests
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: lgtm, approved

#32840 Update capi ibm ci jobs
  ci-operator/config/openshift/cluster-api-provider-ibmcloud/openshift-cluster-api-provider-ibmcloud-main.yaml
  ci-operator/jobs/openshift/cluster-api-provider-ibmcloud/openshift-cluster-api-provider-ibmcloud-main-presubmits.yaml
Labels: lgtm, approved

#32853 [rhd-sbo] Add jobs for release-v1.3.x branch
  ci-operator/config/redhat-developer/service-binding-operator/redhat-developer-service-binding-operator-release-v1.3.x.yaml
  ci-operator/config/redhat-developer/service-binding-operator/redhat-developer-service-binding-operator-release-v1.3.x__4.10.yaml
  ci-operator/config/redhat-developer/service-binding-operator/redhat-developer-service-binding-operator-release-v1.3.x__4.11.yaml
  ci-operator/config/redhat-developer/service-binding-operator/redhat-developer-service-binding-operator-release-v1.3.x__4.12.yaml
  ci-operator/config/redhat-developer/service-binding-operator/redhat-developer-service-binding-operator-release-v1.3.x__4.9.yaml
  ci-operator/jobs/redhat-developer/service-binding-operator/redhat-developer-service-binding-operator-release-v1.3.x-presubmits.yaml
Labels: lgtm, approved

#32922 Fix scos images by pulling from origin/4.12
  ci-operator/config/openshift/cluster-samples-operator/openshift-cluster-samples-operator-master__okd-scos.yaml
  ci-operator/config/openshift/cluster-samples-operator/openshift-cluster-samples-operator-release-4.12__okd-scos.yaml
  ci-operator/config/openshift/cluster-samples-operator/openshift-cluster-samples-operator-release-4.13__okd-scos.yaml
  ci-operator/config/openshift/cluster-update-keys/openshift-cluster-update-keys-master__okd-scos.yaml
  ci-operator/config/openshift/cluster-update-keys/openshift-cluster-update-keys-release-4.12__okd-scos.yaml
  ci-operator/config/openshift/cluster-update-keys/openshift-cluster-update-keys-release-4.13__okd-scos.yaml
  ci-operator/config/openshift/installer/openshift-installer-master__okd-scos.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.12__okd-scos.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.13__okd-scos.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-master__okd-scos.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.12__okd-scos.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.13__okd-scos.yaml
  ci-operator/config/operator-framework/operator-marketplace/operator-framework-operator-marketplace-master__okd-scos.yaml
  ci-operator/config/operator-framework/operator-marketplace/operator-framework-operator-marketplace-release-4.12__okd-scos.yaml
  ci-operator/config/operator-framework/operator-marketplace/operator-framework-operator-marketplace-release-4.13__okd-scos.yaml
Labels: lgtm, approved

#32899 USHIFT-443: Fix binary paths in microshift test workflow
  ci-operator/step-registry/openshift/microshift/e2e/test/openshift-microshift-e2e-test-commands.sh
Labels: lgtm, approved

#32883 Update secret/app.ci-ci-operator-credentials
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved

#32921 Postsubmit for ACM stolostron/image-builder on Arm build cluster
  ci-operator/config/stolostron/image-builder/.config.prowgen
  ci-operator/jobs/stolostron/image-builder/stolostron-image-builder-master-postsubmits.yaml
Labels: lgtm, approved

#32923 Add Prow config for stolostron/kubernetes-dependency-watches
  core-services/prow/02_config/stolostron/kubernetes-dependency-watches/OWNERS
  core-services/prow/02_config/stolostron/kubernetes-dependency-watches/_pluginconfig.yaml
  core-services/prow/02_config/stolostron/kubernetes-dependency-watches/_prowconfig.yaml
Labels: lgtm, approved

#32885 machine-os-content jobs: no renaming for kubeconfig of app.ci
  ci-operator/jobs/openshift/release/openshift-release-release-4.1-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.10-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.11-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.12-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.6-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.8-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.9-periodics.yaml
Labels: lgtm, approved

#32927 Remove yamllint check for cluster-api-provider-ibmcloud
  ci-operator/jobs/openshift/cluster-api-provider-ibmcloud/openshift-cluster-api-provider-ibmcloud-main-presubmits.yaml
Labels: lgtm, approved

#32894 Adding `no-capabilities` cluster bot variant
  ci-operator/jobs/openshift/release/openshift-release-infra-periodics.yaml
Labels: lgtm, approved

#32933 Disable 4.10 quayio pull-through-cache
  ci-operator/step-registry/ipi/conf/aws/ipi-conf-aws-commands.sh
Labels: lgtm, approved

#32924 openstack: Remove NFV gates
  ci-operator/config/openshift/machine-api-provider-openstack/openshift-machine-api-provider-openstack-master.yaml
  ci-operator/config/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main__periodic-4.12.yaml
  ci-operator/jobs/openshift/machine-api-provider-openstack/openshift-machine-api-provider-openstack-master-presubmits.yaml
  ci-operator/jobs/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main-periodics.yaml
Labels: lgtm, approved

#32929 Rewrite ODS tests and entrypoints
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-main__ods.yaml
  ci-operator/jobs/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-main-presubmits.yaml
Labels: lgtm, approved

#32936 configure featureSet: TechPreviewNoUpgrade for mutli-zone
  ci-operator/step-registry/ipi/conf/vsphere/zones/ipi-conf-vsphere-zones-commands.sh
Labels: lgtm, approved

#32928 NO-ISSUE: Fix NVME setup in dev-scripts
  ci-operator/step-registry/baremetalds/devscripts/setup/baremetalds-devscripts-setup-commands.sh
Labels: lgtm, approved

#32937 ods: Finish renaming
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-main__ods.yaml
Labels: lgtm, approved

#32658 Include job for IPv6 testing as additional network
  ci-operator/config/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main__periodic-4.12.yaml
  ci-operator/jobs/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main-periodics.yaml
  ci-operator/step-registry/openshift/e2e/openstack/ipv6/OWNERS
  ci-operator/step-registry/openshift/e2e/openstack/ipv6/openshift-e2e-openstack-ipv6-workflow.metadata.json
  ci-operator/step-registry/openshift/e2e/openstack/ipv6/openshift-e2e-openstack-ipv6-workflow.yaml
  ci-operator/step-registry/openstack/test/ipv6/OWNERS
  ci-operator/step-registry/openstack/test/ipv6/openstack-test-ipv6-commands.sh
  ci-operator/step-registry/openstack/test/ipv6/openstack-test-ipv6-ref.metadata.json
  ci-operator/step-registry/openstack/test/ipv6/openstack-test-ipv6-ref.yaml
Labels: lgtm, approved

#32745 update filter for e2e-aws-ipi-disconnected-private-sdn-workers-rhcos-rhel8-p2
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
Labels: lgtm, approved

#32808 MGMT-11926: assisted-baremetal-conf: set kubeconfig when fetching a list of conformance tests
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/step-registry/assisted/baremetal/conf/assisted-baremetal-conf-commands.sh
  ci-operator/step-registry/assisted/common/verify/assisted-common-verify-ref.yaml
  ci-operator/step-registry/assisted/vsphere/assisted-vsphere-workflow.yaml
Labels: lgtm, approved

#32946 [vsphere] add workflow for multi zone cluster
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.12.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/zones/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/zones/techpreview/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/zones/techpreview/cucushift-installer-rehearse-vsphere-ipi-zones-techpreview-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/zones/techpreview/cucushift-installer-rehearse-vsphere-ipi-zones-techpreview-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/zones/techpreview/deprovision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/zones/techpreview/deprovision/cucushift-installer-rehearse-vsphere-ipi-zones-techpreview-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/zones/techpreview/deprovision/cucushift-installer-rehearse-vsphere-ipi-zones-techpreview-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/zones/techpreview/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/zones/techpreview/provision/cucushift-installer-rehearse-vsphere-ipi-zones-techpreview-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/zones/techpreview/provision/cucushift-installer-rehearse-vsphere-ipi-zones-techpreview-provision-chain.yaml
Labels: lgtm, approved

#32948 [CIGolang]support to remove lib
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.6.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.7.yaml
Labels: lgtm, approved

#32951 publish global hub operator
  ci-operator/config/stolostron/multicluster-global-hub/stolostron-multicluster-global-hub-release-2.7.yaml
  ci-operator/jobs/stolostron/multicluster-global-hub/stolostron-multicluster-global-hub-release-2.7-postsubmits.yaml
Labels: lgtm, approved

#32942 OCPQE-11842: Add e2e for gcp-ipi-disconnected-private
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
Labels: lgtm, approved

#32943 OCPQE-11842: Add e2e for gcp-upi-disconnected
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
Labels: lgtm, approved

#32954 OCPQE-12384 Export build_version for E2E Destructive and Long Duration tests
  ci-operator/step-registry/openshift/e2e/test/qe/destructive/openshift-e2e-test-qe-destructive-chain.yaml
  ci-operator/step-registry/openshift/e2e/test/qe/long-duration/openshift-e2e-test-qe-long-duration-chain.yaml
Labels: lgtm, approved

#32956 OCPQE-11842: Add e2e for vsphere-ipi-zones-techpreview
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
Labels: lgtm, approved

#32955 OCPQE-11842: Add e2e for gcp-upi-private-xpn
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
Labels: lgtm, approved

#32949 [AWS] Custom mirror-registry pull secret was overridden in ipi-conf-aws step
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/disconnected/private/provision/cucushift-installer-rehearse-aws-ipi-disconnected-private-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/disconnected/private/sdn/provision/cucushift-installer-rehearse-aws-ipi-disconnected-private-sdn-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/disconnected/private/sno/provision/cucushift-installer-rehearse-aws-ipi-disconnected-private-sno-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/disconnected/private/techpreview/provision/cucushift-installer-rehearse-aws-ipi-disconnected-private-techpreview-provision-chain.yaml
  ci-operator/step-registry/ipi/install/install/aws/ipi-install-install-aws-commands.sh
Labels: lgtm, approved

#32960 Fix: add cache home for cluster-proxy.
  ci-operator/config/stolostron/cluster-proxy/stolostron-cluster-proxy-backplane-2.2.yaml
  ci-operator/config/stolostron/cluster-proxy/stolostron-cluster-proxy-main.yaml
Labels: lgtm, approved

#32950 qe e2e test for azure-ipi-ingress-custom-ingresscontroller
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
Labels: lgtm, approved

#32957 OCPQE-11842: Add e2e for vsphere-upi-disconnected
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
Labels: lgtm, approved

#32959 To support CA setting when baselinecaps is none
  ci-operator/step-registry/set-sample-operator/disconnected/set-sample-operator-disconnected-commands.sh
Labels: lgtm, approved

#32397 Using ocp411 to test ckcp
  ci-operator/config/openshift-pipelines/pipeline-service/openshift-pipelines-pipeline-service-main.yaml
Labels: lgtm, approved

#32708 mtu workflows
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
Labels: lgtm, approved

#32791 Change upgrade jobs config to use arch prefix (amd64-only)
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-stable-4.11.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
Labels: lgtm, approved

#32966 [common-templates] revert usage of 4.12 ocp in common templates
  ci-operator/config/kubevirt/common-templates/kubevirt-common-templates-master.yaml
Labels: lgtm, approved

#32967 [kubevirt-tekton-tasks-operator] create new testing record for tto stable branch
  ci-operator/config/kubevirt/tekton-tasks-operator/kubevirt-tekton-tasks-operator-release-v0.4.yaml
  ci-operator/jobs/kubevirt/tekton-tasks-operator/kubevirt-tekton-tasks-operator-release-v0.4-presubmits.yaml
Labels: lgtm, approved

#32968 [kubevirt-tekton-tasks] create new testing record for stable branch for kubevirt tekton tasks
  ci-operator/config/kubevirt/kubevirt-tekton-tasks/kubevirt-kubevirt-tekton-tasks-release-v0.12.yaml
  ci-operator/jobs/kubevirt/kubevirt-tekton-tasks/kubevirt-kubevirt-tekton-tasks-release-v0.12-presubmits.yaml
Labels: lgtm, approved

#32930 Override TEST_SKIPS for 4.9 release azure ccm jobs
  ci-operator/config/openshift/cloud-provider-azure/openshift-cloud-provider-azure-release-4.9.yaml
Labels: lgtm, approved

#32935 Update upstream branch to 1.25
  ci-operator/config/openshift-eng/rebasebot/openshift-eng-rebasebot-main.yaml
Labels: lgtm, approved

#32634 [CNF-6319] Add workflow for Optional Capabilities in 4.12
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.12.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/disconnected/private/sno/baselinecaps/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/disconnected/private/sno/baselinecaps/none/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/disconnected/private/sno/baselinecaps/none/cucushift-installer-rehearse-aws-ipi-disconnected-private-sno-baselinecaps-none-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/disconnected/private/sno/baselinecaps/none/cucushift-installer-rehearse-aws-ipi-disconnected-private-sno-baselinecaps-none-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/disconnected/private/sno/baselinecaps/none/deprovision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/disconnected/private/sno/baselinecaps/none/deprovision/cucushift-installer-rehearse-aws-ipi-disconnected-private-sno-baselinecaps-none-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/disconnected/private/sno/baselinecaps/none/deprovision/cucushift-installer-rehearse-aws-ipi-disconnected-private-sno-baselinecaps-none-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/disconnected/private/sno/baselinecaps/none/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/disconnected/private/sno/baselinecaps/none/provision/cucushift-installer-rehearse-aws-ipi-disconnected-private-sno-baselinecaps-none-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/disconnected/private/sno/baselinecaps/none/provision/cucushift-installer-rehearse-aws-ipi-disconnected-private-sno-baselinecaps-none-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/baselinecaps/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/baselinecaps/v412/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/baselinecaps/v412/cucushift-installer-rehearse-azure-ipi-baselinecaps-v412-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/baselinecaps/v412/cucushift-installer-rehearse-azure-ipi-baselinecaps-v412-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/baselinecaps/v412/deprovision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/baselinecaps/v412/deprovision/cucushift-installer-rehearse-azure-ipi-baselinecaps-v412-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/baselinecaps/v412/deprovision/cucushift-installer-rehearse-azure-ipi-baselinecaps-v412-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/baselinecaps/v412/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/baselinecaps/v412/provision/cucushift-installer-rehearse-azure-ipi-baselinecaps-v412-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/baselinecaps/v412/provision/cucushift-installer-rehearse-azure-ipi-baselinecaps-v412-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/baselinecaps/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/baselinecaps/v411/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/baselinecaps/v411/additionalenabledcaps/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/baselinecaps/v411/additionalenabledcaps/cucushift-installer-rehearse-gcp-ipi-baselinecaps-v411-additionalenabledcaps-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/baselinecaps/v411/additionalenabledcaps/cucushift-installer-rehearse-gcp-ipi-baselinecaps-v411-additionalenabledcaps-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/baselinecaps/v411/additionalenabledcaps/deprovision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/baselinecaps/v411/additionalenabledcaps/deprovision/cucushift-installer-rehearse-gcp-ipi-baselinecaps-v411-additionalenabledcaps-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/baselinecaps/v411/additionalenabledcaps/deprovision/cucushift-installer-rehearse-gcp-ipi-baselinecaps-v411-additionalenabledcaps-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/baselinecaps/v411/additionalenabledcaps/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/baselinecaps/v411/additionalenabledcaps/provision/cucushift-installer-rehearse-gcp-ipi-baselinecaps-v411-additionalenabledcaps-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/baselinecaps/v411/additionalenabledcaps/provision/cucushift-installer-rehearse-gcp-ipi-baselinecaps-v411-additionalenabledcaps-provision-chain.yaml
Labels: lgtm, approved

#32647 hypershift-chain: update install
  ci-operator/step-registry/hypershift/aws/create/hypershift-aws-create-chain.yaml
  ci-operator/step-registry/hypershift/aws/destroy-nested-management-cluster/hypershift-aws-destroy-nested-management-cluster-chain.yaml
  ci-operator/step-registry/hypershift/aws/destroy/hypershift-aws-destroy-chain.yaml
  ci-operator/step-registry/hypershift/aws/setup-nested-management-cluster/hypershift-aws-setup-nested-management-cluster-chain.yaml
Labels: lgtm, approved, tide/merge-method-squash

#32965 Add new image for quay omr test
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__omr.yaml
  ci-operator/jobs/quay/quay-tests/quay-quay-tests-master-periodics.yaml
  ci-operator/jobs/quay/quay-tests/quay-quay-tests-master-postsubmits.yaml
  ci-operator/jobs/quay/quay-tests/quay-quay-tests-master-presubmits.yaml
Labels: lgtm, approved, tide/merge-method-squash

#32973 ODS: Continue the refactoring
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-main__ods.yaml
  ci-operator/jobs/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-main-presubmits.yaml
Labels: lgtm, approved

#32961 Prevent promoted-image-governor from pruning new SCOS imagestream
  ci-operator/jobs/infra-periodics.yaml
  clusters/app.ci/supplemental-ci-images/okd/scos.yaml
Labels: lgtm, approved

#32650 Makefile: add subdirectory parameters for `jobs`
  Makefile
  hack/generate-template-allowlist.sh
Labels: lgtm, approved, tide/merge-method-merge

#32983 Fixing incorrect workflow name
  ci-operator/jobs/openshift/release/openshift-release-infra-periodics.yaml
Labels: lgtm, approved

#32816 HCO: test on OCP 4.12
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-main.yaml
Labels: lgtm, approved

#32987 revert claiming cluster for logging e2e
  ci-operator/config/openshift/cluster-logging-operator/openshift-cluster-logging-operator-master.yaml
  ci-operator/jobs/openshift/cluster-logging-operator/openshift-cluster-logging-operator-master-presubmits.yaml
Labels: lgtm, approved

#32912 remove building of sidecar/analyzer imgs for jvm-build-service
  ci-operator/config/redhat-appstudio/jvm-build-service/redhat-appstudio-jvm-build-service-main.yaml
Labels: lgtm, approved

#32988 Disable broken aws-disruptive job for MAO, CPMSO, and CMA
  ci-operator/config/openshift/cluster-control-plane-machine-set-operator/openshift-cluster-control-plane-machine-set-operator-main.yaml
  ci-operator/config/openshift/cluster-machine-approver/openshift-cluster-machine-approver-master.yaml
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-master.yaml
  ci-operator/jobs/openshift/cluster-control-plane-machine-set-operator/openshift-cluster-control-plane-machine-set-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/cluster-machine-approver/openshift-cluster-machine-approver-master-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-master-presubmits.yaml
Labels: lgtm, approved

#32981 OpenStack: Switch default CNI to OVNKubernetes
  ci-operator/step-registry/openstack/conf/installconfig/openstack-conf-installconfig-ref.yaml
Labels: lgtm, approved

#32744 Adding workflow-config in chat-bot for various providers
  core-services/ci-chat-bot/workflows-config.yaml
Labels: lgtm, approved

#32984 Use repo as build root for MAPI Nutanix provider build image
  ci-operator/config/openshift/machine-api-provider-nutanix/openshift-machine-api-provider-nutanix-main.yaml
  ci-operator/jobs/openshift/machine-api-provider-nutanix/openshift-machine-api-provider-nutanix-main-postsubmits.yaml
  ci-operator/jobs/openshift/machine-api-provider-nutanix/openshift-machine-api-provider-nutanix-main-presubmits.yaml
Labels: lgtm, approved

#32991 OKD/SCOS: Temporarily shorten minCreationIntervalSeconds to 900
  core-services/release-controller/_releases/release-okd-scos-4.12.json
Labels: lgtm, approved

#32994 `tide`: use gh apps auth
  clusters/app.ci/prow/03_deployment/tide.yaml
Labels: approved

#32996 OKD/SCOS: Make all installer tests optional
  ci-operator/config/openshift/installer/openshift-installer-master__okd-scos.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.12__okd-scos.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.13__okd-scos.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-periodics.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.12-periodics.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.13-presubmits.yaml
Labels: lgtm, approved

#32995 ocm install: update branch protection
  core-services/prow/02_config/stolostron/backplane-operator/_prowconfig.yaml
  core-services/prow/02_config/stolostron/multiclusterhub-operator/_prowconfig.yaml
Labels: lgtm, approved

#33003 OCPQE-12419: Fix case selection on non-fips clusters
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-stable-4.11.yaml
Labels: lgtm, approved

#32985 set default value of BASTION_HOST_SUBNET as empty in its ref
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/disconnected/provision/cucushift-installer-rehearse-vsphere-ipi-disconnected-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/disconnected/techpreview/provision/cucushift-installer-rehearse-vsphere-ipi-disconnected-techpreview-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/proxy/provision/cucushift-installer-rehearse-vsphere-ipi-proxy-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/proxy/techpreview/provision/cucushift-installer-rehearse-vsphere-ipi-proxy-techpreview-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/disconnected/provision/cucushift-installer-rehearse-vsphere-upi-disconnected-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/disconnected/sdn/provision/cucushift-installer-rehearse-vsphere-upi-disconnected-sdn-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/proxy/provision/cucushift-installer-rehearse-vsphere-upi-proxy-provision-chain.yaml
  ci-operator/step-registry/vsphere/provision/bastionhost/vsphere-provision-bastionhost-commands.sh
  ci-operator/step-registry/vsphere/provision/bastionhost/vsphere-provision-bastionhost-ref.yaml
Labels: lgtm, approved

#32974 Add azure-ipi-ovn-etcd-encryption-workflow
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.12.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/ovn/etcd-encryption/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/ovn/etcd-encryption/cucushift-installer-rehearse-azure-ipi-ovn-etcd-encryption-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/ovn/etcd-encryption/cucushift-installer-rehearse-azure-ipi-ovn-etcd-encryption-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/ovn/etcd-encryption/deprovision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/ovn/etcd-encryption/deprovision/cucushift-installer-rehearse-azure-ipi-ovn-etcd-encryption-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/ovn/etcd-encryption/deprovision/cucushift-installer-rehearse-azure-ipi-ovn-etcd-encryption-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/ovn/etcd-encryption/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/ovn/etcd-encryption/provision/cucushift-installer-rehearse-azure-ipi-ovn-etcd-encryption-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/ovn/etcd-encryption/provision/cucushift-installer-rehearse-azure-ipi-ovn-etcd-encryption-provision-chain.yaml
Labels: lgtm, approved

#33004 Add arch info as variant to support upcoming arm64/multi
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__amd64-stable-4.10-upgrade-from-eus-4.8.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly-4.11-upgrade-from-stable-4.10.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11-periodics.yaml
Labels: lgtm, approved

#32964 OCPQE-11842: Add e2e for vsphere-upi-disconnected-secureboot
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
Labels: lgtm, approved

#32941 OCPQE-11842: Add e2e for aws-ipi-disconnected-private-workers-rhcos-rhel8
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
Labels: lgtm, approved

#32962 OCPQE-11842: Add e2e for gcp-upi-baselinecaps-v411
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
Labels: lgtm, approved

#33008 Add payload architecture
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__amd64-stable-4.10-upgrade-from-eus-4.8.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly-4.11-upgrade-from-stable-4.10.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-stable-4.11.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
Labels: lgtm, approved

#33010 [CIGolang]change timeout for hive case
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
Labels: lgtm, approved

#32528 Point release:latest to AMD payload for ARM tests
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__arm64-nightly.yaml
Labels: lgtm, approved

#33013 Switch to UBI-9 image
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-main.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-main__ods.yaml
Labels: lgtm, approved

#32873 clean up TEST_SKIPS around alerts
  ci-operator/config/openshift/cloud-provider-openstack/openshift-cloud-provider-openstack-release-4.10.yaml
  ci-operator/config/openshift/cloud-provider-openstack/openshift-cloud-provider-openstack-release-4.11.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-master.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.10.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.11.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.12.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.13.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.8.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.9.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.10.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.11.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.12.yaml
Labels: lgtm, approved

#33016 THREESCALE-8535 bump go lang
  ci-operator/config/3scale/3scale-operator/3scale-3scale-operator-master.yaml
Labels: lgtm, approved
