Repository openshift/release, pull requests merged in 2022-03, with the labels that each got.

#26640 [CRC] Switch dev branch to main
  ci-operator/config/code-ready/crc/code-ready-crc-main.yaml
  ci-operator/jobs/code-ready/crc/code-ready-crc-main-presubmits.yaml
Labels: lgtm, approved

#26608 [4.12] Consume ci operator and job configs
  clusters/app.ci/assets/dptp-controller-manager.yaml
  clusters/app.ci/assets/slack-bot.yaml
  clusters/app.ci/ci-chat-bot/ci-chat-bot.yaml
  clusters/app.ci/ci-operator-configresolver/ci-operator-configresolver.yaml
  clusters/app.ci/prow/03_deployment/better-retester.yaml
  clusters/app.ci/prow/03_deployment/crier.yaml
  clusters/app.ci/prow/03_deployment/deck.yaml
  clusters/app.ci/prow/03_deployment/hook.yaml
  clusters/app.ci/prow/03_deployment/horologium.yaml
  clusters/app.ci/prow/03_deployment/jenkins_operator.yaml
  clusters/app.ci/prow/03_deployment/prow-controller-manager.yaml
  clusters/app.ci/prow/03_deployment/statusreconciler.yaml
  clusters/app.ci/prow/03_deployment/tide.yaml
  clusters/app.ci/prow/03_deployment/tot.yaml
Labels: lgtm, approved

#26623 Remove the unnecessary branch protection setting protect=true
  core-services/prow/02_config/code-ready/crc/_prowconfig.yaml
  core-services/prow/02_config/code-ready/snc/_prowconfig.yaml
  core-services/prow/02_config/kubevirt/hyperconverged-cluster-operator/_prowconfig.yaml
  core-services/prow/02_config/kubevirt/node-maintenance-operator/_prowconfig.yaml
  core-services/prow/02_config/openshift/oadp-operator/_prowconfig.yaml
Labels: lgtm, approved

#26534 Set the pipefail option in osin tests
  ci-operator/config/openshift/osin/openshift-osin-master.yaml
Labels: lgtm, approved

#26609 adding cluster install behind proxy in a restricted network
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse.yaml
  ci-operator/step-registry/azure/OWNERS
  ci-operator/step-registry/azure/deprovision/OWNERS
  ci-operator/step-registry/azure/deprovision/resourcegroup/OWNERS
  ci-operator/step-registry/azure/deprovision/resourcegroup/azure-deprovision-resourcegroup-commands.sh
  ci-operator/step-registry/azure/deprovision/resourcegroup/azure-deprovision-resourcegroup-ref.metadata.json
  ci-operator/step-registry/azure/deprovision/resourcegroup/azure-deprovision-resourcegroup-ref.yaml
  ci-operator/step-registry/azure/provision/OWNERS
  ci-operator/step-registry/azure/provision/bastionhost/OWNERS
  ci-operator/step-registry/azure/provision/bastionhost/azure-provision-bastionhost-commands.sh
  ci-operator/step-registry/azure/provision/bastionhost/azure-provision-bastionhost-ref.metadata.json
  ci-operator/step-registry/azure/provision/bastionhost/azure-provision-bastionhost-ref.yaml
  ci-operator/step-registry/azure/provision/resourcegroup/OWNERS
  ci-operator/step-registry/azure/provision/resourcegroup/azure-provision-resourcegroup-commands.sh
  ci-operator/step-registry/azure/provision/resourcegroup/azure-provision-resourcegroup-ref.metadata.json
  ci-operator/step-registry/azure/provision/resourcegroup/azure-provision-resourcegroup-ref.yaml
  ci-operator/step-registry/azure/provision/vnet/OWNERS
  ci-operator/step-registry/azure/provision/vnet/azure-provision-vnet-commands.sh
  ci-operator/step-registry/azure/provision/vnet/azure-provision-vnet-ref.metadata.json
  ci-operator/step-registry/azure/provision/vnet/azure-provision-vnet-ref.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/proxy/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/proxy/cucushift-installer-rehearse-azure-ipi-proxy-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/proxy/cucushift-installer-rehearse-azure-ipi-proxy-workflow.yaml
  ci-operator/step-registry/ipi/conf/azure/provisionednetwork/OWNERS
  ci-operator/step-registry/ipi/conf/azure/provisionednetwork/ipi-conf-azure-provisionednetwork-commands.sh
  ci-operator/step-registry/ipi/conf/azure/provisionednetwork/ipi-conf-azure-provisionednetwork-ref.metadata.json
  ci-operator/step-registry/ipi/conf/azure/provisionednetwork/ipi-conf-azure-provisionednetwork-ref.yaml
  ci-operator/step-registry/ipi/conf/azure/proxy/OWNERS
  ci-operator/step-registry/ipi/conf/azure/proxy/ipi-conf-azure-proxy-commands.sh
  ci-operator/step-registry/ipi/conf/azure/proxy/ipi-conf-azure-proxy-ref.metadata.json
  ci-operator/step-registry/ipi/conf/azure/proxy/ipi-conf-azure-proxy-ref.yaml
Labels: lgtm, approved

#26645 Bump dev-scripts release from 4.10 to 4.11
  ci-operator/config/openshift-metal3/dev-scripts/openshift-metal3-dev-scripts-master.yaml
Labels: lgtm, approved

#26651 Cleaning out non-existent multiarch job references
  core-services/release-controller/_releases/priv/release-ocp-4.10-ppc64le.json
  core-services/release-controller/_releases/priv/release-ocp-4.10-s390x.json
  core-services/release-controller/_releases/priv/release-ocp-4.11-ppc64le.json
  core-services/release-controller/_releases/priv/release-ocp-4.11-s390x.json
  core-services/release-controller/_releases/priv/release-ocp-4.6-ppc64le.json
  core-services/release-controller/_releases/priv/release-ocp-4.6-s390x.json
  core-services/release-controller/_releases/priv/release-ocp-4.7-ppc64le.json
  core-services/release-controller/_releases/priv/release-ocp-4.7-s390x.json
  core-services/release-controller/_releases/priv/release-ocp-4.8-ppc64le.json
  core-services/release-controller/_releases/priv/release-ocp-4.8-s390x.json
  core-services/release-controller/_releases/priv/release-ocp-4.9-ppc64le.json
  core-services/release-controller/_releases/priv/release-ocp-4.9-s390x.json
  core-services/release-controller/_releases/release-ocp-4.10-ppc64le.json
  core-services/release-controller/_releases/release-ocp-4.10-s390x.json
  core-services/release-controller/_releases/release-ocp-4.11-ppc64le.json
  core-services/release-controller/_releases/release-ocp-4.11-s390x.json
  core-services/release-controller/_releases/release-ocp-4.6-ppc64le.json
  core-services/release-controller/_releases/release-ocp-4.6-s390x.json
  core-services/release-controller/_releases/release-ocp-4.7-ppc64le.json
  core-services/release-controller/_releases/release-ocp-4.7-s390x.json
  core-services/release-controller/_releases/release-ocp-4.8-ppc64le.json
  core-services/release-controller/_releases/release-ocp-4.8-s390x.json
  core-services/release-controller/_releases/release-ocp-4.9-ppc64le.json
  core-services/release-controller/_releases/release-ocp-4.9-s390x.json
Labels: lgtm, approved

#26631 Adding support for the trt-admins Rover Group and RBAC
  clusters/app.ci/trt/admin_trt.yaml
  core-services/sync-rover-groups/_config.yaml
  hack/generators/release-controllers/config/__init__.py
  hack/generators/release-controllers/content/__init__.py
  hack/generators/release-controllers/content/development_rbac.py
  hack/generators/release-controllers/content/trt_rbac.py
  hack/generators/release-controllers/generate-release-controllers.py
Labels: lgtm, approved

#26637 Allow ART to manage base images in ocp-private
  clusters/app.ci/release-controller/admin_deploy-ocp-publish-art.yaml
  hack/generators/release-controllers/content/art_publish_permissions.py
Labels: lgtm, approved

#26581 WINC-607: Require platform=none job in master presubmits
  ci-operator/jobs/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.11-presubmits.yaml
  ci-operator/jobs/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.12-presubmits.yaml
Labels: lgtm, approved

#26587 LOG-2247: Update quay mirroring for fluentd v1.14.5
  core-services/image-mirroring/openshift-logging/mapping_logging_5_4_quay
  core-services/image-mirroring/openshift-logging/mapping_logging_fluentd_quay
Labels: lgtm, approved

#26641 osde2e: Updated gpu-operator test harness
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: lgtm, approved

#26658 Remove assisted-test-infra live-iso periodics
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-periodics.yaml
Labels: lgtm, approved

#26617 Set z-stream approvers for OpenShift-Ansible
  core-services/prow/02_config/openshift/openshift-ansible/_pluginconfig.yaml
Labels: lgtm, approved

#26659 Retire `jenkins-ci-provisioner` secret in Vault
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved

#26634 openshift/machine-config-operator: Drop e2e-aws-workers-rhel7
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-master.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-master-presubmits.yaml
Labels: lgtm, approved

#26660 Update GPU Operator tests
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-master.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-master__4.10.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-master__4.6.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-master__4.7.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-master__4.8.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-master__4.9.yaml
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-master__upgrade.yaml
  ci-operator/jobs/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-master-presubmits.yaml
Labels: lgtm, approved

#26644 [4.12] Configure 4.12 mirroring lists
  core-services/image-mirroring/openshift/_config.yaml
Labels: lgtm, approved

#26670 kni: nrop: build numacell CI plugin
  ci-operator/config/openshift-kni/numaresources-operator/openshift-kni-numaresources-operator-main.yaml
Labels: lgtm, approved

#26673 Introduce separate ghproxy throttling time for v4
  clusters/app.ci/prow/03_deployment/ghproxy.yaml
Labels: lgtm, approved

#26662 github-ldap-user-group-creator manages group/openshift-priv-admins
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
  ci-operator/jobs/infra-periodics.yaml
  clusters/app.ci/assets/admin_openshift-priv-admins-to-openshift-priv-ns_rolebinding.yaml
  clusters/app.ci/group-auto-updater/OWNERS
  clusters/app.ci/group-auto-updater/README.md
  clusters/app.ci/group-auto-updater/admin_rbac.yaml
Labels: lgtm, approved

#26668 Make correct tag to net-kourier and net-istio
  ci-operator/config/openshift-knative/net-istio/openshift-knative-net-istio-release-1.1.yaml
  ci-operator/config/openshift-knative/net-kourier/openshift-knative-net-kourier-release-1.1.yaml
Labels: lgtm, approved

#26650 Mirror opendatahub-io/kubeflow promoted images to quay.io
  ci-operator/jobs/infra-image-mirroring.yaml
  core-services/image-mirroring/opendatahub-io/OWNERS
  core-services/image-mirroring/opendatahub-io/mapping_kubeflow_1_5_quay
  core-services/image-mirroring/opendatahub-io/mapping_kubeflow_latest_quay
Labels: lgtm, approved

#26550 Honor OLM's upstream .ci-operator.yaml
  ci-operator/config/openshift/operator-framework-olm/openshift-operator-framework-olm-master.yaml
  ci-operator/jobs/openshift/operator-framework-olm/openshift-operator-framework-olm-master-postsubmits.yaml
  ci-operator/jobs/openshift/operator-framework-olm/openshift-operator-framework-olm-master-presubmits.yaml
Labels: lgtm, approved

#26685 Fix image use in cluster-proxy-addon
  ci-operator/config/stolostron/cluster-proxy-addon/stolostron-cluster-proxy-addon-main.yaml
Labels: lgtm, approved

#26678 stolostron/console: Remove unneccessary build step from unit tests
  ci-operator/config/stolostron/console/stolostron-console-backplane-2.0.yaml
  ci-operator/config/stolostron/console/stolostron-console-main.yaml
  ci-operator/config/stolostron/console/stolostron-console-release-2.3.yaml
  ci-operator/config/stolostron/console/stolostron-console-release-2.4.yaml
  ci-operator/config/stolostron/console/stolostron-console-release-2.5.yaml
Labels: lgtm, approved

#25366 OADP: Add jobs for OCP 4.9 stable
  ci-operator/config/openshift/oadp-operator/openshift-oadp-operator-master__4.9.yaml
  ci-operator/jobs/openshift/oadp-operator/OWNERS
  ci-operator/jobs/openshift/oadp-operator/openshift-oadp-operator-master-periodics.yaml
  ci-operator/jobs/openshift/oadp-operator/openshift-oadp-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/oadp-operator/openshift-oadp-operator-master-presubmits.yaml
Labels: lgtm, approved

#26686 osde2e-job-updates
  ci-operator/config/openshift/osde2e/openshift-osde2e-main.yaml
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: lgtm, approved

#26676 Use resumeTimeout: 20m in OpenShift CI pools
  clusters/hive/pools/openshift-ci/ci-ocp-4-10-0-amd64-aws-us-east-1_clusterpool.yaml
  clusters/hive/pools/openshift-ci/ci-ocp-4-6-0-amd64-aws-us-east-1_clusterpool.yaml
  clusters/hive/pools/openshift-ci/ci-ocp-4-7-0-amd64-aws-us-east-1_clusterpool.yaml
  clusters/hive/pools/openshift-ci/ci-ocp-4-8-0-amd64-aws-us-east-1_clusterpool.yaml
  clusters/hive/pools/openshift-ci/ci-ocp-4-8-0-amd64-aws-us-west-1_clusterpool.yaml
  clusters/hive/pools/openshift-ci/ci-ocp-4-9-0-amd64-aws-us-west-1_clusterpool.yaml
Labels: lgtm, approved

#26681 Remove abandoned integr8ly/grafana-operator CI config
  ci-operator/config/integr8ly/grafana-operator/OWNERS
  ci-operator/config/integr8ly/grafana-operator/integr8ly-grafana-operator-master.yaml
  ci-operator/jobs/integr8ly/grafana-operator/OWNERS
  ci-operator/jobs/integr8ly/grafana-operator/integr8ly-grafana-operator-master-postsubmits.yaml
  ci-operator/jobs/integr8ly/grafana-operator/integr8ly-grafana-operator-master-presubmits.yaml
  core-services/prow/02_config/integr8ly/grafana-operator/OWNERS
  core-services/prow/02_config/integr8ly/grafana-operator/_pluginconfig.yaml
  core-services/prow/02_config/integr8ly/grafana-operator/_prowconfig.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: lgtm, approved

#26689 Hypershift conformance: Bump timeout for clusteroperatos
  ci-operator/step-registry/hypershift/test/aws/create/hypershift-test-aws-create-chain.yaml
Labels: lgtm, approved

#26646 Add Oleg as backport risk assessor to cluster-openshift-apiserver-operator
  core-services/prow/02_config/openshift/cluster-openshift-apiserver-operator/_pluginconfig.yaml
Labels: lgtm, approved

#26691 Hypershift nested presubmit: Use latest CPO image
  ci-operator/config/openshift/hypershift/openshift-hypershift-main.yaml
Labels: lgtm, approved

#26435 WINC-602: Support Windows Server 2022
  ci-operator/step-registry/upi/conf/vsphere/ova/windows/upi-conf-vsphere-ova-windows-commands.sh
Labels: lgtm, approved

#26693 image-mirroring: Stop mirroring coreos-assembler from quay.io
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_coreos
Labels: lgtm, approved

#26702 coreos-assembler: use secretReference for trigger
  clusters/app.ci/supplemental-ci-images/coreos/cosa-rhcos-branched-bc.yaml
Labels: lgtm, approved

#26589 Add service account to hypershift-toolkit namespace for release job
  clusters/app.ci/hypershift-toolkit/OWNERS
  clusters/app.ci/hypershift-toolkit/rbac.yaml
  clusters/app.ci/hypershift-toolkit/sa.yaml
Labels: lgtm, approved

#26705 Adding new secrets for Jikarta to use CCS
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: lgtm, approved

#26656 Update OWNERS
  core-services/image-mirroring/openshift-logging/OWNERS
Labels: lgtm, approved

#26629 ci-operator/config/openshift/release: Drop failing minor rollback tests
  ci-operator/config/openshift/release/openshift-release-master__ci-4.10-upgrade-from-stable-4.9.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.5-upgrade-from-stable-4.4.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.6-upgrade-from-stable-4.5.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.7-upgrade-from-stable-4.6.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.8-upgrade-from-stable-4.7.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: lgtm, approved

#26706 Added the volumeMounts
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: lgtm, approved

#26672 minor fix
  ci-operator/step-registry/azure/deprovision/resourcegroup/azure-deprovision-resourcegroup-commands.sh
  ci-operator/step-registry/azure/provision/bastionhost/azure-provision-bastionhost-commands.sh
Labels: lgtm, approved

#26707 Mirror Knative eventing test images to Quay for 1.1 and 1.2
  core-services/image-mirroring/knative/mapping_knative_v1_1_quay
  core-services/image-mirroring/knative/mapping_knative_v1_2_quay
Labels: lgtm, approved

#26712 osde2e gpu-addon: Increased addon polling timeout
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: lgtm, approved

#26714 spyglass: highlight 'Step <step> failed after' lines
  core-services/prow/02_config/_config.yaml
Labels: lgtm, approved

#26654 MGMT-9482: Change subsystem jobs OCP clusters to use 4.10 cluster pool
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-cloud_hotfix_releases.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.4.yaml
Labels: lgtm, approved

#26715 Tide: Use GH apps auth
  clusters/app.ci/prow/03_deployment/tide.yaml
Labels: lgtm, approved

#26718 Ghproxy: new throttling timings
  clusters/app.ci/prow/03_deployment/ghproxy.yaml
Labels: lgtm, approved

#26719 Ghproxy: v3 time again to 300ms
  clusters/app.ci/prow/03_deployment/ghproxy.yaml
Labels: approved

#26597 ci-operator/config/openshift/release: Add no-capabilities periodic
  ci-operator/config/openshift/release/openshift-release-master__ci-4.11.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  ci-operator/step-registry/ipi/conf/ipi-conf-commands.sh
  ci-operator/step-registry/ipi/conf/ipi-conf-ref.yaml
Labels: lgtm, approved

#26724 Revert "Tide: Use GH apps auth"
  clusters/app.ci/prow/03_deployment/tide.yaml
Labels: lgtm, approved

#26704 Update OLM CI to use custom CI image
  ci-operator/config/openshift/operator-framework-olm/openshift-operator-framework-olm-master.yaml
Labels: lgtm, approved

#26726 Trigger static-ip job daily instead of 6 times a day
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-periodics.yaml
Labels: lgtm, approved

#26732 hypershift: switch tests to 4.9 cluster pool
  ci-operator/config/openshift/hypershift/openshift-hypershift-main.yaml
  clusters/hive/pools/hypershift/hypershift-ocp-4-8-0-amd64-aws-us-east-1_clusterpool.yaml
  clusters/hive/pools/hypershift/hypershift-ocp-4-9-0-amd64-aws-us-east-1_clusterpool.yaml
Labels: lgtm, approved

#26574 MAPO presubmits on master run with CustomNoUpgrade
  ci-operator/config/openshift/machine-api-provider-openstack/openshift-machine-api-provider-openstack-master.yaml
  ci-operator/step-registry/ipi/conf/customnoupgrade/OWNERS
  ci-operator/step-registry/ipi/conf/customnoupgrade/ipi-conf-customnoupgrade-commands.sh
  ci-operator/step-registry/ipi/conf/customnoupgrade/ipi-conf-customnoupgrade-ref.metadata.json
  ci-operator/step-registry/ipi/conf/customnoupgrade/ipi-conf-customnoupgrade-ref.yaml
  ci-operator/step-registry/ipi/conf/openstack/ipi-conf-openstack-chain.yaml
Labels: lgtm, approved

#26734 Initial CI configs for node-observability-operator
  ci-operator/config/openshift/node-observability-operator/OWNERS
  ci-operator/config/openshift/node-observability-operator/openshift-node-observability-operator-main.yaml
  ci-operator/jobs/openshift/node-observability-operator/OWNERS
  ci-operator/jobs/openshift/node-observability-operator/openshift-node-observability-operator-main-presubmits.yaml
  core-services/prow/02_config/openshift/node-observability-operator/OWNERS
  core-services/prow/02_config/openshift/node-observability-operator/_pluginconfig.yaml
Labels: lgtm, approved

#26738 hypershift: switch periodics to 4.9
  ci-operator/config/openshift/hypershift/openshift-hypershift-main__periodics.yaml
Labels: lgtm, approved

#26739 Removing build02 from the cluster pools
  clusters/app.ci/release-controller/deploy-ocp-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-priv-controller.yaml
  hack/generators/release-controllers/content/osd_rc_deployments.py
Labels: lgtm, approved

#26742 s8n: change group name to match rover name
  clusters/app.ci/registry-access/stolostron/admin_stolostron.yaml
Labels: lgtm, approved

#26743 Include b02 pull secret in gcp cluster profile
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved

#26711 Fix image name in the aws-load-balancer-controller
  ci-operator/config/openshift/aws-load-balancer-controller/openshift-aws-load-balancer-controller-main.yaml
Labels: lgtm, approved

#26744 Include b02 pull secret in all cluster profiles
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved

#26517 add periodic RHCOS OS builds
  ci-operator/config/openshift/os/openshift-os-master.yaml
  ci-operator/jobs/openshift/os/openshift-os-master-periodics.yaml
Labels: lgtm, approved

#26730 core-services: add patrickdillon as backport-risk-assessed labeler for installer
  core-services/prow/02_config/openshift/installer/_pluginconfig.yaml
Labels: lgtm, approved

#26591 WINC-607: Require platform=none job in 4.10 presubmits
  ci-operator/jobs/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.10-presubmits.yaml
Labels: lgtm, approved

#26751 Update minor version for kafka consumer test image
  core-services/image-mirroring/knative/mapping_knative_v1_1_quay
Labels: lgtm, approved

#26752 Fix broken image mirror
  core-services/image-mirroring/knative/mapping_knative_v1_2_quay
Labels: lgtm, approved

#26696 openstack/nfv: add experimental job for OpenStack
  ci-operator/config/openshift/sriov-network-operator/openshift-sriov-network-operator-master.yaml
  ci-operator/jobs/openshift/sriov-network-operator/openshift-sriov-network-operator-master-presubmits.yaml
  ci-operator/step-registry/openshift/e2e/openstack/nfv-experimental/OWNERS
  ci-operator/step-registry/openshift/e2e/openstack/nfv-experimental/openshift-e2e-openstack-nfv-experimental-workflow.metadata.json
  ci-operator/step-registry/openshift/e2e/openstack/nfv-experimental/openshift-e2e-openstack-nfv-experimental-workflow.yaml
Labels: lgtm, approved

#26756 [CRC] Remove bundle zip format
  ci-operator/step-registry/code-ready/crc/e2e/test/code-ready-crc-e2e-test-commands.sh
Labels: lgtm, approved

#26753 Add CI Configuration for openshift/node-observability-agent
  ci-operator/config/openshift/node-observability-agent/OWNERS
  ci-operator/config/openshift/node-observability-agent/openshift-node-observability-agent-main.yaml
  ci-operator/jobs/openshift/node-observability-agent/OWNERS
  ci-operator/jobs/openshift/node-observability-agent/openshift-node-observability-agent-main-presubmits.yaml
  core-services/prow/02_config/openshift/node-observability-agent/_pluginconfig.yaml
Labels: lgtm, approved

#26709 update ci-operator config for hac-infra
  ci-operator/config/openshift/hac-infra/openshift-hac-infra-main.yaml
  ci-operator/jobs/openshift/hac-infra/openshift-hac-infra-main-presubmits.yaml
Labels: lgtm, approved

#26758 NO-ISSUE: docker credentials in assisted baremetal
  ci-operator/step-registry/assisted/baremetal/setup/assisted-baremetal-setup-commands.sh
Labels: lgtm, approved

#26596 ibm-roks-toolkit: add post-submit release job
  ci-operator/config/openshift/ibm-roks-toolkit/openshift-ibm-roks-toolkit-master.yaml
  ci-operator/config/openshift/ibm-roks-toolkit/openshift-ibm-roks-toolkit-release-4.10.yaml
  ci-operator/config/openshift/ibm-roks-toolkit/openshift-ibm-roks-toolkit-release-4.6.yaml
  ci-operator/config/openshift/ibm-roks-toolkit/openshift-ibm-roks-toolkit-release-4.7.yaml
  ci-operator/config/openshift/ibm-roks-toolkit/openshift-ibm-roks-toolkit-release-4.8.yaml
  ci-operator/config/openshift/ibm-roks-toolkit/openshift-ibm-roks-toolkit-release-4.9.yaml
  ci-operator/jobs/openshift/ibm-roks-toolkit/openshift-ibm-roks-toolkit-master-postsubmits.yaml
  ci-operator/jobs/openshift/ibm-roks-toolkit/openshift-ibm-roks-toolkit-release-4.10-postsubmits.yaml
  ci-operator/jobs/openshift/ibm-roks-toolkit/openshift-ibm-roks-toolkit-release-4.6-postsubmits.yaml
  ci-operator/jobs/openshift/ibm-roks-toolkit/openshift-ibm-roks-toolkit-release-4.7-postsubmits.yaml
  ci-operator/jobs/openshift/ibm-roks-toolkit/openshift-ibm-roks-toolkit-release-4.8-postsubmits.yaml
  ci-operator/jobs/openshift/ibm-roks-toolkit/openshift-ibm-roks-toolkit-release-4.9-postsubmits.yaml
Labels: lgtm, approved

#26759 Remove tnozicka/openshift-acme configs
  ci-operator/config/tnozicka/openshift-acme/OWNERS
  ci-operator/config/tnozicka/openshift-acme/tnozicka-openshift-acme-master.yaml
  ci-operator/jobs/infra-image-mirroring.yaml
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/tnozicka/openshift-acme/OWNERS
  ci-operator/jobs/tnozicka/openshift-acme/tnozicka-openshift-acme-master-postsubmits.yaml
  ci-operator/jobs/tnozicka/openshift-acme/tnozicka-openshift-acme-master-presubmits.yaml
  core-services/ci-secret-bootstrap/_config.yaml
  core-services/image-mirroring/tnozicka/OWNERS
  core-services/image-mirroring/tnozicka/mapping_tnozicka_openshift-acme
  core-services/prow/02_config/tnozicka/openshift-acme/OWNERS
  core-services/prow/02_config/tnozicka/openshift-acme/_pluginconfig.yaml
  core-services/prow/02_config/tnozicka/openshift-acme/_prowconfig.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: lgtm, approved

#26757 machine-api-provider-openstack: Add proxy test
  ci-operator/config/openshift/machine-api-provider-openstack/openshift-machine-api-provider-openstack-master.yaml
  ci-operator/jobs/openshift/machine-api-provider-openstack/openshift-machine-api-provider-openstack-master-presubmits.yaml
Labels: lgtm, approved

#26688 Assisted dropped support for non-day2 4.7 installation, no need to test it periodically any longer
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.7.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: lgtm, approved

#26767 OCM: mirror bundle image for PR
  ci-operator/config/stolostron/search-v2-operator/stolostron-search-v2-operator-main.yaml
  ci-operator/config/stolostron/search-v2-operator/stolostron-search-v2-operator-release-2.5.yaml
  ci-operator/jobs/stolostron/search-v2-operator/stolostron-search-v2-operator-main-presubmits.yaml
  ci-operator/jobs/stolostron/search-v2-operator/stolostron-search-v2-operator-release-2.5-presubmits.yaml
Labels: lgtm, approved

#26771 hypershift: skip nested e2e for docs
  ci-operator/config/openshift/hypershift/openshift-hypershift-main.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-main-presubmits.yaml
Labels: lgtm, approved

#26770 Updated the secrets to match the correct formatting.
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: lgtm, approved

#26765 Bump roks-toolkit-base image
  clusters/app.ci/supplemental-ci-images/ibm-roks-toolkit-base/ibm-roks-toolkit-base.yaml
Labels: lgtm, approved

#26769 Remove a postsubmit with group-auto-updater
  ci-operator/jobs/openshift/config/openshift-config-master-postsubmits.yaml
Labels: lgtm, approved

#26755 Onboard redhat-appstudio/application-service component
  ci-operator/config/redhat-appstudio/application-service/OWNERS
  ci-operator/config/redhat-appstudio/application-service/redhat-appstudio-application-service-main.yaml
  ci-operator/jobs/redhat-appstudio/application-service/OWNERS
  ci-operator/jobs/redhat-appstudio/application-service/redhat-appstudio-application-service-main-presubmits.yaml
  core-services/prow/02_config/redhat-appstudio/application-service/_pluginconfig.yaml
Labels: lgtm, approved

#26775 Remove builds-rhel7 test for 4.10 and higher
  ci-operator/config/openshift/builder/openshift-builder-master.yaml
  ci-operator/config/openshift/builder/openshift-builder-release-4.10.yaml
  ci-operator/config/openshift/builder/openshift-builder-release-4.11.yaml
  ci-operator/config/openshift/builder/openshift-builder-release-4.12.yaml
  ci-operator/jobs/openshift/builder/openshift-builder-master-presubmits.yaml
  ci-operator/jobs/openshift/builder/openshift-builder-release-4.10-presubmits.yaml
  ci-operator/jobs/openshift/builder/openshift-builder-release-4.11-presubmits.yaml
  ci-operator/jobs/openshift/builder/openshift-builder-release-4.12-presubmits.yaml
Labels: lgtm, approved

#26773 Upgrade minor (stable to nightly) for arm64
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.11-upgrade-from-stable-4.10.yaml
  ci-operator/jobs/openshift/multiarch/openshift-multiarch-master-periodics.yaml
Labels: lgtm, approved

#26781 Use OCP 4.8 for release-ocm-2.4 branch subsystem tests
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.4.yaml
Labels: lgtm, approved

#26612 Creating a new Centos VM for the assisted-test-infra project
  ci-operator/step-registry/assisted/vsphere/assisted-vsphere-workflow.yaml
  ci-operator/step-registry/assisted/vsphere/setup/assisted-vsphere-setup-chain.yaml
  ci-operator/step-registry/assisted/vsphere/setup/configure/assisted-vsphere-setup-configure-commands.sh
  ci-operator/step-registry/assisted/vsphere/setup/machine/OWNERS
  ci-operator/step-registry/assisted/vsphere/setup/machine/assisted-vsphere-setup-machine-commands.sh
  ci-operator/step-registry/assisted/vsphere/setup/machine/assisted-vsphere-setup-machine-ref.metadata.json
  ci-operator/step-registry/assisted/vsphere/setup/machine/assisted-vsphere-setup-machine-ref.yaml
  ci-operator/step-registry/assisted/vsphere/setup/prejob-cleanup/assisted-vsphere-setup-prejob-cleanup-commands.sh
  ci-operator/step-registry/assisted/vsphere/setup/template/assisted-vsphere-setup-template-commands.sh
  ci-operator/step-registry/assisted/vsphere/teardown/OWNERS
  ci-operator/step-registry/assisted/vsphere/teardown/assisted-vsphere-teardown-chain.metadata.json
  ci-operator/step-registry/assisted/vsphere/teardown/assisted-vsphere-teardown-chain.yaml
  ci-operator/step-registry/assisted/vsphere/teardown/machine/OWNERS
  ci-operator/step-registry/assisted/vsphere/teardown/machine/assisted-vsphere-teardown-machine-commands.sh
  ci-operator/step-registry/assisted/vsphere/teardown/machine/assisted-vsphere-teardown-machine-ref.metadata.json
  ci-operator/step-registry/assisted/vsphere/teardown/machine/assisted-vsphere-teardown-machine-ref.yaml
Labels: lgtm, approved

#26787 Removing slack notifications for SRO release-4.12 jobs.
  ci-operator/jobs/openshift-psap/special-resource-operator/openshift-psap-special-resource-operator-release-4.12-periodics.yaml
Labels: lgtm, approved

#26789 shiftstack: Skip doctext check on weekends
  ci-operator/config/shiftstack/bugwatcher/shiftstack-bugwatcher-main.yaml
  ci-operator/jobs/shiftstack/bugwatcher/shiftstack-bugwatcher-main-periodics.yaml
Labels: lgtm, approved

#26790 MGMT-9533: when no diff, we need to stop this step execution
  ci-operator/step-registry/assisted/baremetal/tools/snapshot-repos/assisted-baremetal-tools-snapshot-repos-commands.sh
Labels: lgtm, approved

#26649 Changes for insights-operator-tests 4.10
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_ci
Labels: lgtm, approved

#26794 MGMT-9470: Attempt to promote OLM bundle
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master.yaml
Labels: lgtm, approved

#26795 Add _prowconfig for node-observability operator and agent
  core-services/prow/02_config/openshift/node-observability-agent/_prowconfig.yaml
  core-services/prow/02_config/openshift/node-observability-operator/_prowconfig.yaml
Labels: lgtm, approved

#26796 MGMT-9470 - Attempt another method for promotion of the ci-index
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
Labels: lgtm, approved

#26784 [CRC] Add bundle arch info to download bundles
  ci-operator/step-registry/code-ready/crc/e2e/test/code-ready-crc-e2e-test-commands.sh
  ci-operator/step-registry/code-ready/crc/integration/test/code-ready-crc-integration-test-commands.sh
Labels: lgtm, approved

#26694 Add install junit to help identify install step
  ci-operator/step-registry/baremetalds/devscripts/setup/baremetalds-devscripts-setup-commands.sh
  ci-operator/step-registry/gather/must-gather/gather-must-gather-commands.sh
  ci-operator/step-registry/ipi/install/install/ipi-install-install-commands.sh
  ci-operator/step-registry/ipi/install/libvirt/install/ipi-install-libvirt-install-commands.sh
  ci-operator/step-registry/upi/install/aws/cluster/upi-install-aws-cluster-commands.sh
  ci-operator/step-registry/upi/install/azure/upi-install-azure-commands.sh
  ci-operator/step-registry/upi/install/azurestack/upi-install-azurestack-commands.sh
  ci-operator/step-registry/upi/install/gcp/upi-install-gcp-commands.sh
  ci-operator/step-registry/upi/install/vsphere/upi-install-vsphere-commands.sh
Labels: lgtm, approved

#26792 add env for foundation-2.4
  ci-operator/config/stolostron/multicloud-operators-foundation/stolostron-multicloud-operators-foundation-release-2.4.yaml
Labels: lgtm, approved

#26633 add layering branch to machine-config-operator repo
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-layering.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-layering-postsubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-layering-presubmits.yaml
  core-services/prow/02_config/_plugins.yaml
  core-services/prow/02_config/openshift/machine-config-operator/_prowconfig.yaml
Labels: lgtm, approved

#26804 Revert "[upi-vsphere] Use Windows Server 2022 template"
  ci-operator/step-registry/upi/conf/vsphere/ova/windows/upi-conf-vsphere-ova-windows-commands.sh
Labels: lgtm, approved

#26801 remove mcbs branch config
  ci-operator/config/openshift-priv/machine-config-operator/openshift-priv-machine-config-operator-mcbs.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-mcbs.yaml
  ci-operator/jobs/openshift-priv/machine-config-operator/openshift-priv-machine-config-operator-mcbs-postsubmits.yaml
  ci-operator/jobs/openshift-priv/machine-config-operator/openshift-priv-machine-config-operator-mcbs-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-mcbs-postsubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-mcbs-presubmits.yaml
  core-services/prow/02_config/_plugins.yaml
  core-services/prow/02_config/openshift/machine-config-operator/_prowconfig.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: lgtm, approved

#26684 Hypershift: Use a cli in dump that keeps managed fields
  ci-operator/config/openshift/hypershift/openshift-hypershift-main__periodics.yaml
  ci-operator/step-registry/hypershift/test/aws/destroy/hypershift-test-aws-destroy-chain.yaml
Labels: lgtm, approved

#26806 Hypershift nested: Also dump guest cluster
  ci-operator/config/openshift/hypershift/openshift-hypershift-main.yaml
Labels: lgtm, approved

#26664 Increase Hypershift KubeVirt platform's nodepool replica count
  ci-operator/config/openshift/hypershift/openshift-hypershift-main.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.11.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.12.yaml
Labels: lgtm, approved

#26809 Include ci-xpn SA credentials in cluster-secrets-gcp
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved

#26808 don't hardcode release version in os push script
  ci-operator/config/openshift/os/openshift-os-master.yaml
  ci-operator/config/openshift/os/openshift-os-release-4.11.yaml
Labels: lgtm, approved

#26813 ocm: update image mirror in step registry
  ci-operator/step-registry/ocm/ci/image-mirror-periodic/ocm-ci-image-mirror-periodic-commands.sh
Labels: lgtm, approved

#26816 Update RHDS image builds to use centos:stream8
  ci-operator/config/red-hat-data-services/opendatahub-operator/red-hat-data-services-opendatahub-operator-master.yaml
  ci-operator/config/red-hat-data-services/opendatahub-operator/red-hat-data-services-opendatahub-operator-master__48.yaml
Labels: lgtm, approved

#26817 Ocm step update mirror
  ci-operator/step-registry/ocm/ci/image-mirror-periodic/ocm-ci-image-mirror-periodic-commands.sh
Labels: lgtm, approved

#26819 stolostron: multicloud-operators app repos sonar fix
  ci-operator/config/stolostron/multicloud-integrations/stolostron-multicloud-integrations-main.yaml
  ci-operator/config/stolostron/multicloud-integrations/stolostron-multicloud-integrations-release-2.4.yaml
  ci-operator/config/stolostron/multicloud-integrations/stolostron-multicloud-integrations-release-2.5.yaml
  ci-operator/config/stolostron/multicloud-operators-application/stolostron-multicloud-operators-application-main.yaml
  ci-operator/config/stolostron/multicloud-operators-application/stolostron-multicloud-operators-application-release-2.3.yaml
  ci-operator/config/stolostron/multicloud-operators-application/stolostron-multicloud-operators-application-release-2.4.yaml
  ci-operator/config/stolostron/multicloud-operators-application/stolostron-multicloud-operators-application-release-2.5.yaml
  ci-operator/config/stolostron/multicloud-operators-channel/stolostron-multicloud-operators-channel-main.yaml
  ci-operator/config/stolostron/multicloud-operators-channel/stolostron-multicloud-operators-channel-release-2.3.yaml
  ci-operator/config/stolostron/multicloud-operators-channel/stolostron-multicloud-operators-channel-release-2.4.yaml
  ci-operator/config/stolostron/multicloud-operators-channel/stolostron-multicloud-operators-channel-release-2.5.yaml
  ci-operator/config/stolostron/multicloud-operators-deployable/stolostron-multicloud-operators-deployable-main.yaml
  ci-operator/config/stolostron/multicloud-operators-deployable/stolostron-multicloud-operators-deployable-release-2.3.yaml
  ci-operator/config/stolostron/multicloud-operators-deployable/stolostron-multicloud-operators-deployable-release-2.4.yaml
  ci-operator/config/stolostron/multicloud-operators-placementrule/stolostron-multicloud-operators-placementrule-main.yaml
  ci-operator/config/stolostron/multicloud-operators-placementrule/stolostron-multicloud-operators-placementrule-release-2.3.yaml
  ci-operator/config/stolostron/multicloud-operators-placementrule/stolostron-multicloud-operators-placementrule-release-2.4.yaml
  ci-operator/config/stolostron/multicloud-operators-subscription-release/stolostron-multicloud-operators-subscription-release-main.yaml
  ci-operator/config/stolostron/multicloud-operators-subscription-release/stolostron-multicloud-operators-subscription-release-release-2.3.yaml
  ci-operator/config/stolostron/multicloud-operators-subscription-release/stolostron-multicloud-operators-subscription-release-release-2.4.yaml
  ci-operator/config/stolostron/multicloud-operators-subscription/stolostron-multicloud-operators-subscription-main.yaml
  ci-operator/config/stolostron/multicloud-operators-subscription/stolostron-multicloud-operators-subscription-release-2.3.yaml
  ci-operator/config/stolostron/multicloud-operators-subscription/stolostron-multicloud-operators-subscription-release-2.4.yaml
  ci-operator/config/stolostron/multicloud-operators-subscription/stolostron-multicloud-operators-subscription-release-2.5.yaml
  ci-operator/jobs/stolostron/multicloud-integrations/stolostron-multicloud-integrations-release-2.4-postsubmits.yaml
  ci-operator/jobs/stolostron/multicloud-integrations/stolostron-multicloud-integrations-release-2.5-postsubmits.yaml
  ci-operator/jobs/stolostron/multicloud-operators-application/stolostron-multicloud-operators-application-release-2.4-postsubmits.yaml
  ci-operator/jobs/stolostron/multicloud-operators-application/stolostron-multicloud-operators-application-release-2.5-postsubmits.yaml
  ci-operator/jobs/stolostron/multicloud-operators-channel/stolostron-multicloud-operators-channel-release-2.4-postsubmits.yaml
  ci-operator/jobs/stolostron/multicloud-operators-channel/stolostron-multicloud-operators-channel-release-2.5-postsubmits.yaml
  ci-operator/jobs/stolostron/multicloud-operators-deployable/stolostron-multicloud-operators-deployable-release-2.4-postsubmits.yaml
  ci-operator/jobs/stolostron/multicloud-operators-placementrule/stolostron-multicloud-operators-placementrule-release-2.3-presubmits.yaml
  ci-operator/jobs/stolostron/multicloud-operators-placementrule/stolostron-multicloud-operators-placementrule-release-2.4-postsubmits.yaml
  ci-operator/jobs/stolostron/multicloud-operators-subscription-release/stolostron-multicloud-operators-subscription-release-release-2.4-postsubmits.yaml
  ci-operator/jobs/stolostron/multicloud-operators-subscription/stolostron-multicloud-operators-subscription-release-2.4-postsubmits.yaml
  ci-operator/jobs/stolostron/multicloud-operators-subscription/stolostron-multicloud-operators-subscription-release-2.5-postsubmits.yaml
Labels: lgtm, approved

#26807 Netobserv: remove required labels for QE
  core-services/prow/02_config/netobserv/goflow2-kube-enricher/_prowconfig.yaml
  core-services/prow/02_config/netobserv/network-observability-console-plugin/_prowconfig.yaml
  core-services/prow/02_config/netobserv/network-observability-operator/_prowconfig.yaml
Labels: lgtm, approved

#26814 openstack/nfv: don't run tests as privileged
  ci-operator/step-registry/openstack/test/dpdk/openstack-test-dpdk-commands.sh
  ci-operator/step-registry/openstack/test/sriov/openstack-test-sriov-commands.sh
Labels: lgtm, approved

#26833 Removing slack notifications for d/s SRO release-4.12 jobs.
  ci-operator/jobs/openshift/special-resource-operator/openshift-special-resource-operator-release-4.12-periodics.yaml
Labels: lgtm, approved

#26665 shiftstack/upgrade: attempt to fix CI job for 4.11
  ci-operator/config/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main__periodic-4.11-upgrade-from-stable-4.10.yaml
Labels: lgtm, approved

#26822 hypershift: move remaining tests to 4.9 clusterpool
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.10.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.8.yaml
Labels: lgtm, approved

#26832 Revert "openstack/nfv: don't run tests as privileged"
  ci-operator/step-registry/openstack/test/dpdk/openstack-test-dpdk-commands.sh
  ci-operator/step-registry/openstack/test/sriov/openstack-test-sriov-commands.sh
Labels: lgtm, approved

#26838 coreos-assembler: add main ref to github trigger
  clusters/app.ci/supplemental-ci-images/coreos/cosa-rhcos-branched-bc.yaml
Labels: lgtm, approved

#26835 fix periodic os build branch selection
  ci-operator/config/openshift/os/openshift-os-master.yaml
  ci-operator/config/openshift/os/openshift-os-release-4.11.yaml
  ci-operator/config/openshift/os/openshift-os-release-4.12.yaml
Labels: lgtm, approved

#26723 [MGDAPI-3557] ci: add prow checks for MGDAPI-2427
  ci-operator/config/integr8ly/cloud-resource-operator/integr8ly-cloud-resource-operator-MGDAPI-2427.yaml
  ci-operator/jobs/integr8ly/cloud-resource-operator/integr8ly-cloud-resource-operator-MGDAPI-2427-postsubmits.yaml
  ci-operator/jobs/integr8ly/cloud-resource-operator/integr8ly-cloud-resource-operator-MGDAPI-2427-presubmits.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: lgtm, approved, ok-to-test

#26840 Add Viaq org wide config for plugins
  core-services/prow/02_config/ViaQ/OWNERS
  core-services/prow/02_config/ViaQ/_pluginconfig.yaml
  core-services/prow/02_config/ViaQ/log-file-metric-exporter/_pluginconfig.yaml
  core-services/prow/02_config/ViaQ/logging-fluentd/_pluginconfig.yaml
  core-services/prow/02_config/ViaQ/vector/_pluginconfig.yaml
Labels: lgtm, approved

#26536 Add cluster-group-upgrades-operator 4.11 entry for image mirroring
  core-services/image-mirroring/openshift-kni/mapping_openshift-kni_quay
Labels: lgtm, approved

#26841 temporarely change to hourly job
  ci-operator/config/openshift-assisted/assisted-installer-deployment/openshift-assisted-assisted-installer-deployment-master.yaml
  ci-operator/jobs/openshift-assisted/assisted-installer-deployment/openshift-assisted-assisted-installer-deployment-master-periodics.yaml
Labels: lgtm, approved

#26845 gather-must-gather-commands.sh: add a link to KaaS
  ci-operator/step-registry/gather/must-gather/gather-must-gather-commands.sh
Labels: lgtm, approved

#26592 WINC-607: Require platform=none job in 4.9 presubmits
  ci-operator/jobs/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.9-presubmits.yaml
Labels: lgtm, approved

#26820 enables layering-specific e2e tests
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-layering.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-layering-presubmits.yaml
Labels: lgtm, approved

#26844 hive: Remove one 4.8 pool, add additional 4.10 one
  clusters/hive/pools/openshift-ci/ci-ocp-4-10-0-amd64-aws-us-west-1_clusterpool.yaml
Labels: lgtm, approved

#26843 Move to dev
  ci-operator/config/stolostron/governance-policy-framework/stolostron-governance-policy-framework-main.yaml
  ci-operator/config/stolostron/governance-policy-framework/stolostron-governance-policy-framework-release-2.5.yaml
  ci-operator/config/stolostron/grc-ui/stolostron-grc-ui-main.yaml
  ci-operator/config/stolostron/grc-ui/stolostron-grc-ui-release-2.5.yaml
Labels: lgtm, approved

#26848 hypershift: disable always_run for some 4.10 tests
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.10-presubmits.yaml
Labels: lgtm, approved

#26851 machine-config-operator/layering: Add rhel-coreos into our builds
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-layering.yaml
Labels: lgtm, approved

#26540 gather-extra: spruce up the custom-link-tools
  ci-operator/step-registry/gather/extra/gather-extra-commands.sh
  ci-operator/step-registry/gather/must-gather/gather-must-gather-commands.sh
  ci-operator/step-registry/ipi/install/hosted-loki/ipi-install-hosted-loki-commands.sh
Labels: lgtm, approved

#26842 Set assisted-test-infra release-ocm-2.4 jobs to run every 3 days
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.4.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.4.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.4-periodics.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.4-periodics.yaml
Labels: lgtm, approved

#26831 MGMT-9470: Build and publish OLM index
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
  core-services/image-mirroring/edge-infrastructure/mapping_edge_infrastructure_latest
Labels: lgtm, approved

#26858 add new label to exclusive some cases
  ci-operator/step-registry/openshift-extended/test/openshift-extended-test-commands.sh
Labels: lgtm, approved

#26860 htmlproofer: update to v3.19.0
  clusters/app.ci/supplemental-ci-images/html-proofer_is.yaml
Labels: lgtm, approved

#26827 Assisted installer: 4.6 periodic should run weekly and without conformance tests
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-periodics.yaml
  ci-operator/step-registry/assisted/baremetal/test/assisted-baremetal-test-commands.sh
  ci-operator/step-registry/assisted/baremetal/test/assisted-baremetal-test-ref.yaml
Labels: lgtm, ¯\_(ツ)_/¯, approved

#26830 fix gathering on podman by setting LOGS_DEST
  ci-operator/step-registry/assisted/baremetal/gather/assisted-baremetal-gather-commands.sh
Labels: lgtm, approved

#26839 coreos: Switch to building fcos-buildroot here
  clusters/app.ci/supplemental-ci-images/coreos/fcos-buildroot.yaml
  core-services/image-mirroring/coreos/mapping_coreos_assembler_coreos_assembler
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_coreos
Labels: lgtm, approved

#26859 Revert "temporarely change to hourly job" to daily cron
  ci-operator/config/openshift-assisted/assisted-installer-deployment/openshift-assisted-assisted-installer-deployment-master.yaml
  ci-operator/jobs/openshift-assisted/assisted-installer-deployment/openshift-assisted-assisted-installer-deployment-master-periodics.yaml
Labels: lgtm, approved

#26867 Really use resumeTimeout: 20m in OpenShift CI pools
  clusters/hive/pools/openshift-ci/ci-ocp-4-10-0-amd64-aws-us-east-1_clusterpool.yaml
  clusters/hive/pools/openshift-ci/ci-ocp-4-10-0-amd64-aws-us-west-1_clusterpool.yaml
  clusters/hive/pools/openshift-ci/ci-ocp-4-6-0-amd64-aws-us-east-1_clusterpool.yaml
  clusters/hive/pools/openshift-ci/ci-ocp-4-7-0-amd64-aws-us-east-1_clusterpool.yaml
  clusters/hive/pools/openshift-ci/ci-ocp-4-8-0-amd64-aws-us-east-1_clusterpool.yaml
  clusters/hive/pools/openshift-ci/ci-ocp-4-9-0-amd64-aws-us-west-1_clusterpool.yaml
Labels: lgtm, approved

#26870 Fix PromeCIus link
  ci-operator/step-registry/gather/extra/gather-extra-commands.sh
  ci-operator/step-registry/gather/must-gather/gather-must-gather-commands.sh
Labels: lgtm, approved

#26849 convert 4.10 aggregated jobs to retry three times jobs
  core-services/release-controller/_releases/priv/release-ocp-4.10.json
  core-services/release-controller/_releases/priv/release-ocp-4.7.json
  core-services/release-controller/_releases/release-ocp-4.10-ci.json
  core-services/release-controller/_releases/release-ocp-4.10.json
  core-services/release-controller/_releases/release-ocp-4.7.json
Labels: lgtm, approved

#26666 Hypershift: Add an azure conformance periodic
  ci-operator/config/openshift/hypershift/openshift-hypershift-main__periodics.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-main-periodics.yaml
  ci-operator/step-registry/hypershift/OWNERS
  ci-operator/step-registry/hypershift/aws/OWNERS
  ci-operator/step-registry/hypershift/aws/conformance/OWNERS
  ci-operator/step-registry/hypershift/aws/conformance/hypershift-aws-conformance-workflow.metadata.json
  ci-operator/step-registry/hypershift/aws/conformance/hypershift-aws-conformance-workflow.yaml
  ci-operator/step-registry/hypershift/aws/create/OWNERS
  ci-operator/step-registry/hypershift/aws/create/hypershift-aws-create-chain.metadata.json
  ci-operator/step-registry/hypershift/aws/create/hypershift-aws-create-chain.yaml
  ci-operator/step-registry/hypershift/aws/destroy/OWNERS
  ci-operator/step-registry/hypershift/aws/destroy/hypershift-aws-destroy-chain.metadata.json
  ci-operator/step-registry/hypershift/aws/destroy/hypershift-aws-destroy-chain.yaml
  ci-operator/step-registry/hypershift/azure/OWNERS
  ci-operator/step-registry/hypershift/azure/conformance/OWNERS
  ci-operator/step-registry/hypershift/azure/conformance/hypershift-azure-conformance-workflow.metadata.json
  ci-operator/step-registry/hypershift/azure/conformance/hypershift-azure-conformance-workflow.yaml
  ci-operator/step-registry/hypershift/azure/create/OWNERS
  ci-operator/step-registry/hypershift/azure/create/hypershift-azure-create-chain.metadata.json
  ci-operator/step-registry/hypershift/azure/create/hypershift-azure-create-chain.yaml
  ci-operator/step-registry/hypershift/azure/destroy/OWNERS
  ci-operator/step-registry/hypershift/azure/destroy/hypershift-azure-destroy-chain.metadata.json
  ci-operator/step-registry/hypershift/azure/destroy/hypershift-azure-destroy-chain.yaml
  ci-operator/step-registry/hypershift/conformance/OWNERS
  ci-operator/step-registry/hypershift/conformance/hypershift-conformance-chain.metadata.json
  ci-operator/step-registry/hypershift/conformance/hypershift-conformance-chain.yaml
  ci-operator/step-registry/hypershift/dump/OWNERS
  ci-operator/step-registry/hypershift/dump/hypershift-dump-chain.metadata.json
  ci-operator/step-registry/hypershift/dump/hypershift-dump-chain.yaml
  ci-operator/step-registry/hypershift/install/OWNERS
  ci-operator/step-registry/hypershift/install/hypershift-install-chain.metadata.json
  ci-operator/step-registry/hypershift/install/hypershift-install-chain.yaml
  ci-operator/step-registry/hypershift/test/aws/test/OWNERS
Labels: lgtm, approved

#26872 Disable annotating of EOL releases
  hack/annotate.sh
Labels: lgtm, approved

#26682 Adds Jaime for backport-risk-assessed
  core-services/prow/02_config/openshift/cluster-network-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/machine-config-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/ovn-kubernetes/_pluginconfig.yaml
  core-services/prow/02_config/openshift/sdn/_pluginconfig.yaml
Labels: lgtm, approved

#26852 ci-docs: disable `htmlproofer` concurrency
  ci-operator/config/openshift/ci-docs/openshift-ci-docs-master.yaml
Labels: lgtm, approved

#26861 OSDE2E ARO: Adding the ovn latest Y job.
  ci-operator/config/openshift/osde2e/openshift-osde2e-main.yaml
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: lgtm, approved

#26554 Use official FDP repo
  core-services/release-controller/_repos/ocp-4.10-rhel8-aarch64.repo
  core-services/release-controller/_repos/ocp-4.10-rhel8.repo
  core-services/release-controller/_repos/ocp-4.11-rhel8-aarch64.repo
  core-services/release-controller/_repos/ocp-4.11-rhel8.repo
  core-services/release-controller/_repos/ocp-4.11-rhel85.repo
  core-services/release-controller/_repos/ocp-4.8-rhel8.repo
  core-services/release-controller/_repos/ocp-4.9-rhel8.repo
Labels: lgtm, approved

#26626 LOG-2002: Update osde addon periotic testing for Openshift logging
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: lgtm, approved

#26863 Add steps to verify-golint and verify-deps
  ci-operator/config/openshift/node-observability-agent/openshift-node-observability-agent-main.yaml
  ci-operator/jobs/openshift/node-observability-agent/openshift-node-observability-agent-main-presubmits.yaml
Labels: lgtm, approved

#26873 periodic os builds should alert on failure
  ci-operator/jobs/openshift/os/openshift-os-master-periodics.yaml
  ci-operator/jobs/openshift/os/openshift-os-release-4.11-periodics.yaml
  ci-operator/jobs/openshift/os/openshift-os-release-4.12-periodics.yaml
Labels: lgtm, approved

#26877 build-clusters: make CI admins `self-provisioner`s
  clusters/build-clusters/common/assets/admin_cluster-admin-0_list.yaml
Labels: lgtm, approved

#26880 ci-operator/config/openshift/release: Drop RHEL7 for 4.10+
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.10.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.11.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: lgtm, approved
