Repository openshift/release, pull requests merged in 2022-12, with the labels that each got.

#34402 Replace aws-ipi-ovn-ingress-nlb with aws-ipi-ingress-lbtype-nlb in 4.12+
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#34398 HyperShift: make conformance install wait until available
  ci-operator/step-registry/hypershift/install/hypershift-install-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#33476 fix: cucushift-installer-rehearse-aws-ipi-disconnected-private
  ci-operator/step-registry/aws/provision/cco-manual-users/static/aws-provision-cco-manual-users-static-commands.sh
Labels: lgtm, approved, rehearsals-ack

#34450 Add tide config and owners for openshift-knative/hack
  core-services/prow/02_config/openshift-knative/hack/OWNERS
  core-services/prow/02_config/openshift-knative/hack/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#34448 Disable NTO 4.14 and master branch nightly testing
  ci-operator/config/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-master.yaml
  ci-operator/config/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-release-4.14.yaml
  ci-operator/jobs/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-master-periodics.yaml
  ci-operator/jobs/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-release-4.14-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#34354 Add initial config and unit/linter tests for Glance
  ci-operator/config/openstack-k8s-operators/glance-operator/OWNERS
  ci-operator/config/openstack-k8s-operators/glance-operator/openstack-k8s-operators-glance-operator-master.yaml
  ci-operator/jobs/openstack-k8s-operators/glance-operator/OWNERS
  ci-operator/jobs/openstack-k8s-operators/glance-operator/openstack-k8s-operators-glance-operator-master-presubmits.yaml
  core-services/prow/02_config/openstack-k8s-operators/glance-operator/OWNERS
  core-services/prow/02_config/openstack-k8s-operators/glance-operator/_pluginconfig.yaml
  core-services/prow/02_config/openstack-k8s-operators/glance-operator/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#34429 SPLAT-880: Setup tide for provider-cert-tool
  core-services/prow/02_config/redhat-openshift-ecosystem/provider-certification-tool/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#33800 AGENT-415: Adding (optional) sno ipv6 agent job (dev-scrips repo)
  ci-operator/config/openshift-metal3/dev-scripts/openshift-metal3-dev-scripts-master.yaml
  ci-operator/jobs/openshift-metal3/dev-scripts/openshift-metal3-dev-scripts-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#34409 MGDAPI-4914 : Trigger e2e test on every PR to master
  ci-operator/config/integr8ly/integreatly-operator/integr8ly-integreatly-operator-master.yaml
  ci-operator/jobs/integr8ly/integreatly-operator/integr8ly-integreatly-operator-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#34432 [openshift-loki] Add release-5.6 mirroring for operator and bundle
  core-services/image-mirroring/openshift-logging/mapping_logging_5_6_quay
Labels: lgtm, approved, rehearsals-ack

#34459 Test always_run behavior
  ci-operator/jobs/openstack-k8s-operators/mariadb-operator/openstack-k8s-operators-mariadb-operator-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#34225 AGENT-415: Adding (optional) sno ipv6 agent job (installer repo)
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#33030 AGENT-371: add agent job for testing dualstack
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#34461 Revert "Test always_run behavior"
  ci-operator/jobs/openstack-k8s-operators/mariadb-operator/openstack-k8s-operators-mariadb-operator-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#31601 DPTP-2929 pod-scaler admission alert
  clusters/app.ci/prow-monitoring/mixins/_prometheus/dptp_alerts.libsonnet
  clusters/app.ci/prow-monitoring/mixins/prometheus_out/prometheus-prow-rules_prometheusrule.yaml
  docs/dptp-triage-sop/pod-scaler-admission.md
Labels: lgtm, approved, tide/merge-method-squash, rehearsals-ack

#34373 Remove all template based tests, release < 4.7
  ci-operator/jobs/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift/cloud-credential-operator/openshift-cloud-credential-operator-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-libvirt/openshift-cluster-api-provider-libvirt-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-libvirt/openshift-cluster-api-provider-libvirt-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-libvirt/openshift-cluster-api-provider-libvirt-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-libvirt/openshift-cluster-api-provider-libvirt-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-openstack/openshift-cluster-api-provider-openstack-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-openstack/openshift-cluster-api-provider-openstack-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-openstack/openshift-cluster-api-provider-openstack-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-openstack/openshift-cluster-api-provider-openstack-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/image-registry/openshift-image-registry-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-fcos-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.3-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.4-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.5-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.6-periodics.yaml
  core-services/release-controller/_releases/priv/release-ocp-4.2.json
  core-services/release-controller/_releases/priv/release-ocp-4.3.json
  core-services/release-controller/_releases/priv/release-ocp-4.4.json
  core-services/release-controller/_releases/priv/release-ocp-4.5.json
  core-services/release-controller/_releases/priv/release-ocp-4.6.json
  core-services/release-controller/_releases/release-ocp-4.2.json
  core-services/release-controller/_releases/release-ocp-4.3-ci.json
  core-services/release-controller/_releases/release-ocp-4.3.json
  core-services/release-controller/_releases/release-ocp-4.4-ci.json
  core-services/release-controller/_releases/release-ocp-4.4.json
  core-services/release-controller/_releases/release-ocp-4.5-ci.json
  core-services/release-controller/_releases/release-ocp-4.5.json
  core-services/release-controller/_releases/release-ocp-4.6.json
Labels: lgtm, approved, rehearsals-ack

#34426 remove old pj-rehearse jobs
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#34433 reduce frequency of vSphere periodics
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.10.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.6.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.7.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.8.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.9.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#34436 vsphere: add more quota to ibm vsphere env
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: lgtm, approved, rehearsals-ack

#34462 continuous-release-jobs: Make presubmit jobs required
  ci-operator/jobs/openshift/continuous-release-jobs/openshift-continuous-release-jobs-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#33729 fix clo next job
  ci-operator/config/openshift/cluster-logging-operator/openshift-cluster-logging-operator-master.yaml
Labels: lgtm, approved, rehearsals-ack

#34463 NO-ISSUE: Extend usage of assisted upgrade agent test
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master__edge.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-periodics.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#34474 CRT: Only run images test if Dockerfiles change
  ci-operator/jobs/openshift/continuous-release-jobs/openshift-continuous-release-jobs-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-client-python/openshift-openshift-client-python-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#34472 kcp-dev/*: enable milestone plugins
  core-services/prow/02_config/kcp-dev/apiextensions-apiserver/_pluginconfig.yaml
  core-services/prow/02_config/kcp-dev/apimachinery/_pluginconfig.yaml
  core-services/prow/02_config/kcp-dev/client-go/_pluginconfig.yaml
  core-services/prow/02_config/kcp-dev/code-generator/_pluginconfig.yaml
  core-services/prow/02_config/kcp-dev/controller-runtime-example/_pluginconfig.yaml
  core-services/prow/02_config/kcp-dev/controller-runtime/_pluginconfig.yaml
  core-services/prow/02_config/kcp-dev/edge-mc/_pluginconfig.yaml
  core-services/prow/02_config/kcp-dev/kcp/_pluginconfig.yaml
  core-services/prow/02_config/kcp-dev/logicalcluster/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#34045 Prow CI poc
  ci-operator/config/rhpit/interop-tests/rhpit-interop-tests-master__ocp-412-quay37.yaml
  ci-operator/jobs/rhpit/interop-tests/rhpit-interop-tests-master-periodics.yaml
  core-services/testgrid-config-generator/_allow-list.yaml
Labels: lgtm, approved, rehearsals-ack

#34055 Backport E2E tests to 4.8 and 4.9
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.8__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.9__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.8-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.9-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#34457 fix zone issue for azure-ipi-workers-marketimage long-duration-cloud
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
Labels: lgtm, approved, rehearsals-ack

#34447 Add default capability set for new version
  ci-operator/step-registry/ipi/conf/manual-creds/remove-unnecessary-creds/ipi-conf-manual-creds-remove-unnecessary-creds-commands.sh
Labels: lgtm, approved, rehearsals-ack

#34485 fix ginkgo_filter for aws-c2s-ipi-disconnected-private-p3-f28-destructive
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
Labels: lgtm, approved, rehearsals-ack

#34486 Add aws-ipi-baselinecaps from QE to cluster-bot workflow-launch
  core-services/ci-chat-bot/workflows-config.yaml
Labels: lgtm, approved, rehearsals-ack

#34489 IPI cloud cases failing as cluster is UPI so correcting tag
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-stable.yaml
Labels: lgtm, approved, rehearsals-ack

#34372 refine sdn migration to ovn jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#34399 remove hypershift 4.11 hypershiftinstall test and udpate aws hypershi…
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#34480 add ovn to okd upgrade job name
  ci-operator/config/openshift/release/openshift-release-master__okd-4.13-upgrade-from-okd-4.12.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#34445 Use the same name style for AMD/ARM
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#34484 OCPQE-13009: Fix cron entries for 4.8/4.9
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.8__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.9__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.8-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.9-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#34492 Fix filter for vsphere-upi-disconnected-sdn-workers-rhcos-rhel8
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
Labels: lgtm, approved, rehearsals-ack

#34265 OKD: Remove ironic-ipa-downloader configs from 4.12+ branches
  ci-operator/config/openshift/ironic-ipa-downloader/openshift-ironic-ipa-downloader-master__okd.yaml
  ci-operator/config/openshift/ironic-ipa-downloader/openshift-ironic-ipa-downloader-release-4.12__okd.yaml
  ci-operator/config/openshift/ironic-ipa-downloader/openshift-ironic-ipa-downloader-release-4.13__okd.yaml
  ci-operator/config/openshift/ironic-ipa-downloader/openshift-ironic-ipa-downloader-release-4.14__okd.yaml
  ci-operator/jobs/openshift/ironic-ipa-downloader/openshift-ironic-ipa-downloader-master-postsubmits.yaml
  ci-operator/jobs/openshift/ironic-ipa-downloader/openshift-ironic-ipa-downloader-master-presubmits.yaml
  ci-operator/jobs/openshift/ironic-ipa-downloader/openshift-ironic-ipa-downloader-release-4.12-postsubmits.yaml
  ci-operator/jobs/openshift/ironic-ipa-downloader/openshift-ironic-ipa-downloader-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift/ironic-ipa-downloader/openshift-ironic-ipa-downloader-release-4.13-postsubmits.yaml
  ci-operator/jobs/openshift/ironic-ipa-downloader/openshift-ironic-ipa-downloader-release-4.13-presubmits.yaml
  ci-operator/jobs/openshift/ironic-ipa-downloader/openshift-ironic-ipa-downloader-release-4.14-postsubmits.yaml
  ci-operator/jobs/openshift/ironic-ipa-downloader/openshift-ironic-ipa-downloader-release-4.14-presubmits.yaml
  core-services/image-mirroring/openshift/mapping_origin_4_12
  core-services/image-mirroring/openshift/mapping_origin_4_13
  core-services/image-mirroring/openshift/mapping_origin_4_14
Labels: lgtm, approved, rehearsals-ack

#34481 add -ovn- to 4.12+ ccm presubmits
  ci-operator/config/openshift/cluster-cloud-controller-manager-operator/openshift-cluster-cloud-controller-manager-operator-master.yaml
  ci-operator/config/openshift/cluster-cloud-controller-manager-operator/openshift-cluster-cloud-controller-manager-operator-release-4.12.yaml
  ci-operator/config/openshift/cluster-cloud-controller-manager-operator/openshift-cluster-cloud-controller-manager-operator-release-4.13.yaml
  ci-operator/config/openshift/cluster-cloud-controller-manager-operator/openshift-cluster-cloud-controller-manager-operator-release-4.14.yaml
  ci-operator/jobs/openshift/cluster-cloud-controller-manager-operator/openshift-cluster-cloud-controller-manager-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-cloud-controller-manager-operator/openshift-cluster-cloud-controller-manager-operator-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift/cluster-cloud-controller-manager-operator/openshift-cluster-cloud-controller-manager-operator-release-4.13-presubmits.yaml
  ci-operator/jobs/openshift/cluster-cloud-controller-manager-operator/openshift-cluster-cloud-controller-manager-operator-release-4.14-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#34498 Support of OCPQE-13111
  ci-operator/step-registry/cucushift/e2e/cucushift-e2e-commands.sh
Labels: lgtm, approved, rehearsals-ack

#34380 openstack-operator: add pre-commit tests
  ci-operator/config/openstack-k8s-operators/openstack-operator/openstack-k8s-operators-openstack-operator-master.yaml
  ci-operator/jobs/openstack-k8s-operators/openstack-operator/openstack-k8s-operators-openstack-operator-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#34497 OCPQE-13107: use the correct auth for image mirroring for C2S/SC2S clusters
  ci-operator/step-registry/enable-qe-catalogsource/disconnected/enable-qe-catalogsource-disconnected-commands.sh
Labels: lgtm, approved, rehearsals-ack

#34476 Fix DPTP-3132 Add HyperShift on Hive credentials
  core-services/ci-secret-bootstrap/_config.yaml
  core-services/ci-secret-generator/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#34478 Remove defunct `prow-checkconfig-version.txt`
  core-services/prow/02_config/_bumper.yaml
  core-services/prow/prow-checkconfig-version.txt
Labels: lgtm, approved, rehearsals-ack

#34510 Disable user-monitoring of ns/prow-monitoring
  clusters/app.ci/prow-monitoring/prow-monitoring_ns.yaml
  clusters/app.ci/prow/03_deployment/00_namespaces.yaml
Labels: lgtm, approved, rehearsals-ack

#34482 add -ovn- to 4.12+ prometheus presubmits
  ci-operator/config/openshift/prometheus/openshift-prometheus-master.yaml
  ci-operator/config/openshift/prometheus/openshift-prometheus-release-4.12.yaml
  ci-operator/config/openshift/prometheus/openshift-prometheus-release-4.13.yaml
  ci-operator/config/openshift/prometheus/openshift-prometheus-release-4.14.yaml
  ci-operator/jobs/openshift/prometheus/openshift-prometheus-master-presubmits.yaml
  ci-operator/jobs/openshift/prometheus/openshift-prometheus-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift/prometheus/openshift-prometheus-release-4.13-presubmits.yaml
  ci-operator/jobs/openshift/prometheus/openshift-prometheus-release-4.14-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#34511 Decrease exec frequency of 4.6 periodic jobs
  ci-operator/config/ibmz-eco/isv-operator/ibmz-eco-isv-operator-openshift-4.6.yaml
  ci-operator/config/kubevirt/kubevirt/kubevirt-kubevirt-main__0.34_4.6.yaml
  ci-operator/config/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.6.yaml
  ci-operator/config/openshift-metal3/dev-scripts/openshift-metal3-dev-scripts-master__packetcheck.yaml
  ci-operator/config/openshift/insights-operator/openshift-insights-operator-release-4.6.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.6-upgrade-from-stable-4.5.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.6.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.6.yaml
  ci-operator/config/openshift/release/openshift-release-master__okd-4.6.yaml
  ci-operator/config/quay/quay-bridge-operator/quay-quay-bridge-operator-master__ocp-4.6.yaml
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__ocp-46.yaml
  ci-operator/config/redhat-openshift-ecosystem/certified-operators-preprod/redhat-openshift-ecosystem-certified-operators-preprod-ocp-4.6.yaml
  ci-operator/config/redhat-openshift-ecosystem/certified-operators-prod/redhat-openshift-ecosystem-certified-operators-prod-ocp-4.6.yaml
  ci-operator/config/redhat-openshift-ecosystem/cvp/redhat-openshift-ecosystem-cvp-ocp-4.6.yaml
  ci-operator/config/redhat-openshift-ecosystem/preflight/redhat-openshift-ecosystem-preflight-ocp-4.6.yaml
  ci-operator/config/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main__periodic-4.6.yaml
  ci-operator/jobs/ibmz-eco/isv-operator/ibmz-eco-isv-operator-openshift-4.6-periodics.yaml
  ci-operator/jobs/kubevirt/kubevirt/kubevirt-kubevirt-main-periodics.yaml
  ci-operator/jobs/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.6-periodics.yaml
  ci-operator/jobs/openshift-metal3/dev-scripts/openshift-metal3-dev-scripts-master-periodics.yaml
  ci-operator/jobs/openshift/insights-operator/openshift-insights-operator-release-4.6-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.6-periodics.yaml
  ci-operator/jobs/quay/quay-bridge-operator/quay-quay-bridge-operator-master-periodics.yaml
  ci-operator/jobs/quay/quay-tests/quay-quay-tests-master-periodics.yaml
  ci-operator/jobs/redhat-openshift-ecosystem/certified-operators-preprod/redhat-openshift-ecosystem-certified-operators-preprod-ocp-4.6-periodics.yaml
  ci-operator/jobs/redhat-openshift-ecosystem/certified-operators-prod/redhat-openshift-ecosystem-certified-operators-prod-ocp-4.6-periodics.yaml
  ci-operator/jobs/redhat-openshift-ecosystem/cvp/redhat-openshift-ecosystem-cvp-ocp-4.6-periodics.yaml
  ci-operator/jobs/redhat-openshift-ecosystem/preflight/redhat-openshift-ecosystem-preflight-ocp-4.6-periodics.yaml
  ci-operator/jobs/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#34494 [openshift-logging] Fix EO bundle channel for release-5.5
  ci-operator/config/openshift/elasticsearch-operator/openshift-elasticsearch-operator-release-5.5.yaml
Labels: lgtm, approved, rehearsals-ack

#34495 [openshift-loki] Fix operator bundle channel for release-5.5
  ci-operator/config/openshift/loki/openshift-loki-release-5.5.yaml
Labels: lgtm, approved, rehearsals-ack

#34385 remove ovn-ex-gw-e2e step from metal-ipi-ovn-ipv4
  ci-operator/step-registry/baremetalds/e2e/ovn/ipv4/baremetalds-e2e-ovn-ipv4-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#34514 Allow release admins to patch `imagestreams/status`
  clusters/app.ci/art/admin_art.yaml
  clusters/app.ci/trt/admin_rbac.yaml
Labels: lgtm, approved, rehearsals-ack

#34454 add QE dedicated azure stack cluster profile
  core-services/ci-secret-bootstrap/_config.yaml
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: lgtm, approved, rehearsals-ack

#34522 Fix priority for p1 profiles in 4.Next
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-4.13-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__multi-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#34521 Fix zone issue on azure-ipi-workers-marketimage
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-stable.yaml
Labels: lgtm, approved, rehearsals-ack

#34528 Optimize tests in 4.8/4.9
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.8__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.9__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.8-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.9-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#34529 OCPQE-13107: fix x509 certificate signed by unknown authority
  ci-operator/step-registry/enable-qe-catalogsource/disconnected/enable-qe-catalogsource-disconnected-commands.sh
Labels: lgtm, approved, rehearsals-ack

#34531 Make Zuul job required for mariadb operator
  core-services/prow/02_config/openstack-k8s-operators/mariadb-operator/_prowconfig.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#34508 USHIFT-660: MicroShift router smoke test
  ci-operator/config/openshift/microshift/openshift-microshift-main.yaml
  ci-operator/jobs/openshift/microshift/openshift-microshift-main-presubmits.yaml
  ci-operator/step-registry/openshift/microshift/e2e/router-smoke-test/OWNERS
  ci-operator/step-registry/openshift/microshift/e2e/router-smoke-test/openshift-microshift-e2e-router-smoke-test-chain.metadata.json
  ci-operator/step-registry/openshift/microshift/e2e/router-smoke-test/openshift-microshift-e2e-router-smoke-test-chain.yaml
  ci-operator/step-registry/openshift/microshift/e2e/router-smoke-test/openshift-microshift-e2e-router-smoke-test-commands.sh
  ci-operator/step-registry/openshift/microshift/e2e/router-smoke-test/openshift-microshift-e2e-router-smoke-test-ref.metadata.json
  ci-operator/step-registry/openshift/microshift/e2e/router-smoke-test/openshift-microshift-e2e-router-smoke-test-ref.yaml
  ci-operator/step-registry/openshift/microshift/e2e/router-smoke-test/openshift-microshift-e2e-router-smoke-test-workflow.metadata.json
  ci-operator/step-registry/openshift/microshift/e2e/router-smoke-test/openshift-microshift-e2e-router-smoke-test-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#34491 Add new slice for QE SD
  clusters/app.ci/prow/03_deployment/boskos_reaper.yaml
  core-services/ci-secret-bootstrap/_config.yaml
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: lgtm, approved, rehearsals-ack

#34533 Use github-check for making zuul job voting
  core-services/prow/02_config/openstack-k8s-operators/mariadb-operator/_prowconfig.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#34530 [stackrox/kernel-packer] increase job freq to every 2h
  ci-operator/config/stackrox/kernel-packer/stackrox-kernel-packer-master.yaml
  ci-operator/jobs/stackrox/kernel-packer/stackrox-kernel-packer-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#34538 Make zuul job voting by passing job name
  core-services/prow/02_config/openstack-k8s-operators/mariadb-operator/_prowconfig.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#34506 Enable NTO 4.13 nightly testing
  ci-operator/config/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-release-4.13.yaml
  ci-operator/jobs/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-release-4.13-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#34537 Update ibm-roks-toolkit image base to 8.7-923.1669829893
  clusters/app.ci/supplemental-ci-images/ibm-roks-toolkit-base/ibm-roks-toolkit-base.yaml
Labels: lgtm, approved, rehearsals-ack

#31664 alibabacloud ipi private cluster (using cluster profile 'alibabacloud-qe')
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.12.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
  ci-operator/step-registry/alibabacloud/OWNERS
  ci-operator/step-registry/alibabacloud/deprovision/OWNERS
  ci-operator/step-registry/alibabacloud/deprovision/bastionhost/OWNERS
  ci-operator/step-registry/alibabacloud/deprovision/bastionhost/alibabacloud-deprovision-bastionhost-commands.sh
  ci-operator/step-registry/alibabacloud/deprovision/bastionhost/alibabacloud-deprovision-bastionhost-ref.metadata.json
  ci-operator/step-registry/alibabacloud/deprovision/bastionhost/alibabacloud-deprovision-bastionhost-ref.yaml
  ci-operator/step-registry/alibabacloud/deprovision/vpc/OWNERS
  ci-operator/step-registry/alibabacloud/deprovision/vpc/alibabacloud-deprovision-vpc-commands.sh
  ci-operator/step-registry/alibabacloud/deprovision/vpc/alibabacloud-deprovision-vpc-ref.metadata.json
  ci-operator/step-registry/alibabacloud/deprovision/vpc/alibabacloud-deprovision-vpc-ref.yaml
  ci-operator/step-registry/alibabacloud/provision/OWNERS
  ci-operator/step-registry/alibabacloud/provision/bastionhost/OWNERS
  ci-operator/step-registry/alibabacloud/provision/bastionhost/alibabacloud-provision-bastionhost-commands.sh
  ci-operator/step-registry/alibabacloud/provision/bastionhost/alibabacloud-provision-bastionhost-ref.metadata.json
  ci-operator/step-registry/alibabacloud/provision/bastionhost/alibabacloud-provision-bastionhost-ref.yaml
  ci-operator/step-registry/alibabacloud/provision/vpc/OWNERS
  ci-operator/step-registry/alibabacloud/provision/vpc/alibabacloud-provision-vpc-commands.sh
  ci-operator/step-registry/alibabacloud/provision/vpc/alibabacloud-provision-vpc-ref.metadata.json
  ci-operator/step-registry/alibabacloud/provision/vpc/alibabacloud-provision-vpc-ref.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/alibabacloud/ipi/private/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/alibabacloud/ipi/private/cucushift-installer-rehearse-alibabacloud-ipi-private-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/alibabacloud/ipi/private/cucushift-installer-rehearse-alibabacloud-ipi-private-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/alibabacloud/ipi/private/deprovision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/alibabacloud/ipi/private/deprovision/cucushift-installer-rehearse-alibabacloud-ipi-private-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/alibabacloud/ipi/private/deprovision/cucushift-installer-rehearse-alibabacloud-ipi-private-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/alibabacloud/ipi/private/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/alibabacloud/ipi/private/provision/cucushift-installer-rehearse-alibabacloud-ipi-private-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/alibabacloud/ipi/private/provision/cucushift-installer-rehearse-alibabacloud-ipi-private-provision-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#34544 Use golang 1.19 for ibm-roks-toolkit CI
  ci-operator/config/openshift/ibm-roks-toolkit/openshift-ibm-roks-toolkit-master.yaml
  ci-operator/config/openshift/ibm-roks-toolkit/openshift-ibm-roks-toolkit-release-4.12.yaml
Labels: lgtm, approved, rehearsals-ack

#33479 osde2e: add rosa prod/stage sts e2e tests
  ci-operator/config/openshift/osde2e/openshift-osde2e-main.yaml
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#33024 Bump up MaxStartups
  ci-operator/step-registry/baremetalds/devscripts/proxy/baremetalds-devscripts-proxy-commands.sh
Labels: lgtm, approved, rehearsals-ack

#34512 hypershift: various cleanups
  ci-operator/config/openshift-priv/hypershift/openshift-priv-hypershift-main.yaml
  ci-operator/config/openshift-priv/hypershift/openshift-priv-hypershift-release-4.11.yaml
  ci-operator/config/openshift-priv/hypershift/openshift-priv-hypershift-release-4.12.yaml
  ci-operator/config/openshift-priv/hypershift/openshift-priv-hypershift-release-4.13.yaml
  ci-operator/config/openshift-priv/hypershift/openshift-priv-hypershift-release-4.14.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-main.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-main__kubevirt.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-main__periodics-4.12.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.11.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.11__periodics-4.11.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.12.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.13.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.14.yaml
  ci-operator/jobs/openshift-priv/hypershift/openshift-priv-hypershift-main-presubmits.yaml
  ci-operator/jobs/openshift-priv/hypershift/openshift-priv-hypershift-release-4.11-presubmits.yaml
  ci-operator/jobs/openshift-priv/hypershift/openshift-priv-hypershift-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift-priv/hypershift/openshift-priv-hypershift-release-4.13-presubmits.yaml
  ci-operator/jobs/openshift-priv/hypershift/openshift-priv-hypershift-release-4.14-presubmits.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-main-periodics.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-main-presubmits.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.11-periodics.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.11-presubmits.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.13-presubmits.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.14-presubmits.yaml
  ci-operator/step-registry/hypershift/aws/conformance/hypershift-aws-conformance-workflow.yaml
  ci-operator/step-registry/hypershift/aws/e2e/external/hypershift-aws-e2e-external-workflow.yaml
  ci-operator/step-registry/hypershift/aws/e2e/nested/hypershift-aws-e2e-nested-workflow.yaml
  ci-operator/step-registry/hypershift/aws/setup-nested-management-cluster/hypershift-aws-setup-nested-management-cluster-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#34524 refine ci jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.8__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.9__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.8-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.9-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#34010 Add CI config for serving 1.8
  ci-operator/config/openshift-knative/serving/openshift-knative-serving-release-v1.8__411.yaml
  ci-operator/config/openshift-knative/serving/openshift-knative-serving-release-v1.8__48.yaml
  ci-operator/config/openshift-knative/serving/openshift-knative-serving-release-v1.8__49.yaml
  ci-operator/jobs/openshift-knative/serving/openshift-knative-serving-release-v1.8-periodics.yaml
  ci-operator/jobs/openshift-knative/serving/openshift-knative-serving-release-v1.8-postsubmits.yaml
  ci-operator/jobs/openshift-knative/serving/openshift-knative-serving-release-v1.8-presubmits.yaml
  core-services/image-mirroring/knative/mapping_knative_v1_8_quay
Labels: lgtm, approved, rehearsals-ack

#34554 HyperShift: update OCP release used by nested mgmt clusters
  ci-operator/step-registry/hypershift/aws/setup-nested-management-cluster/hypershift-aws-setup-nested-management-cluster-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#34556 aws-ipi-ovn-ingress-nlb to aws-ipi-ingress-lbtype-nlb in 4.12+
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-4.13-upgrade-from-stable-4.12.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#34560 Re-add rdoproject.org/github-check contexts
  core-services/prow/02_config/openstack-k8s-operators/mariadb-operator/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#34559 OCPQE-13009: Add shell script to generate cron entries
  ci-operator/config/openshift/openshift-tests-private/tools/OWNERS
  ci-operator/config/openshift/openshift-tests-private/tools/generate-cron-entry.sh
Labels: lgtm, approved, rehearsals-ack

#34561 OCPQE-13009: Fix cron entries
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly-4.11-upgrade-from-stable-4.10-from-stable-4.9.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly-4.11-upgrade-from-stable-4.10.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__arm64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#34253 MGMT-12652: Add temporary image streams for ocm-2.8 Assisted Installer migration
  clusters/app.ci/supplemental-ci-images/assisted-ci-tools/temp-images-for-migration.yaml
Labels: lgtm, approved, rehearsals-ack

#34569 skip agent-installer job on docs changes
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#34470 Bump memory available to ipi compact jobs
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.10.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.11.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.12.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.13.yaml
  ci-operator/step-registry/baremetalds/e2e/sdn/serial/compact/baremetalds-e2e-sdn-serial-compact-workflow.yaml
  ci-operator/step-registry/baremetalds/e2e/serial/compact/baremetalds-e2e-serial-compact-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#34255 MGMT-12642: assisted-installer: Add Assisted Installer fast forwards for ocm-2.8 release
  ci-operator/jobs/infra-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#34549 [openshift-logging] Fix OO_CHANNEL values per release branch
  ci-operator/config/openshift/elasticsearch-operator/openshift-elasticsearch-operator-release-5.6.yaml
  ci-operator/config/openshift/loki/openshift-loki-release-5.6.yaml
Labels: lgtm, approved, rehearsals-ack

#34576 Fix MCE builds missing image dependencies
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__mce.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.7__mce.yaml
Labels: lgtm, approved, rehearsals-ack

#34558 Use ovn-kubernetes-base image in 4.12/4.13 upgrade/okd jobs
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master__4.13-upgrade-from-stable-4.12-local-gateway.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master__4.13-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.12__okd.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.13__okd.yaml
Labels: lgtm, approved, rehearsals-ack

#34580 MGMT-12654: fix running conditions and requireness for jobs
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.7.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.7-periodics.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.7-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#34244 hypershift agent
  ci-operator/config/openshift/hypershift/openshift-hypershift-main__periodics-4.12.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-main-periodics.yaml
  ci-operator/step-registry/hypershift/agent/OWNERS
  ci-operator/step-registry/hypershift/agent/conformance/OWNERS
  ci-operator/step-registry/hypershift/agent/conformance/hypershift-agent-conformance-workflow.metadata.json
  ci-operator/step-registry/hypershift/agent/conformance/hypershift-agent-conformance-workflow.yaml
  ci-operator/step-registry/hypershift/agent/create/OWNERS
  ci-operator/step-registry/hypershift/agent/create/add-worker/OWNERS
  ci-operator/step-registry/hypershift/agent/create/add-worker/hypershift-agent-create-add-worker-commands.sh
  ci-operator/step-registry/hypershift/agent/create/add-worker/hypershift-agent-create-add-worker-ref.metadata.json
  ci-operator/step-registry/hypershift/agent/create/add-worker/hypershift-agent-create-add-worker-ref.yaml
  ci-operator/step-registry/hypershift/agent/create/hostedcluster/OWNERS
  ci-operator/step-registry/hypershift/agent/create/hostedcluster/hypershift-agent-create-hostedcluster-commands.sh
  ci-operator/step-registry/hypershift/agent/create/hostedcluster/hypershift-agent-create-hostedcluster-ref.metadata.json
  ci-operator/step-registry/hypershift/agent/create/hostedcluster/hypershift-agent-create-hostedcluster-ref.yaml
  ci-operator/step-registry/hypershift/agent/create/hypershift-agent-create-chain.metadata.json
  ci-operator/step-registry/hypershift/agent/create/hypershift-agent-create-chain.yaml
  ci-operator/step-registry/hypershift/agent/create/proxy/OWNERS
  ci-operator/step-registry/hypershift/agent/create/proxy/hypershift-agent-create-proxy-commands.sh
  ci-operator/step-registry/hypershift/agent/create/proxy/hypershift-agent-create-proxy-ref.metadata.json
  ci-operator/step-registry/hypershift/agent/create/proxy/hypershift-agent-create-proxy-ref.yaml
  ci-operator/step-registry/hypershift/agent/destroy/OWNERS
  ci-operator/step-registry/hypershift/agent/destroy/hypershift-agent-destroy-chain.metadata.json
  ci-operator/step-registry/hypershift/agent/destroy/hypershift-agent-destroy-chain.yaml
  ci-operator/step-registry/hypershift/conformance/hypershift-conformance-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#33937 OCPVE-166 - reenable stalld for realtime config
  ci-operator/config/openshift/release/openshift-release-master__ci-4.10-upgrade-from-stable-4.9.yaml
  ci-operator/step-registry/optional-operators/configure-realtime-tuned-profile/optional-operators-configure-realtime-tuned-profile-commands.sh
  ci-operator/step-registry/optional-operators/configure-realtime-tuned-profile/optional-operators-configure-realtime-tuned-profile-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#34574 USHIFT-660: MicroShift Router smoke test - improve failure logs
  ci-operator/step-registry/openshift/microshift/e2e/router-smoke-test/openshift-microshift-e2e-router-smoke-test-commands.sh
Labels: lgtm, approved, rehearsals-ack

#34575 cincinnati*: trust dependabot to trigger tests
  core-services/prow/02_config/openshift/cincinnati-graph-data/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cincinnati/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#34589 Fix DPTP-3132 Add lease for HyperShift on Hive
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: lgtm, approved, rehearsals-ack

#34593 Add kcp-dev/catalog
  ci-operator/config/kcp-dev/catalog/OWNERS
  ci-operator/config/kcp-dev/catalog/kcp-dev-catalog-main.yaml
  ci-operator/jobs/kcp-dev/catalog/OWNERS
  ci-operator/jobs/kcp-dev/catalog/kcp-dev-catalog-main-presubmits.yaml
  core-services/prow/02_config/kcp-dev/catalog/OWNERS
  core-services/prow/02_config/kcp-dev/catalog/_pluginconfig.yaml
  core-services/prow/02_config/kcp-dev/catalog/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#34596 stolostron: update hypershift-addon-operator to use golang 1.19
  ci-operator/config/stolostron/hypershift-addon-operator/stolostron-hypershift-addon-operator-backplane-2.2.yaml
  ci-operator/config/stolostron/hypershift-addon-operator/stolostron-hypershift-addon-operator-main.yaml
Labels: lgtm, approved, rehearsals-ack

#34604 OCPQE-13163: correct the origin index image
  ci-operator/step-registry/enable-qe-catalogsource/disconnected/enable-qe-catalogsource-disconnected-commands.sh
Labels: lgtm, approved, rehearsals-ack

#34555 GCP IPI cluster with kms enabled
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.12.yaml
  ci-operator/step-registry/cucushift/installer/check/gcp/OWNERS
  ci-operator/step-registry/cucushift/installer/check/gcp/disk-encryption/OWNERS
  ci-operator/step-registry/cucushift/installer/check/gcp/disk-encryption/cucushift-installer-check-gcp-disk-encryption-commands.sh
  ci-operator/step-registry/cucushift/installer/check/gcp/disk-encryption/cucushift-installer-check-gcp-disk-encryption-ref.metadata.json
  ci-operator/step-registry/cucushift/installer/check/gcp/disk-encryption/cucushift-installer-check-gcp-disk-encryption-ref.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/disk/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/disk/encryption/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/disk/encryption/cucushift-installer-rehearse-gcp-ipi-disk-encryption-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/disk/encryption/cucushift-installer-rehearse-gcp-ipi-disk-encryption-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/disk/encryption/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/disk/encryption/provision/cucushift-installer-rehearse-gcp-ipi-disk-encryption-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/disk/encryption/provision/cucushift-installer-rehearse-gcp-ipi-disk-encryption-provision-chain.yaml
  ci-operator/step-registry/ipi/conf/gcp/osdisk/OWNERS
  ci-operator/step-registry/ipi/conf/gcp/osdisk/encryption-key/OWNERS
  ci-operator/step-registry/ipi/conf/gcp/osdisk/encryption-key/ipi-conf-gcp-osdisk-encryption-key-commands.sh
  ci-operator/step-registry/ipi/conf/gcp/osdisk/encryption-key/ipi-conf-gcp-osdisk-encryption-key-ref.metadata.json
  ci-operator/step-registry/ipi/conf/gcp/osdisk/encryption-key/ipi-conf-gcp-osdisk-encryption-key-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#34600 refine ci jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly-4.11-upgrade-from-stable-4.10.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-stable-4.11.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-4.13-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.8__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.9__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.8-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.9-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#34592 cluster-node-tuning-operator: nightly for master
  ci-operator/config/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-master.yaml
  ci-operator/jobs/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#34307 chore: update to new script name, which doesn't need CI_CHE_OPERATOR_IMAGE passed into it anymore (https://github.com/eclipse/che/issues/21836)
  ci-operator/config/eclipse-che/che-operator/eclipse-che-che-operator-main__v11.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#34585 Add pipeline for openshift/managed-notifications
  ci-operator/config/openshift/managed-notifications/OWNERS
  ci-operator/config/openshift/managed-notifications/openshift-managed-notifications-master.yaml
  ci-operator/jobs/openshift/managed-notifications/OWNERS
  ci-operator/jobs/openshift/managed-notifications/openshift-managed-notifications-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#34603 [CIGolang]change build to 413
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-master.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__images.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__images.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-master-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-presubmits.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#34466 infra-deployments: skip CI for stage-only components
  ci-operator/jobs/redhat-appstudio/infra-deployments/redhat-appstudio-infra-deployments-main-presubmits.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#34611 Takeover of 'RHODS: Update OWNERS file'
  ci-operator/config/red-hat-data-services/cuda-minimal-notebook/OWNERS
  ci-operator/config/red-hat-data-services/cuda-minimal-notebook/red-hat-data-services-cuda-minimal-notebook-main.yaml
  ci-operator/jobs/red-hat-data-services/cuda-minimal-notebook/OWNERS
  ci-operator/jobs/red-hat-data-services/cuda-minimal-notebook/red-hat-data-services-cuda-minimal-notebook-main-postsubmits.yaml
  ci-operator/jobs/red-hat-data-services/cuda-minimal-notebook/red-hat-data-services-cuda-minimal-notebook-main-presubmits.yaml
  ci-operator/step-registry/opendatahub-io/OWNERS
  ci-operator/step-registry/opendatahub-io/ci/image-mirror/opendatahub-io-ci-image-mirror-ref.metadata.json
  ci-operator/step-registry/opendatahub-io/ci/image-mirror/opendatahub-io-ci-image-mirror-workflow.metadata.json
  ci-operator/step-registry/red-hat-data-services/OWNERS
  ci-operator/step-registry/red-hat-data-services/ci/image-mirror/red-hat-data-services-ci-image-mirror-ref.metadata.json
  ci-operator/step-registry/red-hat-data-services/ci/image-mirror/red-hat-data-services-ci-image-mirror-workflow.metadata.json
  clusters/app.ci/registry-access/opendatahub-io/OWNERS
  clusters/app.ci/registry-access/red-hat-data-services/OWNERS
  core-services/prow/02_config/red-hat-data-services/cuda-minimal-notebook/OWNERS
  core-services/prow/02_config/red-hat-data-services/cuda-minimal-notebook/_pluginconfig.yaml
  core-services/prow/02_config/red-hat-data-services/cuda-minimal-notebook/_prowconfig.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#34607 update to use OCP 4.12 and quay 3.8.0
  ci-operator/config/quay/quay-tests/quay-quay-tests-master.yaml
  ci-operator/jobs/quay/quay-tests/quay-quay-tests-master-periodics.yaml
  ci-operator/jobs/quay/quay-tests/quay-quay-tests-master-postsubmits.yaml
  ci-operator/jobs/quay/quay-tests/quay-quay-tests-master-presubmits.yaml
  ci-operator/step-registry/quay-tests/deploy-quay-odf/quay-tests-deploy-quay-odf-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#34601 fix unbound variable
  ci-operator/step-registry/ipi/conf/manual-creds/remove-unnecessary-creds/ipi-conf-manual-creds-remove-unnecessary-creds-commands.sh
Labels: lgtm, approved, rehearsals-ack

#34579 ovs-operator: initial configuration for prow
  ci-operator/config/openstack-k8s-operators/ovs-operator/OWNERS
  ci-operator/config/openstack-k8s-operators/ovs-operator/openstack-k8s-operators-ovs-operator-main.yaml
  ci-operator/jobs/openstack-k8s-operators/ovs-operator/OWNERS
  ci-operator/jobs/openstack-k8s-operators/ovs-operator/openstack-k8s-operators-ovs-operator-main-presubmits.yaml
  core-services/prow/02_config/openstack-k8s-operators/ovs-operator/OWNERS
  core-services/prow/02_config/openstack-k8s-operators/ovs-operator/_pluginconfig.yaml
  core-services/prow/02_config/openstack-k8s-operators/ovs-operator/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#34231 VolSync: Build new rsync-tls mover
  ci-operator/config/backube/volsync/backube-volsync-main.yaml
  ci-operator/jobs/backube/volsync/backube-volsync-main-postsubmits.yaml
  ci-operator/jobs/backube/volsync/backube-volsync-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#34546 Fix issue DPTP-3132 Add HyperShift SA
  clusters/hive/hypershift.yaml
Labels: lgtm, approved, rehearsals-ack

#34612 nova-operator: add pre-commit tests
  ci-operator/config/openstack-k8s-operators/nova-operator/openstack-k8s-operators-nova-operator-master.yaml
  ci-operator/jobs/openstack-k8s-operators/nova-operator/openstack-k8s-operators-nova-operator-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#34384 TRT-569: Collecting cluster data for analysis
  ci-operator/step-registry/ipi/install/install/ipi-install-install-commands.sh
Labels: lgtm, approved, rehearsals-ack

#34627 Run serial 3x on CI payloads
  core-services/release-controller/_releases/release-ocp-4.12-ci.json
  core-services/release-controller/_releases/release-ocp-4.13-ci.json
Labels: lgtm, approved, rehearsals-ack

#34616 USHIFT-660: Router smoke test - add retries to reduce flakiness
  ci-operator/step-registry/openshift/microshift/e2e/router-smoke-test/openshift-microshift-e2e-router-smoke-test-commands.sh
Labels: lgtm, approved, rehearsals-ack

#34632 [CVP-3437] Increase runningCount for 4.12 clusterpool
  clusters/hive/pools/cvp/cvp-ocp-4-12-amd64-aws-eu-west-3_clusterpool.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#34563 Add job timing for 4.13 and add serial tests for powervs
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.12.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.13.yaml
  ci-operator/jobs/openshift/multiarch/openshift-multiarch-master-periodics.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#34614 nova-operator: fix functional job environment
  ci-operator/config/openstack-k8s-operators/nova-operator/openstack-k8s-operators-nova-operator-master.yaml
  ci-operator/jobs/openstack-k8s-operators/nova-operator/openstack-k8s-operators-nova-operator-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#34630 dptp-controller: git-sync args fix
  clusters/app.ci/assets/dptp-controller-manager.yaml
Labels: lgtm, approved, rehearsals-ack

#34640 `pj-rehearse`: remove defunct args
  clusters/app.ci/prow/03_deployment/pj-rehearse-plugin.yaml
Labels: lgtm, approved, rehearsals-ack

#34542 Add aws proxy install analysis job
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  ci-operator/step-registry/openshift/release/analysis/test-case-analysis/openshift-release-analysis-test-case-analysis-commands.sh
  core-services/release-controller/_releases/priv/release-ocp-4.12.json
  core-services/release-controller/_releases/priv/release-ocp-4.13.json
  core-services/release-controller/_releases/release-ocp-4.12.json
  core-services/release-controller/_releases/release-ocp-4.13.json
Labels: lgtm, approved, rehearsals-ack

#34552 Add etcd-scaling test presubmits
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.12.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.13.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.14.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.13-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.14-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#34620 chore: jvm-build-service: rename e2e jobs
  ci-operator/config/redhat-appstudio/jvm-build-service/redhat-appstudio-jvm-build-service-main.yaml
  ci-operator/jobs/redhat-appstudio/jvm-build-service/redhat-appstudio-jvm-build-service-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#34626 Add jira-related labels to allowed for o/k approvers
  core-services/prow/02_config/openshift/kubernetes/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#34635 Remove Jenkins tests from source-to-image repository
  ci-operator/jobs/openshift/source-to-image/openshift-source-to-image-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#34584 telco5g: Distribute jobs over the day to reduce cost
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.11.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.12.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.13.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#34641 TRT-720: Fixing Install analysis job does not report failures
  ci-operator/step-registry/openshift/release/analysis/test-case-analysis/openshift-release-analysis-test-case-analysis-commands.sh
Labels: lgtm, approved, rehearsals-ack

#34493 OCPBUGS-4520: Update jenkins master branch to use 4.13 base image
  ci-operator/config/openshift/jenkins/openshift-jenkins-master.yaml
  ci-operator/config/openshift/jenkins/openshift-jenkins-release-4.13.yaml
  ci-operator/step-registry/jenkins/client-plugin/tests/jenkins-client-plugin-tests-ref.yaml
  ci-operator/step-registry/jenkins/sync-plugin/e2e/jenkins-sync-plugin-e2e-ref.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, rehearsals-ack

#34643 opct: remove periodic jobs for vsphere ipi
  ci-operator/config/redhat-openshift-ecosystem/provider-certification-tool/redhat-openshift-ecosystem-provider-certification-tool-main.yaml
  ci-operator/jobs/redhat-openshift-ecosystem/provider-certification-tool/redhat-openshift-ecosystem-provider-certification-tool-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#34636 stackrox: no longer build/push docs images
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies.yaml
Labels: lgtm, approved, rehearsals-ack

#34648 stolostron: revert hypershift-addon-operator to use golang 1.18
  ci-operator/config/stolostron/hypershift-addon-operator/stolostron-hypershift-addon-operator-backplane-2.2.yaml
  ci-operator/config/stolostron/hypershift-addon-operator/stolostron-hypershift-addon-operator-main.yaml
Labels: lgtm, approved, rehearsals-ack

#34527 exclude console cucushift case for e2e-aws-ipi-baselinecaps-none job
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
Labels: lgtm, approved, rehearsals-ack

#34650 updatet-nodejs-ocp-version
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__omr.yaml
  ci-operator/jobs/quay/quay-tests/quay-quay-tests-master-periodics.yaml
  ci-operator/jobs/quay/quay-tests/quay-quay-tests-master-postsubmits.yaml
  ci-operator/jobs/quay/quay-tests/quay-quay-tests-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#34532 support to provision the hypershift rosa cluster
  ci-operator/step-registry/rosa/aws/sts/hypershift/OWNERS
  ci-operator/step-registry/rosa/aws/sts/hypershift/rosa-aws-sts-hypershift-workflow.metadata.json
  ci-operator/step-registry/rosa/aws/sts/hypershift/rosa-aws-sts-hypershift-workflow.yaml
  ci-operator/step-registry/rosa/sts/cluster/provision/rosa-sts-cluster-provision-commands.sh
  ci-operator/step-registry/rosa/sts/cluster/provision/rosa-sts-cluster-provision-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#34660 Updating boskos reaper for powervs lease
  clusters/app.ci/prow/03_deployment/boskos_reaper.yaml
Labels: lgtm, approved, rehearsals-ack

#34082 OCP Logging: added CLO tests to pre-merge tests for vector 0.21-rh
  ci-operator/config/ViaQ/vector/ViaQ-vector-v0.21-rh.yaml
  ci-operator/jobs/ViaQ/vector/ViaQ-vector-v0.21-rh-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#34654 Make ztp gather steps best-effort
  ci-operator/step-registry/assisted/baremetal/operator/gather/assisted-baremetal-operator-gather-ref.yaml
  ci-operator/step-registry/baremetalds/devscripts/gather/baremetalds-devscripts-gather-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#34545 [4.10] - Add repo names to match the RHCOS repo names
  clusters/build-clusters/common/release-controller/rpms-ocp-4.10.yaml
  core-services/release-controller/_repos/ocp-4.10-rhel8.repo
Labels: lgtm, approved, rehearsals-ack

#34662 fix code generation verification in release-4.11 branch
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-4.11__edge.yaml
Labels: lgtm, approved, rehearsals-ack

#34665 [CVP-3439] Increase size and maxSize for 4.12 clusterpool
  clusters/hive/pools/cvp/cvp-ocp-4-12-amd64-aws-eu-west-3_clusterpool.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#34668 NTO: Add Slack reporting for 4.13/4.14/master
  ci-operator/jobs/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-master-periodics.yaml
  ci-operator/jobs/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-release-4.14-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#32978 Add OVNKube SDN job for Nutanix
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.12.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.13.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.14.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.13-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.14-presubmits.yaml
  ci-operator/step-registry/ipi/nutanix/pre/ipi-nutanix-pre-chain.yaml
  ci-operator/step-registry/openshift/e2e/nutanix/ovn/OWNERS
  ci-operator/step-registry/openshift/e2e/nutanix/ovn/openshift-e2e-nutanix-ovn-workflow.metadata.json
  ci-operator/step-registry/openshift/e2e/nutanix/ovn/openshift-e2e-nutanix-ovn-workflow.yaml
  ci-operator/step-registry/openshift/e2e/nutanix/sdn/OWNERS
  ci-operator/step-registry/openshift/e2e/nutanix/sdn/openshift-e2e-nutanix-sdn-workflow.metadata.json
  ci-operator/step-registry/openshift/e2e/nutanix/sdn/openshift-e2e-nutanix-sdn-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#34438 Enable monitoring user-defined projects
  clusters/app.ci/ci-grafana/ci-grafana.yaml
  clusters/app.ci/ci-grafana/cluster-pool_grafanadashboard.yaml
  clusters/app.ci/ci-grafana/datasource_template.yaml
  clusters/app.ci/openshift-user-workload-monitoring/blackbox_probe.yaml
  clusters/app.ci/openshift-user-workload-monitoring/blackbox_prober.yaml
  clusters/app.ci/openshift-user-workload-monitoring/deck_servicemonitor.yaml
  clusters/app.ci/openshift-user-workload-monitoring/mixins/prometheus_out/alertmanager-user-workload-secret_template.yaml
  clusters/app.ci/openshift-user-workload-monitoring/mixins/prometheus_out/ci-alerts_prometheusrule.yaml
  clusters/app.ci/openshift-user-workload-monitoring/openshift-user-workload-monitoring_cm.yaml
  clusters/app.ci/openshift-user-workload-monitoring/retester_podmonitor.yaml
  clusters/app.ci/openshift-user-workload-monitoring/tide_servicemonitor.yaml
Labels: lgtm, approved, rehearsals-ack

#34657 redhat-cps/front-proxy: build image
  ci-operator/config/redhat-cps/front-proxy/redhat-cps-front-proxy-main.yaml
  ci-operator/jobs/redhat-cps/front-proxy/redhat-cps-front-proxy-main-postsubmits.yaml
  ci-operator/jobs/redhat-cps/front-proxy/redhat-cps-front-proxy-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#34661 change networking job with static-ip job from master
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-cloud_hotfix_releases.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-cloud_hotfix_releases-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#34673 UWM: set up mixins
  clusters/app.ci/ci-grafana/cluster-pool_grafanadashboard.yaml
  clusters/app.ci/openshift-user-workload-monitoring/mixins/.gitignore
  clusters/app.ci/openshift-user-workload-monitoring/mixins/Makefile
  clusters/app.ci/openshift-user-workload-monitoring/mixins/_grafana_dashboards/cluster-pool.jsonnet
  clusters/app.ci/openshift-user-workload-monitoring/mixins/_prometheus/alertmanager.jsonnet
  clusters/app.ci/openshift-user-workload-monitoring/mixins/_prometheus/alertmanager.libsonnet
  clusters/app.ci/openshift-user-workload-monitoring/mixins/_prometheus/alertmanager_default_receivers.libsonnet
  clusters/app.ci/openshift-user-workload-monitoring/mixins/_prometheus/alertmanager_routes.libsonnet
  clusters/app.ci/openshift-user-workload-monitoring/mixins/_prometheus/alertmanager_user_workload_secret.jsonnet
  clusters/app.ci/openshift-user-workload-monitoring/mixins/_prometheus/ci_absent_alerts.libsonnet
  clusters/app.ci/openshift-user-workload-monitoring/mixins/_prometheus/prometheus.libsonnet
  clusters/app.ci/openshift-user-workload-monitoring/mixins/_prometheus/prometheus_rule_prow.jsonnet
  clusters/app.ci/openshift-user-workload-monitoring/mixins/config.libsonnet
  clusters/app.ci/openshift-user-workload-monitoring/mixins/create_dashboard.sh
  clusters/app.ci/openshift-user-workload-monitoring/mixins/grafana_dashboards_out/cluster-pool_grafanadashboard.yaml
  clusters/app.ci/openshift-user-workload-monitoring/mixins/grafanadashboard.template
  clusters/app.ci/openshift-user-workload-monitoring/mixins/jsonnetfile.json
  clusters/app.ci/openshift-user-workload-monitoring/mixins/jsonnetfile.lock.json
  clusters/app.ci/openshift-user-workload-monitoring/mixins/prometheus_out/alertmanager-user-workload-secret_template.yaml
Labels: lgtm, approved, rehearsals-ack

#34671 Add Go 1.19 kcp-dev-build-root image
  clusters/app.ci/supplemental-ci-images/kcp-dev-build-root.yaml
Labels: lgtm, approved, rehearsals-ack

#34675 ocm: log sha
  ci-operator/step-registry/ocm/ci/image-mirror/ocm-ci-image-mirror-commands.sh
Labels: lgtm, approved, rehearsals-ack

#34605 OCPQE-12592: OCP regression test on HyperShift cluster on Azure
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-stable.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#34652 Fix auth issue for cluster bot
  ci-operator/step-registry/aws/c2s/init-token-service/aws-c2s-init-token-service-commands.sh
  ci-operator/step-registry/ipi/conf/alibabacloud/cloud-creds-provision/ipi-conf-alibabacloud-cloud-creds-provision-commands.sh
  ci-operator/step-registry/ipi/conf/aws/ipi-conf-aws-commands.sh
  ci-operator/step-registry/ipi/conf/aws/marketplace/ipi-conf-aws-marketplace-commands.sh
  ci-operator/step-registry/ipi/conf/aws/oidc-creds-provision/ipi-conf-aws-oidc-creds-provision-commands.sh
  ci-operator/step-registry/ipi/conf/gcp/ipi-conf-gcp-commands.sh
  ci-operator/step-registry/ipi/conf/gcp/oidc-creds-deprovision/ipi-conf-gcp-oidc-creds-deprovision-commands.sh
  ci-operator/step-registry/ipi/conf/gcp/oidc-creds-provision/ipi-conf-gcp-oidc-creds-provision-commands.sh
  ci-operator/step-registry/ipi/conf/network/mtu/ipi-conf-network-mtu-commands.sh
  ci-operator/step-registry/ipi/conf/tang/ipi-conf-tang-commands.sh
  ci-operator/step-registry/vsphere/provision/haproxy/vsphere-provision-haproxy-commands.sh
Labels: lgtm, approved, rehearsals-ack

#34679 fix: increase timeout for long running test
  ci-operator/config/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-master.yaml
Labels: lgtm, approved, rehearsals-ack

#34683 [CIGolang]correct golint
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-master.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14.yaml
Labels: lgtm, approved, rehearsals-ack

#34422 [Baremetal/QE] Adding firewall config step
  ci-operator/step-registry/baremetal/lab/post/firewall/baremetal-lab-post-firewall-commands.sh
  ci-operator/step-registry/baremetal/lab/post/firewall/baremetal-lab-post-firewall-ref.yaml
  ci-operator/step-registry/baremetal/lab/pre/firewall/baremetal-lab-pre-firewall-commands.sh
  ci-operator/step-registry/baremetal/lab/pre/firewall/baremetal-lab-pre-firewall-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#34421 [Baremetal/QE] Adding dns config step
  ci-operator/step-registry/baremetal/lab/post/dns/baremetal-lab-post-dns-commands.sh
  ci-operator/step-registry/baremetal/lab/post/dns/baremetal-lab-post-dns-ref.yaml
  ci-operator/step-registry/baremetal/lab/pre/dns/baremetal-lab-pre-dns-commands.sh
  ci-operator/step-registry/baremetal/lab/pre/dns/baremetal-lab-pre-dns-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#34689 Update `git-sync` image version
  clusters/app.ci/assets/dptp-controller-manager.yaml
  clusters/app.ci/ci-operator-configresolver/ci-operator-configresolver.yaml
  clusters/app.ci/prow/03_deployment/sinker.yaml
Labels: lgtm, approved, rehearsals-ack

#34686 Update _pluginconfig.yaml
  core-services/prow/02_config/red-hat-storage/_pluginconfig.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack
