Repository openshift/release, pull requests merged in 2022-04, with the labels that each got.

#22260 [QE][AWS] Add support for installing private cluster
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
  ci-operator/step-registry/aws/OWNERS
  ci-operator/step-registry/aws/deprovision/OWNERS
  ci-operator/step-registry/aws/deprovision/bastionhost/OWNERS
  ci-operator/step-registry/aws/deprovision/bastionhost/aws-deprovision-bastionhost-commands.sh
  ci-operator/step-registry/aws/deprovision/bastionhost/aws-deprovision-bastionhost-ref.metadata.json
  ci-operator/step-registry/aws/deprovision/bastionhost/aws-deprovision-bastionhost-ref.yaml
  ci-operator/step-registry/aws/deprovision/vpc/OWNERS
  ci-operator/step-registry/aws/deprovision/vpc/aws-deprovision-vpc-commands.sh
  ci-operator/step-registry/aws/deprovision/vpc/aws-deprovision-vpc-ref.metadata.json
  ci-operator/step-registry/aws/deprovision/vpc/aws-deprovision-vpc-ref.yaml
  ci-operator/step-registry/aws/provision/OWNERS
  ci-operator/step-registry/aws/provision/bastionhost/OWNERS
  ci-operator/step-registry/aws/provision/bastionhost/aws-provision-bastionhost-commands.sh
  ci-operator/step-registry/aws/provision/bastionhost/aws-provision-bastionhost-ref.metadata.json
  ci-operator/step-registry/aws/provision/bastionhost/aws-provision-bastionhost-ref.yaml
  ci-operator/step-registry/aws/provision/vpc/OWNERS
  ci-operator/step-registry/aws/provision/vpc/shared/OWNERS
  ci-operator/step-registry/aws/provision/vpc/shared/aws-provision-vpc-shared-commands.sh
  ci-operator/step-registry/aws/provision/vpc/shared/aws-provision-vpc-shared-ref.metadata.json
  ci-operator/step-registry/aws/provision/vpc/shared/aws-provision-vpc-shared-ref.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/private/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/private/cucushift-installer-rehearse-aws-ipi-private-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/private/cucushift-installer-rehearse-aws-ipi-private-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/private/deprovision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/private/deprovision/cucushift-installer-rehearse-aws-ipi-private-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/private/deprovision/cucushift-installer-rehearse-aws-ipi-private-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/private/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/private/provision/cucushift-installer-rehearse-aws-ipi-private-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/private/provision/cucushift-installer-rehearse-aws-ipi-private-provision-chain.yaml
  ci-operator/step-registry/gather/aws-console/gather-aws-console-commands.sh
  ci-operator/step-registry/ipi/conf/aws/ipi-conf-aws-commands.sh
  ci-operator/step-registry/ipi/conf/aws/privatecluster/OWNERS
  ci-operator/step-registry/ipi/conf/aws/privatecluster/ipi-conf-aws-privatecluster-commands.sh
  ci-operator/step-registry/ipi/conf/aws/privatecluster/ipi-conf-aws-privatecluster-ref.metadata.json
  ci-operator/step-registry/ipi/conf/aws/privatecluster/ipi-conf-aws-privatecluster-ref.yaml
  ci-operator/step-registry/ipi/install/install/ipi-install-install-commands.sh
  ci-operator/step-registry/proxy/config-generate/OWNERS
  ci-operator/step-registry/proxy/config-generate/proxy-config-generate-commands.sh
  ci-operator/step-registry/proxy/config-generate/proxy-config-generate-ref.metadata.json
  ci-operator/step-registry/proxy/config-generate/proxy-config-generate-ref.yaml
Labels: lgtm, approved

#27480 set HOME to tmp
  ci-operator/config/stolostron/clusterlifecycle-state-metrics/stolostron-clusterlifecycle-state-metrics-backplane-2.0.yaml
  ci-operator/config/stolostron/clusterlifecycle-state-metrics/stolostron-clusterlifecycle-state-metrics-main.yaml
Labels: lgtm, approved

#27163 Use cluster profile from QE
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__nightly-4.11.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
Labels: lgtm, approved

#27471 Add secret for OpenShift CI app authorization
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved

#27456 Execute e2e tests on release-1.1+ of kn-event
  ci-operator/config/openshift-knative/kn-plugin-event/openshift-knative-kn-plugin-event-release-1.1.yaml
  ci-operator/config/openshift-knative/kn-plugin-event/openshift-knative-kn-plugin-event-release-1.2.yaml
  ci-operator/config/openshift-knative/kn-plugin-event/openshift-knative-kn-plugin-event-release-next.yaml
  ci-operator/jobs/openshift-knative/kn-plugin-event/openshift-knative-kn-plugin-event-release-1.1-presubmits.yaml
  ci-operator/jobs/openshift-knative/kn-plugin-event/openshift-knative-kn-plugin-event-release-1.2-presubmits.yaml
  ci-operator/jobs/openshift-knative/kn-plugin-event/openshift-knative-kn-plugin-event-release-next-presubmits.yaml
Labels: lgtm, approved

#27385 Installer: Relax upgrade tests on master
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
  ci-operator/config/openshift/installer/openshift-installer-master__okd.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.1.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.10.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.10__okd.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.11.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.11__okd.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.12.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.2.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.3.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.4.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.5.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.6.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.7.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.8.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.9.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.9__okd.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.1-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.10-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.11-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.8-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.9-presubmits.yaml
Labels: lgtm, approved

#27298 adds e2e-aws-serial job to cluster-etcd-operator repo
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-master.yaml
  ci-operator/jobs/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-master-presubmits.yaml
Labels: lgtm, approved

#27380 cluster-api-provider-openstack: main unit-test
  ci-operator/config/openshift/cluster-api-provider-openstack/openshift-cluster-api-provider-openstack-main.yaml
  ci-operator/jobs/openshift/cluster-api-provider-openstack/openshift-cluster-api-provider-openstack-main-presubmits.yaml
Labels: lgtm, approved

#27487 elasticsearch-operator: Update to Go 1.17 in master
  ci-operator/config/openshift/elasticsearch-operator/openshift-elasticsearch-operator-master.yaml
Labels: lgtm, approved

#27349 hco: generate components graph on nightly tests
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-main.yaml
Labels: lgtm, approved

#27420 Add "images" job for cluster-control-plane-machine-set-operator
  ci-operator/config/openshift/cluster-control-plane-machine-set-operator/openshift-cluster-control-plane-machine-set-operator-main.yaml
  ci-operator/jobs/openshift/cluster-control-plane-machine-set-operator/openshift-cluster-control-plane-machine-set-operator-main-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-control-plane-machine-set-operator/openshift-cluster-control-plane-machine-set-operator-main-presubmits.yaml
  core-services/image-mirroring/openshift/mapping_origin_4_11
Labels: lgtm, approved

#27431 Hypershift aws conformance: Use the nested setup rather than the pool
  ci-operator/config/openshift/hypershift/openshift-hypershift-main__periodics.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.11__periodics.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-main-periodics.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.11-periodics.yaml
  ci-operator/step-registry/hypershift/aws/conformance/hypershift-aws-conformance-workflow.yaml
  ci-operator/step-registry/hypershift/aws/destroy-nested-management-cluster/OWNERS
  ci-operator/step-registry/hypershift/aws/destroy-nested-management-cluster/hypershift-aws-destroy-nested-management-cluster-chain.metadata.json
  ci-operator/step-registry/hypershift/aws/destroy-nested-management-cluster/hypershift-aws-destroy-nested-management-cluster-chain.yaml
  ci-operator/step-registry/hypershift/aws/setup-nested-management-cluster/OWNERS
  ci-operator/step-registry/hypershift/aws/setup-nested-management-cluster/hypershift-aws-setup-nested-management-cluster-chain.metadata.json
  ci-operator/step-registry/hypershift/aws/setup-nested-management-cluster/hypershift-aws-setup-nested-management-cluster-chain.yaml
Labels: lgtm, approved

#27486 Removing CRW addon-codeready-operator for staging addon verification
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: lgtm, approved

#27493 hco: fix graphs output folder in the nightly job
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-main.yaml
Labels: lgtm, approved

#27498 Run core metal-ipi jobs every 6h instead of 48h.
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.11.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: lgtm, approved

#27495 Pod Scaler Producer: increase memory limit
  clusters/app.ci/pod-scaler/pod-scaler.yaml
Labels: lgtm, approved

#27245 loki: Remove existing release branches and opt-out of branching
  ci-operator/config/openshift/loki/openshift-loki-main.yaml
  ci-operator/config/openshift/loki/openshift-loki-release-4.10.yaml
  ci-operator/config/openshift/loki/openshift-loki-release-4.11.yaml
  ci-operator/config/openshift/loki/openshift-loki-release-4.12.yaml
  ci-operator/config/openshift/loki/openshift-loki-release-4.2.yaml
  ci-operator/config/openshift/loki/openshift-loki-release-4.3.yaml
  ci-operator/config/openshift/loki/openshift-loki-release-4.4.yaml
  ci-operator/config/openshift/loki/openshift-loki-release-4.5.yaml
  ci-operator/config/openshift/loki/openshift-loki-release-4.6.yaml
  ci-operator/config/openshift/loki/openshift-loki-release-4.7.yaml
  ci-operator/config/openshift/loki/openshift-loki-release-4.8.yaml
  ci-operator/config/openshift/loki/openshift-loki-release-4.9.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-main-presubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-release-4.10-postsubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-release-4.10-presubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-release-4.11-postsubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-release-4.11-presubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-release-4.12-postsubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-release-4.2-postsubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-release-4.2-presubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-release-4.3-postsubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-release-4.3-presubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-release-4.4-postsubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-release-4.5-postsubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-release-4.6-postsubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-release-4.7-postsubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-release-4.8-postsubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-release-4.8-presubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-release-4.9-postsubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-release-4.9-presubmits.yaml
  core-services/image-mirroring/openshift/mapping_origin_4_10
  core-services/image-mirroring/openshift/mapping_origin_4_11
  core-services/image-mirroring/openshift/mapping_origin_4_2
  core-services/image-mirroring/openshift/mapping_origin_4_4
  core-services/image-mirroring/openshift/mapping_origin_4_5
  core-services/image-mirroring/openshift/mapping_origin_4_6
  core-services/image-mirroring/openshift/mapping_origin_4_7
  core-services/image-mirroring/openshift/mapping_origin_4_8
  core-services/image-mirroring/openshift/mapping_origin_4_9
Labels: lgtm, approved

#27463 Remove metal from blocking jobs
  core-services/release-controller/_releases/priv/release-ocp-4.11.json
  core-services/release-controller/_releases/release-ocp-4.11.json
Labels: lgtm, approved

#27503 Hypershift conformance: Use tests image from release imagestream
  ci-operator/step-registry/hypershift/conformance/hypershift-conformance-chain.yaml
Labels: lgtm, approved

#27519 Add resumeTimeout of 15 mins for MSP cluster pools
  clusters/hive/pools/msp/msp-ocp-4-10-medium-single-az-amd64-aws-us-east-1_clusterpool.yaml
  clusters/hive/pools/msp/msp-ocp-4-10-small-single-az-amd64-aws-us-east-2_clusterpool.yaml
  clusters/hive/pools/msp/msp-ocp-4-8-medium-single-az-amd64-aws-us-east-1_clusterpool.yaml
  clusters/hive/pools/msp/msp-ocp-4-8-small-single-az-amd64-aws-us-east-2_clusterpool.yaml
  clusters/hive/pools/msp/msp-ocp-4-9-medium-single-az-amd64-aws-us-east-1_clusterpool.yaml
  clusters/hive/pools/msp/msp-ocp-4-9-small-single-az-amd64-aws-us-east-2_clusterpool.yaml
Labels: lgtm, approved

#27446 UPI cluster on GCP (using 'gcp-qe' cluster profile)
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/upi/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/upi/cucushift-installer-rehearse-gcp-upi-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/upi/cucushift-installer-rehearse-gcp-upi-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/upi/deprovision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/upi/deprovision/cucushift-installer-rehearse-gcp-upi-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/upi/deprovision/cucushift-installer-rehearse-gcp-upi-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/upi/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/upi/provision/cucushift-installer-rehearse-gcp-upi-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/upi/provision/cucushift-installer-rehearse-gcp-upi-provision-chain.yaml
Labels: lgtm, approved

#27257 MGMT-9743: Remove 4.6-e2e-metal-assisted from release controller
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.6.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  core-services/release-controller/_releases/priv/release-ocp-4.6.json
  core-services/release-controller/_releases/release-ocp-4.6.json
Labels: lgtm, approved

#27003 Added rebase bot configuration for powervs cloud provider
  ci-operator/config/openshift-eng/rebasebot/openshift-eng-rebasebot-main.yaml
  ci-operator/jobs/openshift-eng/rebasebot/openshift-eng-rebasebot-main-periodics.yaml
Labels: lgtm, approved

#27075 Include Kuryr upgrade jobs
  ci-operator/config/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main__periodic-4.10-upgrade-from-stable-4.9.yaml
  ci-operator/config/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main__periodic-4.11-upgrade-from-stable-4.10.yaml
  ci-operator/jobs/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main-periodics.yaml
  ci-operator/step-registry/ipi/conf/openstack/enable-octavia/ipi-conf-openstack-enable-octavia-commands.sh
  ci-operator/step-registry/ipi/conf/openstack/enable-octavia/ipi-conf-openstack-enable-octavia-ref.yaml
Labels: lgtm, approved

#27521 Move ci-tools jobs to b01 as canaries
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
  ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-periodics.yaml
  ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
  ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
  ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-shift-week-better-retester-postsubmits.yaml
  ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-shift-week-better-retester-presubmits.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: lgtm, approved

#27523 Add mirror image for Serving 1.2.0
  core-services/image-mirroring/knative/mapping_knative_v1_2_quay
Labels: lgtm, approved

#27469 Bug 2066232: e2e-aws-workers-rhel8 nigtly to use rhel 8.4 in 4.10
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.10.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.11.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#27425 Skip e2e testing if only markdown files have been modified
  ci-operator/config/redhat-appstudio/infra-deployments/redhat-appstudio-infra-deployments-main.yaml
  ci-operator/jobs/redhat-appstudio/infra-deployments/redhat-appstudio-infra-deployments-main-presubmits.yaml
Labels: lgtm, approved, ok-to-test

#27532 Cluster readers on build01/2
  clusters/build-clusters/common_except_app.ci/admin_cluster-reader-0_list.yaml
  core-services/sync-rover-groups/_config.yaml
Labels: lgtm, approved

#27535 Move metal jobs to optional based on TRT guidance
  core-services/release-controller/_releases/priv/release-ocp-4.10.json
  core-services/release-controller/_releases/priv/release-ocp-4.7.json
  core-services/release-controller/_releases/priv/release-ocp-4.8.json
  core-services/release-controller/_releases/priv/release-ocp-4.9.json
  core-services/release-controller/_releases/release-ocp-4.10.json
  core-services/release-controller/_releases/release-ocp-4.7.json
  core-services/release-controller/_releases/release-ocp-4.8.json
  core-services/release-controller/_releases/release-ocp-4.9.json
Labels: lgtm, approved

#27541 osp-director-operator: bump master to golang-1.17
  ci-operator/config/openstack-k8s-operators/osp-director-operator/openstack-k8s-operators-osp-director-operator-master.yaml
Labels: lgtm, approved

#27545 Remove periodic jobs eventing 0.24
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.24__47.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.24__48.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.24-periodics.yaml
Labels: lgtm, approved

#27410 Adding a disconnected build job for SRO.
  ci-operator/config/openshift/special-resource-operator/openshift-special-resource-operator-master.yaml
  ci-operator/jobs/openshift/special-resource-operator/openshift-special-resource-operator-master-presubmits.yaml
Labels: lgtm, approved

#27539 ci-operator: Introduce a periodic prowjob for running OLM's e2e suite
  ci-operator/config/openshift/operator-framework-olm/openshift-operator-framework-olm-master.yaml
  ci-operator/jobs/openshift/operator-framework-olm/openshift-operator-framework-olm-master-periodics.yaml
  ci-operator/jobs/openshift/operator-framework-olm/openshift-operator-framework-olm-master-presubmits.yaml
Labels: lgtm, approved

#27205 Added e2e test config for aws-load-balancer-operator
  ci-operator/config/openshift/aws-load-balancer-operator/openshift-aws-load-balancer-operator-main.yaml
  ci-operator/jobs/openshift/aws-load-balancer-operator/openshift-aws-load-balancer-operator-main-presubmits.yaml
  ci-operator/step-registry/aws-load-balancer/OWNERS
  ci-operator/step-registry/aws-load-balancer/install/OWNERS
  ci-operator/step-registry/aws-load-balancer/install/aws-load-balancer-install-workflow.metadata.json
  ci-operator/step-registry/aws-load-balancer/install/aws-load-balancer-install-workflow.yaml
  ci-operator/step-registry/aws-load-balancer/pre-install/OWNERS
  ci-operator/step-registry/aws-load-balancer/pre-install/aws-load-balancer-pre-install-commands.sh
  ci-operator/step-registry/aws-load-balancer/pre-install/aws-load-balancer-pre-install-ref.metadata.json
  ci-operator/step-registry/aws-load-balancer/pre-install/aws-load-balancer-pre-install-ref.yaml
Labels: lgtm, approved

#27546 Prepare openshift-serverless-v1.21.1 release
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.21__4.6.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.21__4.7.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.21__4.8.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.21__4.9.yaml
Labels: lgtm, approved

#27551 assisted-service: Don't always run e2e dual-stack job
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
Labels: lgtm, approved

#27552 MGMT-9759: Remove 2.5 redundent jobs for assisted
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.5.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.5.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.5.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.5-presubmits.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.5-presubmits.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.5-periodics.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.5-presubmits.yaml
Labels: lgtm, approved

#27553 MGMT-9896: Remove ocp 4.8 from OCM 2.5 jobs
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.5.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.5-periodics.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.5-presubmits.yaml
Labels: lgtm, approved

#27558 Add image to cluster-group-upgrades-operator
  ci-operator/config/openshift-kni/cluster-group-upgrades-operator/openshift-kni-cluster-group-upgrades-operator-main.yaml
Labels: lgtm, approved

#27430 Azure Disk CSI migration is GA in OCP 4.11
  ci-operator/config/openshift/azure-disk-csi-driver-operator/openshift-azure-disk-csi-driver-operator-master.yaml
  ci-operator/config/openshift/azure-disk-csi-driver-operator/openshift-azure-disk-csi-driver-operator-release-4.11.yaml
  ci-operator/config/openshift/azure-disk-csi-driver-operator/openshift-azure-disk-csi-driver-operator-release-4.12.yaml
  ci-operator/config/openshift/azure-disk-csi-driver/openshift-azure-disk-csi-driver-master.yaml
  ci-operator/config/openshift/azure-disk-csi-driver/openshift-azure-disk-csi-driver-release-4.11.yaml
  ci-operator/config/openshift/azure-disk-csi-driver/openshift-azure-disk-csi-driver-release-4.12.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.11.yaml
  ci-operator/jobs/openshift/azure-disk-csi-driver-operator/openshift-azure-disk-csi-driver-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/azure-disk-csi-driver-operator/openshift-azure-disk-csi-driver-operator-release-4.11-presubmits.yaml
  ci-operator/jobs/openshift/azure-disk-csi-driver-operator/openshift-azure-disk-csi-driver-operator-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift/azure-disk-csi-driver/openshift-azure-disk-csi-driver-master-presubmits.yaml
  ci-operator/jobs/openshift/azure-disk-csi-driver/openshift-azure-disk-csi-driver-release-4.11-presubmits.yaml
  ci-operator/jobs/openshift/azure-disk-csi-driver/openshift-azure-disk-csi-driver-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: lgtm, approved

#27556 Promote aws-load-balancer-controller image
  ci-operator/config/openshift/aws-load-balancer-controller/openshift-aws-load-balancer-controller-main.yaml
  ci-operator/jobs/openshift/aws-load-balancer-controller/openshift-aws-load-balancer-controller-main-postsubmits.yaml
Labels: lgtm, approved

#27559 Toolkit base image bump to 8.5-240.1648458092
  clusters/app.ci/supplemental-ci-images/ibm-roks-toolkit-base/ibm-roks-toolkit-base.yaml
Labels: lgtm, approved

#27560 Change E2E test to use ACM 2.5 instead of 2.4
  ci-operator/config/identitatem/idp-mgmt-operator/identitatem-idp-mgmt-operator-main.yaml
Labels: lgtm, approved

#27563 disable rhcos promotion to keep 8.5 until 8.6 might work
  ci-operator/jobs/openshift/release/openshift-release-release-4.11-periodics.yaml
Labels: lgtm, approved, tide/merge-method-squash

#27516 Remove sugar controller since it was merged
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next__47.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next__48.yaml
Labels: lgtm, approved

#27540 Configuring flags for operator-sdk repo
  core-services/prow/02_config/openshift/ocp-release-operator-sdk/_pluginconfig.yaml
Labels: lgtm, approved

#27568 Add image to cluster-group-upgrades-operator
  core-services/image-mirroring/openshift-kni/mapping_openshift-kni_quay
Labels: lgtm, approved

#27570 Make Nikos the default upstream testgrid PR assignee
  ci-operator/jobs/infra-periodics.yaml
Labels: lgtm, approved

#27573 Hypershift: Report 4.11 conformance results in slack
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.11-periodics.yaml
Labels: lgtm, approved

#27576 Add missing secret for openstack-hwoffload cluster profile
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved

#27575 ipi-deprovision image: centos:stream8
  clusters/app.ci/ipi-deprovision/ipi-deprovision-bc.yaml
Labels: lgtm, approved

#27578 Bumping all tools up to 4.11
  clusters/app.ci/release-controller/deploy-ocp-arm64-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-arm64-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-multi-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-multi-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-ppc64le-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-ppc64le-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-s390x-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-s390x-priv-controller.yaml
  hack/generators/release-controllers/content/osd_rc_deployments.py
Labels: lgtm, approved

#27579 Hypershfit conformance: Re-use workflow
  ci-operator/config/openshift/hypershift/openshift-hypershift-main.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-main__periodics.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.11__periodics.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-main-periodics.yaml
  ci-operator/step-registry/hypershift/conformance/hypershift-conformance-chain.yaml
  ci-operator/step-registry/hypershift/dump/hypershift-dump-chain.yaml
Labels: lgtm, approved

#27441 Adjust cucushift E2E_RUN_TAGS in jobs
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__nightly-4.11.yaml
Labels: lgtm, approved

#27514 Adding lint and test for ocm-agent
  ci-operator/config/openshift/ocm-agent/openshift-ocm-agent-master.yaml
  ci-operator/jobs/openshift/ocm-agent/openshift-ocm-agent-master-presubmits.yaml
Labels: lgtm, approved

#27577 Assisted installer: Only publish MCE 2.0 pipeline
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-main.yaml
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.5.yaml
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.5__mce.yaml
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.5__stolostron.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.5.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.5__mce.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.5__stolostron.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-master.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.5.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.5__mce.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.5__stolostron.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.5.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.5__mce.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.5__stolostron.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-main-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.5-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.5-presubmits.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.5-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.5-presubmits.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-master-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.5-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.5-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.5-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.5-presubmits.yaml
Labels: lgtm, approved

#27484 Add several jobs from QE to testgrid
  core-services/testgrid-config-generator/_allow-list.yaml
Labels: lgtm, approved

#27595 odf: z stream update
  core-services/prow/02_config/red-hat-storage/_pluginconfig.yaml
Labels: lgtm, approved

#27598 Promote albc image to ocp stream
  ci-operator/config/openshift/aws-load-balancer-controller/openshift-aws-load-balancer-controller-main.yaml
  ci-operator/jobs/openshift/aws-load-balancer-controller/openshift-aws-load-balancer-controller-main-postsubmits.yaml
Labels: lgtm, approved

#27600 MGMT-9908: Remove ocp 4.8 tests from master jobs
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-periodics.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
Labels: lgtm, approved

#27601 Enable better retester on openshift/ci-tools
  ci-operator/jobs/infra-periodics.yaml
  clusters/app.ci/prow/03_deployment/better-retester.yaml
Labels: lgtm, approved

#27049 [OCPNODE-883] promote e2e-aws-crun to required
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-master.yaml
  ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-master-presubmits.yaml
Labels: lgtm, approved

#27569 Add devfile integration tests with OCP 4.11
  ci-operator/config/devfile/integration-tests/devfile-integration-tests-main__v4.11.console.yaml
  ci-operator/config/devfile/integration-tests/devfile-integration-tests-main__v4.11.odo.yaml
  ci-operator/jobs/devfile/integration-tests/devfile-integration-tests-main-periodics.yaml
  ci-operator/jobs/devfile/integration-tests/devfile-integration-tests-main-postsubmits.yaml
  ci-operator/jobs/devfile/integration-tests/devfile-integration-tests-main-presubmits.yaml
Labels: lgtm, approved

#27611 Really enable better retester on o/ci-tools
  clusters/app.ci/prow/03_deployment/better-retester.yaml
Labels: lgtm, approved

#27614 Switching over to openshift-private-release-admins group
  clusters/app.ci/release-controller/admin_deploy-ocp-arm64-priv-controller.yaml
  clusters/app.ci/release-controller/admin_deploy-ocp-multi-priv-controller.yaml
  clusters/app.ci/release-controller/admin_deploy-ocp-ppc64le-priv-controller.yaml
  clusters/app.ci/release-controller/admin_deploy-ocp-priv-controller.yaml
  clusters/app.ci/release-controller/admin_deploy-ocp-s390x-priv-controller.yaml
  clusters/app.ci/release-controller/serviceaccount.yaml
  core-services/sync-rover-groups/_config.yaml
  hack/generators/release-controllers/content/art_namespaces_rbac.py
  hack/generators/release-controllers/content/osd_rc_rbac.py
Labels: lgtm, approved

#27528 openstack: switch openstack-az job to proxy
  ci-operator/config/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main__periodic-4.10.yaml
  ci-operator/config/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main__periodic-4.11.yaml
  ci-operator/config/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main__periodic-4.9.yaml
Labels: lgtm, approved

#27615 Really really enable better retester on o/ci-tools
  clusters/app.ci/prow/03_deployment/better-retester.yaml
Labels: lgtm, approved

#27254 Enable supply chain for 4.9..4.11
  ci-operator/config/openshift/jenkins/openshift-jenkins-master.yaml
  ci-operator/config/openshift/jenkins/openshift-jenkins-release-4.10.yaml
  ci-operator/config/openshift/jenkins/openshift-jenkins-release-4.11.yaml
  ci-operator/config/openshift/jenkins/openshift-jenkins-release-4.12.yaml
  ci-operator/config/openshift/jenkins/openshift-jenkins-release-4.9.yaml
  ci-operator/jobs/openshift/jenkins/openshift-jenkins-release-4.10-presubmits.yaml
  ci-operator/jobs/openshift/jenkins/openshift-jenkins-release-4.9-presubmits.yaml
Labels: lgtm, approved

#27290 feat: add optional aws single-node upgrade test
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
Labels: lgtm, approved

#27581 Update go version of runtime-utils ci config
  ci-operator/config/openshift/runtime-utils/openshift-runtime-utils-master.yaml
  ci-operator/config/openshift/runtime-utils/openshift-runtime-utils-release-4.11.yaml
  ci-operator/config/openshift/runtime-utils/openshift-runtime-utils-release-4.12.yaml
Labels: lgtm, approved

#27609 core-services/prow/02_config/openshift/cluster-etcd-operator: Add Ge Liu for cherry-pick-approved
  core-services/prow/02_config/openshift/cluster-etcd-operator/_pluginconfig.yaml
Labels: lgtm, approved

#27616 Added ROSAnOVN jobs
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: lgtm, approved

#27613 Add eventing-kafka-broker periodics and post-install image for 1.2
  ci-operator/config/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.2__49.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.2-periodics.yaml
Labels: lgtm, approved

#27618 ci-operator/config/openshift/release: Move GCP to build02
  ci-operator/config/openshift/release/openshift-release-master__ci-4.10-upgrade-from-stable-4.9.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.10.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.11-upgrade-from-stable-4.10.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.11.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.9-upgrade-from-stable-4.8.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.9.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: lgtm, approved

#27619 ostree/rpm-ostree: Use `skip_if_only_changed`
  ci-operator/jobs/coreos/rpm-ostree/coreos-rpm-ostree-main-presubmits.yaml
  ci-operator/jobs/ostreedev/ostree/ostreedev-ostree-main-presubmits.yaml
Labels: lgtm, approved

#27602 tidy up shared info for bastion
  ci-operator/step-registry/aws/provision/bastionhost/aws-provision-bastionhost-commands.sh
  ci-operator/step-registry/azure/provision/bastionhost/azure-provision-bastionhost-commands.sh
  ci-operator/step-registry/azure/provision/bastionhost/azure-provision-bastionhost-ref.yaml
  ci-operator/step-registry/gcp/provision/bastionhost/gcp-provision-bastionhost-commands.sh
  ci-operator/step-registry/gcp/provision/bastionhost/gcp-provision-bastionhost-ref.yaml
  ci-operator/step-registry/ipi/conf/azure/proxy/ipi-conf-azure-proxy-commands.sh
  ci-operator/step-registry/proxy/config-generate/proxy-config-generate-commands.sh
  ci-operator/step-registry/proxy/config/OWNERS
  ci-operator/step-registry/proxy/config/generate/OWNERS
  ci-operator/step-registry/proxy/config/generate/proxy-config-generate-commands.sh
  ci-operator/step-registry/proxy/config/generate/proxy-config-generate-ref.metadata.json
  ci-operator/step-registry/proxy/config/generate/proxy-config-generate-ref.yaml
Labels: lgtm, approved

#27587 Add Xia-Zhao-rh from QE to list.
  core-services/prow/02_config/openshift/ocp-release-operator-sdk/_pluginconfig.yaml
Labels: lgtm, approved

#27625 Adjust cucushift e2e default skip tags
  ci-operator/step-registry/cucushift/e2e/cucushift-e2e-ref.yaml
Labels: lgtm, approved

#25547 Add kubernets-nmstate OVN ipv4 e2e CI jobs
  ci-operator/config/openshift/kubernetes-nmstate/openshift-kubernetes-nmstate-master.yaml
  ci-operator/jobs/openshift/kubernetes-nmstate/openshift-kubernetes-nmstate-master-periodics.yaml
  ci-operator/jobs/openshift/kubernetes-nmstate/openshift-kubernetes-nmstate-master-presubmits.yaml
  ci-operator/step-registry/kubernetes-nmstate/e2e/handler/kubernetes-nmstate-e2e-handler-commands.sh
  ci-operator/step-registry/kubernetes-nmstate/e2e/operator/kubernetes-nmstate-e2e-operator-commands.sh
Labels: lgtm, approved

#27629 launch bastion in similar manner to azure
  ci-operator/step-registry/gcp/provision/bastionhost/gcp-provision-bastionhost-commands.sh
  ci-operator/step-registry/gcp/provision/bastionhost/gcp-provision-bastionhost-ref.yaml
Labels: lgtm, approved

#27596 Update EUS cucushift test case selection
  ci-operator/step-registry/cucushift/upgrade/paused/intermediate/sanity/cucushift-upgrade-paused-intermediate-sanity-ref.yaml
  ci-operator/step-registry/cucushift/upgrade/paused/latest/sanity/cucushift-upgrade-paused-latest-sanity-ref.yaml
Labels: lgtm, approved

#27571 Setup CI for Serverless 1.22
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.22.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.22__4.10.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.22__4.6.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.22-postsubmits.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.22-presubmits.yaml
Labels: lgtm, approved

#27637 Remove myself from various OWNERS files
  OWNERS_ALIASES
  ci-operator/step-registry/optional-operators/OWNERS
  ci-operator/step-registry/optional-operators/configure-proxy-registry/optional-operators-configure-proxy-registry-ref.metadata.json
  ci-operator/step-registry/optional-operators/cvp-common/OWNERS
  ci-operator/step-registry/optional-operators/cvp-common/apply-secrets/optional-operators-cvp-common-apply-secrets-ref.metadata.json
  ci-operator/step-registry/optional-operators/cvp-common/aws/optional-operators-cvp-common-aws-workflow.metadata.json
  ci-operator/step-registry/optional-operators/cvp-common/ibmz-eco/OWNERS
  ci-operator/step-registry/optional-operators/cvp-common/ibmz-eco/optional-operators-cvp-common-ibmz-eco-workflow.metadata.json
  ci-operator/step-registry/optional-operators/cvp-common/powervs/OWNERS
  ci-operator/step-registry/optional-operators/cvp-common/powervs/optional-operators-cvp-common-powervs-workflow.metadata.json
  ci-operator/step-registry/optional-operators/cvp-common/scorecard/optional-operators-cvp-common-scorecard-ref.metadata.json
  ci-operator/step-registry/optional-operators/cvp-common/test/optional-operators-cvp-common-test-ref.metadata.json
  ci-operator/step-registry/optional-operators/subscribe/optional-operators-subscribe-ref.metadata.json
  core-services/prow/02_config/_config.yaml
  core-services/template-deprecation/OWNERS
Labels: lgtm, approved

#27636 release-ocm-2.4 assisted-service postsubmit should publish to ocm-2.4 tag on quay
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.4.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.4-postsubmits.yaml
Labels: lgtm, approved

#27640 cluster-api-provider-openstack: optional unit test
  ci-operator/config/openshift/cluster-api-provider-openstack/openshift-cluster-api-provider-openstack-main.yaml
  ci-operator/jobs/openshift/cluster-api-provider-openstack/openshift-cluster-api-provider-openstack-main-presubmits.yaml
Labels: lgtm, approved

#27638 Use Go 1.18 as the build_root
  ci-operator/config/openshift-psap/special-resource-operator/openshift-psap-special-resource-operator-master.yaml
Labels: lgtm, approved

#27606 Move cluster-api-provider-agent to Go 1.17
  ci-operator/config/openshift/cluster-api-provider-agent/openshift-cluster-api-provider-agent-master.yaml
Labels: lgtm, approved

#27648 Build assisted-service-publish-index image also on 2.4
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.4.yaml
Labels: lgtm, approved

#27647 MGMT-9928 - Remove redundant jobs from release-ocm-2.4 branches
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.4.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.4-periodics.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.4-presubmits.yaml
Labels: lgtm, approved

#24710 [OVN-K] Add upgrade jobs for LGW
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master__4.11-upgrade-from-stable-4.10-local-gateway.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master-presubmits.yaml
Labels: lgtm, approved

#27650 Remove eventing-kafka periodics for unsupported 0.24
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.24__47.yaml
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.24__48.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.24-periodics.yaml
Labels: lgtm, approved

#27652 nro: fix values for substitution
  ci-operator/config/openshift-kni/numaresources-operator/openshift-kni-numaresources-operator-main.yaml
  ci-operator/config/openshift-kni/numaresources-operator/openshift-kni-numaresources-operator-release-4.10.yaml
Labels: lgtm, approved

#27623 Hypershift conformance: Stop taring again
  ci-operator/step-registry/hypershift/dump/hypershift-dump-chain.yaml
Labels: lgtm, approved

#27588 Adding CI for new branch in NMO (Medik8s)
  ci-operator/config/medik8s/node-maintenance-operator/medik8s-node-maintenance-operator-main.yaml
  ci-operator/jobs/medik8s/node-maintenance-operator/medik8s-node-maintenance-operator-main-presubmits.yaml
Labels: lgtm, approved

#27542 adding workflow support for powervs
  OWNERS_ALIASES
  ci-operator/step-registry/gather/powervs/OWNERS
  ci-operator/step-registry/gather/powervs/gather-powervs-chain.metadata.json
  ci-operator/step-registry/gather/powervs/gather-powervs-chain.yaml
  ci-operator/step-registry/ipi/conf/powervs/OWNERS
  ci-operator/step-registry/ipi/conf/powervs/ipi-conf-powervs-chain.metadata.json
  ci-operator/step-registry/ipi/conf/powervs/ipi-conf-powervs-chain.yaml
  ci-operator/step-registry/ipi/conf/powervs/ipi-conf-powervs-commands.sh
  ci-operator/step-registry/ipi/conf/powervs/ipi-conf-powervs-ref.metadata.json
  ci-operator/step-registry/ipi/conf/powervs/ipi-conf-powervs-ref.yaml
  ci-operator/step-registry/ipi/conf/powervs/manual-creds/OWNERS
  ci-operator/step-registry/ipi/conf/powervs/manual-creds/ipi-conf-powervs-manual-creds-commands.sh
  ci-operator/step-registry/ipi/conf/powervs/manual-creds/ipi-conf-powervs-manual-creds-ref.metadata.json
  ci-operator/step-registry/ipi/conf/powervs/manual-creds/ipi-conf-powervs-manual-creds-ref.yaml
  ci-operator/step-registry/ipi/deprovision/deprovision/powervs/OWNERS
  ci-operator/step-registry/ipi/deprovision/deprovision/powervs/deprovision/OWNERS
  ci-operator/step-registry/ipi/deprovision/deprovision/powervs/deprovision/ipi-deprovision-deprovision-powervs-deprovision-commands.sh
  ci-operator/step-registry/ipi/deprovision/deprovision/powervs/deprovision/ipi-deprovision-deprovision-powervs-deprovision-ref.metadata.json
  ci-operator/step-registry/ipi/deprovision/deprovision/powervs/deprovision/ipi-deprovision-deprovision-powervs-deprovision-ref.yaml
  ci-operator/step-registry/ipi/deprovision/deprovision/powervs/ipi-deprovision-deprovision-powervs-chain.metadata.json
  ci-operator/step-registry/ipi/deprovision/deprovision/powervs/ipi-deprovision-deprovision-powervs-chain.yaml
  ci-operator/step-registry/ipi/install/powervs/OWNERS
  ci-operator/step-registry/ipi/install/powervs/install/OWNERS
  ci-operator/step-registry/ipi/install/powervs/install/ipi-install-powervs-install-commands.sh
  ci-operator/step-registry/ipi/install/powervs/install/ipi-install-powervs-install-ref.metadata.json
  ci-operator/step-registry/ipi/install/powervs/install/ipi-install-powervs-install-ref.yaml
  ci-operator/step-registry/ipi/install/powervs/ipi-install-powervs-chain.metadata.json
  ci-operator/step-registry/ipi/install/powervs/ipi-install-powervs-chain.yaml
  ci-operator/step-registry/ipi/powervs/OWNERS
  ci-operator/step-registry/ipi/powervs/gather-resources/OWNERS
  ci-operator/step-registry/ipi/powervs/gather-resources/ipi-powervs-gather-resources-commands.sh
  ci-operator/step-registry/ipi/powervs/gather-resources/ipi-powervs-gather-resources-ref.metadata.json
  ci-operator/step-registry/ipi/powervs/gather-resources/ipi-powervs-gather-resources-ref.yaml
  ci-operator/step-registry/ipi/powervs/ipi-powervs-workflow.metadata.json
  ci-operator/step-registry/ipi/powervs/ipi-powervs-workflow.yaml
  ci-operator/step-registry/ipi/powervs/post/OWNERS
  ci-operator/step-registry/ipi/powervs/post/ipi-powervs-post-chain.metadata.json
  ci-operator/step-registry/ipi/powervs/post/ipi-powervs-post-chain.yaml
  ci-operator/step-registry/ipi/powervs/pre/OWNERS
  ci-operator/step-registry/ipi/powervs/pre/ipi-powervs-pre-chain.metadata.json
  ci-operator/step-registry/ipi/powervs/pre/ipi-powervs-pre-chain.yaml
  ci-operator/step-registry/openshift/e2e/powervs/ipi/OWNERS
  ci-operator/step-registry/openshift/e2e/powervs/ipi/openshift-e2e-powervs-ipi-workflow.metadata.json
  ci-operator/step-registry/openshift/e2e/powervs/ipi/openshift-e2e-powervs-ipi-workflow.yaml
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: lgtm, approved

#27524 Include more periodic upgrade job for Kuryr
  ci-operator/config/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main__periodic-4.8-upgrade-from-stable-4.7.yaml
  ci-operator/config/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main__periodic-4.9-upgrade-from-stable-4.8.yaml
  ci-operator/jobs/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main-periodics.yaml
Labels: lgtm, approved

#27660 Bump eventing core to 1.2.1
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v1.2__47.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v1.2__48.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v1.2__49.yaml
  core-services/image-mirroring/knative/mapping_knative_v1_2_quay
Labels: lgtm, approved

#27662 use different pipeline stage for 2.5
  ci-operator/config/identitatem/idp-mgmt-operator/identitatem-idp-mgmt-operator-main.yaml
Labels: lgtm, approved

#27665 remove the ghproxy redis deployment
  clusters/app.ci/prow/03_deployment/ghproxy-redis.yaml
Labels: lgtm, approved

#27631 Enable tests in redhat-appstudio/e2e-tests
  ci-operator/config/redhat-appstudio/e2e-tests/OWNERS
  ci-operator/config/redhat-appstudio/e2e-tests/redhat-appstudio-e2e-tests-main.yaml
  ci-operator/jobs/redhat-appstudio/e2e-tests/OWNERS
  ci-operator/jobs/redhat-appstudio/e2e-tests/redhat-appstudio-e2e-tests-main-presubmits.yaml
  core-services/prow/02_config/redhat-appstudio/e2e-tests/_pluginconfig.yaml
  core-services/prow/02_config/redhat-appstudio/e2e-tests/_prowconfig.yaml
Labels: lgtm, approved

#27661 Add a failover.sh script to make failovers easier
  hack/failover.sh
Labels: lgtm, approved

#27666 chore: updates sanity test on oc-mirror branches to use task defined …
  ci-operator/config/openshift/oc-mirror/openshift-oc-mirror-main.yaml
  ci-operator/config/openshift/oc-mirror/openshift-oc-mirror-release-4.11.yaml
  ci-operator/config/openshift/oc-mirror/openshift-oc-mirror-release-4.12.yaml
Labels: lgtm, approved

#27251 Add WICD unit test job
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-master.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.11.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.12.yaml
  ci-operator/jobs/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.11-presubmits.yaml
  ci-operator/jobs/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.12-presubmits.yaml
  ci-operator/step-registry/upi/vsphere/windows/post/upi-vsphere-windows-post-commands.sh
  ci-operator/step-registry/upi/vsphere/windows/pre/upi-vsphere-windows-pre-commands.sh
  ci-operator/step-registry/windows/unit/OWNERS
  ci-operator/step-registry/windows/unit/wicd/OWNERS
  ci-operator/step-registry/windows/unit/wicd/windows-unit-wicd-commands.sh
  ci-operator/step-registry/windows/unit/wicd/windows-unit-wicd-ref.metadata.json
  ci-operator/step-registry/windows/unit/wicd/windows-unit-wicd-ref.yaml
Labels: lgtm, approved

#27522 Run CI for 1.2.0 serving, net-istio and net-kourier release
  ci-operator/config/openshift-knative/net-istio/openshift-knative-net-istio-release-1.2.yaml
  ci-operator/config/openshift-knative/net-kourier/openshift-knative-net-kourier-release-1.2.yaml
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-v1.2.0__4.10.yaml
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-v1.2.0__4.6.yaml
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-v1.2.0__4.7.yaml
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-v1.2.0__4.8.yaml
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-v1.2.0__4.9.yaml
  ci-operator/jobs/openshift-knative/net-istio/openshift-knative-net-istio-release-1.2-postsubmits.yaml
  ci-operator/jobs/openshift-knative/net-istio/openshift-knative-net-istio-release-1.2-presubmits.yaml
  ci-operator/jobs/openshift-knative/net-kourier/openshift-knative-net-kourier-release-1.2-postsubmits.yaml
  ci-operator/jobs/openshift-knative/net-kourier/openshift-knative-net-kourier-release-1.2-presubmits.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-v1.2.0-postsubmits.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-v1.2.0-presubmits.yaml
Labels: lgtm, approved

#27628 [azure] enable mirror registry on bastion host
  ci-operator/step-registry/azure/deprovision/resourcegroup/azure-deprovision-resourcegroup-commands.sh
  ci-operator/step-registry/azure/provision/bastionhost/azure-provision-bastionhost-commands.sh
  ci-operator/step-registry/azure/provision/bastionhost/azure-provision-bastionhost-ref.yaml
Labels: lgtm, approved

#27676 Custom shm-size to support console test
  ci-operator/step-registry/cucushift/e2e/cucushift-e2e-ref.yaml
Labels: lgtm, approved

#27680 Move redhat-appstudio/e2e-tests jobs to GCP
  ci-operator/config/redhat-appstudio/e2e-tests/redhat-appstudio-e2e-tests-main.yaml
  ci-operator/jobs/redhat-appstudio/e2e-tests/redhat-appstudio-e2e-tests-main-presubmits.yaml
Labels: lgtm, approved

#27670 Add Nutanix quota slices
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: lgtm, approved

#27641 Adding golang.18 image.
  clusters/app.ci/supplemental-ci-images/origin-stable/release.yaml
  clusters/build-clusters/01_cluster/ci/_origin-release-build/golang-1.18/Dockerfile
  clusters/build-clusters/01_cluster/ci/_origin-release-build/golang-1.18/cbs-paas7-openshift-multiarch-el7-build.repo
  clusters/build-clusters/01_cluster/ci/_origin-release-build/golang-1.18/golang.spec
Labels: lgtm, approved

#27687 exclude rehearsals from the high-ci-operator-infra-error-rate alert
  clusters/app.ci/prow-monitoring/mixins/_prometheus/dptp_alerts.libsonnet
  clusters/app.ci/prow-monitoring/mixins/prometheus_out/prometheus-prow-rules_prometheusrule.yaml
Labels: lgtm, approved

#27626 Fix failing tests on 4.9 and 4.8.
  ci-operator/config/openshift/ocp-release-operator-sdk/openshift-ocp-release-operator-sdk-release-4.8.yaml
  ci-operator/config/openshift/ocp-release-operator-sdk/openshift-ocp-release-operator-sdk-release-4.9.yaml
Labels: lgtm, approved

#27667 vsphere: save broken rhcos guest if install fails
  ci-operator/step-registry/ipi/deprovision/vsphere/diags/ipi-deprovision-vsphere-diags-commands.sh
Labels: lgtm, approved

#27699 Revert "Gather console logs in azure-cli step"
  ci-operator/step-registry/gather/azure-cli/gather-azure-cli-commands.sh
Labels: lgtm, approved

#27610 Add pre and post submit jobs for eventing-kafka-broker 1.3
  ci-operator/config/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.3__49.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.3-postsubmits.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.3-presubmits.yaml
Labels: lgtm, approved

#27580 feat: add crane and crane-runner
  ci-operator/config/konveyor/crane-runner/OWNERS
  ci-operator/config/konveyor/crane-runner/konveyor-crane-runner-main.yaml
  ci-operator/config/konveyor/crane/OWNERS
  ci-operator/config/konveyor/crane/konveyor-crane-main.yaml
  ci-operator/jobs/konveyor/crane-runner/OWNERS
  ci-operator/jobs/konveyor/crane-runner/konveyor-crane-runner-main-postsubmits.yaml
  ci-operator/jobs/konveyor/crane-runner/konveyor-crane-runner-main-presubmits.yaml
  ci-operator/jobs/konveyor/crane/OWNERS
  ci-operator/jobs/konveyor/crane/konveyor-crane-main-postsubmits.yaml
  ci-operator/jobs/konveyor/crane/konveyor-crane-main-presubmits.yaml
  core-services/prow/02_config/konveyor/crane-runner/_pluginconfig.yaml
  core-services/prow/02_config/konveyor/crane-runner/_prowconfig.yaml
  core-services/prow/02_config/konveyor/crane/_pluginconfig.yaml
  core-services/prow/02_config/konveyor/crane/_prowconfig.yaml
Labels: lgtm, approved

#27536 Add mtRHO Operator
  ci-operator/config/konveyor/mtrho-operator/OWNERS
  ci-operator/config/konveyor/mtrho-operator/konveyor-mtrho-operator-main.yaml
  ci-operator/jobs/konveyor/mtrho-operator/OWNERS
  ci-operator/jobs/konveyor/mtrho-operator/konveyor-mtrho-operator-main-postsubmits.yaml
  ci-operator/jobs/konveyor/mtrho-operator/konveyor-mtrho-operator-main-presubmits.yaml
  core-services/prow/02_config/konveyor/mtrho-operator/OWNERS
  core-services/prow/02_config/konveyor/mtrho-operator/_pluginconfig.yaml
  core-services/prow/02_config/konveyor/mtrho-operator/_prowconfig.yaml
Labels: lgtm, approved

#27669 feat: add crane-secret-service to prow
  ci-operator/config/konveyor/crane-secret-service/OWNERS
  ci-operator/config/konveyor/crane-secret-service/konveyor-crane-secret-service-main.yaml
  ci-operator/jobs/konveyor/crane-secret-service/OWNERS
  ci-operator/jobs/konveyor/crane-secret-service/konveyor-crane-secret-service-main-postsubmits.yaml
  ci-operator/jobs/konveyor/crane-secret-service/konveyor-crane-secret-service-main-presubmits.yaml
  core-services/prow/02_config/konveyor/crane-secret-service/_pluginconfig.yaml
  core-services/prow/02_config/konveyor/crane-secret-service/_prowconfig.yaml
Labels: lgtm, approved

#27702 chore: carry manual modifications to 4.11/4.12 configs
  ci-operator/jobs/openshift/insights-operator/openshift-insights-operator-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-provider-openstack/openshift-machine-api-provider-openstack-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift/oc-mirror/openshift-oc-mirror-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift/special-resource-operator/openshift-special-resource-operator-release-4.12-periodics.yaml
  ci-operator/jobs/openshift/sriov-network-operator/openshift-sriov-network-operator-release-4.12-presubmits.yaml
Labels: lgtm, approved

#27696 sync-rover-groups: run if config changes
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
Labels: lgtm, approved

#27704 Gather console logs in azure-cli step
  ci-operator/step-registry/gather/azure-cli/gather-azure-cli-commands.sh
Labels: lgtm, approved

#25832 OKD: remove verification jobs for 4.6/4.7
  core-services/release-controller/_releases/release-okd-4.6.json
  core-services/release-controller/_releases/release-okd-4.7.json
Labels: lgtm, approved, lifecycle/stale

#27694 openstack: remove BYON (replaced by proxy)
  ci-operator/step-registry/openshift/e2e/openstack/byon/OWNERS
  ci-operator/step-registry/openshift/e2e/openstack/byon/openshift-e2e-openstack-byon-workflow.metadata.json
  ci-operator/step-registry/openshift/e2e/openstack/byon/openshift-e2e-openstack-byon-workflow.yaml
  ci-operator/step-registry/openstack/conf/creatednsrecords/openstack-conf-creatednsrecords-ref.yaml
  ci-operator/step-registry/openstack/conf/createfips/openstack-conf-createfips-commands.sh
  ci-operator/step-registry/openstack/conf/createfips/openstack-conf-createfips-ref.yaml
  ci-operator/step-registry/openstack/conf/generateconfig/openstack-conf-generateconfig-commands.sh
  ci-operator/step-registry/openstack/conf/generateconfig/openstack-conf-generateconfig-ref.yaml
  ci-operator/step-registry/openstack/deprovision/bastionproxy/openstack-deprovision-bastionproxy-commands.sh
  ci-operator/step-registry/openstack/deprovision/bastionproxy/openstack-deprovision-bastionproxy-ref.yaml
  ci-operator/step-registry/openstack/deprovision/machinesubnet/openstack-deprovision-machinesubnet-commands.sh
  ci-operator/step-registry/openstack/deprovision/machinesubnet/openstack-deprovision-machinesubnet-ref.yaml
  ci-operator/step-registry/openstack/provision/bastionproxy/openstack-provision-bastionproxy-commands.sh
  ci-operator/step-registry/openstack/provision/bastionproxy/openstack-provision-bastionproxy-ref.yaml
  ci-operator/step-registry/openstack/provision/machinesubnet/openstack-provision-machinesubnet-commands.sh
  ci-operator/step-registry/openstack/provision/machinesubnet/openstack-provision-machinesubnet-ref.yaml
Labels: lgtm, approved

#27709 NO-ISSUE - assisted-installer: test-infra Add odf job presubmit and periodic jobs
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-periodics.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-presubmits.yaml
Labels: lgtm, approved

#27565 Use .ci-operator.yaml config from repository (dpu-network-operator)
  ci-operator/config/openshift/dpu-network-operator/openshift-dpu-network-operator-master.yaml
  ci-operator/jobs/openshift/dpu-network-operator/openshift-dpu-network-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/dpu-network-operator/openshift-dpu-network-operator-master-presubmits.yaml
Labels: lgtm, approved

#27284 Add e2e tests for azure-ipi-proxy 4.11
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__nightly-4.11.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
Labels: lgtm, approved

#27713 Adjust test selection for aws-ipi
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__nightly-4.11.yaml
Labels: lgtm, approved

#27716 Image mirroring for eventing-kafka-broker 1.2
  core-services/image-mirroring/knative/mapping_knative_v1_2_quay
Labels: lgtm, approved

#27646 assisted events scrape: add integration test
  ci-operator/config/openshift-assisted/assisted-events-scrape/openshift-assisted-assisted-events-scrape-master.yaml
  ci-operator/jobs/openshift-assisted/assisted-events-scrape/openshift-assisted-assisted-events-scrape-master-presubmits.yaml
Labels: lgtm, approved

#27342 Add ci-ppc test to NTO as part of PAO migration
  ci-operator/config/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-master.yaml
  ci-operator/config/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-release-4.11.yaml
  ci-operator/config/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-release-4.12.yaml
  ci-operator/jobs/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-release-4.11-presubmits.yaml
  ci-operator/jobs/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-release-4.12-presubmits.yaml
Labels: lgtm, approved, ok-to-test

#27632 make other-ci's mandatory
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/redhat-developer/odo/_prowconfig.yaml
Labels: lgtm, approved

#27690 Onboard rh-ecosystem-edge/nvidia-ci repository
  ci-operator/config/rh-ecosystem-edge/nvidia-ci/OWNERS
  ci-operator/config/rh-ecosystem-edge/nvidia-ci/rh-ecosystem-edge-nvidia-ci-main.yaml
  ci-operator/jobs/rh-ecosystem-edge/nvidia-ci/OWNERS
  ci-operator/jobs/rh-ecosystem-edge/nvidia-ci/rh-ecosystem-edge-nvidia-ci-main-presubmits.yaml
  core-services/prow/02_config/rh-ecosystem-edge/nvidia-ci/_pluginconfig.yaml
  core-services/prow/02_config/rh-ecosystem-edge/nvidia-ci/_prowconfig.yaml
Labels: lgtm, approved

#27714 Adjust test selection for aws-ipi-proxy
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__nightly-4.11.yaml
Labels: lgtm, approved

#27718 Add 3 jobs from QE to testgrid
  core-services/testgrid-config-generator/_allow-list.yaml
Labels: lgtm, approved

#27426 Added marmijo to OWNERS_ALIASES
  OWNERS_ALIASES
Labels: lgtm, approved

#27703 move 4.11 jobs to less used ephemeral cluster accounts
  ci-operator/config/openshift/release/openshift-release-master__ci-4.11-upgrade-from-stable-4.10.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.11.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.11-upgrade-from-stable-4.9.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.11.yaml
  ci-operator/config/openshift/release/openshift-release-master__okd-4.11-upgrade-from-okd-4.10.yaml
  ci-operator/config/openshift/release/openshift-release-master__okd-4.11.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: lgtm, approved

#27691 Use golang image from Azure Disk CSI driver repo
  ci-operator/config/openshift/azure-disk-csi-driver/openshift-azure-disk-csi-driver-master.yaml
  ci-operator/config/openshift/azure-disk-csi-driver/openshift-azure-disk-csi-driver-release-4.11.yaml
  ci-operator/config/openshift/azure-disk-csi-driver/openshift-azure-disk-csi-driver-release-4.12.yaml
  ci-operator/jobs/openshift/azure-disk-csi-driver/openshift-azure-disk-csi-driver-master-postsubmits.yaml
  ci-operator/jobs/openshift/azure-disk-csi-driver/openshift-azure-disk-csi-driver-master-presubmits.yaml
  ci-operator/jobs/openshift/azure-disk-csi-driver/openshift-azure-disk-csi-driver-release-4.11-postsubmits.yaml
  ci-operator/jobs/openshift/azure-disk-csi-driver/openshift-azure-disk-csi-driver-release-4.11-presubmits.yaml
  ci-operator/jobs/openshift/azure-disk-csi-driver/openshift-azure-disk-csi-driver-release-4.12-postsubmits.yaml
  ci-operator/jobs/openshift/azure-disk-csi-driver/openshift-azure-disk-csi-driver-release-4.12-presubmits.yaml
Labels: lgtm, approved

#27534 Remove TechPreviewNoUpgrade from Azure FILE CSI workflow
  ci-operator/config/openshift/azure-file-csi-driver-operator/openshift-azure-file-csi-driver-operator-release-4.10.yaml
  ci-operator/config/openshift/azure-file-csi-driver/openshift-azure-file-csi-driver-release-4.10.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.10.yaml
  ci-operator/step-registry/openshift/e2e/azure/csi/file/nfs/openshift-e2e-azure-csi-file-nfs-workflow.yaml
  ci-operator/step-registry/openshift/e2e/azure/csi/file/openshift-e2e-azure-csi-file-workflow.yaml
Labels: lgtm, approved

#27727 Add no-FF labels for ExternalDNS
  core-services/prow/02_config/openshift/external-dns-operator/_prowconfig.yaml
  core-services/prow/02_config/openshift/external-dns/_prowconfig.yaml
Labels: lgtm, approved

#27705 OCP Logging: Replace nodejs-10 base image for kibana with ubi8
  ci-operator/config/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-master.yaml
Labels: lgtm, approved

#27214 Add images needed to build node-observability-operator and node-obser…
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_ocp
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_openshift
Labels: lgtm, approved

#27436 add auto-assign config to QE for cherry-pick-approved to storage operators
  core-services/prow/02_config/openshift/alibaba-cloud-csi-driver/_pluginconfig.yaml
  core-services/prow/02_config/openshift/alibaba-disk-csi-driver-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/aws-ebs-csi-driver-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/aws-ebs-csi-driver/_pluginconfig.yaml
  core-services/prow/02_config/openshift/aws-efs-csi-driver-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/aws-efs-csi-driver/_pluginconfig.yaml
  core-services/prow/02_config/openshift/aws-efs-utils/_pluginconfig.yaml
  core-services/prow/02_config/openshift/azure-disk-csi-driver-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/azure-disk-csi-driver/_pluginconfig.yaml
  core-services/prow/02_config/openshift/azure-file-csi-driver-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/azure-file-csi-driver/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-csi-snapshot-controller-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/csi-cluster-driver-registrar/_pluginconfig.yaml
  core-services/prow/02_config/openshift/csi-driver-registrar/_pluginconfig.yaml
  core-services/prow/02_config/openshift/csi-external-attacher/_pluginconfig.yaml
  core-services/prow/02_config/openshift/csi-external-provisioner/_pluginconfig.yaml
  core-services/prow/02_config/openshift/csi-external-resizer/_pluginconfig.yaml
  core-services/prow/02_config/openshift/csi-external-snapshotter/_pluginconfig.yaml
  core-services/prow/02_config/openshift/csi-livenessprobe/_pluginconfig.yaml
  core-services/prow/02_config/openshift/csi-node-driver-registrar/_pluginconfig.yaml
  core-services/prow/02_config/openshift/gcp-pd-csi-driver-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/gcp-pd-csi-driver/_pluginconfig.yaml
  core-services/prow/02_config/openshift/ibm-vpc-block-csi-driver-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/ibm-vpc-block-csi-driver/_pluginconfig.yaml
  core-services/prow/02_config/openshift/local-storage-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/sig-storage-local-static-provisioner/_pluginconfig.yaml
  core-services/prow/02_config/openshift/vmware-vsphere-csi-driver-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/vmware-vsphere-csi-driver/_pluginconfig.yaml
  core-services/prow/02_config/openshift/vsphere-problem-detector/_pluginconfig.yaml
Labels: lgtm, approved

#27732 Create cluster pool: rhecoedge-nvidia-ci-aws
  clusters/hive/pools/rhecoedge-nvidia-ci/OWNERS
  clusters/hive/pools/rhecoedge-nvidia-ci/admins_rhecoedge-nvidia-ci-cluster-pool_rbac.yaml
  clusters/hive/pools/rhecoedge-nvidia-ci/rhecoedge-nvidia-ci-aws-cluster-pool.yaml
  clusters/hive/pools/rhecoedge-nvidia-ci/rhecoedge-nvidia-ci-aws-install-config.yaml
Labels: lgtm, approved

#27698 OADP: Add jobs for branch oadp-1.0
  ci-operator/config/openshift/oadp-operator/openshift-oadp-operator-oadp-1.0__4.9.yaml
  ci-operator/jobs/openshift/oadp-operator/openshift-oadp-operator-oadp-1.0-periodics.yaml
  ci-operator/jobs/openshift/oadp-operator/openshift-oadp-operator-oadp-1.0-postsubmits.yaml
  ci-operator/jobs/openshift/oadp-operator/openshift-oadp-operator-oadp-1.0-presubmits.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: lgtm, approved, tide/merge-method-squash

#27052 OADP: Add presubmit jobs for Azure
  ci-operator/config/openshift/oadp-operator/openshift-oadp-operator-master__4.7.yaml
  ci-operator/config/openshift/oadp-operator/openshift-oadp-operator-master__4.8.yaml
  ci-operator/config/openshift/oadp-operator/openshift-oadp-operator-master__4.9.yaml
  ci-operator/jobs/openshift/oadp-operator/openshift-oadp-operator-master-presubmits.yaml
Labels: lgtm, approved, tide/merge-method-squash

#26791 Add OSDE2E job for addon: ocs-consumer
  ci-operator/config/openshift/osde2e/openshift-osde2e-main.yaml
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: lgtm, approved, ok-to-test

#27739 ensure owners need to manually approve
  core-services/prow/02_config/konveyor/pelorus/_pluginconfig.yaml
Labels: lgtm, approved

#27564 hypershift: move to 4.11 on main
  ci-operator/config/openshift/hypershift/openshift-hypershift-main.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-main__periodics.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.10__periodics.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-main-periodics.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-main-presubmits.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.10-periodics.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.10-presubmits.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.11-presubmits.yaml
Labels: lgtm, approved

#27664 remove github IDP from vsphere build cluster
  ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  clusters/build-clusters/vsphere/assets/admin_cluster_oauth_template.yaml
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved

#27743 feat: mirror images for konveyor
  ci-operator/jobs/infra-image-mirroring.yaml
  clusters/app.ci/registry-access/konveyor/OWNERS
  clusters/app.ci/registry-access/konveyor/admin_manifest.yaml
  core-services/image-mirroring/konveyor/OWNERS
  core-services/image-mirroring/konveyor/mapping_konveyor_latest
Labels: lgtm, approved
