Repository openshift/release, pull requests merged in 2022-09, with the labels that each got.

#31863 Remove rocky 8.5 pin
  ci-operator/step-registry/baremetalds/devscripts/proxy/baremetalds-devscripts-proxy-commands.sh
Labels: lgtm, approved

#31841 add workflow vsphere-upi-disconnected-sdn-workers-rhcos-rhel8
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.12.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/disconnected/sdn/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/disconnected/sdn/cucushift-installer-rehearse-vsphere-upi-disconnected-sdn-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/disconnected/sdn/cucushift-installer-rehearse-vsphere-upi-disconnected-sdn-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/disconnected/sdn/deprovision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/disconnected/sdn/deprovision/cucushift-installer-rehearse-vsphere-upi-disconnected-sdn-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/disconnected/sdn/deprovision/cucushift-installer-rehearse-vsphere-upi-disconnected-sdn-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/disconnected/sdn/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/disconnected/sdn/provision/cucushift-installer-rehearse-vsphere-upi-disconnected-sdn-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/disconnected/sdn/provision/cucushift-installer-rehearse-vsphere-upi-disconnected-sdn-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/disconnected/sdn/workers-rhcos-rhel8/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/disconnected/sdn/workers-rhcos-rhel8/cucushift-installer-rehearse-vsphere-upi-disconnected-sdn-workers-rhcos-rhel8-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/disconnected/sdn/workers-rhcos-rhel8/cucushift-installer-rehearse-vsphere-upi-disconnected-sdn-workers-rhcos-rhel8-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/disconnected/sdn/workers-rhcos-rhel8/deprovision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/disconnected/sdn/workers-rhcos-rhel8/deprovision/cucushift-installer-rehearse-vsphere-upi-disconnected-sdn-workers-rhcos-rhel8-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/disconnected/sdn/workers-rhcos-rhel8/deprovision/cucushift-installer-rehearse-vsphere-upi-disconnected-sdn-workers-rhcos-rhel8-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/disconnected/sdn/workers-rhcos-rhel8/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/disconnected/sdn/workers-rhcos-rhel8/provision/cucushift-installer-rehearse-vsphere-upi-disconnected-sdn-workers-rhcos-rhel8-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/disconnected/sdn/workers-rhcos-rhel8/provision/cucushift-installer-rehearse-vsphere-upi-disconnected-sdn-workers-rhcos-rhel8-provision-chain.yaml
Labels: lgtm, approved

#30855 add workflow to select optional operators
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.11.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/baselinecaps/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/baselinecaps/none/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/baselinecaps/none/cucushift-installer-rehearse-aws-ipi-baselinecaps-none-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/baselinecaps/none/cucushift-installer-rehearse-aws-ipi-baselinecaps-none-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/baselinecaps/none/deprovision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/baselinecaps/none/deprovision/cucushift-installer-rehearse-aws-ipi-baselinecaps-none-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/baselinecaps/none/deprovision/cucushift-installer-rehearse-aws-ipi-baselinecaps-none-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/baselinecaps/none/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/baselinecaps/none/provision/cucushift-installer-rehearse-aws-ipi-baselinecaps-none-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/baselinecaps/none/provision/cucushift-installer-rehearse-aws-ipi-baselinecaps-none-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/upi/baselinecaps/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/upi/baselinecaps/v411/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/upi/baselinecaps/v411/cucushift-installer-rehearse-gcp-upi-baselinecaps-v411-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/upi/baselinecaps/v411/cucushift-installer-rehearse-gcp-upi-baselinecaps-v411-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/upi/baselinecaps/v411/deprovision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/upi/baselinecaps/v411/deprovision/cucushift-installer-rehearse-gcp-upi-baselinecaps-v411-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/upi/baselinecaps/v411/deprovision/cucushift-installer-rehearse-gcp-upi-baselinecaps-v411-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/upi/baselinecaps/v411/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/upi/baselinecaps/v411/provision/cucushift-installer-rehearse-gcp-upi-baselinecaps-v411-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/upi/baselinecaps/v411/provision/cucushift-installer-rehearse-gcp-upi-baselinecaps-v411-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/baselinecaps/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/baselinecaps/none/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/baselinecaps/none/additionalenabledcaps/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/baselinecaps/none/additionalenabledcaps/cucushift-installer-rehearse-vsphere-ipi-baselinecaps-none-additionalenabledcaps-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/baselinecaps/none/additionalenabledcaps/cucushift-installer-rehearse-vsphere-ipi-baselinecaps-none-additionalenabledcaps-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/baselinecaps/none/additionalenabledcaps/deprovision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/baselinecaps/none/additionalenabledcaps/deprovision/cucushift-installer-rehearse-vsphere-ipi-baselinecaps-none-additionalenabledcaps-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/baselinecaps/none/additionalenabledcaps/deprovision/cucushift-installer-rehearse-vsphere-ipi-baselinecaps-none-additionalenabledcaps-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/baselinecaps/none/additionalenabledcaps/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/baselinecaps/none/additionalenabledcaps/provision/cucushift-installer-rehearse-vsphere-ipi-baselinecaps-none-additionalenabledcaps-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/baselinecaps/none/additionalenabledcaps/provision/cucushift-installer-rehearse-vsphere-ipi-baselinecaps-none-additionalenabledcaps-provision-chain.yaml
  ci-operator/step-registry/ipi/conf/additional-enabled-capabilities/OWNERS
  ci-operator/step-registry/ipi/conf/additional-enabled-capabilities/ipi-conf-additional-enabled-capabilities-commands.sh
  ci-operator/step-registry/ipi/conf/additional-enabled-capabilities/ipi-conf-additional-enabled-capabilities-ref.metadata.json
  ci-operator/step-registry/ipi/conf/additional-enabled-capabilities/ipi-conf-additional-enabled-capabilities-ref.yaml
Labels: lgtm, approved

#31880 Pass GPU add-on version to must-gather
  ci-operator/config/rh-ecosystem-edge/nvidia-gpu-addon-operator/rh-ecosystem-edge-nvidia-gpu-addon-operator-main.yaml
  ci-operator/config/rh-ecosystem-edge/nvidia-gpu-addon-operator/rh-ecosystem-edge-nvidia-gpu-addon-operator-release-v1.1.yaml
Labels: lgtm, approved

#31793 add 4.12 e2e tests for aws-ipi-sdn-workers-rhel8 related
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
Labels: lgtm, approved

#31682 Use cluster with spot instances as workers for e2e test
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.12.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/spot/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/spot/cucushift-installer-rehearse-aws-ipi-spot-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/spot/cucushift-installer-rehearse-aws-ipi-spot-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/spot/deprovision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/spot/deprovision/cucushift-installer-rehearse-aws-ipi-spot-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/spot/deprovision/cucushift-installer-rehearse-aws-ipi-spot-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/spot/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/spot/provision/cucushift-installer-rehearse-aws-ipi-spot-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/spot/provision/cucushift-installer-rehearse-aws-ipi-spot-provision-chain.yaml
Labels: lgtm, approved

#31846 Fix KUBECONFIG in bashrc for baremetal devscripts
  ci-operator/step-registry/baremetalds/devscripts/setup/baremetalds-devscripts-setup-commands.sh
Labels: lgtm, approved

#31887 add envtest tools for sonarcloud.
  ci-operator/config/stolostron/multicluster-global-hub/stolostron-multicluster-global-hub-main.yaml
  ci-operator/config/stolostron/multicluster-global-hub/stolostron-multicluster-global-hub-release-2.7.yaml
Labels: lgtm, approved

#31801 Adds stackrox/collector RHEL SAP integration tests
  ci-operator/config/stackrox/collector/stackrox-collector-master.yaml
  ci-operator/jobs/stackrox/collector/stackrox-collector-master-postsubmits.yaml
  ci-operator/jobs/stackrox/collector/stackrox-collector-master-presubmits.yaml
Labels: lgtm, approved

#31892 OWNER_ALIASES: remove Saqib Ali from the coreos approvers and reviewers
  OWNERS_ALIASES
Labels: lgtm, approved

#31893 cnf-tests: Remove vrf feature
  ci-operator/step-registry/telco5g/cnf-tests/telco5g-cnf-tests-commands.sh
Labels: lgtm, approved

#31817 Remove self from direct OWNERS membership
  ci-operator/config/identitatem/OWNERS
  ci-operator/config/stolostron-engine/OWNERS
  ci-operator/config/stolostron/OWNERS
  ci-operator/jobs/stolostron-engine/OWNERS
  ci-operator/jobs/stolostron/OWNERS
  ci-operator/step-registry/identitatem/OWNERS
  ci-operator/step-registry/identitatem/ci/image-mirror/identitatem-ci-image-mirror-ref.metadata.json
  ci-operator/step-registry/identitatem/ci/image-mirror/identitatem-ci-image-mirror-workflow.metadata.json
  ci-operator/step-registry/identitatem/ci/rbac/identitatem-ci-rbac-ref.metadata.json
  ci-operator/step-registry/identitatem/ci/rbac/identitatem-ci-rbac-workflow.metadata.json
  ci-operator/step-registry/ocm/OWNERS
  ci-operator/step-registry/ocm/ci/fastforward/ocm-ci-fastforward-ref.metadata.json
  ci-operator/step-registry/ocm/ci/fastforward/ocm-ci-fastforward-workflow.metadata.json
  ci-operator/step-registry/ocm/ci/image-mirror-periodic/ocm-ci-image-mirror-periodic-ref.metadata.json
  ci-operator/step-registry/ocm/ci/image-mirror-periodic/ocm-ci-image-mirror-periodic-workflow.metadata.json
  ci-operator/step-registry/ocm/ci/image-mirror/ocm-ci-image-mirror-ref.metadata.json
  ci-operator/step-registry/ocm/ci/image-mirror/ocm-ci-image-mirror-workflow.metadata.json
  ci-operator/step-registry/ocm/ci/manifest-update/OWNERS
  ci-operator/step-registry/ocm/ci/manifest-update/ocm-ci-manifest-update-ref.metadata.json
  ci-operator/step-registry/ocm/ci/manifest-update/ocm-ci-manifest-update-workflow.metadata.json
  ci-operator/step-registry/ocm/ci/rbac/ocm-ci-rbac-ref.metadata.json
  ci-operator/step-registry/ocm/ci/rbac/ocm-ci-rbac-workflow.metadata.json
  ci-operator/step-registry/ocm/e2e/clusterpool/checkin/ocm-e2e-clusterpool-checkin-ref.metadata.json
  ci-operator/step-registry/ocm/e2e/clusterpool/checkout/ocm-e2e-clusterpool-checkout-chain.metadata.json
  ci-operator/step-registry/ocm/e2e/clusterpool/checkout/ocm-e2e-clusterpool-checkout-ref.metadata.json
  ci-operator/step-registry/ocm/e2e/clusterpool/cluster/deploy/ocm-e2e-clusterpool-cluster-deploy-ref.metadata.json
  ci-operator/step-registry/ocm/e2e/clusterpool/cluster/getcreds/ocm-e2e-clusterpool-cluster-getcreds-ref.metadata.json
  ci-operator/step-registry/ocm/e2e/clusterpool/list/ocm-e2e-clusterpool-list-ref.metadata.json
  ci-operator/step-registry/ocm/e2e/clusterpool/ocm-e2e-clusterpool-workflow.metadata.json
  ci-operator/step-registry/ocm/e2e/kind/create/ocm-e2e-kind-create-ref.metadata.json
  ci-operator/step-registry/ocm/e2e/kind/destroy/ocm-e2e-kind-destroy-ref.metadata.json
  ci-operator/step-registry/ocm/e2e/kind/ocm-e2e-kind-workflow.metadata.json
  ci-operator/step-registry/stolostron-engine/OWNERS
  ci-operator/step-registry/stolostron-engine/ci/image-mirror-periodic/stolostron-engine-ci-image-mirror-periodic-ref.metadata.json
  ci-operator/step-registry/stolostron-engine/ci/image-mirror-periodic/stolostron-engine-ci-image-mirror-periodic-workflow.metadata.json
  ci-operator/step-registry/stolostron-engine/ci/image-mirror/stolostron-engine-ci-image-mirror-ref.metadata.json
  ci-operator/step-registry/stolostron-engine/ci/image-mirror/stolostron-engine-ci-image-mirror-workflow.metadata.json
  ci-operator/step-registry/stolostron-engine/ci/manifest-update/stolostron-engine-ci-manifest-update-ref.metadata.json
  ci-operator/step-registry/stolostron-engine/ci/manifest-update/stolostron-engine-ci-manifest-update-workflow.metadata.json
  ci-operator/step-registry/stolostron-engine/ci/rbac/stolostron-engine-ci-rbac-ref.metadata.json
  ci-operator/step-registry/stolostron-engine/ci/rbac/stolostron-engine-ci-rbac-workflow.metadata.json
  clusters/app.ci/registry-access/stolostron-engine/OWNERS
  clusters/app.ci/registry-access/stolostron/OWNERS
  core-services/prow/02_config/identitatem/OWNERS
  core-services/prow/02_config/open-cluster-management-io/OWNERS
  core-services/prow/02_config/stolostron-engine/OWNERS
  core-services/prow/02_config/stolostron/OWNERS
Labels: lgtm, approved

#31824 secret-generator: use the new script for Prow SAs
  core-services/ci-secret-generator/_config.yaml
Labels: lgtm, approved

#31829 add lint timeout for logging
  ci-operator/config/openshift/cluster-logging-operator/openshift-cluster-logging-operator-master.yaml
  ci-operator/config/openshift/cluster-logging-operator/openshift-cluster-logging-operator-release-5.4.yaml
  ci-operator/config/openshift/cluster-logging-operator/openshift-cluster-logging-operator-release-5.5.yaml
  ci-operator/jobs/openshift/cluster-logging-operator/openshift-cluster-logging-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-logging-operator/openshift-cluster-logging-operator-release-5.4-presubmits.yaml
  ci-operator/jobs/openshift/cluster-logging-operator/openshift-cluster-logging-operator-release-5.5-presubmits.yaml
Labels: lgtm, approved

#31870 make prow-config for MNMO
  ci-operator/config/openshift/managed-node-metadata-operator/openshift-managed-node-metadata-operator-main.yaml
  ci-operator/jobs/openshift/managed-node-metadata-operator/openshift-managed-node-metadata-operator-main-postsubmits.yaml
  ci-operator/jobs/openshift/managed-node-metadata-operator/openshift-managed-node-metadata-operator-main-presubmits.yaml
Labels: lgtm, approved

#31725 [CVP-3057] Setting label security.openshift.io/scc.podSecurityLabelSync value to “true” on the namespace if it starts with "openshift-"
  ci-operator/step-registry/optional-operators/subscribe/optional-operators-subscribe-commands.sh
Labels: lgtm, approved

#31541 Stackrox: Add version compatibility test step
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-presubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-nightlies-postsubmits.yaml
Labels: lgtm, approved, ok-to-test

#31686 openstack: Decommission MOC
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__nightly-4.10-upgrade-from-eus-4.8.yaml
  ci-operator/config/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11-periodics.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
  ci-operator/jobs/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main-periodics.yaml
  ci-operator/step-registry/openstack/conf/clouds/openstack-conf-clouds-ref.yaml
  ci-operator/step-registry/openstack/conf/resourcenames/openstack-conf-resourcenames-commands.sh
  ci-operator/step-registry/shiftstack/monitor/expose/shiftstack-monitor-expose-ref.yaml
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved

#31900 [CVP-3057] add echo statement inside if block
  ci-operator/step-registry/optional-operators/subscribe/optional-operators-subscribe-commands.sh
Labels: lgtm, approved

#31868 Setup basic tide merge rules for terraform-provider-azurestack repo
  core-services/prow/02_config/openshift/terraform-provider-azurestack/_pluginconfig.yaml
  core-services/prow/02_config/openshift/terraform-provider-azurestack/_prowconfig.yaml
Labels: lgtm, approved

#31882 OCPQE-11756: Run console test in serial
  ci-operator/step-registry/cucushift/e2e/cucushift-e2e-commands.sh
Labels: lgtm, approved

#31905 [CVP-3094] Add cluster pools for OCP v4.12
  clusters/hive/pools/cvp/cvp-ocp-4-12-amd64-aws-eu-west-3_clusterpool.yaml
  clusters/hive/pools/cvp/install-config-aws-eu-west-3_secret.yaml
Labels: lgtm, approved

#31910 Update CICD repo builds to omit REMOTE_SRC vars to avoid double mirror
  ci-operator/config/stolostron/helloprow-go/stolostron-helloprow-go-backplane-1.0.yaml
  ci-operator/config/stolostron/helloprow-go/stolostron-helloprow-go-backplane-2.0.yaml
  ci-operator/config/stolostron/helloprow-go/stolostron-helloprow-go-release-2.3.yaml
  ci-operator/config/stolostron/helloprow-go/stolostron-helloprow-go-release-2.4.yaml
  ci-operator/config/stolostron/helloprow-go/stolostron-helloprow-go-release-2.5.yaml
Labels: lgtm, approved

#31912 Update integration builds to omit REMOTE_SRC vars to avoid double mirror
  ci-operator/config/stolostron/managed-serviceaccount-e2e/stolostron-managed-serviceaccount-e2e-backplane-2.0.yaml
  ci-operator/config/stolostron/managed-serviceaccount-e2e/stolostron-managed-serviceaccount-e2e-backplane-2.1.yaml
  ci-operator/config/stolostron/managed-serviceaccount-e2e/stolostron-managed-serviceaccount-e2e-backplane-2.2.yaml
  ci-operator/config/stolostron/managed-serviceaccount/stolostron-managed-serviceaccount-backplane-2.0.yaml
  ci-operator/config/stolostron/managed-serviceaccount/stolostron-managed-serviceaccount-backplane-2.1.yaml
  ci-operator/config/stolostron/managed-serviceaccount/stolostron-managed-serviceaccount-backplane-2.2.yaml
Labels: lgtm, approved

#31914 Update search builds to omit REMOTE_SRC vars to avoid double mirror
  ci-operator/config/stolostron/search-aggregator/stolostron-search-aggregator-release-2.4.yaml
  ci-operator/config/stolostron/search-aggregator/stolostron-search-aggregator-release-2.5.yaml
  ci-operator/config/stolostron/search-aggregator/stolostron-search-aggregator-release-2.6.yaml
  ci-operator/config/stolostron/search-aggregator/stolostron-search-aggregator-release-2.7.yaml
  ci-operator/config/stolostron/search-api/stolostron-search-api-release-2.4.yaml
  ci-operator/config/stolostron/search-api/stolostron-search-api-release-2.5.yaml
  ci-operator/config/stolostron/search-api/stolostron-search-api-release-2.6.yaml
  ci-operator/config/stolostron/search-api/stolostron-search-api-release-2.7.yaml
  ci-operator/config/stolostron/search-collector/stolostron-search-collector-release-2.4.yaml
  ci-operator/config/stolostron/search-collector/stolostron-search-collector-release-2.5.yaml
  ci-operator/config/stolostron/search-collector/stolostron-search-collector-release-2.6.yaml
  ci-operator/config/stolostron/search-collector/stolostron-search-collector-release-2.7.yaml
  ci-operator/config/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.3.yaml
  ci-operator/config/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.4.yaml
  ci-operator/config/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.5.yaml
  ci-operator/config/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.6.yaml
  ci-operator/config/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.7.yaml
  ci-operator/config/stolostron/search-indexer/stolostron-search-indexer-release-2.5.yaml
  ci-operator/config/stolostron/search-indexer/stolostron-search-indexer-release-2.6.yaml
  ci-operator/config/stolostron/search-indexer/stolostron-search-indexer-release-2.7.yaml
  ci-operator/config/stolostron/search-operator/stolostron-search-operator-release-2.3.yaml
  ci-operator/config/stolostron/search-operator/stolostron-search-operator-release-2.4.yaml
  ci-operator/config/stolostron/search-operator/stolostron-search-operator-release-2.5.yaml
  ci-operator/config/stolostron/search-operator/stolostron-search-operator-release-2.6.yaml
  ci-operator/config/stolostron/search-operator/stolostron-search-operator-release-2.7.yaml
  ci-operator/config/stolostron/search-v2-api/stolostron-search-v2-api-release-2.5.yaml
  ci-operator/config/stolostron/search-v2-api/stolostron-search-v2-api-release-2.6.yaml
  ci-operator/config/stolostron/search-v2-api/stolostron-search-v2-api-release-2.7.yaml
  ci-operator/config/stolostron/search-v2-operator-bundle/stolostron-search-v2-operator-bundle-release-2.7.yaml
  ci-operator/config/stolostron/search-v2-operator/stolostron-search-v2-operator-release-2.5.yaml
  ci-operator/config/stolostron/search-v2-operator/stolostron-search-v2-operator-release-2.6.yaml
  ci-operator/config/stolostron/search-v2-operator/stolostron-search-v2-operator-release-2.7.yaml
Labels: lgtm, approved

#31915 Update observability builds to omit REMOTE_SRC vars to avoid double m…
  ci-operator/config/stolostron/grafana/stolostron-grafana-release-2.4.yaml
  ci-operator/config/stolostron/grafana/stolostron-grafana-release-2.5.yaml
  ci-operator/config/stolostron/grafana/stolostron-grafana-release-2.6.yaml
  ci-operator/config/stolostron/grafana/stolostron-grafana-release-2.7.yaml
  ci-operator/config/stolostron/insights-client/stolostron-insights-client-release-2.4.yaml
  ci-operator/config/stolostron/insights-client/stolostron-insights-client-release-2.5.yaml
  ci-operator/config/stolostron/insights-client/stolostron-insights-client-release-2.6.yaml
  ci-operator/config/stolostron/insights-client/stolostron-insights-client-release-2.7.yaml
  ci-operator/config/stolostron/insights-metrics/stolostron-insights-metrics-release-2.3.yaml
  ci-operator/config/stolostron/insights-metrics/stolostron-insights-metrics-release-2.4.yaml
  ci-operator/config/stolostron/insights-metrics/stolostron-insights-metrics-release-2.5.yaml
  ci-operator/config/stolostron/insights-metrics/stolostron-insights-metrics-release-2.6.yaml
  ci-operator/config/stolostron/kube-rbac-proxy/stolostron-kube-rbac-proxy-release-2.4.yaml
  ci-operator/config/stolostron/kube-rbac-proxy/stolostron-kube-rbac-proxy-release-2.5.yaml
  ci-operator/config/stolostron/kube-rbac-proxy/stolostron-kube-rbac-proxy-release-2.6.yaml
  ci-operator/config/stolostron/kube-rbac-proxy/stolostron-kube-rbac-proxy-release-2.7.yaml
  ci-operator/config/stolostron/kube-state-metrics/stolostron-kube-state-metrics-release-2.4.yaml
  ci-operator/config/stolostron/kube-state-metrics/stolostron-kube-state-metrics-release-2.5.yaml
  ci-operator/config/stolostron/kube-state-metrics/stolostron-kube-state-metrics-release-2.6.yaml
  ci-operator/config/stolostron/kube-state-metrics/stolostron-kube-state-metrics-release-2.7.yaml
  ci-operator/config/stolostron/management-ingress/stolostron-management-ingress-release-2.4.yaml
  ci-operator/config/stolostron/management-ingress/stolostron-management-ingress-release-2.5.yaml
  ci-operator/config/stolostron/management-ingress/stolostron-management-ingress-release-2.6.yaml
  ci-operator/config/stolostron/management-ingress/stolostron-management-ingress-release-2.7.yaml
  ci-operator/config/stolostron/multicluster-observability-operator/stolostron-multicluster-observability-operator-release-2.4.yaml
  ci-operator/config/stolostron/multicluster-observability-operator/stolostron-multicluster-observability-operator-release-2.5.yaml
  ci-operator/config/stolostron/multicluster-observability-operator/stolostron-multicluster-observability-operator-release-2.6.yaml
  ci-operator/config/stolostron/multicluster-observability-operator/stolostron-multicluster-observability-operator-release-2.7.yaml
  ci-operator/config/stolostron/node-exporter/stolostron-node-exporter-release-2.4.yaml
  ci-operator/config/stolostron/node-exporter/stolostron-node-exporter-release-2.5.yaml
  ci-operator/config/stolostron/node-exporter/stolostron-node-exporter-release-2.6.yaml
  ci-operator/config/stolostron/node-exporter/stolostron-node-exporter-release-2.7.yaml
  ci-operator/config/stolostron/observatorium-operator/stolostron-observatorium-operator-release-2.4.yaml
  ci-operator/config/stolostron/observatorium-operator/stolostron-observatorium-operator-release-2.5.yaml
  ci-operator/config/stolostron/observatorium-operator/stolostron-observatorium-operator-release-2.6.yaml
  ci-operator/config/stolostron/observatorium-operator/stolostron-observatorium-operator-release-2.7.yaml
  ci-operator/config/stolostron/observatorium/stolostron-observatorium-release-2.4.yaml
  ci-operator/config/stolostron/observatorium/stolostron-observatorium-release-2.5.yaml
  ci-operator/config/stolostron/observatorium/stolostron-observatorium-release-2.6.yaml
  ci-operator/config/stolostron/observatorium/stolostron-observatorium-release-2.7.yaml
  ci-operator/config/stolostron/prometheus-alertmanager/stolostron-prometheus-alertmanager-release-2.5.yaml
  ci-operator/config/stolostron/prometheus-alertmanager/stolostron-prometheus-alertmanager-release-2.6.yaml
  ci-operator/config/stolostron/prometheus-alertmanager/stolostron-prometheus-alertmanager-release-2.7.yaml
  ci-operator/config/stolostron/prometheus-operator/stolostron-prometheus-operator-release-2.5.yaml
  ci-operator/config/stolostron/prometheus-operator/stolostron-prometheus-operator-release-2.6.yaml
  ci-operator/config/stolostron/prometheus-operator/stolostron-prometheus-operator-release-2.7.yaml
  ci-operator/config/stolostron/prometheus/stolostron-prometheus-release-2.4.yaml
  ci-operator/config/stolostron/prometheus/stolostron-prometheus-release-2.5.yaml
  ci-operator/config/stolostron/prometheus/stolostron-prometheus-release-2.6.yaml
  ci-operator/config/stolostron/prometheus/stolostron-prometheus-release-2.7.yaml
  ci-operator/config/stolostron/thanos/stolostron-thanos-release-2.5.yaml
  ci-operator/config/stolostron/thanos/stolostron-thanos-release-2.6.yaml
  ci-operator/config/stolostron/thanos/stolostron-thanos-release-2.7.yaml
Labels: lgtm, approved

#31907 Adding permissions for ART to execute the release-tool
  clusters/app.ci/art/admin_art.yaml
Labels: lgtm, approved

#31923 hypershift: use build from branch head on periodic job
  ci-operator/config/openshift/hypershift/openshift-hypershift-main__periodics.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.11__periodics.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-main-periodics.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-main-presubmits.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.11-periodics.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.11-presubmits.yaml
Labels: lgtm, approved

#31918 Updated makefile reference for search-v2-operator-bundle
  ci-operator/config/stolostron/search-aggregator/stolostron-search-aggregator-main.yaml
  ci-operator/config/stolostron/search-aggregator/stolostron-search-aggregator-release-2.6.yaml
  ci-operator/config/stolostron/search-aggregator/stolostron-search-aggregator-release-2.7.yaml
  ci-operator/config/stolostron/search-indexer/stolostron-search-indexer-main.yaml
  ci-operator/config/stolostron/search-indexer/stolostron-search-indexer-release-2.6.yaml
  ci-operator/config/stolostron/search-indexer/stolostron-search-indexer-release-2.7.yaml
  ci-operator/config/stolostron/search-v2-api/stolostron-search-v2-api-main.yaml
  ci-operator/config/stolostron/search-v2-api/stolostron-search-v2-api-release-2.6.yaml
  ci-operator/config/stolostron/search-v2-api/stolostron-search-v2-api-release-2.7.yaml
  ci-operator/config/stolostron/search-v2-operator-bundle/stolostron-search-v2-operator-bundle-release-2.7.yaml
  ci-operator/config/stolostron/search-v2-operator/stolostron-search-v2-operator-release-2.6.yaml
  core-services/prow/02_config/stolostron/search-v2-operator-bundle/_prowconfig.yaml
  core-services/prow/02_config/stolostron/search-v2-operator/_prowconfig.yaml
Labels: lgtm, approved

#31926 stackrox: mirror images for golang 1.18.4 use
  core-services/image-mirroring/stackrox/mapping_supplemental_ci_images_stackrox_base_images
  core-services/image-mirroring/stackrox/mapping_supplemental_ci_images_stackrox_rox_ci_image
Labels: lgtm, approved

#31919 Update some extra builds to omit REMOTE_SRC vars to avoid double mirror
  ci-operator/config/stolostron/discovery/stolostron-discovery-backplane-2.0.yaml
  ci-operator/config/stolostron/discovery/stolostron-discovery-backplane-2.1.yaml
  ci-operator/config/stolostron/discovery/stolostron-discovery-backplane-2.2.yaml
  ci-operator/config/stolostron/discovery/stolostron-discovery-release-2.4.yaml
  ci-operator/config/stolostron/insights-metrics/stolostron-insights-metrics-release-2.7.yaml
  ci-operator/config/stolostron/maintenance-window/stolostron-maintenance-window-release-2.6.yaml
  ci-operator/config/stolostron/must-gather/stolostron-must-gather-release-2.6.yaml
  ci-operator/config/stolostron/must-gather/stolostron-must-gather-release-2.7.yaml
  ci-operator/config/stolostron/volsync-addon-controller/stolostron-volsync-addon-controller-release-2.5.yaml
  ci-operator/config/stolostron/volsync-addon-controller/stolostron-volsync-addon-controller-release-2.6.yaml
  ci-operator/config/stolostron/volsync-addon-controller/stolostron-volsync-addon-controller-release-2.7.yaml
Labels: lgtm, approved

#31891 add 4.12 e2e test for vsphere-upi-disconnected-sdn-workers-rhcos-rhel8
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
Labels: lgtm, approved

#31930 [CIGolang]add log to print version
  ci-operator/step-registry/openshift-extended/test/openshift-extended-test-commands.sh
Labels: lgtm, approved

#31691 Support paused eus upgrade using --to-latest option
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__stable-4.10-upgrade-from-eus-4.8.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10-periodics.yaml
  ci-operator/step-registry/cucushift/upgrade/paused/intermediate/to-latest/OWNERS
  ci-operator/step-registry/cucushift/upgrade/paused/intermediate/to-latest/cucushift-upgrade-paused-intermediate-to-latest-commands.sh
  ci-operator/step-registry/cucushift/upgrade/paused/intermediate/to-latest/cucushift-upgrade-paused-intermediate-to-latest-ref.metadata.json
  ci-operator/step-registry/cucushift/upgrade/paused/intermediate/to-latest/cucushift-upgrade-paused-intermediate-to-latest-ref.yaml
  ci-operator/step-registry/cucushift/upgrade/paused/latest/to-latest/OWNERS
  ci-operator/step-registry/cucushift/upgrade/paused/latest/to-latest/cucushift-upgrade-paused-latest-to-latest-commands.sh
  ci-operator/step-registry/cucushift/upgrade/paused/latest/to-latest/cucushift-upgrade-paused-latest-to-latest-ref.metadata.json
  ci-operator/step-registry/cucushift/upgrade/paused/latest/to-latest/cucushift-upgrade-paused-latest-to-latest-ref.yaml
  ci-operator/step-registry/cucushift/upgrade/paused/unpause/to-latest/OWNERS
  ci-operator/step-registry/cucushift/upgrade/paused/unpause/to-latest/cucushift-upgrade-paused-unpause-to-latest-commands.sh
  ci-operator/step-registry/cucushift/upgrade/paused/unpause/to-latest/cucushift-upgrade-paused-unpause-to-latest-ref.metadata.json
  ci-operator/step-registry/cucushift/upgrade/paused/unpause/to-latest/cucushift-upgrade-paused-unpause-to-latest-ref.yaml
  ci-operator/step-registry/openshift/upgrade/qe/test/paused-to-latest/OWNERS
  ci-operator/step-registry/openshift/upgrade/qe/test/paused-to-latest/openshift-upgrade-qe-test-paused-to-latest-chain.metadata.json
  ci-operator/step-registry/openshift/upgrade/qe/test/paused-to-latest/openshift-upgrade-qe-test-paused-to-latest-chain.yaml
Labels: lgtm, approved

#31668 Move 4.11 and 4.12 ipv4 ipi jobs to their bm counterpart
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.11.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.12.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  core-services/release-controller/_releases/priv/release-ocp-4.11.json
  core-services/release-controller/_releases/priv/release-ocp-4.12.json
  core-services/release-controller/_releases/release-ocp-4.11.json
  core-services/release-controller/_releases/release-ocp-4.12.json
Labels: lgtm, approved

#31894 fips-check: run debug pod in a privileged namespace
  ci-operator/step-registry/fips-check/fips-check-commands.sh
Labels: lgtm, approved

#31804 chore: Rename test scripts
  ci-operator/config/eclipse-che/che-operator/eclipse-che-che-operator-main__v10.yaml
  ci-operator/config/eclipse-che/che-operator/eclipse-che-che-operator-main__v11.yaml
Labels: lgtm, approved, ok-to-test

#31924 Revert "[CVP-3094] Add cluster pools for OCP v4.12"
  clusters/hive/pools/cvp/cvp-ocp-4-12-amd64-aws-eu-west-3_clusterpool.yaml
  clusters/hive/pools/cvp/install-config-aws-eu-west-3_secret.yaml
Labels: lgtm, approved

#31928 remove ssh key from _config.yaml
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved

#31835 onboard openshift/route-controller-manager
  ci-operator/config/openshift/route-controller-manager/OWNERS
  ci-operator/config/openshift/route-controller-manager/openshift-route-controller-manager-main.yaml
  ci-operator/jobs/openshift/route-controller-manager/OWNERS
  ci-operator/jobs/openshift/route-controller-manager/openshift-route-controller-manager-main-postsubmits.yaml
  ci-operator/jobs/openshift/route-controller-manager/openshift-route-controller-manager-main-presubmits.yaml
  core-services/image-mirroring/openshift/mapping_origin_4_12
  core-services/prow/02_config/openshift/route-controller-manager/OWNERS
  core-services/prow/02_config/openshift/route-controller-manager/_pluginconfig.yaml
  core-services/prow/02_config/openshift/route-controller-manager/_prowconfig.yaml
Labels: lgtm, approved

#31876 Allow patch managers to apply valid-bug and staff-eng-approved labels. Note: we'll be renaming the patch manager team to staff eng shortly so this will make more sense then.
  core-services/prow/02_config/_plugins.yaml
Labels: lgtm, approved

#31902 ci-tools: bump oc-cli to 4.11
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
Labels: lgtm, approved

#31867 define make target to check gh automation for a specific repo
  Makefile
  hack/check-repo.sh
Labels: lgtm, approved

#31922 Add cluster pool for openstack-k8s-operators
  clusters/hive/pools/openstack-k8s-operators/OWNERS
  clusters/hive/pools/openstack-k8s-operators/admins_openstack-k8s-operators-cluster-pool_rbac.yaml
  clusters/hive/pools/openstack-k8s-operators/install-config-sno_secret.yaml
  clusters/hive/pools/openstack-k8s-operators/openstack-k8s-operators-4-10-vexxhost-sno_clusterpool.yaml
Labels: lgtm, approved

#31803 Set up a mirror job for stackrox/collector drivers
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_stackrox
Labels: lgtm, approved

#31939 Revert "Set up a mirror job for stackrox/collector drivers"
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_stackrox
Labels: lgtm, approved

#31940 Setup CPaaS built drivers to be mirrored into OSCI
  ci-operator/jobs/infra-image-mirroring.yaml
  core-services/image-mirroring/stackrox/mapping_stackrox_collector_drivers
Labels: lgtm, approved

#31945 Limit CI payload creation to at most 4 per day
  core-services/release-controller/_releases/release-ocp-4.10-ci.json
  core-services/release-controller/_releases/release-ocp-4.11-ci.json
  core-services/release-controller/_releases/release-ocp-4.12-ci.json
Labels: lgtm, approved

#31949 fix openshift v1 version in manifests
  clusters/app.ci/assets/slack-bot-alpha.yaml
  clusters/app.ci/ci-arm64/arm64_adapter_imagestreams.yaml
  clusters/app.ci/ci-rpms/artifacts-rpms.yaml
  clusters/app.ci/prow/03_deployment/adapter_imagestreams.yaml
  clusters/app.ci/prow/03_deployment/gcsweb.yaml
  clusters/app.ci/supplemental-ci-images/azure/base-images/ci-base.yaml
  clusters/app.ci/supplemental-ci-images/azure/base-images/test-base.yaml
  clusters/app.ci/supplemental-ci-images/cli-jq.yaml
  clusters/app.ci/supplemental-ci-images/cli-ocm.yaml
  clusters/app.ci/supplemental-ci-images/cli-yq.yaml
  clusters/app.ci/supplemental-ci-images/content-mirror/pipeline.yaml
  clusters/app.ci/supplemental-ci-images/coreos/coreos-centos8-buildroot.yaml
  clusters/app.ci/supplemental-ci-images/coreos/coreos-stream8-buildroot.yaml
  clusters/app.ci/supplemental-ci-images/coreos/cosa-continuous.yaml
  clusters/app.ci/supplemental-ci-images/coreos/cosa-exttests.yaml
  clusters/app.ci/supplemental-ci-images/coreos/fcos-buildroot.yaml
  clusters/app.ci/supplemental-ci-images/coreos/fcos-continuous.yaml
  clusters/app.ci/supplemental-ci-images/ocpmetal-postgresql-12-centos7.yaml
  clusters/app.ci/supplemental-ci-images/sshd_build.yaml
  clusters/app.ci/supplemental-ci-images/telco-bastion.yaml
  clusters/app.ci/supplemental-ci-images/validation-images/python/python-validation.yaml
  clusters/app.ci/supplemental-ci-images/validation-images/shellcheck/shellcheck.yaml
  clusters/build-clusters/arm01/assets/arm64_adapter_imagestreams.yaml
  clusters/build-clusters/arm01/supplemental-ci-images/boskos.yaml
Labels: lgtm, approved

#31948 Adding informing jobs for 4.12 ppc64le/s390x
  core-services/release-controller/_releases/priv/release-ocp-4.12-ppc64le.json
  core-services/release-controller/_releases/priv/release-ocp-4.12-s390x.json
  core-services/release-controller/_releases/release-ocp-4.12-ppc64le.json
  core-services/release-controller/_releases/release-ocp-4.12-s390x.json
Labels: lgtm, approved

#31904 ci-secret-generator: use default oc
  core-services/ci-secret-generator/_config.yaml
Labels: lgtm, approved

#31950 Stolostron: Adjust branch protection for search projects
  core-services/prow/02_config/stolostron/search-aggregator/_prowconfig.yaml
  core-services/prow/02_config/stolostron/search-api/_prowconfig.yaml
  core-services/prow/02_config/stolostron/search-collector/_prowconfig.yaml
  core-services/prow/02_config/stolostron/search-e2e-test/_prowconfig.yaml
  core-services/prow/02_config/stolostron/search-indexer/_prowconfig.yaml
  core-services/prow/02_config/stolostron/search-operator/_prowconfig.yaml
  core-services/prow/02_config/stolostron/search-v2-api/_prowconfig.yaml
  core-services/prow/02_config/stolostron/search-v2-operator-bundle/_prowconfig.yaml
  core-services/prow/02_config/stolostron/search-v2-operator/_prowconfig.yaml
Labels: lgtm, approved

#31937 4.6 to 4.11 periodics once a month for other test suites
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.10.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.11-upgrade-from-nightly-4.10.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.11.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.12-upgrade-from-nightly-4.11.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.12-upgrade-from-stable-4.11.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.12.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.8.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.9.yaml
  ci-operator/jobs/openshift/multiarch/openshift-multiarch-master-periodics.yaml
Labels: lgtm, approved

#31956 Set up RBAC for openstack-k8s-operators-ci group
  clusters/hive/pools/openstack-k8s-operators/admins_openstack-k8s-operators-cluster-pool_rbac.yaml
  core-services/sync-rover-groups/_config.yaml
Labels: lgtm, approved

#31957 vsphere: reducing vmc ci job capacity
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: lgtm, approved

#31941 [rhd-sbo] Add jobs for release-v1.2.x branch
  ci-operator/config/redhat-developer/service-binding-operator/redhat-developer-service-binding-operator-release-v1.2.x.yaml
  ci-operator/config/redhat-developer/service-binding-operator/redhat-developer-service-binding-operator-release-v1.2.x__4.10.yaml
  ci-operator/config/redhat-developer/service-binding-operator/redhat-developer-service-binding-operator-release-v1.2.x__4.11.yaml
  ci-operator/config/redhat-developer/service-binding-operator/redhat-developer-service-binding-operator-release-v1.2.x__4.12.yaml
  ci-operator/config/redhat-developer/service-binding-operator/redhat-developer-service-binding-operator-release-v1.2.x__4.9.yaml
  ci-operator/jobs/redhat-developer/service-binding-operator/redhat-developer-service-binding-operator-release-v1.2.x-presubmits.yaml
Labels: lgtm, approved

#31916 Update go version of runtime-utils ci
  ci-operator/config/openshift/runtime-utils/openshift-runtime-utils-master.yaml
  ci-operator/config/openshift/runtime-utils/openshift-runtime-utils-release-4.12.yaml
Labels: lgtm, approved

#31715 [CNF-5333] Add prow CI lane to enable mount namespace hiding e2e testing
  .gitignore
  ci-operator/config/openshift/release/openshift-release-master__ci-4.12.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  ci-operator/step-registry/mount-ns-hiding/OWNERS
  ci-operator/step-registry/mount-ns-hiding/mount-ns-hiding-commands.sh
  ci-operator/step-registry/mount-ns-hiding/mount-ns-hiding-ref.metadata.json
  ci-operator/step-registry/mount-ns-hiding/mount-ns-hiding-ref.yaml
  ci-operator/step-registry/openshift/e2e/gcp/mount-ns-hiding/OWNERS
  ci-operator/step-registry/openshift/e2e/gcp/mount-ns-hiding/openshift-e2e-gcp-mount-ns-hiding-workflow.metadata.json
  ci-operator/step-registry/openshift/e2e/gcp/mount-ns-hiding/openshift-e2e-gcp-mount-ns-hiding-workflow.yaml
Labels: lgtm, approved

#31959 Add kcp release-0.8
  ci-operator/config/kcp-dev/kcp/kcp-dev-kcp-release-0.8.yaml
  ci-operator/jobs/kcp-dev/kcp/kcp-dev-kcp-release-0.8-periodics.yaml
  ci-operator/jobs/kcp-dev/kcp/kcp-dev-kcp-release-0.8-postsubmits.yaml
  ci-operator/jobs/kcp-dev/kcp/kcp-dev-kcp-release-0.8-presubmits.yaml
  core-services/prow/02_config/kcp-dev/kcp/_prowconfig.yaml
Labels: lgtm, approved

#31938 Enable users access to nodes that support virtualization
  ci-operator/jobs/openshift/release/openshift-release-infra-periodics.yaml
Labels: lgtm, approved

#31962 remove --keep-manifest-list from oc image mirror call for COSA
  ci-operator/jobs/infra-image-mirroring.yaml
Labels: lgtm, approved

#31963 OKD: Fix machine-os-content builds
  ci-operator/config/openshift/okd-machine-os/openshift-okd-machine-os-master.yaml
  ci-operator/config/openshift/okd-machine-os/openshift-okd-machine-os-release-4.12.yaml
  ci-operator/config/openshift/okd-machine-os/openshift-okd-machine-os-release-4.13.yaml
Labels: lgtm, approved

#31960 Removed non Base pipeline and diabled rehearses
  ci-operator/config/openshift/osde2e/.config.prowgen
  ci-operator/config/openshift/osde2e/openshift-osde2e-main.yaml
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: lgtm, approved

#31964 build01 infra rightsizing
  clusters/build-clusters/01_cluster/assets/build01-9hdwj-worker-us-east-1a-infra_machineautoscaler.yaml
  clusters/build-clusters/01_cluster/ci-search/deploy.yaml
  clusters/build-clusters/01_cluster/openshift-machine-api/admin_build01-9hdwj-worker-us-east-1a-infra_machine_set.yaml
  clusters/build-clusters/01_cluster/openshift-machine-api/admin_build01-9hdwj-worker-us-east-1a-search_machine_set.yaml
  clusters/build-clusters/01_cluster/openshift-machine-api/admin_build01-9hdwj-worker-us-east-1a_machine_set.yaml
  clusters/build-clusters/01_cluster/openshift-machine-api/admin_build01-9hdwj-worker-us-east-1b_machine_set.yaml
  clusters/build-clusters/01_cluster/openshift-machine-api/admin_build01-9hdwj-worker-us-east-1c_machine_set.yaml
Labels: lgtm, approved

#31978 add ginkgo filter for e2e-vsphere-upi-disconnected-sdn-workers-rhcos-rhel8-p2
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
Labels: lgtm, approved

#31888 Exclude long-duration tests in general e2e
  ci-operator/step-registry/cucushift/e2e/cucushift-e2e-ref.yaml
Labels: lgtm, approved

#31981 okd-machine-os: Use Dockerfile.generated
  ci-operator/config/openshift/okd-machine-os/openshift-okd-machine-os-master.yaml
  ci-operator/config/openshift/okd-machine-os/openshift-okd-machine-os-release-4.12.yaml
  ci-operator/config/openshift/okd-machine-os/openshift-okd-machine-os-release-4.13.yaml
Labels: lgtm, approved

#31929 add workflow azure-ipi-private-sdn and gcp-upi-private-xpn-sdn
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.12.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/private/sdn/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/private/sdn/cucushift-installer-rehearse-azure-ipi-private-sdn-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/private/sdn/cucushift-installer-rehearse-azure-ipi-private-sdn-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/private/sdn/deprovision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/private/sdn/deprovision/cucushift-installer-rehearse-azure-ipi-private-sdn-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/private/sdn/deprovision/cucushift-installer-rehearse-azure-ipi-private-sdn-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/private/sdn/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/private/sdn/provision/cucushift-installer-rehearse-azure-ipi-private-sdn-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/private/sdn/provision/cucushift-installer-rehearse-azure-ipi-private-sdn-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/upi/private/xpn/sdn/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/upi/private/xpn/sdn/cucushift-installer-rehearse-gcp-upi-private-xpn-sdn-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/upi/private/xpn/sdn/cucushift-installer-rehearse-gcp-upi-private-xpn-sdn-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/upi/private/xpn/sdn/deprovision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/upi/private/xpn/sdn/deprovision/cucushift-installer-rehearse-gcp-upi-private-xpn-sdn-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/upi/private/xpn/sdn/deprovision/cucushift-installer-rehearse-gcp-upi-private-xpn-sdn-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/upi/private/xpn/sdn/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/upi/private/xpn/sdn/provision/cucushift-installer-rehearse-gcp-upi-private-xpn-sdn-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/upi/private/xpn/sdn/provision/cucushift-installer-rehearse-gcp-upi-private-xpn-sdn-provision-chain.yaml
Labels: lgtm, approved

#31984 Expose SONAR_GO_TEST_ARGS with coverpkg
  ci-operator/config/stolostron/multicluster-global-hub/stolostron-multicluster-global-hub-main.yaml
  ci-operator/config/stolostron/multicluster-global-hub/stolostron-multicluster-global-hub-release-2.7.yaml
Labels: lgtm, approved

#31946 MGMT-11815: Rename assisted-common chain to assisted-common-pre
  ci-operator/step-registry/assisted/baremetal/assisted-baremetal-workflow.yaml
  ci-operator/step-registry/assisted/common/assisted-common-chain.metadata.json
  ci-operator/step-registry/assisted/common/post-install/OWNERS
  ci-operator/step-registry/assisted/common/post-install/assisted-common-post-install-commands.sh
  ci-operator/step-registry/assisted/common/post-install/assisted-common-post-install-ref.metadata.json
  ci-operator/step-registry/assisted/common/post-install/assisted-common-post-install-ref.yaml
  ci-operator/step-registry/assisted/common/post/assisted-common-post-ref.metadata.json
  ci-operator/step-registry/assisted/common/pre/OWNERS
  ci-operator/step-registry/assisted/common/pre/assisted-common-pre-chain.metadata.json
  ci-operator/step-registry/assisted/common/pre/assisted-common-pre-chain.yaml
  ci-operator/step-registry/assisted/vsphere/assisted-vsphere-workflow.yaml
Labels: lgtm, approved

#31967 delete upgrade-debug-data on b01
  clusters/build-clusters/01_cluster/openshift/scc/ci-privileged_scc.yaml
  clusters/build-clusters/01_cluster/openshift/upgrade-debug-data/iostat-vmstat_daemonset.yaml
Labels: lgtm, approved

#31976 fix: command to run happy path test on eclipse-che/che-operator repos…
  ci-operator/config/eclipse-che/che-operator/eclipse-che-che-operator-main__v11.yaml
Labels: lgtm, approved

#31991 Print env variables in Telco5G job
  ci-operator/step-registry/telco-bastion/setup/telco-bastion-setup-commands.sh
Labels: lgtm, approved

#31990 UPI vsphere sdn migration ovn
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.11.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/ovn/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/ovn/sdn2ovn/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/ovn/sdn2ovn/cucushift-installer-rehearse-vsphere-upi-ovn-sdn2ovn-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/ovn/sdn2ovn/cucushift-installer-rehearse-vsphere-upi-ovn-sdn2ovn-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/ovn/sdn2ovn/deprovision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/ovn/sdn2ovn/deprovision/cucushift-installer-rehearse-vsphere-upi-ovn-sdn2ovn-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/ovn/sdn2ovn/deprovision/cucushift-installer-rehearse-vsphere-upi-ovn-sdn2ovn-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/ovn/sdn2ovn/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/ovn/sdn2ovn/provision/cucushift-installer-rehearse-vsphere-upi-ovn-sdn2ovn-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/ovn/sdn2ovn/provision/cucushift-installer-rehearse-vsphere-upi-ovn-sdn2ovn-provision-chain.yaml
Labels: lgtm, approved

#31927 Add huali9 as cherry-pick approver
  core-services/prow/02_config/openshift/cloud-provider-alibaba-cloud/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cloud-provider-aws/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cloud-provider-azure/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cloud-provider-gcp/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cloud-provider-ibm/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cloud-provider-vpc-controller/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cloud-provider-vsphere/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-api-actuator-pkg/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-api-provider-alibaba/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-api-provider-aws/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-api-provider-azure/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-api-provider-gcp/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-api-provider-ibmcloud/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-api/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-autoscaler-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-capi-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-cloud-controller-manager-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-control-plane-machine-set-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-machine-approver/_pluginconfig.yaml
  core-services/prow/02_config/openshift/kubernetes-autoscaler/_pluginconfig.yaml
  core-services/prow/02_config/openshift/machine-api-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/machine-api-provider-aws/_pluginconfig.yaml
  core-services/prow/02_config/openshift/machine-api-provider-azure/_pluginconfig.yaml
  core-services/prow/02_config/openshift/machine-api-provider-gcp/_pluginconfig.yaml
  core-services/prow/02_config/openshift/machine-api-provider-ibmcloud/_pluginconfig.yaml
  core-services/prow/02_config/openshift/machine-api-provider-nutanix/_pluginconfig.yaml
Labels: lgtm, approved

#31986 HCO: explicitly set COMPUTE_NODE_TYPE on GCP
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-main.yaml
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-1.2.yaml
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-1.3.yaml
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-1.4.yaml
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-1.5.yaml
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-1.6.yaml
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-1.7.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-1.6-presubmits.yaml
Labels: lgtm, approved

#31995 [dptp-controller-manager] enable distributing images to arm01 cluster
  clusters/app.ci/assets/dptp-controller-manager.yaml
Labels: lgtm, approved

#31996 [CVP-3094] Add cluster pools for OCP v4.12
  clusters/hive/pools/cvp/cvp-ocp-4-12-amd64-aws-eu-west-3_clusterpool.yaml
  clusters/hive/pools/cvp/install-config-aws-eu-west-3_secret.yaml
Labels: lgtm, approved

#31756 Use OCP 4.11 instead of 4.10 for knative serving release-next
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-next__410-tls.yaml
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-next__411.yaml
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-next__46.yaml
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-next__47.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-next-postsubmits.yaml
  ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-release-next-presubmits.yaml
  core-services/image-mirroring/knative/mapping_knative_nightly_quay
Labels: lgtm, approved

#31998 Switch redhat-appstudio e2e to pre-kcp
  ci-operator/config/redhat-appstudio/infra-deployments/redhat-appstudio-infra-deployments-pre-kcp.yaml
  ci-operator/jobs/redhat-appstudio/infra-deployments/redhat-appstudio-infra-deployments-pre-kcp-periodics.yaml
  ci-operator/jobs/redhat-appstudio/infra-deployments/redhat-appstudio-infra-deployments-pre-kcp-presubmits.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: lgtm, approved

#31989 ACM: fix cache permission issue for stolostron work
  ci-operator/config/stolostron/work/stolostron-work-backplane-1.0.yaml
  ci-operator/config/stolostron/work/stolostron-work-backplane-2.0.yaml
  ci-operator/config/stolostron/work/stolostron-work-backplane-2.1.yaml
  ci-operator/config/stolostron/work/stolostron-work-backplane-2.2.yaml
  ci-operator/config/stolostron/work/stolostron-work-release-2.3.yaml
  ci-operator/config/stolostron/work/stolostron-work-release-2.4.yaml
Labels: lgtm, approved

#31975 Add openconnect to telco CI image
  clusters/app.ci/supplemental-ci-images/telco-bastion.yaml
Labels: lgtm, approved

#32012 [CVP-3094] Update the ImageSetRef version for OCP 4.12
  clusters/hive/pools/cvp/cvp-ocp-4-12-amd64-aws-eu-west-3_clusterpool.yaml
Labels: lgtm, approved

#30545 Run openshift/console nightly builds more regularly
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.10.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.11.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.12.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.9.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: lgtm, approved

#32011 AWS Cluster with BYO IAM role
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.12.yaml
  ci-operator/step-registry/aws/deprovision/iam-role/OWNERS
  ci-operator/step-registry/aws/deprovision/iam-role/aws-deprovision-iam-role-commands.sh
  ci-operator/step-registry/aws/deprovision/iam-role/aws-deprovision-iam-role-ref.metadata.json
  ci-operator/step-registry/aws/deprovision/iam-role/aws-deprovision-iam-role-ref.yaml
  ci-operator/step-registry/aws/provision/iam-role/OWNERS
  ci-operator/step-registry/aws/provision/iam-role/aws-provision-iam-role-commands.sh
  ci-operator/step-registry/aws/provision/iam-role/aws-provision-iam-role-ref.metadata.json
  ci-operator/step-registry/aws/provision/iam-role/aws-provision-iam-role-ref.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/byo-iam-role/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/byo-iam-role/cucushift-installer-rehearse-aws-ipi-byo-iam-role-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/byo-iam-role/cucushift-installer-rehearse-aws-ipi-byo-iam-role-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/byo-iam-role/deprovision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/byo-iam-role/deprovision/cucushift-installer-rehearse-aws-ipi-byo-iam-role-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/byo-iam-role/deprovision/cucushift-installer-rehearse-aws-ipi-byo-iam-role-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/byo-iam-role/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/byo-iam-role/provision/cucushift-installer-rehearse-aws-ipi-byo-iam-role-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/byo-iam-role/provision/cucushift-installer-rehearse-aws-ipi-byo-iam-role-provision-chain.yaml
  ci-operator/step-registry/ipi/conf/aws/byo-iam-role/OWNERS
  ci-operator/step-registry/ipi/conf/aws/byo-iam-role/ipi-conf-aws-byo-iam-role-commands.sh
  ci-operator/step-registry/ipi/conf/aws/byo-iam-role/ipi-conf-aws-byo-iam-role-ref.metadata.json
  ci-operator/step-registry/ipi/conf/aws/byo-iam-role/ipi-conf-aws-byo-iam-role-ref.yaml
Labels: lgtm, approved

#31980 Use go 1.18 for building operator
  ci-operator/config/red-hat-storage/odf-multicluster-orchestrator/red-hat-storage-odf-multicluster-orchestrator-main.yaml
  ci-operator/config/red-hat-storage/odf-multicluster-orchestrator/red-hat-storage-odf-multicluster-orchestrator-release-4.12.yaml
Labels: lgtm, approved

#32018 [knative-serving] Fix image promotion
  ci-operator/config/openshift/knative-serving/openshift-knative-serving-release-next__411.yaml
Labels: lgtm, approved

#32021 add arm01 kubeconfigs in dptp-controller-manager secret
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved

#31913 Remove the deprecated PSP for loki
  clusters/build-clusters/01_cluster/loki/loki.yaml
Labels: lgtm, approved

#31999 Increase console e2e timeout when running console-operator tests also to 3 hours
  ci-operator/config/openshift/console-operator/openshift-console-operator-master.yaml
  ci-operator/config/openshift/console-operator/openshift-console-operator-release-4.10.yaml
  ci-operator/config/openshift/console-operator/openshift-console-operator-release-4.11.yaml
  ci-operator/config/openshift/console-operator/openshift-console-operator-release-4.12.yaml
  ci-operator/config/openshift/console-operator/openshift-console-operator-release-4.13.yaml
Labels: lgtm, approved

#31168 Increase timeout for e2e-gcp-console to 3 hours
  ci-operator/config/openshift/console/openshift-console-master.yaml
  ci-operator/config/openshift/console/openshift-console-release-4.10.yaml
  ci-operator/config/openshift/console/openshift-console-release-4.11.yaml
  ci-operator/config/openshift/console/openshift-console-release-4.12.yaml
  ci-operator/config/openshift/console/openshift-console-release-4.13.yaml
Labels: lgtm, approved

#32029 supplemental-ci-images: Stop buildiong fcos-buildroot
  clusters/app.ci/supplemental-ci-images/coreos/fcos-buildroot.yaml
Labels: lgtm, approved

#31993 openstack-operator config
  ci-operator/config/openstack-k8s-operators/openstack-operator/OWNERS
  ci-operator/config/openstack-k8s-operators/openstack-operator/openstack-k8s-operators-openstack-operator-master.yaml
  ci-operator/jobs/openstack-k8s-operators/openstack-operator/OWNERS
  ci-operator/jobs/openstack-k8s-operators/openstack-operator/openstack-k8s-operators-openstack-operator-master-presubmits.yaml
  core-services/prow/02_config/openstack-k8s-operators/openstack-operator/OWNERS
  core-services/prow/02_config/openstack-k8s-operators/openstack-operator/_pluginconfig.yaml
  core-services/prow/02_config/openstack-k8s-operators/openstack-operator/_prowconfig.yaml
Labels: lgtm, approved

#31447 correct syntax on deleting SA key
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.12.yaml
  ci-operator/step-registry/upi/deprovision/gcp/upi-deprovision-gcp-commands.sh
  ci-operator/step-registry/upi/install/gcp/upi-install-gcp-commands.sh
Labels: lgtm, approved

#32035 s8n image-builder: add Go 1.19 image
  ci-operator/config/stolostron/image-builder/stolostron-image-builder-master.yaml
Labels: lgtm, approved

#32033 Remove additional configuration for AWS and GCE CSI in CCM workflows
  ci-operator/step-registry/openshift/e2e/aws/ccm/install/openshift-e2e-aws-ccm-install-workflow.yaml
  ci-operator/step-registry/openshift/e2e/aws/ccm/openshift-e2e-aws-ccm-workflow.yaml
  ci-operator/step-registry/openshift/e2e/aws/ccm/ovn-hybrid-install/openshift-e2e-aws-ccm-ovn-hybrid-install-workflow.yaml
  ci-operator/step-registry/openshift/e2e/aws/ccm/ovn-hybrid/openshift-e2e-aws-ccm-ovn-hybrid-workflow.yaml
  ci-operator/step-registry/openshift/e2e/gcp/ccm/install/openshift-e2e-gcp-ccm-install-workflow.yaml
  ci-operator/step-registry/openshift/e2e/gcp/ccm/openshift-e2e-gcp-ccm-workflow.yaml
  ci-operator/step-registry/openshift/e2e/gcp/ccm/ovn/openshift-e2e-gcp-ccm-ovn-workflow.yaml
Labels: lgtm, approved

#31966 bump timeout for logging e2e
  ci-operator/config/openshift/cluster-logging-operator/openshift-cluster-logging-operator-master.yaml
  ci-operator/config/openshift/cluster-logging-operator/openshift-cluster-logging-operator-release-5.4.yaml
  ci-operator/config/openshift/cluster-logging-operator/openshift-cluster-logging-operator-release-5.5.yaml
  ci-operator/jobs/openshift/cluster-logging-operator/openshift-cluster-logging-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-logging-operator/openshift-cluster-logging-operator-release-5.4-presubmits.yaml
  ci-operator/jobs/openshift/cluster-logging-operator/openshift-cluster-logging-operator-release-5.5-presubmits.yaml
Labels: lgtm, approved

#32031 Modify hive configuration for openstack-k8s-operators
  clusters/hive/pools/openstack-k8s-operators/install-config-sno_secret.yaml
  clusters/hive/pools/openstack-k8s-operators/openstack-k8s-operators-4-10-vexxhost-sno_clusterpool.yaml
  clusters/hive/pools/openstack-k8s-operators/openstack-k8s-operators-cdc-pod-01.yaml
Labels: lgtm, approved

#32001 Add unit and lint tests for Alibaba CCM
  ci-operator/config/openshift/cloud-provider-alibaba-cloud/openshift-cloud-provider-alibaba-cloud-master.yaml
  ci-operator/jobs/openshift/cloud-provider-alibaba-cloud/openshift-cloud-provider-alibaba-cloud-master-presubmits.yaml
Labels: lgtm, approved

#32036 add secret to pull from brew.registry.redhat.io and push to the central CI registry
  ci-operator/jobs/infra-image-mirroring.yaml
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved

#32007 Add decoding of PFLT_DOCKERCONFIG
  ci-operator/step-registry/operator-pipelines/preflight-preprod/decrypt/operator-pipelines-preflight-preprod-decrypt-commands.sh
  ci-operator/step-registry/operator-pipelines/preflight-prod/decrypt/operator-pipelines-preflight-prod-decrypt-commands.sh
Labels: lgtm, approved

#31972 bump jvm bld srvce apicurio PR e2e to 3 hours
  ci-operator/config/redhat-appstudio/jvm-build-service/redhat-appstudio-jvm-build-service-main.yaml
Labels: lgtm, approved

#32028 [telco5g] Run nightly info lane job on exact build tag
  ci-operator/step-registry/telco-bastion/setup/telco-bastion-setup-commands.sh
Labels: lgtm, approved

#32039 NO-ISSUE: Add mainteners from assisted for packet-setup step
  ci-operator/step-registry/baremetalds/packet/OWNERS
  ci-operator/step-registry/baremetalds/packet/check/baremetalds-packet-check-ref.metadata.json
  ci-operator/step-registry/baremetalds/packet/setup/baremetalds-packet-setup-ref.metadata.json
  ci-operator/step-registry/baremetalds/packet/teardown/baremetalds-packet-teardown-ref.metadata.json
Labels: lgtm, approved

#30541 Build ovn-kubernetes-{base|microshift} images
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master__okd.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.12.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.13.yaml
  core-services/image-mirroring/openshift/mapping_origin_4_12
Labels: lgtm, approved

#31935 Revert "ci-secret-generator: copy the 4.11 oc-cli binary to the build…
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
Labels: lgtm, approved

#32042 Update Scanner nightly tests to UBI 9
  ci-operator/config/stackrox/scanner/stackrox-scanner-nightlies.yaml
Labels: lgtm, approved

#32040 okd-machine-os: Update build inputs
  ci-operator/config/openshift/okd-machine-os/openshift-okd-machine-os-master.yaml
  ci-operator/config/openshift/okd-machine-os/openshift-okd-machine-os-release-4.12.yaml
  ci-operator/config/openshift/okd-machine-os/openshift-okd-machine-os-release-4.13.yaml
Labels: lgtm, approved

#32048 stolostron-image-builder Add image for nodejs-16
  ci-operator/config/stolostron/image-builder/stolostron-image-builder-master.yaml
Labels: lgtm, approved

#32049 stolostron-common-nodejs-parent Add image for nodejs-16
  ci-operator/config/stolostron/common-nodejs-parent/stolostron-common-nodejs-parent-main.yaml
  ci-operator/jobs/stolostron/common-nodejs-parent/stolostron-common-nodejs-parent-main-periodics.yaml
Labels: lgtm, approved

#32053 SDCICD-762 Machine Enablement r5d
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: lgtm, approved

#31777 stackrox: normalize openshift QA tests
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-postsubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-presubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-nightlies-postsubmits.yaml
Labels: lgtm, approved

#32030 UPI vsphere sdn migration ovn and rollback
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.11.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/ovn/sdn2ovn-rollback/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/ovn/sdn2ovn-rollback/cucushift-installer-rehearse-vsphere-upi-ovn-sdn2ovn-rollback-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/ovn/sdn2ovn-rollback/cucushift-installer-rehearse-vsphere-upi-ovn-sdn2ovn-rollback-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/ovn/sdn2ovn-rollback/deprovision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/ovn/sdn2ovn-rollback/deprovision/cucushift-installer-rehearse-vsphere-upi-ovn-sdn2ovn-rollback-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/ovn/sdn2ovn-rollback/deprovision/cucushift-installer-rehearse-vsphere-upi-ovn-sdn2ovn-rollback-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/ovn/sdn2ovn-rollback/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/ovn/sdn2ovn-rollback/provision/cucushift-installer-rehearse-vsphere-upi-ovn-sdn2ovn-rollback-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/ovn/sdn2ovn-rollback/provision/cucushift-installer-rehearse-vsphere-upi-ovn-sdn2ovn-rollback-provision-chain.yaml
Labels: lgtm, approved

#32054 [vsphere] update chain vsphere-upi-disconnected-sdn-provision to use dynamic bastion host
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/disconnected/sdn/provision/cucushift-installer-rehearse-vsphere-upi-disconnected-sdn-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/disconnected/sdn/workers-rhcos-rhel8/provision/cucushift-installer-rehearse-vsphere-upi-disconnected-sdn-workers-rhcos-rhel8-provision-chain.yaml
Labels: lgtm, approved

#32059 Rollback scanner to UBI8
  ci-operator/config/stackrox/scanner/stackrox-scanner-master.yaml
  ci-operator/config/stackrox/scanner/stackrox-scanner-nightlies.yaml
Labels: lgtm, approved

#32050 Fix loki's securityContext
  clusters/build-clusters/01_cluster/loki/loki.yaml
Labels: lgtm, approved

#32061 extend web tests timeout
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-master.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13.yaml
Labels: lgtm, approved

#32013 AWS Marketplace image for compute nodes
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.12.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/workers-marketplace/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/workers-marketplace/cucushift-installer-rehearse-aws-ipi-workers-marketplace-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/workers-marketplace/cucushift-installer-rehearse-aws-ipi-workers-marketplace-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/workers-marketplace/deprovision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/workers-marketplace/deprovision/cucushift-installer-rehearse-aws-ipi-workers-marketplace-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/workers-marketplace/deprovision/cucushift-installer-rehearse-aws-ipi-workers-marketplace-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/workers-marketplace/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/workers-marketplace/provision/cucushift-installer-rehearse-aws-ipi-workers-marketplace-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/workers-marketplace/provision/cucushift-installer-rehearse-aws-ipi-workers-marketplace-provision-chain.yaml
  ci-operator/step-registry/ipi/conf/aws/marketplace/OWNERS
  ci-operator/step-registry/ipi/conf/aws/marketplace/ipi-conf-aws-marketplace-commands.sh
  ci-operator/step-registry/ipi/conf/aws/marketplace/ipi-conf-aws-marketplace-ref.metadata.json
  ci-operator/step-registry/ipi/conf/aws/marketplace/ipi-conf-aws-marketplace-ref.yaml
Labels: lgtm, approved

#32063 ROX-12481: Mirror golang 1.17.12 image.
  core-services/image-mirroring/stackrox/mapping_supplemental_ci_images_stackrox_base_images
Labels: lgtm, approved

#31917 MGMT-11348: Assisted installer multi arch images
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-master__edge.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-master-postsubmits.yaml
  ci-operator/step-registry/assisted/tools/multi-arch/OWNERS
  ci-operator/step-registry/assisted/tools/multi-arch/assisted-tools-multi-arch-workflow.metadata.json
  ci-operator/step-registry/assisted/tools/multi-arch/assisted-tools-multi-arch-workflow.yaml
  ci-operator/step-registry/assisted/tools/multi-arch/publish/OWNERS
  ci-operator/step-registry/assisted/tools/multi-arch/publish/assisted-tools-multi-arch-publish-commands.sh
  ci-operator/step-registry/assisted/tools/multi-arch/publish/assisted-tools-multi-arch-publish-ref.metadata.json
  ci-operator/step-registry/assisted/tools/multi-arch/publish/assisted-tools-multi-arch-publish-ref.yaml
  ci-operator/step-registry/assisted/tools/multi-arch/setup/OWNERS
  ci-operator/step-registry/assisted/tools/multi-arch/setup/assisted-tools-multi-arch-setup-commands.sh
  ci-operator/step-registry/assisted/tools/multi-arch/setup/assisted-tools-multi-arch-setup-ref.metadata.json
  ci-operator/step-registry/assisted/tools/multi-arch/setup/assisted-tools-multi-arch-setup-ref.yaml
Labels: lgtm, approved

#32070 add the ci-pull-credentials secret to arm01 cluster
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved

#31864 Add netavark-dhcp-proxy
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/containers/netavark-dhcp-proxy/_pluginconfig.yaml
  core-services/prow/02_config/containers/netavark-dhcp-proxy/_prowconfig.yaml
Labels: lgtm, approved

#32071 Revert "[CVP-3094] Add cluster pools for OCP v4.12 (#31996)"
  clusters/hive/pools/cvp/cvp-ocp-4-12-amd64-aws-eu-west-3_clusterpool.yaml
  clusters/hive/pools/cvp/install-config-aws-eu-west-3_secret.yaml
Labels: lgtm, approved

#32066 Remove 'keep-manifest-list' option from stackrox mirroring
  ci-operator/jobs/infra-image-mirroring.yaml
Labels: lgtm, approved

#31581 Add nutanix qe ci jobs
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.11.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/nutanix/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/nutanix/ipi/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/nutanix/ipi/cucushift-installer-rehearse-nutanix-ipi-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/nutanix/ipi/cucushift-installer-rehearse-nutanix-ipi-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/nutanix/ipi/deprovision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/nutanix/ipi/deprovision/cucushift-installer-rehearse-nutanix-ipi-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/nutanix/ipi/deprovision/cucushift-installer-rehearse-nutanix-ipi-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/nutanix/ipi/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/nutanix/ipi/provision/cucushift-installer-rehearse-nutanix-ipi-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/nutanix/ipi/provision/cucushift-installer-rehearse-nutanix-ipi-provision-chain.yaml
  ci-operator/step-registry/ipi/conf/nutanix/context/ipi-conf-nutanix-context-commands.sh
Labels: lgtm, approved

#31909 don't run expensive etcd tests on doc changes
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-master.yaml
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.10.yaml
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.11.yaml
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.12.yaml
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.13.yaml
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.8.yaml
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.9.yaml
  ci-operator/jobs/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.10-presubmits.yaml
  ci-operator/jobs/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.11-presubmits.yaml
  ci-operator/jobs/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.13-presubmits.yaml
  ci-operator/jobs/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.8-presubmits.yaml
  ci-operator/jobs/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.9-presubmits.yaml
Labels: lgtm, approved

#32005 MGMT-11348: Build and publish multi-arch images for assisted agent
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master__edge.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master-postsubmits.yaml
Labels: lgtm, approved

#31933 NO-ISSUE: Do not provision space for home in assisted-metal
  ci-operator/step-registry/assisted/common/setup/prepare/assisted-common-setup-prepare-commands.sh
Labels: lgtm, approved

#32009 Go back to using UNRESOLVED_CONFIG method for test analyzer
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.12.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: lgtm, approved

#32074 Revert "add the ci-pull-credentials secret to arm01 cluster"
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved

#31897 Hypershift: Make node counts for mgmt cluster more appropriate
  ci-operator/step-registry/hypershift/aws/conformance/hypershift-aws-conformance-workflow.yaml
  ci-operator/step-registry/hypershift/aws/e2e/nested/hypershift-aws-e2e-nested-workflow.yaml
  ci-operator/step-registry/hypershift/aws/setup-nested-management-cluster/hypershift-aws-setup-nested-management-cluster-chain.yaml
Labels: lgtm, approved

#32075 Remove configs for `smg247/ci-docs`
  ci-operator/config/smg247/ci-docs/OWNERS
  ci-operator/config/smg247/ci-docs/smg247-ci-docs-master.yaml
  ci-operator/jobs/smg247/ci-docs/OWNERS
  ci-operator/jobs/smg247/ci-docs/smg247-ci-docs-master-postsubmits.yaml
  ci-operator/jobs/smg247/ci-docs/smg247-ci-docs-master-presubmits.yaml
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/smg247/_pluginconfig.yaml
  core-services/prow/02_config/smg247/ci-docs/OWNERS
  core-services/prow/02_config/smg247/ci-docs/_pluginconfig.yaml
  core-services/prow/02_config/smg247/ci-docs/_prowconfig.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: lgtm, approved

#32077 Change odo checks names
  core-services/prow/02_config/redhat-developer/odo/_prowconfig.yaml
Labels: lgtm, approved

#32079 Fix the kubevirt-must-gather-e2e-gcp test
  ci-operator/config/kubevirt/must-gather/kubevirt-must-gather-main.yaml
Labels: lgtm, approved

#32073 openstack: Generate install-config with default values
  ci-operator/step-registry/openstack/conf/installconfig/openstack-conf-installconfig-commands.sh
  ci-operator/step-registry/upi/install/openstack/inventory/upi-install-openstack-inventory-commands.sh
  ci-operator/step-registry/upi/install/openstack/upi-install-openstack-commands.sh
Labels: lgtm, approved

#32078 Removes cos-85-lts integration tests
  ci-operator/config/stackrox/collector/stackrox-collector-master.yaml
  ci-operator/jobs/stackrox/collector/stackrox-collector-master-postsubmits.yaml
  ci-operator/jobs/stackrox/collector/stackrox-collector-master-presubmits.yaml
Labels: lgtm, approved

#32034 Pin OCP version for HyperShift/Kubevirt presubmits to 4.11
  ci-operator/config/openshift/hypershift/openshift-hypershift-main.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-main__periodics.yaml
Labels: lgtm, approved

#31873 OCPBUGS-706: IBMCloud: Retry ibmcloud commands
  ci-operator/step-registry/ipi/ibmcloud/gather-resources/ipi-ibmcloud-gather-resources-commands.sh
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-low

#31895 MGMT-11730: allow users to inject user_data in packet-setup step
  ci-operator/step-registry/baremetalds/packet/setup/baremetalds-packet-setup-commands.sh
  ci-operator/step-registry/baremetalds/packet/setup/baremetalds-packet-setup-ref.yaml
Labels: lgtm, approved

#32026 Use a dedicated privileged namespace for debug commands
  ci-operator/step-registry/network/mtu-migration/network-mtu-migration-commands.sh
Labels: lgtm, approved

#32090 add the sdn version of the azure-techpreview workflow
  ci-operator/config/openshift/release/openshift-release-master__ci-4.12.yaml
Labels: lgtm, approved

#31942 join build farm: update doc for kubeconfig
  clusters/JoinBuildFarm.md
Labels: lgtm, approved, tide/merge-method-squash

#32043 stackrox: avoid image copies for reqd jobs
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-presubmits.yaml
Labels: lgtm, approved

#32098 Revert "stackrox: avoid image copies for reqd jobs"
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-presubmits.yaml
Labels: lgtm, approved

#32060 add 4.12 e2e test for azure-ipi-private-sdn and gcp-upi-private-xpn-sdn
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
Labels: lgtm, approved

#32087 medik8s/nmo: use a ns != default for operator deployment
  ci-operator/config/medik8s/node-maintenance-operator/medik8s-node-maintenance-operator-main.yaml
Labels: lgtm, approved

#30881 OCPQE-11259: Add build info for RELEASE_IMAGE_LATEST which is used in upgrade
  ci-operator/step-registry/cucushift/upgrade/helper-service/OWNERS
  ci-operator/step-registry/cucushift/upgrade/helper-service/build-info/OWNERS
  ci-operator/step-registry/cucushift/upgrade/helper-service/build-info/cucushift-upgrade-helper-service-build-info-commands.sh
  ci-operator/step-registry/cucushift/upgrade/helper-service/build-info/cucushift-upgrade-helper-service-build-info-ref.metadata.json
  ci-operator/step-registry/cucushift/upgrade/helper-service/build-info/cucushift-upgrade-helper-service-build-info-ref.yaml
  ci-operator/step-registry/openshift/upgrade/qe/test/disconnected/openshift-upgrade-qe-test-disconnected-chain.yaml
  ci-operator/step-registry/openshift/upgrade/qe/test/openshift-upgrade-qe-test-chain.yaml
Labels: lgtm, approved

#32101 Stolostron: Search API required jobs
  ci-operator/config/stolostron/search-api/stolostron-search-api-release-2.4.yaml
  ci-operator/config/stolostron/search-api/stolostron-search-api-release-2.5.yaml
  ci-operator/config/stolostron/search-api/stolostron-search-api-release-2.6.yaml
  ci-operator/config/stolostron/search-api/stolostron-search-api-release-2.7.yaml
  ci-operator/jobs/stolostron/search-api/stolostron-search-api-release-2.4-presubmits.yaml
  ci-operator/jobs/stolostron/search-api/stolostron-search-api-release-2.5-presubmits.yaml
  ci-operator/jobs/stolostron/search-api/stolostron-search-api-release-2.6-presubmits.yaml
  ci-operator/jobs/stolostron/search-api/stolostron-search-api-release-2.7-presubmits.yaml
  core-services/prow/02_config/stolostron/search-api/_prowconfig.yaml
Labels: lgtm, approved

#32102 [CIGolang]add redirection for mirror2.openshift.com
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-master.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13.yaml
Labels: lgtm, approved

#32094 Trivial fix for openstack-k8s-operators clusterpool
  clusters/hive/pools/openstack-k8s-operators/openstack-k8s-operators-4-10-vexxhost-sno_clusterpool.yaml
Labels: lgtm, approved
