Repository openshift/release, pull requests merged in 2022-02, with the labels that each got.

#25848 ci-tools: use centos stream8 instead of centos:8
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
  clusters/app.ci/supplemental-ci-images/ci-tools-build-root.yaml
Labels: lgtm, approved

#25849 ci-tools: use centos stream8 instead of centos:8
  clusters/app.ci/supplemental-ci-images/ci-tools-build-root.yaml
Labels: lgtm, approved

#25844 Bug 2047799: Fix quoting error when trying to extract RHCOS_AMI
  ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#25758 Stop IBM Cloud monitoringpvc setup
  ci-operator/step-registry/ipi/conf/ibmcloud/ipi-conf-ibmcloud-chain.yaml
Labels: lgtm, approved

#25852 fix: change the reporting channel for this job
  ci-operator/jobs/redhat-appstudio/infra-deployments/redhat-appstudio-infra-deployments-main-periodics.yaml
Labels: lgtm, approved

#25855 MGMT-9102 - Change assisted-test-infra image on release-ocm-2.4 branch
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.4.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.4-periodics.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.4-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.4-presubmits.yaml
Labels: lgtm, approved

#24805 Add openshift-metal3/terraform-provider-ironic repo prow integration
  ci-operator/config/openshift-metal3/terraform-provider-ironic/OWNERS
  ci-operator/config/openshift-metal3/terraform-provider-ironic/openshift-metal3-terraform-provider-ironic-master.yaml
  ci-operator/jobs/openshift-metal3/terraform-provider-ironic/OWNERS
  ci-operator/jobs/openshift-metal3/terraform-provider-ironic/openshift-metal3-terraform-provider-ironic-master-presubmits.yaml
  core-services/prow/02_config/openshift-metal3/terraform-provider-ironic/OWNERS
  core-services/prow/02_config/openshift-metal3/terraform-provider-ironic/_pluginconfig.yaml
  core-services/prow/02_config/openshift-metal3/terraform-provider-ironic/_prowconfig.yaml
Labels: lgtm, approved

#25858 dev-scripts: refresh owners list
  ci-operator/config/openshift-metal3/dev-scripts/OWNERS
Labels: lgtm, approved

#25860 NO-ISSUE: Set new packet plan with more MEMORY for olm test
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
Labels: lgtm, approved

#25824 fix typo
  ci-operator/config/integr8ly/integreatly-operator/integr8ly-integreatly-operator-MGDAPI-3256-working.yaml
Labels: lgtm, approved

#25846 Fix missing release branch package name
  ci-operator/config/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-release-4.10.yaml
Labels: lgtm, approved

#25851 Migrate to machine-api-provider-powervs from cluster-api-powervs
  ci-operator/config/openshift/machine-api-provider-powervs/OWNERS
  ci-operator/config/openshift/machine-api-provider-powervs/openshift-machine-api-provider-powervs-main.yaml
  ci-operator/jobs/openshift/machine-api-provider-powervs/OWNERS
  ci-operator/jobs/openshift/machine-api-provider-powervs/openshift-machine-api-provider-powervs-main-postsubmits.yaml
  ci-operator/jobs/openshift/machine-api-provider-powervs/openshift-machine-api-provider-powervs-main-presubmits.yaml
Labels: lgtm, approved

#25864 Add packet check for old cluster profile namely packet
  ci-operator/config/openshift-metal3/dev-scripts/openshift-metal3-dev-scripts-master__packetcheck.yaml
  ci-operator/jobs/openshift-metal3/dev-scripts/openshift-metal3-dev-scripts-master-periodics.yaml
Labels: lgtm, approved

#25706 o/release: make several presubmits conditionally triggered
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
Labels: lgtm, approved

#25862 Knative Eventing v1.2 jobs
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v1.2__47.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v1.2__48.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v1.2__49.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v1.2-periodics.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v1.2-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v1.2-presubmits.yaml
  core-services/image-mirroring/knative/mapping_knative_v1_2_quay
Labels: lgtm, approved

#25870 Disable auto-upgrade on b01
  ci-operator/jobs/infra-periodics.yaml
Labels: lgtm, approved

#25875 Modernize CentOS usage under clusters/
  clusters/app.ci/ci-rpms/artifacts-rpms.yaml
  clusters/app.ci/supplemental-ci-images/azure/base-images/ci-base.yaml
  clusters/app.ci/supplemental-ci-images/azure/base-images/test-base.yaml
  clusters/app.ci/supplemental-ci-images/content-mirror/pipeline.yaml
  clusters/build-clusters/01_cluster/ci/_origin-release-build/golang-1.10/Dockerfile
  clusters/build-clusters/01_cluster/ci/_origin-release-build/golang-1.11/Dockerfile
  clusters/build-clusters/01_cluster/ci/_origin-release-build/golang-1.12/Dockerfile
  clusters/build-clusters/01_cluster/ci/_origin-release-build/golang-1.13/Dockerfile
  clusters/build-clusters/01_cluster/ci/_origin-release-build/golang-1.14/Dockerfile
  clusters/build-clusters/01_cluster/ci/_origin-release-build/golang-1.15/Dockerfile
  clusters/build-clusters/01_cluster/ci/_origin-release-build/golang-1.16/Dockerfile
  clusters/build-clusters/01_cluster/ci/_origin-release-build/golang-1.17/Dockerfile
  clusters/build-clusters/01_cluster/ci/_origin-release-build/golang-1.8/Dockerfile
  clusters/build-clusters/01_cluster/ci/_origin-release-build/golang-1.9/Dockerfile
  clusters/build-clusters/01_cluster/ci/origin-release_pipeline_template.yaml
  clusters/build-clusters/arm01/supplemental-ci-images/content-mirror.yaml
Labels: lgtm, approved

#25877 Remove jobs for unsupported Knative Eventing & Kafka v0.24
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.24__47.yaml
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.24__48.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.24__47.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.24__48.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.24-periodics.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.24-postsubmits.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.24-presubmits.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.24-periodics.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.24-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.24-presubmits.yaml
  core-services/image-mirroring/knative/mapping_knative_v0_24_quay
Labels: lgtm, approved

#25767 ocm: update app backend to go 1.17
  ci-operator/config/stolostron/multicloud-integrations/stolostron-multicloud-integrations-main.yaml
  ci-operator/config/stolostron/multicloud-integrations/stolostron-multicloud-integrations-release-2.4.yaml
  ci-operator/config/stolostron/multicloud-integrations/stolostron-multicloud-integrations-release-2.5.yaml
  ci-operator/config/stolostron/multicloud-operators-application/stolostron-multicloud-operators-application-main.yaml
  ci-operator/config/stolostron/multicloud-operators-application/stolostron-multicloud-operators-application-release-2.4.yaml
  ci-operator/config/stolostron/multicloud-operators-application/stolostron-multicloud-operators-application-release-2.5.yaml
  ci-operator/config/stolostron/multicloud-operators-channel/stolostron-multicloud-operators-channel-main.yaml
  ci-operator/config/stolostron/multicloud-operators-channel/stolostron-multicloud-operators-channel-release-2.4.yaml
  ci-operator/config/stolostron/multicloud-operators-channel/stolostron-multicloud-operators-channel-release-2.5.yaml
  ci-operator/config/stolostron/multicloud-operators-deployable/stolostron-multicloud-operators-deployable-main.yaml
  ci-operator/config/stolostron/multicloud-operators-deployable/stolostron-multicloud-operators-deployable-release-2.4.yaml
  ci-operator/config/stolostron/multicloud-operators-placementrule/stolostron-multicloud-operators-placementrule-main.yaml
  ci-operator/config/stolostron/multicloud-operators-placementrule/stolostron-multicloud-operators-placementrule-release-2.4.yaml
  ci-operator/config/stolostron/multicloud-operators-subscription-release/stolostron-multicloud-operators-subscription-release-main.yaml
  ci-operator/config/stolostron/multicloud-operators-subscription-release/stolostron-multicloud-operators-subscription-release-release-2.4.yaml
  ci-operator/config/stolostron/multicloud-operators-subscription/stolostron-multicloud-operators-subscription-main.yaml
  ci-operator/config/stolostron/multicloud-operators-subscription/stolostron-multicloud-operators-subscription-release-2.4.yaml
  ci-operator/config/stolostron/multicloud-operators-subscription/stolostron-multicloud-operators-subscription-release-2.5.yaml
Labels: lgtm, approved

#25872 Use bigger machines for OLM jobs
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.4.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-master.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.4.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-cloud_hotfix_releases.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.4.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
Labels: lgtm, approved

#25878 change job schedule for 4.11 jobs s390x
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.11-upgrade-from-nightly-4.10.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.11.yaml
  ci-operator/jobs/openshift/multiarch/openshift-multiarch-master-periodics.yaml
Labels: lgtm, approved

#25696 Move router packet jobs to new equinix profile
  ci-operator/config/openshift/router/openshift-router-master.yaml
  ci-operator/config/openshift/router/openshift-router-release-4.10.yaml
  ci-operator/config/openshift/router/openshift-router-release-4.11.yaml
  ci-operator/config/openshift/router/openshift-router-release-4.6.yaml
  ci-operator/config/openshift/router/openshift-router-release-4.7.yaml
  ci-operator/config/openshift/router/openshift-router-release-4.8.yaml
  ci-operator/config/openshift/router/openshift-router-release-4.9.yaml
  ci-operator/jobs/openshift/router/openshift-router-master-presubmits.yaml
  ci-operator/jobs/openshift/router/openshift-router-release-4.10-presubmits.yaml
  ci-operator/jobs/openshift/router/openshift-router-release-4.11-presubmits.yaml
  ci-operator/jobs/openshift/router/openshift-router-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/router/openshift-router-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/router/openshift-router-release-4.8-presubmits.yaml
  ci-operator/jobs/openshift/router/openshift-router-release-4.9-presubmits.yaml
Labels: lgtm, approved

#25884 Bump cluster-nfd-operator master to 4.11
  ci-operator/config/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-master.yaml
Labels: lgtm, approved

#25886 Adding e2e tests for the knative broker
  ci-operator/config/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.2__49.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.2-periodics.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.2-presubmits.yaml
Labels: lgtm, approved

#25891 MGMT-9102: Remove unwanted tests and fix some release-ocm-2.4 jobs.
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.4.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.4.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.4-presubmits.yaml
Labels: lgtm, approved

#25887 set up prometheus alerts for qe-private-deck
  clusters/app.ci/prow-monitoring/mixins/_prometheus/ci_absent_alerts.libsonnet
  clusters/app.ci/prow-monitoring/mixins/prometheus_out/prometheus-prow-rules_prometheusrule.yaml
  clusters/app.ci/prow-monitoring/qe-private-deck_servicemonitor.yaml
Labels: lgtm, approved

#25888 Update openshift-elasticsearch-operator-master.yaml
  ci-operator/config/openshift/elasticsearch-operator/openshift-elasticsearch-operator-master.yaml
Labels: lgtm, approved

#25898 assisted-installer-agent: Move to stream8 due to centos8 EOL
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.4.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.4__stolostron.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.5__stolostron.yaml
Labels: lgtm, approved

#25889 state typo
  ci-operator/jobs/redhat-et/microshift/redhat-et-microshift-main-periodics.yaml
Labels: lgtm, approved

#25899 assisted-installer: Update to stream8 due to centos8 EOL
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.4.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.4__stolostron.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.5__stolostron.yaml
Labels: lgtm, approved

#25664 Change owners in the prpqr-aggregator step from the step registry
  ci-operator/step-registry/openshift/release/analysis/prpqr-aggregator/OWNERS
  ci-operator/step-registry/openshift/release/analysis/prpqr-aggregator/openshift-release-analysis-prpqr-aggregator-commands.sh
  ci-operator/step-registry/openshift/release/analysis/prpqr-aggregator/openshift-release-analysis-prpqr-aggregator-ref.metadata.json
Labels: lgtm, approved

#25904 Update openshift-elasticsearch-operator-master.yaml
  ci-operator/config/openshift/elasticsearch-operator/openshift-elasticsearch-operator-master.yaml
Labels: lgtm, approved

#25804 enable customizing provisioned packet OS
  ci-operator/step-registry/baremetalds/packet/setup/baremetalds-packet-setup-commands.sh
  ci-operator/step-registry/baremetalds/packet/setup/baremetalds-packet-setup-ref.yaml
Labels: lgtm, approved

#25871 Use vault repo only for Centos 8
  ci-operator/step-registry/baremetalds/packet/setup/baremetalds-packet-setup-commands.sh
Labels: lgtm, approved

#25907 Adding experimental knative eventing-kafka 1.2 jobs
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v1.2__47.yaml
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v1.2__48.yaml
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v1.2__49.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v1.2-postsubmits.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v1.2-presubmits.yaml
Labels: lgtm, approved

#25908 Enable approver for power vs machine api provider
  ci-operator/config/openshift/cluster-api-provider-powervs/openshift-cluster-api-provider-powervs-main.yaml
  ci-operator/config/openshift/machine-api-provider-powervs/openshift-machine-api-provider-powervs-main.yaml
  ci-operator/jobs/openshift/cluster-api-provider-powervs/openshift-cluster-api-provider-powervs-main-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-provider-powervs/openshift-machine-api-provider-powervs-main-presubmits.yaml
  core-services/prow/02_config/openshift/machine-api-provider-powervs/OWNERS
  core-services/prow/02_config/openshift/machine-api-provider-powervs/_pluginconfig.yaml
  core-services/prow/02_config/openshift/machine-api-provider-powervs/_prowconfig.yaml
Labels: lgtm, approved

#25909 Onboarding medik8s/node-maintenance-operator
  ci-operator/config/medik8s/node-maintenance-operator/OWNERS
  ci-operator/config/medik8s/node-maintenance-operator/medik8s-node-maintenance-operator-master.yaml
  ci-operator/jobs/medik8s/node-maintenance-operator/OWNERS
  ci-operator/jobs/medik8s/node-maintenance-operator/medik8s-node-maintenance-operator-master-presubmits.yaml
  core-services/prow/02_config/medik8s/node-maintenance-operator/OWNERS
  core-services/prow/02_config/medik8s/node-maintenance-operator/_pluginconfig.yaml
  core-services/prow/02_config/medik8s/node-maintenance-operator/_prowconfig.yaml
Labels: lgtm, approved

#25913 Remove rebase merge method for CAPZ
  core-services/prow/02_config/openshift/cluster-api-provider-azure/_prowconfig.yaml
Labels: lgtm, approved

#25885 Use techpreview feature set for CCM tests
  ci-operator/step-registry/ccm/conf/apply-feature-gate/ccm-conf-apply-feature-gate-commands.sh
  ci-operator/step-registry/ccm/conf/pre-create-feature-gate/OWNERS
  ci-operator/step-registry/ccm/conf/pre-create-feature-gate/ccm-conf-pre-create-feature-gate-commands.sh
  ci-operator/step-registry/ccm/conf/pre-create-feature-gate/ccm-conf-pre-create-feature-gate-ref.metadata.json
  ci-operator/step-registry/ccm/conf/pre-create-feature-gate/ccm-conf-pre-create-feature-gate-ref.yaml
  ci-operator/step-registry/openshift/e2e/aws/ccm/install/openshift-e2e-aws-ccm-install-workflow.yaml
  ci-operator/step-registry/openshift/e2e/aws/ccm/ovn-hybrid-install/openshift-e2e-aws-ccm-ovn-hybrid-install-workflow.yaml
  ci-operator/step-registry/openshift/e2e/azure/ccm/install/openshift-e2e-azure-ccm-install-workflow.yaml
  ci-operator/step-registry/openshift/e2e/azure/ccm/ovn-hybrid-install/openshift-e2e-azure-ccm-ovn-hybrid-install-workflow.yaml
  ci-operator/step-registry/openshift/e2e/gcp/ccm/install/openshift-e2e-gcp-ccm-install-workflow.yaml
  ci-operator/step-registry/openshift/e2e/openstack/ccm/install/openshift-e2e-openstack-ccm-install-workflow.yaml
  ci-operator/step-registry/openshift/e2e/vsphere/ccm/install/openshift-e2e-vsphere-ccm-install-workflow.yaml
Labels: lgtm, approved

#25903 ocm :added dco for search-v2-operator
  core-services/prow/02_config/stolostron/search-v2-operator/OWNERS
  core-services/prow/02_config/stolostron/search-v2-operator/_pluginconfig.yaml
  core-services/prow/02_config/stolostron/search-v2-operator/_prowconfig.yaml
Labels: lgtm, approved

#25910 fix leftovers of packet-profile 'packet' in assisted jobs
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.4.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-periodics.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.4-periodics.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.4-presubmits.yaml
Labels: lgtm, approved

#25924 updated volume mount secretName
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: lgtm, approved

#25861 Openstack: Add 4.11 periodics
  ci-operator/config/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main__periodic-4.11-upgrade-from-stable-4.10.yaml
  ci-operator/config/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main__periodic-4.11.yaml
  ci-operator/jobs/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main-periodics.yaml
Labels: lgtm, approved

#25925 remove run_if_changed condition for rbac query proxy component
  ci-operator/config/stolostron/multicluster-observability-operator/OWNERS
  ci-operator/config/stolostron/multicluster-observability-operator/stolostron-multicluster-observability-operator-release-2.4.yaml
  ci-operator/config/stolostron/multicluster-observability-operator/stolostron-multicluster-observability-operator-release-2.5.yaml
  ci-operator/jobs/stolostron/multicluster-observability-operator/OWNERS
  ci-operator/jobs/stolostron/multicluster-observability-operator/stolostron-multicluster-observability-operator-release-2.4-postsubmits.yaml
  ci-operator/jobs/stolostron/multicluster-observability-operator/stolostron-multicluster-observability-operator-release-2.5-postsubmits.yaml
Labels: lgtm, approved

#25921 Use NFD for OCP 4.9
  ci-operator/config/openshift-psap/special-resource-operator/openshift-psap-special-resource-operator-master.yaml
Labels: lgtm, approved

#25672 Update OWNERS for PSAP
  core-services/image-mirroring/openshift-psap/OWNERS
Labels: lgtm, approved

#25917 CI-ARTIFACTS update NFD to run nightly master
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-master__nfd.yaml
  ci-operator/jobs/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-master-periodics.yaml
Labels: lgtm, approved

#25928 ci-operator/step-registry/openshift/credentials-request-freeze: Add optional CLOUD variable
  ci-operator/step-registry/openshift/credentials-request-freeze/openshift-credentials-request-freeze-commands.sh
Labels: lgtm, approved

#25830 add mrunalp, sunilcio, and rphillips to backport and cherry-pick-approved
  core-services/prow/02_config/openshift/kubernetes/_pluginconfig.yaml
Labels: lgtm, approved

#25900 ocm - Remove Sonar from Prow (GRC)
  ci-operator/config/stolostron/config-policy-controller/stolostron-config-policy-controller-main.yaml
  ci-operator/config/stolostron/config-policy-controller/stolostron-config-policy-controller-release-2.5.yaml
  ci-operator/jobs/stolostron/config-policy-controller/stolostron-config-policy-controller-main-presubmits.yaml
  ci-operator/jobs/stolostron/config-policy-controller/stolostron-config-policy-controller-release-2.5-postsubmits.yaml
  ci-operator/jobs/stolostron/config-policy-controller/stolostron-config-policy-controller-release-2.5-presubmits.yaml
Labels: lgtm, approved

#25661 Removing redundant images for NFD and SRO.
  core-services/image-mirroring/openshift-psap/mapping_openshift-psap_4_10
Labels: lgtm, approved

#25934 [vsphere] reenabling VMC leases after vSAN outage resolved
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: lgtm, approved

#25933 coreos-assembler: skip jobs if only docs change
  ci-operator/jobs/coreos/coreos-assembler/coreos-coreos-assembler-main-presubmits.yaml
Labels: lgtm, approved

#25936 Revert "Make b02-dry presubmit optional while b02 is in trouble"
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
Labels: lgtm, approved

#25939 Hive: build with go 1.17
  ci-operator/config/openshift/hive/openshift-hive-master.yaml
Labels: lgtm, approved

#25937 Bumping to Golang 17 and CentOS Stream 8
  ci-operator/config/openshift/release-controller/openshift-release-controller-master.yaml
Labels: lgtm, approved

#25943 onboard prometheus operator
  ci-operator/config/stolostron/prometheus-operator/OWNERS
  ci-operator/config/stolostron/prometheus-operator/stolostron-prometheus-operator-release-2.5.yaml
  ci-operator/jobs/stolostron/prometheus-operator/OWNERS
  ci-operator/jobs/stolostron/prometheus-operator/stolostron-prometheus-operator-release-2.5-postsubmits.yaml
  ci-operator/jobs/stolostron/prometheus-operator/stolostron-prometheus-operator-release-2.5-presubmits.yaml
Labels: lgtm, approved

#25879 Updating OCP on RHV team structure
  OWNERS_ALIASES
Labels: lgtm, approved

#25951 medik8s/nmo: Switch to AllNamespace install mode
  ci-operator/config/medik8s/node-maintenance-operator/medik8s-node-maintenance-operator-master.yaml
Labels: lgtm, approved

#25949 Add final version of knative eventing kafka 1.2 jobs
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v1.2__47.yaml
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v1.2__48.yaml
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v1.2__49.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v1.2-periodics.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v1.2-presubmits.yaml
Labels: lgtm, approved

#25247 Add CI tests and image for hw-event-proxy-operator
  ci-operator/config/redhat-cne/hw-event-proxy-operator/OWNERS
  ci-operator/config/redhat-cne/hw-event-proxy-operator/redhat-cne-hw-event-proxy-operator-main.yaml
  ci-operator/jobs/redhat-cne/hw-event-proxy-operator/OWNERS
  ci-operator/jobs/redhat-cne/hw-event-proxy-operator/redhat-cne-hw-event-proxy-operator-main-postsubmits.yaml
  ci-operator/jobs/redhat-cne/hw-event-proxy-operator/redhat-cne-hw-event-proxy-operator-main-presubmits.yaml
  core-services/image-mirroring/openshift/mapping_origin_4_11
  core-services/prow/02_config/redhat-cne/hw-event-proxy-operator/OWNERS
  core-services/prow/02_config/redhat-cne/hw-event-proxy-operator/_pluginconfig.yaml
  core-services/prow/02_config/redhat-cne/hw-event-proxy-operator/_prowconfig.yaml
Labels: lgtm, approved

#25799 Fix config for 4.11 prevalidation jobs
  ci-operator/config/openshift/ironic-agent-image/openshift-ironic-agent-image-main__prevalidation.yaml
  ci-operator/config/openshift/ironic-image/openshift-ironic-image-master__prevalidation.yaml
Labels: lgtm, approved

#25817 Enable plugins-supply-chain-change check
  ci-operator/config/openshift/jenkins/openshift-jenkins-master.yaml
  ci-operator/jobs/openshift/jenkins/openshift-jenkins-master-presubmits.yaml
Labels: lgtm, approved

#25957 add nginx image to kubevirt flow
  ci-operator/config/kubevirt-ui/kubevirt-plugin/kubevirt-ui-kubevirt-plugin-main.yaml
Labels: lgtm, approved

#25256 Bug 2038405: Fix mirror.openshift.com auth method
  ci-operator/step-registry/workers-rhel/repos/workers-rhel-repos-commands.sh
  ci-operator/step-registry/workers-rhel/repos/workers-rhel-repos-ref.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#25645 Move oc packet jobs to new equinix profile
  ci-operator/config/openshift/oc/openshift-oc-master.yaml
  ci-operator/config/openshift/oc/openshift-oc-release-4.10.yaml
  ci-operator/config/openshift/oc/openshift-oc-release-4.11.yaml
  ci-operator/config/openshift/oc/openshift-oc-release-4.7.yaml
  ci-operator/config/openshift/oc/openshift-oc-release-4.8.yaml
  ci-operator/config/openshift/oc/openshift-oc-release-4.9.yaml
  ci-operator/jobs/openshift/oc/openshift-oc-master-presubmits.yaml
  ci-operator/jobs/openshift/oc/openshift-oc-release-4.10-presubmits.yaml
  ci-operator/jobs/openshift/oc/openshift-oc-release-4.11-presubmits.yaml
  ci-operator/jobs/openshift/oc/openshift-oc-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/oc/openshift-oc-release-4.8-presubmits.yaml
  ci-operator/jobs/openshift/oc/openshift-oc-release-4.9-presubmits.yaml
Labels: lgtm, approved

#25670 Move kubernetes IPI packet jobs to new equinix profile
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-master.yaml
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-release-4.10.yaml
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-release-4.11.yaml
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-release-4.7.yaml
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-release-4.8.yaml
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-release-4.9.yaml
  ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-master-presubmits.yaml
  ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-release-4.10-presubmits.yaml
  ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-release-4.11-presubmits.yaml
  ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-release-4.8-presubmits.yaml
  ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-release-4.9-presubmits.yaml
Labels: lgtm, approved

#25963 fix typo in the aggregatior step arguments
  ci-operator/step-registry/openshift/release/analysis/prpqr-aggregator/openshift-release-analysis-prpqr-aggregator-commands.sh
Labels: lgtm, approved

#25932 ci-operator: add jobs for rhcos-4.10 branch of coreos-assembler
  ci-operator/config/coreos/coreos-assembler/coreos-coreos-assembler-rhcos-4.10.yaml
  ci-operator/jobs/coreos/coreos-assembler/coreos-coreos-assembler-rhcos-4.10-presubmits.yaml
Labels: lgtm, approved

#25967 release-controller: add art-suffix flag
  clusters/app.ci/release-controller/deploy-ocp-arm64-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-arm64-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-multi-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-multi-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-ppc64le-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-ppc64le-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-s390x-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-s390x-priv-controller.yaml
  hack/generators/release-controllers/content/osd_rc_deployments.py
  hack/generators/release-controllers/generate-release-controllers.py
Labels: lgtm, approved

#25969 Bumping up to Golang 1.17
  ci-operator/config/openshift/release-controller/openshift-release-controller-master.yaml
Labels: lgtm, approved

#25965 Rename eventing-kafka 1.2 forward compatibility job
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v1.2__49.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v1.2-presubmits.yaml
Labels: lgtm, approved

#25972 Revert "release-controller: add art-suffix flag"
  clusters/app.ci/release-controller/deploy-ocp-arm64-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-arm64-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-multi-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-multi-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-ppc64le-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-ppc64le-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-s390x-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-s390x-priv-controller.yaml
  hack/generators/release-controllers/content/osd_rc_deployments.py
  hack/generators/release-controllers/generate-release-controllers.py
Labels: lgtm, approved

#25973 fix image name
  ci-operator/config/stolostron/prometheus-operator/stolostron-prometheus-operator-release-2.5.yaml
Labels: lgtm, approved

#25944 Updated search-e2e prow
  ci-operator/config/stolostron/search-e2e-test/stolostron-search-e2e-test-main.yaml
  ci-operator/config/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.3.yaml
  ci-operator/config/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.4.yaml
  ci-operator/config/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.5.yaml
  ci-operator/jobs/stolostron/search-e2e-test/stolostron-search-e2e-test-main-presubmits.yaml
  ci-operator/jobs/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.3-postsubmits.yaml
  ci-operator/jobs/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.3-presubmits.yaml
  ci-operator/jobs/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.4-postsubmits.yaml
  ci-operator/jobs/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.4-presubmits.yaml
  ci-operator/jobs/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.5-postsubmits.yaml
  ci-operator/jobs/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.5-presubmits.yaml
Labels: lgtm, approved

#25976 Revert "Revert "release-controller: add art-suffix flag""
  clusters/app.ci/release-controller/deploy-ocp-arm64-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-arm64-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-multi-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-multi-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-ppc64le-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-ppc64le-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-s390x-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-s390x-priv-controller.yaml
  hack/generators/release-controllers/content/osd_rc_deployments.py
  hack/generators/release-controllers/generate-release-controllers.py
Labels: lgtm, approved

#25971 release-controller: use binaries as input
  ci-operator/config/openshift/release-controller/openshift-release-controller-master.yaml
Labels: lgtm, approved

#25942 Periodic e2e
  ci-operator/config/redhat-et/microshift/redhat-et-microshift-main__periodics.yaml
  ci-operator/jobs/redhat-et/microshift/redhat-et-microshift-main-periodics.yaml
  ci-operator/jobs/redhat-et/microshift/redhat-et-microshift-main-presubmits.yaml
Labels: lgtm, approved

#25977 Alibaba: sourcing the new CI_RESOURCE_GROUP_ID variable to fix rg con…
  ci-operator/step-registry/ipi/conf/alibabacloud/ipi-conf-alibabacloud-commands.sh
Labels: lgtm, approved

#25956 kubevirt: ssp: Remove setup.sh from test commands
  ci-operator/config/kubevirt/ssp-operator/kubevirt-ssp-operator-master.yaml
Labels: lgtm, approved

#25968 MGMT-9069: Report code coverage for assisted-service
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
Labels: lgtm, approved

#25988 Add cherry pick approver for console
  core-services/prow/02_config/openshift/console/_pluginconfig.yaml
Labels: lgtm, approved, needs-ok-to-test

#25991 legacy: add username/password to gcp secrets
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved

#25761 Use only mirror.openshift.com and user/pass auth for 3.11
  cluster/test-deploy/gcp-crio/vars-origin.yaml
  cluster/test-deploy/gcp-dev-ha/vars-origin.yaml
  cluster/test-deploy/gcp-ha-static/vars-origin.yaml
  cluster/test-deploy/gcp-ha/vars-origin.yaml
  cluster/test-deploy/gcp-logging/vars-origin.yaml
  cluster/test-deploy/gcp-openshift-gce-devel-ci-2/vars-origin.yaml
  cluster/test-deploy/gcp/vars-origin.yaml
Labels: lgtm, approved

#25986 OpenStack: do not run e2e-openstack-operator by default
  ci-operator/jobs/openshift/cluster-api-provider-openstack/openshift-cluster-api-provider-openstack-release-4.10-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-openstack/openshift-cluster-api-provider-openstack-release-4.9-presubmits.yaml
Labels: lgtm, approved

#25993 legacy: move mirror.openshift.com creds to correct gcp secret
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved

#25724 Apply the new group policy on pool's RBACs
  clusters/hive/pools/_pool-admin-rbac_template.yaml
  clusters/hive/pools/cvp/admins_cvp-cluster-pool_rbac.yaml
  clusters/hive/pools/hypershift/admins_hypershift-cluster-pool_rbac.yaml
  clusters/hive/pools/msp/admins_msp-cluster-pool_rbac.yaml
  core-services/sync-rover-groups/_config.yaml
  hack/generate_new_pool_admins.sh
Labels: lgtm, approved

#25961 Mark older CI e2e-gcp-ran-profile test optional
  ci-operator/config/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-master.yaml
  ci-operator/jobs/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-master-presubmits.yaml
Labels: lgtm, approved

#25994 Remove owners from make/new-pool-admins
  Makefile
Labels: lgtm, approved

#25981 Microshift - disabile periodic e2e
  ci-operator/config/redhat-et/microshift/redhat-et-microshift-main__periodics.yaml
  ci-operator/jobs/redhat-et/microshift/redhat-et-microshift-main-periodics.yaml
  ci-operator/jobs/redhat-et/microshift/redhat-et-microshift-main-presubmits.yaml
Labels: lgtm, approved

#25999 Adding build04 to the cluster-groups
  clusters/app.ci/release-controller/deploy-ocp-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-priv-controller.yaml
  hack/generators/release-controllers/content/osd_rc_deployments.py
Labels: lgtm, approved

#25998 ocm - Restore SonarCloud presubmit (GRC)
  ci-operator/config/stolostron/config-policy-controller/stolostron-config-policy-controller-main.yaml
  ci-operator/config/stolostron/config-policy-controller/stolostron-config-policy-controller-release-2.5.yaml
  ci-operator/jobs/stolostron/config-policy-controller/stolostron-config-policy-controller-main-presubmits.yaml
  ci-operator/jobs/stolostron/config-policy-controller/stolostron-config-policy-controller-release-2.5-presubmits.yaml
Labels: lgtm, approved

#25996 microshift - correctly define periodic test image deps
  ci-operator/config/redhat-et/microshift/redhat-et-microshift-main__periodics.yaml
  ci-operator/jobs/redhat-et/microshift/redhat-et-microshift-main-periodics.yaml
Labels: lgtm, approved

#26000 supplemental-ci-images: Also build cosa from git main to `:latest`
  clusters/app.ci/supplemental-ci-images/coreos/cosa-rhcos-branched-bc.yaml
Labels: lgtm, approved

#25926 Adding openshift-eng/openshift-goimports repository
  ci-operator/config/openshift-eng/openshift-goimports/OWNERS
  ci-operator/config/openshift-eng/openshift-goimports/openshift-eng-openshift-goimports-main.yaml
  ci-operator/jobs/openshift-eng/openshift-goimports/OWNERS
  ci-operator/jobs/openshift-eng/openshift-goimports/openshift-eng-openshift-goimports-main-presubmits.yaml
  core-services/prow/02_config/openshift-eng/openshift-goimports/_pluginconfig.yaml
Labels: lgtm, approved

#26003 Drop e2e tests for Jenkins 3.11
  ci-operator/config/openshift/jenkins/openshift-jenkins-openshift-3.11.yaml
  ci-operator/jobs/openshift/jenkins/openshift-jenkins-openshift-3.11-presubmits.yaml
Labels: lgtm, approved

#26002 hypershift: skip verify and test on docs changes
  ci-operator/config/openshift/hypershift/openshift-hypershift-main.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-main-presubmits.yaml
Labels: lgtm, approved

#26001 hypershift: enable multi-zone hosted clusters
  ci-operator/config/openshift/hypershift/openshift-hypershift-main.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-main__periodics.yaml
Labels: lgtm, approved

#26007 Get mirror creds from mount point to pass to openshift-ansible
  ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e.yaml
Labels: lgtm, approved

#26008 Update the commands that are run for test and verify to reference the…
  ci-operator/config/openshift/builder/openshift-builder-master.yaml
Labels: lgtm, approved

#26010 Fix IBMCloud CIS resource gather commands
  ci-operator/step-registry/ipi/ibmcloud/gather-resources/ipi-ibmcloud-gather-resources-commands.sh
Labels: lgtm, approved

#26018 Allow rpm mirroring pods to be evicted by autoscaler
  clusters/build-clusters/common/release-controller/rpms-ocp-3.11.yaml
  clusters/build-clusters/common/release-controller/rpms-ocp-4.1.yaml
  clusters/build-clusters/common/release-controller/rpms-ocp-4.10.yaml
  clusters/build-clusters/common/release-controller/rpms-ocp-4.11.yaml
  clusters/build-clusters/common/release-controller/rpms-ocp-4.2.yaml
  clusters/build-clusters/common/release-controller/rpms-ocp-4.3.yaml
  clusters/build-clusters/common/release-controller/rpms-ocp-4.4.yaml
  clusters/build-clusters/common/release-controller/rpms-ocp-4.5.yaml
  clusters/build-clusters/common/release-controller/rpms-ocp-4.6.yaml
  clusters/build-clusters/common/release-controller/rpms-ocp-4.7.yaml
  clusters/build-clusters/common/release-controller/rpms-ocp-4.8.yaml
  clusters/build-clusters/common/release-controller/rpms-ocp-4.9.yaml
  hack/generators/release-controllers/content/art_rpm_mirroring_services.py
Labels: approved

#26017 cluster-init: validate sync-rover-groups' config
  core-services/sync-rover-groups/_config.yaml
  hack/validate-ci-build-clusters.sh
Labels: lgtm, approved

#25959 rename jobs that have multiple installations to include 'suite' in their name
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.4.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-master.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.4.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-cloud_hotfix_releases.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.4.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master-presubmits.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.4-presubmits.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-master-presubmits.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.4-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-cloud_hotfix_releases-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.4-presubmits.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-periodics.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-presubmits.yaml
Labels: lgtm, approved

#26019 Added nvidia-ci-secrets secret mount
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: lgtm, approved

#26020 fix cluster profile of SNO jobs
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.10.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.11.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: lgtm, approved

#26012 Remove use of any mirror but mirror.openshift.com
  cluster/test-deploy/gcp-crio/vars-origin.yaml
  cluster/test-deploy/gcp-dev-ha/vars-origin.yaml
  cluster/test-deploy/gcp-ha-static/vars-origin.yaml
  cluster/test-deploy/gcp-ha/vars-origin.yaml
  cluster/test-deploy/gcp-logging/vars-origin.yaml
  cluster/test-deploy/gcp-openshift-gce-devel-ci-2/vars-origin.yaml
  cluster/test-deploy/gcp/vars-origin.yaml
Labels: lgtm, approved

#25647 Configure additional networks for kubernetes-nmstate in workflow
  ci-operator/config/openshift/kubernetes-nmstate/openshift-kubernetes-nmstate-master.yaml
  ci-operator/step-registry/baremetalds/devscripts/conf/extranetwork/OWNERS
  ci-operator/step-registry/baremetalds/devscripts/conf/extranetwork/baremetalds-devscripts-conf-extranetwork-commands.sh
  ci-operator/step-registry/baremetalds/devscripts/conf/extranetwork/baremetalds-devscripts-conf-extranetwork-ref.metadata.json
  ci-operator/step-registry/baremetalds/devscripts/conf/extranetwork/baremetalds-devscripts-conf-extranetwork-ref.yaml
  ci-operator/step-registry/kubernetes-nmstate/e2e/kubernetes-nmstate-e2e-workflow.yaml
Labels: lgtm, approved

#26030 MGMT-9178: single-node CI should use OVNKubernetes as the network type
  ci-operator/step-registry/single-node/conf/aws/single-node-conf-aws-commands.sh
  ci-operator/step-registry/single-node/conf/gcp/single-node-conf-gcp-commands.sh
Labels: lgtm, approved

#25856 Synchronize SRO upstream and downstream test blocks
  ci-operator/config/openshift/special-resource-operator/openshift-special-resource-operator-master.yaml
  ci-operator/jobs/openshift/special-resource-operator/openshift-special-resource-operator-master-periodics.yaml
  ci-operator/jobs/openshift/special-resource-operator/openshift-special-resource-operator-master-presubmits.yaml
Labels: lgtm, approved, ok-to-test

#26021 remove redundant export of dockerfile reference to be built
  ci-operator/step-registry/baremetalds/assisted/setup/baremetalds-assisted-setup-commands.sh
Labels: lgtm, approved

#26034 Fix bad config bug in single-node conf step
  ci-operator/step-registry/single-node/conf/aws/single-node-conf-aws-commands.sh
  ci-operator/step-registry/single-node/conf/gcp/single-node-conf-gcp-commands.sh
Labels: lgtm, approved

#25989 Add redirector to proxy to the new sippy deployment on DPCR cluster.
  clusters/app.ci/cert-manager/sippy-ingress.yaml
  clusters/app.ci/sippy-redirector/01-deployment.yaml
  clusters/app.ci/sippy-redirector/OWNERS
  clusters/app.ci/sippy-redirector/README.md
Labels: lgtm, approved

#26029 Initialize CI configs for aws-load-balancer-controller
  ci-operator/config/openshift/aws-load-balancer-controller/OWNERS
  ci-operator/config/openshift/aws-load-balancer-controller/openshift-aws-load-balancer-controller-main.yaml
  ci-operator/jobs/openshift/aws-load-balancer-controller/OWNERS
  ci-operator/jobs/openshift/aws-load-balancer-controller/openshift-aws-load-balancer-controller-main-presubmits.yaml
  core-services/prow/02_config/openshift/aws-load-balancer-controller/OWNERS
  core-services/prow/02_config/openshift/aws-load-balancer-controller/_pluginconfig.yaml
Labels: lgtm, approved

#26043 Drop Sam from backport approvals
  core-services/prow/02_config/openshift/api/_pluginconfig.yaml
  core-services/prow/02_config/openshift/apiserver-library-go/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cert-manager-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/client-go/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-authentication-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-bootstrap/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-config-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-etcd-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-kube-apiserver-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-kube-controller-manager-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-kube-descheduler-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-kube-scheduler-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-kube-storage-version-migrator-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-openshift-apiserver-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-openshift-controller-manager-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-policy-controller/_pluginconfig.yaml
  core-services/prow/02_config/openshift/descheduler/_pluginconfig.yaml
  core-services/prow/02_config/openshift/etcd/_pluginconfig.yaml
  core-services/prow/02_config/openshift/kube-rbac-proxy/_pluginconfig.yaml
  core-services/prow/02_config/openshift/kubernetes/_pluginconfig.yaml
  core-services/prow/02_config/openshift/library-go/_pluginconfig.yaml
  core-services/prow/02_config/openshift/must-gather/_pluginconfig.yaml
  core-services/prow/02_config/openshift/oauth-apiserver/_pluginconfig.yaml
  core-services/prow/02_config/openshift/oauth-proxy/_pluginconfig.yaml
  core-services/prow/02_config/openshift/oauth-server/_pluginconfig.yaml
  core-services/prow/02_config/openshift/oc/_pluginconfig.yaml
  core-services/prow/02_config/openshift/openshift-apiserver/_pluginconfig.yaml
  core-services/prow/02_config/openshift/openshift-controller-manager/_pluginconfig.yaml
  core-services/prow/02_config/openshift/origin/_pluginconfig.yaml
  core-services/prow/02_config/openshift/osin/_pluginconfig.yaml
  core-services/prow/02_config/openshift/service-ca-operator/_pluginconfig.yaml
Labels: lgtm, approved

#25997 ci-tools: bump base images
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
Labels: lgtm, approved

#25923 MGMT-9102: Fix test-infra release-ocm-2.4 kubeapi IPv6 job
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.4.yaml
Labels: lgtm, approved

#26026 Revert "Promote sro-test-bin image for later reuse"
  ci-operator/config/openshift-psap/special-resource-operator/openshift-psap-special-resource-operator-master.yaml
  ci-operator/jobs/openshift-psap/special-resource-operator/openshift-psap-special-resource-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift-psap/special-resource-operator/openshift-psap-special-resource-operator-master-presubmits.yaml
  core-services/image-mirroring/openshift/mapping_origin_4_11
Labels: lgtm, approved

#24534 Add CI jobs for CAPI providers
  ci-operator/config/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-master.yaml
  ci-operator/config/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-master.yaml
  ci-operator/config/openshift/cluster-api-provider-gcp/openshift-cluster-api-provider-gcp-master.yaml
  ci-operator/jobs/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-master-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-aws/openshift-cluster-api-provider-aws-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-master-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-gcp/openshift-cluster-api-provider-gcp-master-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-gcp/openshift-cluster-api-provider-gcp-master-presubmits.yaml
  core-services/image-mirroring/openshift/mapping_origin_4_11
Labels: lgtm, approved

#26050 remove null field that is now set to omitempty
  core-services/prow/02_config/_config.yaml
Labels: lgtm, approved

#26053 Updated search-e2e prow
  ci-operator/config/stolostron/search-e2e-test/stolostron-search-e2e-test-main.yaml
Labels: lgtm, approved

#26057 Add step to gather data with azure CLI prior to destroy.
  ci-operator/step-registry/gather/azure-cli/OWNERS
  ci-operator/step-registry/gather/azure-cli/gather-azure-cli-commands.sh
  ci-operator/step-registry/gather/azure-cli/gather-azure-cli-ref.metadata.json
  ci-operator/step-registry/gather/azure-cli/gather-azure-cli-ref.yaml
  ci-operator/step-registry/ipi/azure/post/ipi-azure-post-chain.yaml
Labels: lgtm, approved

#26065 MGMT-9102: Remove unneeded test-infra release-ocm-2.4 jobs
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.4.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.4-presubmits.yaml
Labels: lgtm, approved

#26070 version update
  ci-operator/config/stolostron/discovery/stolostron-discovery-backplane-2.0.yaml
Labels: lgtm, approved

#26067 MGMT-9197: Add missing kube-api function name on assisted-test-infra release-ocm-2.4
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.4.yaml
Labels: lgtm, approved

#26075 remove disabled
  ci-operator/config/stolostron/discovery/stolostron-discovery-backplane-2.0.yaml
Labels: lgtm, approved

#26064 Revert "Drop e2e tests for Jenkins 3.11"
  ci-operator/config/openshift/jenkins/openshift-jenkins-openshift-3.11.yaml
  ci-operator/jobs/openshift/jenkins/openshift-jenkins-openshift-3.11-presubmits.yaml
  core-services/template-deprecation/_allowlist.yaml
Labels: lgtm, approved

#26077 Add branch protections for Assisted Installer repos
  core-services/prow/02_config/openshift/assisted-image-service/_pluginconfig.yaml
  core-services/prow/02_config/openshift/assisted-image-service/_prowconfig.yaml
  core-services/prow/02_config/openshift/assisted-installer-agent/_pluginconfig.yaml
  core-services/prow/02_config/openshift/assisted-installer-agent/_prowconfig.yaml
  core-services/prow/02_config/openshift/assisted-installer/_pluginconfig.yaml
  core-services/prow/02_config/openshift/assisted-installer/_prowconfig.yaml
  core-services/prow/02_config/openshift/assisted-service/_pluginconfig.yaml
  core-services/prow/02_config/openshift/assisted-service/_prowconfig.yaml
  core-services/prow/02_config/openshift/assisted-test-infra/_prowconfig.yaml
Labels: lgtm, approved

#26080 Summarize cucushift junit results in a seperate step
  ci-operator/step-registry/cucushift/e2e/cucushift-e2e-commands.sh
  ci-operator/step-registry/cucushift/e2e/cucushift-e2e-workflow.yaml
  ci-operator/step-registry/cucushift/e2e/report/OWNERS
  ci-operator/step-registry/cucushift/e2e/report/cucushift-e2e-report-commands.sh
  ci-operator/step-registry/cucushift/e2e/report/cucushift-e2e-report-ref.metadata.json
  ci-operator/step-registry/cucushift/e2e/report/cucushift-e2e-report-ref.yaml
Labels: lgtm, approved

#25635 Add EUS upgrade for azure
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__nightly-4.10-upgrade-from-eus-4.8.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
Labels: lgtm, approved

#26042 Fixing the installation of shellcheck for SRO d/s CI.
  ci-operator/config/openshift/special-resource-operator/openshift-special-resource-operator-master.yaml
Labels: lgtm, approved

#26083 Reduce knative eventing periodics
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.25__47.yaml
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.25__48.yaml
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.26__47.yaml
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.26__48.yaml
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v1.0__47.yaml
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v1.0__48.yaml
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v1.1__47.yaml
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v1.1__48.yaml
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v1.2__47.yaml
  ci-operator/config/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v1.2__48.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.25__47.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.25__48.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.26__47.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v0.26__48.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v1.0__47.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v1.0__48.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v1.1__47.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v1.1__48.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v1.2__47.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-v1.2__48.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.25-periodics.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v0.26-periodics.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v1.0-periodics.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v1.1-periodics.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka/openshift-knative-eventing-kafka-release-v1.2-periodics.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.25-periodics.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v0.26-periodics.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v1.0-periodics.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v1.1-periodics.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-v1.2-periodics.yaml
Labels: lgtm, approved

#26086 Rename metal secret to new profile secret
  ci-operator/jobs/openshift/release/openshift-release-infra-periodics.yaml
Labels: lgtm, approved

#26051 Renaming jobs to include the gpu-operator vendor
  ci-operator/config/rh-ecosystem-edge/ci-artifacts/rh-ecosystem-edge-ci-artifacts-master.yaml
  ci-operator/config/rh-ecosystem-edge/ci-artifacts/rh-ecosystem-edge-ci-artifacts-master__4.10.yaml
  ci-operator/config/rh-ecosystem-edge/ci-artifacts/rh-ecosystem-edge-ci-artifacts-master__4.6.yaml
  ci-operator/config/rh-ecosystem-edge/ci-artifacts/rh-ecosystem-edge-ci-artifacts-master__4.9.yaml
  ci-operator/jobs/rh-ecosystem-edge/ci-artifacts/rh-ecosystem-edge-ci-artifacts-master-periodics.yaml
  ci-operator/jobs/rh-ecosystem-edge/ci-artifacts/rh-ecosystem-edge-ci-artifacts-master-presubmits.yaml
Labels: lgtm, approved

#26089 Remove #single-node-ci slack message for non-sno job
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: lgtm, approved

#26076 Use the mapping file generated by sync-rover-groups
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
  ci-operator/jobs/infra-periodics.yaml
  clusters/app.ci/assets/admin_github-ldap-mapping-updater_rbac.yaml
  clusters/psi/Makefile
  clusters/psi/github-ldap-mapping-update_cronjob.yaml
  clusters/psi/sync-rover-groups-update_cronjob.yaml
Labels: lgtm, approved

#26063 sync aos-qe rover group for use with qe-private-deck
  clusters/app.ci/assets/admin_aos-qe-to-private-deck-poc-ns_rolebinding.yaml
  core-services/sync-rover-groups/_config.yaml
Labels: lgtm, approved, tide/merge-method-squash

#25510 Hypeshift: run the E2E tests for kubevirt provider
  ci-operator/config/openshift/hypershift/openshift-hypershift-main.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-main-presubmits.yaml
Labels: lgtm, approved

#26069 More reverts for b02's recovery
  ci-operator/jobs/infra-periodics.yaml
  clusters/app.ci/release-controller/deploy-ocp-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-priv-controller.yaml
  hack/generators/release-controllers/content/osd_rc_deployments.py
Labels: lgtm, approved

#26071 Add driver-toolkit e2e test as release informing
  core-services/release-controller/_releases/release-ocp-4.10.json
  core-services/release-controller/_releases/release-ocp-4.8.json
  core-services/release-controller/_releases/release-ocp-4.9.json
Labels: lgtm, approved

#26092 odf: z-stream release update
  core-services/prow/02_config/red-hat-storage/_pluginconfig.yaml
Labels: lgtm, approved

#26074 add cheesesashimi (zzlotnik) to rhcos-devel-admins
  clusters/app.ci/registry-access/rhcos-devel/admin_manifest.yaml
Labels: lgtm, approved

#26099 Add loki step to CAPI job
  ci-operator/step-registry/openshift/e2e/aws/capi/openshift-e2e-aws-capi-workflow.yaml
Labels: lgtm, approved

#26060 ocm - Update cert-policy-controller Sonar (GRC)
  ci-operator/config/stolostron/cert-policy-controller/stolostron-cert-policy-controller-release-2.5.yaml
  ci-operator/jobs/stolostron/cert-policy-controller/stolostron-cert-policy-controller-main-postsubmits.yaml
  ci-operator/jobs/stolostron/cert-policy-controller/stolostron-cert-policy-controller-release-2.5-postsubmits.yaml
  ci-operator/jobs/stolostron/config-policy-controller/stolostron-config-policy-controller-main-postsubmits.yaml
Labels: lgtm, approved

#26079 Updated search-e2e prow
  ci-operator/config/stolostron/search-e2e-test/stolostron-search-e2e-test-main.yaml
  ci-operator/config/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.3.yaml
  ci-operator/config/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.4.yaml
  ci-operator/config/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.5.yaml
  ci-operator/jobs/stolostron/search-e2e-test/stolostron-search-e2e-test-main-postsubmits.yaml
  ci-operator/jobs/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.3-postsubmits.yaml
  ci-operator/jobs/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.4-postsubmits.yaml
  ci-operator/jobs/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.4-presubmits.yaml
  ci-operator/jobs/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.5-postsubmits.yaml
  ci-operator/jobs/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.5-presubmits.yaml
Labels: lgtm, approved

#26106 Update image ref for search-e2e
  ci-operator/config/stolostron/search-e2e-test/stolostron-search-e2e-test-main.yaml
  ci-operator/config/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.3.yaml
  ci-operator/config/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.4.yaml
  ci-operator/config/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.5.yaml
Labels: lgtm, approved

#25995 Enforce RBAC policy on registry access
  clusters/app.ci/registry-access/addon-operator/admin_addon_operator.yaml
  clusters/app.ci/registry-access/azure/admin_azure_list.yaml
  clusters/app.ci/registry-access/cnf-ci/admin_manifest.yaml
  clusters/app.ci/registry-access/cnf-qe/admin_manifest.yaml
  clusters/app.ci/registry-access/cnv-qe/admin_rbac.yaml
  clusters/app.ci/registry-access/cnv/admin_01_rbac.yaml
  clusters/app.ci/registry-access/codeready-toolchain/admin_codeready-toolchain.yaml
  clusters/app.ci/registry-access/continuous-release-jobs/admin_manifest.yaml
  clusters/app.ci/registry-access/crw-qe/admin_manifest.yaml
  clusters/app.ci/registry-access/dpcr/admin_manifest.yaml
  clusters/app.ci/registry-access/fabric8-services/admin_fabric8-services_list.yaml
  clusters/app.ci/registry-access/hive-team/admin_manifest.yaml
  clusters/app.ci/registry-access/identitatem/admin_identitatem.yaml
  clusters/app.ci/registry-access/idmocp/admin_manifest.yaml
  clusters/app.ci/registry-access/images-openshift-acme/admin_images-openshift-acme_list.yaml
  clusters/app.ci/registry-access/integr8ly/admin_integr8ly.yaml
  clusters/app.ci/registry-access/integration-qe/admin_manifest.yaml
  clusters/app.ci/registry-access/interop-qe/admin_manifest.yaml
  clusters/app.ci/registry-access/kni-edge/admin_rbac.yaml
  clusters/app.ci/registry-access/microshift/admin_manifest.yaml
  clusters/app.ci/registry-access/ocp-kni/admin_ocp-kni_list.yaml
  clusters/app.ci/registry-access/ocp-perfscale/admin_manifest.yaml
  clusters/app.ci/registry-access/ocp-qe/admin_manifest.yaml
  clusters/app.ci/registry-access/ocpappsvc/admin_manifest.yaml
  clusters/app.ci/registry-access/ocs/admin_rbac.yaml
  clusters/app.ci/registry-access/openshift-logging/admin_manifest.yaml
  clusters/app.ci/registry-access/osd-images/admin_manifest.yaml
  clusters/app.ci/registry-access/ovirt/admin_list.yaml
  clusters/app.ci/registry-access/redht-developer/admin_redht-developer_list.yaml
  clusters/app.ci/registry-access/reference-addon/admin_reference_addon.yaml
  clusters/app.ci/registry-access/rhcos-devel/admin_manifest.yaml
  clusters/app.ci/registry-access/sd-app-sre/admin_manifest.yaml
  clusters/app.ci/registry-access/stackrox/admin_manifest.yaml
  clusters/app.ci/registry-access/stolostron/admin_stolostron.yaml
Labels: lgtm, approved

#26108 ocm - Update iam-policy-controller Sonar (GRC)
  ci-operator/config/stolostron/iam-policy-controller/stolostron-iam-policy-controller-release-2.5.yaml
  ci-operator/jobs/stolostron/iam-policy-controller/stolostron-iam-policy-controller-main-postsubmits.yaml
  ci-operator/jobs/stolostron/iam-policy-controller/stolostron-iam-policy-controller-release-2.5-postsubmits.yaml
Labels: lgtm, approved

#26112 ocm - Update governance-policy-propagator Sonar (GRC)
  ci-operator/config/stolostron/governance-policy-propagator/stolostron-governance-policy-propagator-release-2.5.yaml
  ci-operator/jobs/stolostron/governance-policy-propagator/stolostron-governance-policy-propagator-main-postsubmits.yaml
  ci-operator/jobs/stolostron/governance-policy-propagator/stolostron-governance-policy-propagator-release-2.5-postsubmits.yaml
Labels: lgtm, approved

#26087 Switch to new cluster profile for 4.10
  ci-operator/config/openshift/kubernetes-nmstate/openshift-kubernetes-nmstate-release-4.10.yaml
  ci-operator/jobs/openshift/kubernetes-nmstate/openshift-kubernetes-nmstate-release-4.10-periodics.yaml
  ci-operator/jobs/openshift/kubernetes-nmstate/openshift-kubernetes-nmstate-release-4.10-presubmits.yaml
Labels: lgtm, approved
