Repository openshift/release, pull requests merged in 2022-05, with the labels that each got.

#28250 CAPK: skip KV 4.11 related test
  ci-operator/config/openshift/cluster-api-provider-kubevirt/openshift-cluster-api-provider-kubevirt-main.yaml
Labels: lgtm, approved

#28252 CAPK: fix wrong new line in test code
  ci-operator/config/openshift/cluster-api-provider-kubevirt/openshift-cluster-api-provider-kubevirt-main.yaml
Labels: lgtm, approved

#28181 `assisted-baremetal-images-publish-commands.sh` unset variable bug fix
  ci-operator/step-registry/assisted/baremetal/images/publish/assisted-baremetal-images-publish-commands.sh
Labels: lgtm, approved

#28204 MGMT-10167: remove UI repos from prow's configuration
  core-services/prow/02_config/openshift-assisted/_pluginconfig.yaml
  core-services/prow/02_config/openshift-assisted/assisted-events-scrape/_pluginconfig.yaml
  core-services/prow/02_config/openshift-assisted/assisted-installer-deployment/_pluginconfig.yaml
Labels: lgtm, approved

#28237 assisted-service: enable periodic for operator-based CAPI job
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-periodics.yaml
Labels: lgtm, approved

#28142 Add cert-manager to build05
  clusters/app.ci/prow-monitoring/additional-scrape-configs_secret.yaml
  clusters/build-clusters/build05/cert-manager/cert-issuer-staging_clusterissuer.yaml
  clusters/build-clusters/build05/cert-manager/cert-issuer_clusterissuer.yaml
  clusters/build-clusters/build05/cert-manager/cert-manager_deployment.yaml
  clusters/build-clusters/build05/cert-manager/registry-build05_certificate.yaml
  clusters/build-clusters/build05/common_cert_manager
  clusters/build-clusters/build05/openshift-image-registry/cluster_config.yaml
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved

#28239 openstack: fix logic on performanceprofile for 4.9 & 4.10
  ci-operator/step-registry/openstack/provision/performanceprofile/openstack-provision-performanceprofile-commands.sh
Labels: lgtm, approved

#28202 e2e and upgrade schedule update
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.10-upgrade-from-nightly-4.9.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.11-upgrade-from-nightly-4.10.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.8-upgrade-from-nightly-4.7.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.9-upgrade-from-nightly-4.8.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.9.yaml
  ci-operator/jobs/openshift/multiarch/openshift-multiarch-master-periodics.yaml
Labels: lgtm, approved, ok-to-test

#28266 Set the compute nodes to n1-standard-8 for opendatahub-operator e2e runs
  ci-operator/config/opendatahub-io/opendatahub-operator/opendatahub-io-opendatahub-operator-master.yaml
Labels: lgtm, approved

#28212 feat: add e2e tests for secret-service
  ci-operator/config/konveyor/crane-secret-service/konveyor-crane-secret-service-main.yaml
  ci-operator/jobs/konveyor/crane-secret-service/konveyor-crane-secret-service-main-presubmits.yaml
Labels: lgtm, approved

#28248 stackrox: less managed
  core-services/prow/02_config/stackrox/stackrox-osci/_pluginconfig.yaml
Labels: lgtm, approved

#28267 ocm - Fix Go version for release-2.4 (go-template-utils)
  core-services/prow/02_config/stolostron/go-template-utils/_prowconfig.yaml
Labels: lgtm, approved

#28269 stackrox: run all tests on merge
  ci-operator/config/stackrox/stackrox-osci/stackrox-stackrox-osci-master.yaml
  ci-operator/jobs/stackrox/stackrox-osci/stackrox-stackrox-osci-master-postsubmits.yaml
  ci-operator/jobs/stackrox/stackrox-osci/stackrox-stackrox-osci-master-presubmits.yaml
Labels: lgtm, approved

#28235 Add quay-admins group
  core-services/sync-rover-groups/_config.yaml
Labels: lgtm, approved

#28270 stackrox: need separate tests for PR and postsubmit
  ci-operator/config/stackrox/stackrox-osci/stackrox-stackrox-osci-master.yaml
  ci-operator/jobs/stackrox/stackrox-osci/stackrox-stackrox-osci-master-postsubmits.yaml
  ci-operator/jobs/stackrox/stackrox-osci/stackrox-stackrox-osci-master-presubmits.yaml
Labels: lgtm, approved

#28275 Bump prometheus build_root to golang 1.17
  ci-operator/config/openshift/prometheus/openshift-prometheus-master.yaml
  ci-operator/config/openshift/prometheus/openshift-prometheus-release-4.11.yaml
  ci-operator/config/openshift/prometheus/openshift-prometheus-release-4.12.yaml
Labels: lgtm, approved

#27932 Assisted Installer: Move current jobs to edge variant
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-main__edge.yaml
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.4__rhacm.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master__edge.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.4__rhacm.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-master.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-master__edge.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.4__rhacm.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.4__stolostron.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.4__rhacm.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-main-periodics.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-main-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-main-presubmits.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.4-periodics.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.4-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.4-presubmits.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master-periodics.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master-presubmits.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.4-periodics.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.4-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.4-presubmits.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-master-periodics.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-master-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-master-presubmits.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.4-periodics.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.4-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.4-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-periodics.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.4-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.4-presubmits.yaml
Labels: lgtm, approved

#27656 Add support for installing pre create route53 hostedzone cluster on AWS
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
  ci-operator/step-registry/aws/deprovision/route53/OWNERS
  ci-operator/step-registry/aws/deprovision/route53/private-hosted-zone/OWNERS
  ci-operator/step-registry/aws/deprovision/route53/private-hosted-zone/aws-deprovision-route53-private-hosted-zone-commands.sh
  ci-operator/step-registry/aws/deprovision/route53/private-hosted-zone/aws-deprovision-route53-private-hosted-zone-ref.metadata.json
  ci-operator/step-registry/aws/deprovision/route53/private-hosted-zone/aws-deprovision-route53-private-hosted-zone-ref.yaml
  ci-operator/step-registry/aws/provision/route53/OWNERS
  ci-operator/step-registry/aws/provision/route53/private-hosted-zone/OWNERS
  ci-operator/step-registry/aws/provision/route53/private-hosted-zone/aws-provision-route53-private-hosted-zone-commands.sh
  ci-operator/step-registry/aws/provision/route53/private-hosted-zone/aws-provision-route53-private-hosted-zone-ref.metadata.json
  ci-operator/step-registry/aws/provision/route53/private-hosted-zone/aws-provision-route53-private-hosted-zone-ref.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/byo-route53/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/byo-route53/cucushift-installer-rehearse-aws-ipi-byo-route53-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/byo-route53/cucushift-installer-rehearse-aws-ipi-byo-route53-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/byo-route53/deprovision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/byo-route53/deprovision/cucushift-installer-rehearse-aws-ipi-byo-route53-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/byo-route53/deprovision/cucushift-installer-rehearse-aws-ipi-byo-route53-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/byo-route53/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/byo-route53/provision/cucushift-installer-rehearse-aws-ipi-byo-route53-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/byo-route53/provision/cucushift-installer-rehearse-aws-ipi-byo-route53-provision-chain.yaml
  ci-operator/step-registry/ipi/conf/aws/byo-route53/OWNERS
  ci-operator/step-registry/ipi/conf/aws/byo-route53/ipi-conf-aws-byo-route53-commands.sh
  ci-operator/step-registry/ipi/conf/aws/byo-route53/ipi-conf-aws-byo-route53-ref.metadata.json
  ci-operator/step-registry/ipi/conf/aws/byo-route53/ipi-conf-aws-byo-route53-ref.yaml
Labels: lgtm, approved

#27959 Add new aws-ovn-serial job
  ci-operator/config/openshift/release/openshift-release-master__ci-4.11.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.11.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  ci-operator/step-registry/openshift/e2e/aws/ovn/serial/OWNERS
  ci-operator/step-registry/openshift/e2e/aws/ovn/serial/openshift-e2e-aws-ovn-serial-workflow.metadata.json
  ci-operator/step-registry/openshift/e2e/aws/ovn/serial/openshift-e2e-aws-ovn-serial-workflow.yaml
Labels: lgtm, approved

#28178 openstack: simplified workflow for NFV on 4.11
  ci-operator/step-registry/openstack/provision/vfio-noiommu/openstack-provision-vfio-noiommu-commands.sh
  ci-operator/step-registry/openstack/provision/vhostuser/openstack-provision-vhostuser-commands.sh
Labels: lgtm, approved

#28254 Adding OCP version 4.8-4.11 for GitOps Backend Openshift CI
  ci-operator/config/redhat-developer/gitops-backend/redhat-developer-gitops-backend-master__v4.10.yaml
  ci-operator/config/redhat-developer/gitops-backend/redhat-developer-gitops-backend-master__v4.11.yaml
  ci-operator/config/redhat-developer/gitops-backend/redhat-developer-gitops-backend-master__v4.8.yaml
  ci-operator/config/redhat-developer/gitops-backend/redhat-developer-gitops-backend-master__v4.9.yaml
  ci-operator/jobs/redhat-developer/gitops-backend/redhat-developer-gitops-backend-master-presubmits.yaml
Labels: lgtm, approved

#28268 add OpenShift 4.10 to the E2E test pool
  ci-operator/config/identitatem/idp-mgmt-operator/identitatem-idp-mgmt-operator-main.yaml
Labels: lgtm, approved

#28259 MGMT-10164: add verify-generated-code job for release-ocm-2.5 branch
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.5.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.5-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.5-presubmits.yaml
Labels: lgtm, approved

#28273 stackrox: test release branching
  ci-operator/config/stackrox/stackrox-osci/stackrox-stackrox-osci-release-0.0.x.yaml
  ci-operator/jobs/stackrox/stackrox-osci/stackrox-stackrox-osci-release-0.0.x-postsubmits.yaml
  ci-operator/jobs/stackrox/stackrox-osci/stackrox-stackrox-osci-release-0.0.x-presubmits.yaml
Labels: lgtm, approved

#28288 ocm - Set propagator Kind version (governance-policy-propagator)
  core-services/prow/02_config/stolostron/governance-policy-propagator/_prowconfig.yaml
Labels: lgtm, approved

#28291 Add SOP for openshift-priv image-building job failures alert
  clusters/app.ci/prow-monitoring/mixins/_prometheus/dptp_alerts.libsonnet
  clusters/app.ci/prow-monitoring/mixins/prometheus_out/prometheus-prow-rules_prometheusrule.yaml
  docs/dptp-triage-sop/openshift-priv-image-building-jobs.md
Labels: lgtm, approved

#20875 Revert "ci-operator/config/openshift/cluster-version-operator: Temporarily drop abort-at from master"
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-master.yaml
Labels: lgtm, approved, lifecycle/rotten

#28294 ocm - Set Kind version (governance-policy-template-sync)
  core-services/prow/02_config/stolostron/governance-policy-template-sync/_prowconfig.yaml
Labels: lgtm, approved

#28042 Add timeout for cluster ready in osd_create.sh
  ci-operator/step-registry/osd/create/create/osd-create-create-commands.sh
  ci-operator/step-registry/osd/create/create/osd-create-create-ref.yaml
Labels: lgtm, approved, ok-to-test

#28293 Add Sonar post scan for hypershift-deployment-controller and hypershift-addon-operator
  ci-operator/config/stolostron/hypershift-addon-operator/stolostron-hypershift-addon-operator-main.yaml
  ci-operator/config/stolostron/hypershift-deployment-controller/stolostron-hypershift-deployment-controller-main.yaml
  ci-operator/jobs/stolostron/hypershift-addon-operator/stolostron-hypershift-addon-operator-main-postsubmits.yaml
  ci-operator/jobs/stolostron/hypershift-deployment-controller/stolostron-hypershift-deployment-controller-main-postsubmits.yaml
Labels: lgtm, approved

#28292 mirror ubi8:ruby-27
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_ocp
Labels: lgtm, approved

#28289 Fix CI for Kubeflow 1.6
  ci-operator/config/opendatahub-io/kubeflow/opendatahub-io-kubeflow-master.yaml
  ci-operator/jobs/opendatahub-io/kubeflow/opendatahub-io-kubeflow-master-postsubmits.yaml
Labels: lgtm, approved

#28299 core-services/prow/02_config/openshift-priv/router: Copy public _pluginconfig.yaml
  core-services/prow/02_config/openshift-priv/router/_pluginconfig.yaml
Labels: lgtm, approved

#28283 [knative-kafka] Add broker 1.2 rekt tests
  ci-operator/config/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.2__410.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.2-periodics.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.2-presubmits.yaml
Labels: lgtm, approved

#28298 Assisted Installer: Update OCP version on master branch for productization as Agent Installer
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-main.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-master.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master.yaml
Labels: lgtm, approved

#28287 Add nightly job for QBO
  ci-operator/config/quay/quay-bridge-operator/quay-quay-bridge-operator-master.yaml
  ci-operator/jobs/quay/quay-bridge-operator/quay-quay-bridge-operator-master-periodics.yaml
Labels: lgtm, approved

#28303 Fix issue with kubeflow go 1.17
  ci-operator/config/opendatahub-io/kubeflow/opendatahub-io-kubeflow-master.yaml
Labels: lgtm, approved

#28203 add bundle image and configure mirroring to redhat-cne
  ci-operator/config/redhat-cne/hw-event-proxy-operator/redhat-cne-hw-event-proxy-operator-main.yaml
  ci-operator/config/redhat-cne/hw-event-proxy-operator/redhat-cne-hw-event-proxy-operator-release-4.10.yaml
  ci-operator/config/redhat-cne/hw-event-proxy-operator/redhat-cne-hw-event-proxy-operator-release-4.11.yaml
  ci-operator/config/redhat-cne/hw-event-proxy-operator/redhat-cne-hw-event-proxy-operator-release-4.12.yaml
  core-services/image-mirroring/openshift/mapping_origin_4_10
  core-services/image-mirroring/openshift/mapping_origin_4_11
  core-services/image-mirroring/openshift/mapping_origin_4_12
Labels: lgtm, approved

#28296 skip appstudio-e2e-deployment test for .md
  ci-operator/config/redhat-appstudio/infra-deployments/redhat-appstudio-infra-deployments-main.yaml
  ci-operator/jobs/redhat-appstudio/infra-deployments/redhat-appstudio-infra-deployments-main-presubmits.yaml
Labels: lgtm, approved

#28307 kubeflow: make unit tests multistage
  ci-operator/config/opendatahub-io/kubeflow/opendatahub-io-kubeflow-master.yaml
  ci-operator/jobs/opendatahub-io/kubeflow/opendatahub-io-kubeflow-master-presubmits.yaml
Labels: lgtm, approved

#28314 [CVP-2582] Add gather chain step references to gather artifacts and logs
  ci-operator/config/redhat-openshift-ecosystem/msp/redhat-openshift-ecosystem-msp-osd-4.10.yaml
  ci-operator/config/redhat-openshift-ecosystem/msp/redhat-openshift-ecosystem-msp-osd-4.9.yaml
Labels: lgtm, approved

#28285 Promote Akram to Build + Jenkins Backport Risk Assessor
  core-services/prow/02_config/openshift/builder/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-openshift-controller-manager-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/csi-driver-shared-resource-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/csi-driver-shared-resource/_pluginconfig.yaml
  core-services/prow/02_config/openshift/jenkins-client-plugin/_pluginconfig.yaml
  core-services/prow/02_config/openshift/jenkins-openshift-login-plugin/_pluginconfig.yaml
  core-services/prow/02_config/openshift/jenkins-plugin/_pluginconfig.yaml
  core-services/prow/02_config/openshift/jenkins-sync-plugin/_pluginconfig.yaml
  core-services/prow/02_config/openshift/jenkins/_pluginconfig.yaml
  core-services/prow/02_config/openshift/openshift-controller-manager/_pluginconfig.yaml
  core-services/prow/02_config/openshift/origin/_pluginconfig.yaml
  core-services/prow/02_config/openshift/source-to-image/_pluginconfig.yaml
Labels: lgtm, approved, px-approved

#28311 Add restricted_labels config for machine-os-images
  core-services/prow/02_config/openshift/machine-os-images/_pluginconfig.yaml
Labels: lgtm, approved

#28301 Added @engelmi as approver
  OWNERS_ALIASES
Labels: lgtm, approved

#28315 stackrox: add Jouko to OWNERS and sort
  ci-operator/config/stackrox/OWNERS
  ci-operator/jobs/stackrox/OWNERS
  core-services/prow/02_config/stackrox/OWNERS
Labels: lgtm, approved

#28317 Add 4.11 aws-ovn-serial to testgrid
  core-services/testgrid-config-generator/_allow-list.yaml
Labels: lgtm, approved

#28282 Add job for fluentd on ruby 2.7
  ci-operator/config/ViaQ/logging-fluentd/ViaQ-logging-fluentd-ruby27-v1.14.x.yaml
  ci-operator/jobs/ViaQ/logging-fluentd/ViaQ-logging-fluentd-ruby27-v1.14.x-postsubmits.yaml
  ci-operator/jobs/ViaQ/logging-fluentd/ViaQ-logging-fluentd-ruby27-v1.14.x-presubmits.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: lgtm, approved

#28310 Add presubmits tests for Knative Eventing Hyperfoil repository
  ci-operator/config/openshift-knative/eventing-hyperfoil-benchmark/OWNERS
  ci-operator/config/openshift-knative/eventing-hyperfoil-benchmark/openshift-knative-eventing-hyperfoil-benchmark-main__410.yaml
  ci-operator/jobs/openshift-knative/eventing-hyperfoil-benchmark/OWNERS
  ci-operator/jobs/openshift-knative/eventing-hyperfoil-benchmark/openshift-knative-eventing-hyperfoil-benchmark-main-presubmits.yaml
Labels: lgtm, approved

#28316 TRT and OTA become sudoers on b02
  clusters/build-clusters/02_cluster/assets/admin_cluster-admin-0_list.yaml
  core-services/sync-rover-groups/_config.yaml
Labels: lgtm, approved

#28326 Hypershift conformance: Use correct image for nested mgt cluster
  ci-operator/step-registry/hypershift/aws/destroy-nested-management-cluster/hypershift-aws-destroy-nested-management-cluster-chain.yaml
  ci-operator/step-registry/hypershift/aws/setup-nested-management-cluster/hypershift-aws-setup-nested-management-cluster-chain.yaml
Labels: lgtm, approved

#28324 Add KEDA CI tests
  ci-operator/config/openshift-priv/kedacore-keda/openshift-priv-kedacore-keda-main.yaml
  ci-operator/config/openshift-priv/kedacore-keda/openshift-priv-kedacore-keda-release-4.11.yaml
  ci-operator/config/openshift-priv/kedacore-keda/openshift-priv-kedacore-keda-release-4.12.yaml
  ci-operator/config/openshift/kedacore-keda/openshift-kedacore-keda-main.yaml
  ci-operator/config/openshift/kedacore-keda/openshift-kedacore-keda-release-4.11.yaml
  ci-operator/config/openshift/kedacore-keda/openshift-kedacore-keda-release-4.12.yaml
  ci-operator/jobs/openshift-priv/kedacore-keda/openshift-priv-kedacore-keda-main-presubmits.yaml
  ci-operator/jobs/openshift-priv/kedacore-keda/openshift-priv-kedacore-keda-release-4.11-presubmits.yaml
  ci-operator/jobs/openshift-priv/kedacore-keda/openshift-priv-kedacore-keda-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift/kedacore-keda/openshift-kedacore-keda-main-presubmits.yaml
  ci-operator/jobs/openshift/kedacore-keda/openshift-kedacore-keda-release-4.11-presubmits.yaml
  ci-operator/jobs/openshift/kedacore-keda/openshift-kedacore-keda-release-4.12-presubmits.yaml
Labels: lgtm, approved

#27864 Add CI config for RHMI operator branch rhoam-release-v1.20
  ci-operator/config/integr8ly/integreatly-operator/integr8ly-integreatly-operator-rhoam-release-v1.20.yaml
  ci-operator/jobs/integr8ly/integreatly-operator/integr8ly-integreatly-operator-rhoam-release-v1.20-postsubmits.yaml
  ci-operator/jobs/integr8ly/integreatly-operator/integr8ly-integreatly-operator-rhoam-release-v1.20-presubmits.yaml
  core-services/image-mirroring/integr8ly/mapping_integr8ly_operator_1_20
Labels: lgtm, approved, ok-to-test

#28334 [CIGolang]change default
  ci-operator/step-registry/openshift-extended/test/openshift-extended-test-ref.yaml
Labels: lgtm, approved

#28336 fix no mkdir permission in intigration test
  ci-operator/config/stolostron/registration-operator/stolostron-registration-operator-backplane-2.0.yaml
  ci-operator/config/stolostron/registration-operator/stolostron-registration-operator-release-2.2.yaml
  ci-operator/config/stolostron/registration-operator/stolostron-registration-operator-release-2.3.yaml
  ci-operator/config/stolostron/registration-operator/stolostron-registration-operator-release-2.4.yaml
Labels: lgtm, approved

#28186 add shared step to create bastion ignition file
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/disconnected-proxy/provision/cucushift-installer-rehearse-gcp-ipi-disconnected-proxy-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/disconnected/provision/cucushift-installer-rehearse-gcp-ipi-disconnected-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/private/provision/cucushift-installer-rehearse-gcp-ipi-private-provision-chain.yaml
  ci-operator/step-registry/gcp/provision/bastionhost/gcp-provision-bastionhost-commands.sh
  ci-operator/step-registry/gcp/provision/bastionhost/gcp-provision-bastionhost-ref.yaml
  ci-operator/step-registry/ignition/OWNERS
  ci-operator/step-registry/ignition/bastionhost/OWNERS
  ci-operator/step-registry/ignition/bastionhost/ignition-bastionhost-commands.sh
  ci-operator/step-registry/ignition/bastionhost/ignition-bastionhost-ref.metadata.json
  ci-operator/step-registry/ignition/bastionhost/ignition-bastionhost-ref.yaml
Labels: lgtm, approved

#28208 AGENT-74: add initial tests for agent installer branch
  ci-operator/config/openshift/installer/openshift-installer-agent-installer.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-agent-installer-presubmits.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: lgtm, approved

#28154 [kubevirt-tekton-tasks] Rename generatetasks image to base-tests
  ci-operator/config/kubevirt/kubevirt-tekton-tasks/kubevirt-kubevirt-tekton-tasks-main.yaml
Labels: lgtm, approved

#28114 Adding OCP version 4.9-4.11 for GitOps Operator Openshift CI
  ci-operator/config/redhat-developer/gitops-operator/redhat-developer-gitops-operator-master__v4.10.yaml
  ci-operator/config/redhat-developer/gitops-operator/redhat-developer-gitops-operator-master__v4.11.yaml
  ci-operator/config/redhat-developer/gitops-operator/redhat-developer-gitops-operator-master__v4.9.yaml
  ci-operator/jobs/redhat-developer/gitops-operator/redhat-developer-gitops-operator-master-presubmits.yaml
Labels: lgtm, approved

#28305 Update golang version to 1.18 for power vs cloud provider
  ci-operator/config/openshift/cloud-provider-powervs/openshift-cloud-provider-powervs-main.yaml
  ci-operator/config/openshift/cloud-provider-powervs/openshift-cloud-provider-powervs-release-4.11.yaml
  ci-operator/config/openshift/cloud-provider-powervs/openshift-cloud-provider-powervs-release-4.12.yaml
Labels: lgtm, approved

#28338 Hypershift conformance: HO needs to be latest
  ci-operator/step-registry/hypershift/install/hypershift-install-chain.yaml
Labels: lgtm, approved

#28340 [kubevirt ssp operator] update golang version to 1.18
  ci-operator/config/kubevirt/ssp-operator/kubevirt-ssp-operator-master.yaml
Labels: lgtm, approved

#28345 Revert "Adding OCP version 4.9-4.11 for GitOps Operator Openshift CI"
  ci-operator/config/redhat-developer/gitops-operator/redhat-developer-gitops-operator-master__v4.10.yaml
  ci-operator/config/redhat-developer/gitops-operator/redhat-developer-gitops-operator-master__v4.11.yaml
  ci-operator/config/redhat-developer/gitops-operator/redhat-developer-gitops-operator-master__v4.7.yaml
  ci-operator/jobs/redhat-developer/gitops-operator/redhat-developer-gitops-operator-master-presubmits.yaml
Labels: lgtm, approved

#28328 Switch to squash merge for cluster-group-upgrades-operator
  core-services/prow/02_config/openshift-kni/cluster-group-upgrades-operator/_prowconfig.yaml
Labels: lgtm, approved

#28346 Make e2e-metal-ipi-ovn-ipv6 mandatory for origin
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
Labels: lgtm, approved

#28342 Hypershift nested presubmit: Stop overriding release for mgtm cluster
  ci-operator/config/openshift/hypershift/openshift-hypershift-main.yaml
Labels: lgtm, approved

#28349 chore: move mtrho-operator to crane-operator
  ci-operator/config/konveyor/crane-operator/OWNERS
  ci-operator/config/konveyor/crane-operator/konveyor-crane-operator-main.yaml
  ci-operator/jobs/konveyor/crane-operator/OWNERS
  ci-operator/jobs/konveyor/crane-operator/konveyor-crane-operator-main-postsubmits.yaml
  ci-operator/jobs/konveyor/crane-operator/konveyor-crane-operator-main-presubmits.yaml
  core-services/image-mirroring/konveyor/mapping_konveyor_latest
  core-services/prow/02_config/konveyor/crane-operator/OWNERS
  core-services/prow/02_config/konveyor/crane-operator/_pluginconfig.yaml
  core-services/prow/02_config/konveyor/crane-operator/_prowconfig.yaml
Labels: lgtm, approved

#28295 Fix aws-efs-csi-driver-operator channel names for release branches
  ci-operator/config/openshift/aws-efs-csi-driver-operator/openshift-aws-efs-csi-driver-operator-release-4.10.yaml
  ci-operator/config/openshift/aws-efs-csi-driver-operator/openshift-aws-efs-csi-driver-operator-release-4.11.yaml
  ci-operator/config/openshift/aws-efs-csi-driver-operator/openshift-aws-efs-csi-driver-operator-release-4.12.yaml
Labels: lgtm, approved

#28319 stackrox: finally onboard
  ci-operator/config/stackrox/stackrox/OWNERS
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master.yaml
  ci-operator/jobs/stackrox/stackrox/OWNERS
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-postsubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-presubmits.yaml
  core-services/prow/02_config/stackrox/stackrox/OWNERS
  core-services/prow/02_config/stackrox/stackrox/_pluginconfig.yaml
  core-services/prow/02_config/stackrox/stackrox/_prowconfig.yaml
Labels: lgtm, approved

#28286 AWS Pruner: If running for hypershift, fail if there were HC errors
  core-services/ipi-deprovision/aws.sh
Labels: lgtm, approved

#28348 kubeflow: remove periodic image mirror
  ci-operator/jobs/infra-image-mirroring.yaml
  core-services/image-mirroring/opendatahub-io/OWNERS
  core-services/image-mirroring/opendatahub-io/mapping_kubeflow_latest_quay
Labels: lgtm, approved

#28350 vsphere - add hardware 19 testing
  ci-operator/step-registry/upi/conf/vsphere/ova/upi-conf-vsphere-ova-commands.sh
  ci-operator/step-registry/upi/conf/vsphere/upi-conf-vsphere-commands.sh
Labels: lgtm, approved

#28323 add sample-app todolist-mongo and verify
  ci-operator/config/konveyor/pelorus/konveyor-pelorus-master__4.9.yaml
Labels: lgtm, approved

#28341 Remove image golang-lint-ci from README.md
  clusters/app.ci/supplemental-ci-images/README.md
Labels: lgtm, approved

#28356 do not run test in pelorus 4.9
  ci-operator/config/konveyor/pelorus/konveyor-pelorus-master__4.9.yaml
Labels: lgtm, approved

#28358 Add assisted-image-service to the base inputs
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master__edge.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-master__edge.yaml
Labels: lgtm, approved

#28224 Run QE's e2e (cucushift+golang) together
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__periodics.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__nightly-4.11.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11-periodics.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
  ci-operator/step-registry/openshift/e2e/test/qe/OWNERS
  ci-operator/step-registry/openshift/e2e/test/qe/openshift-e2e-test-qe-chain.metadata.json
  ci-operator/step-registry/openshift/e2e/test/qe/openshift-e2e-test-qe-chain.yaml
Labels: lgtm, approved

#28366 [CIGolang]optional test for dr debug
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-master.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11-presubmits.yaml
Labels: lgtm, approved

#28367 [CIGolang]no need aws-e2e test for DR
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-master.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11-presubmits.yaml
Labels: lgtm, approved

#28368 [CIGolang]not force success exit for dr debug
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-master.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11.yaml
Labels: lgtm, approved

#28364 Integrate e2e (golang+cucushift) for aws-ipi-private
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__periodics.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__nightly-4.11.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11-periodics.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
Labels: lgtm, approved

#28375 ocs-consumer periodic job: set a new schedule
  ci-operator/config/openshift/osde2e/openshift-osde2e-main.yaml
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: lgtm, approved, needs-ok-to-test

#28370 Adjust default cpu/memory for openshift-extended-test based on usage
  ci-operator/step-registry/openshift-extended/test/openshift-extended-test-ref.yaml
Labels: lgtm, approved

#28371 [azure] enable proxy mirror registry in bastion host
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse.yaml
  ci-operator/step-registry/azure/deprovision/resourcegroup/azure-deprovision-resourcegroup-commands.sh
  ci-operator/step-registry/azure/provision/bastionhost/azure-provision-bastionhost-chain.metadata.json
  ci-operator/step-registry/azure/provision/bastionhost/azure-provision-bastionhost-chain.yaml
  ci-operator/step-registry/azure/provision/bastionhost/azure-provision-bastionhost-commands.sh
  ci-operator/step-registry/azure/provision/bastionhost/azure-provision-bastionhost-ref.yaml
  ci-operator/step-registry/azure/provision/nat/azure-provision-nat-commands.sh
  ci-operator/step-registry/azure/provision/resourcegroup/azure-provision-resourcegroup-commands.sh
  ci-operator/step-registry/azure/provision/vnet/azure-provision-vnet-commands.sh
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/disconnected/provision/cucushift-installer-rehearse-azure-ipi-disconnected-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/fullyprivate/provision/cucushift-installer-rehearse-azure-ipi-fullyprivate-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/proxy/provision/cucushift-installer-rehearse-azure-ipi-proxy-provision-chain.yaml
  ci-operator/step-registry/ignition/bastionhost/ignition-bastionhost-commands.sh
Labels: lgtm, approved

#28352 AGENT-153: Promote assisted-installer-agent to OCP namespace
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master-presubmits.yaml
  core-services/image-mirroring/openshift/mapping_origin_4_11
Labels: lgtm, approved

#28360 Add Allen to etcd backport approvers
  core-services/prow/02_config/openshift/etcd/_pluginconfig.yaml
Labels: lgtm, approved

#28312 kubeflow: new workflow to mirror images
  ci-operator/config/opendatahub-io/kubeflow/opendatahub-io-kubeflow-master.yaml
  ci-operator/jobs/opendatahub-io/kubeflow/opendatahub-io-kubeflow-master-periodics.yaml
  ci-operator/jobs/opendatahub-io/kubeflow/opendatahub-io-kubeflow-master-postsubmits.yaml
  ci-operator/step-registry/opendatahub-io/OWNERS
  ci-operator/step-registry/opendatahub-io/ci/OWNERS
  ci-operator/step-registry/opendatahub-io/ci/image-mirror/OWNERS
  ci-operator/step-registry/opendatahub-io/ci/image-mirror/opendatahub-io-ci-image-mirror-commands.sh
  ci-operator/step-registry/opendatahub-io/ci/image-mirror/opendatahub-io-ci-image-mirror-ref.metadata.json
  ci-operator/step-registry/opendatahub-io/ci/image-mirror/opendatahub-io-ci-image-mirror-ref.yaml
  ci-operator/step-registry/opendatahub-io/ci/image-mirror/opendatahub-io-ci-image-mirror-workflow.metadata.json
  ci-operator/step-registry/opendatahub-io/ci/image-mirror/opendatahub-io-ci-image-mirror-workflow.yaml
Labels: lgtm, approved

#28378 ACM: add ENVs to fix e2e issue for foundation
  ci-operator/config/stolostron/multicloud-operators-foundation/stolostron-multicloud-operators-foundation-backplane-2.0.yaml
  ci-operator/config/stolostron/multicloud-operators-foundation/stolostron-multicloud-operators-foundation-release-2.2.yaml
  ci-operator/config/stolostron/multicloud-operators-foundation/stolostron-multicloud-operators-foundation-release-2.3.yaml
Labels: lgtm, approved

#28381 Toolkit base image bump to 8.5-243.1651231653
  clusters/app.ci/supplemental-ci-images/ibm-roks-toolkit-base/ibm-roks-toolkit-base.yaml
Labels: lgtm, approved

#28261 Added ci configs and ci jobs for Power VS Block csi driver
  ci-operator/config/openshift/ibm-powervs-block-csi-driver/OWNERS
  ci-operator/config/openshift/ibm-powervs-block-csi-driver/openshift-ibm-powervs-block-csi-driver-main.yaml
  ci-operator/jobs/openshift/ibm-powervs-block-csi-driver/OWNERS
  ci-operator/jobs/openshift/ibm-powervs-block-csi-driver/openshift-ibm-powervs-block-csi-driver-main-postsubmits.yaml
  ci-operator/jobs/openshift/ibm-powervs-block-csi-driver/openshift-ibm-powervs-block-csi-driver-main-presubmits.yaml
  core-services/image-mirroring/openshift/mapping_origin_4_12
  core-services/prow/02_config/openshift/ibm-powervs-block-csi-driver/_pluginconfig.yaml
  core-services/prow/02_config/openshift/ibm-powervs-block-csi-driver/_prowconfig.yaml
Labels: lgtm, approved

#28313 openstack/gather: add ports
  ci-operator/step-registry/openstack/gather/openstack-gather-commands.sh
Labels: lgtm, approved

#28337 update microshift golang-1.17
  ci-operator/config/redhat-et/microshift/redhat-et-microshift-main.yaml
Labels: lgtm, approved

#28325 AGENT-153: Promote assisted-installer to OCP namespace
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-master.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-master-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-master-presubmits.yaml
  core-services/image-mirroring/openshift/mapping_origin_4_11
Labels: lgtm, approved

#28284 kubeflow: add odh-notebook-controller to Openshift CI
  ci-operator/config/opendatahub-io/kubeflow/opendatahub-io-kubeflow-master.yaml
  ci-operator/jobs/opendatahub-io/kubeflow/opendatahub-io-kubeflow-master-periodics.yaml
  ci-operator/jobs/opendatahub-io/kubeflow/opendatahub-io-kubeflow-master-postsubmits.yaml
  ci-operator/jobs/opendatahub-io/kubeflow/opendatahub-io-kubeflow-master-presubmits.yaml
Labels: lgtm, approved

#28382 Hypershift e2e aws: Three azs
  ci-operator/config/openshift/hypershift/openshift-hypershift-main.yaml
Labels: lgtm, approved

#28373 Add myself to stackrox OWNERS
  ci-operator/config/stackrox/OWNERS
  ci-operator/jobs/stackrox/OWNERS
  core-services/prow/02_config/stackrox/OWNERS
Labels: lgtm, approved

#28386 Add Allen to etcd-operator backport approvers
  core-services/prow/02_config/openshift/cluster-etcd-operator/_pluginconfig.yaml
Labels: lgtm, approved

#28385 ci-operator/step-registry/gather/must-gather: Set timeout
  ci-operator/step-registry/gather/must-gather/gather-must-gather-ref.yaml
Labels: lgtm, approved

#28363 ocm - Use Makefile.prow for unit tests (cert-policy-controller)
  ci-operator/config/stolostron/cert-policy-controller/stolostron-cert-policy-controller-main.yaml
Labels: lgtm, approved

#28388 Don't run more that one osde2e verify presubmit at once
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-presubmits.yaml
Labels: lgtm, approved

#28380 [azure] open 6001 6002 in nsg for proxy mirror registry
  ci-operator/step-registry/azure/provision/bastionhost/azure-provision-bastionhost-commands.sh
Labels: lgtm, approved

#28374 Integrate e2e (golang+cucushift) for aws-ipi-proxy
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__periodics.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__nightly-4.11.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11-periodics.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
Labels: lgtm, approved

#28376 [CIGolang]support no case selected
  ci-operator/step-registry/openshift-extended/test/openshift-extended-test-commands.sh
Labels: lgtm, approved

#28397 set HOME to tmp
  ci-operator/config/stolostron/placement/stolostron-placement-backplane-2.0.yaml
Labels: lgtm, approved

#28395 Show each stages used time for cucushift-e2e
  ci-operator/step-registry/cucushift/e2e/cucushift-e2e-commands.sh
Labels: lgtm, approved

#28339 [AWS QE] add rehearse jobs for each cluster profile
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
Labels: lgtm, approved

#28399 ACM: Mirror images for server foundation repos
  ci-operator/config/stolostron/placement/stolostron-placement-main.yaml
  ci-operator/config/stolostron/registration-operator/stolostron-registration-operator-main.yaml
  ci-operator/config/stolostron/registration/stolostron-registration-main.yaml
  ci-operator/config/stolostron/work/stolostron-work-main.yaml
  ci-operator/jobs/stolostron/placement/stolostron-placement-main-postsubmits.yaml
  ci-operator/jobs/stolostron/registration-operator/stolostron-registration-operator-main-postsubmits.yaml
  ci-operator/jobs/stolostron/registration/stolostron-registration-main-postsubmits.yaml
  ci-operator/jobs/stolostron/work/stolostron-work-main-postsubmits.yaml
Labels: lgtm, approved

#28400 Integrate e2e (golang+cucushift) for azure-ipi
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__periodics.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__nightly-4.11.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11-periodics.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
Labels: lgtm, approved

#28406 NO-ISSUE - assisted-installer:image-service Fix image service base image version
  ci-operator/config/openshift/cluster-api-provider-agent/openshift-cluster-api-provider-agent-master.yaml
Labels: lgtm, approved

#28281 openshift/assisted-test-infra repo live-iso-with-worker job
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-presubmits.yaml
  ci-operator/step-registry/baremetalds/sno/setup/baremetalds-sno-setup-commands.sh
  ci-operator/step-registry/baremetalds/sno/setup/baremetalds-sno-setup-ref.yaml
Labels: lgtm, approved

#28404 ACM: fix foundation publish issue
  ci-operator/config/stolostron/multicloud-operators-foundation/stolostron-multicloud-operators-foundation-release-2.2.yaml
  ci-operator/jobs/stolostron/multicloud-operators-foundation/stolostron-multicloud-operators-foundation-release-2.2-postsubmits.yaml
Labels: lgtm, approved

#28402 Integrate e2e (golang+cucushift) for multiple azure profiles
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__periodics.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__nightly-4.11.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11-periodics.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
Labels: lgtm, approved

#28217 add azure sdn to ovn
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/ovn/sdn2ovn/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/ovn/sdn2ovn/cucushift-installer-rehearse-azure-ipi-ovn-sdn2ovn-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/ovn/sdn2ovn/cucushift-installer-rehearse-azure-ipi-ovn-sdn2ovn-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/ovn/sdn2ovn/deprovision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/ovn/sdn2ovn/deprovision/cucushift-installer-rehearse-azure-ipi-ovn-sdn2ovn-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/ovn/sdn2ovn/deprovision/cucushift-installer-rehearse-azure-ipi-ovn-sdn2ovn-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/ovn/sdn2ovn/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/ovn/sdn2ovn/provision/cucushift-installer-rehearse-azure-ipi-ovn-sdn2ovn-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/ovn/sdn2ovn/provision/cucushift-installer-rehearse-azure-ipi-ovn-sdn2ovn-provision-chain.yaml
Labels: lgtm, approved

#28412 ACM: fix promotion issue for foundation repos
  ci-operator/config/stolostron/cluster-curator-controller/stolostron-cluster-curator-controller-backplane-2.0.yaml
  ci-operator/config/stolostron/cluster-curator-controller/stolostron-cluster-curator-controller-main.yaml
  ci-operator/config/stolostron/cluster-lifecycle-e2e/stolostron-cluster-lifecycle-e2e-main.yaml
  ci-operator/config/stolostron/cluster-lifecycle-e2e/stolostron-cluster-lifecycle-e2e-release-2.5.yaml
  ci-operator/config/stolostron/cluster-proxy-addon/stolostron-cluster-proxy-addon-main.yaml
  ci-operator/config/stolostron/cluster-proxy-addon/stolostron-cluster-proxy-addon-release-2.5.yaml
  ci-operator/config/stolostron/cluster-proxy/stolostron-cluster-proxy-main.yaml
  ci-operator/config/stolostron/cluster-proxy/stolostron-cluster-proxy-release-2.5.yaml
  ci-operator/config/stolostron/clusterclaims-controller/stolostron-clusterclaims-controller-backplane-2.0.yaml
  ci-operator/config/stolostron/clusterclaims-controller/stolostron-clusterclaims-controller-main.yaml
  ci-operator/config/stolostron/clusterlifecycle-state-metrics/stolostron-clusterlifecycle-state-metrics-backplane-2.0.yaml
  ci-operator/config/stolostron/clusterlifecycle-state-metrics/stolostron-clusterlifecycle-state-metrics-main.yaml
  ci-operator/config/stolostron/klusterlet-addon-controller/stolostron-klusterlet-addon-controller-main.yaml
  ci-operator/config/stolostron/klusterlet-addon-controller/stolostron-klusterlet-addon-controller-release-2.5.yaml
  ci-operator/config/stolostron/klusterlet-addon-operator/stolostron-klusterlet-addon-operator-main.yaml
  ci-operator/config/stolostron/klusterlet-addon-operator/stolostron-klusterlet-addon-operator-release-2.5.yaml
  ci-operator/config/stolostron/managedcluster-import-controller/stolostron-managedcluster-import-controller-backplane-2.0.yaml
  ci-operator/config/stolostron/managedcluster-import-controller/stolostron-managedcluster-import-controller-main.yaml
  ci-operator/config/stolostron/multicloud-operators-foundation/stolostron-multicloud-operators-foundation-backplane-2.0.yaml
  ci-operator/config/stolostron/multicloud-operators-foundation/stolostron-multicloud-operators-foundation-main.yaml
  ci-operator/config/stolostron/provider-credential-controller/stolostron-provider-credential-controller-backplane-2.0.yaml
  ci-operator/config/stolostron/provider-credential-controller/stolostron-provider-credential-controller-main.yaml
Labels: lgtm, approved

#28417 kubeflow: check repo_owner only when presubmit
  ci-operator/step-registry/opendatahub-io/ci/image-mirror/opendatahub-io-ci-image-mirror-commands.sh
Labels: lgtm, approved

#28418 Add assisted-image-service in ``cloud_hotfix_releases`` branch definition
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-cloud_hotfix_releases.yaml
Labels: lgtm, approved

#28361 ocm - Migrate `2.3` publish and sonar to configs and step-registry (GRC)
  ci-operator/config/stolostron/cert-policy-controller/stolostron-cert-policy-controller-release-2.3.yaml
  ci-operator/config/stolostron/config-policy-controller/stolostron-config-policy-controller-release-2.3.yaml
  ci-operator/config/stolostron/governance-policy-propagator/stolostron-governance-policy-propagator-release-2.3.yaml
  ci-operator/config/stolostron/governance-policy-spec-sync/stolostron-governance-policy-spec-sync-release-2.3.yaml
  ci-operator/config/stolostron/governance-policy-status-sync/stolostron-governance-policy-status-sync-release-2.3.yaml
  ci-operator/config/stolostron/governance-policy-template-sync/stolostron-governance-policy-template-sync-release-2.3.yaml
  ci-operator/config/stolostron/grc-ui-api/stolostron-grc-ui-api-release-2.3.yaml
  ci-operator/config/stolostron/grc-ui/stolostron-grc-ui-release-2.3.yaml
  ci-operator/config/stolostron/iam-policy-controller/stolostron-iam-policy-controller-release-2.3.yaml
  ci-operator/jobs/stolostron/cert-policy-controller/stolostron-cert-policy-controller-release-2.3-postsubmits.yaml
  ci-operator/jobs/stolostron/config-policy-controller/stolostron-config-policy-controller-release-2.3-postsubmits.yaml
  ci-operator/jobs/stolostron/governance-policy-propagator/stolostron-governance-policy-propagator-release-2.3-postsubmits.yaml
  ci-operator/jobs/stolostron/governance-policy-spec-sync/stolostron-governance-policy-spec-sync-release-2.3-postsubmits.yaml
  ci-operator/jobs/stolostron/governance-policy-status-sync/stolostron-governance-policy-status-sync-release-2.3-postsubmits.yaml
  ci-operator/jobs/stolostron/governance-policy-template-sync/stolostron-governance-policy-template-sync-release-2.3-postsubmits.yaml
  ci-operator/jobs/stolostron/grc-ui-api/stolostron-grc-ui-api-release-2.3-postsubmits.yaml
  ci-operator/jobs/stolostron/grc-ui/stolostron-grc-ui-release-2.3-postsubmits.yaml
  ci-operator/jobs/stolostron/iam-policy-controller/stolostron-iam-policy-controller-release-2.3-postsubmits.yaml
Labels: lgtm, approved

#27332 Switch to go 1.18 for CRI-O `main` branch
  ci-operator/config/cri-o/cri-o/cri-o-cri-o-main.yaml
Labels: lgtm, approved

#28420 SNO BIP TEST_FUNC doesn't propagate to the remote SSH session
  ci-operator/step-registry/baremetalds/sno/setup/baremetalds-sno-setup-commands.sh
Labels: lgtm, approved

#28353 Promote assisted-service to ocp namespace
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
  core-services/image-mirroring/openshift/mapping_origin_4_11
Labels: lgtm, approved

#28416 MGMT-10255: Optimize OLM jobs triggering
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master__edge.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.4.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.5.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-master__edge.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.4.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.5.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-cloud_hotfix_releases.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.4.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.5.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master-presubmits.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.4-presubmits.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.5-presubmits.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-master-presubmits.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.4-presubmits.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.5-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-cloud_hotfix_releases-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.4-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.5-presubmits.yaml
Labels: lgtm, approved

#28421 Adding Eventhubs to the broker test image build procedure
  ci-operator/config/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.2__410.yaml
  ci-operator/config/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.2__49.yaml
Labels: lgtm, approved

#28427 Mirror new golangci-lint 1.46.0
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_ci
Labels: lgtm, approved

#28423 Update golang version to 1.17
  ci-operator/config/ViaQ/log-file-metric-exporter/ViaQ-log-file-metric-exporter-main.yaml
Labels: lgtm, approved

#28428 KEDA: Set release metadata, clear GOFLAGS for CI tests
  ci-operator/config/openshift-priv/kedacore-keda/openshift-priv-kedacore-keda-main.yaml
  ci-operator/config/openshift-priv/kedacore-keda/openshift-priv-kedacore-keda-release-4.11.yaml
  ci-operator/config/openshift-priv/kedacore-keda/openshift-priv-kedacore-keda-release-4.12.yaml
  ci-operator/config/openshift/kedacore-keda/openshift-kedacore-keda-main.yaml
  ci-operator/config/openshift/kedacore-keda/openshift-kedacore-keda-release-4.11.yaml
  ci-operator/config/openshift/kedacore-keda/openshift-kedacore-keda-release-4.12.yaml
  ci-operator/jobs/openshift-priv/kedacore-keda/openshift-priv-kedacore-keda-main-postsubmits.yaml
  ci-operator/jobs/openshift-priv/kedacore-keda/openshift-priv-kedacore-keda-main-presubmits.yaml
  ci-operator/jobs/openshift-priv/kedacore-keda/openshift-priv-kedacore-keda-release-4.11-postsubmits.yaml
  ci-operator/jobs/openshift-priv/kedacore-keda/openshift-priv-kedacore-keda-release-4.11-presubmits.yaml
  ci-operator/jobs/openshift-priv/kedacore-keda/openshift-priv-kedacore-keda-release-4.12-postsubmits.yaml
  ci-operator/jobs/openshift-priv/kedacore-keda/openshift-priv-kedacore-keda-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift/kedacore-keda/openshift-kedacore-keda-main-postsubmits.yaml
  ci-operator/jobs/openshift/kedacore-keda/openshift-kedacore-keda-main-presubmits.yaml
  ci-operator/jobs/openshift/kedacore-keda/openshift-kedacore-keda-release-4.11-postsubmits.yaml
  ci-operator/jobs/openshift/kedacore-keda/openshift-kedacore-keda-release-4.11-presubmits.yaml
  ci-operator/jobs/openshift/kedacore-keda/openshift-kedacore-keda-release-4.12-postsubmits.yaml
  ci-operator/jobs/openshift/kedacore-keda/openshift-kedacore-keda-release-4.12-presubmits.yaml
Labels: lgtm, approved

#28229 run e2e-vsphere-upi if upi images change
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
Labels: lgtm, approved

#28290 Adding workflow for gcp ipi ovn
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/ovn/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/ovn/cucushift-installer-rehearse-gcp-ipi-ovn-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/ovn/cucushift-installer-rehearse-gcp-ipi-ovn-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/ovn/deprovision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/ovn/deprovision/cucushift-installer-rehearse-gcp-ipi-ovn-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/ovn/deprovision/cucushift-installer-rehearse-gcp-ipi-ovn-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/ovn/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/ovn/provision/cucushift-installer-rehearse-gcp-ipi-ovn-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/ovn/provision/cucushift-installer-rehearse-gcp-ipi-ovn-provision-chain.yaml
Labels: lgtm, approved

#28436 Integrate e2e (golang+cucushift) for multiple gcp profiles
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__periodics.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__nightly-4.11.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11-periodics.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
Labels: lgtm, approved

#28332 ACM: use generic-claim workflow for foundation e2e
  ci-operator/config/stolostron/multicloud-operators-foundation/stolostron-multicloud-operators-foundation-backplane-2.0.yaml
  ci-operator/config/stolostron/multicloud-operators-foundation/stolostron-multicloud-operators-foundation-main.yaml
  ci-operator/config/stolostron/multicloud-operators-foundation/stolostron-multicloud-operators-foundation-release-2.3.yaml
  ci-operator/config/stolostron/multicloud-operators-foundation/stolostron-multicloud-operators-foundation-release-2.4.yaml
  ci-operator/jobs/stolostron/multicloud-operators-foundation/stolostron-multicloud-operators-foundation-backplane-2.0-presubmits.yaml
  ci-operator/jobs/stolostron/multicloud-operators-foundation/stolostron-multicloud-operators-foundation-main-presubmits.yaml
  ci-operator/jobs/stolostron/multicloud-operators-foundation/stolostron-multicloud-operators-foundation-release-2.3-presubmits.yaml
  ci-operator/jobs/stolostron/multicloud-operators-foundation/stolostron-multicloud-operators-foundation-release-2.4-presubmits.yaml
Labels: lgtm, approved

#28431 Adding Eventhubs to the broker test image build procedure
  ci-operator/config/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.3__410.yaml
  ci-operator/config/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.3__49.yaml
Labels: lgtm, approved

#28439 Adding OCP version 4.8-4.11 for GitOps Backend Openshift CI
  ci-operator/config/redhat-developer/gitops-backend/redhat-developer-gitops-backend-master__v4.10.yaml
  ci-operator/config/redhat-developer/gitops-backend/redhat-developer-gitops-backend-master__v4.11.yaml
  ci-operator/config/redhat-developer/gitops-backend/redhat-developer-gitops-backend-master__v4.8.yaml
  ci-operator/config/redhat-developer/gitops-backend/redhat-developer-gitops-backend-master__v4.9.yaml
  ci-operator/jobs/redhat-developer/gitops-backend/redhat-developer-gitops-backend-master-presubmits.yaml
Labels: lgtm, approved

#28444 NO-ISSUE: assisted-baremetal-setup requires assisted-image-service
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.4.yaml
Labels: lgtm, approved

#28443 Changing the merge-method of DTK to 'squash'.
  core-services/prow/02_config/openshift/driver-toolkit/_prowconfig.yaml
Labels: lgtm, approved

#28410 minor fix for AWS bastion host
  ci-operator/step-registry/aws/provision/bastionhost/aws-provision-bastionhost-commands.sh
Labels: lgtm, approved

#28429 VolSync: adjust for go1.17 upstream, OCP 4.11, prep for go 1.18
  ci-operator/config/backube/volsync/backube-volsync-main.yaml
  ci-operator/jobs/backube/volsync/backube-volsync-main-postsubmits.yaml
  ci-operator/jobs/backube/volsync/backube-volsync-main-presubmits.yaml
Labels: lgtm, approved

#28437 ACM: Bump golang to 1.18 for hypershift repos
  ci-operator/config/stolostron/hypershift-addon-operator/stolostron-hypershift-addon-operator-backplane-2.0.yaml
  ci-operator/config/stolostron/hypershift-addon-operator/stolostron-hypershift-addon-operator-main.yaml
  ci-operator/config/stolostron/hypershift-deployment-controller/stolostron-hypershift-deployment-controller-backplane-2.0.yaml
  ci-operator/config/stolostron/hypershift-deployment-controller/stolostron-hypershift-deployment-controller-main.yaml
Labels: lgtm, approved

#28450 hypershift: use 3 zones for nested e2e-aws test
  ci-operator/config/openshift/hypershift/openshift-hypershift-main.yaml
Labels: lgtm, approved

#28383 external-dns-operator: use stable OLM channel for the bundle
  ci-operator/config/openshift/external-dns-operator/openshift-external-dns-operator-main.yaml
Labels: lgtm, approved

#28433 Hypershift: add assisted-image-service to base_images
  ci-operator/config/openshift/hypershift/openshift-hypershift-main.yaml
Labels: lgtm, approved

#28391 Stop using dot in release name
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.5.yaml
Labels: lgtm, approved

#28452 Add CI config for RHMI operator branch rhoam-release-v1.21
  ci-operator/config/integr8ly/integreatly-operator/integr8ly-integreatly-operator-rhoam-release-v1.21.yaml
  ci-operator/jobs/integr8ly/integreatly-operator/integr8ly-integreatly-operator-rhoam-release-v1.21-postsubmits.yaml
  ci-operator/jobs/integr8ly/integreatly-operator/integr8ly-integreatly-operator-rhoam-release-v1.21-presubmits.yaml
  core-services/image-mirroring/integr8ly/mapping_integr8ly_operator_1_21
Labels: lgtm, approved, ok-to-test

#28079 Knative eventing release-next testing 4.10 and 4.9
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next__410.yaml
  ci-operator/config/openshift/knative-eventing/openshift-knative-eventing-release-next__49.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-next-postsubmits.yaml
  ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-release-next-presubmits.yaml
Labels: lgtm, approved

#28446 assisted-service: promote index image
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
Labels: lgtm, approved

#28454 Use fully qualified domain names for machine and machineset objects
  ci-operator/step-registry/openstack/provision/sriov-worker/openstack-provision-sriov-worker-commands.sh
Labels: lgtm, approved

#28458 Add image-v2.3.1 to boilerplate
  clusters/app.ci/supplemental-ci-images/boilerplate/boilerplate.yaml
Labels: lgtm, approved

#28432 Add golangci-lint to origin
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
Labels: lgtm, approved

#28461 Update konveyor/mig-operator bz automation
  core-services/prow/02_config/konveyor/mig-operator/_pluginconfig.yaml
Labels: lgtm, approved

#28455 VolSync: switch unit tests to go 1.18
  ci-operator/config/backube/volsync/backube-volsync-main.yaml
Labels: lgtm, approved

#28448 Make cnv optional presubmit job of assisted-service
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
Labels: lgtm, approved

#28464 hypershift: unify test-e2e invocation
  ci-operator/config/openshift/hypershift/openshift-hypershift-main.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-main__periodics.yaml
Labels: lgtm, approved

#28466 Update ViaQ-logging-fluentd-main.yaml
  ci-operator/config/ViaQ/logging-fluentd/ViaQ-logging-fluentd-main.yaml
Labels: lgtm, approved
