Repository openshift/release, pull requests merged in 2023-05, with the labels that each got.

#38882 telco5g: Run nightly jobs on BOS2 upstream lab
  ci-operator/step-registry/telco5g/cluster-setup/telco5g-cluster-setup-commands.sh
Labels: lgtm, approved, rehearsals-ack

#38860 Add a PVC for /var/lib/grafana
  clusters/app.ci/grafana-loki/OWNERS
  clusters/app.ci/grafana-loki/README.md
  clusters/app.ci/grafana-loki/admin_grafana.yaml
Labels: lgtm, approved, rehearsals-ack

#38883 ci-operator/cri-o: add release-1.27 tests config and presubmit jobs
  ci-operator/config/cri-o/cri-o/cri-o-cri-o-release-1.27.yaml
  ci-operator/jobs/cri-o/cri-o/cri-o-cri-o-release-1.27-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#38880 configure vSphere clusterbot jobs to use IBM VIP
  ci-operator/step-registry/ipi/conf/vsphere/dns/ipi-conf-vsphere-dns-commands.sh
Labels: lgtm, approved, rehearsals-ack

#38879 add timeout to LFME
  ci-operator/config/ViaQ/log-file-metric-exporter/ViaQ-log-file-metric-exporter-main.yaml
  ci-operator/jobs/ViaQ/log-file-metric-exporter/ViaQ-log-file-metric-exporter-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#38892 [LPTOCPCI-207] Fixing MTR Interop Scenario Operator Install
  ci-operator/config/windup/windup-ui-tests/windup-windup-ui-tests-v1.0__mtr-ocp4.13-lp-interop.yaml
  ci-operator/step-registry/install-operators/install-operators-commands.sh
Labels: lgtm, approved, rehearsals-ack

#38895 [LPTOCPCI-208] Adding gangway api to OADP scenario
  ci-operator/config/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-main__oadp1.1-ocp4.13-lp-interop.yaml
  ci-operator/jobs/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#38893 Use 4.13 releases for all assisted 2.8 ZTP jobs
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.8.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.8.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.8.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.8.yaml
  ci-operator/config/openshift/cluster-api-provider-agent/openshift-cluster-api-provider-agent-release-ocm-2.8.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.8-periodics.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.8-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.8-presubmits.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.8-periodics.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.8-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.8-presubmits.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.8-periodics.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.8-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.8-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.8-periodics.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.8-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.8-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#38903 Update the image tag for 'backplane-tools' repo
  ci-operator/config/openshift/backplane-tools/openshift-backplane-tools-main.yaml
Labels: lgtm, approved, rehearsals-ack

#38901 [LPTOCPCI-210] Add the aws-cspi-qe-vpn Quota Slice
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: lgtm, approved, rehearsals-ack

#38906 update stackrox mirrors
  core-services/image-mirroring/stackrox/mapping_supplemental_ci_images_stackrox_rox_ci_image
Labels: lgtm, approved, rehearsals-ack

#38886 telco5g: Delete cluster after nightly job
  ci-operator/step-registry/telco5g/cluster-setup/telco5g-cluster-setup-commands.sh
  ci-operator/step-registry/telco5g/jobs-router/telco5g-jobs-router-commands.sh
  ci-operator/step-registry/telco5g/release-cluster/telco5g-release-cluster-commands.sh
  ci-operator/step-registry/telco5g/release-cluster/telco5g-release-cluster-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#38909 test adding back aws-2.ci.openshift.org base domain
  ci-operator/config/openshift/release/openshift-release-master__ci-4.12.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.13.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.14.yaml
Labels: lgtm, approved, rehearsals-ack

#37968 MGMT-14155: Assisted-Installer: Add vsphere version specific periodic presubmit jobs
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-periodics.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#38857 openstack: Improve authentication method selection algorithm
  ci-operator/step-registry/openstack/conf/clouds/openstack-conf-clouds-commands.sh
Labels: lgtm, approved, rehearsals-ack

#38918 Added presubmit 4.11 optional job
  ci-operator/config/rh-ecosystem-edge/ci-tools-nvidia-gpu-operator/rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main__4.11.yaml
  ci-operator/jobs/rh-ecosystem-edge/ci-tools-nvidia-gpu-operator/rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#38726 OSSM-3270: Migrate proxy postsubmit jobs
  ci-operator/config/maistra/proxy/maistra-proxy-maistra-2.2.yaml
  ci-operator/config/maistra/proxy/maistra-proxy-maistra-2.3.yaml
  ci-operator/config/maistra/proxy/maistra-proxy-maistra-2.4.yaml
  ci-operator/jobs/maistra/proxy/maistra-proxy-maistra-2.2-postsubmits.yaml
  ci-operator/jobs/maistra/proxy/maistra-proxy-maistra-2.3-postsubmits.yaml
  ci-operator/jobs/maistra/proxy/maistra-proxy-maistra-2.4-postsubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#38686 Enable nodepool e2e tests for kubevirt platform
  ci-operator/step-registry/hypershift/kubevirt/run-e2e-local/hypershift-kubevirt-run-e2e-local-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#38920 [LPTOCPCI-208] Interop Scenario Re-Trigger 05/01
  ci-operator/config/3scale-qe/3scale-deploy/3scale-qe-3scale-deploy-main__3scale-amp-ocp4.13-lp-interop.yaml
  ci-operator/config/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-main__oadp1.1-ocp4.13-lp-interop.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main__ocp4.13-lp-interop.yaml
  ci-operator/config/windup/windup-ui-tests/windup-windup-ui-tests-v1.0__mtr-ocp4.13-lp-interop.yaml
  ci-operator/jobs/3scale-qe/3scale-deploy/3scale-qe-3scale-deploy-main-periodics.yaml
  ci-operator/jobs/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-main-periodics.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main-periodics.yaml
  ci-operator/jobs/windup/windup-ui-tests/windup-windup-ui-tests-v1.0-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#38861 Adding kiali integration tests image to be used in iterop pipeline
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_ci
Labels: lgtm, approved, rehearsals-ack

#38921 disable periodic PTP jobs temporarily
  ci-operator/step-registry/telco5g/ptp-cluster-setup/telco5g-ptp-cluster-setup-commands.sh
  ci-operator/step-registry/telco5g/ptp/tests/telco5g-ptp-tests-commands.sh
Labels: lgtm, approved, rehearsals-ack

#38927 Create OCP4.12 CP to be consumed by openstack-k8s-operators
  clusters/hive/pools/openstack-k8s-operators/openstack-k8s-operators-4-10-vexxhost-sno_clusterpool.yaml
  clusters/hive/pools/openstack-k8s-operators/openstack-k8s-operators-4-12-vexxhost-sno_clusterpool.yaml
Labels: lgtm, approved, rehearsals-ack

#38842 fix: fixed errors due to arm instances
  ci-operator/config/openshift/microshift/openshift-microshift-main.yaml
  ci-operator/config/openshift/microshift/openshift-microshift-release-4.14.yaml
  ci-operator/config/openshift/microshift/openshift-microshift-release-4.15.yaml
  ci-operator/step-registry/openshift/microshift/infra/aws/ec2/openshift-microshift-infra-aws-ec2-commands.sh
Labels: lgtm, approved, rehearsals-ack

#38933 Cleanup old configurations
  ci-operator/config/stolostron/cert-policy-controller/stolostron-cert-policy-controller-release-2.3.yaml
  ci-operator/config/stolostron/cert-policy-controller/stolostron-cert-policy-controller-release-2.4.yaml
  ci-operator/config/stolostron/config-policy-controller/stolostron-config-policy-controller-release-2.3.yaml
  ci-operator/config/stolostron/config-policy-controller/stolostron-config-policy-controller-release-2.4.yaml
  ci-operator/config/stolostron/governance-policy-framework/stolostron-governance-policy-framework-main.yaml
  ci-operator/config/stolostron/governance-policy-framework/stolostron-governance-policy-framework-release-2.4.yaml
  ci-operator/config/stolostron/governance-policy-propagator/stolostron-governance-policy-propagator-release-2.3.yaml
  ci-operator/config/stolostron/governance-policy-propagator/stolostron-governance-policy-propagator-release-2.4.yaml
  ci-operator/config/stolostron/governance-policy-spec-sync/stolostron-governance-policy-spec-sync-release-2.3.yaml
  ci-operator/config/stolostron/governance-policy-spec-sync/stolostron-governance-policy-spec-sync-release-2.4.yaml
  ci-operator/config/stolostron/governance-policy-status-sync/stolostron-governance-policy-status-sync-release-2.3.yaml
  ci-operator/config/stolostron/governance-policy-status-sync/stolostron-governance-policy-status-sync-release-2.4.yaml
  ci-operator/config/stolostron/governance-policy-template-sync/stolostron-governance-policy-template-sync-release-2.3.yaml
  ci-operator/config/stolostron/governance-policy-template-sync/stolostron-governance-policy-template-sync-release-2.4.yaml
  ci-operator/config/stolostron/iam-policy-controller/stolostron-iam-policy-controller-release-2.3.yaml
  ci-operator/config/stolostron/iam-policy-controller/stolostron-iam-policy-controller-release-2.4.yaml
  ci-operator/jobs/stolostron/cert-policy-controller/stolostron-cert-policy-controller-release-2.3-postsubmits.yaml
  ci-operator/jobs/stolostron/cert-policy-controller/stolostron-cert-policy-controller-release-2.3-presubmits.yaml
  ci-operator/jobs/stolostron/cert-policy-controller/stolostron-cert-policy-controller-release-2.4-postsubmits.yaml
  ci-operator/jobs/stolostron/cert-policy-controller/stolostron-cert-policy-controller-release-2.4-presubmits.yaml
  ci-operator/jobs/stolostron/config-policy-controller/stolostron-config-policy-controller-release-2.3-postsubmits.yaml
  ci-operator/jobs/stolostron/config-policy-controller/stolostron-config-policy-controller-release-2.3-presubmits.yaml
  ci-operator/jobs/stolostron/config-policy-controller/stolostron-config-policy-controller-release-2.4-postsubmits.yaml
  ci-operator/jobs/stolostron/config-policy-controller/stolostron-config-policy-controller-release-2.4-presubmits.yaml
  ci-operator/jobs/stolostron/governance-policy-framework/stolostron-governance-policy-framework-main-periodics.yaml
  ci-operator/jobs/stolostron/governance-policy-framework/stolostron-governance-policy-framework-release-2.4-postsubmits.yaml
  ci-operator/jobs/stolostron/governance-policy-framework/stolostron-governance-policy-framework-release-2.4-presubmits.yaml
  ci-operator/jobs/stolostron/governance-policy-propagator/stolostron-governance-policy-propagator-release-2.3-postsubmits.yaml
  ci-operator/jobs/stolostron/governance-policy-propagator/stolostron-governance-policy-propagator-release-2.3-presubmits.yaml
  ci-operator/jobs/stolostron/governance-policy-propagator/stolostron-governance-policy-propagator-release-2.4-postsubmits.yaml
  ci-operator/jobs/stolostron/governance-policy-propagator/stolostron-governance-policy-propagator-release-2.4-presubmits.yaml
  ci-operator/jobs/stolostron/governance-policy-spec-sync/stolostron-governance-policy-spec-sync-release-2.3-postsubmits.yaml
  ci-operator/jobs/stolostron/governance-policy-spec-sync/stolostron-governance-policy-spec-sync-release-2.3-presubmits.yaml
  ci-operator/jobs/stolostron/governance-policy-spec-sync/stolostron-governance-policy-spec-sync-release-2.4-postsubmits.yaml
  ci-operator/jobs/stolostron/governance-policy-spec-sync/stolostron-governance-policy-spec-sync-release-2.4-presubmits.yaml
  ci-operator/jobs/stolostron/governance-policy-status-sync/stolostron-governance-policy-status-sync-release-2.3-postsubmits.yaml
  ci-operator/jobs/stolostron/governance-policy-status-sync/stolostron-governance-policy-status-sync-release-2.3-presubmits.yaml
  ci-operator/jobs/stolostron/governance-policy-status-sync/stolostron-governance-policy-status-sync-release-2.4-postsubmits.yaml
  ci-operator/jobs/stolostron/governance-policy-status-sync/stolostron-governance-policy-status-sync-release-2.4-presubmits.yaml
  ci-operator/jobs/stolostron/governance-policy-template-sync/stolostron-governance-policy-template-sync-release-2.3-postsubmits.yaml
  ci-operator/jobs/stolostron/governance-policy-template-sync/stolostron-governance-policy-template-sync-release-2.3-presubmits.yaml
  ci-operator/jobs/stolostron/governance-policy-template-sync/stolostron-governance-policy-template-sync-release-2.4-postsubmits.yaml
  ci-operator/jobs/stolostron/governance-policy-template-sync/stolostron-governance-policy-template-sync-release-2.4-presubmits.yaml
  ci-operator/jobs/stolostron/iam-policy-controller/stolostron-iam-policy-controller-release-2.3-postsubmits.yaml
  ci-operator/jobs/stolostron/iam-policy-controller/stolostron-iam-policy-controller-release-2.3-presubmits.yaml
  ci-operator/jobs/stolostron/iam-policy-controller/stolostron-iam-policy-controller-release-2.4-postsubmits.yaml
  ci-operator/jobs/stolostron/iam-policy-controller/stolostron-iam-policy-controller-release-2.4-presubmits.yaml
  core-services/prow/02_config/stolostron/cert-policy-controller/_prowconfig.yaml
  core-services/prow/02_config/stolostron/config-policy-controller/_prowconfig.yaml
  core-services/prow/02_config/stolostron/go-template-utils/_prowconfig.yaml
  core-services/prow/02_config/stolostron/governance-policy-framework/_prowconfig.yaml
  core-services/prow/02_config/stolostron/governance-policy-propagator/_prowconfig.yaml
  core-services/prow/02_config/stolostron/governance-policy-spec-sync/_prowconfig.yaml
  core-services/prow/02_config/stolostron/governance-policy-status-sync/_prowconfig.yaml
  core-services/prow/02_config/stolostron/governance-policy-template-sync/_prowconfig.yaml
  core-services/prow/02_config/stolostron/iam-policy-controller/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#38931 core-services/cri-o: trust dependabot
  core-services/prow/02_config/cri-o/cri-o/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#38812 vSphere: remove VMC from leases
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: lgtm, approved, rehearsals-ack

#38940 Update the image tag for 'backplane-tools' repo (again)
  ci-operator/config/openshift/backplane-tools/openshift-backplane-tools-main.yaml
Labels: lgtm, approved, rehearsals-ack

#38518 OpenStack: New environment for `mecha` cloud
  ci-operator/config/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main__periodic-4.10.yaml
  ci-operator/config/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main__periodic-4.11.yaml
  ci-operator/config/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main__periodic-4.12.yaml
  ci-operator/config/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main__periodic-4.13.yaml
  ci-operator/config/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main__periodic-4.14.yaml
  ci-operator/config/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main__periodic-4.9.yaml
  ci-operator/jobs/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main-periodics.yaml
  ci-operator/step-registry/openshift/e2e/openstack/csi/cinder/openshift-e2e-openstack-csi-cinder-workflow.yaml
  ci-operator/step-registry/openshift/e2e/openstack/csi/manila/openshift-e2e-openstack-csi-manila-workflow.yaml
  ci-operator/step-registry/openstack/conf/installconfig/openstack-conf-installconfig-commands.sh
  ci-operator/step-registry/openstack/conf/installconfig/openstack-conf-installconfig-ref.yaml
  ci-operator/step-registry/openstack/conf/proxy/openstack-conf-proxy-commands.sh
  ci-operator/step-registry/openstack/conf/resourcenames/openstack-conf-resourcenames-commands.sh
  ci-operator/step-registry/openstack/deprovision/bastionproxy/openstack-deprovision-bastionproxy-commands.sh
  ci-operator/step-registry/openstack/deprovision/machinesubnet/openstack-deprovision-machinesubnet-commands.sh
  ci-operator/step-registry/openstack/deprovision/machinesubnet/openstack-deprovision-machinesubnet-ref.yaml
  ci-operator/step-registry/openstack/provision/bastionproxy/openstack-provision-bastionproxy-commands.sh
  ci-operator/step-registry/openstack/provision/bastionproxy/openstack-provision-bastionproxy-ref.yaml
  ci-operator/step-registry/openstack/provision/machinesubnet/openstack-provision-machinesubnet-commands.sh
  ci-operator/step-registry/openstack/provision/machinesubnet/openstack-provision-machinesubnet-ref.yaml
  ci-operator/step-registry/storage/obj/check/storage-obj-check-commands.sh
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: lgtm, approved, rehearsals-ack

#38779 modelmesh runtime adapter to openshift ci
  ci-operator/config/opendatahub-io/modelmesh-runtime-adapter/OWNERS
  ci-operator/config/opendatahub-io/modelmesh-runtime-adapter/opendatahub-io-modelmesh-runtime-adapter-main.yaml
  ci-operator/config/opendatahub-io/modelmesh-runtime-adapter/opendatahub-io-modelmesh-runtime-adapter-release-v0.11.0-alpha.yaml
  ci-operator/jobs/opendatahub-io/modelmesh-runtime-adapter/OWNERS
  ci-operator/jobs/opendatahub-io/modelmesh-runtime-adapter/opendatahub-io-modelmesh-runtime-adapter-main-postsubmits.yaml
  ci-operator/jobs/opendatahub-io/modelmesh-runtime-adapter/opendatahub-io-modelmesh-runtime-adapter-main-presubmits.yaml
  ci-operator/jobs/opendatahub-io/modelmesh-runtime-adapter/opendatahub-io-modelmesh-runtime-adapter-release-v0.11.0-alpha-postsubmits.yaml
  ci-operator/jobs/opendatahub-io/modelmesh-runtime-adapter/opendatahub-io-modelmesh-runtime-adapter-release-v0.11.0-alpha-presubmits.yaml
  core-services/prow/02_config/opendatahub-io/modelmesh-runtime-adapter/OWNERS
  core-services/prow/02_config/opendatahub-io/modelmesh-runtime-adapter/_pluginconfig.yaml
  core-services/prow/02_config/opendatahub-io/modelmesh-runtime-adapter/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#38937 [LPTOCPCI-208] Stagger Interop Scenarios and Fix OADP Operator Install
  ci-operator/config/3scale-qe/3scale-deploy/3scale-qe-3scale-deploy-main__3scale-amp-ocp4.13-lp-interop.yaml
  ci-operator/config/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-main__oadp1.1-ocp4.13-lp-interop.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main__ocp4.13-lp-interop.yaml
  ci-operator/config/windup/windup-ui-tests/windup-windup-ui-tests-v1.0__mtr-ocp4.13-lp-interop.yaml
  ci-operator/jobs/3scale-qe/3scale-deploy/3scale-qe-3scale-deploy-main-periodics.yaml
  ci-operator/jobs/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-main-periodics.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main-periodics.yaml
  ci-operator/jobs/windup/windup-ui-tests/windup-windup-ui-tests-v1.0-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#38908 stackrox: run UI e2e under ocp
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-10.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-12.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies__ocp-4-10.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies__ocp-4-12.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-x.y__ocp-4-10.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-x.y__ocp-4-12.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-postsubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-nightlies-postsubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-x.y-postsubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#38938 remove elb snice jobs no longer run in VMC
  ci-operator/step-registry/ipi/conf/vsphere/dns/ipi-conf-vsphere-dns-commands.sh
  ci-operator/step-registry/ipi/conf/vsphere/ipi-conf-vsphere-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#38730 vSphere: OCP 4.10 reduce nightly to weekly
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.10.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#38825 [release-1.29] Add Serverless operator CI config
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.29.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.29__4.10.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.29__4.12.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.29-postsubmits.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.29-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#38949 [LPTOCPCI-208] Fix 3Scale operator install and update schedules
  ci-operator/config/3scale-qe/3scale-deploy/3scale-qe-3scale-deploy-main__3scale-amp-ocp4.13-lp-interop.yaml
  ci-operator/config/windup/windup-ui-tests/windup-windup-ui-tests-v1.0__mtr-ocp4.13-lp-interop.yaml
  ci-operator/jobs/3scale-qe/3scale-deploy/3scale-qe-3scale-deploy-main-periodics.yaml
  ci-operator/jobs/windup/windup-ui-tests/windup-windup-ui-tests-v1.0-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#38165 ODH workbench: Build the runtime images on post and pre submit jobs
  ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-main.yaml
  ci-operator/jobs/opendatahub-io/notebooks/opendatahub-io-notebooks-main-postsubmits.yaml
  ci-operator/jobs/opendatahub-io/notebooks/opendatahub-io-notebooks-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#38925 Add cnv-qe-tests images mirroring + RBAC
  ci-operator/jobs/infra-image-mirroring.yaml
  clusters/app.ci/registry-access/cnv-qe/admin_rbac.yaml
  core-services/image-mirroring/openshift-cnv/OWNERS
  core-services/image-mirroring/openshift-cnv/mapping_openshift-cnv
Labels: lgtm, approved, rehearsals-ack

#38896 WINC-1035: Configuration of the nutanix-e2e test jobs for Windows
  ci-operator/config/openshift/cloud-provider-nutanix/openshift-cloud-provider-nutanix-main.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-master.yaml
  ci-operator/jobs/openshift/cloud-provider-nutanix/openshift-cloud-provider-nutanix-main-presubmits.yaml
  ci-operator/jobs/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#38956 NO-ISSUE: Update frequency for assisted/ocp4.10 periodic
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#38955 Add assign plugin to maistra
  core-services/prow/02_config/maistra/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#38629 MSI: Add test variant and remove un-used repo
  ci-operator/config/CSPI-QE/MSI/CSPI-QE-MSI-rdbaas-operator-addon__v4.12.yaml
  ci-operator/config/CSPI-QE/amq-streams/OWNERS
  ci-operator/jobs/CSPI-QE/MSI/CSPI-QE-MSI-rdbaas-operator-addon-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#38954 NO-ISSUE: Remove all periodics for assisted in 2.5
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.5.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.5.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.5.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.5-periodics.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.5-periodics.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.5-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#38952 Drop Azure/GCP CCM install jobs on 4.12+
  ci-operator/config/openshift-priv/cloud-provider-azure/openshift-priv-cloud-provider-azure-master.yaml
  ci-operator/config/openshift-priv/cloud-provider-azure/openshift-priv-cloud-provider-azure-release-4.12.yaml
  ci-operator/config/openshift-priv/cloud-provider-azure/openshift-priv-cloud-provider-azure-release-4.13.yaml
  ci-operator/config/openshift-priv/cloud-provider-azure/openshift-priv-cloud-provider-azure-release-4.14.yaml
  ci-operator/config/openshift-priv/cloud-provider-azure/openshift-priv-cloud-provider-azure-release-4.15.yaml
  ci-operator/config/openshift-priv/cloud-provider-gcp/openshift-priv-cloud-provider-gcp-master.yaml
  ci-operator/config/openshift-priv/cloud-provider-gcp/openshift-priv-cloud-provider-gcp-release-4.12.yaml
  ci-operator/config/openshift-priv/cloud-provider-gcp/openshift-priv-cloud-provider-gcp-release-4.13.yaml
  ci-operator/config/openshift-priv/cloud-provider-gcp/openshift-priv-cloud-provider-gcp-release-4.14.yaml
  ci-operator/config/openshift-priv/cloud-provider-gcp/openshift-priv-cloud-provider-gcp-release-4.15.yaml
  ci-operator/config/openshift-priv/cluster-cloud-controller-manager-operator/openshift-priv-cluster-cloud-controller-manager-operator-master.yaml
  ci-operator/config/openshift-priv/cluster-cloud-controller-manager-operator/openshift-priv-cluster-cloud-controller-manager-operator-release-4.12.yaml
  ci-operator/config/openshift-priv/cluster-cloud-controller-manager-operator/openshift-priv-cluster-cloud-controller-manager-operator-release-4.13.yaml
  ci-operator/config/openshift-priv/cluster-cloud-controller-manager-operator/openshift-priv-cluster-cloud-controller-manager-operator-release-4.14.yaml
  ci-operator/config/openshift-priv/cluster-cloud-controller-manager-operator/openshift-priv-cluster-cloud-controller-manager-operator-release-4.15.yaml
  ci-operator/config/openshift/cloud-provider-azure/openshift-cloud-provider-azure-master.yaml
  ci-operator/config/openshift/cloud-provider-azure/openshift-cloud-provider-azure-release-4.12.yaml
  ci-operator/config/openshift/cloud-provider-azure/openshift-cloud-provider-azure-release-4.13.yaml
  ci-operator/config/openshift/cloud-provider-azure/openshift-cloud-provider-azure-release-4.14.yaml
  ci-operator/config/openshift/cloud-provider-azure/openshift-cloud-provider-azure-release-4.15.yaml
  ci-operator/config/openshift/cloud-provider-gcp/openshift-cloud-provider-gcp-master.yaml
  ci-operator/config/openshift/cloud-provider-gcp/openshift-cloud-provider-gcp-release-4.12.yaml
  ci-operator/config/openshift/cloud-provider-gcp/openshift-cloud-provider-gcp-release-4.13.yaml
  ci-operator/config/openshift/cloud-provider-gcp/openshift-cloud-provider-gcp-release-4.14.yaml
  ci-operator/config/openshift/cloud-provider-gcp/openshift-cloud-provider-gcp-release-4.15.yaml
  ci-operator/config/openshift/cluster-cloud-controller-manager-operator/openshift-cluster-cloud-controller-manager-operator-master.yaml
  ci-operator/config/openshift/cluster-cloud-controller-manager-operator/openshift-cluster-cloud-controller-manager-operator-release-4.12.yaml
  ci-operator/config/openshift/cluster-cloud-controller-manager-operator/openshift-cluster-cloud-controller-manager-operator-release-4.13.yaml
  ci-operator/config/openshift/cluster-cloud-controller-manager-operator/openshift-cluster-cloud-controller-manager-operator-release-4.14.yaml
  ci-operator/config/openshift/cluster-cloud-controller-manager-operator/openshift-cluster-cloud-controller-manager-operator-release-4.15.yaml
  ci-operator/jobs/openshift-priv/cloud-provider-azure/openshift-priv-cloud-provider-azure-master-presubmits.yaml
  ci-operator/jobs/openshift-priv/cloud-provider-azure/openshift-priv-cloud-provider-azure-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift-priv/cloud-provider-azure/openshift-priv-cloud-provider-azure-release-4.13-presubmits.yaml
  ci-operator/jobs/openshift-priv/cloud-provider-azure/openshift-priv-cloud-provider-azure-release-4.14-presubmits.yaml
  ci-operator/jobs/openshift-priv/cloud-provider-azure/openshift-priv-cloud-provider-azure-release-4.15-presubmits.yaml
  ci-operator/jobs/openshift-priv/cloud-provider-gcp/openshift-priv-cloud-provider-gcp-master-presubmits.yaml
  ci-operator/jobs/openshift-priv/cloud-provider-gcp/openshift-priv-cloud-provider-gcp-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift-priv/cloud-provider-gcp/openshift-priv-cloud-provider-gcp-release-4.13-presubmits.yaml
  ci-operator/jobs/openshift-priv/cloud-provider-gcp/openshift-priv-cloud-provider-gcp-release-4.14-presubmits.yaml
  ci-operator/jobs/openshift-priv/cloud-provider-gcp/openshift-priv-cloud-provider-gcp-release-4.15-presubmits.yaml
  ci-operator/jobs/openshift-priv/cluster-cloud-controller-manager-operator/openshift-priv-cluster-cloud-controller-manager-operator-master-presubmits.yaml
  ci-operator/jobs/openshift-priv/cluster-cloud-controller-manager-operator/openshift-priv-cluster-cloud-controller-manager-operator-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift-priv/cluster-cloud-controller-manager-operator/openshift-priv-cluster-cloud-controller-manager-operator-release-4.13-presubmits.yaml
  ci-operator/jobs/openshift-priv/cluster-cloud-controller-manager-operator/openshift-priv-cluster-cloud-controller-manager-operator-release-4.14-presubmits.yaml
  ci-operator/jobs/openshift-priv/cluster-cloud-controller-manager-operator/openshift-priv-cluster-cloud-controller-manager-operator-release-4.15-presubmits.yaml
  ci-operator/jobs/openshift/cloud-provider-azure/openshift-cloud-provider-azure-master-presubmits.yaml
  ci-operator/jobs/openshift/cloud-provider-azure/openshift-cloud-provider-azure-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift/cloud-provider-azure/openshift-cloud-provider-azure-release-4.13-presubmits.yaml
  ci-operator/jobs/openshift/cloud-provider-azure/openshift-cloud-provider-azure-release-4.14-presubmits.yaml
  ci-operator/jobs/openshift/cloud-provider-azure/openshift-cloud-provider-azure-release-4.15-presubmits.yaml
  ci-operator/jobs/openshift/cloud-provider-gcp/openshift-cloud-provider-gcp-master-presubmits.yaml
  ci-operator/jobs/openshift/cloud-provider-gcp/openshift-cloud-provider-gcp-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift/cloud-provider-gcp/openshift-cloud-provider-gcp-release-4.13-presubmits.yaml
  ci-operator/jobs/openshift/cloud-provider-gcp/openshift-cloud-provider-gcp-release-4.14-presubmits.yaml
  ci-operator/jobs/openshift/cloud-provider-gcp/openshift-cloud-provider-gcp-release-4.15-presubmits.yaml
  ci-operator/jobs/openshift/cluster-cloud-controller-manager-operator/openshift-cluster-cloud-controller-manager-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-cloud-controller-manager-operator/openshift-cluster-cloud-controller-manager-operator-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift/cluster-cloud-controller-manager-operator/openshift-cluster-cloud-controller-manager-operator-release-4.13-presubmits.yaml
  ci-operator/jobs/openshift/cluster-cloud-controller-manager-operator/openshift-cluster-cloud-controller-manager-operator-release-4.14-presubmits.yaml
  ci-operator/jobs/openshift/cluster-cloud-controller-manager-operator/openshift-cluster-cloud-controller-manager-operator-release-4.15-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#38963 openstack-deprovision-machinesubnet: remove useless comment
  ci-operator/step-registry/openstack/deprovision/machinesubnet/openstack-deprovision-machinesubnet-commands.sh
Labels: lgtm, approved, rehearsals-ack

#33499 CONSOLE-3303: Move plugin template to the openshift GitHub org
  ci-operator/config/openshift/console-plugin-template/OWNERS
  ci-operator/config/openshift/console-plugin-template/openshift-console-plugin-template-main.yaml
  ci-operator/jobs/openshift/console-plugin-template/OWNERS
  ci-operator/jobs/openshift/console-plugin-template/openshift-console-plugin-template-main-postsubmits.yaml
  ci-operator/jobs/openshift/console-plugin-template/openshift-console-plugin-template-main-presubmits.yaml
  core-services/image-mirroring/openshift/mapping_origin_4_14
  core-services/prow/02_config/openshift/console-plugin-template/_pluginconfig.yaml
  core-services/prow/02_config/openshift/console-plugin-template/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#38808 Add retester aws credentials
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#38947 Fix Azure CCM OVN Hybrid Install
  ci-operator/step-registry/openshift/e2e/azure/ccm/ovn-hybrid-install/openshift-e2e-azure-ccm-ovn-hybrid-install-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#38967 Update jenkins-openshift-login-plugin to use .ci-operator.yaml file
  ci-operator/config/openshift/jenkins-openshift-login-plugin/openshift-jenkins-openshift-login-plugin-release-4.15.yaml
Labels: lgtm, approved, rehearsals-ack

#38912 add recovery test suite to origin master presubmits
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#38974 Upload github users's cost center
  ci-operator/jobs/infra-periodics.yaml
  clusters/psi/sync-rover-groups-update_cronjob.yaml
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#38970 Created new labels for SD Docs to use for review requests
  core-services/prow/02_config/_labels.yaml
  core-services/prow/02_config/openshift/openshift-docs/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#38987 Fix job/periodic-github-ldap-user-group-creator
  ci-operator/jobs/infra-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#38985 shiftstack/quotas: tolerate > 10% of resource available from quotas
  ci-operator/step-registry/shiftstack/quotas/shiftstack-quotas-commands.sh
  ci-operator/step-registry/shiftstack/quotas/shiftstack-quotas-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#38994 Add automountServiceAccountToken to cnv-tests mirroring
  ci-operator/jobs/infra-image-mirroring.yaml
Labels: lgtm, approved, rehearsals-ack

#38362 Add build job for openshift/windows_exporter
  ci-operator/config/openshift/prometheus-community-windows_exporter/OWNERS
  ci-operator/config/openshift/prometheus-community-windows_exporter/openshift-prometheus-community-windows_exporter-master.yaml
  ci-operator/jobs/openshift/prometheus-community-windows_exporter/OWNERS
  ci-operator/jobs/openshift/prometheus-community-windows_exporter/openshift-prometheus-community-windows_exporter-master-presubmits.yaml
  core-services/prow/02_config/openshift/prometheus-community-windows_exporter/OWNERS
  core-services/prow/02_config/openshift/prometheus-community-windows_exporter/_pluginconfig.yaml
  core-services/prow/02_config/openshift/prometheus-community-windows_exporter/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#38997 Use REGISTRY_AUTH_FILE as argument to oc mirror command
  ci-operator/jobs/infra-image-mirroring.yaml
Labels: lgtm, approved, rehearsals-ack

#38894 stackrox: tighten RC bounds for ocp 4.13
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-13.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies__ocp-4-13.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-x.y__ocp-4-13.yaml
Labels: lgtm, approved, rehearsals-ack

#38953 New(image-mirroring): Tests image for Red Hat Integration Service Reg…
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_ci
Labels: lgtm, approved, rehearsals-ack

#38930 Add rebasebot periodic job for openstack-sushy
  ci-operator/config/openshift-eng/rebasebot/openshift-eng-rebasebot-main.yaml
  ci-operator/jobs/openshift-eng/rebasebot/openshift-eng-rebasebot-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#38704 feat: add clean-quay-tags to cronjob
  ci-operator/step-registry/redhat-appstudio/clean-external-resources/redhat-appstudio-clean-external-resources-commands.sh
Labels: lgtm, approved, rehearsals-ack

#39003 grafana-loki: Add token-refresher sidecar for dpcr loki datasource
  clusters/app.ci/grafana-loki/admin_grafana.yaml
Labels: lgtm, approved, rehearsals-ack

#39008 Add psalajova as dptp approver
  OWNERS_ALIASES
Labels: lgtm, approved, rehearsals-ack

#38979 Rework a bit the pluginconfig associated to ci-framework
  core-services/prow/02_config/openstack-k8s-operators/ci-framework/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#38977 [LPTOCPCI-221] Add Gangway API to all interop scenarios
  ci-operator/config/3scale-qe/3scale-deploy/3scale-qe-3scale-deploy-main__3scale-amp-ocp4.13-lp-interop.yaml
  ci-operator/config/amq-streams-qe/strimzi-kafka-operator/amq-streams-qe-strimzi-kafka-operator-main__amq-streams-ocp4.13-lp-interop.yaml
  ci-operator/config/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-main__oadp1.1-ocp4.13-lp-interop.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main__ocp4.13-lp-interop.yaml
  ci-operator/config/redhat-developer/odo/redhat-developer-odo-main__odo-ocp4.13-lp-interop.yaml
  ci-operator/config/windup/windup-ui-tests/windup-windup-ui-tests-v1.0__mtr-ocp4.13-lp-interop.yaml
  ci-operator/jobs/3scale-qe/3scale-deploy/3scale-qe-3scale-deploy-main-periodics.yaml
  ci-operator/jobs/amq-streams-qe/strimzi-kafka-operator/amq-streams-qe-strimzi-kafka-operator-main-periodics.yaml
  ci-operator/jobs/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-main-periodics.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main-periodics.yaml
  ci-operator/jobs/redhat-developer/odo/redhat-developer-odo-main-periodics.yaml
  ci-operator/jobs/windup/windup-ui-tests/windup-windup-ui-tests-v1.0-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#38907 Bump CI image for go1.20.3
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-10.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-12.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-13.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies__ocp-4-10.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies__ocp-4-12.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies__ocp-4-13.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-x.y.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-x.y__ocp-4-10.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-x.y__ocp-4-12.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-x.y__ocp-4-13.yaml
Labels: lgtm, approved, rehearsals-ack

#38877 USHIFT-1201: Transition to AWS
  ci-operator/config/openshift/microshift/openshift-microshift-release-4.13.yaml
  ci-operator/jobs/openshift/microshift/openshift-microshift-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/microshift/openshift-microshift-release-4.13-presubmits.yaml
  ci-operator/step-registry/openshift/microshift/e2e/greenboot-aws/OWNERS
  ci-operator/step-registry/openshift/microshift/e2e/greenboot-aws/openshift-microshift-e2e-greenboot-aws-chain.metadata.json
  ci-operator/step-registry/openshift/microshift/e2e/greenboot-aws/openshift-microshift-e2e-greenboot-aws-chain.yaml
  ci-operator/step-registry/openshift/microshift/e2e/greenboot-aws/openshift-microshift-e2e-greenboot-aws-commands.sh
  ci-operator/step-registry/openshift/microshift/e2e/greenboot-aws/openshift-microshift-e2e-greenboot-aws-ref.metadata.json
  ci-operator/step-registry/openshift/microshift/e2e/greenboot-aws/openshift-microshift-e2e-greenboot-aws-ref.yaml
  ci-operator/step-registry/openshift/microshift/e2e/greenboot-aws/openshift-microshift-e2e-greenboot-aws-workflow.metadata.json
  ci-operator/step-registry/openshift/microshift/e2e/greenboot-aws/openshift-microshift-e2e-greenboot-aws-workflow.yaml
  ci-operator/step-registry/openshift/microshift/e2e/loadbalancer-smoke-test-aws/OWNERS
  ci-operator/step-registry/openshift/microshift/e2e/loadbalancer-smoke-test-aws/openshift-microshift-e2e-loadbalancer-smoke-test-aws-chain.metadata.json
  ci-operator/step-registry/openshift/microshift/e2e/loadbalancer-smoke-test-aws/openshift-microshift-e2e-loadbalancer-smoke-test-aws-chain.yaml
  ci-operator/step-registry/openshift/microshift/e2e/loadbalancer-smoke-test-aws/openshift-microshift-e2e-loadbalancer-smoke-test-aws-commands.sh
  ci-operator/step-registry/openshift/microshift/e2e/loadbalancer-smoke-test-aws/openshift-microshift-e2e-loadbalancer-smoke-test-aws-ref.metadata.json
  ci-operator/step-registry/openshift/microshift/e2e/loadbalancer-smoke-test-aws/openshift-microshift-e2e-loadbalancer-smoke-test-aws-ref.yaml
  ci-operator/step-registry/openshift/microshift/e2e/loadbalancer-smoke-test-aws/openshift-microshift-e2e-loadbalancer-smoke-test-aws-workflow.metadata.json
  ci-operator/step-registry/openshift/microshift/e2e/loadbalancer-smoke-test-aws/openshift-microshift-e2e-loadbalancer-smoke-test-aws-workflow.yaml
  ci-operator/step-registry/openshift/microshift/e2e/reboot-tests-aws/OWNERS
  ci-operator/step-registry/openshift/microshift/e2e/reboot-tests-aws/openshift-microshift-e2e-reboot-tests-aws-chain.metadata.json
  ci-operator/step-registry/openshift/microshift/e2e/reboot-tests-aws/openshift-microshift-e2e-reboot-tests-aws-chain.yaml
  ci-operator/step-registry/openshift/microshift/e2e/reboot-tests-aws/openshift-microshift-e2e-reboot-tests-aws-commands.sh
  ci-operator/step-registry/openshift/microshift/e2e/reboot-tests-aws/openshift-microshift-e2e-reboot-tests-aws-ref.metadata.json
  ci-operator/step-registry/openshift/microshift/e2e/reboot-tests-aws/openshift-microshift-e2e-reboot-tests-aws-ref.yaml
  ci-operator/step-registry/openshift/microshift/e2e/reboot-tests-aws/openshift-microshift-e2e-reboot-tests-aws-workflow.metadata.json
  ci-operator/step-registry/openshift/microshift/e2e/reboot-tests-aws/openshift-microshift-e2e-reboot-tests-aws-workflow.yaml
  ci-operator/step-registry/openshift/microshift/e2e/reboot-tests-aws/verify/OWNERS
  ci-operator/step-registry/openshift/microshift/e2e/reboot-tests-aws/verify/openshift-microshift-e2e-reboot-tests-aws-verify-commands.sh
  ci-operator/step-registry/openshift/microshift/e2e/reboot-tests-aws/verify/openshift-microshift-e2e-reboot-tests-aws-verify-ref.metadata.json
  ci-operator/step-registry/openshift/microshift/e2e/reboot-tests-aws/verify/openshift-microshift-e2e-reboot-tests-aws-verify-ref.yaml
  ci-operator/step-registry/openshift/microshift/e2e/router-smoke-test-aws/OWNERS
  ci-operator/step-registry/openshift/microshift/e2e/router-smoke-test-aws/openshift-microshift-e2e-router-smoke-test-aws-chain.metadata.json
  ci-operator/step-registry/openshift/microshift/e2e/router-smoke-test-aws/openshift-microshift-e2e-router-smoke-test-aws-chain.yaml
  ci-operator/step-registry/openshift/microshift/e2e/router-smoke-test-aws/openshift-microshift-e2e-router-smoke-test-aws-commands.sh
  ci-operator/step-registry/openshift/microshift/e2e/router-smoke-test-aws/openshift-microshift-e2e-router-smoke-test-aws-ref.metadata.json
  ci-operator/step-registry/openshift/microshift/e2e/router-smoke-test-aws/openshift-microshift-e2e-router-smoke-test-aws-ref.yaml
  ci-operator/step-registry/openshift/microshift/e2e/router-smoke-test-aws/openshift-microshift-e2e-router-smoke-test-aws-workflow.metadata.json
  ci-operator/step-registry/openshift/microshift/e2e/router-smoke-test-aws/openshift-microshift-e2e-router-smoke-test-aws-workflow.yaml
  ci-operator/step-registry/openshift/microshift/e2e/test-aws/OWNERS
  ci-operator/step-registry/openshift/microshift/e2e/test-aws/openshift-microshift-e2e-test-aws-chain.metadata.json
  ci-operator/step-registry/openshift/microshift/e2e/test-aws/openshift-microshift-e2e-test-aws-chain.yaml
  ci-operator/step-registry/openshift/microshift/e2e/test-aws/openshift-microshift-e2e-test-aws-commands.sh
  ci-operator/step-registry/openshift/microshift/e2e/test-aws/openshift-microshift-e2e-test-aws-ref.metadata.json
  ci-operator/step-registry/openshift/microshift/e2e/test-aws/openshift-microshift-e2e-test-aws-ref.yaml
  ci-operator/step-registry/openshift/microshift/e2e/test-aws/openshift-microshift-e2e-test-aws-workflow.metadata.json
  ci-operator/step-registry/openshift/microshift/e2e/test-aws/openshift-microshift-e2e-test-aws-workflow.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#39012 hypershift: add HO install flags for CI
  ci-operator/step-registry/hypershift/install/hypershift-install-commands.sh
Labels: lgtm, approved, rehearsals-ack

#39015 OCPVE-286: Integrate code coverage tooling into lvm-operator
  ci-operator/config/openshift/lvm-operator/openshift-lvm-operator-main.yaml
  ci-operator/jobs/openshift/lvm-operator/openshift-lvm-operator-main-postsubmits.yaml
  ci-operator/jobs/openshift/lvm-operator/openshift-lvm-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#38914 dpcr loki
  ci-operator/step-registry/ipi/install/hosted-loki/ipi-install-hosted-loki-commands.sh
  ci-operator/step-registry/ipi/install/hosted-loki/ipi-install-hosted-loki-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#38980 add -ovn- to multiarch presubmits
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.13-upgrade-from-nightly-4.12.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.13-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.14-upgrade-from-nightly-4.13.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.14-upgrade-from-stable-4.13.yaml
  ci-operator/jobs/openshift/multiarch/openshift-multiarch-master-periodics.yaml
  core-services/release-controller/_releases/priv/release-ocp-4.13-multi.json
  core-services/release-controller/_releases/priv/release-ocp-4.14-multi.json
  core-services/release-controller/_releases/release-ocp-4.13-multi.json
  core-services/release-controller/_releases/release-ocp-4.14-multi.json
Labels: lgtm, approved, rehearsals-ack

#38984 Allow post steps to be run as best-effor in AWS ecryption job
  ci-operator/step-registry/ipi/aws/ipi-aws-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#38215 Bump the FIO pull spec to match the latest version
  ci-operator/config/openshift/file-integrity-operator/openshift-file-integrity-operator-master.yaml
Labels: lgtm, approved, rehearsals-ack

#38983 add -ovn- to release periodic job names missing it
  ci-operator/config/openshift/release/openshift-release-master__ci-4.13-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.14-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.12.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.13.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#38678 ROX-16624: Enable OCP 4.13 for ACS 3.74
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-3.74__ocp-4-13.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-3.74-postsubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-3.74-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#38959 Onboard new terraform-provider-ocm component
  ci-operator/config/terraform-redhat/terraform-provider-ocm/OWNERS
  ci-operator/config/terraform-redhat/terraform-provider-ocm/terraform-redhat-terraform-provider-ocm-main.yaml
  ci-operator/jobs/terraform-redhat/terraform-provider-ocm/OWNERS
  ci-operator/jobs/terraform-redhat/terraform-provider-ocm/terraform-redhat-terraform-provider-ocm-main-presubmits.yaml
  core-services/prow/02_config/terraform-redhat/terraform-provider-ocm/_pluginconfig.yaml
  core-services/prow/02_config/terraform-redhat/terraform-provider-ocm/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#38290 Add nmstatectl for the unit tests #38290
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
Labels: lgtm, approved, rehearsals-ack

#38993 add rest-proxy repo to openshift ci
  ci-operator/config/opendatahub-io/rest-proxy/OWNERS
  ci-operator/config/opendatahub-io/rest-proxy/opendatahub-io-rest-proxy-main.yaml
  ci-operator/config/opendatahub-io/rest-proxy/opendatahub-io-rest-proxy-release-v0.10.0.yaml
  ci-operator/jobs/opendatahub-io/rest-proxy/OWNERS
  ci-operator/jobs/opendatahub-io/rest-proxy/opendatahub-io-rest-proxy-main-postsubmits.yaml
  ci-operator/jobs/opendatahub-io/rest-proxy/opendatahub-io-rest-proxy-main-presubmits.yaml
  ci-operator/jobs/opendatahub-io/rest-proxy/opendatahub-io-rest-proxy-release-v0.10.0-postsubmits.yaml
  ci-operator/jobs/opendatahub-io/rest-proxy/opendatahub-io-rest-proxy-release-v0.10.0-presubmits.yaml
  core-services/prow/02_config/opendatahub-io/rest-proxy/OWNERS
  core-services/prow/02_config/opendatahub-io/rest-proxy/_pluginconfig.yaml
  core-services/prow/02_config/opendatahub-io/rest-proxy/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#39022 Fast forward to 2.9 release branch and use go 1.19 for unit tests
  ci-operator/config/stolostron/cluster-backup-operator/stolostron-cluster-backup-operator-main.yaml
  ci-operator/config/stolostron/cluster-backup-operator/stolostron-cluster-backup-operator-release-2.4.yaml
  ci-operator/config/stolostron/cluster-backup-operator/stolostron-cluster-backup-operator-release-2.5.yaml
  ci-operator/config/stolostron/cluster-backup-operator/stolostron-cluster-backup-operator-release-2.6.yaml
  ci-operator/config/stolostron/cluster-backup-operator/stolostron-cluster-backup-operator-release-2.7.yaml
  ci-operator/config/stolostron/cluster-backup-operator/stolostron-cluster-backup-operator-release-2.8.yaml
  ci-operator/config/stolostron/cluster-backup-operator/stolostron-cluster-backup-operator-release-2.9.yaml
Labels: lgtm, approved, rehearsals-ack

#38899 Update operator image to v1.6.0
  ci-operator/config/opendatahub-io/opendatahub-operator/opendatahub-io-opendatahub-operator-master.yaml
Labels: lgtm, approved, rehearsals-ack

#38981 Bump coreos-assembler to Fedora 38
  ci-operator/config/coreos/coreos-assembler/coreos-coreos-assembler-main.yaml
Labels: lgtm, approved, rehearsals-ack

#38904 Add must-gather images for ODH
  ci-operator/config/opendatahub-io/odh-manifests/opendatahub-io-odh-manifests-master.yaml
  ci-operator/config/opendatahub-io/odh-manifests/opendatahub-io-odh-manifests-master__410.yaml
  ci-operator/config/opendatahub-io/odh-manifests/opendatahub-io-odh-manifests-master__411.yaml
  ci-operator/config/red-hat-data-services/must-gather/OWNERS
  ci-operator/config/red-hat-data-services/must-gather/red-hat-data-services-must-gather-main.yaml
  ci-operator/jobs/opendatahub-io/odh-manifests/opendatahub-io-odh-manifests-master-postsubmits.yaml
  ci-operator/jobs/opendatahub-io/odh-manifests/opendatahub-io-odh-manifests-master-presubmits.yaml
  ci-operator/jobs/red-hat-data-services/must-gather/OWNERS
  ci-operator/jobs/red-hat-data-services/must-gather/red-hat-data-services-must-gather-main-postsubmits.yaml
  ci-operator/jobs/red-hat-data-services/must-gather/red-hat-data-services-must-gather-main-presubmits.yaml
  core-services/prow/02_config/red-hat-data-services/must-gather/OWNERS
  core-services/prow/02_config/red-hat-data-services/must-gather/_pluginconfig.yaml
  core-services/prow/02_config/red-hat-data-services/must-gather/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#39000 Use 4.14 "upi-installer" to avoid "ERROR: Python 2 is not compatible with the Google Cloud SDK. Please use Python version 3.5 and up."
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.14.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
  ci-operator/step-registry/cucushift/installer/check/gcp/disk-encryption/cucushift-installer-check-gcp-disk-encryption-ref.yaml
  ci-operator/step-registry/gcp/deprovision/bastionhost/gcp-deprovision-bastionhost-ref.yaml
  ci-operator/step-registry/gcp/deprovision/minimal-permission/gcp-deprovision-minimal-permission-ref.yaml
  ci-operator/step-registry/gcp/deprovision/public-dns-zone/ingress-records/gcp-deprovision-public-dns-zone-ingress-records-ref.yaml
  ci-operator/step-registry/gcp/deprovision/vpc/gcp-deprovision-vpc-ref.yaml
  ci-operator/step-registry/gcp/provision/bastionhost/gcp-provision-bastionhost-ref.yaml
  ci-operator/step-registry/gcp/provision/minimal-permission/gcp-provision-minimal-permission-ref.yaml
  ci-operator/step-registry/gcp/provision/public-dns-zone/ingress-records/gcp-provision-public-dns-zone-ingress-records-ref.yaml
  ci-operator/step-registry/gcp/provision/vpc/gcp-provision-vpc-ref.yaml
  ci-operator/step-registry/ipi/conf/gcp/oidc-creds-additional/ipi-conf-gcp-oidc-creds-additional-ref.yaml
  ci-operator/step-registry/workers-rhel/gcp-provision/workers-rhel-gcp-provision-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#39028 Bump go version tag for osde2e test harness pre submit job
  ci-operator/config/openshift/osde2e-example-test-harness/openshift-osde2e-example-test-harness-main.yaml
Labels: lgtm, approved, rehearsals-ack

#38797 add apiserver cronjob for longduration cases
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#39033 [CIGolang]exclude api server from default longduration
  ci-operator/step-registry/openshift-extended/test/longduration/openshift-extended-test-longduration-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#39035 add aws-prow
  core-services/ci-chat-bot/workflows-config.yaml
Labels: lgtm, approved, rehearsals-ack

#38676 ROX-16625: Enable OCP 4.13 for ACS 3.73
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-3.73__ocp-4-13.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-3.73-postsubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-3.73-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#39027 OCPQE-15057: Fix test filter on agent installer SNO clusters
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#39014 Add token ocpci-lp-interop to gangway
  clusters/app.ci/ocpci-lp-interop/admin_rbac.yaml
  clusters/app.ci/prow/03_deployment/gangway.yaml
Labels: lgtm, approved, rehearsals-ack

#39045 remove all droslean fork repositories
  ci-operator/config/droslean/ci-tools/OWNERS
  ci-operator/config/droslean/ci-tools/droslean-ci-tools-master.yaml
  ci-operator/jobs/droslean/ci-tools/droslean-ci-tools-master-postsubmits.yaml
  ci-operator/jobs/droslean/ci-tools/droslean-ci-tools-master-presubmits.yaml
  core-services/prow/02_config/droslean/ci-tools/OWNERS
  core-services/prow/02_config/droslean/ci-tools/_pluginconfig.yaml
  core-services/prow/02_config/droslean/ci-tools/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#38916 Rename ipi-conf-techpreview to ipi-conf-techpreview-do-not-use
  ci-operator/config/openshift-priv/azure-disk-csi-driver-operator/openshift-priv-azure-disk-csi-driver-operator-release-4.9.yaml
  ci-operator/config/openshift-priv/azure-disk-csi-driver/openshift-priv-azure-disk-csi-driver-release-4.9.yaml
  ci-operator/config/openshift-priv/azure-file-csi-driver-operator/openshift-priv-azure-file-csi-driver-operator-release-4.10.yaml
  ci-operator/config/openshift-priv/azure-file-csi-driver/openshift-priv-azure-file-csi-driver-release-4.10.yaml
  ci-operator/config/openshift-priv/cluster-storage-operator/openshift-priv-cluster-storage-operator-release-4.10.yaml
  ci-operator/config/openshift-priv/cluster-storage-operator/openshift-priv-cluster-storage-operator-release-4.9.yaml
  ci-operator/config/openshift/azure-disk-csi-driver-operator/openshift-azure-disk-csi-driver-operator-release-4.9.yaml
  ci-operator/config/openshift/azure-disk-csi-driver/openshift-azure-disk-csi-driver-release-4.9.yaml
  ci-operator/config/openshift/azure-file-csi-driver-operator/openshift-azure-file-csi-driver-operator-release-4.10.yaml
  ci-operator/config/openshift/azure-file-csi-driver/openshift-azure-file-csi-driver-release-4.10.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.10.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.9.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.9.yaml
  ci-operator/step-registry/csi-driver-shared-resource/e2e/techpreview/csi-driver-shared-resource-e2e-techpreview-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/disconnected/private/techpreview/provision/cucushift-installer-rehearse-aws-ipi-disconnected-private-techpreview-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/proxy/techpreview/po/provision/cucushift-installer-rehearse-aws-ipi-proxy-techpreview-po-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/proxy/techpreview/provision/cucushift-installer-rehearse-aws-ipi-proxy-techpreview-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/disconnected/fullyprivate/techpreview/provision/cucushift-installer-rehearse-azure-ipi-disconnected-fullyprivate-techpreview-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/proxy/techpreview/provision/cucushift-installer-rehearse-azure-ipi-proxy-techpreview-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/proxy/techpreview/provision/cucushift-installer-rehearse-gcp-ipi-proxy-techpreview-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/disconnected/techpreview/provision/cucushift-installer-rehearse-vsphere-ipi-disconnected-techpreview-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/proxy/techpreview/provision/cucushift-installer-rehearse-vsphere-ipi-proxy-techpreview-provision-chain.yaml
  ci-operator/step-registry/ipi/conf/techpreview-do-not-use/OWNERS
  ci-operator/step-registry/ipi/conf/techpreview-do-not-use/ipi-conf-techpreview-do-not-use-commands.sh
  ci-operator/step-registry/ipi/conf/techpreview-do-not-use/ipi-conf-techpreview-do-not-use-ref.metadata.json
  ci-operator/step-registry/ipi/conf/techpreview-do-not-use/ipi-conf-techpreview-do-not-use-ref.yaml
  ci-operator/step-registry/ipi/conf/techpreview/ipi-conf-techpreview-ref.yaml
  ci-operator/step-registry/ipi/gcp/techpreview/ipi-gcp-techpreview-workflow.yaml
  ci-operator/step-registry/openshift/e2e/aws/builds/techpreview/openshift-e2e-aws-builds-techpreview-workflow.yaml
  ci-operator/step-registry/openshift/e2e/aws/ccm/install/openshift-e2e-aws-ccm-install-workflow.yaml
  ci-operator/step-registry/openshift/e2e/aws/ccm/ovn-hybrid-install/openshift-e2e-aws-ccm-ovn-hybrid-install-workflow.yaml
  ci-operator/step-registry/openshift/e2e/aws/sdn/techpreview/openshift-e2e-aws-sdn-techpreview-workflow.yaml
  ci-operator/step-registry/openshift/e2e/aws/sdn/techpreview/serial/openshift-e2e-aws-sdn-techpreview-serial-workflow.yaml
  ci-operator/step-registry/openshift/e2e/aws/techpreview/openshift-e2e-aws-techpreview-workflow.yaml
  ci-operator/step-registry/openshift/e2e/aws/techpreview/serial/openshift-e2e-aws-techpreview-serial-workflow.yaml
  ci-operator/step-registry/openshift/e2e/aws/techpreview/upgrade/openshift-e2e-aws-techpreview-upgrade-workflow.yaml
  ci-operator/step-registry/openshift/e2e/azure/ccm/install/openshift-e2e-azure-ccm-install-workflow.yaml
  ci-operator/step-registry/openshift/e2e/azure/sdn/techpreview/openshift-e2e-azure-sdn-techpreview-workflow.yaml
  ci-operator/step-registry/openshift/e2e/azure/sdn/techpreview/serial/openshift-e2e-azure-sdn-techpreview-serial-workflow.yaml
  ci-operator/step-registry/openshift/e2e/azure/techpreview/openshift-e2e-azure-techpreview-workflow.yaml
  ci-operator/step-registry/openshift/e2e/azure/techpreview/serial/openshift-e2e-azure-techpreview-serial-workflow.yaml
  ci-operator/step-registry/openshift/e2e/azure/techpreview/upgrade/openshift-e2e-azure-techpreview-upgrade-workflow.yaml
  ci-operator/step-registry/openshift/e2e/gcp/ccm/install/openshift-e2e-gcp-ccm-install-workflow.yaml
  ci-operator/step-registry/openshift/e2e/gcp/sdn/techpreview/openshift-e2e-gcp-sdn-techpreview-workflow.yaml
  ci-operator/step-registry/openshift/e2e/gcp/sdn/techpreview/serial/openshift-e2e-gcp-sdn-techpreview-serial-workflow.yaml
  ci-operator/step-registry/openshift/e2e/gcp/techpreview/openshift-e2e-gcp-techpreview-workflow.yaml
  ci-operator/step-registry/openshift/e2e/gcp/techpreview/serial/openshift-e2e-gcp-techpreview-serial-workflow.yaml
  ci-operator/step-registry/openshift/e2e/gcp/techpreview/upgrade/openshift-e2e-gcp-techpreview-upgrade-workflow.yaml
  ci-operator/step-registry/openshift/e2e/openstack/techpreview/openshift-e2e-openstack-techpreview-workflow.yaml
  ci-operator/step-registry/openshift/e2e/vsphere/ccm/install/openshift-e2e-vsphere-ccm-install-workflow.yaml
  ci-operator/step-registry/openshift/e2e/vsphere/ccm/ovn-hybrid-install/openshift-e2e-vsphere-ccm-ovn-hybrid-install-workflow.yaml
  ci-operator/step-registry/openshift/e2e/vsphere/techpreview/openshift-e2e-vsphere-techpreview-workflow.yaml
  ci-operator/step-registry/openshift/e2e/vsphere/techpreview/serial/openshift-e2e-vsphere-techpreview-serial-workflow.yaml
  ci-operator/step-registry/openshift/e2e/vsphere/techpreview/upgrade/openshift-e2e-vsphere-techpreview-upgrade-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#39049 ADD byoc environment to point to ocp ephemeral cluster
  ci-operator/step-registry/redhat-appstudio/e2e/redhat-appstudio-e2e-commands.sh
Labels: lgtm, approved, rehearsals-ack

#39055 Fix: ADD byoc environment to point to ocp ephemeral cluster
  ci-operator/step-registry/redhat-appstudio/e2e/redhat-appstudio-e2e-commands.sh
Labels: do-not-merge/hold, lgtm, approved, rehearsals-ack

#39023 add operator group to install-operators json.
  ci-operator/config/stolostron/policy-collection/stolostron-policy-collection-main__opp-ocp4.12-interop.yaml
Labels: lgtm, approved, rehearsals-ack

#39057 Bump go version to 1.19 for osde2e
  ci-operator/config/openshift/osde2e/openshift-osde2e-main.yaml
Labels: lgtm, approved, rehearsals-ack

#39059 KMM: also run codecov in a postsubmit job
  ci-operator/config/rh-ecosystem-edge/kernel-module-management/rh-ecosystem-edge-kernel-module-management-main.yaml
  ci-operator/jobs/rh-ecosystem-edge/kernel-module-management/rh-ecosystem-edge-kernel-module-management-main-postsubmits.yaml
  ci-operator/jobs/rh-ecosystem-edge/kernel-module-management/rh-ecosystem-edge-kernel-module-management-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#39060 Revert "dpcr loki"
  ci-operator/step-registry/ipi/install/hosted-loki/ipi-install-hosted-loki-commands.sh
  ci-operator/step-registry/ipi/install/hosted-loki/ipi-install-hosted-loki-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#39019 WINC-1037: Specify Windows Server 2019 jobs
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-master.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.11.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.12.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.13.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.11.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.12.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.13.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-master.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.11.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.12.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.13.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#38936 feat: added log gathering for ec2 and post steps
  ci-operator/config/openshift/microshift/openshift-microshift-main.yaml
  ci-operator/config/openshift/microshift/openshift-microshift-release-4.14.yaml
  ci-operator/config/openshift/microshift/openshift-microshift-release-4.15.yaml
  ci-operator/step-registry/openshift/microshift/e2e/openshift-conformance-reduced-aws/openshift-microshift-e2e-openshift-conformance-reduced-aws-commands.sh
  ci-operator/step-registry/openshift/microshift/infra/aws/ec2/logs/OWNERS
  ci-operator/step-registry/openshift/microshift/infra/aws/ec2/logs/openshift-microshift-infra-aws-ec2-logs-commands.sh
  ci-operator/step-registry/openshift/microshift/infra/aws/ec2/logs/openshift-microshift-infra-aws-ec2-logs-ref.metadata.json
  ci-operator/step-registry/openshift/microshift/infra/aws/ec2/logs/openshift-microshift-infra-aws-ec2-logs-ref.yaml
  ci-operator/step-registry/openshift/microshift/infra/aws/ec2/openshift-microshift-infra-aws-ec2-chain.metadata.json
  ci-operator/step-registry/openshift/microshift/infra/aws/ec2/openshift-microshift-infra-aws-ec2-chain.yaml
  ci-operator/step-registry/openshift/microshift/infra/aws/ec2/openshift-microshift-infra-aws-ec2-commands.sh
  ci-operator/step-registry/openshift/microshift/infra/aws/post/openshift-microshift-infra-aws-post-chain.yaml
  ci-operator/step-registry/openshift/microshift/infra/aws/pre/openshift-microshift-infra-aws-pre-chain.yaml
  ci-operator/step-registry/openshift/microshift/infra/sos-aws/OWNERS
  ci-operator/step-registry/openshift/microshift/infra/sos-aws/openshift-microshift-infra-sos-aws-commands.sh
  ci-operator/step-registry/openshift/microshift/infra/sos-aws/openshift-microshift-infra-sos-aws-ref.metadata.json
  ci-operator/step-registry/openshift/microshift/infra/sos-aws/openshift-microshift-infra-sos-aws-ref.yaml
  ci-operator/step-registry/openshift/microshift/infra/wait-for-cluster-up-aws/openshift-microshift-infra-wait-for-cluster-up-aws-commands.sh
Labels: lgtm, approved, rehearsals-ack

#36749 Add tempest job for neutron operator
  ci-operator/config/openstack-k8s-operators/neutron-operator/openstack-k8s-operators-neutron-operator-master.yaml
  ci-operator/jobs/openstack-k8s-operators/neutron-operator/openstack-k8s-operators-neutron-operator-master-presubmits.yaml
  ci-operator/step-registry/openstack-k8s-operators/tempest/openstack-k8s-operators-tempest-commands.sh
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#39048 [OSPk8s] update infra-operator config
  ci-operator/config/openstack-k8s-operators/infra-operator/openstack-k8s-operators-infra-operator-master.yaml
  ci-operator/jobs/openstack-k8s-operators/infra-operator/openstack-k8s-operators-infra-operator-master-presubmits.yaml
  ci-operator/step-registry/openstack-k8s-operators/build/openstack-k8s-operators-build-commands.sh
Labels: lgtm, approved, rehearsals-ack

#39065 Debug tools fix for Loki and addition of Intervals via Sippy
  ci-operator/step-registry/gather/extra/gather-extra-commands.sh
  ci-operator/step-registry/ipi/install/hosted-loki/ipi-install-hosted-loki-commands.sh
Labels: lgtm, approved, rehearsals-ack

#39070 Add gangway api capability to our slack-poc jobs
  ci-operator/config/rhpit/interop-tests/rhpit-interop-tests-main__slack-poc.yaml
  ci-operator/jobs/rhpit/interop-tests/rhpit-interop-tests-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#38471 Converge capk e2e test with hypershift step registeries
  ci-operator/config/openshift/cluster-api-provider-kubevirt/openshift-cluster-api-provider-kubevirt-main.yaml
  ci-operator/jobs/openshift/cluster-api-provider-kubevirt/openshift-cluster-api-provider-kubevirt-main-presubmits.yaml
  ci-operator/step-registry/hypershift/kubevirt/custom-capk/OWNERS
  ci-operator/step-registry/hypershift/kubevirt/custom-capk/hypershift-kubevirt-custom-capk-chain.metadata.json
  ci-operator/step-registry/hypershift/kubevirt/custom-capk/hypershift-kubevirt-custom-capk-chain.yaml
  ci-operator/step-registry/hypershift/kubevirt/e2e/capk/OWNERS
  ci-operator/step-registry/hypershift/kubevirt/e2e/capk/hypershift-kubevirt-e2e-capk-workflow.metadata.json
  ci-operator/step-registry/hypershift/kubevirt/e2e/capk/hypershift-kubevirt-e2e-capk-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#39072 Update ocp-qe-perfscale-ci OWNERS
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/OWNERS
Labels: lgtm, approved, rehearsals-ack

#38998 Run cluster-density test on rosa cluster
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa-4.13-nightly.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-periodics.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-postsubmits.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#39078 [release-controller] Adding RBAC for releasepayloads
  clusters/app.ci/release-controller/admin_deploy-ocp-arm64-controller.yaml
  clusters/app.ci/release-controller/admin_deploy-ocp-arm64-priv-controller.yaml
  clusters/app.ci/release-controller/admin_deploy-ocp-controller.yaml
  clusters/app.ci/release-controller/admin_deploy-ocp-multi-controller.yaml
  clusters/app.ci/release-controller/admin_deploy-ocp-multi-priv-controller.yaml
  clusters/app.ci/release-controller/admin_deploy-ocp-ppc64le-controller.yaml
  clusters/app.ci/release-controller/admin_deploy-ocp-ppc64le-priv-controller.yaml
  clusters/app.ci/release-controller/admin_deploy-ocp-priv-controller.yaml
  clusters/app.ci/release-controller/admin_deploy-ocp-s390x-controller.yaml
  clusters/app.ci/release-controller/admin_deploy-ocp-s390x-priv-controller.yaml
  clusters/app.ci/release-controller/serviceaccount.yaml
  hack/generators/release-controllers/content/art_namespaces_rbac.py
  hack/generators/release-controllers/content/osd_rc_rbac.py
Labels: lgtm, approved, rehearsals-ack

#39080 [release-controller] Fixing pod service account name
  clusters/app.ci/release-controller/admin_deploy-ocp-arm64-controller.yaml
  clusters/app.ci/release-controller/admin_deploy-ocp-arm64-priv-controller.yaml
  clusters/app.ci/release-controller/admin_deploy-ocp-controller.yaml
  clusters/app.ci/release-controller/admin_deploy-ocp-multi-controller.yaml
  clusters/app.ci/release-controller/admin_deploy-ocp-multi-priv-controller.yaml
  clusters/app.ci/release-controller/admin_deploy-ocp-ppc64le-controller.yaml
  clusters/app.ci/release-controller/admin_deploy-ocp-ppc64le-priv-controller.yaml
  clusters/app.ci/release-controller/admin_deploy-ocp-priv-controller.yaml
  clusters/app.ci/release-controller/admin_deploy-ocp-s390x-controller.yaml
  clusters/app.ci/release-controller/admin_deploy-ocp-s390x-priv-controller.yaml
  clusters/app.ci/release-controller/serviceaccount.yaml
  hack/generators/release-controllers/content/art_namespaces_rbac.py
  hack/generators/release-controllers/content/osd_rc_rbac.py
Labels: lgtm, approved, rehearsals-ack

#39079 ci-operator/cri-o: skip CI tests for OWNERS_ALIASES
  ci-operator/jobs/cri-o/cri-o/cri-o-cri-o-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#39002 update QE workflow relevant with FEATURE_SET
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.13.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/proxy/techpreview/po/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/proxy/techpreview/po/cucushift-installer-rehearse-aws-ipi-proxy-techpreview-po-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/proxy/techpreview/po/cucushift-installer-rehearse-aws-ipi-proxy-techpreview-po-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/proxy/techpreview/po/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/proxy/techpreview/po/provision/cucushift-installer-rehearse-aws-ipi-proxy-techpreview-po-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/proxy/techpreview/po/provision/cucushift-installer-rehearse-aws-ipi-proxy-techpreview-po-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/usertags/cucushift-installer-rehearse-azure-ipi-usertags-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/usertags/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/usertags/provision/cucushift-installer-rehearse-azure-ipi-usertags-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/usertags/provision/cucushift-installer-rehearse-azure-ipi-usertags-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/usertags/techpreview/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/usertags/techpreview/cucushift-installer-rehearse-azure-ipi-usertags-techpreview-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/usertags/techpreview/cucushift-installer-rehearse-azure-ipi-usertags-techpreview-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/usertags/techpreview/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/usertags/techpreview/provision/cucushift-installer-rehearse-azure-ipi-usertags-techpreview-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/usertags/techpreview/provision/cucushift-installer-rehearse-azure-ipi-usertags-techpreview-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/xpn/techpreview/provision/cucushift-installer-rehearse-gcp-ipi-xpn-techpreview-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/zones/provision/cucushift-installer-rehearse-vsphere-ipi-zones-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/zones/techpreview/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/zones/techpreview/cucushift-installer-rehearse-vsphere-ipi-zones-techpreview-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/zones/techpreview/cucushift-installer-rehearse-vsphere-ipi-zones-techpreview-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/zones/techpreview/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/zones/techpreview/provision/cucushift-installer-rehearse-vsphere-ipi-zones-techpreview-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/zones/techpreview/provision/cucushift-installer-rehearse-vsphere-ipi-zones-techpreview-provision-chain.yaml
  ci-operator/step-registry/ipi/conf/feature-set/OWNERS
  ci-operator/step-registry/ipi/conf/feature-set/ipi-conf-feature-set-commands.sh
  ci-operator/step-registry/ipi/conf/feature-set/ipi-conf-feature-set-ref.metadata.json
  ci-operator/step-registry/ipi/conf/feature-set/ipi-conf-feature-set-ref.yaml
  ci-operator/step-registry/openshift/e2e/aws/cpu-partitioning/openshift-e2e-aws-cpu-partitioning-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#39046 add api call for 4.12 upgrade jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-aro.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-eus-4.10.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-stable-4.11.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-stable-4.12-upgrade-from-eus-4.10.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-stable-4.12-upgrade-from-stable-4.11.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-stable-4.12-upgrade-from-stable-4.6.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-stable-4.12-upgrade-from-stable-4.7.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__arm64-nightly-4.12-upgrade-from-eus-4.10.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__arm64-nightly-4.12-upgrade-from-stable-4.11.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__arm64-nightly-4.12-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__arm64-stable-4.12-upgrade-from-stable-4.11.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#37853 OCPQE-15091: Fix 4.1 channel
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-4.13-upgrade-from-stable-4.1.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#39087 update 4.12 stable jobs to support API call
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__arm64-stable.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#37095 Add osd fm e2e pipeline
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-stable.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
  ci-operator/step-registry/osd-ccs/fleet-manager/osd-ccs-fleet-manager-workflow.yaml
  ci-operator/step-registry/osd-ccs/fleet-manager/sc/deprovision/osd-ccs-fleet-manager-sc-deprovision-commands.sh
  ci-operator/step-registry/osd-ccs/fleet-manager/sc/deprovision/osd-ccs-fleet-manager-sc-deprovision-ref.yaml
  ci-operator/step-registry/osd-ccs/fleet-manager/sc/provision/osd-ccs-fleet-manager-sc-provision-commands.sh
  ci-operator/step-registry/osd-ccs/fleet-manager/sc/provision/osd-ccs-fleet-manager-sc-provision-ref.yaml
  ci-operator/step-registry/rosa/conf/idp/htpasswd/rosa-conf-idp-htpasswd-ref.yaml
  ci-operator/step-registry/rosa/sts/cluster/deprovision/rosa-sts-cluster-deprovision-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#39089 Always set ret to 0 before function check_mcp
  ci-operator/step-registry/cucushift/installer/check/cluster-health/cucushift-installer-check-cluster-health-commands.sh
Labels: lgtm, approved, rehearsals-ack

#39026 upgrade global hub image builder from go1.18 to go1.19
  ci-operator/config/stolostron/multicluster-global-hub/stolostron-multicluster-global-hub-main.yaml
  ci-operator/config/stolostron/multicluster-global-hub/stolostron-multicluster-global-hub-release-2.8.yaml
  ci-operator/config/stolostron/multicluster-global-hub/stolostron-multicluster-global-hub-release-2.9.yaml
Labels: lgtm, approved, rehearsals-ack

#38481 Add: aws-efs-csi-driver-operator extended presubmit test jobs
  ci-operator/config/openshift/aws-efs-csi-driver-operator/openshift-aws-efs-csi-driver-operator-master.yaml
  ci-operator/config/openshift/aws-efs-csi-driver-operator/openshift-aws-efs-csi-driver-operator-release-4.14.yaml
  ci-operator/jobs/openshift/aws-efs-csi-driver-operator/openshift-aws-efs-csi-driver-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/aws-efs-csi-driver-operator/openshift-aws-efs-csi-driver-operator-release-4.14-presubmits.yaml
  ci-operator/step-registry/openshift/e2e/aws/csi/efs/extended/OWNERS
  ci-operator/step-registry/openshift/e2e/aws/csi/efs/extended/openshift-e2e-aws-csi-efs-extended-workflow.metadata.json
  ci-operator/step-registry/openshift/e2e/aws/csi/efs/extended/openshift-e2e-aws-csi-efs-extended-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#38915 Assisted-Installer: Remove conformance test from vsphere periodic workflow
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/step-registry/assisted/vsphere/assisted-vsphere-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#39092 Assisted-Installer: Remove conformance test from vsphere periodic 4.12
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
Labels: lgtm, approved, rehearsals-ack

#39064 Re-introduce DPCR Loki logging for GCP and Azure clusters
  ci-operator/step-registry/ipi/install/hosted-loki/ipi-install-hosted-loki-commands.sh
  ci-operator/step-registry/ipi/install/hosted-loki/ipi-install-hosted-loki-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#38887 telco5g: Run SNO job for telco5g CI
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.12.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.13.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.14.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  ci-operator/step-registry/telco5g/cnf/tests/telco5g-cnf-tests-commands.sh
  ci-operator/step-registry/telco5g/jobs-router/telco5g-jobs-router-commands.sh
  ci-operator/step-registry/telco5g/sno-cnf/OWNERS
  ci-operator/step-registry/telco5g/sno-cnf/telco5g-sno-cnf-workflow.metadata.json
  ci-operator/step-registry/telco5g/sno-cnf/telco5g-sno-cnf-workflow.yaml
  ci-operator/step-registry/telco5g/sno-setup/OWNERS
  ci-operator/step-registry/telco5g/sno-setup/telco5g-sno-setup-commands.sh
  ci-operator/step-registry/telco5g/sno-setup/telco5g-sno-setup-ref.metadata.json
  ci-operator/step-registry/telco5g/sno-setup/telco5g-sno-setup-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#39062 install-analysis-all: refactor to common entry point and log to files
  ci-operator/step-registry/openshift/release/analysis/test-case-analysis/openshift-release-analysis-test-case-analysis-commands.sh
Labels: lgtm, approved, rehearsals-ack

#39102 add opct-test-platform-none-vsphere to chatbot
  core-services/ci-chat-bot/workflows-config.yaml
Labels: lgtm, approved, rehearsals-ack

#38932 SDCICD-987: Switch OSD AWS/GCP OCP informing jobs to 24h interval
  ci-operator/jobs/openshift/release/openshift-release-release-4.10-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.11-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.12-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.14-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#39016 SPLAT-1048: enable vSphere daily upgrade jobs
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.13-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.14-upgrade-from-stable-4.13.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  ci-operator/step-registry/ipi/install/install/stableinitial/ipi-install-install-stableinitial-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#39113 Update Modelmesh-serving to use the source in a PR
  ci-operator/config/opendatahub-io/modelmesh-serving/opendatahub-io-modelmesh-serving-main.yaml
  ci-operator/config/opendatahub-io/modelmesh-serving/opendatahub-io-modelmesh-serving-release-v0.11.0-alpha.yaml
Labels: lgtm, approved, rehearsals-ack

#39058 Fix job/periodic-pr-reminder
  ci-operator/jobs/infra-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#39021 WINC-1036: wmco: Delete Azure jobs in 4.10
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.10.yaml
  ci-operator/jobs/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.10-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#38428 hypershift: kubevirt-baremetalds
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.13__periodics.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.13-periodics.yaml
  ci-operator/step-registry/hypershift/conformance/hypershift-conformance-chain.yaml
  ci-operator/step-registry/hypershift/dump/hypershift-dump-chain.yaml
  ci-operator/step-registry/hypershift/kubevirt/baremetalds/OWNERS
  ci-operator/step-registry/hypershift/kubevirt/baremetalds/conformance/OWNERS
  ci-operator/step-registry/hypershift/kubevirt/baremetalds/conformance/hypershift-kubevirt-baremetalds-conformance-workflow.metadata.json
  ci-operator/step-registry/hypershift/kubevirt/baremetalds/conformance/hypershift-kubevirt-baremetalds-conformance-workflow.yaml
  ci-operator/step-registry/hypershift/kubevirt/baremetalds/metallb/OWNERS
  ci-operator/step-registry/hypershift/kubevirt/baremetalds/metallb/hypershift-kubevirt-baremetalds-metallb-chain.metadata.json
  ci-operator/step-registry/hypershift/kubevirt/baremetalds/metallb/hypershift-kubevirt-baremetalds-metallb-chain.yaml
  ci-operator/step-registry/hypershift/kubevirt/baremetalds/metallb/hypershift-kubevirt-baremetalds-metallb-commands.sh
  ci-operator/step-registry/hypershift/kubevirt/baremetalds/metallb/hypershift-kubevirt-baremetalds-metallb-ref.metadata.json
  ci-operator/step-registry/hypershift/kubevirt/baremetalds/metallb/hypershift-kubevirt-baremetalds-metallb-ref.yaml
  ci-operator/step-registry/hypershift/kubevirt/baremetalds/odf/OWNERS
  ci-operator/step-registry/hypershift/kubevirt/baremetalds/odf/hypershift-kubevirt-baremetalds-odf-chain.metadata.json
  ci-operator/step-registry/hypershift/kubevirt/baremetalds/odf/hypershift-kubevirt-baremetalds-odf-chain.yaml
  ci-operator/step-registry/hypershift/kubevirt/baremetalds/odf/hypershift-kubevirt-baremetalds-odf-commands.sh
  ci-operator/step-registry/hypershift/kubevirt/baremetalds/odf/hypershift-kubevirt-baremetalds-odf-ref.metadata.json
  ci-operator/step-registry/hypershift/kubevirt/baremetalds/odf/hypershift-kubevirt-baremetalds-odf-ref.yaml
  ci-operator/step-registry/hypershift/kubevirt/baremetalds/proxy/OWNERS
  ci-operator/step-registry/hypershift/kubevirt/baremetalds/proxy/health-check/OWNERS
  ci-operator/step-registry/hypershift/kubevirt/baremetalds/proxy/health-check/hypershift-kubevirt-baremetalds-proxy-health-check-commands.sh
  ci-operator/step-registry/hypershift/kubevirt/baremetalds/proxy/health-check/hypershift-kubevirt-baremetalds-proxy-health-check-ref.metadata.json
  ci-operator/step-registry/hypershift/kubevirt/baremetalds/proxy/health-check/hypershift-kubevirt-baremetalds-proxy-health-check-ref.yaml
  ci-operator/step-registry/hypershift/kubevirt/baremetalds/proxy/hypershift-kubevirt-baremetalds-proxy-chain.metadata.json
  ci-operator/step-registry/hypershift/kubevirt/baremetalds/proxy/hypershift-kubevirt-baremetalds-proxy-chain.yaml
  ci-operator/step-registry/hypershift/kubevirt/baremetalds/proxy/hypershift-kubevirt-baremetalds-proxy-commands.sh
  ci-operator/step-registry/hypershift/kubevirt/baremetalds/proxy/hypershift-kubevirt-baremetalds-proxy-ref.metadata.json
  ci-operator/step-registry/hypershift/kubevirt/baremetalds/proxy/hypershift-kubevirt-baremetalds-proxy-ref.yaml
  ci-operator/step-registry/hypershift/kubevirt/create/hypershift-kubevirt-create-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#38982 add odh-model-controller
  ci-operator/config/opendatahub-io/odh-model-controller/OWNERS
  ci-operator/config/opendatahub-io/odh-model-controller/opendatahub-io-odh-model-controller-main.yaml
  ci-operator/config/opendatahub-io/odh-model-controller/opendatahub-io-odh-model-controller-release-v0.11.0-alpha.yaml
  ci-operator/jobs/opendatahub-io/odh-model-controller/OWNERS
  ci-operator/jobs/opendatahub-io/odh-model-controller/opendatahub-io-odh-model-controller-main-postsubmits.yaml
  ci-operator/jobs/opendatahub-io/odh-model-controller/opendatahub-io-odh-model-controller-main-presubmits.yaml
  ci-operator/jobs/opendatahub-io/odh-model-controller/opendatahub-io-odh-model-controller-release-v0.11.0-alpha-postsubmits.yaml
  ci-operator/jobs/opendatahub-io/odh-model-controller/opendatahub-io-odh-model-controller-release-v0.11.0-alpha-presubmits.yaml
  core-services/prow/02_config/opendatahub-io/odh-model-controller/OWNERS
  core-services/prow/02_config/opendatahub-io/odh-model-controller/_pluginconfig.yaml
  core-services/prow/02_config/opendatahub-io/odh-model-controller/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#39121 govulncheck: bump golang version to 1.20.4
  clusters/app.ci/supplemental-ci-images/crt/govulncheck.yaml
Labels: lgtm, approved, rehearsals-ack

#39109 ovn-kubernetes: remove old rhel8-based Dockerfile builds
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.13.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.13__4.13-upgrade-from-stable-4.12-local-gateway.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.13__4.13-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.13__okd.yaml
  core-services/image-mirroring/openshift/mapping_origin_4_13
Labels: lgtm, approved, rehearsals-ack

#39104 vSphere: remove network option from govc clone, additional debug output
  ci-operator/step-registry/upi/conf/vsphere/ova/upi-conf-vsphere-ova-commands.sh
Labels: lgtm, approved, rehearsals-ack

#39124 release-controller,jira-lifecycle-plugin: use stream9
  ci-operator/config/openshift-eng/jira-lifecycle-plugin/openshift-eng-jira-lifecycle-plugin-main.yaml
  ci-operator/config/openshift/release-controller/openshift-release-controller-master.yaml
Labels: lgtm, approved, rehearsals-ack

#39128 Update repo on must-gather config
  ci-operator/config/opendatahub-io/odh-manifests/opendatahub-io-odh-manifests-master.yaml
  ci-operator/config/opendatahub-io/odh-manifests/opendatahub-io-odh-manifests-master__410.yaml
  ci-operator/config/opendatahub-io/odh-manifests/opendatahub-io-odh-manifests-master__411.yaml
  ci-operator/config/red-hat-data-services/must-gather/red-hat-data-services-must-gather-main.yaml
Labels: lgtm, approved, rehearsals-ack

#39117 On-board openshift-eng/ci-test-mapping
  ci-operator/config/openshift-eng/ci-test-mapping/OWNERS
  ci-operator/config/openshift-eng/ci-test-mapping/openshift-eng-ci-test-mapping-main.yaml
  ci-operator/jobs/openshift-eng/ci-test-mapping/OWNERS
  ci-operator/jobs/openshift-eng/ci-test-mapping/openshift-eng-ci-test-mapping-main-presubmits.yaml
  core-services/prow/02_config/openshift-eng/ci-test-mapping/_pluginconfig.yaml
  core-services/prow/02_config/openshift-eng/ci-test-mapping/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#39132 Use 4.14 upi-installer to fix python2 not compatible with gcloud issue
  ci-operator/step-registry/ipi/conf/gcp/xpn/ipi-conf-gcp-xpn-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#39138 [CIGolang]check kubeamdin passwd
  ci-operator/step-registry/openshift-extended/test/openshift-extended-test-commands.sh
Labels: lgtm, approved, rehearsals-ack

#39139 Skip meta-operator go.mod changes if operator not integrated.
  ci-operator/step-registry/openstack-k8s-operators/build/openstack-k8s-operators-build-commands.sh
Labels: lgtm, approved, rehearsals-ack

#39140 update test Frequency
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#38796 add workflow rosa-aws-sts-hypershift-sector and debug prod green sector
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-stable.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
  ci-operator/step-registry/rosa/aws/sts/hypershift-sector/OWNERS
  ci-operator/step-registry/rosa/aws/sts/hypershift-sector/rosa-aws-sts-hypershift-sector-workflow.metadata.json
  ci-operator/step-registry/rosa/aws/sts/hypershift-sector/rosa-aws-sts-hypershift-sector-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#38928 MGMT-14494: Increase worker node storage for e2e-metal-assisted-kube-…
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.8.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#39144 Update(image-mirroring): Use interop tag for test-image of Service Re…
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_ci
Labels: lgtm, approved, rehearsals-ack

#39136 migrate jobs to vsphere because of vsphere-ibm-7 dismiss
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.13.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#39147 setup image build&push for runtime image on main branch
  ci-operator/config/red-hat-data-services/notebooks/red-hat-data-services-notebooks-main.yaml
  ci-operator/jobs/red-hat-data-services/notebooks/red-hat-data-services-notebooks-main-postsubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#39006 Add 4.13 config for community operator testing
  ci-operator/config/redhat-openshift-ecosystem/community-operators-pipeline/redhat-openshift-ecosystem-community-operators-pipeline-main__4.13.yaml
  ci-operator/config/redhat-openshift-ecosystem/community-operators-prod/redhat-openshift-ecosystem-community-operators-prod-main__4.13.yaml
  ci-operator/jobs/redhat-openshift-ecosystem/community-operators-pipeline/redhat-openshift-ecosystem-community-operators-pipeline-main-presubmits.yaml
  ci-operator/jobs/redhat-openshift-ecosystem/community-operators-prod/redhat-openshift-ecosystem-community-operators-prod-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#39145 setup image build&push for runtime image on release branch 2023a
  ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-2023a.yaml
  ci-operator/jobs/opendatahub-io/notebooks/opendatahub-io-notebooks-2023a-postsubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#39146 setup image build&push for runtime image on rhods release branch 2023a
  ci-operator/config/red-hat-data-services/notebooks/red-hat-data-services-notebooks-release-2023a.yaml
  ci-operator/jobs/red-hat-data-services/notebooks/red-hat-data-services-notebooks-release-2023a-postsubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#39118 KMM: add config for release-1.1
  ci-operator/config/rh-ecosystem-edge/kernel-module-management/rh-ecosystem-edge-kernel-module-management-release-1.1.yaml
  ci-operator/jobs/rh-ecosystem-edge/kernel-module-management/rh-ecosystem-edge-kernel-module-management-release-1.1-postsubmits.yaml
  ci-operator/jobs/rh-ecosystem-edge/kernel-module-management/rh-ecosystem-edge-kernel-module-management-release-1.1-presubmits.yaml
  core-services/image-mirroring/edge-infrastructure/mapping_edge_infrastructure_kernel_module_management
Labels: lgtm, approved, rehearsals-ack

#39120 additional quota in vsphere 8
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: lgtm, approved, rehearsals-ack
