Repository openshift/release, pull requests merged in 2023-09, with the labels that each got.

#42874 Upgrade go to 1.20.
  ci-operator/config/stolostron/multicloud-operators-foundation/stolostron-multicloud-operators-foundation-backplane-2.4.yaml
  ci-operator/config/stolostron/multicloud-operators-foundation/stolostron-multicloud-operators-foundation-main.yaml
Labels: lgtm, approved, rehearsals-ack

#42906 Bump TEST_TIMEOUT of GCP long duration jobs to 100 minutes
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-nightly.yaml
Labels: lgtm, approved, rehearsals-ack

#42625 utilize oc adm release extract --included options
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-ec.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly-4.14-upgrade-from-ec-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly-4.14-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-ec.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly-4.14-upgrade-from-ec-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly-4.14-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-ec.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
  ci-operator/step-registry/aws/c2s/init-token-service/aws-c2s-init-token-service-commands.sh
  ci-operator/step-registry/aws/c2s/init-token-service/aws-c2s-init-token-service-ref.yaml
  ci-operator/step-registry/aws/provision/cco-manual-users/static/aws-provision-cco-manual-users-static-commands.sh
  ci-operator/step-registry/aws/provision/cco-manual-users/static/aws-provision-cco-manual-users-static-ref.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/c2s/ipi/disconnected/private/provision/cucushift-installer-rehearse-aws-c2s-ipi-disconnected-private-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/disconnected/private/network-mtu/localzone/provision/cucushift-installer-rehearse-aws-ipi-disconnected-private-network-mtu-localzone-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/disconnected/private/provision/cucushift-installer-rehearse-aws-ipi-disconnected-private-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/disconnected/private/sdn/provision/cucushift-installer-rehearse-aws-ipi-disconnected-private-sdn-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/disconnected/private/sno/provision/cucushift-installer-rehearse-aws-ipi-disconnected-private-sno-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/disconnected/private/techpreview/provision/cucushift-installer-rehearse-aws-ipi-disconnected-private-techpreview-provision-chain.yaml
  ci-operator/step-registry/ipi/conf/alibabacloud/cloud-creds-provision/ipi-conf-alibabacloud-cloud-creds-provision-commands.sh
  ci-operator/step-registry/ipi/conf/alibabacloud/cloud-creds-provision/ipi-conf-alibabacloud-cloud-creds-provision-ref.yaml
  ci-operator/step-registry/ipi/conf/aws/oidc-creds-provision/ipi-conf-aws-oidc-creds-provision-commands.sh
  ci-operator/step-registry/ipi/conf/aws/oidc-creds-provision/ipi-conf-aws-oidc-creds-provision-ref.yaml
  ci-operator/step-registry/ipi/conf/azure/oidc-creds-provision/ipi-conf-azure-oidc-creds-provision-commands.sh
  ci-operator/step-registry/ipi/conf/azure/oidc-creds-provision/ipi-conf-azure-oidc-creds-provision-ref.yaml
  ci-operator/step-registry/ipi/conf/azurestack/creds/ipi-conf-azurestack-creds-commands.sh
  ci-operator/step-registry/ipi/conf/azurestack/creds/ipi-conf-azurestack-creds-ref.yaml
  ci-operator/step-registry/ipi/conf/gcp/oidc-creds-provision/ipi-conf-gcp-oidc-creds-provision-commands.sh
  ci-operator/step-registry/ipi/conf/gcp/oidc-creds-provision/ipi-conf-gcp-oidc-creds-provision-ref.yaml
  ci-operator/step-registry/ipi/conf/manual-creds/remove-unnecessary-creds/ipi-conf-manual-creds-remove-unnecessary-creds-commands.sh
  ci-operator/step-registry/ipi/conf/manual-creds/remove-unnecessary-creds/ipi-conf-manual-creds-remove-unnecessary-creds-ref.yaml
  ci-operator/step-registry/ipi/conf/nutanix/manual-creds/ipi-conf-nutanix-manual-creds-commands.sh
  ci-operator/step-registry/ipi/conf/nutanix/manual-creds/ipi-conf-nutanix-manual-creds-ref.yaml
  ci-operator/step-registry/quay-tests/aws-ipi-disconnected-private-provision/quay-tests-aws-ipi-disconnected-private-provision-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#42875 Changes to always_run: false
  ci-operator/jobs/ComplianceAsCode/content/ComplianceAsCode-content-master-presubmits.yaml
  ci-operator/jobs/openshift-priv/windows-machine-config-operator/openshift-priv-windows-machine-config-operator-master-presubmits.yaml
  ci-operator/jobs/openshift-priv/windows-machine-config-operator/openshift-priv-windows-machine-config-operator-release-4.14-presubmits.yaml
  ci-operator/jobs/openshift-priv/windows-machine-config-operator/openshift-priv-windows-machine-config-operator-release-4.15-presubmits.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-presubmits.yaml
  ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
  ci-operator/jobs/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.14-presubmits.yaml
  ci-operator/jobs/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.15-presubmits.yaml
  ci-operator/jobs/redhat-appstudio/e2e-tests/redhat-appstudio-e2e-tests-main-presubmits.yaml
  ci-operator/jobs/redhat-appstudio/infra-deployments/redhat-appstudio-infra-deployments-main-presubmits.yaml
  ci-operator/jobs/redhat-chaos/krkn-hub/redhat-chaos-krkn-hub-main-presubmits.yaml
  ci-operator/jobs/terraform-redhat/terraform-provider-rhcs/terraform-redhat-terraform-provider-rhcs-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#42905 Remove envoyproxy old image
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
Labels: lgtm, approved, rehearsals-ack

#42903 Updat quay39 tests ROSA on ocp414
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__quay-rosa-ocp.yaml
  ci-operator/jobs/quay/quay-tests/quay-quay-tests-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#42914 Run health check for EC (stable) builds
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-ec.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#42424 Automation for DVO tests bundle building approach
  ci-operator/config/app-sre/deployment-validation-operator/app-sre-deployment-validation-operator-master.yaml
  ci-operator/jobs/app-sre/deployment-validation-operator/app-sre-deployment-validation-operator-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#42913 Update marketplace profiles
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-ec.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#42910 observability-operator: use squash to merge
  core-services/prow/02_config/rhobs/observability-operator/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#42821 add/update advance rosa workflow
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-master__rosacli.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-master-periodics.yaml
  ci-operator/step-registry/osd-ccs/fleet-manager/osd-ccs-fleet-manager-workflow.yaml
  ci-operator/step-registry/rosa/aws/non-sts/advanced/OWNERS
  ci-operator/step-registry/rosa/aws/non-sts/advanced/rosa-aws-non-sts-advanced-workflow.metadata.json
  ci-operator/step-registry/rosa/aws/non-sts/advanced/rosa-aws-non-sts-advanced-workflow.yaml
  ci-operator/step-registry/rosa/aws/non-sts/rosa-aws-non-sts-workflow.yaml
  ci-operator/step-registry/rosa/aws/sts/advanced/OWNERS
  ci-operator/step-registry/rosa/aws/sts/advanced/rosa-aws-sts-advanced-workflow.metadata.json
  ci-operator/step-registry/rosa/aws/sts/advanced/rosa-aws-sts-advanced-workflow.yaml
  ci-operator/step-registry/rosa/aws/sts/deprovision/byo/oidc/OWNERS
  ci-operator/step-registry/rosa/aws/sts/deprovision/byo/oidc/rosa-aws-sts-deprovision-byo-oidc-chain.metadata.json
  ci-operator/step-registry/rosa/aws/sts/deprovision/byo/oidc/rosa-aws-sts-deprovision-byo-oidc-chain.yaml
  ci-operator/step-registry/rosa/aws/sts/hypershift/advanced/OWNERS
  ci-operator/step-registry/rosa/aws/sts/hypershift/advanced/rosa-aws-sts-hypershift-advanced-workflow.metadata.json
  ci-operator/step-registry/rosa/aws/sts/hypershift/advanced/rosa-aws-sts-hypershift-advanced-workflow.yaml
  ci-operator/step-registry/rosa/aws/sts/hypershift/deprovision/OWNERS
  ci-operator/step-registry/rosa/aws/sts/hypershift/deprovision/rosa-aws-sts-hypershift-deprovision-chain.metadata.json
  ci-operator/step-registry/rosa/aws/sts/hypershift/deprovision/rosa-aws-sts-hypershift-deprovision-chain.yaml
  ci-operator/step-registry/rosa/aws/sts/hypershift/mp/rosa-aws-sts-hypershift-mp-workflow.yaml
  ci-operator/step-registry/rosa/aws/sts/hypershift/provision/OWNERS
  ci-operator/step-registry/rosa/aws/sts/hypershift/provision/rosa-aws-sts-hypershift-provision-chain.metadata.json
  ci-operator/step-registry/rosa/aws/sts/hypershift/provision/rosa-aws-sts-hypershift-provision-chain.yaml
  ci-operator/step-registry/rosa/aws/sts/hypershift/rosa-aws-sts-hypershift-workflow.yaml
  ci-operator/step-registry/rosa/aws/sts/hypershift/sector/rosa-aws-sts-hypershift-sector-workflow.yaml
  ci-operator/step-registry/rosa/aws/sts/provision/byo/oidc/OWNERS
  ci-operator/step-registry/rosa/aws/sts/provision/byo/oidc/rosa-aws-sts-provision-byo-oidc-chain.metadata.json
  ci-operator/step-registry/rosa/aws/sts/provision/byo/oidc/rosa-aws-sts-provision-byo-oidc-chain.yaml
  ci-operator/step-registry/rosa/cluster/deprovision/rosa-cluster-deprovision-commands.sh
  ci-operator/step-registry/rosa/cluster/provision/rosa-cluster-provision-commands.sh
  ci-operator/step-registry/rosa/cluster/provision/rosa-cluster-provision-ref.yaml
  ci-operator/step-registry/rosa/sts/oidc-config/create/rosa-sts-oidc-config-create-commands.sh
  ci-operator/step-registry/rosa/sts/oidc-config/delete/rosa-sts-oidc-config-delete-commands.sh
  ci-operator/step-registry/rosa/sts/operator-roles/create/rosa-sts-operator-roles-create-commands.sh
Labels: lgtm, approved, rehearsals-ack

#42803 Adding cspi team alias into OWNERS files
  ci-operator/config/redhat-developer/odo/OWNERS
  ci-operator/jobs/redhat-developer/odo/OWNERS
Labels: lgtm, approved, rehearsals-ack

#42562 VolSync: CI-replace golang1.20 builder with ocp builder
  ci-operator/config/backube/volsync/backube-volsync-main.yaml
Labels: lgtm, approved, rehearsals-ack

#42928 setup openshift ci for kserve 1.32 release
  ci-operator/config/red-hat-data-services/kserve/red-hat-data-services-kserve-rhods-1.32.yaml
  ci-operator/jobs/red-hat-data-services/kserve/red-hat-data-services-kserve-rhods-1.32-periodics.yaml
  ci-operator/jobs/red-hat-data-services/kserve/red-hat-data-services-kserve-rhods-1.32-postsubmits.yaml
  ci-operator/jobs/red-hat-data-services/kserve/red-hat-data-services-kserve-rhods-1.32-presubmits.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#42805 Adding cspi team alias into OWNERS files
  ci-operator/config/redhat-developer/service-binding-operator/OWNERS
  ci-operator/jobs/redhat-developer/service-binding-operator/OWNERS
Labels: lgtm, approved, rehearsals-ack

#42934 Convert KServe nightlies to post-submits
  ci-operator/config/red-hat-data-services/kserve/red-hat-data-services-kserve-rhods-1.32.yaml
  ci-operator/jobs/red-hat-data-services/kserve/red-hat-data-services-kserve-rhods-1.32-periodics.yaml
  ci-operator/jobs/red-hat-data-services/kserve/red-hat-data-services-kserve-rhods-1.32-postsubmits.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#42937 re-add cspi-qe-ocp-lp as owner since autosync removed it.
  ci-operator/config/stolostron/acmqe-autotest/OWNERS
  ci-operator/jobs/stolostron/acmqe-autotest/OWNERS
Labels: lgtm, approved, rehearsals-ack

#42473 allow firewatch to fail to prevent false positive
  ci-operator/config/stolostron/acmqe-autotest/stolostron-acmqe-autotest-main__acm-ocp4.14-lp-interop.yaml
  ci-operator/step-registry/acm/ipi/aws/acm-ipi-aws-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#42931 Setup TGIS for RHODS 1.32
  ci-operator/config/red-hat-data-services/text-generation-inference/red-hat-data-services-text-generation-inference-rhods-1.32.yaml
  ci-operator/jobs/red-hat-data-services/text-generation-inference/red-hat-data-services-text-generation-inference-rhods-1.32-postsubmits.yaml
  ci-operator/jobs/red-hat-data-services/text-generation-inference/red-hat-data-services-text-generation-inference-rhods-1.32-presubmits.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#42940 update mce-install shell
  ci-operator/step-registry/hypershift/mce/install/hypershift-mce-install-commands.sh
Labels: lgtm, approved, rehearsals-ack

#42932 Setup caikit-tgis-serving for RHODS 1.32
  ci-operator/config/red-hat-data-services/caikit-tgis-serving/red-hat-data-services-caikit-tgis-serving-rhods-1.32.yaml
  ci-operator/jobs/red-hat-data-services/caikit-tgis-serving/red-hat-data-services-caikit-tgis-serving-rhods-1.32-postsubmits.yaml
  ci-operator/jobs/red-hat-data-services/caikit-tgis-serving/red-hat-data-services-caikit-tgis-serving-rhods-1.32-presubmits.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#42941 [Kubevirt UI] move to OCP 4.14
  ci-operator/config/kubevirt-ui/kubevirt-plugin/kubevirt-ui-kubevirt-plugin-main.yaml
Labels: lgtm, approved, rehearsals-ack

#42942 telco5g: Use 4.14 image for 4.15 branch for now
  ci-operator/step-registry/telco5g/cnf/tests/telco5g-cnf-tests-commands.sh
Labels: lgtm, approved, rehearsals-ack

#42920 [4.13-4.14] refine ec/stable ci jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-ec.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-ec.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-ec.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#42916 Update Quay tests to 3.9 on OSD OCP 4.14 nightly build
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__quay-osd-ocp.yaml
  ci-operator/jobs/quay/quay-tests/quay-quay-tests-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#42949 Fix tests for several destructive jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-nightly.yaml
Labels: lgtm, approved, rehearsals-ack

#42901 external ccm job
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#42124 CORS-2782: add custom machine type testing into minimal permissions testing
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.13.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.14.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
  ci-operator/step-registry/cucushift/installer/check/gcp/machine-type/OWNERS
  ci-operator/step-registry/cucushift/installer/check/gcp/machine-type/cucushift-installer-check-gcp-machine-type-commands.sh
  ci-operator/step-registry/cucushift/installer/check/gcp/machine-type/cucushift-installer-check-gcp-machine-type-ref.metadata.json
  ci-operator/step-registry/cucushift/installer/check/gcp/machine-type/cucushift-installer-check-gcp-machine-type-ref.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/minimal-permission/cucushift-installer-rehearse-gcp-ipi-minimal-permission-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/minimal-permission/provision/cucushift-installer-rehearse-gcp-ipi-minimal-permission-provision-chain.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#42948 Remove 1.7 serving family manifests
  ci-operator/config/openshift-knative/net-istio/openshift-knative-net-istio-release-1.7.yaml
  ci-operator/config/openshift-knative/net-kourier/openshift-knative-net-kourier-release-1.7.yaml
  ci-operator/config/openshift-knative/serving/openshift-knative-serving-release-v1.7__410.yaml
  ci-operator/config/openshift-knative/serving/openshift-knative-serving-release-v1.7__411.yaml
  ci-operator/config/openshift-knative/serving/openshift-knative-serving-release-v1.7__412.yaml
  ci-operator/config/openshift-knative/serving/openshift-knative-serving-release-v1.7__48.yaml
  ci-operator/config/openshift-knative/serving/openshift-knative-serving-release-v1.7__49.yaml
  ci-operator/jobs/openshift-knative/net-istio/openshift-knative-net-istio-release-1.7-postsubmits.yaml
  ci-operator/jobs/openshift-knative/net-istio/openshift-knative-net-istio-release-1.7-presubmits.yaml
  ci-operator/jobs/openshift-knative/net-kourier/openshift-knative-net-kourier-release-1.7-postsubmits.yaml
  ci-operator/jobs/openshift-knative/net-kourier/openshift-knative-net-kourier-release-1.7-presubmits.yaml
  ci-operator/jobs/openshift-knative/serving/openshift-knative-serving-release-v1.7-periodics.yaml
  ci-operator/jobs/openshift-knative/serving/openshift-knative-serving-release-v1.7-postsubmits.yaml
  ci-operator/jobs/openshift-knative/serving/openshift-knative-serving-release-v1.7-presubmits.yaml
  core-services/image-mirroring/knative/mapping_knative_v1_7_quay
Labels: lgtm, approved, rehearsals-ack

#42952 refine tp and to-multiarch ci jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-ec.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#42960 Remove priority field from test names for 4.13
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-4.13-upgrade-from-aro.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-4.13-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-4.13-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-openshift-logging-5.7.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-stable-4.13-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-nightly-4.13-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-nightly-4.13-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-nightly-openshift-logging-5.7.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-stable-4.13-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__multi-nightly-4.13-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__multi-nightly-4.13-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__multi-stable-4.13-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__ppc64le-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#42771 add check for caps Build, DeploymentConfig and ImageRegistry
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-ec.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-nightly.yaml
  ci-operator/step-registry/cucushift/installer/check/capability/cucushift-installer-check-capability-commands.sh
  ci-operator/step-registry/ipi/conf/manual-creds/remove-unnecessary-creds/ipi-conf-manual-creds-remove-unnecessary-creds-commands.sh
Labels: lgtm, approved, rehearsals-ack

#42924 Remove operator-framework/operator-lib
  ci-operator/config/operator-framework/operator-lib/OWNERS
  ci-operator/config/operator-framework/operator-lib/operator-framework-operator-lib-main.yaml
  ci-operator/jobs/infra-periodics.yaml
  ci-operator/jobs/operator-framework/operator-lib/OWNERS
  ci-operator/jobs/operator-framework/operator-lib/operator-framework-operator-lib-main-presubmits.yaml
  core-services/prow/02_config/operator-framework/operator-lib/OWNERS
  core-services/prow/02_config/operator-framework/operator-lib/_pluginconfig.yaml
  core-services/prow/02_config/operator-framework/operator-lib/_prowconfig.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#42921 ci-tools-build-root: add 1.21 remove 1.17
  clusters/app.ci/supplemental-ci-images/ci-tools-build-root.yaml
Labels: lgtm, approved, rehearsals-ack

#42965 Remove priority field from test names for 4.13
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#42953 Add Nutanix cucushift-installer-check
  ci-operator/step-registry/cucushift/installer/rehearse/nutanix/ipi/boot-categories-project/provision/cucushift-installer-rehearse-nutanix-ipi-boot-categories-project-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/nutanix/ipi/disconnected/provision/cucushift-installer-rehearse-nutanix-ipi-disconnected-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/nutanix/ipi/image-registry-s3/provision/cucushift-installer-rehearse-nutanix-ipi-image-registry-s3-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/nutanix/ipi/provision/cucushift-installer-rehearse-nutanix-ipi-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/nutanix/ipi/proxy/provision/cucushift-installer-rehearse-nutanix-ipi-proxy-provision-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#42918 fix getVersion issue when trigger job by remote api
  ci-operator/step-registry/cucushift/installer/check/capability/cucushift-installer-check-capability-commands.sh
  ci-operator/step-registry/cucushift/installer/check/capability/cucushift-installer-check-capability-ref.yaml
  ci-operator/step-registry/cucushift/installer/check/control-plane-machinesets/cucushift-installer-check-control-plane-machinesets-commands.sh
  ci-operator/step-registry/cucushift/installer/check/control-plane-machinesets/cucushift-installer-check-control-plane-machinesets-ref.yaml
  ci-operator/step-registry/ipi/conf/azure/ipi-conf-azure-commands.sh
  ci-operator/step-registry/ipi/conf/azure/ipi-conf-azure-ref.yaml
  ci-operator/step-registry/ipi/conf/azure/osimage/ipi-conf-azure-osimage-commands.sh
  ci-operator/step-registry/ipi/conf/azure/osimage/ipi-conf-azure-osimage-ref.yaml
  ci-operator/step-registry/ipi/conf/ibmcloud/provisionednetwork/ipi-conf-ibmcloud-provisionednetwork-commands.sh
  ci-operator/step-registry/ipi/conf/ibmcloud/provisionednetwork/ipi-conf-ibmcloud-provisionednetwork-ref.yaml
  ci-operator/step-registry/ipi/conf/vsphere/ipi-conf-vsphere-commands.sh
  ci-operator/step-registry/ipi/conf/vsphere/ipi-conf-vsphere-ref.yaml
  ci-operator/step-registry/ipi/conf/vsphere/template/ipi-conf-vsphere-template-commands.sh
  ci-operator/step-registry/ipi/conf/vsphere/template/ipi-conf-vsphere-template-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#42922 Fix issue DPTP-3553 Add TAG env
  Makefile
Labels: lgtm, approved, rehearsals-ack

#42968 USHIFT-1656: Add reporter config to metal nightly
  ci-operator/jobs/openshift/microshift/openshift-microshift-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#42979 Update Package Operator to go 1.20
  ci-operator/config/package-operator/package-operator/package-operator-package-operator-main.yaml
Labels: lgtm, approved, rehearsals-ack

#42982 `arm01`: add quay.io pull-secret
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#42974 Update Jaeger version and debug Jaeger jobs
  ci-operator/config/jaegertracing/jaeger-operator/jaegertracing-jaeger-operator-main.yaml
  ci-operator/config/jaegertracing/jaeger-operator/jaegertracing-jaeger-operator-main__ocp-4.13-hypershift.yaml
  ci-operator/config/jaegertracing/jaeger-operator/jaegertracing-jaeger-operator-main__ocp-4.14-amd64.yaml
Labels: lgtm, approved, rehearsals-ack

#41945 CORS-2772: Support pd-balanced disk types for GCP deployments
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.13.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.14.yaml
  ci-operator/step-registry/cucushift/installer/check/gcp/disktype-compute/OWNERS
  ci-operator/step-registry/cucushift/installer/check/gcp/disktype-compute/cucushift-installer-check-gcp-disktype-compute-commands.sh
  ci-operator/step-registry/cucushift/installer/check/gcp/disktype-compute/cucushift-installer-check-gcp-disktype-compute-ref.metadata.json
  ci-operator/step-registry/cucushift/installer/check/gcp/disktype-compute/cucushift-installer-check-gcp-disktype-compute-ref.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/provision/cucushift-installer-rehearse-gcp-ipi-provision-chain.yaml
  ci-operator/step-registry/ipi/conf/gcp/ipi-conf-gcp-chain.yaml
  ci-operator/step-registry/ipi/conf/gcp/osdisk/disktype-compute/OWNERS
  ci-operator/step-registry/ipi/conf/gcp/osdisk/disktype-compute/ipi-conf-gcp-osdisk-disktype-compute-commands.sh
  ci-operator/step-registry/ipi/conf/gcp/osdisk/disktype-compute/ipi-conf-gcp-osdisk-disktype-compute-ref.metadata.json
  ci-operator/step-registry/ipi/conf/gcp/osdisk/disktype-compute/ipi-conf-gcp-osdisk-disktype-compute-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#42957 remove hypershift aws kubevirt jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#42950 Update quay39 tests on ARO OCP 4.14
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__quay-aro-ocp.yaml
  ci-operator/jobs/quay/quay-tests/quay-quay-tests-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#42967 [azure] add job for NAT gateway
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.14.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
  ci-operator/step-registry/ipi/conf/azure/ipi-conf-azure-commands.sh
Labels: lgtm, approved, rehearsals-ack

#42987 fix: Build base image from repository
  ci-operator/config/openshift/addon-operator/openshift-addon-operator-main.yaml
  ci-operator/jobs/openshift/addon-operator/openshift-addon-operator-main-postsubmits.yaml
  ci-operator/jobs/openshift/addon-operator/openshift-addon-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#42758 Enable defaulting webhook for hypershift/kubevirt platform
  ci-operator/config/openshift/hypershift/openshift-hypershift-main.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.14__periodics.yaml
  ci-operator/step-registry/hypershift/install/hypershift-install-commands.sh
  ci-operator/step-registry/hypershift/install/hypershift-install-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#42951 use a baseDomain having no public dns zone, for GCP IPI XPN Private scenario
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.13.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/xpn/private/provision/cucushift-installer-rehearse-gcp-ipi-xpn-private-provision-chain.yaml
  ci-operator/step-registry/ipi/conf/gcp/basedomain/OWNERS
  ci-operator/step-registry/ipi/conf/gcp/basedomain/ipi-conf-gcp-basedomain-commands.sh
  ci-operator/step-registry/ipi/conf/gcp/basedomain/ipi-conf-gcp-basedomain-ref.metadata.json
  ci-operator/step-registry/ipi/conf/gcp/basedomain/ipi-conf-gcp-basedomain-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#42989 Fix tests for several destructive jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly.yaml
Labels: lgtm, approved, rehearsals-ack

#42991 Fix test filter
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__arm64-nightly.yaml
Labels: lgtm, approved, rehearsals-ack

#42977 test: add additional check for osd fm deprovision job
  ci-operator/step-registry/osd-ccs/fleet-manager/sc/deprovision/osd-ccs-fleet-manager-sc-deprovision-commands.sh
Labels: lgtm, approved, rehearsals-ack

#42946 Change metallb-operator image_stream_tag to go1.20
  ci-operator/config/openshift/metallb-operator/openshift-metallb-operator-main.yaml
  ci-operator/config/openshift/metallb-operator/openshift-metallb-operator-release-4.15.yaml
Labels: lgtm, approved, rehearsals-ack

#43006 [CRC] update bundle url from gcp bucket to mirror
  ci-operator/step-registry/code-ready/crc/integration/test/code-ready-crc-integration-test-commands.sh
Labels: lgtm, approved, rehearsals-ack

#42996 Add destructive job for vSphere 4.14
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#42707 Added govulncheck to backplane-cli CI
  ci-operator/config/openshift/backplane-cli/openshift-backplane-cli-main.yaml
  ci-operator/jobs/openshift/backplane-cli/openshift-backplane-cli-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#42978 USHIFT-547: Add periodic conformance job
  ci-operator/config/openshift/microshift/openshift-microshift-main.yaml
  ci-operator/jobs/openshift/microshift/openshift-microshift-main-periodics.yaml
  ci-operator/step-registry/openshift/microshift/e2e/conformance-from-source/OWNERS
  ci-operator/step-registry/openshift/microshift/e2e/conformance-from-source/openshift-microshift-e2e-conformance-from-source-workflow.metadata.json
  ci-operator/step-registry/openshift/microshift/e2e/conformance-from-source/openshift-microshift-e2e-conformance-from-source-workflow.yaml
  ci-operator/step-registry/openshift/microshift/e2e/openshift-conformance-reduced-aws/openshift-microshift-e2e-openshift-conformance-reduced-aws-commands.sh
  ci-operator/step-registry/openshift/microshift/infra/install-from-source/OWNERS
  ci-operator/step-registry/openshift/microshift/infra/install-from-source/openshift-microshift-infra-install-from-source-commands.sh
  ci-operator/step-registry/openshift/microshift/infra/install-from-source/openshift-microshift-infra-install-from-source-ref.metadata.json
  ci-operator/step-registry/openshift/microshift/infra/install-from-source/openshift-microshift-infra-install-from-source-ref.yaml
  ci-operator/step-registry/openshift/microshift/infra/sos-aws/openshift-microshift-infra-sos-aws-commands.sh
  ci-operator/step-registry/openshift/microshift/infra/wait-for-cluster-up-aws/openshift-microshift-infra-wait-for-cluster-up-aws-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#43012 MGMT-15506: Make assisted-service-index:ocm-2.9 image available in Prow
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_edge_infrastructure
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#42840 update upstream dockerfile reference for linuxptp-daemon
  ci-operator/config/openshift/linuxptp-daemon/openshift-linuxptp-daemon-master.yaml
  ci-operator/config/openshift/linuxptp-daemon/openshift-linuxptp-daemon-release-4.14.yaml
  ci-operator/config/openshift/linuxptp-daemon/openshift-linuxptp-daemon-release-4.15.yaml
Labels: lgtm, approved, rehearsals-ack

#43030 ocpbugs-18550: remove failing gcp-osdisk check
  ci-operator/step-registry/ipi/conf/gcp/ipi-conf-gcp-chain.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#42888 Fixing iterations on control plan smoke tests
  ci-operator/step-registry/openshift-qe/kube-burner-smoke/openshift-qe-kube-burner-smoke-commands.sh
Labels: lgtm, approved, rehearsals-ack

#43027 fix missing comma in firewatch config.
  ci-operator/config/stolostron/acmqe-autotest/stolostron-acmqe-autotest-main__acm-ocp4.14-lp-interop.yaml
Labels: lgtm, approved, rehearsals-ack

#43031 telco5g: Run 4.11 telco5g jobs on weekends only
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.11.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#42984 Use modelmesh-serving-develop for running FVTs
  ci-operator/config/opendatahub-io/modelmesh-runtime-adapter/opendatahub-io-modelmesh-runtime-adapter-main.yaml
  ci-operator/config/opendatahub-io/modelmesh-runtime-adapter/opendatahub-io-modelmesh-runtime-adapter-release-v0.11.0-alpha.yaml
Labels: lgtm, approved, rehearsals-ack

#43013 Add if HCP for node ready to account for infra node being included in HCP desired node count
  ci-operator/step-registry/rosa/cluster/wait-ready/nodes/rosa-cluster-wait-ready-nodes-commands.sh
Labels: lgtm, approved, rehearsals-ack

#43034 update base image to base-rhel9 for linuxptp-daemon
  ci-operator/config/openshift/linuxptp-daemon/openshift-linuxptp-daemon-master.yaml
  ci-operator/config/openshift/linuxptp-daemon/openshift-linuxptp-daemon-release-4.14.yaml
  ci-operator/config/openshift/linuxptp-daemon/openshift-linuxptp-daemon-release-4.15.yaml
Labels: lgtm, approved, rehearsals-ack

#43035 Updating docs on release controller page for Multi payload
  core-services/release-controller/_releases/priv/release-ocp-4.13-multi.json
  core-services/release-controller/_releases/priv/release-ocp-4.14-multi.json
  core-services/release-controller/_releases/priv/release-ocp-4.15-multi.json
  core-services/release-controller/_releases/release-ocp-4.13-multi.json
  core-services/release-controller/_releases/release-ocp-4.14-multi.json
  core-services/release-controller/_releases/release-ocp-4.15-multi.json
Labels: lgtm, approved, rehearsals-ack

#43039 Limit the rate of writes to quay.io
  ci-operator/jobs/infra-image-mirroring.yaml
Labels: lgtm, approved, rehearsals-ack

#42993 mtsre-1421 prow changes for codecov
  ci-operator/config/openshift/addon-operator/openshift-addon-operator-main.yaml
  ci-operator/jobs/openshift/addon-operator/openshift-addon-operator-main-postsubmits.yaml
  ci-operator/jobs/openshift/addon-operator/openshift-addon-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#43046 fix: consume root image from repository
  ci-operator/config/openshift/backplane-cli/openshift-backplane-cli-main.yaml
  ci-operator/jobs/openshift/backplane-cli/openshift-backplane-cli-main-postsubmits.yaml
  ci-operator/jobs/openshift/backplane-cli/openshift-backplane-cli-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#43005 Refine test filter for destructive tests
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__ppc64le-nightly.yaml
Labels: lgtm, approved, rehearsals-ack

#42966 enable encryption for rosa/rosa hypershift
  ci-operator/step-registry/rosa/aws/non-sts/advanced/rosa-aws-non-sts-advanced-workflow.yaml
  ci-operator/step-registry/rosa/aws/sts/advanced/rosa-aws-sts-advanced-workflow.yaml
  ci-operator/step-registry/rosa/aws/sts/deprovision/byo/oidc/rosa-aws-sts-deprovision-byo-oidc-chain.yaml
  ci-operator/step-registry/rosa/aws/sts/hypershift/advanced/rosa-aws-sts-hypershift-advanced-workflow.yaml
  ci-operator/step-registry/rosa/aws/sts/hypershift/deprovision/rosa-aws-sts-hypershift-deprovision-chain.yaml
  ci-operator/step-registry/rosa/aws/sts/hypershift/provision/rosa-aws-sts-hypershift-provision-chain.yaml
  ci-operator/step-registry/rosa/aws/sts/provision/byo/oidc/rosa-aws-sts-provision-byo-oidc-chain.yaml
  ci-operator/step-registry/rosa/cluster/provision/rosa-cluster-provision-commands.sh
  ci-operator/step-registry/rosa/cluster/provision/rosa-cluster-provision-ref.yaml
  ci-operator/step-registry/rosa/sts/account-roles/create/rosa-sts-account-roles-create-commands.sh
  ci-operator/step-registry/rosa/sts/account-roles/delete/rosa-sts-account-roles-delete-commands.sh
  ci-operator/step-registry/rosa/sts/kms-key/OWNERS
  ci-operator/step-registry/rosa/sts/kms-key/create/OWNERS
  ci-operator/step-registry/rosa/sts/kms-key/create/rosa-sts-kms-key-create-commands.sh
  ci-operator/step-registry/rosa/sts/kms-key/create/rosa-sts-kms-key-create-ref.metadata.json
  ci-operator/step-registry/rosa/sts/kms-key/create/rosa-sts-kms-key-create-ref.yaml
  ci-operator/step-registry/rosa/sts/kms-key/delete/OWNERS
  ci-operator/step-registry/rosa/sts/kms-key/delete/rosa-sts-kms-key-delete-commands.sh
  ci-operator/step-registry/rosa/sts/kms-key/delete/rosa-sts-kms-key-delete-ref.metadata.json
  ci-operator/step-registry/rosa/sts/kms-key/delete/rosa-sts-kms-key-delete-ref.yaml
  ci-operator/step-registry/rosa/sts/oidc-config/create/rosa-sts-oidc-config-create-chain.metadata.json
  ci-operator/step-registry/rosa/sts/oidc-config/create/rosa-sts-oidc-config-create-chain.yaml
  ci-operator/step-registry/rosa/sts/oidc-config/create/rosa-sts-oidc-config-create-commands.sh
  ci-operator/step-registry/rosa/sts/oidc-config/delete/rosa-sts-oidc-config-delete-chain.metadata.json
  ci-operator/step-registry/rosa/sts/oidc-config/delete/rosa-sts-oidc-config-delete-chain.yaml
  ci-operator/step-registry/rosa/sts/oidc-config/delete/rosa-sts-oidc-config-delete-commands.sh
  ci-operator/step-registry/rosa/sts/operator-roles/create/rosa-sts-operator-roles-create-commands.sh
  ci-operator/step-registry/rosa/sts/operator-roles/delete/rosa-sts-operator-roles-delete-commands.sh
Labels: lgtm, approved, rehearsals-ack

#43045 increase test frequency from f28 to f14 on 4.14 eus ci
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly-4.14-upgrade-from-eus-4.12.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#42857 add workflow for zonal masters and workers in different subnets
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/zones/multisubnets/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/zones/multisubnets/external-lb/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/zones/multisubnets/external-lb/cucushift-installer-rehearse-vsphere-ipi-zones-multisubnets-external-lb-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/zones/multisubnets/external-lb/cucushift-installer-rehearse-vsphere-ipi-zones-multisubnets-external-lb-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/zones/multisubnets/external-lb/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/zones/multisubnets/external-lb/provision/cucushift-installer-rehearse-vsphere-ipi-zones-multisubnets-external-lb-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/zones/multisubnets/external-lb/provision/cucushift-installer-rehearse-vsphere-ipi-zones-multisubnets-external-lb-provision-chain.yaml
  ci-operator/step-registry/ipi/conf/vsphere/lb/external/ipi-conf-vsphere-lb-external-commands.sh
  ci-operator/step-registry/ipi/conf/vsphere/zones/multisubnets/OWNERS
  ci-operator/step-registry/ipi/conf/vsphere/zones/multisubnets/external-lb/OWNERS
  ci-operator/step-registry/ipi/conf/vsphere/zones/multisubnets/external-lb/ipi-conf-vsphere-zones-multisubnets-external-lb-chain.metadata.json
  ci-operator/step-registry/ipi/conf/vsphere/zones/multisubnets/external-lb/ipi-conf-vsphere-zones-multisubnets-external-lb-chain.yaml
  ci-operator/step-registry/ipi/conf/vsphere/zones/multisubnets/ipi-conf-vsphere-zones-multisubnets-commands.sh
  ci-operator/step-registry/ipi/conf/vsphere/zones/multisubnets/ipi-conf-vsphere-zones-multisubnets-ref.metadata.json
  ci-operator/step-registry/ipi/conf/vsphere/zones/multisubnets/ipi-conf-vsphere-zones-multisubnets-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#43009 MGMT-15504: Add temporary image streams for ocm-2.10 Assisted Installer migration
  clusters/app.ci/supplemental-ci-images/assisted-ci-tools/temp-images-for-migration.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#43048 Clean up unused workflows
  ci-operator/step-registry/cucushift/e2e/destructive/cucushift-e2e-destructive-workflow.metadata.json
  ci-operator/step-registry/cucushift/e2e/destructive/cucushift-e2e-destructive-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#43044 Update quay38 and quay37 ocp413
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__ocp-413-quay39.yaml
  ci-operator/jobs/quay/quay-tests/quay-quay-tests-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#43017 :lady_beetle: Adding a specific timeout to the `e2e-mesh-ocp-*` jobs
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main__4.10.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main__4.13.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main-periodics.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main-presubmits.yaml
Labels: kind/bug, lgtm, approved, rehearsals-ack

#43060 adjust job name for report portal
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-master__rosacli.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#43052 Update 'che-server' component
  ci-operator/config/eclipse-che/che-server/eclipse-che-che-server-main__v12.yaml
  ci-operator/jobs/eclipse-che/che-server/eclipse-che-che-server-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#42970 separate post submit job for aws & gcp
  ci-operator/config/openshift-power-monitoring/kepler-operator/openshift-power-monitoring-kepler-operator-v1alpha1__post-submits-aws.yaml
  ci-operator/config/openshift-power-monitoring/kepler-operator/openshift-power-monitoring-kepler-operator-v1alpha1__post-submits-gcp.yaml
  ci-operator/jobs/openshift-power-monitoring/kepler-operator/openshift-power-monitoring-kepler-operator-v1alpha1-postsubmits.yaml
  ci-operator/jobs/openshift-power-monitoring/kepler-operator/openshift-power-monitoring-kepler-operator-v1alpha1-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#43057 KMM: comment out image mirroring for 2.0
  core-services/image-mirroring/edge-infrastructure/mapping_edge_infrastructure_kernel_module_management
Labels: lgtm, approved, rehearsals-ack

#43043 hypershift: skip release image validation on conformance workflow
  ci-operator/step-registry/hypershift/aws/create/hypershift-aws-create-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#42958 [odf-mg] Fix buildroot Dockerfile path
  ci-operator/config/red-hat-storage/odf-must-gather/red-hat-storage-odf-must-gather-main.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#43041 Looking to add a simple SNO job
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-sno-4.13.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-sno-4.14.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-periodics.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-postsubmits.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#43073 Update UPI step-registry OWNERS
  ci-operator/step-registry/upi/OWNERS
Labels: lgtm, approved, rehearsals-ack

#43077 turn off presubmits gcp CI for oadp
  ci-operator/jobs/openshift/oadp-operator/openshift-oadp-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/oadp-operator/openshift-oadp-operator-oadp-1.1-presubmits.yaml
  ci-operator/jobs/openshift/oadp-operator/openshift-oadp-operator-oadp-1.2-presubmits.yaml
  ci-operator/jobs/openshift/oadp-operator/openshift-oadp-operator-velero-datamover-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#43063 openstack: Tag floating IPs
  ci-operator/step-registry/openstack/provision/floatingips/openstack-provision-floatingips-commands.sh
Labels: lgtm, approved, rehearsals-ack

#42078 openstack-k8s: drop support for storage bundle
  ci-operator/step-registry/openstack-k8s-operators/build/openstack-k8s-operators-build-commands.sh
Labels: lgtm, approved, rehearsals-ack

#42861 cert-rotation: collect sos report and other data after time skew
  ci-operator/step-registry/gather/cert-rotation/OWNERS
  ci-operator/step-registry/gather/cert-rotation/gather-cert-rotation-commands.sh
  ci-operator/step-registry/gather/cert-rotation/gather-cert-rotation-ref.metadata.json
  ci-operator/step-registry/gather/cert-rotation/gather-cert-rotation-ref.yaml
  ci-operator/step-registry/openshift/e2e/cert-rotation/shutdown/openshift-e2e-cert-rotation-shutdown-commands.sh
  ci-operator/step-registry/openshift/e2e/cert-rotation/shutdown/openshift-e2e-cert-rotation-shutdown-workflow.yaml
  ci-operator/step-registry/openshift/e2e/cert-rotation/shutdown/sno/openshift-e2e-cert-rotation-shutdown-sno-workflow.yaml
  ci-operator/step-registry/openshift/e2e/cert-rotation/suspend/openshift-e2e-cert-rotation-suspend-commands.sh
  ci-operator/step-registry/openshift/e2e/cert-rotation/suspend/openshift-e2e-cert-rotation-suspend-workflow.yaml
  ci-operator/step-registry/openshift/e2e/cert-rotation/suspend/sno/openshift-e2e-cert-rotation-suspend-sno-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#43085 SDCICD-985 - Distributing cicd jobs on new aws
  ci-operator/config/openshift/aws-vpce-operator/openshift-aws-vpce-operator-main.yaml
  ci-operator/config/openshift/osde2e/openshift-osde2e-main.yaml
  ci-operator/config/openshift/osde2e/openshift-osde2e-main__addon.yaml
  ci-operator/jobs/openshift/aws-vpce-operator/openshift-aws-vpce-operator-main-postsubmits.yaml
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#43067 fix bug with golang-1.20 dockerfile
  clusters/build-clusters/01_cluster/ci/_origin-release-build/golang-1.20/Dockerfile
Labels: lgtm, approved, rehearsals-ack

#42751 HyperShift QE: add 4.14 job
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#42938 ACM-6105: update binary name for hcp for mce 2.4
  ci-operator/step-registry/hypershift/mce/aws/create/hypershift-mce-aws-create-chain.yaml
  ci-operator/step-registry/hypershift/mce/aws/destroy/hypershift-mce-aws-destroy-chain.yaml
  ci-operator/step-registry/hypershift/mce/dump/hypershift-mce-dump-commands.sh
  ci-operator/step-registry/hypershift/mce/dump/hypershift-mce-dump-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#43080 PTP tests: nightly periodics scheduling changes
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.11.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.15.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#42563 cno: Add hypershift kubevirt job
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-master.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.14.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.15.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.14-presubmits.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.15-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#43056 Refine test filter for long duration tests
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-nightly.yaml
  ci-operator/step-registry/cucushift/e2e/long-duration/cucushift-e2e-long-duration-commands.sh
Labels: lgtm, approved, rehearsals-ack

#42954 MULTIARCH-3731: Use hcp-cli-download component instead of hypershift-cli-download
  ci-operator/step-registry/hypershift/mce/power/conformance/hypershift-mce-power-conformance-workflow.yaml
  ci-operator/step-registry/hypershift/mce/power/create/hypershift-mce-power-create-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#42983 Update GPU operator test matrix
  ci-operator/config/rh-ecosystem-edge/ci-tools-nvidia-gpu-operator/rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main.yaml
  ci-operator/config/rh-ecosystem-edge/ci-tools-nvidia-gpu-operator/rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main__4.10.yaml
  ci-operator/config/rh-ecosystem-edge/ci-tools-nvidia-gpu-operator/rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main__4.11.yaml
  ci-operator/config/rh-ecosystem-edge/ci-tools-nvidia-gpu-operator/rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main__4.12.yaml
  ci-operator/config/rh-ecosystem-edge/ci-tools-nvidia-gpu-operator/rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main__4.13.yaml
  ci-operator/config/rh-ecosystem-edge/ci-tools-nvidia-gpu-operator/rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main__4.14.yaml
  ci-operator/jobs/rh-ecosystem-edge/ci-tools-nvidia-gpu-operator/rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-periodics.yaml
  ci-operator/jobs/rh-ecosystem-edge/ci-tools-nvidia-gpu-operator/rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#43058 Adding a timeout to operator-sdk run bundle for DVO
  ci-operator/config/app-sre/deployment-validation-operator/app-sre-deployment-validation-operator-master.yaml
Labels: lgtm, approved, rehearsals-ack

#42428 hypershift: cluster-image-registry-operator: add conformance presubmit test
  ci-operator/config/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-master.yaml
  ci-operator/config/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-release-4.14.yaml
  ci-operator/config/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-release-4.15.yaml
  ci-operator/jobs/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-release-4.14-presubmits.yaml
  ci-operator/jobs/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-release-4.15-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#43008 sriov-cni: rename Dockerfile and bump rhel version
  ci-operator/config/openshift/sriov-cni/openshift-sriov-cni-release-4.13.yaml
Labels: lgtm, approved, rehearsals-ack

#42686 Enable cucushift-installer-check to all vSphere workflows
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/disconnected/provision/cucushift-installer-rehearse-vsphere-ipi-disconnected-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/disconnected/techpreview/provision/cucushift-installer-rehearse-vsphere-ipi-disconnected-techpreview-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/disk-encryption/tang/provision/cucushift-installer-rehearse-vsphere-ipi-disk-encryption-tang-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/external-lb/post/provision/cucushift-installer-rehearse-vsphere-ipi-external-lb-post-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/external-lb/pre/provision/cucushift-installer-rehearse-vsphere-ipi-external-lb-pre-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/ovn/dualstack/provision/cucushift-installer-rehearse-vsphere-ipi-ovn-dualstack-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/ovn/ipsec/provision/cucushift-installer-rehearse-vsphere-ipi-ovn-ipsec-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/ovn/provision/cucushift-installer-rehearse-vsphere-ipi-ovn-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/ovn/sdn2ovn/provision/cucushift-installer-rehearse-vsphere-ipi-ovn-sdn2ovn-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/provision/cucushift-installer-rehearse-vsphere-ipi-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/proxy/provision/cucushift-installer-rehearse-vsphere-ipi-proxy-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/proxy/techpreview/provision/cucushift-installer-rehearse-vsphere-ipi-proxy-techpreview-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/remote-worker/provision/cucushift-installer-rehearse-vsphere-ipi-remote-worker-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/sdn/provision/cucushift-installer-rehearse-vsphere-ipi-sdn-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/static-ip/provision/cucushift-installer-rehearse-vsphere-ipi-static-ip-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/template/provision/cucushift-installer-rehearse-vsphere-ipi-template-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/zones/provision/cucushift-installer-rehearse-vsphere-ipi-zones-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/disconnected/provision/cucushift-installer-rehearse-vsphere-upi-disconnected-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/disconnected/sdn/provision/cucushift-installer-rehearse-vsphere-upi-disconnected-sdn-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/disconnecting-network/provision/cucushift-installer-rehearse-vsphere-upi-disconnecting-network-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/ovn/sdn2ovn-rollback/provision/cucushift-installer-rehearse-vsphere-upi-ovn-sdn2ovn-rollback-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/ovn/sdn2ovn/provision/cucushift-installer-rehearse-vsphere-upi-ovn-sdn2ovn-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/platform-external/provision/cucushift-installer-rehearse-vsphere-upi-platform-external-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/provision/cucushift-installer-rehearse-vsphere-upi-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/proxy/provision/cucushift-installer-rehearse-vsphere-upi-proxy-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/upi/zones/provision/cucushift-installer-rehearse-vsphere-upi-zones-provision-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#42998 Wait until cluster is ready before running CNF tests in Telco 5G DevOps/CI
  ci-operator/step-registry/telco5g/cnf/tests/telco5g-cnf-tests-commands.sh
Labels: lgtm, approved, rehearsals-ack

#43102 HyperShift: update enable-qe-catalogsource
  ci-operator/step-registry/cucushift/hypershift-extended/enable-qe/catalogsource/cucushift-hypershift-extended-enable-qe-catalogsource-commands.sh
  ci-operator/step-registry/cucushift/hypershift-extended/enable-qe/pull-secret/cucushift-hypershift-extended-enable-qe-pull-secret-commands.sh
Labels: lgtm, approved, rehearsals-ack

#43075 Add long duration Azure Mag job for Hive
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#43104 manila-operator: Make kuttl job and tempest job required
  ci-operator/config/openstack-k8s-operators/manila-operator/openstack-k8s-operators-manila-operator-main.yaml
  ci-operator/jobs/openstack-k8s-operators/manila-operator/openstack-k8s-operators-manila-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#43100 Do not mirror the payload in agent/bm workflows with cluster-wide proxy
  ci-operator/step-registry/baremetal/lab/agent/conf/disconnected/proxy/baremetal-lab-agent-conf-disconnected-proxy-chain.yaml
  ci-operator/step-registry/baremetal/lab/agent/install/baremetal-lab-agent-install-commands.sh
  ci-operator/step-registry/baremetal/lab/ipi/install/baremetal-lab-ipi-install-commands.sh
  ci-operator/step-registry/baremetal/lab/upi/install/baremetal-lab-upi-install-commands.sh
Labels: lgtm, approved, rehearsals-ack

#43109 vSphere 8 vpn updated boskos
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: lgtm, approved, rehearsals-ack

#43114 Adding chaos prow image
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_chaos
Labels: lgtm, approved, rehearsals-ack

#43116 openstack: Fix no-dry-run flag
  ci-operator/step-registry/shiftstack/cleanup/shiftstack-cleanup-commands.sh
Labels: lgtm, approved, rehearsals-ack

#42971 Onboarding Securesign Trillian
  ci-operator/config/securesign/trillian/OWNERS
  ci-operator/config/securesign/trillian/securesign-trillian-redhat-v1.5.2.yaml
  ci-operator/config/securesign/trillian/securesign-trillian-release-next.yaml
  ci-operator/jobs/securesign/trillian/OWNERS
  ci-operator/jobs/securesign/trillian/securesign-trillian-redhat-v1.5.2-presubmits.yaml
  ci-operator/jobs/securesign/trillian/securesign-trillian-release-next-presubmits.yaml
  core-services/prow/02_config/securesign/trillian/OWNERS
  core-services/prow/02_config/securesign/trillian/_pluginconfig.yaml
  core-services/prow/02_config/securesign/trillian/_prowconfig.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#43054 ODH DW: Install CodeFlare operator from latest main
  ci-operator/config/opendatahub-io/distributed-workloads/opendatahub-io-distributed-workloads-main.yaml
Labels: lgtm, approved, rehearsals-ack

#43106 Added jupyter-trustyai-ubi8-python-3.8
  ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-2023a.yaml
  ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-main.yaml
  ci-operator/jobs/opendatahub-io/notebooks/opendatahub-io-notebooks-2023a-postsubmits.yaml
  ci-operator/jobs/opendatahub-io/notebooks/opendatahub-io-notebooks-main-postsubmits.yaml
  ci-operator/jobs/opendatahub-io/notebooks/opendatahub-io-notebooks-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#42919 add tsa to openshift release
  ci-operator/config/securesign/timestamp-authority/OWNERS
  ci-operator/config/securesign/timestamp-authority/securesign-timestamp-authority-release-next.yaml
  ci-operator/jobs/securesign/timestamp-authority/OWNERS
  ci-operator/jobs/securesign/timestamp-authority/securesign-timestamp-authority-release-next-presubmits.yaml
  core-services/prow/02_config/securesign/timestamp-authority/OWNERS
  core-services/prow/02_config/securesign/timestamp-authority/_pluginconfig.yaml
  core-services/prow/02_config/securesign/timestamp-authority/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#43107 Remove e2e test from csi-operator
  ci-operator/config/openshift/csi-operator/OWNERS
  ci-operator/config/openshift/csi-operator/openshift-csi-operator-master.yaml
  ci-operator/config/openshift/csi-operator/openshift-csi-operator-release-4.14.yaml
  ci-operator/config/openshift/csi-operator/openshift-csi-operator-release-4.15.yaml
  ci-operator/jobs/openshift/csi-operator/openshift-csi-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/csi-operator/openshift-csi-operator-release-4.14-presubmits.yaml
  ci-operator/jobs/openshift/csi-operator/openshift-csi-operator-release-4.15-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#42873 add test tags for OBS
  ci-operator/step-registry/acm/mch/acm-mch-commands.sh
  ci-operator/step-registry/acm/tests/obs/acm-tests-obs-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#43083 Use golang v1.20
  ci-operator/config/stolostron/volsync-addon-controller/stolostron-volsync-addon-controller-main.yaml
  ci-operator/config/stolostron/volsync-addon-controller/stolostron-volsync-addon-controller-release-2.6.yaml
  ci-operator/config/stolostron/volsync-addon-controller/stolostron-volsync-addon-controller-release-2.7.yaml
  ci-operator/config/stolostron/volsync-addon-controller/stolostron-volsync-addon-controller-release-2.8.yaml
  ci-operator/config/stolostron/volsync-addon-controller/stolostron-volsync-addon-controller-release-2.9.yaml
Labels: lgtm, approved, rehearsals-ack

#42881 Disable Loki and UDP aggregation for s390x multi-arch compute
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.14.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.15.yaml
  ci-operator/step-registry/ipi/install/heterogeneous/ipi-install-heterogeneous-commands.sh
Labels: lgtm, approved, rehearsals-ack

#43117 Upgrade HyperShift operator to 20230907
  Makefile
  ci-operator/step-registry/hypershift/hostedcluster/create/hostedcluster/hypershift-hostedcluster-create-hostedcluster-commands.sh
  ci-operator/step-registry/hypershift/hostedcluster/create/hostedcluster/hypershift-hostedcluster-create-hostedcluster-ref.yaml
  ci-operator/step-registry/hypershift/hostedcluster/destroy/hostedcluster/hypershift-hostedcluster-destroy-hostedcluster-ref.yaml
  ci-operator/step-registry/hypershift/hostedcluster/dump/hostedcluster/hypershift-hostedcluster-dump-hostedcluster-ref.yaml
  clusters/app.ci/supplemental-ci-images/hypershift/hypershift-cli.yaml
Labels: lgtm, approved, rehearsals-ack

#42672 Parameterizing sdn to ovn migration timeout
  ci-operator/step-registry/ovn/sdn-migration/ovn-sdn-migration-commands.sh
  ci-operator/step-registry/ovn/sdn-migration/ovn-sdn-migration-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#42749 OPRUN-1873: openshift/operator-framework-olm: publish the bumper image
  ci-operator/config/openshift/operator-framework-olm/openshift-operator-framework-olm-master.yaml
  ci-operator/jobs/openshift/operator-framework-olm/openshift-operator-framework-olm-master-postsubmits.yaml
  ci-operator/jobs/openshift/operator-framework-olm/openshift-operator-framework-olm-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#42796 Adding cspi team alias into OWNERS files
  ci-operator/config/jaegertracing/jaeger-operator/OWNERS
  ci-operator/config/openshift/grafana-tempo-operator/OWNERS
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/OWNERS
  ci-operator/jobs/jaegertracing/jaeger-operator/OWNERS
  ci-operator/jobs/openshift/grafana-tempo-operator/OWNERS
  ci-operator/jobs/openshift/open-telemetry-opentelemetry-operator/OWNERS
Labels: lgtm, approved, rehearsals-ack

#42935 SPLAT-1131: introduce multi-zone-techpreview for vSphere
  ci-operator/jobs/openshift/release/openshift-release-infra-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#42936 Add back cspi-qe-ocp-lp alias as approver.
  ci-operator/config/openshift/jenkins/OWNERS
  ci-operator/jobs/openshift/jenkins/OWNERS
Labels: lgtm, approved, rehearsals-ack

#43126 Update cluster-backup-operator to use golang 1.20
  ci-operator/config/stolostron/cluster-backup-operator/stolostron-cluster-backup-operator-main.yaml
  ci-operator/config/stolostron/cluster-backup-operator/stolostron-cluster-backup-operator-release-2.6.yaml
  ci-operator/config/stolostron/cluster-backup-operator/stolostron-cluster-backup-operator-release-2.7.yaml
  ci-operator/config/stolostron/cluster-backup-operator/stolostron-cluster-backup-operator-release-2.8.yaml
  ci-operator/config/stolostron/cluster-backup-operator/stolostron-cluster-backup-operator-release-2.9.yaml
Labels: lgtm, approved, rehearsals-ack

#43093 SDN-4105: add perfscale job to CNO
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-master.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#43129 Revert "OPRUN-1873: openshift/operator-framework-olm: publish the bumper image"
  ci-operator/config/openshift/operator-framework-olm/openshift-operator-framework-olm-master.yaml
  ci-operator/jobs/openshift/operator-framework-olm/openshift-operator-framework-olm-master-postsubmits.yaml
  ci-operator/jobs/openshift/operator-framework-olm/openshift-operator-framework-olm-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#42519 OCPQE-16634: add mce-agent workflow
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.14__periodics.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.14-periodics.yaml
  ci-operator/step-registry/hypershift/agent/create/metallb/hypershift-agent-create-metallb-commands.sh
  ci-operator/step-registry/hypershift/mce/agent/OWNERS
  ci-operator/step-registry/hypershift/mce/agent/conformance/OWNERS
  ci-operator/step-registry/hypershift/mce/agent/conformance/hypershift-mce-agent-conformance-workflow.metadata.json
  ci-operator/step-registry/hypershift/mce/agent/conformance/hypershift-mce-agent-conformance-workflow.yaml
  ci-operator/step-registry/hypershift/mce/agent/create/OWNERS
  ci-operator/step-registry/hypershift/mce/agent/create/agentserviceconfig/OWNERS
  ci-operator/step-registry/hypershift/mce/agent/create/agentserviceconfig/hypershift-mce-agent-create-agentserviceconfig-commands.sh
  ci-operator/step-registry/hypershift/mce/agent/create/agentserviceconfig/hypershift-mce-agent-create-agentserviceconfig-ref.metadata.json
  ci-operator/step-registry/hypershift/mce/agent/create/agentserviceconfig/hypershift-mce-agent-create-agentserviceconfig-ref.yaml
  ci-operator/step-registry/hypershift/mce/agent/create/hostedcluster/OWNERS
  ci-operator/step-registry/hypershift/mce/agent/create/hostedcluster/hypershift-mce-agent-create-hostedcluster-commands.sh
  ci-operator/step-registry/hypershift/mce/agent/create/hostedcluster/hypershift-mce-agent-create-hostedcluster-ref.metadata.json
  ci-operator/step-registry/hypershift/mce/agent/create/hostedcluster/hypershift-mce-agent-create-hostedcluster-ref.yaml
  ci-operator/step-registry/hypershift/mce/agent/create/hypershift-mce-agent-create-chain.metadata.json
  ci-operator/step-registry/hypershift/mce/agent/create/hypershift-mce-agent-create-chain.yaml
  ci-operator/step-registry/hypershift/mce/agent/destroy/OWNERS
  ci-operator/step-registry/hypershift/mce/agent/destroy/hypershift-mce-agent-destroy-chain.metadata.json
  ci-operator/step-registry/hypershift/mce/agent/destroy/hypershift-mce-agent-destroy-chain.yaml
  ci-operator/step-registry/hypershift/mce/agent/lvm/OWNERS
  ci-operator/step-registry/hypershift/mce/agent/lvm/hypershift-mce-agent-lvm-chain.metadata.json
  ci-operator/step-registry/hypershift/mce/agent/lvm/hypershift-mce-agent-lvm-chain.yaml
  ci-operator/step-registry/hypershift/mce/agent/lvm/hypershift-mce-agent-lvm-commands.sh
  ci-operator/step-registry/hypershift/mce/agent/lvm/hypershift-mce-agent-lvm-ref.metadata.json
  ci-operator/step-registry/hypershift/mce/agent/lvm/hypershift-mce-agent-lvm-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#42963 Remove the importing GPG key step
  ci-operator/step-registry/cucushift/chainupgrade/toimage/cucushift-chainupgrade-toimage-commands.sh
  ci-operator/step-registry/cucushift/upgrade/toimage/cucushift-upgrade-toimage-commands.sh
Labels: lgtm, approved, rehearsals-ack

#42804 Adding cspi team alias into OWNERS files
  ci-operator/config/redhat-developer/helm/OWNERS
  ci-operator/jobs/redhat-developer/helm/OWNERS
Labels: lgtm, approved, rehearsals-ack

#42945 Jv rox 17417 fix incorrect collection method in ocp
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-13.yaml
Labels: lgtm, approved, rehearsals-ack

#43134 Move the tests from EC to RC for 4.14
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-4.13-upgrade-from-aro.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-4.13-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-4.13-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-openshift-logging-5.7.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-stable-4.13-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-nightly-4.13-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-nightly-4.13-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-nightly-openshift-logging-5.7.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-stable-4.13-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__multi-nightly-4.13-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__multi-nightly-4.13-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__multi-stable-4.13-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly-4.14-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly-4.14-upgrade-from-stable-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-stable-4.14-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly-4.14-upgrade-from-stable-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-stable-4.14-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-nightly-4.14-upgrade-from-stable-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-stable-4.14-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-stable.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#43049 RELEASE_IMAGE_INITIAL take higher priority than RELEASE_IMAGE_LATEST
  ci-operator/step-registry/aws/c2s/init-token-service/aws-c2s-init-token-service-commands.sh
  ci-operator/step-registry/aws/provision/cco-manual-users/static/aws-provision-cco-manual-users-static-commands.sh
  ci-operator/step-registry/cucushift/installer/check/control-plane-machinesets/cucushift-installer-check-control-plane-machinesets-commands.sh
  ci-operator/step-registry/ipi/conf/alibabacloud/cloud-creds-provision/ipi-conf-alibabacloud-cloud-creds-provision-commands.sh
  ci-operator/step-registry/ipi/conf/aws/marketplace/ipi-conf-aws-marketplace-commands.sh
  ci-operator/step-registry/ipi/conf/aws/oidc-creds-provision/ipi-conf-aws-oidc-creds-provision-commands.sh
  ci-operator/step-registry/ipi/conf/azure/ipi-conf-azure-commands.sh
  ci-operator/step-registry/ipi/conf/azure/oidc-creds-provision/ipi-conf-azure-oidc-creds-provision-commands.sh
  ci-operator/step-registry/ipi/conf/azure/osimage/ipi-conf-azure-osimage-commands.sh
  ci-operator/step-registry/ipi/conf/azurestack/creds/ipi-conf-azurestack-creds-commands.sh
  ci-operator/step-registry/ipi/conf/gcp/oidc-creds-deprovision/ipi-conf-gcp-oidc-creds-deprovision-commands.sh
  ci-operator/step-registry/ipi/conf/gcp/oidc-creds-provision/ipi-conf-gcp-oidc-creds-provision-commands.sh
  ci-operator/step-registry/ipi/conf/gcp/osdisk/disktype-compute/ipi-conf-gcp-osdisk-disktype-compute-commands.sh
  ci-operator/step-registry/ipi/conf/ibmcloud/provisionednetwork/ipi-conf-ibmcloud-provisionednetwork-commands.sh
  ci-operator/step-registry/ipi/conf/nutanix/manual-creds/ipi-conf-nutanix-manual-creds-commands.sh
  ci-operator/step-registry/ipi/conf/vsphere/ipi-conf-vsphere-commands.sh
  ci-operator/step-registry/ipi/conf/vsphere/template/ipi-conf-vsphere-template-commands.sh
  ci-operator/step-registry/ipi/conf/vsphere/template/ipi-conf-vsphere-template-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#43120 updated Prow config for Kuadrant: adding docs.kuadrant.io and kuadran…
  core-services/prow/02_config/Kuadrant/docs.kuadrant.io/_pluginconfig.yaml
  core-services/prow/02_config/Kuadrant/docs.kuadrant.io/_prowconfig.yaml
  core-services/prow/02_config/Kuadrant/kuadrant.github.io/_pluginconfig.yaml
  core-services/prow/02_config/Kuadrant/kuadrant.github.io/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#41903 MULTIARCH-3734: Fix e2e-powervs workflow
  ci-operator/step-registry/hypershift/powervs/e2e/hypershift-powervs-e2e-workflow.yaml
  ci-operator/step-registry/hypershift/powervs/run-e2e/hypershift-powervs-run-e2e-chain.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#43138 MGMT-15703: Update nutanix ci machine base image
  ci-operator/step-registry/assisted/nutanix/setup/template/assisted-nutanix-setup-template-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#42999 capability jobs update to cover more scenarios
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
  ci-operator/step-registry/cucushift/installer/check/capability/cucushift-installer-check-capability-commands.sh
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/capability/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/capability/addtionalcaps/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/capability/addtionalcaps/cucushift-installer-rehearse-gcp-ipi-capability-addtionalcaps-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/capability/addtionalcaps/cucushift-installer-rehearse-gcp-ipi-capability-addtionalcaps-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/capability/addtionalcaps/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/capability/addtionalcaps/provision/cucushift-installer-rehearse-gcp-ipi-capability-addtionalcaps-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/capability/addtionalcaps/provision/cucushift-installer-rehearse-gcp-ipi-capability-addtionalcaps-provision-chain.yaml
  ci-operator/step-registry/ipi/conf/capability/OWNERS
  ci-operator/step-registry/ipi/conf/capability/additonalcaps/OWNERS
  ci-operator/step-registry/ipi/conf/capability/additonalcaps/ipi-conf-capability-additonalcaps-commands.sh
  ci-operator/step-registry/ipi/conf/capability/additonalcaps/ipi-conf-capability-additonalcaps-ref.metadata.json
  ci-operator/step-registry/ipi/conf/capability/additonalcaps/ipi-conf-capability-additonalcaps-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#43132 [4.12-4.13] gcp-ipi-workers-marketplace jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#42286 Branching 4.14: Update periodics
  ci-operator/jobs/infra-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#42343 Branching 4.14: Update the lists of images mirrored to Quay
  core-services/image-mirroring/openshift/_config.yaml
  core-services/image-mirroring/openshift/mapping_origin_4_14
  core-services/image-mirroring/openshift/mapping_origin_4_15
Labels: lgtm, rehearsals-ack

#43147 Bump maistra-3.0 builder image
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_ci
Labels: lgtm, approved, rehearsals-ack

#43112 gather-cert-rotation: update sosreport collect procedure
  ci-operator/step-registry/gather/cert-rotation/gather-cert-rotation-commands.sh
Labels: lgtm, approved, rehearsals-ack

#43121 cert-rotation: approve certificates for workers too
  ci-operator/step-registry/openshift/e2e/cert-rotation/shutdown/openshift-e2e-cert-rotation-shutdown-commands.sh
  ci-operator/step-registry/openshift/e2e/cert-rotation/suspend/openshift-e2e-cert-rotation-suspend-commands.sh
Labels: lgtm, approved, rehearsals-ack

#43157 Revert "RELEASE_IMAGE_INITIAL take higher priority than RELEASE_IMAGE_LATEST"
  ci-operator/step-registry/aws/c2s/init-token-service/aws-c2s-init-token-service-commands.sh
  ci-operator/step-registry/aws/provision/cco-manual-users/static/aws-provision-cco-manual-users-static-commands.sh
  ci-operator/step-registry/cucushift/installer/check/control-plane-machinesets/cucushift-installer-check-control-plane-machinesets-commands.sh
  ci-operator/step-registry/ipi/conf/alibabacloud/cloud-creds-provision/ipi-conf-alibabacloud-cloud-creds-provision-commands.sh
  ci-operator/step-registry/ipi/conf/aws/marketplace/ipi-conf-aws-marketplace-commands.sh
  ci-operator/step-registry/ipi/conf/aws/oidc-creds-provision/ipi-conf-aws-oidc-creds-provision-commands.sh
  ci-operator/step-registry/ipi/conf/azure/ipi-conf-azure-commands.sh
  ci-operator/step-registry/ipi/conf/azure/oidc-creds-provision/ipi-conf-azure-oidc-creds-provision-commands.sh
  ci-operator/step-registry/ipi/conf/azure/osimage/ipi-conf-azure-osimage-commands.sh
  ci-operator/step-registry/ipi/conf/azurestack/creds/ipi-conf-azurestack-creds-commands.sh
  ci-operator/step-registry/ipi/conf/gcp/oidc-creds-deprovision/ipi-conf-gcp-oidc-creds-deprovision-commands.sh
  ci-operator/step-registry/ipi/conf/gcp/oidc-creds-provision/ipi-conf-gcp-oidc-creds-provision-commands.sh
  ci-operator/step-registry/ipi/conf/gcp/osdisk/disktype-compute/ipi-conf-gcp-osdisk-disktype-compute-commands.sh
  ci-operator/step-registry/ipi/conf/ibmcloud/provisionednetwork/ipi-conf-ibmcloud-provisionednetwork-commands.sh
  ci-operator/step-registry/ipi/conf/nutanix/manual-creds/ipi-conf-nutanix-manual-creds-commands.sh
  ci-operator/step-registry/ipi/conf/vsphere/ipi-conf-vsphere-commands.sh
  ci-operator/step-registry/ipi/conf/vsphere/template/ipi-conf-vsphere-template-commands.sh
  ci-operator/step-registry/ipi/conf/vsphere/template/ipi-conf-vsphere-template-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#43153 Revert "Revert "openshift/operator-framework-olm: publish the bumper …
  ci-operator/config/openshift/operator-framework-olm/openshift-operator-framework-olm-master.yaml
  ci-operator/jobs/openshift/operator-framework-olm/openshift-operator-framework-olm-master-postsubmits.yaml
  ci-operator/jobs/openshift/operator-framework-olm/openshift-operator-framework-olm-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#43023 Change installation namespace for gitops operator
  ci-operator/config/redhat-developer/gitops-operator/redhat-developer-gitops-operator-master__v4.12.yaml
  ci-operator/config/redhat-developer/gitops-operator/redhat-developer-gitops-operator-master__v4.13.yaml
  ci-operator/config/redhat-developer/gitops-operator/redhat-developer-gitops-operator-master__v4.14.yaml
  ci-operator/jobs/redhat-developer/gitops-operator/redhat-developer-gitops-operator-master-periodics.yaml
  ci-operator/jobs/redhat-developer/gitops-operator/redhat-developer-gitops-operator-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#43160 node-density-cni update
  ci-operator/step-registry/openshift-qe/node-density-cni/openshift-qe-node-density-cni-commands.sh
  ci-operator/step-registry/openshift-qe/node-density-cni/openshift-qe-node-density-cni-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#43166 oadp: Add `.dockerignore` to `run-if-changed`
  ci-operator/jobs/openshift/oadp-operator/openshift-oadp-operator-ci-multi-cloud-presubmits.yaml
  ci-operator/jobs/openshift/oadp-operator/openshift-oadp-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/oadp-operator/openshift-oadp-operator-velero-datamover-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#43167 remove osde2e harness test job from avo postsubmit pipeline
  ci-operator/config/openshift/aws-vpce-operator/openshift-aws-vpce-operator-main.yaml
  ci-operator/jobs/openshift/aws-vpce-operator/openshift-aws-vpce-operator-main-postsubmits.yaml
Labels: lgtm, approved, rehearsals-ack
