Repository openshift/release, pull requests merged in 2023-08, with the labels that each got.

#41834 Fix cron entries
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__amd64-nightly-4.10-upgrade-from-eus-4.8.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__amd64-nightly-4.10-upgrade-from-stable-4.10.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__amd64-nightly-4.10-upgrade-from-stable-4.9.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__amd64-stable-4.10-upgrade-from-eus-4.8.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__arm64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly-4.11-upgrade-from-aro.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly-4.11-upgrade-from-stable-4.10-from-stable-4.9.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly-4.11-upgrade-from-stable-4.10.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly-4.11-upgrade-from-stable-4.11.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly-openshift-logging-5.5.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly-openshift-logging-5.7.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__arm64-nightly-4.11-upgrade-from-stable-4.10.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__arm64-nightly-4.11-upgrade-from-stable-4.11.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__arm64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly-openshift-logging-5.6.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly-openshift-logging-5.7.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-4.13-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-4.13-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-openshift-logging-5.7.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-nightly-openshift-logging-5.7.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#41756 check control-plane machinesets state
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.10.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.11.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.12.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.13.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.14.yaml
  ci-operator/step-registry/cucushift/installer/check/control-plane-machinesets/OWNERS
  ci-operator/step-registry/cucushift/installer/check/control-plane-machinesets/cucushift-installer-check-control-plane-machinesets-commands.sh
  ci-operator/step-registry/cucushift/installer/check/control-plane-machinesets/cucushift-installer-check-control-plane-machinesets-ref.metadata.json
  ci-operator/step-registry/cucushift/installer/check/control-plane-machinesets/cucushift-installer-check-control-plane-machinesets-ref.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/provision/cucushift-installer-rehearse-gcp-ipi-provision-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#41820 OPCT: reviewing periodics for baseline executions
  ci-operator/config/redhat-openshift-ecosystem/provider-certification-tool/redhat-openshift-ecosystem-provider-certification-tool-main__4.11.yaml
  ci-operator/config/redhat-openshift-ecosystem/provider-certification-tool/redhat-openshift-ecosystem-provider-certification-tool-main__4.13.yaml
  ci-operator/config/redhat-openshift-ecosystem/provider-certification-tool/redhat-openshift-ecosystem-provider-certification-tool-main__4.14.yaml
  ci-operator/config/redhat-openshift-ecosystem/provider-certification-tool/redhat-openshift-ecosystem-provider-certification-tool-main__4.15.yaml
  ci-operator/jobs/redhat-openshift-ecosystem/provider-certification-tool/redhat-openshift-ecosystem-provider-certification-tool-main-periodics.yaml
  ci-operator/step-registry/provider-certification-tool/run/provider-certification-tool-run-commands.sh
  ci-operator/step-registry/provider-certification-tool/run/provider-certification-tool-run-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#41837 Remove unused priority field from test names
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-master__rosacli.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.6__amd64-nightly-4.6-upgrade-from-stable-4.6.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.7__amd64-nightly-4.7-upgrade-from-stable-4.7.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.8__amd64-nightly-4.8-upgrade-from-stable-4.8.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.9__amd64-nightly-4.9-upgrade-from-stable-4.9.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-master-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.6-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.7-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.8-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.9-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#41797 Add more testconfigs for arm on gcp
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#41711 OCPBUGS-16815: EgressIP migration: use cloud egress-ipconfig instead of static values
  ci-operator/step-registry/ovn/sdn-migration/feature-migration/config-egress-ip/ovn-sdn-migration-feature-migration-config-egress-ip-commands.sh
  ci-operator/step-registry/ovn/sdn-migration/feature-migration/validate-egress-ip/ovn-sdn-migration-feature-migration-validate-egress-ip-commands.sh
  ci-operator/step-registry/ovn/sdn-migration/feature-migration/validate-egress-ip/ovn-sdn-migration-feature-migration-validate-egress-ip-ref.yaml
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, rehearsals-ack, jira/valid-reference

#41796 openshift insights operator techpreview testsuite is no more optional
  ci-operator/config/openshift/insights-operator/openshift-insights-operator-master.yaml
  ci-operator/jobs/openshift/insights-operator/openshift-insights-operator-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#41830 [openshift-loki]: Fix operator pullspec substitutions
  ci-operator/config/openshift/loki/openshift-loki-main.yaml
Labels: lgtm, approved, rehearsals-ack

#41814 gcp marketplace image for compute nodes
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.14.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
  ci-operator/step-registry/cucushift/installer/check/gcp/osimage/OWNERS
  ci-operator/step-registry/cucushift/installer/check/gcp/osimage/cucushift-installer-check-gcp-osimage-commands.sh
  ci-operator/step-registry/cucushift/installer/check/gcp/osimage/cucushift-installer-check-gcp-osimage-ref.metadata.json
  ci-operator/step-registry/cucushift/installer/check/gcp/osimage/cucushift-installer-check-gcp-osimage-ref.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/workers-marketplace/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/workers-marketplace/cucushift-installer-rehearse-gcp-ipi-workers-marketplace-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/workers-marketplace/cucushift-installer-rehearse-gcp-ipi-workers-marketplace-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/workers-marketplace/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/workers-marketplace/provision/cucushift-installer-rehearse-gcp-ipi-workers-marketplace-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/workers-marketplace/provision/cucushift-installer-rehearse-gcp-ipi-workers-marketplace-provision-chain.yaml
  ci-operator/step-registry/ipi/conf/gcp/osimage/OWNERS
  ci-operator/step-registry/ipi/conf/gcp/osimage/ipi-conf-gcp-osimage-commands.sh
  ci-operator/step-registry/ipi/conf/gcp/osimage/ipi-conf-gcp-osimage-ref.metadata.json
  ci-operator/step-registry/ipi/conf/gcp/osimage/ipi-conf-gcp-osimage-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#41819 `triage`: add filters for some errors that we don't care about
  docs/dptp-triage-sop/logs/filter.py
Labels: lgtm, approved, rehearsals-ack

#41809 KMM: Build the worker image
  ci-operator/config/rh-ecosystem-edge/kernel-module-management/rh-ecosystem-edge-kernel-module-management-main.yaml
  core-services/image-mirroring/edge-infrastructure/mapping_edge_infrastructure_kernel_module_management
Labels: lgtm, approved, rehearsals-ack

#41093 MSI: Add RHODS-RHOAM test
  ci-operator/config/CSPI-QE/MSI/CSPI-QE-MSI-rhods-rhoam__v4.13.yaml
Labels: lgtm, approved, rehearsals-ack

#41840 HCO: Add images for the new version, 1.11.0
  clusters/app.ci/supplemental-ci-images/hyperconverged-cluster-bundle.yaml
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_ci
Labels: lgtm, approved, rehearsals-ack

#41850 Add Kserve build in operator-ci
  ci-operator/config/opendatahub-io/kserve/OWNERS
  ci-operator/config/opendatahub-io/kserve/opendatahub-io-kserve-master.yaml
  ci-operator/jobs/opendatahub-io/kserve/OWNERS
  ci-operator/jobs/opendatahub-io/kserve/opendatahub-io-kserve-master-postsubmits.yaml
  ci-operator/jobs/opendatahub-io/kserve/opendatahub-io-kserve-master-presubmits.yaml
  core-services/prow/02_config/opendatahub-io/kserve/OWNERS
  core-services/prow/02_config/opendatahub-io/kserve/_pluginconfig.yaml
  core-services/prow/02_config/opendatahub-io/kserve/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#41829 [LPTOCPCI-573] Update Firewatch config to use COST project and assign test failures to dchorvat@redhat.com
  ci-operator/config/insights-qe/iqe-cost-management-plugin/insights-qe-iqe-cost-management-plugin-master__ocp4.14-lp-interop.yaml
Labels: lgtm, approved, rehearsals-ack

#41851 Add upgrade tests for stable 4.13 to EC 4.14
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-ec-4.14-upgrade-from-stable-4.13.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#41087 MSI - Onboarding RHODS interop jobs on AWS OSD
  ci-operator/config/CSPI-QE/MSI/CSPI-QE-MSI-rhods-addon-interop__v4.13-GA-production.yaml
  ci-operator/config/CSPI-QE/MSI/CSPI-QE-MSI-rhods-addon-interop__v4.13-IIB.yaml
  ci-operator/jobs/CSPI-QE/MSI/CSPI-QE-MSI-rhods-addon-interop-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#41836 Move vSphere job to devqe
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#41853 ROX-17337: increase maxSize of stackrox cluster pool as preparation for wider rollout
  clusters/hive/pools/stackrox/ocp-4.13_clusterpool.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#41859 crc: add e2e-story-microshift test
  ci-operator/step-registry/code-ready/crc/e2e/test/code-ready-crc-e2e-test-commands.sh
  ci-operator/step-registry/code-ready/crc/microshift/test/code-ready-crc-microshift-test-commands.sh
Labels: lgtm, approved, rehearsals-ack

#41841 HCO: add tests for the new branch, release-1.10
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-1.10.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-1.10-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#41864 Add default assignee and priority for Quarkus Jiras
  ci-operator/config/quarkus-qe/quarkus-openshift-interop/quarkus-qe-quarkus-openshift-interop-main__quarkus-ocp4.14-lp-interop.yaml
Labels: lgtm, approved, rehearsals-ack

#41865 Make kuttl jobs voting
  ci-operator/config/openstack-k8s-operators/openstack-operator/openstack-k8s-operators-openstack-operator-main.yaml
  ci-operator/jobs/openstack-k8s-operators/openstack-operator/openstack-k8s-operators-openstack-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#41870 Update grafana loki cpu/memory requests/limits
  clusters/app.ci/grafana-loki/admin_grafana.yaml
Labels: lgtm, approved, rehearsals-ack

#41698 chore: bump ROSA golang v1.20
  ci-operator/config/openshift/rosa/openshift-rosa-master.yaml
  ci-operator/config/openshift/rosa/openshift-rosa-master__images.yaml
Labels: lgtm, approved, rehearsals-ack

#41832 Updating multiarch GA'd release periodic timings
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.10-upgrade-from-nightly-4.9.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.10.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.11-upgrade-from-nightly-4.10.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.11.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.12-upgrade-from-nightly-4.11.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.12.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.13-upgrade-from-nightly-4.12.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.13.yaml
  ci-operator/jobs/openshift/multiarch/openshift-multiarch-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#41875 Revert "W/A for CRI-O permissions issue writing to block devices (#41805)
  ci-operator/step-registry/hypershift/kubevirt/install/hypershift-kubevirt-install-commands.sh
Labels: lgtm, approved, rehearsals-ack

#41880 ci-chat-bot: fix runtime dir error
  clusters/app.ci/ci-chat-bot/ci-chat-bot.yaml
Labels: lgtm, approved, rehearsals-ack

#41640 Onboard ACM - allow version of spoke cluster to be changed via env var
  ci-operator/config/stolostron/acmqe-autotest/stolostron-acmqe-autotest-main__acm-ocp4.14-lp-interop.yaml
  ci-operator/jobs/stolostron/acmqe-autotest/stolostron-acmqe-autotest-main-periodics.yaml
  ci-operator/step-registry/acm/ipi/aws/acm-ipi-aws-workflow.yaml
  ci-operator/step-registry/acm/tests/clc-create/acm-tests-clc-create-commands.sh
  ci-operator/step-registry/acm/tests/clc-create/acm-tests-clc-create-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#41876 Set TIMEOUT to 300 in kuttl test
  ci-operator/step-registry/openstack-k8s-operators/deploy/openstack-k8s-operators-deploy-commands.sh
  ci-operator/step-registry/openstack-k8s-operators/kuttl/openstack-k8s-operators-kuttl-commands.sh
Labels: lgtm, approved, rehearsals-ack

#41872 Run e2e-aws-ovn-serial with useMultiNetworkPolicy=true
  ci-operator/step-registry/openshift/e2e/aws/ovn/serial/openshift-e2e-aws-ovn-serial-workflow.yaml
  ci-operator/step-registry/ovn/conf/multi-network-policy-manifest/OWNERS
  ci-operator/step-registry/ovn/conf/multi-network-policy-manifest/ovn-conf-multi-network-policy-manifest-commands.sh
  ci-operator/step-registry/ovn/conf/multi-network-policy-manifest/ovn-conf-multi-network-policy-manifest-ref.metadata.json
  ci-operator/step-registry/ovn/conf/multi-network-policy-manifest/ovn-conf-multi-network-policy-manifest-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#41697 Updates to ROSA ingress-testing
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa-4.12-nightly.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa-4.13-nightly.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-periodics.yaml
  ci-operator/step-registry/openshift-qe/ingress-perf/openshift-qe-ingress-perf-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#41854 post-installation check for Single-Node OpenShift cluster
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.14.yaml
  ci-operator/step-registry/cucushift/installer/check/sno/OWNERS
  ci-operator/step-registry/cucushift/installer/check/sno/cucushift-installer-check-sno-commands.sh
  ci-operator/step-registry/cucushift/installer/check/sno/cucushift-installer-check-sno-ref.metadata.json
  ci-operator/step-registry/cucushift/installer/check/sno/cucushift-installer-check-sno-ref.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/sno/provision/cucushift-installer-rehearse-gcp-ipi-sno-provision-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#41881 Add CodeFlare-sdk repo
  ci-operator/config/project-codeflare/codeflare-operator/OWNERS
  ci-operator/config/project-codeflare/codeflare-operator/project-codeflare-codeflare-operator-main.yaml
  ci-operator/config/project-codeflare/instascale/OWNERS
  ci-operator/config/project-codeflare/instascale/project-codeflare-instascale-main.yaml
  ci-operator/config/project-codeflare/multi-cluster-app-dispatcher/project-codeflare-multi-cluster-app-dispatcher-main.yaml
  ci-operator/jobs/project-codeflare/codeflare-operator/project-codeflare-codeflare-operator-main-presubmits.yaml
  ci-operator/jobs/project-codeflare/instascale/project-codeflare-instascale-main-presubmits.yaml
  ci-operator/jobs/project-codeflare/multi-cluster-app-dispatcher/project-codeflare-multi-cluster-app-dispatcher-main-presubmits.yaml
  core-services/prow/02_config/project-codeflare/codeflare-sdk/OWNERS
  core-services/prow/02_config/project-codeflare/codeflare-sdk/_pluginconfig.yaml
  core-services/prow/02_config/project-codeflare/codeflare-sdk/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#41746 AGENT-621: CI test for unconfigured ignition and config image
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#41860 ROX-17337: enable 4.13 cluster pool for PRs
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-13.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies__ocp-4-13.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-presubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-nightlies-postsubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#41855 HCO: bump version to 1.11.0
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-main.yaml
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-main__okd.yaml
Labels: lgtm, approved, rehearsals-ack

#41514 Onboard janus-idp/showcase-e2e repository
  ci-operator/config/janus-idp/showcase-e2e/OWNERS
  ci-operator/config/janus-idp/showcase-e2e/janus-idp-showcase-e2e-main__v4.13.yaml
  ci-operator/jobs/janus-idp/showcase-e2e/OWNERS
  ci-operator/jobs/janus-idp/showcase-e2e/janus-idp-showcase-e2e-main-presubmits.yaml
  core-services/prow/02_config/janus-idp/showcase-e2e/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#41590 Add chaos cluster profile
  core-services/ci-secret-bootstrap/_config.yaml
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: lgtm, approved, rehearsals-ack

#41884 Add upgrade tests for stable 4.13 to EC 4.14 for ARM and multi
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-ec-4.14-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-ec-4.14-upgrade-from-stable-4.13.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#41895 bump golang for ci jobs
  ci-operator/config/3scale/3scale-operator/3scale-3scale-operator-3scale-2.12-candidate.yaml
  ci-operator/config/3scale/3scale-operator/3scale-3scale-operator-3scale-2.12-stable.yaml
Labels: lgtm, approved, rehearsals-ack

#41877 NO-ISSUE: Create temporary 4.14 ODF and CNV jobs
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#41812 parameters for rhcs-terraform-provider source and version
  ci-operator/config/terraform-redhat/terraform-provider-rhcs/terraform-redhat-terraform-provider-rhcs-main.yaml
  ci-operator/step-registry/rosa/terraform/e2e/setup/rosa-terraform-e2e-setup-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#41901 Add verify step and bump to oc 4.14
  ci-operator/config/openshift/rosa/openshift-rosa-master__images.yaml
Labels: lgtm, approved, rehearsals-ack

#41908 Removes tests for Ceph storage plugin from Openshift console
  ci-operator/config/openshift/console/openshift-console-master.yaml
  ci-operator/jobs/openshift/console/openshift-console-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#41900 KMM: Move to a more recent golangci-lint
  ci-operator/config/rh-ecosystem-edge/kernel-module-management/rh-ecosystem-edge-kernel-module-management-main.yaml
Labels: lgtm, approved, rehearsals-ack

#41422 MON-3295: add openshift/prometheus-promu config
  ci-operator/config/openshift/prometheus-promu/OWNERS
  ci-operator/config/openshift/prometheus-promu/openshift-prometheus-promu-master.yaml
  ci-operator/jobs/openshift/prometheus-promu/OWNERS
  ci-operator/jobs/openshift/prometheus-promu/openshift-prometheus-promu-master-presubmits.yaml
  core-services/prow/02_config/openshift/prometheus-promu/_pluginconfig.yaml
  core-services/prow/02_config/openshift/prometheus-promu/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#41916 Remove some hard coded resource names from deploy step script
  ci-operator/step-registry/openstack-k8s-operators/deploy/openstack-k8s-operators-deploy-commands.sh
Labels: lgtm, approved, rehearsals-ack

#41917 Remove old vars used in Ceph deploy
  ci-operator/step-registry/openstack-k8s-operators/deploy/openstack-k8s-operators-deploy-commands.sh
  ci-operator/step-registry/openstack-k8s-operators/kuttl/openstack-k8s-operators-kuttl-commands.sh
Labels: lgtm, approved, rehearsals-ack

#41863 Update skip list for neutron/ovn operators
  ci-operator/jobs/openstack-k8s-operators/neutron-operator/openstack-k8s-operators-neutron-operator-main-presubmits.yaml
  ci-operator/jobs/openstack-k8s-operators/ovn-operator/openstack-k8s-operators-ovn-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#41882 Remove dsp builds and tests.
  ci-operator/config/opendatahub-io/data-science-pipelines-operator/OWNERS
  ci-operator/config/opendatahub-io/data-science-pipelines-operator/opendatahub-io-data-science-pipelines-operator-main.yaml
  ci-operator/config/opendatahub-io/data-science-pipelines/OWNERS
  ci-operator/config/opendatahub-io/data-science-pipelines/opendatahub-io-data-science-pipelines-master.yaml
  ci-operator/jobs/opendatahub-io/data-science-pipelines-operator/opendatahub-io-data-science-pipelines-operator-main-postsubmits.yaml
  ci-operator/jobs/opendatahub-io/data-science-pipelines-operator/opendatahub-io-data-science-pipelines-operator-main-presubmits.yaml
  ci-operator/jobs/opendatahub-io/data-science-pipelines/opendatahub-io-data-science-pipelines-master-postsubmits.yaml
  ci-operator/jobs/opendatahub-io/data-science-pipelines/opendatahub-io-data-science-pipelines-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#41914 W/A for CNV inability to write to block devices
  ci-operator/step-registry/hypershift/kubevirt/conformance/hypershift-kubevirt-conformance-workflow.yaml
  ci-operator/step-registry/hypershift/kubevirt/set-crio-permissions/OWNERS
  ci-operator/step-registry/hypershift/kubevirt/set-crio-permissions/hypershift-kubevirt-set-crio-permissions-commands.sh
  ci-operator/step-registry/hypershift/kubevirt/set-crio-permissions/hypershift-kubevirt-set-crio-permissions-ref.metadata.json
  ci-operator/step-registry/hypershift/kubevirt/set-crio-permissions/hypershift-kubevirt-set-crio-permissions-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#41843 Refine keyword position for disabled jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-devpreview.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/tools/generate-cron-entry.sh
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#41927 Mirror boilerplate:image-v3.0.4
  clusters/app.ci/supplemental-ci-images/boilerplate/boilerplate.yaml
Labels: lgtm, approved, rehearsals-ack

#41873 Add openshift-ci for TGIS release rhods-1.31
  ci-operator/config/red-hat-data-services/text-generation-inference/OWNERS
  ci-operator/config/red-hat-data-services/text-generation-inference/red-hat-data-services-text-generation-inference-rhods-1.31.yaml
  ci-operator/jobs/red-hat-data-services/text-generation-inference/OWNERS
  ci-operator/jobs/red-hat-data-services/text-generation-inference/red-hat-data-services-text-generation-inference-rhods-1.31-periodics.yaml
  ci-operator/jobs/red-hat-data-services/text-generation-inference/red-hat-data-services-text-generation-inference-rhods-1.31-postsubmits.yaml
  ci-operator/jobs/red-hat-data-services/text-generation-inference/red-hat-data-services-text-generation-inference-rhods-1.31-presubmits.yaml
  core-services/prow/02_config/_plugins.yaml
  core-services/prow/02_config/red-hat-data-services/text-generation-inference/OWNERS
  core-services/prow/02_config/red-hat-data-services/text-generation-inference/_pluginconfig.yaml
  core-services/prow/02_config/red-hat-data-services/text-generation-inference/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#41929 update cccmo unit test to request 100m cpu
  ci-operator/config/openshift/cluster-cloud-controller-manager-operator/openshift-cluster-cloud-controller-manager-operator-master.yaml
  ci-operator/jobs/openshift/cluster-cloud-controller-manager-operator/openshift-cluster-cloud-controller-manager-operator-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#41507 Adding medium scale
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.14.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-periodics.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-presubmits.yaml
  ci-operator/step-registry/gather/extra/gather-extra-ref.yaml
  ci-operator/step-registry/gather/must-gather/gather-must-gather-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#41738 Jv rox 18537 switch e2e tests in stackrox to core bpf switch to core bpf
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-10.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-13.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies__ocp-4-10.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies__ocp-4-13.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-x.y.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-x.y__ocp-4-10.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-x.y__ocp-4-13.yaml
  ci-operator/config/stackrox/stackrox/summary.html
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-postsubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-presubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-nightlies-postsubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-x.y-postsubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-x.y-presubmits.yaml
Labels: do-not-merge/hold, lgtm, approved, rehearsals-ack

#41940 OADP-1.2(ocp 4.12): Add e2e tests for 1.2 branch
  ci-operator/config/openshift/oadp-operator/openshift-oadp-operator-oadp-1.2__4.12.yaml
  ci-operator/jobs/openshift/oadp-operator/openshift-oadp-operator-oadp-1.2-periodics.yaml
  ci-operator/jobs/openshift/oadp-operator/openshift-oadp-operator-oadp-1.2-postsubmits.yaml
  ci-operator/jobs/openshift/oadp-operator/openshift-oadp-operator-oadp-1.2-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#41893 Add more testconfigs for multi arch
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#41942 Unify the usage of devpreview builds to ec
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-ec.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly-4.14-upgrade-from-ec-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-ec.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly-4.14-upgrade-from-ec-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-ec-4.14-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-ec.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-nightly-4.14-upgrade-from-ec-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#41924 add TP for CEO e2e tests
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-master.yaml
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.14.yaml
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.15.yaml
Labels: lgtm, approved, rehearsals-ack

#41946 Add prow config for ODH Distributed Workloads repo
  core-services/prow/02_config/opendatahub-io/distributed-workloads/OWNERS
  core-services/prow/02_config/opendatahub-io/distributed-workloads/_pluginconfig.yaml
  core-services/prow/02_config/opendatahub-io/distributed-workloads/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#41947 Setup openshift-ci for caikit-tgis-serving
  ci-operator/config/red-hat-data-services/caikit-tgis-serving/OWNERS
  ci-operator/config/red-hat-data-services/caikit-tgis-serving/red-hat-data-services-caikit-tgis-serving-rhods-1.31.yaml
  ci-operator/jobs/red-hat-data-services/caikit-tgis-serving/OWNERS
  ci-operator/jobs/red-hat-data-services/caikit-tgis-serving/red-hat-data-services-caikit-tgis-serving-rhods-1.31-periodics.yaml
  ci-operator/jobs/red-hat-data-services/caikit-tgis-serving/red-hat-data-services-caikit-tgis-serving-rhods-1.31-postsubmits.yaml
  ci-operator/jobs/red-hat-data-services/caikit-tgis-serving/red-hat-data-services-caikit-tgis-serving-rhods-1.31-presubmits.yaml
  core-services/prow/02_config/_plugins.yaml
  core-services/prow/02_config/red-hat-data-services/caikit-tgis-serving/OWNERS
  core-services/prow/02_config/red-hat-data-services/caikit-tgis-serving/_pluginconfig.yaml
  core-services/prow/02_config/red-hat-data-services/caikit-tgis-serving/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#41934 update CCCMO unit tests to use 200m cpu request
  ci-operator/config/openshift/cluster-cloud-controller-manager-operator/openshift-cluster-cloud-controller-manager-operator-master.yaml
  ci-operator/config/openshift/cluster-cloud-controller-manager-operator/openshift-cluster-cloud-controller-manager-operator-release-4.13.yaml
  ci-operator/config/openshift/cluster-cloud-controller-manager-operator/openshift-cluster-cloud-controller-manager-operator-release-4.14.yaml
  ci-operator/config/openshift/cluster-cloud-controller-manager-operator/openshift-cluster-cloud-controller-manager-operator-release-4.15.yaml
  ci-operator/jobs/openshift/cluster-cloud-controller-manager-operator/openshift-cluster-cloud-controller-manager-operator-release-4.13-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#41874 Allow users to Tag the clusters
  ci-operator/step-registry/rosa/sts/cluster/provision/rosa-sts-cluster-provision-commands.sh
  ci-operator/step-registry/rosa/sts/cluster/provision/rosa-sts-cluster-provision-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#41954 Run UI fullfunction tests on selected profiles
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
  ci-operator/step-registry/cucushift/e2e/ui/OWNERS
  ci-operator/step-registry/cucushift/e2e/ui/cucushift-e2e-ui-commands.sh
  ci-operator/step-registry/cucushift/e2e/ui/cucushift-e2e-ui-ref.metadata.json
  ci-operator/step-registry/cucushift/e2e/ui/cucushift-e2e-ui-ref.yaml
  ci-operator/step-registry/openshift/e2e/test/qe/ui/OWNERS
  ci-operator/step-registry/openshift/e2e/test/qe/ui/openshift-e2e-test-qe-ui-chain.metadata.json
  ci-operator/step-registry/openshift/e2e/test/qe/ui/openshift-e2e-test-qe-ui-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#41926 fix: bump rosa to use base image rhel-8-golang-1.20
  ci-operator/config/openshift/rosa/openshift-rosa-master.yaml
  ci-operator/config/openshift/rosa/openshift-rosa-master__images.yaml
Labels: lgtm, approved, rehearsals-ack

#41952 skip arm64 for fips test
  ci-operator/step-registry/fips-check/fips-or-die/fips-check-fips-or-die-commands.sh
Labels: lgtm, approved, rehearsals-ack

#41944 swift-operator: Requre swift-operator-build-deploy job
  ci-operator/config/openstack-k8s-operators/swift-operator/openstack-k8s-operators-swift-operator-main.yaml
  ci-operator/jobs/openstack-k8s-operators/swift-operator/openstack-k8s-operators-swift-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#41958 Fix test filter for alibaba cloud related profiles
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-ec.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
Labels: lgtm, approved, rehearsals-ack

#41937 [continuous-release-jobs] Disable impacts verification
  ci-operator/config/openshift/continuous-release-jobs/openshift-continuous-release-jobs-master.yaml
  ci-operator/jobs/openshift/continuous-release-jobs/openshift-continuous-release-jobs-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#41966 tide: skip unknown targets in operator-framework
  core-services/prow/02_config/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#41964 USHIFT-1504: give rebase bot permission to add special labels
  core-services/prow/02_config/openshift/microshift/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#41955 ROX-17337/fix: enable auto updater for image set in stackrox OCP 4.13 cluster pool
  clusters/hive/pools/stackrox/ocp-4.13_clusterpool.yaml
Labels: lgtm, approved, rehearsals-ack

#41933 enabled for ibmcloud-ipi-p3-f28-destructive
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
Labels: lgtm, approved, rehearsals-ack

#41971 Bumping govulncheck to go1.21rc4
  clusters/app.ci/supplemental-ci-images/crt/govulncheck.yaml
Labels: lgtm, approved, rehearsals-ack

#41970 Set timeout for osde2e-test step
  ci-operator/step-registry/osde2e/test/osde2e-test-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#41957 Setup openshift-ci for kserve release branch
  ci-operator/config/red-hat-data-services/kserve/OWNERS
  ci-operator/config/red-hat-data-services/kserve/red-hat-data-services-kserve-rhods-1.31.yaml
  ci-operator/jobs/red-hat-data-services/kserve/OWNERS
  ci-operator/jobs/red-hat-data-services/kserve/red-hat-data-services-kserve-rhods-1.31-postsubmits.yaml
  ci-operator/jobs/red-hat-data-services/kserve/red-hat-data-services-kserve-rhods-1.31-presubmits.yaml
  core-services/prow/02_config/_plugins.yaml
  core-services/prow/02_config/red-hat-data-services/kserve/OWNERS
  core-services/prow/02_config/red-hat-data-services/kserve/_pluginconfig.yaml
  core-services/prow/02_config/red-hat-data-services/kserve/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#40389 Enable full parallel conformance test for Hypershift/KubeVirt platform
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.13__periodics.yaml
  ci-operator/step-registry/hypershift/OWNERS
  ci-operator/step-registry/hypershift/aws/conformance-proxy/hypershift-aws-conformance-proxy-workflow.metadata.json
  ci-operator/step-registry/hypershift/aws/conformance/hypershift-aws-conformance-workflow.metadata.json
  ci-operator/step-registry/hypershift/aws/create/hypershift-aws-create-chain.metadata.json
  ci-operator/step-registry/hypershift/aws/destroy-nested-management-cluster/hypershift-aws-destroy-nested-management-cluster-chain.metadata.json
  ci-operator/step-registry/hypershift/aws/destroy/hypershift-aws-destroy-chain.metadata.json
  ci-operator/step-registry/hypershift/aws/setup-nested-management-cluster/hypershift-aws-setup-nested-management-cluster-chain.metadata.json
  ci-operator/step-registry/hypershift/azure/conformance/hypershift-azure-conformance-workflow.metadata.json
  ci-operator/step-registry/hypershift/azure/create/hypershift-azure-create-chain.metadata.json
  ci-operator/step-registry/hypershift/azure/destroy/hypershift-azure-destroy-chain.metadata.json
  ci-operator/step-registry/hypershift/conformance/hypershift-conformance-chain.metadata.json
  ci-operator/step-registry/hypershift/conformance/hypershift-conformance-chain.yaml
  ci-operator/step-registry/hypershift/debug/hypershift-debug-ref.metadata.json
  ci-operator/step-registry/hypershift/dump/hypershift-dump-chain.metadata.json
  ci-operator/step-registry/hypershift/install/hypershift-install-ref.metadata.json
Labels: lgtm, approved, rehearsals-ack

#41978 Add build for kserve-queue-proxy in RHODS
  ci-operator/config/red-hat-data-services/kserve/red-hat-data-services-kserve-rhods-1.31.yaml
  ci-operator/jobs/red-hat-data-services/kserve/red-hat-data-services-kserve-rhods-1.31-postsubmits.yaml
  ci-operator/jobs/red-hat-data-services/kserve/red-hat-data-services-kserve-rhods-1.31-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#41973 NO-ISSUE: Disable microshift conformance reduced jobs
  ci-operator/config/openshift/microshift/openshift-microshift-main.yaml
  ci-operator/jobs/openshift/microshift/openshift-microshift-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#39941 Hive/master: Use latest HCP for e2e-pool
  ci-operator/config/openshift/hive/openshift-hive-master.yaml
  ci-operator/jobs/openshift/hive/openshift-hive-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#41974 `dptp-controller-manager`: increase memory request
  clusters/app.ci/assets/dptp-controller-manager.yaml
Labels: lgtm, approved, rehearsals-ack

#41965 Migrate handcrafted osde2e addon job to multi stage job
  ci-operator/config/openshift/osde2e/openshift-osde2e-main__addon.yaml
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
  core-services/testgrid-config-generator/_allow-list.yaml
Labels: lgtm, approved, rehearsals-ack

#41977 Creating data-path workflow
  ci-operator/step-registry/openshift-qe/data-path-tests/OWNERS
  ci-operator/step-registry/openshift-qe/data-path-tests/openshift-qe-data-path-tests-chain.metadata.json
  ci-operator/step-registry/openshift-qe/data-path-tests/openshift-qe-data-path-tests-chain.yaml
  ci-operator/step-registry/openshift-qe/data-path-tests/openshift-qe-data-path-tests-workflow.metadata.json
  ci-operator/step-registry/openshift-qe/data-path-tests/openshift-qe-data-path-tests-workflow.yaml
  ci-operator/step-registry/openshift-qe/ingress-perf/openshift-qe-ingress-perf-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#41804 OCPQE-16156 Wait mc to be applied on all nodes when there are multiple mcs at the…
  ci-operator/step-registry/cucushift/chainupgrade/toimage/cucushift-chainupgrade-toimage-commands.sh
  ci-operator/step-registry/cucushift/upgrade/toimage/cucushift-upgrade-toimage-commands.sh
Labels: lgtm, approved, rehearsals-ack

#42001 Update _pluginconfig.yaml
  core-services/prow/02_config/red-hat-storage/_pluginconfig.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#42000 Fix TGIS build to push images in correct repo.
  ci-operator/config/red-hat-data-services/caikit-tgis-serving/red-hat-data-services-caikit-tgis-serving-rhods-1.31.yaml
  ci-operator/config/red-hat-data-services/kserve/red-hat-data-services-kserve-rhods-1.31.yaml
  ci-operator/config/red-hat-data-services/text-generation-inference/red-hat-data-services-text-generation-inference-rhods-1.31.yaml
  ci-operator/jobs/red-hat-data-services/caikit-tgis-serving/red-hat-data-services-caikit-tgis-serving-rhods-1.31-postsubmits.yaml
  ci-operator/jobs/red-hat-data-services/caikit-tgis-serving/red-hat-data-services-caikit-tgis-serving-rhods-1.31-presubmits.yaml
  ci-operator/jobs/red-hat-data-services/kserve/red-hat-data-services-kserve-rhods-1.31-periodics.yaml
  ci-operator/jobs/red-hat-data-services/kserve/red-hat-data-services-kserve-rhods-1.31-postsubmits.yaml
  ci-operator/jobs/red-hat-data-services/kserve/red-hat-data-services-kserve-rhods-1.31-presubmits.yaml
  ci-operator/jobs/red-hat-data-services/text-generation-inference/red-hat-data-services-text-generation-inference-rhods-1.31-postsubmits.yaml
  ci-operator/jobs/red-hat-data-services/text-generation-inference/red-hat-data-services-text-generation-inference-rhods-1.31-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#41844 add checkpoint for cluster capabilities
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.14.yaml
  ci-operator/step-registry/cucushift/installer/check/capability/OWNERS
  ci-operator/step-registry/cucushift/installer/check/capability/cucushift-installer-check-capability-commands.sh
  ci-operator/step-registry/cucushift/installer/check/capability/cucushift-installer-check-capability-ref.metadata.json
  ci-operator/step-registry/cucushift/installer/check/capability/cucushift-installer-check-capability-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#41803 Revert back to the original cron job schedule for 4.14 ppc64le
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__ppc64le-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#42003 Skip powervs when batch updating cron entries
  ci-operator/config/openshift/openshift-tests-private/tools/generate-cron-entry.sh
Labels: lgtm, approved, rehearsals-ack

#42006 send slack message for the job rosa-aws-sts-rosacli-e2e-f3
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#42004 append tags and wait for api.url
  ci-operator/step-registry/osd-ccs/conf/idp/htpasswd/osd-ccs-conf-idp-htpasswd-commands.sh
  ci-operator/step-registry/rosa/aws/non-sts/rosa-aws-non-sts-workflow.yaml
  ci-operator/step-registry/rosa/aws/sts/proxy/rosa-aws-sts-proxy-workflow.yaml
  ci-operator/step-registry/rosa/cluster/provision/rosa-cluster-provision-commands.sh
  ci-operator/step-registry/rosa/cluster/provision/rosa-cluster-provision-ref.yaml
  ci-operator/step-registry/rosa/conf/idp/htpasswd/rosa-conf-idp-htpasswd-commands.sh
Labels: lgtm, approved, rehearsals-ack

#42008 Sync Serverless CI
  ci-operator/config/openshift-knative/serving/openshift-knative-serving-release-next__411.yaml
  ci-operator/jobs/openshift-knative/serving/openshift-knative-serving-release-next-periodics.yaml
  ci-operator/jobs/openshift-knative/serving/openshift-knative-serving-release-next-postsubmits.yaml
  ci-operator/jobs/openshift-knative/serving/openshift-knative-serving-release-next-presubmits.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#41655 STOR-1315: Add e2e workflow for Secrets Store CSI Driver
  ci-operator/config/openshift/secrets-store-csi-driver-operator/openshift-secrets-store-csi-driver-operator-main.yaml
  ci-operator/jobs/openshift/secrets-store-csi-driver-operator/openshift-secrets-store-csi-driver-operator-main-presubmits.yaml
  ci-operator/step-registry/openshift/e2e/azure/csi/secrets-store/OWNERS
  ci-operator/step-registry/openshift/e2e/azure/csi/secrets-store/openshift-e2e-azure-csi-secrets-store-workflow.metadata.json
  ci-operator/step-registry/openshift/e2e/azure/csi/secrets-store/openshift-e2e-azure-csi-secrets-store-workflow.yaml
  ci-operator/step-registry/storage/create/csi-secrets-store/OWNERS
  ci-operator/step-registry/storage/create/csi-secrets-store/storage-create-csi-secrets-store-commands.sh
  ci-operator/step-registry/storage/create/csi-secrets-store/storage-create-csi-secrets-store-ref.metadata.json
  ci-operator/step-registry/storage/create/csi-secrets-store/storage-create-csi-secrets-store-ref.yaml
  ci-operator/step-registry/storage/destroy/csi-secrets-store/OWNERS
  ci-operator/step-registry/storage/destroy/csi-secrets-store/storage-destroy-csi-secrets-store-commands.sh
  ci-operator/step-registry/storage/destroy/csi-secrets-store/storage-destroy-csi-secrets-store-ref.metadata.json
  ci-operator/step-registry/storage/destroy/csi-secrets-store/storage-destroy-csi-secrets-store-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#41823 USHIFT-1459: Add cncf periodic job
  ci-operator/config/openshift/microshift/openshift-microshift-main.yaml
  ci-operator/jobs/openshift/microshift/openshift-microshift-main-periodics.yaml
  ci-operator/jobs/openshift/microshift/openshift-microshift-main-presubmits.yaml
  ci-operator/step-registry/openshift/microshift/e2e/metal-tests/openshift-microshift-e2e-metal-tests-commands.sh
  ci-operator/step-registry/openshift/microshift/infra/iso-boot/openshift-microshift-infra-iso-boot-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#41959 Rename Validated Patterns organization
  ci-operator/config/validatedpatterns/docs/OWNERS
  ci-operator/config/validatedpatterns/docs/validatedpatterns-docs-main.yaml
  ci-operator/config/validatedpatterns/patterns-operator/OWNERS
  ci-operator/config/validatedpatterns/patterns-operator/validatedpatterns-patterns-operator-main.yaml
  ci-operator/config/validatedpatterns/patterns-operator/validatedpatterns-patterns-operator-release-4.14.yaml
  ci-operator/config/validatedpatterns/patterns-operator/validatedpatterns-patterns-operator-release-4.15.yaml
  ci-operator/jobs/validatedpatterns/docs/OWNERS
  ci-operator/jobs/validatedpatterns/docs/validatedpatterns-docs-main-presubmits.yaml
  ci-operator/jobs/validatedpatterns/patterns-operator/OWNERS
  ci-operator/jobs/validatedpatterns/patterns-operator/validatedpatterns-patterns-operator-main-presubmits.yaml
  ci-operator/jobs/validatedpatterns/patterns-operator/validatedpatterns-patterns-operator-release-4.14-presubmits.yaml
  ci-operator/jobs/validatedpatterns/patterns-operator/validatedpatterns-patterns-operator-release-4.15-presubmits.yaml
  core-services/prow/02_config/validatedpatterns/docs/_pluginconfig.yaml
  core-services/prow/02_config/validatedpatterns/docs/_prowconfig.yaml
  core-services/prow/02_config/validatedpatterns/patterns-operator/OWNERS
  core-services/prow/02_config/validatedpatterns/patterns-operator/_pluginconfig.yaml
  core-services/prow/02_config/validatedpatterns/patterns-operator/_prowconfig.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#41993 GitOps Operator | Update CI version to 4.14
  ci-operator/config/redhat-developer/gitops-operator/redhat-developer-gitops-operator-master__v4.14.yaml
  ci-operator/config/redhat-developer/gitops-operator/redhat-developer-gitops-operator-v1.8__v4.14.yaml
  ci-operator/config/redhat-developer/gitops-operator/redhat-developer-gitops-operator-v1.9__v4.14.yaml
  ci-operator/jobs/redhat-developer/gitops-operator/redhat-developer-gitops-operator-master-presubmits.yaml
  ci-operator/jobs/redhat-developer/gitops-operator/redhat-developer-gitops-operator-v1.8-presubmits.yaml
  ci-operator/jobs/redhat-developer/gitops-operator/redhat-developer-gitops-operator-v1.9-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#41981 Build ci-images-mirror
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
Labels: lgtm, approved, rehearsals-ack

#42009 `arm01`: ci-operator build framework
  clusters/build-clusters/arm01/ci-tools/000_is_ci-tools-build-root-arm64.yaml
  clusters/build-clusters/arm01/ci-tools/001_is_ci-tools-bin-arm64.yaml
  clusters/build-clusters/arm01/ci-tools/002_is_ci-operator-arm64.yaml
  clusters/build-clusters/arm01/ci-tools/100_bc_ci-tools-build-root-1.19-arm64.yaml
  clusters/build-clusters/arm01/ci-tools/101_bc_ci-tools-bin-arm64.yaml
  clusters/build-clusters/arm01/ci-tools/102_bc_ci-operator-arm64.yaml
Labels: lgtm, approved, rehearsals-ack

#42018 Set release image latest environment variable for osde2e-test ref
  ci-operator/step-registry/osde2e/test/osde2e-test-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#42020 Enabling the 4.11 and 4.12 upgrade rollback jobs
  core-services/release-controller/_releases/priv/release-ocp-4.11.json
  core-services/release-controller/_releases/priv/release-ocp-4.12.json
  core-services/release-controller/_releases/release-ocp-4.11.json
  core-services/release-controller/_releases/release-ocp-4.12.json
Labels: lgtm, approved, rehearsals-ack

#42030 update the Dockerfile referenced by the CI build
  ci-operator/config/openshift/linuxptp-daemon/openshift-linuxptp-daemon-master.yaml
  ci-operator/config/openshift/linuxptp-daemon/openshift-linuxptp-daemon-release-4.14.yaml
  ci-operator/config/openshift/linuxptp-daemon/openshift-linuxptp-daemon-release-4.15.yaml
Labels: lgtm, approved, rehearsals-ack

#42025 Fix issue DPTP-3312 Add oc and hypershift CLI
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
Labels: lgtm, approved, rehearsals-ack

#42028 Fix agent ha dualstack workflow
  ci-operator/step-registry/agent/e2e/ha/dualstack/agent-e2e-ha-dualstack-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#41962 MicroShift E2E: Custom link to log.html
  ci-operator/step-registry/openshift/microshift/e2e/microshift-tests-aws/openshift-microshift-e2e-microshift-tests-aws-commands.sh
Labels: lgtm, approved, rehearsals-ack

#42034 Remove sonar jobs for ACM Thanos
  ci-operator/config/stolostron/thanos/stolostron-thanos-release-2.5.yaml
  ci-operator/config/stolostron/thanos/stolostron-thanos-release-2.6.yaml
  ci-operator/config/stolostron/thanos/stolostron-thanos-release-2.7.yaml
  ci-operator/config/stolostron/thanos/stolostron-thanos-release-2.8.yaml
  ci-operator/config/stolostron/thanos/stolostron-thanos-release-2.9.yaml
  ci-operator/jobs/stolostron/thanos/stolostron-thanos-release-2.5-postsubmits.yaml
  ci-operator/jobs/stolostron/thanos/stolostron-thanos-release-2.5-presubmits.yaml
  ci-operator/jobs/stolostron/thanos/stolostron-thanos-release-2.6-postsubmits.yaml
  ci-operator/jobs/stolostron/thanos/stolostron-thanos-release-2.6-presubmits.yaml
  ci-operator/jobs/stolostron/thanos/stolostron-thanos-release-2.7-postsubmits.yaml
  ci-operator/jobs/stolostron/thanos/stolostron-thanos-release-2.7-presubmits.yaml
  ci-operator/jobs/stolostron/thanos/stolostron-thanos-release-2.8-postsubmits.yaml
  ci-operator/jobs/stolostron/thanos/stolostron-thanos-release-2.8-presubmits.yaml
  ci-operator/jobs/stolostron/thanos/stolostron-thanos-release-2.9-postsubmits.yaml
  ci-operator/jobs/stolostron/thanos/stolostron-thanos-release-2.9-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#41941 OADP-1.2: Add e2e tests on ocp-4.12
  ci-operator/config/openshift/oadp-operator/openshift-oadp-operator-oadp-1.2__4.12.yaml
  ci-operator/jobs/openshift/oadp-operator/openshift-oadp-operator-oadp-1.2-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#42036 hypershift: extend e2e timeout to 2h
  ci-operator/step-registry/hypershift/aws/run-e2e/external/hypershift-aws-run-e2e-external-chain.yaml
  ci-operator/step-registry/hypershift/aws/run-e2e/hypershift-aws-run-e2e-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#42017 USHIFT-1504: fix the name of the bot account
  core-services/prow/02_config/openshift/microshift/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#42002 hypershift-kubevirt: enable qe-catalogsource on hostedcluster
  ci-operator/step-registry/cucushift/installer/rehearse/baremetalds/ipi/ovn/ipv4/kubevirt/hypershift/provision/cucushift-installer-rehearse-baremetalds-ipi-ovn-ipv4-kubevirt-hypershift-provision-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#41792 MGMT-15397: Add Nutanix post installation step to CI
  ci-operator/step-registry/assisted/nutanix/assisted-nutanix-workflow.yaml
  ci-operator/step-registry/assisted/nutanix/postinstall/assisted-nutanix-postinstall-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#42024 Enable a [sig-kubevirt] conformance test case: infra pod --> guest pod via NodePort
  ci-operator/step-registry/hypershift/conformance/hypershift-conformance-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#42044 openstack-k8s: run make bundle after operator build completes
  ci-operator/step-registry/openstack-k8s-operators/build/openstack-k8s-operators-build-commands.sh
Labels: lgtm, approved, rehearsals-ack

#42042 telco5g: Don't skip tests because of bugs
  ci-operator/step-registry/telco5g/cnf/tests/telco5g-cnf-tests-commands.sh
Labels: lgtm, approved, rehearsals-ack

#42022 Extract oc client from the latest 4.10 release image for OCP 4.6 test
  ci-operator/step-registry/openshift/upgrade/qe/test/cert-rotation/openshift-upgrade-qe-test-cert-rotation-commands.sh
Labels: lgtm, approved, rehearsals-ack

#41835 Bump the oldest-supported-z-rollback to 4.11.0
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.11.yaml
Labels: lgtm, approved, rehearsals-ack

#41950 OCPQE-16212: Run UI smoke tests by default
  ci-operator/step-registry/cucushift/e2e/cucushift-e2e-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#41997 Update skip list for heat/horizon operator
  ci-operator/jobs/openstack-k8s-operators/heat-operator/openstack-k8s-operators-heat-operator-main-presubmits.yaml
  ci-operator/jobs/openstack-k8s-operators/horizon-operator/openstack-k8s-operators-horizon-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#42049 Fix test filter for OVN profiles
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__amd64-nightly-4.10-upgrade-from-stable-4.9.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly-4.11-upgrade-from-stable-4.10.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-stable-4.11.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-4.13-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly-4.14-upgrade-from-stable-4.13.yaml
Labels: lgtm, approved, rehearsals-ack

#42051 openstack-ansiblee-operator: Do not run build-deploy job by default
  ci-operator/jobs/openstack-k8s-operators/openstack-ansibleee-operator/openstack-k8s-operators-openstack-ansibleee-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#42013 Before-branching 4.14: Add missing multiarch jobs
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.15-upgrade-from-nightly-4.14.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.15-upgrade-from-stable-4.14.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.15.yaml
  ci-operator/jobs/openshift/multiarch/openshift-multiarch-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#42019 Remove tp_only from e2e tests and periodic tests for IO
  ci-operator/config/openshift/insights-operator/openshift-insights-operator-master.yaml
Labels: lgtm, approved, rehearsals-ack

#41999 infra-operator: Enable kuttl job
  ci-operator/config/openstack-k8s-operators/infra-operator/openstack-k8s-operators-infra-operator-main.yaml
  ci-operator/jobs/openstack-k8s-operators/infra-operator/openstack-k8s-operators-infra-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#42041 Hypershift+CNV: re-enable skiped test
  ci-operator/step-registry/hypershift/conformance/hypershift-conformance-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#41998 Update skip list for infra/mariadb/keystone operator
  ci-operator/jobs/openstack-k8s-operators/infra-operator/openstack-k8s-operators-infra-operator-main-presubmits.yaml
  ci-operator/jobs/openstack-k8s-operators/keystone-operator/openstack-k8s-operators-keystone-operator-main-presubmits.yaml
  ci-operator/jobs/openstack-k8s-operators/mariadb-operator/openstack-k8s-operators-mariadb-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#42062 hypershift: increase hypershift-aws-destroy chain timeout
  ci-operator/step-registry/hypershift/aws/destroy/hypershift-aws-destroy-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#42064 Add ART openshift-eng/ocp-build-data to prow
  core-services/prow/02_config/openshift-eng/ocp-build-data/OWNERS
  core-services/prow/02_config/openshift-eng/ocp-build-data/_pluginconfig.yaml
  core-services/prow/02_config/openshift-eng/ocp-build-data/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#42048 Mirror boilerplate:image-v3.0.5
  clusters/app.ci/supplemental-ci-images/boilerplate/boilerplate.yaml
Labels: lgtm, approved, rehearsals-ack

#41989 Revert "Update FIO pullspec for 1.3.1"
  ci-operator/config/openshift/file-integrity-operator/openshift-file-integrity-operator-master.yaml
Labels: lgtm, approved, rehearsals-ack

#42077 Update images for apiserver-network-proxy (konnectivity)
  ci-operator/config/openshift/apiserver-network-proxy/openshift-apiserver-network-proxy-master.yaml
  ci-operator/config/openshift/apiserver-network-proxy/openshift-apiserver-network-proxy-release-4.14.yaml
  ci-operator/config/openshift/apiserver-network-proxy/openshift-apiserver-network-proxy-release-4.15.yaml
Labels: lgtm, approved, rehearsals-ack

#40716 switch to using new hcp tool for hypershift/kubevirt create/destroy
  ci-operator/step-registry/hypershift/kubevirt/conformance/hypershift-kubevirt-conformance-workflow.yaml
  ci-operator/step-registry/hypershift/kubevirt/create/hypershift-kubevirt-create-chain.yaml
  ci-operator/step-registry/hypershift/kubevirt/csi-e2e/hypershift-kubevirt-csi-e2e-workflow.yaml
  ci-operator/step-registry/hypershift/kubevirt/destroy/hypershift-kubevirt-destroy-chain.yaml
  ci-operator/step-registry/hypershift/kubevirt/e2e/hypershift-kubevirt-e2e-workflow.yaml
  ci-operator/step-registry/hypershift/mce/kubevirt/conformance/hypershift-mce-kubevirt-conformance-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#42091 oko: Fix wrong test directory name
  ci-operator/jobs/openstack-k8s-operators/heat-operator/openstack-k8s-operators-heat-operator-main-presubmits.yaml
  ci-operator/jobs/openstack-k8s-operators/horizon-operator/openstack-k8s-operators-horizon-operator-main-presubmits.yaml
  ci-operator/jobs/openstack-k8s-operators/infra-operator/openstack-k8s-operators-infra-operator-main-presubmits.yaml
  ci-operator/jobs/openstack-k8s-operators/keystone-operator/openstack-k8s-operators-keystone-operator-main-presubmits.yaml
  ci-operator/jobs/openstack-k8s-operators/mariadb-operator/openstack-k8s-operators-mariadb-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#42060 Before-branching 4.14: Add missing release-controller jobs
  ci-operator/config/openshift/cluster-control-plane-machine-set-operator/openshift-cluster-control-plane-machine-set-operator-release-4.15__periodics.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.15__periodics.yaml
  ci-operator/config/openshift/osde2e/openshift-osde2e-main__nightly-4.15.yaml
  ci-operator/jobs/openshift/cluster-control-plane-machine-set-operator/openshift-cluster-control-plane-machine-set-operator-release-4.15-periodics.yaml
  ci-operator/jobs/openshift/cluster-control-plane-machine-set-operator/openshift-cluster-control-plane-machine-set-operator-release-4.15-presubmits.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.15-periodics.yaml
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#42066 Change tag name to final
  ci-operator/config/red-hat-data-services/kserve/red-hat-data-services-kserve-rhods-1.31.yaml
Labels: lgtm, approved, rehearsals-ack

#41992 OCPQE-16212: Run UI fullfunction tests on more profiles
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
  ci-operator/step-registry/cucushift/e2e/ui/cucushift-e2e-ui-commands.sh
  ci-operator/step-registry/cucushift/e2e/ui/cucushift-e2e-ui-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#42079 openstack-k8s: add .prow-ci.env support
  ci-operator/step-registry/openstack-k8s-operators/build/openstack-k8s-operators-build-commands.sh
  ci-operator/step-registry/openstack-k8s-operators/deploy/openstack-k8s-operators-deploy-commands.sh
  ci-operator/step-registry/openstack-k8s-operators/kuttl/openstack-k8s-operators-kuttl-commands.sh
  ci-operator/step-registry/openstack-k8s-operators/tempest/openstack-k8s-operators-tempest-commands.sh
Labels: lgtm, approved, rehearsals-ack

#42068 Data plane write
  ci-operator/step-registry/openshift-qe/data-path-tests/openshift-qe-data-path-tests-chain.yaml
  ci-operator/step-registry/openshift-qe/ingress-perf/openshift-qe-ingress-perf-chain.metadata.json
  ci-operator/step-registry/openshift-qe/ingress-perf/openshift-qe-ingress-perf-chain.yaml
  ci-operator/step-registry/openshift-qe/ingress-perf/openshift-qe-ingress-perf-commands.sh
  ci-operator/step-registry/openshift-qe/ingress-perf/openshift-qe-ingress-perf-ref.yaml
  ci-operator/step-registry/openshift-qe/write-perfscale-results/ingress-perf/OWNERS
  ci-operator/step-registry/openshift-qe/write-perfscale-results/ingress-perf/openshift-qe-write-perfscale-results-ingress-perf-commands.sh
  ci-operator/step-registry/openshift-qe/write-perfscale-results/ingress-perf/openshift-qe-write-perfscale-results-ingress-perf-ref.metadata.json
  ci-operator/step-registry/openshift-qe/write-perfscale-results/ingress-perf/openshift-qe-write-perfscale-results-ingress-perf-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#41857 MSI: Add RHODS-RHOAM 4.13 production scenraio
  ci-operator/config/CSPI-QE/MSI/CSPI-QE-MSI-rhods-rhoam__v4.13-production.yaml
  ci-operator/jobs/CSPI-QE/MSI/CSPI-QE-MSI-rhods-rhoam-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#42093 MGMT-14710: Change the regex for ci operator file names
  core-services/prow/02_config/_plugins.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#42015 USHIFT-1542: Add custom links to metal tests
  ci-operator/step-registry/openshift/microshift/e2e/metal-tests/openshift-microshift-e2e-metal-tests-commands.sh
  ci-operator/step-registry/openshift/microshift/infra/iso-boot/openshift-microshift-infra-iso-boot-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#41849 OCPBUGS-16889: add upi no capabilities job to CEO
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-master.yaml
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.14.yaml
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.15.yaml
  ci-operator/jobs/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.14-presubmits.yaml
  ci-operator/jobs/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.15-presubmits.yaml
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, rehearsals-ack, jira/valid-reference

#42090 Update skip list for ironic operator
  ci-operator/jobs/openstack-k8s-operators/ironic-operator/openstack-k8s-operators-ironic-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#41714 API-1617: Add test which ensures the SNO cluster can recover after being suspended/shutdown
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.14.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  ci-operator/step-registry/openshift/e2e/cert-rotation/OWNERS
  ci-operator/step-registry/openshift/e2e/cert-rotation/shutdown/OWNERS
  ci-operator/step-registry/openshift/e2e/cert-rotation/shutdown/openshift-e2e-cert-rotation-shutdown-commands.sh
  ci-operator/step-registry/openshift/e2e/cert-rotation/shutdown/openshift-e2e-cert-rotation-shutdown-ref.metadata.json
  ci-operator/step-registry/openshift/e2e/cert-rotation/shutdown/openshift-e2e-cert-rotation-shutdown-ref.yaml
  ci-operator/step-registry/openshift/e2e/cert-rotation/shutdown/openshift-e2e-cert-rotation-shutdown-workflow.metadata.json
  ci-operator/step-registry/openshift/e2e/cert-rotation/shutdown/openshift-e2e-cert-rotation-shutdown-workflow.yaml
  ci-operator/step-registry/openshift/e2e/cert-rotation/shutdown/sno/OWNERS
  ci-operator/step-registry/openshift/e2e/cert-rotation/shutdown/sno/openshift-e2e-cert-rotation-shutdown-sno-workflow.metadata.json
  ci-operator/step-registry/openshift/e2e/cert-rotation/shutdown/sno/openshift-e2e-cert-rotation-shutdown-sno-workflow.yaml
  ci-operator/step-registry/openshift/e2e/cert-rotation/suspend/OWNERS
  ci-operator/step-registry/openshift/e2e/cert-rotation/suspend/openshift-e2e-cert-rotation-suspend-commands.sh
  ci-operator/step-registry/openshift/e2e/cert-rotation/suspend/openshift-e2e-cert-rotation-suspend-ref.metadata.json
  ci-operator/step-registry/openshift/e2e/cert-rotation/suspend/openshift-e2e-cert-rotation-suspend-ref.yaml
  ci-operator/step-registry/openshift/e2e/cert-rotation/suspend/openshift-e2e-cert-rotation-suspend-workflow.metadata.json
  ci-operator/step-registry/openshift/e2e/cert-rotation/suspend/openshift-e2e-cert-rotation-suspend-workflow.yaml
  ci-operator/step-registry/openshift/e2e/cert-rotation/suspend/sno/OWNERS
  ci-operator/step-registry/openshift/e2e/cert-rotation/suspend/sno/openshift-e2e-cert-rotation-suspend-sno-workflow.metadata.json
  ci-operator/step-registry/openshift/e2e/cert-rotation/suspend/sno/openshift-e2e-cert-rotation-suspend-sno-workflow.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#42106 MSI - Fix addon-install and addon-uninstall firewatch classification
  ci-operator/config/CSPI-QE/MSI/CSPI-QE-MSI-rhods-rhoam__v4.13-production.yaml
  ci-operator/config/CSPI-QE/MSI/CSPI-QE-MSI-rhods-rhoam__v4.13.yaml
Labels: lgtm, approved, rehearsals-ack

#42111 Onboard Automated Release Tooling repos
  core-services/prow/02_config/openshift-eng/art-bot/OWNERS
  core-services/prow/02_config/openshift-eng/art-bot/_pluginconfig.yaml
  core-services/prow/02_config/openshift-eng/art-bot/_prowconfig.yaml
  core-services/prow/02_config/openshift-eng/art-config/OWNERS
  core-services/prow/02_config/openshift-eng/art-config/_pluginconfig.yaml
  core-services/prow/02_config/openshift-eng/art-config/_prowconfig.yaml
  core-services/prow/02_config/openshift-eng/art-dashboard-server/OWNERS
  core-services/prow/02_config/openshift-eng/art-dashboard-server/_pluginconfig.yaml
  core-services/prow/02_config/openshift-eng/art-dashboard-server/_prowconfig.yaml
  core-services/prow/02_config/openshift-eng/art-dashboard-ui/OWNERS
  core-services/prow/02_config/openshift-eng/art-dashboard-ui/_pluginconfig.yaml
  core-services/prow/02_config/openshift-eng/art-dashboard-ui/_prowconfig.yaml
  core-services/prow/02_config/openshift-eng/art-docs/OWNERS
  core-services/prow/02_config/openshift-eng/art-docs/_pluginconfig.yaml
  core-services/prow/02_config/openshift-eng/art-docs/_prowconfig.yaml
  core-services/prow/02_config/openshift-eng/art-tools/OWNERS
  core-services/prow/02_config/openshift-eng/art-tools/_pluginconfig.yaml
  core-services/prow/02_config/openshift-eng/art-tools/_prowconfig.yaml
  core-services/prow/02_config/openshift-eng/ocp-build-data-validator/OWNERS
  core-services/prow/02_config/openshift-eng/ocp-build-data-validator/_pluginconfig.yaml
  core-services/prow/02_config/openshift-eng/ocp-build-data-validator/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#42115 slack-bot&tide: use git-sync to pull Prow Job yamls
  clusters/app.ci/assets/slack-bot.yaml
  clusters/app.ci/prow/03_deployment/tide.yaml
Labels: lgtm, approved, rehearsals-ack

#42127 promote k8sgpt image
  ci-operator/config/openshift/release-tests/openshift-release-tests-master.yaml
Labels: lgtm, approved, rehearsals-ack

#41673 [LPTOCPCI-230] First draft of kie-cloud-tests-container config file
  ci-operator/config/kiegroup/kie-cloud-tests-container/OWNERS
  ci-operator/config/kiegroup/kie-cloud-tests-container/README.md
  ci-operator/config/kiegroup/kie-cloud-tests-container/kiegroup-kie-cloud-tests-container-main__rhba-ocp4.14-lp-interop.yaml
  ci-operator/jobs/kiegroup/kie-cloud-tests-container/OWNERS
  ci-operator/jobs/kiegroup/kie-cloud-tests-container/kiegroup-kie-cloud-tests-container-main-periodics.yaml
  ci-operator/jobs/kiegroup/kie-cloud-tests-container/kiegroup-kie-cloud-tests-container-main-presubmits.yaml
  ci-operator/step-registry/rhba/OWNERS
  ci-operator/step-registry/rhba/interop-tests/OWNERS
  ci-operator/step-registry/rhba/interop-tests/README.md
  ci-operator/step-registry/rhba/interop-tests/rhba-interop-tests-commands.sh
  ci-operator/step-registry/rhba/interop-tests/rhba-interop-tests-ref.metadata.json
  ci-operator/step-registry/rhba/interop-tests/rhba-interop-tests-ref.yaml
  core-services/prow/02_config/kiegroup/kie-cloud-tests-container/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack
