Repository openshift/release, pull requests merged in 2023-04, with the labels that each got.

#37971 Make cluster-health check a chain for upcoming other checks
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__arm64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__arm64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__arm64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.9__amd64-stable.yaml
  ci-operator/step-registry/cucushift/installer/check/cluster-health/cucushift-installer-check-cluster-health-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/check/cluster-health/cucushift-installer-check-cluster-health-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#37927 hypershift: merge test step
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
  ci-operator/step-registry/cucushift/hypershift-extended/enable-guest/cucushift-hypershift-extended-enable-guest-commands.sh
  ci-operator/step-registry/idp/htpasswd/idp-htpasswd-commands.sh
Labels: lgtm, approved, rehearsals-ack

#37925 Add more options on rosa-sts provision
  ci-operator/step-registry/osd-ccs/conf/idp/htpasswd/osd-ccs-conf-idp-htpasswd-commands.sh
  ci-operator/step-registry/rosa/conf/idp/htpasswd/rosa-conf-idp-htpasswd-commands.sh
  ci-operator/step-registry/rosa/sts/cluster/provision/rosa-sts-cluster-provision-commands.sh
  ci-operator/step-registry/rosa/sts/cluster/provision/rosa-sts-cluster-provision-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#37530 workflow-launch: Add Windows node config for GCP
  ci-operator/step-registry/ipi/conf/gcp/windows-machineset/OWNERS
  ci-operator/step-registry/ipi/conf/gcp/windows-machineset/ipi-conf-gcp-windows-machineset-commands.sh
  ci-operator/step-registry/ipi/conf/gcp/windows-machineset/ipi-conf-gcp-windows-machineset-ref.metadata.json
  ci-operator/step-registry/ipi/conf/gcp/windows-machineset/ipi-conf-gcp-windows-machineset-ref.yaml
  ci-operator/step-registry/openshift/e2e/gcp/windows-node/OWNERS
  ci-operator/step-registry/openshift/e2e/gcp/windows-node/openshift-e2e-gcp-windows-node-workflow.metadata.json
  ci-operator/step-registry/openshift/e2e/gcp/windows-node/openshift-e2e-gcp-windows-node-workflow.yaml
  core-services/ci-chat-bot/workflows-config.yaml
Labels: lgtm, approved, rehearsals-ack

#37956 OTA-925: ci-operator/step-registry/hypershift/hostedcluster: Gather a dump
  ci-operator/step-registry/hypershift/hostedcluster/workflow/hypershift-hostedcluster-workflow-workflow.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#37976 add vsphere job
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#37798 [knative-client] Remove non-existing image
  ci-operator/config/openshift-knative/client/openshift-knative-client-release-next__4.11.yaml
Labels: lgtm, approved, rehearsals-ack

#37984 Revert "Revert "add the config-updater kubeconfig for the multi01 cluster""
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#37980 Added random etcd encryption
  ci-operator/step-registry/etcd-encryption/etcd-encryption-commands.sh
Labels: lgtm, approved, rehearsals-ack

#37989 Revert "Revert "Revert "add the config-updater kubeconfig for the multi01 cluster"""
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#37626 Add kuttl test in e2e job for ansiblee-opertor
  ci-operator/config/openstack-k8s-operators/openstack-ansibleee-operator/openstack-k8s-operators-openstack-ansibleee-operator-main.yaml
  ci-operator/jobs/openstack-k8s-operators/openstack-ansibleee-operator/openstack-k8s-operators-openstack-ansibleee-operator-main-presubmits.yaml
  ci-operator/step-registry/openstack-k8s-operators/kuttl/openstack-k8s-operators-kuttl-commands.sh
Labels: lgtm, approved, rehearsals-ack

#37978 MicroShift: greenboot - fix error propagation
  ci-operator/step-registry/openshift/microshift/e2e/greenboot/openshift-microshift-e2e-greenboot-commands.sh
Labels: lgtm, approved, rehearsals-ack

#37744 CSPI MSI - update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: lgtm, approved, rehearsals-ack

#37752 msi - add ocp-addons-operators-cli image mirroring
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_ci
Labels: lgtm, approved, rehearsals-ack

#37696 ocm - Update for new RHTAP bot name (GRC)
  core-services/prow/02_config/_plugins.yaml
  core-services/prow/02_config/stolostron/config-policy-controller/_pluginconfig.yaml
  core-services/prow/02_config/stolostron/governance-policy-addon-controller/_pluginconfig.yaml
  core-services/prow/02_config/stolostron/governance-policy-framework-addon/_pluginconfig.yaml
  core-services/prow/02_config/stolostron/governance-policy-propagator/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#37168 Remove remaining CSI migration jobs for AWS EBS
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-master.yaml
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-release-4.12.yaml
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-release-4.13.yaml
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-release-4.14.yaml
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.12.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.13.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.14.yaml
  ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-master-presubmits.yaml
  ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-release-4.13-presubmits.yaml
  ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-release-4.14-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.13-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.14-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#37912 OSSM-3612: Add maistra-test-tool tide config and plugins
  ci-operator/config/maistra/maistra-test-tool/OWNERS
  ci-operator/jobs/maistra/maistra-test-tool/OWNERS
  core-services/prow/02_config/maistra/maistra-test-tool/_pluginconfig.yaml
  core-services/prow/02_config/maistra/maistra-test-tool/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#37940 stackrox: a release branch template and test branch
  ci-operator/config/stackrox/stackrox/README.md
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-x.y.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-x.y__ocp-4-10.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-x.y__ocp-4-12.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-x.y-postsubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-x.y-presubmits.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: lgtm, approved, rehearsals-ack

#37988 Add on-demand e2e-azure-ovn job for Kube apiserver operator
  ci-operator/config/openshift/cluster-kube-apiserver-operator/openshift-cluster-kube-apiserver-operator-master.yaml
  ci-operator/jobs/openshift/cluster-kube-apiserver-operator/openshift-cluster-kube-apiserver-operator-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#37954 SDCICD-913 ap-southeast-4 region testing
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#37337 CRW-3581 add Jira integration for devworkspace-operator project
  core-services/prow/02_config/devfile/_pluginconfig.yaml
  core-services/prow/02_config/devfile/devworkspace-operator/_pluginconfig.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#38005 Revert "OTA-925: ci-operator/step-registry/hypershift/hostedcluster: Gather a dump"
  ci-operator/step-registry/hypershift/hostedcluster/workflow/hypershift-hostedcluster-workflow-workflow.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#37967 PowerVS: add new cluster secrets
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#38010 velero-plugin-for-vsm use squash for tide
  core-services/prow/02_config/migtools/velero-plugin-for-vsm/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#36885 OPNET-138: Add e2e vsphere dual-stack job
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-master.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.13.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.13-presubmits.yaml
  ci-operator/step-registry/openshift/e2e/vsphere/ovn/dualstack/OWNERS
  ci-operator/step-registry/openshift/e2e/vsphere/ovn/dualstack/openshift-e2e-vsphere-ovn-dualstack-workflow.metadata.json
  ci-operator/step-registry/openshift/e2e/vsphere/ovn/dualstack/openshift-e2e-vsphere-ovn-dualstack-workflow.yaml
  ci-operator/step-registry/ovn/conf/baremetal-dualstack/OWNERS
  ci-operator/step-registry/ovn/conf/baremetal-dualstack/ovn-conf-baremetal-dualstack-commands.sh
  ci-operator/step-registry/ovn/conf/baremetal-dualstack/ovn-conf-baremetal-dualstack-ref.metadata.json
  ci-operator/step-registry/ovn/conf/baremetal-dualstack/ovn-conf-baremetal-dualstack-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#37746 add promotion for nmstate-console-plugin image
  ci-operator/config/openshift/nmstate-console-plugin/openshift-nmstate-console-plugin-main.yaml
  ci-operator/jobs/openshift/nmstate-console-plugin/openshift-nmstate-console-plugin-main-postsubmits.yaml
  ci-operator/jobs/openshift/nmstate-console-plugin/openshift-nmstate-console-plugin-main-presubmits.yaml
  core-services/image-mirroring/openshift/mapping_origin_4_13
Labels: lgtm, approved, rehearsals-ack

#37964 sdcicd-717 followup, update existing addon jobs to use new generic harness
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#38000 hypershift: bump CLI version for CAPI presub workflow
  ci-operator/step-registry/hypershift/aws/run-e2e/external/hypershift-aws-run-e2e-external-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#37985 Use CentOS 8 for FAR base image
  ci-operator/config/medik8s/fence-agents-remediation/medik8s-fence-agents-remediation-main.yaml
Labels: lgtm, approved, rehearsals-ack

#37900 PowerVS: Turn one cluster type into two
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.12.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.13.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.14.yaml
  ci-operator/jobs/openshift/multiarch/openshift-multiarch-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#37979 add gather-azure-resource step in azure-ipi-proxy-deprovision-chain
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/proxy/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/proxy/cucushift-installer-rehearse-azure-ipi-proxy-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/proxy/deprovision/cucushift-installer-rehearse-azure-ipi-proxy-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/proxy/deprovision/cucushift-installer-rehearse-azure-ipi-proxy-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/proxy/provision/cucushift-installer-rehearse-azure-ipi-proxy-provision-chain.metadata.json
Labels: lgtm, approved, rehearsals-ack

#37937 slack notify for longduration cloud tests to include success/failure/…
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#37919 Adding disconnected e2e testing for agent
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#38024 Added missing reporter conf for 4.12/23.3 nightly.
  ci-operator/jobs/rh-ecosystem-edge/ci-tools-nvidia-gpu-operator/rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#37992 Deployment of gangway component
  clusters/app.ci/prow/03_deployment/admin_gangway_rbac.yaml
  clusters/app.ci/prow/03_deployment/gangway.yaml
Labels: lgtm, approved, rehearsals-ack

#38003 Adding FilipB to maistra-approvers and maistra-reviewers
  OWNERS_ALIASES
Labels: lgtm, approved, rehearsals-ack

#32068 [loki] add loki-operator package to CLO's e2e jobs
  ci-operator/config/openshift/cluster-logging-operator/openshift-cluster-logging-operator-master.yaml
  ci-operator/jobs/openshift/cluster-logging-operator/openshift-cluster-logging-operator-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#37983 [kubevirt-tekton-tasks] feat:remove namespaced test lane
  ci-operator/config/kubevirt/kubevirt-tekton-tasks/kubevirt-kubevirt-tekton-tasks-main.yaml
  ci-operator/jobs/kubevirt/kubevirt-tekton-tasks/kubevirt-kubevirt-tekton-tasks-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#37999 NO-ISSUE: Fix virsh hang
  ci-operator/step-registry/assisted/common/gather/assisted-common-gather-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#38030 Add missing rbacs for gangway-oauth
  clusters/app.ci/prow/03_deployment/admin_gangway_rbac.yaml
Labels: lgtm, approved, rehearsals-ack

#38031 Add ocs-ci-container to image mirroring
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_ci
Labels: lgtm, approved, rehearsals-ack

#37623 Add rlobillo as QE cherry-pick approver for OCP on OSP repos
  core-services/prow/02_config/openshift/cloud-provider-openstack/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-api-provider-openstack/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-network-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/csi-driver-manila-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/csi-driver-nfs/_pluginconfig.yaml
  core-services/prow/02_config/openshift/installer/_pluginconfig.yaml
  core-services/prow/02_config/openshift/kuryr-kubernetes/_pluginconfig.yaml
  core-services/prow/02_config/openshift/machine-api-provider-openstack/_pluginconfig.yaml
  core-services/prow/02_config/openshift/machine-config-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/openstack-cinder-csi-driver-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/openstack-test/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#38035 parodos-dev/parodos: Disable review_acts_as_lgtm
  core-services/prow/02_config/parodos-dev/parodos/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#38034 Add docker login before bundle bc step
  ci-operator/step-registry/openstack-k8s-operators/build/openstack-k8s-operators-build-commands.sh
Labels: lgtm, approved, rehearsals-ack

#37959 openstack: Revert creds rotation workaround for MAPO
  ci-operator/step-registry/openstack/rotate/cloud-credentials/openstack-rotate-cloud-credentials-commands.sh
Labels: lgtm, approved, rehearsals-ack

#38036 Changes in gangway deployment
  clusters/app.ci/prow/03_deployment/gangway.yaml
Labels: lgtm, approved, rehearsals-ack

#37990 odf-console: skip 'post' steps on test success
  ci-operator/config/red-hat-storage/odf-console/red-hat-storage-odf-console-master.yaml
  ci-operator/config/red-hat-storage/odf-console/red-hat-storage-odf-console-release-4.13.yaml
Labels: lgtm, approved, rehearsals-ack

#38037 Serverless: Run kitchensink E2E and upgrade tests on demand
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main__4.10.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main__4.12.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#37852 Use different JVM Build Service Dockerfiles
  ci-operator/config/redhat-appstudio/jvm-build-service/redhat-appstudio-jvm-build-service-main.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#38040 Undo Promtail changes in 37832 and 37909
  ci-operator/step-registry/ipi/install/hosted-loki/ipi-install-hosted-loki-commands.sh
Labels: lgtm, approved, rehearsals-ack

#38043 Change type of the port to grpc for gangway
  clusters/app.ci/prow/03_deployment/gangway.yaml
Labels: lgtm, approved, rehearsals-ack

#37970 METAL-569: BM fixes
  ci-operator/step-registry/baremetalds/devscripts/setup/baremetalds-devscripts-setup-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#38023 aws-load-balancer-operator: pre-install-rosa - use deterministic json output to describe the cluster
  ci-operator/step-registry/aws-load-balancer/pre-install-rosa/aws-load-balancer-pre-install-rosa-commands.sh
Labels: lgtm, approved, rehearsals-ack

#38042 PowerVS: remove old powervs
  core-services/ci-secret-bootstrap/_config.yaml
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: lgtm, approved, rehearsals-ack

#38045 OSSM-3266: Update maistra prowconfig
  core-services/prow/02_config/_config.yaml
  core-services/prow/02_config/maistra/envoy/_prowconfig.yaml
  core-services/prow/02_config/maistra/istio-must-gather/_prowconfig.yaml
  core-services/prow/02_config/maistra/istio-operator/_prowconfig.yaml
  core-services/prow/02_config/maistra/istio/_prowconfig.yaml
  core-services/prow/02_config/maistra/proxy/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#38047 stackrox: run OCP e2e when collector changes
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-10.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-12.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#38050 Mount the job-config-4.0 ConfigMap
  clusters/app.ci/assets/slack-bot.yaml
  clusters/app.ci/ci-chat-bot/ci-chat-bot.yaml
  clusters/app.ci/prow/03_deployment/crier.yaml
  clusters/app.ci/prow/03_deployment/deck.yaml
  clusters/app.ci/prow/03_deployment/hook.yaml
  clusters/app.ci/prow/03_deployment/horologium.yaml
  clusters/app.ci/prow/03_deployment/jenkins_operator.yaml
  clusters/app.ci/prow/03_deployment/prow-controller-manager.yaml
  clusters/app.ci/prow/03_deployment/qe_private_deck.yaml
  clusters/app.ci/prow/03_deployment/retester.yaml
  clusters/app.ci/prow/03_deployment/statusreconciler.yaml
  clusters/app.ci/prow/03_deployment/tide.yaml
  clusters/app.ci/prow/03_deployment/tot.yaml
  clusters/app.ci/release-controller/deploy-ocp-arm64-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-arm64-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-multi-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-multi-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-ppc64le-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-ppc64le-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-s390x-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-s390x-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-origin-controller.yaml
  hack/generators/release-controllers/content/utils.py
Labels: lgtm, approved, rehearsals-ack

#38049 [openshift-loki] Revert change of operator image tag
  ci-operator/config/openshift/loki/openshift-loki-main.yaml
Labels: lgtm, approved, rehearsals-ack

#37576 Add Notebook controller tests downstream
  ci-operator/config/red-hat-data-services/kubeflow/OWNERS
  ci-operator/config/red-hat-data-services/kubeflow/red-hat-data-services-kubeflow-master.yaml
  ci-operator/jobs/red-hat-data-services/kubeflow/OWNERS
  ci-operator/jobs/red-hat-data-services/kubeflow/red-hat-data-services-kubeflow-master-postsubmits.yaml
  ci-operator/jobs/red-hat-data-services/kubeflow/red-hat-data-services-kubeflow-master-presubmits.yaml
  core-services/prow/02_config/red-hat-data-services/kubeflow/OWNERS
  core-services/prow/02_config/red-hat-data-services/kubeflow/_pluginconfig.yaml
  core-services/prow/02_config/red-hat-data-services/kubeflow/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#37982 Onboard designate operator
  ci-operator/config/openstack-k8s-operators/designate-operator/OWNERS
  ci-operator/config/openstack-k8s-operators/designate-operator/openstack-k8s-operators-designate-operator-main.yaml
  ci-operator/jobs/openstack-k8s-operators/designate-operator/OWNERS
  ci-operator/jobs/openstack-k8s-operators/designate-operator/openstack-k8s-operators-designate-operator-main-presubmits.yaml
  core-services/prow/02_config/openstack-k8s-operators/designate-operator/OWNERS
  core-services/prow/02_config/openstack-k8s-operators/designate-operator/_pluginconfig.yaml
  core-services/prow/02_config/openstack-k8s-operators/designate-operator/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#37822 PowerVS-remove-os-image-override
  ci-operator/step-registry/ipi/install/powervs/install/ipi-install-powervs-install-commands.sh
Labels: lgtm, approved, rehearsals-ack

#38059 ci-operator/step-registry: deprovision gcp vpc for cri-o tests
  ci-operator/step-registry/cri-o/cgroupv2/e2e-crun/cri-o-cgroupv2-e2e-crun-workflow.yaml
  ci-operator/step-registry/cri-o/cgroupv2/e2e-features/cri-o-cgroupv2-e2e-features-workflow.yaml
  ci-operator/step-registry/cri-o/cgroupv2/e2e/cri-o-cgroupv2-e2e-workflow.yaml
  ci-operator/step-registry/cri-o/cgroupv2/integration/cri-o-cgroupv2-integration-workflow.yaml
  ci-operator/step-registry/cri-o/crun/e2e/cri-o-crun-e2e-workflow.yaml
  ci-operator/step-registry/cri-o/crun/integration/cri-o-crun-integration-workflow.yaml
  ci-operator/step-registry/cri-o/e2e/cri-o-e2e-workflow.yaml
  ci-operator/step-registry/cri-o/fedora/critest/cri-o-fedora-critest-workflow.yaml
  ci-operator/step-registry/cri-o/fedora/e2e/cri-o-fedora-e2e-workflow.yaml
  ci-operator/step-registry/cri-o/fedora/integration/cri-o-fedora-integration-workflow.yaml
  ci-operator/step-registry/cri-o/rhel/critest/cri-o-rhel-critest-workflow.yaml
  ci-operator/step-registry/cri-o/rhel/e2e/cri-o-rhel-e2e-workflow.yaml
  ci-operator/step-registry/cri-o/rhel/integration/cri-o-rhel-integration-workflow.yaml
  ci-operator/step-registry/cri-o/setup-fedora/cri-o-setup-fedora-workflow.yaml
  ci-operator/step-registry/cri-o/setup/cri-o-setup-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#37847 PowerVS: Add tests to skiplist for 4.13 and 4.14
  ci-operator/step-registry/openshift/e2e/libvirt/conf/openshift-e2e-libvirt-conf-commands.sh
Labels: lgtm, approved, rehearsals-ack

#38032 Filter amd64 test cases when testing on amd64
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.8__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.9__amd64-nightly.yaml
Labels: lgtm, approved, rehearsals-ack

#37902 Vboulos obs change imagename
  ci-operator/config/stolostron/observability_core_automation/stolostron-observability_core_automation-release-2.7.yaml
Labels: lgtm, approved, rehearsals-ack

#37904 Add Prow CI support for ABI using proxy in restricted network environments
  ci-operator/step-registry/baremetal/lab/agent/conf/disconnected/proxy/OWNERS
  ci-operator/step-registry/baremetal/lab/agent/conf/disconnected/proxy/baremetal-lab-agent-conf-disconnected-proxy-chain.metadata.json
  ci-operator/step-registry/baremetal/lab/agent/conf/disconnected/proxy/baremetal-lab-agent-conf-disconnected-proxy-chain.yaml
  ci-operator/step-registry/baremetal/lab/agent/install/network/static/disconnected/proxy/OWNERS
  ci-operator/step-registry/baremetal/lab/agent/install/network/static/disconnected/proxy/baremetal-lab-agent-install-network-static-disconnected-proxy-workflow.metadata.json
  ci-operator/step-registry/baremetal/lab/agent/install/network/static/disconnected/proxy/baremetal-lab-agent-install-network-static-disconnected-proxy-workflow.yaml
  ci-operator/step-registry/baremetal/lab/pre/firewall/baremetal-lab-pre-firewall-commands.sh
  ci-operator/step-registry/baremetal/lab/pre/firewall/baremetal-lab-pre-firewall-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#38065 openshift-loki: Add ci config for branch upstream-v2.8.0
  ci-operator/config/openshift/loki/openshift-loki-upstream-v2.8.0.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-upstream-v2.8.0-postsubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-upstream-v2.8.0-presubmits.yaml
  core-services/image-mirroring/openshift-logging/mapping_logging_loki_quay
Labels: lgtm, approved, rehearsals-ack

#38067 Add envoyproxy img
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
Labels: lgtm, approved, rehearsals-ack

#38041 Add nutanix disconnected cluster profile
  core-services/ci-secret-bootstrap/_config.yaml
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: lgtm, approved, rehearsals-ack

#37565 Mirror 3scale-qe test image
  ci-operator/jobs/infra-image-mirroring.yaml
  clusters/app.ci/registry-access/3scale-qe/OWNERS
  clusters/app.ci/registry-access/3scale-qe/admin_3scale-qe.yaml
  core-services/image-mirroring/3scale-qe/OWNERS
  core-services/image-mirroring/3scale-qe/mapping_3scale-qe-test-image
Labels: lgtm, approved, rehearsals-ack

#38060 openstack/gather: skip gather only if no bastion
  ci-operator/step-registry/openstack/gather/openstack-gather-commands.sh
Labels: lgtm, approved, rehearsals-ack

#38070 Add hamzy and tvardema to libvirt test owners
  ci-operator/step-registry/openshift/e2e/libvirt/test/OWNERS
  ci-operator/step-registry/openshift/e2e/libvirt/test/openshift-e2e-libvirt-test-chain.metadata.json
  ci-operator/step-registry/openshift/e2e/libvirt/test/openshift-e2e-libvirt-test-ref.metadata.json
Labels: lgtm, approved, rehearsals-ack

#37564 ushift: Fix run workflow to pick up kubeconfig
  ci-operator/step-registry/openshift/microshift/e2e/test/openshift-microshift-e2e-test-commands.sh
Labels: lgtm, approved, rehearsals-ack

#38058 PowerVS: fix unsupported cluster type
  ci-operator/step-registry/ipi/install/powervs/install/ipi-install-powervs-install-commands.sh
  ci-operator/step-registry/openshift/e2e/libvirt/test/openshift-e2e-libvirt-test-commands.sh
Labels: lgtm, approved, rehearsals-ack

#38077 cri-o: add debug information for the current branch
  ci-operator/step-registry/cri-o/common/test/cri-o-common-test-commands.sh
Labels: lgtm, approved, rehearsals-ack

#38057 openshift-velero-plugin tide: squash
  core-services/prow/02_config/openshift/openshift-velero-plugin/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#38054 add -ovn- to aws-single-node presubmit in CNO
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.12.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.12-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#37770 Updated prow prometheus-alertmanager config to build required files f…
  ci-operator/config/stolostron/prometheus-alertmanager/stolostron-prometheus-alertmanager-release-2.8.yaml
Labels: lgtm, approved, rehearsals-ack

#37253 AMQ Streams Onboarding for layer-product testing
  OWNERS_ALIASES
  ci-operator/config/amq-streams-qe/strimzi-kafka-operator/OWNERS
  ci-operator/config/amq-streams-qe/strimzi-kafka-operator/amq-streams-qe-strimzi-kafka-operator-main__amq-streams-ocp4.13-lp-interop.yaml
  ci-operator/jobs/amq-streams-qe/strimzi-kafka-operator/OWNERS
  ci-operator/jobs/amq-streams-qe/strimzi-kafka-operator/amq-streams-qe-strimzi-kafka-operator-main-periodics.yaml
  ci-operator/step-registry/strimzi/OWNERS
  ci-operator/step-registry/strimzi/run-tests/OWNERS
  ci-operator/step-registry/strimzi/run-tests/strimzi-run-tests-commands.sh
  ci-operator/step-registry/strimzi/run-tests/strimzi-run-tests-ref.metadata.json
  ci-operator/step-registry/strimzi/run-tests/strimzi-run-tests-ref.yaml
  core-services/prow/02_config/amq-streams-qe/strimzi-kafka-operator/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#38082 3scale-qe: Add ci-registry authentication command
  ci-operator/jobs/infra-image-mirroring.yaml
Labels: lgtm, approved, rehearsals-ack

#38083 Add OBS image to allow us to use updated images in pj-rehearse
  ci-operator/config/rhpit/interop-tests/rhpit-interop-tests-main__image-hack.yaml
  ci-operator/jobs/rhpit/interop-tests/rhpit-interop-tests-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#38089 velero-plugins: Setup oadp-1.2 branch config
  ci-operator/config/openshift/velero-plugin-for-aws/openshift-velero-plugin-for-aws-oadp-1.2.yaml
  ci-operator/config/openshift/velero-plugin-for-csi/openshift-velero-plugin-for-csi-oadp-1.2.yaml
  ci-operator/config/openshift/velero-plugin-for-gcp/openshift-velero-plugin-for-gcp-oadp-1.2.yaml
  ci-operator/config/openshift/velero-plugin-for-microsoft-azure/openshift-velero-plugin-for-microsoft-azure-oadp-1.2.yaml
  ci-operator/jobs/openshift/velero-plugin-for-aws/openshift-velero-plugin-for-aws-oadp-1.2-postsubmits.yaml
  ci-operator/jobs/openshift/velero-plugin-for-aws/openshift-velero-plugin-for-aws-oadp-1.2-presubmits.yaml
  ci-operator/jobs/openshift/velero-plugin-for-csi/openshift-velero-plugin-for-csi-oadp-1.2-postsubmits.yaml
  ci-operator/jobs/openshift/velero-plugin-for-csi/openshift-velero-plugin-for-csi-oadp-1.2-presubmits.yaml
  ci-operator/jobs/openshift/velero-plugin-for-gcp/openshift-velero-plugin-for-gcp-oadp-1.2-postsubmits.yaml
  ci-operator/jobs/openshift/velero-plugin-for-gcp/openshift-velero-plugin-for-gcp-oadp-1.2-presubmits.yaml
  ci-operator/jobs/openshift/velero-plugin-for-microsoft-azure/openshift-velero-plugin-for-microsoft-azure-oadp-1.2-postsubmits.yaml
  ci-operator/jobs/openshift/velero-plugin-for-microsoft-azure/openshift-velero-plugin-for-microsoft-azure-oadp-1.2-presubmits.yaml
  core-services/image-mirroring/konveyor/mapping_konveyor_latest
  core-services/prow/02_config/openshift/velero-plugin-for-aws/_prowconfig.yaml
  core-services/prow/02_config/openshift/velero-plugin-for-csi/_prowconfig.yaml
  core-services/prow/02_config/openshift/velero-plugin-for-gcp/_prowconfig.yaml
  core-services/prow/02_config/openshift/velero-plugin-for-microsoft-azure/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#38088 Add envoyproxy to gangway deployment
  clusters/app.ci/prow/03_deployment/gangway.yaml
Labels: lgtm, approved, rehearsals-ack

#37238 Update operator config to use new tests
  ci-operator/config/opendatahub-io/opendatahub-operator/opendatahub-io-opendatahub-operator-master.yaml
  ci-operator/jobs/opendatahub-io/opendatahub-operator/opendatahub-io-opendatahub-operator-master-periodics.yaml
  ci-operator/jobs/opendatahub-io/opendatahub-operator/opendatahub-io-opendatahub-operator-master-postsubmits.yaml
  ci-operator/jobs/opendatahub-io/opendatahub-operator/opendatahub-io-opendatahub-operator-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#38063 ACS Scanner 2.29
  ci-operator/config/stackrox/scanner/stackrox-scanner-release-2.29.yaml
  ci-operator/jobs/stackrox/scanner/stackrox-scanner-release-2.29-postsubmits.yaml
  ci-operator/jobs/stackrox/scanner/stackrox-scanner-release-2.29-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#38095 OCPQE-14334: Add cluster health check step before running e2e test
  ci-operator/step-registry/openshift/e2e/test/qe/destructive/openshift-e2e-test-qe-destructive-chain.yaml
  ci-operator/step-registry/openshift/e2e/test/qe/long-duration/openshift-e2e-test-qe-long-duration-chain.yaml
  ci-operator/step-registry/openshift/e2e/test/qe/openshift-e2e-test-qe-chain.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#38096 gcp workload identity requires 4.10+
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__amd64-nightly-4.10-upgrade-from-stable-4.9.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#38101 Revert "Added random etcd encryption"
  ci-operator/step-registry/etcd-encryption/etcd-encryption-commands.sh
Labels: lgtm, approved, rehearsals-ack

#38099 Fix golang version
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.6.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.7.yaml
Labels: lgtm, approved, rehearsals-ack

#37965 New repo - Intersmash/intersmash
  ci-operator/config/Intersmash/intersmash/Intersmash-intersmash-main.yaml
  ci-operator/config/Intersmash/intersmash/OWNERS
  ci-operator/jobs/Intersmash/intersmash/Intersmash-intersmash-main-presubmits.yaml
  ci-operator/jobs/Intersmash/intersmash/OWNERS
  core-services/prow/02_config/Intersmash/intersmash/_pluginconfig.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#38091 Remove jira plugin in maistra pluginconfigs
  core-services/prow/02_config/maistra/api/_pluginconfig.yaml
  core-services/prow/02_config/maistra/envoy/_pluginconfig.yaml
  core-services/prow/02_config/maistra/header-append-filter/_pluginconfig.yaml
  core-services/prow/02_config/maistra/istio-images-centos/_pluginconfig.yaml
  core-services/prow/02_config/maistra/istio-must-gather/_pluginconfig.yaml
  core-services/prow/02_config/maistra/istio-operator/_pluginconfig.yaml
  core-services/prow/02_config/maistra/istio/_pluginconfig.yaml
  core-services/prow/02_config/maistra/maistra-test-tool/_pluginconfig.yaml
  core-services/prow/02_config/maistra/prometheus/OWNERS
  core-services/prow/02_config/maistra/prometheus/_pluginconfig.yaml
  core-services/prow/02_config/maistra/proxy/_pluginconfig.yaml
  core-services/prow/02_config/maistra/test-infra/_pluginconfig.yaml
  core-services/prow/02_config/maistra/xns-informer/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#38093 openshift/cri-o: add image pull rbac rules
  clusters/app.ci/registry-access/cri-o/OWNERS
  clusters/app.ci/registry-access/cri-o/admin_manifest.yaml
Labels: lgtm, approved, rehearsals-ack

#38098 OCPQE-14610 Adding jobs for marketimage on amd64 platform
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__amd64-nightly-4.10-upgrade-from-stable-4.9.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly-4.11-upgrade-from-stable-4.10.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-stable-4.11.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-stable-4.12-upgrade-from-stable-4.11.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-4.13-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-4.13-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-stable-4.13-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-nightly-4.13-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-nightly-4.13-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-stable-4.13-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly-4.14-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly-4.14-upgrade-from-stable-4.13.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#38109 Add prow-config for openstack ironic repos
  core-services/prow/02_config/openshift/openstack-ironic-inspector/OWNERS
  core-services/prow/02_config/openshift/openstack-ironic-inspector/_pluginconfig.yaml
  core-services/prow/02_config/openshift/openstack-ironic-inspector/_prowconfig.yaml
  core-services/prow/02_config/openshift/openstack-ironic-lib/OWNERS
  core-services/prow/02_config/openshift/openstack-ironic-lib/_pluginconfig.yaml
  core-services/prow/02_config/openshift/openstack-ironic-lib/_prowconfig.yaml
  core-services/prow/02_config/openshift/openstack-ironic-python-agent/OWNERS
  core-services/prow/02_config/openshift/openstack-ironic-python-agent/_pluginconfig.yaml
  core-services/prow/02_config/openshift/openstack-ironic-python-agent/_prowconfig.yaml
  core-services/prow/02_config/openshift/openstack-ironic/OWNERS
  core-services/prow/02_config/openshift/openstack-ironic/_pluginconfig.yaml
  core-services/prow/02_config/openshift/openstack-ironic/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#37505 OSSM maistra Remove git workaround
  ci-operator/config/maistra/api/maistra-api-maistra-2.1.yaml
  ci-operator/config/maistra/api/maistra-api-maistra-2.2.yaml
  ci-operator/config/maistra/api/maistra-api-maistra-2.3.yaml
  ci-operator/config/maistra/api/maistra-api-maistra-2.4.yaml
  ci-operator/config/maistra/header-append-filter/maistra-header-append-filter-maistra-2.2.yaml
  ci-operator/config/maistra/header-append-filter/maistra-header-append-filter-maistra-2.3.yaml
  ci-operator/config/maistra/header-append-filter/maistra-header-append-filter-maistra-2.4.yaml
  ci-operator/config/maistra/istio-images-centos/maistra-istio-images-centos-maistra-2.2.yaml
  ci-operator/config/maistra/istio-images-centos/maistra-istio-images-centos-maistra-2.3.yaml
  ci-operator/config/maistra/istio-images-centos/maistra-istio-images-centos-maistra-2.4.yaml
  ci-operator/config/maistra/istio-must-gather/maistra-istio-must-gather-maistra-2.2.yaml
  ci-operator/config/maistra/istio-must-gather/maistra-istio-must-gather-maistra-2.3.yaml
  ci-operator/config/maistra/istio-must-gather/maistra-istio-must-gather-maistra-2.4.yaml
  ci-operator/config/maistra/istio-operator/maistra-istio-operator-maistra-2.2.yaml
  ci-operator/config/maistra/istio-operator/maistra-istio-operator-maistra-2.3.yaml
  ci-operator/config/maistra/istio-operator/maistra-istio-operator-maistra-2.4.yaml
  ci-operator/config/maistra/istio-operator/maistra-istio-operator-maistra-3.0.yaml
  ci-operator/config/maistra/istio/maistra-istio-maistra-2.1.yaml
  ci-operator/config/maistra/istio/maistra-istio-maistra-2.2.yaml
  ci-operator/config/maistra/istio/maistra-istio-maistra-2.3.yaml
  ci-operator/config/maistra/istio/maistra-istio-maistra-2.4.yaml
  ci-operator/config/maistra/xns-informer/maistra-xns-informer-maistra-2.1.yaml
  ci-operator/config/maistra/xns-informer/maistra-xns-informer-maistra-2.2.yaml
  ci-operator/config/maistra/xns-informer/maistra-xns-informer-maistra-2.3.yaml
  ci-operator/config/maistra/xns-informer/maistra-xns-informer-maistra-2.4.yaml
  ci-operator/jobs/maistra/api/maistra-api-maistra-2.1-presubmits.yaml
  ci-operator/jobs/maistra/api/maistra-api-maistra-2.2-presubmits.yaml
  ci-operator/jobs/maistra/api/maistra-api-maistra-2.3-presubmits.yaml
  ci-operator/jobs/maistra/api/maistra-api-maistra-2.4-presubmits.yaml
  ci-operator/jobs/maistra/header-append-filter/maistra-header-append-filter-maistra-2.2-presubmits.yaml
  ci-operator/jobs/maistra/header-append-filter/maistra-header-append-filter-maistra-2.3-presubmits.yaml
  ci-operator/jobs/maistra/header-append-filter/maistra-header-append-filter-maistra-2.4-presubmits.yaml
  ci-operator/jobs/maistra/istio-images-centos/maistra-istio-images-centos-maistra-2.2-presubmits.yaml
  ci-operator/jobs/maistra/istio-images-centos/maistra-istio-images-centos-maistra-2.3-presubmits.yaml
  ci-operator/jobs/maistra/istio-images-centos/maistra-istio-images-centos-maistra-2.4-presubmits.yaml
  ci-operator/jobs/maistra/istio-must-gather/maistra-istio-must-gather-maistra-2.2-presubmits.yaml
  ci-operator/jobs/maistra/istio-must-gather/maistra-istio-must-gather-maistra-2.3-presubmits.yaml
  ci-operator/jobs/maistra/istio-must-gather/maistra-istio-must-gather-maistra-2.4-presubmits.yaml
  ci-operator/jobs/maistra/istio-operator/maistra-istio-operator-maistra-2.2-presubmits.yaml
  ci-operator/jobs/maistra/istio-operator/maistra-istio-operator-maistra-2.3-presubmits.yaml
  ci-operator/jobs/maistra/istio-operator/maistra-istio-operator-maistra-2.4-presubmits.yaml
  ci-operator/jobs/maistra/istio-operator/maistra-istio-operator-maistra-3.0-presubmits.yaml
  ci-operator/jobs/maistra/istio/maistra-istio-maistra-2.1-presubmits.yaml
  ci-operator/jobs/maistra/istio/maistra-istio-maistra-2.2-presubmits.yaml
  ci-operator/jobs/maistra/istio/maistra-istio-maistra-2.3-presubmits.yaml
  ci-operator/jobs/maistra/istio/maistra-istio-maistra-2.4-presubmits.yaml
  ci-operator/jobs/maistra/xns-informer/maistra-xns-informer-maistra-2.1-presubmits.yaml
  ci-operator/jobs/maistra/xns-informer/maistra-xns-informer-maistra-2.2-presubmits.yaml
  ci-operator/jobs/maistra/xns-informer/maistra-xns-informer-maistra-2.3-presubmits.yaml
  ci-operator/jobs/maistra/xns-informer/maistra-xns-informer-maistra-2.4-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#38113 Disable ginkgo color output in CI
  ci-operator/config/openstack-k8s-operators/nova-operator/openstack-k8s-operators-nova-operator-master.yaml
  ci-operator/config/openstack-k8s-operators/placement-operator/openstack-k8s-operators-placement-operator-master.yaml
Labels: lgtm, approved, rehearsals-ack

#38117 [LPTOCPCI-93] Use release-v1.1 branch instead of master for oadp-e2e-qe
  ci-operator/config/oadp-qe/oadp-e2e-qe/oadp-qe-oadp-e2e-qe-release-v1.1.yaml
  ci-operator/config/rhpit/interop-tests/rhpit-interop-tests-main__image-hack.yaml
  ci-operator/jobs/oadp-qe/oadp-e2e-qe/oadp-qe-oadp-e2e-qe-release-v1.1-postsubmits.yaml
  ci-operator/jobs/oadp-qe/oadp-e2e-qe/oadp-qe-oadp-e2e-qe-release-v1.1-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#35864 Added pre-commit job for cinder-operator
  ci-operator/config/openstack-k8s-operators/cinder-operator/openstack-k8s-operators-cinder-operator-master.yaml
  ci-operator/jobs/openstack-k8s-operators/cinder-operator/openstack-k8s-operators-cinder-operator-master-presubmits.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#36010 Added pre-commit jobs for glance operator
  ci-operator/config/openstack-k8s-operators/glance-operator/openstack-k8s-operators-glance-operator-master.yaml
  ci-operator/jobs/openstack-k8s-operators/glance-operator/openstack-k8s-operators-glance-operator-master-presubmits.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#36013 Added pre-commit job for ovs-operator
  ci-operator/config/openstack-k8s-operators/ovs-operator/openstack-k8s-operators-ovs-operator-main.yaml
  ci-operator/jobs/openstack-k8s-operators/ovs-operator/openstack-k8s-operators-ovs-operator-main-presubmits.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#36751 Added pre-commit job for ovn-operator
  ci-operator/config/openstack-k8s-operators/ovn-operator/openstack-k8s-operators-ovn-operator-main.yaml
  ci-operator/jobs/openstack-k8s-operators/ovn-operator/openstack-k8s-operators-ovn-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#38115 USHIFT-1051: feat: added alert channel for failed rebase periodic
  ci-operator/jobs/openshift/microshift/openshift-microshift-main-periodics.yaml
  ci-operator/jobs/openshift/microshift/openshift-microshift-release-4.12-periodics.yaml
  ci-operator/jobs/openshift/microshift/openshift-microshift-release-4.13-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#38080 Add pre-commit job for neutron-operator
  ci-operator/config/openstack-k8s-operators/neutron-operator/openstack-k8s-operators-neutron-operator-master.yaml
  ci-operator/jobs/openstack-k8s-operators/neutron-operator/openstack-k8s-operators-neutron-operator-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#38062 openshift-ansible: drop shadow-utils pkg
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-master.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-4.10.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-4.11.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-4.12.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-4.13.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-4.14.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-4.15.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-4.8.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-4.9.yaml
Labels: lgtm, approved, rehearsals-ack

#38126 update branch for cloud-provider-ibm in rebasebot
  ci-operator/config/openshift-eng/rebasebot/openshift-eng-rebasebot-main.yaml
Labels: lgtm, approved, rehearsals-ack

#38131 aws-load-balancer-operator: use allnamespaces install mode to enable conversion to v1beta1
  ci-operator/config/openshift/aws-load-balancer-operator/openshift-aws-load-balancer-operator-main.yaml
Labels: lgtm, approved, rehearsals-ack

#38112 Add random etcd encryption with aesgcm cipher for cluster greater than or equal 4.13
  ci-operator/step-registry/etcd-encryption/etcd-encryption-commands.sh
Labels: lgtm, approved, rehearsals-ack

#37949 Add-aws-ipi-ovn-migration-sdn-workflow
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
  ci-operator/step-registry/cucushift/ovn-migration-sdn/OWNERS
  ci-operator/step-registry/cucushift/ovn-migration-sdn/cucushift-ovn-migration-sdn-chain.metadata.json
  ci-operator/step-registry/cucushift/ovn-migration-sdn/cucushift-ovn-migration-sdn-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#38118 add-hypeshift-ovn-workflow-for-cluster-bot
  core-services/ci-chat-bot/workflows-config.yaml
Labels: lgtm, approved, rehearsals-ack

#37975 Hypershift: add publicAndPrivate to 4.12
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#38048 OCPQE-14685 [ASH] change CLUSTER_OS_IMAGE for rhcos 9.2
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.13.yaml
Labels: lgtm, approved, rehearsals-ack

#38141 OCPQE-14677: Remove unsupported sts jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__amd64-nightly-4.10-upgrade-from-stable-4.9.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#38130 velero-plugins: OADP-1.2 branch config
  ci-operator/config/migtools/velero-plugin-for-vsm/migtools-velero-plugin-for-vsm-oadp-1.2.yaml
  ci-operator/config/migtools/volume-snapshot-mover/migtools-volume-snapshot-mover-oadp-1.2.yaml
  ci-operator/config/openshift/openshift-velero-plugin/openshift-openshift-velero-plugin-oadp-1.2.yaml
  ci-operator/jobs/migtools/velero-plugin-for-vsm/migtools-velero-plugin-for-vsm-oadp-1.2-postsubmits.yaml
  ci-operator/jobs/migtools/velero-plugin-for-vsm/migtools-velero-plugin-for-vsm-oadp-1.2-presubmits.yaml
  ci-operator/jobs/migtools/volume-snapshot-mover/migtools-volume-snapshot-mover-oadp-1.2-postsubmits.yaml
  ci-operator/jobs/migtools/volume-snapshot-mover/migtools-volume-snapshot-mover-oadp-1.2-presubmits.yaml
  ci-operator/jobs/openshift/openshift-velero-plugin/openshift-openshift-velero-plugin-oadp-1.2-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-velero-plugin/openshift-openshift-velero-plugin-oadp-1.2-presubmits.yaml
  core-services/image-mirroring/konveyor/mapping_konveyor_latest
  core-services/prow/02_config/_plugins.yaml
  core-services/prow/02_config/migtools/velero-plugin-for-vsm/_prowconfig.yaml
  core-services/prow/02_config/migtools/volume-snapshot-mover/_prowconfig.yaml
  core-services/prow/02_config/openshift/openshift-velero-plugin/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#38145 add base_images
  core-services/ci-chat-bot/workflows-config.yaml
Labels: lgtm, approved, rehearsals-ack

#38008 baremetal: ipv4 provisioning network in dualstack
  ci-operator/step-registry/baremetalds/e2e/serial/ovn/dualstack/baremetalds-e2e-serial-ovn-dualstack-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#38064 RHODS: s/ods-plot-notebooks/ods-notebooks-plot/
  ci-operator/config/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-main__ods.yaml
  ci-operator/jobs/openshift-psap/ci-artifacts/openshift-psap-ci-artifacts-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#38146 [azure] subscriptionId for DES is required
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.13.yaml
  ci-operator/step-registry/ipi/conf/azure/provisioned-des/ipi-conf-azure-provisioned-des-commands.sh
Labels: lgtm, approved, rehearsals-ack

#38137 Older logging-view-plugin image is tagged latest
  core-services/image-mirroring/openshift-logging/mapping_logging_5_5_quay
Labels: lgtm, approved, rehearsals-ack

#38148 OCPQE-14724: Fix periodic-ci-openshift-openshift-tests-private-release-4.14-arm64-nightly-aws-ipi-compact-p3-f28-destructive
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#38157 add chain: openshift-e2e-test-hypershift-qe
  ci-operator/step-registry/openshift/e2e/test/hypershift-qe/OWNERS
  ci-operator/step-registry/openshift/e2e/test/hypershift-qe/openshift-e2e-test-hypershift-qe-chain.metadata.json
  ci-operator/step-registry/openshift/e2e/test/hypershift-qe/openshift-e2e-test-hypershift-qe-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#38160 Flowschema: ocp 4.13 no longer supports `v1beta1`
  clusters/build-clusters/01_cluster/readyz-flowschema.yaml
Labels: lgtm, approved, rehearsals-ack

#38136 OSSM-3716: Add maistra prometheus tests
  ci-operator/config/maistra/prometheus/OWNERS
  ci-operator/config/maistra/prometheus/maistra-prometheus-maistra-2.1.yaml
  ci-operator/jobs/maistra/prometheus/OWNERS
  ci-operator/jobs/maistra/prometheus/maistra-prometheus-maistra-2.1-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#38158 OCPQE-14725: HyperShift-MCE: fix
  ci-operator/step-registry/hypershift/mce/aws/create/hypershift-mce-aws-create-chain.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#38150 OKD-93: feat: adds a service account to OKD CI
  clusters/app.ci/okd/admin_okd.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#38161 Enable verbose logging for unit tests
  ci-operator/config/stolostron/multicluster-observability-operator/stolostron-multicluster-observability-operator-main.yaml
  ci-operator/config/stolostron/multicluster-observability-operator/stolostron-multicluster-observability-operator-release-2.5.yaml
  ci-operator/config/stolostron/multicluster-observability-operator/stolostron-multicluster-observability-operator-release-2.6.yaml
  ci-operator/config/stolostron/multicluster-observability-operator/stolostron-multicluster-observability-operator-release-2.7.yaml
  ci-operator/config/stolostron/multicluster-observability-operator/stolostron-multicluster-observability-operator-release-2.8.yaml
Labels: lgtm, approved, rehearsals-ack

#38133 Update image to v1.5 of ODH Operator
  ci-operator/config/opendatahub-io/opendatahub-operator/opendatahub-io-opendatahub-operator-master.yaml
Labels: lgtm, approved, rehearsals-ack

#38125 feat(hypershift): Add CI tests for 4.12 IBMCloud
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.12.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.12-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#38147 mtu-migration: oc sa get-token is deprecated
  ci-operator/step-registry/network/mtu-migration/network-mtu-migration-commands.sh
Labels: lgtm, approved, rehearsals-ack

#38164 velero: Update ci/prow/images to optional
  ci-operator/jobs/openshift/velero/openshift-velero-oadp-1.2-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#38166 konveyor org: Update image tags
  ci-operator/config/openshift/velero/openshift-velero-oadp-1.2.yaml
  ci-operator/jobs/openshift/velero/openshift-velero-oadp-1.2-postsubmits.yaml
  ci-operator/jobs/openshift/velero/openshift-velero-oadp-1.2-presubmits.yaml
  core-services/image-mirroring/konveyor/mapping_konveyor_latest
Labels: lgtm, approved, rehearsals-ack

#38169 govulncheck: bump go version to 1.19.8
  clusters/app.ci/supplemental-ci-images/crt/govulncheck.yaml
Labels: lgtm, approved, rehearsals-ack

#38173 add: openshift-e2e-test-hypershift-qe-destructive
  ci-operator/step-registry/openshift/e2e/test/hypershift-qe/destructive/OWNERS
  ci-operator/step-registry/openshift/e2e/test/hypershift-qe/destructive/openshift-e2e-test-hypershift-qe-destructive-chain.metadata.json
  ci-operator/step-registry/openshift/e2e/test/hypershift-qe/destructive/openshift-e2e-test-hypershift-qe-destructive-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#38175 Updating go version to 1.19 for ocm-agent
  ci-operator/config/openshift/ocm-agent/openshift-ocm-agent-master.yaml
Labels: lgtm, approved, rehearsals-ack

#38134 remove osde2e harness image publish job from avo main pipeline.
  ci-operator/config/openshift/aws-vpce-operator/openshift-aws-vpce-operator-main.yaml
  ci-operator/jobs/openshift/aws-vpce-operator/openshift-aws-vpce-operator-main-postsubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#38176 Fix write permission issue
  ci-operator/step-registry/cucushift/upgrade/toimage/cucushift-upgrade-toimage-commands.sh
Labels: lgtm, approved, rehearsals-ack

#38178 [CIGolang]exclude workload from default long-duration test
  ci-operator/step-registry/openshift-extended/test/longduration/openshift-extended-test-longduration-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#38151 add workload cronjob for oc-mirror cases
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#38172 OCPQE-14727: update hypershift-guest test chain
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-nightly.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#38180 add: openshift-e2e-test-hypershift-qe-mgmt
  ci-operator/step-registry/openshift/e2e/test/hypershift-qe/mgmt/OWNERS
  ci-operator/step-registry/openshift/e2e/test/hypershift-qe/mgmt/openshift-e2e-test-hypershift-qe-mgmt-chain.metadata.json
  ci-operator/step-registry/openshift/e2e/test/hypershift-qe/mgmt/openshift-e2e-test-hypershift-qe-mgmt-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#38181 Fix test filter on non-fips profiles
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__amd64-nightly-4.10-upgrade-from-stable-4.9.yaml
Labels: lgtm, approved, rehearsals-ack

#36321 [cluster-logging-operator] Use 5.6 branch of logging-view-plugin
  ci-operator/config/openshift/cluster-logging-operator/openshift-cluster-logging-operator-release-5.6.yaml
Labels: lgtm, approved, rehearsals-ack

#38189 LOG-3864 Add logging-view-plugin:5.6 mirroring config
  core-services/image-mirroring/openshift-logging/mapping_logging_5_6_quay
Labels: lgtm, approved, rehearsals-ack

#36396 Onboard openstack-k8s-operators/install_yamls repo
  ci-operator/config/openstack-k8s-operators/install_yamls/OWNERS
  ci-operator/config/openstack-k8s-operators/install_yamls/openstack-k8s-operators-install_yamls-master.yaml
  ci-operator/jobs/openstack-k8s-operators/install_yamls/OWNERS
  ci-operator/jobs/openstack-k8s-operators/install_yamls/openstack-k8s-operators-install_yamls-master-presubmits.yaml
  core-services/prow/02_config/openstack-k8s-operators/install_yamls/OWNERS
  core-services/prow/02_config/openstack-k8s-operators/install_yamls/_pluginconfig.yaml
  core-services/prow/02_config/openstack-k8s-operators/install_yamls/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#38086 Grant some more labels to TRT
  core-services/prow/02_config/_plugins.yaml
Labels: lgtm, approved, rehearsals-ack

#38177 build foundation-e2e image per branch
  ci-operator/config/stolostron/foundation-e2e/stolostron-foundation-e2e-backplane-2.3.yaml
  ci-operator/config/stolostron/foundation-e2e/stolostron-foundation-e2e-main.yaml
  ci-operator/jobs/stolostron/foundation-e2e/stolostron-foundation-e2e-backplane-2.3-postsubmits.yaml
  ci-operator/jobs/stolostron/foundation-e2e/stolostron-foundation-e2e-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#38174 Bump volume size for integration tests in openshift/kubernetes
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-master.yaml
Labels: lgtm, approved, rehearsals-ack

#37816 OCPBUGS-11204: ovn-kubernetes: remove building duplicate RHEL9 images
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master__4.14-upgrade-from-stable-4.13-local-gateway.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master__4.14-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master__okd.yaml
  core-services/image-mirroring/openshift/mapping_origin_4_14
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, rehearsals-ack, jira/valid-reference

#38073 SPLAT-1017 - multi-zone CI jobs are not cleaning up orphaned VMs in the datacenter-2
  ci-operator/step-registry/ipi/conf/vsphere/check/ipi-conf-vsphere-check-commands.sh
Labels: lgtm, approved, rehearsals-ack

#38195 Includes 'oc describe' when gathering logs from all resources
  ci-operator/step-registry/openstack-k8s-operators/gather/openstack-k8s-operators-gather-commands.sh
Labels: lgtm, approved, rehearsals-ack

#38163 oadp: e2e periodic and presubmit jobs for branch oadp-1.2
  ci-operator/config/openshift/oadp-operator/openshift-oadp-operator-oadp-1.2__4.10.yaml
  ci-operator/config/openshift/oadp-operator/openshift-oadp-operator-oadp-1.2__4.11.yaml
  ci-operator/config/openshift/oadp-operator/openshift-oadp-operator-oadp-1.2__4.9.yaml
  ci-operator/jobs/openshift/oadp-operator/openshift-oadp-operator-oadp-1.2-periodics.yaml
  ci-operator/jobs/openshift/oadp-operator/openshift-oadp-operator-oadp-1.2-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack
