Repository openshift/release, pull requests merged in 2023-10, with the labels that each got.

#43833 Add OCP 4.15 for NMO and FAR
  ci-operator/config/medik8s/fence-agents-remediation/medik8s-fence-agents-remediation-main__4.15.yaml
  ci-operator/config/medik8s/node-maintenance-operator/medik8s-node-maintenance-operator-main__4.15.yaml
  ci-operator/jobs/medik8s/fence-agents-remediation/medik8s-fence-agents-remediation-main-presubmits.yaml
  ci-operator/jobs/medik8s/node-maintenance-operator/medik8s-node-maintenance-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#43802 run tf-provider periodic job with the latest build from main branch
  ci-operator/config/terraform-redhat/terraform-provider-rhcs/terraform-redhat-terraform-provider-rhcs-main.yaml
Labels: lgtm, approved, rehearsals-ack

#43373 openstack: Replace symlink with actual file
  ci-operator/step-registry/openshift/manifests/openstack/OWNERS
Labels: lgtm, approved, rehearsals-ack

#43820 adding the cloud-experts label to openshift-docs
  core-services/prow/02_config/_labels.yaml
  core-services/prow/02_config/openshift/openshift-docs/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#43813 vSphere: 4.10 EOL, jobs to yearly
  ci-operator/config/openshift/release/openshift-release-master__ci-4.10-upgrade-from-stable-4.9.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.10.yaml
  ci-operator/config/openshift/release/openshift-release-master__okd-4.10.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#42537 [kubevirt-tekton-tasks] feat: introduce ci for tekton tasks release-v0.15.0 branch
  ci-operator/config/kubevirt/kubevirt-tekton-tasks/kubevirt-kubevirt-tekton-tasks-release-v0.15.yaml
  ci-operator/jobs/kubevirt/kubevirt-tekton-tasks/kubevirt-kubevirt-tekton-tasks-release-v0.15-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#43853 Bring back timeouts for payload jobs to after landing k8s 1.28
  ci-operator/step-registry/openshift/release/analysis/aggregator/openshift-release-analysis-aggregator-commands.sh
  ci-operator/step-registry/openshift/release/analysis/prpqr-aggregator/openshift-release-analysis-prpqr-aggregator-commands.sh
Labels: lgtm, approved, rehearsals-ack

#43869 fix branch protection for remote-secret and spi repositories
  core-services/prow/02_config/redhat-appstudio/remote-secret/_prowconfig.yaml
  core-services/prow/02_config/redhat-appstudio/service-provider-integration-operator/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#43871 reverting build check to unblock weekly run.
  ci-operator/step-registry/trigger-jobs/trigger-jobs-commands.sh
Labels: lgtm, approved, rehearsals-ack

#42274 Update OWNER_ALIASES: Add members to cspi-qe-ocp-lp
  OWNERS_ALIASES
Labels: lgtm, approved, rehearsals-ack

#43850 Sync Serverless CI
  ci-operator/config/openshift-knative/eventing-hyperfoil-benchmark/openshift-knative-eventing-hyperfoil-benchmark-main__412.yaml
  ci-operator/config/openshift-knative/eventing-istio/openshift-knative-eventing-istio-release-next__411.yaml
  ci-operator/config/openshift-knative/eventing-istio/openshift-knative-eventing-istio-release-next__413.yaml
  ci-operator/config/openshift-knative/eventing-istio/openshift-knative-eventing-istio-release-v1.10__410.yaml
  ci-operator/config/openshift-knative/eventing-istio/openshift-knative-eventing-istio-release-v1.10__413.yaml
  ci-operator/config/openshift-knative/eventing-istio/openshift-knative-eventing-istio-release-v1.11__411.yaml
  ci-operator/config/openshift-knative/eventing-istio/openshift-knative-eventing-istio-release-v1.11__413.yaml
  ci-operator/config/openshift-knative/eventing-istio/openshift-knative-eventing-istio-release-v1.8__410.yaml
  ci-operator/config/openshift-knative/eventing-istio/openshift-knative-eventing-istio-release-v1.8__413.yaml
  ci-operator/config/openshift-knative/eventing-istio/openshift-knative-eventing-istio-release-v1.9__410.yaml
  ci-operator/config/openshift-knative/eventing-istio/openshift-knative-eventing-istio-release-v1.9__413.yaml
  ci-operator/config/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-next__411.yaml
  ci-operator/config/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-next__413.yaml
  ci-operator/config/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.10__410.yaml
  ci-operator/config/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.10__413.yaml
  ci-operator/config/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.11__411.yaml
  ci-operator/config/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.11__413.yaml
  ci-operator/config/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.6__412.yaml
  ci-operator/config/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.6__48.yaml
  ci-operator/config/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.7__412.yaml
  ci-operator/config/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.7__48.yaml
  ci-operator/config/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.8__410.yaml
  ci-operator/config/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.8__413.yaml
  ci-operator/config/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.9__410.yaml
  ci-operator/config/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.9__413.yaml
  ci-operator/config/openshift-knative/eventing/openshift-knative-eventing-release-next__411.yaml
  ci-operator/config/openshift-knative/eventing/openshift-knative-eventing-release-next__413.yaml
  ci-operator/config/openshift-knative/eventing/openshift-knative-eventing-release-v1.10__410.yaml
  ci-operator/config/openshift-knative/eventing/openshift-knative-eventing-release-v1.10__413.yaml
  ci-operator/config/openshift-knative/eventing/openshift-knative-eventing-release-v1.11__411.yaml
  ci-operator/config/openshift-knative/eventing/openshift-knative-eventing-release-v1.11__413.yaml
  ci-operator/config/openshift-knative/eventing/openshift-knative-eventing-release-v1.6__412.yaml
  ci-operator/config/openshift-knative/eventing/openshift-knative-eventing-release-v1.6__48.yaml
  ci-operator/config/openshift-knative/eventing/openshift-knative-eventing-release-v1.7__412.yaml
  ci-operator/config/openshift-knative/eventing/openshift-knative-eventing-release-v1.7__48.yaml
  ci-operator/config/openshift-knative/eventing/openshift-knative-eventing-release-v1.8__410.yaml
  ci-operator/config/openshift-knative/eventing/openshift-knative-eventing-release-v1.8__413.yaml
  ci-operator/config/openshift-knative/eventing/openshift-knative-eventing-release-v1.9__410.yaml
  ci-operator/config/openshift-knative/eventing/openshift-knative-eventing-release-v1.9__413.yaml
  ci-operator/config/openshift-knative/serving/openshift-knative-serving-release-next__411.yaml
  ci-operator/config/openshift-knative/serving/openshift-knative-serving-release-next__413.yaml
  ci-operator/config/openshift-knative/serving/openshift-knative-serving-release-v1.10__410.yaml
  ci-operator/config/openshift-knative/serving/openshift-knative-serving-release-v1.10__413.yaml
  ci-operator/config/openshift-knative/serving/openshift-knative-serving-release-v1.11__410.yaml
  ci-operator/config/openshift-knative/serving/openshift-knative-serving-release-v1.11__413.yaml
  ci-operator/config/openshift-knative/serving/openshift-knative-serving-release-v1.8__410.yaml
  ci-operator/config/openshift-knative/serving/openshift-knative-serving-release-v1.8__413.yaml
  ci-operator/config/openshift-knative/serving/openshift-knative-serving-release-v1.9__410.yaml
  ci-operator/config/openshift-knative/serving/openshift-knative-serving-release-v1.9__413.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#43868 MGMT-15888: build for s390x at upstream images
  ci-operator/step-registry/assisted/tools/multi-arch/publish/assisted-tools-multi-arch-publish-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#43882 `tide`: Use apps authentication method
  clusters/app.ci/prow/03_deployment/tide.yaml
Labels: lgtm, approved, rehearsals-ack

#43873 [knative-client] Add CI jobs for release-v1.10 branch
  ci-operator/config/openshift-knative/client/openshift-knative-client-release-v1.10.yaml
  ci-operator/jobs/openshift-knative/client/openshift-knative-client-release-v1.10-postsubmits.yaml
  ci-operator/jobs/openshift-knative/client/openshift-knative-client-release-v1.10-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#43849 ROX-17348: ocp4.14 nightlies fix base
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies__ocp-4-14.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-nightlies-postsubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#43889 Add secret/registry-push-credentials-ci-images-mirror
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#43877 Increase TGIS build memory to avoid oom situation
  ci-operator/config/opendatahub-io/text-generation-inference/opendatahub-io-text-generation-inference-main.yaml
Labels: lgtm, approved, rehearsals-ack

#43879 Experiment using INT TERM instead of EXIT for trap
  ci-operator/step-registry/observers/resource-watch/observers-resource-watch-commands.sh
Labels: lgtm, approved, rehearsals-ack

#43891 add `token_image-pusher_app.ci_reg_auth_value.txt` to `app.ci`
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#43450 Replace CNV smoke tests with e2e tests
  ci-operator/config/RedHatQE/interop-testing/OWNERS
  ci-operator/config/RedHatQE/interop-testing/RedHatQE-interop-testing-cnv-4.11__ocp-cnv-odf-4.11.yaml
  ci-operator/config/RedHatQE/interop-testing/RedHatQE-interop-testing-cnv-4.12__ocp-cnv-odf-4.12.yaml
  ci-operator/config/RedHatQE/interop-testing/RedHatQE-interop-testing-cnv-4.13__ocp-cnv-odf-4.13.yaml
  ci-operator/jobs/RedHatQE/cnv-tests/RedHatQE-cnv-tests-main-periodics.yaml
  ci-operator/jobs/RedHatQE/interop-testing/RedHatQE-interop-testing-cnv-4.11-periodics.yaml
  ci-operator/jobs/RedHatQE/interop-testing/RedHatQE-interop-testing-cnv-4.11-presubmits.yaml
  ci-operator/jobs/RedHatQE/interop-testing/RedHatQE-interop-testing-cnv-4.12-periodics.yaml
  ci-operator/jobs/RedHatQE/interop-testing/RedHatQE-interop-testing-cnv-4.12-presubmits.yaml
  ci-operator/jobs/RedHatQE/interop-testing/RedHatQE-interop-testing-cnv-4.13-periodics.yaml
  ci-operator/jobs/RedHatQE/interop-testing/RedHatQE-interop-testing-cnv-4.13-presubmits.yaml
  ci-operator/step-registry/interop-tests/cnv-tests-e2e-deploy/OWNERS
  ci-operator/step-registry/interop-tests/cnv-tests-e2e-deploy/interop-tests-cnv-tests-e2e-deploy-commands.sh
  ci-operator/step-registry/interop-tests/cnv-tests-e2e-deploy/interop-tests-cnv-tests-e2e-deploy-ref.metadata.json
  ci-operator/step-registry/interop-tests/cnv-tests-e2e-deploy/interop-tests-cnv-tests-e2e-deploy-ref.yaml
  ci-operator/step-registry/interop-tests/deploy-odf/interop-tests-deploy-odf-commands.sh
  ci-operator/step-registry/interop-tests/deploy-odf/interop-tests-deploy-odf-ref.yaml
  ci-operator/step-registry/interop-tests/ocs-tests/interop-tests-ocs-tests-commands.sh
  ci-operator/step-registry/interop-tests/ocs-tests/interop-tests-ocs-tests-ref.yaml
  core-services/prow/02_config/RedHatQE/interop-testing/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#43890 use bot auth with `crier` to free up tokens for tide
  clusters/app.ci/prow/03_deployment/crier.yaml
Labels: lgtm, approved, rehearsals-ack

#43888 Remove router-perf tests
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__gcp-4.13-nightly-x86.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-periodics.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#43893 jira-lifecycle-plugin: add premerge bug configs
  core-services/jira-lifecycle-plugin/config.yaml
Labels: lgtm, approved, rehearsals-ack

#43837 CRC: Update go version to 1.20
  ci-operator/config/crc-org/crc/crc-org-crc-main.yaml
Labels: lgtm, approved, rehearsals-ack

#43881 MGMT-15773: decrease the usage of jobs in ocm-2.7 branch
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.5.yaml
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.5__mce.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.5.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.5__mce.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.6.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.5.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.5__mce.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.5.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.5__mce.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.6.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.7.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.5.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.6.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.7.yaml
  ci-operator/config/openshift/cluster-api-provider-agent/openshift-cluster-api-provider-agent-release-ocm-2.5.yaml
  ci-operator/config/openshift/cluster-api-provider-agent/openshift-cluster-api-provider-agent-release-ocm-2.5__mce.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.5-periodics.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.5-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.5-presubmits.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.5-periodics.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.5-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.5-presubmits.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.6-periodics.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.5-periodics.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.5-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.5-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.5-periodics.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.5-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.5-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.6-periodics.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.7-periodics.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.5-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.5-presubmits.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.6-periodics.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.7-periodics.yaml
  ci-operator/jobs/openshift/cluster-api-provider-agent/openshift-cluster-api-provider-agent-release-ocm-2.5-periodics.yaml
  ci-operator/jobs/openshift/cluster-api-provider-agent/openshift-cluster-api-provider-agent-release-ocm-2.5-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-agent/openshift-cluster-api-provider-agent-release-ocm-2.5-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#43365 openstack: Ensure resource names are configured
  ci-operator/step-registry/ipi/conf/openstack/cgroupsv1/ipi-conf-openstack-cgroupsv1-chain.yaml
  ci-operator/step-registry/ipi/conf/openstack/noramfs/ipi-conf-openstack-noramfs-chain.yaml
  ci-operator/step-registry/openshift/manifests/openstack/openshift-manifests-openstack-workflow.yaml
  ci-operator/step-registry/openstack/conf/clouds/openstack-conf-clouds-commands.sh
  ci-operator/step-registry/shiftstack/cleanup/shiftstack-cleanup-workflow.yaml
  ci-operator/step-registry/shiftstack/liveliness/shiftstack-liveliness-workflow.yaml
  ci-operator/step-registry/shiftstack/monitor/shiftstack-monitor-workflow.yaml
  ci-operator/step-registry/shiftstack/quotas/shiftstack-quotas-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#42456 Fix: Linux default env USER is inherit into Makefile
  Makefile
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#43799 mirror rhsso test image to ci registry
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_ci
Labels: lgtm, approved, rehearsals-ack

#43908 use apps-auth with crier
  clusters/app.ci/prow/03_deployment/crier.yaml
Labels: lgtm, approved, rehearsals-ack

#43797 Add not@workloads tag for profile baselinecaps-v412
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly.yaml
Labels: lgtm, approved, rehearsals-ack

#43459 Ingress/Router performance test
  ci-operator/config/openshift/router/openshift-router-master.yaml
  ci-operator/jobs/openshift/router/openshift-router-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#43910 MSI - add option to collect must-gather
  ci-operator/step-registry/cluster/install/cluster-install-commands.sh
  ci-operator/step-registry/cluster/install/cluster-install-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#43831 Remove prefixes
  ci-operator/step-registry/openshift-qe/cluster-density-v2/openshift-qe-cluster-density-v2-commands.sh
  ci-operator/step-registry/openshift-qe/control-plane-smoke/openshift-qe-control-plane-smoke-commands.sh
  ci-operator/step-registry/openshift-qe/ingress-perf/openshift-qe-ingress-perf-commands.sh
  ci-operator/step-registry/openshift-qe/network-perf/openshift-qe-network-perf-commands.sh
  ci-operator/step-registry/openshift-qe/network-policy/openshift-qe-network-policy-commands.sh
  ci-operator/step-registry/openshift-qe/network-smoke/openshift-qe-network-smoke-commands.sh
  ci-operator/step-registry/openshift-qe/node-density-cni/openshift-qe-node-density-cni-commands.sh
  ci-operator/step-registry/openshift-qe/node-density-heavy/openshift-qe-node-density-heavy-commands.sh
  ci-operator/step-registry/openshift-qe/node-density/openshift-qe-node-density-commands.sh
  ci-operator/step-registry/openshift-qe/router-perf/openshift-qe-router-perf-commands.sh
Labels: lgtm, approved, rehearsals-ack

#43900 add more users to etcd so that they can add cherry-pick-approved labels
  core-services/prow/02_config/openshift/cluster-etcd-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/etcd/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#43916 Update cron and test name for conc tests.
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.13-nightly-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.14-nightly-x86.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#43923 MIXEDARCH-271: change the slice from au-syd to us-south
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#43926 Revert "mirror rhsso test image to ci registry"
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_ci
Labels: lgtm, approved, rehearsals-ack

#43925 add manifest-tool-local-pusher secret
  ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-master-presubmits.yaml
  ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-release-4.14-presubmits.yaml
  ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-release-4.16-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#43933 ci-tools: use_build_cache=false
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
Labels: lgtm, approved, rehearsals-ack

#43705 feat: use upstream e2e tests in CI
  ci-operator/config/openshift-power-monitoring/kepler-operator/openshift-power-monitoring-kepler-operator-v1alpha1.yaml
  ci-operator/config/openshift-power-monitoring/kepler-operator/openshift-power-monitoring-kepler-operator-v1alpha1__post-submits-aws.yaml
  ci-operator/config/openshift-power-monitoring/kepler-operator/openshift-power-monitoring-kepler-operator-v1alpha1__post-submits-gcp.yaml
  ci-operator/step-registry/openshift-power-monitoring/install/OWNERS
  ci-operator/step-registry/openshift-power-monitoring/install/kepler/OWNERS
  ci-operator/step-registry/openshift-power-monitoring/install/kepler/openshift-power-monitoring-install-kepler-commands.sh
  ci-operator/step-registry/openshift-power-monitoring/install/kepler/openshift-power-monitoring-install-kepler-ref.metadata.json
  ci-operator/step-registry/openshift-power-monitoring/install/kepler/openshift-power-monitoring-install-kepler-ref.yaml
  ci-operator/step-registry/openshift-power-monitoring/tests/kepler/openshift-power-monitoring-tests-kepler-commands.sh
  ci-operator/step-registry/openshift-power-monitoring/tests/kepler/openshift-power-monitoring-tests-kepler-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#43902 feat: CI skip when changes in tests/release/pipelines, according to RHTAPREL-373
  ci-operator/config/redhat-appstudio/e2e-tests/redhat-appstudio-e2e-tests-main.yaml
  ci-operator/jobs/redhat-appstudio/e2e-tests/redhat-appstudio-e2e-tests-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#43907 `crier` uses more memory than current request
  clusters/app.ci/prow/03_deployment/crier.yaml
Labels: lgtm, approved, rehearsals-ack

#43931 Remove base image override
  ci-operator/config/opendatahub-io/caikit-tgis-serving/opendatahub-io-caikit-tgis-serving-main.yaml
Labels: lgtm, approved, rehearsals-ack

#43561 LPTOCPCI-712: Fix junit reporting for service registry
  ci-operator/step-registry/service-registry/run-tests/service-registry-run-tests-commands.sh
  ci-operator/step-registry/service-registry/run-tests/service-registry-run-tests-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#43939 Add Distributed Tracing stage testing jobs
  ci-operator/config/jaegertracing/jaeger-operator/jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.11-stage.yaml
  ci-operator/config/jaegertracing/jaeger-operator/jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.12-stage.yaml
  ci-operator/config/jaegertracing/jaeger-operator/jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.13-stage.yaml
  ci-operator/config/jaegertracing/jaeger-operator/jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.14-stage.yaml
  ci-operator/config/jaegertracing/jaeger-operator/jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.15-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.11-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.12-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.13-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.14-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.15-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.11-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.12-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.13-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.14-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.15-stage.yaml
  ci-operator/jobs/jaegertracing/jaeger-operator/jaegertracing-jaeger-operator-main-periodics.yaml
  ci-operator/jobs/jaegertracing/jaeger-operator/jaegertracing-jaeger-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main-periodics.yaml
  ci-operator/jobs/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main-periodics.yaml
  ci-operator/jobs/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#43955 app.ci: Add scos-4.15 IS
  clusters/app.ci/supplemental-ci-images/okd/scos.yaml
Labels: lgtm, approved, rehearsals-ack

#43751 enable pr-reminders for monitoring team
  core-services/pr-reminder/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#43364 ROX-19449: Run GKE-based operator e2e tests on merge too
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-x.y.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-postsubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-x.y-postsubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-x.y-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#43952 Agent-716: Add must gather chain
  ci-operator/step-registry/cucushift/agent/vsphere/disconnected/deprovision/cucushift-agent-vsphere-disconnected-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/agent/vsphere/install/compact/cucushift-agent-vsphere-install-compact-workflow.yaml
  ci-operator/step-registry/cucushift/agent/vsphere/install/ha/cucushift-agent-vsphere-install-ha-workflow.yaml
  ci-operator/step-registry/cucushift/agent/vsphere/install/sno/cucushift-agent-vsphere-install-sno-workflow.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#43964 [ClusterBot] Adding manifest-tool secret
  ci-operator/jobs/openshift/release/openshift-release-infra-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#43935 Revert "ci-tools: use_build_cache=false (#43933)"
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
Labels: lgtm, approved, rehearsals-ack

#43969 OSSM maistra add a seperate hypershift workflow
  ci-operator/step-registry/servicemesh/istio/e2e/hypershift/OWNERS
  ci-operator/step-registry/servicemesh/istio/e2e/hypershift/servicemesh-istio-e2e-hypershift-workflow.metadata.json
  ci-operator/step-registry/servicemesh/istio/e2e/hypershift/servicemesh-istio-e2e-hypershift-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#43914 [PERFSCALE-2513] Update the timeout
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.13-nightly-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.14-nightly-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa-4.12-nightly-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa-4.13-nightly-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa-4.14-nightly-x86.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-periodics.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#43970 OADP-master: Removee ocp version 4.10
  ci-operator/config/openshift/oadp-operator/openshift-oadp-operator-master__4.10.yaml
  ci-operator/jobs/openshift/oadp-operator/openshift-oadp-operator-master-periodics.yaml
  ci-operator/jobs/openshift/oadp-operator/openshift-oadp-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/oadp-operator/openshift-oadp-operator-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#43973 Remove warning about using multi payloads for stable releases
  core-services/release-controller/_releases/release-ocp-4.y-stable-multi.json
Labels: lgtm, approved, rehearsals-ack

#43901 oadp: adding oadp-1.2 to the interop testing
  ci-operator/config/oadp-qe/oadp-e2e-qe/oadp-qe-oadp-e2e-qe-release-v1.2.yaml
  ci-operator/config/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-main__oadp1.2-ocp4.13-lp-interop.yaml
  ci-operator/config/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-main__oadp1.2-ocp4.14-lp-interop.yaml
  ci-operator/jobs/oadp-qe/oadp-e2e-qe/oadp-qe-oadp-e2e-qe-release-v1.2-postsubmits.yaml
  ci-operator/jobs/oadp-qe/oadp-e2e-qe/oadp-qe-oadp-e2e-qe-release-v1.2-presubmits.yaml
  ci-operator/jobs/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-main-periodics.yaml
  ci-operator/jobs/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#43947 [release-1.31] Initialize Serverless Operator CI config
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.31__4.10.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.31__4.13-aws-ovn.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.31__4.13-azure.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.31__4.13-gcp.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.31__4.13-hypershift.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.31__4.13-osd.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.31__4.13-single-node.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.31__4.13-vsphere.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.31__4.13.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.31__ocp4.14-lp-interop.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.31-postsubmits.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.31-presubmits.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#43963 release-controller: Remove broken verification tests
  core-services/release-controller/_releases/release-okd-4.y-stable.json
  core-services/release-controller/_releases/release-okd-scos-4.y-next.json
  core-services/release-controller/_releases/release-okd-scos-4.y-stable.json
Labels: lgtm, approved, rehearsals-ack

#43886 Update: incubation to trigger prow in CI
  ci-operator/config/opendatahub-io/opendatahub-operator/opendatahub-io-opendatahub-operator-incubation.yaml
  ci-operator/jobs/opendatahub-io/opendatahub-operator/opendatahub-io-opendatahub-operator-incubation-postsubmits.yaml
  ci-operator/jobs/opendatahub-io/opendatahub-operator/opendatahub-io-opendatahub-operator-incubation-presubmits.yaml
  core-services/prow/02_config/opendatahub-io/opendatahub-operator/_pluginconfig.yaml
  core-services/prow/02_config/opendatahub-io/opendatahub-operator/_prowconfig.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#43638 osde2e: bump go version and prune unused base_images
  ci-operator/config/openshift/osde2e/openshift-osde2e-main.yaml
  ci-operator/config/openshift/osde2e/openshift-osde2e-main__nightly-4.10.yaml
  ci-operator/config/openshift/osde2e/openshift-osde2e-main__nightly-4.11.yaml
  ci-operator/config/openshift/osde2e/openshift-osde2e-main__nightly-4.12.yaml
  ci-operator/config/openshift/osde2e/openshift-osde2e-main__nightly-4.13.yaml
  ci-operator/config/openshift/osde2e/openshift-osde2e-main__nightly-4.14.yaml
  ci-operator/config/openshift/osde2e/openshift-osde2e-main__nightly-4.15.yaml
Labels: lgtm, approved, rehearsals-ack

#43965 Add bmangoen to maistra-approvers & maistra-reviewers
  OWNERS_ALIASES
Labels: lgtm, approved, rehearsals-ack

#43976 OSSM-4884: Create a job for scorecard test
  ci-operator/config/maistra/istio-operator/maistra-istio-operator-maistra-3.0.yaml
  ci-operator/jobs/maistra/istio-operator/maistra-istio-operator-maistra-3.0-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#43980 Add dex-rh-sso for build09
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#43983 Simplify the names for operator jobs
  ci-operator/config/maistra/istio-operator/maistra-istio-operator-maistra-3.0.yaml
  ci-operator/jobs/maistra/istio-operator/maistra-istio-operator-maistra-3.0-periodics.yaml
  ci-operator/jobs/maistra/istio-operator/maistra-istio-operator-maistra-3.0-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#43927 add `known-infra-file` args to `ci-operator-prowgen` usages
  Makefile
  hack/validate-generated-config.sh
Labels: lgtm, approved, rehearsals-ack

#43826 CORS-2843: openshift-installer altinfra variant
  ci-operator/config/openshift/installer/openshift-installer-master__altinfra.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-postsubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#43897 Rename openstack-machine-controllers to openstack-cluster-api-controllers
  ci-operator/config/openshift/cluster-api-provider-openstack/openshift-cluster-api-provider-openstack-main.yaml
  core-services/image-mirroring/openshift/mapping_origin_4_15
Labels: lgtm, approved, rehearsals-ack

#43912 main cloud bulldozer with specific kube burner version
  ci-operator/step-registry/openshift-qe/conc-builds/openshift-qe-conc-builds-commands.sh
Labels: lgtm, approved, rehearsals-ack

#43930 Update opendatahub-io-text-generation-inference-release.yaml
  ci-operator/config/opendatahub-io/text-generation-inference/opendatahub-io-text-generation-inference-release.yaml
Labels: lgtm, approved, rehearsals-ack

#43985 Remove old test versions for OADP and add slack configuration.
  ci-operator/config/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-main__oadp1.1-ocp4.13-lp-interop.yaml
  ci-operator/config/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-main__oadp1.1-ocp4.14-lp-interop.yaml
  ci-operator/config/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-main__oadp1.2-ocp4.13-lp-interop.yaml
  ci-operator/jobs/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-main-periodics.yaml
  ci-operator/jobs/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#43978 Cni output
  ci-operator/step-registry/openshift-qe/cluster-density-v2/openshift-qe-cluster-density-v2-commands.sh
  ci-operator/step-registry/openshift-qe/conc-builds/openshift-qe-conc-builds-commands.sh
  ci-operator/step-registry/openshift-qe/ingress-perf/openshift-qe-ingress-perf-commands.sh
  ci-operator/step-registry/openshift-qe/network-perf/openshift-qe-network-perf-commands.sh
  ci-operator/step-registry/openshift-qe/network-policy/openshift-qe-network-policy-commands.sh
  ci-operator/step-registry/openshift-qe/node-density-cni/openshift-qe-node-density-cni-commands.sh
  ci-operator/step-registry/openshift-qe/node-density-heavy/openshift-qe-node-density-heavy-commands.sh
  ci-operator/step-registry/openshift-qe/node-density/openshift-qe-node-density-commands.sh
  ci-operator/step-registry/openshift-qe/router-perf/openshift-qe-router-perf-commands.sh
Labels: lgtm, approved, rehearsals-ack

#43953 [ODH] Drop PyTorch and TensorFlow notebooks from 2023b branch
  ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-2023b.yaml
  ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-main.yaml
  ci-operator/jobs/opendatahub-io/notebooks/opendatahub-io-notebooks-2023b-postsubmits.yaml
  ci-operator/jobs/opendatahub-io/notebooks/opendatahub-io-notebooks-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#43997 MSI - remove cron from some jobs
  ci-operator/config/CSPI-QE/MSI/CSPI-QE-MSI-cluster-install-uninstall.yaml
  ci-operator/config/CSPI-QE/MSI/CSPI-QE-MSI-multi-cluster-smoke__v4.13.yaml
  ci-operator/jobs/CSPI-QE/MSI/CSPI-QE-MSI-cluster-install-uninstall-periodics.yaml
  ci-operator/jobs/CSPI-QE/MSI/CSPI-QE-MSI-cluster-install-uninstall-presubmits.yaml
  ci-operator/jobs/CSPI-QE/MSI/CSPI-QE-MSI-multi-cluster-smoke-periodics.yaml
  ci-operator/jobs/CSPI-QE/MSI/CSPI-QE-MSI-multi-cluster-smoke-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#43941 [cnv-fbc] Configure tide
  core-services/prow/02_config/openshift-cnv/cnv-fbc/OWNERS
  core-services/prow/02_config/openshift-cnv/cnv-fbc/_pluginconfig.yaml
  core-services/prow/02_config/openshift-cnv/cnv-fbc/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#43948 MULTIARCH-3788: Add lease config for hypershift powervs
  core-services/ci-secret-bootstrap/_config.yaml
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#43956 Add pipeline-controller deployment and modify img job
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
  clusters/app.ci/prow/03_deployment/admin_pipeline-controller_rbac.yaml
  clusters/app.ci/prow/03_deployment/pipeline-controller.yaml
Labels: lgtm, approved, rehearsals-ack

#44002 Use rhel-8-golang-1.20-openshift-4.14 and 4.14 CLI image
  ci-operator/config/jaegertracing/jaeger-operator/jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.11-stage.yaml
  ci-operator/config/jaegertracing/jaeger-operator/jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.12-stage.yaml
  ci-operator/config/jaegertracing/jaeger-operator/jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.13-stage.yaml
  ci-operator/config/jaegertracing/jaeger-operator/jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.15-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.11-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.12-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.13-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.15-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.11-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.12-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.13-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.15-stage.yaml
Labels: lgtm, approved, rehearsals-ack

#43986 openstack/nfv: find PCI address using sriovnetworknodestates
  ci-operator/step-registry/openstack/test/dpdk/openstack-test-dpdk-commands.sh
  ci-operator/step-registry/openstack/test/sriov/openstack-test-sriov-commands.sh
Labels: lgtm, approved, rehearsals-ack

#43992 shiftstack/ci-configs: remove useless test
  ci-operator/config/shiftstack/ci-configs/shiftstack-ci-configs-main.yaml
  ci-operator/jobs/shiftstack/ci-configs/shiftstack-ci-configs-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#43967 feat: rhtap e2e: add slack bot token
  ci-operator/step-registry/redhat-appstudio/e2e/redhat-appstudio-e2e-commands.sh
Labels: lgtm, approved, rehearsals-ack

#38586 [LPTOCPCI-163] - Fuse On Openshift interop onboarding over Openshift CI
  OWNERS_ALIASES
  ci-operator/config/jboss-fuse/fuse-xpaas-qe-container/OWNERS
  ci-operator/config/jboss-fuse/fuse-xpaas-qe-container/README.md
  ci-operator/config/jboss-fuse/fuse-xpaas-qe-container/jboss-fuse-fuse-xpaas-qe-container-main__jboss-fuse-ocp4.14-lp-interop.yaml
  ci-operator/jobs/jboss-fuse/fuse-xpaas-qe-container/OWNERS
  ci-operator/jobs/jboss-fuse/fuse-xpaas-qe-container/jboss-fuse-fuse-xpaas-qe-container-main-periodics.yaml
  ci-operator/step-registry/jboss-fuse/OWNERS
  ci-operator/step-registry/jboss-fuse/deploy-resources/OWNERS
  ci-operator/step-registry/jboss-fuse/deploy-resources/README.md
  ci-operator/step-registry/jboss-fuse/deploy-resources/jboss-fuse-deploy-resources-commands.sh
  ci-operator/step-registry/jboss-fuse/deploy-resources/jboss-fuse-deploy-resources-ref.metadata.json
  ci-operator/step-registry/jboss-fuse/deploy-resources/jboss-fuse-deploy-resources-ref.yaml
  ci-operator/step-registry/jboss-fuse/run-tests/OWNERS
  ci-operator/step-registry/jboss-fuse/run-tests/README.md
  ci-operator/step-registry/jboss-fuse/run-tests/jboss-fuse-run-tests-commands.sh
  ci-operator/step-registry/jboss-fuse/run-tests/jboss-fuse-run-tests-ref.metadata.json
  ci-operator/step-registry/jboss-fuse/run-tests/jboss-fuse-run-tests-ref.yaml
  core-services/prow/02_config/jboss-fuse/fuse-xpaas-qe-container/_pluginconfig.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#44000 ROX-19728: Run prow jobs for stage branch too.
  ci-operator/config/stackrox/acs-fleet-manager/stackrox-acs-fleet-manager-stage.yaml
  ci-operator/jobs/stackrox/acs-fleet-manager/stackrox-acs-fleet-manager-stage-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#44007 cluster-api-provider-ibmcloud: remove e2e techpreview job
  ci-operator/config/openshift/cluster-api-provider-ibmcloud/openshift-cluster-api-provider-ibmcloud-main.yaml
  ci-operator/config/openshift/cluster-api-provider-ibmcloud/openshift-cluster-api-provider-ibmcloud-release-4.14.yaml
  ci-operator/config/openshift/cluster-api-provider-ibmcloud/openshift-cluster-api-provider-ibmcloud-release-4.15.yaml
  ci-operator/config/openshift/cluster-api-provider-ibmcloud/openshift-cluster-api-provider-ibmcloud-release-4.16.yaml
  ci-operator/jobs/openshift/cluster-api-provider-ibmcloud/openshift-cluster-api-provider-ibmcloud-main-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-ibmcloud/openshift-cluster-api-provider-ibmcloud-release-4.14-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-ibmcloud/openshift-cluster-api-provider-ibmcloud-release-4.15-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-ibmcloud/openshift-cluster-api-provider-ibmcloud-release-4.16-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#43977 Update the wildfly/quickstart branches
  ci-operator/config/wildfly/quickstart/wildfly-quickstart-main.yaml
  ci-operator/jobs/wildfly/quickstart/wildfly-quickstart-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#43995 Update RHODS notebook main and 2023a branch to build habana based images
  ci-operator/config/red-hat-data-services/notebooks/red-hat-data-services-notebooks-main.yaml
  ci-operator/config/red-hat-data-services/notebooks/red-hat-data-services-notebooks-release-2023a.yaml
  ci-operator/jobs/red-hat-data-services/notebooks/red-hat-data-services-notebooks-main-postsubmits.yaml
  ci-operator/jobs/red-hat-data-services/notebooks/red-hat-data-services-notebooks-release-2023a-postsubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#43972 Increase aggregator timeout since lots of GCP jobs are running tight …
  ci-operator/step-registry/openshift/release/analysis/aggregator/openshift-release-analysis-aggregator-commands.sh
  ci-operator/step-registry/openshift/release/analysis/prpqr-aggregator/openshift-release-analysis-prpqr-aggregator-commands.sh
Labels: lgtm, approved, rehearsals-ack

#40488 add ODF and acm-must-gather to the OPP job
  ci-operator/config/stolostron/policy-collection/stolostron-policy-collection-main__opp-ocp4.13-interop.yaml
  ci-operator/step-registry/interop-tests/ocs-tests/interop-tests-ocs-tests-commands.sh
Labels: lgtm, approved, rehearsals-ack

#44013 CAPO: Use KUBEBUILDER_ASSETS_DIR instead of XDG_DATA_HOME
  ci-operator/config/openshift/cluster-api-provider-openstack/openshift-cluster-api-provider-openstack-main.yaml
Labels: lgtm, approved, rehearsals-ack

#44019 Remove auto lgtm for openshift-velero-plugin
  core-services/prow/02_config/openshift/openshift-velero-plugin/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#43602 Add a script that collects some data on OPP environment being tested
  ci-operator/config/stolostron/policy-collection/stolostron-policy-collection-main__opp-ocp4.13-interop.yaml
  ci-operator/step-registry/acm/fetch-operator-versions/OWNERS
  ci-operator/step-registry/acm/fetch-operator-versions/README.md
  ci-operator/step-registry/acm/fetch-operator-versions/acm-fetch-operator-versions-commands.sh
  ci-operator/step-registry/acm/fetch-operator-versions/acm-fetch-operator-versions-ref.metadata.json
  ci-operator/step-registry/acm/fetch-operator-versions/acm-fetch-operator-versions-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#43962 OSSM-4818 Use upstream build image for istio-operator
  ci-operator/config/maistra/istio-operator/maistra-istio-operator-maistra-3.0.yaml
  ci-operator/jobs/maistra/istio-operator/maistra-istio-operator-maistra-3.0-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#44021 OSSM-4169 maistra setup operator 2.5 CI jobs
  ci-operator/config/maistra/istio-operator/maistra-istio-operator-maistra-2.5.yaml
  ci-operator/jobs/maistra/istio-operator/maistra-istio-operator-maistra-2.5-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#43989 update capk e2e test config
  ci-operator/step-registry/hypershift/kubevirt/e2e/capk/hypershift-kubevirt-e2e-capk-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#43887 Azure oidc no longer needs TechPreviewNoUpgrade
  ci-operator/step-registry/ipi/conf/azure/oidc-creds-provision/ipi-conf-azure-oidc-creds-provision-commands.sh
  ci-operator/step-registry/openshift/e2e/azure/manual-oidc-workload-identity/openshift-e2e-azure-manual-oidc-workload-identity-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#43876 NO-ISSUE: Remove ushift periodics from 4.15 and 4.16
  ci-operator/config/openshift/microshift/openshift-microshift-release-4.15.yaml
  ci-operator/config/openshift/microshift/openshift-microshift-release-4.16.yaml
  ci-operator/jobs/openshift/microshift/openshift-microshift-release-4.15-periodics.yaml
  ci-operator/jobs/openshift/microshift/openshift-microshift-release-4.16-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#44003 NO-ISSUE: Fix conformance nightly for 4.14
  ci-operator/config/openshift/microshift/openshift-microshift-release-4.14.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#44024 sriov-networknodepolicy: print state before creating policies
  ci-operator/step-registry/openstack/provision/sriov-networknodepolicy/openstack-provision-sriov-networknodepolicy-commands.sh
Labels: lgtm, approved, rehearsals-ack

#42899 OPNET-329: add DualStackIPv6Primary for vSphere
  ci-operator/config/openshift-priv/cluster-network-operator/openshift-priv-cluster-network-operator-master.yaml
  ci-operator/config/openshift-priv/cluster-network-operator/openshift-priv-cluster-network-operator-release-4.14.yaml
  ci-operator/config/openshift-priv/cluster-network-operator/openshift-priv-cluster-network-operator-release-4.15.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-master.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.14.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.15.yaml
  ci-operator/jobs/openshift-priv/cluster-network-operator/openshift-priv-cluster-network-operator-master-presubmits.yaml
  ci-operator/jobs/openshift-priv/cluster-network-operator/openshift-priv-cluster-network-operator-release-4.14-presubmits.yaml
  ci-operator/jobs/openshift-priv/cluster-network-operator/openshift-priv-cluster-network-operator-release-4.15-presubmits.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.14-presubmits.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.15-presubmits.yaml
  ci-operator/jobs/openshift/release/openshift-release-infra-periodics.yaml
  ci-operator/step-registry/ovn/conf/vsphere-dualstack/ovn-conf-vsphere-dualstack-commands.sh
  ci-operator/step-registry/ovn/conf/vsphere-dualstack/ovn-conf-vsphere-dualstack-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#44023 Add job for kind integration tests
  ci-operator/config/maistra/istio-operator/maistra-istio-operator-maistra-3.0.yaml
  ci-operator/jobs/maistra/istio-operator/maistra-istio-operator-maistra-3.0-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#44029 wmco: opt into 2-stage pipelines
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-master.yaml
  ci-operator/jobs/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-master-presubmits.yaml
  core-services/prow/02_config/openshift/windows-machine-config-operator/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#43895 GitOps | Updating version to v1.10
  ci-operator/config/redhat-developer/gitops-operator/redhat-developer-gitops-operator-v1.10__gitops-ocp4.14-lp-interop.yaml
  ci-operator/jobs/redhat-developer/gitops-operator/redhat-developer-gitops-operator-v1.10-periodics.yaml
  ci-operator/jobs/redhat-developer/gitops-operator/redhat-developer-gitops-operator-v1.10-presubmits.yaml
  ci-operator/jobs/redhat-developer/gitops-operator/redhat-developer-gitops-operator-v1.9-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#44028 Add ci for RHODS-1.34 caikit-tgis-serving
  ci-operator/config/red-hat-data-services/caikit-tgis-serving/red-hat-data-services-caikit-tgis-serving-rhods-1.34.yaml
  ci-operator/jobs/red-hat-data-services/caikit-tgis-serving/red-hat-data-services-caikit-tgis-serving-rhods-1.34-postsubmits.yaml
  ci-operator/jobs/red-hat-data-services/caikit-tgis-serving/red-hat-data-services-caikit-tgis-serving-rhods-1.34-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#43592 [odf-must-gather] Update job with upstream changes
  ci-operator/config/red-hat-storage/odf-must-gather/red-hat-storage-odf-must-gather-main.yaml
  ci-operator/jobs/red-hat-storage/odf-must-gather/red-hat-storage-odf-must-gather-main-presubmits.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#44031 MSI - Update path to ocp_addons_operators_cli code
  ci-operator/step-registry/addon/install/addon-install-commands.sh
  ci-operator/step-registry/addon/uninstall/addon-uninstall-commands.sh
  ci-operator/step-registry/operator/install/operator-install-commands.sh
  ci-operator/step-registry/operator/uninstall/operator-uninstall-commands.sh
Labels: lgtm, approved, rehearsals-ack

#44036 fix(stackrox): remove sensor-profiling job run_if_changed trigger from config manually
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#44034 Remove installer-e2e-aws-csi jobs
  ci-operator/jobs/openshift/release/openshift-release-release-4.10-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.11-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.12-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.14-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.15-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.8-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.9-periodics.yaml
  ci-operator/templates/openshift/installer/cluster-launch-installer-custom-test-image.yaml
  core-services/prow/02_config/_plugins.yaml
  core-services/template-deprecation/_allowlist.yaml
Labels: lgtm, approved, rehearsals-ack

#44041 Revert "Restore kdump step for ovn-rt job."
  ci-operator/step-registry/ipi/conf/debug/kdump-gather-logs/ipi-conf-debug-kdump-gather-logs-commands.sh
  ci-operator/step-registry/ipi/libvirt/post/ipi-libvirt-post-chain.yaml
  ci-operator/step-registry/openshift/upgrade/gcp/ovn-rt/openshift-upgrade-gcp-ovn-rt-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#44042 [release-controller] Bumping CLI image to version supporting manifest lists
  core-services/release-controller/_releases/release-ocp-4-dev-preview-arm64.json
  core-services/release-controller/_releases/release-ocp-4-dev-preview-multi.json
  core-services/release-controller/_releases/release-ocp-4-dev-preview-ppc64le.json
  core-services/release-controller/_releases/release-ocp-4-dev-preview-s390x.json
  core-services/release-controller/_releases/release-ocp-4-dev-preview.json
  core-services/release-controller/_releases/release-ocp-4.y-stable-arm64.json
  core-services/release-controller/_releases/release-ocp-4.y-stable-multi.json
  core-services/release-controller/_releases/release-ocp-4.y-stable-ppc64le.json
  core-services/release-controller/_releases/release-ocp-4.y-stable-s390x.json
  core-services/release-controller/_releases/release-ocp-4.y-stable.json
  core-services/release-controller/_releases/release-okd-scos-4.y-next.json
  core-services/release-controller/_releases/release-okd-scos-4.y-stable.json
Labels: lgtm, approved, rehearsals-ack

#43356 Securesign Scaffolding Onboarding
  ci-operator/config/securesign/scaffolding/OWNERS
  ci-operator/config/securesign/scaffolding/securesign-scaffolding-redhat-v0.6.5.yaml
  ci-operator/config/securesign/scaffolding/securesign-scaffolding-release-next.yaml
  ci-operator/jobs/securesign/scaffolding/OWNERS
  ci-operator/jobs/securesign/scaffolding/securesign-scaffolding-redhat-v0.6.5-presubmits.yaml
  ci-operator/jobs/securesign/scaffolding/securesign-scaffolding-release-next-presubmits.yaml
  core-services/prow/02_config/securesign/scaffolding/OWNERS
  core-services/prow/02_config/securesign/scaffolding/_pluginconfig.yaml
  core-services/prow/02_config/securesign/scaffolding/_prowconfig.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#44038 [kubevirt-common-templates] feat: udate common templates ci to 4.15
  ci-operator/config/kubevirt/common-templates/kubevirt-common-templates-master.yaml
Labels: lgtm, approved, rehearsals-ack

#44015 OpenStack: Remove Kuryr jobs
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-master.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.15.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.16.yaml
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.15.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.16.yaml
  ci-operator/config/openshift/kuryr-kubernetes/openshift-kuryr-kubernetes-master.yaml
  ci-operator/config/openshift/kuryr-kubernetes/openshift-kuryr-kubernetes-release-4.15.yaml
  ci-operator/config/openshift/kuryr-kubernetes/openshift-kuryr-kubernetes-release-4.16.yaml
  ci-operator/config/openshift/openstack-test/openshift-openstack-test-main.yaml
  ci-operator/config/openshift/openstack-test/openshift-openstack-test-release-4.15.yaml
  ci-operator/config/openshift/openstack-test/openshift-openstack-test-release-4.16.yaml
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.15.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.16.yaml
  ci-operator/config/shiftstack/merge-bot/shiftstack-merge-bot-main.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.15-presubmits.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.16-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.15-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.16-presubmits.yaml
  ci-operator/jobs/openshift/kuryr-kubernetes/openshift-kuryr-kubernetes-master-postsubmits.yaml
  ci-operator/jobs/openshift/kuryr-kubernetes/openshift-kuryr-kubernetes-master-presubmits.yaml
  ci-operator/jobs/openshift/kuryr-kubernetes/openshift-kuryr-kubernetes-release-4.15-postsubmits.yaml
  ci-operator/jobs/openshift/kuryr-kubernetes/openshift-kuryr-kubernetes-release-4.15-presubmits.yaml
  ci-operator/jobs/openshift/kuryr-kubernetes/openshift-kuryr-kubernetes-release-4.16-postsubmits.yaml
  ci-operator/jobs/openshift/kuryr-kubernetes/openshift-kuryr-kubernetes-release-4.16-presubmits.yaml
  ci-operator/jobs/openshift/openstack-test/openshift-openstack-test-main-presubmits.yaml
  ci-operator/jobs/openshift/openstack-test/openshift-openstack-test-release-4.15-presubmits.yaml
  ci-operator/jobs/openshift/openstack-test/openshift-openstack-test-release-4.16-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.15-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.16-presubmits.yaml
  ci-operator/jobs/shiftstack/merge-bot/shiftstack-merge-bot-main-periodics.yaml
  core-services/image-mirroring/openshift/mapping_origin_4_15
Labels: lgtm, approved, rehearsals-ack

#44045 Disable build09
  core-services/prow/02_config/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#44050 Fix the image repo name for RHODS habana images
  ci-operator/config/red-hat-data-services/notebooks/red-hat-data-services-notebooks-main.yaml
  ci-operator/config/red-hat-data-services/notebooks/red-hat-data-services-notebooks-release-2023a.yaml
Labels: lgtm, approved, rehearsals-ack

#44051 Add maistra team reviewer in OWNERS_ALIASES
  OWNERS_ALIASES
Labels: lgtm, approved, rehearsals-ack

#44052 Fix regex instead of OR to use AND
  ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-main.yaml
  ci-operator/jobs/opendatahub-io/notebooks/opendatahub-io-notebooks-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#44059 Update rbac so we can get image data for ibm-roks
  clusters/app.ci/hypershift-toolkit/rbac.yaml
Labels: lgtm, approved, rehearsals-ack

#43719 MIXEDARCH-271: hardens the powervs install and deprovision
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.14.yaml
  ci-operator/step-registry/openshift/e2e/ibmcloud/heterogeneous/upi/OWNERS
  ci-operator/step-registry/openshift/e2e/ibmcloud/heterogeneous/upi/openshift-e2e-ibmcloud-heterogeneous-upi-workflow.metadata.json
  ci-operator/step-registry/upi/deprovision/heterogeneous/OWNERS
  ci-operator/step-registry/upi/deprovision/heterogeneous/powervs/OWNERS
  ci-operator/step-registry/upi/deprovision/heterogeneous/powervs/upi-deprovision-heterogeneous-powervs-commands.sh
  ci-operator/step-registry/upi/deprovision/heterogeneous/powervs/upi-deprovision-heterogeneous-powervs-ref.metadata.json
  ci-operator/step-registry/upi/install/heterogeneous/powervs/upi-install-heterogeneous-powervs-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#44065 fix several issues on azure jobs
  ci-operator/step-registry/cucushift/installer/rehearse/azure/stack/upi/provision/cucushift-installer-rehearse-azure-stack-upi-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/upi/disconnected/provision/cucushift-installer-rehearse-azure-upi-disconnected-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/upi/provision/cucushift-installer-rehearse-azure-upi-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/upi/proxy/provision/cucushift-installer-rehearse-azure-upi-proxy-provision-chain.yaml
  ci-operator/step-registry/gather/azure-resource/gather-azure-resource-commands.sh
Labels: lgtm, approved, rehearsals-ack

#43792 [hypershift] move hypershift install job to 414
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#44067 [CIGolang]change base image
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-master.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__images.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16.yaml
Labels: lgtm, approved, rehearsals-ack

#44066 Fix OO_INDEX
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-nightly.yaml
Labels: lgtm, approved, rehearsals-ack

#44064 skip storage cases when storage Capability is not enabled
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__arm64-nightly.yaml
Labels: lgtm, approved, rehearsals-ack

#43791 refine azure oidc install workflow
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly-4.14-upgrade-from-stable-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-nightly-4.14-upgrade-from-stable-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__multi-nightly-4.15-upgrade-from-stable-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__multi-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
  ci-operator/step-registry/azure/deprovision/resourcegroup/azure-deprovision-resourcegroup-commands.sh
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/cco-manual-workload-identity/provision/cucushift-installer-rehearse-azure-ipi-cco-manual-workload-identity-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/cco-manual-workload-identity/tp/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/cco-manual-workload-identity/tp/cucushift-installer-rehearse-azure-ipi-cco-manual-workload-identity-tp-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/cco-manual-workload-identity/tp/cucushift-installer-rehearse-azure-ipi-cco-manual-workload-identity-tp-workflow.yaml
  ci-operator/step-registry/ipi/conf/azure/oidc-creds-provision/ipi-conf-azure-oidc-creds-provision-commands.sh
  ci-operator/step-registry/ipi/conf/azure/provisioned-resourcegroup/ipi-conf-azure-provisioned-resourcegroup-commands.sh
Labels: lgtm, approved, rehearsals-ack

#44072 enable cap MachineAPI for install with baseline:none on upgrade job from 4.14
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly-4.15-upgrade-from-stable-4.14.yaml
Labels: lgtm, approved, rehearsals-ack

#44074 Add tests for 4.15 EC
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-ec.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__arm64-ec.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__multi-ec.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#44076 Fix payload for 4.15 EC tests
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-ec.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__arm64-ec.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__multi-ec.yaml
Labels: lgtm, approved, rehearsals-ack

#44075 Sort configs for easier compare across different versions
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-stable-4.11.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__arm64-nightly-4.12-upgrade-from-stable-4.11.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__multi-nightly.yaml
Labels: lgtm, approved, rehearsals-ack

#44077 remove gather-installer-boostrap-logs-in-bastion step from non-private install
  ci-operator/step-registry/cucushift/installer/rehearse/azure/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/aro/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/aro/cucushift-installer-rehearse-azure-aro-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/cucushift-installer-rehearse-azure-ipi-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/deprovision/cucushift-installer-rehearse-azure-ipi-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/disconnected/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/disconnected/cucushift-installer-rehearse-azure-ipi-disconnected-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/disconnected/deprovision/cucushift-installer-rehearse-azure-ipi-disconnected-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/disconnected/deprovision/cucushift-installer-rehearse-azure-ipi-disconnected-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/disconnected/fullyprivate/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/disconnected/fullyprivate/cucushift-installer-rehearse-azure-ipi-disconnected-fullyprivate-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/disconnected/fullyprivate/cucushift-installer-rehearse-azure-ipi-disconnected-fullyprivate-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/disconnected/fullyprivate/deprovision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/disconnected/fullyprivate/deprovision/cucushift-installer-rehearse-azure-ipi-disconnected-fullyprivate-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/disconnected/fullyprivate/deprovision/cucushift-installer-rehearse-azure-ipi-disconnected-fullyprivate-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/disconnected/fullyprivate/techpreview/cucushift-installer-rehearse-azure-ipi-disconnected-fullyprivate-techpreview-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/disconnected/provision/cucushift-installer-rehearse-azure-ipi-disconnected-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/disk-encryption-set/cucushift-installer-rehearse-azure-ipi-disk-encryption-set-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/disk-encryption-set/deprovision/cucushift-installer-rehearse-azure-ipi-disk-encryption-set-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/disk-encryption-set/provision/cucushift-installer-rehearse-azure-ipi-disk-encryption-set-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/private/cucushift-installer-rehearse-azure-ipi-private-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/private/deprovision/cucushift-installer-rehearse-azure-ipi-private-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/private/provision/cucushift-installer-rehearse-azure-ipi-private-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/provision/cucushift-installer-rehearse-azure-ipi-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/resourcegroup/cucushift-installer-rehearse-azure-ipi-resourcegroup-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/resourcegroup/provision/cucushift-installer-rehearse-azure-ipi-resourcegroup-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/sharednetwork/cucushift-installer-rehearse-azure-ipi-sharednetwork-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/sharednetwork/deprovision/cucushift-installer-rehearse-azure-ipi-sharednetwork-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/sharednetwork/provision/cucushift-installer-rehearse-azure-ipi-sharednetwork-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/vmgenv1/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/vmgenv1/cucushift-installer-rehearse-azure-ipi-vmgenv1-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/upi/cucushift-installer-rehearse-azure-upi-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/upi/deprovision/cucushift-installer-rehearse-azure-upi-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/upi/provision/cucushift-installer-rehearse-azure-upi-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/disconnected/deprovision/cucushift-installer-rehearse-gcp-ipi-disconnected-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/disconnected/private/cco-manual-workload-identity/deprovision/cucushift-installer-rehearse-gcp-ipi-disconnected-private-cco-manual-workload-identity-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/disconnected/private/cucushift-installer-rehearse-gcp-ipi-disconnected-private-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/disconnected/private/deprovision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/disconnected/private/deprovision/cucushift-installer-rehearse-gcp-ipi-disconnected-private-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/disconnected/private/deprovision/cucushift-installer-rehearse-gcp-ipi-disconnected-private-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/disconnected/private/ovn/cucushift-installer-rehearse-gcp-ipi-disconnected-private-ovn-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#44079 Fix E2E_RUN_TAGS
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
Labels: lgtm, approved, rehearsals-ack

#44069 add debugging time for operators timeout issue
  ci-operator/step-registry/rosa/cluster/wait-ready/operators/rosa-cluster-wait-ready-operators-commands.sh
Labels: lgtm, approved, rehearsals-ack

#44083 Extend timeout to 8h for cypress tests
  ci-operator/step-registry/openshift-extended/web-tests/openshift-extended-web-tests-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#44080 Fix several fips jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly.yaml
Labels: lgtm, approved, rehearsals-ack

#43741 Azure Workload Identity disconnected CI
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__multi-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/disconnected/cco-manual-workload-identity/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/disconnected/cco-manual-workload-identity/cucushift-installer-rehearse-azure-ipi-disconnected-cco-manual-workload-identity-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/disconnected/cco-manual-workload-identity/cucushift-installer-rehearse-azure-ipi-disconnected-cco-manual-workload-identity-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/disconnected/cco-manual-workload-identity/deprovision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/disconnected/cco-manual-workload-identity/deprovision/cucushift-installer-rehearse-azure-ipi-disconnected-cco-manual-workload-identity-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/disconnected/cco-manual-workload-identity/deprovision/cucushift-installer-rehearse-azure-ipi-disconnected-cco-manual-workload-identity-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/disconnected/cco-manual-workload-identity/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/disconnected/cco-manual-workload-identity/provision/cucushift-installer-rehearse-azure-ipi-disconnected-cco-manual-workload-identity-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/disconnected/cco-manual-workload-identity/provision/cucushift-installer-rehearse-azure-ipi-disconnected-cco-manual-workload-identity-provision-chain.yaml
  ci-operator/step-registry/ipi/conf/azure/oidc-creds-provision/ipi-conf-azure-oidc-creds-provision-commands.sh
Labels: lgtm, approved, rehearsals-ack

#41085 update sdn job to fips enable
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
Labels: lgtm, approved, lifecycle/stale, rehearsals-ack

#44082 OCPQE-16967: fix auth issue on shared-vpc cluster
  ci-operator/step-registry/ipi/conf/aws/oidc-creds-provision/ipi-conf-aws-oidc-creds-provision-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#44037 [kubevirt-ssp-operator] feat: use ocp 4.15 for ssp operator ci
  ci-operator/config/kubevirt/ssp-operator/kubevirt-ssp-operator-main.yaml
Labels: lgtm, approved, rehearsals-ack

#43960 test: add fleet-manager endpoints checks
  ci-operator/step-registry/osd-ccs/fleet-manager/test/osd-ccs-fleet-manager-test-commands.sh
Labels: lgtm, approved, rehearsals-ack

#43874 Create Bundle instead of building Index for FAR using operator-sdk
  ci-operator/config/medik8s/fence-agents-remediation/medik8s-fence-agents-remediation-main__4.12.yaml
  ci-operator/config/medik8s/fence-agents-remediation/medik8s-fence-agents-remediation-main__4.13.yaml
  ci-operator/config/medik8s/fence-agents-remediation/medik8s-fence-agents-remediation-main__4.14.yaml
  ci-operator/config/medik8s/fence-agents-remediation/medik8s-fence-agents-remediation-main__4.15.yaml
  ci-operator/jobs/medik8s/fence-agents-remediation/medik8s-fence-agents-remediation-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#43780 MGMT-15867: Fix infrastructure operator publish in community-operators
  ci-operator/step-registry/assisted/baremetal/operator/publish/assisted-baremetal-operator-publish-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#44039 OCPVE-705: lvms: chore: add use_build_cache for build root
  ci-operator/config/openshift/lvm-operator/openshift-lvm-operator-main.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#43905 MGMT-15863 - fix resources for assisted-cnv e2e
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master__edge.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-master__edge.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-cloud_hotfix_releases.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
Labels: lgtm, approved, rehearsals-ack

#44095 move pvc permission check to install post check
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/disk-encryption-set/provision/cucushift-installer-rehearse-azure-ipi-disk-encryption-set-provision-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#44103 Fix typo in rosa-cluster-provision-commands.sh
  ci-operator/step-registry/rosa/cluster/provision/rosa-cluster-provision-commands.sh
Labels: lgtm, approved, rehearsals-ack

#44098 Mirror claire quay image for AMQ Broker scenario
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_ci
Labels: lgtm, approved, rehearsals-ack

#41527 3scale operator test go 1.19
  ci-operator/config/3scale/3scale-operator/3scale-3scale-operator-master.yaml
Labels: lgtm, approved, rehearsals-ack

#44060 baremetalds dev-scripts setup: perform all finish tasks
  ci-operator/step-registry/baremetalds/devscripts/setup/baremetalds-devscripts-setup-commands.sh
Labels: lgtm, approved, rehearsals-ack

#44105 prowconfig(osso): enable tide merging for 4.13 and 4.14
  core-services/prow/02_config/openshift/secondary-scheduler-operator/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#44081 Temporarily change build farm for chain upgrade
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly-4.14-upgrade-from-stable-4.1.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly-4.14-upgrade-from-stable-4.2.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#44026 Change Azure COMPUTE_NODE_TYPE for CNV e2e tests
  ci-operator/config/openshift-cnv/cnv-ci/openshift-cnv-cnv-ci-master.yaml
  ci-operator/config/openshift-cnv/cnv-ci/openshift-cnv-cnv-ci-master__4.10.yaml
  ci-operator/config/openshift-cnv/cnv-ci/openshift-cnv-cnv-ci-master__4.11.yaml
  ci-operator/config/openshift-cnv/cnv-ci/openshift-cnv-cnv-ci-master__4.12.yaml
  ci-operator/config/openshift-cnv/cnv-ci/openshift-cnv-cnv-ci-master__4.13.yaml
  ci-operator/config/openshift-cnv/cnv-ci/openshift-cnv-cnv-ci-master__4.14.yaml
  ci-operator/config/openshift-cnv/cnv-ci/openshift-cnv-cnv-ci-release-4.10.yaml
  ci-operator/config/openshift-cnv/cnv-ci/openshift-cnv-cnv-ci-release-4.11.yaml
  ci-operator/config/openshift-cnv/cnv-ci/openshift-cnv-cnv-ci-release-4.12.yaml
  ci-operator/config/openshift-cnv/cnv-ci/openshift-cnv-cnv-ci-release-4.13.yaml
  ci-operator/config/openshift-cnv/cnv-ci/openshift-cnv-cnv-ci-release-4.14.yaml
  ci-operator/config/openshift-cnv/cnv-ci/openshift-cnv-cnv-ci-release-4.15.yaml
Labels: lgtm, approved, rehearsals-ack

#43464 LPTOCPCI-587: Fix quay results do not contain junit_ prefix when fails
  ci-operator/step-registry/quay-tests/test-quay-e2e/quay-tests-test-quay-e2e-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference
