Repository openshift/release, pull requests merged in 2023-02, with the labels that each got.

#35758 enable netobserv tests
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
Labels: lgtm, approved, rehearsals-ack

#35860 hypershift: OCP regression test on KubeVirt-HyperShift
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#35891 hypershift-qe: delete the hypershift part of 4.11
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__arm64-stable.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#35871 Sync serverless ci
  ci-operator/config/openshift-knative/eventing-hyperfoil-benchmark/openshift-knative-eventing-hyperfoil-benchmark-main__412.yaml
  ci-operator/config/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-next__412.yaml
  ci-operator/config/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.6__412.yaml
  ci-operator/config/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.7__412.yaml
  ci-operator/config/openshift-knative/eventing/openshift-knative-eventing-release-next__412.yaml
  ci-operator/config/openshift-knative/eventing/openshift-knative-eventing-release-v1.6__412.yaml
  ci-operator/config/openshift-knative/eventing/openshift-knative-eventing-release-v1.7__412.yaml
  ci-operator/config/openshift-knative/eventing/openshift-knative-eventing-release-v1.8__412.yaml
  ci-operator/jobs/openshift-knative/eventing-hyperfoil-benchmark/openshift-knative-eventing-hyperfoil-benchmark-main-periodics.yaml
  ci-operator/jobs/openshift-knative/eventing-hyperfoil-benchmark/openshift-knative-eventing-hyperfoil-benchmark-main-postsubmits.yaml
  ci-operator/jobs/openshift-knative/eventing-hyperfoil-benchmark/openshift-knative-eventing-hyperfoil-benchmark-main-presubmits.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-next-periodics.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-next-postsubmits.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-next-presubmits.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.6-periodics.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.6-postsubmits.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.6-presubmits.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.7-periodics.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.7-postsubmits.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.7-presubmits.yaml
  ci-operator/jobs/openshift-knative/eventing/openshift-knative-eventing-release-next-periodics.yaml
  ci-operator/jobs/openshift-knative/eventing/openshift-knative-eventing-release-next-postsubmits.yaml
  ci-operator/jobs/openshift-knative/eventing/openshift-knative-eventing-release-next-presubmits.yaml
  ci-operator/jobs/openshift-knative/eventing/openshift-knative-eventing-release-v1.6-periodics.yaml
  ci-operator/jobs/openshift-knative/eventing/openshift-knative-eventing-release-v1.6-postsubmits.yaml
  ci-operator/jobs/openshift-knative/eventing/openshift-knative-eventing-release-v1.6-presubmits.yaml
  ci-operator/jobs/openshift-knative/eventing/openshift-knative-eventing-release-v1.7-periodics.yaml
  ci-operator/jobs/openshift-knative/eventing/openshift-knative-eventing-release-v1.7-postsubmits.yaml
  ci-operator/jobs/openshift-knative/eventing/openshift-knative-eventing-release-v1.7-presubmits.yaml
  ci-operator/jobs/openshift-knative/eventing/openshift-knative-eventing-release-v1.8-periodics.yaml
  ci-operator/jobs/openshift-knative/eventing/openshift-knative-eventing-release-v1.8-postsubmits.yaml
  ci-operator/jobs/openshift-knative/eventing/openshift-knative-eventing-release-v1.8-presubmits.yaml
  core-services/image-mirroring/knative/mapping_knative_knative-nightly_eventing-kafka-broker_quay
  core-services/image-mirroring/knative/mapping_knative_knative-v1.4_eventing-kafka-broker_quay
  core-services/image-mirroring/knative/mapping_knative_knative-v1.5_eventing-kafka-broker_quay
  core-services/image-mirroring/knative/mapping_knative_knative-v1.6_eventing-kafka-broker_quay
  core-services/image-mirroring/knative/mapping_knative_knative-v1.7_eventing-kafka-broker_quay
Labels: lgtm, approved, rehearsals-ack

#35880 chore: add an extra step to inject env variable before addon-operator e2e tests are run
  ci-operator/config/openshift/addon-operator/openshift-addon-operator-main.yaml
Labels: lgtm, approved, rehearsals-ack

#35917 use explicit installation namespace for addon operator
  ci-operator/config/openshift/addon-operator/openshift-addon-operator-main.yaml
Labels: lgtm, approved, rehearsals-ack

#35916 USHIFT-821: Fix post chains in microshift workflows
  ci-operator/step-registry/openshift/microshift/e2e/copr-install/openshift-microshift-e2e-copr-install-workflow.yaml
  ci-operator/step-registry/openshift/microshift/e2e/openshift-conformance-sig-api-machinery/openshift-microshift-e2e-openshift-conformance-sig-api-machinery-workflow.yaml
  ci-operator/step-registry/openshift/microshift/e2e/openshift-conformance-sig-apps/openshift-microshift-e2e-openshift-conformance-sig-apps-workflow.yaml
  ci-operator/step-registry/openshift/microshift/e2e/openshift-conformance-sig-auth/openshift-microshift-e2e-openshift-conformance-sig-auth-workflow.yaml
  ci-operator/step-registry/openshift/microshift/e2e/openshift-conformance-sig-cli/openshift-microshift-e2e-openshift-conformance-sig-cli-workflow.yaml
  ci-operator/step-registry/openshift/microshift/e2e/openshift-conformance-sig-instrumentation/openshift-microshift-e2e-openshift-conformance-sig-instrumentation-workflow.yaml
  ci-operator/step-registry/openshift/microshift/e2e/openshift-conformance-sig-network/openshift-microshift-e2e-openshift-conformance-sig-network-workflow.yaml
  ci-operator/step-registry/openshift/microshift/e2e/openshift-conformance-sig-node/openshift-microshift-e2e-openshift-conformance-sig-node-workflow.yaml
  ci-operator/step-registry/openshift/microshift/e2e/openshift-conformance-sig-scheduling/openshift-microshift-e2e-openshift-conformance-sig-scheduling-workflow.yaml
  ci-operator/step-registry/openshift/microshift/e2e/openshift-conformance-sig-storage/openshift-microshift-e2e-openshift-conformance-sig-storage-workflow.yaml
  ci-operator/step-registry/openshift/microshift/e2e/reboot-tests/openshift-microshift-e2e-reboot-tests-workflow.yaml
  ci-operator/step-registry/openshift/microshift/e2e/router-smoke-test/openshift-microshift-e2e-router-smoke-test-workflow.yaml
  ci-operator/step-registry/openshift/microshift/e2e/rpm-install/openshift-microshift-e2e-rpm-install-workflow.yaml
  ci-operator/step-registry/openshift/microshift/e2e/test/openshift-microshift-e2e-test-workflow.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#35872 Shared Resources CSI Driver: switch to from_repository build_root
  ci-operator/config/openshift/csi-driver-shared-resource-operator/openshift-csi-driver-shared-resource-operator-master.yaml
  ci-operator/config/openshift/csi-driver-shared-resource-operator/openshift-csi-driver-shared-resource-operator-release-4.13.yaml
  ci-operator/config/openshift/csi-driver-shared-resource-operator/openshift-csi-driver-shared-resource-operator-release-4.14.yaml
  ci-operator/jobs/openshift/csi-driver-shared-resource-operator/openshift-csi-driver-shared-resource-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/csi-driver-shared-resource-operator/openshift-csi-driver-shared-resource-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/csi-driver-shared-resource-operator/openshift-csi-driver-shared-resource-operator-release-4.13-postsubmits.yaml
  ci-operator/jobs/openshift/csi-driver-shared-resource-operator/openshift-csi-driver-shared-resource-operator-release-4.13-presubmits.yaml
  ci-operator/jobs/openshift/csi-driver-shared-resource-operator/openshift-csi-driver-shared-resource-operator-release-4.14-postsubmits.yaml
  ci-operator/jobs/openshift/csi-driver-shared-resource-operator/openshift-csi-driver-shared-resource-operator-release-4.14-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#35561 STOR-1126: CSI migration is GA in 4.13 for vSphere
  ci-operator/config/openshift/vmware-vsphere-csi-driver-operator/openshift-vmware-vsphere-csi-driver-operator-master.yaml
  ci-operator/config/openshift/vmware-vsphere-csi-driver-operator/openshift-vmware-vsphere-csi-driver-operator-release-4.13.yaml
  ci-operator/config/openshift/vmware-vsphere-csi-driver-operator/openshift-vmware-vsphere-csi-driver-operator-release-4.14.yaml
  ci-operator/config/openshift/vmware-vsphere-csi-driver/openshift-vmware-vsphere-csi-driver-master.yaml
  ci-operator/config/openshift/vmware-vsphere-csi-driver/openshift-vmware-vsphere-csi-driver-release-4.13.yaml
  ci-operator/config/openshift/vmware-vsphere-csi-driver/openshift-vmware-vsphere-csi-driver-release-4.14.yaml
  ci-operator/jobs/openshift/vmware-vsphere-csi-driver-operator/openshift-vmware-vsphere-csi-driver-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/vmware-vsphere-csi-driver-operator/openshift-vmware-vsphere-csi-driver-operator-release-4.13-presubmits.yaml
  ci-operator/jobs/openshift/vmware-vsphere-csi-driver-operator/openshift-vmware-vsphere-csi-driver-operator-release-4.14-presubmits.yaml
  ci-operator/jobs/openshift/vmware-vsphere-csi-driver/openshift-vmware-vsphere-csi-driver-master-presubmits.yaml
  ci-operator/jobs/openshift/vmware-vsphere-csi-driver/openshift-vmware-vsphere-csi-driver-release-4.13-presubmits.yaml
  ci-operator/jobs/openshift/vmware-vsphere-csi-driver/openshift-vmware-vsphere-csi-driver-release-4.14-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#35892 [OCPBUGS-6496] Fix machine-os-content promotino job
  ci-operator/jobs/openshift/release/openshift-release-release-4.10-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.11-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.9-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#35919 addon operator e2e tests: pass OO_INSTALLATION_NAMESPACE to the mage command
  ci-operator/config/openshift/addon-operator/openshift-addon-operator-main.yaml
Labels: lgtm, approved, rehearsals-ack

#35553 Add build and deploy job for mariadb-op
  ci-operator/config/openstack-k8s-operators/mariadb-operator/openstack-k8s-operators-mariadb-operator-master.yaml
  ci-operator/jobs/openstack-k8s-operators/mariadb-operator/openstack-k8s-operators-mariadb-operator-master-presubmits.yaml
  ci-operator/step-registry/openstack-k8s-operators/build/openstack-k8s-operators-build-commands.sh
  ci-operator/step-registry/openstack-k8s-operators/deploy/openstack-k8s-operators-deploy-commands.sh
Labels: lgtm, approved, rehearsals-ack

#35874 HCO: Move one azure test to the CNV account
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-main.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#35923 add alibabacloud-quota-slice to lease garbage collector
  clusters/app.ci/prow/03_deployment/boskos_reaper.yaml
Labels: lgtm, approved, rehearsals-ack

#35903 stolostron: hypershift-addon-operator canary test fix
  ci-operator/config/stolostron/hypershift-addon-operator/stolostron-hypershift-addon-operator-backplane-2.2.yaml
  ci-operator/config/stolostron/hypershift-addon-operator/stolostron-hypershift-addon-operator-backplane-2.3.yaml
Labels: lgtm, approved, rehearsals-ack

#35390 cnf-features-deploy: ran profile CI updates
  ci-operator/config/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-master.yaml
  ci-operator/jobs/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#35819 CVP-3490 : Add OCP 4.12 clusters to MSP cluster pools
  clusters/hive/pools/msp/msp-ocp-4-12-medium-single-az-aws_clusterpool.yaml
  clusters/hive/pools/msp/msp-ocp-4-12-small-single-az-aws_clusterpool.yaml
Labels: lgtm, approved, rehearsals-ack

#35899 Chaos image
  clusters/app.ci/multi-arch/namespaces.yaml
  core-services/image-mirroring-arm64/mapping_supplemental_ci_images_redhat_chaos
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_redhat_chaos
Labels: lgtm, approved, rehearsals-ack

#35924 oc-compliance: Use go 1.19 and OCP 4.12
  ci-operator/config/openshift/oc-compliance/openshift-oc-compliance-master.yaml
  ci-operator/jobs/openshift/oc-compliance/openshift-oc-compliance-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#35926 ci-operator/config/cri-o: disable rhel-integration test
  ci-operator/config/cri-o/cri-o/cri-o-cri-o-main__ci.yaml
  ci-operator/jobs/cri-o/cri-o/cri-o-cri-o-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#35459 add -ovn- to cluster-baremetal-operator presubmits
  ci-operator/config/openshift/cluster-baremetal-operator/openshift-cluster-baremetal-operator-master.yaml
  ci-operator/config/openshift/cluster-baremetal-operator/openshift-cluster-baremetal-operator-release-4.12.yaml
  ci-operator/config/openshift/cluster-baremetal-operator/openshift-cluster-baremetal-operator-release-4.13.yaml
  ci-operator/config/openshift/cluster-baremetal-operator/openshift-cluster-baremetal-operator-release-4.14.yaml
  ci-operator/jobs/openshift/cluster-baremetal-operator/openshift-cluster-baremetal-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-baremetal-operator/openshift-cluster-baremetal-operator-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift/cluster-baremetal-operator/openshift-cluster-baremetal-operator-release-4.13-presubmits.yaml
  ci-operator/jobs/openshift/cluster-baremetal-operator/openshift-cluster-baremetal-operator-release-4.14-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#35934 Rename e2e-openstack-sdn-upgrade to ovn
  ci-operator/config/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main__periodic-4.12-upgrade-from-stable-4.11.yaml
  ci-operator/jobs/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#35936 Custom Metrics Autoscaler: Update to go 1.19
  ci-operator/config/openshift-priv/custom-metrics-autoscaler-operator/openshift-priv-custom-metrics-autoscaler-operator-main.yaml
  ci-operator/config/openshift-priv/custom-metrics-autoscaler-operator/openshift-priv-custom-metrics-autoscaler-operator-release-4.12.yaml
  ci-operator/config/openshift-priv/custom-metrics-autoscaler-operator/openshift-priv-custom-metrics-autoscaler-operator-release-4.13.yaml
  ci-operator/config/openshift/custom-metrics-autoscaler-operator/openshift-custom-metrics-autoscaler-operator-main.yaml
  ci-operator/config/openshift/custom-metrics-autoscaler-operator/openshift-custom-metrics-autoscaler-operator-release-4.12.yaml
  ci-operator/config/openshift/custom-metrics-autoscaler-operator/openshift-custom-metrics-autoscaler-operator-release-4.13.yaml
Labels: lgtm, approved, rehearsals-ack

#35787 Update osdctl CI image to Go 1.19
  ci-operator/config/openshift/osdctl/openshift-osdctl-master.yaml
Labels: lgtm, approved, rehearsals-ack

#35935 Promote machine-os-content from 4.x-legacy-arch location
  ci-operator/jobs/openshift/release/openshift-release-release-4.10-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.11-periodics.yaml
  ci-operator/jobs/openshift/release/openshift-release-release-4.9-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#35940 Create a long-lived token for ART service account
  clusters/app.ci/release-controller/admin_deploy-ocp-publish-art.yaml
  hack/generators/release-controllers/content/art_publish_permissions.py
Labels: lgtm, approved, rehearsals-ack

#35943 stackrox: remove opensource builds
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__stackrox_branding.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies__stackrox_branding.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-postsubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-presubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-nightlies-postsubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-nightlies-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#35942 MCO: don't run jobs on all PRs
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#35908 [CIGolang]correct build after 412 ga
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12.yaml
Labels: lgtm, approved, rehearsals-ack

#35933 Hive
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.8__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.8__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.9__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.9__amd64-stable.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.8-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.9-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#35913 Update Quay3.8 on OCP 4.13 to use ODF 4.12
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__ocp-412-quay36.yaml
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__ocp-412-quay37.yaml
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__ocp-413-quay38.yaml
Labels: lgtm, approved, rehearsals-ack

#35909 hypershift: KubeVirt-HyperShift-guest
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/ovn/kubevirt/hypershift/guest/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/ovn/kubevirt/hypershift/guest/cucushift-installer-rehearse-aws-ipi-ovn-kubevirt-hypershift-guest-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/ovn/kubevirt/hypershift/guest/cucushift-installer-rehearse-aws-ipi-ovn-kubevirt-hypershift-guest-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/ovn/kubevirt/hypershift/guest/deprovision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/ovn/kubevirt/hypershift/guest/deprovision/cucushift-installer-rehearse-aws-ipi-ovn-kubevirt-hypershift-guest-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/ovn/kubevirt/hypershift/guest/deprovision/cucushift-installer-rehearse-aws-ipi-ovn-kubevirt-hypershift-guest-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/ovn/kubevirt/hypershift/guest/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/ovn/kubevirt/hypershift/guest/provision/cucushift-installer-rehearse-aws-ipi-ovn-kubevirt-hypershift-guest-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/ovn/kubevirt/hypershift/guest/provision/cucushift-installer-rehearse-aws-ipi-ovn-kubevirt-hypershift-guest-provision-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#35932 Filestore CSI driver: test mount options and multiplePVsSameID capability
  ci-operator/step-registry/storage/create/csi-gcp-filestore/storage-create-csi-gcp-filestore-commands.sh
Labels: lgtm, approved, rehearsals-ack

#35958 Update _pluginconfig.yaml
  core-services/prow/02_config/red-hat-storage/_pluginconfig.yaml
Labels: lgtm, approved, needs-ok-to-test, rehearsals-ack

#35957 NTO: set long timeout for pao e2e
  ci-operator/config/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-release-4.12.yaml
Labels: lgtm, approved, rehearsals-ack

#35975 for upi-zonal installs use internal DNS
  ci-operator/step-registry/ipi/conf/vsphere/check/ipi-conf-vsphere-check-commands.sh
Labels: lgtm, approved, rehearsals-ack

#35890 [OCPCLOUD-1865] update cloud-provider-ibm to use from_repository builds
  ci-operator/config/openshift/cloud-provider-ibm/openshift-cloud-provider-ibm-master.yaml
  ci-operator/config/openshift/cloud-provider-ibm/openshift-cloud-provider-ibm-release-4.12.yaml
  ci-operator/config/openshift/cloud-provider-ibm/openshift-cloud-provider-ibm-release-4.13.yaml
  ci-operator/config/openshift/cloud-provider-ibm/openshift-cloud-provider-ibm-release-4.14.yaml
  ci-operator/jobs/openshift/cloud-provider-ibm/openshift-cloud-provider-ibm-master-postsubmits.yaml
  ci-operator/jobs/openshift/cloud-provider-ibm/openshift-cloud-provider-ibm-master-presubmits.yaml
  ci-operator/jobs/openshift/cloud-provider-ibm/openshift-cloud-provider-ibm-release-4.12-postsubmits.yaml
  ci-operator/jobs/openshift/cloud-provider-ibm/openshift-cloud-provider-ibm-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift/cloud-provider-ibm/openshift-cloud-provider-ibm-release-4.13-postsubmits.yaml
  ci-operator/jobs/openshift/cloud-provider-ibm/openshift-cloud-provider-ibm-release-4.13-presubmits.yaml
  ci-operator/jobs/openshift/cloud-provider-ibm/openshift-cloud-provider-ibm-release-4.14-postsubmits.yaml
  ci-operator/jobs/openshift/cloud-provider-ibm/openshift-cloud-provider-ibm-release-4.14-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#31743 add integration tests for cgroupv2 variant
  ci-operator/config/cri-o/cri-o/cri-o-cri-o-main__ci.yaml
  ci-operator/jobs/cri-o/cri-o/cri-o-cri-o-main-presubmits.yaml
  ci-operator/step-registry/cri-o/cgroupv2/integration/OWNERS
  ci-operator/step-registry/cri-o/cgroupv2/integration/cri-o-cgroupv2-integration-workflow.metadata.json
  ci-operator/step-registry/cri-o/cgroupv2/integration/cri-o-cgroupv2-integration-workflow.yaml
  ci-operator/step-registry/cri-o/cgroupv2/integration/test/OWNERS
  ci-operator/step-registry/cri-o/cgroupv2/integration/test/cri-o-cgroupv2-integration-test-commands.sh
  ci-operator/step-registry/cri-o/cgroupv2/integration/test/cri-o-cgroupv2-integration-test-ref.metadata.json
  ci-operator/step-registry/cri-o/cgroupv2/integration/test/cri-o-cgroupv2-integration-test-ref.yaml
  ci-operator/step-registry/cri-o/crun/integration/OWNERS
  ci-operator/step-registry/cri-o/crun/integration/cri-o-crun-integration-workflow.metadata.json
  ci-operator/step-registry/cri-o/crun/integration/cri-o-crun-integration-workflow.yaml
  ci-operator/step-registry/cri-o/crun/integration/test/OWNERS
  ci-operator/step-registry/cri-o/crun/integration/test/cri-o-crun-integration-test-commands.sh
  ci-operator/step-registry/cri-o/crun/integration/test/cri-o-crun-integration-test-ref.metadata.json
  ci-operator/step-registry/cri-o/crun/integration/test/cri-o-crun-integration-test-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#35925 HCO: Remove jobs for unused release branches
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.10.yaml
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.11.yaml
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.12.yaml
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.13.yaml
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.7.yaml
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.8.yaml
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.9.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.10-periodics.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.10-postsubmits.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.10-presubmits.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.11-periodics.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.11-postsubmits.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.11-presubmits.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.12-periodics.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.12-postsubmits.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.12-presubmits.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.13-periodics.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.13-postsubmits.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.13-presubmits.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.7-periodics.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.7-postsubmits.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.7-presubmits.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.8-periodics.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.8-postsubmits.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.8-presubmits.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.9-periodics.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.9-postsubmits.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-4.9-presubmits.yaml
  core-services/image-mirroring/openshift/mapping_origin_4_12
  core-services/image-mirroring/openshift/mapping_origin_4_7
  core-services/image-mirroring/openshift/mapping_origin_4_8
Labels: lgtm, approved, rehearsals-ack

#35912 Add build instructions and mirror jobs for the ubi9 version of the images (part 1)
  ci-operator/config/red-hat-data-services/notebooks/red-hat-data-services-notebooks-main.yaml
  ci-operator/jobs/red-hat-data-services/notebooks/red-hat-data-services-notebooks-main-postsubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#35945 ACS Scanner release 2.28
  ci-operator/config/stackrox/scanner/stackrox-scanner-release-2.28.yaml
  ci-operator/jobs/stackrox/scanner/stackrox-scanner-release-2.28-postsubmits.yaml
  ci-operator/jobs/stackrox/scanner/stackrox-scanner-release-2.28-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#35781 [WINC-921]: add fast-forward workflow
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-master.yaml
  ci-operator/step-registry/windows/ci/OWNERS
  ci-operator/step-registry/windows/ci/fastforward/OWNERS
  ci-operator/step-registry/windows/ci/fastforward/windows-ci-fastforward-commands.sh
  ci-operator/step-registry/windows/ci/fastforward/windows-ci-fastforward-ref.metadata.json
  ci-operator/step-registry/windows/ci/fastforward/windows-ci-fastforward-ref.yaml
  ci-operator/step-registry/windows/ci/fastforward/windows-ci-fastforward-workflow.metadata.json
  ci-operator/step-registry/windows/ci/fastforward/windows-ci-fastforward-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#35340 OSDe2e - Hypershift PR Check and Prowgen Periodic
  ci-operator/config/openshift/osde2e/.config.prowgen
  ci-operator/config/openshift/osde2e/openshift-osde2e-main.yaml
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-presubmits.yaml
  core-services/testgrid-config-generator/_allow-list.yaml
Labels: lgtm, approved, tide/merge-method-squash, rehearsals-ack

#35985 Velero-plugin-for-csi: update promotion
  ci-operator/config/openshift/velero-plugin-for-csi/openshift-velero-plugin-for-csi-main.yaml
  ci-operator/jobs/openshift/velero-plugin-for-csi/openshift-velero-plugin-for-csi-main-postsubmits.yaml
  ci-operator/jobs/openshift/velero-plugin-for-csi/openshift-velero-plugin-for-csi-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#35989 Build osde2e binary as part of hypershift-pr-check job
  ci-operator/config/openshift/osde2e/openshift-osde2e-main.yaml
Labels: lgtm, approved, rehearsals-ack

#35986 installer test coverage
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
Labels: lgtm, approved, rehearsals-ack

#35959 Adding slack notification to hive long duration cases for 4.13
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#35915 Add build instructions and test jobs for the ubi9 images buildchain part 2 (ODH)
  ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-main.yaml
  ci-operator/jobs/opendatahub-io/notebooks/opendatahub-io-notebooks-main-postsubmits.yaml
  ci-operator/jobs/opendatahub-io/notebooks/opendatahub-io-notebooks-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#35513 add cherry pick approve label
  core-services/prow/02_config/openshift/dpu-network-operator/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#35996 Add release jobs for ARO-Installer
  ci-operator/config/openshift/ARO-Installer/openshift-ARO-Installer-release-4.10.yaml
  ci-operator/config/openshift/ARO-Installer/openshift-ARO-Installer-release-4.11.yaml
  ci-operator/jobs/openshift/ARO-Installer/openshift-ARO-Installer-release-4.10-presubmits.yaml
  ci-operator/jobs/openshift/ARO-Installer/openshift-ARO-Installer-release-4.11-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#35995 Patch for #35563
  ci-operator/config/openshift/osde2e/openshift-osde2e-main.yaml
Labels: lgtm, approved, rehearsals-ack

#35964 [CIGolang]correct build
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-master.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14.yaml
Labels: lgtm, approved, rehearsals-ack

#35956 Add quay 3.8 tests on rosa with ocp 4.12
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__quay38-rosa-ocp412.yaml
  ci-operator/jobs/quay/quay-tests/quay-quay-tests-master-periodics.yaml
Labels: lgtm, approved, tide/merge-method-squash, rehearsals-ack

#35998 Adding slack notification to hive long duration cases
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#35982 Adding eventing v1.9
  ci-operator/config/openshift-knative/eventing/openshift-knative-eventing-release-v1.9__412.yaml
  ci-operator/config/openshift-knative/eventing/openshift-knative-eventing-release-v1.9__48.yaml
  ci-operator/jobs/openshift-knative/eventing/openshift-knative-eventing-release-v1.9-periodics.yaml
  ci-operator/jobs/openshift-knative/eventing/openshift-knative-eventing-release-v1.9-postsubmits.yaml
  ci-operator/jobs/openshift-knative/eventing/openshift-knative-eventing-release-v1.9-presubmits.yaml
  core-services/image-mirroring/knative/mapping_knative_knative-v1.9_eventing_quay
Labels: lgtm, approved, rehearsals-ack

#35947 Bump up multi-jump upgrade from 4.12 to 4.13 as 4.12 GAed
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-4.13-upgrade-from-stable-4.2.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-4.13-upgrade-from-stable-4.3.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-4.13-upgrade-from-stable-4.4.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-4.13-upgrade-from-stable-4.5.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-4.13-upgrade-from-stable-4.6.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-4.13-upgrade-from-stable-4.7.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#35972 skip logs verification in ocp 4.13
  ci-operator/config/medik8s/self-node-remediation/medik8s-self-node-remediation-main__4.13.yaml
Labels: lgtm, approved, rehearsals-ack

#35962 Modify mirroring workflow to generate YearIndex Image Tag
  ci-operator/step-registry/opendatahub-io/ci/image-mirror/opendatahub-io-ci-image-mirror-commands.sh
  ci-operator/step-registry/opendatahub-io/ci/image-mirror/opendatahub-io-ci-image-mirror-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#36020 Login as kubeadmin
  ci-operator/step-registry/redhat-appstudio/e2e/redhat-appstudio-e2e-commands.sh
Labels: lgtm, approved, rehearsals-ack

#35980 Replace current build-root image
  ci-operator/config/openstack-k8s-operators/openstack-k8s-operators-ci/openstack-k8s-operators-openstack-k8s-operators-ci-master.yaml
Labels: lgtm, approved, rehearsals-ack

#36009 openshift-loki: Add ci config for branch upstream-v2.7.3
  ci-operator/config/openshift/loki/openshift-loki-upstream-v2.7.3.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-upstream-v2.7.3-postsubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-upstream-v2.7.3-presubmits.yaml
  core-services/image-mirroring/openshift-logging/mapping_logging_loki_quay
Labels: lgtm, approved, rehearsals-ack

#36017 Fix issue DPTP-3306 Add tags to AWS resources created by HyperShift
  ci-operator/step-registry/hypershift/hostedcluster/create/hostedcluster/hypershift-hostedcluster-create-hostedcluster-commands.sh
Labels: lgtm, approved, rehearsals-ack

#35930 `pod-scaler-ui`: update memory request and limit
  clusters/app.ci/pod-scaler/pod-scaler-ui.yaml
Labels: lgtm, approved, rehearsals-ack

#36024 Add verify-commits job
  ci-operator/config/openshift/aws-ebs-csi-driver/openshift-aws-ebs-csi-driver-master.yaml
  ci-operator/jobs/openshift/aws-ebs-csi-driver/openshift-aws-ebs-csi-driver-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#35748 OCPBUGS-5079: Increase openshift/console e2e-gcp-console test step ti…
  ci-operator/config/openshift/console/openshift-console-master.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-critical, jira/valid-bug, rehearsals-ack, jira/valid-reference

#36027 Sync Serverless CI after removal of event-library image
  ci-operator/config/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-next__412.yaml
  ci-operator/config/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-next__48.yaml
  core-services/image-mirroring/knative/mapping_knative_knative-nightly_eventing-kafka-broker_quay
  core-services/image-mirroring/knative/mapping_knative_knative-v1.4_eventing-kafka-broker_quay
  core-services/image-mirroring/knative/mapping_knative_knative-v1.5_eventing-kafka-broker_quay
  core-services/image-mirroring/knative/mapping_knative_knative-v1.6_eventing-kafka-broker_quay
  core-services/image-mirroring/knative/mapping_knative_knative-v1.7_eventing-kafka-broker_quay
Labels: lgtm, approved, rehearsals-ack

#35987 [WINC-921]: Follow-up add fast-forward workflow
  ci-operator/step-registry/windows/ci/fastforward/windows-ci-fastforward-commands.sh
  ci-operator/step-registry/windows/ci/fastforward/windows-ci-fastforward-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#35994 cert-manager on b02: --dns01-recursive-nameservers='8.8.8.8:53'
  clusters/build-clusters/02_cluster/README.md
  clusters/build-clusters/02_cluster/cert-manager/cert-manager_deployment.yaml
Labels: lgtm, approved, rehearsals-ack

#36031 `pod-scaler-ui`: remove limit to allow for brief heavy memory consumption at startup
  clusters/app.ci/pod-scaler/pod-scaler-ui.yaml
Labels: lgtm, approved, rehearsals-ack

#36032 Print debugging info for HyperShift
  ci-operator/step-registry/hypershift/hostedcluster/create/hostedcluster/hypershift-hostedcluster-create-hostedcluster-commands.sh
  ci-operator/step-registry/hypershift/hostedcluster/destroy/hostedcluster/hypershift-hostedcluster-destroy-hostedcluster-commands.sh
Labels: lgtm, approved, rehearsals-ack

#36037 Revert "Add verify-commit job (#36024)"
  ci-operator/config/openshift/aws-ebs-csi-driver/openshift-aws-ebs-csi-driver-master.yaml
  ci-operator/jobs/openshift/aws-ebs-csi-driver/openshift-aws-ebs-csi-driver-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#36029 rely on non-zonal ova import to import ova to the IBMCloud datacenter
  ci-operator/step-registry/upi/conf/vsphere/zones/upi-conf-vsphere-zones-commands.sh
Labels: lgtm, approved, rehearsals-ack

#35960 hypershift-mce: support downstream
  ci-operator/step-registry/hypershift/mce/aws/create/2.2/hypershift-mce-aws-create-2.2-chain.yaml
  ci-operator/step-registry/hypershift/mce/aws/destroy/2.2/hypershift-mce-aws-destroy-2.2-chain.yaml
  ci-operator/step-registry/hypershift/mce/install/hypershift-mce-install-commands.sh
  ci-operator/step-registry/hypershift/mce/install/hypershift-mce-install-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#36047 chore:drop konveyor/crane* from openshift/release
  core-services/image-mirroring/konveyor/mapping_konveyor_latest
Labels: lgtm, approved, rehearsals-ack

#36046 ci-chat-bot: update hypershift-hosted job
  ci-operator/jobs/openshift/release/openshift-release-infra-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#36045 ovn: increase CNO progressing=true timeouts
  ci-operator/step-registry/ovn/local-to-shared-gateway-mode-migration/ovn-local-to-shared-gateway-mode-migration-commands.sh
  ci-operator/step-registry/ovn/sdn-migration-rollback/ovn-sdn-migration-rollback-commands.sh
  ci-operator/step-registry/ovn/sdn-migration/ovn-sdn-migration-commands.sh
  ci-operator/step-registry/ovn/shared-to-local-gateway-mode-migration/ovn-shared-to-local-gateway-mode-migration-commands.sh
Labels: lgtm, approved, rehearsals-ack

#36035 Bind cluster-reader role to hypershift-pool-admins
  clusters/hive/admin_cluster-reader-1_list.yaml
Labels: lgtm, approved, rehearsals-ack

#36038 Use build_root image from repo
  ci-operator/config/openstack-k8s-operators/openstack-operator/openstack-k8s-operators-openstack-operator-master.yaml
  ci-operator/jobs/openstack-k8s-operators/openstack-operator/openstack-k8s-operators-openstack-operator-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#36016 [4.13] CORS-2420 Compact 3-node Clusters on Public Cloud (GCP)
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.13.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/compact/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/compact/cucushift-installer-rehearse-gcp-ipi-compact-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/compact/cucushift-installer-rehearse-gcp-ipi-compact-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#36025 update azure-ipi-compact workflow with simple way
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.13.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/compact/cucushift-installer-rehearse-azure-ipi-compact-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/compact/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/compact/provision/cucushift-installer-rehearse-azure-ipi-compact-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/compact/provision/cucushift-installer-rehearse-azure-ipi-compact-provision-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#36043 HCO: main: move azure tests to CNV account
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-main.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#36054 HCO move release-1.6 tests to CNV account
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-1.6.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-1.6-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#36007 Update AWS Local Zone jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__arm64-nightly-4.12-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__arm64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-4.13-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#36059 Drop serving 1.3 CI configs
  ci-operator/config/openshift-knative/serving/openshift-knative-serving-release-v1.3__410.yaml
  ci-operator/config/openshift-knative/serving/openshift-knative-serving-release-v1.3__46.yaml
  ci-operator/config/openshift-knative/serving/openshift-knative-serving-release-v1.3__47.yaml
  ci-operator/config/openshift-knative/serving/openshift-knative-serving-release-v1.3__48.yaml
  ci-operator/config/openshift-knative/serving/openshift-knative-serving-release-v1.3__49.yaml
  ci-operator/jobs/openshift-knative/serving/openshift-knative-serving-release-v1.3-periodics.yaml
  ci-operator/jobs/openshift-knative/serving/openshift-knative-serving-release-v1.3-postsubmits.yaml
  ci-operator/jobs/openshift-knative/serving/openshift-knative-serving-release-v1.3-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#36062 update install mce's operator check time
  ci-operator/step-registry/hypershift/mce/install/hypershift-mce-install-commands.sh
Labels: lgtm, approved, rehearsals-ack

#36061 update notification
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#35953 Add new `monitoring-plugin` repo
  ci-operator/config/openshift/monitoring-plugin/OWNERS
  ci-operator/config/openshift/monitoring-plugin/openshift-monitoring-plugin-main.yaml
  ci-operator/jobs/openshift/monitoring-plugin/OWNERS
  ci-operator/jobs/openshift/monitoring-plugin/openshift-monitoring-plugin-main-presubmits.yaml
  core-services/prow/02_config/openshift/monitoring-plugin/OWNERS
  core-services/prow/02_config/openshift/monitoring-plugin/_pluginconfig.yaml
  core-services/prow/02_config/openshift/monitoring-plugin/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#35921 Add assisted events stream
  ci-operator/config/openshift-assisted/assisted-events-stream/OWNERS
  ci-operator/config/openshift-assisted/assisted-events-stream/openshift-assisted-assisted-events-stream-master.yaml
  ci-operator/jobs/openshift-assisted/assisted-events-stream/OWNERS
  ci-operator/jobs/openshift-assisted/assisted-events-stream/openshift-assisted-assisted-events-stream-master-presubmits.yaml
  core-services/prow/02_config/openshift-assisted/assisted-events-stream/_pluginconfig.yaml
  core-services/prow/02_config/openshift-assisted/assisted-events-stream/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#35977 Update OWNER_ALIASES
  OWNERS_ALIASES
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#35741 kubevirt: Move common-templates to gcp-virtualization
  ci-operator/config/kubevirt/common-templates/kubevirt-common-templates-master.yaml
  ci-operator/config/kubevirt/common-templates/kubevirt-common-templates-release-v0.13.yaml
  ci-operator/config/kubevirt/common-templates/kubevirt-common-templates-release-v0.15.yaml
  ci-operator/config/kubevirt/common-templates/kubevirt-common-templates-release-v0.16.yaml
  ci-operator/config/kubevirt/common-templates/kubevirt-common-templates-release-v0.19.yaml
  ci-operator/config/kubevirt/common-templates/kubevirt-common-templates-release-v0.23.yaml
  ci-operator/config/kubevirt/common-templates/kubevirt-common-templates-release-v0.24.yaml
  ci-operator/jobs/kubevirt/common-templates/kubevirt-common-templates-master-presubmits.yaml
  ci-operator/jobs/kubevirt/common-templates/kubevirt-common-templates-release-v0.13-presubmits.yaml
  ci-operator/jobs/kubevirt/common-templates/kubevirt-common-templates-release-v0.15-presubmits.yaml
  ci-operator/jobs/kubevirt/common-templates/kubevirt-common-templates-release-v0.16-presubmits.yaml
  ci-operator/jobs/kubevirt/common-templates/kubevirt-common-templates-release-v0.19-presubmits.yaml
  ci-operator/jobs/kubevirt/common-templates/kubevirt-common-templates-release-v0.23-presubmits.yaml
  ci-operator/jobs/kubevirt/common-templates/kubevirt-common-templates-release-v0.24-presubmits.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#35760 remove tests PR tests for odo repo
  ci-operator/config/redhat-developer/odo/redhat-developer-odo-main.yaml
  ci-operator/config/redhat-developer/odo/redhat-developer-odo-main__v4.11.yaml
  ci-operator/jobs/redhat-developer/odo/redhat-developer-odo-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#35999 Validate number of nodes
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/disconnected/private/network-mtu/localzone/provision/cucushift-installer-rehearse-aws-ipi-disconnected-private-network-mtu-localzone-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/network-mtu/localzone/provision/cucushift-installer-rehearse-aws-ipi-network-mtu-localzone-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/network-mtu/localzone/sdn/provision/cucushift-installer-rehearse-aws-ipi-network-mtu-localzone-sdn-provision-chain.yaml
  ci-operator/step-registry/health-check/OWNERS
  ci-operator/step-registry/health-check/node-count/OWNERS
  ci-operator/step-registry/health-check/node-count/health-check-node-count-commands.sh
  ci-operator/step-registry/health-check/node-count/health-check-node-count-ref.metadata.json
  ci-operator/step-registry/health-check/node-count/health-check-node-count-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#35931 CONSOLE-3303: nodejs-16 and nginx image mirroring for console plugin template
  core-services/image-mirroring-arm64/mapping_supplemental_ci_images_openshift
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_openshift
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#36068 Sync Serverless CI config/eventing-hyperfoil-benchmark.yaml
  ci-operator/config/openshift-knative/eventing-hyperfoil-benchmark/openshift-knative-eventing-hyperfoil-benchmark-main__412.yaml
  ci-operator/jobs/openshift-knative/eventing-hyperfoil-benchmark/openshift-knative-eventing-hyperfoil-benchmark-main-periodics.yaml
  ci-operator/jobs/openshift-knative/eventing-hyperfoil-benchmark/openshift-knative-eventing-hyperfoil-benchmark-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#36076 workflow: cucushift-installer-rehearse-azure-ipi-ovn-hypershift-guest
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/ovn/hypershift/guest/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/ovn/hypershift/guest/cucushift-installer-rehearse-azure-ipi-ovn-hypershift-guest-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/ovn/hypershift/guest/cucushift-installer-rehearse-azure-ipi-ovn-hypershift-guest-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/ovn/hypershift/guest/deprovision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/ovn/hypershift/guest/deprovision/cucushift-installer-rehearse-azure-ipi-ovn-hypershift-guest-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/ovn/hypershift/guest/deprovision/cucushift-installer-rehearse-azure-ipi-ovn-hypershift-guest-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/ovn/hypershift/guest/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/ovn/hypershift/guest/provision/cucushift-installer-rehearse-azure-ipi-ovn-hypershift-guest-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/ovn/hypershift/guest/provision/cucushift-installer-rehearse-azure-ipi-ovn-hypershift-guest-provision-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#36036 Use ocp base images with inlined dockerfile
  ci-operator/config/openshift/agent-installer-utils/openshift-agent-installer-utils-main.yaml
Labels: lgtm, approved, rehearsals-ack

#35906 openstack: fix SDN jobs for installer presubmits
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.12.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.13.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.14.yaml
Labels: lgtm, approved, rehearsals-ack

#36069 Fix ovn-kubernetes image build in 4.11 to 4.12 upgrade jobs
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.12__4.12-upgrade-from-stable-4.11-local-gateway.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.12__4.12-upgrade-from-stable-4.11.yaml
Labels: lgtm, approved, rehearsals-ack

#35937 Add Alex and Alessandro to PKO pipeline approvers
  ci-operator/config/package-operator/package-operator/OWNERS
Labels: lgtm, approved, rehearsals-ack

#35941 TRT-812: Adding periodic for gcp ovn micro upgrades
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.13.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#36084 Bind cluster-reader role to hive-team
  clusters/hive/admin_cluster-reader-1_list.yaml
  core-services/sync-rover-groups/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#36073 MGMT-13577: Dynamically select disk on m3.large
  ci-operator/step-registry/assisted/common/setup/prepare/assisted-common-setup-prepare-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#36085 Removing cross-dependency for multi release-controller
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.13.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  core-services/release-controller/_releases/priv/release-ocp-4.13.json
  core-services/release-controller/_releases/release-ocp-4.13.json
Labels: lgtm, approved, rehearsals-ack

#35978 OSSM 3309: Add maistra istio operator push image jobs
  ci-operator/config/maistra/istio-operator/maistra-istio-operator-maistra-2.3.yaml
  ci-operator/config/maistra/istio-operator/maistra-istio-operator-maistra-2.4.yaml
  ci-operator/jobs/maistra/istio-operator/maistra-istio-operator-maistra-2.3-presubmits.yaml
  ci-operator/jobs/maistra/istio-operator/maistra-istio-operator-maistra-2.4-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#36088 Move aggregated-gcp-ovn-upgrade to informing and not as aggregated
  core-services/release-controller/_releases/priv/release-ocp-4.13.json
  core-services/release-controller/_releases/release-ocp-4.13.json
Labels: lgtm, approved, rehearsals-ack

#36028 cri-o: Skip ci jobs for no-code changes in presubmits
  ci-operator/jobs/cri-o/cri-o/cri-o-cri-o-main-presubmits.yaml
  ci-operator/jobs/cri-o/cri-o/cri-o-cri-o-release-1.22-presubmits.yaml
  ci-operator/jobs/cri-o/cri-o/cri-o-cri-o-release-1.23-presubmits.yaml
  ci-operator/jobs/cri-o/cri-o/cri-o-cri-o-release-1.24-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#35968 Stackrox e2e on PowerVS cluster
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-periodics.yaml
  ci-operator/step-registry/stackrox/automation-flavors/powervs-e2e/OWNERS
  ci-operator/step-registry/stackrox/automation-flavors/powervs-e2e/stackrox-automation-flavors-powervs-e2e-commands.sh
  ci-operator/step-registry/stackrox/automation-flavors/powervs-e2e/stackrox-automation-flavors-powervs-e2e-workflow.metadata.json
  ci-operator/step-registry/stackrox/automation-flavors/powervs-e2e/stackrox-automation-flavors-powervs-e2e-workflow.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#35755 AzureStack UPI needs to remove tech preview credential requests.
  ci-operator/step-registry/upi/install/azurestack/upi-install-azurestack-commands.sh
Labels: lgtm, approved, rehearsals-ack

#36098 Make hypershift aws e2e job a payload informing job
  core-services/release-controller/_releases/priv/release-ocp-4.13.json
  core-services/release-controller/_releases/release-ocp-4.13.json
Labels: lgtm, approved, rehearsals-ack

#36100 OSSM maistra skip report ci/prow/images jobs
  ci-operator/jobs/maistra/api/maistra-api-maistra-2.1-presubmits.yaml
  ci-operator/jobs/maistra/api/maistra-api-maistra-2.2-presubmits.yaml
  ci-operator/jobs/maistra/api/maistra-api-maistra-2.3-presubmits.yaml
  ci-operator/jobs/maistra/api/maistra-api-maistra-2.4-presubmits.yaml
  ci-operator/jobs/maistra/header-append-filter/maistra-header-append-filter-maistra-2.2-presubmits.yaml
  ci-operator/jobs/maistra/header-append-filter/maistra-header-append-filter-maistra-2.3-presubmits.yaml
  ci-operator/jobs/maistra/header-append-filter/maistra-header-append-filter-maistra-2.4-presubmits.yaml
  ci-operator/jobs/maistra/istio-images-centos/maistra-istio-images-centos-maistra-2.2-presubmits.yaml
  ci-operator/jobs/maistra/istio-images-centos/maistra-istio-images-centos-maistra-2.3-presubmits.yaml
  ci-operator/jobs/maistra/istio-images-centos/maistra-istio-images-centos-maistra-2.4-presubmits.yaml
  ci-operator/jobs/maistra/istio-must-gather/maistra-istio-must-gather-maistra-2.2-presubmits.yaml
  ci-operator/jobs/maistra/istio-must-gather/maistra-istio-must-gather-maistra-2.3-presubmits.yaml
  ci-operator/jobs/maistra/istio-must-gather/maistra-istio-must-gather-maistra-2.4-presubmits.yaml
  ci-operator/jobs/maistra/istio-operator/maistra-istio-operator-maistra-2.2-presubmits.yaml
  ci-operator/jobs/maistra/istio-operator/maistra-istio-operator-maistra-2.3-presubmits.yaml
  ci-operator/jobs/maistra/istio-operator/maistra-istio-operator-maistra-2.4-presubmits.yaml
  ci-operator/jobs/maistra/istio/maistra-istio-maistra-2.1-presubmits.yaml
  ci-operator/jobs/maistra/istio/maistra-istio-maistra-2.2-presubmits.yaml
  ci-operator/jobs/maistra/istio/maistra-istio-maistra-2.3-presubmits.yaml
  ci-operator/jobs/maistra/istio/maistra-istio-maistra-2.4-presubmits.yaml
  ci-operator/jobs/maistra/xns-informer/maistra-xns-informer-maistra-2.1-presubmits.yaml
  ci-operator/jobs/maistra/xns-informer/maistra-xns-informer-maistra-2.2-presubmits.yaml
  ci-operator/jobs/maistra/xns-informer/maistra-xns-informer-maistra-2.3-presubmits.yaml
  ci-operator/jobs/maistra/xns-informer/maistra-xns-informer-maistra-2.4-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#35966 Config nmstate-console-plugin prow
  ci-operator/config/openshift/nmstate-console-plugin/OWNERS
  ci-operator/config/openshift/nmstate-console-plugin/openshift-nmstate-console-plugin-main.yaml
  ci-operator/jobs/openshift/nmstate-console-plugin/OWNERS
  ci-operator/jobs/openshift/nmstate-console-plugin/openshift-nmstate-console-plugin-main-presubmits.yaml
  core-services/prow/02_config/openshift/nmstate-console-plugin/_pluginconfig.yaml
  core-services/prow/02_config/openshift/nmstate-console-plugin/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#36072 Add c2s profile to cluster bot
  core-services/ci-chat-bot/workflows-config.yaml
Labels: lgtm, approved, rehearsals-ack

#36102 bootc: Trim plugins
  core-services/prow/02_config/containers/bootc/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#36104 containers/bootc: Add coreos-{reviewers,approvers} for prow config
  core-services/prow/02_config/containers/bootc/OWNERS
Labels: lgtm, approved, rehearsals-ack

#36064 OCPQE-13810 [Azure] fail to get the resource group in step gather-azure-resource of azure-ipi-resourcegroup job
  ci-operator/step-registry/gather/azure-resource/gather-azure-resource-commands.sh
Labels: lgtm, approved, rehearsals-ack

#36109 [CIGolang]change opm location for 413
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-master.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14.yaml
Labels: lgtm, approved, rehearsals-ack

#36078 feat: add win2k22 test lane for tekton task operator
  ci-operator/config/kubevirt/tekton-tasks-operator/kubevirt-tekton-tasks-operator-main.yaml
  ci-operator/jobs/kubevirt/tekton-tasks-operator/kubevirt-tekton-tasks-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#36058 Add a new branch devel for verification-tests
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-devel.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-devel-postsubmits.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-devel-presubmits.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: lgtm, approved, rehearsals-ack

#36002 OCPQE-13626 yaml module is not available in ocp/4.8:upi-installer image
  ci-operator/step-registry/upi/install/aws/cluster/upi-install-aws-cluster-commands.sh
  ci-operator/step-registry/upi/install/azure/upi-install-azure-commands.sh
Labels: lgtm, approved, rehearsals-ack

#36108 OCPQE-13775: Fix selector for destructive test
  ci-operator/step-registry/cucushift/e2e/cucushift-e2e-commands.sh
  ci-operator/step-registry/cucushift/e2e/destructive/cucushift-e2e-destructive-commands.sh
  ci-operator/step-registry/cucushift/e2e/destructive/cucushift-e2e-destructive-ref.yaml
  ci-operator/step-registry/cucushift/e2e/long-duration/cucushift-e2e-long-duration-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#36110 [openshift-loki] Use loki v2.7.3 in operator release branches
  ci-operator/config/openshift/loki/openshift-loki-main.yaml
  ci-operator/config/openshift/loki/openshift-loki-release-5.6.yaml
Labels: lgtm, approved, rehearsals-ack

#36119 Do not trigger optional jobs in test-infra 2.7 branch
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.7-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#36123 add stlaz for backport-risk-assessed in control-plane repos
  core-services/prow/02_config/openshift/apiserver-library-go/_pluginconfig.yaml
  core-services/prow/02_config/openshift/kubernetes/_pluginconfig.yaml
  core-services/prow/02_config/openshift/library-go/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#36126 USHIFT-552: don't build 4.12 images from main branch
  ci-operator/config/openshift/microshift/openshift-microshift-main__periodic-ocp-4.12.yaml
  ci-operator/jobs/openshift/microshift/openshift-microshift-main-periodics.yaml
  ci-operator/jobs/openshift/microshift/openshift-microshift-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#36070 Create a openstack-operators job with tempest
  ci-operator/config/openstack-k8s-operators/openstack-operator/openstack-k8s-operators-openstack-operator-master.yaml
  ci-operator/jobs/openstack-k8s-operators/openstack-operator/openstack-k8s-operators-openstack-operator-master-presubmits.yaml
  ci-operator/step-registry/openstack-k8s-operators/tempest/OWNERS
  ci-operator/step-registry/openstack-k8s-operators/tempest/openstack-k8s-operators-tempest-commands.sh
  ci-operator/step-registry/openstack-k8s-operators/tempest/openstack-k8s-operators-tempest-ref.metadata.json
  ci-operator/step-registry/openstack-k8s-operators/tempest/openstack-k8s-operators-tempest-ref.yaml
  ci-operator/step-registry/openstack-k8s-operators/test/build-deploy-tempest/OWNERS
  ci-operator/step-registry/openstack-k8s-operators/test/build-deploy-tempest/openstack-k8s-operators-test-build-deploy-tempest-workflow.metadata.json
  ci-operator/step-registry/openstack-k8s-operators/test/build-deploy-tempest/openstack-k8s-operators-test-build-deploy-tempest-workflow.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#35879 Use go1.19 for Package Operator tests
  ci-operator/config/package-operator/package-operator/package-operator-package-operator-main.yaml
Labels: lgtm, approved, rehearsals-ack

#32756 Retry on install infrastructure failures
  ci-operator/step-registry/gather/must-gather/gather-must-gather-commands.sh
  ci-operator/step-registry/ipi/install/install/ipi-install-install-commands.sh
Labels: lgtm, approved, rehearsals-ack

#34710 Mirror golangci-lint 1.48.0
  core-services/image-mirroring-arm64/mapping_supplemental_ci_images_ci
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_ci
Labels: lgtm, approved, rehearsals-ack

#36118 Insights Operator - remove px & docs no-FF labels
  core-services/prow/02_config/openshift/insights-operator/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#36127 [neutron-operator] Update functional job
  ci-operator/config/openstack-k8s-operators/neutron-operator/openstack-k8s-operators-neutron-operator-master.yaml
  ci-operator/jobs/openstack-k8s-operators/neutron-operator/openstack-k8s-operators-neutron-operator-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#35893 Bump/remove 4.6/4.7 openshift-ci ClusterPool jobs
  ci-operator/config/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.4__46.yaml
  ci-operator/config/openshift-knative/eventing/openshift-knative-eventing-release-v1.4__46.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.22__4.6.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.23__4.6.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.24__4.6.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.25__4.6.yaml
  ci-operator/config/openshift/aws-account-operator/openshift-aws-account-operator-master.yaml
  ci-operator/config/openshift/hive/openshift-hive-ocm-2.3.yaml
  ci-operator/config/openshift/hive/openshift-hive-ocm-2.4.yaml
  ci-operator/config/openshift/route-monitor-operator/openshift-route-monitor-operator-master.yaml
  ci-operator/config/stackrox/acs-fleet-manager/stackrox-acs-fleet-manager-main.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.4-periodics.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.4-postsubmits.yaml
  ci-operator/jobs/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-v1.4-presubmits.yaml
  ci-operator/jobs/openshift-knative/eventing/openshift-knative-eventing-release-v1.4-periodics.yaml
  ci-operator/jobs/openshift-knative/eventing/openshift-knative-eventing-release-v1.4-postsubmits.yaml
  ci-operator/jobs/openshift-knative/eventing/openshift-knative-eventing-release-v1.4-presubmits.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.22-postsubmits.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.22-presubmits.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.23-postsubmits.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.23-presubmits.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.24-postsubmits.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.24-presubmits.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.25-postsubmits.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.25-presubmits.yaml
  ci-operator/jobs/openshift/route-monitor-operator/openshift-route-monitor-operator-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#35997 Fix makefile compatibility with podman for mac
  Makefile
Labels: lgtm, approved, rehearsals-ack

#36135 ushift: Add team members to microshift rhel OWNERS file
  ci-operator/step-registry/upi/gcp/rhel8/OWNERS
  ci-operator/step-registry/upi/gcp/rhel8/post/upi-gcp-rhel8-post-chain.metadata.json
  ci-operator/step-registry/upi/gcp/rhel8/post/upi-gcp-rhel8-post-ref.metadata.json
  ci-operator/step-registry/upi/gcp/rhel8/pre/upi-gcp-rhel8-pre-chain.metadata.json
  ci-operator/step-registry/upi/gcp/rhel8/pre/upi-gcp-rhel8-pre-ref.metadata.json
  ci-operator/step-registry/upi/gcp/rhel8/upi-gcp-rhel8-workflow.metadata.json
Labels: lgtm, approved, rehearsals-ack

#36141 Hive: Remove EOL ACM/MCE jobs
  ci-operator/config/openshift/hive/openshift-hive-mce-2.1.yaml
  ci-operator/config/openshift/hive/openshift-hive-mce-2.2.yaml
  ci-operator/config/openshift/hive/openshift-hive-ocm-1.0.yaml
  ci-operator/config/openshift/hive/openshift-hive-ocm-2.0.yaml
  ci-operator/config/openshift/hive/openshift-hive-ocm-2.1.yaml
  ci-operator/config/openshift/hive/openshift-hive-ocm-2.2.yaml
  ci-operator/config/openshift/hive/openshift-hive-ocm-2.3.yaml
  ci-operator/config/openshift/hive/openshift-hive-ocm-2.4.yaml
  ci-operator/jobs/openshift/hive/openshift-hive-mce-2.1-postsubmits.yaml
  ci-operator/jobs/openshift/hive/openshift-hive-mce-2.1-presubmits.yaml
  ci-operator/jobs/openshift/hive/openshift-hive-mce-2.2-postsubmits.yaml
  ci-operator/jobs/openshift/hive/openshift-hive-mce-2.2-presubmits.yaml
  ci-operator/jobs/openshift/hive/openshift-hive-ocm-1.0-postsubmits.yaml
  ci-operator/jobs/openshift/hive/openshift-hive-ocm-1.0-presubmits.yaml
  ci-operator/jobs/openshift/hive/openshift-hive-ocm-2.0-postsubmits.yaml
  ci-operator/jobs/openshift/hive/openshift-hive-ocm-2.0-presubmits.yaml
  ci-operator/jobs/openshift/hive/openshift-hive-ocm-2.1-postsubmits.yaml
  ci-operator/jobs/openshift/hive/openshift-hive-ocm-2.1-presubmits.yaml
  ci-operator/jobs/openshift/hive/openshift-hive-ocm-2.2-postsubmits.yaml
  ci-operator/jobs/openshift/hive/openshift-hive-ocm-2.2-presubmits.yaml
  ci-operator/jobs/openshift/hive/openshift-hive-ocm-2.3-postsubmits.yaml
  ci-operator/jobs/openshift/hive/openshift-hive-ocm-2.3-presubmits.yaml
  ci-operator/jobs/openshift/hive/openshift-hive-ocm-2.4-postsubmits.yaml
  ci-operator/jobs/openshift/hive/openshift-hive-ocm-2.4-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#35729 OCPVE-184: Migrate red-hat-storage/lvm-operator to openshift/lvm-operator
  ci-operator/config/openshift/lvm-operator/OWNERS
  ci-operator/config/openshift/lvm-operator/openshift-lvm-operator-main.yaml
  ci-operator/config/openshift/lvm-operator/openshift-lvm-operator-release-4.10.yaml
  ci-operator/config/openshift/lvm-operator/openshift-lvm-operator-release-4.11.yaml
  ci-operator/jobs/openshift/lvm-operator/OWNERS
  ci-operator/jobs/openshift/lvm-operator/openshift-lvm-operator-main-postsubmits.yaml
  ci-operator/jobs/openshift/lvm-operator/openshift-lvm-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/lvm-operator/openshift-lvm-operator-release-4.10-presubmits.yaml
  ci-operator/jobs/openshift/lvm-operator/openshift-lvm-operator-release-4.11-postsubmits.yaml
  ci-operator/jobs/openshift/lvm-operator/openshift-lvm-operator-release-4.11-presubmits.yaml
  ci-operator/jobs/red-hat-storage/lvm-operator/red-hat-storage-lvm-operator-main-postsubmits.yaml
  ci-operator/jobs/red-hat-storage/lvm-operator/red-hat-storage-lvm-operator-release-4.11-postsubmits.yaml
  core-services/prow/02_config/openshift/lvm-operator/OWNERS
  core-services/prow/02_config/openshift/lvm-operator/_pluginconfig.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#36105 Custom Metrics Autoscaler: Add new CI jobs to verify commit messages and check CSVs
  ci-operator/config/openshift-priv/custom-metrics-autoscaler-operator/openshift-priv-custom-metrics-autoscaler-operator-main.yaml
  ci-operator/config/openshift-priv/custom-metrics-autoscaler-operator/openshift-priv-custom-metrics-autoscaler-operator-release-4.11.yaml
  ci-operator/config/openshift-priv/custom-metrics-autoscaler-operator/openshift-priv-custom-metrics-autoscaler-operator-release-4.12.yaml
  ci-operator/config/openshift-priv/custom-metrics-autoscaler-operator/openshift-priv-custom-metrics-autoscaler-operator-release-4.13.yaml
  ci-operator/config/openshift-priv/custom-metrics-autoscaler-operator/openshift-priv-custom-metrics-autoscaler-operator-release-4.14.yaml
  ci-operator/config/openshift/custom-metrics-autoscaler-operator/openshift-custom-metrics-autoscaler-operator-main.yaml
  ci-operator/config/openshift/custom-metrics-autoscaler-operator/openshift-custom-metrics-autoscaler-operator-release-4.11.yaml
  ci-operator/config/openshift/custom-metrics-autoscaler-operator/openshift-custom-metrics-autoscaler-operator-release-4.12.yaml
  ci-operator/config/openshift/custom-metrics-autoscaler-operator/openshift-custom-metrics-autoscaler-operator-release-4.13.yaml
  ci-operator/config/openshift/custom-metrics-autoscaler-operator/openshift-custom-metrics-autoscaler-operator-release-4.14.yaml
  ci-operator/jobs/openshift-priv/custom-metrics-autoscaler-operator/openshift-priv-custom-metrics-autoscaler-operator-main-postsubmits.yaml
  ci-operator/jobs/openshift-priv/custom-metrics-autoscaler-operator/openshift-priv-custom-metrics-autoscaler-operator-main-presubmits.yaml
  ci-operator/jobs/openshift-priv/custom-metrics-autoscaler-operator/openshift-priv-custom-metrics-autoscaler-operator-release-4.11-postsubmits.yaml
  ci-operator/jobs/openshift-priv/custom-metrics-autoscaler-operator/openshift-priv-custom-metrics-autoscaler-operator-release-4.11-presubmits.yaml
  ci-operator/jobs/openshift-priv/custom-metrics-autoscaler-operator/openshift-priv-custom-metrics-autoscaler-operator-release-4.12-postsubmits.yaml
  ci-operator/jobs/openshift-priv/custom-metrics-autoscaler-operator/openshift-priv-custom-metrics-autoscaler-operator-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift-priv/custom-metrics-autoscaler-operator/openshift-priv-custom-metrics-autoscaler-operator-release-4.13-postsubmits.yaml
  ci-operator/jobs/openshift-priv/custom-metrics-autoscaler-operator/openshift-priv-custom-metrics-autoscaler-operator-release-4.13-presubmits.yaml
  ci-operator/jobs/openshift-priv/custom-metrics-autoscaler-operator/openshift-priv-custom-metrics-autoscaler-operator-release-4.14-postsubmits.yaml
  ci-operator/jobs/openshift-priv/custom-metrics-autoscaler-operator/openshift-priv-custom-metrics-autoscaler-operator-release-4.14-presubmits.yaml
  ci-operator/jobs/openshift/custom-metrics-autoscaler-operator/openshift-custom-metrics-autoscaler-operator-main-postsubmits.yaml
  ci-operator/jobs/openshift/custom-metrics-autoscaler-operator/openshift-custom-metrics-autoscaler-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/custom-metrics-autoscaler-operator/openshift-custom-metrics-autoscaler-operator-release-4.11-postsubmits.yaml
  ci-operator/jobs/openshift/custom-metrics-autoscaler-operator/openshift-custom-metrics-autoscaler-operator-release-4.11-presubmits.yaml
  ci-operator/jobs/openshift/custom-metrics-autoscaler-operator/openshift-custom-metrics-autoscaler-operator-release-4.12-postsubmits.yaml
  ci-operator/jobs/openshift/custom-metrics-autoscaler-operator/openshift-custom-metrics-autoscaler-operator-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift/custom-metrics-autoscaler-operator/openshift-custom-metrics-autoscaler-operator-release-4.13-postsubmits.yaml
  ci-operator/jobs/openshift/custom-metrics-autoscaler-operator/openshift-custom-metrics-autoscaler-operator-release-4.13-presubmits.yaml
  ci-operator/jobs/openshift/custom-metrics-autoscaler-operator/openshift-custom-metrics-autoscaler-operator-release-4.14-postsubmits.yaml
  ci-operator/jobs/openshift/custom-metrics-autoscaler-operator/openshift-custom-metrics-autoscaler-operator-release-4.14-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#35703 Kill all references to service-idler
  Makefile
  clusters/app.ci/publicize/_config.yaml
  core-services/openshift-priv/_whitelist.yaml
  core-services/prow/02_config/openshift/service-idler/OWNERS
  core-services/prow/02_config/openshift/service-idler/_pluginconfig.yaml
  core-services/prow/02_config/openshift/service-idler/_prowconfig.yaml
  projects/service-idler/pipeline.yaml
Labels: lgtm, approved, rehearsals-ack

#36101 Bump TALM golang version to 1.19
  ci-operator/config/openshift-kni/cluster-group-upgrades-operator/openshift-kni-cluster-group-upgrades-operator-main.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#36140 Import image
  core-services/image-mirroring-arm64/mapping_supplemental_ci_images_stackrox_rox_ci_image
  core-services/image-mirroring/stackrox/mapping_supplemental_ci_images_stackrox_rox_ci_image
Labels: lgtm, approved, rehearsals-ack

#36145 OSDe2e Hypershift pipelines version rollback patch
  ci-operator/config/openshift/osde2e/openshift-osde2e-main.yaml
Labels: lgtm, approved, rehearsals-ack

#36153 Hive: Get rid of obsolete cmm jobs
  ci-operator/config/openshift/hive/openshift-hive-cmm.yaml
  ci-operator/jobs/openshift/hive/openshift-hive-cmm-postsubmits.yaml
  ci-operator/jobs/openshift/hive/openshift-hive-cmm-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#35796 Update coredns-mdns images to current
  ci-operator/config/openshift/coredns-mdns/openshift-coredns-mdns-master.yaml
Labels: lgtm, approved, rehearsals-ack

#36095 OCPQE-13515 Add workflow for compact 3 node cluster on AWS
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.13.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/compact/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/compact/cucushift-installer-rehearse-aws-ipi-compact-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/compact/cucushift-installer-rehearse-aws-ipi-compact-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#36156 Add step cucushift-e2e-devel for devel branch in repo verification-tests
  ci-operator/step-registry/cucushift/e2e/devel/OWNERS
  ci-operator/step-registry/cucushift/e2e/devel/cucushift-e2e-devel-commands.sh
  ci-operator/step-registry/cucushift/e2e/devel/cucushift-e2e-devel-ref.metadata.json
  ci-operator/step-registry/cucushift/e2e/devel/cucushift-e2e-devel-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#36049 hypershift: hypershift-azure update
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-stable.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#36004 add quay3.8 tests on osd with ocp 4.12
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__quay38-osd-ocp412.yaml
  ci-operator/jobs/quay/quay-tests/quay-quay-tests-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#36129 Fix issue DPTP-3312 Add periodic for clean up HyperShift leaked resources
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
  ci-operator/jobs/infra-periodics.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#36083 Remove ocs-must-gather image from ocs-operator ci workflow
  ci-operator/config/red-hat-storage/ocs-operator/red-hat-storage-ocs-operator-main.yaml
  ci-operator/config/red-hat-storage/ocs-operator/red-hat-storage-ocs-operator-main__latest-upstream.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#36091 cri-o: Add release-1.25 tests config and presubmit jobs
  ci-operator/config/cri-o/cri-o/cri-o-cri-o-release-1.25.yaml
  ci-operator/jobs/cri-o/cri-o/cri-o-cri-o-release-1.25-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#36125 Revert "Rename e2e-openstack-sdn-upgrade to ovn"
  ci-operator/config/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main__periodic-4.12-upgrade-from-stable-4.11.yaml
  ci-operator/jobs/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack
