Repository openshift/release, pull requests merged in 2024-01, with the labels that each got.

#47125 Remove NVIDIA GPU operator 23.3.x due to EOL
  ci-operator/config/rh-ecosystem-edge/ci-tools-nvidia-gpu-operator/rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main__4.11.yaml
  ci-operator/config/rh-ecosystem-edge/ci-tools-nvidia-gpu-operator/rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main__4.12.yaml
  ci-operator/config/rh-ecosystem-edge/ci-tools-nvidia-gpu-operator/rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main__4.13.yaml
  ci-operator/jobs/rh-ecosystem-edge/ci-tools-nvidia-gpu-operator/rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#47082 migrate aws arm/amd profiles to multiarch profiles on 4.12/4.13/4.14
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__multi-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#47128 OCPQE-18492: Remove tag singlenode
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-nightly.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#46287 Adding upgrade test from 4.1 to 4.15
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly-4.15-upgrade-from-stable-4.1.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
  ci-operator/step-registry/cucushift/chainupgrade/toimage/cucushift-chainupgrade-toimage-commands.sh
Labels: lgtm, approved, rehearsals-ack

#46874 OCPQE-18082: Deploy disconnected OpenShift cluster behind http proxy with Workload Identity on Google Cloud
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__multi-nightly.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.15.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/proxy/cco-manual-workload-identity/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/proxy/cco-manual-workload-identity/cucushift-installer-rehearse-gcp-ipi-proxy-cco-manual-workload-identity-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/proxy/cco-manual-workload-identity/cucushift-installer-rehearse-gcp-ipi-proxy-cco-manual-workload-identity-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/proxy/cco-manual-workload-identity/deprovision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/proxy/cco-manual-workload-identity/deprovision/cucushift-installer-rehearse-gcp-ipi-proxy-cco-manual-workload-identity-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/proxy/cco-manual-workload-identity/deprovision/cucushift-installer-rehearse-gcp-ipi-proxy-cco-manual-workload-identity-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/proxy/cco-manual-workload-identity/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/proxy/cco-manual-workload-identity/provision/cucushift-installer-rehearse-gcp-ipi-proxy-cco-manual-workload-identity-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/proxy/cco-manual-workload-identity/provision/cucushift-installer-rehearse-gcp-ipi-proxy-cco-manual-workload-identity-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/proxy/provision/cucushift-installer-rehearse-gcp-ipi-proxy-provision-chain.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#47084 Improve version coverage for the rosa/rosa hcp clusters
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-master__rosacli.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#47050 update description for workers-infra-workload
  ci-operator/step-registry/openshift-qe/workers-infra-workload/openshift-qe-workers-infra-workload-commands.sh
  ci-operator/step-registry/openshift-qe/workers-infra-workload/openshift-qe-workers-infra-workload-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#44567 OCPQE-18524:Fix registry with nutanix object storage
  ci-operator/step-registry/configure-registry-storage/set-nutanix-object/configure-registry-storage-set-nutanix-object-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#47126 Revert "2023 year end recharge scale back"
  clusters/hive/pools/cvp/cvp-ocp-4-11-amd64-aws-eu-west-2_clusterpool.yaml
  clusters/hive/pools/cvp/cvp-ocp-4-12-amd64-aws-eu-west-3_clusterpool.yaml
  clusters/hive/pools/cvp/cvp-ocp-4-13-amd64-aws-eu-central-1_clusterpool.yaml
  clusters/hive/pools/cvp/cvp-ocp-4-14-amd64-aws-eu-north-1_clusterpool.yaml
  clusters/hive/pools/cvp/cvp-ocp-4-15-amd64-aws-eu-west-1_clusterpool.yaml
Labels: lgtm, approved, rehearsals-ack

#46935 OCPQE-18079: Install OCP to a shared VPC, with credentialsMode "Manual" and Workload Identity
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__multi-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/xpn/cco-manual-workload-identity/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/xpn/cco-manual-workload-identity/cucushift-installer-rehearse-gcp-ipi-xpn-cco-manual-workload-identity-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/xpn/cco-manual-workload-identity/cucushift-installer-rehearse-gcp-ipi-xpn-cco-manual-workload-identity-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/xpn/cco-manual-workload-identity/deprovision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/xpn/cco-manual-workload-identity/deprovision/cucushift-installer-rehearse-gcp-ipi-xpn-cco-manual-workload-identity-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/xpn/cco-manual-workload-identity/deprovision/cucushift-installer-rehearse-gcp-ipi-xpn-cco-manual-workload-identity-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/xpn/cco-manual-workload-identity/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/xpn/cco-manual-workload-identity/provision/cucushift-installer-rehearse-gcp-ipi-xpn-cco-manual-workload-identity-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/xpn/cco-manual-workload-identity/provision/cucushift-installer-rehearse-gcp-ipi-xpn-cco-manual-workload-identity-provision-chain.yaml
  ci-operator/step-registry/gcp/deprovision/iam-creds-xpn-roles/OWNERS
  ci-operator/step-registry/gcp/deprovision/iam-creds-xpn-roles/gcp-deprovision-iam-creds-xpn-roles-commands.sh
  ci-operator/step-registry/gcp/deprovision/iam-creds-xpn-roles/gcp-deprovision-iam-creds-xpn-roles-ref.metadata.json
  ci-operator/step-registry/gcp/deprovision/iam-creds-xpn-roles/gcp-deprovision-iam-creds-xpn-roles-ref.yaml
  ci-operator/step-registry/gcp/provision/iam-creds-xpn-roles/OWNERS
  ci-operator/step-registry/gcp/provision/iam-creds-xpn-roles/gcp-provision-iam-creds-xpn-roles-commands.sh
  ci-operator/step-registry/gcp/provision/iam-creds-xpn-roles/gcp-provision-iam-creds-xpn-roles-ref.metadata.json
  ci-operator/step-registry/gcp/provision/iam-creds-xpn-roles/gcp-provision-iam-creds-xpn-roles-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#47085 OCPQE-18322: Invoke e2e test on hypershift-agent-mce-dualstack
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#47120 Update quay dast test image
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__quay-dast.yaml
Labels: lgtm, approved, tide/merge-method-squash, rehearsals-ack

#47093 OCPQE-18528: automate OCP-68544 OCP-68545 and OCP-68546
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.14.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.15.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.16.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
  ci-operator/step-registry/cucushift/installer/check/azure/vm-generation/OWNERS
  ci-operator/step-registry/cucushift/installer/check/azure/vm-generation/cucushift-installer-check-azure-vm-generation-commands.sh
  ci-operator/step-registry/cucushift/installer/check/azure/vm-generation/cucushift-installer-check-azure-vm-generation-ref.metadata.json
  ci-operator/step-registry/cucushift/installer/check/azure/vm-generation/cucushift-installer-check-azure-vm-generation-ref.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/generation/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/generation/cucushift-installer-rehearse-azure-ipi-generation-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/generation/cucushift-installer-rehearse-azure-ipi-generation-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/generation/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/generation/provision/cucushift-installer-rehearse-azure-ipi-generation-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/generation/provision/cucushift-installer-rehearse-azure-ipi-generation-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/usertags/cucushift-installer-rehearse-azure-ipi-usertags-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/usertags/storage-account-encryption/provision/cucushift-installer-rehearse-azure-ipi-usertags-storage-account-encryption-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/vmgenv1/cucushift-installer-rehearse-azure-ipi-vmgenv1-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/vmgenv1/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/vmgenv1/provision/cucushift-installer-rehearse-azure-ipi-vmgenv1-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/vmgenv1/provision/cucushift-installer-rehearse-azure-ipi-vmgenv1-provision-chain.yaml
  ci-operator/step-registry/ipi/conf/azure/vmgenv1/ipi-conf-azure-vmgenv1-commands.sh
  ci-operator/step-registry/ipi/conf/azure/vmgenv1/ipi-conf-azure-vmgenv1-ref.metadata.json
  ci-operator/step-registry/ipi/conf/azure/vmgenv1/ipi-conf-azure-vmgenv1-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#47135 Add upgrade tests for stable 4.14 to stable 4.15
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-stable-4.15-upgrade-from-stable-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__arm64-stable-4.15-upgrade-from-stable-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__multi-stable-4.15-upgrade-from-stable-4.14.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#47130 Add release image controller quay org and token
  ci-operator/step-registry/redhat-appstudio/e2e/redhat-appstudio-e2e-commands.sh
Labels: lgtm, approved, rehearsals-ack

#47139 chore(RHTAP-2101): turn on CI jobs turned off during shutdown period
  ci-operator/config/redhat-appstudio/e2e-tests/redhat-appstudio-e2e-tests-main.yaml
  ci-operator/jobs/redhat-appstudio/e2e-tests/redhat-appstudio-e2e-tests-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#47122 trt-923: add out-of-change informing
  core-services/release-controller/_releases/priv/release-ocp-4.16.json
  core-services/release-controller/_releases/release-ocp-4.16.json
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#46981 chore(SRVKP-3752): Switch Pipelines perf tests to dedicated AWS account
  ci-operator/config/openshift-pipelines/performance/openshift-pipelines-performance-master.yaml
  ci-operator/jobs/openshift-pipelines/performance/openshift-pipelines-performance-master-periodics.yaml
  ci-operator/jobs/openshift-pipelines/performance/openshift-pipelines-performance-master-presubmits.yaml
  ci-operator/step-registry/openshift-pipelines/max-concurrency/openshift-pipelines-max-concurrency-workflow.yaml
  ci-operator/step-registry/openshift-pipelines/scaling-pipelines/openshift-pipelines-scaling-pipelines-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#47036 chore(RHIDP-885): Use new AWS account to run Backstage perf&scale tests
  ci-operator/config/redhat-performance/backstage-performance/redhat-performance-backstage-performance-main.yaml
  ci-operator/jobs/redhat-performance/backstage-performance/redhat-performance-backstage-performance-main-presubmits.yaml
  ci-operator/step-registry/redhat-performance/backstage-performance/redhat-performance-backstage-performance-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#45947 update update_upi-conf-vsphere-zones-commands.sh to fix terraform apply failure.
  ci-operator/step-registry/upi/conf/vsphere/zones/upi-conf-vsphere-zones-commands.sh
Labels: lgtm, approved, rehearsals-ack

#47142 Updating 4.11 and prow test builds
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-enterprise-4.11.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-prow-test.yaml
  ci-operator/jobs/openshift/openshift-docs/openshift-openshift-docs-prow-test-presubmits.yaml
  ci-operator/step-registry/openshift-docs/portal/openshift-docs-portal-commands.sh
  ci-operator/step-registry/openshift-docs/portal/openshift-docs-portal-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#47096 terraform-provider-rhcs: Add 2 more test suits
  ci-operator/config/terraform-redhat/terraform-provider-rhcs/terraform-redhat-terraform-provider-rhcs-main.yaml
  ci-operator/jobs/terraform-redhat/terraform-provider-rhcs/terraform-redhat-terraform-provider-rhcs-main-periodics.yaml
  ci-operator/jobs/terraform-redhat/terraform-provider-rhcs/terraform-redhat-terraform-provider-rhcs-main-presubmits.yaml
  ci-operator/step-registry/rhcs/e2e/general-tests/OWNERS
  ci-operator/step-registry/rhcs/e2e/general-tests/rhcs-e2e-general-tests-commands.sh
  ci-operator/step-registry/rhcs/e2e/general-tests/rhcs-e2e-general-tests-ref.metadata.json
  ci-operator/step-registry/rhcs/e2e/general-tests/rhcs-e2e-general-tests-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#42406 Loki ipv6 support
  ci-operator/step-registry/baremetalds/devscripts/proxy/baremetalds-devscripts-proxy-commands.sh
  ci-operator/step-registry/baremetalds/devscripts/setup/baremetalds-devscripts-setup-commands.sh
  ci-operator/step-registry/baremetalds/ipi/pre/baremetalds-ipi-pre-chain.yaml
  ci-operator/step-registry/baremetalds/ofcir/pre/baremetalds-ofcir-pre-chain.yaml
  ci-operator/step-registry/ipi/install/hosted-loki/ipi-install-hosted-loki-commands.sh
Labels: lgtm, approved, lifecycle/stale, rehearsals-ack

#47147 Setting action to only 1
  ci-operator/step-registry/redhat-chaos/container-scenarios/etcd-hangup/redhat-chaos-container-scenarios-etcd-hangup-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#47152 DPTP-3609 Set test-platform-results as an alias for origin-ci-test
  clusters/app.ci/app.ci/prow/staging/gcsweb.yaml
Labels: lgtm, approved, rehearsals-ack

#46911 Start moving Prow jobs over from 4.12 to 4.14 Hive cluster
  ci-operator/config/openstack-k8s-operators/horizon-operator/openstack-k8s-operators-horizon-operator-main.yaml
  ci-operator/config/openstack-k8s-operators/manila-operator/openstack-k8s-operators-manila-operator-main.yaml
Labels: lgtm, approved, rehearsals-ack

#47129 OCPQE-18510: Optimize the test filter for cucushift on fips
  ci-operator/step-registry/cucushift/e2e/cucushift-e2e-commands.sh
  ci-operator/step-registry/cucushift/e2e/destructive/cucushift-e2e-destructive-commands.sh
  ci-operator/step-registry/cucushift/e2e/devel/cucushift-e2e-devel-commands.sh
  ci-operator/step-registry/cucushift/e2e/longduration/cucushift-e2e-longduration-commands.sh
  ci-operator/step-registry/cucushift/e2e/ui/cucushift-e2e-ui-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#47078 Update node scan result to fail when there is a warning reported
  ci-operator/step-registry/fips-check/node-scan/fips-check-node-scan-commands.sh
Labels: lgtm, approved, rehearsals-ack

#47132 fix sp creation failed
  ci-operator/step-registry/azure/provision/bastionhost/azure-provision-bastionhost-commands.sh
  ci-operator/step-registry/azure/provision/service-principal/minimal-permission/azure-provision-service-principal-minimal-permission-commands.sh
Labels: lgtm, approved, rehearsals-ack

#47131 OCPQE-18089: Config CCO in manual mode and provide credentials manually
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.14.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.15.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.16.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/cco-manual-users-static/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/cco-manual-users-static/cucushift-installer-rehearse-gcp-ipi-cco-manual-users-static-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/cco-manual-users-static/cucushift-installer-rehearse-gcp-ipi-cco-manual-users-static-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/cco-manual-users-static/deprovision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/cco-manual-users-static/deprovision/cucushift-installer-rehearse-gcp-ipi-cco-manual-users-static-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/cco-manual-users-static/deprovision/cucushift-installer-rehearse-gcp-ipi-cco-manual-users-static-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/cco-manual-users-static/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/cco-manual-users-static/provision/cucushift-installer-rehearse-gcp-ipi-cco-manual-users-static-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/cco-manual-users-static/provision/cucushift-installer-rehearse-gcp-ipi-cco-manual-users-static-provision-chain.yaml
  ci-operator/step-registry/gcp/deprovision/cco-manual-users/OWNERS
  ci-operator/step-registry/gcp/deprovision/cco-manual-users/static/OWNERS
  ci-operator/step-registry/gcp/deprovision/cco-manual-users/static/gcp-deprovision-cco-manual-users-static-commands.sh
  ci-operator/step-registry/gcp/deprovision/cco-manual-users/static/gcp-deprovision-cco-manual-users-static-ref.metadata.json
  ci-operator/step-registry/gcp/deprovision/cco-manual-users/static/gcp-deprovision-cco-manual-users-static-ref.yaml
  ci-operator/step-registry/gcp/provision/cco-manual-users/OWNERS
  ci-operator/step-registry/gcp/provision/cco-manual-users/static/OWNERS
  ci-operator/step-registry/gcp/provision/cco-manual-users/static/gcp-provision-cco-manual-users-static-commands.sh
  ci-operator/step-registry/gcp/provision/cco-manual-users/static/gcp-provision-cco-manual-users-static-ref.metadata.json
  ci-operator/step-registry/gcp/provision/cco-manual-users/static/gcp-provision-cco-manual-users-static-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#47163 installer-aro: update memory limits to match upstream for unit tests
  ci-operator/config/openshift/installer-aro/openshift-installer-aro-main.yaml
  ci-operator/config/openshift/installer-aro/openshift-installer-aro-release-4.10-azure.yaml
  ci-operator/config/openshift/installer-aro/openshift-installer-aro-release-4.11-azure.yaml
  ci-operator/config/openshift/installer-aro/openshift-installer-aro-release-4.12-azure.yaml
  ci-operator/config/openshift/installer-aro/openshift-installer-aro-release-4.13-azure.yaml
  ci-operator/config/openshift/installer-aro/openshift-installer-aro-release-4.14-azure.yaml
Labels: lgtm, approved, rehearsals-ack

#47158 OCPQE-18510: Remove tag 'not @fips'
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__ppc64le-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__ppc64le-nightly.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#47170 OCPBUGS-24735: Add security scan for openshift-ibm-powervs-block-csi-driver-operator
  ci-operator/config/openshift/ibm-powervs-block-csi-driver-operator/openshift-ibm-powervs-block-csi-driver-operator-main.yaml
  ci-operator/config/openshift/ibm-powervs-block-csi-driver-operator/openshift-ibm-powervs-block-csi-driver-operator-release-4.12.yaml
  ci-operator/config/openshift/ibm-powervs-block-csi-driver-operator/openshift-ibm-powervs-block-csi-driver-operator-release-4.13.yaml
  ci-operator/config/openshift/ibm-powervs-block-csi-driver-operator/openshift-ibm-powervs-block-csi-driver-operator-release-4.14.yaml
  ci-operator/config/openshift/ibm-powervs-block-csi-driver-operator/openshift-ibm-powervs-block-csi-driver-operator-release-4.15.yaml
  ci-operator/config/openshift/ibm-powervs-block-csi-driver-operator/openshift-ibm-powervs-block-csi-driver-operator-release-4.16.yaml
  ci-operator/jobs/openshift/ibm-powervs-block-csi-driver-operator/openshift-ibm-powervs-block-csi-driver-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/ibm-powervs-block-csi-driver-operator/openshift-ibm-powervs-block-csi-driver-operator-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift/ibm-powervs-block-csi-driver-operator/openshift-ibm-powervs-block-csi-driver-operator-release-4.13-presubmits.yaml
  ci-operator/jobs/openshift/ibm-powervs-block-csi-driver-operator/openshift-ibm-powervs-block-csi-driver-operator-release-4.14-presubmits.yaml
  ci-operator/jobs/openshift/ibm-powervs-block-csi-driver-operator/openshift-ibm-powervs-block-csi-driver-operator-release-4.15-presubmits.yaml
  ci-operator/jobs/openshift/ibm-powervs-block-csi-driver-operator/openshift-ibm-powervs-block-csi-driver-operator-release-4.16-presubmits.yaml
Labels: lgtm, approved, jira/valid-bug, rehearsals-ack, jira/valid-reference

#47179 NO-ISSUE: Enable assisted vsphere job
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#44603 MULTIARCH-3987: Add security scan for openshift-ibm-powervs-block-csi-driver
  ci-operator/config/openshift/ibm-powervs-block-csi-driver/openshift-ibm-powervs-block-csi-driver-main.yaml
  ci-operator/config/openshift/ibm-powervs-block-csi-driver/openshift-ibm-powervs-block-csi-driver-release-4.12.yaml
  ci-operator/config/openshift/ibm-powervs-block-csi-driver/openshift-ibm-powervs-block-csi-driver-release-4.13.yaml
  ci-operator/config/openshift/ibm-powervs-block-csi-driver/openshift-ibm-powervs-block-csi-driver-release-4.14.yaml
  ci-operator/config/openshift/ibm-powervs-block-csi-driver/openshift-ibm-powervs-block-csi-driver-release-4.15.yaml
  ci-operator/config/openshift/ibm-powervs-block-csi-driver/openshift-ibm-powervs-block-csi-driver-release-4.16.yaml
  ci-operator/jobs/openshift/ibm-powervs-block-csi-driver/openshift-ibm-powervs-block-csi-driver-main-presubmits.yaml
  ci-operator/jobs/openshift/ibm-powervs-block-csi-driver/openshift-ibm-powervs-block-csi-driver-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift/ibm-powervs-block-csi-driver/openshift-ibm-powervs-block-csi-driver-release-4.13-presubmits.yaml
  ci-operator/jobs/openshift/ibm-powervs-block-csi-driver/openshift-ibm-powervs-block-csi-driver-release-4.14-presubmits.yaml
  ci-operator/jobs/openshift/ibm-powervs-block-csi-driver/openshift-ibm-powervs-block-csi-driver-release-4.15-presubmits.yaml
  ci-operator/jobs/openshift/ibm-powervs-block-csi-driver/openshift-ibm-powervs-block-csi-driver-release-4.16-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#47161 OCPQE-18599: add workflow azure-ipi-marketplace-minimal-permission
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.15.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
  ci-operator/step-registry/azure/provision/service-principal/minimal-permission/azure-provision-service-principal-minimal-permission-commands.sh
  ci-operator/step-registry/azure/provision/service-principal/minimal-permission/azure-provision-service-principal-minimal-permission-ref.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/marketplace/minimal-permission/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/marketplace/minimal-permission/cucushift-installer-rehearse-azure-ipi-marketplace-minimal-permission-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/marketplace/minimal-permission/cucushift-installer-rehearse-azure-ipi-marketplace-minimal-permission-workflow.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#47171 Add Quay DAST Test image with required python 3.11
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__quay-dast.yaml
Labels: lgtm, approved, tide/merge-method-squash, rehearsals-ack

#47191 DPTP-3807: Configuring bugzilla and jira validation criteria
  core-services/jira-lifecycle-plugin/config.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#47169 OCPQE-18080: Install OCP to a shared VPC on GCP, with credentialsMode "Manual" and static credentials
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.14.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.15.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.16.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.15.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/xpn/cco-manual-users-static/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/xpn/cco-manual-users-static/cucushift-installer-rehearse-gcp-ipi-xpn-cco-manual-users-static-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/xpn/cco-manual-users-static/cucushift-installer-rehearse-gcp-ipi-xpn-cco-manual-users-static-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/xpn/cco-manual-users-static/deprovision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/xpn/cco-manual-users-static/deprovision/cucushift-installer-rehearse-gcp-ipi-xpn-cco-manual-users-static-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/xpn/cco-manual-users-static/deprovision/cucushift-installer-rehearse-gcp-ipi-xpn-cco-manual-users-static-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/xpn/cco-manual-users-static/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/xpn/cco-manual-users-static/provision/cucushift-installer-rehearse-gcp-ipi-xpn-cco-manual-users-static-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/xpn/cco-manual-users-static/provision/cucushift-installer-rehearse-gcp-ipi-xpn-cco-manual-users-static-provision-chain.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#47168 Promote the Distributed Tracing tests runner image for running acceptance tests.
  ci-operator/config/openshift/distributed-tracing-qe/openshift-distributed-tracing-qe-main__ocp4.13-amd64-acceptance.yaml
  ci-operator/config/openshift/distributed-tracing-qe/openshift-distributed-tracing-qe-main__ocp4.13-amd64.yaml
  ci-operator/jobs/openshift/distributed-tracing-qe/openshift-distributed-tracing-qe-main-postsubmits.yaml
  ci-operator/jobs/openshift/distributed-tracing-qe/openshift-distributed-tracing-qe-main-presubmits.yaml
  ci-operator/step-registry/distributed-tracing/tests/common/acceptance/OWNERS
  ci-operator/step-registry/distributed-tracing/tests/common/acceptance/distributed-tracing-tests-common-acceptance-commands.sh
  ci-operator/step-registry/distributed-tracing/tests/common/acceptance/distributed-tracing-tests-common-acceptance-ref.metadata.json
  ci-operator/step-registry/distributed-tracing/tests/common/acceptance/distributed-tracing-tests-common-acceptance-ref.yaml
  ci-operator/step-registry/distributed-tracing/tests/common/distributed-tracing-tests-common-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#47156 Move 3 nodes from 4.12 cluster pool into 4.14
  clusters/hive/pools/openstack-k8s-operators/openstack-k8s-operators-4-12-vexxhost-hybrid_clusterpool.yaml
  clusters/hive/pools/openstack-k8s-operators/openstack-k8s-operators-4-14-vexxhost-hybrid_clusterpool.yaml
Labels: lgtm, approved, rehearsals-ack

#46906 Add golang 1.20 and 1.21 container images
  ci-operator/config/openstack-k8s-operators/openstack-k8s-operators-ci/openstack-k8s-operators-openstack-k8s-operators-ci-main.yaml
Labels: lgtm, approved, rehearsals-ack

#47199 DPTP-3808: Update periodic-openshift-release-merge-blockers
  ci-operator/jobs/infra-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#45547 Add security scanner to openstack repos
  ci-operator/config/openshift/cloud-provider-openstack/openshift-cloud-provider-openstack-master.yaml
  ci-operator/config/openshift/cluster-api-provider-openstack/openshift-cluster-api-provider-openstack-main.yaml
  ci-operator/config/openshift/csi-driver-manila-operator/openshift-csi-driver-manila-operator-master.yaml
  ci-operator/config/openshift/csi-driver-nfs/openshift-csi-driver-nfs-master.yaml
  ci-operator/config/openshift/machine-api-provider-openstack/openshift-machine-api-provider-openstack-master.yaml
  ci-operator/config/openshift/openstack-cinder-csi-driver-operator/openshift-openstack-cinder-csi-driver-operator-master.yaml
  ci-operator/jobs/openshift/cloud-provider-openstack/openshift-cloud-provider-openstack-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-openstack/openshift-cluster-api-provider-openstack-main-presubmits.yaml
  ci-operator/jobs/openshift/csi-driver-manila-operator/openshift-csi-driver-manila-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/csi-driver-nfs/openshift-csi-driver-nfs-master-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-provider-openstack/openshift-machine-api-provider-openstack-master-presubmits.yaml
  ci-operator/jobs/openshift/openstack-cinder-csi-driver-operator/openshift-openstack-cinder-csi-driver-operator-master-presubmits.yaml
Labels: lgtm, approved, lifecycle/stale, rehearsals-ack

#47134 chore: remove kepler references from jobs
  ci-operator/config/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-v1alpha1.yaml
  ci-operator/config/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-v1alpha1__ocp4.13-periodic.yaml
  ci-operator/config/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-v1alpha1__ocp4.14-periodic.yaml
  ci-operator/config/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-v1alpha1__post-submit.yaml
  ci-operator/jobs/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-v1alpha1-periodics.yaml
  ci-operator/jobs/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-v1alpha1-postsubmits.yaml
  ci-operator/jobs/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-v1alpha1-presubmits.yaml
  ci-operator/step-registry/openshift-power-monitoring/tests/kepler/openshift-power-monitoring-tests-kepler-ref.yaml
  ci-operator/step-registry/openshift-power-monitoring/tests/power-monitoring-operator/OWNERS
  ci-operator/step-registry/openshift-power-monitoring/tests/power-monitoring-operator/README.md
  ci-operator/step-registry/openshift-power-monitoring/tests/power-monitoring-operator/openshift-power-monitoring-tests-power-monitoring-operator-commands.sh
  ci-operator/step-registry/openshift-power-monitoring/tests/power-monitoring-operator/openshift-power-monitoring-tests-power-monitoring-operator-ref.metadata.json
  ci-operator/step-registry/openshift-power-monitoring/tests/power-monitoring-operator/openshift-power-monitoring-tests-power-monitoring-operator-ref.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: lgtm, approved, rehearsals-ack

#46991 Add config for stackrox ui component test job
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#46632 IO test report generation in artifacts
  ci-operator/config/openshift/insights-operator/openshift-insights-operator-master.yaml
Labels: lgtm, approved, rehearsals-ack

#47198 `payload testing`: remove deprecated pullRequest field from CRD
  clusters/app.ci/prow/01_crd/pullrequestpayloadqualificationruns.yaml
Labels: lgtm, approved, rehearsals-ack

#47202 Update label access for openshift/etcd repository
  core-services/prow/02_config/openshift/etcd/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#47143 Support specifying zones to create NodePools for Hypershift
  ci-operator/step-registry/hypershift/aws/create/hypershift-aws-create-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#47178 Workaorund for failing tests
  ci-operator/config/openshift/openstack-ironic-python-agent/openshift-openstack-ironic-python-agent-release-4.13.yaml
  ci-operator/config/openshift/openstack-ironic-python-agent/openshift-openstack-ironic-python-agent-release-4.14.yaml
  ci-operator/config/openshift/openstack-ironic-python-agent/openshift-openstack-ironic-python-agent-release-4.15.yaml
  ci-operator/jobs/openshift/openstack-ironic-python-agent/openshift-openstack-ironic-python-agent-release-4.13-postsubmits.yaml
  ci-operator/jobs/openshift/openstack-ironic-python-agent/openshift-openstack-ironic-python-agent-release-4.13-presubmits.yaml
  ci-operator/jobs/openshift/openstack-ironic-python-agent/openshift-openstack-ironic-python-agent-release-4.14-postsubmits.yaml
  ci-operator/jobs/openshift/openstack-ironic-python-agent/openshift-openstack-ironic-python-agent-release-4.14-presubmits.yaml
  ci-operator/jobs/openshift/openstack-ironic-python-agent/openshift-openstack-ironic-python-agent-release-4.15-postsubmits.yaml
  ci-operator/jobs/openshift/openstack-ironic-python-agent/openshift-openstack-ironic-python-agent-release-4.15-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#47185 NO-ISSUE: Use cheaper machine for ztp jobs
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-main__edge.yaml
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.6.yaml
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.7.yaml
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.8.yaml
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.9.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master__edge.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.6.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.7.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.8.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.9.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-master__edge.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.6.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.7.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.8.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.9.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.6.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.7.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.8.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.9.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#47201 Add bastion host user variable
  ci-operator/step-registry/telco5g/cluster-setup/telco5g-cluster-setup-commands.sh
Labels: lgtm, approved, rehearsals-ack

#47207 Add back deployment for gcsweb
  clusters/app.ci/prow/03_deployment/gcsweb.yaml
Labels: lgtm, approved, rehearsals-ack

#47209 Use RHEL9 as base image for cnf-tests
  ci-operator/config/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-master.yaml
Labels: lgtm, approved, rehearsals-ack

#47213 Add `cluster-config-api-changed` label to openshift-kni/lifecycle-agent
  core-services/prow/02_config/_labels.yaml
  core-services/prow/02_config/openshift-kni/lifecycle-agent/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#47162 stackrox: provide a step name env value
  ci-operator/step-registry/stackrox/e2e/stackrox-e2e-commands.sh
  ci-operator/step-registry/stackrox/stackrox/begin/stackrox-stackrox-begin-commands.sh
  ci-operator/step-registry/stackrox/stackrox/e2e-test/stackrox-stackrox-e2e-test-commands.sh
  ci-operator/step-registry/stackrox/stackrox/end/stackrox-stackrox-end-commands.sh
Labels: lgtm, approved, rehearsals-ack

#47215 try rebase merge for CLO
  core-services/prow/02_config/openshift/cluster-logging-operator/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#47193 Remove the reset_host function
  ci-operator/step-registry/baremetal/lab/agent/install/baremetal-lab-agent-install-commands.sh
  ci-operator/step-registry/baremetal/lab/agent/install/ephemeral/boot-unconfigured-image/baremetal-lab-agent-install-ephemeral-boot-unconfigured-image-commands.sh
  ci-operator/step-registry/baremetal/lab/ipi/install/baremetal-lab-ipi-install-commands.sh
  ci-operator/step-registry/baremetal/lab/post/wipe/baremetal-lab-post-wipe-commands.sh
  ci-operator/step-registry/baremetal/lab/upi/install/baremetal-lab-upi-install-commands.sh
  ci-operator/step-registry/upi/install/heterogeneous/upi-install-heterogeneous-commands.sh
Labels: lgtm, approved, rehearsals-ack

#47212 Use bastionuser secret in sno-setup and cluster-setup scripts
  ci-operator/step-registry/telco5g/cluster-setup/telco5g-cluster-setup-commands.sh
  ci-operator/step-registry/telco5g/cluster-setup/telco5g-cluster-setup-ref.yaml
  ci-operator/step-registry/telco5g/sno-setup/telco5g-sno-setup-commands.sh
  ci-operator/step-registry/telco5g/sno-setup/telco5g-sno-setup-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#47138 [PERFSCALE-2749]: Remove ROSA-HCP OCP 4.13 jobs
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa_hcp-4.13-nightly-x86.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-periodics.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-postsubmits.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#47221 Increases perfscale 120node timeout to 7h
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.13-nightly-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.14-nightly-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.15-nightly-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa-4.13-nightly-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa-4.14-nightly-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa-4.15-nightly-x86.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#45899 [IBMCloud] OCP-66528 install a cluster with minimal permission
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.14.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.15.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/ibmcloud/ipi/minimal-permission/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/ibmcloud/ipi/minimal-permission/cucushift-installer-rehearse-ibmcloud-ipi-minimal-permission-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/ibmcloud/ipi/minimal-permission/cucushift-installer-rehearse-ibmcloud-ipi-minimal-permission-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/ibmcloud/ipi/minimal-permission/deprovision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/ibmcloud/ipi/minimal-permission/deprovision/cucushift-installer-rehearse-ibmcloud-ipi-minimal-permission-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/ibmcloud/ipi/minimal-permission/deprovision/cucushift-installer-rehearse-ibmcloud-ipi-minimal-permission-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/ibmcloud/ipi/minimal-permission/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/ibmcloud/ipi/minimal-permission/provision/cucushift-installer-rehearse-ibmcloud-ipi-minimal-permission-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/ibmcloud/ipi/minimal-permission/provision/cucushift-installer-rehearse-ibmcloud-ipi-minimal-permission-provision-chain.yaml
  ci-operator/step-registry/gather/ibmcloud-resource/gather-ibmcloud-resource-commands.sh
  ci-operator/step-registry/ibmcloud/deprovision/iamservice/OWNERS
  ci-operator/step-registry/ibmcloud/deprovision/iamservice/minimal-permission/OWNERS
  ci-operator/step-registry/ibmcloud/deprovision/iamservice/minimal-permission/ibmcloud-deprovision-iamservice-minimal-permission-commands.sh
  ci-operator/step-registry/ibmcloud/deprovision/iamservice/minimal-permission/ibmcloud-deprovision-iamservice-minimal-permission-ref.metadata.json
  ci-operator/step-registry/ibmcloud/deprovision/iamservice/minimal-permission/ibmcloud-deprovision-iamservice-minimal-permission-ref.yaml
  ci-operator/step-registry/ibmcloud/provision/iamservice/OWNERS
  ci-operator/step-registry/ibmcloud/provision/iamservice/minimal-permission/OWNERS
  ci-operator/step-registry/ibmcloud/provision/iamservice/minimal-permission/ibmcloud-provision-iamservice-minimal-permission-commands.sh
  ci-operator/step-registry/ibmcloud/provision/iamservice/minimal-permission/ibmcloud-provision-iamservice-minimal-permission-ref.metadata.json
  ci-operator/step-registry/ibmcloud/provision/iamservice/minimal-permission/ibmcloud-provision-iamservice-minimal-permission-ref.yaml
  ci-operator/step-registry/ipi/deprovision/deprovision/ipi-deprovision-deprovision-commands.sh
  ci-operator/step-registry/ipi/install/install/ipi-install-install-commands.sh
Labels: lgtm, approved, rehearsals-ack

#47164 enable cvo conditional update when installing HO by default
  ci-operator/step-registry/cucushift/hypershift-extended/install-private/cucushift-hypershift-extended-install-private-commands.sh
Labels: lgtm, approved, rehearsals-ack

#47216 OCPBUGS-25400: Updated arm64 and multi release controller to upgrade from nightlies instead of PreviousMinor.
  core-services/release-controller/_releases/priv/release-ocp-4.14-arm64.json
  core-services/release-controller/_releases/priv/release-ocp-4.14-multi.json
  core-services/release-controller/_releases/priv/release-ocp-4.15-arm64.json
  core-services/release-controller/_releases/priv/release-ocp-4.15-multi.json
  core-services/release-controller/_releases/priv/release-ocp-4.16-arm64.json
  core-services/release-controller/_releases/priv/release-ocp-4.16-multi.json
  core-services/release-controller/_releases/release-ocp-4.14-arm64.json
  core-services/release-controller/_releases/release-ocp-4.14-multi.json
  core-services/release-controller/_releases/release-ocp-4.15-arm64.json
  core-services/release-controller/_releases/release-ocp-4.15-multi.json
  core-services/release-controller/_releases/release-ocp-4.16-arm64.json
  core-services/release-controller/_releases/release-ocp-4.16-multi.json
Labels: lgtm, approved, jira/valid-bug, rehearsals-ack, jira/valid-reference

#47224 MIXEDARCH-356: resolved the service-instance retrieval
  ci-operator/step-registry/upi/install/heterogeneous/powervs/upi-install-heterogeneous-powervs-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#47187 rename gcp workload-identity ci jobs to oidc on 4.14+
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-4.13-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly-4.14-upgrade-from-eus-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly-4.14-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly-4.14-upgrade-from-stable-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-stable-4.14-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly-4.15-upgrade-from-stable-4.10.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly-4.15-upgrade-from-stable-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-stable-4.15-upgrade-from-stable-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__arm64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly-4.16-upgrade-from-stable-4.15.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__multi-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#47103 Enabel infra and master addtional security groups
  ci-operator/step-registry/rosa/cluster/provision/rosa-cluster-provision-commands.sh
Labels: lgtm, approved, rehearsals-ack

#47208 Multi-zone job for Hypershift
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly.yaml
Labels: lgtm, approved, rehearsals-ack

#47182 call jobs for z-stream of 4.14+
  ci-operator/step-registry/api-job/api-job-commands.sh
Labels: lgtm, approved, rehearsals-ack

#47181 enable ROSA hcp 4.15
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-stable.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#47157 Fix junit errors for node scan
  ci-operator/step-registry/fips-check/node-scan/fips-check-node-scan-commands.sh
Labels: lgtm, approved, rehearsals-ack

#47059 OCPQE-18090: post-installation check for nested virtualization
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.14.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.15.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.16.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
  ci-operator/step-registry/cucushift/installer/check/gcp/nested-virtualization/OWNERS
  ci-operator/step-registry/cucushift/installer/check/gcp/nested-virtualization/cucushift-installer-check-gcp-nested-virtualization-commands.sh
  ci-operator/step-registry/cucushift/installer/check/gcp/nested-virtualization/cucushift-installer-check-gcp-nested-virtualization-ref.metadata.json
  ci-operator/step-registry/cucushift/installer/check/gcp/nested-virtualization/cucushift-installer-check-gcp-nested-virtualization-ref.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/customer-vpc/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/customer-vpc/deprovision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/customer-vpc/deprovision/cucushift-installer-rehearse-gcp-ipi-customer-vpc-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/customer-vpc/deprovision/cucushift-installer-rehearse-gcp-ipi-customer-vpc-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/customer-vpc/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/customer-vpc/provision/cucushift-installer-rehearse-gcp-ipi-customer-vpc-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/customer-vpc/provision/cucushift-installer-rehearse-gcp-ipi-customer-vpc-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/nested-virtualization/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/nested-virtualization/cucushift-installer-rehearse-gcp-ipi-nested-virtualization-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/nested-virtualization/cucushift-installer-rehearse-gcp-ipi-nested-virtualization-workflow.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#47189 Move TrustyAI to AWS
  ci-operator/config/trustyai-explainability/trustyai-explainability/trustyai-explainability-trustyai-explainability-main.yaml
  ci-operator/config/trustyai-explainability/trustyai-service-operator/trustyai-explainability-trustyai-service-operator-main.yaml
  ci-operator/jobs/trustyai-explainability/trustyai-explainability/trustyai-explainability-trustyai-explainability-main-postsubmits.yaml
  ci-operator/jobs/trustyai-explainability/trustyai-explainability/trustyai-explainability-trustyai-explainability-main-presubmits.yaml
  ci-operator/jobs/trustyai-explainability/trustyai-service-operator/trustyai-explainability-trustyai-service-operator-main-postsubmits.yaml
  ci-operator/jobs/trustyai-explainability/trustyai-service-operator/trustyai-explainability-trustyai-service-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#47231 Update quay dast test image with pip3 and all required packages
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__quay-dast.yaml
Labels: lgtm, approved, tide/merge-method-squash, rehearsals-ack

#47238 Adjust ROSA-HCP 4.14 job
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-stable.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#47247 add rbacs to allow ci-operator to get/list routes from the image registry namespace
  clusters/build-clusters/common/ci-operator/admin_ci-operator_rbac.yaml
Labels: lgtm, approved, rehearsals-ack

#47106 Interop - [3scale x ROSA] Fix Firewatch config, remove '3scale-apimanager-uninstall' step in scenario
  ci-operator/config/3scale-qe/3scale-deploy/3scale-qe-3scale-deploy-main__3scale-amp-ocp4.14-lp-rosa-classic.yaml
Labels: lgtm, approved, rehearsals-ack

#47249 add the external image registry route on the manifest pusher secrets on all clusters
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#47239 fix: Renamed default branch to main
  ci-operator/config/openshift-pipelines/performance/openshift-pipelines-performance-main.yaml
  ci-operator/jobs/openshift-pipelines/performance/openshift-pipelines-performance-main-periodics.yaml
  ci-operator/jobs/openshift-pipelines/performance/openshift-pipelines-performance-main-presubmits.yaml
  ci-operator/step-registry/openshift-pipelines/max-concurrency/openshift-pipelines-max-concurrency-commands.sh
  ci-operator/step-registry/openshift-pipelines/scaling-pipelines/openshift-pipelines-scaling-pipelines-commands.sh
Labels: lgtm, approved, rehearsals-ack

#47228 OCPQE-18091: Install cluster with valid disktype and disksize specified
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.14.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.15.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.16.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
  ci-operator/step-registry/cucushift/installer/check/gcp/disksize/OWNERS
  ci-operator/step-registry/cucushift/installer/check/gcp/disksize/cucushift-installer-check-gcp-disksize-commands.sh
  ci-operator/step-registry/cucushift/installer/check/gcp/disksize/cucushift-installer-check-gcp-disksize-ref.metadata.json
  ci-operator/step-registry/cucushift/installer/check/gcp/disksize/cucushift-installer-check-gcp-disksize-ref.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/disk/type-size/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/disk/type-size/cucushift-installer-rehearse-gcp-ipi-disk-type-size-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/disk/type-size/cucushift-installer-rehearse-gcp-ipi-disk-type-size-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/disk/type-size/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/disk/type-size/provision/cucushift-installer-rehearse-gcp-ipi-disk-type-size-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/disk/type-size/provision/cucushift-installer-rehearse-gcp-ipi-disk-type-size-provision-chain.yaml
  ci-operator/step-registry/ipi/conf/gcp/osdisk/disksize/OWNERS
  ci-operator/step-registry/ipi/conf/gcp/osdisk/disksize/ipi-conf-gcp-osdisk-disksize-commands.sh
  ci-operator/step-registry/ipi/conf/gcp/osdisk/disksize/ipi-conf-gcp-osdisk-disksize-ref.metadata.json
  ci-operator/step-registry/ipi/conf/gcp/osdisk/disksize/ipi-conf-gcp-osdisk-disksize-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#47256 Remove obsolete Stolostron cluster-proxy jobs
  ci-operator/config/stolostron/cluster-proxy/stolostron-cluster-proxy-release-2.5.yaml
  ci-operator/config/stolostron/cluster-proxy/stolostron-cluster-proxy-release-2.6.yaml
  ci-operator/jobs/stolostron/cluster-proxy/stolostron-cluster-proxy-release-2.5-postsubmits.yaml
  ci-operator/jobs/stolostron/cluster-proxy/stolostron-cluster-proxy-release-2.5-presubmits.yaml
  ci-operator/jobs/stolostron/cluster-proxy/stolostron-cluster-proxy-release-2.6-postsubmits.yaml
  ci-operator/jobs/stolostron/cluster-proxy/stolostron-cluster-proxy-release-2.6-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#47306 Remove obsolete Stolostron search-api jobs
  ci-operator/config/stolostron/search-api/stolostron-search-api-release-2.3.yaml
  ci-operator/config/stolostron/search-api/stolostron-search-api-release-2.4.yaml
  ci-operator/config/stolostron/search-api/stolostron-search-api-release-2.5.yaml
  ci-operator/config/stolostron/search-api/stolostron-search-api-release-2.6.yaml
  ci-operator/jobs/stolostron/search-api/stolostron-search-api-release-2.3-postsubmits.yaml
  ci-operator/jobs/stolostron/search-api/stolostron-search-api-release-2.3-presubmits.yaml
  ci-operator/jobs/stolostron/search-api/stolostron-search-api-release-2.4-postsubmits.yaml
  ci-operator/jobs/stolostron/search-api/stolostron-search-api-release-2.4-presubmits.yaml
  ci-operator/jobs/stolostron/search-api/stolostron-search-api-release-2.5-postsubmits.yaml
  ci-operator/jobs/stolostron/search-api/stolostron-search-api-release-2.5-presubmits.yaml
  ci-operator/jobs/stolostron/search-api/stolostron-search-api-release-2.6-postsubmits.yaml
  ci-operator/jobs/stolostron/search-api/stolostron-search-api-release-2.6-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#47310 Remove obsolete Stolostron search-ui jobs
  ci-operator/config/stolostron/search-ui/stolostron-search-ui-release-2.3.yaml
  ci-operator/config/stolostron/search-ui/stolostron-search-ui-release-2.4.yaml
  ci-operator/jobs/stolostron/search-ui/stolostron-search-ui-release-2.3-postsubmits.yaml
  ci-operator/jobs/stolostron/search-ui/stolostron-search-ui-release-2.3-presubmits.yaml
  ci-operator/jobs/stolostron/search-ui/stolostron-search-ui-release-2.4-postsubmits.yaml
  ci-operator/jobs/stolostron/search-ui/stolostron-search-ui-release-2.4-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#47305 Remove obsolete Stolostron search-aggregator jobs
  ci-operator/config/stolostron/search-aggregator/stolostron-search-aggregator-release-2.3.yaml
  ci-operator/config/stolostron/search-aggregator/stolostron-search-aggregator-release-2.4.yaml
  ci-operator/config/stolostron/search-aggregator/stolostron-search-aggregator-release-2.5.yaml
  ci-operator/config/stolostron/search-aggregator/stolostron-search-aggregator-release-2.6.yaml
  ci-operator/jobs/stolostron/search-aggregator/stolostron-search-aggregator-release-2.3-postsubmits.yaml
  ci-operator/jobs/stolostron/search-aggregator/stolostron-search-aggregator-release-2.3-presubmits.yaml
  ci-operator/jobs/stolostron/search-aggregator/stolostron-search-aggregator-release-2.4-postsubmits.yaml
  ci-operator/jobs/stolostron/search-aggregator/stolostron-search-aggregator-release-2.4-presubmits.yaml
  ci-operator/jobs/stolostron/search-aggregator/stolostron-search-aggregator-release-2.5-postsubmits.yaml
  ci-operator/jobs/stolostron/search-aggregator/stolostron-search-aggregator-release-2.5-presubmits.yaml
  ci-operator/jobs/stolostron/search-aggregator/stolostron-search-aggregator-release-2.6-postsubmits.yaml
  ci-operator/jobs/stolostron/search-aggregator/stolostron-search-aggregator-release-2.6-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#47314 DPTP-3809: Add fast-forwarding for 4.17
  ci-operator/jobs/infra-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#47062 NO-JIRA: cluster-api/cluster-capi-operator: add openstack/gcp e2e
  ci-operator/config/openshift/cluster-api/openshift-cluster-api-master.yaml
  ci-operator/config/openshift/cluster-api/openshift-cluster-api-release-4.16.yaml
  ci-operator/config/openshift/cluster-capi-operator/openshift-cluster-capi-operator-main.yaml
  ci-operator/config/openshift/cluster-capi-operator/openshift-cluster-capi-operator-release-4.16.yaml
  ci-operator/jobs/openshift/cluster-api/openshift-cluster-api-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api/openshift-cluster-api-release-4.16-presubmits.yaml
  ci-operator/jobs/openshift/cluster-capi-operator/openshift-cluster-capi-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/cluster-capi-operator/openshift-cluster-capi-operator-release-4.16-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#47234 update base image in CI config to reflect change from rhel-8 to rhel-9
  ci-operator/config/redhat-cne/cloud-event-proxy/redhat-cne-cloud-event-proxy-main.yaml
  ci-operator/config/redhat-cne/cloud-event-proxy/redhat-cne-cloud-event-proxy-release-4.15.yaml
  ci-operator/config/redhat-cne/cloud-event-proxy/redhat-cne-cloud-event-proxy-release-4.16.yaml
Labels: lgtm, approved, rehearsals-ack

#47255 Remove obsolete Stolostron cluster-lifecycle-e2e jobs
  ci-operator/config/stolostron/cluster-lifecycle-e2e/stolostron-cluster-lifecycle-e2e-release-2.2.yaml
  ci-operator/config/stolostron/cluster-lifecycle-e2e/stolostron-cluster-lifecycle-e2e-release-2.3.yaml
  ci-operator/config/stolostron/cluster-lifecycle-e2e/stolostron-cluster-lifecycle-e2e-release-2.4.yaml
  ci-operator/config/stolostron/cluster-lifecycle-e2e/stolostron-cluster-lifecycle-e2e-release-2.5.yaml
  ci-operator/config/stolostron/cluster-lifecycle-e2e/stolostron-cluster-lifecycle-e2e-release-2.6.yaml
  ci-operator/jobs/stolostron/cluster-lifecycle-e2e/stolostron-cluster-lifecycle-e2e-release-2.2-postsubmits.yaml
  ci-operator/jobs/stolostron/cluster-lifecycle-e2e/stolostron-cluster-lifecycle-e2e-release-2.2-presubmits.yaml
  ci-operator/jobs/stolostron/cluster-lifecycle-e2e/stolostron-cluster-lifecycle-e2e-release-2.3-postsubmits.yaml
  ci-operator/jobs/stolostron/cluster-lifecycle-e2e/stolostron-cluster-lifecycle-e2e-release-2.3-presubmits.yaml
  ci-operator/jobs/stolostron/cluster-lifecycle-e2e/stolostron-cluster-lifecycle-e2e-release-2.4-postsubmits.yaml
  ci-operator/jobs/stolostron/cluster-lifecycle-e2e/stolostron-cluster-lifecycle-e2e-release-2.4-presubmits.yaml
  ci-operator/jobs/stolostron/cluster-lifecycle-e2e/stolostron-cluster-lifecycle-e2e-release-2.5-postsubmits.yaml
  ci-operator/jobs/stolostron/cluster-lifecycle-e2e/stolostron-cluster-lifecycle-e2e-release-2.5-presubmits.yaml
  ci-operator/jobs/stolostron/cluster-lifecycle-e2e/stolostron-cluster-lifecycle-e2e-release-2.6-postsubmits.yaml
  ci-operator/jobs/stolostron/cluster-lifecycle-e2e/stolostron-cluster-lifecycle-e2e-release-2.6-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#47287 Remove obsolete Stolostron multicloud-operators-application jobs
  ci-operator/config/stolostron/multicloud-operators-application/stolostron-multicloud-operators-application-release-2.3.yaml
  ci-operator/config/stolostron/multicloud-operators-application/stolostron-multicloud-operators-application-release-2.4.yaml
  ci-operator/config/stolostron/multicloud-operators-application/stolostron-multicloud-operators-application-release-2.5.yaml
  ci-operator/config/stolostron/multicloud-operators-application/stolostron-multicloud-operators-application-release-2.6.yaml
  ci-operator/jobs/stolostron/multicloud-operators-application/stolostron-multicloud-operators-application-release-2.3-postsubmits.yaml
  ci-operator/jobs/stolostron/multicloud-operators-application/stolostron-multicloud-operators-application-release-2.3-presubmits.yaml
  ci-operator/jobs/stolostron/multicloud-operators-application/stolostron-multicloud-operators-application-release-2.4-postsubmits.yaml
  ci-operator/jobs/stolostron/multicloud-operators-application/stolostron-multicloud-operators-application-release-2.4-presubmits.yaml
  ci-operator/jobs/stolostron/multicloud-operators-application/stolostron-multicloud-operators-application-release-2.5-postsubmits.yaml
  ci-operator/jobs/stolostron/multicloud-operators-application/stolostron-multicloud-operators-application-release-2.5-presubmits.yaml
  ci-operator/jobs/stolostron/multicloud-operators-application/stolostron-multicloud-operators-application-release-2.6-postsubmits.yaml
  ci-operator/jobs/stolostron/multicloud-operators-application/stolostron-multicloud-operators-application-release-2.6-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#47290 Remove obsolete Stolostron multicloud-operators-placementrule jobs
  ci-operator/config/stolostron/multicloud-operators-placementrule/stolostron-multicloud-operators-placementrule-release-2.3.yaml
  ci-operator/config/stolostron/multicloud-operators-placementrule/stolostron-multicloud-operators-placementrule-release-2.4.yaml
  ci-operator/jobs/stolostron/multicloud-operators-placementrule/stolostron-multicloud-operators-placementrule-release-2.3-postsubmits.yaml
  ci-operator/jobs/stolostron/multicloud-operators-placementrule/stolostron-multicloud-operators-placementrule-release-2.3-presubmits.yaml
  ci-operator/jobs/stolostron/multicloud-operators-placementrule/stolostron-multicloud-operators-placementrule-release-2.4-postsubmits.yaml
  ci-operator/jobs/stolostron/multicloud-operators-placementrule/stolostron-multicloud-operators-placementrule-release-2.4-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#47292 Remove obsolete Stolostron multicloud-operators-subscription-release …
  ci-operator/config/stolostron/multicloud-operators-subscription-release/stolostron-multicloud-operators-subscription-release-release-2.3.yaml
  ci-operator/config/stolostron/multicloud-operators-subscription-release/stolostron-multicloud-operators-subscription-release-release-2.4.yaml
  ci-operator/jobs/stolostron/multicloud-operators-subscription-release/stolostron-multicloud-operators-subscription-release-release-2.3-postsubmits.yaml
  ci-operator/jobs/stolostron/multicloud-operators-subscription-release/stolostron-multicloud-operators-subscription-release-release-2.3-presubmits.yaml
  ci-operator/jobs/stolostron/multicloud-operators-subscription-release/stolostron-multicloud-operators-subscription-release-release-2.4-postsubmits.yaml
  ci-operator/jobs/stolostron/multicloud-operators-subscription-release/stolostron-multicloud-operators-subscription-release-release-2.4-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#47246 Remove ci/prow/images build it's not required for openshift-docs
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-enterprise-4.11.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-main.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-prow-test.yaml
  ci-operator/jobs/openshift/openshift-docs/openshift-openshift-docs-enterprise-4.11-presubmits.yaml
  ci-operator/jobs/openshift/openshift-docs/openshift-openshift-docs-main-presubmits.yaml
  ci-operator/jobs/openshift/openshift-docs/openshift-openshift-docs-prow-test-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#47257 Remove obsolete Stolostron cert-policy-controller jobs
  ci-operator/config/stolostron/cert-policy-controller/stolostron-cert-policy-controller-release-2.5.yaml
  ci-operator/config/stolostron/cert-policy-controller/stolostron-cert-policy-controller-release-2.6.yaml
  ci-operator/jobs/stolostron/cert-policy-controller/stolostron-cert-policy-controller-release-2.5-postsubmits.yaml
  ci-operator/jobs/stolostron/cert-policy-controller/stolostron-cert-policy-controller-release-2.5-presubmits.yaml
  ci-operator/jobs/stolostron/cert-policy-controller/stolostron-cert-policy-controller-release-2.6-postsubmits.yaml
  ci-operator/jobs/stolostron/cert-policy-controller/stolostron-cert-policy-controller-release-2.6-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#47219 Update ibm-roks-toolkit-base.yaml
  clusters/app.ci/supplemental-ci-images/ibm-roks-toolkit-base/ibm-roks-toolkit-base.yaml
Labels: lgtm, approved, rehearsals-ack

#47263 Remove obsolete Stolostron config-policy-controller jobs
  ci-operator/config/stolostron/config-policy-controller/stolostron-config-policy-controller-release-2.5.yaml
  ci-operator/config/stolostron/config-policy-controller/stolostron-config-policy-controller-release-2.6.yaml
  ci-operator/jobs/stolostron/config-policy-controller/stolostron-config-policy-controller-release-2.5-postsubmits.yaml
  ci-operator/jobs/stolostron/config-policy-controller/stolostron-config-policy-controller-release-2.5-presubmits.yaml
  ci-operator/jobs/stolostron/config-policy-controller/stolostron-config-policy-controller-release-2.6-postsubmits.yaml
  ci-operator/jobs/stolostron/config-policy-controller/stolostron-config-policy-controller-release-2.6-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#47270 Remove obsolete Stolostron governance-policy-addon-controller jobs
  ci-operator/config/stolostron/governance-policy-addon-controller/stolostron-governance-policy-addon-controller-release-2.5.yaml
  ci-operator/config/stolostron/governance-policy-addon-controller/stolostron-governance-policy-addon-controller-release-2.6.yaml
  ci-operator/jobs/stolostron/governance-policy-addon-controller/stolostron-governance-policy-addon-controller-release-2.5-postsubmits.yaml
  ci-operator/jobs/stolostron/governance-policy-addon-controller/stolostron-governance-policy-addon-controller-release-2.5-presubmits.yaml
  ci-operator/jobs/stolostron/governance-policy-addon-controller/stolostron-governance-policy-addon-controller-release-2.6-postsubmits.yaml
  ci-operator/jobs/stolostron/governance-policy-addon-controller/stolostron-governance-policy-addon-controller-release-2.6-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#47272 Remove obsolete Stolostron governance-policy-propagator jobs
  ci-operator/config/stolostron/governance-policy-propagator/stolostron-governance-policy-propagator-release-2.5.yaml
  ci-operator/config/stolostron/governance-policy-propagator/stolostron-governance-policy-propagator-release-2.6.yaml
  ci-operator/jobs/stolostron/governance-policy-propagator/stolostron-governance-policy-propagator-release-2.5-postsubmits.yaml
  ci-operator/jobs/stolostron/governance-policy-propagator/stolostron-governance-policy-propagator-release-2.5-presubmits.yaml
  ci-operator/jobs/stolostron/governance-policy-propagator/stolostron-governance-policy-propagator-release-2.6-postsubmits.yaml
  ci-operator/jobs/stolostron/governance-policy-propagator/stolostron-governance-policy-propagator-release-2.6-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#47276 Remove obsolete Stolostron iam-policy-controller jobs
  ci-operator/config/stolostron/iam-policy-controller/stolostron-iam-policy-controller-release-2.5.yaml
  ci-operator/config/stolostron/iam-policy-controller/stolostron-iam-policy-controller-release-2.6.yaml
  ci-operator/jobs/stolostron/iam-policy-controller/stolostron-iam-policy-controller-release-2.5-postsubmits.yaml
  ci-operator/jobs/stolostron/iam-policy-controller/stolostron-iam-policy-controller-release-2.5-presubmits.yaml
  ci-operator/jobs/stolostron/iam-policy-controller/stolostron-iam-policy-controller-release-2.6-postsubmits.yaml
  ci-operator/jobs/stolostron/iam-policy-controller/stolostron-iam-policy-controller-release-2.6-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#47317 Add `cluster-config-api-changed` label to `additional_labels`
  core-services/prow/02_config/_plugins.yaml
Labels: lgtm, approved, rehearsals-ack

#47258 Remove obsolete Stolostron cluster-backup-operator jobs
  ci-operator/config/stolostron/cluster-backup-operator/stolostron-cluster-backup-operator-release-2.4.yaml
  ci-operator/config/stolostron/cluster-backup-operator/stolostron-cluster-backup-operator-release-2.5.yaml
  ci-operator/config/stolostron/cluster-backup-operator/stolostron-cluster-backup-operator-release-2.6.yaml
  ci-operator/jobs/stolostron/cluster-backup-operator/stolostron-cluster-backup-operator-release-2.4-postsubmits.yaml
  ci-operator/jobs/stolostron/cluster-backup-operator/stolostron-cluster-backup-operator-release-2.4-presubmits.yaml
  ci-operator/jobs/stolostron/cluster-backup-operator/stolostron-cluster-backup-operator-release-2.5-postsubmits.yaml
  ci-operator/jobs/stolostron/cluster-backup-operator/stolostron-cluster-backup-operator-release-2.5-presubmits.yaml
  ci-operator/jobs/stolostron/cluster-backup-operator/stolostron-cluster-backup-operator-release-2.6-postsubmits.yaml
  ci-operator/jobs/stolostron/cluster-backup-operator/stolostron-cluster-backup-operator-release-2.6-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#47151 PerfScale 416 jobs
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.16-nightly-x86.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-periodics.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-postsubmits.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#47318 Removed legacy jobs for deprecated grc and application charts
  core-services/prow/02_config/stolostron/application-chart/OWNERS
  core-services/prow/02_config/stolostron/application-chart/_pluginconfig.yaml
  core-services/prow/02_config/stolostron/grc-chart/OWNERS
  core-services/prow/02_config/stolostron/grc-chart/_pluginconfig.yaml
  core-services/prow/02_config/stolostron/grc-chart/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#47322 fix: update presubmit job to always run e2e tests
  ci-operator/jobs/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-v1alpha1-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#47324 Excluding `rhel-coreos-next[-extensions]` from OKD promotion
  core-services/release-controller/_releases/release-ocp-4.16-ci.json
Labels: lgtm, approved, rehearsals-ack

#47144 PowerVS: Fix ibmcloud resource service-instances
  ci-operator/step-registry/ipi/install/powervs/install/ipi-install-powervs-install-commands.sh
Labels: lgtm, approved, rehearsals-ack

#47313 Remove obsolete Stolostron volsync-addon-controller jobs
  ci-operator/config/stolostron/volsync-addon-controller/stolostron-volsync-addon-controller-release-2.5.yaml
  ci-operator/jobs/stolostron/volsync-addon-controller/stolostron-volsync-addon-controller-release-2.5-postsubmits.yaml
  ci-operator/jobs/stolostron/volsync-addon-controller/stolostron-volsync-addon-controller-release-2.5-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#47200 openstack: Move monitoring to new OpenStack tenant
  ci-operator/step-registry/shiftstack/monitor/shiftstack-monitor-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#44552 Add security scanning job AWS EBS driver & csi-operator repositories
  ci-operator/config/openshift/aws-ebs-csi-driver/openshift-aws-ebs-csi-driver-master.yaml
  ci-operator/config/openshift/aws-ebs-csi-driver/openshift-aws-ebs-csi-driver-release-4.16.yaml
  ci-operator/config/openshift/csi-operator/openshift-csi-operator-master.yaml
  ci-operator/config/openshift/csi-operator/openshift-csi-operator-release-4.16.yaml
  ci-operator/jobs/openshift/aws-ebs-csi-driver/openshift-aws-ebs-csi-driver-master-presubmits.yaml
  ci-operator/jobs/openshift/aws-ebs-csi-driver/openshift-aws-ebs-csi-driver-release-4.16-presubmits.yaml
  ci-operator/jobs/openshift/csi-operator/openshift-csi-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/csi-operator/openshift-csi-operator-release-4.16-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#47155 Move Cinder and dataplane prow jobs over from 4.12 to 4.14 Hive cluster
  ci-operator/config/openstack-k8s-operators/cinder-operator/openstack-k8s-operators-cinder-operator-main.yaml
  ci-operator/config/openstack-k8s-operators/dataplane-operator/openstack-k8s-operators-dataplane-operator-main.yaml
Labels: lgtm, approved, rehearsals-ack

#47326 stackrox: fix step name var
  ci-operator/step-registry/stackrox/stackrox/begin/stackrox-stackrox-begin-commands.sh
  ci-operator/step-registry/stackrox/stackrox/end/stackrox-stackrox-end-commands.sh
Labels: lgtm, approved, rehearsals-ack

#47175 Update 4.15 rollback job
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.15.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  core-services/release-controller/_releases/priv/release-ocp-4.15.json
  core-services/release-controller/_releases/release-ocp-4.15.json
Labels: lgtm, approved, rehearsals-ack

#47250 Add HOME ENV in build Quay DAST image used by rapidast
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__quay-dast.yaml
Labels: lgtm, approved, rehearsals-ack

#47260 Remove obsolete Stolostron cluster-proxy-addon jobs
  ci-operator/config/stolostron/cluster-proxy-addon/stolostron-cluster-proxy-addon-release-2.5.yaml
  ci-operator/jobs/stolostron/cluster-proxy-addon/stolostron-cluster-proxy-addon-release-2.5-postsubmits.yaml
  ci-operator/jobs/stolostron/cluster-proxy-addon/stolostron-cluster-proxy-addon-release-2.5-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#47279 Remove obsolete Stolostron klusterlet-addon-operator jobs
  ci-operator/config/stolostron/klusterlet-addon-operator/stolostron-klusterlet-addon-operator-release-2.3.yaml
  ci-operator/config/stolostron/klusterlet-addon-operator/stolostron-klusterlet-addon-operator-release-2.4.yaml
  ci-operator/config/stolostron/klusterlet-addon-operator/stolostron-klusterlet-addon-operator-release-2.5.yaml
  ci-operator/jobs/stolostron/klusterlet-addon-operator/stolostron-klusterlet-addon-operator-release-2.3-postsubmits.yaml
  ci-operator/jobs/stolostron/klusterlet-addon-operator/stolostron-klusterlet-addon-operator-release-2.3-presubmits.yaml
  ci-operator/jobs/stolostron/klusterlet-addon-operator/stolostron-klusterlet-addon-operator-release-2.4-postsubmits.yaml
  ci-operator/jobs/stolostron/klusterlet-addon-operator/stolostron-klusterlet-addon-operator-release-2.4-presubmits.yaml
  ci-operator/jobs/stolostron/klusterlet-addon-operator/stolostron-klusterlet-addon-operator-release-2.5-postsubmits.yaml
  ci-operator/jobs/stolostron/klusterlet-addon-operator/stolostron-klusterlet-addon-operator-release-2.5-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#47186 OCPQE-18510: Optimize the test filter for cucushift on different arch
  ci-operator/step-registry/cucushift/e2e/cucushift-e2e-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#47090 Update readme file for openshift-tests-private
  ci-operator/config/openshift/openshift-tests-private/README.md
Labels: lgtm, approved, rehearsals-ack

#47338 Change HOME ENV to give write permissions to ZAP
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__quay-dast.yaml
Labels: lgtm, approved, tide/merge-method-squash, rehearsals-ack

#47244 fix aws sno control plane vm type
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__multi-nightly.yaml
Labels: lgtm, approved, rehearsals-ack

#47331 trigger z-stream test jobs from a JSON file
  ci-operator/step-registry/api-job/api-job-commands.sh
Labels: lgtm, approved, rehearsals-ack

#47334 fix provision shard filters to make it available for both int, stage …
  ci-operator/step-registry/osd-ccs/fleet-manager/provision-shards/osd-ccs-fleet-manager-provision-shards-commands.sh
Labels: lgtm, approved, rehearsals-ack

#47017 OCPQE-18525: automate case OCP-27422 and OCP-33370
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.14.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.15.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.16.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
  ci-operator/step-registry/azure/provision/bastionhost/azure-provision-bastionhost-commands.sh
  ci-operator/step-registry/cucushift/installer/check/reboot-nodes/OWNERS
  ci-operator/step-registry/cucushift/installer/check/reboot-nodes/cucushift-installer-check-reboot-nodes-commands.sh
  ci-operator/step-registry/cucushift/installer/check/reboot-nodes/cucushift-installer-check-reboot-nodes-ref.metadata.json
  ci-operator/step-registry/cucushift/installer/check/reboot-nodes/cucushift-installer-check-reboot-nodes-ref.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/mag/ipi/fullyprivate/provision/cucushift-installer-rehearse-azure-mag-ipi-fullyprivate-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/upi/proxy/provision/cucushift-installer-rehearse-azure-upi-proxy-provision-chain.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#43723 HOSTEDCP-999: Add periodic Hypershift CI test
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-periodics.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#47321 OKO: Create a unique tag for each build
  ci-operator/step-registry/openstack-k8s-operators/build/openstack-k8s-operators-build-commands.sh
  ci-operator/step-registry/openstack-k8s-operators/deploy/openstack-k8s-operators-deploy-commands.sh
  ci-operator/step-registry/openstack-k8s-operators/kuttl/openstack-k8s-operators-kuttl-commands.sh
Labels: lgtm, approved, rehearsals-ack

#47348 Restore Stolostron policy jobs for 2.6
  ci-operator/config/stolostron/cert-policy-controller/stolostron-cert-policy-controller-release-2.6.yaml
  ci-operator/config/stolostron/config-policy-controller/stolostron-config-policy-controller-release-2.6.yaml
  ci-operator/config/stolostron/governance-policy-addon-controller/stolostron-governance-policy-addon-controller-release-2.6.yaml
  ci-operator/config/stolostron/governance-policy-framework/stolostron-governance-policy-framework-release-2.6.yaml
  ci-operator/config/stolostron/governance-policy-propagator/stolostron-governance-policy-propagator-release-2.6.yaml
  ci-operator/config/stolostron/iam-policy-controller/stolostron-iam-policy-controller-release-2.6.yaml
  ci-operator/jobs/stolostron/cert-policy-controller/stolostron-cert-policy-controller-release-2.6-postsubmits.yaml
  ci-operator/jobs/stolostron/cert-policy-controller/stolostron-cert-policy-controller-release-2.6-presubmits.yaml
  ci-operator/jobs/stolostron/config-policy-controller/stolostron-config-policy-controller-release-2.6-postsubmits.yaml
  ci-operator/jobs/stolostron/config-policy-controller/stolostron-config-policy-controller-release-2.6-presubmits.yaml
  ci-operator/jobs/stolostron/governance-policy-addon-controller/stolostron-governance-policy-addon-controller-release-2.6-postsubmits.yaml
  ci-operator/jobs/stolostron/governance-policy-addon-controller/stolostron-governance-policy-addon-controller-release-2.6-presubmits.yaml
  ci-operator/jobs/stolostron/governance-policy-framework/stolostron-governance-policy-framework-release-2.6-postsubmits.yaml
  ci-operator/jobs/stolostron/governance-policy-framework/stolostron-governance-policy-framework-release-2.6-presubmits.yaml
  ci-operator/jobs/stolostron/governance-policy-propagator/stolostron-governance-policy-propagator-release-2.6-postsubmits.yaml
  ci-operator/jobs/stolostron/governance-policy-propagator/stolostron-governance-policy-propagator-release-2.6-presubmits.yaml
  ci-operator/jobs/stolostron/iam-policy-controller/stolostron-iam-policy-controller-release-2.6-postsubmits.yaml
  ci-operator/jobs/stolostron/iam-policy-controller/stolostron-iam-policy-controller-release-2.6-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#47356 Restore Stolostron search-api jobs for 2.6
  ci-operator/config/stolostron/search-api/stolostron-search-api-release-2.6.yaml
  ci-operator/jobs/stolostron/search-api/stolostron-search-api-release-2.6-postsubmits.yaml
  ci-operator/jobs/stolostron/search-api/stolostron-search-api-release-2.6-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#47363 bump `golangci-lint` to allow go 1.21
  ci-operator/config/openshift/ci-chat-bot/openshift-ci-chat-bot-master.yaml
Labels: lgtm, approved, rehearsals-ack

#47336 [CVP-3822]: Update the image from ec to rc tag
  clusters/hive/pools/cvp/cvp-ocp-4-15-amd64-aws-eu-west-1_clusterpool.yaml
  clusters/hive/pools/ocp-release-4.15.0-rc.0-x86-64-for-4.15.0-0-to-4.16.0-0_clusterimageset.yaml
Labels: lgtm, approved, rehearsals-ack

#47357 Update configuration for openshift/etcd for 4.15 and 4.16
  core-services/prow/02_config/openshift/etcd/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#47364 Skip agent gather for 4.15 or greater version
  ci-operator/step-registry/cucushift/agent/gather/cucushift-agent-gather-commands.sh
Labels: lgtm, approved, rehearsals-ack

#47366 [ci-search] Expanding the jira search versions
  clusters/build-clusters/01_cluster/ci-search/deploy.yaml
Labels: lgtm, approved, rehearsals-ack

#47352 Restore Stolostron cluster-proxy jobs for 2.6
  ci-operator/config/stolostron/cluster-proxy/stolostron-cluster-proxy-release-2.6.yaml
  ci-operator/jobs/stolostron/cluster-proxy/stolostron-cluster-proxy-release-2.6-postsubmits.yaml
  ci-operator/jobs/stolostron/cluster-proxy/stolostron-cluster-proxy-release-2.6-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#46523 [AMQ Streams] Update AMQ Streams version to 2.6.0 after release
  ci-operator/config/amq-streams-qe/strimzi-kafka-operator/amq-streams-qe-strimzi-kafka-operator-main__amq-streams-ocp4.14-lp-interop.yaml
  ci-operator/config/amq-streams-qe/strimzi-kafka-operator/amq-streams-qe-strimzi-kafka-operator-main__amq-streams-ocp4.14-lp-rosa-classic.yaml
  ci-operator/config/amq-streams-qe/strimzi-kafka-operator/amq-streams-qe-strimzi-kafka-operator-main__amq-streams-ocp4.15-lp-interop.yaml
  ci-operator/jobs/amq-streams-qe/strimzi-kafka-operator/amq-streams-qe-strimzi-kafka-operator-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#47307 Remove obsolete Stolostron search-collector jobs
  ci-operator/config/stolostron/search-collector/stolostron-search-collector-release-2.3.yaml
  ci-operator/config/stolostron/search-collector/stolostron-search-collector-release-2.4.yaml
  ci-operator/config/stolostron/search-collector/stolostron-search-collector-release-2.5.yaml
  ci-operator/jobs/stolostron/search-collector/stolostron-search-collector-release-2.3-postsubmits.yaml
  ci-operator/jobs/stolostron/search-collector/stolostron-search-collector-release-2.3-presubmits.yaml
  ci-operator/jobs/stolostron/search-collector/stolostron-search-collector-release-2.4-postsubmits.yaml
  ci-operator/jobs/stolostron/search-collector/stolostron-search-collector-release-2.4-presubmits.yaml
  ci-operator/jobs/stolostron/search-collector/stolostron-search-collector-release-2.5-postsubmits.yaml
  ci-operator/jobs/stolostron/search-collector/stolostron-search-collector-release-2.5-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#47308 Remove obsolete Stolostron search-e2e-test jobs
  ci-operator/config/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.3.yaml
  ci-operator/config/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.4.yaml
  ci-operator/config/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.5.yaml
  ci-operator/jobs/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.3-postsubmits.yaml
  ci-operator/jobs/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.3-presubmits.yaml
  ci-operator/jobs/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.4-postsubmits.yaml
  ci-operator/jobs/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.4-presubmits.yaml
  ci-operator/jobs/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.5-postsubmits.yaml
  ci-operator/jobs/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.5-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#47355 Restore Stolostron search-aggregator jobs for 2.6
  ci-operator/config/stolostron/search-aggregator/stolostron-search-aggregator-release-2.6.yaml
  ci-operator/jobs/stolostron/search-aggregator/stolostron-search-aggregator-release-2.6-postsubmits.yaml
  ci-operator/jobs/stolostron/search-aggregator/stolostron-search-aggregator-release-2.6-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#46541 WINC-1158: Fast forward to community-4.16 branch
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-master.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.15.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.16.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#47330 Resolve 4.13 ARM test failures
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.13-nightly-arm.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-periodics.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-postsubmits.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#47360 use bucket_alias from `test-platform-results` to `origin-ci-test` in `spyglass`
  core-services/prow/02_config/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#47266 Remove obsolete Stolostron multiclusterhub-operator jobs
  ci-operator/config/stolostron/multiclusterhub-operator/stolostron-multiclusterhub-operator-release-2.3.yaml
  ci-operator/config/stolostron/multiclusterhub-operator/stolostron-multiclusterhub-operator-release-2.4.yaml
  ci-operator/config/stolostron/multiclusterhub-operator/stolostron-multiclusterhub-operator-release-2.5.yaml
  ci-operator/jobs/stolostron/multiclusterhub-operator/stolostron-multiclusterhub-operator-release-2.3-postsubmits.yaml
  ci-operator/jobs/stolostron/multiclusterhub-operator/stolostron-multiclusterhub-operator-release-2.3-presubmits.yaml
  ci-operator/jobs/stolostron/multiclusterhub-operator/stolostron-multiclusterhub-operator-release-2.4-postsubmits.yaml
  ci-operator/jobs/stolostron/multiclusterhub-operator/stolostron-multiclusterhub-operator-release-2.4-presubmits.yaml
  ci-operator/jobs/stolostron/multiclusterhub-operator/stolostron-multiclusterhub-operator-release-2.5-postsubmits.yaml
  ci-operator/jobs/stolostron/multiclusterhub-operator/stolostron-multiclusterhub-operator-release-2.5-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#47268 Remove obsolete Stolostron discovery jobs
  ci-operator/config/stolostron/discovery/stolostron-discovery-release-2.3.yaml
  ci-operator/config/stolostron/discovery/stolostron-discovery-release-2.4.yaml
  ci-operator/jobs/stolostron/discovery/stolostron-discovery-release-2.3-postsubmits.yaml
  ci-operator/jobs/stolostron/discovery/stolostron-discovery-release-2.3-presubmits.yaml
  ci-operator/jobs/stolostron/discovery/stolostron-discovery-release-2.4-postsubmits.yaml
  ci-operator/jobs/stolostron/discovery/stolostron-discovery-release-2.4-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#47277 Remove obsolete Stolostron insights-client jobs
  ci-operator/config/stolostron/insights-client/stolostron-insights-client-release-2.3.yaml
  ci-operator/config/stolostron/insights-client/stolostron-insights-client-release-2.4.yaml
  ci-operator/config/stolostron/insights-client/stolostron-insights-client-release-2.5.yaml
  ci-operator/jobs/stolostron/insights-client/stolostron-insights-client-release-2.3-postsubmits.yaml
  ci-operator/jobs/stolostron/insights-client/stolostron-insights-client-release-2.3-presubmits.yaml
  ci-operator/jobs/stolostron/insights-client/stolostron-insights-client-release-2.4-postsubmits.yaml
  ci-operator/jobs/stolostron/insights-client/stolostron-insights-client-release-2.4-presubmits.yaml
  ci-operator/jobs/stolostron/insights-client/stolostron-insights-client-release-2.5-postsubmits.yaml
  ci-operator/jobs/stolostron/insights-client/stolostron-insights-client-release-2.5-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#47278 Remove obsolete Stolostron insights-metrics jobs
  ci-operator/config/stolostron/insights-metrics/stolostron-insights-metrics-release-2.3.yaml
  ci-operator/config/stolostron/insights-metrics/stolostron-insights-metrics-release-2.4.yaml
  ci-operator/config/stolostron/insights-metrics/stolostron-insights-metrics-release-2.5.yaml
  ci-operator/jobs/stolostron/insights-metrics/stolostron-insights-metrics-release-2.3-postsubmits.yaml
  ci-operator/jobs/stolostron/insights-metrics/stolostron-insights-metrics-release-2.3-presubmits.yaml
  ci-operator/jobs/stolostron/insights-metrics/stolostron-insights-metrics-release-2.4-postsubmits.yaml
  ci-operator/jobs/stolostron/insights-metrics/stolostron-insights-metrics-release-2.4-presubmits.yaml
  ci-operator/jobs/stolostron/insights-metrics/stolostron-insights-metrics-release-2.5-postsubmits.yaml
  ci-operator/jobs/stolostron/insights-metrics/stolostron-insights-metrics-release-2.5-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#47371 [release-controller] Correcting the stream name for `multi` release-controller
  core-services/release-controller/_releases/priv/release-ocp-4.14-multi.json
  core-services/release-controller/_releases/priv/release-ocp-4.15-multi.json
  core-services/release-controller/_releases/priv/release-ocp-4.16-multi.json
  core-services/release-controller/_releases/release-ocp-4.14-multi.json
  core-services/release-controller/_releases/release-ocp-4.15-multi.json
  core-services/release-controller/_releases/release-ocp-4.16-multi.json
Labels: lgtm, approved, rehearsals-ack

#47372 OpenStack: rename az0 to nova
  ci-operator/step-registry/openstack/conf/resourcenames/openstack-conf-resourcenames-commands.sh
Labels: lgtm, approved, rehearsals-ack

#47344 Revert "Use RHEL9 as base image for cnf-tests"
  ci-operator/config/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-master.yaml
Labels: lgtm, approved, rehearsals-ack

#47230 Renamed step, limited 'PAO must gather' to 4.13
  ci-operator/step-registry/telco5g/cnf/telco5g-cnf-workflow.yaml
  ci-operator/step-registry/telco5g/log-gather/OWNERS
  ci-operator/step-registry/telco5g/log-gather/telco5g-log-gather-commands.sh
  ci-operator/step-registry/telco5g/log-gather/telco5g-log-gather-ref.metadata.json
  ci-operator/step-registry/telco5g/log-gather/telco5g-log-gather-ref.yaml
  ci-operator/step-registry/telco5g/origin/telco5g-origin-workflow.yaml
  ci-operator/step-registry/telco5g/sno-cnf/telco5g-sno-cnf-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#46796 telco: Move GCP jobs to run on AWS in openshift-kni
  ci-operator/config/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-master.yaml
  ci-operator/config/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.10.yaml
  ci-operator/config/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.11.yaml
  ci-operator/config/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.12.yaml
  ci-operator/config/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.13.yaml
  ci-operator/config/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.14.yaml
  ci-operator/config/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.15.yaml
  ci-operator/jobs/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-master-presubmits.yaml
  ci-operator/jobs/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.10-presubmits.yaml
  ci-operator/jobs/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.11-presubmits.yaml
  ci-operator/jobs/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.13-presubmits.yaml
  ci-operator/jobs/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.14-presubmits.yaml
  ci-operator/jobs/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.15-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#46731 telco: Remove GCP jobs for PAO repository
  ci-operator/config/openshift-kni/performance-addon-operators/openshift-kni-performance-addon-operators-release-4.10.yaml
  ci-operator/config/openshift-kni/performance-addon-operators/openshift-kni-performance-addon-operators-release-4.11.yaml
  ci-operator/config/openshift-kni/performance-addon-operators/openshift-kni-performance-addon-operators-release-4.4.yaml
  ci-operator/config/openshift-kni/performance-addon-operators/openshift-kni-performance-addon-operators-release-4.5.yaml
  ci-operator/config/openshift-kni/performance-addon-operators/openshift-kni-performance-addon-operators-release-4.6.yaml
  ci-operator/config/openshift-kni/performance-addon-operators/openshift-kni-performance-addon-operators-release-4.7.yaml
  ci-operator/config/openshift-kni/performance-addon-operators/openshift-kni-performance-addon-operators-release-4.8.yaml
  ci-operator/config/openshift-kni/performance-addon-operators/openshift-kni-performance-addon-operators-release-4.9.yaml
  ci-operator/jobs/openshift-kni/performance-addon-operators/openshift-kni-performance-addon-operators-release-4.10-presubmits.yaml
  ci-operator/jobs/openshift-kni/performance-addon-operators/openshift-kni-performance-addon-operators-release-4.11-presubmits.yaml
  ci-operator/jobs/openshift-kni/performance-addon-operators/openshift-kni-performance-addon-operators-release-4.4-postsubmits.yaml
  ci-operator/jobs/openshift-kni/performance-addon-operators/openshift-kni-performance-addon-operators-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift-kni/performance-addon-operators/openshift-kni-performance-addon-operators-release-4.5-postsubmits.yaml
  ci-operator/jobs/openshift-kni/performance-addon-operators/openshift-kni-performance-addon-operators-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift-kni/performance-addon-operators/openshift-kni-performance-addon-operators-release-4.6-postsubmits.yaml
  ci-operator/jobs/openshift-kni/performance-addon-operators/openshift-kni-performance-addon-operators-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift-kni/performance-addon-operators/openshift-kni-performance-addon-operators-release-4.7-postsubmits.yaml
  ci-operator/jobs/openshift-kni/performance-addon-operators/openshift-kni-performance-addon-operators-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift-kni/performance-addon-operators/openshift-kni-performance-addon-operators-release-4.8-postsubmits.yaml
  ci-operator/jobs/openshift-kni/performance-addon-operators/openshift-kni-performance-addon-operators-release-4.8-presubmits.yaml
  ci-operator/jobs/openshift-kni/performance-addon-operators/openshift-kni-performance-addon-operators-release-4.9-postsubmits.yaml
  ci-operator/jobs/openshift-kni/performance-addon-operators/openshift-kni-performance-addon-operators-release-4.9-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#47195 Add quay dast testing on stage quayio
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__quay-dast.yaml
  ci-operator/jobs/quay/quay-tests/quay-quay-tests-master-periodics.yaml
  ci-operator/jobs/quay/quay-tests/quay-quay-tests-master-presubmits.yaml
  ci-operator/step-registry/quay-tests/test-quay-dast/OWNERS
  ci-operator/step-registry/quay-tests/test-quay-dast/quay-tests-test-quay-dast-commands.sh
  ci-operator/step-registry/quay-tests/test-quay-dast/quay-tests-test-quay-dast-ref.metadata.json
  ci-operator/step-registry/quay-tests/test-quay-dast/quay-tests-test-quay-dast-ref.yaml
Labels: lgtm, approved, tide/merge-method-squash, rehearsals-ack
