Repository openshift/release, pull requests merged in 2024-12, with the labels that each got.

#59212 telcov10n: add hcp cnf 4.18 config
  ci-operator/config/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main__hcp-cnf-4.18.yaml
  ci-operator/jobs/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#59361 OCPQE-26329: Remove bootstrap IP drop rule on post
  ci-operator/step-registry/baremetal/lab/upi/install/baremetal-lab-upi-install-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#59360 Update ingress-lbtype workflow platform
  core-services/ci-chat-bot/workflows-config.yaml
Labels: lgtm, approved, rehearsals-ack

#59264 Enable mini-perm tests on 4.18 AWS jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__multi-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#59370 Integrate quay new UI stress testing to prow CI - V1
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__quay-newui-stress.yaml
  ci-operator/jobs/quay/quay-tests/quay-quay-tests-master-periodics.yaml
  ci-operator/jobs/quay/quay-tests/quay-quay-tests-master-presubmits.yaml
  ci-operator/step-registry/quay-tests/test-quay-newui-stress/OWNERS
  ci-operator/step-registry/quay-tests/test-quay-newui-stress/quay-tests-test-quay-newui-stress-commands.sh
  ci-operator/step-registry/quay-tests/test-quay-newui-stress/quay-tests-test-quay-newui-stress-ref.metadata.json
  ci-operator/step-registry/quay-tests/test-quay-newui-stress/quay-tests-test-quay-newui-stress-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#59378 Remove openshift-e2e-test-clusterinfra-qe from openshift-e2e-test-qe
  ci-operator/step-registry/openshift/e2e/test/qe/openshift-e2e-test-qe-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#59379 update 'gcp-ipi-proxy-oidc' into 'gcp-ipi-proxy-private' for tests in stable
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__multi-stable-4.15-upgrade-from-stable-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__multi-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__multi-stable-4.16-upgrade-from-stable-4.15.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__multi-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__multi-stable-4.17-upgrade-from-stable-4.16.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__multi-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__multi-stable-4.18-upgrade-from-stable-4.17.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__multi-stable.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#58774 Telco operators DAST testing CI
  ci-operator/config/openshift-kni/eco-ci-cd/.config.prowgen
  ci-operator/config/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main__telco-operators-dast-4.16.yaml
  ci-operator/jobs/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main-periodics.yaml
  ci-operator/jobs/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main-presubmits.yaml
  ci-operator/step-registry/telcov10n/functional/dast/OWNERS
  ci-operator/step-registry/telcov10n/functional/dast/setup/OWNERS
  ci-operator/step-registry/telcov10n/functional/dast/setup/telcov10n-functional-dast-setup-workflow.metadata.json
  ci-operator/step-registry/telcov10n/functional/dast/setup/telcov10n-functional-dast-setup-workflow.yaml
  ci-operator/step-registry/telcov10n/functional/dast/tests/OWNERS
  ci-operator/step-registry/telcov10n/functional/dast/tests/telcov10n-functional-dast-tests-commands.sh
  ci-operator/step-registry/telcov10n/functional/dast/tests/telcov10n-functional-dast-tests-ref.metadata.json
  ci-operator/step-registry/telcov10n/functional/dast/tests/telcov10n-functional-dast-tests-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#59388 Fix typo in create_kubeconfig.sh
  clusters/psi/create_kubeconfig.sh
Labels: lgtm, approved, rehearsals-ack

#58984 verify OCPBUGS-34974 Require additional service endpoint overrides
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly-4.18-upgrade-from-stable-4.18.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-stable.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.17.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.18.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
  ci-operator/step-registry/cucushift/installer/check/ibmcloud/custom-endpoints/cucushift-installer-check-ibmcloud-custom-endpoints-commands.sh
  ci-operator/step-registry/cucushift/installer/check/ibmcloud/custom-endpoints/cucushift-installer-check-ibmcloud-custom-endpoints-ref.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/ibmcloud/ipi/disconnected/private/provision/cucushift-installer-rehearse-ibmcloud-ipi-disconnected-private-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/ibmcloud/ipi/private/with-ep-cos/provision/cucushift-installer-rehearse-ibmcloud-ipi-private-with-ep-cos-provision-chain.yaml
  ci-operator/step-registry/ibmcloud/provision/vpc/endpoints-gateway/ibmcloud-provision-vpc-endpoints-gateway-commands.sh
  ci-operator/step-registry/ibmcloud/provision/vpc/endpoints-gateway/ibmcloud-provision-vpc-endpoints-gateway-ref.yaml
  ci-operator/step-registry/ipi/conf/ibmcloud/custom-endpoints/ipi-conf-ibmcloud-custom-endpoints-commands.sh
  ci-operator/step-registry/ipi/conf/ibmcloud/custom-endpoints/ipi-conf-ibmcloud-custom-endpoints-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#59383 [PERFSCALE-3525] Update OVN PerfScale AWS Cluster Profile us-east-1
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: lgtm, approved, rehearsals-ack

#59348 MULTIARCH-4696: Manage the creation of VPC connections to the Transit Gateway
  ci-operator/step-registry/upi/deprovision/heterogeneous/powervs/upi-deprovision-heterogeneous-powervs-commands.sh
  ci-operator/step-registry/upi/install/heterogeneous/powervs/upi-install-heterogeneous-powervs-commands.sh
Labels: lgtm, approved, ok-to-test, rehearsals-ack, jira/valid-reference

#59252 SPLAT-1899: Re-enable vsphere ipi volume deprovision
  ci-operator/step-registry/ipi/vsphere/post/ipi-vsphere-post-chain.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#59408 fix jobs after changes in prowgen and dispatcher algorithm
  ci-operator/jobs/migtools/oadp-non-admin/migtools-oadp-non-admin-master-postsubmits.yaml
  ci-operator/jobs/migtools/oadp-non-admin/migtools-oadp-non-admin-master-presubmits.yaml
  ci-operator/jobs/openshift-qe/baremetal-qe-infra/openshift-qe-baremetal-qe-infra-master-postsubmits.yaml
  ci-operator/jobs/openshift-qe/baremetal-qe-infra/openshift-qe-baremetal-qe-infra-master-presubmits.yaml
  ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
  ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-upstream-v3.2.0-postsubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-upstream-v3.2.0-presubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-upstream-v3.2.1-postsubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-upstream-v3.2.1-presubmits.yaml
  ci-operator/jobs/openshift/multiarch-tuning-operator/openshift-multiarch-tuning-operator-main-postsubmits.yaml
  ci-operator/jobs/openshift/multiarch-tuning-operator/openshift-multiarch-tuning-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/multiarch-tuning-operator/openshift-multiarch-tuning-operator-v0.0.1-postsubmits.yaml
  ci-operator/jobs/openshift/multiarch-tuning-operator/openshift-multiarch-tuning-operator-v0.0.1-presubmits.yaml
  ci-operator/jobs/openshift/multiarch-tuning-operator/openshift-multiarch-tuning-operator-v1.0-postsubmits.yaml
  ci-operator/jobs/openshift/multiarch-tuning-operator/openshift-multiarch-tuning-operator-v1.0-presubmits.yaml
  ci-operator/jobs/openshift/oadp-operator/openshift-oadp-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/oadp-operator/openshift-oadp-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/oadp-operator/openshift-oadp-operator-oadp-1.4-postsubmits.yaml
  ci-operator/jobs/openshift/oadp-operator/openshift-oadp-operator-oadp-1.4-presubmits.yaml
  ci-operator/jobs/openshift/openshift-velero-plugin/openshift-openshift-velero-plugin-master-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-velero-plugin/openshift-openshift-velero-plugin-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-velero-plugin/openshift-openshift-velero-plugin-oadp-1.4-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-velero-plugin/openshift-openshift-velero-plugin-oadp-1.4-presubmits.yaml
  ci-operator/jobs/openshift/velero-plugin-for-aws/openshift-velero-plugin-for-aws-konveyor-dev-postsubmits.yaml
  ci-operator/jobs/openshift/velero-plugin-for-aws/openshift-velero-plugin-for-aws-konveyor-dev-presubmits.yaml
  ci-operator/jobs/openshift/velero-plugin-for-aws/openshift-velero-plugin-for-aws-oadp-1.4-postsubmits.yaml
  ci-operator/jobs/openshift/velero-plugin-for-aws/openshift-velero-plugin-for-aws-oadp-1.4-presubmits.yaml
  ci-operator/jobs/openshift/velero-plugin-for-gcp/openshift-velero-plugin-for-gcp-konveyor-dev-postsubmits.yaml
  ci-operator/jobs/openshift/velero-plugin-for-gcp/openshift-velero-plugin-for-gcp-konveyor-dev-presubmits.yaml
  ci-operator/jobs/openshift/velero-plugin-for-gcp/openshift-velero-plugin-for-gcp-oadp-1.4-postsubmits.yaml
  ci-operator/jobs/openshift/velero-plugin-for-gcp/openshift-velero-plugin-for-gcp-oadp-1.4-presubmits.yaml
  ci-operator/jobs/openshift/velero-plugin-for-legacy-aws/openshift-velero-plugin-for-legacy-aws-konveyor-dev-postsubmits.yaml
  ci-operator/jobs/openshift/velero-plugin-for-legacy-aws/openshift-velero-plugin-for-legacy-aws-konveyor-dev-presubmits.yaml
  ci-operator/jobs/openshift/velero-plugin-for-legacy-aws/openshift-velero-plugin-for-legacy-aws-oadp-1.4-postsubmits.yaml
  ci-operator/jobs/openshift/velero-plugin-for-legacy-aws/openshift-velero-plugin-for-legacy-aws-oadp-1.4-presubmits.yaml
  ci-operator/jobs/openshift/velero-plugin-for-microsoft-azure/openshift-velero-plugin-for-microsoft-azure-konveyor-dev-postsubmits.yaml
  ci-operator/jobs/openshift/velero-plugin-for-microsoft-azure/openshift-velero-plugin-for-microsoft-azure-konveyor-dev-presubmits.yaml
  ci-operator/jobs/openshift/velero-plugin-for-microsoft-azure/openshift-velero-plugin-for-microsoft-azure-oadp-1.4-postsubmits.yaml
  ci-operator/jobs/openshift/velero-plugin-for-microsoft-azure/openshift-velero-plugin-for-microsoft-azure-oadp-1.4-presubmits.yaml
  ci-operator/jobs/openshift/velero/openshift-velero-konveyor-dev-postsubmits.yaml
  ci-operator/jobs/openshift/velero/openshift-velero-konveyor-dev-presubmits.yaml
  ci-operator/jobs/openshift/velero/openshift-velero-oadp-1.4-postsubmits.yaml
  ci-operator/jobs/openshift/velero/openshift-velero-oadp-1.4-presubmits.yaml
  ci-operator/jobs/stolostron/image-builder/stolostron-image-builder-master-postsubmits.yaml
  ci-operator/jobs/stolostron/image-builder/stolostron-image-builder-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#59406 fix logging 6.1 testing to for ER and LFME
  ci-operator/config/openshift/cluster-logging-operator/openshift-cluster-logging-operator-release-6.1.yaml
Labels: lgtm, approved, rehearsals-ack

#59038 increase memory in nmstate
  ci-operator/config/openshift/nmstate-console-plugin/openshift-nmstate-console-plugin-main.yaml
  ci-operator/config/openshift/nmstate-console-plugin/openshift-nmstate-console-plugin-release-4.17.yaml
  ci-operator/config/openshift/nmstate-console-plugin/openshift-nmstate-console-plugin-release-4.18.yaml
  ci-operator/config/openshift/nmstate-console-plugin/openshift-nmstate-console-plugin-release-4.19.yaml
Labels: lgtm, approved, rehearsals-ack

#59337 hcp/osp: clean clouds.yaml CLI args
  ci-operator/step-registry/hypershift/openstack/create/hostedcluster/hypershift-openstack-create-hostedcluster-commands.sh
  ci-operator/step-registry/hypershift/openstack/e2e/execute/hypershift-openstack-e2e-execute-commands.sh
Labels: lgtm, approved, rehearsals-ack

#59414 elasticsearch-operator: Add minimal CI config for master
  ci-operator/config/openshift/elasticsearch-operator/openshift-elasticsearch-operator-master.yaml
  ci-operator/jobs/openshift/elasticsearch-operator/openshift-elasticsearch-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/elasticsearch-operator/openshift-elasticsearch-operator-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#59419 Partial revert of vsphere python steps
  ci-operator/step-registry/ipi/conf/vsphere/dns/ipi-conf-vsphere-dns-ref.yaml
  ci-operator/step-registry/ipi/deprovision/vsphere/dns/ipi-deprovision-vsphere-dns-ref.yaml
  ci-operator/step-registry/ipi/vsphere/post/ipi-vsphere-post-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#59411 csi-openstack: fix manifest logic
  ci-operator/step-registry/storage/conf/csi-openstack-cinder/storage-conf-csi-openstack-cinder-commands.sh
  ci-operator/step-registry/storage/conf/csi-openstack-manila/storage-conf-csi-openstack-manila-commands.sh
Labels: lgtm, approved, rehearsals-ack

#59424 Add auto-upgrade for build06
  ci-operator/jobs/infra-periodics.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#59088 HCP on OSP jobs for Cinder & Manila CSI into CSO and csi-operator
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-master.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.18.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.19.yaml
  ci-operator/config/openshift/csi-operator/openshift-csi-operator-master.yaml
  ci-operator/config/openshift/csi-operator/openshift-csi-operator-release-4.18.yaml
  ci-operator/config/openshift/csi-operator/openshift-csi-operator-release-4.19.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.18-presubmits.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.19-presubmits.yaml
  ci-operator/jobs/openshift/csi-operator/openshift-csi-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/csi-operator/openshift-csi-operator-release-4.18-presubmits.yaml
  ci-operator/jobs/openshift/csi-operator/openshift-csi-operator-release-4.19-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#59422 PowerVS: Use version 0.2.2 of get-largest-system-pool
  ci-operator/step-registry/ipi/conf/powervs/ipi-conf-powervs-commands.sh
Labels: lgtm, approved, rehearsals-ack

#59416 Pin sippy e2e presubmit to build10 due to build06 secret problem
  ci-operator/config/openshift/sippy/openshift-sippy-master.yaml
  ci-operator/jobs/openshift/sippy/openshift-sippy-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#59382 Enable mini-perm tests on 4.18 AWS jobs [Upgrade]
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly-4.18-upgrade-from-stable-4.18.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__arm64-nightly-4.18-upgrade-from-stable-4.18.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__multi-nightly-4.18-upgrade-from-stable-4.18.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#59377 Update TEST_PARALLEL parameter for compliance operator releated test jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-nightly.yaml
Labels: lgtm, approved, rehearsals-ack

#59415 MULTIARCH-4696: update to e980
  ci-operator/step-registry/upi/install/powervs/cluster/upi-install-powervs-cluster-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#59216 OCM-12262 | ci: enable rosa classic profile for OCP E2E 4.18 nightly
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18-periodics.yaml
  ci-operator/step-registry/rosa/setup/readiness/nodes/rosa-setup-readiness-nodes-commands.sh
  ci-operator/step-registry/rosa/setup/readiness/nodes/rosa-setup-readiness-nodes-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#59037 [PERFSCALE-3540] Added the configurable kubeconfig path
  ci-operator/step-registry/openshift-qe/ingress-perf/openshift-qe-ingress-perf-commands.sh
  ci-operator/step-registry/openshift-qe/ingress-perf/openshift-qe-ingress-perf-ref.yaml
  ci-operator/step-registry/openshift-qe/installer/bm/day2/cnv/openshift-qe-installer-bm-day2-cnv-commands.sh
  ci-operator/step-registry/openshift-qe/installer/bm/day2/cnv/openshift-qe-installer-bm-day2-cnv-ref.yaml
  ci-operator/step-registry/openshift-qe/installer/bm/day2/label/openshift-qe-installer-bm-day2-label-commands.sh
  ci-operator/step-registry/openshift-qe/installer/bm/day2/label/openshift-qe-installer-bm-day2-label-ref.yaml
  ci-operator/step-registry/openshift-qe/installer/bm/day2/lso/openshift-qe-installer-bm-day2-lso-commands.sh
  ci-operator/step-registry/openshift-qe/installer/bm/day2/lso/openshift-qe-installer-bm-day2-lso-ref.yaml
  ci-operator/step-registry/openshift-qe/installer/bm/day2/metallb/openshift-qe-installer-bm-day2-metallb-commands.sh
  ci-operator/step-registry/openshift-qe/installer/bm/day2/metallb/openshift-qe-installer-bm-day2-metallb-ref.yaml
  ci-operator/step-registry/openshift-qe/installer/bm/day2/perf-profile/rds-core/openshift-qe-installer-bm-day2-perf-profile-rds-core-commands.sh
  ci-operator/step-registry/openshift-qe/installer/bm/day2/perf-profile/rds-core/openshift-qe-installer-bm-day2-perf-profile-rds-core-ref.yaml
  ci-operator/step-registry/openshift-qe/installer/bm/day2/sriov/openshift-qe-installer-bm-day2-sriov-commands.sh
  ci-operator/step-registry/openshift-qe/installer/bm/day2/sriov/openshift-qe-installer-bm-day2-sriov-ref.yaml
  ci-operator/step-registry/openshift-qe/network-perf/openshift-qe-network-perf-commands.sh
  ci-operator/step-registry/openshift-qe/network-perf/openshift-qe-network-perf-ref.yaml
  ci-operator/step-registry/openshift-qe/network-smoke/openshift-qe-network-smoke-commands.sh
  ci-operator/step-registry/openshift-qe/network-smoke/openshift-qe-network-smoke-ref.yaml
  ci-operator/step-registry/openshift-qe/network-vm-perf/openshift-qe-network-vm-perf-commands.sh
  ci-operator/step-registry/openshift-qe/network-vm-perf/openshift-qe-network-vm-perf-ref.yaml
  ci-operator/step-registry/openshift-qe/node-density-heavy/openshift-qe-node-density-heavy-commands.sh
  ci-operator/step-registry/openshift-qe/node-density-heavy/openshift-qe-node-density-heavy-ref.yaml
  ci-operator/step-registry/openshift-qe/udn-density-l2-pods/openshift-qe-udn-density-l2-pods-commands.sh
  ci-operator/step-registry/openshift-qe/udn-density-l2-pods/openshift-qe-udn-density-l2-pods-ref.yaml
  ci-operator/step-registry/openshift-qe/udn-density-l3-pods/openshift-qe-udn-density-l3-pods-commands.sh
  ci-operator/step-registry/openshift-qe/udn-density-l3-pods/openshift-qe-udn-density-l3-pods-ref.yaml
  ci-operator/step-registry/openshift-qe/web-burner/openshift-qe-web-burner-commands.sh
  ci-operator/step-registry/openshift-qe/web-burner/openshift-qe-web-burner-ref.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#59440 rhdh cluster pool size update
  clusters/hosted-mgmt/hive/pools/rhdh/rhdh-ocp-4-15-0-amd64-aws-us-east-2_clusterpool.yaml
  clusters/hosted-mgmt/hive/pools/rhdh/rhdh-ocp-4-16-0-amd64-aws-us-east-2_clusterpool.yaml
  clusters/hosted-mgmt/hive/pools/rhdh/rhdh-ocp-4-17-0-amd64-aws-us-east-2_clusterpool.yaml
Labels: lgtm, approved, rehearsals-ack

#59435 Test RHOSDT 3.4 Tempo
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.12-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.13-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.14-arm-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.14-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.15-ibm-p-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.15-ibm-z-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.15-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.16-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.17-stage.yaml
  ci-operator/step-registry/distributed-tracing/tests/tempo/downstream/distributed-tracing-tests-tempo-downstream-commands.sh
  ci-operator/step-registry/distributed-tracing/tests/tempo/downstream/distributed-tracing-tests-tempo-downstream-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#59397 Test RHOSDT 3.4 OTEL
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.12-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.13-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.14-arm-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.14-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.15-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.16-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.17-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-ibm-p-4.15-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-ibm-z-4.15-stage.yaml
  ci-operator/step-registry/distributed-tracing/tests/opentelemetry/downstream/distributed-tracing-tests-opentelemetry-downstream-commands.sh
  ci-operator/step-registry/distributed-tracing/tests/opentelemetry/downstream/distributed-tracing-tests-opentelemetry-downstream-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#59410 OCPBUGS-44943 still return 0 in order to continue test
  ci-operator/step-registry/cucushift/installer/check/ibmcloud/custom-endpoints/cucushift-installer-check-ibmcloud-custom-endpoints-commands.sh
Labels: lgtm, approved, rehearsals-ack

#59443 [ODH] Disable prow branch protection for v1.9-branch on kubeflow repository
  core-services/prow/02_config/opendatahub-io/kubeflow/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#59449 Add condition to check cluster stability if the version is 4.15 or more
  ci-operator/step-registry/cucushift/agent/vsphere/provision/cucushift-agent-vsphere-provision-commands.sh
Labels: lgtm, approved, rehearsals-ack

#59334 Add mapt to mirrored images
  core-services/image-mirroring/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#59425 Add hypershift conformance job to origin presubmit
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#59099 CORS-3698: Introduce default configuration step on AWS
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.16.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.17.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.18.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/default/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/default/cucushift-installer-rehearse-aws-ipi-default-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/default/cucushift-installer-rehearse-aws-ipi-default-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/default/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/default/provision/cucushift-installer-rehearse-aws-ipi-default-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/default/provision/cucushift-installer-rehearse-aws-ipi-default-provision-chain.yaml
  ci-operator/step-registry/ipi/conf/aws/default/OWNERS
  ci-operator/step-registry/ipi/conf/aws/default/ipi-conf-aws-default-commands.sh
  ci-operator/step-registry/ipi/conf/aws/default/ipi-conf-aws-default-ref.metadata.json
  ci-operator/step-registry/ipi/conf/aws/default/ipi-conf-aws-default-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#59403 assisted installer: set writable location for golang cache
  ci-operator/config/openshift-assisted/cluster-api-agent/openshift-assisted-cluster-api-agent-master.yaml
Labels: lgtm, approved, rehearsals-ack

#59386 OLS-1252 - Separating periodic jobs
  ci-operator/config/openshift/lightspeed-service/openshift-lightspeed-service-main__4.15.yaml
  ci-operator/config/openshift/lightspeed-service/openshift-lightspeed-service-main__4.16.yaml
  ci-operator/config/openshift/lightspeed-service/openshift-lightspeed-service-main__4.17.yaml
  ci-operator/jobs/openshift/lightspeed-service/openshift-lightspeed-service-main-periodics.yaml
  ci-operator/jobs/openshift/lightspeed-service/openshift-lightspeed-service-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#59454 Remove readonly org/repo to cure fast-forwarding periodic
  ci-operator/config/project-flotta/flotta-operator/OWNERS
  ci-operator/config/project-flotta/flotta-operator/project-flotta-flotta-operator-main.yaml
  ci-operator/config/project-flotta/flotta-operator/project-flotta-flotta-operator-release-4.11.yaml
  ci-operator/config/project-flotta/flotta-operator/project-flotta-flotta-operator-release-4.12.yaml
  ci-operator/config/project-flotta/flotta-operator/project-flotta-flotta-operator-release-4.13.yaml
  ci-operator/config/project-flotta/flotta-operator/project-flotta-flotta-operator-release-4.14.yaml
  ci-operator/config/project-flotta/flotta-operator/project-flotta-flotta-operator-release-4.15.yaml
  ci-operator/config/project-flotta/flotta-operator/project-flotta-flotta-operator-release-4.16.yaml
  ci-operator/config/project-flotta/flotta-operator/project-flotta-flotta-operator-release-4.17.yaml
  ci-operator/config/project-flotta/flotta-operator/project-flotta-flotta-operator-release-4.18.yaml
  ci-operator/config/project-flotta/flotta-operator/project-flotta-flotta-operator-release-4.19.yaml
  ci-operator/config/project-flotta/flotta-operator/project-flotta-flotta-operator-release-4.20.yaml
  ci-operator/jobs/project-flotta/flotta-operator/OWNERS
  ci-operator/jobs/project-flotta/flotta-operator/project-flotta-flotta-operator-main-presubmits.yaml
  ci-operator/jobs/project-flotta/flotta-operator/project-flotta-flotta-operator-release-4.11-presubmits.yaml
  ci-operator/jobs/project-flotta/flotta-operator/project-flotta-flotta-operator-release-4.12-presubmits.yaml
  ci-operator/jobs/project-flotta/flotta-operator/project-flotta-flotta-operator-release-4.13-presubmits.yaml
  ci-operator/jobs/project-flotta/flotta-operator/project-flotta-flotta-operator-release-4.14-presubmits.yaml
  ci-operator/jobs/project-flotta/flotta-operator/project-flotta-flotta-operator-release-4.15-presubmits.yaml
  ci-operator/jobs/project-flotta/flotta-operator/project-flotta-flotta-operator-release-4.16-presubmits.yaml
  ci-operator/jobs/project-flotta/flotta-operator/project-flotta-flotta-operator-release-4.17-presubmits.yaml
  ci-operator/jobs/project-flotta/flotta-operator/project-flotta-flotta-operator-release-4.18-presubmits.yaml
  ci-operator/jobs/project-flotta/flotta-operator/project-flotta-flotta-operator-release-4.19-presubmits.yaml
  ci-operator/jobs/project-flotta/flotta-operator/project-flotta-flotta-operator-release-4.20-presubmits.yaml
  core-services/prow/02_config/project-flotta/flotta-operator/OWNERS
  core-services/prow/02_config/project-flotta/flotta-operator/_pluginconfig.yaml
  core-services/prow/02_config/project-flotta/flotta-operator/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#59241 HCO: Bump operator-sdk to v1.37.0
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-main.yaml
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-main__okd.yaml
Labels: lgtm, approved, rehearsals-ack

#59459 add 'check registry.redhat.io is available' to TEST_SKIPS
  ci-operator/step-registry/hypershift/mce/agent/metal3/conformance/hypershift-mce-agent-metal3-conformance-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#59412 Fix release configuration for virt techpreview jobs
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.18__periodics.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.19__periodics.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.18-periodics.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.18-presubmits.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.19-periodics.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.19-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#59466 Sync Serverless CI config/
  ci-operator/config/openshift-knative/kn-plugin-func/openshift-knative-kn-plugin-func-release-next__417.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#59467 Clean up GRC Kind credential
  ci-operator/step-registry/ocm/e2e/kind/create/ocm-e2e-kind-create-ref.yaml
  ci-operator/step-registry/ocm/e2e/kind/destroy/ocm-e2e-kind-destroy-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#59199 CCO 4.16 periodics daily
  ci-operator/config/openshift/cloud-credential-operator/openshift-cloud-credential-operator-release-4.16__periodics.yaml
  ci-operator/jobs/openshift/cloud-credential-operator/openshift-cloud-credential-operator-release-4.16-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#59404 Interop - Update AAP to test on version 2.5 on OCP 4.18
  ci-operator/config/ansible/tower-qa/ansible-tower-qa-devel__ocp4.18-lp-interop.yaml
  ci-operator/jobs/ansible/tower-qa/ansible-tower-qa-devel-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#59465 disable automatic aks e2e runs on hypershift
  ci-operator/config/openshift-priv/hypershift/openshift-priv-hypershift-main.yaml
  ci-operator/config/openshift-priv/hypershift/openshift-priv-hypershift-release-4.17.yaml
  ci-operator/config/openshift-priv/hypershift/openshift-priv-hypershift-release-4.18.yaml
  ci-operator/config/openshift-priv/hypershift/openshift-priv-hypershift-release-4.19.yaml
  ci-operator/config/openshift-priv/hypershift/openshift-priv-hypershift-release-4.20.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-main.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.17.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.18.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.19.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.20.yaml
  ci-operator/jobs/openshift-priv/hypershift/openshift-priv-hypershift-main-presubmits.yaml
  ci-operator/jobs/openshift-priv/hypershift/openshift-priv-hypershift-release-4.17-presubmits.yaml
  ci-operator/jobs/openshift-priv/hypershift/openshift-priv-hypershift-release-4.18-presubmits.yaml
  ci-operator/jobs/openshift-priv/hypershift/openshift-priv-hypershift-release-4.19-presubmits.yaml
  ci-operator/jobs/openshift-priv/hypershift/openshift-priv-hypershift-release-4.20-presubmits.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-main-presubmits.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.17-presubmits.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.18-presubmits.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.19-presubmits.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.20-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#59474 Bumping timeout for featuregate
  ci-operator/step-registry/openshift-qe/installer/featuregate/openshift-qe-installer-featuregate-commands.sh
Labels: lgtm, approved, rehearsals-ack

#59473 Add RHOAI-metal test POC
  ci-operator/config/openshift-psap/topsail/openshift-psap-topsail-main__rhoai.yaml
  ci-operator/jobs/openshift-psap/topsail/openshift-psap-topsail-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, network-access-rehearsals-ok

#59069 NO-JIRA: add abi compact job (optional)
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-master.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#59205 NETOBSERV-1988 netobserv clusterpool
  clusters/hosted-mgmt/hive/pools/openshift-observability/obs-netobserv-ocp-4-17-amd64-us-east-1_clusterpool.yaml
Labels: lgtm, approved, rehearsals-ack

#59342 Update OCP levels to 4.17 for ci tests
  ci-operator/config/janus-idp/backstage-showcase/janus-idp-backstage-showcase-main.yaml
  ci-operator/jobs/janus-idp/backstage-showcase/janus-idp-backstage-showcase-main-periodics.yaml
  ci-operator/step-registry/janus-idp/backstage-showcase/1.2.x/janus-idp-backstage-showcase-1.2.x-commands.sh
  ci-operator/step-registry/janus-idp/backstage-showcase/janus-idp-backstage-showcase-commands.sh
  ci-operator/step-registry/janus-idp/backstage-showcase/nightly/janus-idp-backstage-showcase-nightly-ref.yaml
  ci-operator/step-registry/janus-idp/backstage-showcase/release-1.3/janus-idp-backstage-showcase-release-1.3-commands.sh
Labels: lgtm, approved, rehearsals-ack

#59461 OCPQE-27386: rosa: only wait for osd-cluster-ready on non-hcp
  ci-operator/step-registry/rosa/cluster/wait-ready/operators/rosa-cluster-wait-ready-operators-commands.sh
  ci-operator/step-registry/rosa/cluster/wait-ready/operators/rosa-cluster-wait-ready-operators-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#59456 Update image mirroring for 3scale-interop-tests
  core-services/image-mirroring/_config.yaml
Labels: lgtm, approved, needs-ok-to-test, rehearsals-ack

#59277 Add nightly jobs for Nutanix Winc
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#59399 ignore job/osd-cluster-ready for rosa hcp
  ci-operator/step-registry/cucushift/hypershift-extended/health-check/cucushift-hypershift-extended-health-check-commands.sh
Labels: lgtm, approved, rehearsals-ack

#59355 enhance the way of getting new capacities list in upgrade cases
  ci-operator/step-registry/cucushift/upgrade/check/capability/cucushift-upgrade-check-capability-commands.sh
Labels: lgtm, approved, rehearsals-ack

#52542 Ibmcloud Network perf test
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__ibmcloud-4.18-nightly-x86.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-presubmits.yaml
  ci-operator/step-registry/cucushift/installer/wait/cucushift-installer-wait-commands.sh
  ci-operator/step-registry/openshift-qe/perfscale-ibm-data-path-sg/OWNERS
  ci-operator/step-registry/openshift-qe/perfscale-ibm-data-path-sg/openshift-qe-perfscale-ibm-data-path-sg-commands.sh
  ci-operator/step-registry/openshift-qe/perfscale-ibm-data-path-sg/openshift-qe-perfscale-ibm-data-path-sg-ref.metadata.json
  ci-operator/step-registry/openshift-qe/perfscale-ibm-data-path-sg/openshift-qe-perfscale-ibm-data-path-sg-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#59118 OSASINFRA-3562: ShiftStack 4.15 periodic jobs relocation
  ci-operator/config/shiftstack/ci/shiftstack-ci-release-4.15.yaml
  ci-operator/jobs/shiftstack/ci/shiftstack-ci-release-4.15-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#59499 Removing precommits for 415 416 in ols
  ci-operator/config/openshift/lightspeed-service/openshift-lightspeed-service-main__4.15.yaml
  ci-operator/config/openshift/lightspeed-service/openshift-lightspeed-service-main__4.16.yaml
  ci-operator/jobs/openshift/lightspeed-service/openshift-lightspeed-service-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#59503 MGMT-19370: Add e2e none platform 4 masters job
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#59504 Openstack-test: Add tide config for release-4.18
  core-services/prow/02_config/openshift/openstack-test/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#59510 Upgrade cluster-logging-operator
  clusters/build-clusters/common_ocp/openshift-logging-operator.yaml
Labels: lgtm, approved, rehearsals-ack

#59451 RHOSDT 3.4 security and FIPS scan
  ci-operator/config/openshift/distributed-tracing-qe/openshift-distributed-tracing-qe-main__ocp-4.14-dast.yaml
  ci-operator/config/openshift/distributed-tracing-qe/openshift-distributed-tracing-qe-main__ocp-4.16-fips-scan.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__upstream-ocp-4.15-amd64-aws.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__upstream-ocp-4.15-amd64-aws.yaml
  ci-operator/jobs/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#59495 RHOSDT 3.4 test Jaeger
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.12-stage.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.13-stage.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.14-arm-stage.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.14-stage.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.15-ibm-p-stage.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.15-ibm-z-stage.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.15-stage.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.16-stage.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.17-stage.yaml
Labels: lgtm, approved, rehearsals-ack

#59445 dast ci job for 4.17
  ci-operator/config/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main__telco-operators-dast-4.17.yaml
  ci-operator/jobs/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main-periodics.yaml
  ci-operator/jobs/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#59444 Remove last cdc from FIPs POC ClusterPool
  clusters/hosted-mgmt/hive/pools/openstack-k8s-operators/openstack-k8s-operators-4-14-vexxhost-hybrid_fips_clusterpool.yaml
  clusters/hosted-mgmt/hive/pools/openstack-k8s-operators/openstack-k8s-operators-4-18-vexxhost-hybrid_clusterpool.yaml
Labels: lgtm, approved, rehearsals-ack

#59472 virt, periodics, 4.19: enable TP feature set
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.19__periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#57927 [PERFSCALE-3509] BM CPT deployment pre-reqs
  ci-operator/step-registry/openshift-qe/installer/bm/deploy/openshift-qe-installer-bm-deploy-commands.sh
  ci-operator/step-registry/openshift-qe/installer/bm/deploy/openshift-qe-installer-bm-deploy-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#59446 chore(RHIDP-4928): add jobs for rhdh-v1.3.x release branch
  ci-operator/config/redhat-performance/backstage-performance/redhat-performance-backstage-performance-rhdh-v1.3.x.yaml
  ci-operator/jobs/redhat-performance/backstage-performance/redhat-performance-backstage-performance-rhdh-v1.3.x-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#59276 add mco sno pin target image
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly-4.16-upgrade-from-stable-4.16.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#59488 CORS-3698 - Add test for AWS default install config
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.18.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.19.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.20.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.18-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.19-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.20-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#59521 Remove workaround for metal zone
  clusters/build-clusters/common_managed/dns.yaml
Labels: lgtm, approved, rehearsals-ack

#58576 Openjdk zstream expansion and remove fips config
  ci-operator/config/rh-openjdk/jdkContainerOcpTests/rh-openjdk-jdkContainerOcpTests-main__openjdk-ocp4.16-lp-interop.yaml
  ci-operator/config/rh-openjdk/jdkContainerOcpTests/rh-openjdk-jdkContainerOcpTests-main__openjdk-ocp4.17-lp-interop.yaml
  ci-operator/config/rh-openjdk/jdkContainerOcpTests/rh-openjdk-jdkContainerOcpTests-main__openjdk-ocp4.18-lp-interop.yaml
  ci-operator/jobs/rh-openjdk/jdkContainerOcpTests/rh-openjdk-jdkContainerOcpTests-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#59529 Update `cincinnati-approvers`
  OWNERS_ALIASES
Labels: lgtm, approved, rehearsals-ack

#59513 Add linter status checker to o/api
  ci-operator/config/openshift/api/openshift-api-master.yaml
  ci-operator/jobs/openshift/api/openshift-api-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#59517 Remove HCP on OSP jobs for 4.17
  ci-operator/config/openshift-priv/hypershift/openshift-priv-hypershift-release-4.17.yaml
  ci-operator/config/openshift-priv/machine-config-operator/openshift-priv-machine-config-operator-release-4.17.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.17.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.17__periodics.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.17.yaml
  ci-operator/jobs/openshift-priv/hypershift/openshift-priv-hypershift-release-4.17-presubmits.yaml
  ci-operator/jobs/openshift-priv/machine-config-operator/openshift-priv-machine-config-operator-release-4.17-presubmits.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.17-periodics.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.17-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.17-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#59405 Skip istioctl unsupported commands tests
  ci-operator/config/openshift-service-mesh/istio/openshift-service-mesh-istio-master.yaml
Labels: lgtm, approved, rehearsals-ack

#59518 OTA-1348: cincinnati-ci: Add RBAC and Secret to pull the Cincinnati CI images
  clusters/app.ci/supplemental-ci-images/cincinnati-ci/cincinnati-ci-registry-viewer.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#59533 [BM/CPT] Quick fix in the pre-reqs
  ci-operator/step-registry/openshift-qe/installer/bm/deploy/openshift-qe-installer-bm-deploy-commands.sh
Labels: lgtm, approved, rehearsals-ack

#59516 Interop - Update AMQ-Streams to 2.8 on FIPS and fix crons
  ci-operator/config/amq-streams-qe/strimzi-kafka-operator/.config.prowgen
  ci-operator/config/amq-streams-qe/strimzi-kafka-operator/amq-streams-qe-strimzi-kafka-operator-main__amq-streams-ocp4.18-lp-interop.yaml
  ci-operator/jobs/amq-streams-qe/strimzi-kafka-operator/amq-streams-qe-strimzi-kafka-operator-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#59532 Realign base images
  ci-operator/config/stolostron/cluster-proxy-addon/stolostron-cluster-proxy-addon-backplane-2.8.yaml
  ci-operator/config/stolostron/cluster-proxy-addon/stolostron-cluster-proxy-addon-main.yaml
  ci-operator/config/stolostron/cluster-proxy/stolostron-cluster-proxy-backplane-2.7.yaml
  ci-operator/config/stolostron/cluster-proxy/stolostron-cluster-proxy-backplane-2.8.yaml
  ci-operator/config/stolostron/cluster-proxy/stolostron-cluster-proxy-main.yaml
Labels: lgtm, approved, rehearsals-ack

#59381 [HyperShift] add shared vpc support
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18-periodics.yaml
  ci-operator/step-registry/hypershift/aws/create/hypershift-aws-create-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#59550 OCPQE-27382: Add tests for OCP 4.19 in OpenShift CI
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__multi-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#59493 Add presubmit job to check upgrade tags
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#58572 Datagrid zstream expansion and remove FIPS config
  ci-operator/config/infinispan/infinispan-operator/infinispan-infinispan-operator-stable__data-grid-ocp4.16-lp-interop.yaml
  ci-operator/config/infinispan/infinispan-operator/infinispan-infinispan-operator-stable__data-grid-ocp4.17-lp-interop.yaml
  ci-operator/config/infinispan/infinispan-operator/infinispan-infinispan-operator-stable__data-grid-ocp4.18-lp-interop.yaml
  ci-operator/jobs/infinispan/infinispan-operator/infinispan-infinispan-operator-stable-periodics.yaml
  ci-operator/jobs/infinispan/infinispan-operator/infinispan-infinispan-operator-stable-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#59542 OCPQE-27389 - Add default configuration step on Azure
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.16.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.17.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.18.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/default/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/default/cucushift-installer-rehearse-azure-ipi-default-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/default/cucushift-installer-rehearse-azure-ipi-default-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/default/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/default/provision/cucushift-installer-rehearse-azure-ipi-default-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/default/provision/cucushift-installer-rehearse-azure-ipi-default-provision-chain.yaml
  ci-operator/step-registry/ipi/conf/azure/default/OWNERS
  ci-operator/step-registry/ipi/conf/azure/default/ipi-conf-azure-default-commands.sh
  ci-operator/step-registry/ipi/conf/azure/default/ipi-conf-azure-default-ref.metadata.json
  ci-operator/step-registry/ipi/conf/azure/default/ipi-conf-azure-default-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#59314 MGMT-19234: Add OpenShift sandboxed containers operator(OSC)
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-presubmits.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack, jira/valid-reference

#59453 remove evakhoni
  ci-operator/step-registry/cucushift/ota/OWNERS
  ci-operator/step-registry/cucushift/ota/postupgrade/OWNERS
  ci-operator/step-registry/cucushift/ota/postupgrade/cucushift-ota-postupgrade-ref.metadata.json
  ci-operator/step-registry/cucushift/ota/preupgrade/OWNERS
  ci-operator/step-registry/cucushift/ota/preupgrade/cucushift-ota-preupgrade-ref.metadata.json
  ci-operator/step-registry/cucushift/upgrade/check/capability/OWNERS
  ci-operator/step-registry/cucushift/upgrade/check/capability/cucushift-upgrade-check-capability-ref.metadata.json
  ci-operator/step-registry/cucushift/upgrade/cpou/latest/OWNERS
  ci-operator/step-registry/cucushift/upgrade/cpou/pause-worker-mcp/OWNERS
  ci-operator/step-registry/cucushift/upgrade/cpou/pause-worker-mcp/cucushift-upgrade-cpou-pause-worker-mcp-ref.metadata.json
  ci-operator/step-registry/cucushift/upgrade/cpou/unpause-worker-mcp/OWNERS
  ci-operator/step-registry/cucushift/upgrade/cpou/unpause-worker-mcp/cucushift-upgrade-cpou-unpause-worker-mcp-ref.metadata.json
  ci-operator/step-registry/mco/conf/day2/destroy-custom-mcp/OWNERS
  ci-operator/step-registry/mco/conf/day2/destroy-custom-mcp/mco-conf-day2-destroy-custom-mcp-ref.metadata.json
  ci-operator/step-registry/openshift/upgrade/qe/sanity/cpou/OWNERS
  ci-operator/step-registry/openshift/upgrade/qe/sanity/cpou/openshift-upgrade-qe-sanity-cpou-chain.metadata.json
  ci-operator/step-registry/openshift/upgrade/qe/test/canary/OWNERS
  ci-operator/step-registry/openshift/upgrade/qe/test/canary/openshift-upgrade-qe-test-canary-chain.metadata.json
  ci-operator/step-registry/openshift/upgrade/qe/test/cpou/OWNERS
  ci-operator/step-registry/openshift/upgrade/qe/test/cpou/openshift-upgrade-qe-test-cpou-chain.metadata.json
Labels: lgtm, approved, rehearsals-ack

#59531 OLS-658: lightspeed-operator: update to golang 1.22
  ci-operator/config/openshift/lightspeed-operator/openshift-lightspeed-operator-main.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#59500 remove CustomNoUpgrade for multi vCenter CI jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly-4.18-upgrade-from-stable-4.18.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#59519 RHOSDT 3.4 test on IBM P
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.16-ibm-p-stage.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.16-ibm-p-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.15-ibm-z-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.16-ibm-p-stage.yaml
  ci-operator/jobs/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main-presubmits.yaml
  ci-operator/step-registry/distributed-tracing/install/ibm-p/distributed-tracing-install-ibm-p-workflow.yaml
  ci-operator/step-registry/distributed-tracing/install/ibm-z/distributed-tracing-install-ibm-z-workflow.yaml
  ci-operator/step-registry/distributed-tracing/install/jaeger-konflux-catalogsource/distributed-tracing-install-jaeger-konflux-catalogsource-commands.sh
  ci-operator/step-registry/distributed-tracing/install/otel-konflux-catalogsource/distributed-tracing-install-otel-konflux-catalogsource-commands.sh
  ci-operator/step-registry/distributed-tracing/install/tempo-konflux-catalogsource/distributed-tracing-install-tempo-konflux-catalogsource-commands.sh
Labels: lgtm, approved, rehearsals-ack

#59262 SDN-5498: increase all jobs w/out timeout specified to 6h
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master__4.18-upgrade-from-stable-4.17.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.16.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.16__4.16-upgrade-from-stable-4.15.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.17.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.17__4.17-upgrade-from-stable-4.16.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.18.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.19.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master-periodics.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master-presubmits.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.16-periodics.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.16-presubmits.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.17-periodics.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.17-presubmits.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.18-periodics.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.18-presubmits.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.19-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#59321 OLS-1179: lightspeed-operator: use FIPS cluster for E2E tests
  ci-operator/config/openshift/lightspeed-operator/openshift-lightspeed-operator-main.yaml
  clusters/hosted-mgmt/hive/pools/openshift-observability/ols-ocp-4-15-0-amd64-aws-us-east-1_clusterpool.yaml
  clusters/hosted-mgmt/hive/pools/openshift-observability/ols-ocp-4-16-0-amd64-aws-us-east-1_clusterpool.yaml
  clusters/hosted-mgmt/hive/pools/openshift-observability/ols-ocp-4-17-0-amd64-aws-us-east-1_clusterpool.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#59385 Add env option to overwrite kubevirt testing config file
  ci-operator/config/RedHatQE/interop-testing/RedHatQE-interop-testing-cnv-4.12__ocp-cnv-odf-4.12.yaml
  ci-operator/config/RedHatQE/interop-testing/RedHatQE-interop-testing-cnv-4.13__ocp-cnv-odf-4.13.yaml
  ci-operator/step-registry/interop-tests/cnv-tests-e2e-deploy/interop-tests-cnv-tests-e2e-deploy-commands.sh
  ci-operator/step-registry/interop-tests/cnv-tests-e2e-deploy/interop-tests-cnv-tests-e2e-deploy-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#59448 add release compatibility branches in jira config
  core-services/jira-lifecycle-plugin/config.yaml
  core-services/prow/02_config/red-hat-storage/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#59570 NO-ISSUE: Fix OSC jobs trigger
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#59548 Config pull-secret for nutanix-qe-flow profile
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#59572 update `validate-prow` as `ci-chat-bot` has changed to 'main'
  ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#59301 add cnv-odf-tests-aws-ipi-ocp418-fips
  ci-operator/config/RedHatQE/interop-testing/.config.prowgen
  ci-operator/config/RedHatQE/interop-testing/RedHatQE-interop-testing-cnv-4.18__cnv-odf-ocp4.18-lp-interop.yaml
  ci-operator/jobs/RedHatQE/interop-testing/RedHatQE-interop-testing-cnv-4.18-periodics.yaml
  ci-operator/jobs/RedHatQE/interop-testing/RedHatQE-interop-testing-cnv-4.18-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#59574 [insights-runtime-extractor] Update prow config
  core-services/prow/02_config/openshift/insights-runtime-extractor/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#59433 OCPQE-27383: skip openshift-kubernetes-e2e-kube-proxy-test on 4.17 and eariler
  ci-operator/step-registry/openshift/kubernetes/e2e/kube-proxy-test/openshift-kubernetes-e2e-kube-proxy-test-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#59553 network-flow-matrix: test main branch for release-4.19
  ci-operator/step-registry/network-flow-matrix/tests/network-flow-matrix-tests-commands.sh
Labels: lgtm, approved, rehearsals-ack

#55946 MULTIARCH-4798 enable kdump for multiarch UPI workflow
  ci-operator/step-registry/openshift/e2e/libvirt/upi/openshift-e2e-libvirt-upi-workflow.yaml
  ci-operator/step-registry/upi/conf/libvirt/upi-conf-libvirt-chain.yaml
  ci-operator/step-registry/upi/install/libvirt/upi-install-libvirt-commands.sh
Labels: lgtm, approved, rehearsals-ack

#56864 [PERFSCALE-3427] Public VLAN deployment
  ci-operator/config/redhat-performance/jetlag/redhat-performance-jetlag-main.yaml
  ci-operator/step-registry/openshift-qe/installer/bm/deploy/openshift-qe-installer-bm-deploy-commands.sh
  ci-operator/step-registry/openshift-qe/installer/bm/deploy/openshift-qe-installer-bm-deploy-ref.yaml
Labels: lgtm, approved, rehearsals-ack, network-access-rehearsals-ok

#59582 Add istio 1.24 images
  ci-operator/config/maistra/test-infra/maistra-test-infra-main.yaml
  core-services/image-mirroring/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#59579 Jetlag CI health check
  ci-operator/config/redhat-performance/jetlag/redhat-performance-jetlag-main.yaml
  ci-operator/jobs/redhat-performance/jetlag/redhat-performance-jetlag-main-presubmits.yaml
  ci-operator/step-registry/openshift-qe/cluster-health/OWNERS
  ci-operator/step-registry/openshift-qe/cluster-health/openshift-qe-cluster-health-chain.metadata.json
  ci-operator/step-registry/openshift-qe/cluster-health/openshift-qe-cluster-health-chain.yaml
  ci-operator/step-registry/openshift-qe/cluster-health/openshift-qe-cluster-health-commands.sh
  ci-operator/step-registry/openshift-qe/cluster-health/openshift-qe-cluster-health-ref.metadata.json
  ci-operator/step-registry/openshift-qe/cluster-health/openshift-qe-cluster-health-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#59585 Reduce the number of jobs executions
  ci-operator/config/openshift-kni/eco-ci-cd-public/openshift-kni-eco-ci-cd-public-main__sno-hub-ztp-4.17-latest.yaml
  ci-operator/config/openshift-kni/eco-ci-cd-public/openshift-kni-eco-ci-cd-public-main__sno-spoke-4.18-nightly.yaml
  ci-operator/jobs/openshift-kni/eco-ci-cd-public/openshift-kni-eco-ci-cd-public-main-periodics.yaml
  ci-operator/step-registry/telcov10n/sno-hub-ztp/share-hub-cluster-profile/telcov10n-sno-hub-ztp-share-hub-cluster-profile-commands.sh
Labels: lgtm, approved, rehearsals-ack

#59524 MULTIARCH-5021: Skip oauth related tests for agent runs on ppc64le
  ci-operator/step-registry/openshift/e2e/libvirt/conf/openshift-e2e-libvirt-conf-commands.sh
  ci-operator/step-registry/openshift/e2e/libvirt/conf/openshift-e2e-libvirt-conf-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#59587 Add istio jobs for 1.24
  ci-operator/config/openshift-service-mesh/istio/openshift-service-mesh-istio-release-1.24.yaml
  ci-operator/jobs/openshift-service-mesh/istio/openshift-service-mesh-istio-release-1.24-periodics.yaml
  ci-operator/jobs/openshift-service-mesh/istio/openshift-service-mesh-istio-release-1.24-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#59551 NO-JIRA: Increase aws-ovn-serial timeout to 5h
  ci-operator/config/openshift/oc/openshift-oc-release-4.18.yaml
  ci-operator/jobs/openshift/oc/openshift-oc-release-4.18-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#59588 Fix breaking changes in ci-tools
  core-services/sanitize-prow-jobs/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#59581 cloud-event-proxy: enable tide for 4.18
  core-services/prow/02_config/redhat-cne/cloud-event-proxy/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#59591 add revert for dns workaround
  clusters/build-clusters/common_managed/dns.yaml
Labels: lgtm, approved, rehearsals-ack

#59593 Fix istio 1.24 jobs
  ci-operator/config/openshift-service-mesh/istio/openshift-service-mesh-istio-release-1.24.yaml
  ci-operator/jobs/openshift-service-mesh/istio/openshift-service-mesh-istio-release-1.24-periodics.yaml
  ci-operator/jobs/openshift-service-mesh/istio/openshift-service-mesh-istio-release-1.24-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#59589 PODAUTO-284: Add VPA ci test for checking operator-sdk commands are no-ops
  ci-operator/config/openshift/vertical-pod-autoscaler-operator/openshift-vertical-pod-autoscaler-operator-master.yaml
  ci-operator/jobs/openshift/vertical-pod-autoscaler-operator/openshift-vertical-pod-autoscaler-operator-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#59594 Remove old okd jobs from installer
  ci-operator/config/openshift/installer/openshift-installer-master__okd.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.10__okd.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.11__okd.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.12__okd.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.13__okd.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.14__okd.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.15__okd.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.16__okd.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.17__okd.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.18__okd.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.19__okd.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.20__okd.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.9__okd.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-periodics.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-postsubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.10-postsubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.10-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.11-postsubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.11-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.12-postsubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.13-postsubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.13-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.14-periodics.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.14-postsubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.14-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.15-periodics.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.15-postsubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.15-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.16-periodics.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.16-postsubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.16-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.17-periodics.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.17-postsubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.17-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.18-periodics.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.18-postsubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.18-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.19-postsubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.19-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.20-postsubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.20-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.9-postsubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.9-presubmits.yaml
  core-services/image-mirroring/openshift/mapping_origin_4_10
  core-services/image-mirroring/openshift/mapping_origin_4_11
  core-services/image-mirroring/openshift/mapping_origin_4_12
  core-services/image-mirroring/openshift/mapping_origin_4_13
  core-services/image-mirroring/openshift/mapping_origin_4_14
  core-services/image-mirroring/openshift/mapping_origin_4_15
  core-services/image-mirroring/openshift/mapping_origin_4_16
  core-services/image-mirroring/openshift/mapping_origin_4_17
  core-services/image-mirroring/openshift/mapping_origin_4_18
  core-services/image-mirroring/openshift/mapping_origin_4_19
  core-services/image-mirroring/openshift/mapping_origin_4_20
  core-services/image-mirroring/openshift/mapping_origin_4_9
Labels: lgtm, approved, rehearsals-ack

#59578 hcp/openstack: use a pre-created FIP
  ci-operator/step-registry/hypershift/openstack/conformance/hypershift-openstack-conformance-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#59511 OCPQE-27400 migrate ocp-47160
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.16.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.17.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.18.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
  ci-operator/step-registry/cucushift/ota/preupgrade/cucushift-ota-preupgrade-commands.sh
Labels: lgtm, approved, rehearsals-ack

#59573 Skip host FIPS validation for command "openshift-install create permissions-policy"
  ci-operator/step-registry/ipi/conf/aws/user-min-permissions/ipi-conf-aws-user-min-permissions-commands.sh
  ci-operator/step-registry/ipi/conf/aws/user-min-permissions/ipi-conf-aws-user-min-permissions-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#58439 AWS auto case - byo KMS key
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__multi-nightly.yaml
  ci-operator/step-registry/aws/deprovision/kms-key/aws-deprovision-kms-key-commands.sh
  ci-operator/step-registry/aws/provision/kms-key/aws-provision-kms-key-commands.sh
  ci-operator/step-registry/aws/provision/kms-key/aws-provision-kms-key-ref.yaml
  ci-operator/step-registry/cucushift/installer/check/aws/byo-kms-key/OWNERS
  ci-operator/step-registry/cucushift/installer/check/aws/byo-kms-key/cucushift-installer-check-aws-byo-kms-key-commands.sh
  ci-operator/step-registry/cucushift/installer/check/aws/byo-kms-key/cucushift-installer-check-aws-byo-kms-key-ref.metadata.json
  ci-operator/step-registry/cucushift/installer/check/aws/byo-kms-key/cucushift-installer-check-aws-byo-kms-key-ref.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/byo-kms/etcd-encryption/provision/cucushift-installer-rehearse-aws-ipi-byo-kms-etcd-encryption-provision-chain.yaml
  ci-operator/step-registry/ipi/conf/aws/kms-key/ipi-conf-aws-kms-key-commands.sh
  ci-operator/step-registry/ipi/conf/aws/kms-key/ipi-conf-aws-kms-key-ref.yaml
  ci-operator/step-registry/ipi/conf/aws/user-min-permissions/ipi-conf-aws-user-min-permissions-commands.sh
Labels: lgtm, approved, rehearsals-ack

#59601 OCPERT-30 update token from new secret
  ci-operator/step-registry/release-qe-tests/release-qe-tests-commands.sh
  ci-operator/step-registry/release-qe-tests/release-qe-tests-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#59604 OCPQE-27348 - Move the AWS public-to-private test to E2E job list
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__multi-nightly.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.17.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.18.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18-periodics.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#59338 Update ODH operator to Go 1.22
  ci-operator/config/opendatahub-io/opendatahub-operator/opendatahub-io-opendatahub-operator-main.yaml
Labels: lgtm, approved, rehearsals-ack

#59580 HyperShift-QE: Enable MCE 2.7,2.8 Agent upgrade
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-nightly-4.17-upgrade-from-stable-4.16.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly-4.18-upgrade-from-stable-4.17.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#59442 OCPQE-27354: Add the CI job to cover the migration from a public cluster to private on Azure
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__multi-nightly.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.17.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.18.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18-periodics.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
  ci-operator/step-registry/azure/cluster/OWNERS
  ci-operator/step-registry/azure/cluster/public-to-private/OWNERS
  ci-operator/step-registry/azure/cluster/public-to-private/azure-cluster-public-to-private-commands.sh
  ci-operator/step-registry/azure/cluster/public-to-private/azure-cluster-public-to-private-ref.metadata.json
  ci-operator/step-registry/azure/cluster/public-to-private/azure-cluster-public-to-private-ref.yaml
  ci-operator/step-registry/azure/provision/bastionhost/azure-provision-bastionhost-commands.sh
  ci-operator/step-registry/cucushift/installer/check/azure/internal-registry/OWNERS
  ci-operator/step-registry/cucushift/installer/check/azure/internal-registry/cucushift-installer-check-azure-internal-registry-commands.sh
  ci-operator/step-registry/cucushift/installer/check/azure/internal-registry/cucushift-installer-check-azure-internal-registry-ref.metadata.json
  ci-operator/step-registry/cucushift/installer/check/azure/internal-registry/cucushift-installer-check-azure-internal-registry-ref.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/public-to-private/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/public-to-private/cucushift-installer-rehearse-azure-ipi-public-to-private-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/public-to-private/cucushift-installer-rehearse-azure-ipi-public-to-private-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/public-to-private/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/public-to-private/provision/cucushift-installer-rehearse-azure-ipi-public-to-private-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/public-to-private/provision/cucushift-installer-rehearse-azure-ipi-public-to-private-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/sharednetwork/public-to-private/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/sharednetwork/public-to-private/cucushift-installer-rehearse-azure-ipi-sharednetwork-public-to-private-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/sharednetwork/public-to-private/cucushift-installer-rehearse-azure-ipi-sharednetwork-public-to-private-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/sharednetwork/public-to-private/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/sharednetwork/public-to-private/provision/cucushift-installer-rehearse-azure-ipi-sharednetwork-public-to-private-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/sharednetwork/public-to-private/provision/cucushift-installer-rehearse-azure-ipi-sharednetwork-public-to-private-provision-chain.yaml
  ci-operator/step-registry/ipi/deprovision/deprovision/ipi-deprovision-deprovision-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#59447 [RHOAI] Update configuration to main instead master
  ci-operator/config/red-hat-data-services/kubeflow/red-hat-data-services-kubeflow-main.yaml
  ci-operator/jobs/red-hat-data-services/kubeflow/red-hat-data-services-kubeflow-main-postsubmits.yaml
  ci-operator/jobs/red-hat-data-services/kubeflow/red-hat-data-services-kubeflow-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#59597 okd-scos: Import SCOS to origin/scos-4.19:stream-coreos ImageStreamTag
  clusters/app.ci/supplemental-ci-images/okd/scos.yaml
Labels: lgtm, approved, rehearsals-ack

#59335 AGENT-1035: extend abi jobs with add-nodes workflow
  ci-operator/config/openshift-metal3/dev-scripts/openshift-metal3-dev-scripts-master.yaml
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.15.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.16.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.17.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.18.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.19.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.20.yaml
  ci-operator/config/openshift/oc/openshift-oc-master.yaml
  ci-operator/config/openshift/oc/openshift-oc-release-4.17.yaml
  ci-operator/config/openshift/oc/openshift-oc-release-4.18.yaml
  ci-operator/config/openshift/oc/openshift-oc-release-4.19.yaml
  ci-operator/config/openshift/oc/openshift-oc-release-4.20.yaml
  ci-operator/jobs/openshift-metal3/dev-scripts/openshift-metal3-dev-scripts-master-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.17-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.18-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.19-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.20-presubmits.yaml
  ci-operator/jobs/openshift/oc/openshift-oc-master-presubmits.yaml
  ci-operator/jobs/openshift/oc/openshift-oc-release-4.17-presubmits.yaml
  ci-operator/jobs/openshift/oc/openshift-oc-release-4.18-presubmits.yaml
  ci-operator/jobs/openshift/oc/openshift-oc-release-4.19-presubmits.yaml
  ci-operator/jobs/openshift/oc/openshift-oc-release-4.20-presubmits.yaml
  ci-operator/step-registry/agent/e2e/compact/ipv4/agent-e2e-compact-ipv4-workflow.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#59430 STOR-1847: Extended Windows-based SMB csi jobs
  ci-operator/config/openshift/csi-operator/openshift-csi-operator-master.yaml
  ci-operator/config/openshift/csi-operator/openshift-csi-operator-release-4.18.yaml
  ci-operator/config/openshift/csi-operator/openshift-csi-operator-release-4.19.yaml
  ci-operator/config/openshift/csi-operator/openshift-csi-operator-release-4.20.yaml
  ci-operator/jobs/openshift/csi-operator/openshift-csi-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/csi-operator/openshift-csi-operator-release-4.18-presubmits.yaml
  ci-operator/jobs/openshift/csi-operator/openshift-csi-operator-release-4.19-presubmits.yaml
  ci-operator/jobs/openshift/csi-operator/openshift-csi-operator-release-4.20-presubmits.yaml
  ci-operator/step-registry/openshift/e2e/aws/csi/smb-win/openshift-e2e-aws-csi-smb-win-workflow.yaml
  ci-operator/step-registry/storage/conf/csi-optional/smb-winserver/storage-conf-csi-optional-smb-winserver-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#59611 OCPQE-27354: Add 4.19 CI jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__multi-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#59616 MGMT-19450: Reduce OCI cleanup periodicity
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master__oci-cleanup.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#59619 Sync Serverless CI config/
  ci-operator/config/openshift-knative/client/openshift-knative-client-release-v1.16__417.yaml
  ci-operator/config/openshift-knative/client/openshift-knative-client-release-v1.16__418.yaml
  core-services/image-mirroring/knative/mapping_knative_knative-main_serverless-operator_quay
  core-services/image-mirroring/knative/mapping_knative_knative-v1.15_backstage-plugins_quay
  core-services/image-mirroring/knative/mapping_knative_knative-v1.15_client_quay
  core-services/image-mirroring/knative/mapping_knative_knative-v1.15_eventing-istio_quay
  core-services/image-mirroring/knative/mapping_knative_knative-v1.15_eventing-kafka-broker_quay
  core-services/image-mirroring/knative/mapping_knative_knative-v1.15_eventing_quay
  core-services/image-mirroring/knative/mapping_knative_knative-v1.15_kn-plugin-func_quay
  core-services/image-mirroring/knative/mapping_knative_knative-v1.15_net-istio_quay
  core-services/image-mirroring/knative/mapping_knative_knative-v1.15_net-kourier_quay
  core-services/image-mirroring/knative/mapping_knative_knative-v1.15_serving_quay
  core-services/image-mirroring/knative/mapping_knative_knative-v1.16_backstage-plugins_quay
  core-services/image-mirroring/knative/mapping_knative_knative-v1.16_client_quay
  core-services/image-mirroring/knative/mapping_knative_knative-v1.16_eventing-istio_quay
  core-services/image-mirroring/knative/mapping_knative_knative-v1.16_eventing-kafka-broker_quay
  core-services/image-mirroring/knative/mapping_knative_knative-v1.16_eventing_quay
  core-services/image-mirroring/knative/mapping_knative_knative-v1.16_kn-plugin-func_quay
  core-services/image-mirroring/knative/mapping_knative_knative-v1.16_net-istio_quay
  core-services/image-mirroring/knative/mapping_knative_knative-v1.16_net-kourier_quay
  core-services/image-mirroring/knative/mapping_knative_knative-v1.16_serving_quay
  core-services/image-mirroring/knative/mapping_knative_release-1.15_kn-plugin-event_quay
  core-services/image-mirroring/knative/mapping_knative_release-1.16_kn-plugin-event_quay
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#59624 build-definitions: disable all plugins except Jira
  core-services/prow/02_config/konflux-ci/build-definitions/_pluginconfig.yaml
Labels: lgtm, approved, needs-ok-to-test, rehearsals-ack

#59089 hcp/openstack: periodic jobs for Cinder & Manila CSI
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.18__periodics.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.19__periodics.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.18-periodics.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.19-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#59571 MULTIARCH-4696: fix copy kubeconfig to root kube folder
  ci-operator/step-registry/upi/install/powervs/cluster/upi-install-powervs-cluster-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#59309 RHDH release 1.4 ci jobs setup
  ci-operator/config/janus-idp/backstage-showcase/janus-idp-backstage-showcase-release-1.4.yaml
  ci-operator/jobs/janus-idp/backstage-showcase/janus-idp-backstage-showcase-release-1.4-periodics.yaml
  ci-operator/jobs/janus-idp/backstage-showcase/janus-idp-backstage-showcase-release-1.4-presubmits.yaml
  ci-operator/step-registry/janus-idp/backstage-showcase/release-1.4/OWNERS
  ci-operator/step-registry/janus-idp/backstage-showcase/release-1.4/janus-idp-backstage-showcase-release-1.4-commands.sh
  ci-operator/step-registry/janus-idp/backstage-showcase/release-1.4/janus-idp-backstage-showcase-release-1.4-ref.metadata.json
  ci-operator/step-registry/janus-idp/backstage-showcase/release-1.4/janus-idp-backstage-showcase-release-1.4-ref.yaml
  ci-operator/step-registry/janus-idp/backstage-showcase/release-1.4/nightly/OWNERS
  ci-operator/step-registry/janus-idp/backstage-showcase/release-1.4/nightly/janus-idp-backstage-showcase-release-1.4-nightly-commands.sh
  ci-operator/step-registry/janus-idp/backstage-showcase/release-1.4/nightly/janus-idp-backstage-showcase-release-1.4-nightly-ref.metadata.json
  ci-operator/step-registry/janus-idp/backstage-showcase/release-1.4/nightly/janus-idp-backstage-showcase-release-1.4-nightly-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#59409 GCP-OVN-FIPS-EtcdEncrypt control-plane - 120 nodes
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__gcp-4.18-nightly-x86.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#59598 hcp/openstack: rename OSP jobs when running on AWS mgt cluster
  ci-operator/config/openshift-priv/cluster-storage-operator/openshift-priv-cluster-storage-operator-master.yaml
  ci-operator/config/openshift-priv/cluster-storage-operator/openshift-priv-cluster-storage-operator-release-4.18.yaml
  ci-operator/config/openshift-priv/cluster-storage-operator/openshift-priv-cluster-storage-operator-release-4.19.yaml
  ci-operator/config/openshift-priv/cluster-storage-operator/openshift-priv-cluster-storage-operator-release-4.20.yaml
  ci-operator/config/openshift-priv/csi-operator/openshift-priv-csi-operator-master.yaml
  ci-operator/config/openshift-priv/csi-operator/openshift-priv-csi-operator-release-4.18.yaml
  ci-operator/config/openshift-priv/csi-operator/openshift-priv-csi-operator-release-4.19.yaml
  ci-operator/config/openshift-priv/csi-operator/openshift-priv-csi-operator-release-4.20.yaml
  ci-operator/config/openshift-priv/hypershift/openshift-priv-hypershift-main.yaml
  ci-operator/config/openshift-priv/hypershift/openshift-priv-hypershift-release-4.18.yaml
  ci-operator/config/openshift-priv/hypershift/openshift-priv-hypershift-release-4.19.yaml
  ci-operator/config/openshift-priv/hypershift/openshift-priv-hypershift-release-4.20.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-master.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.18.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.19.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.20.yaml
  ci-operator/config/openshift/csi-operator/openshift-csi-operator-master.yaml
  ci-operator/config/openshift/csi-operator/openshift-csi-operator-release-4.18.yaml
  ci-operator/config/openshift/csi-operator/openshift-csi-operator-release-4.19.yaml
  ci-operator/config/openshift/csi-operator/openshift-csi-operator-release-4.20.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-main.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.18.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.18__periodics.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.19.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.19__periodics.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.20.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.18-presubmits.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.19-presubmits.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.20-presubmits.yaml
  ci-operator/jobs/openshift/csi-operator/openshift-csi-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/csi-operator/openshift-csi-operator-release-4.18-presubmits.yaml
  ci-operator/jobs/openshift/csi-operator/openshift-csi-operator-release-4.19-presubmits.yaml
  ci-operator/jobs/openshift/csi-operator/openshift-csi-operator-release-4.20-presubmits.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-main-presubmits.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.18-periodics.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.18-presubmits.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.19-periodics.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.19-presubmits.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.20-presubmits.yaml
  ci-operator/step-registry/hypershift/openstack/aws/OWNERS
  ci-operator/step-registry/hypershift/openstack/aws/conformance/OWNERS
  ci-operator/step-registry/hypershift/openstack/aws/conformance/hypershift-openstack-aws-conformance-workflow.metadata.json
  ci-operator/step-registry/hypershift/openstack/aws/conformance/hypershift-openstack-aws-conformance-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#59520 RHOAIENG-11274: chore(odh/notebooks): widen the container build context to the whole repo, so we can start reusing code between images in the future
  ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-main.yaml
Labels: lgtm, approved, tide/merge-method-squash, rehearsals-ack, jira/valid-reference

#59470 [hypershift/kubevirt] Unblock CI: don't patch scheduler on nested-mgmt
  ci-operator/step-registry/hypershift/kubevirt/baremetalds/odf/hypershift-kubevirt-baremetalds-odf-commands.sh
  ci-operator/step-registry/hypershift/kubevirt/e2e-nested/hypershift-kubevirt-e2e-nested-workflow.yaml
  ci-operator/step-registry/hypershift/kubevirt/install/disconnected/hypershift-kubevirt-install-disconnected-commands.sh
  ci-operator/step-registry/hypershift/kubevirt/install/hypershift-kubevirt-install-commands.sh
  ci-operator/step-registry/hypershift/kubevirt/install/odf/hypershift-kubevirt-install-odf-commands.sh
Labels: lgtm, approved, rehearsals-ack

#59631 NO-JIRA: add ovn-k resource watch
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-master.yaml
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-release-4.19.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#59633 Update paramters for aggregated timeout
  clusters/app.ci/job-trigger-controller-manager/job-trigger-controller-manager_deploy.yaml
Labels: lgtm, approved, rehearsals-ack

#59632 NO-ISSUE: Make OSC jobs optional
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#59641 MGMT-19454: Add 'OPENSHIFT_VERSION' configuration to all assisted-installer test-infra jobs
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-main__edge.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master__edge.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-master__edge.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-cloud_hotfix_releases.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.10.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.11.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.12.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.9.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-main-presubmits.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master-presubmits.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-master-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-cloud_hotfix_releases-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-periodics.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-periodics.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-presubmits.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.10-periodics.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.10-presubmits.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.11-periodics.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.11-presubmits.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.12-periodics.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.12-presubmits.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.9-periodics.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.9-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#59640 [KMM] Adding `ubi-minimal:9.5` substitution in the signimage.
  ci-operator/config/rh-ecosystem-edge/kernel-module-management/rh-ecosystem-edge-kernel-module-management-main.yaml
Labels: lgtm, approved, rehearsals-ack

#59230 Adding new e2e CI Tests
  ci-operator/config/cloud-bulldozer/e2e-benchmarking/cloud-bulldozer-e2e-benchmarking-master.yaml
  ci-operator/jobs/cloud-bulldozer/e2e-benchmarking/cloud-bulldozer-e2e-benchmarking-master-presubmits.yaml
  ci-operator/step-registry/cloud-bulldozer/e2e-benchmarking/udn-density-pods/OWNERS
  ci-operator/step-registry/cloud-bulldozer/e2e-benchmarking/udn-density-pods/cloud-bulldozer-e2e-benchmarking-udn-density-pods-commands.sh
  ci-operator/step-registry/cloud-bulldozer/e2e-benchmarking/udn-density-pods/cloud-bulldozer-e2e-benchmarking-udn-density-pods-ref.metadata.json
  ci-operator/step-registry/cloud-bulldozer/e2e-benchmarking/udn-density-pods/cloud-bulldozer-e2e-benchmarking-udn-density-pods-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#59603 Fix mini-perm issue on Shared-VPC cluster
  ci-operator/step-registry/aws/provision/iam-user/aws-provision-iam-user-commands.sh
  ci-operator/step-registry/aws/provision/route53/private-hosted-zone/associate-diff-vpc/aws-provision-route53-private-hosted-zone-associate-diff-vpc-commands.sh
  ci-operator/step-registry/aws/provision/route53/private-hosted-zone/aws-provision-route53-private-hosted-zone-commands.sh
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/private/shared-vpc-phz/sts/provision/cucushift-installer-rehearse-aws-ipi-private-shared-vpc-phz-sts-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/shared-phz/provision/cucushift-installer-rehearse-aws-ipi-shared-phz-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/shared-phz/sts/provision/cucushift-installer-rehearse-aws-ipi-shared-phz-sts-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/shared-vpc-phz/provision/cucushift-installer-rehearse-aws-ipi-shared-vpc-phz-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/shared-vpc-phz/sts/provision/cucushift-installer-rehearse-aws-ipi-shared-vpc-phz-sts-provision-chain.yaml
  ci-operator/step-registry/ipi/conf/aws/shared-vpc-phz-finalize/OWNERS
  ci-operator/step-registry/ipi/conf/aws/shared-vpc-phz-finalize/ipi-conf-aws-shared-vpc-phz-finalize-commands.sh
  ci-operator/step-registry/ipi/conf/aws/shared-vpc-phz-finalize/ipi-conf-aws-shared-vpc-phz-finalize-ref.metadata.json
  ci-operator/step-registry/ipi/conf/aws/shared-vpc-phz-finalize/ipi-conf-aws-shared-vpc-phz-finalize-ref.yaml
  ci-operator/step-registry/ipi/conf/aws/user-min-permissions/ipi-conf-aws-user-min-permissions-commands.sh
Labels: lgtm, approved, rehearsals-ack
