Repository openshift/release, pull requests merged in 2024-05, with the labels that each got.

#51015 OCPQE-20784: Upgrade implementation Compact Hosted Control Plane
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly-4.15-upgrade-from-stable-4.14.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/baremetalds/assisted/hypershift-agent/mce/guest/cucushift-installer-rehearse-baremetalds-assisted-hypershift-agent-mce-guest-workflow.yaml
  ci-operator/step-registry/cucushift/upgrade/toimage/cucushift-upgrade-toimage-commands.sh
  ci-operator/step-registry/hypershift/mce/upgrade/hypershift-mce-upgrade-commands.sh
  ci-operator/step-registry/openshift/upgrade/qe/test/hypershift/full/OWNERS
  ci-operator/step-registry/openshift/upgrade/qe/test/hypershift/full/openshift-upgrade-qe-test-hypershift-full-chain.metadata.json
  ci-operator/step-registry/openshift/upgrade/qe/test/hypershift/full/openshift-upgrade-qe-test-hypershift-full-chain.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#51513 update to use go1.21 and set to readonly mod
  ci-operator/config/openshift/kube-compare/openshift-kube-compare-main.yaml
Labels: lgtm, approved, rehearsals-ack

#51544 OCPBUGS-33152: fix: use upi-installer image for sno config update
  ci-operator/step-registry/single-node/conf/aws/single-node-conf-aws-ref.yaml
  ci-operator/step-registry/single-node/conf/azure/single-node-conf-azure-ref.yaml
  ci-operator/step-registry/single-node/conf/gcp/single-node-conf-gcp-ref.yaml
Labels: lgtm, approved, jira/severity-critical, jira/valid-bug, rehearsals-ack, jira/valid-reference

#51546 NO-ISSUE: Change the image used for conformance tests to openshift-tests-415
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-main__edge.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master__edge.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-master__edge.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-cloud_hotfix_releases.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
  ci-operator/step-registry/assisted/baremetal/conf/assisted-baremetal-conf-ref.yaml
  ci-operator/step-registry/assisted/baremetal/test/assisted-baremetal-test-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#51549 SDCICD-1287: promote main to 4.16+
  ci-operator/config/openshift/managed-release-bundle-osd/openshift-managed-release-bundle-osd-main.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#51504 Exclude metal-ipi upgrade jobs from using ESI
  ci-operator/step-registry/ofcir/acquire/ofcir-acquire-commands.sh
Labels: lgtm, approved, rehearsals-ack

#51552 SDCICD-1287: set up jobs for older branches
  ci-operator/config/openshift/managed-release-bundle-osd/openshift-managed-release-bundle-osd-release-4.12.yaml
  ci-operator/config/openshift/managed-release-bundle-osd/openshift-managed-release-bundle-osd-release-4.13.yaml
  ci-operator/config/openshift/managed-release-bundle-osd/openshift-managed-release-bundle-osd-release-4.14.yaml
  ci-operator/config/openshift/managed-release-bundle-osd/openshift-managed-release-bundle-osd-release-4.15.yaml
  ci-operator/jobs/openshift/managed-release-bundle-osd/openshift-managed-release-bundle-osd-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift/managed-release-bundle-osd/openshift-managed-release-bundle-osd-release-4.13-presubmits.yaml
  ci-operator/jobs/openshift/managed-release-bundle-osd/openshift-managed-release-bundle-osd-release-4.14-presubmits.yaml
  ci-operator/jobs/openshift/managed-release-bundle-osd/openshift-managed-release-bundle-osd-release-4.15-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#51551 NO-ISSUE: Change openshift-tests image name to 'tests'
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-main__edge.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master__edge.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-master__edge.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-cloud_hotfix_releases.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
  ci-operator/step-registry/assisted/baremetal/conf/assisted-baremetal-conf-ref.yaml
  ci-operator/step-registry/assisted/baremetal/test/assisted-baremetal-test-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#51522 Update Backporters for Build Repositories
  core-services/prow/02_config/openshift/builder/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-openshift-controller-manager-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/csi-driver-shared-resource-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/csi-driver-shared-resource/_pluginconfig.yaml
  core-services/prow/02_config/openshift/jenkins-client-plugin/_pluginconfig.yaml
  core-services/prow/02_config/openshift/jenkins-openshift-login-plugin/_pluginconfig.yaml
  core-services/prow/02_config/openshift/jenkins-plugin/_pluginconfig.yaml
  core-services/prow/02_config/openshift/jenkins-sync-plugin/_pluginconfig.yaml
  core-services/prow/02_config/openshift/jenkins/_pluginconfig.yaml
  core-services/prow/02_config/openshift/openshift-apiserver/_pluginconfig.yaml
  core-services/prow/02_config/openshift/openshift-controller-manager/_pluginconfig.yaml
  core-services/prow/02_config/openshift/origin/_pluginconfig.yaml
  core-services/prow/02_config/openshift/route-controller-manager/_pluginconfig.yaml
  core-services/prow/02_config/openshift/source-to-image/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#51476 Update periodic compliance jobs to use job-release label
  ci-operator/config/ComplianceAsCode/content/ComplianceAsCode-content-master__4.13.yaml
  ci-operator/config/ComplianceAsCode/content/ComplianceAsCode-content-master__4.14.yaml
  ci-operator/config/ComplianceAsCode/content/ComplianceAsCode-content-master__4.15.yaml
  ci-operator/config/ComplianceAsCode/content/ComplianceAsCode-content-master__4.16.yaml
  ci-operator/jobs/ComplianceAsCode/content/ComplianceAsCode-content-master-periodics.yaml
  ci-operator/jobs/ComplianceAsCode/content/ComplianceAsCode-content-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#51565 SPLAT-1583: api/ingress records should target IBM LB cname
  ci-operator/step-registry/ipi/conf/vsphere/dns/ipi-conf-vsphere-dns-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#51563 OCPBUGS-33100: CCO 4.16 periodics to use rhel9 base
  ci-operator/config/openshift/cloud-credential-operator/openshift-cloud-credential-operator-release-4.16__periodics.yaml
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, rehearsals-ack, jira/valid-reference

#51570 Cancel e2e test if new PR is pushed up and e2e for that PR is running
  ci-operator/step-registry/dpu-operator/e2e-tests-workflow/tests/dpu-operator-e2e-tests-workflow-tests-commands.sh
Labels: lgtm, approved, rehearsals-ack

#51562 OCPBUGS-33162: fix: update step images to use upi-installer
  ci-operator/step-registry/ipi/install/install/ipi-install-install-ref.yaml
  ci-operator/step-registry/openshift/manifests/external/openshift-manifests-external-ref.yaml
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, rehearsals-ack, jira/valid-reference

#51503 OLS-506: openshift-lightspeed: Remove redundant OLS CI tests
  ci-operator/config/openshift/lightspeed-service/openshift-lightspeed-service-main.yaml
  ci-operator/jobs/openshift/lightspeed-service/openshift-lightspeed-service-main-periodics.yaml
  ci-operator/jobs/openshift/lightspeed-service/openshift-lightspeed-service-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#51558 USHIFT-3124: Update RHEL-9.4 AMIs to GA image from beta images
  ci-operator/step-registry/openshift/microshift/infra/aws/ec2/openshift-microshift-infra-aws-ec2-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#50746 MULTIARCH-4593: Enable Loki arm64 builds
  ci-operator/config/openshift/loki/.config.prowgen
  ci-operator/config/openshift/loki/openshift-loki-main.yaml
  ci-operator/config/openshift/loki/openshift-loki-release-5.6.yaml
  ci-operator/config/openshift/loki/openshift-loki-release-5.7.yaml
  ci-operator/config/openshift/loki/openshift-loki-release-5.8.yaml
  ci-operator/config/openshift/loki/openshift-loki-release-5.9.yaml
  ci-operator/config/openshift/loki/openshift-loki-upstream-v2.9.2.yaml
  ci-operator/config/openshift/loki/openshift-loki-upstream-v2.9.3.yaml
  ci-operator/config/openshift/loki/openshift-loki-upstream-v2.9.4.yaml
  ci-operator/config/openshift/loki/openshift-loki-upstream-v2.9.6.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-main-postsubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-main-presubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-release-5.6-postsubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-release-5.6-presubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-release-5.7-postsubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-release-5.7-presubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-release-5.8-postsubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-release-5.8-presubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-release-5.9-postsubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-release-5.9-presubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-upstream-v2.9.2-postsubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-upstream-v2.9.2-presubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-upstream-v2.9.3-postsubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-upstream-v2.9.3-presubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-upstream-v2.9.4-postsubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-upstream-v2.9.4-presubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-upstream-v2.9.6-postsubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-upstream-v2.9.6-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#51581 HCO: temporary stop okd lanes, as okd is currently broken
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-main__okd.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#51578 WRKLDS-1251: Remove temporarily must-gather-base image from oc presubmits
  ci-operator/config/openshift/oc/openshift-oc-master.yaml
  ci-operator/config/openshift/oc/openshift-oc-release-4.16.yaml
  ci-operator/config/openshift/oc/openshift-oc-release-4.17.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#51447 OCM-7748 | ci: Setup RHCS_URL for TF RHCS jobs
  ci-operator/config/terraform-redhat/terraform-provider-rhcs/terraform-redhat-terraform-provider-rhcs-main.yaml
  ci-operator/config/terraform-redhat/terraform-provider-rhcs/terraform-redhat-terraform-provider-rhcs-v1.4.0-branch.yaml
  ci-operator/config/terraform-redhat/terraform-provider-rhcs/terraform-redhat-terraform-provider-rhcs-v1.5.0-branch.yaml
  ci-operator/step-registry/rhcs/e2e/general-tests/rhcs-e2e-general-tests-commands.sh
  ci-operator/step-registry/rhcs/e2e/general-tests/rhcs-e2e-general-tests-ref.yaml
  ci-operator/step-registry/rhcs/e2e/setup/rhcs-e2e-setup-commands.sh
  ci-operator/step-registry/rhcs/e2e/setup/rhcs-e2e-setup-ref.yaml
  ci-operator/step-registry/rhcs/e2e/teardown/rhcs-e2e-teardown-commands.sh
  ci-operator/step-registry/rhcs/e2e/teardown/rhcs-e2e-teardown-ref.yaml
  ci-operator/step-registry/rhcs/e2e/tests/rhcs-e2e-tests-commands.sh
  ci-operator/step-registry/rhcs/e2e/tests/rhcs-e2e-tests-ref.yaml
  ci-operator/step-registry/rosa/terraform/OWNERS
  ci-operator/step-registry/rosa/terraform/e2e/OWNERS
  ci-operator/step-registry/rosa/terraform/e2e/setup/OWNERS
  ci-operator/step-registry/rosa/terraform/e2e/setup/rosa-terraform-e2e-setup-commands.sh
  ci-operator/step-registry/rosa/terraform/e2e/setup/rosa-terraform-e2e-setup-ref.metadata.json
  ci-operator/step-registry/rosa/terraform/e2e/setup/rosa-terraform-e2e-setup-ref.yaml
  ci-operator/step-registry/rosa/terraform/e2e/teardown/OWNERS
  ci-operator/step-registry/rosa/terraform/e2e/teardown/rosa-terraform-e2e-teardown-commands.sh
  ci-operator/step-registry/rosa/terraform/e2e/teardown/rosa-terraform-e2e-teardown-ref.metadata.json
  ci-operator/step-registry/rosa/terraform/e2e/teardown/rosa-terraform-e2e-teardown-ref.yaml
  ci-operator/step-registry/rosa/terraform/e2e/tests/OWNERS
  ci-operator/step-registry/rosa/terraform/e2e/tests/upload-polarion/OWNERS
  ci-operator/step-registry/rosa/terraform/e2e/tests/upload-polarion/rosa-terraform-e2e-tests-upload-polarion-commands.sh
  ci-operator/step-registry/rosa/terraform/e2e/tests/upload-polarion/rosa-terraform-e2e-tests-upload-polarion-ref.metadata.json
  ci-operator/step-registry/rosa/terraform/e2e/tests/upload-polarion/rosa-terraform-e2e-tests-upload-polarion-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#51584 NO-JIRA: HCO: add tests for version 1.12
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-1.12.yaml
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-release-1.12-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#51408 Service Interconnect zstream onboarding on ibmcloud
  ci-operator/config/skupperproject/skupper-openshift-smoke-test-image/skupperproject-skupper-openshift-smoke-test-image-main__service-interconnect-ocp4.14-lp-interop.yaml
  ci-operator/config/skupperproject/skupper-openshift-smoke-test-image/skupperproject-skupper-openshift-smoke-test-image-main__service-interconnect-ocp4.15-lp-interop.yaml
  ci-operator/jobs/skupperproject/skupper-openshift-smoke-test-image/skupperproject-skupper-openshift-smoke-test-image-main-periodics.yaml
  ci-operator/jobs/skupperproject/skupper-openshift-smoke-test-image/skupperproject-skupper-openshift-smoke-test-image-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#51555 Devspaces zstream onboarding on ibmcloud
  ci-operator/config/redhat-developer/devspaces-interop-tests/redhat-developer-devspaces-interop-tests-main__devspaces-ocp4.14-lp-interop.yaml
  ci-operator/config/redhat-developer/devspaces-interop-tests/redhat-developer-devspaces-interop-tests-main__devspaces-ocp4.15-lp-interop.yaml
  ci-operator/jobs/redhat-developer/devspaces-interop-tests/redhat-developer-devspaces-interop-tests-main-periodics.yaml
  ci-operator/jobs/redhat-developer/devspaces-interop-tests/redhat-developer-devspaces-interop-tests-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#51498 Update version of AMQ Streams 2.6.0 and remove unused files
  ci-operator/config/amq-streams-qe/strimzi-kafka-operator/amq-streams-qe-strimzi-kafka-operator-main__amq-streams-ocp4.14-lp-interop.yaml
  ci-operator/config/amq-streams-qe/strimzi-kafka-operator/amq-streams-qe-strimzi-kafka-operator-main__amq-streams-ocp4.14-lp-rosa-classic.yaml
  ci-operator/config/amq-streams-qe/strimzi-kafka-operator/amq-streams-qe-strimzi-kafka-operator-main__amq-streams-ocp4.15-lp-interop.yaml
  ci-operator/config/amq-streams-qe/strimzi-kafka-operator/amq-streams-qe-strimzi-kafka-operator-main__amq-streams-ocp4.16-lp-interop.yaml
  ci-operator/jobs/amq-streams-qe/strimzi-kafka-operator/amq-streams-qe-strimzi-kafka-operator-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#51591 Update cron for e2e-powervs for 4.16 and 4.17 release jobs
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.16__periodics.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.17__periodics.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.16-periodics.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.17-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#51590 TRT-1639: revert: changing back to installer image
  ci-operator/step-registry/ipi/install/install/ipi-install-install-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#51593 [openshift-psap/topsail] Update ocp version to 4.15
  ci-operator/config/openshift-psap/topsail/openshift-psap-topsail-main__rhoai.yaml
Labels: lgtm, approved, rehearsals-ack

#51595 NOJIRA: fix: fixing the grep so 4.17 isn't pulled in from CI
  ci-operator/step-registry/openshift/image-based/upgrade/seed/create/openshift-image-based-upgrade-seed-create-commands.sh
Labels: lgtm, approved, rehearsals-ack

#51569 Adding Jira assignee to firewatch config
  ci-operator/config/jboss-eap-qe/openshift-eap-tests/jboss-eap-qe-openshift-eap-tests-pit-7.4.x__eap-ocp4.16-lp-interop.yaml
Labels: lgtm, approved, rehearsals-ack

#51358 enable Go units tests in openshift/images (release 4.15)
  ci-operator/config/openshift/images/openshift-images-release-4.15.yaml
  ci-operator/jobs/openshift/images/openshift-images-release-4.15-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#50754 OCM-7095 Enable rosa-hcp presubmit jobs
  ci-operator/config/terraform-redhat/terraform-provider-rhcs/terraform-redhat-terraform-provider-rhcs-main.yaml
  ci-operator/jobs/terraform-redhat/terraform-provider-rhcs/terraform-redhat-terraform-provider-rhcs-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#51589 Fix code to get IP's of nodes during ds-gather
  ci-operator/step-registry/baremetalds/devscripts/gather/baremetalds-devscripts-gather-commands.sh
Labels: lgtm, approved, rehearsals-ack

#51270 [INTEROP-7365] Update ACM config for 2.10.
  ci-operator/config/stolostron/acmqe-autotest/stolostron-acmqe-autotest-main__acm-ocp4.16-lp-interop.yaml
  ci-operator/step-registry/mce/must-gather/mce-must-gather-commands.sh
Labels: lgtm, approved, rehearsals-ack

#51510 chore: update stackrox Go version to 1.21.9
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-12.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-14-lp-interop.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-15-lp-interop.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-15.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-16-lp-interop.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-preview.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-stable-scanner-v4.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies__ocp-4-12.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies__ocp-4-15.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-x.y.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-x.y__ocp-4-12.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-x.y__ocp-4-15.yaml
Labels: lgtm, approved, rehearsals-ack

#51596 HCO: temporary stop okd lanes, as okd is currently broken
  ci-operator/jobs/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#51611 [HyperShift-MCE]: fix MCE 2.3 CI failing
  ci-operator/step-registry/hypershift/kubevirt/create/hypershift-kubevirt-create-commands.sh
  ci-operator/step-registry/hypershift/mce/dump/hypershift-mce-dump-commands.sh
Labels: lgtm, approved, rehearsals-ack

#51246 [MTO] Move tests on build10, Skip tests when non needed, add post-submit
  ci-operator/config/openshift/multiarch-tuning-operator/openshift-multiarch-tuning-operator-main.yaml
  ci-operator/jobs/openshift/multiarch-tuning-operator/openshift-multiarch-tuning-operator-main-postsubmits.yaml
  ci-operator/jobs/openshift/multiarch-tuning-operator/openshift-multiarch-tuning-operator-main-presubmits.yaml
  ci-operator/step-registry/openshift/ci-security/snyk/scan/openshift-ci-security-snyk-scan-commands.sh
Labels: lgtm, approved, rehearsals-ack

#51619 config-resolver: use a dedicated sa
  clusters/app.ci/ci-operator-configresolver/ci-operator-configresolver.yaml
Labels: lgtm, approved, rehearsals-ack

#51588 [openshift/jenkins-sync-plugin] Update _prowconfig.yaml
  core-services/prow/02_config/openshift/jenkins-sync-plugin/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#51523 feat: add jobs for PowerMon Operator for tech-preview-0.2 branch
  ci-operator/config/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-tech-preview-0.2__tech-preview-0.2-ocp4.14-periodic.yaml
  ci-operator/config/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-tech-preview-0.2__tech-preview-0.2-ocp4.15-periodic.yaml
  ci-operator/jobs/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-tech-preview-0.2-periodics.yaml
  ci-operator/jobs/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-tech-preview-0.2-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#51632 Require jira/valid-reference for Jenkins Plugins
  core-services/prow/02_config/openshift/jenkins-client-plugin/_prowconfig.yaml
  core-services/prow/02_config/openshift/jenkins-openshift-login-plugin/_prowconfig.yaml
  core-services/prow/02_config/openshift/jenkins-plugin/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#51616 Remove janus-idp/showcase-e2e repository
  ci-operator/config/janus-idp/showcase-e2e/OWNERS
  ci-operator/config/janus-idp/showcase-e2e/janus-idp-showcase-e2e-main__v4.13.yaml
  ci-operator/jobs/janus-idp/showcase-e2e/OWNERS
  ci-operator/jobs/janus-idp/showcase-e2e/janus-idp-showcase-e2e-main-periodics.yaml
  ci-operator/jobs/janus-idp/showcase-e2e/janus-idp-showcase-e2e-main-presubmits.yaml
  ci-operator/step-registry/cluster-profiles/cluster-profiles-config.yaml
  core-services/prow/02_config/janus-idp/showcase-e2e/OWNERS
  core-services/prow/02_config/janus-idp/showcase-e2e/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#51600 cluster-logging-operator: Address go1.21.9 e2e issues
  ci-operator/config/openshift/cluster-logging-operator/openshift-cluster-logging-operator-release-5.6.yaml
  ci-operator/config/openshift/cluster-logging-operator/openshift-cluster-logging-operator-release-5.7.yaml
  ci-operator/config/openshift/cluster-logging-operator/openshift-cluster-logging-operator-release-5.8.yaml
Labels: lgtm, approved, rehearsals-ack

#51603 NO-ISSUE: setup mirroring to new openshift-lightspeed quay org
  ci-operator/jobs/infra-image-mirroring.yaml
  core-services/image-mirroring/openshift-lightspeed/OWNERS
  core-services/image-mirroring/openshift-lightspeed/mapping_openshift_lightspeed
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#51622 Add podman to dpu-operator image used for testing
  ci-operator/config/openshift/dpu-operator/openshift-dpu-operator-main.yaml
Labels: lgtm, approved, rehearsals-ack

#51553 MULTIARCH-4516: add logging and bump the openshift-installer-power version
  ci-operator/step-registry/upi/install/powervs/cluster/upi-install-powervs-cluster-commands.sh
  ci-operator/step-registry/upi/install/powervs/cluster/upi-install-powervs-cluster-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#51556 Helm zstream onboarding on ibmcloud
  ci-operator/config/redhat-developer/helm/redhat-developer-helm-release-3.11__helm-ocp4.14-lp-interop.yaml
  ci-operator/config/redhat-developer/helm/redhat-developer-helm-release-3.11__helm-ocp4.15-lp-interop.yaml
  ci-operator/jobs/redhat-developer/helm/redhat-developer-helm-release-3.11-periodics.yaml
  ci-operator/jobs/redhat-developer/helm/redhat-developer-helm-release-3.11-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#51634 GitOps | Disable cluster pool
  clusters/hive/pools/gitops/gitops-ocp-4-12-0-amd64-aws-us-east-2_clusterpool.yaml
  clusters/hive/pools/gitops/gitops-ocp-4-14-0-amd64-aws-us-east-2_clusterpool.yaml
  clusters/hive/pools/gitops/gitops-ocp-4-15-0-amd64-aws-us-east-2_clusterpool.yaml
  clusters/hosted-mgmt/hive/pools/gitops/gitops-ocp-4-14-0-amd64-aws-us-east-2_clusterpool.yaml
  clusters/hosted-mgmt/hive/pools/gitops/gitops-ocp-4-15-0-amd64-aws-us-east-2_clusterpool.yaml
Labels: lgtm, approved, rehearsals-ack

#51223 Krkn upgrade
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__4.16-nightly-upgrade.yaml
  ci-operator/jobs/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main-periodics.yaml
  ci-operator/jobs/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main-presubmits.yaml
  ci-operator/step-registry/redhat-chaos/krkn-hub-tests/redhat-chaos-krkn-hub-tests-chain.yaml
  ci-operator/step-registry/redhat-chaos/pod-scenarios/etcd-disruption/redhat-chaos-pod-scenarios-etcd-disruption-commands.sh
  ci-operator/step-registry/redhat-chaos/pod-scenarios/random-system-pods/observer/OWNERS
  ci-operator/step-registry/redhat-chaos/pod-scenarios/random-system-pods/observer/redhat-chaos-pod-scenarios-random-system-pods-observer-commands.sh
  ci-operator/step-registry/redhat-chaos/pod-scenarios/random-system-pods/observer/redhat-chaos-pod-scenarios-random-system-pods-observer-observer.metadata.json
  ci-operator/step-registry/redhat-chaos/pod-scenarios/random-system-pods/observer/redhat-chaos-pod-scenarios-random-system-pods-observer-observer.yaml
  ci-operator/step-registry/redhat-chaos/start-krkn/OWNERS
  ci-operator/step-registry/redhat-chaos/start-krkn/redhat-chaos-start-krkn-commands.sh
  ci-operator/step-registry/redhat-chaos/start-krkn/redhat-chaos-start-krkn-ref.metadata.json
  ci-operator/step-registry/redhat-chaos/start-krkn/redhat-chaos-start-krkn-ref.yaml
  ci-operator/step-registry/redhat-chaos/start-krkn/redhat-chaos-start-krkn-workflow.metadata.json
  ci-operator/step-registry/redhat-chaos/start-krkn/redhat-chaos-start-krkn-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#51638 NO-ISSUE: fix ols image push secret name
  ci-operator/jobs/infra-image-mirroring.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#51629 NO-ISSUE: Workaround conformance tests in assisted
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.10.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.7.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.8.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.9.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#50740 SDN-4313: Add e2e-aws-ipsec-upgrade CI lane
  ci-operator/config/openshift-priv/cluster-network-operator/openshift-priv-cluster-network-operator-master.yaml
  ci-operator/config/openshift-priv/cluster-network-operator/openshift-priv-cluster-network-operator-release-4.16.yaml
  ci-operator/config/openshift-priv/cluster-network-operator/openshift-priv-cluster-network-operator-release-4.17.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__azure-4.15-nightly-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__azure-4.16-nightly-x86.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-master.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.16.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.17.yaml
  ci-operator/jobs/openshift-priv/cluster-network-operator/openshift-priv-cluster-network-operator-master-presubmits.yaml
  ci-operator/jobs/openshift-priv/cluster-network-operator/openshift-priv-cluster-network-operator-release-4.16-presubmits.yaml
  ci-operator/jobs/openshift-priv/cluster-network-operator/openshift-priv-cluster-network-operator-release-4.17-presubmits.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-presubmits.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.16-presubmits.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.17-presubmits.yaml
  ci-operator/step-registry/openshift/e2e/aws/ovn/ipsec-upgrade/OWNERS
  ci-operator/step-registry/openshift/e2e/aws/ovn/ipsec-upgrade/openshift-e2e-aws-ovn-ipsec-upgrade-workflow.metadata.json
  ci-operator/step-registry/openshift/e2e/aws/ovn/ipsec-upgrade/openshift-e2e-aws-ovn-ipsec-upgrade-workflow.yaml
  ci-operator/step-registry/ovn/conf/ipsec-manifest/ovn-conf-ipsec-manifest-commands.sh
  ci-operator/step-registry/ovn/conf/ipsec-manifest/ovn-conf-ipsec-manifest-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#51495 add build root
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__write_jobs_to_gsheet.yaml
Labels: lgtm, approved, rehearsals-ack

#46695 Adding rhel and rchos hybrid worker installer
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.15-nightly-x86.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-presubmits.yaml
  ci-operator/step-registry/openshift-qe/installer/aws/hybrid-nodes/OWNERS
  ci-operator/step-registry/openshift-qe/installer/aws/hybrid-nodes/openshift-qe-installer-aws-hybrid-nodes-workflow.metadata.json
  ci-operator/step-registry/openshift-qe/installer/aws/hybrid-nodes/openshift-qe-installer-aws-hybrid-nodes-workflow.yaml
  ci-operator/step-registry/openshift-qe/workers-infra-workload/openshift-qe-workers-infra-workload-commands.sh
  ci-operator/step-registry/workers-scale/workers-scale-commands.sh
Labels: lgtm, approved, rehearsals-ack

#51255 OCPEDGE-996: IBU e2e serial conformance test
  ci-operator/config/openshift-kni/lifecycle-agent/openshift-kni-lifecycle-agent-main__nightly-4.15.yaml
  ci-operator/config/openshift-kni/lifecycle-agent/openshift-kni-lifecycle-agent-main__nightly-4.16.yaml
  ci-operator/jobs/openshift-kni/lifecycle-agent/openshift-kni-lifecycle-agent-main-periodics.yaml
  ci-operator/step-registry/openshift/image-based/infra/aws/ec2/openshift-image-based-infra-aws-ec2-ref.yaml
  ci-operator/step-registry/openshift/image-based/upgrade/e2e/OWNERS
  ci-operator/step-registry/openshift/image-based/upgrade/e2e/gather/OWNERS
  ci-operator/step-registry/openshift/image-based/upgrade/e2e/gather/openshift-image-based-upgrade-e2e-gather-commands.sh
  ci-operator/step-registry/openshift/image-based/upgrade/e2e/gather/openshift-image-based-upgrade-e2e-gather-ref.metadata.json
  ci-operator/step-registry/openshift/image-based/upgrade/e2e/gather/openshift-image-based-upgrade-e2e-gather-ref.yaml
  ci-operator/step-registry/openshift/image-based/upgrade/e2e/openshift-image-based-upgrade-e2e-commands.sh
  ci-operator/step-registry/openshift/image-based/upgrade/e2e/openshift-image-based-upgrade-e2e-ref.metadata.json
  ci-operator/step-registry/openshift/image-based/upgrade/e2e/openshift-image-based-upgrade-e2e-ref.yaml
  ci-operator/step-registry/openshift/image-based/upgrade/e2e/openshift-image-based-upgrade-e2e-workflow.metadata.json
  ci-operator/step-registry/openshift/image-based/upgrade/e2e/openshift-image-based-upgrade-e2e-workflow.yaml
  ci-operator/step-registry/openshift/image-based/upgrade/metal/config/openshift-image-based-upgrade-metal-config-commands.sh
  ci-operator/step-registry/openshift/image-based/upgrade/seed/create/openshift-image-based-upgrade-seed-create-commands.sh
  ci-operator/step-registry/openshift/image-based/upgrade/seed/create/openshift-image-based-upgrade-seed-create-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#51625 openshift-loki: Add ci config for branch upstream-v2.9.8
  ci-operator/config/openshift/loki/openshift-loki-upstream-v2.9.8.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-upstream-v2.9.8-postsubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-upstream-v2.9.8-presubmits.yaml
  core-services/image-mirroring/openshift-logging/mapping_logging_loki_quay
Labels: lgtm, approved, rehearsals-ack

#51635 OCPBUGS-33244: Change LVMS base image to fix openssl conflicts
  ci-operator/config/openshift/lvm-operator/openshift-lvm-operator-main.yaml
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, rehearsals-ack, jira/valid-reference

#51644 MULTIARCH-4286: fix skip_if_only_changed regex
  ci-operator/config/openshift/multiarch-tuning-operator/openshift-multiarch-tuning-operator-main.yaml
  ci-operator/jobs/openshift/multiarch-tuning-operator/openshift-multiarch-tuning-operator-main-postsubmits.yaml
  ci-operator/jobs/openshift/multiarch-tuning-operator/openshift-multiarch-tuning-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#51648 remove redis image from ols mirroring
  core-services/image-mirroring/lightspeed-service/mapping_lightspeed_service
Labels: lgtm, approved, rehearsals-ack

#51652 drop redis mirroring from other ols mirror config
  core-services/image-mirroring/openshift-lightspeed/mapping_openshift_lightspeed
Labels: lgtm, approved, rehearsals-ack

#51567 Add zstream config for springboot
  ci-operator/config/rhoar-qe/spring-boot-openshift-interop-tests/rhoar-qe-spring-boot-openshift-interop-tests-main__springboot-ocp4.14-lp-interop.yaml
  ci-operator/config/rhoar-qe/spring-boot-openshift-interop-tests/rhoar-qe-spring-boot-openshift-interop-tests-main__springboot-ocp4.15-lp-interop.yaml
  ci-operator/jobs/rhoar-qe/spring-boot-openshift-interop-tests/rhoar-qe-spring-boot-openshift-interop-tests-main-periodics.yaml
  ci-operator/jobs/rhoar-qe/spring-boot-openshift-interop-tests/rhoar-qe-spring-boot-openshift-interop-tests-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#51602 Onboard Quarkus for zstream testing
  ci-operator/config/quarkus-qe/quarkus-openshift-interop/quarkus-qe-quarkus-openshift-interop-main__quarkus-ocp4.14-lp-interop.yaml
  ci-operator/config/quarkus-qe/quarkus-openshift-interop/quarkus-qe-quarkus-openshift-interop-main__quarkus-ocp4.15-lp-interop.yaml
  ci-operator/jobs/quarkus-qe/quarkus-openshift-interop/quarkus-qe-quarkus-openshift-interop-main-periodics.yaml
  ci-operator/jobs/quarkus-qe/quarkus-openshift-interop/quarkus-qe-quarkus-openshift-interop-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#51633 shipwright-io: Enable Cherrypick Bot
  core-services/prow/02_config/shipwright-io/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#51636 Add auto-upgrade for build09/10/hosted-mgmt
  ci-operator/jobs/infra-periodics.yaml
  clusters/build-clusters/build09/upgrader-sa.yaml
  clusters/build-clusters/build10/upgrader-sa.yaml
  clusters/hosted-mgmt/upgrader-sa.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#51656 openshift-loki: Use loki v2.9.8 in operator branches
  ci-operator/config/openshift/loki/openshift-loki-main.yaml
  ci-operator/config/openshift/loki/openshift-loki-release-5.6.yaml
  ci-operator/config/openshift/loki/openshift-loki-release-5.7.yaml
  ci-operator/config/openshift/loki/openshift-loki-release-5.8.yaml
  ci-operator/config/openshift/loki/openshift-loki-release-5.9.yaml
Labels: lgtm, approved, rehearsals-ack

#50547 WINC-1223: Add vsphere-disconnected to WINC e2e suite
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-master.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.16.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.17.yaml
  ci-operator/jobs/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.16-presubmits.yaml
  ci-operator/jobs/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.17-presubmits.yaml
  ci-operator/step-registry/windows/e2e/operator/test/mirror-images/OWNERS
  ci-operator/step-registry/windows/e2e/operator/test/mirror-images/windows-e2e-operator-test-mirror-images-commands.sh
  ci-operator/step-registry/windows/e2e/operator/test/mirror-images/windows-e2e-operator-test-mirror-images-ref.metadata.json
  ci-operator/step-registry/windows/e2e/operator/test/mirror-images/windows-e2e-operator-test-mirror-images-ref.yaml
  ci-operator/step-registry/windows/e2e/operator/test/mirror-images/windows-e2e-operator-test-mirror-images.metadata.json
  ci-operator/step-registry/windows/e2e/operator/test/vsphere-disconnected/OWNERS
  ci-operator/step-registry/windows/e2e/operator/test/vsphere-disconnected/post/OWNERS
  ci-operator/step-registry/windows/e2e/operator/test/vsphere-disconnected/post/windows-e2e-operator-test-vsphere-disconnected-post-chain.metadata.json
  ci-operator/step-registry/windows/e2e/operator/test/vsphere-disconnected/post/windows-e2e-operator-test-vsphere-disconnected-post-chain.yaml
  ci-operator/step-registry/windows/e2e/operator/test/vsphere-disconnected/pre/OWNERS
  ci-operator/step-registry/windows/e2e/operator/test/vsphere-disconnected/pre/windows-e2e-operator-test-vsphere-disconnected-pre-chain.metadata.json
  ci-operator/step-registry/windows/e2e/operator/test/vsphere-disconnected/pre/windows-e2e-operator-test-vsphere-disconnected-pre-chain.yaml
  ci-operator/step-registry/windows/e2e/operator/test/vsphere-disconnected/windows-e2e-operator-test-vsphere-disconnected-workflow.metadata.json
  ci-operator/step-registry/windows/e2e/operator/test/vsphere-disconnected/windows-e2e-operator-test-vsphere-disconnected-workflow.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#51658 openshift-loki: Remove obsolete loki upstream branches and mirroring
  ci-operator/config/openshift/loki/openshift-loki-upstream-v2.9.4.yaml
  ci-operator/config/openshift/loki/openshift-loki-upstream-v2.9.6.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-upstream-v2.9.4-postsubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-upstream-v2.9.4-presubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-upstream-v2.9.6-postsubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-upstream-v2.9.6-presubmits.yaml
  core-services/image-mirroring/openshift-logging/mapping_logging_loki_quay
Labels: lgtm, approved, rehearsals-ack

#51489 diable debug info in capi steps
  ci-operator/step-registry/cucushift/hypershift-extended/capi/clear/cucushift-hypershift-extended-capi-clear-commands.sh
  ci-operator/step-registry/cucushift/hypershift-extended/capi/health-check/cucushift-hypershift-extended-capi-health-check-commands.sh
  ci-operator/step-registry/cucushift/hypershift-extended/capi/init/cucushift-hypershift-extended-capi-init-commands.sh
  ci-operator/step-registry/cucushift/hypershift-extended/capi/provision/cucushift-hypershift-extended-capi-provision-commands.sh
  ci-operator/step-registry/cucushift/hypershift-extended/capi/vpc-peering/cucushift-hypershift-extended-capi-vpc-peering-commands.sh
Labels: lgtm, approved, rehearsals-ack

#51614 [OCPQE-21318 HyperShift-QE] enable hypershift-dump in Azure workflow
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/ovn/hypershift/deprovision/cucushift-installer-rehearse-azure-ipi-ovn-hypershift-deprovision-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#51605 okd-scos: fix machine-os-images job
  ci-operator/config/openshift/machine-os-images/openshift-machine-os-images-main__okd-scos.yaml
Labels: lgtm, approved, rehearsals-ack

#51507 Change the cron job schedule for 4.16 ppc64le job
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__ppc64le-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#51492 Add quay 3.11 testing with AWS RDS Postgresql 16 and 15
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__ocp-416-quay.yaml
  ci-operator/jobs/quay/quay-tests/quay-quay-tests-master-periodics.yaml
  ci-operator/step-registry/quay-tests/cucushift-installer-rehearse-aws-ipi/OWNERS
  ci-operator/step-registry/quay-tests/cucushift-installer-rehearse-aws-ipi/quay-tests-cucushift-installer-rehearse-aws-ipi-workflow.metadata.json
  ci-operator/step-registry/quay-tests/cucushift-installer-rehearse-aws-ipi/quay-tests-cucushift-installer-rehearse-aws-ipi-workflow.yaml
  ci-operator/step-registry/quay-tests/deploy-quay-aws-rds-postgresql/OWNERS
  ci-operator/step-registry/quay-tests/deploy-quay-aws-rds-postgresql/quay-tests-deploy-quay-aws-rds-postgresql-commands.sh
  ci-operator/step-registry/quay-tests/deploy-quay-aws-rds-postgresql/quay-tests-deploy-quay-aws-rds-postgresql-ref.metadata.json
  ci-operator/step-registry/quay-tests/deploy-quay-aws-rds-postgresql/quay-tests-deploy-quay-aws-rds-postgresql-ref.yaml
  ci-operator/step-registry/quay-tests/deprovisioning-quay-aws-rds-postgresql/OWNERS
  ci-operator/step-registry/quay-tests/deprovisioning-quay-aws-rds-postgresql/quay-tests-deprovisioning-quay-aws-rds-postgresql-commands.sh
  ci-operator/step-registry/quay-tests/deprovisioning-quay-aws-rds-postgresql/quay-tests-deprovisioning-quay-aws-rds-postgresql-ref.metadata.json
  ci-operator/step-registry/quay-tests/deprovisioning-quay-aws-rds-postgresql/quay-tests-deprovisioning-quay-aws-rds-postgresql-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#51676 [CIGolang]additinoal master image
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__images.yaml
Labels: lgtm, approved, rehearsals-ack

#51680 Update _pluginconfig.yaml
  core-services/prow/02_config/red-hat-storage/_pluginconfig.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#51662 remove OpenShiftSDN jobs from 4.16+ in k8s-nmstate
  ci-operator/config/openshift/kubernetes-nmstate/openshift-kubernetes-nmstate-master.yaml
  ci-operator/config/openshift/kubernetes-nmstate/openshift-kubernetes-nmstate-release-4.16.yaml
  ci-operator/config/openshift/kubernetes-nmstate/openshift-kubernetes-nmstate-release-4.17.yaml
  ci-operator/jobs/openshift/kubernetes-nmstate/openshift-kubernetes-nmstate-master-periodics.yaml
  ci-operator/jobs/openshift/kubernetes-nmstate/openshift-kubernetes-nmstate-master-presubmits.yaml
  ci-operator/jobs/openshift/kubernetes-nmstate/openshift-kubernetes-nmstate-release-4.16-presubmits.yaml
  ci-operator/jobs/openshift/kubernetes-nmstate/openshift-kubernetes-nmstate-release-4.17-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#51516 Include NMO upgrade installation test in OCP-e2e cluster test for OCP…
  ci-operator/config/medik8s/fence-agents-remediation/medik8s-fence-agents-remediation-main__4.12.yaml
  ci-operator/config/medik8s/fence-agents-remediation/medik8s-fence-agents-remediation-main__4.13.yaml
  ci-operator/config/medik8s/fence-agents-remediation/medik8s-fence-agents-remediation-main__4.14.yaml
  ci-operator/config/medik8s/fence-agents-remediation/medik8s-fence-agents-remediation-main__4.15.yaml
  ci-operator/config/medik8s/fence-agents-remediation/medik8s-fence-agents-remediation-main__4.16.yaml
  ci-operator/config/medik8s/node-maintenance-operator/medik8s-node-maintenance-operator-main__4.12.yaml
  ci-operator/config/medik8s/node-maintenance-operator/medik8s-node-maintenance-operator-main__4.13.yaml
  ci-operator/config/medik8s/node-maintenance-operator/medik8s-node-maintenance-operator-main__4.14.yaml
  ci-operator/config/medik8s/node-maintenance-operator/medik8s-node-maintenance-operator-main__4.15.yaml
Labels: lgtm, approved, rehearsals-ack

#51669 NO-JIRA: mirror the new version of the hco bundle image
  clusters/app.ci/supplemental-ci-images/hyperconverged-cluster-bundle.yaml
  core-services/image-mirroring/_config.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#51687 disable cron for aws bm arm
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.16-nightly-arm-bm.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-periodics.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#51684 OCPQE-21400: [4.12] move more aws/azure ci jobs to multi arch ci
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-stable-4.11.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__arm64-nightly-4.12-upgrade-from-stable-4.11.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__arm64-nightly-4.12-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__multi-nightly-4.12-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__multi-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#51705 chore: update jobs for PowerMon Operator
  ci-operator/config/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-tech-preview-0.2__tech-preview-0.2-ocp4.14-periodic.yaml
  ci-operator/config/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-tech-preview-0.2__tech-preview-0.2-ocp4.15-periodic.yaml
  ci-operator/config/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-tech-preview.yaml
  ci-operator/config/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-tech-preview__ocp4.13-periodic.yaml
  ci-operator/config/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-tech-preview__ocp4.14-periodic.yaml
  ci-operator/config/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-tech-preview__post-submit.yaml
  ci-operator/config/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-tech-preview__product-ocp-4.14-stage.yaml
  ci-operator/config/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-v1alpha1.yaml
  ci-operator/config/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-v1alpha1__ocp4.14-periodic.yaml
  ci-operator/config/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-v1alpha1__ocp4.15-periodic.yaml
  ci-operator/config/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-v1alpha1__post-submit.yaml
  ci-operator/step-registry/openshift-power-monitoring/tests/kepler/openshift-power-monitoring-tests-kepler-commands.sh
  ci-operator/step-registry/openshift-power-monitoring/tests/power-monitoring-operator/openshift-power-monitoring-tests-power-monitoring-operator-commands.sh
Labels: lgtm, approved, rehearsals-ack

#51610 WRKLDS-1251: Remove rhel8 based tags from cli image
  ci-operator/config/openshift/oc/openshift-oc-master.yaml
  ci-operator/config/openshift/oc/openshift-oc-release-4.16.yaml
  ci-operator/config/openshift/oc/openshift-oc-release-4.17.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#51671 WRKLDS-1257: Change base image of must-gather to RHEL9
  ci-operator/config/openshift/must-gather/openshift-must-gather-master.yaml
  ci-operator/config/openshift/must-gather/openshift-must-gather-release-4.16.yaml
  ci-operator/config/openshift/must-gather/openshift-must-gather-release-4.17.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#51703 Upgrade konflux-ci org jobs to use ocp 4.14
  ci-operator/config/konflux-ci/release-service-catalog/konflux-ci-release-service-catalog-development.yaml
  ci-operator/config/konflux-ci/remote-secret/konflux-ci-remote-secret-main.yaml
  ci-operator/config/konflux-ci/service-provider-integration-operator/konflux-ci-service-provider-integration-operator-main.yaml
Labels: lgtm, approved, rehearsals-ack

#51699 Point all konflux jobs to ocp4.14
  ci-operator/config/redhat-appstudio/application-service/redhat-appstudio-application-service-main.yaml
  ci-operator/config/redhat-appstudio/build-service/redhat-appstudio-build-service-main.yaml
  ci-operator/config/redhat-appstudio/e2e-tests/redhat-appstudio-e2e-tests-main.yaml
  ci-operator/config/redhat-appstudio/image-controller/redhat-appstudio-image-controller-main.yaml
  ci-operator/config/redhat-appstudio/infra-deployments/redhat-appstudio-infra-deployments-main.yaml
  ci-operator/config/redhat-appstudio/integration-service/redhat-appstudio-integration-service-main.yaml
  ci-operator/config/redhat-appstudio/jvm-build-service/redhat-appstudio-jvm-build-service-main.yaml
  ci-operator/config/redhat-appstudio/release-service/redhat-appstudio-release-service-main.yaml
Labels: lgtm, approved, rehearsals-ack

#51655 Remove secret/registry-push-credentials-quay.io
  ci-operator/jobs/infra-image-mirroring.yaml
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#46889 Onboard Openshift Serverless operator on ROSA Classic
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main__ocp4.14-lp-rosa-classic.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main__ocp4.15-lp-rosa-classic.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main-periodics.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#51717 MULTIARCH-4516: add -ignore-os-checks for rhel9
  ci-operator/step-registry/upi/deprovision/powervs/cluster/upi-deprovision-powervs-cluster-commands.sh
  ci-operator/step-registry/upi/install/powervs/cluster/upi-install-powervs-cluster-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#51718 fix job/periodic-image-mirroring-kubefed
  ci-operator/jobs/infra-image-mirroring.yaml
Labels: lgtm, approved, rehearsals-ack

#51708 WRKLDS-1257: Use must-gather base image to use latest must-gather in cli
  ci-operator/config/openshift/oc/openshift-oc-master.yaml
  ci-operator/config/openshift/oc/openshift-oc-release-4.16.yaml
  ci-operator/config/openshift/oc/openshift-oc-release-4.17.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#51309 OSSM-4505 Add integration upstream test jobs
  ci-operator/config/openshift-service-mesh/istio/openshift-service-mesh-istio-master.yaml
  ci-operator/jobs/openshift-service-mesh/istio/openshift-service-mesh-istio-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#51714 ETCD-519: add feature flag to e2e jobs
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-master.yaml
  ci-operator/jobs/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#51665 Run make test with jenkins
  ci-operator/config/openshift/dpu-operator/openshift-dpu-operator-main.yaml
  ci-operator/jobs/openshift/dpu-operator/openshift-dpu-operator-main-presubmits.yaml
  ci-operator/step-registry/dpu-operator/tests-workflow/OWNERS
  ci-operator/step-registry/dpu-operator/tests-workflow/dpu-operator-tests-workflow-workflow.metadata.json
  ci-operator/step-registry/dpu-operator/tests-workflow/dpu-operator-tests-workflow-workflow.yaml
  ci-operator/step-registry/dpu-operator/tests-workflow/dpu-operator-tests-workflow.metadata.json
  ci-operator/step-registry/dpu-operator/tests-workflow/tests/OWNERS
  ci-operator/step-registry/dpu-operator/tests-workflow/tests/dpu-operator-tests-workflow-tests-commands.sh
  ci-operator/step-registry/dpu-operator/tests-workflow/tests/dpu-operator-tests-workflow-tests-ref.metadata.json
  ci-operator/step-registry/dpu-operator/tests-workflow/tests/dpu-operator-tests-workflow-tests-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#51673 disable CLO: e2e and functional tests
  ci-operator/config/openshift/cluster-logging-operator/OWNERS
  ci-operator/config/openshift/cluster-logging-operator/openshift-cluster-logging-operator-master.yaml
  ci-operator/jobs/openshift/cluster-logging-operator/openshift-cluster-logging-operator-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#51701 USHIFT-2912: Build MicroShift's multus & CNI plugins
  ci-operator/config/openshift/containernetworking-plugins/openshift-containernetworking-plugins-master.yaml
  ci-operator/config/openshift/containernetworking-plugins/openshift-containernetworking-plugins-release-4.16.yaml
  ci-operator/config/openshift/multus-cni/openshift-multus-cni-master.yaml
  ci-operator/config/openshift/multus-cni/openshift-multus-cni-release-4.16.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#51719 adding hibernation back to 4.15 clusters
  clusters/hosted-mgmt/hive/pools/rh-openshift-ecosystem/rhoe-ocp-4-15-amd64-aws-us-east-1_clusterpool.yaml
  clusters/hosted-mgmt/hive/pools/rh-openshift-ecosystem/rhoe-ocp-4-15-amd64-aws-us-east-2_clusterpool.yaml
Labels: lgtm, approved, rehearsals-ack

#51564 chore: mirror scanner-test-0.3.69 image
  core-services/image-mirroring/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#51612 cert-rotation: tweak CSR approval
  ci-operator/step-registry/openshift/e2e/cert-rotation/prepare-for-shutdown/openshift-e2e-cert-rotation-prepare-for-shutdown-commands.sh
Labels: lgtm, approved, rehearsals-ack

#51725 TRT-1613: Ensure minor upgrades match 4.16 to 4.17
  core-services/release-controller/_releases/priv/release-ocp-4.17.json
  core-services/release-controller/_releases/release-ocp-4.17.json
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#51533 Fix cli, cli-artifacts image generation for okd scos
  ci-operator/config/openshift/oc/openshift-oc-master__okd-scos.yaml
Labels: lgtm, approved, rehearsals-ack

#51690 elasticsearch-proxy: Fix builds to promote RHEL-9 images only
  ci-operator/config/openshift/elasticsearch-proxy/openshift-elasticsearch-proxy-master.yaml
  ci-operator/jobs/openshift/elasticsearch-proxy/openshift-elasticsearch-proxy-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#50084 STOR-1692: CI implementation: Test the Vault provider with Secret Store CSI driver operator
  ci-operator/config/openshift/secrets-store-csi-driver-operator/openshift-secrets-store-csi-driver-operator-main.yaml
  ci-operator/config/openshift/secrets-store-csi-driver-operator/openshift-secrets-store-csi-driver-operator-release-4.16.yaml
  ci-operator/config/openshift/secrets-store-csi-driver-operator/openshift-secrets-store-csi-driver-operator-release-4.17.yaml
  ci-operator/jobs/openshift/secrets-store-csi-driver-operator/openshift-secrets-store-csi-driver-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/secrets-store-csi-driver-operator/openshift-secrets-store-csi-driver-operator-release-4.16-presubmits.yaml
  ci-operator/jobs/openshift/secrets-store-csi-driver-operator/openshift-secrets-store-csi-driver-operator-release-4.17-presubmits.yaml
  ci-operator/step-registry/openshift/e2e/azure/csi/secrets-store/vault/OWNERS
  ci-operator/step-registry/openshift/e2e/azure/csi/secrets-store/vault/openshift-e2e-azure-csi-secrets-store-vault-workflow.metadata.json
  ci-operator/step-registry/openshift/e2e/azure/csi/secrets-store/vault/openshift-e2e-azure-csi-secrets-store-vault-workflow.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#51542 LOG-5468: Switch CLO CI to use vector release-6.0
  ci-operator/config/openshift/cluster-logging-operator/openshift-cluster-logging-operator-master.yaml
  core-services/image-mirroring/openshift-logging/mapping_logging_latest_quay
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#51672 [winc][disconnected] Mirror all required images
  ci-operator/step-registry/windows/e2e/operator/test/mirror-images/windows-e2e-operator-test-mirror-images-commands.sh
Labels: lgtm, approved, rehearsals-ack

#51716 [release-v1.12] Add CI config for Knative Client 1.12 release
  ci-operator/config/openshift-knative/client/openshift-knative-client-release-v1.12.yaml
  ci-operator/jobs/openshift-knative/client/openshift-knative-client-release-v1.12-postsubmits.yaml
  ci-operator/jobs/openshift-knative/client/openshift-knative-client-release-v1.12-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#51736 update clc-e2e ff
  ci-operator/config/stolostron/cluster-lifecycle-e2e/stolostron-cluster-lifecycle-e2e-main.yaml
Labels: lgtm, approved, rehearsals-ack

#51738 ACM: foundation skip tests if only matched files changed
  ci-operator/config/stolostron/managed-serviceaccount/stolostron-managed-serviceaccount-backplane-2.4.yaml
  ci-operator/config/stolostron/managed-serviceaccount/stolostron-managed-serviceaccount-backplane-2.5.yaml
  ci-operator/config/stolostron/managed-serviceaccount/stolostron-managed-serviceaccount-backplane-2.6.yaml
  ci-operator/config/stolostron/managed-serviceaccount/stolostron-managed-serviceaccount-main.yaml
  ci-operator/config/stolostron/managedcluster-import-controller/stolostron-managedcluster-import-controller-backplane-2.4.yaml
  ci-operator/config/stolostron/managedcluster-import-controller/stolostron-managedcluster-import-controller-backplane-2.5.yaml
  ci-operator/config/stolostron/managedcluster-import-controller/stolostron-managedcluster-import-controller-backplane-2.6.yaml
  ci-operator/config/stolostron/managedcluster-import-controller/stolostron-managedcluster-import-controller-main.yaml
  ci-operator/config/stolostron/multicloud-operators-foundation/stolostron-multicloud-operators-foundation-backplane-2.4.yaml
  ci-operator/config/stolostron/multicloud-operators-foundation/stolostron-multicloud-operators-foundation-backplane-2.5.yaml
  ci-operator/config/stolostron/multicloud-operators-foundation/stolostron-multicloud-operators-foundation-backplane-2.6.yaml
  ci-operator/config/stolostron/multicloud-operators-foundation/stolostron-multicloud-operators-foundation-main.yaml
  ci-operator/config/stolostron/ocm/stolostron-ocm-backplane-2.4.yaml
  ci-operator/config/stolostron/ocm/stolostron-ocm-backplane-2.5.yaml
  ci-operator/config/stolostron/ocm/stolostron-ocm-backplane-2.6.yaml
  ci-operator/jobs/stolostron/managed-serviceaccount/stolostron-managed-serviceaccount-backplane-2.4-presubmits.yaml
  ci-operator/jobs/stolostron/managed-serviceaccount/stolostron-managed-serviceaccount-backplane-2.5-presubmits.yaml
  ci-operator/jobs/stolostron/managed-serviceaccount/stolostron-managed-serviceaccount-backplane-2.6-presubmits.yaml
  ci-operator/jobs/stolostron/managed-serviceaccount/stolostron-managed-serviceaccount-main-presubmits.yaml
  ci-operator/jobs/stolostron/managedcluster-import-controller/stolostron-managedcluster-import-controller-backplane-2.4-presubmits.yaml
  ci-operator/jobs/stolostron/managedcluster-import-controller/stolostron-managedcluster-import-controller-backplane-2.5-presubmits.yaml
  ci-operator/jobs/stolostron/managedcluster-import-controller/stolostron-managedcluster-import-controller-backplane-2.6-presubmits.yaml
  ci-operator/jobs/stolostron/managedcluster-import-controller/stolostron-managedcluster-import-controller-main-postsubmits.yaml
  ci-operator/jobs/stolostron/managedcluster-import-controller/stolostron-managedcluster-import-controller-main-presubmits.yaml
  ci-operator/jobs/stolostron/multicloud-operators-foundation/stolostron-multicloud-operators-foundation-backplane-2.4-presubmits.yaml
  ci-operator/jobs/stolostron/multicloud-operators-foundation/stolostron-multicloud-operators-foundation-backplane-2.5-presubmits.yaml
  ci-operator/jobs/stolostron/multicloud-operators-foundation/stolostron-multicloud-operators-foundation-backplane-2.6-presubmits.yaml
  ci-operator/jobs/stolostron/multicloud-operators-foundation/stolostron-multicloud-operators-foundation-main-postsubmits.yaml
  ci-operator/jobs/stolostron/multicloud-operators-foundation/stolostron-multicloud-operators-foundation-main-presubmits.yaml
  ci-operator/jobs/stolostron/ocm/stolostron-ocm-backplane-2.4-presubmits.yaml
  ci-operator/jobs/stolostron/ocm/stolostron-ocm-backplane-2.5-presubmits.yaml
  ci-operator/jobs/stolostron/ocm/stolostron-ocm-backplane-2.6-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#51654 okd-scos: fix etcd job and add installer-etcd-artifact image
  ci-operator/config/openshift/etcd/openshift-etcd-openshift-4.16__okd-scos.yaml
Labels: lgtm, approved, rehearsals-ack

#51726 add control-plane node selector to azure mgmt cluster
  ci-operator/step-registry/hypershift/setup-nested-management-cluster/hypershift-setup-nested-management-cluster-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#51739 feat(RELEASE-230): migrate release-service to konflux-ci org
  ci-operator/config/konflux-ci/release-service/OWNERS
  ci-operator/config/konflux-ci/release-service/konflux-ci-release-service-main.yaml
  ci-operator/jobs/konflux-ci/release-service/OWNERS
  ci-operator/jobs/konflux-ci/release-service/konflux-ci-release-service-main-presubmits.yaml
  core-services/prow/02_config/konflux-ci/release-service/_pluginconfig.yaml
  core-services/prow/02_config/konflux-ci/release-service/_prowconfig.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#51720 MULTIARCH-4516: convert period to dash
  ci-operator/step-registry/upi/install/powervs/cluster/upi-install-powervs-cluster-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#51694 konflux build-service: move to konflux-ci
  ci-operator/config/konflux-ci/build-service/OWNERS
  ci-operator/config/konflux-ci/build-service/konflux-ci-build-service-main.yaml
  ci-operator/jobs/konflux-ci/build-service/OWNERS
  ci-operator/jobs/konflux-ci/build-service/konflux-ci-build-service-main-presubmits.yaml
  core-services/prow/02_config/konflux-ci/build-service/OWNERS
  core-services/prow/02_config/konflux-ci/build-service/_pluginconfig.yaml
  core-services/prow/02_config/konflux-ci/build-service/_prowconfig.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#51740 Push results of ObO&OCP416 compat job to slack channel
  ci-operator/jobs/rhobs/observability-operator/rhobs-observability-operator-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#51643 This commit will make the python-client-test optional.
  ci-operator/config/opendatahub-io/model-registry/opendatahub-io-model-registry-main.yaml
  ci-operator/jobs/opendatahub-io/model-registry/opendatahub-io-model-registry-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#51743 Update Distributed Tracing upstream testing jobs
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__ocp4.13-amd64-upgrade.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__ocp4.13-hypershift.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__ocp4.14-amd64.yaml
Labels: lgtm, approved, rehearsals-ack

#51744 always create install junit even no kubeconfig is generated
  ci-operator/step-registry/gather/must-gather/gather-must-gather-commands.sh
Labels: lgtm, approved, rehearsals-ack

#51742 ACM: trust red-hat-konflux for clc-state-metrics
  core-services/prow/02_config/stolostron/clusterlifecycle-state-metrics/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#51384 update code to disable worload mcp
  ci-operator/step-registry/openshift-qe/workers-infra-workload/openshift-qe-workers-infra-workload-commands.sh
  ci-operator/step-registry/openshift-qe/workers-infra-workload/openshift-qe-workers-infra-workload-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#51741 HCO: bump to v1.13
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-main.yaml
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-main__okd.yaml
Labels: lgtm, approved, rehearsals-ack

#51627 Tempo zstream onboarding on ibmcloud
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.14-lp-interop.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.15-lp-interop.yaml
  ci-operator/jobs/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main-periodics.yaml
  ci-operator/jobs/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#51630 Opentelemetry zstream onboarding on ibmcloud
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.14-lp-interop.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.15-lp-interop.yaml
  ci-operator/jobs/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main-periodics.yaml
  ci-operator/jobs/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#51678 mapi-regression-gcp
  ci-operator/config/openshift/machine-api-provider-gcp/openshift-machine-api-provider-gcp-main.yaml
  ci-operator/jobs/openshift/machine-api-provider-gcp/openshift-machine-api-provider-gcp-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#51528 Updating to use e2e v2.1.7
  ci-operator/step-registry/openshift-qe/cluster-density-v2/openshift-qe-cluster-density-v2-ref.yaml
  ci-operator/step-registry/openshift-qe/conc-builds/openshift-qe-conc-builds-ref.yaml
  ci-operator/step-registry/openshift-qe/control-plane-smoke/openshift-qe-control-plane-smoke-ref.yaml
  ci-operator/step-registry/openshift-qe/ingress-perf/openshift-qe-ingress-perf-ref.yaml
  ci-operator/step-registry/openshift-qe/loaded-upgrade/openshift-qe-loaded-upgrade-ref.yaml
  ci-operator/step-registry/openshift-qe/network-perf/openshift-qe-network-perf-ref.yaml
  ci-operator/step-registry/openshift-qe/network-policy/openshift-qe-network-policy-ref.yaml
  ci-operator/step-registry/openshift-qe/network-smoke/openshift-qe-network-smoke-ref.yaml
  ci-operator/step-registry/openshift-qe/node-density-cni/openshift-qe-node-density-cni-ref.yaml
  ci-operator/step-registry/openshift-qe/node-density-heavy/openshift-qe-node-density-heavy-ref.yaml
  ci-operator/step-registry/openshift-qe/node-density/openshift-qe-node-density-ref.yaml
  ci-operator/step-registry/openshift-qe/router-perf/openshift-qe-router-perf-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#51601 OKD-scos: fix hyperkube, pod build
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-master__okd-scos.yaml
Labels: lgtm, approved, rehearsals-ack

#51618 OSASINFRA-3435: openstack: Add CAPI-installer periodics
  ci-operator/config/openshift/installer/openshift-installer-master__altinfra-periodics.yaml
  ci-operator/config/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main__periodic-4.16.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-periodics.yaml
  ci-operator/jobs/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#51734 Bump to UBI9
  ci-operator/config/stolostron/cert-policy-controller/stolostron-cert-policy-controller-main.yaml
  ci-operator/config/stolostron/cert-policy-controller/stolostron-cert-policy-controller-release-2.10.yaml
  ci-operator/config/stolostron/cert-policy-controller/stolostron-cert-policy-controller-release-2.11.yaml
  ci-operator/config/stolostron/config-policy-controller/stolostron-config-policy-controller-main.yaml
  ci-operator/config/stolostron/config-policy-controller/stolostron-config-policy-controller-release-2.10.yaml
  ci-operator/config/stolostron/config-policy-controller/stolostron-config-policy-controller-release-2.11.yaml
  ci-operator/config/stolostron/governance-policy-addon-controller/stolostron-governance-policy-addon-controller-main.yaml
  ci-operator/config/stolostron/governance-policy-addon-controller/stolostron-governance-policy-addon-controller-release-2.10.yaml
  ci-operator/config/stolostron/governance-policy-addon-controller/stolostron-governance-policy-addon-controller-release-2.11.yaml
  ci-operator/config/stolostron/governance-policy-framework-addon/stolostron-governance-policy-framework-addon-main.yaml
  ci-operator/config/stolostron/governance-policy-framework-addon/stolostron-governance-policy-framework-addon-release-2.10.yaml
  ci-operator/config/stolostron/governance-policy-framework-addon/stolostron-governance-policy-framework-addon-release-2.11.yaml
  ci-operator/config/stolostron/governance-policy-framework/stolostron-governance-policy-framework-main.yaml
  ci-operator/config/stolostron/governance-policy-framework/stolostron-governance-policy-framework-release-2.10.yaml
  ci-operator/config/stolostron/governance-policy-framework/stolostron-governance-policy-framework-release-2.11.yaml
  ci-operator/config/stolostron/governance-policy-propagator/stolostron-governance-policy-propagator-main.yaml
  ci-operator/config/stolostron/governance-policy-propagator/stolostron-governance-policy-propagator-release-2.10.yaml
  ci-operator/config/stolostron/governance-policy-propagator/stolostron-governance-policy-propagator-release-2.11.yaml
  ci-operator/config/stolostron/iam-policy-controller/stolostron-iam-policy-controller-release-2.10.yaml
Labels: lgtm, approved, rehearsals-ack

#51756 NO-JIRA: Revert fix: use upi-installer image for sno config update
  ci-operator/step-registry/single-node/conf/aws/single-node-conf-aws-ref.yaml
  ci-operator/step-registry/single-node/conf/azure/single-node-conf-azure-ref.yaml
  ci-operator/step-registry/single-node/conf/gcp/single-node-conf-gcp-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#51750 repos: 4.16: Use RHEL 9.4 EUS repos for RHCOS
  clusters/build-clusters/common/release-controller/rpms-ocp-4.16.yaml
  core-services/release-controller/_repos/ocp-4.16-rhel92.repo
  core-services/release-controller/_repos/ocp-4.16-rhel94.repo
Labels: lgtm, approved, rehearsals-ack

#51759 Reduce boskos lease count for periodics
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: lgtm, approved, rehearsals-ack

#51730 chore(stackrox): update build root for 4.4 to 0.3.67.1
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-4.4.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-4.4__ocp-4-11.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-4.4__ocp-4-15.yaml
Labels: lgtm, approved, rehearsals-ack

#51650 OCPEDGE-995: feat: parallel conformance tests
  ci-operator/config/openshift-kni/lifecycle-agent/openshift-kni-lifecycle-agent-main__nightly-4.15.yaml
  ci-operator/config/openshift-kni/lifecycle-agent/openshift-kni-lifecycle-agent-main__nightly-4.16.yaml
  ci-operator/jobs/openshift-kni/lifecycle-agent/openshift-kni-lifecycle-agent-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#51747 Switch NVIDIA GPU tests to new repo
  ci-operator/config/rh-ecosystem-edge/ci-tools-nvidia-gpu-operator/OWNERS
  ci-operator/config/rh-ecosystem-edge/ci-tools-nvidia-gpu-operator/rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main.yaml
  ci-operator/config/rh-ecosystem-edge/ci-tools-nvidia-gpu-operator/rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main__4.14.yaml
  ci-operator/config/rh-ecosystem-edge/ci-tools-nvidia-gpu-operator/rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main__4.16.yaml
  ci-operator/config/rh-ecosystem-edge/nvidia-ci/rh-ecosystem-edge-nvidia-ci-main__4.12.yaml
  ci-operator/config/rh-ecosystem-edge/nvidia-ci/rh-ecosystem-edge-nvidia-ci-main__4.13.yaml
  ci-operator/config/rh-ecosystem-edge/nvidia-ci/rh-ecosystem-edge-nvidia-ci-main__4.14.yaml
  ci-operator/config/rh-ecosystem-edge/nvidia-ci/rh-ecosystem-edge-nvidia-ci-main__4.15.yaml
  ci-operator/config/rh-ecosystem-edge/nvidia-ci/rh-ecosystem-edge-nvidia-ci-main__4.16.yaml
  ci-operator/jobs/rh-ecosystem-edge/ci-tools-nvidia-gpu-operator/rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-periodics.yaml
  ci-operator/jobs/rh-ecosystem-edge/ci-tools-nvidia-gpu-operator/rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-postsubmits.yaml
  ci-operator/jobs/rh-ecosystem-edge/ci-tools-nvidia-gpu-operator/rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-presubmits.yaml
  ci-operator/jobs/rh-ecosystem-edge/nvidia-ci/rh-ecosystem-edge-nvidia-ci-main-periodics.yaml
  ci-operator/jobs/rh-ecosystem-edge/nvidia-ci/rh-ecosystem-edge-nvidia-ci-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#51760 OCPBUGS-33152: fix: update script setup to account for rhel9
  ci-operator/step-registry/single-node/conf/aws/single-node-conf-aws-commands.sh
  ci-operator/step-registry/single-node/conf/azure/single-node-conf-azure-commands.sh
  ci-operator/step-registry/single-node/conf/gcp/single-node-conf-gcp-commands.sh
Labels: lgtm, approved, jira/severity-critical, jira/valid-bug, rehearsals-ack, jira/valid-reference

#51767 okd-scos: add tools image
  ci-operator/config/openshift/oc/openshift-oc-master__okd-scos.yaml
Labels: lgtm, approved, rehearsals-ack

#51766 updating openshift-preflight jobs to go 1.22
  ci-operator/config/redhat-openshift-ecosystem/openshift-preflight/redhat-openshift-ecosystem-openshift-preflight-main__4.12.yaml
  ci-operator/config/redhat-openshift-ecosystem/openshift-preflight/redhat-openshift-ecosystem-openshift-preflight-main__4.15.yaml
Labels: lgtm, approved, rehearsals-ack

#51536 installer: remove ovirt-installer image building
  ci-operator/config/openshift/installer/openshift-installer-fcos.yaml
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
  ci-operator/config/openshift/installer/openshift-installer-master__okd.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.16.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.16__okd.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.17.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.17__okd.yaml
  core-services/image-mirroring/openshift/mapping_origin_4_16
  core-services/image-mirroring/openshift/mapping_origin_4_17
  core-services/image-mirroring/openshift/mapping_origin_4_6
Labels: lgtm, approved, rehearsals-ack

#51659 add chrome images to test-private-ui release branch images
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15.yaml
Labels: lgtm, approved, rehearsals-ack

#50965 [OCPQE-20308] Run Profile with no-kubeadmin
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
  ci-operator/step-registry/openshift-extended/test/openshift-extended-test-commands.sh
  ci-operator/step-registry/openshift-extended/test/openshift-extended-test-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#51697 Update aosqe-index image to 4.16 for 4.16 z stream upgrade
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__multi-nightly-4.16-upgrade-from-stable-4.16.yaml
Labels: lgtm, approved, rehearsals-ack

#51042 [OLS] operator - moving to use hypershift cluster for e2e
  ci-operator/config/openshift/lightspeed-operator/openshift-lightspeed-operator-main.yaml
  ci-operator/jobs/openshift/lightspeed-operator/openshift-lightspeed-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#51765 [HCO] bump to golang 1.22
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-main.yaml
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-main__okd.yaml
Labels: lgtm, approved, rehearsals-ack

#51753 Add env for quay api
  ci-operator/config/redhat-appstudio/rhtap-installer/redhat-appstudio-rhtap-installer-release-1.0.yaml
  ci-operator/jobs/redhat-appstudio/rhtap-installer/redhat-appstudio-rhtap-installer-release-1.0-postsubmits.yaml
  ci-operator/jobs/redhat-appstudio/rhtap-installer/redhat-appstudio-rhtap-installer-release-1.0-presubmits.yaml
  ci-operator/step-registry/redhat-appstudio/rhtap-installer/install-rhtap/redhat-appstudio-rhtap-installer-install-rhtap-commands.sh
Labels: lgtm, approved, rehearsals-ack

#51794 Add spec to logging web-tests
  ci-operator/step-registry/openshift-extended/logging-test/web-tests/openshift-extended-logging-test-web-tests-commands.sh
Labels: lgtm, approved, rehearsals-ack

#51792 Update Distributed Tracing acceptance test job
  ci-operator/config/openshift/distributed-tracing-qe/openshift-distributed-tracing-qe-main__ocp4.13-amd64-acceptance.yaml
  ci-operator/config/openshift/distributed-tracing-qe/openshift-distributed-tracing-qe-main__ocp4.14-acceptance.yaml
  ci-operator/config/openshift/distributed-tracing-qe/openshift-distributed-tracing-qe-main__ocp4.14-dast.yaml
  ci-operator/jobs/openshift/distributed-tracing-qe/openshift-distributed-tracing-qe-main-periodics.yaml
  ci-operator/jobs/openshift/distributed-tracing-qe/openshift-distributed-tracing-qe-main-postsubmits.yaml
  ci-operator/jobs/openshift/distributed-tracing-qe/openshift-distributed-tracing-qe-main-presubmits.yaml
  ci-operator/step-registry/distributed-tracing/tests/common/acceptance/OWNERS
  ci-operator/step-registry/distributed-tracing/tests/common/acceptance/distributed-tracing-tests-common-acceptance-commands.sh
  ci-operator/step-registry/distributed-tracing/tests/common/acceptance/distributed-tracing-tests-common-acceptance-ref.metadata.json
  ci-operator/step-registry/distributed-tracing/tests/common/acceptance/distributed-tracing-tests-common-acceptance-ref.yaml
  ci-operator/step-registry/distributed-tracing/tests/common/distributed-tracing-tests-common-chain.metadata.json
  ci-operator/step-registry/distributed-tracing/tests/common/distributed-tracing-tests-common-chain.yaml
  ci-operator/step-registry/distributed-tracing/tests/common/distributed-tracing-tests-common-commands.sh
Labels: lgtm, approved, rehearsals-ack

#51310 OCP-60816 - [IPI-on-IBMCloud] install cluster under BYON with a different resource group
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.15.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.16.yaml
  ci-operator/step-registry/cucushift/installer/check/ibmcloud/resourcegroup/OWNERS
  ci-operator/step-registry/cucushift/installer/check/ibmcloud/resourcegroup/cucushift-installer-check-ibmcloud-resourcegroup-commands.sh
  ci-operator/step-registry/cucushift/installer/check/ibmcloud/resourcegroup/cucushift-installer-check-ibmcloud-resourcegroup-ref.metadata.json
  ci-operator/step-registry/cucushift/installer/check/ibmcloud/resourcegroup/cucushift-installer-check-ibmcloud-resourcegroup-ref.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/ibmcloud/ipi/proxy/cucushift-installer-rehearse-ibmcloud-ipi-proxy-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/ibmcloud/ipi/proxy/provision/cucushift-installer-rehearse-ibmcloud-ipi-proxy-provision-chain.yaml
  ci-operator/step-registry/ibmcloud/deprovision/resourcegroup/ibmcloud-deprovision-resourcegroup-commands.sh
  ci-operator/step-registry/ibmcloud/provision/vpc/resources-info/OWNERS
  ci-operator/step-registry/ibmcloud/provision/vpc/resources-info/ibmcloud-provision-vpc-resources-info-commands.sh
  ci-operator/step-registry/ibmcloud/provision/vpc/resources-info/ibmcloud-provision-vpc-resources-info-ref.metadata.json
  ci-operator/step-registry/ibmcloud/provision/vpc/resources-info/ibmcloud-provision-vpc-resources-info-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#51784 Enable the service load balancer monitor test
  ci-operator/step-registry/openshift/e2e/libvirt/test/openshift-e2e-libvirt-test-commands.sh
Labels: lgtm, approved, rehearsals-ack

#51803 Onboard openstack-k8s-operators/ci-playground repo
  ci-operator/config/openstack-k8s-operators/ci-playground/OWNERS
  ci-operator/config/openstack-k8s-operators/ci-playground/openstack-k8s-operators-ci-playground-main.yaml
  ci-operator/jobs/openstack-k8s-operators/ci-playground/OWNERS
  ci-operator/jobs/openstack-k8s-operators/ci-playground/openstack-k8s-operators-ci-playground-main-presubmits.yaml
  core-services/prow/02_config/openstack-k8s-operators/ci-playground/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#51706 Skip the host FIPS validation for agent install steps
  ci-operator/step-registry/baremetal/lab/agent/install/baremetal-lab-agent-install-commands.sh
  ci-operator/step-registry/baremetal/lab/agent/install/baremetal-lab-agent-install-ref.yaml
  ci-operator/step-registry/cucushift/agent/vsphere/conf/cucushift-agent-vsphere-conf-commands.sh
  ci-operator/step-registry/cucushift/agent/vsphere/conf/cucushift-agent-vsphere-conf-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#51780 HOSTEDCP-1565: app.ci: hypershift: add image puller sa
  clusters/app.ci/registry-access/hypershift/admin_manifest.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#51065 Prow Configurations: Onboarding new component `troubleshooting-panel-console-plugin`
  ci-operator/config/openshift/troubleshooting-panel-console-plugin/OWNERS
  ci-operator/config/openshift/troubleshooting-panel-console-plugin/openshift-troubleshooting-panel-console-plugin-main.yaml
  ci-operator/jobs/openshift/troubleshooting-panel-console-plugin/OWNERS
  ci-operator/jobs/openshift/troubleshooting-panel-console-plugin/openshift-troubleshooting-panel-console-plugin-main-postsubmits.yaml
  ci-operator/jobs/openshift/troubleshooting-panel-console-plugin/openshift-troubleshooting-panel-console-plugin-main-presubmits.yaml
  core-services/prow/02_config/openshift/troubleshooting-panel-console-plugin/OWNERS
  core-services/prow/02_config/openshift/troubleshooting-panel-console-plugin/_pluginconfig.yaml
  core-services/prow/02_config/openshift/troubleshooting-panel-console-plugin/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#51745 Update rhdh nightly job : add Slack Notifications for Nightly Job
  ci-operator/jobs/janus-idp/backstage-showcase/janus-idp-backstage-showcase-main-periodics.yaml
  ci-operator/step-registry/janus-idp/backstage-showcase/janus-idp-backstage-showcase-commands.sh
Labels: lgtm, approved, rehearsals-ack
