Repository openshift/release, pull requests merged in 2024-03, with the labels that each got.

#49328 Add support of non standard ports (again)
  ci-operator/step-registry/baremetalds/devscripts/proxy/baremetalds-devscripts-proxy-commands.sh
  ci-operator/step-registry/baremetalds/devscripts/setup/baremetalds-devscripts-setup-commands.sh
  ci-operator/step-registry/hypershift/agent/create/proxy/hypershift-agent-create-proxy-commands.sh
  ci-operator/step-registry/ofcir/acquire/ofcir-acquire-commands.sh
Labels: lgtm, approved, rehearsals-ack

#49403 OCPQE-17833: Remove cypress tests on vsphere ci jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#49410 Fix test report file name
  ci-operator/step-registry/cucushift/upgrade/check/cucushift-upgrade-check-commands.sh
  ci-operator/step-registry/cucushift/upgrade/prepare/cucushift-upgrade-prepare-commands.sh
Labels: lgtm, approved, rehearsals-ack

#49391 Use trusted certificates in RHTAP
  ci-operator/step-registry/redhat-appstudio/openshift-trusted-ca/OWNERS
  ci-operator/step-registry/redhat-appstudio/openshift-trusted-ca/redhat-appstudio-openshift-trusted-ca-commands.sh
  ci-operator/step-registry/redhat-appstudio/openshift-trusted-ca/redhat-appstudio-openshift-trusted-ca-ref.metadata.json
  ci-operator/step-registry/redhat-appstudio/openshift-trusted-ca/redhat-appstudio-openshift-trusted-ca-ref.yaml
  ci-operator/step-registry/redhat-appstudio/rhtap-installer/install-rhtap/redhat-appstudio-rhtap-installer-install-rhtap-commands.sh
  ci-operator/step-registry/redhat-appstudio/rhtap-installer/redhat-appstudio-rhtap-installer-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#49406 Changed the cluster profile of 4.16 ppc64le
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__ppc64le-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#49417 Enable TPA in RHTAP CI
  ci-operator/step-registry/redhat-appstudio/rhtap-installer/install-rhtap/redhat-appstudio-rhtap-installer-install-rhtap-commands.sh
Labels: lgtm, approved, rehearsals-ack

#49397 qci-appci: generate jwt tokens
  clusters/app.ci/assets/admin_qci-appci.yaml
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#49425 Revert "add warning for loki"
  ci-operator/step-registry/ipi/install/hosted-loki/ipi-install-hosted-loki-commands.sh
Labels: lgtm, approved, rehearsals-ack

#49434 KMM: use the local webhook server image
  ci-operator/config/rh-ecosystem-edge/kernel-module-management/rh-ecosystem-edge-kernel-module-management-main.yaml
Labels: lgtm, approved, rehearsals-ack

#49416 Add 4.16 ocp-e2e-ovn-remote-libvirt-s390x-heterogeneous nightly
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.16.yaml
  ci-operator/jobs/openshift/multiarch/openshift-multiarch-master-periodics.yaml
  ci-operator/step-registry/upi/libvirt/install/heterogeneous/upi-libvirt-install-heterogeneous-commands.sh
  ci-operator/step-registry/upi/libvirt/install/heterogeneous/upi-libvirt-install-heterogeneous-ref.yaml
  ci-operator/step-registry/upi/libvirt/install/install/upi-libvirt-install-install-commands.sh
  ci-operator/step-registry/upi/libvirt/install/install/upi-libvirt-install-install-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#49431 MGMT-17099: Fix recert rename containers not stopping
  ci-operator/step-registry/baremetalds/sno/rename/baremetalds-sno-rename-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#49383 Add i18n validation
  ci-operator/config/openshift/networking-console-plugin/openshift-networking-console-plugin-main.yaml
Labels: lgtm, approved, rehearsals-ack

#49437 openshift-ci clusterpool: networkType=>OVNKubernetes
  clusters/hive/pools/openshift-ci/install-config-aws-us-east-1_secret.yaml
  clusters/hive/pools/openshift-ci/install-config-aws-us-west-1_secret.yaml
Labels: lgtm, approved, rehearsals-ack

#49127 Move cluster profiles config into ci-operator/step-registry
  Makefile
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  ci-operator/step-registry/cluster-profiles/OWNERS
  ci-operator/step-registry/cluster-profiles/README.md
  ci-operator/step-registry/cluster-profiles/cluster-profiles-config.metadata.json
  ci-operator/step-registry/cluster-profiles/cluster-profiles-config.yaml
Labels: lgtm, approved, rehearsals-ack

#45524 JWS onboarding on OCP-CI
  ci-operator/config/jws-qe/interop-ocp-ci/OWNERS
  ci-operator/config/jws-qe/interop-ocp-ci/README.md
  ci-operator/config/jws-qe/interop-ocp-ci/jws-qe-interop-ocp-ci-main__ocp-4.14-lp-interop.yaml
  ci-operator/config/jws-qe/interop-ocp-ci/jws-qe-interop-ocp-ci-main__ocp-4.15-lp-interop.yaml
  ci-operator/config/jws-qe/interop-ocp-ci/jws-qe-interop-ocp-ci-main__ocp-4.16-lp-interop.yaml
  ci-operator/jobs/jws-qe/interop-ocp-ci/OWNERS
  ci-operator/jobs/jws-qe/interop-ocp-ci/jws-qe-interop-ocp-ci-main-periodics.yaml
  ci-operator/step-registry/jboss-web-server/OWNERS
  ci-operator/step-registry/jboss-web-server/lp-interop-tests/OWNERS
  ci-operator/step-registry/jboss-web-server/lp-interop-tests/README.md
  ci-operator/step-registry/jboss-web-server/lp-interop-tests/jboss-web-server-lp-interop-tests-commands.sh
  ci-operator/step-registry/jboss-web-server/lp-interop-tests/jboss-web-server-lp-interop-tests-ref.metadata.json
  ci-operator/step-registry/jboss-web-server/lp-interop-tests/jboss-web-server-lp-interop-tests-ref.yaml
  core-services/prow/02_config/jws-qe/interop-ocp-ci/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#49356 Run hypershift-aws-conformance, not hypershift-aws-e2e-external in CNO
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-master.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.14.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.15.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.16.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.17.yaml
Labels: lgtm, approved, rehearsals-ack

#49355 volsync-addon-ctlr ffwd to release-2.11
  ci-operator/config/stolostron/volsync-addon-controller/stolostron-volsync-addon-controller-main.yaml
Labels: lgtm, approved, rehearsals-ack

#49386 Trust Konflux for CertPolicy and IamPolicy
  core-services/prow/02_config/_plugins.yaml
  core-services/prow/02_config/stolostron/cert-policy-controller/_pluginconfig.yaml
  core-services/prow/02_config/stolostron/iam-policy-controller/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#49442 qci-appci: add probes into its deployment
  clusters/app.ci/assets/admin_qci-appci.yaml
Labels: lgtm, approved, rehearsals-ack

#49396 stackrox: release 4.4 add ocp415 tests
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-4.4__ocp-4-15.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-4.4-postsubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-4.4-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#49348 migrating openshift-preflight jobs from 4.14 to 4.15
  ci-operator/config/redhat-openshift-ecosystem/openshift-preflight/redhat-openshift-ecosystem-openshift-preflight-main__4.15.yaml
  ci-operator/jobs/redhat-openshift-ecosystem/openshift-preflight/redhat-openshift-ecosystem-openshift-preflight-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#49448 add kubeconfig to test command if provided by pre-step
  ci-operator/step-registry/osde2e/test/osde2e-test-commands.sh
Labels: lgtm, approved, rehearsals-ack

#49444 PERFSCALE-2870
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aro-4.13-nightly-x86-upi.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.13-nightly-arm.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.13-nightly-x86-loaded-upgrade-from-4.12.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.13-nightly-x86-sno.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.13-nightly-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.14-nightly-arm.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.14-nightly-x86-loaded-upgrade-from-4.12.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.14-nightly-x86-sno.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.14-nightly-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.15-nightly-arm.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.15-nightly-x86-loaded-upgrade-from-4.14.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.15-nightly-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__azure-4.15-nightly-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__gcp-4.12-nightly-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__gcp-4.13-nightly-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__gcp-4.14-nightly-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__gcp-4.15-nightly-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa-4.12-candidate-x86-loaded-upgrade-from-4.12.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa-4.12-nightly-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa-4.13-candidate-x86-loaded-upgrade-from-4.12.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa-4.13-nightly-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa-4.14-ec-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa-4.14-nightly-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa_hcp-4.14-nightly-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa_hcp-4.14-stable-x86-loaded-upgrade-from-4.14.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-periodics.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#49447 Inform about new cluster profiles config location
  core-services/cluster-profiles/OWNERS
  core-services/cluster-profiles/README.md
Labels: lgtm, approved, rehearsals-ack

#49318 [opendatahub-io/notebooks] Update image stream tags
  ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-2023a.yaml
  ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-2023b.yaml
  ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-main.yaml
Labels: lgtm, approved, rehearsals-ack

#48398 Revert "[opendatahub-io/notebooks] Disable CI checks for anaconda bas…
  ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-main.yaml
  ci-operator/jobs/opendatahub-io/notebooks/opendatahub-io-notebooks-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#49454 updating openshift-preflight jobs to use go 1.21
  ci-operator/config/redhat-openshift-ecosystem/openshift-preflight/redhat-openshift-ecosystem-openshift-preflight-main__4.12.yaml
  ci-operator/config/redhat-openshift-ecosystem/openshift-preflight/redhat-openshift-ecosystem-openshift-preflight-main__4.15.yaml
Labels: lgtm, approved, rehearsals-ack

#45045 OCPBUGS-25119: Add security scan for machine-api-provider-powervs repository
  ci-operator/config/openshift/machine-api-provider-powervs/openshift-machine-api-provider-powervs-main.yaml
  ci-operator/config/openshift/machine-api-provider-powervs/openshift-machine-api-provider-powervs-release-4.10.yaml
  ci-operator/config/openshift/machine-api-provider-powervs/openshift-machine-api-provider-powervs-release-4.11.yaml
  ci-operator/config/openshift/machine-api-provider-powervs/openshift-machine-api-provider-powervs-release-4.12.yaml
  ci-operator/config/openshift/machine-api-provider-powervs/openshift-machine-api-provider-powervs-release-4.13.yaml
  ci-operator/config/openshift/machine-api-provider-powervs/openshift-machine-api-provider-powervs-release-4.14.yaml
  ci-operator/config/openshift/machine-api-provider-powervs/openshift-machine-api-provider-powervs-release-4.15.yaml
  ci-operator/config/openshift/machine-api-provider-powervs/openshift-machine-api-provider-powervs-release-4.16.yaml
  ci-operator/jobs/openshift/machine-api-provider-powervs/openshift-machine-api-provider-powervs-main-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-provider-powervs/openshift-machine-api-provider-powervs-release-4.10-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-provider-powervs/openshift-machine-api-provider-powervs-release-4.11-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-provider-powervs/openshift-machine-api-provider-powervs-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-provider-powervs/openshift-machine-api-provider-powervs-release-4.13-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-provider-powervs/openshift-machine-api-provider-powervs-release-4.14-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-provider-powervs/openshift-machine-api-provider-powervs-release-4.15-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-provider-powervs/openshift-machine-api-provider-powervs-release-4.16-presubmits.yaml
Labels: lgtm, approved, jira/valid-bug, rehearsals-ack, jira/valid-reference

#49456 keda: adjust verify-codegen copy command to accommodate newer codegen script requirements
  ci-operator/config/openshift/kedacore-keda/openshift-kedacore-keda-main.yaml
Labels: lgtm, approved, rehearsals-ack

#49050 telco5g: add checkout submodules logic if the PR associated with the job is from the same repo as the submodule
  ci-operator/step-registry/telco5g/cnf/tests/telco5g-cnf-tests-commands.sh
Labels: lgtm, approved, rehearsals-ack

#49191 telco5g: make PULL_URL and PR_URLS variables avilable in cnf-features-deploy scripts
  ci-operator/step-registry/telco5g/cnf/tests/telco5g-cnf-tests-commands.sh
Labels: lgtm, approved, rehearsals-ack

#49455 Add 4.15 job for operator certification pipeline
  ci-operator/config/redhat-openshift-ecosystem/certified-operators-prod/redhat-openshift-ecosystem-certified-operators-prod-ocp-4.15.yaml
  ci-operator/config/redhat-openshift-ecosystem/preflight/redhat-openshift-ecosystem-preflight-ocp-4.15.yaml
  ci-operator/jobs/redhat-openshift-ecosystem/certified-operators-prod/redhat-openshift-ecosystem-certified-operators-prod-ocp-4.15-periodics.yaml
  ci-operator/jobs/redhat-openshift-ecosystem/preflight/redhat-openshift-ecosystem-preflight-ocp-4.15-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#49460 OCPQE-19629 Add env variable for step to support multi-arch
  ci-operator/step-registry/release-qe-tests/release-qe-tests-commands.sh
  ci-operator/step-registry/release-qe-tests/release-qe-tests-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#49465 Cleanup upgrade tags that have optimized
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly-4.11-upgrade-from-aro.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly-4.11-upgrade-from-stable-4.10.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly-4.11-upgrade-from-stable-4.11.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__arm64-nightly-4.11-upgrade-from-stable-4.10.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__arm64-nightly-4.11-upgrade-from-stable-4.11.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-aro.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-stable-4.11.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__arm64-nightly-4.12-upgrade-from-stable-4.11.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__arm64-nightly-4.12-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-4.13-upgrade-from-aro.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-4.13-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-4.13-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-nightly-4.13-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-nightly-4.13-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__multi-nightly-4.13-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__multi-nightly-4.13-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly-4.14-upgrade-from-aro.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly-4.14-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly-4.14-upgrade-from-stable-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly-4.14-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly-4.14-upgrade-from-stable-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-nightly-4.14-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-nightly-4.14-upgrade-from-stable-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly-4.15-upgrade-from-aro.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly-4.15-upgrade-from-stable-4.1.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly-4.15-upgrade-from-stable-4.10.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly-4.15-upgrade-from-stable-4.11.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly-4.15-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly-4.15-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly-4.15-upgrade-from-stable-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly-4.15-upgrade-from-stable-4.15.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly-4.15-upgrade-from-stable-4.2.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly-4.15-upgrade-from-stable-4.3.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly-4.15-upgrade-from-stable-4.4.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly-4.15-upgrade-from-stable-4.5.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly-4.15-upgrade-from-stable-4.6.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly-4.15-upgrade-from-stable-4.7.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly-4.15-upgrade-from-stable-4.8.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly-4.15-upgrade-from-stable-4.9.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-stable-4.15-upgrade-from-stable-4.10.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-stable-4.15-upgrade-from-stable-4.11.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-stable-4.15-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__arm64-nightly-4.15-upgrade-from-stable-4.10.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__arm64-nightly-4.15-upgrade-from-stable-4.11.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__arm64-nightly-4.15-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__arm64-nightly-4.15-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__arm64-nightly-4.15-upgrade-from-stable-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__arm64-stable-4.15-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__multi-nightly-4.15-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__multi-nightly-4.15-upgrade-from-stable-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly-4.16-upgrade-from-stable-4.15.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__arm64-nightly-4.16-upgrade-from-stable-4.15.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__multi-nightly-4.16-upgrade-from-stable-4.15.yaml
Labels: lgtm, approved, rehearsals-ack

#49468 Add missed disconnected tag for disconnected jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly-4.11-upgrade-from-stable-4.10.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly-4.11-upgrade-from-stable-4.11.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__arm64-nightly-4.11-upgrade-from-stable-4.10.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__arm64-nightly-4.11-upgrade-from-stable-4.11.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-stable-4.11.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__arm64-nightly-4.12-upgrade-from-stable-4.11.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__arm64-nightly-4.12-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-4.13-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-4.13-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-nightly-4.13-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-nightly-4.13-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly-4.14-upgrade-from-stable-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly-4.14-upgrade-from-stable-4.14.yaml
Labels: lgtm, approved, rehearsals-ack

#47677 update code to run apf customized workflow
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.15-nightly-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.16-nightly-x86.yaml
  ci-operator/step-registry/openshift-qe/run-api-apf-customized-flowcontrol/OWNERS
  ci-operator/step-registry/openshift-qe/run-api-apf-customized-flowcontrol/openshift-qe-run-api-apf-customized-flowcontrol-chain.metadata.json
  ci-operator/step-registry/openshift-qe/run-api-apf-customized-flowcontrol/openshift-qe-run-api-apf-customized-flowcontrol-chain.yaml
  ci-operator/step-registry/openshift-qe/run-api-apf-customized-flowcontrol/openshift-qe-run-api-apf-customized-flowcontrol-commands.sh
  ci-operator/step-registry/openshift-qe/run-api-apf-customized-flowcontrol/openshift-qe-run-api-apf-customized-flowcontrol-ref.metadata.json
  ci-operator/step-registry/openshift-qe/run-api-apf-customized-flowcontrol/openshift-qe-run-api-apf-customized-flowcontrol-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#49299 Adding slack notification to hive long duration cases for 4.14 - 4.16.
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#49235 [ibmcloud] fix step check-ibmcloud-destroy result is FAILURE
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.15.yaml
  ci-operator/step-registry/cucushift/installer/check/ibmcloud/destroy/cucushift-installer-check-ibmcloud-destroy-commands.sh
Labels: lgtm, approved, rehearsals-ack

#49409 Serverfoundation fast forward backplane 2.6
  ci-operator/config/stolostron/cluster-proxy-addon/stolostron-cluster-proxy-addon-backplane-2.1.yaml
  ci-operator/config/stolostron/cluster-proxy-addon/stolostron-cluster-proxy-addon-backplane-2.2.yaml
  ci-operator/config/stolostron/cluster-proxy-addon/stolostron-cluster-proxy-addon-backplane-2.3.yaml
  ci-operator/config/stolostron/cluster-proxy-addon/stolostron-cluster-proxy-addon-backplane-2.4.yaml
  ci-operator/config/stolostron/cluster-proxy-addon/stolostron-cluster-proxy-addon-backplane-2.5.yaml
  ci-operator/config/stolostron/cluster-proxy-addon/stolostron-cluster-proxy-addon-backplane-2.6.yaml
  ci-operator/config/stolostron/cluster-proxy-addon/stolostron-cluster-proxy-addon-main.yaml
  ci-operator/config/stolostron/cluster-proxy-addon/stolostron-cluster-proxy-addon-release-2.6.yaml
  ci-operator/config/stolostron/cluster-proxy/stolostron-cluster-proxy-backplane-2.1.yaml
  ci-operator/config/stolostron/cluster-proxy/stolostron-cluster-proxy-backplane-2.2.yaml
  ci-operator/config/stolostron/cluster-proxy/stolostron-cluster-proxy-backplane-2.3.yaml
  ci-operator/config/stolostron/cluster-proxy/stolostron-cluster-proxy-backplane-2.4.yaml
  ci-operator/config/stolostron/cluster-proxy/stolostron-cluster-proxy-backplane-2.5.yaml
  ci-operator/config/stolostron/cluster-proxy/stolostron-cluster-proxy-backplane-2.6.yaml
  ci-operator/config/stolostron/cluster-proxy/stolostron-cluster-proxy-main.yaml
  ci-operator/config/stolostron/cluster-proxy/stolostron-cluster-proxy-release-2.6.yaml
  ci-operator/config/stolostron/clusterlifecycle-state-metrics/stolostron-clusterlifecycle-state-metrics-main.yaml
  ci-operator/config/stolostron/klusterlet-addon-controller/stolostron-klusterlet-addon-controller-main.yaml
  ci-operator/config/stolostron/klusterlet-addon-controller/stolostron-klusterlet-addon-controller-release-2.11.yaml
  ci-operator/config/stolostron/managed-serviceaccount-e2e/stolostron-managed-serviceaccount-e2e-backplane-2.6.yaml
  ci-operator/config/stolostron/managed-serviceaccount-e2e/stolostron-managed-serviceaccount-e2e-main.yaml
  ci-operator/config/stolostron/managed-serviceaccount/stolostron-managed-serviceaccount-main.yaml
  ci-operator/config/stolostron/managedcluster-import-controller/stolostron-managedcluster-import-controller-backplane-2.6.yaml
  ci-operator/config/stolostron/managedcluster-import-controller/stolostron-managedcluster-import-controller-main.yaml
  ci-operator/config/stolostron/multicloud-operators-foundation/stolostron-multicloud-operators-foundation-backplane-2.6.yaml
  ci-operator/config/stolostron/multicloud-operators-foundation/stolostron-multicloud-operators-foundation-main.yaml
  ci-operator/jobs/stolostron/cluster-proxy-addon/stolostron-cluster-proxy-addon-release-2.6-postsubmits.yaml
  ci-operator/jobs/stolostron/cluster-proxy-addon/stolostron-cluster-proxy-addon-release-2.6-presubmits.yaml
  ci-operator/jobs/stolostron/cluster-proxy/stolostron-cluster-proxy-release-2.6-postsubmits.yaml
  ci-operator/jobs/stolostron/cluster-proxy/stolostron-cluster-proxy-release-2.6-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#49471 Cleanup tags that have optimized in to-multiarch tests
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__arm64-nightly.yaml
Labels: lgtm, approved, rehearsals-ack

#49426 test: osdfm move podisolation tests to target main/canary sectors
  ci-operator/step-registry/osd-ccs/fleet-manager/test/osd-ccs-fleet-manager-test-commands.sh
Labels: lgtm, approved, rehearsals-ack

#48183 NO-ISSUE: Fix assisted-service gather when there's >1 virtual network
  ci-operator/step-registry/assisted/baremetal/operator/gather/assisted-baremetal-operator-gather-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#49182 This commit will change the default merge settings.
  core-services/prow/02_config/opendatahub-io/model-registry/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#49475 NO-ISSUE: Update assisted-cicd owners
  OWNERS_ALIASES
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#49477 Cleanup tags that have optimized in sdn-migration-ovn tests
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-nightly.yaml
Labels: lgtm, approved, rehearsals-ack

#49470 chore: add oc client in windows tests
  ci-operator/config/kubevirt/kubevirt-tekton-tasks/kubevirt-kubevirt-tekton-tasks-main.yaml
Labels: lgtm, approved, rehearsals-ack

#49480 make the yamllint test optional
  ci-operator/config/redhat-appstudio/rhtap-installer/redhat-appstudio-rhtap-installer-main.yaml
  ci-operator/jobs/redhat-appstudio/rhtap-installer/redhat-appstudio-rhtap-installer-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#49481 fix: add slack notification for powermon staging job
  ci-operator/jobs/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-v1alpha1-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#49435 Fix AWS SNO recert containers not properly stopping
  ci-operator/step-registry/single-node/recert/single-node-recert-commands.sh
Labels: lgtm, approved, rehearsals-ack

#49461 telco5g: Add CNF Baremetal tests job for 4.15 release branch
  ci-operator/config/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-release-4.15.yaml
  ci-operator/jobs/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-release-4.15-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#49429 use devsandboxci-aws cluster profile for all toolchain repos
  ci-operator/config/codeready-toolchain/host-operator/codeready-toolchain-host-operator-master.yaml
  ci-operator/config/codeready-toolchain/member-operator/codeready-toolchain-member-operator-master.yaml
  ci-operator/config/codeready-toolchain/registration-service/codeready-toolchain-registration-service-master.yaml
  ci-operator/jobs/codeready-toolchain/host-operator/codeready-toolchain-host-operator-master-presubmits.yaml
  ci-operator/jobs/codeready-toolchain/member-operator/codeready-toolchain-member-operator-master-presubmits.yaml
  ci-operator/jobs/codeready-toolchain/registration-service/codeready-toolchain-registration-service-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#49462 telco5g: SRIOV Add CNF Baremetal tests job for 4.15 release branch
  ci-operator/config/openshift/sriov-network-operator/openshift-sriov-network-operator-release-4.15.yaml
  ci-operator/jobs/openshift/sriov-network-operator/openshift-sriov-network-operator-release-4.15-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#49487 cluster-capi-operator: add build testjob
  ci-operator/config/openshift/cluster-capi-operator/openshift-cluster-capi-operator-main.yaml
  ci-operator/config/openshift/cluster-capi-operator/openshift-cluster-capi-operator-release-4.16.yaml
  ci-operator/config/openshift/cluster-capi-operator/openshift-cluster-capi-operator-release-4.17.yaml
  ci-operator/jobs/openshift/cluster-capi-operator/openshift-cluster-capi-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/cluster-capi-operator/openshift-cluster-capi-operator-release-4.16-presubmits.yaml
  ci-operator/jobs/openshift/cluster-capi-operator/openshift-cluster-capi-operator-release-4.17-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#48633 add logic to auto clean stale Ho deploys
  ci-operator/step-registry/hypershift/ibmcloud/cluster-claim/hypershift-ibmcloud-cluster-claim-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#49469 Use hypershift-cli as base image
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
  clusters/app.ci/supplemental-ci-images/hypershift/hypershift-cli.yaml
Labels: lgtm, approved, rehearsals-ack

#49483 MULTIARCH-4348: Rename mmo to mto
  ci-operator/config/openshift/multiarch-tuning-operator/.config.prowgen
  ci-operator/config/openshift/multiarch-tuning-operator/OWNERS
  ci-operator/config/openshift/multiarch-tuning-operator/openshift-multiarch-tuning-operator-main.yaml
  ci-operator/config/openshift/multiarch-tuning-operator/openshift-multiarch-tuning-operator-release-4.16.yaml
  ci-operator/config/openshift/multiarch-tuning-operator/openshift-multiarch-tuning-operator-v0.0.1.yaml
  ci-operator/jobs/openshift/multiarch-tuning-operator/OWNERS
  ci-operator/jobs/openshift/multiarch-tuning-operator/openshift-multiarch-tuning-operator-main-postsubmits.yaml
  ci-operator/jobs/openshift/multiarch-tuning-operator/openshift-multiarch-tuning-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/multiarch-tuning-operator/openshift-multiarch-tuning-operator-release-4.16-postsubmits.yaml
  ci-operator/jobs/openshift/multiarch-tuning-operator/openshift-multiarch-tuning-operator-release-4.16-presubmits.yaml
  ci-operator/jobs/openshift/multiarch-tuning-operator/openshift-multiarch-tuning-operator-v0.0.1-postsubmits.yaml
  ci-operator/jobs/openshift/multiarch-tuning-operator/openshift-multiarch-tuning-operator-v0.0.1-presubmits.yaml
  core-services/prow/02_config/openshift/multiarch-tuning-operator/OWNERS
  core-services/prow/02_config/openshift/multiarch-tuning-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/multiarch-tuning-operator/_prowconfig.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#49315 Adding remaining openshift-docs branches to Prow
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-build-docs-1.0.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-build-docs-1.1.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-build-docs-main.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-gitops-docs-1.10.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-gitops-docs-1.11.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-gitops-docs-1.12.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-gitops-docs-1.8.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-gitops-docs-1.9.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-gitops-docs-main.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-opp-docs.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-pipelines-docs-1.10.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-pipelines-docs-1.11.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-pipelines-docs-1.12.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-pipelines-docs-1.13.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-pipelines-docs-1.14.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-pipelines-docs-main.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-rhde-docs-main.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-serverless-docs-1.28.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-serverless-docs-1.29.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-serverless-docs-1.30.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-serverless-docs-1.31.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-serverless-docs-1.32.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-serverless-docs-main.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-service-mesh-docs-main.yaml
  ci-operator/jobs/openshift/openshift-docs/openshift-openshift-docs-build-docs-1.0-presubmits.yaml
  ci-operator/jobs/openshift/openshift-docs/openshift-openshift-docs-build-docs-1.1-presubmits.yaml
  ci-operator/jobs/openshift/openshift-docs/openshift-openshift-docs-build-docs-main-presubmits.yaml
  ci-operator/jobs/openshift/openshift-docs/openshift-openshift-docs-gitops-docs-1.10-presubmits.yaml
  ci-operator/jobs/openshift/openshift-docs/openshift-openshift-docs-gitops-docs-1.11-presubmits.yaml
  ci-operator/jobs/openshift/openshift-docs/openshift-openshift-docs-gitops-docs-1.12-presubmits.yaml
  ci-operator/jobs/openshift/openshift-docs/openshift-openshift-docs-gitops-docs-1.8-presubmits.yaml
  ci-operator/jobs/openshift/openshift-docs/openshift-openshift-docs-gitops-docs-1.9-presubmits.yaml
  ci-operator/jobs/openshift/openshift-docs/openshift-openshift-docs-gitops-docs-main-presubmits.yaml
  ci-operator/jobs/openshift/openshift-docs/openshift-openshift-docs-opp-docs-presubmits.yaml
  ci-operator/jobs/openshift/openshift-docs/openshift-openshift-docs-pipelines-docs-1.10-presubmits.yaml
  ci-operator/jobs/openshift/openshift-docs/openshift-openshift-docs-pipelines-docs-1.11-presubmits.yaml
  ci-operator/jobs/openshift/openshift-docs/openshift-openshift-docs-pipelines-docs-1.12-presubmits.yaml
  ci-operator/jobs/openshift/openshift-docs/openshift-openshift-docs-pipelines-docs-1.13-presubmits.yaml
  ci-operator/jobs/openshift/openshift-docs/openshift-openshift-docs-pipelines-docs-1.14-presubmits.yaml
  ci-operator/jobs/openshift/openshift-docs/openshift-openshift-docs-pipelines-docs-main-presubmits.yaml
  ci-operator/jobs/openshift/openshift-docs/openshift-openshift-docs-rhde-docs-main-presubmits.yaml
  ci-operator/jobs/openshift/openshift-docs/openshift-openshift-docs-serverless-docs-1.28-presubmits.yaml
  ci-operator/jobs/openshift/openshift-docs/openshift-openshift-docs-serverless-docs-1.29-presubmits.yaml
  ci-operator/jobs/openshift/openshift-docs/openshift-openshift-docs-serverless-docs-1.30-presubmits.yaml
  ci-operator/jobs/openshift/openshift-docs/openshift-openshift-docs-serverless-docs-1.31-presubmits.yaml
  ci-operator/jobs/openshift/openshift-docs/openshift-openshift-docs-serverless-docs-1.32-presubmits.yaml
  ci-operator/jobs/openshift/openshift-docs/openshift-openshift-docs-serverless-docs-main-presubmits.yaml
  ci-operator/jobs/openshift/openshift-docs/openshift-openshift-docs-service-mesh-docs-main-presubmits.yaml
  ci-operator/step-registry/openshift-docs/portal/openshift-docs-portal-commands.sh
Labels: lgtm, approved, rehearsals-ack

#49499 Add preprod job and config for 4.15
  ci-operator/config/redhat-openshift-ecosystem/certified-operators-preprod/redhat-openshift-ecosystem-certified-operators-preprod-ocp-4.15.yaml
  ci-operator/jobs/redhat-openshift-ecosystem/certified-operators-preprod/redhat-openshift-ecosystem-certified-operators-preprod-ocp-4.15-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#49388 PERFSCALE-2870 - Reduce payload jobs to once per week
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.15-nightly-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.16-nightly-x86.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#49507 Reenable compress file types
  core-services/prow/02_config/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#49286 Add dotnet config for zstream
  ci-operator/config/sclorg/ansible-tests/sclorg-ansible-tests-master__dotnet-ocp4.13-lp-interop.yaml
  ci-operator/config/sclorg/ansible-tests/sclorg-ansible-tests-master__dotnet-ocp4.14-lp-interop.yaml
  ci-operator/jobs/sclorg/ansible-tests/sclorg-ansible-tests-master-periodics.yaml
  ci-operator/jobs/sclorg/ansible-tests/sclorg-ansible-tests-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#49439 ACM-10217 Update branch forwarding for stolostron/console
  ci-operator/config/stolostron/console/stolostron-console-backplane-2.6.yaml
  ci-operator/config/stolostron/console/stolostron-console-main.yaml
  ci-operator/config/stolostron/console/stolostron-console-release-2.11.yaml
Labels: lgtm, approved, rehearsals-ack

#49466 Adding firewatch `success_rules` to ROSA Classic scenarios
  ci-operator/config/3scale-qe/3scale-deploy/3scale-qe-3scale-deploy-main__3scale-amp-ocp4.14-lp-rosa-classic.yaml
  ci-operator/config/amq-streams-qe/strimzi-kafka-operator/amq-streams-qe-strimzi-kafka-operator-main__amq-streams-ocp4.14-lp-rosa-classic.yaml
  ci-operator/config/jboss-fuse/camel-k-test-container/jboss-fuse-camel-k-test-container-main__camel-k-ocp4.14-lp-rosa-classic.yaml
  ci-operator/config/maistra/maistra-test-tool/maistra-maistra-test-tool-main__servicemesh-ocp4.14-lp-rosa-classic.yaml
  ci-operator/config/mtc-qe/mtc-e2e-qev2/mtc-qe-mtc-e2e-qev2-master__mtc1.8-ocp4.14-lp-rosa-classic.yaml
  ci-operator/config/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-main__oadp1.3-ocp4.14-lp-rosa-classic.yaml
  ci-operator/config/rh-messaging-qe/claire/rh-messaging-qe-claire-lpt__amq-broker-ocp4.14-lp-rosa-classic.yaml
  ci-operator/config/skupperproject/skupper-openshift-smoke-test-image/skupperproject-skupper-openshift-smoke-test-image-main__service-interconnect-ocp4.14-lp-rosa-classic.yaml
Labels: lgtm, approved, rehearsals-ack

#49492 Add pull secret for quay.io/openshift/ci
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#49516 Fix replacement for multiarch tuning operator
  ci-operator/config/openshift/multiarch-tuning-operator/openshift-multiarch-tuning-operator-main.yaml
  ci-operator/config/openshift/multiarch-tuning-operator/openshift-multiarch-tuning-operator-v0.0.1.yaml
Labels: lgtm, approved, rehearsals-ack

#49351 stackrox: ocp4-15 GA'd, test on fast-4.15
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-15.yaml
Labels: lgtm, approved, rehearsals-ack

#49511 Revert "Use hypershift-cli as base image"
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
  clusters/app.ci/supplemental-ci-images/hypershift/hypershift-cli.yaml
Labels: lgtm, approved, rehearsals-ack

#49519 Deploy qci-pull-through-cache
  clusters/app.ci/quayio-pull-through-cache/qci-pull-through-cache-aws_configmap.yaml
  clusters/app.ci/quayio-pull-through-cache/qci-pull-through-cache-us-east-1.yaml
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#49495 update base image
  ci-operator/config/stolostron/grafana/stolostron-grafana-globalhub-1.2.yaml
Labels: lgtm, approved, rehearsals-ack

#48921 Add nutanix failure domain job
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/nutanix/ipi/zones/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/nutanix/ipi/zones/cucushift-installer-rehearse-nutanix-ipi-zones-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/nutanix/ipi/zones/cucushift-installer-rehearse-nutanix-ipi-zones-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/nutanix/ipi/zones/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/nutanix/ipi/zones/provision/cucushift-installer-rehearse-nutanix-ipi-zones-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/nutanix/ipi/zones/provision/cucushift-installer-rehearse-nutanix-ipi-zones-provision-chain.yaml
  ci-operator/step-registry/ipi/conf/nutanix/zones/OWNERS
  ci-operator/step-registry/ipi/conf/nutanix/zones/ipi-conf-nutanix-zones-commands.sh
  ci-operator/step-registry/ipi/conf/nutanix/zones/ipi-conf-nutanix-zones-ref.metadata.json
  ci-operator/step-registry/ipi/conf/nutanix/zones/ipi-conf-nutanix-zones-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#49527 update base image to ubi9
  ci-operator/config/stolostron/grafana/stolostron-grafana-globalhub-1.2.yaml
Labels: lgtm, approved, rehearsals-ack

#49407 CORS-2591: Add support to BYO hosted zones while deploying OpenShift to a shared VPC (XPN) in GCP
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__multi-nightly.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.16.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/xpn/minimal-permission/byo-hosted-zone/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/xpn/minimal-permission/byo-hosted-zone/cucushift-installer-rehearse-gcp-ipi-xpn-minimal-permission-byo-hosted-zone-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/xpn/minimal-permission/byo-hosted-zone/cucushift-installer-rehearse-gcp-ipi-xpn-minimal-permission-byo-hosted-zone-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/xpn/minimal-permission/byo-hosted-zone/deprovision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/xpn/minimal-permission/byo-hosted-zone/deprovision/cucushift-installer-rehearse-gcp-ipi-xpn-minimal-permission-byo-hosted-zone-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/xpn/minimal-permission/byo-hosted-zone/deprovision/cucushift-installer-rehearse-gcp-ipi-xpn-minimal-permission-byo-hosted-zone-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/xpn/minimal-permission/byo-hosted-zone/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/xpn/minimal-permission/byo-hosted-zone/provision/cucushift-installer-rehearse-gcp-ipi-xpn-minimal-permission-byo-hosted-zone-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/xpn/minimal-permission/byo-hosted-zone/provision/cucushift-installer-rehearse-gcp-ipi-xpn-minimal-permission-byo-hosted-zone-provision-chain.yaml
  ci-operator/step-registry/gcp/provision/private-dns-zone/in-service-project/gcp-provision-private-dns-zone-in-service-project-commands.sh
  ci-operator/step-registry/gcp/provision/private-dns-zone/in-service-project/gcp-provision-private-dns-zone-in-service-project-ref.yaml
  ci-operator/step-registry/gcp/provision/xpn-byo-hosted-zone-min-perm-passthrough-serviceaccount/OWNERS
  ci-operator/step-registry/gcp/provision/xpn-byo-hosted-zone-min-perm-passthrough-serviceaccount/gcp-provision-xpn-byo-hosted-zone-min-perm-passthrough-serviceaccount-commands.sh
  ci-operator/step-registry/gcp/provision/xpn-byo-hosted-zone-min-perm-passthrough-serviceaccount/gcp-provision-xpn-byo-hosted-zone-min-perm-passthrough-serviceaccount-ref.metadata.json
  ci-operator/step-registry/gcp/provision/xpn-byo-hosted-zone-min-perm-passthrough-serviceaccount/gcp-provision-xpn-byo-hosted-zone-min-perm-passthrough-serviceaccount-ref.yaml
  ci-operator/step-registry/ipi/deprovision/deprovision/ipi-deprovision-deprovision-commands.sh
  ci-operator/step-registry/ipi/install/install/ipi-install-install-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#48711 Fix issue DPTP-3146 Add MachineHealthCheck for OCP clusters
  clusters/build-clusters/01_cluster/machinehealthcheck.yaml
  clusters/build-clusters/01_cluster/openshift-machine-api/admin_build01-9hdwj-worker-us-east-1a-infra_machine_set.yaml
  clusters/build-clusters/02_cluster/machinehealthcheck.yaml
  clusters/build-clusters/02_cluster/openshift-machine-api/build0-gstfj-w-b-infra_machineset.yaml
  clusters/build-clusters/build09/machinehealthcheck.yaml
  clusters/build-clusters/build09/openshift-machine-api/machineset-worker-infra.yaml
  clusters/build-clusters/build10/machinehealthcheck.yaml
  clusters/build-clusters/common/README.md
  clusters/build-clusters/common/_machinehealthcheck.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#49252 Enable agent gather for >=4.15
  ci-operator/step-registry/cucushift/agent/gather/cucushift-agent-gather-commands.sh
Labels: lgtm, approved, rehearsals-ack

#49538 Adding ibm workflow to assist in speedy debug
  core-services/ci-chat-bot/workflows-config.yaml
Labels: lgtm, approved, rehearsals-ack

#49424 Change region for RHTAP QE Cluster profile
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: lgtm, approved, rehearsals-ack

#49524 Fix cloud filter in post upgrade check
  ci-operator/step-registry/cucushift/upgrade/check/cucushift-upgrade-check-commands.sh
Labels: lgtm, approved, rehearsals-ack

#49257 [installer-aro-wrapper] bump go version to 1.20
  ci-operator/config/openshift/installer-aro-wrapper/openshift-installer-aro-wrapper-main.yaml
  ci-operator/config/openshift/installer-aro-wrapper/openshift-installer-aro-wrapper-release-4.14.yaml
Labels: lgtm, approved, rehearsals-ack

#49544 Add quay.io pull for b09 and b10
  clusters/build-clusters/build09/assets/quayio-pull-through-cache-icsp.yaml
  clusters/build-clusters/build10/assets/quayio-pull-through-cache-icsp.yaml
Labels: lgtm, approved, rehearsals-ack

#49430 make devsandboxci-aws cluster profile private
  ci-operator/step-registry/cluster-profiles/cluster-profiles-config.yaml
Labels: lgtm, approved, rehearsals-ack

#49526 Adding aws-arm64 to the cluster-profile list
  ci-operator/step-registry/cluster-profiles/cluster-profiles-config.yaml
Labels: lgtm, approved, rehearsals-ack

#49193 vSphere - remove hard defined vlans for zones
  ci-operator/step-registry/ipi/conf/vsphere/check/ipi-conf-vsphere-check-commands.sh
  ci-operator/step-registry/ipi/conf/vsphere/lb/external/ipi-conf-vsphere-lb-external-commands.sh
Labels: lgtm, approved, rehearsals-ack

#49512 Sync CNV interop files to have same build_args
  ci-operator/config/RedHatQE/interop-testing/RedHatQE-interop-testing-cnv-4.14__cnv-odf-ocp4.14-lp-interop.yaml
Labels: lgtm, approved, rehearsals-ack

#48435 kata-containers: Switch CI pipeline repository
  ci-operator/config/kata-containers/kata-containers/kata-containers-kata-containers-main.yaml
Labels: lgtm, approved, rehearsals-ack

#49547 Adding rhde-docs-main distro to Prow CI for openshift-docs
  ci-operator/step-registry/openshift-docs/portal/openshift-docs-portal-commands.sh
Labels: lgtm, approved, rehearsals-ack

#49543 Update job to use proper cloud provider
  ci-operator/jobs/redhat-openshift-ecosystem/preflight/redhat-openshift-ecosystem-preflight-ocp-4.15-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#47872 OSASINFRA-3260: UPI installation with dualstack.
  ci-operator/config/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main__periodic-4.15.yaml
  ci-operator/config/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main__periodic-4.16.yaml
  ci-operator/jobs/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main-periodics.yaml
  ci-operator/step-registry/openstack/conf/installconfig/openstack-conf-installconfig-commands.sh
  ci-operator/step-registry/upi/install/openstack/inventory/upi-install-openstack-inventory-commands.sh
  ci-operator/step-registry/upi/install/openstack/inventory/upi-install-openstack-inventory-ref.yaml
  ci-operator/step-registry/upi/install/openstack/upi-install-openstack-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#49496 Switching cluster profile for arm64 jobs
  ci-operator/config/openshift/cluster-control-plane-machine-set-operator/openshift-cluster-control-plane-machine-set-operator-release-4.12.yaml
  ci-operator/config/openshift/cluster-control-plane-machine-set-operator/openshift-cluster-control-plane-machine-set-operator-release-4.12__periodics.yaml
  ci-operator/config/openshift/cluster-control-plane-machine-set-operator/openshift-cluster-control-plane-machine-set-operator-release-4.13__periodics.yaml
  ci-operator/config/openshift/cluster-control-plane-machine-set-operator/openshift-cluster-control-plane-machine-set-operator-release-4.14__periodics.yaml
  ci-operator/config/openshift/cluster-control-plane-machine-set-operator/openshift-cluster-control-plane-machine-set-operator-release-4.15__periodics.yaml
  ci-operator/config/openshift/cluster-control-plane-machine-set-operator/openshift-cluster-control-plane-machine-set-operator-release-4.16__periodics.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.10.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.11-upgrade-from-nightly-4.10.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.11-upgrade-from-stable-4.10.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.11.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.12-upgrade-from-nightly-4.11.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.12-upgrade-from-stable-4.11.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.12.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.13-upgrade-from-nightly-4.12.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.13-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.13.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.14-upgrade-from-nightly-4.13.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.14-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.14.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.15-upgrade-from-nightly-4.14.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.15-upgrade-from-stable-4.14.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.15.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.16.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.9.yaml
  ci-operator/jobs/openshift/cluster-control-plane-machine-set-operator/openshift-cluster-control-plane-machine-set-operator-release-4.12-periodics.yaml
  ci-operator/jobs/openshift/cluster-control-plane-machine-set-operator/openshift-cluster-control-plane-machine-set-operator-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/cluster-control-plane-machine-set-operator/openshift-cluster-control-plane-machine-set-operator-release-4.14-periodics.yaml
  ci-operator/jobs/openshift/cluster-control-plane-machine-set-operator/openshift-cluster-control-plane-machine-set-operator-release-4.15-periodics.yaml
  ci-operator/jobs/openshift/cluster-control-plane-machine-set-operator/openshift-cluster-control-plane-machine-set-operator-release-4.16-periodics.yaml
  ci-operator/jobs/openshift/multiarch/openshift-multiarch-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#49451 [LPTOCPCI-1153] Add re-trigger functionality to MTR and MTA 4.16 interop tests
  ci-operator/config/konveyor/tackle-ui-tests/konveyor-tackle-ui-tests-mta_7.0.0__mta-ocp4.16-lp-interop.yaml
  ci-operator/config/windup/windup-ui-tests/windup-windup-ui-tests-v1.2__mtr-ocp4.16-lp-interop.yaml
  ci-operator/step-registry/firewatch/ipi/aws/firewatch-ipi-aws-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#49521 Turning off chaos runs
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__4.14-nightly-arm.yaml
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__4.14-nightly.yaml
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__4.15-nightly.yaml
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__rosa-4.14-nightly.yaml
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__rosa-4.15-nightly.yaml
  ci-operator/jobs/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main-periodics.yaml
  ci-operator/jobs/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#49224 add cidr-expansion job to 4.16/4.17 for CNO
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.16.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.17.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.16-periodics.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.17-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#49274 remove 4.10 aws-ovn-windows presubmit job
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.10.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.10-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#49389 OCPBUGS-30044: test vmedia job with bonding off
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.12.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.13.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.14.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.15.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.16.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  core-services/release-controller/_releases/priv/release-ocp-4.12.json
  core-services/release-controller/_releases/priv/release-ocp-4.13.json
  core-services/release-controller/_releases/priv/release-ocp-4.14.json
  core-services/release-controller/_releases/priv/release-ocp-4.15.json
  core-services/release-controller/_releases/priv/release-ocp-4.16.json
  core-services/release-controller/_releases/release-ocp-4.12.json
  core-services/release-controller/_releases/release-ocp-4.13.json
  core-services/release-controller/_releases/release-ocp-4.14.json
  core-services/release-controller/_releases/release-ocp-4.15.json
  core-services/release-controller/_releases/release-ocp-4.16.json
Labels: lgtm, approved, jira/valid-bug, rehearsals-ack, jira/valid-reference

#49559 Adding the `release-payload-modifiers` RBAC
  clusters/app.ci/crt/admin_generated_rbac.yaml
  core-services/sync-rover-groups/README.md
  core-services/sync-rover-groups/_config.yaml
  hack/generators/release-controllers/content/rbac_resources.py
Labels: lgtm, approved, rehearsals-ack

#49449 OLS-371: Add a hypershift based e2e test that runs ols on a cluster
  ci-operator/config/openshift/lightspeed-service/openshift-lightspeed-service-main.yaml
  ci-operator/jobs/openshift/lightspeed-service/openshift-lightspeed-service-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#49557 base OLS rag image on OLS api image
  ci-operator/config/openshift/lightspeed-service/openshift-lightspeed-service-main.yaml
Labels: lgtm, approved, rehearsals-ack

#49553 OpenStack: Include dualstack-upi to the installer
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.15.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.16.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.17.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.15-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.16-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.17-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#49036 MULTIARCH-4120: Add UPI step to create libvirt network XML.
  ci-operator/step-registry/upi/conf/libvirt/OWNERS
  ci-operator/step-registry/upi/conf/libvirt/network/OWNERS
  ci-operator/step-registry/upi/conf/libvirt/network/upi-conf-libvirt-network-commands.sh
  ci-operator/step-registry/upi/conf/libvirt/network/upi-conf-libvirt-network-ref.metadata.json
  ci-operator/step-registry/upi/conf/libvirt/network/upi-conf-libvirt-network-ref.yaml
  ci-operator/step-registry/upi/conf/libvirt/upi-conf-libvirt-chain.metadata.json
  ci-operator/step-registry/upi/conf/libvirt/upi-conf-libvirt-chain.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#49354 CNF-11459: update ptp test jobs to use new telco-runner image
  ci-operator/step-registry/telco5g/ptp-cluster-setup/telco5g-ptp-cluster-setup-commands.sh
  ci-operator/step-registry/telco5g/ptp-cluster-setup/telco5g-ptp-cluster-setup-ref.yaml
  ci-operator/step-registry/telco5g/ptp/tests/telco5g-ptp-tests-commands.sh
  ci-operator/step-registry/telco5g/ptp/tests/telco5g-ptp-tests-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#49569 OLS-283: add job configuration for azure provider
  ci-operator/config/openshift/lightspeed-service/openshift-lightspeed-service-main.yaml
  ci-operator/jobs/openshift/lightspeed-service/openshift-lightspeed-service-main-periodics.yaml
  ci-operator/jobs/openshift/lightspeed-service/openshift-lightspeed-service-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#49570 Fix the dotnet repo name
  ci-operator/config/sclorg/ansible-tests/sclorg-ansible-tests-master__dotnet-ocp4.13-lp-interop.yaml
  ci-operator/jobs/sclorg/ansible-tests/sclorg-ansible-tests-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#49241 [OCPQE-19626]Add jobs to test logging 5.9
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly-openshift-logging-5.9.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly-openshift-logging-5.9.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#49550 add opeco qe in catalogd repo
  core-services/prow/02_config/openshift/operator-framework-catalogd/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#49532 [CIGolang]move CPaasrunOnly from hard-coded to optional
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly.yaml
  ci-operator/step-registry/openshift-extended/test/disruptive/openshift-extended-test-disruptive-commands.sh
  ci-operator/step-registry/openshift-extended/test/disruptive/openshift-extended-test-disruptive-ref.yaml
  ci-operator/step-registry/openshift-extended/test/longduration/openshift-extended-test-longduration-commands.sh
  ci-operator/step-registry/openshift-extended/test/longduration/openshift-extended-test-longduration-ref.yaml
  ci-operator/step-registry/openshift-extended/test/openshift-extended-test-commands.sh
  ci-operator/step-registry/openshift-extended/test/openshift-extended-test-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#49572 Cleanup tags that have optimized in arch-migration tests
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-ec.yaml
Labels: lgtm, approved, rehearsals-ack

#49575 Disable sonar check
  ci-operator/config/stolostron/grafana/stolostron-grafana-globalhub-1.0.yaml
  ci-operator/config/stolostron/grafana/stolostron-grafana-globalhub-1.2.yaml
  ci-operator/jobs/stolostron/grafana/stolostron-grafana-globalhub-1.0-postsubmits.yaml
  ci-operator/jobs/stolostron/grafana/stolostron-grafana-globalhub-1.0-presubmits.yaml
  ci-operator/jobs/stolostron/grafana/stolostron-grafana-globalhub-1.2-postsubmits.yaml
  ci-operator/jobs/stolostron/grafana/stolostron-grafana-globalhub-1.2-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#49578 make the yamllint test use the ci/config/yamllint.yaml
  ci-operator/config/redhat-appstudio/rhtap-installer/redhat-appstudio-rhtap-installer-main.yaml
Labels: lgtm, approved, rehearsals-ack

#49537 [azure] fix failure of key creation without permission
  ci-operator/step-registry/azure/provision/customer-managed-key/azure-provision-customer-managed-key-commands.sh
Labels: lgtm, approved, rehearsals-ack

#49479 Update image tag for rook master branch job
  ci-operator/config/red-hat-storage/rook/red-hat-storage-rook-master.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#49581 Cleanup jobs on EOL versions 4.10/4.11
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.10.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.11.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#49478 automate case OCP-47086
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__multi-nightly.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.14.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.15.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.16.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
  ci-operator/step-registry/azure/provision/service-principal/minimal-permission/azure-provision-service-principal-minimal-permission-commands.sh
  ci-operator/step-registry/azure/provision/service-principal/minimal-permission/azure-provision-service-principal-minimal-permission-ref.yaml
  ci-operator/step-registry/azure/provision/vnet/azure-provision-vnet-commands.sh
  ci-operator/step-registry/azure/provision/vnet/azure-provision-vnet-ref.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/private/networking-type/minimal-permission/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/private/networking-type/minimal-permission/cucushift-installer-rehearse-azure-ipi-private-networking-type-minimal-permission-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/private/networking-type/minimal-permission/cucushift-installer-rehearse-azure-ipi-private-networking-type-minimal-permission-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/private/networking-type/minimal-permission/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/private/networking-type/minimal-permission/provision/cucushift-installer-rehearse-azure-ipi-private-networking-type-minimal-permission-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/private/networking-type/minimal-permission/provision/cucushift-installer-rehearse-azure-ipi-private-networking-type-minimal-permission-provision-chain.yaml
  ci-operator/step-registry/ipi/conf/azure/resourcegroup/ipi-conf-azure-resourcegroup-commands.sh
  ci-operator/step-registry/ipi/conf/azure/resourcegroup/ipi-conf-azure-resourcegroup-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#49583 GitOps | Change `.metadata.name` for cluster pool
  clusters/hive/pools/gitops/gitops-ocp-4-12-0-amd64-aws-us-east-2_clusterpool.yaml
  clusters/hive/pools/gitops/gitops-ocp-4-13-0-amd64-aws-us-east-2_clusterpool.yaml
  clusters/hive/pools/gitops/gitops-ocp-4-14-0-amd64-aws-us-east-2_clusterpool.yaml
Labels: lgtm, approved, rehearsals-ack

#49200 [KMM] Using `src` for the base image of `operator-upgrade`.
  ci-operator/config/rh-ecosystem-edge/kernel-module-management/rh-ecosystem-edge-kernel-module-management-main.yaml
Labels: lgtm, approved, rehearsals-ack

#49105 MGMT-16961: add IP change
  ci-operator/step-registry/baremetalds/sno/rename/baremetalds-sno-rename-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#48639 MCE-disconnected: avoid hardcoding oc-mirror image
  ci-operator/step-registry/hypershift/mce/install/disconnected/hypershift-mce-install-disconnected-commands.sh
Labels: lgtm, approved, rehearsals-ack

#49582 [CIGolang]prepare for 4.17 images
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__images.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#49415 Disable the 4.15 ppc64le job
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__ppc64le-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#49551 Update _pluginconfig.yaml
  core-services/prow/02_config/red-hat-storage/_pluginconfig.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#49565 Add cluster pool for certification-pipeline
  clusters/hive/pools/rh-openshift-ecosystem/OWNERS
  clusters/hive/pools/rh-openshift-ecosystem/admins_rh-openshift-ecosystem-cluster-pool_rbac.yaml
  clusters/hive/pools/rh-openshift-ecosystem/certification-pipeline-ocp-4-15-amd64-aws-us-east-1_clusterpool.yaml
  clusters/hive/pools/rh-openshift-ecosystem/install-config-aws-us-east-1_secret.yaml
Labels: lgtm, approved, rehearsals-ack

#49586 [release-1.32] Initialize Serverless Operator CI config
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.32__412.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.32__414-aws-ovn.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.32__414-azure.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.32__414-gcp.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.32__414-hypershift.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.32__414-osd.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.32__414-single-node.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.32__414-vsphere.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.32__414.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.32__415.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.32__ocp4.14-lp-interop.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.32__ocp4.15-lp-interop.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.32__ocp4.16-lp-interop.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.32-presubmits.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#49530 Use hypershift-cli as base image
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
  clusters/app.ci/supplemental-ci-images/hypershift/hypershift-cli.yaml
Labels: lgtm, approved, rehearsals-ack

#49593 Bumping Govulncheck image to version 1.21.8
  clusters/app.ci/supplemental-ci-images/crt/govulncheck.yaml
Labels: lgtm, approved, rehearsals-ack

#49566 make unit tests optional
  ci-operator/config/openshift/sandboxed-containers-operator/openshift-sandboxed-containers-operator-devel.yaml
  ci-operator/config/openshift/sandboxed-containers-operator/openshift-sandboxed-containers-operator-main.yaml
  ci-operator/jobs/openshift/sandboxed-containers-operator/openshift-sandboxed-containers-operator-devel-presubmits.yaml
  ci-operator/jobs/openshift/sandboxed-containers-operator/openshift-sandboxed-containers-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#49156 openshift/kubernetes: stop modifying machine-os-content
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-master.yaml
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-release-4.16.yaml
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-release-4.17.yaml
Labels: lgtm, approved, rehearsals-ack

#49520 Make job/pull-ci-openshift-release-master-build-clusters required
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#49563 volsync: update selector for e2e clusterpool match
  ci-operator/config/backube/volsync/backube-volsync-main.yaml
Labels: lgtm, approved, rehearsals-ack

#49555 [LPTINTEROP-4061] Fix MTC clusters configs for interop 4.16 testing
  ci-operator/config/mtc-qe/mtc-e2e-qev2/mtc-qe-mtc-e2e-qev2-master__mtc1.8-ocp4.16-lp-interop.yaml
Labels: lgtm, approved, rehearsals-ack

#49592 ofcir-acquire: better error messages
  ci-operator/step-registry/ofcir/acquire/ofcir-acquire-commands.sh
Labels: lgtm, approved, rehearsals-ack

#49594 Remove RHTAP to reinstall in Stage environment
  ci-operator/config/redhat-appstudio/rhtap-installer/redhat-appstudio-rhtap-installer-main.yaml
Labels: lgtm, approved, rehearsals-ack

#49599 OCPQE-18644: Wipe disk always
  ci-operator/step-registry/baremetal/lab/post/wipe/baremetal-lab-post-wipe-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#49558 Add rh-openshift-ecosystem registry and hive access
  core-services/sync-rover-groups/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#49600 NO-ISSUE: reduce run frequency for ztp-node-labels job
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.10.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.9.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-periodics.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.10-periodics.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.9-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#49595 Fix quay token issue
  ci-operator/step-registry/redhat-appstudio/rhtap-installer/install-rhtap/redhat-appstudio-rhtap-installer-install-rhtap-commands.sh
Labels: lgtm, approved, rehearsals-ack

#48524 Create a sample application that uses all of OPP
  ci-operator/config/stolostron/policy-collection/stolostron-policy-collection-main__opp-ocp4.14-interop.yaml
  ci-operator/config/stolostron/policy-collection/stolostron-policy-collection-main__opp-ocp4.15-interop.yaml
  ci-operator/step-registry/acm/opp-app/OWNERS
  ci-operator/step-registry/acm/opp-app/README.md
  ci-operator/step-registry/acm/opp-app/acm-opp-app-commands.sh
  ci-operator/step-registry/acm/opp-app/acm-opp-app-ref.metadata.json
  ci-operator/step-registry/acm/opp-app/acm-opp-app-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#49564 TRT-1544: Include ART repos in acknowledge-critical-fixes
  hack/acknowledge-critical-fix-repos.txt
  hack/generate-acknowledge-critical-fixes-repo-list.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#49335 SPLAT-1423: Created CI jobs for CAPI vSphere static IP.
  ci-operator/config/openshift/installer/openshift-installer-master__altinfra.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.16__altinfra.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.17__altinfra.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.16-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.17-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#49079 MGMT-16990: Configure go version for disconnected CI tests
  ci-operator/step-registry/assisted/baremetal/conf/devscripts/assisted-baremetal-conf-devscripts-commands.sh
  ci-operator/step-registry/assisted/baremetal/conf/devscripts/assisted-baremetal-conf-devscripts-ref.yaml
  ci-operator/step-registry/assisted/baremetal/operator/capi/assisted-baremetal-operator-capi-workflow.yaml
  ci-operator/step-registry/assisted/baremetal/operator/ztp/assisted-baremetal-operator-ztp-workflow.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#49498 Make the checklinks-pr presubmit check optional for managed-notifications
  ci-operator/config/openshift/managed-notifications/openshift-managed-notifications-master.yaml
  ci-operator/jobs/openshift/managed-notifications/openshift-managed-notifications-master-periodics.yaml
  ci-operator/jobs/openshift/managed-notifications/openshift-managed-notifications-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#49590 [CIGolang]disable base images for 417
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__images.yaml
Labels: lgtm, approved, rehearsals-ack

#49589 Enable 4.15 ppc64le job on a different region
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__ppc64le-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#49613 Add platform detect for PowerVS
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__ppc64le-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__ppc64le-nightly.yaml
  ci-operator/step-registry/cucushift/e2e/cucushift-e2e-commands.sh
  ci-operator/step-registry/cucushift/e2e/devel/cucushift-e2e-devel-commands.sh
  ci-operator/step-registry/cucushift/upgrade/check/cucushift-upgrade-check-commands.sh
  ci-operator/step-registry/cucushift/upgrade/prepare/cucushift-upgrade-prepare-commands.sh
Labels: lgtm, approved, rehearsals-ack

#49626 update code to fix machines not found issue
  ci-operator/step-registry/cucushift/installer/check/vsphere/cpms/cucushift-installer-check-vsphere-cpms-commands.sh
Labels: lgtm, approved, rehearsals-ack

#49620 telco5g: Fix unbound variable for pull requests
  ci-operator/step-registry/telco5g/cnf/tests/telco5g-cnf-tests-commands.sh
  ci-operator/step-registry/telco5g/jobs-router/telco5g-jobs-router-commands.sh
Labels: lgtm, approved, rehearsals-ack

#49636 Reduce min number of nodes for build10
  clusters/build-clusters/build10/machineset/worker-aarch64.yaml
  clusters/build-clusters/build10/machineset/worker-amd64.yaml
Labels: lgtm, approved, rehearsals-ack

#49603 CNF-11584: deploy linuxptp-daemon pods to worker nodes only
  ci-operator/step-registry/telco5g/ptp/tests/telco5g-ptp-tests-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#49619 fix issue of RHTAP installer CI deploying installer from main branch
  ci-operator/step-registry/redhat-appstudio/rhtap-installer/install-rhtap/redhat-appstudio-rhtap-installer-install-rhtap-commands.sh
Labels: lgtm, approved, rehearsals-ack

#49344 sriov: create `SriovOperatorConfig` while deploying
  ci-operator/config/openshift/sriov-network-operator/openshift-sriov-network-operator-master.yaml
  ci-operator/step-registry/openstack/provision/sriov-networknodepolicy/openstack-provision-sriov-networknodepolicy-commands.sh
Labels: lgtm, approved, rehearsals-ack

#49641 Incease 4.14 hive cluster pool
  clusters/hive/pools/openshift-ci/ci-ocp-4-14-0-amd64-aws-us-east-1_clusterpool.yaml
Labels: lgtm, approved, rehearsals-ack

#49508 ACM policies interfere with OCS interop tests
  ci-operator/step-registry/interop-tests/ocs-tests/interop-tests-ocs-tests-commands.sh
Labels: lgtm, approved, rehearsals-ack

#49377 Adding rosa latest from image
  ci-operator/step-registry/rosa/sts/account-roles/create/rosa-sts-account-roles-create-ref.yaml
Labels: lgtm, approved, rehearsals-ack
