Repository openshift/release, pull requests merged in 2024-10, with the labels that each got.

#56290 Add AKS periodic nightly test for backstage-showcase
  ci-operator/config/janus-idp/backstage-showcase/janus-idp-backstage-showcase-main.yaml
  ci-operator/jobs/janus-idp/backstage-showcase/janus-idp-backstage-showcase-main-periodics.yaml
  ci-operator/step-registry/janus-idp/backstage-showcase/helm-aks-nightly/OWNERS
  ci-operator/step-registry/janus-idp/backstage-showcase/helm-aks-nightly/janus-idp-backstage-showcase-helm-aks-nightly-commands.sh
  ci-operator/step-registry/janus-idp/backstage-showcase/helm-aks-nightly/janus-idp-backstage-showcase-helm-aks-nightly-ref.metadata.json
  ci-operator/step-registry/janus-idp/backstage-showcase/helm-aks-nightly/janus-idp-backstage-showcase-helm-aks-nightly-ref.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#57088 GitOps | Update branch name for interop tests
  ci-operator/config/redhat-developer/gitops-operator/redhat-developer-gitops-operator-v1.14__gitops-ocp4.14-lp-interop.yaml
  ci-operator/config/redhat-developer/gitops-operator/redhat-developer-gitops-operator-v1.14__gitops-ocp4.15-lp-interop.yaml
  ci-operator/config/redhat-developer/gitops-operator/redhat-developer-gitops-operator-v1.14__gitops-ocp4.16-lp-interop.yaml
  ci-operator/config/redhat-developer/gitops-operator/redhat-developer-gitops-operator-v1.14__gitops-ocp4.17-lp-interop.yaml
  ci-operator/jobs/redhat-developer/gitops-operator/redhat-developer-gitops-operator-v1.12-periodics.yaml
  ci-operator/jobs/redhat-developer/gitops-operator/redhat-developer-gitops-operator-v1.12-presubmits.yaml
  ci-operator/jobs/redhat-developer/gitops-operator/redhat-developer-gitops-operator-v1.13-presubmits.yaml
  ci-operator/jobs/redhat-developer/gitops-operator/redhat-developer-gitops-operator-v1.14-periodics.yaml
  ci-operator/jobs/redhat-developer/gitops-operator/redhat-developer-gitops-operator-v1.14-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#57329 [INTEROP-7527] OCP 4.18 expansion for DevSpaces
  ci-operator/config/redhat-developer/devspaces-interop-tests/.config.prowgen
  ci-operator/config/redhat-developer/devspaces-interop-tests/redhat-developer-devspaces-interop-tests-main__devspaces-ocp4.18-lp-interop.yaml
  ci-operator/jobs/redhat-developer/devspaces-interop-tests/redhat-developer-devspaces-interop-tests-main-periodics.yaml
  ci-operator/jobs/redhat-developer/devspaces-interop-tests/redhat-developer-devspaces-interop-tests-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#57312 Add HTML test result for OCS test
  ci-operator/step-registry/interop-tests/ocs-tests/interop-tests-ocs-tests-commands.sh
  ci-operator/step-registry/interop-tests/ocs-tests/interop-tests-ocs-tests-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#57328 Remove unnecessary `make e2e` from hypershift/kubevirt e2e-local chain
  ci-operator/step-registry/hypershift/kubevirt/run-e2e-local/hypershift-kubevirt-run-e2e-local-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#57317 NO-JIRA: hypershift: add hypershift base_images to csi-operator config
  ci-operator/config/openshift/csi-operator/openshift-csi-operator-master.yaml
  ci-operator/config/openshift/csi-operator/openshift-csi-operator-release-4.15.yaml
  ci-operator/config/openshift/csi-operator/openshift-csi-operator-release-4.16.yaml
  ci-operator/config/openshift/csi-operator/openshift-csi-operator-release-4.17.yaml
  ci-operator/config/openshift/csi-operator/openshift-csi-operator-release-4.18.yaml
  ci-operator/config/openshift/csi-operator/openshift-csi-operator-release-4.19.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#57335 openshift-loki: Add ci config for branch upstream-v3.2.0
  ci-operator/config/openshift/loki/openshift-loki-upstream-v3.2.0.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-upstream-v3.2.0-postsubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-upstream-v3.2.0-presubmits.yaml
  core-services/image-mirroring/openshift-logging/mapping_logging_loki_quay
Labels: lgtm, approved, rehearsals-ack

#57347 RHDH fix Slack report URLs for AKS
  ci-operator/jobs/janus-idp/backstage-showcase/janus-idp-backstage-showcase-main-periodics.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#57306 OU-550: use the default lint command from the test image
  ci-operator/config/openshift/monitoring-plugin/openshift-monitoring-plugin-release-4.18.yaml
  ci-operator/config/openshift/monitoring-plugin/openshift-monitoring-plugin-release-4.19.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#57308 Fix csi-operator verify-kustomize-assets
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-master.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.14.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.15.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.16.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.17.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.18.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.19.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.14-presubmits.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.15-presubmits.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.16-presubmits.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.17-presubmits.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.18-presubmits.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.19-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#57337 MGMT-19035: Change assisted-test-infra day2 periodic jobs back to run minimal conformance tests
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#57331 Use latest images for HO and e2e tests
  ci-operator/config/openshift/cluster-monitoring-operator/openshift-cluster-monitoring-operator-master.yaml
  ci-operator/config/openshift/cluster-monitoring-operator/openshift-cluster-monitoring-operator-release-4.17.yaml
  ci-operator/config/openshift/cluster-monitoring-operator/openshift-cluster-monitoring-operator-release-4.18.yaml
  ci-operator/config/openshift/cluster-monitoring-operator/openshift-cluster-monitoring-operator-release-4.19.yaml
  ci-operator/config/openshift/monitoring-plugin/openshift-monitoring-plugin-main.yaml
  ci-operator/config/openshift/monitoring-plugin/openshift-monitoring-plugin-release-4.18.yaml
  ci-operator/config/openshift/monitoring-plugin/openshift-monitoring-plugin-release-4.19.yaml
Labels: lgtm, approved, rehearsals-ack

#57182 Updated deprecated git-sync options
  clusters/app.ci/assets/admin_ci-images-mirror.yaml
  clusters/app.ci/assets/dptp-controller-manager.yaml
  clusters/app.ci/assets/slack-bot.yaml
  clusters/app.ci/ci-chat-bot/ci-chat-bot.yaml
  clusters/app.ci/ci-operator-configresolver/ci-operator-configresolver.yaml
  clusters/app.ci/prow/03_deployment/crier.yaml
  clusters/app.ci/prow/03_deployment/deck.yaml
  clusters/app.ci/prow/03_deployment/gangway.yaml
  clusters/app.ci/prow/03_deployment/hook.yaml
  clusters/app.ci/prow/03_deployment/horologium.yaml
  clusters/app.ci/prow/03_deployment/payload-testing-prow-plugin.yaml
  clusters/app.ci/prow/03_deployment/pipeline-controller.yaml
  clusters/app.ci/prow/03_deployment/prow-controller-manager.yaml
  clusters/app.ci/prow/03_deployment/prowjob-dispatcher.yaml
  clusters/app.ci/prow/03_deployment/qe_private_deck.yaml
  clusters/app.ci/prow/03_deployment/retester.yaml
  clusters/app.ci/prow/03_deployment/sinker.yaml
  clusters/app.ci/prow/03_deployment/statusreconciler.yaml
  clusters/app.ci/prow/03_deployment/tide.yaml
  clusters/app.ci/prow/03_deployment/tot.yaml
  clusters/app.ci/release-controller/deploy-ocp-arm64-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-arm64-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-multi-2-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-multi-2-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-multi-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-multi-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-ppc64le-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-ppc64le-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-s390x-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-s390x-priv-controller.yaml
  hack/generators/release-controllers/content/osd_rc_deployments.py
Labels: lgtm, approved, rehearsals-ack

#57288 chore: make release service e2e tests optional
  ci-operator/config/konflux-ci/release-service/konflux-ci-release-service-main.yaml
  ci-operator/jobs/konflux-ci/release-service/konflux-ci-release-service-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#57353 OU-550 : fix lint command in monitoring plugin for main branch
  ci-operator/config/openshift/monitoring-plugin/openshift-monitoring-plugin-main.yaml
Labels: lgtm, approved, rehearsals-ack

#57228 [wasp-agent]: update prow plugins config
  core-services/prow/02_config/openshift-virtualization/wasp-agent/_pluginconfig.yaml
  core-services/prow/02_config/openshift-virtualization/wasp-agent/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#57359 Add secret for HAC to access RHTPA
  ci-operator/step-registry/openshift/hac-dev/e2e/openshift-hac-dev-e2e-commands.sh
Labels: lgtm, approved, rehearsals-ack

#57349 Add hypershift base images to storage job
  ci-operator/config/openshift/cluster-csi-snapshot-controller-operator/openshift-cluster-csi-snapshot-controller-operator-master.yaml
  ci-operator/config/openshift/cluster-csi-snapshot-controller-operator/openshift-cluster-csi-snapshot-controller-operator-release-4.12.yaml
  ci-operator/config/openshift/cluster-csi-snapshot-controller-operator/openshift-cluster-csi-snapshot-controller-operator-release-4.13.yaml
  ci-operator/config/openshift/cluster-csi-snapshot-controller-operator/openshift-cluster-csi-snapshot-controller-operator-release-4.14.yaml
  ci-operator/config/openshift/cluster-csi-snapshot-controller-operator/openshift-cluster-csi-snapshot-controller-operator-release-4.15.yaml
  ci-operator/config/openshift/cluster-csi-snapshot-controller-operator/openshift-cluster-csi-snapshot-controller-operator-release-4.16.yaml
  ci-operator/config/openshift/cluster-csi-snapshot-controller-operator/openshift-cluster-csi-snapshot-controller-operator-release-4.17.yaml
  ci-operator/config/openshift/cluster-csi-snapshot-controller-operator/openshift-cluster-csi-snapshot-controller-operator-release-4.18.yaml
  ci-operator/config/openshift/cluster-csi-snapshot-controller-operator/openshift-cluster-csi-snapshot-controller-operator-release-4.19.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-master.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.12.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.13.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.14.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.15.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.16.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.17.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.18.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.19.yaml
Labels: lgtm, approved, rehearsals-ack

#57224 hypershift: remove ability to set CPO image
  ci-operator/step-registry/hypershift/aws/conformance-proxy/hypershift-aws-conformance-proxy-workflow.yaml
  ci-operator/step-registry/hypershift/aws/create/hypershift-aws-create-chain.yaml
  ci-operator/step-registry/hypershift/hostedcluster/create/hostedcluster/hypershift-hostedcluster-create-hostedcluster-commands.sh
  ci-operator/step-registry/hypershift/hostedcluster/create/hostedcluster/hypershift-hostedcluster-create-hostedcluster-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#57138 MGMT-18934: Replace fast-forward for ocm-2.12 with ocm-2.13
  ci-operator/jobs/infra-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#57235 opendatahub/vllm: adjust requirements
  ci-operator/config/opendatahub-io/vllm/opendatahub-io-vllm-ibm-dev.yaml
  ci-operator/config/opendatahub-io/vllm/opendatahub-io-vllm-main.yaml
  ci-operator/config/opendatahub-io/vllm/opendatahub-io-vllm-release.yaml
  ci-operator/jobs/opendatahub-io/vllm/opendatahub-io-vllm-main-postsubmits.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#57313 Add Caikit-Tgis CI for 2.14
  ci-operator/config/red-hat-data-services/caikit-tgis-serving/red-hat-data-services-caikit-tgis-serving-rhoai-2.14.yaml
  ci-operator/jobs/red-hat-data-services/caikit-tgis-serving/red-hat-data-services-caikit-tgis-serving-rhoai-2.14-postsubmits.yaml
  ci-operator/jobs/red-hat-data-services/caikit-tgis-serving/red-hat-data-services-caikit-tgis-serving-rhoai-2.14-presubmits.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#57360 Remove unused aws-splat cluster profile
  ci-operator/step-registry/cluster-profiles/cluster-profiles-config.yaml
Labels: lgtm, approved, rehearsals-ack

#57356 Ibm runfalse
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#57364 Removing the 4.16 informing jobs on P/Z
  core-services/release-controller/_releases/priv/release-ocp-4.16-ppc64le.json
  core-services/release-controller/_releases/priv/release-ocp-4.16-s390x.json
  core-services/release-controller/_releases/release-ocp-4.16-ppc64le.json
  core-services/release-controller/_releases/release-ocp-4.16-s390x.json
Labels: lgtm, approved, rehearsals-ack

#56530 MULTIARCH-4859 Etcd Optimizations for 4.17
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.17.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.18-upgrade-from-nightly-4.17.yaml
Labels: lgtm, approved, rehearsals-ack

#57334 ACM-14584: stolostron/clusterlifecycle-state-metrics use ubi9
  ci-operator/config/stolostron/clusterlifecycle-state-metrics/stolostron-clusterlifecycle-state-metrics-backplane-2.7.yaml
  ci-operator/config/stolostron/clusterlifecycle-state-metrics/stolostron-clusterlifecycle-state-metrics-main.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#57229 OPRUN-3542: Use openshift/ folder Makefile for running OLM v1 tests
  ci-operator/config/openshift/operator-framework-catalogd/openshift-operator-framework-catalogd-main.yaml
  ci-operator/config/openshift/operator-framework-operator-controller/openshift-operator-framework-operator-controller-main.yaml
  ci-operator/jobs/openshift/operator-framework-catalogd/openshift-operator-framework-catalogd-main-presubmits.yaml
  ci-operator/jobs/openshift/operator-framework-operator-controller/openshift-operator-framework-operator-controller-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#57341 NO-JIRA: hypershift: add hypershift base_images to cloud-credential-operator config
  ci-operator/config/openshift/cloud-credential-operator/openshift-cloud-credential-operator-master.yaml
  ci-operator/config/openshift/cloud-credential-operator/openshift-cloud-credential-operator-release-4.14.yaml
  ci-operator/config/openshift/cloud-credential-operator/openshift-cloud-credential-operator-release-4.15.yaml
  ci-operator/config/openshift/cloud-credential-operator/openshift-cloud-credential-operator-release-4.16.yaml
  ci-operator/config/openshift/cloud-credential-operator/openshift-cloud-credential-operator-release-4.17.yaml
  ci-operator/config/openshift/cloud-credential-operator/openshift-cloud-credential-operator-release-4.18.yaml
  ci-operator/config/openshift/cloud-credential-operator/openshift-cloud-credential-operator-release-4.19.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#57065 STOR-1823: Remove shared-resource CSI driver e2e presubmit jobs
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-master.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.18.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.19.yaml
  ci-operator/config/openshift/csi-driver-shared-resource-operator/openshift-csi-driver-shared-resource-operator-master.yaml
  ci-operator/config/openshift/csi-driver-shared-resource-operator/openshift-csi-driver-shared-resource-operator-release-4.18.yaml
  ci-operator/config/openshift/csi-driver-shared-resource-operator/openshift-csi-driver-shared-resource-operator-release-4.19.yaml
  ci-operator/config/openshift/csi-driver-shared-resource/openshift-csi-driver-shared-resource-master.yaml
  ci-operator/config/openshift/csi-driver-shared-resource/openshift-csi-driver-shared-resource-release-4.18.yaml
  ci-operator/config/openshift/csi-driver-shared-resource/openshift-csi-driver-shared-resource-release-4.19.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.18-presubmits.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.19-presubmits.yaml
  ci-operator/jobs/openshift/csi-driver-shared-resource-operator/openshift-csi-driver-shared-resource-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/csi-driver-shared-resource-operator/openshift-csi-driver-shared-resource-operator-release-4.18-presubmits.yaml
  ci-operator/jobs/openshift/csi-driver-shared-resource-operator/openshift-csi-driver-shared-resource-operator-release-4.19-presubmits.yaml
  ci-operator/jobs/openshift/csi-driver-shared-resource/openshift-csi-driver-shared-resource-master-presubmits.yaml
  ci-operator/jobs/openshift/csi-driver-shared-resource/openshift-csi-driver-shared-resource-release-4.18-presubmits.yaml
  ci-operator/jobs/openshift/csi-driver-shared-resource/openshift-csi-driver-shared-resource-release-4.19-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#57103 SPLAT-1807: enable sos report generation for vSphere UPI jobs
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.16.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.17.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.18.yaml
  ci-operator/step-registry/ipi/deprovision/vsphere/diags/vcm/ipi-deprovision-vsphere-diags-vcm-commands.sh
  ci-operator/step-registry/ipi/deprovision/vsphere/diags/vcm/ipi-deprovision-vsphere-diags-vcm-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#57185 SDN-4971: add sandbox branch jobs for ovnk
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-sandbox-release-4.16.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-sandbox-release-4.16__4.16-upgrade-from-stable-4.15-local-gateway.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-sandbox-release-4.16__4.16-upgrade-from-stable-4.15.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-sandbox-release-4.17.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-sandbox-release-4.17__4.17-upgrade-from-stable-4.16-local-gateway.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-sandbox-release-4.17__4.17-upgrade-from-stable-4.16.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-sandbox-release-4.16-periodics.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-sandbox-release-4.16-postsubmits.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-sandbox-release-4.16-presubmits.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-sandbox-release-4.17-periodics.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-sandbox-release-4.17-postsubmits.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-sandbox-release-4.17-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#57348 cvo: make tp job run on code changes only
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-master.yaml
  ci-operator/jobs/openshift/cluster-version-operator/openshift-cluster-version-operator-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#57354 installer: use latest ARO marketplace image for given release
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.16.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.17.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.18.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.19.yaml
Labels: lgtm, approved, rehearsals-ack

#57271 vSphere: clean up registry mirror
  ci-operator/step-registry/ipi/install/install/ipi-install-install-commands.sh
  ci-operator/step-registry/ipi/install/vsphere/registry/ipi-install-vsphere-registry-commands.sh
Labels: lgtm, approved, rehearsals-ack

#57369 Removed the next set of deprecated template tests (openstack)
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.11-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.9-presubmits.yaml
  core-services/prow/02_config/_plugins.yaml
  core-services/template-deprecation/_allowlist.yaml
Labels: lgtm, approved, rehearsals-ack

#57241 origin: limit gcp builds jobs to build directories
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#57355 Removing rosa 413 jobs
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa-4.13-candidate-x86-loaded-upgrade-from-4.12.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa-4.13-nightly-x86.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-periodics.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#57374 core-services: hypershift: remove per release mirroring
  core-services/image-mirroring/hypershift/mapping_hypershift_4_10
  core-services/image-mirroring/hypershift/mapping_hypershift_4_11
  core-services/image-mirroring/hypershift/mapping_hypershift_4_12
  core-services/image-mirroring/hypershift/mapping_hypershift_4_13
  core-services/image-mirroring/hypershift/mapping_hypershift_4_14
  core-services/image-mirroring/hypershift/mapping_hypershift_4_15
  core-services/image-mirroring/hypershift/mapping_hypershift_4_16
  core-services/image-mirroring/hypershift/mapping_hypershift_4_17
  core-services/image-mirroring/hypershift/mapping_hypershift_4_18
  core-services/image-mirroring/hypershift/mapping_hypershift_latest
Labels: lgtm, approved, rehearsals-ack

#57346 [PERFSCALE-3401] BM CPT: LSO operator deploy
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__metal-x86.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-presubmits.yaml
  ci-operator/step-registry/openshift-qe/installer/bm/day2/lso/OWNERS
  ci-operator/step-registry/openshift-qe/installer/bm/day2/lso/openshift-qe-installer-bm-day2-lso-chain.metadata.json
  ci-operator/step-registry/openshift-qe/installer/bm/day2/lso/openshift-qe-installer-bm-day2-lso-chain.yaml
  ci-operator/step-registry/openshift-qe/installer/bm/day2/lso/openshift-qe-installer-bm-day2-lso-commands.sh
  ci-operator/step-registry/openshift-qe/installer/bm/day2/lso/openshift-qe-installer-bm-day2-lso-ref.metadata.json
  ci-operator/step-registry/openshift-qe/installer/bm/day2/lso/openshift-qe-installer-bm-day2-lso-ref.yaml
  ci-operator/step-registry/openshift-qe/installer/bm/day2/lso/openshift-qe-installer-bm-day2-lso-workflow.metadata.json
  ci-operator/step-registry/openshift-qe/installer/bm/day2/lso/openshift-qe-installer-bm-day2-lso-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#57378 TRT-1757: turn off 4.17 aggregation at GA
  core-services/release-controller/_releases/priv/release-ocp-4.17.json
  core-services/release-controller/_releases/release-ocp-4.17-ci.json
  core-services/release-controller/_releases/release-ocp-4.17.json
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#57373 Purged deprecated template remaining files
  Makefile
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  core-services/prow/02_config/_plugins.yaml
  core-services/template-deprecation/_allowlist.yaml
  hack/generate-template-allowlist.sh
Labels: lgtm, approved, rehearsals-ack

#57193 stackrox: switch acs tests to ocp-4.17 after GA oct1st
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-16.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-17.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-postsubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#57379 Removed the last script related to template deprecation
  hack/validate-template-deprecation.sh
Labels: lgtm, approved, rehearsals-ack

#57311 Add TGIS CI for 2.14
  ci-operator/config/red-hat-data-services/text-generation-inference/red-hat-data-services-text-generation-inference-rhoai-2.14.yaml
  ci-operator/jobs/red-hat-data-services/text-generation-inference/red-hat-data-services-text-generation-inference-rhoai-2.14-postsubmits.yaml
  ci-operator/jobs/red-hat-data-services/text-generation-inference/red-hat-data-services-text-generation-inference-rhoai-2.14-presubmits.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#57358 Upgrade kubevirt-ui to 4.17 openshift version
  ci-operator/config/kubevirt-ui/kubevirt-plugin/kubevirt-ui-kubevirt-plugin-main.yaml
Labels: lgtm, approved, rehearsals-ack

#57343 Add OVMS CI for 2.14
  ci-operator/config/red-hat-data-services/openvino_model_server/red-hat-data-services-openvino_model_server-rhoai-2.14.yaml
  ci-operator/jobs/red-hat-data-services/openvino_model_server/red-hat-data-services-openvino_model_server-rhoai-2.14-postsubmits.yaml
  ci-operator/jobs/red-hat-data-services/openvino_model_server/red-hat-data-services-openvino_model_server-rhoai-2.14-presubmits.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#57345 OCPBUGS-42626: [CI] no tests were found matching the OPENSTACK_TEST_SKIPS regex
  ci-operator/config/shiftstack/ci/shiftstack-ci-release-4.12.yaml
  ci-operator/config/shiftstack/ci/shiftstack-ci-release-4.13.yaml
Labels: lgtm, approved, jira/valid-bug, rehearsals-ack, jira/valid-reference

#57063 STOR-1873: update OLM manifests to use stable channel
  ci-operator/config/openshift/secrets-store-csi-driver-operator/openshift-secrets-store-csi-driver-operator-main.yaml
  ci-operator/config/openshift/secrets-store-csi-driver-operator/openshift-secrets-store-csi-driver-operator-release-4.18.yaml
  ci-operator/config/openshift/secrets-store-csi-driver-operator/openshift-secrets-store-csi-driver-operator-release-4.19.yaml
  ci-operator/jobs/openshift/secrets-store-csi-driver-operator/openshift-secrets-store-csi-driver-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/secrets-store-csi-driver-operator/openshift-secrets-store-csi-driver-operator-release-4.18-presubmits.yaml
  ci-operator/jobs/openshift/secrets-store-csi-driver-operator/openshift-secrets-store-csi-driver-operator-release-4.19-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#57367 feat(cluster-init): add cluster installs
  clusters/_cluster-install/build01.yaml
  clusters/_cluster-install/build02.yaml
  clusters/_cluster-install/build03.yaml
  clusters/_cluster-install/build04.yaml
  clusters/_cluster-install/build05.yaml
  clusters/_cluster-install/build09.yaml
  clusters/_cluster-install/build10.yaml
  clusters/_cluster-install/build11.yaml
  hack/validate-ci-build-clusters.sh
Labels: lgtm, approved, rehearsals-ack

#57383 NO-JIRA: remove agent-based installer okd fcos jobs
  ci-operator/config/openshift/installer/openshift-installer-master__okd.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.15__okd.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.16__okd.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.17__okd.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.18__okd.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.19__okd.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.15-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.16-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.17-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.18-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.19-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#57387 Sync Serverless CI config/
  ci-operator/config/openshift-knative/kn-plugin-func/openshift-knative-kn-plugin-func-release-v1.15__416.yaml
  ci-operator/config/openshift-knative/kn-plugin-func/openshift-knative-kn-plugin-func-release-v1.15__417.yaml
  ci-operator/jobs/openshift-knative/kn-plugin-func/openshift-knative-kn-plugin-func-release-v1.15-postsubmits.yaml
  ci-operator/jobs/openshift-knative/kn-plugin-func/openshift-knative-kn-plugin-func-release-v1.15-presubmits.yaml
  core-services/image-mirroring/knative/mapping_knative_knative-v1.15_kn-plugin-func_quay
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#57389 NO-JIRA: Update edge enablement owners
  OWNERS_ALIASES
  clusters/app.ci/registry-access/lvms/OWNERS
  core-services/image-mirroring/lvms/OWNERS
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#57390 removing rosa-hcp from the 4.18 openshift-docs build
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-enterprise-4.18.yaml
Labels: lgtm, approved, rehearsals-ack

#57232 TRT-1803: Add oc adm wait-for-stable-cluster before e2e testing
  ci-operator/step-registry/openshift/e2e/test/openshift-e2e-test-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#57391 MGMT-18941: Make assisted-service-index:ocm-2.12 image available in Prow
  core-services/image-mirroring/_config.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#57270 Add NetObserv CLI
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-master.yaml
Labels: lgtm, approved, rehearsals-ack

#57370 SPLAT-1830: add resource requests to tcpdump pods
  ci-operator/step-registry/upi/conf/vsphere/tcpdump/upi-conf-vsphere-tcpdump-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#57377 updating rh openshift ecosystem 4.17 jobs to use fast channel
  ci-operator/config/redhat-openshift-ecosystem/certified-operators-preprod/redhat-openshift-ecosystem-certified-operators-preprod-ocp-4.17.yaml
  ci-operator/config/redhat-openshift-ecosystem/certified-operators-prod/redhat-openshift-ecosystem-certified-operators-prod-ocp-4.17.yaml
  ci-operator/config/redhat-openshift-ecosystem/openshift-preflight/redhat-openshift-ecosystem-openshift-preflight-main__4.17.yaml
  ci-operator/config/redhat-openshift-ecosystem/preflight/redhat-openshift-ecosystem-preflight-ocp-4.17.yaml
  ci-operator/jobs/redhat-openshift-ecosystem/certified-operators-preprod/redhat-openshift-ecosystem-certified-operators-preprod-ocp-4.17-periodics.yaml
  ci-operator/jobs/redhat-openshift-ecosystem/certified-operators-prod/redhat-openshift-ecosystem-certified-operators-prod-ocp-4.17-periodics.yaml
  ci-operator/jobs/redhat-openshift-ecosystem/openshift-preflight/redhat-openshift-ecosystem-openshift-preflight-main-presubmits.yaml
  ci-operator/jobs/redhat-openshift-ecosystem/preflight/redhat-openshift-ecosystem-preflight-ocp-4.17-periodics.yaml
  clusters/hosted-mgmt/hive/pools/rh-openshift-ecosystem/rhoe-ocp-4-17-amd64-aws-us-west-1_clusterpool.yaml
  clusters/hosted-mgmt/hive/pools/rh-openshift-ecosystem/rhoe-ocp-4-17-amd64-aws-us-west-2_clusterpool.yaml
Labels: lgtm, approved, rehearsals-ack

#57398 osde2e: update presubmits
  ci-operator/config/openshift/osde2e/openshift-osde2e-main.yaml
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#57357 Orion fail
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__write_jobs_to_gsheet.yaml
Labels: lgtm, approved, rehearsals-ack

#57392 Some of the build images were missing the YearIndex in the generated tag
  ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-2024b.yaml
  ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-main.yaml
  ci-operator/config/red-hat-data-services/notebooks/red-hat-data-services-notebooks-main.yaml
  ci-operator/config/red-hat-data-services/notebooks/red-hat-data-services-notebooks-release-2024a.yaml
  ci-operator/config/red-hat-data-services/notebooks/red-hat-data-services-notebooks-release-2024b.yaml
Labels: lgtm, approved, rehearsals-ack

#57393 Add cloud-event-proxy to cluster profile "aws-telco"
  ci-operator/step-registry/cluster-profiles/cluster-profiles-config.yaml
Labels: lgtm, approved, rehearsals-ack

#57407 fix output for failed or aborted jobs
  ci-operator/step-registry/dpu-operator/e2e-tests-workflow/tests/dpu-operator-e2e-tests-workflow-tests-commands.sh
Labels: lgtm, approved, rehearsals-ack

#57372 LOG-6022: Update vector 6.1 to rely upon clo 6.1
  ci-operator/config/ViaQ/vector/ViaQ-vector-release-6.1.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#57371 LOG-6138: Set logging claims to 4.17 for testing
  ci-operator/config/openshift/cluster-logging-operator/openshift-cluster-logging-operator-master.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#57409 Remove openshift-priv/cluster-logging-operator and openshift-priv/elasticsearch-proxy
  ci-operator/config/openshift-priv/cluster-logging-operator/openshift-priv-cluster-logging-operator-release-4.6.yaml
  ci-operator/config/openshift-priv/elasticsearch-operator/openshift-priv-elasticsearch-operator-release-4.6.yaml
  ci-operator/config/openshift-priv/elasticsearch-proxy/openshift-priv-elasticsearch-proxy-release-4.6.yaml
  ci-operator/jobs/openshift-priv/cluster-logging-operator/OWNERS
  ci-operator/jobs/openshift-priv/cluster-logging-operator/openshift-priv-cluster-logging-operator-release-4.6-postsubmits.yaml
  ci-operator/jobs/openshift-priv/cluster-logging-operator/openshift-priv-cluster-logging-operator-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift-priv/elasticsearch-operator/OWNERS
  ci-operator/jobs/openshift-priv/elasticsearch-operator/openshift-priv-elasticsearch-operator-release-4.6-postsubmits.yaml
  ci-operator/jobs/openshift-priv/elasticsearch-operator/openshift-priv-elasticsearch-operator-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift-priv/elasticsearch-proxy/OWNERS
  ci-operator/jobs/openshift-priv/elasticsearch-proxy/openshift-priv-elasticsearch-proxy-release-4.6-postsubmits.yaml
  ci-operator/jobs/openshift-priv/elasticsearch-proxy/openshift-priv-elasticsearch-proxy-release-4.6-presubmits.yaml
  core-services/prow/02_config/openshift-priv/cluster-logging-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift-priv/cluster-logging-operator/_prowconfig.yaml
  core-services/prow/02_config/openshift-priv/elasticsearch-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift-priv/elasticsearch-operator/_prowconfig.yaml
  core-services/prow/02_config/openshift-priv/elasticsearch-proxy/_pluginconfig.yaml
  core-services/prow/02_config/openshift-priv/elasticsearch-proxy/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#57174 Add prod.psi.redhat.com
  clusters/build-clusters/build05/assets/dns.yaml
Labels: lgtm, approved, rehearsals-ack

#57408 cvo: explicitly import hypershift base images
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-master.yaml
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-release-4.15.yaml
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-release-4.16.yaml
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-release-4.17.yaml
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-release-4.18.yaml
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-release-4.19.yaml
Labels: lgtm, approved, rehearsals-ack

#57141 use openshift 4.18 in rook CI
  ci-operator/config/red-hat-storage/rook/red-hat-storage-rook-master.yaml
Labels: lgtm, approved, rehearsals-ack

#57344 Bump Streams for Apache Kafka to 2.7.0-5 after respin
  ci-operator/config/amq-streams-qe/strimzi-kafka-operator/amq-streams-qe-strimzi-kafka-operator-main__amq-streams-ocp4.14-lp-interop.yaml
  ci-operator/config/amq-streams-qe/strimzi-kafka-operator/amq-streams-qe-strimzi-kafka-operator-main__amq-streams-ocp4.14-lp-rosa-classic.yaml
  ci-operator/config/amq-streams-qe/strimzi-kafka-operator/amq-streams-qe-strimzi-kafka-operator-main__amq-streams-ocp4.15-lp-interop.yaml
  ci-operator/config/amq-streams-qe/strimzi-kafka-operator/amq-streams-qe-strimzi-kafka-operator-main__amq-streams-ocp4.16-lp-interop.yaml
  ci-operator/config/amq-streams-qe/strimzi-kafka-operator/amq-streams-qe-strimzi-kafka-operator-main__amq-streams-ocp4.16-lp-rosa-classic.yaml
  ci-operator/config/amq-streams-qe/strimzi-kafka-operator/amq-streams-qe-strimzi-kafka-operator-main__amq-streams-ocp4.17-lp-interop.yaml
Labels: lgtm, approved, rehearsals-ack

#57384 openshift-loki: Use loki v3.2.0 in operator branches
  ci-operator/config/openshift/loki/openshift-loki-main.yaml
  ci-operator/config/openshift/loki/openshift-loki-release-5.6.yaml
  ci-operator/config/openshift/loki/openshift-loki-release-5.8.yaml
  ci-operator/config/openshift/loki/openshift-loki-release-5.9.yaml
  ci-operator/config/openshift/loki/openshift-loki-release-6.0.yaml
Labels: lgtm, approved, rehearsals-ack

#57419 Test OTEL multi-container multi-instrumenation without feature gate
  ci-operator/step-registry/distributed-tracing/tests/opentelemetry/upstream/distributed-tracing-tests-opentelemetry-upstream-commands.sh
Labels: lgtm, approved, rehearsals-ack

#57395 Create prow configuration for nbde-tang-server
  ci-operator/config/openshift/nbde-tang-server/OWNERS
  ci-operator/config/openshift/nbde-tang-server/openshift-nbde-tang-server-main.yaml
  core-services/prow/02_config/openshift/nbde-tang-server/_pluginconfig.yaml
  core-services/prow/02_config/openshift/nbde-tang-server/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#57152 MGMT-18940: Adjust the configuration files for cluster-api-provider-agent to the new ocm-2.13 branch
  ci-operator/config/openshift/cluster-api-provider-agent/openshift-cluster-api-provider-agent-master.yaml
  ci-operator/config/openshift/cluster-api-provider-agent/openshift-cluster-api-provider-agent-master__mce.yaml
  ci-operator/config/openshift/cluster-api-provider-agent/openshift-cluster-api-provider-agent-release-ocm-2.12.yaml
  ci-operator/config/openshift/cluster-api-provider-agent/openshift-cluster-api-provider-agent-release-ocm-2.12__mce.yaml
  ci-operator/jobs/openshift/cluster-api-provider-agent/openshift-cluster-api-provider-agent-release-ocm-2.12-periodics.yaml
  ci-operator/jobs/openshift/cluster-api-provider-agent/openshift-cluster-api-provider-agent-release-ocm-2.12-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-agent/openshift-cluster-api-provider-agent-release-ocm-2.12-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#57402 enable requestServingIsolation test on hypershift periodics 4.16-4.18
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.15__periodics.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.16__periodics.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.17__periodics.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.18__periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#57140 MGMT-18940: Adjust the configuration files for assisted-image-service to ocm-2.12 feature freeze
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-main__edge.yaml
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-main__mce.yaml
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.11.yaml
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.12.yaml
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.12__mce.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.11-periodics.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.11-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.11-presubmits.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.12-periodics.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.12-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.12-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#57142 MGMT-18940: Adjust the configuration files for assisted-installer to the new ocm-2.13 branch
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-master__edge.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-master__mce.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.12.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.12__mce.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.12-periodics.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.12-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.12-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#57144 MGMT-18940: Adjust the configuration files for assisted-installer-agent to the new ocm-2.13 branch
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master__edge.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master__mce.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.11__mce.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.12.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.12__mce.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.12-periodics.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.12-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.12-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#57146 MGMT-18940: Adjust the configuration files for assisted-service to the new ocm-2.13 branch
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-cloud_hotfix_releases.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__mce.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.11.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.12.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.12__mce.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.11-periodics.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.11-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.11-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.12-periodics.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.12-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.12-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#57427 MGMT-18940: Adjust the configuration files for assisted-test-infra to the new ocm-2.13 branch
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master__oci-cleanup.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.11.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.12.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.9.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.12-periodics.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.12-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.12-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#57397 Apply samples config only on vsphere okd-scos
  ci-operator/step-registry/ipi/install/install/ipi-install-install-commands.sh
Labels: lgtm, approved, rehearsals-ack

#56217 Enable dynamic cluster creation for Stackrox ppc64le CI
  ci-operator/step-registry/stackrox/automation-flavors/powervs-e2e/cluster-create/stackrox-automation-flavors-powervs-e2e-cluster-create-commands.sh
  ci-operator/step-registry/stackrox/automation-flavors/powervs-e2e/cluster-create/stackrox-automation-flavors-powervs-e2e-cluster-create-ref.yaml
  ci-operator/step-registry/stackrox/automation-flavors/powervs-e2e/cluster-destroy/stackrox-automation-flavors-powervs-e2e-cluster-destroy-commands.sh
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#57351 Add vLLM CI for 2.14
  ci-operator/config/red-hat-data-services/vllm/red-hat-data-services-vllm-rhoai-2.14.yaml
  ci-operator/jobs/red-hat-data-services/vllm/red-hat-data-services-vllm-rhoai-2.14-postsubmits.yaml
  ci-operator/jobs/red-hat-data-services/vllm/red-hat-data-services-vllm-rhoai-2.14-presubmits.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#57433 FRR CI: use the proper metallb / operator branches
  ci-operator/config/openshift/frr/openshift-frr-release-4.12.yaml
Labels: lgtm, approved, rehearsals-ack

#57058 update to support apicurio for ocp 4.18
  ci-operator/config/Apicurio/apicurio-registry-system-tests/Apicurio-apicurio-registry-system-tests-main__service-registry-ocp4.18-lp-interop.yaml
  ci-operator/jobs/Apicurio/apicurio-registry-system-tests/Apicurio-apicurio-registry-system-tests-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#57442 Change MON to 1 for orion cron expression
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__write_jobs_to_gsheet.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#57388 AGENT-998: add job to run node-joiner integration tests
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#57446 promote images using name: sandbox-4.16
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-sandbox-release-4.16.yaml
Labels: lgtm, approved, rehearsals-ack

#57435 Allow openshift-eng access to aws-2
  ci-operator/step-registry/cluster-profiles/cluster-profiles-config.yaml
Labels: lgtm, approved, rehearsals-ack

#57443 Add openshift-tests-extension config
  ci-operator/config/openshift-eng/openshift-tests-extension/OWNERS
  ci-operator/config/openshift-eng/openshift-tests-extension/openshift-eng-openshift-tests-extension-main.yaml
  ci-operator/jobs/openshift-eng/openshift-tests-extension/OWNERS
  ci-operator/jobs/openshift-eng/openshift-tests-extension/openshift-eng-openshift-tests-extension-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#57450 Fix ovn-kubernetes sandbox-release config
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-sandbox-release-4.16.yaml
Labels: lgtm, approved, rehearsals-ack

#57413 ci-chat-bot: add new secrets
  clusters/app.ci/ci-chat-bot/ci-chat-bot.yaml
Labels: lgtm, approved, rehearsals-ack

#57452 Revert "ci-chat-bot: add new secrets"
  clusters/app.ci/ci-chat-bot/ci-chat-bot.yaml
Labels: lgtm, approved, rehearsals-ack

#57441 Fix OVMS builds for 2.14
  ci-operator/config/opendatahub-io/openvino_model_server/opendatahub-io-openvino_model_server-2024.3-release.yaml
  ci-operator/config/red-hat-data-services/openvino_model_server/red-hat-data-services-openvino_model_server-rhoai-2.14.yaml
  ci-operator/jobs/opendatahub-io/openvino_model_server/opendatahub-io-openvino_model_server-2024.3-release-postsubmits.yaml
  ci-operator/jobs/red-hat-data-services/openvino_model_server/red-hat-data-services-openvino_model_server-rhoai-2.14-postsubmits.yaml
  ci-operator/jobs/red-hat-data-services/openvino_model_server/red-hat-data-services-openvino_model_server-rhoai-2.14-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#57422 Align CI to match OSC upstream repo
  ci-operator/config/openshift/sandboxed-containers-operator/openshift-sandboxed-containers-operator-devel.yaml
Labels: lgtm, approved, rehearsals-ack

#55896 hcp/openstack: support multiple RHCOS version
  ci-operator/config/openshift/hypershift/openshift-hypershift-main.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.17.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.17__periodics.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.18.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.18__periodics.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.19.yaml
  ci-operator/step-registry/hypershift/openstack/e2e/execute/hypershift-openstack-e2e-execute-commands.sh
  ci-operator/step-registry/hypershift/openstack/e2e/execute/hypershift-openstack-e2e-execute-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#57455 Fix vLLM 2.14 build
  ci-operator/config/red-hat-data-services/vllm/red-hat-data-services-vllm-rhoai-2.14.yaml
  ci-operator/jobs/red-hat-data-services/vllm/red-hat-data-services-vllm-rhoai-2.14-postsubmits.yaml
  ci-operator/jobs/red-hat-data-services/vllm/red-hat-data-services-vllm-rhoai-2.14-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#57459 Reduce cluster stable time
  ci-operator/step-registry/baremetal/lab/agent/day2/baremetal-lab-agent-day2-commands.sh
  ci-operator/step-registry/baremetal/lab/agent/install/baremetal-lab-agent-install-commands.sh
  ci-operator/step-registry/cucushift/agent/vsphere/day2/add-nodes/cucushift-agent-vsphere-day2-add-nodes-commands.sh
  ci-operator/step-registry/cucushift/agent/vsphere/provision/cucushift-agent-vsphere-provision-commands.sh
Labels: lgtm, approved, rehearsals-ack

#57461 OCPBUGS-42764: add ocp 4.17 branch
  core-services/prow/02_config/openshift/etcd/_prowconfig.yaml
Labels: lgtm, approved, jira/valid-bug, rehearsals-ack, jira/valid-reference

#57074 OLS-1072: Add 4.17 tests for OLS
  ci-operator/config/openshift/lightspeed-service/openshift-lightspeed-service-main.yaml
  ci-operator/jobs/openshift/lightspeed-service/openshift-lightspeed-service-main-periodics.yaml
  ci-operator/jobs/openshift/lightspeed-service/openshift-lightspeed-service-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#57432 NO-JIRA: fix: adding Jeremy Poulin to edge enablement
  OWNERS_ALIASES
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#57436 OCPQE-26108 MCO add vsphere dedicated job
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#57470 Prepare RHCS modules 1.6.4 branch jobs
  ci-operator/config/terraform-redhat/terraform-rhcs-rosa-classic/terraform-redhat-terraform-rhcs-rosa-classic-release-1.6.4.yaml
  ci-operator/config/terraform-redhat/terraform-rhcs-rosa-hcp/terraform-redhat-terraform-rhcs-rosa-hcp-release-1.6.4.yaml
  ci-operator/jobs/terraform-redhat/terraform-rhcs-rosa-classic/terraform-redhat-terraform-rhcs-rosa-classic-release-1.6.4-presubmits.yaml
  ci-operator/jobs/terraform-redhat/terraform-rhcs-rosa-hcp/terraform-redhat-terraform-rhcs-rosa-hcp-release-1.6.4-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#57457 OCM-11594 | RHCS modules: review PR checks
  ci-operator/config/terraform-redhat/terraform-rhcs-rosa-hcp/terraform-redhat-terraform-rhcs-rosa-hcp-main.yaml
  ci-operator/jobs/terraform-redhat/terraform-rhcs-rosa-hcp/terraform-redhat-terraform-rhcs-rosa-hcp-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#56927 OSSM Add federation new repo jobs
  ci-operator/config/openshift-service-mesh/federation/OWNERS
  ci-operator/config/openshift-service-mesh/federation/openshift-service-mesh-federation-master.yaml
  ci-operator/jobs/openshift-service-mesh/federation/OWNERS
  ci-operator/jobs/openshift-service-mesh/federation/openshift-service-mesh-federation-master-presubmits.yaml
  core-services/prow/02_config/openshift-service-mesh/federation/_pluginconfig.yaml
  core-services/prow/02_config/openshift-service-mesh/federation/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#57454 Added configuration for `rhacs-docs-4.6` branch
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-rhacs-docs-4.6.yaml
  ci-operator/jobs/openshift/openshift-docs/openshift-openshift-docs-rhacs-docs-4.6-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#57469 [ODH] Remove Python 3.8 references in RHDS notebooks
  ci-operator/config/red-hat-data-services/notebooks/red-hat-data-services-notebooks-main.yaml
  ci-operator/jobs/red-hat-data-services/notebooks/red-hat-data-services-notebooks-main-postsubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#57476 Update _pluginconfig.yaml
  core-services/prow/02_config/red-hat-storage/_pluginconfig.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#57368 cvo: add more techpreview jobs (manually triggered)
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-master.yaml
  ci-operator/jobs/openshift/cluster-version-operator/openshift-cluster-version-operator-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#57273 Add Steve and Taneem to model serving related OWNERS files
  ci-operator/config/opendatahub-io/caikit-nlp/OWNERS
  ci-operator/config/opendatahub-io/caikit-tgis-serving/OWNERS
  ci-operator/config/opendatahub-io/kserve/OWNERS
  ci-operator/config/opendatahub-io/modelmesh-runtime-adapter/OWNERS
  ci-operator/config/opendatahub-io/modelmesh-serving/OWNERS
  ci-operator/config/opendatahub-io/modelmesh/OWNERS
  ci-operator/config/opendatahub-io/odh-model-controller/OWNERS
  ci-operator/config/opendatahub-io/openvino_model_server/OWNERS
  ci-operator/config/opendatahub-io/rest-proxy/OWNERS
  ci-operator/config/opendatahub-io/text-generation-inference/OWNERS
  ci-operator/config/opendatahub-io/vllm/OWNERS
Labels: lgtm, approved, rehearsals-ack

#57448 Expansion of scenario to run for 4.18
  ci-operator/config/quarkus-qe/quarkus-openshift-interop/.config.prowgen
  ci-operator/config/quarkus-qe/quarkus-openshift-interop/quarkus-qe-quarkus-openshift-interop-main__quarkus-ocp4.18-lp-interop.yaml
  ci-operator/jobs/quarkus-qe/quarkus-openshift-interop/quarkus-qe-quarkus-openshift-interop-main-periodics.yaml
  ci-operator/jobs/quarkus-qe/quarkus-openshift-interop/quarkus-qe-quarkus-openshift-interop-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#57480 SPLAT-1836: unpin 4.16 e2e-vsphere-ovn from nested-7
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.16.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#57486 scanner ocp 4.12 test should use 4.12
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-12.yaml
Labels: lgtm, approved, rehearsals-ack

#57489 Update Distributed Tracing jobs to presubmit jobs
  ci-operator/config/openshift/distributed-tracing-qe/openshift-distributed-tracing-qe-main__ocp-4.14-dast.yaml
  ci-operator/config/openshift/distributed-tracing-qe/openshift-distributed-tracing-qe-main__ocp-4.15-disconnected.yaml
  ci-operator/config/openshift/distributed-tracing-qe/openshift-distributed-tracing-qe-main__ocp-4.16-fips-scan.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.12-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.13-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.14-arm-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.14-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.15-ibm-p-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.15-ibm-z-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.15-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.16-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.17-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__upstream-ocp-4.13-amd64-aws-ipi-ovn-hypershift.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__upstream-ocp-4.14-amd64-gcp-ipi-ovn-ipsec.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__upstream-ocp-4.15-amd64-aws.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__upstream-ocp-4.16-amd64-aws-ipi-shared-vpc-phz-sts.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__upstream-upgrade-ocp-4.17-amd64-azure.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.12-stage.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.13-stage.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.14-arm-stage.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.14-stage.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.15-ibm-p-stage.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.15-ibm-z-stage.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.15-stage.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.16-stage.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__ocp-4.13-hypershift.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__ocp-4.14-amd64.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.12-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.13-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.14-arm-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.14-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.15-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.16-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.17-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-ibm-p-4.15-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-ibm-z-4.15-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__upstream-ocp-4.13-amd64-aws-ipi-ovn-hypershift.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__upstream-ocp-4.14-amd64-gcp-ipi-ovn-ipsec.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__upstream-ocp-4.15-amd64-aws.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__upstream-ocp-4.16-amd64-aws-ipi-shared-vpc-phz-sts.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__upstream-upgrade-ocp-4.17-amd64-azure.yaml
  ci-operator/jobs/openshift/distributed-tracing-qe/openshift-distributed-tracing-qe-main-periodics.yaml
  ci-operator/jobs/openshift/distributed-tracing-qe/openshift-distributed-tracing-qe-main-presubmits.yaml
  ci-operator/jobs/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main-periodics.yaml
  ci-operator/jobs/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main-periodics.yaml
  ci-operator/jobs/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main-periodics.yaml
  ci-operator/jobs/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#57490 ci-chat-bot: use projected volumes for kubeconfigs
  clusters/app.ci/ci-chat-bot/ci-chat-bot.yaml
Labels: lgtm, approved, rehearsals-ack

#57494 [continuous-release-jobs] Only run Cluster Apply when corresponding files change
  ci-operator/jobs/openshift/continuous-release-jobs/openshift-continuous-release-jobs-master-postsubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#57488 Hive: Add jobs for mce-2.7
  ci-operator/config/openshift/hive/openshift-hive-mce-2.7.yaml
  ci-operator/jobs/openshift/hive/openshift-hive-mce-2.7-postsubmits.yaml
  ci-operator/jobs/openshift/hive/openshift-hive-mce-2.7-presubmits.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#57498 USHIFT-4382: Blocking jobs for MicroShift conformance
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  core-services/release-controller/_releases/priv/release-ocp-4.18.json
  core-services/release-controller/_releases/release-ocp-4.18.json
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#57501 Run NVIDIA GPU Operator jobs on 4.17 daily
  ci-operator/config/rh-ecosystem-edge/nvidia-ci/rh-ecosystem-edge-nvidia-ci-main__4.17.yaml
  ci-operator/jobs/rh-ecosystem-edge/nvidia-ci/rh-ecosystem-edge-nvidia-ci-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#57503 NO-ISSUE: Remove temporary images
  core-services/image-mirroring/_config.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#57474 Expansion of scenario to run for 4.18
  ci-operator/config/redhat-developer/odo/.config.prowgen
  ci-operator/config/redhat-developer/odo/redhat-developer-odo-main__odo-ocp4.18-lp-interop.yaml
  ci-operator/jobs/redhat-developer/odo/redhat-developer-odo-main-periodics.yaml
  ci-operator/jobs/redhat-developer/odo/redhat-developer-odo-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#57509 Remove vllm-2.14 build definitions
  ci-operator/config/red-hat-data-services/vllm/red-hat-data-services-vllm-rhoai-2.14.yaml
  ci-operator/jobs/red-hat-data-services/vllm/red-hat-data-services-vllm-rhoai-2.14-postsubmits.yaml
  ci-operator/jobs/red-hat-data-services/vllm/red-hat-data-services-vllm-rhoai-2.14-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#57499 MGMT-18957: change ODF and CNV jobs to latest stable (4.17)
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-cloud_hotfix_releases.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-cloud_hotfix_releases-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-periodics.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#57504 [INTEROP-7527] OCP 4.18 expansion for Quay 3.12 lp-interop.
  ci-operator/config/quay/quay-tests/.config.prowgen
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__ocp-418-quay.yaml
  ci-operator/jobs/quay/quay-tests/quay-quay-tests-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#57505 [INTEROP-7527] OCP 4.18 expansion for MTR lp-interop.
  ci-operator/config/windup/.config.prowgen
  ci-operator/config/windup/windup-ui-tests/windup-windup-ui-tests-v1.2__mtr-ocp4.18-lp-interop.yaml
  ci-operator/jobs/windup/windup-ui-tests/windup-windup-ui-tests-main-presubmits.yaml
  ci-operator/jobs/windup/windup-ui-tests/windup-windup-ui-tests-v1.2-periodics.yaml
  ci-operator/jobs/windup/windup-ui-tests/windup-windup-ui-tests-v1.2-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#57449 Add basic lint checking to telco-reference
  ci-operator/config/openshift-kni/telco-reference/OWNERS
  ci-operator/config/openshift-kni/telco-reference/openshift-kni-telco-reference-main.yaml
  ci-operator/jobs/openshift-kni/telco-reference/OWNERS
  ci-operator/jobs/openshift-kni/telco-reference/openshift-kni-telco-reference-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#57473 [descheduler] cover load-aware-descheduling branch
  ci-operator/config/openshift/descheduler/OWNERS
  ci-operator/config/openshift/descheduler/openshift-descheduler-load-aware-descheduling.yaml
  ci-operator/jobs/openshift/descheduler/openshift-descheduler-load-aware-descheduling-postsubmits.yaml
  ci-operator/jobs/openshift/descheduler/openshift-descheduler-load-aware-descheduling-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#57515 NO-ISSUE: Add OCP 4.16 odf, cnv jobs for assisted-service
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#57458 OCM-11612 | ci: Fix rosa-hcp-regional job
  ci-operator/config/openshift/rosa/openshift-rosa-master__e2e.yaml
Labels: lgtm, approved, rehearsals-ack

#57512 Revert "[openstack-k8s-operators][fips-check] Use custom image"
  ci-operator/step-registry/openstack-k8s-operators/fips-check/openstack-k8s-operators-fips-check-commands.sh
Labels: lgtm, approved, rehearsals-ack

#57522 failover build10
  core-services/sanitize-prow-jobs/_clusters.yaml
Labels: lgtm, approved, rehearsals-ack

#57513 gpu-scheduling-webhook: increase deployment replicas
  clusters/build-clusters/common_gpu_scheduling_webhook/20_deployment.yaml
Labels: lgtm, approved, rehearsals-ack

#57511 Fix the volume name
  ci-operator/step-registry/upi/install/libvirt/upi-install-libvirt-commands.sh
Labels: lgtm, approved, rehearsals-ack

#57526 OpenStack: Use RAMFS for UPI jobs
  ci-operator/step-registry/upi/openstack/pre/upi-openstack-pre-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#57521 NO-ISSUE: Make sure MicroShift is released when using RHOCP
  ci-operator/step-registry/openshift/microshift/clusterbot/prepare-host/openshift-microshift-clusterbot-prepare-host-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#57541 updated Prow config for Kuadrant: renaming console-plugin
  core-services/prow/02_config/Kuadrant/kuadrant-console-plugin/OWNERS
  core-services/prow/02_config/Kuadrant/kuadrant-console-plugin/_pluginconfig.yaml
  core-services/prow/02_config/Kuadrant/kuadrant-console-plugin/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#57113 support for ocp 4.18 for rhscl
  ci-operator/config/sclorg/ansible-tests/sclorg-ansible-tests-master__rhscl-ocp4.18-lp-interop.yaml
  ci-operator/jobs/sclorg/ansible-tests/sclorg-ansible-tests-master-periodics.yaml
  ci-operator/jobs/sclorg/ansible-tests/sclorg-ansible-tests-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#57249 OCPBUGS-41363 Add e2e-metal CI job for versions 4.12 through 4.15 to openshift/images repository to exercise the keepalived-ipfailover component
  ci-operator/config/openshift/images/openshift-images-release-4.12.yaml
  ci-operator/config/openshift/images/openshift-images-release-4.13.yaml
  ci-operator/config/openshift/images/openshift-images-release-4.14.yaml
  ci-operator/config/openshift/images/openshift-images-release-4.15.yaml
  ci-operator/jobs/openshift/images/openshift-images-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift/images/openshift-images-release-4.13-presubmits.yaml
  ci-operator/jobs/openshift/images/openshift-images-release-4.14-presubmits.yaml
  ci-operator/jobs/openshift/images/openshift-images-release-4.15-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#57472 SPLAT-1834: disable sosreport collection for UPI vSphere jobs
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.16.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.17.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.18.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#55897 4.17 rosa loaded upgrade
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa-4.17-candidate-x86-loaded-upgrade-from-4.16.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa_hcp-4.17-candidate-x86-loaded-upgrade-from-4.16.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#57551 include osde2e abs path when calling it in cleanup jobs
  ci-operator/config/openshift/osde2e/openshift-osde2e-main.yaml
Labels: lgtm, approved, rehearsals-ack

#57554 Update prometheus configMap resources
  clusters/build-clusters/build09/openshift-monitoring/cluster-monitoring-config.yaml
  clusters/build-clusters/build10/openshift-monitoring/cluster-monitoring-config.yaml
  clusters/build-clusters/build11/openshift-monitoring/cluster-monitoring-config.yaml
Labels: lgtm, approved, rehearsals-ack

#56468 SPLAT-1628: disable AWS platform external skips
  ci-operator/step-registry/openshift/e2e/external/aws/openshift-e2e-external-aws-workflow.yaml
  ci-operator/step-registry/platform-external/cluster/wait-for/install-complete/platform-external-cluster-wait-for-install-complete-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#57562 [CIGolang]update tag fro hypershift-operator
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-master.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19.yaml
Labels: lgtm, approved, rehearsals-ack

#57558 ci-chat-bot: fix rosa file permissions
  clusters/app.ci/ci-chat-bot/ci-chat-bot.yaml
Labels: lgtm, approved, rehearsals-ack

#57110 Add ARO 4.15.27 upgrade to 4.15 nightly and e2e testing
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly-4.15-upgrade-from-aro-4.15.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
  ci-operator/step-registry/aro/provision/cluster/aro-provision-cluster-commands.sh
Labels: lgtm, approved, rehearsals-ack

#57540 expansion of jws scenario to run for 4.18
  ci-operator/config/jws-qe/interop-ocp-ci/.config.prowgen
  ci-operator/config/jws-qe/interop-ocp-ci/jws-qe-interop-ocp-ci-main__ocp-4.18-lp-interop.yaml
  ci-operator/jobs/jws-qe/interop-ocp-ci/jws-qe-interop-ocp-ci-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#56439 NP-1075: Remove SD clusters disguise from live migration CI jobs for 4.15
  ci-operator/config/openshift-priv/cluster-network-operator/openshift-priv-cluster-network-operator-release-4.15.yaml
  ci-operator/config/openshift-priv/ovn-kubernetes/openshift-priv-ovn-kubernetes-release-4.15.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.15.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.15.yaml
  ci-operator/step-registry/ovn/sdn-live-migration-init/OWNERS
  ci-operator/step-registry/ovn/sdn-live-migration-init/ovn-sdn-live-migration-init-commands.sh
  ci-operator/step-registry/ovn/sdn-live-migration-init/ovn-sdn-live-migration-init-ref.metadata.json
  ci-operator/step-registry/ovn/sdn-live-migration-init/ovn-sdn-live-migration-init-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#57293 disabling FIPS for 4.16 TP tests due to OCPBUGS-35808
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__multi-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
Labels: lgtm, approved, rehearsals-ack
