Repository openshift/release, pull requests merged in 2024-07, with the labels that each got.

#52846 Adding 4.17 jobs
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.17-nightly-x86.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-periodics.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#53602 OCPQE-23166: [4.17] add GCP CAPI tests and FIPS+TP tests
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__multi-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#53765 post to renamed channel
  ci-operator/jobs/infra-image-mirroring.yaml
Labels: lgtm, approved, rehearsals-ack

#53833 OCPBUGS-36352: change PACKET_OS to 'rocky_9'
  ci-operator/step-registry/cucushift/installer/rehearse/baremetalds/ipi/ovn/ipv4/kubevirt/provision/cucushift-installer-rehearse-baremetalds-ipi-ovn-ipv4-kubevirt-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/baremetalds/ipi/provision/cucushift-installer-rehearse-baremetalds-ipi-provision-chain.yaml
Labels: lgtm, approved, jira/valid-bug, rehearsals-ack, jira/valid-reference

#52984 OCPQE-16512 Add IPI BM job config with fips enabled
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__multi-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
  ci-operator/step-registry/baremetal/lab/ipi/install/baremetal-lab-ipi-install-commands.sh
  ci-operator/step-registry/baremetal/lab/ipi/install/baremetal-lab-ipi-install-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#53830 OCPQE-23300: Refine 4.14 test frequency
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly-4.14-upgrade-from-aro-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly-4.14-upgrade-from-eus-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly-4.14-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly-4.14-upgrade-from-stable-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly-openshift-logging-5.8.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-rollback-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-rollback-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-stable-4.14-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly-4.14-upgrade-from-eus-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly-4.14-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly-4.14-upgrade-from-stable-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly-openshift-logging-5.8.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-stable-4.14-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-nightly-4.14-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-nightly-4.14-upgrade-from-stable-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-nightly-openshift-logging-5.7.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-stable-4.14-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-stable.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#53789 Light cleanup in makefile plus new temp message
  Makefile
  hack/refresh-bugzilla-prs.sh
Labels: lgtm, approved, rehearsals-ack

#53791 OCPQE-23207 ROSA HCP should use extended health check
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-stable.yaml
Labels: lgtm, approved, rehearsals-ack

#53774 OCPQE-23276: handle junit results robustly
  ci-operator/step-registry/cucushift/chainupgrade/toimage/cucushift-chainupgrade-toimage-commands.sh
  ci-operator/step-registry/cucushift/e2e/cucushift-e2e-commands.sh
  ci-operator/step-registry/cucushift/e2e/devel/cucushift-e2e-devel-commands.sh
  ci-operator/step-registry/cucushift/upgrade/check/cucushift-upgrade-check-commands.sh
  ci-operator/step-registry/cucushift/upgrade/prepare/cucushift-upgrade-prepare-commands.sh
  ci-operator/step-registry/openshift-extended/logging-test/openshift-extended-logging-test-commands.sh
  ci-operator/step-registry/openshift-extended/logging-test/web-tests/openshift-extended-logging-test-web-tests-commands.sh
  ci-operator/step-registry/openshift-extended/rosacli-tests/openshift-extended-rosacli-tests-commands.sh
  ci-operator/step-registry/openshift-extended/test/disasterrecovery/openshift-extended-test-disasterrecovery-commands.sh
  ci-operator/step-registry/openshift-extended/test/disruptive/openshift-extended-test-disruptive-commands.sh
  ci-operator/step-registry/openshift-extended/test/longduration/openshift-extended-test-longduration-commands.sh
  ci-operator/step-registry/openshift-extended/test/openshift-extended-test-commands.sh
  ci-operator/step-registry/openshift-extended/test/stresstest/openshift-extended-test-stresstest-commands.sh
  ci-operator/step-registry/openshift-extended/test/supplementary/openshift-extended-test-supplementary-commands.sh
  ci-operator/step-registry/openshift-extended/web-tests/ext-oidc-cli-login/openshift-extended-web-tests-ext-oidc-cli-login-commands.sh
  ci-operator/step-registry/openshift-extended/web-tests/openshift-extended-web-tests-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#53839 medik8s: Remove branch protection config
  core-services/prow/02_config/medik8s/.github/OWNERS
  core-services/prow/02_config/medik8s/.github/_prowconfig.yaml
  core-services/prow/02_config/medik8s/common/OWNERS
  core-services/prow/02_config/medik8s/common/_prowconfig.yaml
  core-services/prow/02_config/medik8s/customized-user-remediation/OWNERS
  core-services/prow/02_config/medik8s/customized-user-remediation/_prowconfig.yaml
  core-services/prow/02_config/medik8s/docs/OWNERS
  core-services/prow/02_config/medik8s/docs/_prowconfig.yaml
  core-services/prow/02_config/medik8s/fence-agents-remediation/OWNERS
  core-services/prow/02_config/medik8s/fence-agents-remediation/_prowconfig.yaml
  core-services/prow/02_config/medik8s/machine-deletion-remediation/OWNERS
  core-services/prow/02_config/medik8s/machine-deletion-remediation/_prowconfig.yaml
  core-services/prow/02_config/medik8s/must-gather/OWNERS
  core-services/prow/02_config/medik8s/must-gather/_prowconfig.yaml
  core-services/prow/02_config/medik8s/node-healthcheck-operator/OWNERS
  core-services/prow/02_config/medik8s/node-healthcheck-operator/_prowconfig.yaml
  core-services/prow/02_config/medik8s/node-maintenance-operator/OWNERS
  core-services/prow/02_config/medik8s/node-maintenance-operator/_prowconfig.yaml
  core-services/prow/02_config/medik8s/node-remediation-console/_prowconfig.yaml
  core-services/prow/02_config/medik8s/self-node-remediation/OWNERS
  core-services/prow/02_config/medik8s/self-node-remediation/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#53828 [4.14] move some disconnected ci jobs to single arch ci
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#53817 Sync Serverless CI config/
  ci-operator/config/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-next__412.yaml
  ci-operator/config/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-next__415.yaml
  ci-operator/config/openshift-knative/eventing-kafka-broker/openshift-knative-eventing-kafka-broker-release-next__416.yaml
  core-services/image-mirroring/knative/mapping_knative_knative-nightly_eventing-kafka-broker_quay
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#53005 OCPBUGS-35209: Update centos image and repo for openshift ansible
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-master.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-4.14.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-4.15.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-4.16.yaml
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-release-4.17.yaml
Labels: lgtm, approved, jira/valid-bug, rehearsals-ack, jira/valid-reference

#53822 Copy provisioning-host-ssh-port arch file to Cluster dir
  ci-operator/step-registry/baremetal/lab/ipi/install/baremetal-lab-ipi-install-commands.sh
Labels: lgtm, approved, rehearsals-ack

#53816 OCPEDGE-1170: fix: informing sno upgrade jobs
  core-services/release-controller/_releases/priv/release-ocp-4.17.json
  core-services/release-controller/_releases/release-ocp-4.17.json
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#53853 Remove both autoscaler pods as part of cron
  clusters/build-clusters/build04/assets/auto-scaler-cron.yaml
Labels: lgtm, approved, rehearsals-ack

#53486 Removing Intersmash
  ci-operator/config/Intersmash/intersmash/Intersmash-intersmash-main.yaml
  ci-operator/config/Intersmash/intersmash/Intersmash-intersmash-main__periodic.yaml
  ci-operator/config/Intersmash/intersmash/Intersmash-intersmash-main__prod.yaml
  ci-operator/config/Intersmash/intersmash/OWNERS
  ci-operator/jobs/Intersmash/intersmash/Intersmash-intersmash-main-periodics.yaml
  ci-operator/jobs/Intersmash/intersmash/Intersmash-intersmash-main-presubmits.yaml
  ci-operator/jobs/Intersmash/intersmash/OWNERS
  core-services/prow/02_config/Intersmash/intersmash/OWNERS
  core-services/prow/02_config/Intersmash/intersmash/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#53841 bump kuttl version to 0.17.0
  ci-operator/config/openstack-k8s-operators/barbican-operator/openstack-k8s-operators-barbican-operator-main.yaml
  ci-operator/config/openstack-k8s-operators/cinder-operator/openstack-k8s-operators-cinder-operator-main.yaml
  ci-operator/config/openstack-k8s-operators/dataplane-operator/openstack-k8s-operators-dataplane-operator-main.yaml
  ci-operator/config/openstack-k8s-operators/designate-operator/openstack-k8s-operators-designate-operator-main.yaml
  ci-operator/config/openstack-k8s-operators/glance-operator/openstack-k8s-operators-glance-operator-main.yaml
  ci-operator/config/openstack-k8s-operators/heat-operator/openstack-k8s-operators-heat-operator-main.yaml
  ci-operator/config/openstack-k8s-operators/horizon-operator/openstack-k8s-operators-horizon-operator-main.yaml
  ci-operator/config/openstack-k8s-operators/infra-operator/openstack-k8s-operators-infra-operator-main.yaml
  ci-operator/config/openstack-k8s-operators/ironic-operator/openstack-k8s-operators-ironic-operator-main.yaml
  ci-operator/config/openstack-k8s-operators/keystone-operator/openstack-k8s-operators-keystone-operator-main.yaml
  ci-operator/config/openstack-k8s-operators/manila-operator/openstack-k8s-operators-manila-operator-main.yaml
  ci-operator/config/openstack-k8s-operators/mariadb-operator/openstack-k8s-operators-mariadb-operator-main.yaml
  ci-operator/config/openstack-k8s-operators/neutron-operator/openstack-k8s-operators-neutron-operator-main.yaml
  ci-operator/config/openstack-k8s-operators/octavia-operator/openstack-k8s-operators-octavia-operator-main.yaml
  ci-operator/config/openstack-k8s-operators/openstack-ansibleee-operator/openstack-k8s-operators-openstack-ansibleee-operator-main.yaml
  ci-operator/config/openstack-k8s-operators/openstack-operator/openstack-k8s-operators-openstack-operator-main.yaml
  ci-operator/config/openstack-k8s-operators/ovn-operator/openstack-k8s-operators-ovn-operator-main.yaml
  ci-operator/config/openstack-k8s-operators/placement-operator/openstack-k8s-operators-placement-operator-main.yaml
  ci-operator/config/openstack-k8s-operators/swift-operator/openstack-k8s-operators-swift-operator-main.yaml
  ci-operator/config/openstack-k8s-operators/telemetry-operator/openstack-k8s-operators-telemetry-operator-main.yaml
Labels: lgtm, approved, rehearsals-ack

#53859 [LPTOCPCI-1382] Add interop group to qci image puller rbac
  clusters/app.ci/assets/admin_qci-image-puller_rbac.yaml
Labels: lgtm, approved, rehearsals-ack

#53855 Add new profile: equinix-ocp-hcp
  core-services/ci-secret-bootstrap/_config.yaml
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: lgtm, approved, rehearsals-ack

#53843 Update initial-minor for API upgrade jobs
  ci-operator/config/openshift/api/openshift-api-master.yaml
  ci-operator/config/openshift/api/openshift-api-release-4.17.yaml
  ci-operator/config/openshift/api/openshift-api-release-4.18.yaml
Labels: lgtm, approved, rehearsals-ack

#53741 Update LP Interop configs to OCP version 4.17
  ci-operator/config/3scale-qe/3scale-deploy/3scale-qe-3scale-deploy-main__3scale-amp-ocp4.17-lp-interop.yaml
  ci-operator/config/amq-streams-qe/strimzi-kafka-operator/amq-streams-qe-strimzi-kafka-operator-main__amq-streams-ocp4.17-lp-interop.yaml
  ci-operator/config/ansible/tower-qa/ansible-tower-qa-devel__ocp4.17-lp-interop.yaml
  ci-operator/config/infinispan/infinispan-operator/infinispan-infinispan-operator-stable__data-grid-ocp4.17-lp-interop.yaml
  ci-operator/config/jboss-fuse/camel-k-test-container/jboss-fuse-camel-k-test-container-main__camel-k-ocp4.17-lp-interop.yaml
  ci-operator/config/jboss-fuse/camel-quarkus-openshift-interop/jboss-fuse-camel-quarkus-openshift-interop-main__camel-quarkus-ocp4.17-lp-interop.yaml
  ci-operator/config/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-main__oadp1.3-ocp4.17-lp-interop.yaml
  ci-operator/config/redhat-developer/helm/redhat-developer-helm-release-3.11__helm-ocp4.17-lp-interop.yaml
  ci-operator/config/rh-messaging-qe/claire/rh-messaging-qe-claire-lpt__amq-broker-ocp4.17-lp-interop.yaml
  ci-operator/config/sclorg/ansible-tests/sclorg-ansible-tests-master__dotnet-ocp4.17-lp-interop.yaml
  ci-operator/jobs/3scale-qe/3scale-deploy/3scale-qe-3scale-deploy-main-periodics.yaml
  ci-operator/jobs/3scale-qe/3scale-deploy/3scale-qe-3scale-deploy-main-presubmits.yaml
  ci-operator/jobs/amq-streams-qe/strimzi-kafka-operator/amq-streams-qe-strimzi-kafka-operator-main-periodics.yaml
  ci-operator/jobs/ansible/tower-qa/ansible-tower-qa-devel-periodics.yaml
  ci-operator/jobs/infinispan/infinispan-operator/infinispan-infinispan-operator-stable-periodics.yaml
  ci-operator/jobs/infinispan/infinispan-operator/infinispan-infinispan-operator-stable-presubmits.yaml
  ci-operator/jobs/jboss-fuse/camel-k-test-container/jboss-fuse-camel-k-test-container-main-periodics.yaml
  ci-operator/jobs/jboss-fuse/camel-k-test-container/jboss-fuse-camel-k-test-container-main-presubmits.yaml
  ci-operator/jobs/jboss-fuse/camel-quarkus-openshift-interop/jboss-fuse-camel-quarkus-openshift-interop-main-periodics.yaml
  ci-operator/jobs/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-main-periodics.yaml
  ci-operator/jobs/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-main-presubmits.yaml
  ci-operator/jobs/redhat-developer/helm/redhat-developer-helm-release-3.11-periodics.yaml
  ci-operator/jobs/redhat-developer/helm/redhat-developer-helm-release-3.11-presubmits.yaml
  ci-operator/jobs/rh-messaging-qe/claire/rh-messaging-qe-claire-lpt-periodics.yaml
  ci-operator/jobs/sclorg/ansible-tests/sclorg-ansible-tests-master-periodics.yaml
  ci-operator/jobs/sclorg/ansible-tests/sclorg-ansible-tests-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#53865 add lenient blackbox probe and alert
  clusters/app.ci/openshift-user-workload-monitoring/blackbox_probe.yaml
  clusters/app.ci/openshift-user-workload-monitoring/mixins/_prometheus/dptp_alerts.libsonnet
  clusters/app.ci/openshift-user-workload-monitoring/mixins/prometheus_out/ci-alerts_prometheusrule.yaml
Labels: lgtm, approved, rehearsals-ack

#53863 Update config to use preprod registry steps
  ci-operator/config/redhat-openshift-ecosystem/certified-operators-preprod/redhat-openshift-ecosystem-certified-operators-preprod-ocp-4.15.yaml
  ci-operator/config/redhat-openshift-ecosystem/certified-operators-preprod/redhat-openshift-ecosystem-certified-operators-preprod-ocp-4.16.yaml
Labels: lgtm, approved, rehearsals-ack

#53857 fix ipi vcm deprov
  ci-operator/step-registry/ipi/conf/vsphere/check/vcm/ipi-conf-vsphere-check-vcm-commands.sh
  ci-operator/step-registry/ipi/deprovision/vsphere/diags/vcm/ipi-deprovision-vsphere-diags-vcm-commands.sh
  ci-operator/step-registry/ipi/deprovision/vsphere/diags/vcm/ipi-deprovision-vsphere-diags-vcm-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#53852 [MCO] Move the base image to ubi 9 on 2.11
  ci-operator/config/stolostron/multicluster-observability-operator/stolostron-multicluster-observability-operator-main.yaml
  ci-operator/config/stolostron/multicluster-observability-operator/stolostron-multicluster-observability-operator-release-2.11.yaml
Labels: lgtm, approved, rehearsals-ack

#53858 ocpbugs-36299: add hypershift presubmits
  ci-operator/config/openshift/cluster-monitoring-operator/openshift-cluster-monitoring-operator-master.yaml
  ci-operator/config/openshift/cluster-monitoring-operator/openshift-cluster-monitoring-operator-release-4.17.yaml
  ci-operator/config/openshift/cluster-monitoring-operator/openshift-cluster-monitoring-operator-release-4.18.yaml
  ci-operator/jobs/openshift/cluster-monitoring-operator/openshift-cluster-monitoring-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-monitoring-operator/openshift-cluster-monitoring-operator-release-4.17-presubmits.yaml
  ci-operator/jobs/openshift/cluster-monitoring-operator/openshift-cluster-monitoring-operator-release-4.18-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#53870 Add new profile: equinix-ocp-hcp
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#53811 TRT-1724: remove aggregated jobs for 4.16 (it's GA)
  core-services/release-controller/_releases/priv/release-ocp-4.16.json
  core-services/release-controller/_releases/release-ocp-4.16-ci.json
  core-services/release-controller/_releases/release-ocp-4.16.json
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#53861 Updated discovery go version to 1.22
  ci-operator/config/stolostron/discovery/stolostron-discovery-backplane-2.7.yaml
  ci-operator/config/stolostron/discovery/stolostron-discovery-main.yaml
Labels: lgtm, approved, rehearsals-ack

#53873 [azure-workload-identity] rename Dockerfile
  ci-operator/config/openshift/azure-workload-identity/openshift-azure-workload-identity-main.yaml
Labels: lgtm, approved, rehearsals-ack

#53628 Test limited live migration
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__multi-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
  ci-operator/step-registry/cucushift/sdn-live-migration-ovn/OWNERS
  ci-operator/step-registry/cucushift/sdn-live-migration-ovn/cucushift-sdn-live-migration-ovn-chain.metadata.json
  ci-operator/step-registry/cucushift/sdn-live-migration-ovn/cucushift-sdn-live-migration-ovn-chain.yaml
  ci-operator/step-registry/cucushift/sdn-live-migration-ovn/cucushift-sdn-live-migration-ovn-commands.sh
  ci-operator/step-registry/cucushift/sdn-live-migration-ovn/cucushift-sdn-live-migration-ovn-ref.metadata.json
  ci-operator/step-registry/cucushift/sdn-live-migration-ovn/cucushift-sdn-live-migration-ovn-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#53880 Unify test frequency
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly-4.12-upgrade-from-aro-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-4.13-upgrade-from-aro-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly-4.15-upgrade-from-aro-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly-4.16-upgrade-from-aro-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly-4.16-upgrade-from-stable-4.1.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly-4.16-upgrade-from-stable-4.10.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly-4.16-upgrade-from-stable-4.11.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly-4.16-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly-4.16-upgrade-from-stable-4.15.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly-4.16-upgrade-from-stable-4.16.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly-4.16-upgrade-from-stable-4.2.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly-4.16-upgrade-from-stable-4.3.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly-4.16-upgrade-from-stable-4.4.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly-4.16-upgrade-from-stable-4.5.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly-4.16-upgrade-from-stable-4.6.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly-4.16-upgrade-from-stable-4.7.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly-4.16-upgrade-from-stable-4.8.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly-4.16-upgrade-from-stable-4.9.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#53881 OCPQE-23322: Refine 4.15 test frequency
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__multi-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#53876 medik8s: update base image to CentOS Stream9
  ci-operator/config/medik8s/fence-agents-remediation/medik8s-fence-agents-remediation-main__4.12.yaml
  ci-operator/config/medik8s/fence-agents-remediation/medik8s-fence-agents-remediation-main__4.13.yaml
  ci-operator/config/medik8s/fence-agents-remediation/medik8s-fence-agents-remediation-main__4.14.yaml
  ci-operator/config/medik8s/fence-agents-remediation/medik8s-fence-agents-remediation-main__4.15.yaml
  ci-operator/config/medik8s/fence-agents-remediation/medik8s-fence-agents-remediation-main__4.16.yaml
  ci-operator/config/medik8s/fence-agents-remediation/medik8s-fence-agents-remediation-main__4.17.yaml
  ci-operator/config/medik8s/fence-agents-remediation/medik8s-fence-agents-remediation-release-0.4__4.12.yaml
  ci-operator/config/medik8s/fence-agents-remediation/medik8s-fence-agents-remediation-release-0.4__4.13.yaml
  ci-operator/config/medik8s/fence-agents-remediation/medik8s-fence-agents-remediation-release-0.4__4.14.yaml
  ci-operator/config/medik8s/fence-agents-remediation/medik8s-fence-agents-remediation-release-0.4__4.15.yaml
  ci-operator/config/medik8s/fence-agents-remediation/medik8s-fence-agents-remediation-release-0.4__4.16.yaml
  ci-operator/config/medik8s/fence-agents-remediation/medik8s-fence-agents-remediation-release-0.4__4.17.yaml
Labels: lgtm, approved, rehearsals-ack

#53216 MULTIARCH-4684: Change release payload to multi-latest for ppc64le jobs
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.15.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.16.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.17.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#53877 [cluster-etcd-operator] rename Dockerfile
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-master.yaml
Labels: lgtm, approved, rehearsals-ack

#51667 OCPBUGS-33278: remove e2e-gcp-qe-no-capabilities
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-master.yaml
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.13.yaml
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.14.yaml
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.15.yaml
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.16.yaml
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.17.yaml
  ci-operator/config/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.18.yaml
  ci-operator/jobs/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.13-presubmits.yaml
  ci-operator/jobs/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.14-presubmits.yaml
  ci-operator/jobs/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.15-presubmits.yaml
  ci-operator/jobs/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.16-presubmits.yaml
  ci-operator/jobs/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.17-presubmits.yaml
  ci-operator/jobs/openshift/cluster-etcd-operator/openshift-cluster-etcd-operator-release-4.18-presubmits.yaml
Labels: lgtm, approved, jira/valid-bug, rehearsals-ack, jira/valid-reference

#53883 [azure] add checkpoint for azure identity attached to master instances
  ci-operator/step-registry/cucushift/installer/check/azure/cp/identity/OWNERS
  ci-operator/step-registry/cucushift/installer/check/azure/cp/identity/cucushift-installer-check-azure-cp-identity-commands.sh
  ci-operator/step-registry/cucushift/installer/check/azure/cp/identity/cucushift-installer-check-azure-cp-identity-ref.metadata.json
  ci-operator/step-registry/cucushift/installer/check/azure/cp/identity/cucushift-installer-check-azure-cp-identity-ref.yaml
  ci-operator/step-registry/cucushift/installer/check/azure/cucushift-installer-check-azure-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#53886 Medik8s: fix far base image
  ci-operator/config/medik8s/fence-agents-remediation/medik8s-fence-agents-remediation-main__4.12.yaml
  ci-operator/config/medik8s/fence-agents-remediation/medik8s-fence-agents-remediation-main__4.13.yaml
  ci-operator/config/medik8s/fence-agents-remediation/medik8s-fence-agents-remediation-main__4.14.yaml
  ci-operator/config/medik8s/fence-agents-remediation/medik8s-fence-agents-remediation-main__4.15.yaml
  ci-operator/config/medik8s/fence-agents-remediation/medik8s-fence-agents-remediation-main__4.16.yaml
  ci-operator/config/medik8s/fence-agents-remediation/medik8s-fence-agents-remediation-main__4.17.yaml
  ci-operator/config/medik8s/fence-agents-remediation/medik8s-fence-agents-remediation-release-0.4__4.12.yaml
  ci-operator/config/medik8s/fence-agents-remediation/medik8s-fence-agents-remediation-release-0.4__4.13.yaml
  ci-operator/config/medik8s/fence-agents-remediation/medik8s-fence-agents-remediation-release-0.4__4.14.yaml
  ci-operator/config/medik8s/fence-agents-remediation/medik8s-fence-agents-remediation-release-0.4__4.15.yaml
  ci-operator/config/medik8s/fence-agents-remediation/medik8s-fence-agents-remediation-release-0.4__4.16.yaml
  ci-operator/config/medik8s/fence-agents-remediation/medik8s-fence-agents-remediation-release-0.4__4.17.yaml
Labels: lgtm, approved, rehearsals-ack

#53856 update rhdh base image
  ci-operator/config/janus-idp/backstage-showcase/janus-idp-backstage-showcase-1.2.x.yaml
  ci-operator/config/janus-idp/backstage-showcase/janus-idp-backstage-showcase-main.yaml
Labels: lgtm, approved, rehearsals-ack

#53854 [maistra] Add OPERATOR_VERSION variable for test suite to skip unsupported tests
  ci-operator/config/maistra/maistra-test-tool/maistra-maistra-test-tool-main__servicemesh-hypershift-4.14-lp-rosa-hypershift.yaml
  ci-operator/config/maistra/maistra-test-tool/maistra-maistra-test-tool-main__servicemesh-hypershift-4.15-lp-rosa-hypershift.yaml
  ci-operator/config/maistra/maistra-test-tool/maistra-maistra-test-tool-main__servicemesh-ocp4.13-lp-interop.yaml
  ci-operator/config/maistra/maistra-test-tool/maistra-maistra-test-tool-main__servicemesh-ocp4.14-lp-interop.yaml
  ci-operator/config/maistra/maistra-test-tool/maistra-maistra-test-tool-main__servicemesh-ocp4.14-lp-rosa-classic.yaml
  ci-operator/config/maistra/maistra-test-tool/maistra-maistra-test-tool-main__servicemesh-ocp4.15-lp-interop.yaml
  ci-operator/config/maistra/maistra-test-tool/maistra-maistra-test-tool-main__servicemesh-ocp4.16-lp-interop.yaml
  ci-operator/step-registry/servicemesh/maistra-test-tool/execute/servicemesh-maistra-test-tool-execute-ref.yaml
  ci-operator/step-registry/servicemesh/smcp/install/servicemesh-smcp-install-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#53885 Add nutanix e2e network check
  ci-operator/step-registry/cucushift/installer/check/nutanix/infra/OWNERS
  ci-operator/step-registry/cucushift/installer/check/nutanix/infra/cucushift-installer-check-nutanix-infra-commands.sh
  ci-operator/step-registry/cucushift/installer/check/nutanix/infra/cucushift-installer-check-nutanix-infra-ref.metadata.json
  ci-operator/step-registry/cucushift/installer/check/nutanix/infra/cucushift-installer-check-nutanix-infra-ref.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/nutanix/ipi/boot-categories-project/provision/cucushift-installer-rehearse-nutanix-ipi-boot-categories-project-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/nutanix/ipi/disconnected/provision/cucushift-installer-rehearse-nutanix-ipi-disconnected-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/nutanix/ipi/proxy/provision/cucushift-installer-rehearse-nutanix-ipi-proxy-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/nutanix/ipi/zones/provision/cucushift-installer-rehearse-nutanix-ipi-zones-provision-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#53892 SNC: Add release-4.17 branch
  ci-operator/config/crc-org/snc/crc-org-snc-release-4.17.yaml
  ci-operator/jobs/crc-org/snc/crc-org-snc-release-4.17-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#53894 Add msi-qe group to qci image puller
  clusters/app.ci/assets/admin_qci-image-puller_rbac.yaml
Labels: lgtm, approved, rehearsals-ack

#53896 Gangway oauth update
  clusters/app.ci/prow/03_deployment/gangway.yaml
Labels: lgtm, approved, rehearsals-ack

#53887 Update Golang version to 1.22 in Distributed Tracing jobs
  ci-operator/config/openshift/distributed-tracing-qe/openshift-distributed-tracing-qe-main__ocp4.14-acceptance.yaml
  ci-operator/config/openshift/distributed-tracing-qe/openshift-distributed-tracing-qe-main__ocp4.14-dast.yaml
  ci-operator/config/openshift/distributed-tracing-qe/openshift-distributed-tracing-qe-main__ocp4.15-disconnected.yaml
  ci-operator/config/openshift/grafana-tempo-operator/README.md
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__ocp4.13-amd64-upgrade.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__ocp4.13-hypershift.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__ocp4.14-amd64.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.12-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.13-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.14-arm-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.14-lp-interop.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.14-lp-rosa-classic.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.14-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.15-ibm-p-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.15-ibm-z-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.15-lp-interop.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.15-lp-rosa-classic.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.15-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.16-lp-interop.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.16-stage.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/README.md
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-hypershift-4.12-lp-rosa-hypershift.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-hypershift-4.13-lp-rosa-hypershift.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-hypershift-4.14-lp-rosa-hypershift.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-hypershift-4.15-lp-rosa-hypershift.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.12-stage.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.13-stage.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.14-arm-stage.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.14-lp-interop.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.14-stage.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.15-ibm-p-stage.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.15-ibm-z-stage.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.15-lp-interop.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.15-stage.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.16-lp-interop.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.16-stage.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__ocp-4.13-hypershift.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__ocp-4.14-amd64.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/README.md
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__ocp-4.13-amd64-upgrade.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__ocp-4.13-hypershift.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__ocp-4.14-amd64.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.12-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.13-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.14-arm-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.14-lp-interop.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.14-lp-rosa-classic.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.14-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.15-lp-interop.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.15-lp-rosa-classic.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.15-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.16-lp-interop.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.16-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-ibm-p-4.15-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-ibm-z-4.15-stage.yaml
Labels: lgtm, approved, rehearsals-ack

#53889 OCPEDGE-1151: chore: move pre commit check to base image
  ci-operator/config/openshift/lvm-operator/openshift-lvm-operator-main.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#53900 odf: add ibm_storage to allowed Bugzilla groups
  core-services/prow/02_config/red-hat-storage/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#53803 OCM-9205 Setup TF day1 supplemental jobs
  ci-operator/config/terraform-redhat/terraform-provider-rhcs/terraform-redhat-terraform-provider-rhcs-main.yaml
  ci-operator/jobs/terraform-redhat/terraform-provider-rhcs/terraform-redhat-terraform-provider-rhcs-main-periodics.yaml
  ci-operator/jobs/terraform-redhat/terraform-provider-rhcs/terraform-redhat-terraform-provider-rhcs-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#53882 [4.13] move some disconnected ci jobs to single arch ci
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__multi-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#53898 Remove some exceptions granted for cluster pools
  core-services/cluster-pools/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#53826 telco5g: Add packages to Telco CI image
  clusters/app.ci/supplemental-ci-images/telco-runner.yaml
Labels: lgtm, approved, rehearsals-ack

#53911 envoyproxy: update config
  clusters/app.ci/prow/03_deployment/gangway.yaml
  clusters/app.ci/supplemental-ci-images/envoyproxy/README.md
  clusters/app.ci/supplemental-ci-images/envoyproxy/envoyproxy.yaml
  clusters/app.ci/supplemental-ci-images/envoyproxy/gangway_api_descriptor.pb
Labels: lgtm, approved, rehearsals-ack

#53917 Enabling SCC on all the clusters in buildfarm
  clusters/build-clusters/02_cluster/openshift/scc
  clusters/build-clusters/build03/openshift/scc
  clusters/build-clusters/build04/openshift/scc
  clusters/build-clusters/build05/openshift/scc
  clusters/build-clusters/build09/openshift/scc
  clusters/build-clusters/common_except_app.ci/openshift/scc/README.md
  clusters/build-clusters/common_except_app.ci/openshift/scc/ci-privileged_scc.yaml
  clusters/build-clusters/common_except_app.ci/openshift/scc/vpn.yaml
Labels: lgtm, approved, rehearsals-ack

#53918 Pivot the multiarch-tuning-operator deploy in build10 to the one shipped in the openshift-operators catalog
  clusters/build-clusters/build10/multiarch-manager-operator/admin_01-operator.yaml
Labels: lgtm, approved, rehearsals-ack

#53903 Add perfscale to rover sync
  core-services/sync-rover-groups/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#53909 OCPEDGE-1151: chore: add patch to allow carry patches
  ci-operator/config/openshift/lvm-operator/openshift-lvm-operator-main.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#53922 Adding the openshift-metal-platform-tech to QCI Image Pullers
  clusters/app.ci/assets/admin_qci-image-puller_rbac.yaml
Labels: lgtm, approved, rehearsals-ack

#53925 Update the Makefile message for QCI login
  Makefile
Labels: do-not-merge/hold, lgtm, approved, rehearsals-ack

#53929 Update message for escape characters
  Makefile
Labels: lgtm, approved, rehearsals-ack

#53920 [LPTOCPCI-1383] Add option for new additional labels file in firewatch
  ci-operator/step-registry/firewatch/report-issues/firewatch-report-issues-commands.sh
  ci-operator/step-registry/firewatch/report-issues/firewatch-report-issues-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#53935 gh-automation periodic job is failing due to timeout
  ci-operator/jobs/infra-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#53939 Add telco-runner image to mirroring
  core-services/image-mirroring/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#53851 Add ocp4-stig test to ocp4e2e
  ci-operator/config/ComplianceAsCode/ocp4e2e/ComplianceAsCode-ocp4e2e-main.yaml
  ci-operator/jobs/ComplianceAsCode/ocp4e2e/ComplianceAsCode-ocp4e2e-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#53926 telco5g: Add HCP baremetal jobs to cnf-feature-deploy and fix releases
  ci-operator/config/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-master.yaml
  ci-operator/config/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.16.yaml
  ci-operator/jobs/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-master-presubmits.yaml
  ci-operator/jobs/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.16-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#53943 clusters/build-clusters/common_managed/rh-logging: Set cluster-monitoring namespace label
  clusters/build-clusters/common_managed/rh-logging.yaml
Labels: lgtm, approved, rehearsals-ack

#53932 backplane-must-gather: Upgrade to `oc` v4.16
  ci-operator/config/stolostron/backplane-must-gather/stolostron-backplane-must-gather-backplane-2.4.yaml
  ci-operator/config/stolostron/backplane-must-gather/stolostron-backplane-must-gather-backplane-2.5.yaml
  ci-operator/config/stolostron/backplane-must-gather/stolostron-backplane-must-gather-backplane-2.6.yaml
  ci-operator/config/stolostron/backplane-must-gather/stolostron-backplane-must-gather-backplane-2.7.yaml
  ci-operator/config/stolostron/backplane-must-gather/stolostron-backplane-must-gather-main.yaml
  ci-operator/jobs/stolostron/backplane-must-gather/stolostron-backplane-must-gather-backplane-2.4-presubmits.yaml
  ci-operator/jobs/stolostron/backplane-must-gather/stolostron-backplane-must-gather-backplane-2.5-presubmits.yaml
  ci-operator/jobs/stolostron/backplane-must-gather/stolostron-backplane-must-gather-backplane-2.6-presubmits.yaml
  ci-operator/jobs/stolostron/backplane-must-gather/stolostron-backplane-must-gather-backplane-2.7-presubmits.yaml
  ci-operator/jobs/stolostron/backplane-must-gather/stolostron-backplane-must-gather-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#53923 removing OCP 4.15 from preflight presubmits
  ci-operator/config/redhat-openshift-ecosystem/openshift-preflight/redhat-openshift-ecosystem-openshift-preflight-main__4.15.yaml
  ci-operator/jobs/redhat-openshift-ecosystem/openshift-preflight/redhat-openshift-ecosystem-openshift-preflight-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#53951 Scanner 2.34 release
  ci-operator/config/stackrox/scanner/stackrox-scanner-release-2.34.yaml
  ci-operator/jobs/stackrox/scanner/stackrox-scanner-release-2.34-postsubmits.yaml
  ci-operator/jobs/stackrox/scanner/stackrox-scanner-release-2.34-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#53948 [INTEROP-7432] Update weekly cron and watcher bot to 4.17.
  ci-operator/config/rhpit/interop-tests/rhpit-interop-tests-main__weekly_trigger.yaml
  ci-operator/jobs/rhpit/interop-tests/rhpit-interop-tests-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#53907 [4.12] move some disconnected ci jobs to single arch ci
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__multi-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#53953 Unify job names
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#53913 Fix building of binaries in OpenTelemetry jobs
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__ocp-4.13-amd64-upgrade.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__ocp-4.13-hypershift.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__ocp-4.14-amd64.yaml
Labels: lgtm, approved, rehearsals-ack

#53823 telco5g: Create HCP deployments
  ci-operator/step-registry/telco5g/hcp-cluster-setup/telco5g-hcp-cluster-setup-commands.sh
  ci-operator/step-registry/telco5g/hcp-release-cluster/telco5g-hcp-release-cluster-commands.sh
Labels: lgtm, approved, rehearsals-ack

#53608 Fix apf description
  ci-operator/step-registry/openshift-qe/run-api-apf-customized-flowcontrol/openshift-qe-run-api-apf-customized-flowcontrol-commands.sh
Labels: lgtm, approved, rehearsals-ack

#53940 [cluster-capacity] Rename dockerfile
  ci-operator/config/openshift/cluster-capacity/openshift-cluster-capacity-master.yaml
Labels: lgtm, approved, rehearsals-ack

#53962 Makefile.legacy, eg: make -f Makefile.legacy jobs
  Makefile.legacy
Labels: lgtm, approved, rehearsals-ack

#52706 STOR-1856: build AWS EFS operator from csi-operator
  ci-operator/config/openshift/aws-efs-csi-driver-operator/openshift-aws-efs-csi-driver-operator-master.yaml
  ci-operator/config/openshift/aws-efs-csi-driver-operator/openshift-aws-efs-csi-driver-operator-release-4.17.yaml
  ci-operator/config/openshift/aws-efs-csi-driver-operator/openshift-aws-efs-csi-driver-operator-release-4.18.yaml
  ci-operator/config/openshift/csi-operator/openshift-csi-operator-master.yaml
  ci-operator/config/openshift/csi-operator/openshift-csi-operator-release-4.17.yaml
  ci-operator/config/openshift/csi-operator/openshift-csi-operator-release-4.18.yaml
  ci-operator/jobs/openshift/aws-efs-csi-driver-operator/openshift-aws-efs-csi-driver-operator-master-periodics.yaml
  ci-operator/jobs/openshift/aws-efs-csi-driver-operator/openshift-aws-efs-csi-driver-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/aws-efs-csi-driver-operator/openshift-aws-efs-csi-driver-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/aws-efs-csi-driver-operator/openshift-aws-efs-csi-driver-operator-release-4.17-postsubmits.yaml
  ci-operator/jobs/openshift/aws-efs-csi-driver-operator/openshift-aws-efs-csi-driver-operator-release-4.17-presubmits.yaml
  ci-operator/jobs/openshift/aws-efs-csi-driver-operator/openshift-aws-efs-csi-driver-operator-release-4.18-postsubmits.yaml
  ci-operator/jobs/openshift/aws-efs-csi-driver-operator/openshift-aws-efs-csi-driver-operator-release-4.18-presubmits.yaml
  ci-operator/jobs/openshift/csi-operator/openshift-csi-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/csi-operator/openshift-csi-operator-release-4.17-presubmits.yaml
  ci-operator/jobs/openshift/csi-operator/openshift-csi-operator-release-4.18-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#53690 Add architecture for compact upgrade jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly-4.16-upgrade-from-stable-4.15.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly-4.16-upgrade-from-stable-4.16.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-nightly-4.17-upgrade-from-stable-4.16.yaml
Labels: lgtm, approved, rehearsals-ack

#53912 Bumping the OAuth images up to 4.16
  clusters/app.ci/release-controller/deploy-ocp-arm64-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-multi-2-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-multi-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-ppc64le-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-s390x-priv-controller.yaml
  hack/generators/release-controllers/content/osd_files_cache_resources.py
  hack/generators/release-controllers/content/osd_rc_deployments.py
Labels: lgtm, approved, rehearsals-ack

#53967 Fix sriov prow jobs
  ci-operator/config/openshift/ib-sriov-cni/openshift-ib-sriov-cni-master.yaml
  ci-operator/config/openshift/ib-sriov-cni/openshift-ib-sriov-cni-release-4.17.yaml
  ci-operator/config/openshift/ib-sriov-cni/openshift-ib-sriov-cni-release-4.18.yaml
  ci-operator/config/openshift/sriov-cni/openshift-sriov-cni-master.yaml
  ci-operator/config/openshift/sriov-cni/openshift-sriov-cni-release-4.12.yaml
  ci-operator/config/openshift/sriov-cni/openshift-sriov-cni-release-4.13.yaml
  ci-operator/config/openshift/sriov-cni/openshift-sriov-cni-release-4.14.yaml
  ci-operator/config/openshift/sriov-cni/openshift-sriov-cni-release-4.15.yaml
  ci-operator/config/openshift/sriov-cni/openshift-sriov-cni-release-4.16.yaml
  ci-operator/config/openshift/sriov-cni/openshift-sriov-cni-release-4.17.yaml
  ci-operator/config/openshift/sriov-cni/openshift-sriov-cni-release-4.18.yaml
  ci-operator/config/openshift/sriov-dp-admission-controller/openshift-sriov-dp-admission-controller-master.yaml
  ci-operator/config/openshift/sriov-dp-admission-controller/openshift-sriov-dp-admission-controller-release-4.17.yaml
  ci-operator/config/openshift/sriov-dp-admission-controller/openshift-sriov-dp-admission-controller-release-4.18.yaml
  ci-operator/config/openshift/sriov-network-device-plugin/openshift-sriov-network-device-plugin-release-4.17.yaml
  ci-operator/config/openshift/sriov-network-device-plugin/openshift-sriov-network-device-plugin-release-4.18.yaml
  ci-operator/config/openshift/sriov-network-metrics-exporter/openshift-sriov-network-metrics-exporter-release-4.17.yaml
  ci-operator/config/openshift/sriov-network-metrics-exporter/openshift-sriov-network-metrics-exporter-release-4.18.yaml
  ci-operator/config/openshift/sriov-network-operator/openshift-sriov-network-operator-master.yaml
  ci-operator/config/openshift/sriov-network-operator/openshift-sriov-network-operator-release-4.16.yaml
  ci-operator/config/openshift/sriov-network-operator/openshift-sriov-network-operator-release-4.17.yaml
  ci-operator/config/openshift/sriov-network-operator/openshift-sriov-network-operator-release-4.18.yaml
Labels: lgtm, approved, rehearsals-ack

#53899 Add environmental variables for 4.16 install analysis job
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.16.yaml
  ci-operator/jobs/openshift/multiarch/openshift-multiarch-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#53973 [release-1.33] Initialize Serverless Operator CI config
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.33__412.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.33__415.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#53919 Failover build04 to build01
  core-services/prow/02_config/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#53801 Update golangci-lint in o/ci-tools
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
Labels: lgtm, approved, rehearsals-ack

#53971 sriov: Update `cherry-pick-approved` allowed_users
  core-services/prow/02_config/openshift/sriov-cni/_pluginconfig.yaml
  core-services/prow/02_config/openshift/sriov-dp-admission-controller/_pluginconfig.yaml
  core-services/prow/02_config/openshift/sriov-network-device-plugin/_pluginconfig.yaml
  core-services/prow/02_config/openshift/sriov-network-operator/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#53969 OCPQE-23426: Make aks node vm size adjustable
  ci-operator/step-registry/aks/provision/aks-provision-commands.sh
  ci-operator/step-registry/aks/provision/aks-provision-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#53938 OCPBUGS-36457 Fixing obsolete pool removal
  ci-operator/step-registry/upi/libvirt/cleanup/post/upi-libvirt-cleanup-post-commands.sh
Labels: lgtm, approved, rehearsals-ack

#53906 Updating the reference to root image for openshift-ansible unit.
  ci-operator/config/openshift/openshift-ansible/openshift-openshift-ansible-master.yaml
Labels: lgtm, approved, rehearsals-ack

#53957 Add etcd chaos test suite for OCP 4.17
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__4.17-nightly-component-readiness.yaml
  ci-operator/jobs/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main-periodics.yaml
  ci-operator/jobs/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main-presubmits.yaml
  ci-operator/step-registry/redhat-chaos/krkn-hub-etcd-tests/OWNERS
  ci-operator/step-registry/redhat-chaos/krkn-hub-etcd-tests/redhat-chaos-krkn-hub-etcd-tests-chain.metadata.json
  ci-operator/step-registry/redhat-chaos/krkn-hub-etcd-tests/redhat-chaos-krkn-hub-etcd-tests-chain.yaml
  ci-operator/step-registry/redhat-chaos/krkn-hub-etcd-tests/redhat-chaos-krkn-hub-etcd-tests-workflow.metadata.json
  ci-operator/step-registry/redhat-chaos/krkn-hub-etcd-tests/redhat-chaos-krkn-hub-etcd-tests-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#53988 opendatahub/vllm: always run smoke test
  ci-operator/jobs/opendatahub-io/vllm/opendatahub-io-vllm-main-presubmits.yaml
  ci-operator/jobs/opendatahub-io/vllm/opendatahub-io-vllm-release-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#53990 Adjust cucushift-hypershift-extended-health-check
  ci-operator/step-registry/cucushift/hypershift-extended/health-check/cucushift-hypershift-extended-health-check-commands.sh
Labels: lgtm, approved, rehearsals-ack

#53820 Fix KubeVirt BM CI jobs failure
  ci-operator/step-registry/hypershift/kubevirt/baremetalds/conformance/hypershift-kubevirt-baremetalds-conformance-workflow.yaml
  ci-operator/step-registry/hypershift/kubevirt/baremetalds/disconnected/conformance/hypershift-kubevirt-baremetalds-disconnected-conformance-workflow.yaml
  ci-operator/step-registry/hypershift/mce/kubevirt/baremetalds/conformance/hypershift-mce-kubevirt-baremetalds-conformance-workflow.yaml
  ci-operator/step-registry/hypershift/mce/kubevirt/baremetalds/disconnected/conformance/hypershift-mce-kubevirt-baremetalds-disconnected-conformance-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#53984 hypershift: unpin mgmt cluster version
  ci-operator/step-registry/hypershift/setup-nested-management-cluster/hypershift-setup-nested-management-cluster-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#53983 correcting ols 4.15 cluster-pool name
  clusters/hosted-mgmt/hive/pools/openshift-observability/ols-ocp-4-15-0-amd64-aws-us-east-1_clusterpool.yaml
Labels: lgtm, approved, rehearsals-ack

#53538 [ART-9752] add node scan to art fips-scan
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.12.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.13.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.14.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.15.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.16.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.17.yaml
Labels: lgtm, approved, rehearsals-ack

#53965 USHIFT-3518: Use dynamic aws region selection based on availability
  ci-operator/step-registry/openshift/microshift/clusterbot/openshift-microshift-clusterbot-workflow.yaml
  ci-operator/step-registry/openshift/microshift/e2e/metal-cache/openshift-microshift-e2e-metal-cache-workflow.yaml
  ci-operator/step-registry/openshift/microshift/e2e/metal-tests/openshift-microshift-e2e-metal-tests-workflow.yaml
  ci-operator/step-registry/openshift/microshift/infra/aws/deprovision/OWNERS
  ci-operator/step-registry/openshift/microshift/infra/aws/deprovision/openshift-microshift-infra-aws-deprovision-commands.sh
  ci-operator/step-registry/openshift/microshift/infra/aws/deprovision/openshift-microshift-infra-aws-deprovision-ref.metadata.json
  ci-operator/step-registry/openshift/microshift/infra/aws/deprovision/openshift-microshift-infra-aws-deprovision-ref.yaml
  ci-operator/step-registry/openshift/microshift/infra/aws/ec2/openshift-microshift-infra-aws-ec2-commands.sh
  ci-operator/step-registry/openshift/microshift/infra/aws/ec2/openshift-microshift-infra-aws-ec2-ref.yaml
  ci-operator/step-registry/openshift/microshift/infra/aws/post/openshift-microshift-infra-aws-post-chain.yaml
  ci-operator/step-registry/openshift/microshift/infra/iso-build/openshift-microshift-infra-iso-build-commands.sh
  ci-operator/step-registry/openshift/microshift/infra/iso-build/openshift-microshift-infra-iso-build-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#53950 updating operator sdk version in preflight presubmits
  ci-operator/config/redhat-openshift-ecosystem/openshift-preflight/redhat-openshift-ecosystem-openshift-preflight-main__4.12.yaml
  ci-operator/config/redhat-openshift-ecosystem/openshift-preflight/redhat-openshift-ecosystem-openshift-preflight-main__4.16.yaml
Labels: lgtm, approved, rehearsals-ack

#53941 e2e:hypershift: add KUBECONFIG env
  ci-operator/config/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-master.yaml
Labels: lgtm, approved, rehearsals-ack

#53992 Add reporter_config for OCP 4.17 jobs
  ci-operator/jobs/3scale-qe/3scale-deploy/3scale-qe-3scale-deploy-main-periodics.yaml
  ci-operator/jobs/amq-streams-qe/strimzi-kafka-operator/amq-streams-qe-strimzi-kafka-operator-main-periodics.yaml
  ci-operator/jobs/ansible/tower-qa/ansible-tower-qa-devel-periodics.yaml
  ci-operator/jobs/infinispan/infinispan-operator/infinispan-infinispan-operator-stable-periodics.yaml
  ci-operator/jobs/jboss-fuse/camel-k-test-container/jboss-fuse-camel-k-test-container-main-periodics.yaml
  ci-operator/jobs/jboss-fuse/camel-quarkus-openshift-interop/jboss-fuse-camel-quarkus-openshift-interop-main-periodics.yaml
  ci-operator/jobs/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-main-periodics.yaml
  ci-operator/jobs/redhat-developer/helm/redhat-developer-helm-release-3.11-periodics.yaml
  ci-operator/jobs/rh-messaging-qe/claire/rh-messaging-qe-claire-lpt-periodics.yaml
  ci-operator/jobs/sclorg/ansible-tests/sclorg-ansible-tests-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#54005 MULTIARCH-4696: change timing to add gap between jobs
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.14.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.15.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.16.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.17.yaml
  ci-operator/jobs/openshift/multiarch/openshift-multiarch-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#53968 add gcp support for arm64 upgrade jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__arm64-nightly-4.15-upgrade-from-stable-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__arm64-stable-4.15-upgrade-from-stable-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__arm64-nightly-4.16-upgrade-from-stable-4.15.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__arm64-stable-4.16-upgrade-from-stable-4.15.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#53785 CI implementation: Enable Agent Disconnected 2.5 e2e CI jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/baremetalds/assisted/hypershift-agent/mce/disconnected/cucushift-installer-rehearse-baremetalds-assisted-hypershift-agent-mce-disconnected-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/baremetalds/assisted/hypershift-agent/mce/disconnected/guest/cucushift-installer-rehearse-baremetalds-assisted-hypershift-agent-mce-disconnected-guest-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#53972 NO-JIRA: Fix REDHAT_OPERATOR_INDEX_REPO
  ci-operator/step-registry/cucushift/hypershift-extended/k8s-mgmt/get-guest-annotations/cucushift-hypershift-extended-k8s-mgmt-get-guest-annotations-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#53888 OCPQE-23341: Add fips to indicate fips testing
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#53921 chore(KONFLUX-2504): remove references to SPI service env vars
  ci-operator/step-registry/redhat-appstudio/e2e/redhat-appstudio-e2e-commands.sh
Labels: lgtm, approved, rehearsals-ack

#53980 Interop - Add eclipse/che-e2e image mirroring
  core-services/image-mirroring/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#54019 Adjust equinix-ocp-hcp-quota
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: lgtm, approved, rehearsals-ack

#54020 chore: remove remote-secret and spi jobs
  ci-operator/config/konflux-ci/remote-secret/OWNERS
  ci-operator/config/konflux-ci/remote-secret/konflux-ci-remote-secret-main.yaml
  ci-operator/config/konflux-ci/service-provider-integration-operator/OWNERS
  ci-operator/config/konflux-ci/service-provider-integration-operator/konflux-ci-service-provider-integration-operator-main.yaml
  ci-operator/jobs/konflux-ci/remote-secret/konflux-ci-remote-secret-main-presubmits.yaml
  ci-operator/jobs/konflux-ci/service-provider-integration-operator/konflux-ci-service-provider-integration-operator-main-presubmits.yaml
  ci-operator/step-registry/redhat-appstudio/e2e/redhat-appstudio-e2e-ref.yaml
  ci-operator/step-registry/redhat-appstudio/install-konflux/redhat-appstudio-install-konflux-ref.yaml
  core-services/prow/02_config/konflux-ci/remote-secret/OWNERS
  core-services/prow/02_config/konflux-ci/remote-secret/_pluginconfig.yaml
  core-services/prow/02_config/konflux-ci/remote-secret/_prowconfig.yaml
  core-services/prow/02_config/konflux-ci/service-provider-integration-operator/OWNERS
  core-services/prow/02_config/konflux-ci/service-provider-integration-operator/_pluginconfig.yaml
  core-services/prow/02_config/konflux-ci/service-provider-integration-operator/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#53838 OCPBUGS-36363: Install yq manually if not found in installer image
  ci-operator/step-registry/ipi/install/powervs/install/ipi-install-powervs-install-commands.sh
Labels: lgtm, approved, jira/valid-bug, rehearsals-ack, jira/valid-reference

#54027 psi: transition to mp+
  clusters/psi/Makefile
  clusters/psi/README.md
  clusters/psi/sync-rover-groups-update_cronjob.yaml
Labels: lgtm, approved, rehearsals-ack

#54023 NO-ISSUE: fix(assisted-installer-agent): Prepare replacing ci test images
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master__edge.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.10.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.11.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.8.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.9.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.8-periodics.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.8-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.8-presubmits.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.9-periodics.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.9-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.9-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#53924 Bump dev-scripts serial job timouts to 5h
  ci-operator/config/openshift-metal3/dev-scripts/openshift-metal3-dev-scripts-master.yaml
  ci-operator/jobs/openshift-metal3/dev-scripts/openshift-metal3-dev-scripts-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#53985 NO-ISSUE: Prepare configuration for replacing ci golang images in test builds for assisted-image-service
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-main__edge.yaml
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.10.yaml
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.11.yaml
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.8.yaml
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.9.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.8-periodics.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.8-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.8-presubmits.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.9-periodics.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.9-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-release-ocm-2.9-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#54026 OCPQE-23445: Prevent port masking
  ci-operator/step-registry/baremetal/lab/ipi/deprovision/baremetal-lab-ipi-deprovision-commands.sh
  ci-operator/step-registry/baremetal/lab/ipi/install/baremetal-lab-ipi-install-commands.sh
  ci-operator/step-registry/baremetal/lab/post/provisioning-network/baremetal-lab-post-provisioning-network-commands.sh
  ci-operator/step-registry/baremetal/lab/pre/provisioning-network/baremetal-lab-pre-provisioning-network-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#54030 e2e-aws use cloud-event-consumer image from pipeline
  ci-operator/config/redhat-cne/cloud-event-proxy/redhat-cne-cloud-event-proxy-main.yaml
Labels: lgtm, approved, rehearsals-ack

#54031 update go version in ptp ci
  ci-operator/step-registry/telco5g/ptp/tests/telco5g-ptp-tests-commands.sh
Labels: lgtm, approved, rehearsals-ack

#53927 OCPQE-23286 increase wait time before upgrade
  ci-operator/step-registry/cucushift/chainupgrade/toimage/cucushift-chainupgrade-toimage-commands.sh
  ci-operator/step-registry/cucushift/upgrade/check-not-recommended/cucushift-upgrade-check-not-recommended-commands.sh
Labels: lgtm, approved, rehearsals-ack

#53312 install gitops-prerelease rhtap
  ci-operator/config/redhat-appstudio/rhtap-installer/redhat-appstudio-rhtap-installer-release-1.0.yaml
  ci-operator/jobs/redhat-appstudio/rhtap-installer/redhat-appstudio-rhtap-installer-release-1.0-periodics.yaml
  ci-operator/jobs/redhat-appstudio/rhtap-installer/redhat-appstudio-rhtap-installer-release-1.0-presubmits.yaml
  ci-operator/step-registry/redhat-appstudio/rhtap-installer/gitops-prerelease/OWNERS
  ci-operator/step-registry/redhat-appstudio/rhtap-installer/gitops-prerelease/redhat-appstudio-rhtap-installer-gitops-prerelease-commands.sh
  ci-operator/step-registry/redhat-appstudio/rhtap-installer/gitops-prerelease/redhat-appstudio-rhtap-installer-gitops-prerelease-ref.metadata.json
  ci-operator/step-registry/redhat-appstudio/rhtap-installer/gitops-prerelease/redhat-appstudio-rhtap-installer-gitops-prerelease-ref.yaml
  ci-operator/step-registry/redhat-appstudio/rhtap-installer/gitops-prerelease/redhat-appstudio-rhtap-installer-gitops-prerelease-workflow.metadata.json
  ci-operator/step-registry/redhat-appstudio/rhtap-installer/gitops-prerelease/redhat-appstudio-rhtap-installer-gitops-prerelease-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#53970 openshift-lightspeed: image substituion for bundle built on Konflux
  ci-operator/config/openshift/lightspeed-operator/openshift-lightspeed-operator-main.yaml
Labels: lgtm, approved, rehearsals-ack

#54016 CI implementation: Enable Agent Disconnected 2.6 e2e CI jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#53777 add stress test job
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17-periodics.yaml
  ci-operator/step-registry/openshift-extended/test/stresstest/openshift-extended-test-stresstest-commands.sh
Labels: lgtm, approved, rehearsals-ack

#54038 [CIGolang]make optional image for setting up disc catsrc
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__images.yaml
Labels: lgtm, approved, rehearsals-ack

#53904 OCPBUGS-36399: Avoid ESI for -serial jobs
  ci-operator/step-registry/ofcir/acquire/ofcir-acquire-commands.sh
Labels: lgtm, approved, jira/valid-bug, rehearsals-ack, jira/valid-reference

#54017 CI implementation: change cluster_profile to equinix-ocp-hcp
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.14__periodics.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.15__periodics.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.16__periodics.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.14-periodics.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.15-periodics.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.16-periodics.yaml
  ci-operator/step-registry/hypershift/mce/agent/create/hostedcluster/hypershift-mce-agent-create-hostedcluster-commands.sh
  ci-operator/step-registry/hypershift/mce/agent/manual/conformance/hypershift-mce-agent-manual-conformance-workflow.yaml
  ci-operator/step-registry/hypershift/mce/agent/metal3/conformance/hypershift-mce-agent-metal3-conformance-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#54043 [CIGolang]disable to build optional image
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__images.yaml
Labels: lgtm, approved, rehearsals-ack

#54047 Add SNR release-0.9 branch to CI and minor script updates
  ci-operator/config/medik8s/common/new-ocp-version.sh
  ci-operator/config/medik8s/common/new-release.sh
  ci-operator/config/medik8s/self-node-remediation/medik8s-self-node-remediation-release-0.9__4.12.yaml
  ci-operator/config/medik8s/self-node-remediation/medik8s-self-node-remediation-release-0.9__4.13.yaml
  ci-operator/config/medik8s/self-node-remediation/medik8s-self-node-remediation-release-0.9__4.14.yaml
  ci-operator/config/medik8s/self-node-remediation/medik8s-self-node-remediation-release-0.9__4.15.yaml
  ci-operator/config/medik8s/self-node-remediation/medik8s-self-node-remediation-release-0.9__4.16.yaml
  ci-operator/config/medik8s/self-node-remediation/medik8s-self-node-remediation-release-0.9__4.17.yaml
  ci-operator/jobs/medik8s/self-node-remediation/medik8s-self-node-remediation-release-0.9-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#54003 Revert "Failover build04 to build01"
  core-services/prow/02_config/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#54007 removing oc echo from preflight presubmit, preflight no uses oc
  ci-operator/config/redhat-openshift-ecosystem/openshift-preflight/redhat-openshift-ecosystem-openshift-preflight-main__4.12.yaml
  ci-operator/config/redhat-openshift-ecosystem/openshift-preflight/redhat-openshift-ecosystem-openshift-preflight-main__4.16.yaml
Labels: lgtm, approved, rehearsals-ack

#54049 openshift-loki: Add ci config for branch upstream-v3.1.0
  ci-operator/config/openshift/loki/openshift-loki-upstream-v3.1.0.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-upstream-v3.1.0-postsubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-upstream-v3.1.0-presubmits.yaml
  core-services/image-mirroring/openshift-logging/mapping_logging_loki_quay
Labels: lgtm, approved, rehearsals-ack

#53934 [csi-external-attacher] rename Dockerfile
  ci-operator/config/openshift/csi-external-attacher/openshift-csi-external-attacher-master.yaml
Labels: lgtm, approved, rehearsals-ack

#54066 Add option to skip health checks in trigger job
  ci-operator/config/rhpit/interop-tests/rhpit-interop-tests-main__weekly_trigger.yaml
  ci-operator/step-registry/trigger-jobs/trigger-jobs-commands.sh
  ci-operator/step-registry/trigger-jobs/trigger-jobs-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#53627 TRT-1573: a29y special handling for ocp-build-data
  Makefile
  hack/acknowledge_critical_fix_repos_single_repo.py
  hack/generate-acknowledge-critical-fixes-repo-list.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#53755 add periodic-ci-insights-qe-iqe-cost-management-plugin-master-ocp4.17-lp-interop-cost-management-interop-aws
  ci-operator/config/insights-qe/iqe-cost-management-plugin/insights-qe-iqe-cost-management-plugin-master__ocp4.17-lp-interop.yaml
  ci-operator/jobs/insights-qe/iqe-cost-management-plugin/insights-qe-iqe-cost-management-plugin-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#53902 OCPQE-23340: Update Hypershift AKS jobs to align with the latest docs
  ci-operator/step-registry/aks/deprovision/aks-deprovision-commands.sh
  ci-operator/step-registry/aks/provision/aks-provision-commands.sh
  ci-operator/step-registry/aks/provision/aks-provision-ref.yaml
  ci-operator/step-registry/azure/deprovision/resourcegroup/azure-deprovision-resourcegroup-commands.sh
  ci-operator/step-registry/azure/deprovision/resourcegroup/azure-deprovision-resourcegroup-ref.yaml
  ci-operator/step-registry/azure/provision/vnet-hypershift/OWNERS
  ci-operator/step-registry/azure/provision/vnet-hypershift/azure-provision-vnet-hypershift-commands.sh
  ci-operator/step-registry/azure/provision/vnet-hypershift/azure-provision-vnet-hypershift-ref.metadata.json
  ci-operator/step-registry/azure/provision/vnet-hypershift/azure-provision-vnet-hypershift-ref.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/aks/hypershift/deprovision/cucushift-installer-rehearse-azure-aks-hypershift-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/aks/hypershift/provision/cucushift-installer-rehearse-azure-aks-hypershift-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/aks/provision/cucushift-installer-rehearse-azure-aks-provision-chain.yaml
  ci-operator/step-registry/hypershift/azure/create/hypershift-azure-create-chain.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#53753 add periodic-ci-jboss-fuse-csb-tnb-tests-container-main-csb-ocp4.17-lp-interop-csb-interop-aws-latest
  ci-operator/config/jboss-fuse/csb-tnb-tests-container/jboss-fuse-csb-tnb-tests-container-main__csb-ocp4.17-lp-interop.yaml
  ci-operator/jobs/jboss-fuse/csb-tnb-tests-container/jboss-fuse-csb-tnb-tests-container-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#54051 telco5g: Less verbose logging
  ci-operator/step-registry/telco5g/hcp-cluster-setup/telco5g-hcp-cluster-setup-commands.sh
Labels: lgtm, approved, rehearsals-ack

#53936 [csi-livenessprobe] rename Dockerfile
  ci-operator/config/openshift/csi-livenessprobe/openshift-csi-livenessprobe-master.yaml
Labels: lgtm, approved, rehearsals-ack

#54000 [cluster-csi-snapshot-controller-operator] Rename dockerfile
  ci-operator/config/openshift/cluster-csi-snapshot-controller-operator/openshift-cluster-csi-snapshot-controller-operator-master.yaml
Labels: lgtm, approved, rehearsals-ack

#54083 Hive: Fix periodic image jobs
  ci-operator/config/openshift/hive/openshift-hive-master__periodic.yaml
Labels: lgtm, approved, rehearsals-ack

#54072 [cluster-kube-scheduler-operator] Rename dockerfile
  ci-operator/config/openshift/cluster-kube-scheduler-operator/openshift-cluster-kube-scheduler-operator-master.yaml
Labels: lgtm, approved, rehearsals-ack

#53915 upgrade status should only log yet unseen errors during upgrade
  ci-operator/step-registry/cucushift/chainupgrade/toimage/cucushift-chainupgrade-toimage-commands.sh
  ci-operator/step-registry/cucushift/upgrade/toimage/cucushift-upgrade-toimage-commands.sh
Labels: lgtm, approved, rehearsals-ack

#53796 Prow configuration for pf-status-relay
  ci-operator/config/openshift/pf-status-relay/OWNERS
  ci-operator/config/openshift/pf-status-relay/openshift-pf-status-relay-main.yaml
  ci-operator/jobs/openshift/pf-status-relay/OWNERS
  ci-operator/jobs/openshift/pf-status-relay/openshift-pf-status-relay-main-presubmits.yaml
  core-services/prow/02_config/openshift/pf-status-relay/_pluginconfig.yaml
  core-services/prow/02_config/openshift/pf-status-relay/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#54089 NO-ISSUE: Use generic image stream for ocm/mce 2.8/2.9
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.8__mce.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.9__mce.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#54088 Test NVIDIA GPU operator 23.9 and 24.3 on OCP 4.16
  ci-operator/config/rh-ecosystem-edge/nvidia-ci/rh-ecosystem-edge-nvidia-ci-main__4.16.yaml
  ci-operator/jobs/rh-ecosystem-edge/nvidia-ci/rh-ecosystem-edge-nvidia-ci-main-periodics.yaml
  ci-operator/jobs/rh-ecosystem-edge/nvidia-ci/rh-ecosystem-edge-nvidia-ci-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#54087 CNF-13537: Add Snyk security scanning
  ci-operator/config/openshift/kube-compare/openshift-kube-compare-main.yaml
  ci-operator/jobs/openshift/kube-compare/openshift-kube-compare-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#54045 OCPQE-23434 Remove unsupported arm jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__arm64-nightly-4.17-upgrade-from-stable-4.16.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#53752 add periodic-ci-stackrox-stackrox-master-ocp-4-17-lp-interop-acs-tests-aws
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-17-lp-interop.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies__ocp-4-17.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-periodics.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-nightlies-postsubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#53750 add periodic-ci-stolostron-acmqe-autotest-main-acm-ocp4.17-lp-interop-acm-interop-aws
  ci-operator/config/stolostron/acmqe-autotest/stolostron-acmqe-autotest-main__acm-ocp4.17-lp-interop.yaml
  ci-operator/jobs/stolostron/acmqe-autotest/stolostron-acmqe-autotest-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack
