Repository openshift/release, pull requests merged in 2024-08, with the labels that each got.

#55037 Backport HCP KubeVirt reduced e2e job
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.14.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.15.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.16.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.14-presubmits.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.15-presubmits.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.16-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#55039 OCPQE-24353: Update workflow-launch images for hypershift aws jobs
  core-services/ci-chat-bot/workflows-config.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#55061 fips support for helm
  ci-operator/config/redhat-developer/helm/.config.prowgen
  ci-operator/config/redhat-developer/helm/redhat-developer-helm-release-3.11__helm-ocp4.17-lp-interop.yaml
  ci-operator/jobs/redhat-developer/helm/redhat-developer-helm-release-3.11-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#55064 [CIGolang]change UI image to rhel9
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__images.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__images.yaml
Labels: lgtm, approved, rehearsals-ack

#55069 [CIGolang]disable ui base optional
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__images.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__images.yaml
Labels: lgtm, approved, rehearsals-ack

#54975 Add Quay 3.12 testing on all supported OCP versions
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__ocp-412-quay.yaml
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__ocp-413-quay.yaml
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__ocp-414-quay.yaml
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__ocp-415-quay-nightly.yaml
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__ocp-415-quay.yaml
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__ocp-416-quay.yaml
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__ocp-417-quay.yaml
  ci-operator/jobs/quay/quay-tests/quay-quay-tests-master-periodics.yaml
Labels: lgtm, approved, tide/merge-method-squash, rehearsals-ack

#55074 NO-JIRA: Restore my OWNERS permissions which were inadvertently removed
  ci-operator/step-registry/idp/OWNERS
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#54762 [MGMT-10097] - Revert "MGMT-15398: Pull multi-arch images from brew in AI arm job (#…
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-main__edge.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#55071 Remove old aws-rosa-shared-vpc-auto-e2e-f7 job
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-master__rosacli.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#55031 telco5g: Install 4.17 HCP guest cluster on baremetal
  ci-operator/step-registry/telco5g/hcp-cluster-setup/telco5g-hcp-cluster-setup-commands.sh
Labels: lgtm, approved, rehearsals-ack

#55062 [INTEROP-7456][INTEROP-7458] Update GitOps config to run FIPS; add `slack_reporter` to config.
  ci-operator/config/redhat-developer/gitops-operator/.config.prowgen
  ci-operator/config/redhat-developer/gitops-operator/redhat-developer-gitops-operator-v1.13__gitops-ocp4.17-lp-interop.yaml
  ci-operator/jobs/redhat-developer/gitops-operator/redhat-developer-gitops-operator-v1.13-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#55072 CNF-13836: Upgrade kube-compare Go
  ci-operator/config/openshift/kube-compare/openshift-kube-compare-main.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#54980 MCO Add MCO dedicated Vsphere agent SNO job
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17-periodics.yaml
  ci-operator/step-registry/mco/conf/day2/add-mcoqe-robot-to-pull-secret/mco-conf-day2-add-mcoqe-robot-to-pull-secret-commands.sh
Labels: lgtm, approved, rehearsals-ack

#54799 Update 4.12 Power libvirt jobs to run once in two weeks
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.12-upgrade-from-nightly-4.11.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.12.yaml
  ci-operator/jobs/openshift/multiarch/openshift-multiarch-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#55054 Update scenario to support FIPS with OCP 4.17
  ci-operator/config/jboss-fuse/camel-quarkus-openshift-interop/jboss-fuse-camel-quarkus-openshift-interop-main__camel-quarkus-ocp4.17-lp-interop.yaml
  ci-operator/jobs/jboss-fuse/camel-quarkus-openshift-interop/jboss-fuse-camel-quarkus-openshift-interop-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#55089 Move dev-scripts jobs to OVN
  ci-operator/config/openshift-metal3/dev-scripts/openshift-metal3-dev-scripts-master.yaml
Labels: lgtm, approved, rehearsals-ack

#53119 OCPQE-19900: Hypershift OpenLDAP IDP Integration
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17-periodics.yaml
  ci-operator/step-registry/idp/htpasswd/idp-htpasswd-commands.sh
  ci-operator/step-registry/idp/openldap/idp-openldap-commands.sh
  ci-operator/step-registry/idp/openldap/idp-openldap-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#54622 Add OCP/CNV/ODF 4.17 Interop Job
  ci-operator/config/RedHatQE/interop-testing/RedHatQE-interop-testing-cnv-4.17__ocp-cnv-odf-4.17.yaml
  ci-operator/jobs/RedHatQE/interop-testing/RedHatQE-interop-testing-cnv-4.17-periodics.yaml
  ci-operator/jobs/RedHatQE/interop-testing/RedHatQE-interop-testing-cnv-4.17-presubmits.yaml
  ci-operator/step-registry/interop-tests/cnv-tests-e2e-deploy/interop-tests-cnv-tests-e2e-deploy-commands.sh
  ci-operator/step-registry/interop-tests/deploy-odf/interop-tests-deploy-odf-commands.sh
  ci-operator/step-registry/interop-tests/openshift-virtualization-tests/interop-tests-openshift-virtualization-tests-commands.sh
Labels: lgtm, approved, rehearsals-ack

#55053 chore: migrate janus-idp/operator to...
  core-services/prow/02_config/janus-idp/operator/_pluginconfig.yaml
  core-services/prow/02_config/redhat-developer/rhdh-operator/OWNERS
  core-services/prow/02_config/redhat-developer/rhdh-operator/_pluginconfig.yaml
  core-services/prow/02_config/redhat-developer/rhdh-operator/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#55088 Update HyperShift to weekly run
  ci-operator/step-registry/trigger-jobs/trigger-jobs-commands.sh
Labels: lgtm, approved, rehearsals-ack

#38168 OPNET-219: Add dev-scripts ci job for v6-primary dual stack
  ci-operator/config/openshift-metal3/dev-scripts/openshift-metal3-dev-scripts-master.yaml
  ci-operator/jobs/openshift-metal3/dev-scripts/openshift-metal3-dev-scripts-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#55102 fips-scan set blocking for 4.12-4.16 and 4.18
  core-services/release-controller/_releases/priv/release-ocp-4.12.json
  core-services/release-controller/_releases/priv/release-ocp-4.13.json
  core-services/release-controller/_releases/priv/release-ocp-4.14.json
  core-services/release-controller/_releases/priv/release-ocp-4.15.json
  core-services/release-controller/_releases/priv/release-ocp-4.16.json
  core-services/release-controller/_releases/priv/release-ocp-4.18.json
  core-services/release-controller/_releases/release-ocp-4.12.json
  core-services/release-controller/_releases/release-ocp-4.13.json
  core-services/release-controller/_releases/release-ocp-4.14.json
  core-services/release-controller/_releases/release-ocp-4.15.json
  core-services/release-controller/_releases/release-ocp-4.16.json
  core-services/release-controller/_releases/release-ocp-4.18.json
Labels: lgtm, approved, rehearsals-ack

#55100 Expand Fuse CSB to support FIPS
  ci-operator/config/jboss-fuse/csb-tnb-tests-container/jboss-fuse-csb-tnb-tests-container-main__csb-ocp4.17-lp-interop.yaml
  ci-operator/jobs/jboss-fuse/csb-tnb-tests-container/jboss-fuse-csb-tnb-tests-container-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#55044 Fix bug for jq piping
  ci-operator/step-registry/dpu-operator/e2e-tests-workflow/tests/dpu-operator-e2e-tests-workflow-tests-commands.sh
Labels: lgtm, approved, rehearsals-ack

#55112 release-controllers: fix rc-priv tls
  clusters/app.ci/release-controller/deploy-ocp-arm64-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-multi-2-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-multi-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-ppc64le-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-s390x-priv-controller.yaml
  hack/generators/release-controllers/content/utils.py
Labels: lgtm, approved, rehearsals-ack

#55096 Expand Camel K to support FIPS with OCP 4.17
  ci-operator/config/jboss-fuse/camel-k-test-container/jboss-fuse-camel-k-test-container-main__camel-k-ocp4.17-lp-interop.yaml
  ci-operator/jobs/jboss-fuse/camel-k-test-container/jboss-fuse-camel-k-test-container-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#55093 NO-JIRA: feat: add optional sno techpreview presubmits
  ci-operator/config/openshift/origin/openshift-origin-release-4.17.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.18.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.17-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.18-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#54801 add day2 scale on azure
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__azure-4.15-nightly-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__azure-4.16-nightly-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__azure-4.17-nightly-x86.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-periodics.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-presubmits.yaml
  ci-operator/step-registry/openshift-qe/network-perf/openshift-qe-network-perf-commands.sh
  ci-operator/step-registry/openshift-qe/network-perf/openshift-qe-network-perf-ref.yaml
  ci-operator/step-registry/openshift-qe/network-smoke/openshift-qe-network-smoke-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#55117 [CIGolang]update base to get latest golang 1.22
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__images.yaml
Labels: lgtm, approved, rehearsals-ack

#55120 [CIGolang]disable it
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__images.yaml
Labels: lgtm, approved, rehearsals-ack

#55079 Bump AMQ Streams operator to version 2.7.0-3
  ci-operator/config/amq-streams-qe/strimzi-kafka-operator/amq-streams-qe-strimzi-kafka-operator-main__amq-streams-ocp4.14-lp-interop.yaml
  ci-operator/config/amq-streams-qe/strimzi-kafka-operator/amq-streams-qe-strimzi-kafka-operator-main__amq-streams-ocp4.14-lp-rosa-classic.yaml
  ci-operator/config/amq-streams-qe/strimzi-kafka-operator/amq-streams-qe-strimzi-kafka-operator-main__amq-streams-ocp4.15-lp-interop.yaml
  ci-operator/config/amq-streams-qe/strimzi-kafka-operator/amq-streams-qe-strimzi-kafka-operator-main__amq-streams-ocp4.16-lp-interop.yaml
  ci-operator/config/amq-streams-qe/strimzi-kafka-operator/amq-streams-qe-strimzi-kafka-operator-main__amq-streams-ocp4.16-lp-rosa-classic.yaml
  ci-operator/config/amq-streams-qe/strimzi-kafka-operator/amq-streams-qe-strimzi-kafka-operator-main__amq-streams-ocp4.17-lp-interop.yaml
  ci-operator/step-registry/strimzi/run-tests/README.md
  ci-operator/step-registry/strimzi/run-tests/strimzi-run-tests-commands.sh
Labels: lgtm, approved, rehearsals-ack

#55078 [maistra] Remove elasticsearch operator from test jobs
  ci-operator/config/maistra/maistra-test-tool/maistra-maistra-test-tool-main__servicemesh-hypershift-4.14-lp-rosa-hypershift.yaml
  ci-operator/config/maistra/maistra-test-tool/maistra-maistra-test-tool-main__servicemesh-hypershift-4.15-lp-rosa-hypershift.yaml
  ci-operator/config/maistra/maistra-test-tool/maistra-maistra-test-tool-main__servicemesh-ocp4.13-lp-interop.yaml
  ci-operator/config/maistra/maistra-test-tool/maistra-maistra-test-tool-main__servicemesh-ocp4.14-lp-interop.yaml
  ci-operator/config/maistra/maistra-test-tool/maistra-maistra-test-tool-main__servicemesh-ocp4.14-lp-rosa-classic.yaml
  ci-operator/config/maistra/maistra-test-tool/maistra-maistra-test-tool-main__servicemesh-ocp4.15-lp-interop.yaml
  ci-operator/config/maistra/maistra-test-tool/maistra-maistra-test-tool-main__servicemesh-ocp4.16-lp-interop.yaml
  ci-operator/config/maistra/maistra-test-tool/maistra-maistra-test-tool-main__servicemesh-ocp4.16-lp-rosa-classic.yaml
  ci-operator/config/maistra/maistra-test-tool/maistra-maistra-test-tool-main__servicemesh-ocp4.17-lp-interop.yaml
Labels: lgtm, approved, rehearsals-ack

#55073 CFE-1099: update ansible-operator-plugins configuration
  ci-operator/config/openshift/ansible-operator-plugins/openshift-ansible-operator-plugins-main.yaml
  ci-operator/config/openshift/ansible-operator-plugins/openshift-ansible-operator-plugins-release-4.17.yaml
  ci-operator/config/openshift/ansible-operator-plugins/openshift-ansible-operator-plugins-release-4.18.yaml
  ci-operator/jobs/openshift/ansible-operator-plugins/openshift-ansible-operator-plugins-main-presubmits.yaml
  ci-operator/jobs/openshift/ansible-operator-plugins/openshift-ansible-operator-plugins-release-4.17-presubmits.yaml
  ci-operator/jobs/openshift/ansible-operator-plugins/openshift-ansible-operator-plugins-release-4.18-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#55076 Read IAM resource name from install-config directly in post-destroy check.
  ci-operator/step-registry/aws/deprovision/iam-profile/aws-deprovision-iam-profile-commands.sh
  ci-operator/step-registry/aws/deprovision/iam-role/aws-deprovision-iam-role-commands.sh
  ci-operator/step-registry/cucushift/installer/check/aws/byo-iam-role/cucushift-installer-check-aws-byo-iam-role-commands.sh
Labels: lgtm, approved, rehearsals-ack

#55129 chore(powermon): update the daemonset to use python3.10
  ci-operator/step-registry/openshift-power-monitoring/tests/power-monitoring-operator/openshift-power-monitoring-tests-power-monitoring-operator-commands.sh
Labels: lgtm, approved, rehearsals-ack

#54193 [Stackrox] Remove ppc64le ebpf jobs
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-periodics.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-presubmits.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#55134 Revert "Use n2-highmem-32"
  clusters/build-clusters/02_cluster/openshift-machine-api/build0-gstfj-w-b-infra_machineset.yaml
Labels: lgtm, approved, rehearsals-ack

#54994 Add MCE 2.7 publish in openshift hypershift
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.17__mce.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.17-postsubmits.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.17-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#53339 OCPQE-20701 cpms qe cases
  ci-operator/config/openshift/cluster-control-plane-machine-set-operator/openshift-cluster-control-plane-machine-set-operator-main.yaml
  ci-operator/config/openshift/cluster-control-plane-machine-set-operator/openshift-cluster-control-plane-machine-set-operator-release-4.15.yaml
  ci-operator/config/openshift/cluster-control-plane-machine-set-operator/openshift-cluster-control-plane-machine-set-operator-release-4.16.yaml
  ci-operator/jobs/openshift/cluster-control-plane-machine-set-operator/openshift-cluster-control-plane-machine-set-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/cluster-control-plane-machine-set-operator/openshift-cluster-control-plane-machine-set-operator-release-4.15-presubmits.yaml
  ci-operator/jobs/openshift/cluster-control-plane-machine-set-operator/openshift-cluster-control-plane-machine-set-operator-release-4.16-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#55106 fix: konflux-e2e: update regex
  ci-operator/config/konflux-ci/e2e-tests/konflux-ci-e2e-tests-main.yaml
  ci-operator/jobs/konflux-ci/e2e-tests/konflux-ci-e2e-tests-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#55070 OCPQE-24377: Move EXTRA_ARGS=--fips down to the -provision chain
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-nightly.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/aks/hypershift/byo-vnet/provision/cucushift-installer-rehearse-azure-aks-hypershift-byo-vnet-provision-chain.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#55110 MULTIARCH-4860 Multiarch CI missing upgrade jobs
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.17-upgrade-from-nightly-4.16.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.18-upgrade-from-nightly-4.17.yaml
  ci-operator/jobs/openshift/multiarch/openshift-multiarch-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#55140 Revert "Revert "Use n2-highmem-32""
  clusters/build-clusters/02_cluster/openshift-machine-api/build0-gstfj-w-b-infra_machineset.yaml
Labels: lgtm, approved, rehearsals-ack

#55000 OCPEDGE-1087: feat: adding baseline conformance test jobs to compare results against
  ci-operator/config/openshift-kni/lifecycle-agent/openshift-kni-lifecycle-agent-main__nightly-4.16.yaml
  ci-operator/jobs/openshift-kni/lifecycle-agent/openshift-kni-lifecycle-agent-main-periodics.yaml
  ci-operator/step-registry/openshift/image-based/upgrade/e2e/baseline/OWNERS
  ci-operator/step-registry/openshift/image-based/upgrade/e2e/baseline/openshift-image-based-upgrade-e2e-baseline-workflow.metadata.json
  ci-operator/step-registry/openshift/image-based/upgrade/e2e/baseline/openshift-image-based-upgrade-e2e-baseline-workflow.yaml
  ci-operator/step-registry/openshift/image-based/upgrade/e2e/conf/openshift-image-based-upgrade-e2e-conf-commands.sh
  ci-operator/step-registry/openshift/image-based/upgrade/e2e/conf/openshift-image-based-upgrade-e2e-conf-ref.yaml
  ci-operator/step-registry/openshift/image-based/upgrade/e2e/openshift-image-based-upgrade-e2e-commands.sh
  ci-operator/step-registry/openshift/image-based/upgrade/e2e/openshift-image-based-upgrade-e2e-ref.yaml
  ci-operator/step-registry/openshift/image-based/upgrade/seed/create/openshift-image-based-upgrade-seed-create-commands.sh
  ci-operator/step-registry/openshift/image-based/upgrade/seed/create/openshift-image-based-upgrade-seed-create-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#55144 openstack/fips: make it flexible
  ci-operator/step-registry/openstack/provision/floatingips/openstack-provision-floatingips-commands.sh
  ci-operator/step-registry/openstack/provision/floatingips/openstack-provision-floatingips-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#55131 OCPQE-24437: Support workflow-launching a hosted cluster on AWS using QE cluster profile
  ci-operator/jobs/openshift/release/openshift-release-infra-periodics.yaml
  core-services/ci-chat-bot/workflows-config.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#55141 Update Cost Management scenario to support FIPS
  ci-operator/config/insights-qe/iqe-cost-management-plugin/insights-qe-iqe-cost-management-plugin-master__ocp4.17-lp-interop.yaml
  ci-operator/jobs/insights-qe/iqe-cost-management-plugin/insights-qe-iqe-cost-management-plugin-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#55142 Update Data Grid scenario to support FIPS
  ci-operator/config/infinispan/infinispan-operator/infinispan-infinispan-operator-stable__data-grid-ocp4.17-lp-interop.yaml
  ci-operator/jobs/infinispan/infinispan-operator/infinispan-infinispan-operator-stable-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#55145 Only run multi-arch tuning on labeled namespaces
  clusters/build-clusters/build10/multiarch-manager-operator/admin_10-pod-placement-config.yaml
Labels: lgtm, approved, rehearsals-ack

#55104 openstack: dnsrecords are more flexible
  ci-operator/step-registry/openstack/deprovision/dnsrecords/openstack-deprovision-dnsrecords-commands.sh
  ci-operator/step-registry/openstack/deprovision/dnsrecords/openstack-deprovision-dnsrecords-ref.yaml
  ci-operator/step-registry/openstack/provision/dnsrecords/openstack-provision-dnsrecords-commands.sh
  ci-operator/step-registry/openstack/provision/dnsrecords/openstack-provision-dnsrecords-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#55153 openstack/dnsrecords: unset AWS_PROFILE if empty
  ci-operator/step-registry/openstack/deprovision/dnsrecords/openstack-deprovision-dnsrecords-commands.sh
  ci-operator/step-registry/openstack/provision/dnsrecords/openstack-provision-dnsrecords-commands.sh
Labels: lgtm, approved, rehearsals-ack

#55123 Fixed curl for stopping jobs by adding post
  ci-operator/step-registry/dpu-operator/e2e-tests-workflow/tests/dpu-operator-e2e-tests-workflow-tests-commands.sh
Labels: lgtm, approved, rehearsals-ack

#55115 OSASINFRA-3555: hypershift/openstack: handle Ingress
  ci-operator/step-registry/hypershift/openstack/e2e/execute/hypershift-openstack-e2e-execute-commands.sh
  ci-operator/step-registry/hypershift/openstack/e2e/hypershift-openstack-e2e-chain.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#55143 Update JBoss EAP scenarios to support FIPS
  ci-operator/config/jboss-eap-qe/openshift-eap-tests/jboss-eap-qe-openshift-eap-tests-pit-7.4.x__eap-ocp4.17-lp-interop.yaml
  ci-operator/jobs/jboss-eap-qe/openshift-eap-tests/jboss-eap-qe-openshift-eap-tests-pit-7.4.x-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#55149 Increase worker disks in e2e-metal-ipi-ovn-upgrade
  ci-operator/step-registry/baremetalds/devscripts/setup/baremetalds-devscripts-setup-commands.sh
Labels: lgtm, approved, rehearsals-ack

#55156 Fix curl commands that are using POST
  ci-operator/step-registry/dpu-operator/e2e-tests-workflow/tests/dpu-operator-e2e-tests-workflow-tests-commands.sh
Labels: lgtm, approved, rehearsals-ack

#55154 Use external network ID in Hypershift cmdline
  ci-operator/step-registry/hypershift/openstack/e2e/execute/hypershift-openstack-e2e-execute-commands.sh
  ci-operator/step-registry/openstack/conf/resourcenames/openstack-conf-resourcenames-commands.sh
Labels: lgtm, approved, rehearsals-ack

#55158 Increase replicas on build02 registry
  clusters/build-clusters/02_cluster/openshift-image-registry/cluster_config.yaml
Labels: lgtm, approved, rehearsals-ack

#54416 OCPQE-22908: test backup/restore in HostedCluster
  ci-operator/step-registry/hypershift/mce/agent/oadp/hypershift-mce-agent-oadp-commands.sh
  ci-operator/step-registry/hypershift/mce/agent/oadp/hypershift-mce-agent-oadp-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#55133 kni:nrop: build topics
  ci-operator/config/openshift-kni/numaresources-operator/openshift-kni-numaresources-operator-main.yaml
Labels: lgtm, approved, rehearsals-ack

#55113 add fips support for dotnet
  ci-operator/config/sclorg/ansible-tests/.config.prowgen
  ci-operator/config/sclorg/ansible-tests/sclorg-ansible-tests-master__dotnet-ocp4.17-lp-interop.yaml
  ci-operator/jobs/sclorg/ansible-tests/sclorg-ansible-tests-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#55090 add 4.17-lp-interop-quarkus-interop-aws-fips
  ci-operator/config/quarkus-qe/quarkus-openshift-interop/quarkus-qe-quarkus-openshift-interop-main__quarkus-ocp4.17-lp-interop.yaml
  ci-operator/jobs/quarkus-qe/quarkus-openshift-interop/quarkus-qe-quarkus-openshift-interop-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#55108 add ocp 4.17 odo-scenario-aws-fips
  ci-operator/config/redhat-developer/odo/redhat-developer-odo-main__odo-ocp4.17-lp-interop.yaml
  ci-operator/jobs/redhat-developer/odo/redhat-developer-odo-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#54538 Enable INSTALLER IPI tests in Prow
  ci-operator/step-registry/openshift-extended/test/openshift-extended-test-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#55091 Updaitng image for write
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__write_jobs_to_gsheet.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-periodics.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-postsubmits.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#55170 [azure] remove feature gates on 4.17 jobs with mixarch
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__multi-nightly.yaml
Labels: lgtm, approved, rehearsals-ack

#55097 SDCICD-1345 Onboard the rest of the Cicada team and remove osd-example-operator
  core-services/pr-reminder/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#55178 NO-ISSUE: build image-service image in CI with centos stream 9
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-main.yaml
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-main__mce.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#55081 OSASINFRA-3551: Reducing the openstack-nfv-quota-slice to 4
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#55164 Replace old NVIDIA GPU operator following release of 24.6
  ci-operator/config/rh-ecosystem-edge/nvidia-ci/.config.prowgen
  ci-operator/config/rh-ecosystem-edge/nvidia-ci/rh-ecosystem-edge-nvidia-ci-main__4.12.yaml
  ci-operator/config/rh-ecosystem-edge/nvidia-ci/rh-ecosystem-edge-nvidia-ci-main__4.13.yaml
  ci-operator/config/rh-ecosystem-edge/nvidia-ci/rh-ecosystem-edge-nvidia-ci-main__4.14.yaml
  ci-operator/config/rh-ecosystem-edge/nvidia-ci/rh-ecosystem-edge-nvidia-ci-main__4.15.yaml
  ci-operator/config/rh-ecosystem-edge/nvidia-ci/rh-ecosystem-edge-nvidia-ci-main__4.16.yaml
  ci-operator/jobs/rh-ecosystem-edge/nvidia-ci/rh-ecosystem-edge-nvidia-ci-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#55165 Abort with CNV deploy_test exit code
  ci-operator/step-registry/interop-tests/cnv-tests-e2e-deploy/interop-tests-cnv-tests-e2e-deploy-commands.sh
Labels: lgtm, approved, rehearsals-ack

#55176 fix(powermon): update the daemonset definition to switch python version
  ci-operator/step-registry/openshift-power-monitoring/tests/power-monitoring-operator/openshift-power-monitoring-tests-power-monitoring-operator-commands.sh
Labels: lgtm, approved, rehearsals-ack

#55126 Update Quay 3.12 OCI Conformance Testing
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__quay-oci-conformance.yaml
  ci-operator/step-registry/quay-tests/deploy-quay-aws-s3/quay-tests-deploy-quay-aws-s3-commands.sh
  ci-operator/step-registry/quay-tests/deploy-quay-aws-s3/quay-tests-deploy-quay-aws-s3-ref.yaml
  ci-operator/step-registry/quay-tests/quay-oci-conformance-test/quay-tests-quay-oci-conformance-test-commands.sh
Labels: lgtm, approved, tide/merge-method-squash, rehearsals-ack

#55182 openstack: Fetch the network ID in a separate step
  ci-operator/step-registry/ipi/conf/openstack/ipi-conf-openstack-chain.yaml
  ci-operator/step-registry/openstack/conf/externalnetworkid/OWNERS
  ci-operator/step-registry/openstack/conf/externalnetworkid/openstack-conf-externalnetworkid-commands.sh
  ci-operator/step-registry/openstack/conf/externalnetworkid/openstack-conf-externalnetworkid-ref.metadata.json
  ci-operator/step-registry/openstack/conf/externalnetworkid/openstack-conf-externalnetworkid-ref.yaml
  ci-operator/step-registry/openstack/conf/resourcenames/openstack-conf-resourcenames-commands.sh
Labels: lgtm, approved, rehearsals-ack

#54963 Update vsphere winc cluster profile
  ci-operator/step-registry/cucushift/installer/rehearse/vsphere/ipi/ovn/winc/cucushift-installer-rehearse-vsphere-ipi-ovn-winc-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#55174 Build Opamp bridge-server from OTEL CI jobs and enable e2e-openshift-serverless test suite in Tempo jobs.
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__upstream-ocp-4.13-amd64-aws-ipi-ovn-hypershift.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__upstream-ocp-4.14-amd64-gcp-ipi-ovn-ipsec.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__upstream-ocp-4.15-amd64-aws.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__upstream-ocp-4.16-amd64-aws-ipi-shared-vpc-phz-sts.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__upstream-upgrade-ocp-4.17-amd64-azure.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__upstream-ocp-4.13-amd64-aws-ipi-ovn-hypershift.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__upstream-ocp-4.14-amd64-gcp-ipi-ovn-ipsec.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__upstream-ocp-4.15-amd64-aws.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__upstream-ocp-4.16-amd64-aws-ipi-shared-vpc-phz-sts.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__upstream-upgrade-ocp-4.17-amd64-azure.yaml
  ci-operator/step-registry/distributed-tracing/tests/opentelemetry/upstream/distributed-tracing-tests-opentelemetry-upstream-commands.sh
  ci-operator/step-registry/distributed-tracing/tests/opentelemetry/upstream/distributed-tracing-tests-opentelemetry-upstream-ref.yaml
  ci-operator/step-registry/distributed-tracing/tests/tempo/upstream/distributed-tracing-tests-tempo-upstream-commands.sh
Labels: lgtm, approved, rehearsals-ack

#54344 MGMT-18398: Align all jobs running with latest OCP release to run 4.17
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-main.yaml
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-main__edge.yaml
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-main__mce.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master__edge.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master__mce.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-master__edge.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-master__mce.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-cloud_hotfix_releases.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__mce.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master__equinix-cleanup.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master__oci-cleanup.yaml
  ci-operator/config/openshift/cluster-api-provider-agent/openshift-cluster-api-provider-agent-master.yaml
  ci-operator/config/openshift/cluster-api-provider-agent/openshift-cluster-api-provider-agent-master__mce.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-main-periodics.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-main-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-main-presubmits.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master-periodics.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master-presubmits.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-master-periodics.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-master-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-master-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-cloud_hotfix_releases-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-cloud_hotfix_releases-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-periodics.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-periodics.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#55193 Add RBACs for ci-operator to get/list secrets from the ci namespace
  clusters/build-clusters/common/ci-operator/admin_ci-operator_rbac.yaml
Labels: lgtm, approved, rehearsals-ack

#55162 USHIFT-3150: Restructure MicroShift scenario files and add bootc presubmits
  ci-operator/config/openshift/microshift/openshift-microshift-main.yaml
  ci-operator/jobs/openshift/microshift/openshift-microshift-main-presubmits.yaml
  ci-operator/step-registry/openshift/microshift/infra/iso-boot/openshift-microshift-infra-iso-boot-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#55189 aws-load-balancer, external-dns: move image building to the repository [redo]
  ci-operator/config/openshift/aws-load-balancer-controller/openshift-aws-load-balancer-controller-main.yaml
  ci-operator/config/openshift/aws-load-balancer-controller/openshift-aws-load-balancer-controller-openshift-rel-1.0.yaml
  ci-operator/config/openshift/aws-load-balancer-controller/openshift-aws-load-balancer-controller-openshift-rel-1.1.yaml
  ci-operator/config/openshift/aws-load-balancer-controller/openshift-aws-load-balancer-controller-openshift-release-0.2.yaml
  ci-operator/config/openshift/external-dns/openshift-external-dns-master.yaml
  ci-operator/config/openshift/external-dns/openshift-external-dns-release-1.0.yaml
  ci-operator/config/openshift/external-dns/openshift-external-dns-release-1.1.yaml
  ci-operator/config/openshift/external-dns/openshift-external-dns-release-1.2.yaml
Labels: lgtm, approved, rehearsals-ack

#55199 Revert "Increase worker disks in e2e-metal-ipi-ovn-upgrade"
  ci-operator/step-registry/baremetalds/devscripts/setup/baremetalds-devscripts-setup-commands.sh
Labels: lgtm, approved, rehearsals-ack

#55187 chore(RHIDP-3335): Add job for running MVP with CPU and memory profilers on
  ci-operator/config/redhat-performance/backstage-performance/redhat-performance-backstage-performance-main.yaml
  ci-operator/jobs/redhat-performance/backstage-performance/redhat-performance-backstage-performance-main-presubmits.yaml
  ci-operator/step-registry/redhat-performance/backstage-performance/redhat-performance-backstage-performance-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#55190 [DPTP-4093] Include the multi arch builds under the ci-operator images stanza
  ci-operator/config/openshift-qe/baremetal-qe-infra/openshift-qe-baremetal-qe-infra-master.yaml
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
  ci-operator/config/openshift/loki/openshift-loki-main.yaml
  ci-operator/config/openshift/loki/openshift-loki-release-5.6.yaml
  ci-operator/config/openshift/loki/openshift-loki-release-5.8.yaml
  ci-operator/config/openshift/loki/openshift-loki-release-5.9.yaml
  ci-operator/config/openshift/loki/openshift-loki-upstream-v2.9.8.yaml
  ci-operator/config/openshift/loki/openshift-loki-upstream-v3.1.0.yaml
  ci-operator/config/openshift/multiarch-tuning-operator/openshift-multiarch-tuning-operator-main.yaml
  ci-operator/config/openshift/multiarch-tuning-operator/openshift-multiarch-tuning-operator-v0.0.1.yaml
  ci-operator/config/stolostron/image-builder/stolostron-image-builder-master.yaml
Labels: lgtm, approved, rehearsals-ack

#55048 [BM CPT] Add performance profile setup
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__metal-x86.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-presubmits.yaml
  ci-operator/step-registry/openshift-qe/installer/bm/day2/perf-profile/OWNERS
  ci-operator/step-registry/openshift-qe/installer/bm/day2/perf-profile/rds-core/OWNERS
  ci-operator/step-registry/openshift-qe/installer/bm/day2/perf-profile/rds-core/openshift-qe-installer-bm-day2-perf-profile-rds-core-chain.metadata.json
  ci-operator/step-registry/openshift-qe/installer/bm/day2/perf-profile/rds-core/openshift-qe-installer-bm-day2-perf-profile-rds-core-chain.yaml
  ci-operator/step-registry/openshift-qe/installer/bm/day2/perf-profile/rds-core/openshift-qe-installer-bm-day2-perf-profile-rds-core-commands.sh
  ci-operator/step-registry/openshift-qe/installer/bm/day2/perf-profile/rds-core/openshift-qe-installer-bm-day2-perf-profile-rds-core-ref.metadata.json
  ci-operator/step-registry/openshift-qe/installer/bm/day2/perf-profile/rds-core/openshift-qe-installer-bm-day2-perf-profile-rds-core-ref.yaml
  ci-operator/step-registry/openshift-qe/installer/bm/day2/perf-profile/rds-core/openshift-qe-installer-bm-day2-perf-profile-rds-core-workflow.metadata.json
  ci-operator/step-registry/openshift-qe/installer/bm/day2/perf-profile/rds-core/openshift-qe-installer-bm-day2-perf-profile-rds-core-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#55185 Add must-gather option to run command
  ci-operator/step-registry/operator/install/operator-install-commands.sh
  ci-operator/step-registry/operator/install/operator-install-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#55040 WRKLDS-1319: A job that adds nodes on day2 in already created compact ipv4 cluster by ABI
  ci-operator/config/openshift/oc/openshift-oc-master.yaml
  ci-operator/jobs/openshift/oc/openshift-oc-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#55209 Revert "Failover build03 to build09"
  clusters/app.ci/release-controller/deploy-ocp-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-priv-controller.yaml
  core-services/prow/02_config/_config.yaml
  hack/generators/release-controllers/content/osd_rc_deployments.py
Labels: lgtm, approved, rehearsals-ack

#55210 Revert "hypershift/openstack: also run e2e `TestNodePool` (#54827)"
  ci-operator/step-registry/hypershift/openstack/e2e/execute/hypershift-openstack-e2e-execute-commands.sh
Labels: lgtm, approved, rehearsals-ack

#55211 hypershift/openstack: fix base domain
  ci-operator/step-registry/hypershift/openstack/e2e/execute/hypershift-openstack-e2e-execute-commands.sh
  ci-operator/step-registry/hypershift/openstack/e2e/execute/hypershift-openstack-e2e-execute-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#55197 Update ACS scenario to support FIPS
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-17-lp-interop.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#55168 [INTEROP-7456] [INTEROP-7458] Create FIPS test for skupper/Service InterConnect; create .config.prowgen for slack_reporter config.
  ci-operator/config/skupperproject/skupper-openshift-smoke-test-image/.config.prowgen
  ci-operator/config/skupperproject/skupper-openshift-smoke-test-image/skupperproject-skupper-openshift-smoke-test-image-main__service-interconnect-ocp4.17-lp-interop.yaml
  ci-operator/jobs/skupperproject/skupper-openshift-smoke-test-image/skupperproject-skupper-openshift-smoke-test-image-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#55214 NO-JIRA: hypershift: unset resource-request-override annotation from mgmt clusters
  ci-operator/step-registry/hypershift/setup-nested-management-cluster/hypershift-setup-nested-management-cluster-chain.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#55201 Expand Ansible Tower to support FIPS
  ci-operator/config/ansible/tower-qa/ansible-tower-qa-devel__ocp4.17-lp-interop.yaml
  ci-operator/jobs/ansible/tower-qa/ansible-tower-qa-devel-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#54740 OCPQE-22438 Adding new introduced profiles in 4.16 to 4.17 upgrade config
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-nightly-4.17-upgrade-from-stable-4.16.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-nightly-4.17-upgrade-from-stable-4.17.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-stable-4.17-upgrade-from-stable-4.16.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__arm64-nightly-4.17-upgrade-from-stable-4.16.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__arm64-stable-4.17-upgrade-from-stable-4.16.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__multi-nightly-4.17-upgrade-from-stable-4.16.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__multi-stable-4.17-upgrade-from-stable-4.16.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#55217 NO-ISSUE: CAPI Agent report failed CI jobs to new slack channel
  core-services/prow/02_config/openshift/cluster-api-provider-agent/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#54878 stackrox: release-x.y ocp 4.15 -> 4.16
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-x.y__ocp-4-16.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-x.y-postsubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-x.y-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#55222 Use Dockerfile from S-O repo
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main.yaml
Labels: lgtm, approved, rehearsals-ack

#55230 Remove cancellation code
  ci-operator/step-registry/dpu-operator/e2e-tests-workflow/tests/dpu-operator-e2e-tests-workflow-tests-commands.sh
Labels: lgtm, approved, rehearsals-ack

#55234 chore: e2e-tests: make e2e-tests job optional
  ci-operator/config/konflux-ci/e2e-tests/konflux-ci-e2e-tests-main.yaml
  ci-operator/jobs/konflux-ci/e2e-tests/konflux-ci-e2e-tests-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#55121 Add snyk scanner
  ci-operator/config/openshift/cluster-api-provider-gcp/openshift-cluster-api-provider-gcp-master.yaml
  ci-operator/jobs/openshift/cluster-api-provider-gcp/openshift-cluster-api-provider-gcp-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#55109 MULTIARCH-4770: multi-arch: change day0 jobs to use TechPreview featu…
  ci-operator/config/openshift/installer/openshift-installer-master.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.17.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#55192 jobs-to-trigger move setting of retry_interval, used by both conditions
  ci-operator/step-registry/trigger-jobs/trigger-jobs-commands.sh
Labels: lgtm, approved, rehearsals-ack

#54930 sync ci profiles across versions - part 2 - gcp
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__multi-nightly-4.16-upgrade-from-stable-4.16.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-nightly-4.17-upgrade-from-stable-4.17.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__multi-nightly-4.17-upgrade-from-stable-4.16.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__multi-nightly-4.17-upgrade-from-stable-4.17.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__multi-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#55146 Fix issue DPTP-4121 Deploy Cloudability
  clusters/app.ci/cloudability-agent.yaml
  clusters/build-clusters/01_cluster/cloudability-agent.yaml
  clusters/build-clusters/02_cluster/cloudability-agent.yaml
  clusters/build-clusters/build03/cloudability-agent.yaml
  clusters/build-clusters/build04/cloudability-agent.yaml
  clusters/build-clusters/build05/cloudability-agent.yaml
  clusters/build-clusters/build09/cloudability-agent.yaml
  clusters/build-clusters/build10/cloudability-agent.yaml
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#55243 enable multi architecture builds for ci-operator image
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
Labels: lgtm, approved, rehearsals-ack

#55101 OCPEDGE-1088: feat: add Y-Stream periodic upgrade lanes for IBU
  ci-operator/config/openshift-kni/lifecycle-agent/openshift-kni-lifecycle-agent-main.yaml
  ci-operator/config/openshift-kni/lifecycle-agent/openshift-kni-lifecycle-agent-main__nightly-4.15-upgrade-from-stable-4.14.yaml
  ci-operator/config/openshift-kni/lifecycle-agent/openshift-kni-lifecycle-agent-main__nightly-4.15.yaml
  ci-operator/config/openshift-kni/lifecycle-agent/openshift-kni-lifecycle-agent-main__nightly-4.16-upgrade-from-stable-4.15.yaml
  ci-operator/config/openshift-kni/lifecycle-agent/openshift-kni-lifecycle-agent-main__nightly-4.16.yaml
  ci-operator/config/openshift-kni/lifecycle-agent/openshift-kni-lifecycle-agent-main__nightly-4.17-upgrade-from-stable-4.16.yaml
  ci-operator/config/openshift-kni/lifecycle-agent/openshift-kni-lifecycle-agent-release-4.14.yaml
  ci-operator/config/openshift-kni/lifecycle-agent/openshift-kni-lifecycle-agent-release-4.15.yaml
  ci-operator/config/openshift-kni/lifecycle-agent/openshift-kni-lifecycle-agent-release-4.16.yaml
  ci-operator/jobs/openshift-kni/lifecycle-agent/openshift-kni-lifecycle-agent-main-periodics.yaml
  ci-operator/step-registry/openshift/image-based/upgrade/seed/create/openshift-image-based-upgrade-seed-create-commands.sh
  ci-operator/step-registry/openshift/image-based/upgrade/seed/create/openshift-image-based-upgrade-seed-create-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#55221 hypershift/openstack: export cluster name
  ci-operator/step-registry/hypershift/openstack/e2e/execute/hypershift-openstack-e2e-execute-commands.sh
Labels: lgtm, approved, rehearsals-ack

#55224 Fix for BM day2/sriov
  ci-operator/step-registry/openshift-qe/installer/bm/day2/sriov/openshift-qe-installer-bm-day2-sriov-commands.sh
Labels: lgtm, approved, rehearsals-ack

#55247 Bump expected recovery time to 120s
  ci-operator/step-registry/redhat-chaos/pod-scenarios/random-system-pods/redhat-chaos-pod-scenarios-random-system-pods-ref.yaml
  ci-operator/step-registry/redhat-chaos/pod-scenarios/random-system-pods/redhat-chaos-pod-scenarios-random-system-pods-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#50795 Adding aro for 4.15
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__4.15-nightly.yaml
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__4.16-nightly.yaml
  ci-operator/jobs/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main-periodics.yaml
  ci-operator/step-registry/redhat-chaos/network-chaos/redhat-chaos-network-chaos-commands.sh
Labels: lgtm, approved, rehearsals-ack

#55250 Failover build02 to build09
  clusters/app.ci/release-controller/deploy-ocp-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-priv-controller.yaml
  core-services/prow/02_config/_config.yaml
  hack/generators/release-controllers/content/osd_rc_deployments.py
Labels: lgtm, approved, rehearsals-ack

#55244 OCPQE-24480: ServiceAccount For Programmatic Access to QCI for BM qe
  clusters/app.ci/registry-access/baremetal-qe/OWNERS
  clusters/app.ci/registry-access/baremetal-qe/baremetal-qe.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#53875 add rhtap cli install
  ci-operator/config/redhat-appstudio/rhtap-cli/OWNERS
  ci-operator/config/redhat-appstudio/rhtap-cli/redhat-appstudio-rhtap-cli-main.yaml
  ci-operator/jobs/redhat-appstudio/rhtap-cli/OWNERS
  ci-operator/jobs/redhat-appstudio/rhtap-cli/redhat-appstudio-rhtap-cli-main-periodics.yaml
  ci-operator/jobs/redhat-appstudio/rhtap-cli/redhat-appstudio-rhtap-cli-main-presubmits.yaml
  ci-operator/step-registry/redhat-appstudio/rhtap-cli/OWNERS
  ci-operator/step-registry/redhat-appstudio/rhtap-cli/redhat-appstudio-rhtap-cli-commands.sh
  ci-operator/step-registry/redhat-appstudio/rhtap-cli/redhat-appstudio-rhtap-cli-ref.metadata.json
  ci-operator/step-registry/redhat-appstudio/rhtap-cli/redhat-appstudio-rhtap-cli-ref.yaml
  ci-operator/step-registry/redhat-appstudio/rhtap-cli/redhat-appstudio-rhtap-cli-workflow.metadata.json
  ci-operator/step-registry/redhat-appstudio/rhtap-cli/redhat-appstudio-rhtap-cli-workflow.yaml
  ci-operator/step-registry/redhat-appstudio/rhtap-installer/e2e-test/redhat-appstudio-rhtap-installer-e2e-test-commands.sh
  core-services/prow/02_config/redhat-appstudio/rhtap-cli/OWNERS
  core-services/prow/02_config/redhat-appstudio/rhtap-cli/OWNERS copy
  core-services/prow/02_config/redhat-appstudio/rhtap-cli/_pluginconfig.yaml
  core-services/prow/02_config/redhat-appstudio/rhtap-cli/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#55172 [INTEROP-7456] [INTEROP-7458] Create FIPS test for SBO; create .config.prowgen for slack_reporter config.
  ci-operator/config/redhat-developer/service-binding-operator/.config.prowgen
  ci-operator/config/redhat-developer/service-binding-operator/redhat-developer-service-binding-operator-release-v1.4.x__4.17.yaml
  ci-operator/jobs/redhat-developer/service-binding-operator/redhat-developer-service-binding-operator-release-v1.4.x-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#55242 Revert tectonic v28 for kubevirt plugin
  ci-operator/config/kubevirt-ui/kubevirt-plugin/kubevirt-ui-kubevirt-plugin-main.yaml
Labels: lgtm, approved, rehearsals-ack

#55157 MULTIARCH-4847 README for multi-payload jobs
  ci-operator/config/openshift/multiarch/README.md
Labels: lgtm, approved, rehearsals-ack

#54838 Fuse csb firewatch base config and zstream expansion
  ci-operator/config/jboss-fuse/csb-tnb-tests-container/jboss-fuse-csb-tnb-tests-container-main__csb-ocp4.16-lp-interop.yaml
  ci-operator/jobs/jboss-fuse/csb-tnb-tests-container/jboss-fuse-csb-tnb-tests-container-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#55256 Remove OVMS release Build
  ci-operator/config/opendatahub-io/openvino_model_server/opendatahub-io-openvino_model_server-new_release.yaml
  ci-operator/config/opendatahub-io/openvino_model_server/opendatahub-io-openvino_model_server-release.yaml
  ci-operator/jobs/opendatahub-io/openvino_model_server/opendatahub-io-openvino_model_server-new_release-periodics.yaml
  ci-operator/jobs/opendatahub-io/openvino_model_server/opendatahub-io-openvino_model_server-new_release-postsubmits.yaml
  ci-operator/jobs/opendatahub-io/openvino_model_server/opendatahub-io-openvino_model_server-new_release-presubmits.yaml
  ci-operator/jobs/opendatahub-io/openvino_model_server/opendatahub-io-openvino_model_server-release-periodics.yaml
  ci-operator/jobs/opendatahub-io/openvino_model_server/opendatahub-io-openvino_model_server-release-postsubmits.yaml
  ci-operator/jobs/opendatahub-io/openvino_model_server/opendatahub-io-openvino_model_server-release-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#55260 Revert "Only run multi-arch tuning on labeled namespaces"
  clusters/build-clusters/build10/multiarch-manager-operator/admin_10-pod-placement-config.yaml
Labels: lgtm, approved, rehearsals-ack

#55261 Rename the stable tag of OVMS 2024.1-release branch of opendatahub-io…
  ci-operator/config/opendatahub-io/openvino_model_server/opendatahub-io-openvino_model_server-2024.1-release.yaml
Labels: lgtm, approved, rehearsals-ack

#55254 Add quota slices for ibmcloud-cspi-qe
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: lgtm, approved, rehearsals-ack

#55258 ACM business continuity - use golang 1.22 - https://issues.redhat.com/browse/ACM-13102
  ci-operator/config/stolostron/cluster-backup-operator/stolostron-cluster-backup-operator-main.yaml
  ci-operator/config/stolostron/cluster-backup-operator/stolostron-cluster-backup-operator-release-2.12.yaml
  ci-operator/config/stolostron/volsync-addon-controller/stolostron-volsync-addon-controller-main.yaml
  ci-operator/config/stolostron/volsync-addon-controller/stolostron-volsync-addon-controller-release-2.12.yaml
Labels: lgtm, approved, rehearsals-ack

#55251 `pod-scaler`: add `cache-bucket-v2` argument producer to start storing v2 data
  clusters/app.ci/pod-scaler/pod-scaler.yaml
Labels: lgtm, approved, rehearsals-ack

#55055 add springboot-interop-aws-fips for ocp 4.17
  ci-operator/config/rhoar-qe/spring-boot-openshift-interop-tests/rhoar-qe-spring-boot-openshift-interop-tests-main__springboot-ocp4.17-lp-interop.yaml
  ci-operator/jobs/rhoar-qe/spring-boot-openshift-interop-tests/rhoar-qe-spring-boot-openshift-interop-tests-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#53601 Onboarding openshift/ols-load-generator config to the CI
  ci-operator/config/openshift/ols-load-generator/OWNERS
  ci-operator/config/openshift/ols-load-generator/openshift-ols-load-generator-main.yaml
  ci-operator/jobs/openshift/ols-load-generator/OWNERS
  ci-operator/jobs/openshift/ols-load-generator/openshift-ols-load-generator-main-presubmits.yaml
  core-services/prow/02_config/openshift/ols-load-generator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/ols-load-generator/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#55181 OCPQE-24437: Set BASE_DOMAIN to support workflow-launch
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/ovn/hypershift/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/ovn/hypershift/cucushift-installer-rehearse-aws-ipi-ovn-hypershift-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/ovn/hypershift/provision/cucushift-installer-rehearse-aws-ipi-ovn-hypershift-provision-chain.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#55267 Update vsphere cluster profile
  core-services/ci-chat-bot/workflows-config.yaml
Labels: lgtm, approved, rehearsals-ack

#55219 [azure] enable CAPI on 4.17 jobs - part2
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__multi-nightly.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.17.yaml
  ci-operator/step-registry/ipi/deprovision/deprovision/in-bastion/ipi-deprovision-deprovision-in-bastion-commands.sh
  ci-operator/step-registry/ipi/install/install/in-bastion/ipi-install-install-in-bastion-commands.sh
Labels: lgtm, approved, rehearsals-ack

#55273 Fix url in ci-chat-bot README
  core-services/ci-chat-bot/README.md
Labels: lgtm, approved, rehearsals-ack

#54658 add capi rosa hcp upgrade job
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-stable.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
  ci-operator/step-registry/cucushift/hypershift-extended/capi/dump/OWNERS
  ci-operator/step-registry/cucushift/hypershift-extended/capi/dump/cucushift-hypershift-extended-capi-dump-commands.sh
  ci-operator/step-registry/cucushift/hypershift-extended/capi/dump/cucushift-hypershift-extended-capi-dump-ref.metadata.json
  ci-operator/step-registry/cucushift/hypershift-extended/capi/dump/cucushift-hypershift-extended-capi-dump-ref.yaml
  ci-operator/step-registry/cucushift/hypershift-extended/capi/init/cucushift-hypershift-extended-capi-init-commands.sh
  ci-operator/step-registry/cucushift/hypershift-extended/capi/provision/cucushift-hypershift-extended-capi-provision-commands.sh
  ci-operator/step-registry/cucushift/hypershift-extended/capi/provision/cucushift-hypershift-extended-capi-provision-ref.yaml
  ci-operator/step-registry/cucushift/hypershift-extended/capi/upgrade-cp/OWNERS
  ci-operator/step-registry/cucushift/hypershift-extended/capi/upgrade-cp/cucushift-hypershift-extended-capi-upgrade-cp-commands.sh
  ci-operator/step-registry/cucushift/hypershift-extended/capi/upgrade-cp/cucushift-hypershift-extended-capi-upgrade-cp-ref.metadata.json
  ci-operator/step-registry/cucushift/hypershift-extended/capi/upgrade-cp/cucushift-hypershift-extended-capi-upgrade-cp-ref.yaml
  ci-operator/step-registry/cucushift/hypershift-extended/capi/upgrade-np/OWNERS
  ci-operator/step-registry/cucushift/hypershift-extended/capi/upgrade-np/cucushift-hypershift-extended-capi-upgrade-np-commands.sh
  ci-operator/step-registry/cucushift/hypershift-extended/capi/upgrade-np/cucushift-hypershift-extended-capi-upgrade-np-ref.metadata.json
  ci-operator/step-registry/cucushift/hypershift-extended/capi/upgrade-np/cucushift-hypershift-extended-capi-upgrade-np-ref.yaml
  ci-operator/step-registry/rosa/aws/sts/hcp/capi-upgrade/OWNERS
  ci-operator/step-registry/rosa/aws/sts/hcp/capi-upgrade/rosa-aws-sts-hcp-capi-upgrade-workflow.metadata.json
  ci-operator/step-registry/rosa/aws/sts/hcp/capi-upgrade/rosa-aws-sts-hcp-capi-upgrade-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#55233 Update quay 3.12 SDL and DAST testing
  ci-operator/step-registry/quay-tests/deploy-quay-odf/quay-tests-deploy-quay-odf-commands.sh
  ci-operator/step-registry/quay-tests/provisioning-quay-security-testing/quay-tests-provisioning-quay-security-testing-commands.sh
  ci-operator/step-registry/quay-tests/scan-quay-images/quay-tests-scan-quay-images-commands.sh
  ci-operator/step-registry/quay-tests/scan-quay-images/quay-tests-scan-quay-images-ref.yaml
Labels: lgtm, approved, tide/merge-method-squash, rehearsals-ack

#55274 Update slack channel for rhdh main nightly
  ci-operator/jobs/janus-idp/backstage-showcase/janus-idp-backstage-showcase-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#55239 Adding FIPS validation as periodic job for Insights Operator
  ci-operator/config/openshift/insights-operator/openshift-insights-operator-master.yaml
  ci-operator/jobs/openshift/insights-operator/openshift-insights-operator-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#55231 Migrate to new image repository
  ci-operator/config/securesign/secure-sign-operator/securesign-secure-sign-operator-main.yaml
Labels: lgtm, approved, rehearsals-ack

#54400 Equinix baremetal sno recert test
  ci-operator/config/rh-ecosystem-edge/recert/rh-ecosystem-edge-recert-release-4.14.yaml
  ci-operator/config/rh-ecosystem-edge/recert/rh-ecosystem-edge-recert-release-4.15.yaml
  ci-operator/config/rh-ecosystem-edge/recert/rh-ecosystem-edge-recert-release-4.16.yaml
  ci-operator/jobs/rh-ecosystem-edge/recert/rh-ecosystem-edge-recert-release-4.14-periodics.yaml
  ci-operator/jobs/rh-ecosystem-edge/recert/rh-ecosystem-edge-recert-release-4.15-periodics.yaml
  ci-operator/jobs/rh-ecosystem-edge/recert/rh-ecosystem-edge-recert-release-4.16-periodics.yaml
  ci-operator/step-registry/single-node/recert/single-node-recert-commands.sh
Labels: lgtm, approved, rehearsals-ack

#54802 Add configuration for ospk8s test-operator
  ci-operator/config/openstack-k8s-operators/test-operator/OWNERS
  ci-operator/config/openstack-k8s-operators/test-operator/openstack-k8s-operators-test-operator-main.yaml
  ci-operator/jobs/openstack-k8s-operators/test-operator/OWNERS
  ci-operator/jobs/openstack-k8s-operators/test-operator/openstack-k8s-operators-test-operator-main-presubmits.yaml
  core-services/prow/02_config/openstack-k8s-operators/test-operator/OWNERS
  core-services/prow/02_config/openstack-k8s-operators/test-operator/_pluginconfig.yaml
  core-services/prow/02_config/openstack-k8s-operators/test-operator/_prowconfig.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#55075 Support external OIDC config for OCPE2E testing
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-stable.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17-periodics.yaml
  ci-operator/step-registry/rosa/setup/rosa-setup-commands.sh
Labels: lgtm, approved, rehearsals-ack

#55270 sync ci profiles across versions - part 3 - azure
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__multi-nightly-4.15-upgrade-from-stable-4.15.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__multi-stable-4.15-upgrade-from-stable-4.15.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly-4.16-upgrade-from-stable-4.15.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly-4.16-upgrade-from-stable-4.16.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__multi-nightly-4.16-upgrade-from-stable-4.15.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__multi-nightly-4.16-upgrade-from-stable-4.16.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__multi-stable-4.16-upgrade-from-stable-4.16.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-nightly-4.17-upgrade-from-stable-4.17.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__multi-nightly-4.17-upgrade-from-stable-4.16.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__multi-nightly-4.17-upgrade-from-stable-4.17.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__multi-stable-4.17-upgrade-from-stable-4.17.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#53502 Add ROSA HCP testing for File Integrity Operator
  ci-operator/config/openshift/file-integrity-operator/openshift-file-integrity-operator-master.yaml
  ci-operator/jobs/openshift/file-integrity-operator/openshift-file-integrity-operator-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#55266 CORS-2994: CI implementation: Support existing IAM instance profiles in AWS at install time
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__multi-nightly-4.17-upgrade-from-stable-4.17.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__multi-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17-periodics.yaml
  ci-operator/step-registry/cucushift/installer/check/aws/byo-iam-profile/OWNERS
  ci-operator/step-registry/cucushift/installer/check/aws/byo-iam-profile/cucushift-installer-check-aws-byo-iam-profile-commands.sh
  ci-operator/step-registry/cucushift/installer/check/aws/byo-iam-profile/cucushift-installer-check-aws-byo-iam-profile-ref.metadata.json
  ci-operator/step-registry/cucushift/installer/check/aws/byo-iam-profile/cucushift-installer-check-aws-byo-iam-profile-ref.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/byo-iam-profile/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/byo-iam-profile/cucushift-installer-rehearse-aws-ipi-byo-iam-profile-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/byo-iam-profile/cucushift-installer-rehearse-aws-ipi-byo-iam-profile-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/byo-iam-profile/deprovision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/byo-iam-profile/deprovision/cucushift-installer-rehearse-aws-ipi-byo-iam-profile-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/byo-iam-profile/deprovision/cucushift-installer-rehearse-aws-ipi-byo-iam-profile-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/byo-iam-profile/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/byo-iam-profile/provision/cucushift-installer-rehearse-aws-ipi-byo-iam-profile-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/byo-iam-profile/provision/cucushift-installer-rehearse-aws-ipi-byo-iam-profile-provision-chain.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#55202 ROX-25585: let openshift destroy use same ocp version as create
  ci-operator/step-registry/stackrox/automation-flavors/ocp-4-crun-e2e/stackrox-automation-flavors-ocp-4-crun-e2e-workflow.yaml
  ci-operator/step-registry/stackrox/automation-flavors/ocp-4-e2e/stackrox-automation-flavors-ocp-4-e2e-workflow.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#54703 Verify the readiness and architecture of nodes after installation and swap some jobs to mixarch day0
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__multi-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17-periodics.yaml
  ci-operator/step-registry/ipi/install/ipi-install-chain.yaml
  ci-operator/step-registry/multiarch/OWNERS
  ci-operator/step-registry/multiarch/validate-nodes/OWNERS
  ci-operator/step-registry/multiarch/validate-nodes/multiarch-validate-nodes-commands.sh
  ci-operator/step-registry/multiarch/validate-nodes/multiarch-validate-nodes-ref.metadata.json
  ci-operator/step-registry/multiarch/validate-nodes/multiarch-validate-nodes-ref.yaml
  ci-operator/step-registry/nodes/OWNERS
  ci-operator/step-registry/nodes/readiness/OWNERS
  ci-operator/step-registry/nodes/readiness/nodes-readiness-commands.sh
  ci-operator/step-registry/nodes/readiness/nodes-readiness-ref.metadata.json
  ci-operator/step-registry/nodes/readiness/nodes-readiness-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#55297 config/aep: use go 1.22 image
  ci-operator/config/openshift/aws-encryption-provider/openshift-aws-encryption-provider-master.yaml
  ci-operator/config/openshift/aws-encryption-provider/openshift-aws-encryption-provider-release-4.17.yaml
  ci-operator/config/openshift/aws-encryption-provider/openshift-aws-encryption-provider-release-4.18.yaml
Labels: lgtm, approved, rehearsals-ack

#55302 `pod-scaler`: add `cluster-monitoring-viewer` role to `pod-scaler` SA
  clusters/build-clusters/common/pod-scaler/serviceaccount.yaml
Labels: lgtm, approved, rehearsals-ack

#52090 [Pipelines] Switch to OpenShift Pipelines cluster pool
  ci-operator/config/openshift-pipelines/task-containers/openshift-pipelines-task-containers-main.yaml
  ci-operator/config/openshift-pipelines/task-git/openshift-pipelines-task-git-main.yaml
  ci-operator/config/openshift-pipelines/task-maven/openshift-pipelines-task-maven-main.yaml
  ci-operator/config/openshift-pipelines/task-openshift/openshift-pipelines-task-openshift-main.yaml
  ci-operator/jobs/openshift-pipelines/task-containers/openshift-pipelines-task-containers-main-presubmits.yaml
  ci-operator/jobs/openshift-pipelines/task-git/openshift-pipelines-task-git-main-presubmits.yaml
  ci-operator/jobs/openshift-pipelines/task-maven/openshift-pipelines-task-maven-main-presubmits.yaml
  ci-operator/jobs/openshift-pipelines/task-openshift/openshift-pipelines-task-openshift-main-presubmits.yaml
Labels: lgtm, approved, lifecycle/rotten, rehearsals-ack

#55296 [ACM-12523] Onboarded siteconfig component
  ci-operator/config/stolostron/siteconfig/OWNERS
  ci-operator/config/stolostron/siteconfig/stolostron-siteconfig-main.yaml
  ci-operator/config/stolostron/siteconfig/stolostron-siteconfig-release-2.12.yaml
  ci-operator/jobs/stolostron/siteconfig/OWNERS
  ci-operator/jobs/stolostron/siteconfig/stolostron-siteconfig-main-postsubmits.yaml
  ci-operator/jobs/stolostron/siteconfig/stolostron-siteconfig-main-presubmits.yaml
  ci-operator/jobs/stolostron/siteconfig/stolostron-siteconfig-release-2.12-postsubmits.yaml
  ci-operator/jobs/stolostron/siteconfig/stolostron-siteconfig-release-2.12-presubmits.yaml
  core-services/prow/02_config/stolostron/siteconfig/OWNERS
  core-services/prow/02_config/stolostron/siteconfig/_pluginconfig.yaml
  core-services/prow/02_config/stolostron/siteconfig/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#55295 Split unit and integration test on sail-operator jobs
  ci-operator/config/openshift-service-mesh/sail-operator/openshift-service-mesh-sail-operator-main.yaml
  ci-operator/config/openshift-service-mesh/sail-operator/openshift-service-mesh-sail-operator-release-3.0-tp1.yaml
  ci-operator/jobs/openshift-service-mesh/sail-operator/openshift-service-mesh-sail-operator-main-presubmits.yaml
  ci-operator/jobs/openshift-service-mesh/sail-operator/openshift-service-mesh-sail-operator-release-3.0-tp1-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#55305 Add optional kube-apiserver rollout presubmits to origin
  ci-operator/config/openshift/origin/openshift-origin-master.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#55298 OCPBUGS-38113: openstack: Fix the generation of application credentials
  ci-operator/step-registry/openstack/conf/clouds/openstack-conf-clouds-commands.sh
Labels: lgtm, approved, jira/valid-bug, rehearsals-ack, jira/valid-reference

#55311 [ACM-12523] Updated siteconfig ref name
  ci-operator/config/stolostron/siteconfig/stolostron-siteconfig-main.yaml
  ci-operator/config/stolostron/siteconfig/stolostron-siteconfig-release-2.12.yaml
Labels: lgtm, approved, rehearsals-ack
