Repository openshift/release, pull requests merged in 2024-04, with the labels that each got.

#49932 Ignore the initial cluster upgrade failure when there's RHEL workers
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly-4.16-upgrade-from-stable-4.15.yaml
  ci-operator/step-registry/cucushift/chainupgrade/toimage/cucushift-chainupgrade-toimage-commands.sh
  ci-operator/step-registry/cucushift/chainupgrade/toimage/cucushift-chainupgrade-toimage-ref.yaml
  ci-operator/step-registry/cucushift/upgrade/toimage/cucushift-upgrade-toimage-commands.sh
  ci-operator/step-registry/cucushift/upgrade/toimage/cucushift-upgrade-toimage-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#50403 Update the global hub base image tag
  ci-operator/config/stolostron/multicluster-global-hub/stolostron-multicluster-global-hub-release-2.11.yaml
  ci-operator/config/stolostron/multicluster-global-hub/stolostron-multicluster-global-hub-release-2.9.yaml
Labels: lgtm, approved, rehearsals-ack

#50376 replace jobs' workflows for rosa classic
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-master__rosacli.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-ec.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-master-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
  ci-operator/step-registry/rosa/aws/sts/localzone/rosa-aws-sts-localzone-workflow.yaml
  ci-operator/step-registry/rosa/aws/sts/private-proxy/rosa-aws-sts-private-proxy-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#50396 [HyperShift QE]: remove hypershift0-*-control-plane/worker-node
  ci-operator/step-registry/openshift/upgrade/qe/test/hypershift/control-plane/OWNERS
  ci-operator/step-registry/openshift/upgrade/qe/test/hypershift/control-plane/openshift-upgrade-qe-test-hypershift-control-plane-chain.metadata.json
  ci-operator/step-registry/openshift/upgrade/qe/test/hypershift/control-plane/openshift-upgrade-qe-test-hypershift-control-plane-chain.yaml
  ci-operator/step-registry/openshift/upgrade/qe/test/hypershift/worker-node/OWNERS
  ci-operator/step-registry/openshift/upgrade/qe/test/hypershift/worker-node/openshift-upgrade-qe-test-hypershift-worker-node-chain.metadata.json
  ci-operator/step-registry/openshift/upgrade/qe/test/hypershift/worker-node/openshift-upgrade-qe-test-hypershift-worker-node-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#50395 make ref use installer created namespaces.
  ci-operator/step-registry/redhat-appstudio/rhtap-installer/e2e-test/redhat-appstudio-rhtap-installer-e2e-test-commands.sh
Labels: lgtm, approved, rehearsals-ack

#50409 chore: update powermon jobs
  ci-operator/config/openshift-power-monitoring/kepler/openshift-power-monitoring-kepler-main.yaml
  ci-operator/config/openshift-power-monitoring/kepler/openshift-power-monitoring-kepler-main__ocp4.15-periodic.yaml
  ci-operator/config/openshift-power-monitoring/kepler/openshift-power-monitoring-kepler-main__post-submit.yaml
  ci-operator/config/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-tech-preview__ocp4.13-periodic.yaml
  ci-operator/config/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-tech-preview__product-ocp-4.14-stage.yaml
  ci-operator/config/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-v1alpha1.yaml
  ci-operator/config/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-v1alpha1__ocp4.15-periodic.yaml
  ci-operator/config/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-v1alpha1__post-submit.yaml
  ci-operator/jobs/openshift-power-monitoring/kepler/openshift-power-monitoring-kepler-main-periodics.yaml
  ci-operator/jobs/openshift-power-monitoring/kepler/openshift-power-monitoring-kepler-main-postsubmits.yaml
  ci-operator/jobs/openshift-power-monitoring/kepler/openshift-power-monitoring-kepler-main-presubmits.yaml
  ci-operator/jobs/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-tech-preview-periodics.yaml
  ci-operator/jobs/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-tech-preview-presubmits.yaml
  ci-operator/jobs/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-v1alpha1-periodics.yaml
  ci-operator/jobs/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-v1alpha1-postsubmits.yaml
  ci-operator/jobs/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-v1alpha1-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#50278 openshift-loki: Add ci config for branch upstream-v2.9.6
  ci-operator/config/openshift/loki/openshift-loki-upstream-v2.9.6.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-upstream-v2.9.6-postsubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-upstream-v2.9.6-presubmits.yaml
  core-services/image-mirroring/openshift-logging/mapping_logging_loki_quay
Labels: lgtm, approved, rehearsals-ack

#50420 GitOps | Enable cluster pool
  clusters/hive/pools/gitops/gitops-ocp-4-12-0-amd64-aws-us-east-2_clusterpool.yaml
  clusters/hive/pools/gitops/gitops-ocp-4-14-0-amd64-aws-us-east-2_clusterpool.yaml
  clusters/hive/pools/gitops/gitops-ocp-4-15-0-amd64-aws-us-east-2_clusterpool.yaml
Labels: lgtm, approved, rehearsals-ack

#50418 GitOps | Disable CI for v1.9 branch
  ci-operator/config/redhat-developer/gitops-operator/redhat-developer-gitops-operator-v1.9.yaml
  ci-operator/config/redhat-developer/gitops-operator/redhat-developer-gitops-operator-v1.9__v4.12.yaml
  ci-operator/config/redhat-developer/gitops-operator/redhat-developer-gitops-operator-v1.9__v4.13.yaml
  ci-operator/config/redhat-developer/gitops-operator/redhat-developer-gitops-operator-v1.9__v4.14.yaml
  ci-operator/jobs/redhat-developer/gitops-operator/redhat-developer-gitops-operator-v1.9-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#50311 MULTIARCH-4555: Moved libvirt heterogeneous chain to make room for shared base chain.
  ci-operator/step-registry/openshift/e2e/libvirt/upi/heterogeneous/openshift-e2e-libvirt-upi-heterogeneous-workflow.yaml
  ci-operator/step-registry/upi/libvirt/heterogeneous/OWNERS
  ci-operator/step-registry/upi/libvirt/heterogeneous/post/OWNERS
  ci-operator/step-registry/upi/libvirt/heterogeneous/post/upi-libvirt-heterogeneous-post-chain.metadata.json
  ci-operator/step-registry/upi/libvirt/heterogeneous/post/upi-libvirt-heterogeneous-post-chain.yaml
  ci-operator/step-registry/upi/libvirt/heterogeneous/pre/OWNERS
  ci-operator/step-registry/upi/libvirt/heterogeneous/pre/upi-libvirt-heterogeneous-pre-chain.metadata.json
  ci-operator/step-registry/upi/libvirt/heterogeneous/pre/upi-libvirt-heterogeneous-pre-chain.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#50422 Add ODF members to RedHat-Storage OWNERS
  ci-operator/config/red-hat-storage/OWNERS
Labels: lgtm, approved, rehearsals-ack

#50429 stop ignoring gh review status for o-f/api repo
  core-services/prow/02_config/operator-framework/api/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#50427 `check-gh-automation`: disable branch-protection check in the tide version
  ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#50423 Update ODF_VERSION_MAJOR_MINOR var
  ci-operator/step-registry/interop-tests/deploy-odf/interop-tests-deploy-odf-ref.yaml
  ci-operator/step-registry/interop-tests/ocs-tests/interop-tests-ocs-tests-commands.sh
  ci-operator/step-registry/interop-tests/ocs-tests/interop-tests-ocs-tests-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#50431 `BYOIP`: specify region in Boskos resource name
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: lgtm, approved, rehearsals-ack

#50433 setting rhoe-cluster-pool for ocp 4.15 east-1 to size 5
  clusters/hive/pools/rh-openshift-ecosystem/rhoe-ocp-4-15-amd64-aws-us-east-1_clusterpool.yaml
Labels: lgtm, approved, rehearsals-ack

#50416 update(go): update go version for ODH and RHOAI operator
  ci-operator/config/opendatahub-io/opendatahub-operator/opendatahub-io-opendatahub-operator-incubation.yaml
  ci-operator/config/opendatahub-io/opendatahub-operator/opendatahub-io-opendatahub-operator-main.yaml
  ci-operator/config/red-hat-data-services/must-gather/red-hat-data-services-must-gather-main.yaml
  ci-operator/config/red-hat-data-services/opendatahub-operator/red-hat-data-services-opendatahub-operator-master.yaml
  ci-operator/config/red-hat-data-services/opendatahub-operator/red-hat-data-services-opendatahub-operator-master__48.yaml
Labels: lgtm, approved, rehearsals-ack

#50435 setting rhoe-cluster-pool for ocp 4.15 east-2 to size 5
  clusters/hive/pools/rh-openshift-ecosystem/rhoe-ocp-4-15-amd64-aws-us-east-2_clusterpool.yaml
Labels: lgtm, approved, rehearsals-ack

#50428 fix: add OADP non admin image job
  ci-operator/config/migtools/oadp-non-admin/OWNERS
  ci-operator/config/migtools/oadp-non-admin/migtools-oadp-non-admin-master.yaml
  ci-operator/jobs/migtools/oadp-non-admin/OWNERS
  ci-operator/jobs/migtools/oadp-non-admin/migtools-oadp-non-admin-master-postsubmits.yaml
  ci-operator/jobs/migtools/oadp-non-admin/migtools-oadp-non-admin-master-presubmits.yaml
  core-services/prow/02_config/migtools/oadp-non-admin/_pluginconfig.yaml
  core-services/prow/02_config/migtools/oadp-non-admin/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#50440 setting rhoe-cluster-pool for ocp 4.15 east-2 to size 0
  clusters/hive/pools/rh-openshift-ecosystem/rhoe-ocp-4-15-amd64-aws-us-east-2_clusterpool.yaml
Labels: lgtm, approved, rehearsals-ack

#50443 fix: add OADP non admin image mirroring job
  core-services/image-mirroring/konveyor/mapping_konveyor_latest
Labels: lgtm, approved, rehearsals-ack

#50415 Removed the old workflows for rosa classic
  ci-operator/step-registry/rosa/aws/non-sts/advanced/OWNERS
  ci-operator/step-registry/rosa/aws/non-sts/advanced/rosa-aws-non-sts-advanced-workflow.metadata.json
  ci-operator/step-registry/rosa/aws/non-sts/advanced/rosa-aws-non-sts-advanced-workflow.yaml
  ci-operator/step-registry/rosa/aws/sts/advanced/OWNERS
  ci-operator/step-registry/rosa/aws/sts/advanced/rosa-aws-sts-advanced-workflow.metadata.json
  ci-operator/step-registry/rosa/aws/sts/advanced/rosa-aws-sts-advanced-workflow.yaml
  ci-operator/step-registry/rosa/aws/sts/private-link/OWNERS
  ci-operator/step-registry/rosa/aws/sts/private-link/rosa-aws-sts-private-link-workflow.metadata.json
  ci-operator/step-registry/rosa/aws/sts/private-link/rosa-aws-sts-private-link-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#50447 move to stable channel for rosa sts classic
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-master__rosacli.yaml
Labels: lgtm, approved, rehearsals-ack

#50323 Add cluster autoscaler parameters for rosa
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-ec.yaml
  ci-operator/step-registry/rosa/cluster/provision/rosa-cluster-provision-commands.sh
  ci-operator/step-registry/rosa/cluster/provision/rosa-cluster-provision-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#50291 osdfm: test mhc
  ci-operator/step-registry/osd-ccs/fleet-manager/osd-ccs-fleet-manager-workflow.yaml
  ci-operator/step-registry/osd-ccs/fleet-manager/test/machinehealthchecks/OWNERS
  ci-operator/step-registry/osd-ccs/fleet-manager/test/machinehealthchecks/osd-ccs-fleet-manager-test-machinehealthchecks-commands.sh
  ci-operator/step-registry/osd-ccs/fleet-manager/test/machinehealthchecks/osd-ccs-fleet-manager-test-machinehealthchecks-ref.metadata.json
  ci-operator/step-registry/osd-ccs/fleet-manager/test/machinehealthchecks/osd-ccs-fleet-manager-test-machinehealthchecks-ref.yaml
  ci-operator/step-registry/osd-ccs/fleet-manager/test/osd-ccs-fleet-manager-test-commands.sh
Labels: lgtm, approved, rehearsals-ack

#50451 HyperShift: Ignore the error of the azure-path-fix pod temporarily
  ci-operator/step-registry/cucushift/hypershift-extended/health-check/cucushift-hypershift-extended-health-check-commands.sh
Labels: lgtm, approved, rehearsals-ack

#50343 Sync Serverless CI
  ci-operator/config/openshift-knative/eventing-hyperfoil-benchmark/openshift-knative-eventing-hyperfoil-benchmark-main__414.yaml
  ci-operator/config/openshift-knative/eventing-hyperfoil-benchmark/openshift-knative-eventing-hyperfoil-benchmark-main__415.yaml
  ci-operator/jobs/openshift-knative/eventing-hyperfoil-benchmark/openshift-knative-eventing-hyperfoil-benchmark-main-periodics.yaml
  ci-operator/jobs/openshift-knative/eventing-hyperfoil-benchmark/openshift-knative-eventing-hyperfoil-benchmark-main-postsubmits.yaml
  ci-operator/jobs/openshift-knative/eventing-hyperfoil-benchmark/openshift-knative-eventing-hyperfoil-benchmark-main-presubmits.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#50452 Treat platform External as none
  ci-operator/step-registry/cucushift/chainupgrade/toimage/cucushift-chainupgrade-toimage-commands.sh
  ci-operator/step-registry/cucushift/e2e/cucushift-e2e-commands.sh
  ci-operator/step-registry/cucushift/e2e/devel/cucushift-e2e-devel-commands.sh
  ci-operator/step-registry/cucushift/upgrade/check/cucushift-upgrade-check-commands.sh
  ci-operator/step-registry/cucushift/upgrade/prepare/cucushift-upgrade-prepare-commands.sh
Labels: lgtm, approved, rehearsals-ack

#50121 OCPQE-20265: Update vsphere-csi-extended workflow
  ci-operator/step-registry/openshift/e2e/vsphere/csi/extended/openshift-e2e-vsphere-csi-extended-workflow.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#48201 Interop - Onboard ODF scenario
  ci-operator/config/red-hat-storage/ocs-ci/OWNERS
  ci-operator/config/red-hat-storage/ocs-ci/README.md
  ci-operator/config/red-hat-storage/ocs-ci/red-hat-storage-ocs-ci-master__odf-ocp4.15-lp-interop.yaml
  ci-operator/config/red-hat-storage/ocs-ci/red-hat-storage-ocs-ci-master__odf-ocp4.16-lp-interop.yaml
  ci-operator/jobs/red-hat-storage/ocs-ci/OWNERS
  ci-operator/jobs/red-hat-storage/ocs-ci/red-hat-storage-ocs-ci-master-periodics.yaml
  ci-operator/step-registry/odf/OWNERS
  ci-operator/step-registry/odf/apply-storage-cluster/OWNERS
  ci-operator/step-registry/odf/apply-storage-cluster/odf-apply-storage-cluster-commands.sh
  ci-operator/step-registry/odf/apply-storage-cluster/odf-apply-storage-cluster-ref.metadata.json
  ci-operator/step-registry/odf/apply-storage-cluster/odf-apply-storage-cluster-ref.yaml
  ci-operator/step-registry/odf/prepare-cluster/OWNERS
  ci-operator/step-registry/odf/prepare-cluster/odf-prepare-cluster-commands.sh
  ci-operator/step-registry/odf/prepare-cluster/odf-prepare-cluster-ref.metadata.json
  ci-operator/step-registry/odf/prepare-cluster/odf-prepare-cluster-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#50353 Adding list of preview URLs to the CI build bot comment
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-build-docs-1.0.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-build-docs-1.1.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-build-docs-main.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-enterprise-4.11.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-enterprise-4.12.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-enterprise-4.13.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-enterprise-4.14.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-enterprise-4.15.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-enterprise-4.16.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-gitops-docs-1.10.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-gitops-docs-1.11.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-gitops-docs-1.12.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-gitops-docs-1.8.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-gitops-docs-1.9.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-gitops-docs-main.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-main.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-opp-docs.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-pipelines-docs-1.10.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-pipelines-docs-1.11.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-pipelines-docs-1.12.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-pipelines-docs-1.13.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-pipelines-docs-1.14.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-pipelines-docs-main.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-rhde-docs-main.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-serverless-docs-1.28.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-serverless-docs-1.29.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-serverless-docs-1.30.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-serverless-docs-1.31.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-serverless-docs-1.32.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-serverless-docs-main.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-service-mesh-docs-main.yaml
Labels: lgtm, approved, rehearsals-ack

#50446 OCPQE-19762 Skip upgrade when target is not recommended in stable-stable path
  ci-operator/step-registry/cucushift/chainupgrade/toimage/cucushift-chainupgrade-toimage-commands.sh
  ci-operator/step-registry/cucushift/chainupgrade/toimage/cucushift-chainupgrade-toimage-ref.yaml
  ci-operator/step-registry/cucushift/upgrade/check-not-recommended/OWNERS
  ci-operator/step-registry/cucushift/upgrade/check-not-recommended/cucushift-upgrade-check-not-recommended-commands.sh
  ci-operator/step-registry/cucushift/upgrade/check-not-recommended/cucushift-upgrade-check-not-recommended-ref.metadata.json
  ci-operator/step-registry/cucushift/upgrade/check-not-recommended/cucushift-upgrade-check-not-recommended-ref.yaml
  ci-operator/step-registry/openshift/upgrade/qe/sanity/openshift-upgrade-qe-sanity-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#50455 OCM-6387 Add notification to `rosa-hcp-ad` nightlies
  ci-operator/jobs/terraform-redhat/terraform-provider-rhcs/terraform-redhat-terraform-provider-rhcs-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#50470 rhtap: Update pipeline task name
  ci-operator/step-registry/redhat-appstudio/rhtap-installer/install-rhtap/redhat-appstudio-rhtap-installer-install-rhtap-commands.sh
  ci-operator/step-registry/redhat-appstudio/rhtap-installer/reinstall-rhtap/redhat-appstudio-rhtap-installer-reinstall-rhtap-commands.sh
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#49830 USHIFT-1349: automate publishing microshift pre-release info
  ci-operator/config/openshift/microshift/openshift-microshift-main.yaml
  ci-operator/jobs/openshift/microshift/openshift-microshift-main-periodics.yaml
  ci-operator/step-registry/openshift/microshift/publish-release-notes/OWNERS
  ci-operator/step-registry/openshift/microshift/publish-release-notes/openshift-microshift-publish-release-notes-chain.metadata.json
  ci-operator/step-registry/openshift/microshift/publish-release-notes/openshift-microshift-publish-release-notes-chain.yaml
  ci-operator/step-registry/openshift/microshift/publish-release-notes/openshift-microshift-publish-release-notes-commands.sh
  ci-operator/step-registry/openshift/microshift/publish-release-notes/openshift-microshift-publish-release-notes-ref.metadata.json
  ci-operator/step-registry/openshift/microshift/publish-release-notes/openshift-microshift-publish-release-notes-ref.yaml
  ci-operator/step-registry/openshift/microshift/publish-release-notes/openshift-microshift-publish-release-notes-workflow.metadata.json
  ci-operator/step-registry/openshift/microshift/publish-release-notes/openshift-microshift-publish-release-notes-workflow.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#50473 chore: require self approval for dsp repo
  core-services/prow/02_config/opendatahub-io/data-science-pipelines/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#50086 hypershift, kubevirt: Add dev-scripts to presubmit
  ci-operator/config/openshift/hypershift/openshift-hypershift-main.yaml
Labels: lgtm, approved, rehearsals-ack

#50475 Ignore a broken image ci/rhcs-tf-e2e:90f0a9d8fd70fbc4785006c298a3ae99…
  clusters/app.ci/assets/admin_ci-images-mirror.yaml
Labels: lgtm, approved, rehearsals-ack

#50206 Increase disk size for KubeVirt Periodic infra
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.16__periodics.yaml
  ci-operator/step-registry/hypershift/kubevirt/baremetalds/conformance/hypershift-kubevirt-baremetalds-conformance-workflow.yaml
  ci-operator/step-registry/hypershift/mce/kubevirt/baremetalds/conformance/hypershift-mce-kubevirt-baremetalds-conformance-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#50391 Adding azure arm
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__azure-4.16-nightly-arm.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__azure-4.16-nightly-x86.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-postsubmits.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-presubmits.yaml
  ci-operator/step-registry/openshift-qe/installer/azure/ipi/ovn/arm/OWNERS
  ci-operator/step-registry/openshift-qe/installer/azure/ipi/ovn/arm/openshift-qe-installer-azure-ipi-ovn-arm-workflow.metadata.json
  ci-operator/step-registry/openshift-qe/installer/azure/ipi/ovn/arm/openshift-qe-installer-azure-ipi-ovn-arm-workflow.yaml
  ci-operator/step-registry/openshift-qe/workers-infra-workload/openshift-qe-workers-infra-workload-commands.sh
Labels: lgtm, approved, rehearsals-ack

#50476 Always run some presubmit recert jobs
  ci-operator/config/rh-ecosystem-edge/recert/rh-ecosystem-edge-recert-main.yaml
  ci-operator/jobs/rh-ecosystem-edge/recert/rh-ecosystem-edge-recert-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#50450 Temporary fix for 4.15 operator-registry issue
  ci-operator/step-registry/operator-pipelines/preflight-common/operator-registry-cache-fix/OWNERS
  ci-operator/step-registry/operator-pipelines/preflight-common/operator-registry-cache-fix/operator-pipelines-preflight-common-operator-registry-cache-fix-commands.sh
  ci-operator/step-registry/operator-pipelines/preflight-common/operator-registry-cache-fix/operator-pipelines-preflight-common-operator-registry-cache-fix-ref.metadata.json
  ci-operator/step-registry/operator-pipelines/preflight-common/operator-registry-cache-fix/operator-pipelines-preflight-common-operator-registry-cache-fix-ref.yaml
  ci-operator/step-registry/operator-pipelines/preflight-preprod/operator-registry-cache-fix/OWNERS
  ci-operator/step-registry/operator-pipelines/preflight-preprod/operator-registry-cache-fix/operator-pipelines-preflight-preprod-operator-registry-cache-fix-commands.sh
  ci-operator/step-registry/operator-pipelines/preflight-preprod/operator-registry-cache-fix/operator-pipelines-preflight-preprod-operator-registry-cache-fix-ref.metadata.json
  ci-operator/step-registry/operator-pipelines/preflight-preprod/operator-registry-cache-fix/operator-pipelines-preflight-preprod-operator-registry-cache-fix-ref.yaml
  ci-operator/step-registry/operator-pipelines/preflight-prod/operator-registry-cache-fix/OWNERS
  ci-operator/step-registry/operator-pipelines/preflight-prod/operator-registry-cache-fix/operator-pipelines-preflight-prod-operator-registry-cache-fix-commands.sh
  ci-operator/step-registry/operator-pipelines/preflight-prod/operator-registry-cache-fix/operator-pipelines-preflight-prod-operator-registry-cache-fix-ref.metadata.json
  ci-operator/step-registry/operator-pipelines/preflight-prod/operator-registry-cache-fix/operator-pipelines-preflight-prod-operator-registry-cache-fix-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#50288 Add Openshift virtualization tests as a step
  ci-operator/config/RedHatQE/interop-testing/RedHatQE-interop-testing-cnv-4.16__cnv-odf-ocp4.16-lp-interop.yaml
  ci-operator/step-registry/interop-tests/openshift-virtualization-tests/OWNERS
  ci-operator/step-registry/interop-tests/openshift-virtualization-tests/interop-tests-openshift-virtualization-tests-commands.sh
  ci-operator/step-registry/interop-tests/openshift-virtualization-tests/interop-tests-openshift-virtualization-tests-ref.metadata.json
  ci-operator/step-registry/interop-tests/openshift-virtualization-tests/interop-tests-openshift-virtualization-tests-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#50488 Fix the username for OSSM bot
  core-services/prow/02_config/openshift-service-mesh/sail-operator/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#50457 Update AzureFile limits
  ci-operator/config/openshift/azure-file-csi-driver/openshift-azure-file-csi-driver-master.yaml
  ci-operator/config/openshift/azure-file-csi-driver/openshift-azure-file-csi-driver-release-4.12.yaml
  ci-operator/config/openshift/azure-file-csi-driver/openshift-azure-file-csi-driver-release-4.13.yaml
  ci-operator/config/openshift/azure-file-csi-driver/openshift-azure-file-csi-driver-release-4.14.yaml
  ci-operator/config/openshift/azure-file-csi-driver/openshift-azure-file-csi-driver-release-4.15.yaml
  ci-operator/config/openshift/azure-file-csi-driver/openshift-azure-file-csi-driver-release-4.16.yaml
  ci-operator/config/openshift/azure-file-csi-driver/openshift-azure-file-csi-driver-release-4.17.yaml
Labels: lgtm, approved, rehearsals-ack

#49615 onboard acm-workload
  ci-operator/config/stolostron/acm-workload/OWNERS
  ci-operator/config/stolostron/acm-workload/stolostron-acm-workload-main.yaml
  ci-operator/config/stolostron/acm-workload/stolostron-acm-workload-release-2.10.yaml
  ci-operator/config/stolostron/acm-workload/stolostron-acm-workload-release-2.9.yaml
  ci-operator/jobs/stolostron/acm-workload/OWNERS
  ci-operator/jobs/stolostron/acm-workload/stolostron-acm-workload-main-postsubmits.yaml
  ci-operator/jobs/stolostron/acm-workload/stolostron-acm-workload-main-presubmits.yaml
  ci-operator/jobs/stolostron/acm-workload/stolostron-acm-workload-release-2.10-postsubmits.yaml
  ci-operator/jobs/stolostron/acm-workload/stolostron-acm-workload-release-2.10-presubmits.yaml
  ci-operator/jobs/stolostron/acm-workload/stolostron-acm-workload-release-2.9-postsubmits.yaml
  ci-operator/jobs/stolostron/acm-workload/stolostron-acm-workload-release-2.9-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#50472 Fix issue DPTP-3923 Add missing files for app.ci
  clusters/app.ci/common_managed
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#50486 CORS-2899: pre/installer/altinfra: edge zones split into Wavelength and Local Zones
  ci-operator/config/openshift/installer/openshift-installer-master__altinfra.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.16__altinfra.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.17__altinfra.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.16-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.17-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#50493 Add proper image and export KUBECONFIG
  ci-operator/step-registry/operator-pipelines/preflight-common/operator-registry-cache-fix/operator-pipelines-preflight-common-operator-registry-cache-fix-commands.sh
  ci-operator/step-registry/operator-pipelines/preflight-common/operator-registry-cache-fix/operator-pipelines-preflight-common-operator-registry-cache-fix-ref.yaml
  ci-operator/step-registry/operator-pipelines/preflight-preprod/operator-registry-cache-fix/operator-pipelines-preflight-preprod-operator-registry-cache-fix-commands.sh
  ci-operator/step-registry/operator-pipelines/preflight-preprod/operator-registry-cache-fix/operator-pipelines-preflight-preprod-operator-registry-cache-fix-ref.yaml
  ci-operator/step-registry/operator-pipelines/preflight-prod/operator-registry-cache-fix/operator-pipelines-preflight-prod-operator-registry-cache-fix-commands.sh
  ci-operator/step-registry/operator-pipelines/preflight-prod/operator-registry-cache-fix/operator-pipelines-preflight-prod-operator-registry-cache-fix-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#50448 SDN-4464: remove OpenShiftSDN jobs in 4.16+
  ci-operator/config/openshift/cloud-network-config-controller/openshift-cloud-network-config-controller-master.yaml
  ci-operator/config/openshift/cloud-network-config-controller/openshift-cloud-network-config-controller-release-4.16.yaml
  ci-operator/config/openshift/cloud-network-config-controller/openshift-cloud-network-config-controller-release-4.17.yaml
  ci-operator/jobs/openshift/cloud-network-config-controller/openshift-cloud-network-config-controller-master-presubmits.yaml
  ci-operator/jobs/openshift/cloud-network-config-controller/openshift-cloud-network-config-controller-release-4.16-presubmits.yaml
  ci-operator/jobs/openshift/cloud-network-config-controller/openshift-cloud-network-config-controller-release-4.17-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#50489 stackrox: add ocp-dev-preview optional on master
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-preview.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#50495 Update jobs to implement registry fix
  ci-operator/config/redhat-openshift-ecosystem/certified-operators-preprod/redhat-openshift-ecosystem-certified-operators-preprod-ocp-4.15.yaml
  ci-operator/config/redhat-openshift-ecosystem/certified-operators-prod/redhat-openshift-ecosystem-certified-operators-prod-ocp-4.15.yaml
  ci-operator/config/redhat-openshift-ecosystem/preflight/redhat-openshift-ecosystem-preflight-ocp-4.15.yaml
  ci-operator/step-registry/operator-pipelines/preflight-common/operator-registry-cache-fix/operator-pipelines-preflight-common-operator-registry-cache-fix-commands.sh
  ci-operator/step-registry/operator-pipelines/preflight-preprod/operator-registry-cache-fix/operator-pipelines-preflight-preprod-operator-registry-cache-fix-commands.sh
  ci-operator/step-registry/operator-pipelines/preflight-prod/operator-registry-cache-fix/operator-pipelines-preflight-prod-operator-registry-cache-fix-commands.sh
Labels: lgtm, approved, rehearsals-ack

#50441 stackrox: move nightlies and x.y to 4-12
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies__ocp-4-12.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-x.y__ocp-4-12.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-nightlies-postsubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-x.y-postsubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-x.y-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#50309 MULTIARCH-4554: Removing legacy libvirt specific gather commands.
  ci-operator/step-registry/gather/libvirt/OWNERS
  ci-operator/step-registry/gather/libvirt/gather-libvirt-commands.sh
  ci-operator/step-registry/gather/libvirt/gather-libvirt-ref.metadata.json
  ci-operator/step-registry/gather/libvirt/gather-libvirt-ref.yaml
  ci-operator/step-registry/ipi/libvirt/post/ipi-libvirt-post-chain.yaml
  ci-operator/step-registry/upi/libvirt/heterogeneous/post/upi-libvirt-heterogeneous-post-chain.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#50501 `gangway`: increase initial seconds on probes to avoid crashloop
  clusters/app.ci/prow/03_deployment/gangway.yaml
Labels: lgtm, approved, rehearsals-ack

#50497 [ART-9247] payload fips check step
  ci-operator/step-registry/openshift/release/fips/OWNERS
  ci-operator/step-registry/openshift/release/fips/openshift-release-fips-commands.sh
  ci-operator/step-registry/openshift/release/fips/openshift-release-fips-ref.metadata.json
  ci-operator/step-registry/openshift/release/fips/openshift-release-fips-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#50502 Show pods and their statuses from disk
  ci-operator/step-registry/operator-pipelines/preflight-common/operator-registry-cache-fix/operator-pipelines-preflight-common-operator-registry-cache-fix-commands.sh
  ci-operator/step-registry/operator-pipelines/preflight-preprod/operator-registry-cache-fix/operator-pipelines-preflight-preprod-operator-registry-cache-fix-commands.sh
  ci-operator/step-registry/operator-pipelines/preflight-prod/operator-registry-cache-fix/operator-pipelines-preflight-prod-operator-registry-cache-fix-commands.sh
Labels: lgtm, approved, rehearsals-ack

#50506 Stop mirroring private images to CI
  ci-operator/jobs/infra-image-mirroring.yaml
  clusters/app.ci/assets/admin_ci-images-mirror.yaml
  core-services/ci-secret-bootstrap/_config.yaml
  core-services/image-mirroring/supplemental-ci-private-images-redhat/mapping_supplemental_ci_private_images_redhat_ci
Labels: lgtm, approved, rehearsals-ack

#50508 Fix issue DPTP-3839 Fix Splunk URL
  clusters/build-clusters/common_managed/rh-logging-splunk.yaml
Labels: lgtm, approved, rehearsals-ack

#50503 DPTP-3921: Migrate supplemental ci images
  core-services/image-mirroring/_config.yaml
  core-services/image-mirroring/supplemental-ci-images/README.md
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_azure
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_chaos
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_ci
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_coreos
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_edge_infrastructure
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_logging
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_ocp
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_ocp_on_powervs
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_openshift
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_origin
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_rh_cloud_services
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_securesign
  core-services/image-mirroring/supplemental-ci-images/mapping_supplemental_ci_images_stackrox
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#50511 [CRT] Synchronizing our prow plugin config
  core-services/prow/02_config/openshift-eng/cyborg/_pluginconfig.yaml
  core-services/prow/02_config/openshift/ci-search/_pluginconfig.yaml
  core-services/prow/02_config/openshift/continuous-release-jobs/_pluginconfig.yaml
  core-services/prow/02_config/openshift/openshift-client-python/_pluginconfig.yaml
  core-services/prow/02_config/openshift/org/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#50483 stackrox: Rox 23270 nightlies ocp415 fast
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies__ocp-4-15.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-4.2__ocp-4-15.yaml
Labels: lgtm, approved, rehearsals-ack

#50241 Replace the ROSA HCP workflows for external teams
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa_hcp-4.14-nightly-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa_hcp-4.14-stable-x86-loaded-upgrade-from-4.14.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa_hcp-4.15-ec-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa_hcp-4.15-nightly-x86.yaml
  ci-operator/config/openshift/svt/openshift-svt-master__reliability-v2-rosa_hcp-4.15-nightly-x86.yaml
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__rosa-4.15-nightly.yaml
  ci-operator/step-registry/firewatch/rosa/aws/sts/hypershift/firewatch-rosa-aws-sts-hypershift-workflow.yaml
  ci-operator/step-registry/osd-ccs/fleet-manager/osd-ccs-fleet-manager-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#50518 Remove the old ROSA HCP workflows
  ci-operator/step-registry/rosa/aws/sts/hypershift/OWNERS
  ci-operator/step-registry/rosa/aws/sts/hypershift/advanced-sg/OWNERS
  ci-operator/step-registry/rosa/aws/sts/hypershift/advanced-sg/rosa-aws-sts-hypershift-advanced-sg-workflow.metadata.json
  ci-operator/step-registry/rosa/aws/sts/hypershift/advanced-sg/rosa-aws-sts-hypershift-advanced-sg-workflow.yaml
  ci-operator/step-registry/rosa/aws/sts/hypershift/advanced/OWNERS
  ci-operator/step-registry/rosa/aws/sts/hypershift/advanced/rosa-aws-sts-hypershift-advanced-workflow.metadata.json
  ci-operator/step-registry/rosa/aws/sts/hypershift/advanced/rosa-aws-sts-hypershift-advanced-workflow.yaml
  ci-operator/step-registry/rosa/aws/sts/hypershift/capi/OWNERS
  ci-operator/step-registry/rosa/aws/sts/hypershift/capi/rosa-aws-sts-hypershift-capi-workflow.metadata.json
  ci-operator/step-registry/rosa/aws/sts/hypershift/capi/rosa-aws-sts-hypershift-capi-workflow.yaml
  ci-operator/step-registry/rosa/aws/sts/hypershift/cilium/OWNERS
  ci-operator/step-registry/rosa/aws/sts/hypershift/cilium/rosa-aws-sts-hypershift-cilium-workflow.metadata.json
  ci-operator/step-registry/rosa/aws/sts/hypershift/cilium/rosa-aws-sts-hypershift-cilium-workflow.yaml
  ci-operator/step-registry/rosa/aws/sts/hypershift/deprovision/OWNERS
  ci-operator/step-registry/rosa/aws/sts/hypershift/deprovision/rosa-aws-sts-hypershift-deprovision-chain.metadata.json
  ci-operator/step-registry/rosa/aws/sts/hypershift/deprovision/rosa-aws-sts-hypershift-deprovision-chain.yaml
  ci-operator/step-registry/rosa/aws/sts/hypershift/mp/OWNERS
  ci-operator/step-registry/rosa/aws/sts/hypershift/mp/rosa-aws-sts-hypershift-mp-workflow.metadata.json
  ci-operator/step-registry/rosa/aws/sts/hypershift/mp/rosa-aws-sts-hypershift-mp-workflow.yaml
  ci-operator/step-registry/rosa/aws/sts/hypershift/private-link-sg/OWNERS
  ci-operator/step-registry/rosa/aws/sts/hypershift/private-link-sg/rosa-aws-sts-hypershift-private-link-sg-workflow.metadata.json
  ci-operator/step-registry/rosa/aws/sts/hypershift/private-link-sg/rosa-aws-sts-hypershift-private-link-sg-workflow.yaml
  ci-operator/step-registry/rosa/aws/sts/hypershift/private-link/OWNERS
  ci-operator/step-registry/rosa/aws/sts/hypershift/private-link/rosa-aws-sts-hypershift-private-link-workflow.metadata.json
  ci-operator/step-registry/rosa/aws/sts/hypershift/private-link/rosa-aws-sts-hypershift-private-link-workflow.yaml
  ci-operator/step-registry/rosa/aws/sts/hypershift/provision/OWNERS
  ci-operator/step-registry/rosa/aws/sts/hypershift/provision/rosa-aws-sts-hypershift-provision-chain.metadata.json
  ci-operator/step-registry/rosa/aws/sts/hypershift/provision/rosa-aws-sts-hypershift-provision-chain.yaml
  ci-operator/step-registry/rosa/aws/sts/hypershift/rosa-aws-sts-hypershift-workflow.metadata.json
  ci-operator/step-registry/rosa/aws/sts/hypershift/rosa-aws-sts-hypershift-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#50410 Add MCE publish jobs for release-4.16/MCE 2.6
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.16__mce.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.16-postsubmits.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.16-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#50500 MULTIARCH-4516: change machine type to s922
  ci-operator/step-registry/upi/install/powervs/cluster/upi-install-powervs-cluster-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#50169 OCPQE-20704: [HyperShift QE] Azure CI e2e
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/ovn/hypershift/provision/cucushift-installer-rehearse-azure-ipi-ovn-hypershift-provision-chain.yaml
  ci-operator/step-registry/hypershift/azure/create/hypershift-azure-create-chain.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#50406 OCPQE-20584: some enhancements on step "osd-ccs-cluster-provision-gcp"
  ci-operator/step-registry/osd-ccs/cluster/deprovision/osd-ccs-cluster-deprovision-commands.sh
  ci-operator/step-registry/osd-ccs/cluster/provision/gcp/osd-ccs-cluster-provision-gcp-commands.sh
  ci-operator/step-registry/osd-ccs/cluster/provision/gcp/osd-ccs-cluster-provision-gcp-ref.yaml
  ci-operator/step-registry/osd-ccs/gcp/osd-ccs-gcp-workflow.yaml
  ci-operator/step-registry/osd-ccs/gcp/xpn/osd-ccs-gcp-xpn-workflow.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#50466 OCPQE-20709: re-export PATH to ensure extracted oc/ccoctl clients can be loaded correctly
  ci-operator/step-registry/cucushift/chainupgrade/toimage/cucushift-chainupgrade-toimage-commands.sh
  ci-operator/step-registry/cucushift/ota/postupgrade/cucushift-ota-postupgrade-commands.sh
  ci-operator/step-registry/cucushift/ota/preupgrade/cucushift-ota-preupgrade-commands.sh
  ci-operator/step-registry/cucushift/upgrade/check-not-recommended/cucushift-upgrade-check-not-recommended-commands.sh
  ci-operator/step-registry/cucushift/upgrade/mirror-images/by-oc-adm/cucushift-upgrade-mirror-images-by-oc-adm-commands.sh
  ci-operator/step-registry/cucushift/upgrade/setchannel/cucushift-upgrade-setchannel-commands.sh
  ci-operator/step-registry/cucushift/upgrade/toimage/cucushift-upgrade-toimage-commands.sh
  ci-operator/step-registry/cucushift/upgrade/toversion/cucushift-upgrade-toversion-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#50516 Add quay 3.11 testing on OCP 4.16
  ci-operator/config/quay/quay-tests/quay-quay-tests-master.yaml
  ci-operator/jobs/quay/quay-tests/quay-quay-tests-master-periodics.yaml
  ci-operator/jobs/quay/quay-tests/quay-quay-tests-master-postsubmits.yaml
  ci-operator/jobs/quay/quay-tests/quay-quay-tests-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#50519 make sure gather is running after unregister pac
  ci-operator/step-registry/redhat-appstudio/rhtap-installer/redhat-appstudio-rhtap-installer-workflow.yaml
  ci-operator/step-registry/redhat-appstudio/rhtap-installer/reinstall-rhtap/redhat-appstudio-rhtap-installer-reinstall-rhtap-commands.sh
Labels: lgtm, approved, rehearsals-ack

#50521 HyperShift QE: remove 4.13 jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-stable.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#50515 Add more JVM build service skips
  ci-operator/config/redhat-appstudio/jvm-build-service/redhat-appstudio-jvm-build-service-main.yaml
  ci-operator/jobs/redhat-appstudio/jvm-build-service/redhat-appstudio-jvm-build-service-main-presubmits.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#50529 WRKLDS-1067: Use base-rhel9 image and ci specific Dockerfile
  ci-operator/config/openshift/cli-manager-operator/openshift-cli-manager-operator-main.yaml
  ci-operator/config/openshift/cli-manager-operator/openshift-cli-manager-operator-release-4.16.yaml
  ci-operator/config/openshift/cli-manager-operator/openshift-cli-manager-operator-release-4.17.yaml
  ci-operator/config/openshift/cli-manager/openshift-cli-manager-main.yaml
  ci-operator/config/openshift/cli-manager/openshift-cli-manager-release-4.16.yaml
  ci-operator/config/openshift/cli-manager/openshift-cli-manager-release-4.17.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#50468 OCPBUGS-20097: Update oc master configuration to RHEL9
  ci-operator/config/openshift/oc/openshift-oc-master.yaml
  ci-operator/config/openshift/oc/openshift-oc-release-4.16.yaml
  ci-operator/config/openshift/oc/openshift-oc-release-4.17.yaml
Labels: lgtm, approved, jira/valid-bug, rehearsals-ack, jira/valid-reference

#50527 nvidia-ci: Renaming Dockerfile --> Containerfile.
  ci-operator/config/rh-ecosystem-edge/nvidia-ci/rh-ecosystem-edge-nvidia-ci-main.yaml
Labels: lgtm, approved, rehearsals-ack

#50339 use the index image as the cache since OCP4.15
  ci-operator/step-registry/enable-qe-catalogsource/disconnected/enable-qe-catalogsource-disconnected-commands.sh
  ci-operator/step-registry/enable-qe-catalogsource/enable-qe-catalogsource-commands.sh
  ci-operator/step-registry/enable-qe-catalogsource/logging/enable-qe-catalogsource-logging-commands.sh
Labels: lgtm, approved, rehearsals-ack

#50482 Do not override the use of ART base images
  ci-operator/config/openshift/baremetal-runtimecfg/openshift-baremetal-runtimecfg-release-4.16.yaml
  ci-operator/config/openshift/baremetal-runtimecfg/openshift-baremetal-runtimecfg-release-4.17.yaml
Labels: lgtm, approved, rehearsals-ack

#50490 Reverting reverted "OCPQE-19493: Change facility to metro""
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__arm64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__arm64-nightly-4.15-upgrade-from-stable-4.11.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__arm64-nightly.yaml
  ci-operator/step-registry/baremetalds/packet/check/baremetalds-packet-check-commands.sh
  ci-operator/step-registry/baremetalds/packet/setup/baremetalds-packet-setup-commands.sh
  ci-operator/step-registry/baremetalds/packet/setup/baremetalds-packet-setup-ref.yaml
  ci-operator/step-registry/baremetalds/packet/teardown/baremetalds-packet-teardown-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#50414 move waiting cluster ready to a step
  ci-operator/step-registry/rosa/aws/sts/hcp/byo-kms-oidc-auditlog/rosa-aws-sts-hcp-byo-kms-oidc-auditlog-workflow.yaml
  ci-operator/step-registry/rosa/aws/sts/hcp/cilium/rosa-aws-sts-hcp-cilium-workflow.yaml
  ci-operator/step-registry/rosa/aws/sts/hcp/mp/rosa-aws-sts-hcp-mp-workflow.yaml
  ci-operator/step-registry/rosa/aws/sts/hcp/private-proxy/rosa-aws-sts-hcp-private-proxy-workflow.yaml
  ci-operator/step-registry/rosa/aws/sts/hcp/provision/rosa-aws-sts-hcp-provision-chain.yaml
  ci-operator/step-registry/rosa/aws/sts/hcp/rosa-aws-sts-hcp-workflow.yaml
  ci-operator/step-registry/rosa/aws/sts/hcp/security-group/private/rosa-aws-sts-hcp-security-group-private-workflow.yaml
  ci-operator/step-registry/rosa/aws/sts/hcp/security-group/rosa-aws-sts-hcp-security-group-workflow.yaml
  ci-operator/step-registry/rosa/cluster/notify/error/rosa-cluster-notify-error-commands.sh
  ci-operator/step-registry/rosa/cluster/provision/rosa-cluster-provision-chain.yaml
  ci-operator/step-registry/rosa/cluster/provision/rosa-cluster-provision-commands.sh
  ci-operator/step-registry/rosa/cluster/provision/rosa-cluster-provision-ref.yaml
  ci-operator/step-registry/rosa/cluster/wait-ready/cluster/OWNERS
  ci-operator/step-registry/rosa/cluster/wait-ready/cluster/rosa-cluster-wait-ready-cluster-commands.sh
  ci-operator/step-registry/rosa/cluster/wait-ready/cluster/rosa-cluster-wait-ready-cluster-ref.metadata.json
  ci-operator/step-registry/rosa/cluster/wait-ready/cluster/rosa-cluster-wait-ready-cluster-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#50499 fix: increase timeout while running run bundle command
  ci-operator/config/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-tech-preview.yaml
  ci-operator/config/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-tech-preview__ocp4.13-periodic.yaml
  ci-operator/config/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-tech-preview__ocp4.14-periodic.yaml
  ci-operator/config/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-tech-preview__post-submit.yaml
  ci-operator/config/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-v1alpha1.yaml
  ci-operator/config/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-v1alpha1__ocp4.14-periodic.yaml
  ci-operator/config/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-v1alpha1__ocp4.15-periodic.yaml
  ci-operator/config/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-v1alpha1__post-submit.yaml
Labels: lgtm, approved, rehearsals-ack

#50538 NO-JIRA: Separate tools image from cli image
  ci-operator/config/openshift/oc/openshift-oc-master.yaml
  ci-operator/config/openshift/oc/openshift-oc-release-4.16.yaml
  ci-operator/config/openshift/oc/openshift-oc-release-4.17.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#50539 NO-JIRA: Add base image and use explicit tools Dockerfile
  ci-operator/config/openshift/oc/openshift-oc-master.yaml
  ci-operator/config/openshift/oc/openshift-oc-release-4.16.yaml
  ci-operator/config/openshift/oc/openshift-oc-release-4.17.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#47941 Added rhacs-docs branches
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-rhacs-docs-4.3.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-rhacs-docs-4.4.yaml
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-rhacs-docs-main.yaml
  ci-operator/jobs/openshift/openshift-docs/openshift-openshift-docs-rhacs-docs-4.3-presubmits.yaml
  ci-operator/jobs/openshift/openshift-docs/openshift-openshift-docs-rhacs-docs-4.4-presubmits.yaml
  ci-operator/jobs/openshift/openshift-docs/openshift-openshift-docs-rhacs-docs-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#50543 NO-JIRA: Use dockerfile_path in tools image
  ci-operator/config/openshift/oc/openshift-oc-master.yaml
  ci-operator/config/openshift/oc/openshift-oc-release-4.16.yaml
  ci-operator/config/openshift/oc/openshift-oc-release-4.17.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#50260 OSSM maistra use own profile
  ci-operator/config/maistra/header-append-filter/maistra-header-append-filter-maistra-2.2.yaml
  ci-operator/config/maistra/header-append-filter/maistra-header-append-filter-maistra-2.3.yaml
  ci-operator/config/maistra/header-append-filter/maistra-header-append-filter-maistra-2.4.yaml
  ci-operator/config/maistra/istio-images-centos/maistra-istio-images-centos-maistra-2.2.yaml
  ci-operator/config/maistra/istio-images-centos/maistra-istio-images-centos-maistra-2.3.yaml
  ci-operator/config/maistra/istio-images-centos/maistra-istio-images-centos-maistra-2.4.yaml
  ci-operator/config/maistra/test-infra/maistra-test-infra-main.yaml
  ci-operator/jobs/maistra/header-append-filter/maistra-header-append-filter-maistra-2.2-postsubmits.yaml
  ci-operator/jobs/maistra/header-append-filter/maistra-header-append-filter-maistra-2.2-presubmits.yaml
  ci-operator/jobs/maistra/header-append-filter/maistra-header-append-filter-maistra-2.3-postsubmits.yaml
  ci-operator/jobs/maistra/header-append-filter/maistra-header-append-filter-maistra-2.3-presubmits.yaml
  ci-operator/jobs/maistra/header-append-filter/maistra-header-append-filter-maistra-2.4-postsubmits.yaml
  ci-operator/jobs/maistra/header-append-filter/maistra-header-append-filter-maistra-2.4-presubmits.yaml
  ci-operator/jobs/maistra/istio-images-centos/maistra-istio-images-centos-maistra-2.2-presubmits.yaml
  ci-operator/jobs/maistra/istio-images-centos/maistra-istio-images-centos-maistra-2.3-periodics.yaml
  ci-operator/jobs/maistra/istio-images-centos/maistra-istio-images-centos-maistra-2.3-presubmits.yaml
  ci-operator/jobs/maistra/istio-images-centos/maistra-istio-images-centos-maistra-2.4-periodics.yaml
  ci-operator/jobs/maistra/istio-images-centos/maistra-istio-images-centos-maistra-2.4-presubmits.yaml
  ci-operator/jobs/maistra/test-infra/maistra-test-infra-main-postsubmits.yaml
  ci-operator/jobs/maistra/test-infra/maistra-test-infra-main-presubmits.yaml
  ci-operator/step-registry/servicemesh/istio/e2e/claim/OWNERS
  ci-operator/step-registry/servicemesh/istio/e2e/claim/servicemesh-istio-e2e-claim-workflow.metadata.json
  ci-operator/step-registry/servicemesh/istio/e2e/claim/servicemesh-istio-e2e-claim-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#50505 DPTP-3921 remove the periodic for supplemental ci image mirroring
  ci-operator/jobs/infra-image-mirroring.yaml
  docs/dptp-triage-sop/infrastructure-jobs.md
Labels: lgtm, approved, rehearsals-ack

#50351 Remove maistra/istio jobs for maistra-3.0 branch
  ci-operator/config/maistra/istio/maistra-istio-maistra-3.0.yaml
  ci-operator/config/maistra/test-infra/maistra-test-infra-main.yaml
  ci-operator/jobs/maistra/istio/maistra-istio-maistra-3.0-postsubmits.yaml
  ci-operator/jobs/maistra/istio/maistra-istio-maistra-3.0-presubmits.yaml
  ci-operator/jobs/maistra/test-infra/maistra-test-infra-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#50549 OLS: trust red-hat-konflux in lightspeed-* repos
  core-services/prow/02_config/openshift/lightspeed-console/_pluginconfig.yaml
  core-services/prow/02_config/openshift/lightspeed-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/lightspeed-rag-content/_pluginconfig.yaml
  core-services/prow/02_config/openshift/lightspeed-service/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#50335 ADO CI to conditionally run PKO tests
  ci-operator/config/openshift/addon-operator/openshift-addon-operator-main.yaml
  ci-operator/jobs/openshift/addon-operator/openshift-addon-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#50546 Remove istio-operator 3.0 jobs
  ci-operator/config/maistra/istio-operator/maistra-istio-operator-maistra-3.0.yaml
  ci-operator/jobs/maistra/istio-operator/maistra-istio-operator-maistra-3.0-periodics.yaml
  ci-operator/jobs/maistra/istio-operator/maistra-istio-operator-maistra-3.0-presubmits.yaml
  core-services/prow/02_config/maistra/istio-operator/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#50551 setting rhoe-cluster-pool for ocp 4.15 east-2 to size back to 5
  clusters/hive/pools/rh-openshift-ecosystem/rhoe-ocp-4-15-amd64-aws-us-east-2_clusterpool.yaml
Labels: lgtm, approved, rehearsals-ack

#48942 [CRC] Add security scanning for openshift local
  ci-operator/config/crc-org/crc/crc-org-crc-main.yaml
  ci-operator/jobs/crc-org/crc/crc-org-crc-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#47225 Adding pod network chaos to prow
  ci-operator/step-registry/redhat-chaos/krkn-hub-tests/redhat-chaos-krkn-hub-tests-chain.yaml
  ci-operator/step-registry/redhat-chaos/pod-network-chaos/OWNERS
  ci-operator/step-registry/redhat-chaos/pod-network-chaos/redhat-chaos-pod-network-chaos-commands.sh
  ci-operator/step-registry/redhat-chaos/pod-network-chaos/redhat-chaos-pod-network-chaos-ref.metadata.json
  ci-operator/step-registry/redhat-chaos/pod-network-chaos/redhat-chaos-pod-network-chaos-ref.yaml
  ci-operator/step-registry/redhat-chaos/pod-network-chaos/redhat-chaos-pod-network-chaos-workflow.metadata.json
  ci-operator/step-registry/redhat-chaos/pod-network-chaos/redhat-chaos-pod-network-chaos-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#50564 Replace `pre-main` with `main` branch in sail-operator
  ci-operator/config/openshift-service-mesh/sail-operator/openshift-service-mesh-sail-operator-main.yaml
  ci-operator/jobs/openshift-service-mesh/sail-operator/openshift-service-mesh-sail-operator-main-periodics.yaml
  ci-operator/jobs/openshift-service-mesh/sail-operator/openshift-service-mesh-sail-operator-main-presubmits.yaml
  core-services/prow/02_config/openshift-service-mesh/sail-operator/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#49963 Update operator installation from iib
  ci-operator/config/CSPI-QE/MSI/CSPI-QE-MSI-rhoai-operator-interop__v4.14-IIB.yaml
  ci-operator/config/CSPI-QE/MSI/CSPI-QE-MSI-rhoai-operator-interop__v4.14-hypershift-IIB.yaml
  ci-operator/step-registry/operator/install/operator-install-commands.sh
  ci-operator/step-registry/operator/install/operator-install-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#50566 rhtap: Update pipeline task name
  ci-operator/step-registry/redhat-appstudio/rhtap-installer/install-rhtap/redhat-appstudio-rhtap-installer-install-rhtap-commands.sh
  ci-operator/step-registry/redhat-appstudio/rhtap-installer/reinstall-rhtap/redhat-appstudio-rhtap-installer-reinstall-rhtap-commands.sh
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#50570 Stop mirroring registry.fedoraproject.org/fedora:latest
  core-services/image-mirroring/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#50568 Add 0.12.0 for odh-model-controller.
  ci-operator/config/opendatahub-io/odh-model-controller/opendatahub-io-odh-model-controller-release-0.11.0.yaml
  ci-operator/config/opendatahub-io/odh-model-controller/opendatahub-io-odh-model-controller-release-0.12.0.yaml
  ci-operator/jobs/opendatahub-io/odh-model-controller/opendatahub-io-odh-model-controller-release-0.12.0-postsubmits.yaml
  ci-operator/jobs/opendatahub-io/odh-model-controller/opendatahub-io-odh-model-controller-release-0.12.0-presubmits.yaml
  ci-operator/jobs/opendatahub-io/odh-model-controller/opendatahub-io-odh-model-controller-release-v0.11.0-alpha-postsubmits.yaml
  ci-operator/jobs/opendatahub-io/odh-model-controller/opendatahub-io-odh-model-controller-release-v0.11.0-alpha-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#50316 Create RHEL 9.4 beta content mirror for 4.16
  clusters/build-clusters/common/release-controller/rpms-ocp-4.16.yaml
  core-services/release-controller/_repos/ocp-4.16-rhel94.repo
Labels: lgtm, approved, rehearsals-ack

#50572 Ignore src images
  core-services/image-mirroring/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#50571 [LPTOCPCI-1235] Do not run re-trigger on rehearsal jobs
  ci-operator/step-registry/job-re-trigger/job-re-trigger-commands.sh
Labels: lgtm, approved, rehearsals-ack

#50008 [HyperShift KubeVirt] Add new optional Azure lane
  ci-operator/config/openshift-priv/cluster-api-provider-kubevirt/openshift-priv-cluster-api-provider-kubevirt-main.yaml
  ci-operator/config/openshift-priv/cluster-api-provider-kubevirt/openshift-priv-cluster-api-provider-kubevirt-release-4.14.yaml
  ci-operator/config/openshift-priv/cluster-api-provider-kubevirt/openshift-priv-cluster-api-provider-kubevirt-release-4.15.yaml
  ci-operator/config/openshift-priv/cluster-api-provider-kubevirt/openshift-priv-cluster-api-provider-kubevirt-release-4.16.yaml
  ci-operator/config/openshift-priv/cluster-api-provider-kubevirt/openshift-priv-cluster-api-provider-kubevirt-release-4.17.yaml
  ci-operator/config/openshift-priv/hypershift/openshift-priv-hypershift-main.yaml
  ci-operator/config/openshift-priv/hypershift/openshift-priv-hypershift-release-4.13.yaml
  ci-operator/config/openshift-priv/hypershift/openshift-priv-hypershift-release-4.14.yaml
  ci-operator/config/openshift-priv/hypershift/openshift-priv-hypershift-release-4.15.yaml
  ci-operator/config/openshift-priv/hypershift/openshift-priv-hypershift-release-4.16.yaml
  ci-operator/config/openshift-priv/hypershift/openshift-priv-hypershift-release-4.17.yaml
  ci-operator/config/openshift/cluster-api-provider-kubevirt/openshift-cluster-api-provider-kubevirt-main.yaml
  ci-operator/config/openshift/cluster-api-provider-kubevirt/openshift-cluster-api-provider-kubevirt-release-4.14.yaml
  ci-operator/config/openshift/cluster-api-provider-kubevirt/openshift-cluster-api-provider-kubevirt-release-4.15.yaml
  ci-operator/config/openshift/cluster-api-provider-kubevirt/openshift-cluster-api-provider-kubevirt-release-4.16.yaml
  ci-operator/config/openshift/cluster-api-provider-kubevirt/openshift-cluster-api-provider-kubevirt-release-4.17.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-main.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.13.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.14.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.15.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.16.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.17.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-main-presubmits.yaml
  ci-operator/step-registry/hypershift/kubevirt/e2e-aws/OWNERS
  ci-operator/step-registry/hypershift/kubevirt/e2e-aws/capk/OWNERS
  ci-operator/step-registry/hypershift/kubevirt/e2e-aws/capk/hypershift-kubevirt-e2e-aws-capk-workflow.metadata.json
  ci-operator/step-registry/hypershift/kubevirt/e2e-aws/capk/hypershift-kubevirt-e2e-aws-capk-workflow.yaml
  ci-operator/step-registry/hypershift/kubevirt/e2e-aws/hypershift-kubevirt-e2e-aws-workflow.metadata.json
  ci-operator/step-registry/hypershift/kubevirt/e2e-aws/hypershift-kubevirt-e2e-aws-workflow.yaml
  ci-operator/step-registry/hypershift/kubevirt/e2e-azure/OWNERS
  ci-operator/step-registry/hypershift/kubevirt/e2e-azure/capk/OWNERS
  ci-operator/step-registry/hypershift/kubevirt/e2e-azure/capk/hypershift-kubevirt-e2e-azure-capk-workflow.metadata.json
  ci-operator/step-registry/hypershift/kubevirt/e2e-azure/capk/hypershift-kubevirt-e2e-azure-capk-workflow.yaml
  ci-operator/step-registry/hypershift/kubevirt/e2e-azure/hypershift-kubevirt-e2e-azure-workflow.metadata.json
  ci-operator/step-registry/hypershift/kubevirt/e2e-azure/hypershift-kubevirt-e2e-azure-workflow.yaml
  ci-operator/step-registry/hypershift/kubevirt/install/odf/hypershift-kubevirt-install-odf-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#50580 fix unbound variable issue
  ci-operator/step-registry/rosa/cluster/provision/rosa-cluster-provision-commands.sh
Labels: lgtm, approved, rehearsals-ack

#50255 Add Install-operators-verify ref
  ci-operator/step-registry/acm/ipi/aws/acm-ipi-aws-workflow.yaml
  ci-operator/step-registry/firewatch/ipi/aws/firewatch-ipi-aws-workflow.yaml
  ci-operator/step-registry/install-operators/verify/OWNERS
  ci-operator/step-registry/install-operators/verify/install-operators-verify-commands.sh
  ci-operator/step-registry/install-operators/verify/install-operators-verify-ref.metadata.json
  ci-operator/step-registry/install-operators/verify/install-operators-verify-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#50584 fix install cmds for ocs-ooperator release-4.16
  ci-operator/config/red-hat-storage/ocs-operator/red-hat-storage-ocs-operator-release-4.16.yaml
Labels: lgtm, approved, rehearsals-ack

#50589 rhtap: Update pipeline task name
  ci-operator/step-registry/redhat-appstudio/rhtap-installer/install-rhtap/redhat-appstudio-rhtap-installer-install-rhtap-commands.sh
  ci-operator/step-registry/redhat-appstudio/rhtap-installer/reinstall-rhtap/redhat-appstudio-rhtap-installer-reinstall-rhtap-commands.sh
Labels: lgtm, approved, rehearsals-ack

#50578 rhtap: Update pipeline task name
  ci-operator/step-registry/redhat-appstudio/rhtap-installer/install-rhtap/redhat-appstudio-rhtap-installer-install-rhtap-commands.sh
  ci-operator/step-registry/redhat-appstudio/rhtap-installer/reinstall-rhtap/redhat-appstudio-rhtap-installer-reinstall-rhtap-commands.sh
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#50560 Rollout of Retriggering Support for Interop scenarios, phase 5
  ci-operator/config/jws-qe/interop-ocp-ci/jws-qe-interop-ocp-ci-main__ocp-4.16-lp-interop.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.16-lp-interop.yaml
  ci-operator/config/redhat-developer/devspaces-interop-tests/redhat-developer-devspaces-interop-tests-main__devspaces-ocp4.16-lp-interop.yaml
  ci-operator/config/redhat-developer/helm/redhat-developer-helm-release-3.11__helm-ocp4.16-lp-interop.yaml
  ci-operator/config/skupperproject/skupper-openshift-smoke-test-image/skupperproject-skupper-openshift-smoke-test-image-main__service-interconnect-ocp4.16-lp-interop.yaml
Labels: lgtm, approved, rehearsals-ack

#50565 albo: e2e on rosa - use stable channel to unblock CI
  ci-operator/config/openshift/aws-load-balancer-operator/openshift-aws-load-balancer-operator-main.yaml
Labels: lgtm, approved, rehearsals-ack

#50586 telco5g: Wait for SNO cluster to be finished
  ci-operator/step-registry/telco5g/sno-setup/telco5g-sno-setup-commands.sh
Labels: lgtm, approved, rehearsals-ack

#50594 Medik8s branch protection
  ci-operator/config/medik8s/common/new-release.sh
  ci-operator/config/medik8s/node-healthcheck-operator/README.txt
  core-services/prow/02_config/medik8s/.github/OWNERS
  core-services/prow/02_config/medik8s/.github/_pluginconfig.yaml
  core-services/prow/02_config/medik8s/.github/_prowconfig.yaml
  core-services/prow/02_config/medik8s/_pluginconfig.yaml
  core-services/prow/02_config/medik8s/_prowconfig.yaml
  core-services/prow/02_config/medik8s/common/OWNERS
  core-services/prow/02_config/medik8s/common/_pluginconfig.yaml
  core-services/prow/02_config/medik8s/common/_prowconfig.yaml
  core-services/prow/02_config/medik8s/customized-user-remediation/OWNERS
  core-services/prow/02_config/medik8s/customized-user-remediation/_pluginconfig.yaml
  core-services/prow/02_config/medik8s/customized-user-remediation/_prowconfig.yaml
  core-services/prow/02_config/medik8s/fence-agents-remediation/OWNERS
  core-services/prow/02_config/medik8s/fence-agents-remediation/_pluginconfig.yaml
  core-services/prow/02_config/medik8s/fence-agents-remediation/_prowconfig.yaml
  core-services/prow/02_config/medik8s/ha-sno/OWNERS
  core-services/prow/02_config/medik8s/ha-sno/_pluginconfig.yaml
  core-services/prow/02_config/medik8s/ha-sno/_prowconfig.yaml
  core-services/prow/02_config/medik8s/machine-deletion-remediation/OWNERS
  core-services/prow/02_config/medik8s/machine-deletion-remediation/_pluginconfig.yaml
  core-services/prow/02_config/medik8s/machine-deletion-remediation/_prowconfig.yaml
  core-services/prow/02_config/medik8s/must-gather/OWNERS
  core-services/prow/02_config/medik8s/must-gather/_prowconfig.yaml
  core-services/prow/02_config/medik8s/node-healthcheck-operator/_pluginconfig.yaml
  core-services/prow/02_config/medik8s/node-healthcheck-operator/_prowconfig.yaml
  core-services/prow/02_config/medik8s/node-maintenance-operator/OWNERS
  core-services/prow/02_config/medik8s/node-maintenance-operator/_pluginconfig.yaml
  core-services/prow/02_config/medik8s/node-maintenance-operator/_prowconfig.yaml
  core-services/prow/02_config/medik8s/node-remediation-console/_pluginconfig.yaml
  core-services/prow/02_config/medik8s/node-remediation-console/_prowconfig.yaml
  core-services/prow/02_config/medik8s/poison-pill/OWNERS
  core-services/prow/02_config/medik8s/poison-pill/_pluginconfig.yaml
  core-services/prow/02_config/medik8s/poison-pill/_prowconfig.yaml
  core-services/prow/02_config/medik8s/self-node-remediation/OWNERS
  core-services/prow/02_config/medik8s/self-node-remediation/_pluginconfig.yaml
  core-services/prow/02_config/medik8s/self-node-remediation/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#50598 Kubevirt/HyperShift/Azure - Don't run the lane automatically - fix
  ci-operator/config/openshift/hypershift/openshift-hypershift-main.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#50562 add in operator-registry-cache-fix as pre step in openshift-preflight
  ci-operator/config/redhat-openshift-ecosystem/openshift-preflight/redhat-openshift-ecosystem-openshift-preflight-main__4.15.yaml
Labels: lgtm, approved, rehearsals-ack

#50602 govulncheck: bump go version to 1.22.2
  clusters/app.ci/supplemental-ci-images/crt/govulncheck.yaml
Labels: lgtm, approved, rehearsals-ack

#50387 OCPEDGE-924: feat: added dynamic seed versioning
  ci-operator/config/openshift-kni/lifecycle-agent/openshift-kni-lifecycle-agent-main.yaml
  ci-operator/config/openshift-kni/lifecycle-agent/openshift-kni-lifecycle-agent-main__periodics.yaml
  ci-operator/jobs/openshift-kni/lifecycle-agent/openshift-kni-lifecycle-agent-main-periodics.yaml
  ci-operator/step-registry/openshift/image-based/upgrade/recipient/presubmit/openshift-image-based-upgrade-recipient-presubmit-commands.sh
  ci-operator/step-registry/openshift/image-based/upgrade/recipient/presubmit/openshift-image-based-upgrade-recipient-presubmit-ref.yaml
  ci-operator/step-registry/openshift/image-based/upgrade/seed/create/periodic/openshift-image-based-upgrade-seed-create-periodic-commands.sh
  ci-operator/step-registry/openshift/image-based/upgrade/seed/create/periodic/openshift-image-based-upgrade-seed-create-periodic-ref.yaml
  ci-operator/step-registry/openshift/image-based/upgrade/seed/create/presubmit/openshift-image-based-upgrade-seed-create-presubmit-commands.sh
  ci-operator/step-registry/openshift/image-based/upgrade/seed/create/presubmit/openshift-image-based-upgrade-seed-create-presubmit-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#50603 GitOps | Add install config for 4.15
  clusters/hive/pools/gitops/gitops-install-config-4.15.yaml
  clusters/hive/pools/gitops/gitops-ocp-4-15-0-amd64-aws-us-east-2_clusterpool.yaml
Labels: lgtm, approved, rehearsals-ack

#50607 rhtap: Update pipeline task name
  ci-operator/step-registry/redhat-appstudio/rhtap-installer/install-rhtap/redhat-appstudio-rhtap-installer-install-rhtap-commands.sh
  ci-operator/step-registry/redhat-appstudio/rhtap-installer/reinstall-rhtap/redhat-appstudio-rhtap-installer-reinstall-rhtap-commands.sh
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#50199 Vboulos acm210 ocp4.16
  ci-operator/config/stolostron/policy-collection/stolostron-policy-collection-main__opp-ocp4.14-interop.yaml
  ci-operator/config/stolostron/policy-collection/stolostron-policy-collection-main__opp-ocp4.16-interop.yaml
  ci-operator/jobs/stolostron/policy-collection/stolostron-policy-collection-main-periodics.yaml
  ci-operator/jobs/stolostron/policy-collection/stolostron-policy-collection-main-presubmits.yaml
  ci-operator/step-registry/acm/must-gather/acm-must-gather-commands.sh
  ci-operator/step-registry/acm/policies/openshift-plus-setup/acm-policies-openshift-plus-setup-commands.sh
  ci-operator/step-registry/acm/tests/clc-create/acm-tests-clc-create-commands.sh
Labels: lgtm, approved, rehearsals-ack

#50609 Replace b04 with b09
  core-services/prow/02_config/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#50614 installer: altinfra: make aws jobs truly optional
  ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#50597 Bump timeout of metal-ipi serial jobs
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.16.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#50478 Update byoip allocation step to use ci-operator boskos lease feature
  ci-operator/step-registry/ipi/conf/aws/byo-ipv4-pool-public/ipi-conf-aws-byo-ipv4-pool-public-commands.sh
Labels: lgtm, approved, rehearsals-ack

#50605 OCPEDGE-926: add a configurable recert image pullspec
  ci-operator/step-registry/openshift/image-based/upgrade/recipient/presubmit/openshift-image-based-upgrade-recipient-presubmit-commands.sh
  ci-operator/step-registry/openshift/image-based/upgrade/seed/create/periodic/openshift-image-based-upgrade-seed-create-periodic-commands.sh
  ci-operator/step-registry/openshift/image-based/upgrade/seed/create/periodic/openshift-image-based-upgrade-seed-create-periodic-ref.yaml
  ci-operator/step-registry/openshift/image-based/upgrade/seed/create/presubmit/openshift-image-based-upgrade-seed-create-presubmit-commands.sh
  ci-operator/step-registry/openshift/image-based/upgrade/seed/create/presubmit/openshift-image-based-upgrade-seed-create-presubmit-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#50596 Use `make test` for functional tests
  ci-operator/config/openstack-k8s-operators/openstack-baremetal-operator/openstack-k8s-operators-openstack-baremetal-operator-main.yaml
  ci-operator/jobs/openstack-k8s-operators/openstack-baremetal-operator/openstack-k8s-operators-openstack-baremetal-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#50604 [CVP-4073]: Slightly scale back cluster pool sizes and running count
  clusters/hive/pools/cvp/cvp-fips-ocp-4-10-amd64-aws-eu-west-1_clusterpool.yaml
  clusters/hive/pools/cvp/cvp-fips-ocp-4-11-amd64-aws-eu-west-2_clusterpool.yaml
  clusters/hive/pools/cvp/cvp-fips-ocp-4-12-amd64-aws-eu-west-3_clusterpool.yaml
  clusters/hive/pools/cvp/cvp-fips-ocp-4-13-amd64-aws-eu-central-1_clusterpool.yaml
  clusters/hive/pools/cvp/cvp-fips-ocp-4-14-amd64-aws-eu-north-1_clusterpool.yaml
  clusters/hive/pools/cvp/cvp-fips-ocp-4-15-amd64-aws-eu-west-1_clusterpool.yaml
  clusters/hive/pools/cvp/cvp-fips-ocp-4-16-amd64-aws-us-west-1_clusterpool.yaml
  clusters/hive/pools/cvp/cvp-ocp-4-10-amd64-aws-eu-west-1_clusterpool.yaml
  clusters/hive/pools/cvp/cvp-ocp-4-11-amd64-aws-eu-west-2_clusterpool.yaml
  clusters/hive/pools/cvp/cvp-ocp-4-12-amd64-aws-eu-west-3_clusterpool.yaml
  clusters/hive/pools/cvp/cvp-ocp-4-13-amd64-aws-eu-central-1_clusterpool.yaml
  clusters/hive/pools/cvp/cvp-ocp-4-14-amd64-aws-eu-north-1_clusterpool.yaml
  clusters/hive/pools/cvp/cvp-ocp-4-6-amd64-aws-us-west-1_clusterpool.yaml
  clusters/hive/pools/cvp/cvp-ocp-4-7-amd64-aws-us-east-1_clusterpool.yaml
  clusters/hive/pools/cvp/cvp-ocp-4-8-amd64-aws-us-east-2_clusterpool.yaml
  clusters/hive/pools/cvp/cvp-ocp-4-9-amd64-aws-us-west-2_clusterpool.yaml
Labels: lgtm, approved, rehearsals-ack

#50622 Enable auto merge for Knative Backstage plugins
  core-services/prow/02_config/openshift-knative/backstage-plugins/OWNERS
  core-services/prow/02_config/openshift-knative/backstage-plugins/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#50600 ofcir acquire cs9 user
  ci-operator/step-registry/ofcir/acquire/ofcir-acquire-commands.sh
Labels: lgtm, approved, rehearsals-ack

#50628 FIX: Adding $JOB_NAME to openshift-docs comments step
  ci-operator/step-registry/openshift-docs/preview-comment-pages/openshift-docs-preview-comment-pages-commands.sh
Labels: lgtm, approved, rehearsals-ack

#50576 remove skip_on_success
  ci-operator/step-registry/redhat-appstudio/rhtap-installer/OWNERS
  ci-operator/step-registry/redhat-appstudio/rhtap-installer/cluster-bot/redhat-appstudio-rhtap-installer-cluster-bot-workflow.yaml
  ci-operator/step-registry/redhat-appstudio/rhtap-installer/redhat-appstudio-rhtap-installer-workflow.metadata.json
  ci-operator/step-registry/redhat-appstudio/rhtap-installer/redhat-appstudio-rhtap-installer-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#47825 Bail out of ipi-deprovision-deprovision properly on failed install
  ci-operator/step-registry/ipi/deprovision/deprovision/ipi-deprovision-deprovision-commands.sh
Labels: lgtm, approved, rehearsals-ack

#50535 TRT-1160 Introduce a periodic vsphere upgrade job for 4.14
  ci-operator/config/openshift/release/openshift-release-master__ci-4.14.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#50582 NO-JIRA: HCO: use labels to skip tests
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-main.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#50613 PowerVS: Add mad02 leases
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: lgtm, approved, rehearsals-ack

#50627 cloud-provider-kubevirt: Activate snyk jobs
  ci-operator/config/openshift/cloud-provider-kubevirt/openshift-cloud-provider-kubevirt-main.yaml
  ci-operator/config/openshift/cloud-provider-kubevirt/openshift-cloud-provider-kubevirt-release-4.14.yaml
  ci-operator/config/openshift/cloud-provider-kubevirt/openshift-cloud-provider-kubevirt-release-4.15.yaml
  ci-operator/config/openshift/cloud-provider-kubevirt/openshift-cloud-provider-kubevirt-release-4.16.yaml
  ci-operator/config/openshift/cloud-provider-kubevirt/openshift-cloud-provider-kubevirt-release-4.17.yaml
  ci-operator/jobs/openshift/cloud-provider-kubevirt/openshift-cloud-provider-kubevirt-main-presubmits.yaml
  ci-operator/jobs/openshift/cloud-provider-kubevirt/openshift-cloud-provider-kubevirt-release-4.14-presubmits.yaml
  ci-operator/jobs/openshift/cloud-provider-kubevirt/openshift-cloud-provider-kubevirt-release-4.15-presubmits.yaml
  ci-operator/jobs/openshift/cloud-provider-kubevirt/openshift-cloud-provider-kubevirt-release-4.16-presubmits.yaml
  ci-operator/jobs/openshift/cloud-provider-kubevirt/openshift-cloud-provider-kubevirt-release-4.17-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#50233 add tests for openshift-pipelines on rosa classic
  ci-operator/config/openshift-pipelines/release-tests/openshift-pipelines-release-tests-release-v1.14__openshift-pipelines-ocp4.14-lp-rosa-classic.yaml
  ci-operator/config/openshift-pipelines/release-tests/openshift-pipelines-release-tests-release-v1.14__openshift-pipelines-ocp4.15-lp-rosa-classic.yaml
  ci-operator/jobs/openshift-pipelines/release-tests/openshift-pipelines-release-tests-release-v1.14-periodics.yaml
  ci-operator/jobs/openshift-pipelines/release-tests/openshift-pipelines-release-tests-release-v1.14-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#50631 Clean orgs/repos that moved out of openshift cluster profile
  ci-operator/config/redhat-openshift-ecosystem/cvp/redhat-openshift-ecosystem-cvp-ocp-4.12.yaml
  ci-operator/config/redhat-openshift-ecosystem/okd-operators/redhat-openshift-ecosystem-okd-operators-main__4.10.yaml
  ci-operator/config/redhat-openshift-ecosystem/okd-operators/redhat-openshift-ecosystem-okd-operators-main__4.11.yaml
  ci-operator/config/redhat-openshift-ecosystem/okd-operators/redhat-openshift-ecosystem-okd-operators-main__4.6.yaml
  ci-operator/config/redhat-openshift-ecosystem/okd-operators/redhat-openshift-ecosystem-okd-operators-main__4.7.yaml
  ci-operator/config/redhat-openshift-ecosystem/okd-operators/redhat-openshift-ecosystem-okd-operators-main__4.8.yaml
  ci-operator/config/redhat-openshift-ecosystem/okd-operators/redhat-openshift-ecosystem-okd-operators-main__4.9.yaml
  ci-operator/jobs/redhat-openshift-ecosystem/cvp/redhat-openshift-ecosystem-cvp-ocp-4.12-periodics.yaml
  ci-operator/jobs/redhat-openshift-ecosystem/okd-operators/redhat-openshift-ecosystem-okd-operators-main-presubmits.yaml
  ci-operator/step-registry/cluster-profiles/cluster-profiles-config.yaml
Labels: lgtm, approved, rehearsals-ack

#50623 openshift-loki: Use loki v2.9.6 in operator release-5.8
  ci-operator/config/openshift/loki/openshift-loki-release-5.8.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-release-5.8-postsubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-release-5.8-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#50624 openshift-loki: Use loki v2.9.6 in operator release-5.7
  ci-operator/config/openshift/loki/openshift-loki-release-5.7.yaml
Labels: lgtm, approved, rehearsals-ack

#50625 openshift-loki: Use loki v2.9.6 in operator release-5.6
  ci-operator/config/openshift/loki/openshift-loki-release-5.6.yaml
Labels: lgtm, approved, rehearsals-ack

#50630 SNC: Add release-4.16 branch
  ci-operator/config/crc-org/snc/crc-org-snc-release-4.16.yaml
  ci-operator/jobs/crc-org/snc/crc-org-snc-release-4.16-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#50575 Add SOP for alert/quay-io-image-mirroring-failures
  docs/dptp-triage-sop/misc.md
Labels: lgtm, approved, rehearsals-ack

#50626 openshift-loki: Add config and image mirroring for branch release-5.9
  ci-operator/config/openshift/loki/openshift-loki-release-5.9.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-release-5.9-postsubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-release-5.9-presubmits.yaml
  core-services/image-mirroring/openshift-logging/mapping_logging_5_9_quay
Labels: lgtm, approved, rehearsals-ack

#50593 openshift-loki: Use loki v2.9.6 in operator main
  ci-operator/config/openshift/loki/openshift-loki-main.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-main-postsubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#50617 Change cluster profiles for 4.15 and 4.16 ppc64le jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__ppc64le-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__ppc64le-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#50639 Ignore mirroring ci/fedora:latest
  clusters/app.ci/assets/admin_ci-images-mirror.yaml
Labels: lgtm, approved, rehearsals-ack

#50590 Interop - Add support for install-operators-verify ref
  ci-operator/config/3scale-qe/3scale-deploy/3scale-qe-3scale-deploy-main__3scale-amp-ocp4.16-lp-interop.yaml
  ci-operator/config/ansible/tower-qa/ansible-tower-qa-devel__ocp4.16-lp-interop.yaml
  ci-operator/config/infinispan/infinispan-operator/infinispan-infinispan-operator-stable__data-grid-ocp4.16-lp-interop.yaml
  ci-operator/config/jboss-eap-qe/openshift-eap-tests/jboss-eap-qe-openshift-eap-tests-pit-7.4.x__eap-ocp4.16-lp-interop.yaml
  ci-operator/config/jboss-fuse/camel-k-test-container/jboss-fuse-camel-k-test-container-main__camel-k-ocp4.16-lp-interop.yaml
  ci-operator/config/jws-qe/interop-ocp-ci/jws-qe-interop-ocp-ci-main__ocp-4.16-lp-interop.yaml
  ci-operator/config/konveyor/tackle-ui-tests/konveyor-tackle-ui-tests-mta_7.0.0__mta-ocp4.16-lp-interop.yaml
  ci-operator/config/maistra/maistra-test-tool/maistra-maistra-test-tool-main__servicemesh-ocp4.16-lp-interop.yaml
  ci-operator/step-registry/3scale/ipi/aws/3scale-ipi-aws-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#50599 OLS: added bundle build for lightspeed operator
  ci-operator/config/openshift/lightspeed-operator/openshift-lightspeed-operator-main.yaml
  ci-operator/jobs/openshift/lightspeed-operator/openshift-lightspeed-operator-main-postsubmits.yaml
  ci-operator/jobs/openshift/lightspeed-operator/openshift-lightspeed-operator-main-presubmits.yaml
Labels: lgtm, approved, tide/merge-method-squash, rehearsals-ack

#50629 [TRT-1160] Migrate the periodic vsphere upgrade job from 4.14 to 4.16
  ci-operator/config/openshift/release/openshift-release-master__ci-4.14.yaml
  ci-operator/config/openshift/release/openshift-release-master__ci-4.16.yaml
  ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#47991 Remove unnecessary windows-e2e-operator-test-with-custom-vxlan-port workflow
  ci-operator/config/openshift-priv/cluster-network-operator/openshift-priv-cluster-network-operator-master.yaml
  ci-operator/config/openshift-priv/cluster-network-operator/openshift-priv-cluster-network-operator-release-4.10.yaml
  ci-operator/config/openshift-priv/cluster-network-operator/openshift-priv-cluster-network-operator-release-4.11.yaml
  ci-operator/config/openshift-priv/cluster-network-operator/openshift-priv-cluster-network-operator-release-4.12.yaml
  ci-operator/config/openshift-priv/cluster-network-operator/openshift-priv-cluster-network-operator-release-4.13.yaml
  ci-operator/config/openshift-priv/cluster-network-operator/openshift-priv-cluster-network-operator-release-4.14.yaml
  ci-operator/config/openshift-priv/cluster-network-operator/openshift-priv-cluster-network-operator-release-4.15.yaml
  ci-operator/config/openshift-priv/cluster-network-operator/openshift-priv-cluster-network-operator-release-4.16.yaml
  ci-operator/config/openshift-priv/cluster-network-operator/openshift-priv-cluster-network-operator-release-4.17.yaml
  ci-operator/config/openshift-priv/cluster-network-operator/openshift-priv-cluster-network-operator-release-4.7.yaml
  ci-operator/config/openshift-priv/cluster-network-operator/openshift-priv-cluster-network-operator-release-4.8.yaml
  ci-operator/config/openshift-priv/cluster-network-operator/openshift-priv-cluster-network-operator-release-4.9.yaml
  ci-operator/config/openshift-priv/ovn-kubernetes/openshift-priv-ovn-kubernetes-release-4.10.yaml
  ci-operator/config/openshift-priv/ovn-kubernetes/openshift-priv-ovn-kubernetes-release-4.11.yaml
  ci-operator/config/openshift-priv/ovn-kubernetes/openshift-priv-ovn-kubernetes-release-4.12.yaml
  ci-operator/config/openshift-priv/ovn-kubernetes/openshift-priv-ovn-kubernetes-release-4.13.yaml
  ci-operator/config/openshift-priv/ovn-kubernetes/openshift-priv-ovn-kubernetes-release-4.14.yaml
  ci-operator/config/openshift-priv/ovn-kubernetes/openshift-priv-ovn-kubernetes-release-4.15.yaml
  ci-operator/config/openshift-priv/ovn-kubernetes/openshift-priv-ovn-kubernetes-release-4.7.yaml
  ci-operator/config/openshift-priv/ovn-kubernetes/openshift-priv-ovn-kubernetes-release-4.8.yaml
  ci-operator/config/openshift-priv/ovn-kubernetes/openshift-priv-ovn-kubernetes-release-4.9.yaml
  ci-operator/config/openshift-priv/windows-machine-config-operator/openshift-priv-windows-machine-config-operator-master.yaml
  ci-operator/config/openshift-priv/windows-machine-config-operator/openshift-priv-windows-machine-config-operator-release-4.12.yaml
  ci-operator/config/openshift-priv/windows-machine-config-operator/openshift-priv-windows-machine-config-operator-release-4.13.yaml
  ci-operator/config/openshift-priv/windows-machine-config-operator/openshift-priv-windows-machine-config-operator-release-4.14.yaml
  ci-operator/config/openshift-priv/windows-machine-config-operator/openshift-priv-windows-machine-config-operator-release-4.15.yaml
  ci-operator/config/openshift-priv/windows-machine-config-operator/openshift-priv-windows-machine-config-operator-release-4.16.yaml
  ci-operator/config/openshift-priv/windows-machine-config-operator/openshift-priv-windows-machine-config-operator-release-4.17.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-master.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.10.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.11.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.12.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.13.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.14.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.15.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.16.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.17.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.7.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.8.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.9.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.10.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.11.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.12.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.13.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.14.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.15.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.7.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.8.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.9.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-master.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.12.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.13.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.14.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.15.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.16.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.17.yaml
  ci-operator/step-registry/windows/e2e/operator/test/with-custom-vxlan-port/OWNERS
  ci-operator/step-registry/windows/e2e/operator/test/with-custom-vxlan-port/windows-e2e-operator-test-with-custom-vxlan-port-commands.sh
  ci-operator/step-registry/windows/e2e/operator/test/with-custom-vxlan-port/windows-e2e-operator-test-with-custom-vxlan-port-ref.metadata.json
  ci-operator/step-registry/windows/e2e/operator/test/with-custom-vxlan-port/windows-e2e-operator-test-with-custom-vxlan-port-ref.yaml
Labels: lgtm, approved, rehearsals-ack
