Repository openshift/release, pull requests merged in 2025-05, with the labels that each got.

#64257 MULTIARCH-5349: MTO adjusted to track v1.x
  ci-operator/config/openshift/multiarch-tuning-operator/openshift-multiarch-tuning-operator-v1.x.yaml
  ci-operator/config/openshift/multiarch-tuning-operator/openshift-multiarch-tuning-operator-v1.x__ocp416.yaml
  ci-operator/config/openshift/multiarch-tuning-operator/openshift-multiarch-tuning-operator-v1.x__ocp417.yaml
  ci-operator/config/openshift/multiarch-tuning-operator/openshift-multiarch-tuning-operator-v1.x__ocp418.yaml
  ci-operator/config/openshift/multiarch-tuning-operator/openshift-multiarch-tuning-operator-v1.x__ocp419.yaml
  ci-operator/jobs/openshift/multiarch-tuning-operator/openshift-multiarch-tuning-operator-v1.x-periodics.yaml
  ci-operator/jobs/openshift/multiarch-tuning-operator/openshift-multiarch-tuning-operator-v1.x-postsubmits.yaml
  ci-operator/jobs/openshift/multiarch-tuning-operator/openshift-multiarch-tuning-operator-v1.x-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#64418 SPLAT-2063: update the QE workflow to agree with nightly multiarch
  ci-operator/step-registry/openshift/e2e/ibmcloud/heterogeneous/test/qe/openshift-e2e-ibmcloud-heterogeneous-test-qe-workflow.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#63500 adding get of observer status
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__4.15-nightly.yaml
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__4.16-nightly-upgrade.yaml
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__4.16-nightly-x86-cpou-upgrade-4.14.yaml
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__4.16-nightly.yaml
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__4.17-nightly.yaml
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__4.18-nightly-upgrade.yaml
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__4.18-nightly-x86-cpou-upgrade-4.16.yaml
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__4.18-nightly.yaml
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__4.19-nightly.yaml
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__cr-4.17-nightly.yaml
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__cr-4.18-nightly.yaml
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__cr-4.19-nightly.yaml
  ci-operator/step-registry/redhat-chaos/cerberus/redhat-chaos-cerberus-commands.sh
  ci-operator/step-registry/redhat-chaos/cerberus/redhat-chaos-cerberus-observer.yaml
  ci-operator/step-registry/redhat-chaos/installer/OWNERS
  ci-operator/step-registry/redhat-chaos/installer/aws/OWNERS
  ci-operator/step-registry/redhat-chaos/installer/aws/compact/OWNERS
  ci-operator/step-registry/redhat-chaos/installer/aws/compact/redhat-chaos-installer-aws-compact-workflow.metadata.json
  ci-operator/step-registry/redhat-chaos/installer/aws/compact/redhat-chaos-installer-aws-compact-workflow.yaml
  ci-operator/step-registry/redhat-chaos/installer/aws/redhat-chaos-installer-aws-workflow.metadata.json
  ci-operator/step-registry/redhat-chaos/installer/aws/redhat-chaos-installer-aws-workflow.yaml
  ci-operator/step-registry/redhat-chaos/installer/azure/OWNERS
  ci-operator/step-registry/redhat-chaos/installer/azure/aro/OWNERS
  ci-operator/step-registry/redhat-chaos/installer/azure/aro/upi/OWNERS
  ci-operator/step-registry/redhat-chaos/installer/azure/aro/upi/redhat-chaos-installer-azure-aro-upi-workflow.metadata.json
  ci-operator/step-registry/redhat-chaos/installer/azure/aro/upi/redhat-chaos-installer-azure-aro-upi-workflow.yaml
  ci-operator/step-registry/redhat-chaos/installer/azure/ipi/OWNERS
  ci-operator/step-registry/redhat-chaos/installer/azure/ipi/ovn/OWNERS
  ci-operator/step-registry/redhat-chaos/installer/azure/ipi/ovn/ipsec/OWNERS
  ci-operator/step-registry/redhat-chaos/installer/azure/ipi/ovn/ipsec/redhat-chaos-installer-azure-ipi-ovn-ipsec-workflow.metadata.json
  ci-operator/step-registry/redhat-chaos/installer/azure/ipi/ovn/ipsec/redhat-chaos-installer-azure-ipi-ovn-ipsec-workflow.yaml
  ci-operator/step-registry/redhat-chaos/installer/azure/redhat-chaos-installer-azure-workflow.metadata.json
  ci-operator/step-registry/redhat-chaos/installer/azure/redhat-chaos-installer-azure-workflow.yaml
  ci-operator/step-registry/redhat-chaos/installer/gcp/OWNERS
  ci-operator/step-registry/redhat-chaos/installer/gcp/ipi/OWNERS
  ci-operator/step-registry/redhat-chaos/installer/gcp/ipi/ovn/OWNERS
  ci-operator/step-registry/redhat-chaos/installer/gcp/ipi/ovn/etcd-encryption/OWNERS
  ci-operator/step-registry/redhat-chaos/installer/gcp/ipi/ovn/etcd-encryption/fips/OWNERS
  ci-operator/step-registry/redhat-chaos/installer/gcp/ipi/ovn/etcd-encryption/fips/redhat-chaos-installer-gcp-ipi-ovn-etcd-encryption-fips-workflow.metadata.json
  ci-operator/step-registry/redhat-chaos/installer/gcp/ipi/ovn/etcd-encryption/fips/redhat-chaos-installer-gcp-ipi-ovn-etcd-encryption-fips-workflow.yaml
  ci-operator/step-registry/redhat-chaos/installer/gcp/ipi/ovn/ipsec/OWNERS
  ci-operator/step-registry/redhat-chaos/installer/gcp/ipi/ovn/ipsec/redhat-chaos-installer-gcp-ipi-ovn-ipsec-workflow.metadata.json
  ci-operator/step-registry/redhat-chaos/installer/gcp/ipi/ovn/ipsec/redhat-chaos-installer-gcp-ipi-ovn-ipsec-workflow.yaml
  ci-operator/step-registry/redhat-chaos/installer/gcp/redhat-chaos-installer-gcp-workflow.metadata.json
  ci-operator/step-registry/redhat-chaos/installer/gcp/redhat-chaos-installer-gcp-workflow.yaml
  ci-operator/step-registry/redhat-chaos/installer/ibmcloud/OWNERS
  ci-operator/step-registry/redhat-chaos/installer/ibmcloud/ipi/OWNERS
  ci-operator/step-registry/redhat-chaos/installer/ibmcloud/ipi/ovn/OWNERS
  ci-operator/step-registry/redhat-chaos/installer/ibmcloud/ipi/ovn/redhat-chaos-installer-ibmcloud-ipi-ovn-workflow.metadata.json
  ci-operator/step-registry/redhat-chaos/installer/ibmcloud/ipi/ovn/redhat-chaos-installer-ibmcloud-ipi-ovn-workflow.yaml
  ci-operator/step-registry/redhat-chaos/observer-start/OWNERS
  ci-operator/step-registry/redhat-chaos/observer-start/redhat-chaos-observer-start-commands.sh
  ci-operator/step-registry/redhat-chaos/observer-start/redhat-chaos-observer-start-ref.metadata.json
  ci-operator/step-registry/redhat-chaos/observer-start/redhat-chaos-observer-start-ref.yaml
  ci-operator/step-registry/redhat-chaos/observer-stop/OWNERS
  ci-operator/step-registry/redhat-chaos/observer-stop/redhat-chaos-observer-stop-commands.sh
  ci-operator/step-registry/redhat-chaos/observer-stop/redhat-chaos-observer-stop-ref.metadata.json
  ci-operator/step-registry/redhat-chaos/observer-stop/redhat-chaos-observer-stop-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#64414 MULTIARCH-5196: remove an invalid cp command from vpc deployment
  ci-operator/step-registry/upi/install/heterogeneous/vpc/upi-install-heterogeneous-vpc-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#64444 release-controller: add secret permissions for mirror-cleanup-controller
  clusters/app.ci/release-mirror-cleanup-controller/admin_rbac.yaml
  clusters/app.ci/release-mirror-cleanup-controller/deployment.yaml
  hack/generators/release-controllers/content/release_mirror_cleanup_controller_resources.py
Labels: lgtm, approved, rehearsals-ack

#64441 ci-operator/step-registry/gather/extra: Gather Jobs too
  ci-operator/step-registry/gather/extra/gather-extra-commands.sh
Labels: lgtm, approved, rehearsals-ack

#60060 wmco: Adjust AWS replicas count for all releases
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.12.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.13.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.14.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.15.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.16.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.17.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.18.yaml
Labels: lgtm, approved, rehearsals-ack

#64450 HIVE-2270: Pass additional environment variables to hive e2e
  ci-operator/config/openshift/hive/openshift-hive-master.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#64443 [4.19] Image mirroring config
  core-services/image-mirroring/openshift/_config.yaml
  core-services/image-mirroring/openshift/mapping_origin_4_19
  core-services/image-mirroring/openshift/mapping_origin_4_20
  core-services/image-mirroring/openshift/mapping_origin_ptp-4_19
  core-services/image-mirroring/openshift/mapping_origin_ptp-4_20
  core-services/image-mirroring/openshift/mapping_origin_scos-4_19
  core-services/image-mirroring/openshift/mapping_origin_sriov-4_19
  core-services/image-mirroring/openshift/mapping_origin_sriov-4_20
Labels: lgtm, approved, rehearsals-ack

#64457 4.19 etcd special case
  core-services/prow/02_config/openshift/etcd/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#64434 Update dockerfile path for agent qe
  ci-operator/config/openshift-eng/agent-qe-infra/openshift-eng-agent-qe-infra-master.yaml
Labels: lgtm, approved, rehearsals-ack

#64463 Skip shellcheck if files are deleted in the PR
  ci-operator/config/openshift-eng/agent-qe-infra/openshift-eng-agent-qe-infra-master.yaml
Labels: lgtm, approved, rehearsals-ack

#61457 kata-containers: Add peer-pods variant
  ci-operator/config/kata-containers/kata-containers/kata-containers-kata-containers-main__peer-pods.yaml
  ci-operator/jobs/kata-containers/kata-containers/kata-containers-kata-containers-main-periodics.yaml
  ci-operator/jobs/kata-containers/kata-containers/kata-containers-kata-containers-main-presubmits.yaml
Labels: lgtm, approved, lifecycle/stale, rehearsals-ack

#64468 NO_JIRA: Add PeaceRebel (Bipin) to coreos approvers & reviewers list
  OWNERS_ALIASES
Labels: lgtm, approved, rehearsals-ack

#64440 (ocm) Set `images` stanza to optional (GRC)
  ci-operator/config/stolostron/acm-cli/stolostron-acm-cli-main.yaml
  ci-operator/config/stolostron/acm-cli/stolostron-acm-cli-release-2.12.yaml
  ci-operator/config/stolostron/acm-cli/stolostron-acm-cli-release-2.13.yaml
  ci-operator/config/stolostron/acm-cli/stolostron-acm-cli-release-2.14.yaml
  ci-operator/config/stolostron/cert-policy-controller/stolostron-cert-policy-controller-main.yaml
  ci-operator/config/stolostron/cert-policy-controller/stolostron-cert-policy-controller-release-2.10.yaml
  ci-operator/config/stolostron/cert-policy-controller/stolostron-cert-policy-controller-release-2.11.yaml
  ci-operator/config/stolostron/cert-policy-controller/stolostron-cert-policy-controller-release-2.12.yaml
  ci-operator/config/stolostron/cert-policy-controller/stolostron-cert-policy-controller-release-2.13.yaml
  ci-operator/config/stolostron/cert-policy-controller/stolostron-cert-policy-controller-release-2.14.yaml
  ci-operator/config/stolostron/cert-policy-controller/stolostron-cert-policy-controller-release-2.9.yaml
  ci-operator/config/stolostron/config-policy-controller/stolostron-config-policy-controller-main.yaml
  ci-operator/config/stolostron/config-policy-controller/stolostron-config-policy-controller-release-2.10.yaml
  ci-operator/config/stolostron/config-policy-controller/stolostron-config-policy-controller-release-2.11.yaml
  ci-operator/config/stolostron/config-policy-controller/stolostron-config-policy-controller-release-2.12.yaml
  ci-operator/config/stolostron/config-policy-controller/stolostron-config-policy-controller-release-2.13.yaml
  ci-operator/config/stolostron/config-policy-controller/stolostron-config-policy-controller-release-2.14.yaml
  ci-operator/config/stolostron/config-policy-controller/stolostron-config-policy-controller-release-2.9.yaml
  ci-operator/config/stolostron/governance-policy-addon-controller/stolostron-governance-policy-addon-controller-main.yaml
  ci-operator/config/stolostron/governance-policy-addon-controller/stolostron-governance-policy-addon-controller-release-2.10.yaml
  ci-operator/config/stolostron/governance-policy-addon-controller/stolostron-governance-policy-addon-controller-release-2.11.yaml
  ci-operator/config/stolostron/governance-policy-addon-controller/stolostron-governance-policy-addon-controller-release-2.12.yaml
  ci-operator/config/stolostron/governance-policy-addon-controller/stolostron-governance-policy-addon-controller-release-2.13.yaml
  ci-operator/config/stolostron/governance-policy-addon-controller/stolostron-governance-policy-addon-controller-release-2.14.yaml
  ci-operator/config/stolostron/governance-policy-addon-controller/stolostron-governance-policy-addon-controller-release-2.9.yaml
  ci-operator/config/stolostron/governance-policy-framework-addon/stolostron-governance-policy-framework-addon-main.yaml
  ci-operator/config/stolostron/governance-policy-framework-addon/stolostron-governance-policy-framework-addon-release-2.10.yaml
  ci-operator/config/stolostron/governance-policy-framework-addon/stolostron-governance-policy-framework-addon-release-2.11.yaml
  ci-operator/config/stolostron/governance-policy-framework-addon/stolostron-governance-policy-framework-addon-release-2.12.yaml
  ci-operator/config/stolostron/governance-policy-framework-addon/stolostron-governance-policy-framework-addon-release-2.13.yaml
  ci-operator/config/stolostron/governance-policy-framework-addon/stolostron-governance-policy-framework-addon-release-2.14.yaml
  ci-operator/config/stolostron/governance-policy-framework-addon/stolostron-governance-policy-framework-addon-release-2.9.yaml
  ci-operator/config/stolostron/governance-policy-framework/stolostron-governance-policy-framework-main.yaml
  ci-operator/config/stolostron/governance-policy-framework/stolostron-governance-policy-framework-release-2.10.yaml
  ci-operator/config/stolostron/governance-policy-framework/stolostron-governance-policy-framework-release-2.11.yaml
  ci-operator/config/stolostron/governance-policy-framework/stolostron-governance-policy-framework-release-2.12.yaml
  ci-operator/config/stolostron/governance-policy-framework/stolostron-governance-policy-framework-release-2.13.yaml
  ci-operator/config/stolostron/governance-policy-framework/stolostron-governance-policy-framework-release-2.14.yaml
  ci-operator/config/stolostron/governance-policy-framework/stolostron-governance-policy-framework-release-2.9.yaml
  ci-operator/config/stolostron/governance-policy-propagator/stolostron-governance-policy-propagator-main.yaml
  ci-operator/config/stolostron/governance-policy-propagator/stolostron-governance-policy-propagator-release-2.10.yaml
  ci-operator/config/stolostron/governance-policy-propagator/stolostron-governance-policy-propagator-release-2.11.yaml
  ci-operator/config/stolostron/governance-policy-propagator/stolostron-governance-policy-propagator-release-2.12.yaml
  ci-operator/config/stolostron/governance-policy-propagator/stolostron-governance-policy-propagator-release-2.13.yaml
  ci-operator/config/stolostron/governance-policy-propagator/stolostron-governance-policy-propagator-release-2.14.yaml
  ci-operator/config/stolostron/governance-policy-propagator/stolostron-governance-policy-propagator-release-2.9.yaml
  ci-operator/config/stolostron/iam-policy-controller/stolostron-iam-policy-controller-release-2.10.yaml
  ci-operator/config/stolostron/iam-policy-controller/stolostron-iam-policy-controller-release-2.9.yaml
  ci-operator/config/stolostron/must-gather/stolostron-must-gather-main.yaml
  ci-operator/config/stolostron/must-gather/stolostron-must-gather-release-2.10.yaml
  ci-operator/config/stolostron/must-gather/stolostron-must-gather-release-2.11.yaml
  ci-operator/config/stolostron/must-gather/stolostron-must-gather-release-2.12.yaml
  ci-operator/config/stolostron/must-gather/stolostron-must-gather-release-2.13.yaml
  ci-operator/config/stolostron/must-gather/stolostron-must-gather-release-2.14.yaml
  ci-operator/config/stolostron/must-gather/stolostron-must-gather-release-2.9.yaml
Labels: lgtm, approved, rehearsals-ack

#64461 ACS: Remove ui-component-tests from `master` and `release-4.6`
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-4.6.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-presubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-4.6-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#64214 Add CI testing to SPO konflux branch
  ci-operator/config/openshift/security-profiles-operator/openshift-security-profiles-operator-konflux.yaml
  ci-operator/jobs/openshift/security-profiles-operator/openshift-security-profiles-operator-konflux-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#64472 set ci-deps optional for kubernetes
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-master.yaml
  ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#64284 add ocm-cluster-service to prow management
  ci-operator/config/openshift-online/ocm-cluster-service/.config.prowgen
  ci-operator/config/openshift-online/ocm-cluster-service/OWNERS
  ci-operator/config/openshift-online/ocm-cluster-service/openshift-online-ocm-cluster-service-main.yaml
  ci-operator/jobs/openshift-online/ocm-cluster-service/OWNERS
  ci-operator/jobs/openshift-online/ocm-cluster-service/openshift-online-ocm-cluster-service-main-presubmits.yaml
  core-services/prow/02_config/openshift-online/ocm-cluster-service/OWNERS
  core-services/prow/02_config/openshift-online/ocm-cluster-service/_pluginconfig.yaml
  core-services/prow/02_config/openshift-online/ocm-cluster-service/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#64445 NO-ISSUE: Fix dependency download order
  ci-operator/config/openshift-assisted/cluster-api-provider-openshift-assisted/openshift-assisted-cluster-api-provider-openshift-assisted-master.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#64479 Bumped ocp version for e2e claim tests
  clusters/hosted-mgmt/hive/pools/ci-tools/fake-ocp-4-18-amd64-aws_clusterpool.yaml
  clusters/hosted-mgmt/hive/pools/ci-tools/ocp-release-4.18.20-x86-64-for-4.18.0-0-to-4.19.0-0_clusterimageset.yaml
Labels: lgtm, approved, rehearsals-ack

#64481 stolostron search release 2-11 ubi updates
  ci-operator/config/stolostron/search-collector/stolostron-search-collector-release-2.11.yaml
  ci-operator/config/stolostron/search-indexer/stolostron-search-indexer-release-2.11.yaml
  ci-operator/config/stolostron/search-v2-api/stolostron-search-v2-api-release-2.11.yaml
  ci-operator/config/stolostron/search-v2-operator/stolostron-search-v2-operator-release-2.11.yaml
Labels: lgtm, approved, rehearsals-ack

#64486 add `shard_count` back to `e2e-aws-ovn-serial` jobs
  ci-operator/config/openshift/origin/openshift-origin-main.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.19.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.20.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-main-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.19-presubmits.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-release-4.20-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#64464 CNTRLPLASE-371: Increase timeouts for payload jobs to land k8s 1.33
  clusters/app.ci/job-trigger-controller-manager/job-trigger-controller-manager_deploy.yaml
Labels: lgtm, approved, rehearsals-ack

#64462 NO-JIRA: promote cincinnati-ci-public/cincinnati-graph-data:stable
  ci-operator/config/openshift/cincinnati-graph-data/openshift-cincinnati-graph-data-master.yaml
  ci-operator/jobs/openshift/cincinnati-graph-data/openshift-cincinnati-graph-data-master-postsubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#62819 OTA-1455: cincinnati: build tag cincinnati-ci-public/rust:boot-root-1.79.0
  clusters/app.ci/supplemental-ci-images/cincinnati-ci/rust.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#64282 OTA-1491: cincinnator: add job/verify-crypto
  ci-operator/config/openshift/cincinnati-operator/openshift-cincinnati-operator-master.yaml
  ci-operator/jobs/openshift/cincinnati-operator/openshift-cincinnati-operator-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#64382 Enable OSSM istio integration security tests
  ci-operator/config/openshift-service-mesh/istio/openshift-service-mesh-istio-master.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#64403 Update maistra reviewers and approvers lists
  OWNERS_ALIASES
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#64503 Update workdir to /home/default
  ci-operator/config/openshift/jenkins-sync-plugin/openshift-jenkins-sync-plugin-master.yaml
  ci-operator/config/openshift/jenkins-sync-plugin/openshift-jenkins-sync-plugin-release-4.12.yaml
  ci-operator/config/openshift/jenkins-sync-plugin/openshift-jenkins-sync-plugin-release-4.13.yaml
  ci-operator/config/openshift/jenkins-sync-plugin/openshift-jenkins-sync-plugin-release-4.14.yaml
  ci-operator/config/openshift/jenkins-sync-plugin/openshift-jenkins-sync-plugin-release-4.15.yaml
  ci-operator/config/openshift/jenkins-sync-plugin/openshift-jenkins-sync-plugin-release-4.16.yaml
  ci-operator/config/openshift/jenkins-sync-plugin/openshift-jenkins-sync-plugin-release-4.17.yaml
  ci-operator/config/openshift/jenkins-sync-plugin/openshift-jenkins-sync-plugin-release-4.18.yaml
  ci-operator/config/openshift/jenkins-sync-plugin/openshift-jenkins-sync-plugin-release-4.19.yaml
  ci-operator/config/openshift/jenkins-sync-plugin/openshift-jenkins-sync-plugin-release-4.20.yaml
Labels: lgtm, approved, rehearsals-ack

#64492 NO-JIRA: mirror cincinnati-ci-public/rust:boot-root-1.79.0 to QCI
  core-services/image-mirroring/_config.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#64504 k-nmstate: automagically fix golang dependencies
  ci-operator/config/openshift-eng/rebasebot/openshift-eng-rebasebot-main.yaml
Labels: lgtm, approved, rehearsals-ack

#64485 CNTRLPLANE-777: Update cron schedule for e2e-aks periodic job to run every 6 hours for 4.20
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.20__periodics.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.20-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#64508 Remove rhtap-cli periodic jobs
  ci-operator/config/redhat-appstudio/rhtap-cli/redhat-appstudio-rhtap-cli-main.yaml
  ci-operator/jobs/redhat-appstudio/rhtap-cli/redhat-appstudio-rhtap-cli-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#64518 ci-operator: machine-api-operator: add techpreview job
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-main.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#64340 cnf network: switch to dynamic pipeline env, added eco-gotests step
  ci-operator/config/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main__cnf-network-4.17.yaml
  ci-operator/step-registry/telcov10n/functional/cnf-network/eco-gotests/OWNERS
  ci-operator/step-registry/telcov10n/functional/cnf-network/eco-gotests/telcov10n-functional-cnf-network-eco-gotests-commands.sh
  ci-operator/step-registry/telcov10n/functional/cnf-network/eco-gotests/telcov10n-functional-cnf-network-eco-gotests-ref.metadata.json
  ci-operator/step-registry/telcov10n/functional/cnf-network/eco-gotests/telcov10n-functional-cnf-network-eco-gotests-ref.yaml
  ci-operator/step-registry/telcov10n/functional/cnf-network/ocp-deploy/telcov10n-functional-cnf-network-ocp-deploy-commands.sh
  ci-operator/step-registry/telcov10n/functional/cnf-network/setup-cluster-env/telcov10n-functional-cnf-network-setup-cluster-env-commands.sh
  ci-operator/step-registry/telcov10n/functional/cnf-network/setup-cluster-env/telcov10n-functional-cnf-network-setup-cluster-env-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#64520 instaslice: use 4.18 for instaslice
  ci-operator/config/openshift/instaslice-operator/openshift-instaslice-operator-main.yaml
Labels: lgtm, approved, rehearsals-ack

#64523 instaslice: remove promotion
  ci-operator/config/openshift/instaslice-operator/openshift-instaslice-operator-main.yaml
  ci-operator/jobs/openshift/instaslice-operator/openshift-instaslice-operator-main-postsubmits.yaml
  ci-operator/jobs/openshift/instaslice-operator/openshift-instaslice-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#64474 ACS: Remove EBPF tests from OCP, EKS and AKS
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-12.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-18.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-dev-preview.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-next-candidate.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-stable-scanner-v4-install.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies__ocp-4-12.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies__ocp-4-18.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-x.y.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-x.y__ocp-4-12.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-x.y__ocp-4-18.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-postsubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-presubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-nightlies-postsubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-x.y-postsubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-x.y-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#64278 MGMT-19567: splitting the pre-submit CI jobs of assisted-installer-agent to 2 stages.
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master__edge.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.10.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.11.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.12.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.13.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.9.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master-presubmits.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.10-presubmits.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.11-presubmits.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.12-presubmits.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.13-presubmits.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-release-ocm-2.9-presubmits.yaml
  core-services/pipeline-controller/lgtm-config.yaml
  core-services/prow/02_config/openshift/assisted-installer-agent/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#64498 tag/rust:boot-root-1.79.0 fix PATH
  clusters/app.ci/supplemental-ci-images/cincinnati-ci/rust.yaml
Labels: lgtm, approved, rehearsals-ack

#64526 Keep istag cincinnati-ci-public/cincinnati-graph-data:6420f7fbf3724e1…
  ci-operator/jobs/infra-periodics.yaml
  clusters/app.ci/supplemental-ci-images/cincinnati-ci/cincinnati-graph-data_is.yaml
Labels: lgtm, approved, rehearsals-ack

#64531 make e2e-aws mandatory for cloud-event-proxy
  ci-operator/config/redhat-cne/cloud-event-proxy/redhat-cne-cloud-event-proxy-main.yaml
  ci-operator/config/redhat-cne/cloud-event-proxy/redhat-cne-cloud-event-proxy-release-4.12.yaml
  ci-operator/config/redhat-cne/cloud-event-proxy/redhat-cne-cloud-event-proxy-release-4.13.yaml
  ci-operator/config/redhat-cne/cloud-event-proxy/redhat-cne-cloud-event-proxy-release-4.14.yaml
  ci-operator/config/redhat-cne/cloud-event-proxy/redhat-cne-cloud-event-proxy-release-4.15.yaml
  ci-operator/config/redhat-cne/cloud-event-proxy/redhat-cne-cloud-event-proxy-release-4.16.yaml
  ci-operator/config/redhat-cne/cloud-event-proxy/redhat-cne-cloud-event-proxy-release-4.17.yaml
  ci-operator/config/redhat-cne/cloud-event-proxy/redhat-cne-cloud-event-proxy-release-4.18.yaml
  ci-operator/config/redhat-cne/cloud-event-proxy/redhat-cne-cloud-event-proxy-release-4.19.yaml
  ci-operator/config/redhat-cne/cloud-event-proxy/redhat-cne-cloud-event-proxy-release-4.20.yaml
  ci-operator/jobs/redhat-cne/cloud-event-proxy/redhat-cne-cloud-event-proxy-main-presubmits.yaml
  ci-operator/jobs/redhat-cne/cloud-event-proxy/redhat-cne-cloud-event-proxy-release-4.12-presubmits.yaml
  ci-operator/jobs/redhat-cne/cloud-event-proxy/redhat-cne-cloud-event-proxy-release-4.13-presubmits.yaml
  ci-operator/jobs/redhat-cne/cloud-event-proxy/redhat-cne-cloud-event-proxy-release-4.14-presubmits.yaml
  ci-operator/jobs/redhat-cne/cloud-event-proxy/redhat-cne-cloud-event-proxy-release-4.15-presubmits.yaml
  ci-operator/jobs/redhat-cne/cloud-event-proxy/redhat-cne-cloud-event-proxy-release-4.16-presubmits.yaml
  ci-operator/jobs/redhat-cne/cloud-event-proxy/redhat-cne-cloud-event-proxy-release-4.17-presubmits.yaml
  ci-operator/jobs/redhat-cne/cloud-event-proxy/redhat-cne-cloud-event-proxy-release-4.18-presubmits.yaml
  ci-operator/jobs/redhat-cne/cloud-event-proxy/redhat-cne-cloud-event-proxy-release-4.19-presubmits.yaml
  ci-operator/jobs/redhat-cne/cloud-event-proxy/redhat-cne-cloud-event-proxy-release-4.20-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#64536 Updated the ClusterImageSet from 4.11 to 4.18 for e2e tests
  clusters/hosted-mgmt/hive/pools/ci-tools/ocp-release-4.18.20-x86-64-for-4.18.0-0-to-4.19.0-0_clusterimageset.yaml
Labels: lgtm, approved, rehearsals-ack

#64540 instaslice: use 4.18.10 release
  ci-operator/config/openshift/instaslice-operator/openshift-instaslice-operator-main.yaml
Labels: lgtm, approved, rehearsals-ack

#64234 OCPQE-29043: Use capabilities intranet for presubmit jobs
  ci-operator/config/openshift-priv/openshift-tests-private/openshift-priv-openshift-tests-private-master.yaml
  ci-operator/config/openshift-priv/openshift-tests-private/openshift-priv-openshift-tests-private-release-4.16.yaml
  ci-operator/config/openshift-priv/openshift-tests-private/openshift-priv-openshift-tests-private-release-4.17.yaml
  ci-operator/config/openshift-priv/openshift-tests-private/openshift-priv-openshift-tests-private-release-4.18.yaml
  ci-operator/config/openshift-priv/openshift-tests-private/openshift-priv-openshift-tests-private-release-4.19.yaml
  ci-operator/config/openshift-priv/openshift-tests-private/openshift-priv-openshift-tests-private-release-4.20.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-master.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20.yaml
  ci-operator/jobs/openshift-priv/openshift-tests-private/openshift-priv-openshift-tests-private-master-presubmits.yaml
  ci-operator/jobs/openshift-priv/openshift-tests-private/openshift-priv-openshift-tests-private-release-4.16-presubmits.yaml
  ci-operator/jobs/openshift-priv/openshift-tests-private/openshift-priv-openshift-tests-private-release-4.17-presubmits.yaml
  ci-operator/jobs/openshift-priv/openshift-tests-private/openshift-priv-openshift-tests-private-release-4.18-presubmits.yaml
  ci-operator/jobs/openshift-priv/openshift-tests-private/openshift-priv-openshift-tests-private-release-4.19-presubmits.yaml
  ci-operator/jobs/openshift-priv/openshift-tests-private/openshift-priv-openshift-tests-private-release-4.20-presubmits.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-master-presubmits.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-presubmits.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-presubmits.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-presubmits.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17-presubmits.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18-presubmits.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19-presubmits.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#64366 Refine 4.16 images
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__images.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#64513 skip CI steps for konflux chnages and remove Sonar jobs
  ci-operator/config/stolostron/multicluster-observability-operator/stolostron-multicluster-observability-operator-main.yaml
  ci-operator/config/stolostron/multicluster-observability-operator/stolostron-multicluster-observability-operator-release-2.10.yaml
  ci-operator/config/stolostron/multicluster-observability-operator/stolostron-multicluster-observability-operator-release-2.11.yaml
  ci-operator/config/stolostron/multicluster-observability-operator/stolostron-multicluster-observability-operator-release-2.12.yaml
  ci-operator/config/stolostron/multicluster-observability-operator/stolostron-multicluster-observability-operator-release-2.13.yaml
  ci-operator/jobs/stolostron/multicluster-observability-operator/stolostron-multicluster-observability-operator-main-postsubmits.yaml
  ci-operator/jobs/stolostron/multicluster-observability-operator/stolostron-multicluster-observability-operator-main-presubmits.yaml
  ci-operator/jobs/stolostron/multicluster-observability-operator/stolostron-multicluster-observability-operator-release-2.10-presubmits.yaml
  ci-operator/jobs/stolostron/multicluster-observability-operator/stolostron-multicluster-observability-operator-release-2.11-postsubmits.yaml
  ci-operator/jobs/stolostron/multicluster-observability-operator/stolostron-multicluster-observability-operator-release-2.11-presubmits.yaml
  ci-operator/jobs/stolostron/multicluster-observability-operator/stolostron-multicluster-observability-operator-release-2.12-postsubmits.yaml
  ci-operator/jobs/stolostron/multicluster-observability-operator/stolostron-multicluster-observability-operator-release-2.12-presubmits.yaml
  ci-operator/jobs/stolostron/multicluster-observability-operator/stolostron-multicluster-observability-operator-release-2.13-postsubmits.yaml
  ci-operator/jobs/stolostron/multicluster-observability-operator/stolostron-multicluster-observability-operator-release-2.13-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#64225 OADP-5782: Set HCP E2E and periodics to required
  ci-operator/config/openshift/oadp-operator/openshift-oadp-operator-master__4.19.yaml
  ci-operator/config/openshift/oadp-operator/openshift-oadp-operator-oadp-1.5__4.19.yaml
  ci-operator/jobs/openshift/oadp-operator/openshift-oadp-operator-master-periodics.yaml
  ci-operator/jobs/openshift/oadp-operator/openshift-oadp-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/oadp-operator/openshift-oadp-operator-oadp-1.5-periodics.yaml
  ci-operator/jobs/openshift/oadp-operator/openshift-oadp-operator-oadp-1.5-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#64548 make opm support rhel8
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15.yaml
Labels: lgtm, approved, rehearsals-ack

#64469 ACS: Add osd-aws-qa-e2e-tests as optional pre to 4.7 and x.y
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-4.7.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-x.y.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-4.7-presubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-x.y-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#64305 Retire 4.18 chain upgrade jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__multi-nightly-4.18-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-tests-private-retired/openshift-openshift-tests-private-release-4.18__arm64-nightly-4.18-upgrade-from-stable-4.11.yaml.retired
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#64509 OCPBUGS-55643: equinix-ocp-metal-quota-slice raised to 110
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: lgtm, approved, jira/valid-bug, rehearsals-ack, jira/valid-reference

#64552 snc-gather: Add logic to create GCP bucket for bundle upload
  ci-operator/step-registry/gather/snc/gather-snc-commands.sh
Labels: lgtm, approved, rehearsals-ack

#63130 [kubevirt-common-templates] add e2e test config for common templates v0.32
  ci-operator/config/kubevirt/common-templates/kubevirt-common-templates-release-v0.32.yaml
  ci-operator/jobs/kubevirt/common-templates/kubevirt-common-templates-release-v0.32-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#64159 Automate code to support hypershift libvirt on BM
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__hypershift_bm-4.18-nightly-x86.yaml
  ci-operator/jobs/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main-periodics.yaml
  ci-operator/step-registry/openshift-qe/cluster-density-v2/openshift-qe-cluster-density-v2-commands.sh
  ci-operator/step-registry/openshift-qe/crd-scale/openshift-qe-crd-scale-commands.sh
  ci-operator/step-registry/openshift-qe/installer/hypershift-mce-agent-metal3/OWNERS
  ci-operator/step-registry/openshift-qe/installer/hypershift-mce-agent-metal3/openshift-qe-installer-hypershift-mce-agent-metal3-workflow.metadata.json
  ci-operator/step-registry/openshift-qe/installer/hypershift-mce-agent-metal3/openshift-qe-installer-hypershift-mce-agent-metal3-workflow.yaml
  ci-operator/step-registry/openshift-qe/node-density-cni/openshift-qe-node-density-cni-commands.sh
  ci-operator/step-registry/openshift-qe/node-density/openshift-qe-node-density-commands.sh
Labels: lgtm, approved, rehearsals-ack

#64561 Konflux: Add RBAC for the EphemeralCluster controller
  clusters/app.ci/assets/dptp-controller-manager.yaml
Labels: lgtm, approved, rehearsals-ack

#64567 OCPQE-29043: Use capabilities intranet in telcov
  ci-operator/config/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main__ci-4.19.yaml
  ci-operator/config/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main__ci-4.20.yaml
  ci-operator/config/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main__nightly-4.18.yaml
  ci-operator/config/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main__nightly-4.19.yaml
  ci-operator/config/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main__nightly-4.20.yaml
  ci-operator/config/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main__telco-operators-dast-4.16.yaml
  ci-operator/config/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main__telco-operators-dast-4.17.yaml
  ci-operator/jobs/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#64547 update OTA cherry-pick approver
  core-services/prow/02_config/openshift/cluster-version-operator/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#64573 Bump go version bond-cni
  ci-operator/config/openshift/bond-cni/openshift-bond-cni-main.yaml
Labels: lgtm, approved, rehearsals-ack

#64574 telco5g: Reduce SNO testing
  ci-operator/step-registry/telco5g/cnf/tests/telco5g-cnf-tests-commands.sh
Labels: lgtm, approved, rehearsals-ack

#64530 Renamed ci-docs from master to main
  ci-operator/config/openshift/ci-docs/openshift-ci-docs-main.yaml
  ci-operator/jobs/openshift/ci-docs/openshift-ci-docs-main-postsubmits.yaml
  ci-operator/jobs/openshift/ci-docs/openshift-ci-docs-main-presubmits.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#64586 release-controllers: enable mirror cleanup
  clusters/app.ci/release-mirror-cleanup-controller/deployment.yaml
  hack/generators/release-controllers/content/release_mirror_cleanup_controller_resources.py
Labels: lgtm, approved, rehearsals-ack

#64585 NETOBSERV-2159: Update NetObserv FBC
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__multi-nightly.yaml
  ci-operator/step-registry/netobserv/install-operator/netobserv-install-operator-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#64578 DPTP-4387: Update BASE_DOMAIN
  ci-operator/step-registry/ipi/conf/aws/default/ipi-conf-aws-default-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#64592 NO-JIRA: Downgrade operator-sdk image version for CMA and VPA operators
  ci-operator/config/openshift/custom-metrics-autoscaler-operator/openshift-custom-metrics-autoscaler-operator-main.yaml
  ci-operator/config/openshift/vertical-pod-autoscaler-operator/openshift-vertical-pod-autoscaler-operator-main.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#63968 Remove Terraform and Altinfra Images from Installer
  ci-operator/config/openshift/installer/openshift-installer-main.yaml
  ci-operator/config/openshift/installer/openshift-installer-main__altinfra.yaml
  ci-operator/config/openshift/installer/openshift-installer-main__okd-scos.yaml
  ci-operator/config/openshift/installer/openshift-installer-main__terraform-okd-scos.yaml
  ci-operator/config/openshift/installer/openshift-installer-main__terraform.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.19.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.19__altinfra.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.19__okd-scos.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.19__terraform.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.20.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.20__altinfra.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.20__terraform.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-main-postsubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-main-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.19-postsubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.19-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.20-postsubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.20-presubmits.yaml
  core-services/image-mirroring/openshift/mapping_origin_scos-4_19
  core-services/image-mirroring/openshift/mapping_origin_scos-4_20
Labels: lgtm, approved, tide/merge-method-squash, rehearsals-ack

#64537 CNTRLPLANE-777: Add AKS e2e as an informing test on the CI payload release controllers for 4.20
  ci-operator/step-registry/hypershift/azure/aks/conformance/hypershift-azure-aks-conformance-workflow.yaml
  ci-operator/step-registry/hypershift/azure/aks/e2e/hypershift-azure-aks-e2e-workflow.yaml
  core-services/release-controller/_releases/release-ocp-4.20-ci.json
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#64157 CORS-3874: Pre-submit job for "Add ability to choose ingress controller subnets at installation"
  ci-operator/config/openshift/installer/openshift-installer-main.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.19.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.20.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-main-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.19-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.20-presubmits.yaml
  ci-operator/step-registry/ipi/conf/aws/sharednetwork/ipi-conf-aws-sharednetwork-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#63768 NETOBSERV-2128 Tests for NetObserv Perf scripts and image building in Prow
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/OWNERS
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-netobserv-perf-tests.yaml
  ci-operator/jobs/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-netobserv-perf-tests-postsubmits.yaml
  ci-operator/jobs/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-netobserv-perf-tests-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#64600 Add highperf machinesets for build03
  clusters/build-clusters/build03/ci-scheduling-webhook/ci-builds-highperf-worker-amd64.yaml
Labels: lgtm, approved, rehearsals-ack

#64558 Simply the logic of opm installation
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15.yaml
Labels: lgtm, approved, rehearsals-ack

#64373 OCPQE-29207: Implement UPI with Realtime Kernel
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19-periodics.yaml
  ci-operator/step-registry/baremetal/lab/rt-kernel/OWNERS
  ci-operator/step-registry/baremetal/lab/rt-kernel/baremetal-lab-rt-kernel-commands.sh
  ci-operator/step-registry/baremetal/lab/rt-kernel/baremetal-lab-rt-kernel-ref.metadata.json
  ci-operator/step-registry/baremetal/lab/rt-kernel/baremetal-lab-rt-kernel-ref.yaml
  ci-operator/step-registry/baremetal/lab/upi/conf/baremetal-lab-upi-conf-chain.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#64350 OTA-1492: cincinnator: add test/operator-e2e-new-ocp-published-graph-data-fips
  ci-operator/config/openshift/cincinnati-operator/openshift-cincinnati-operator-master.yaml
  ci-operator/jobs/openshift/cincinnati-operator/openshift-cincinnati-operator-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#64605 Remove unused AMI config
  ci-operator/step-registry/ipi/conf/aws/ipi-conf-aws-commands.sh
Labels: lgtm, approved, rehearsals-ack

#63926 Update OMR 2.0.6 image
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__omr-ocp412-unreleased.yaml
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__omr-ocp413.yaml
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__omr-ocp414-unreleased.yaml
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__omr-ocp415-unreleased.yaml
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__omr-ocp416-unreleased.yaml
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__omr-ocp417-unreleased.yaml
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__omr-ocp418-unreleased.yaml
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__omr-ocp419-unreleased.yaml
  ci-operator/jobs/quay/quay-tests/quay-quay-tests-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#64612 Remove azure oidc job from 4.14-upgrade-from-stable-4.13
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly-4.14-upgrade-from-stable-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-nightly-4.14-upgrade-from-stable-4.13.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#63327 OCM-14088 | ci: Add oidc-cli-login step
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__amd64-nightly.yaml
  ci-operator/step-registry/cucushift/hypershift-extended/external-oidc/console-app/OWNERS
  ci-operator/step-registry/cucushift/hypershift-extended/external-oidc/console-app/redirect-uri/OWNERS
  ci-operator/step-registry/cucushift/hypershift-extended/external-oidc/console-app/redirect-uri/add/OWNERS
  ci-operator/step-registry/cucushift/hypershift-extended/external-oidc/console-app/redirect-uri/add/cucushift-hypershift-extended-external-oidc-console-app-redirect-uri-add-commands.sh
  ci-operator/step-registry/cucushift/hypershift-extended/external-oidc/console-app/redirect-uri/add/cucushift-hypershift-extended-external-oidc-console-app-redirect-uri-add-ref.metadata.json
  ci-operator/step-registry/rosa/conf/external-oidc/OWNERS
  ci-operator/step-registry/rosa/conf/external-oidc/create/OWNERS
  ci-operator/step-registry/rosa/conf/external-oidc/create/rosa-conf-external-oidc-create-commands.sh
  ci-operator/step-registry/rosa/conf/external-oidc/create/rosa-conf-external-oidc-create-ref.metadata.json
  ci-operator/step-registry/rosa/conf/external-oidc/create/rosa-conf-external-oidc-create-ref.yaml
  ci-operator/step-registry/rosa/lifecycle/external-auth-advanced/rosa-lifecycle-external-auth-advanced-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#64478 ACS: Sort out GKE oldest/latest jobs
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-x.y.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-presubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-nightlies-postsubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-x.y-postsubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-x.y-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#64579 Add ABI team members to add cherry-pick-approved label
  core-services/prow/02_config/openshift/oc/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#64376 Install krew and commatrix plugin
  ci-operator/step-registry/network-flow-matrix/tests/network-flow-matrix-tests-commands.sh
Labels: lgtm, approved, rehearsals-ack

#64493 bump minor upgrade presubmit jobs in OVNK/CNO
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-master__4.20-upgrade-from-stable-4.19.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.19__4.19-upgrade-from-stable-4.18.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master__4.20-upgrade-from-stable-4.19.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.19__4.19-upgrade-from-stable-4.18.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.19-presubmits.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master-presubmits.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.19-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#64622 telcov10n: Remove unused steps
  ci-operator/step-registry/telcov10n/functional/far-edge-vran-ran-ptp/OWNERS
  ci-operator/step-registry/telcov10n/functional/far-edge-vran-ran-ptp/telcov10n-functional-far-edge-vran-ran-ptp-workflow.metadata.json
  ci-operator/step-registry/telcov10n/functional/far-edge-vran-ran-ptp/telcov10n-functional-far-edge-vran-ran-ptp-workflow.yaml
  ci-operator/step-registry/telcov10n/functional/ocp-far-edge-vran-deployment/OWNERS
  ci-operator/step-registry/telcov10n/functional/ocp-far-edge-vran-deployment/telcov10n-functional-ocp-far-edge-vran-deployment-commands.sh
  ci-operator/step-registry/telcov10n/functional/ocp-far-edge-vran-deployment/telcov10n-functional-ocp-far-edge-vran-deployment-ref.metadata.json
  ci-operator/step-registry/telcov10n/functional/ocp-far-edge-vran-deployment/telcov10n-functional-ocp-far-edge-vran-deployment-ref.yaml
  ci-operator/step-registry/telcov10n/functional/ocp-far-edge-vran-reporting/OWNERS
  ci-operator/step-registry/telcov10n/functional/ocp-far-edge-vran-reporting/telcov10n-functional-ocp-far-edge-vran-reporting-commands.sh
  ci-operator/step-registry/telcov10n/functional/ocp-far-edge-vran-reporting/telcov10n-functional-ocp-far-edge-vran-reporting-ref.metadata.json
  ci-operator/step-registry/telcov10n/functional/ocp-far-edge-vran-reporting/telcov10n-functional-ocp-far-edge-vran-reporting-ref.yaml
  ci-operator/step-registry/telcov10n/functional/ocp-far-edge-vran-tests/OWNERS
  ci-operator/step-registry/telcov10n/functional/ocp-far-edge-vran-tests/telcov10n-functional-ocp-far-edge-vran-tests-commands.sh
  ci-operator/step-registry/telcov10n/functional/ocp-far-edge-vran-tests/telcov10n-functional-ocp-far-edge-vran-tests-ref.metadata.json
  ci-operator/step-registry/telcov10n/functional/ocp-far-edge-vran-tests/telcov10n-functional-ocp-far-edge-vran-tests-ref.yaml
  ci-operator/step-registry/telcov10n/functional/ocp-olm-setup/OWNERS
  ci-operator/step-registry/telcov10n/functional/ocp-olm-setup/telcov10n-functional-ocp-olm-setup-commands.sh
  ci-operator/step-registry/telcov10n/functional/ocp-olm-setup/telcov10n-functional-ocp-olm-setup-ref.metadata.json
  ci-operator/step-registry/telcov10n/functional/ocp-olm-setup/telcov10n-functional-ocp-olm-setup-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#63699 CNTRLPLANE-354: Add step which observes cert rotation
  ci-operator/config/openshift/cluster-kube-apiserver-operator/openshift-cluster-kube-apiserver-operator-main.yaml
  ci-operator/jobs/openshift/cluster-kube-apiserver-operator/openshift-cluster-kube-apiserver-operator-main-presubmits.yaml
  ci-operator/step-registry/openshift/e2e/cert-rotation/observe/OWNERS
  ci-operator/step-registry/openshift/e2e/cert-rotation/observe/openshift-e2e-cert-rotation-observe-commands.sh
  ci-operator/step-registry/openshift/e2e/cert-rotation/observe/openshift-e2e-cert-rotation-observe-ref.metadata.json
  ci-operator/step-registry/openshift/e2e/cert-rotation/observe/openshift-e2e-cert-rotation-observe-ref.yaml
  ci-operator/step-registry/openshift/e2e/cert-rotation/short/OWNERS
  ci-operator/step-registry/openshift/e2e/cert-rotation/short/openshift-e2e-cert-rotation-short-workflow.metadata.json
  ci-operator/step-registry/openshift/e2e/cert-rotation/short/openshift-e2e-cert-rotation-short-workflow.yaml
  ci-operator/step-registry/openshift/e2e/cert-rotation/test/openshift-e2e-cert-rotation-test-commands.sh
  core-services/ci-chat-bot/workflows-config.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#64334 converter release jobs
  ci-operator/config/openshift-service-mesh/istio/openshift-service-mesh-istio-master.yaml
  ci-operator/jobs/openshift-service-mesh/istio/openshift-service-mesh-istio-master-presubmits.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#64321 MGMT-20501: Change the assisted bare metal RESTful API conformance tests to use the tests image from the OCP payload
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-assisted-version-placeholder.yaml
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-main__edge.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-assisted-version-placeholder.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master__edge.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-assisted-version-placeholder.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-master__edge.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-assisted-version-placeholder.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-cloud_hotfix_releases.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.10.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.11.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.12.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.13.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.9.yaml
  ci-operator/step-registry/assisted/baremetal/test/assisted-baremetal-test-commands.sh
  ci-operator/step-registry/assisted/baremetal/test/assisted-baremetal-test-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#63960 enable reusing preserved sp and mi resources
  ci-operator/step-registry/aks/provision/aks-provision-commands.sh
  ci-operator/step-registry/azure/provision/service-principal/hypershift/azure-provision-service-principal-hypershift-ref.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/aks/hypershift/ephemeral-creds/provision/cucushift-installer-rehearse-azure-aks-hypershift-ephemeral-creds-provision-chain.yaml
  ci-operator/step-registry/hypershift/azure/aks/attach-kv/hypershift-azure-aks-attach-kv-commands.sh
  ci-operator/step-registry/hypershift/azure/aks/attach-kv/hypershift-azure-aks-attach-kv-ref.yaml
  ci-operator/step-registry/hypershift/azure/create/hypershift-azure-create-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#64619 Fix incorrect zone reading
  ci-operator/step-registry/ipi/conf/aws/custom-vpc/ipi-conf-aws-custom-vpc-commands.sh
Labels: lgtm, approved, rehearsals-ack

#64627 ACS: Add `sensor-integration-tests` to OCP 4.12 nightlies
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies__ocp-4-12.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-nightlies-postsubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#64274 ci-tools: remove konflux occurences & update e2e registry credentials to use quay
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
  ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-periodics.yaml
  ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
  ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#64584 SPLAT-2039: Created new image for vSphere hybrid env jobs
  core-services/image-mirroring/_config.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#64603 OCPQE-29571 - Use the release-4.18 RHCOS image list for bastion provisioning for AWS
  ci-operator/step-registry/aws/provision/bastionhost/aws-provision-bastionhost-commands.sh
Labels: lgtm, approved, rehearsals-ack

#64631 NO-JIRA: Update cherry-pick approvers
  core-services/prow/02_config/openshift/cli-manager-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cli-manager/_pluginconfig.yaml
  core-services/prow/02_config/openshift/jobset-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/kubernetes-sigs-jobset/_pluginconfig.yaml
  core-services/prow/02_config/openshift/kubernetes-sigs-lws/_pluginconfig.yaml
  core-services/prow/02_config/openshift/lws-operator/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#64625 Use build root from repository bond-cni
  ci-operator/config/openshift/bond-cni/openshift-bond-cni-main.yaml
  ci-operator/jobs/openshift/bond-cni/openshift-bond-cni-main-postsubmits.yaml
  ci-operator/jobs/openshift/bond-cni/openshift-bond-cni-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#64590 config: add coreos/rhel-coreos-config
  ci-operator/config/coreos/rhel-coreos-config/OWNERS
  ci-operator/config/coreos/rhel-coreos-config/coreos-rhel-coreos-config-main.yaml
  ci-operator/config/coreos/rhel-coreos-config/coreos-rhel-coreos-config-rhel-coreos-config-main.yaml
  ci-operator/config/openshift/os/openshift-os-master.yaml
  ci-operator/jobs/coreos/rhel-coreos-config/OWNERS
  ci-operator/jobs/coreos/rhel-coreos-config/coreos-rhel-coreos-config-main-postsubmits.yaml
  ci-operator/jobs/coreos/rhel-coreos-config/coreos-rhel-coreos-config-main-presubmits.yaml
  ci-operator/jobs/coreos/rhel-coreos-config/coreos-rhel-coreos-config-rhel-coreos-config-main-postsubmits.yaml
  ci-operator/jobs/coreos/rhel-coreos-config/coreos-rhel-coreos-config-rhel-coreos-config-main-presubmits.yaml
  ci-operator/jobs/openshift/os/openshift-os-master-presubmits.yaml
  core-services/prow/02_config/coreos/rhel-coreos-config/OWNERS
  core-services/prow/02_config/coreos/rhel-coreos-config/_pluginconfig.yaml
  core-services/prow/02_config/coreos/rhel-coreos-config/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#64279 MGMT-19567: splitting the pre-submit CI jobs of assisted-installer to 2 stages.
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-master__edge.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.10.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.11.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.12.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.13.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.9.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-master-presubmits.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.10-presubmits.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.11-presubmits.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.12-presubmits.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.13-presubmits.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-release-ocm-2.9-presubmits.yaml
  core-services/pipeline-controller/lgtm-config.yaml
  core-services/prow/02_config/openshift/assisted-installer/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#62387 ESO-42: Prow configs for external-secrets-operator and external-secrets-operator-release repos
  ci-operator/config/openshift/external-secrets-operator-release/OWNERS
  ci-operator/config/openshift/external-secrets-operator-release/openshift-external-secrets-operator-release-main.yaml
  ci-operator/config/openshift/external-secrets-operator-release/openshift-external-secrets-operator-release-release-0.14.yaml
  ci-operator/config/openshift/external-secrets-operator/OWNERS
  ci-operator/config/openshift/external-secrets-operator/openshift-external-secrets-operator-main.yaml
  ci-operator/config/openshift/external-secrets-operator/openshift-external-secrets-operator-release-0.14.yaml
  ci-operator/jobs/openshift/external-secrets-operator-release/OWNERS
  ci-operator/jobs/openshift/external-secrets-operator-release/openshift-external-secrets-operator-release-main-presubmits.yaml
  ci-operator/jobs/openshift/external-secrets-operator-release/openshift-external-secrets-operator-release-release-0.14-presubmits.yaml
  ci-operator/jobs/openshift/external-secrets-operator/OWNERS
  ci-operator/jobs/openshift/external-secrets-operator/openshift-external-secrets-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/external-secrets-operator/openshift-external-secrets-operator-release-0.14-presubmits.yaml
  core-services/prow/02_config/openshift/external-secrets-operator-release/OWNERS
  core-services/prow/02_config/openshift/external-secrets-operator-release/_pluginconfig.yaml
  core-services/prow/02_config/openshift/external-secrets-operator-release/_prowconfig.yaml
  core-services/prow/02_config/openshift/external-secrets-operator/OWNERS
  core-services/prow/02_config/openshift/external-secrets-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/external-secrets-operator/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#64483 add unit testing for clusters-service
  ci-operator/config/openshift-online/ocm-api-metamodel/openshift-online-ocm-api-metamodel-main.yaml
  ci-operator/config/openshift-online/ocm-cluster-service/openshift-online-ocm-cluster-service-main.yaml
  ci-operator/jobs/openshift-online/ocm-cluster-service/openshift-online-ocm-cluster-service-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#64589 4.20 branching day tasks
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-master.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.20.yaml
Labels: lgtm, approved, rehearsals-ack

#64618 snc: Add bucket test as part of if statement to avoid failure
  ci-operator/step-registry/gather/snc/gather-snc-commands.sh
Labels: lgtm, approved, rehearsals-ack

#64628 ACS: Remove gke-perf-scale-tests and perf-scale-tests
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-stable-scanner-v4-install.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-4.6.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-presubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-4.6-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#64638 Include jq for telco-ref ci
  ci-operator/config/openshift-kni/telco-reference/openshift-kni-telco-reference-main.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#64650 Add a PodDisruptionBudget for the MTO
  clusters/build-clusters/multiarch_tuning_operator/admin_40_pdb.yaml
Labels: lgtm, approved, rehearsals-ack

#64599 Security Profile Operator Roll back to golang 1.23
  ci-operator/config/openshift/security-profiles-operator/openshift-security-profiles-operator-konflux.yaml
Labels: lgtm, approved, rehearsals-ack

#64327 Bump orion to v0.0.11
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__aws-4.17-nightly-x86.yaml
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__aws-4.18-nightly-x86.yaml
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__aws-4.19-nightly-x86.yaml
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__aws-4.20-nightly-x86.yaml
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__write_jobs_to_gsheet.yaml
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-netobserv-perf-tests__netobserv-aws-4.19-nightly-x86.yaml
  ci-operator/config/openshift/ols-load-generator/openshift-ols-load-generator-main.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.20.yaml
  ci-operator/step-registry/openshift-qe/orion/cluster-density/openshift-qe-orion-cluster-density-ref.yaml
  ci-operator/step-registry/openshift-qe/orion/crd-scale/openshift-qe-orion-crd-scale-ref.yaml
  ci-operator/step-registry/openshift-qe/orion/node-density-cni/openshift-qe-orion-node-density-cni-ref.yaml
  ci-operator/step-registry/openshift-qe/orion/node-density/openshift-qe-orion-node-density-ref.yaml
  ci-operator/step-registry/openshift-qe/orion/openshift-qe-orion-commands.sh
  ci-operator/step-registry/openshift-qe/orion/openshift-qe-orion-ref.yaml
  ci-operator/step-registry/openshift-qe/orion/udn-l3/openshift-qe-orion-udn-l3-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#64215 removed rhcos labels
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__aws-4.15-nightly-x86.yaml
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__metal-4.19-latest-x86.yaml
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__vsphere-4.18-nightly-x86.yaml
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__vsphere-4.19-nightly-x86.yaml
  ci-operator/jobs/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main-presubmits.yaml
  ci-operator/step-registry/openshift-qe/workers-infra-workload/openshift-qe-workers-infra-workload-commands.sh
  ci-operator/step-registry/workers-scale/workers-scale-commands.sh
Labels: lgtm, approved, rehearsals-ack

#64670 [AUTO]enhance opm
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16.yaml
Labels: lgtm, approved, rehearsals-ack

#64643 NO-ISSUE: Fix NetworkManager usage of DNS servers
  ci-operator/step-registry/assisted/ofcir/setup/assisted-ofcir-setup-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#64677 Add Slack notification for telco KPI jobs
  ci-operator/config/openshift-kni/eco-ci-cd/.config.prowgen
  ci-operator/config/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main__nightly-4.19-ztp-kpis.yaml
  ci-operator/config/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main__nightly-4.20-ztp-kpis.yaml
  ci-operator/config/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-ztp-left-shifting-kpi__ci-4.19.yaml
  ci-operator/jobs/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main-periodics.yaml
  ci-operator/jobs/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-ztp-left-shifting-kpi-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#64671 OCPQE-29612: Fix aws-ipi-private-byo-subnet-role-mini-perm-arm-f28-destructive
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__multi-nightly.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#60982 MULTIARCH-5178:Add conformance tests in CI for agent based HyperShift heterogeneous Power and X86 NodePools
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.17__periodics-mce.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.18__periodics-mce.yaml
  ci-operator/step-registry/hypershift/mce/power/create/ibmcloud-workers/lb/hypershift-mce-power-create-ibmcloud-workers-lb-commands.sh
  ci-operator/step-registry/hypershift/mce/power/destroy/hypershift-mce-power-destroy-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#64687 POST-BRANCHING [4.19]: jira validation criteria
  core-services/jira-lifecycle-plugin/config.yaml
Labels: lgtm, approved, rehearsals-ack

#64228 :broom: Turn off 4.17 cluster pool
  clusters/hosted-mgmt/hive/pools/serverless/serverless-ocp-4-15-amd64-aws-us-east-1_clusterpool.yaml
  clusters/hosted-mgmt/hive/pools/serverless/serverless-ocp-4-16-amd64-aws-us-east-1_clusterpool.yaml
  clusters/hosted-mgmt/hive/pools/serverless/serverless-ocp-4-17-amd64-aws-us-east-1_clusterpool.yaml
  clusters/hosted-mgmt/hive/pools/serverless/serverless-ocp-4-18-amd64-aws-us-east-1_clusterpool.yaml
Labels: lgtm, approved, kind/cleanup, rehearsals-ack

#64689 ESO-42: Set all external-secrets-operator tests as optional until stable repo
  ci-operator/config/openshift/external-secrets-operator-release/openshift-external-secrets-operator-release-main.yaml
  ci-operator/config/openshift/external-secrets-operator-release/openshift-external-secrets-operator-release-release-0.14.yaml
  ci-operator/config/openshift/external-secrets-operator/openshift-external-secrets-operator-main.yaml
  ci-operator/config/openshift/external-secrets-operator/openshift-external-secrets-operator-release-0.14.yaml
  ci-operator/jobs/openshift/external-secrets-operator-release/openshift-external-secrets-operator-release-main-presubmits.yaml
  ci-operator/jobs/openshift/external-secrets-operator-release/openshift-external-secrets-operator-release-release-0.14-presubmits.yaml
  ci-operator/jobs/openshift/external-secrets-operator/openshift-external-secrets-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/external-secrets-operator/openshift-external-secrets-operator-release-0.14-presubmits.yaml
  core-services/prow/02_config/openshift/external-secrets-operator-release/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#64679 CAPK CI: update ODF subscription channel
  ci-operator/config/openshift-priv/cluster-api-provider-kubevirt/openshift-priv-cluster-api-provider-kubevirt-release-4.19.yaml
  ci-operator/config/openshift-priv/cluster-api-provider-kubevirt/openshift-priv-cluster-api-provider-kubevirt-release-4.20.yaml
  ci-operator/config/openshift/cluster-api-provider-kubevirt/openshift-cluster-api-provider-kubevirt-main.yaml
  ci-operator/config/openshift/cluster-api-provider-kubevirt/openshift-cluster-api-provider-kubevirt-release-4.18.yaml
  ci-operator/config/openshift/cluster-api-provider-kubevirt/openshift-cluster-api-provider-kubevirt-release-4.19.yaml
  ci-operator/config/openshift/cluster-api-provider-kubevirt/openshift-cluster-api-provider-kubevirt-release-4.20.yaml
Labels: lgtm, approved, rehearsals-ack

#64692 POST-BRANCHING [4.19]: fast forward future branch
  ci-operator/jobs/infra-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#63374 Update gcp jobs to use sustaining profile for 4.12
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__automated-release.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#64642 CNTRLPLANE-839: Add TestOnCreateAPIUX to the Azure tests
  ci-operator/step-registry/hypershift/azure/run-e2e/hypershift-azure-run-e2e-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#64696 Metal should use sharding args in their test step
  ci-operator/step-registry/baremetalds/e2e/test/baremetalds-e2e-test-commands.sh
  ci-operator/step-registry/baremetalds/e2e/test/baremetalds-e2e-test-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#64230 MGMT-19567: splitting the pre-submit CI jobs of assisted-service to 2 stages.
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.10.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.11.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.12.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.13.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.9.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.10-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.11-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.12-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.13-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.9-presubmits.yaml
  core-services/pipeline-controller/lgtm-config.yaml
  core-services/prow/02_config/openshift/assisted-service/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#64629 Use image pushed to CI instead of src
  ci-operator/config/openshift/cluster-control-plane-machine-set-operator/openshift-cluster-control-plane-machine-set-operator-release-4.19__periodics.yaml
  ci-operator/config/openshift/cluster-control-plane-machine-set-operator/openshift-cluster-control-plane-machine-set-operator-release-4.20__periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#64429 AUTOSCALE-59: Scheduling config for autoscaling team's rebasebot for karpenter
  ci-operator/config/openshift-eng/rebasebot/openshift-eng-rebasebot-main.yaml
  ci-operator/jobs/openshift-eng/rebasebot/openshift-eng-rebasebot-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#64699 Update ibm-roks-toolkit-base.yaml
  clusters/app.ci/supplemental-ci-images/ibm-roks-toolkit-base/ibm-roks-toolkit-base.yaml
Labels: lgtm, approved, rehearsals-ack

#64712 CNF-17847: fix ptp ci abnormal exit
  ci-operator/step-registry/telco5g/ptp/tests/telco5g-ptp-tests-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#64691 workload-analyzer: skip e2e tests for rulesets changes
  ci-operator/config/codeready-toolchain/workload-analyzer/codeready-toolchain-workload-analyzer-master.yaml
  ci-operator/jobs/codeready-toolchain/workload-analyzer/codeready-toolchain-workload-analyzer-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#63502 CNTRLPLANE-371: Add techpreview jobs for openshift/kubernetes
  ci-operator/config/openshift/kubernetes/openshift-kubernetes-master.yaml
  ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#64448 Use Standard_D8s_v5
  ci-operator/config/openshift/release/openshift-release-master__ci-4.19-upgrade-from-stable-4.18.yaml
Labels: lgtm, approved, rehearsals-ack

#64714 Metal shouldn't overwrite TEST_ARGS
  ci-operator/step-registry/baremetalds/e2e/test/baremetalds-e2e-test-commands.sh
Labels: lgtm, approved, rehearsals-ack

#64715 stolostron/search Enable e2e on release branches
  ci-operator/config/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.11.yaml
  ci-operator/config/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.12.yaml
  ci-operator/config/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.13.yaml
  ci-operator/jobs/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.11-presubmits.yaml
  ci-operator/jobs/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.12-presubmits.yaml
  ci-operator/jobs/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.13-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#64436 MULTIARCH-5326 use multi payload as initial/latest for MA 4.19 jobs
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.19-upgrade-from-nightly-4.18.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.19-upgrade-from-stable-4.18.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.19.yaml
Labels: lgtm, approved, rehearsals-ack

#64719 apply go 1.23 as the base image for cluster curator in mce 2.9
  ci-operator/config/stolostron/cluster-curator-controller/stolostron-cluster-curator-controller-backplane-2.9.yaml
Labels: lgtm, approved, rehearsals-ack

#64669 [AUTO]tune parameter for olm stress
  ci-operator/step-registry/openshift-extended/olm-test/burner-pkg-ins-v1/openshift-extended-olm-test-burner-pkg-ins-v1-ref.yaml
  ci-operator/step-registry/openshift-extended/olm-test/burner-pkg-ins/openshift-extended-olm-test-burner-pkg-ins-ref.yaml
  ci-operator/step-registry/openshift/e2e/test/olm-qe/stress/burner/openshift-e2e-test-olm-qe-stress-burner-chain.yaml
  ci-operator/step-registry/openshift/e2e/test/olm-qe/stress/golang/openshift-e2e-test-olm-qe-stress-golang-chain.yaml
  ci-operator/step-registry/openshift/e2e/test/olm-qe/stress/openshift-e2e-test-olm-qe-stress-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#64707 no-jira: add jcpowermac to nutanix reviewers/approvers
  OWNERS_ALIASES
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#64705 remove 4.18 aks hcp jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#64724 Fix config in repo rhel-coreos-config to recover job periodic-openshi…
  ci-operator/config/coreos/rhel-coreos-config/coreos-rhel-coreos-config-rhel-coreos-config-main.yaml
  ci-operator/jobs/coreos/rhel-coreos-config/coreos-rhel-coreos-config-rhel-coreos-config-main-postsubmits.yaml
  ci-operator/jobs/coreos/rhel-coreos-config/coreos-rhel-coreos-config-rhel-coreos-config-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#64216 fix mce-aws
  ci-operator/step-registry/hypershift/mce/aws/create/hypershift-mce-aws-create-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#64657 SPLAT-2192: external/aws: temp skip perm failure. #64359 perm fixes
  ci-operator/step-registry/openshift/e2e/external/aws/openshift-e2e-external-aws-workflow.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#64554 OCPQE-29551: add cluster-api-actuator-pkg 4.20 image
  ci-operator/config/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-release-4.20__images.yaml
  ci-operator/jobs/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-release-4.20-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-release-4.20-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#64602 Export proxy before running OC command
  ci-operator/step-registry/cucushift/e2e/cucushift-e2e-commands.sh
  ci-operator/step-registry/cucushift/upgrade/prepare/cucushift-upgrade-prepare-commands.sh
Labels: lgtm, approved, rehearsals-ack

#64187 [PERFSCALE-3886] Isolate cluster profiles through Vault
  ci-operator/config/cloud-bulldozer/e2e-benchmarking/cloud-bulldozer-e2e-benchmarking-master.yaml
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__metal-4.16-latest-x86.yaml
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__metal-rhoso-x86.yaml
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__metal-telco-x86.yaml
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__metal-x86.yaml
  ci-operator/config/redhat-performance/jetlag/redhat-performance-jetlag-main.yaml
  ci-operator/step-registry/openshift-qe/installer/bm/deploy/openshift-qe-installer-bm-deploy-commands.sh
  ci-operator/step-registry/openshift-qe/installer/bm/deploy/openshift-qe-installer-bm-deploy-ref.yaml
Labels: lgtm, approved, rehearsals-ack, network-access-rehearsals-ok

#64655 Add vm-host zonal jobs for mao
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-main.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#64727 apply go 1.23 as the base builder for cluster-image-set in mce 2.9 an…
  ci-operator/config/stolostron/cluster-image-set-controller/stolostron-cluster-image-set-controller-backplane-2.9.yaml
  ci-operator/config/stolostron/cluster-image-set-controller/stolostron-cluster-image-set-controller-main.yaml
Labels: lgtm, approved, rehearsals-ack

#64470 Standard d8as v5
  ci-operator/config/openshift/release/openshift-release-master__ci-4.20-upgrade-from-stable-4.19.yaml
Labels: lgtm, approved, rehearsals-ack

#64545 rust:boot-root-1.79.0 HOME=/go
  clusters/app.ci/supplemental-ci-images/cincinnati-ci/rust.yaml
Labels: lgtm, approved, rehearsals-ack

#64534 ACS: Add ROSA coverage to release-4.6, -4.7 and -x.y
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-4.6.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-4.7.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-x.y.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-4.6-postsubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-4.7-postsubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-4.7-presubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-x.y-postsubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-x.y-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#64709 telcov10: Add capabilities for builder05
  ci-operator/config/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main__hcp-cnf-4.17.yaml
  ci-operator/config/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main__hcp-cnf-4.18.yaml
  ci-operator/jobs/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main-periodics.yaml
  ci-operator/step-registry/telcov10n/functional/hcp-cnf/tests/telcov10n-functional-hcp-cnf-tests-commands.sh
Labels: lgtm, approved, rehearsals-ack

#64748 Update bpfman contributors
  core-services/prow/02_config/openshift/bpfman-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/bpfman/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#63726 Chaos 419 ROSA tests
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__rosa-4.19-nightly.yaml
  ci-operator/jobs/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main-periodics.yaml
  ci-operator/jobs/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main-presubmits.yaml
Labels: lgtm, approved, tide/merge-method-squash, rehearsals-ack

#64615 OVN BGP: set hostname on external containers
  ci-operator/step-registry/baremetalds/e2e/ovn/bgp/pre/baremetalds-e2e-ovn-bgp-pre-commands.sh
Labels: lgtm, approved, rehearsals-ack

#64595 cnf network: added metric tests and reporter post step
  ci-operator/config/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main__cnf-network-4.17.yaml
  ci-operator/step-registry/telcov10n/functional/cnf-network/cnf-reporter/OWNERS
  ci-operator/step-registry/telcov10n/functional/cnf-network/cnf-reporter/telcov10n-functional-cnf-network-cnf-reporter-commands.sh
  ci-operator/step-registry/telcov10n/functional/cnf-network/cnf-reporter/telcov10n-functional-cnf-network-cnf-reporter-ref.metadata.json
  ci-operator/step-registry/telcov10n/functional/cnf-network/cnf-reporter/telcov10n-functional-cnf-network-cnf-reporter-ref.yaml
  ci-operator/step-registry/telcov10n/functional/cnf-network/cnf-tests/telcov10n-functional-cnf-network-cnf-tests-commands.sh
  ci-operator/step-registry/telcov10n/functional/cnf-network/metrics-daemon-tests/OWNERS
  ci-operator/step-registry/telcov10n/functional/cnf-network/metrics-daemon-tests/telcov10n-functional-cnf-network-metrics-daemon-tests-commands.sh
  ci-operator/step-registry/telcov10n/functional/cnf-network/metrics-daemon-tests/telcov10n-functional-cnf-network-metrics-daemon-tests-ref.metadata.json
  ci-operator/step-registry/telcov10n/functional/cnf-network/metrics-daemon-tests/telcov10n-functional-cnf-network-metrics-daemon-tests-ref.yaml
  ci-operator/step-registry/telcov10n/functional/cnf-network/ocp-setup/telcov10n-functional-cnf-network-ocp-setup-workflow.yaml
Labels: lgtm, approved, rehearsals-ack
