Repository openshift/release, pull requests merged in 2025-02, with the labels that each got.

#61194 bump go version to 1.22 as required by 4.16 release [for installer-aro-wrapper]
  ci-operator/config/openshift-priv/installer-aro-wrapper/openshift-priv-installer-aro-wrapper-main.yaml
  ci-operator/config/openshift-priv/installer-aro-wrapper/openshift-priv-installer-aro-wrapper-release-4.12.yaml
  ci-operator/config/openshift-priv/installer-aro-wrapper/openshift-priv-installer-aro-wrapper-release-4.13.yaml
  ci-operator/config/openshift-priv/installer-aro-wrapper/openshift-priv-installer-aro-wrapper-release-4.14.yaml
  ci-operator/config/openshift-priv/installer-aro-wrapper/openshift-priv-installer-aro-wrapper-release-4.15.yaml
  ci-operator/config/openshift-priv/installer-aro-wrapper/openshift-priv-installer-aro-wrapper-release-4.16.yaml
  ci-operator/config/openshift/installer-aro-wrapper/openshift-installer-aro-wrapper-main.yaml
  ci-operator/config/openshift/installer-aro-wrapper/openshift-installer-aro-wrapper-release-4.12.yaml
  ci-operator/config/openshift/installer-aro-wrapper/openshift-installer-aro-wrapper-release-4.13.yaml
  ci-operator/config/openshift/installer-aro-wrapper/openshift-installer-aro-wrapper-release-4.14.yaml
  ci-operator/config/openshift/installer-aro-wrapper/openshift-installer-aro-wrapper-release-4.15.yaml
  ci-operator/config/openshift/installer-aro-wrapper/openshift-installer-aro-wrapper-release-4.16.yaml
Labels: lgtm, approved, rehearsals-ack

#61167 OLS-1338 - Changing the must-gather to be skippable on success
  ci-operator/config/openshift/lightspeed-service/openshift-lightspeed-service-main__4.15.yaml
  ci-operator/config/openshift/lightspeed-service/openshift-lightspeed-service-main__4.16.yaml
  ci-operator/config/openshift/lightspeed-service/openshift-lightspeed-service-main__4.17.yaml
Labels: lgtm, approved, rehearsals-ack

#61185 Add azure-cli to mirrored images
  core-services/image-mirroring/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#61140 [release-1.35] Initialize Serverless Operator CI config
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.35__413.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-release-1.35__417.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#61198 [INTEROP-7955] Updating the default assignee for firewatch configs
  ci-operator/config/RedHatQE/interop-testing/RedHatQE-interop-testing-cnv-4.18__cnv-odf-ocp4.18-lp-interop.yaml
  ci-operator/config/rh-messaging-qe/claire/rh-messaging-qe-claire-amq-broker-lpt__amq-broker-ocp4.18-lp-interop.yaml
Labels: lgtm, approved, rehearsals-ack

#61156 RHDH: fix optional PR checks & static token on AKS
  ci-operator/config/redhat-developer/rhdh/redhat-developer-rhdh-main.yaml
  ci-operator/jobs/redhat-developer/rhdh/redhat-developer-rhdh-main-periodics.yaml
  ci-operator/jobs/redhat-developer/rhdh/redhat-developer-rhdh-main-presubmits.yaml
  ci-operator/step-registry/redhat-developer/rhdh/aks/helm/nightly/redhat-developer-rhdh-aks-helm-nightly-commands.sh
  ci-operator/step-registry/redhat-developer/rhdh/gke/helm/nightly/redhat-developer-rhdh-gke-helm-nightly-commands.sh
  ci-operator/step-registry/redhat-developer/rhdh/nightly/redhat-developer-rhdh-nightly-commands.sh
  ci-operator/step-registry/redhat-developer/rhdh/operator/nightly/redhat-developer-rhdh-operator-nightly-commands.sh
Labels: lgtm, approved, rehearsals-ack

#61204 NO-ISSUE: Reduce the amount of presubmits
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.10.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.11.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.12.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.9.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.10-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.11-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.12-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#60909 OSSM-6617 Enable Upgrade test on Helm suite
  ci-operator/config/openshift-service-mesh/istio/openshift-service-mesh-istio-master.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#61203 Increase kubevirt-e2e-aws-tests timeout limit
  ci-operator/config/kubevirt-ui/kubevirt-plugin/kubevirt-ui-kubevirt-plugin-main.yaml
Labels: lgtm, approved, rehearsals-ack

#61209 orc: sync from release-1.0 instead of main
  ci-operator/config/shiftstack/merge-bot/shiftstack-merge-bot-main.yaml
Labels: lgtm, approved, rehearsals-ack

#61199 Add volume group snapshot job to 4.18
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.18.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.18-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#61145 add lint for openshift kueue-operator
  ci-operator/config/openshift/kueue-operator/openshift-kueue-operator-main.yaml
  ci-operator/jobs/openshift/kueue-operator/openshift-kueue-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#61210 volsync - use golang 1.23
  ci-operator/config/backube/volsync/backube-volsync-main.yaml
Labels: lgtm, approved, rehearsals-ack

#61112 Add edpm-image-builder repo
  ci-operator/config/openstack-k8s-operators/edpm-image-builder/OWNERS
  ci-operator/config/openstack-k8s-operators/edpm-image-builder/openstack-k8s-operators-edpm-image-builder-main.yaml
  ci-operator/jobs/openstack-k8s-operators/edpm-image-builder/OWNERS
  ci-operator/jobs/openstack-k8s-operators/edpm-image-builder/openstack-k8s-operators-edpm-image-builder-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#61226 [INTEROP-7955] Updating default JIRA assignee username for Distributed Tracing
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.18-lp-interop.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.18-lp-interop.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.18-lp-interop.yaml
Labels: lgtm, approved, rehearsals-ack

#61217 ossm/sail-operator: run scorecard test only when bundle changed
  ci-operator/config/openshift-service-mesh/sail-operator/openshift-service-mesh-sail-operator-main.yaml
  ci-operator/config/openshift-service-mesh/sail-operator/openshift-service-mesh-sail-operator-release-3.0.yaml
  ci-operator/jobs/openshift-service-mesh/sail-operator/openshift-service-mesh-sail-operator-main-presubmits.yaml
  ci-operator/jobs/openshift-service-mesh/sail-operator/openshift-service-mesh-sail-operator-release-3.0-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#58057 [PERFSCALE-3528] Add PreSubmit Jobs for OVN-Core Team
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.16.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.17.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.18.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.19.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.16-presubmits.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.17-presubmits.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.18-presubmits.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.19-presubmits.yaml
  ci-operator/step-registry/openshift-qe/cluster-density-v2/openshift-qe-cluster-density-v2-ref.yaml
  ci-operator/step-registry/workers-scale/workers-scale-commands.sh
  core-services/prow/02_config/_config.yaml
Labels: lgtm, approved, tide/merge-method-squash, rehearsals-ack

#61202 [CNV Nightly 4.18]: add multiarch release config
  ci-operator/config/openshift/release/openshift-release-master__cnv-nightly-4.18.yaml
Labels: lgtm, approved, rehearsals-ack

#61232 NO-ISSUE: Don't always run assisted OCI jobs
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-main__edge.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master__edge.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-master__edge.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-main-presubmits.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master-presubmits.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-master-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#61197 Add security job to pf-status-relay-operator
  ci-operator/config/openshift/pf-status-relay-operator/openshift-pf-status-relay-operator-main.yaml
  ci-operator/jobs/openshift/pf-status-relay-operator/openshift-pf-status-relay-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#61234 Telcov10n: capture ginkgo return status to continue with reporting
  ci-operator/step-registry/telcov10n/functional/hcp-cnf/tests/telcov10n-functional-hcp-cnf-tests-commands.sh
Labels: lgtm, approved, rehearsals-ack

#61162 generic-autobumper: bump manifests in openshift/ci-tools
  ci-operator/jobs/infra-periodics.yaml
  core-services/prow/02_config/_ci-tools-bumper.yaml
  core-services/prow/02_config/_release-bumper.yaml
Labels: lgtm, approved, rehearsals-ack

#61233 Telcov10-Increase the cadence of NTO Hypershift tests
  ci-operator/config/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main__hcp-cnf-4.18.yaml
  ci-operator/config/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main__hcp-cnf-4.19.yaml
  ci-operator/jobs/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#61240 OWNERS_ALIASES: update TRT aliases
  OWNERS_ALIASES
Labels: lgtm, approved, rehearsals-ack

#61222 Hive/master: bump builder image (go 1.23, OCP 4.19)
  ci-operator/config/openshift/hive/openshift-hive-master.yaml
Labels: lgtm, approved, rehearsals-ack

#61193 windows_exporter: Use OCP 4.19 and go 1.23
  ci-operator/config/openshift/prometheus-community-windows_exporter/openshift-prometheus-community-windows_exporter-master.yaml
Labels: lgtm, approved, rehearsals-ack

#61168 RHDH: create job to mapt destroy orphaned clusters
  ci-operator/config/redhat-developer/rhdh/redhat-developer-rhdh-main.yaml
  ci-operator/jobs/redhat-developer/rhdh/redhat-developer-rhdh-main-periodics.yaml
  ci-operator/jobs/redhat-developer/rhdh/redhat-developer-rhdh-main-presubmits.yaml
  ci-operator/step-registry/redhat-developer/rhdh/aks/mapt/orphaned/OWNERS
  ci-operator/step-registry/redhat-developer/rhdh/aks/mapt/orphaned/destroy/OWNERS
  ci-operator/step-registry/redhat-developer/rhdh/aks/mapt/orphaned/destroy/redhat-developer-rhdh-aks-mapt-orphaned-destroy-commands.sh
  ci-operator/step-registry/redhat-developer/rhdh/aks/mapt/orphaned/destroy/redhat-developer-rhdh-aks-mapt-orphaned-destroy-ref.metadata.json
  ci-operator/step-registry/redhat-developer/rhdh/aks/mapt/orphaned/destroy/redhat-developer-rhdh-aks-mapt-orphaned-destroy-ref.yaml
  ci-operator/step-registry/redhat-developer/rhdh/aks/mapt/orphaned/get/OWNERS
  ci-operator/step-registry/redhat-developer/rhdh/aks/mapt/orphaned/get/redhat-developer-rhdh-aks-mapt-orphaned-get-commands.sh
  ci-operator/step-registry/redhat-developer/rhdh/aks/mapt/orphaned/get/redhat-developer-rhdh-aks-mapt-orphaned-get-ref.metadata.json
  ci-operator/step-registry/redhat-developer/rhdh/aks/mapt/orphaned/get/redhat-developer-rhdh-aks-mapt-orphaned-get-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#61245 Update ODH owners for step-registry
  ci-operator/step-registry/opendatahub-io/OWNERS
  ci-operator/step-registry/opendatahub-io/ci/image-mirror/opendatahub-io-ci-image-mirror-ref.metadata.json
  ci-operator/step-registry/opendatahub-io/ci/image-mirror/opendatahub-io-ci-image-mirror-workflow.metadata.json
  ci-operator/step-registry/opendatahub-io/ci/s390x-build/build-publish/opendatahub-io-ci-s390x-build-build-publish-workflow.metadata.json
  ci-operator/step-registry/opendatahub-io/ci/s390x-build/create/opendatahub-io-ci-s390x-build-create-ref.metadata.json
  ci-operator/step-registry/opendatahub-io/ci/s390x-build/dashboard/opendatahub-io-ci-s390x-build-dashboard-ref.metadata.json
  ci-operator/step-registry/opendatahub-io/ci/s390x-build/delete/opendatahub-io-ci-s390x-build-delete-ref.metadata.json
Labels: lgtm, approved, rehearsals-ack

#60443 OCPBUGS-48100: rename 'master' to 'main' for gcp-pd-csi-driver-operator
  ci-operator/config/openshift-priv/gcp-pd-csi-driver-operator/openshift-priv-gcp-pd-csi-driver-operator-main.yaml
  ci-operator/config/openshift/gcp-pd-csi-driver-operator/openshift-gcp-pd-csi-driver-operator-main.yaml
  ci-operator/config/openshift/gcp-pd-csi-driver-operator/openshift-gcp-pd-csi-driver-operator-main__okd-scos.yaml
  ci-operator/jobs/openshift-priv/gcp-pd-csi-driver-operator/openshift-priv-gcp-pd-csi-driver-operator-main-postsubmits.yaml
  ci-operator/jobs/openshift-priv/gcp-pd-csi-driver-operator/openshift-priv-gcp-pd-csi-driver-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/gcp-pd-csi-driver-operator/openshift-gcp-pd-csi-driver-operator-main-periodics.yaml
  ci-operator/jobs/openshift/gcp-pd-csi-driver-operator/openshift-gcp-pd-csi-driver-operator-main-postsubmits.yaml
  ci-operator/jobs/openshift/gcp-pd-csi-driver-operator/openshift-gcp-pd-csi-driver-operator-main-presubmits.yaml
Labels: lgtm, approved, jira/valid-bug, rehearsals-ack, jira/valid-reference

#61127 MGMT-19831: Add new workflow and job for assisted installer installation in vSphere environment with user-managed LB
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
  ci-operator/step-registry/assisted/vsphere/external-lb/OWNERS
  ci-operator/step-registry/assisted/vsphere/external-lb/assisted-vsphere-external-lb-workflow.metadata.json
  ci-operator/step-registry/assisted/vsphere/external-lb/assisted-vsphere-external-lb-workflow.yaml
  ci-operator/step-registry/assisted/vsphere/external-lb/setup/OWNERS
  ci-operator/step-registry/assisted/vsphere/external-lb/setup/assisted-vsphere-external-lb-setup-chain.metadata.json
  ci-operator/step-registry/assisted/vsphere/external-lb/setup/assisted-vsphere-external-lb-setup-chain.yaml
  ci-operator/step-registry/assisted/vsphere/external-lb/teardown/OWNERS
  ci-operator/step-registry/assisted/vsphere/external-lb/teardown/assisted-vsphere-external-lb-teardown-chain.metadata.json
  ci-operator/step-registry/assisted/vsphere/external-lb/teardown/assisted-vsphere-external-lb-teardown-chain.yaml
  ci-operator/step-registry/assisted/vsphere/setup/configure/assisted-vsphere-setup-configure-commands.sh
  ci-operator/step-registry/assisted/vsphere/setup/configure/assisted-vsphere-setup-configure-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#60085 Adjust hcp conformance chain
  ci-operator/step-registry/hypershift/conformance/hypershift-conformance-chain.yaml
  ci-operator/step-registry/rosa/aws/sts/hcp/conformance/rosa-aws-sts-hcp-conformance-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#61252 [CVP-4326] Update the request limits for 4.19 jobs
  ci-operator/config/redhat-openshift-ecosystem/cvp/redhat-openshift-ecosystem-cvp-ocp-4.19.yaml
Labels: lgtm, approved, rehearsals-ack

#61211 orc: adding images & update test layout
  ci-operator/config/openshift/openstack-resource-controller/openshift-openstack-resource-controller-main.yaml
  ci-operator/jobs/openshift/openstack-resource-controller/openshift-openstack-resource-controller-main-postsubmits.yaml
  ci-operator/jobs/openshift/openstack-resource-controller/openshift-openstack-resource-controller-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#61135 fixing unbound variables for odh-dashboard multiarch image
  ci-operator/step-registry/opendatahub-io/ci/s390x-build/dashboard/opendatahub-io-ci-s390x-build-dashboard-commands.sh
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#61247 wmco: Bump golang to 1.23
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-master.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.19.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.20.yaml
Labels: lgtm, approved, rehearsals-ack

#61128 HOSTEDCP-2170: enable size tagging and add testAzureScheduler to test pool for hypershift-azure-e2e
  ci-operator/step-registry/hypershift/azure/aks/e2e/hypershift-azure-aks-e2e-workflow.yaml
  ci-operator/step-registry/hypershift/azure/run-e2e/hypershift-azure-run-e2e-commands.sh
  ci-operator/step-registry/hypershift/install/hypershift-install-commands.sh
  ci-operator/step-registry/hypershift/install/hypershift-install-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#61251 Update Sail Operator 3.0 branch jobs to latest OCP versions
  ci-operator/config/openshift-service-mesh/sail-operator/openshift-service-mesh-sail-operator-release-3.0.yaml
Labels: lgtm, approved, rehearsals-ack

#61262 Make E2E test optional on Custom Metrics Autoscaler Operator repo
  ci-operator/config/openshift/kedacore-keda/openshift-kedacore-keda-main.yaml
  ci-operator/jobs/openshift/kedacore-keda/openshift-kedacore-keda-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#60896 OTA-1415 Auto OCP-73352
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly-4.18-upgrade-from-stable-4.17.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__multi-nightly-4.19-upgrade-from-stable-4.18.yaml
  ci-operator/step-registry/cucushift/upgrade/toimage/cucushift-upgrade-toimage-commands.sh
Labels: lgtm, approved, rehearsals-ack

#60108 Auto OCP-32747
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.14.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.15.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.16.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.17.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.18.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.19.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
  ci-operator/step-registry/cucushift/ota/preupgrade/cucushift-ota-preupgrade-commands.sh
Labels: lgtm, approved, rehearsals-ack

#60689 Add the missed 4.18 jobs to 4.19
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__amd64-nightly-4.19-upgrade-from-stable-4.18.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__arm64-nightly-4.19-upgrade-from-stable-4.18.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__multi-nightly-4.19-upgrade-from-stable-4.18.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#60463 Enable 4.19 ppc64le jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__ppc64le-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#61258 [KMM] Increasing the timeout on the bundle deployment.
  ci-operator/config/rh-ecosystem-edge/kernel-module-management/rh-ecosystem-edge-kernel-module-management-main.yaml
  ci-operator/config/rh-ecosystem-edge/kernel-module-management/rh-ecosystem-edge-kernel-module-management-release-2.3.yaml
Labels: lgtm, approved, rehearsals-ack

#61242 add konflux test placeholders
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
  ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-periodics.yaml
  ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
  ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#61238 SPIRE-22: [o/spire-operator] Adds prow and ci-operator config for o/spire-operator repository
  ci-operator/config/openshift/spire-operator/OWNERS
  ci-operator/config/openshift/spire-operator/openshift-spire-operator-main.yaml
  ci-operator/jobs/openshift/spire-operator/OWNERS
  ci-operator/jobs/openshift/spire-operator/openshift-spire-operator-main-presubmits.yaml
  core-services/prow/02_config/openshift/spire-operator/OWNERS
  core-services/prow/02_config/openshift/spire-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/spire-operator/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#60555 rhdh helm osd nighlty job
  ci-operator/config/redhat-developer/rhdh/redhat-developer-rhdh-main.yaml
  ci-operator/jobs/redhat-developer/rhdh/redhat-developer-rhdh-main-periodics.yaml
  ci-operator/jobs/redhat-developer/rhdh/redhat-developer-rhdh-main-presubmits.yaml
  ci-operator/step-registry/redhat-developer/rhdh/osd-gcp/OWNERS
  ci-operator/step-registry/redhat-developer/rhdh/osd-gcp/claim-cluster/OWNERS
  ci-operator/step-registry/redhat-developer/rhdh/osd-gcp/claim-cluster/create/OWNERS
  ci-operator/step-registry/redhat-developer/rhdh/osd-gcp/claim-cluster/create/redhat-developer-rhdh-osd-gcp-claim-cluster-create-commands.sh
  ci-operator/step-registry/redhat-developer/rhdh/osd-gcp/claim-cluster/create/redhat-developer-rhdh-osd-gcp-claim-cluster-create-ref.metadata.json
  ci-operator/step-registry/redhat-developer/rhdh/osd-gcp/claim-cluster/create/redhat-developer-rhdh-osd-gcp-claim-cluster-create-ref.yaml
  ci-operator/step-registry/redhat-developer/rhdh/osd-gcp/claim-cluster/delete/OWNERS
  ci-operator/step-registry/redhat-developer/rhdh/osd-gcp/claim-cluster/delete/redhat-developer-rhdh-osd-gcp-claim-cluster-delete-commands.sh
  ci-operator/step-registry/redhat-developer/rhdh/osd-gcp/claim-cluster/delete/redhat-developer-rhdh-osd-gcp-claim-cluster-delete-ref.metadata.json
  ci-operator/step-registry/redhat-developer/rhdh/osd-gcp/claim-cluster/delete/redhat-developer-rhdh-osd-gcp-claim-cluster-delete-ref.yaml
  ci-operator/step-registry/redhat-developer/rhdh/osd-gcp/claim-cluster/redhat-developer-rhdh-osd-gcp-claim-cluster-workflow.metadata.json
  ci-operator/step-registry/redhat-developer/rhdh/osd-gcp/claim-cluster/redhat-developer-rhdh-osd-gcp-claim-cluster-workflow.yaml
  ci-operator/step-registry/redhat-developer/rhdh/osd-gcp/nightly/OWNERS
  ci-operator/step-registry/redhat-developer/rhdh/osd-gcp/nightly/redhat-developer-rhdh-osd-gcp-nightly-commands.sh
  ci-operator/step-registry/redhat-developer/rhdh/osd-gcp/nightly/redhat-developer-rhdh-osd-gcp-nightly-ref.metadata.json
  ci-operator/step-registry/redhat-developer/rhdh/osd-gcp/nightly/redhat-developer-rhdh-osd-gcp-nightly-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#61239 SPIRE-22: [o/spire-operator-release] Adds prow config for o/spire-operator-release repository
  core-services/prow/02_config/openshift/spire-operator-release/OWNERS
  core-services/prow/02_config/openshift/spire-operator-release/_pluginconfig.yaml
  core-services/prow/02_config/openshift/spire-operator-release/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#61293 Resolve brewhub.engineering.redhat.com
  clusters/build-clusters/common_managed/dns.yaml
Labels: lgtm, approved, rehearsals-ack

#61297 Update admin_manifest.yaml
  clusters/app.ci/registry-access/cnf-ci/admin_manifest.yaml
Labels: lgtm, approved, rehearsals-ack

#61250 Update 4-18 Sail Operator job to use Hypershift on main branch
  ci-operator/config/openshift-service-mesh/sail-operator/openshift-service-mesh-sail-operator-main.yaml
  ci-operator/config/openshift-service-mesh/sail-operator/openshift-service-mesh-sail-operator-release-3.0.yaml
  ci-operator/jobs/openshift-service-mesh/sail-operator/openshift-service-mesh-sail-operator-release-3.0-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#61286 TELCOV10N-508: Enable Jira integration to eco-ci-cd repos
  core-services/jira-lifecycle-plugin/config.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#61296 Adding payload job to ovn-k
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.18.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.19.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.20.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master-presubmits.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.18-presubmits.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.19-presubmits.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.20-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#61011 resource-watch observer: build timeline
  ci-operator/step-registry/observers/resource-watch/observers-resource-watch-commands.sh
Labels: lgtm, approved, rehearsals-ack

#61301 Fix issue DPTP-4315 Workaround by bumping up memory
  ci-operator/config/redhat-openshift-ecosystem/cvp/redhat-openshift-ecosystem-cvp-ocp-4.10.yaml
  ci-operator/config/redhat-openshift-ecosystem/cvp/redhat-openshift-ecosystem-cvp-ocp-4.11.yaml
  ci-operator/config/redhat-openshift-ecosystem/cvp/redhat-openshift-ecosystem-cvp-ocp-4.12.yaml
  ci-operator/config/redhat-openshift-ecosystem/cvp/redhat-openshift-ecosystem-cvp-ocp-4.13.yaml
  ci-operator/config/redhat-openshift-ecosystem/cvp/redhat-openshift-ecosystem-cvp-ocp-4.14.yaml
  ci-operator/config/redhat-openshift-ecosystem/cvp/redhat-openshift-ecosystem-cvp-ocp-4.15.yaml
  ci-operator/config/redhat-openshift-ecosystem/cvp/redhat-openshift-ecosystem-cvp-ocp-4.16.yaml
  ci-operator/config/redhat-openshift-ecosystem/cvp/redhat-openshift-ecosystem-cvp-ocp-4.17.yaml
  ci-operator/config/redhat-openshift-ecosystem/cvp/redhat-openshift-ecosystem-cvp-ocp-4.18.yaml
  ci-operator/config/redhat-openshift-ecosystem/cvp/redhat-openshift-ecosystem-cvp-ocp-4.19.yaml
  ci-operator/config/redhat-openshift-ecosystem/cvp/redhat-openshift-ecosystem-cvp-ocp-4.6.yaml
  ci-operator/config/redhat-openshift-ecosystem/cvp/redhat-openshift-ecosystem-cvp-ocp-4.7.yaml
  ci-operator/config/redhat-openshift-ecosystem/cvp/redhat-openshift-ecosystem-cvp-ocp-4.8.yaml
  ci-operator/config/redhat-openshift-ecosystem/cvp/redhat-openshift-ecosystem-cvp-ocp-4.9.yaml
Labels: lgtm, approved, rehearsals-ack

#60446 OCPBUGS-48103: rename 'master' to 'main' for vmware-vsphere-csi-driver-operator
  ci-operator/config/openshift-priv/vmware-vsphere-csi-driver-operator/openshift-priv-vmware-vsphere-csi-driver-operator-main.yaml
  ci-operator/config/openshift/vmware-vsphere-csi-driver-operator/openshift-vmware-vsphere-csi-driver-operator-main.yaml
  ci-operator/config/openshift/vmware-vsphere-csi-driver-operator/openshift-vmware-vsphere-csi-driver-operator-main__okd-scos.yaml
  ci-operator/jobs/openshift-priv/vmware-vsphere-csi-driver-operator/openshift-priv-vmware-vsphere-csi-driver-operator-main-postsubmits.yaml
  ci-operator/jobs/openshift-priv/vmware-vsphere-csi-driver-operator/openshift-priv-vmware-vsphere-csi-driver-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/vmware-vsphere-csi-driver-operator/openshift-vmware-vsphere-csi-driver-operator-main-postsubmits.yaml
  ci-operator/jobs/openshift/vmware-vsphere-csi-driver-operator/openshift-vmware-vsphere-csi-driver-operator-main-presubmits.yaml
Labels: lgtm, approved, jira/valid-bug, rehearsals-ack, jira/valid-reference

#58919 HOSTEDCP-2179: add hypershift-aks-e2e as required presub for csi-operator
  ci-operator/config/openshift/csi-operator/openshift-csi-operator-main.yaml
  ci-operator/config/openshift/csi-operator/openshift-csi-operator-release-4.18.yaml
  ci-operator/config/openshift/csi-operator/openshift-csi-operator-release-4.19.yaml
  ci-operator/jobs/openshift/csi-operator/openshift-csi-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/csi-operator/openshift-csi-operator-release-4.18-presubmits.yaml
  ci-operator/jobs/openshift/csi-operator/openshift-csi-operator-release-4.19-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#60976 OCPBUGS-49317: rename 'master' to 'main' for linuxptp-daemon
  ci-operator/config/openshift-priv/linuxptp-daemon/openshift-priv-linuxptp-daemon-main.yaml
  ci-operator/config/openshift/linuxptp-daemon/openshift-linuxptp-daemon-main.yaml
  ci-operator/jobs/openshift-priv/linuxptp-daemon/openshift-priv-linuxptp-daemon-main-postsubmits.yaml
  ci-operator/jobs/openshift-priv/linuxptp-daemon/openshift-priv-linuxptp-daemon-main-presubmits.yaml
  ci-operator/jobs/openshift/linuxptp-daemon/openshift-linuxptp-daemon-main-postsubmits.yaml
  ci-operator/jobs/openshift/linuxptp-daemon/openshift-linuxptp-daemon-main-presubmits.yaml
Labels: lgtm, approved, jira/valid-bug, rehearsals-ack, jira/valid-reference

#60956 shiftstack/prune: relax images cleanup on VEXXHOST
  ci-operator/config/shiftstack/ci/shiftstack-ci-main.yaml
  ci-operator/step-registry/shiftstack/cleanup/shiftstack-cleanup-commands.sh
  ci-operator/step-registry/shiftstack/cleanup/shiftstack-cleanup-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#61303 release-controller: fix baseurls for RHEL 9.6 ART mirrors
  core-services/release-controller/_repos/ocp-4.19-rhel96.repo
Labels: lgtm, approved, rehearsals-ack

#61309 Add envoy OWNERS group
  OWNERS_ALIASES
Labels: lgtm, approved, rehearsals-ack

#61311 Add mirroring configuration for rhdh-e2e-runner image
  core-services/image-mirroring/_config.yaml
Labels: lgtm, approved, needs-ok-to-test, rehearsals-ack

#61313 Add envoy upstream image
  core-services/image-mirroring/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#61246 OCPERT-47 Enable auto release jobs for 4.18
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__automated-release-stable-4.18-upgrade-from-stable-4.17.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__automated-release-stable-4.18-upgrade-from-stable-4.18.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__automated-release.yaml
  ci-operator/config/openshift/release-tests/openshift-release-tests-master.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#60464 Update the cronjob schedule for 4.17 ppc64le jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__ppc64le-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#61155 add zmiklank to maistra-approvers and maistra-reviewers
  OWNERS_ALIASES
Labels: lgtm, approved, needs-ok-to-test, rehearsals-ack

#61325 Onboard build11 2nd attempt
  core-services/sanitize-prow-jobs/_clusters.yaml
Labels: lgtm, approved, rehearsals-ack

#61277 fix mce-install failed for disconnected ipv6
  ci-operator/step-registry/hypershift/mce/install/hypershift-mce-install-commands.sh
Labels: lgtm, approved, rehearsals-ack

#61335 Remove b06 from rotation for #incident-20250206-build06-image-pull
  core-services/sanitize-prow-jobs/_clusters.yaml
Labels: lgtm, approved, rehearsals-ack

#61276 Update Tracing jobs
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.13-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.14-lp-interop.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.14-lp-rosa-classic.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.15-lp-interop.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.15-lp-rosa-classic.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.16-lp-interop.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.16-lp-rosa-classic.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.17-lp-interop.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.17-lp-rosa-classic.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__upstream-ocp-4.13-amd64-aws-ipi-ovn-hypershift.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.13-stage.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__ocp-4.16-hypershift.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.13-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.14-lp-interop.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.14-lp-rosa-classic.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.15-lp-interop.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.15-lp-rosa-classic.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.16-lp-interop.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.16-lp-rosa-classic.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.17-lp-interop.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.17-lp-rosa-classic.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__upstream-ocp-4.13-amd64-aws-ipi-ovn-hypershift.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__upstream-ocp-4.14-amd64-gcp-ipi-ovn-ipsec.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__upstream-ocp-4.15-amd64-aws.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__upstream-ocp-4.16-amd64-aws-ipi-shared-vpc-phz-sts.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__upstream-upgrade-ocp-4.17-amd64-azure.yaml
  ci-operator/jobs/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main-presubmits.yaml
  ci-operator/step-registry/distributed-tracing/tests/opentelemetry/interop/distributed-tracing-tests-opentelemetry-interop-commands.sh
  ci-operator/step-registry/distributed-tracing/tests/opentelemetry/interop/distributed-tracing-tests-opentelemetry-interop-ref.yaml
  ci-operator/step-registry/distributed-tracing/tests/opentelemetry/upstream/distributed-tracing-tests-opentelemetry-upstream-ref.yaml
  ci-operator/step-registry/distributed-tracing/tests/tempo/downstream/distributed-tracing-tests-tempo-downstream-commands.sh
  ci-operator/step-registry/distributed-tracing/tests/tempo/interop/distributed-tracing-tests-tempo-interop-commands.sh
Labels: lgtm, approved, rehearsals-ack

#61121 [PERFSCALE-3545] Running krkn etcd pod distruption scenarios
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__metal-x86.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-presubmits.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#61282 MGMT-19831: Fix vSphere job with external LB
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
  ci-operator/step-registry/assisted/vsphere/external-lb/setup/assisted-vsphere-external-lb-setup-chain.yaml
  ci-operator/step-registry/assisted/vsphere/setup/configure/assisted-vsphere-setup-configure-commands.sh
  ci-operator/step-registry/assisted/vsphere/setup/configure/assisted-vsphere-setup-configure-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#61343 Add aarch64 to ci-scheduling-webhook
  ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
Labels: lgtm, approved, rehearsals-ack

#61333 Delete non needed oc copy binary from openshift-service-mesh organization jobs
  ci-operator/config/openshift-service-mesh/federation/openshift-service-mesh-federation-master.yaml
  ci-operator/config/openshift-service-mesh/istio/openshift-service-mesh-istio-master.yaml
  ci-operator/config/openshift-service-mesh/istio/openshift-service-mesh-istio-release-1.23.yaml
  ci-operator/config/openshift-service-mesh/sail-operator/openshift-service-mesh-sail-operator-main.yaml
  ci-operator/config/openshift-service-mesh/sail-operator/openshift-service-mesh-sail-operator-release-3.0.yaml
Labels: lgtm, approved, rehearsals-ack

#61253 OTA-209: Bump golangci-lint image to support go1.23
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-main.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#61354 gangway: add user annotation in prowjob
  clusters/app.ci/prow/03_deployment/gangway.yaml
  clusters/app.ci/supplemental-ci-images/envoyproxy/envoyproxy.yaml
Labels: lgtm, approved, rehearsals-ack

#60882 hypershift/openstack: set CleanupOrcImageResourcesAnnotation to false
  ci-operator/step-registry/hypershift/openstack/e2e/execute/hypershift-openstack-e2e-execute-commands.sh
Labels: lgtm, approved, rehearsals-ack

#61040 [COS-3017] Build extensions container in CI
  ci-operator/config/openshift/os/openshift-os-master.yaml
Labels: lgtm, approved, rehearsals-ack

#61353 telcov10: use OR operator to capture the exit status of ginkgo
  ci-operator/step-registry/telcov10n/functional/hcp-cnf/tests/telcov10n-functional-hcp-cnf-tests-commands.sh
Labels: lgtm, approved, rehearsals-ack

#61342 Update ovnk upgrade jobs to use base image 4.18
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-master__4.19-upgrade-from-stable-4.18.yaml
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.18__4.18-upgrade-from-stable-4.17.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master__4.19-upgrade-from-stable-4.18.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.18-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#61257 SPLAT-2022: enable presubmits for host group tesing
  ci-operator/config/openshift/vsphere-problem-detector/openshift-vsphere-problem-detector-main.yaml
  ci-operator/config/openshift/vsphere-problem-detector/openshift-vsphere-problem-detector-release-4.19.yaml
  ci-operator/config/openshift/vsphere-problem-detector/openshift-vsphere-problem-detector-release-4.20.yaml
  ci-operator/jobs/openshift/vsphere-problem-detector/openshift-vsphere-problem-detector-main-presubmits.yaml
  ci-operator/jobs/openshift/vsphere-problem-detector/openshift-vsphere-problem-detector-release-4.19-presubmits.yaml
  ci-operator/jobs/openshift/vsphere-problem-detector/openshift-vsphere-problem-detector-release-4.20-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#61363 NO-JIRA: hcp/osp: increase parallel tests
  ci-operator/step-registry/hypershift/openstack/e2e/execute/hypershift-openstack-e2e-execute-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#61368 SPLAT-2028: make host-group test always_run: false
  ci-operator/jobs/openshift/installer/openshift-installer-main-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.20-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#61360 Bump Timout for MCO e2e-gcp-op for 4.17
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.17.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.17-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#61319 rhdh operator osd nighlty job
  ci-operator/config/redhat-developer/rhdh/redhat-developer-rhdh-main.yaml
  ci-operator/jobs/redhat-developer/rhdh/redhat-developer-rhdh-main-periodics.yaml
  ci-operator/jobs/redhat-developer/rhdh/redhat-developer-rhdh-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#61266 CORS-3879: add confidentialVM jobs on 4.17
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-nightly-4.17-upgrade-from-stable-4.17.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly-4.18-upgrade-from-stable-4.17.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.17.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18-periodics.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
  ci-operator/step-registry/cucushift/installer/check/azure/confidential/cucushift-installer-check-azure-confidential-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#61306 coreos/rpm-ostree: Stop using old image for build root
  ci-operator/config/coreos/rpm-ostree/coreos-rpm-ostree-main.yaml
Labels: lgtm, approved, rehearsals-ack

#61316 OCPQE-28009: disable 4.13 multiarch jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__multi-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#61272 [azure] fix failure on azure minimal permission jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__multi-nightly-4.17-upgrade-from-stable-4.16.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__multi-nightly-4.17-upgrade-from-stable-4.17.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__multi-nightly-4.18-upgrade-from-stable-4.17.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__multi-nightly-4.18-upgrade-from-stable-4.18.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__multi-nightly-4.19-upgrade-from-stable-4.18.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__multi-nightly-4.19-upgrade-from-stable-4.19.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__multi-nightly.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.18.yaml
  ci-operator/step-registry/azure/deprovision/sp-and-custom-role/azure-deprovision-sp-and-custom-role-commands.sh
  ci-operator/step-registry/azure/provision/disk-encryption-set/azure-provision-disk-encryption-set-commands.sh
  ci-operator/step-registry/azure/provision/disk-encryption-set/grant-permission/azure-provision-disk-encryption-set-grant-permission-commands.sh
  ci-operator/step-registry/azure/provision/service-principal/minimal-permission/azure-provision-service-principal-minimal-permission-commands.sh
  ci-operator/step-registry/azure/provision/vnet/azure-provision-vnet-commands.sh
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/disk-encryption-set/provision/cucushift-installer-rehearse-azure-ipi-disk-encryption-set-provision-chain.yaml
  ci-operator/step-registry/ipi/conf/azure/resourcegroup/ipi-conf-azure-resourcegroup-commands.sh
Labels: lgtm, approved, rehearsals-ack

#61278 refining instance
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__azure-4.17-nightly-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__azure-4.18-nightly-x86.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#61289 fix issues in ipsec 120 and 250 nodes
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.18-nightly-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.19-nightly-x86.yaml
Labels: lgtm, approved, rehearsals-ack

#61359 cluster-init: patch clonerefs manifests
  clusters/_cluster-install/build01.yaml
  clusters/_cluster-install/build02.yaml
  clusters/_cluster-install/build03.yaml
  clusters/_cluster-install/build04.yaml
  clusters/_cluster-install/build05.yaml
  clusters/_cluster-install/build06.yaml
  clusters/_cluster-install/build09.yaml
  clusters/_cluster-install/build10.yaml
  clusters/_cluster-install/build11.yaml
Labels: lgtm, approved, rehearsals-ack

#59846 remove references to jvm-build-service
  ci-operator/config/redhat-appstudio/jvm-build-service/OWNERS
  ci-operator/config/redhat-appstudio/jvm-build-service/redhat-appstudio-jvm-build-service-main.yaml
  ci-operator/jobs/redhat-appstudio/jvm-build-service/OWNERS
  ci-operator/jobs/redhat-appstudio/jvm-build-service/redhat-appstudio-jvm-build-service-main-presubmits.yaml
  ci-operator/step-registry/devfile/konflux-nightly/devfile-konflux-nightly-ref.yaml
  ci-operator/step-registry/redhat-appstudio/e2e/redhat-appstudio-e2e-ref.yaml
  ci-operator/step-registry/redhat-appstudio/gather/redhat-appstudio-gather-commands.sh
  ci-operator/step-registry/redhat-appstudio/install-konflux/redhat-appstudio-install-konflux-ref.yaml
  ci-operator/step-registry/redhat-appstudio/upgrade/redhat-appstudio-upgrade-ref.yaml
  core-services/prow/02_config/redhat-appstudio/jvm-build-service/OWNERS
  core-services/prow/02_config/redhat-appstudio/jvm-build-service/_pluginconfig.yaml
  core-services/prow/02_config/redhat-appstudio/jvm-build-service/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#61351 adding service mesh 3.test jobs
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-service-mesh-docs-3.test.yaml
  ci-operator/jobs/openshift/openshift-docs/openshift-openshift-docs-service-mesh-docs-3.test-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#61361 release-controller: add rhel-9.6-early-kernel
  core-services/release-controller/_repos/ocp-4.19-rhel96.repo
Labels: lgtm, approved, rehearsals-ack

#61386 Reenable build06
  core-services/sanitize-prow-jobs/_clusters.yaml
Labels: lgtm, approved, rehearsals-ack

#61395 [ODH] Disable prow branch protection for feast
  core-services/prow/02_config/opendatahub-io/feast/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#61398 turning off events when nodes are restarted
  ci-operator/step-registry/redhat-chaos/node-disruptions/infra-outage/redhat-chaos-node-disruptions-infra-outage-ref.yaml
  ci-operator/step-registry/redhat-chaos/node-disruptions/master-outage/redhat-chaos-node-disruptions-master-outage-ref.yaml
  ci-operator/step-registry/redhat-chaos/node-disruptions/worker-outage/redhat-chaos-node-disruptions-worker-outage-ref.yaml
  ci-operator/step-registry/redhat-chaos/power-outage/redhat-chaos-power-outage-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#61336 Add support for creating arm machine on GCP
  ci-operator/config/crc-org/snc/crc-org-snc-master.yaml
  ci-operator/jobs/crc-org/snc/crc-org-snc-master-presubmits.yaml
  ci-operator/step-registry/code-ready/snc/microshift-arm/OWNERS
  ci-operator/step-registry/code-ready/snc/microshift-arm/code-ready-snc-microshift-arm-workflow.metadata.json
  ci-operator/step-registry/code-ready/snc/microshift-arm/code-ready-snc-microshift-arm-workflow.yaml
  ci-operator/step-registry/code-ready/snc/microshift-arm/test/OWNERS
  ci-operator/step-registry/code-ready/snc/microshift-arm/test/code-ready-snc-microshift-arm-test-commands.sh
  ci-operator/step-registry/code-ready/snc/microshift-arm/test/code-ready-snc-microshift-arm-test-ref.metadata.json
  ci-operator/step-registry/code-ready/snc/microshift-arm/test/code-ready-snc-microshift-arm-test-ref.yaml
  ci-operator/step-registry/upi/gcp/arm/OWNERS
  ci-operator/step-registry/upi/gcp/arm/post/OWNERS
  ci-operator/step-registry/upi/gcp/arm/post/upi-gcp-arm-post-chain.metadata.json
  ci-operator/step-registry/upi/gcp/arm/post/upi-gcp-arm-post-chain.yaml
  ci-operator/step-registry/upi/gcp/arm/post/upi-gcp-arm-post-commands.sh
  ci-operator/step-registry/upi/gcp/arm/post/upi-gcp-arm-post-ref.metadata.json
  ci-operator/step-registry/upi/gcp/arm/post/upi-gcp-arm-post-ref.yaml
  ci-operator/step-registry/upi/gcp/arm/pre/OWNERS
  ci-operator/step-registry/upi/gcp/arm/pre/upi-gcp-arm-pre-chain.metadata.json
  ci-operator/step-registry/upi/gcp/arm/pre/upi-gcp-arm-pre-chain.yaml
  ci-operator/step-registry/upi/gcp/arm/pre/upi-gcp-arm-pre-commands.sh
  ci-operator/step-registry/upi/gcp/arm/pre/upi-gcp-arm-pre-ref.metadata.json
  ci-operator/step-registry/upi/gcp/arm/pre/upi-gcp-arm-pre-ref.yaml
  ci-operator/step-registry/upi/gcp/arm/upi-gcp-arm-workflow.metadata.json
  ci-operator/step-registry/upi/gcp/arm/upi-gcp-arm-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#61389 Add step to capture mg
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.18.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.19.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.20.yaml
Labels: lgtm, approved, rehearsals-ack

#60980 update ptp-operator CI test branch to main
  ci-operator/step-registry/telco5g/ptp/tests/telco5g-ptp-tests-commands.sh
Labels: lgtm, approved, rehearsals-ack

#61352 Update netobserv-console-plugin build recipe
  ci-operator/config/netobserv/network-observability-console-plugin/netobserv-network-observability-console-plugin-main.yaml
Labels: lgtm, approved, rehearsals-ack

#61357 Hive: Bump periodics for OCP 4.19, go 1.23
  ci-operator/config/openshift/hive/openshift-hive-master__periodic.yaml
  ci-operator/jobs/openshift/hive/openshift-hive-master-periodics.yaml
  ci-operator/jobs/openshift/hive/openshift-hive-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#61358 Hive: Add mce-2.8
  ci-operator/config/openshift/hive/openshift-hive-mce-2.8.yaml
  ci-operator/jobs/openshift/hive/openshift-hive-mce-2.8-postsubmits.yaml
  ci-operator/jobs/openshift/hive/openshift-hive-mce-2.8-presubmits.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#61394 NO-JIRA: orc: run make without vendoring
  ci-operator/config/openshift/openstack-resource-controller/openshift-openstack-resource-controller-main.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#61279 OCPQE-27320 - Adding stable to stable upgrade jobs for OCP 4.19
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__amd64-stable-4.19-upgrade-from-stable-4.18.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__arm64-stable-4.19-upgrade-from-stable-4.18.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__multi-stable-4.19-upgrade-from-stable-4.18.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#61406 Hive: Use newer clusterpool
  ci-operator/config/openshift/hive/openshift-hive-master.yaml
  ci-operator/config/openshift/hive/openshift-hive-master__periodic.yaml
  ci-operator/config/openshift/hive/openshift-hive-mce-2.2.yaml
  ci-operator/config/openshift/hive/openshift-hive-mce-2.3.yaml
  ci-operator/config/openshift/hive/openshift-hive-mce-2.4.yaml
  ci-operator/config/openshift/hive/openshift-hive-mce-2.5.yaml
  ci-operator/config/openshift/hive/openshift-hive-mce-2.6.yaml
  ci-operator/config/openshift/hive/openshift-hive-mce-2.7.yaml
  ci-operator/config/openshift/hive/openshift-hive-mce-2.8.yaml
Labels: lgtm, approved, rehearsals-ack

#61012 Add cluster health check after deployment
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__metal-4.16-latest-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__metal-4.17-latest-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__metal-4.18-latest-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__metal-dev-latest-x86.yaml
  ci-operator/step-registry/openshift-qe/installer/bm/day2/label/openshift-qe-installer-bm-day2-label-ref.yaml
Labels: lgtm, approved, rehearsals-ack, network-access-rehearsals-ok

#61411 Ignore .github and .tekton changes for ci tests
  ci-operator/config/stolostron/multicluster-global-hub/stolostron-multicluster-global-hub-main.yaml
  ci-operator/config/stolostron/multicluster-global-hub/stolostron-multicluster-global-hub-release-2.12.yaml
  ci-operator/config/stolostron/multicluster-global-hub/stolostron-multicluster-global-hub-release-2.13.yaml
  ci-operator/jobs/stolostron/multicluster-global-hub/stolostron-multicluster-global-hub-main-postsubmits.yaml
  ci-operator/jobs/stolostron/multicluster-global-hub/stolostron-multicluster-global-hub-main-presubmits.yaml
  ci-operator/jobs/stolostron/multicluster-global-hub/stolostron-multicluster-global-hub-release-2.12-postsubmits.yaml
  ci-operator/jobs/stolostron/multicluster-global-hub/stolostron-multicluster-global-hub-release-2.12-presubmits.yaml
  ci-operator/jobs/stolostron/multicluster-global-hub/stolostron-multicluster-global-hub-release-2.13-postsubmits.yaml
  ci-operator/jobs/stolostron/multicluster-global-hub/stolostron-multicluster-global-hub-release-2.13-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#61414 Ignore .github and .tekton changes for ci tests
  ci-operator/config/stolostron/multicluster-global-hub/stolostron-multicluster-global-hub-main.yaml
  ci-operator/config/stolostron/multicluster-global-hub/stolostron-multicluster-global-hub-release-2.12.yaml
  ci-operator/config/stolostron/multicluster-global-hub/stolostron-multicluster-global-hub-release-2.13.yaml
  ci-operator/jobs/stolostron/multicluster-global-hub/stolostron-multicluster-global-hub-main-postsubmits.yaml
  ci-operator/jobs/stolostron/multicluster-global-hub/stolostron-multicluster-global-hub-main-presubmits.yaml
  ci-operator/jobs/stolostron/multicluster-global-hub/stolostron-multicluster-global-hub-release-2.12-postsubmits.yaml
  ci-operator/jobs/stolostron/multicluster-global-hub/stolostron-multicluster-global-hub-release-2.12-presubmits.yaml
  ci-operator/jobs/stolostron/multicluster-global-hub/stolostron-multicluster-global-hub-release-2.13-postsubmits.yaml
  ci-operator/jobs/stolostron/multicluster-global-hub/stolostron-multicluster-global-hub-release-2.13-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#60888 update mce version for 4.17
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-nightly-4.17-upgrade-from-stable-4.17.yaml
Labels: lgtm, approved, rehearsals-ack

#61419 HyperShift: Extend hypershift-kubevirt-create to support 'EXTRA_ARGS'
  ci-operator/step-registry/hypershift/kubevirt/create/hypershift-kubevirt-create-commands.sh
  ci-operator/step-registry/hypershift/kubevirt/create/hypershift-kubevirt-create-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#61416 CORS-3815: aws - generate junit file for install pre configure and post check
  ci-operator/step-registry/aws/c2s/get-project-info/aws-c2s-get-project-info-commands.sh
  ci-operator/step-registry/aws/c2s/init-token-service/aws-c2s-init-token-service-commands.sh
  ci-operator/step-registry/aws/c2s/instance-metadata/aws-c2s-instance-metadata-commands.sh
  ci-operator/step-registry/aws/c2s/mirror-images/aws-c2s-mirror-images-commands.sh
  ci-operator/step-registry/aws/cluster/public-to-private/aws-cluster-public-to-private-commands.sh
  ci-operator/step-registry/aws/provision/bastionhost/aws-provision-bastionhost-commands.sh
  ci-operator/step-registry/aws/provision/cco-manual-users/static/aws-provision-cco-manual-users-static-commands.sh
  ci-operator/step-registry/aws/provision/edge-zone-subnet/aws-provision-edge-zone-subnet-commands.sh
  ci-operator/step-registry/aws/provision/iam-profile/aws-provision-iam-profile-commands.sh
  ci-operator/step-registry/aws/provision/iam-role/aws-provision-iam-role-commands.sh
  ci-operator/step-registry/aws/provision/iam-user/aws-provision-iam-user-commands.sh
  ci-operator/step-registry/aws/provision/kms-key/aws-provision-kms-key-commands.sh
  ci-operator/step-registry/aws/provision/route53/private-hosted-zone/associate-diff-vpc/aws-provision-route53-private-hosted-zone-associate-diff-vpc-commands.sh
  ci-operator/step-registry/aws/provision/route53/private-hosted-zone/aws-provision-route53-private-hosted-zone-commands.sh
  ci-operator/step-registry/aws/provision/security-group/aws-provision-security-group-commands.sh
  ci-operator/step-registry/aws/provision/tags-for-byo-vpc/aws-provision-tags-for-byo-vpc-commands.sh
  ci-operator/step-registry/aws/provision/tags-for-byo-vpc/ocm/pre/aws-provision-tags-for-byo-vpc-ocm-pre-commands.sh
  ci-operator/step-registry/aws/provision/vpc/disconnected/aws-provision-vpc-disconnected-commands.sh
  ci-operator/step-registry/aws/provision/vpc/shared/aws-provision-vpc-shared-commands.sh
  ci-operator/step-registry/cucushift/installer/check/aws/bootstrap-ignition/cucushift-installer-check-aws-bootstrap-ignition-commands.sh
  ci-operator/step-registry/cucushift/installer/check/aws/bootstrap-ignition/cucushift-installer-check-aws-bootstrap-ignition-ref.yaml
  ci-operator/step-registry/cucushift/installer/check/aws/byo-iam-profile/cucushift-installer-check-aws-byo-iam-profile-commands.sh
  ci-operator/step-registry/cucushift/installer/check/aws/byo-iam-profile/cucushift-installer-check-aws-byo-iam-profile-ref.yaml
  ci-operator/step-registry/cucushift/installer/check/aws/byo-iam-role/cucushift-installer-check-aws-byo-iam-role-commands.sh
  ci-operator/step-registry/cucushift/installer/check/aws/byo-iam-role/cucushift-installer-check-aws-byo-iam-role-ref.yaml
  ci-operator/step-registry/cucushift/installer/check/aws/byo-kms-key/cucushift-installer-check-aws-byo-kms-key-commands.sh
  ci-operator/step-registry/cucushift/installer/check/aws/byo-kms-key/cucushift-installer-check-aws-byo-kms-key-ref.yaml
  ci-operator/step-registry/cucushift/installer/check/aws/c2s/cucushift-installer-check-aws-c2s-commands.sh
  ci-operator/step-registry/cucushift/installer/check/aws/c2s/cucushift-installer-check-aws-c2s-ref.yaml
  ci-operator/step-registry/cucushift/installer/check/aws/custom-ami/cucushift-installer-check-aws-custom-ami-commands.sh
  ci-operator/step-registry/cucushift/installer/check/aws/custom-ami/cucushift-installer-check-aws-custom-ami-ref.yaml
  ci-operator/step-registry/cucushift/installer/check/aws/custom-sg/cucushift-installer-check-aws-custom-sg-commands.sh
  ci-operator/step-registry/cucushift/installer/check/aws/custom-sg/cucushift-installer-check-aws-custom-sg-ref.yaml
  ci-operator/step-registry/cucushift/installer/check/aws/custom-tag/cucushift-installer-check-aws-custom-tag-commands.sh
  ci-operator/step-registry/cucushift/installer/check/aws/custom-tag/cucushift-installer-check-aws-custom-tag-ref.yaml
  ci-operator/step-registry/cucushift/installer/check/aws/edge-zone/cucushift-installer-check-aws-edge-zone-commands.sh
  ci-operator/step-registry/cucushift/installer/check/aws/edge-zone/cucushift-installer-check-aws-edge-zone-ref.yaml
  ci-operator/step-registry/cucushift/installer/check/aws/ipv4-pool/cucushift-installer-check-aws-ipv4-pool-commands.sh
  ci-operator/step-registry/cucushift/installer/check/aws/ipv4-pool/cucushift-installer-check-aws-ipv4-pool-ref.yaml
  ci-operator/step-registry/cucushift/installer/check/aws/outpost/cucushift-installer-check-aws-outpost-commands.sh
  ci-operator/step-registry/cucushift/installer/check/aws/outpost/cucushift-installer-check-aws-outpost-ref.yaml
  ci-operator/step-registry/cucushift/installer/check/aws/private/cucushift-installer-check-aws-private-commands.sh
  ci-operator/step-registry/cucushift/installer/check/aws/private/cucushift-installer-check-aws-private-ref.yaml
  ci-operator/step-registry/cucushift/installer/check/aws/shared-phz/cucushift-installer-check-aws-shared-phz-commands.sh
  ci-operator/step-registry/cucushift/installer/check/aws/shared-phz/cucushift-installer-check-aws-shared-phz-ref.yaml
  ci-operator/step-registry/ipi/conf/aws/user-min-permissions/ipi-conf-aws-user-min-permissions-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#61432 Update check commands to set GOLANGCI_LINT_CACHE before execution
  ci-operator/config/stolostron/managedcluster-import-controller/stolostron-managedcluster-import-controller-backplane-2.4.yaml
  ci-operator/config/stolostron/managedcluster-import-controller/stolostron-managedcluster-import-controller-backplane-2.5.yaml
  ci-operator/config/stolostron/managedcluster-import-controller/stolostron-managedcluster-import-controller-backplane-2.6.yaml
  ci-operator/config/stolostron/managedcluster-import-controller/stolostron-managedcluster-import-controller-backplane-2.7.yaml
  ci-operator/config/stolostron/managedcluster-import-controller/stolostron-managedcluster-import-controller-backplane-2.8.yaml
  ci-operator/config/stolostron/managedcluster-import-controller/stolostron-managedcluster-import-controller-main.yaml
Labels: lgtm, approved, rehearsals-ack

#61227 Exclude unsupported loadbalancer testcases for power jobs
  ci-operator/step-registry/openshift/e2e/libvirt/conf/openshift-e2e-libvirt-conf-commands.sh
Labels: lgtm, approved, rehearsals-ack

#61317 add 4.18 hypershift guest jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__arm64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#61425 USHIFT-5367: Enable podman log collection in sos reports
  ci-operator/step-registry/openshift/microshift/infra/sos-aws/openshift-microshift-infra-sos-aws-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#61418 OCPQE-19583: add roxctl into dockerfile
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__omr-ocp416.yaml
Labels: lgtm, approved, tide/merge-method-squash, rehearsals-ack, jira/valid-reference

#61405 add ec2 to osde2e cleanup jobs
  ci-operator/config/openshift/osde2e/openshift-osde2e-main.yaml
Labels: lgtm, approved, rehearsals-ack

#60823 Add ci for multi network
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#61433 RHDH authentication providers
  ci-operator/config/redhat-developer/rhdh/redhat-developer-rhdh-main.yaml
  ci-operator/jobs/redhat-developer/rhdh/redhat-developer-rhdh-main-periodics.yaml
  ci-operator/step-registry/redhat-developer/rhdh/auth-providers-nightly/OWNERS
  ci-operator/step-registry/redhat-developer/rhdh/auth-providers-nightly/redhat-developer-rhdh-auth-providers-nightly-commands.sh
  ci-operator/step-registry/redhat-developer/rhdh/auth-providers-nightly/redhat-developer-rhdh-auth-providers-nightly-ref.metadata.json
  ci-operator/step-registry/redhat-developer/rhdh/auth-providers-nightly/redhat-developer-rhdh-auth-providers-nightly-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#61430 disable ccm folder check from 4.18
  ci-operator/step-registry/cucushift/installer/check/vsphere/folder/cucushift-installer-check-vsphere-folder-commands.sh
Labels: lgtm, approved, rehearsals-ack

#57894 adjust hypershift-mce-agent-create-agentserviceconfig step
  ci-operator/step-registry/hypershift/mce/agent/create/agentserviceconfig/hypershift-mce-agent-create-agentserviceconfig-commands.sh
Labels: lgtm, approved, rehearsals-ack

#61331 Sync Serverless CI config/
  ci-operator/config/openshift-knative/serving/openshift-knative-serving-release-next__413.yaml
  ci-operator/config/openshift-knative/serving/openshift-knative-serving-release-next__417.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#61421 Revert "Disable build09"
  core-services/sanitize-prow-jobs/_clusters.yaml
Labels: lgtm, approved, rehearsals-ack

#61390 use correct make target for oc-service-common
  ci-operator/config/openshift-online/ocm-service-common/openshift-online-ocm-service-common-master.yaml
Labels: lgtm, approved, rehearsals-ack

#61446 fix osd operator job
  ci-operator/jobs/redhat-developer/rhdh/redhat-developer-rhdh-main-periodics.yaml
  ci-operator/step-registry/redhat-developer/rhdh/osd-gcp/claim-cluster/delete/redhat-developer-rhdh-osd-gcp-claim-cluster-delete-commands.sh
  ci-operator/step-registry/redhat-developer/rhdh/osd-gcp/nightly/redhat-developer-rhdh-osd-gcp-nightly-commands.sh
Labels: lgtm, approved, rehearsals-ack

#61345 OCPBUGS-49942: rename 'master' to 'main' for cloud-provider-azure
  ci-operator/config/openshift-priv/cloud-provider-azure/openshift-priv-cloud-provider-azure-main.yaml
  ci-operator/config/openshift/cloud-provider-azure/openshift-cloud-provider-azure-main.yaml
  ci-operator/config/openshift/cloud-provider-azure/openshift-cloud-provider-azure-main__okd-scos.yaml
  ci-operator/jobs/openshift-priv/cloud-provider-azure/openshift-priv-cloud-provider-azure-main-postsubmits.yaml
  ci-operator/jobs/openshift-priv/cloud-provider-azure/openshift-priv-cloud-provider-azure-main-presubmits.yaml
  ci-operator/jobs/openshift/cloud-provider-azure/openshift-cloud-provider-azure-main-postsubmits.yaml
  ci-operator/jobs/openshift/cloud-provider-azure/openshift-cloud-provider-azure-main-presubmits.yaml
Labels: lgtm, approved, jira/valid-bug, rehearsals-ack, jira/valid-reference

#61190 New virt-density step
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__metal-dev-latest-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__metal-x86.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-presubmits.yaml
  ci-operator/step-registry/openshift-qe/installer/bm/day2/cnv/openshift-qe-installer-bm-day2-cnv-ref.yaml
  ci-operator/step-registry/openshift-qe/virt-density/OWNERS
  ci-operator/step-registry/openshift-qe/virt-density/openshift-qe-virt-density-chain.metadata.json
  ci-operator/step-registry/openshift-qe/virt-density/openshift-qe-virt-density-chain.yaml
  ci-operator/step-registry/openshift-qe/virt-density/openshift-qe-virt-density-commands.sh
  ci-operator/step-registry/openshift-qe/virt-density/openshift-qe-virt-density-ref.metadata.json
  ci-operator/step-registry/openshift-qe/virt-density/openshift-qe-virt-density-ref.yaml
  ci-operator/step-registry/openshift-qe/virt-density/openshift-qe-virt-density-workflow.metadata.json
  ci-operator/step-registry/openshift-qe/virt-density/openshift-qe-virt-density-workflow.yaml
Labels: lgtm, approved, rehearsals-ack, network-access-rehearsals-ok

#60966 OCPBUGS-49304: rename 'master' to 'main' for ironic-rhcos-downloader
  ci-operator/config/openshift-priv/ironic-rhcos-downloader/openshift-priv-ironic-rhcos-downloader-main.yaml
  ci-operator/config/openshift/ironic-rhcos-downloader/openshift-ironic-rhcos-downloader-main.yaml
  ci-operator/config/openshift/ironic-rhcos-downloader/openshift-ironic-rhcos-downloader-main__okd-scos.yaml
  ci-operator/jobs/openshift-priv/ironic-rhcos-downloader/openshift-priv-ironic-rhcos-downloader-main-postsubmits.yaml
  ci-operator/jobs/openshift-priv/ironic-rhcos-downloader/openshift-priv-ironic-rhcos-downloader-main-presubmits.yaml
  ci-operator/jobs/openshift/ironic-rhcos-downloader/openshift-ironic-rhcos-downloader-main-postsubmits.yaml
  ci-operator/jobs/openshift/ironic-rhcos-downloader/openshift-ironic-rhcos-downloader-main-presubmits.yaml
Labels: lgtm, approved, jira/valid-bug, rehearsals-ack, jira/valid-reference

#61468 [release-controller] Bumping tools up to version 4.19
  clusters/app.ci/release-controller/deploy-ocp-arm64-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-arm64-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-multi-2-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-multi-2-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-multi-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-multi-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-ppc64le-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-ppc64le-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-s390x-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-s390x-priv-controller.yaml
  hack/generators/release-controllers/content/osd_files_cache_resources.py
  hack/generators/release-controllers/content/osd_rc_deployments.py
Labels: lgtm, approved, rehearsals-ack

#61481 stackrox scanner 2.36
  ci-operator/config/stackrox/scanner/stackrox-scanner-release-2.36.yaml
  ci-operator/jobs/stackrox/scanner/stackrox-scanner-release-2.36-postsubmits.yaml
  ci-operator/jobs/stackrox/scanner/stackrox-scanner-release-2.36-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#61412 OCPQE-19583: Quay image vulnerabilities Scan with ACS
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__ocp-417-quay.yaml
  ci-operator/jobs/quay/quay-tests/quay-quay-tests-master-periodics.yaml
  ci-operator/step-registry/quay-tests/quay-acs/OWNERS
  ci-operator/step-registry/quay-tests/quay-acs/quay-tests-quay-acs-commands.sh
  ci-operator/step-registry/quay-tests/quay-acs/quay-tests-quay-acs-ref.metadata.json
  ci-operator/step-registry/quay-tests/quay-acs/quay-tests-quay-acs-ref.yaml
  ci-operator/step-registry/quay-tests/quay/deploy-registry-noobaa/OWNERS
  ci-operator/step-registry/quay-tests/quay/deploy-registry-noobaa/quay-tests-quay-deploy-registry-noobaa-commands.sh
  ci-operator/step-registry/quay-tests/quay/deploy-registry-noobaa/quay-tests-quay-deploy-registry-noobaa-ref.metadata.json
  ci-operator/step-registry/quay-tests/quay/deploy-registry-noobaa/quay-tests-quay-deploy-registry-noobaa-ref.yaml
Labels: lgtm, approved, tide/merge-method-squash, rehearsals-ack, jira/valid-reference

#61444 remove TEST_E2E for oc-mirror
  ci-operator/step-registry/mirror-images/by-oc-mirror/mirror-images-by-oc-mirror-commands.sh
Labels: lgtm, approved, rehearsals-ack

#61487 Automate stage.quay.io testing v2
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__stage-quay-io.yaml
  ci-operator/jobs/quay/quay-tests/quay-quay-tests-master-periodics.yaml
  ci-operator/jobs/quay/quay-tests/quay-quay-tests-master-presubmits.yaml
  ci-operator/step-registry/quay-tests/stage-quay-io/OWNERS
  ci-operator/step-registry/quay-tests/stage-quay-io/quay-tests-stage-quay-io-commands.sh
  ci-operator/step-registry/quay-tests/stage-quay-io/quay-tests-stage-quay-io-ref.metadata.json
  ci-operator/step-registry/quay-tests/stage-quay-io/quay-tests-stage-quay-io-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#61491 Upgrade to go 1.23
  ci-operator/config/red-hat-storage/odf-multicluster-orchestrator/red-hat-storage-odf-multicluster-orchestrator-main.yaml
  ci-operator/config/red-hat-storage/odf-multicluster-orchestrator/red-hat-storage-odf-multicluster-orchestrator-release-4.18.yaml
  ci-operator/config/red-hat-storage/odf-multicluster-orchestrator/red-hat-storage-odf-multicluster-orchestrator-release-4.19.yaml
  ci-operator/config/red-hat-storage/odf-multicluster-orchestrator/red-hat-storage-odf-multicluster-orchestrator-release-4.20.yaml
Labels: lgtm, approved, rehearsals-ack

#61431 OCM-13458 | ci: update the autoscaler para to fix the cluster creation failure
  ci-operator/step-registry/rosa/cluster/provision/rosa-cluster-provision-commands.sh
Labels: lgtm, approved, rehearsals-ack

#61494 OAPE-118: remane CFE to OAP
  ci-operator/step-registry/openshift-extended/test/disruptive/openshift-extended-test-disruptive-ref.yaml
  ci-operator/step-registry/openshift-extended/test/longduration/openshift-extended-test-longduration-ref.yaml
  ci-operator/step-registry/openshift-extended/test/openshift-extended-test-ref.yaml
  ci-operator/step-registry/openshift-extended/upgrade/post/openshift-extended-upgrade-post-ref.yaml
  ci-operator/step-registry/openshift-extended/upgrade/pre-custom-cli/openshift-extended-upgrade-pre-custom-cli-ref.yaml
  ci-operator/step-registry/openshift-extended/upgrade/pre/openshift-extended-upgrade-pre-ref.yaml
  ci-operator/step-registry/openshift/e2e/test/hypershift-qe/longrun/openshift-e2e-test-hypershift-qe-longrun-chain.yaml
  ci-operator/step-registry/openshift/e2e/test/hypershift-qe/mgmt/longrun/openshift-e2e-test-hypershift-qe-mgmt-longrun-chain.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#61497 [gitstream] Bumping the `build` job to use golang-1.23.
  ci-operator/config/rh-ecosystem-edge/gitstream/rh-ecosystem-edge-gitstream-main.yaml
Labels: lgtm, approved, rehearsals-ack

#61500 Add Caikit CI for 2.18
  ci-operator/config/red-hat-data-services/caikit-tgis-serving/red-hat-data-services-caikit-tgis-serving-rhoai-2.18.yaml
  ci-operator/jobs/red-hat-data-services/caikit-tgis-serving/red-hat-data-services-caikit-tgis-serving-rhoai-2.18-postsubmits.yaml
  ci-operator/jobs/red-hat-data-services/caikit-tgis-serving/red-hat-data-services-caikit-tgis-serving-rhoai-2.18-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#61473 cloud-provider-azure branch rename update for rebasebot
  ci-operator/config/openshift-eng/rebasebot/openshift-eng-rebasebot-main.yaml
Labels: lgtm, approved, rehearsals-ack

#61507 [INTEROP-7990] Updating default JIRA assignee username for Quay scenario
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__ocp-418-quay.yaml
Labels: lgtm, approved, rehearsals-ack

#60459 add mto test against rosa hcp
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__amd64-nightly.yaml
Labels: lgtm, approved, rehearsals-ack

#61508 [ODF] enable backports for z-streams
  core-services/jira-lifecycle-plugin/config.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#58976 STOR-2078: Add TechPreviewNoUpgrade CI to aws-ebs driver
  ci-operator/config/openshift/aws-ebs-csi-driver/openshift-aws-ebs-csi-driver-master.yaml
  ci-operator/config/openshift/aws-ebs-csi-driver/openshift-aws-ebs-csi-driver-release-4.19.yaml
  ci-operator/config/openshift/aws-ebs-csi-driver/openshift-aws-ebs-csi-driver-release-4.20.yaml
  ci-operator/jobs/openshift/aws-ebs-csi-driver/openshift-aws-ebs-csi-driver-master-periodics.yaml
  ci-operator/jobs/openshift/aws-ebs-csi-driver/openshift-aws-ebs-csi-driver-master-presubmits.yaml
  ci-operator/jobs/openshift/aws-ebs-csi-driver/openshift-aws-ebs-csi-driver-release-4.19-presubmits.yaml
  ci-operator/jobs/openshift/aws-ebs-csi-driver/openshift-aws-ebs-csi-driver-release-4.20-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#61509 update csi-driver-smb unit test configuration
  ci-operator/config/openshift/csi-driver-smb/openshift-csi-driver-smb-master.yaml
  ci-operator/config/openshift/csi-driver-smb/openshift-csi-driver-smb-release-4.16.yaml
  ci-operator/config/openshift/csi-driver-smb/openshift-csi-driver-smb-release-4.17.yaml
  ci-operator/config/openshift/csi-driver-smb/openshift-csi-driver-smb-release-4.18.yaml
  ci-operator/config/openshift/csi-driver-smb/openshift-csi-driver-smb-release-4.19.yaml
  ci-operator/config/openshift/csi-driver-smb/openshift-csi-driver-smb-release-4.20.yaml
Labels: lgtm, approved, rehearsals-ack

#61187 Disable health check from SNO jetlag deploys
  ci-operator/config/redhat-performance/jetlag/redhat-performance-jetlag-main.yaml
Labels: lgtm, approved, rehearsals-ack

#61449 Update OWNERS
  ci-operator/config/jboss-fuse/camel-quarkus-openshift-interop/OWNERS
  ci-operator/jobs/jboss-fuse/camel-quarkus-openshift-interop/OWNERS
  ci-operator/step-registry/camel-quarkus/OWNERS
  ci-operator/step-registry/camel-quarkus/execute-tests/OWNERS
  ci-operator/step-registry/camel-quarkus/execute-tests/camel-quarkus-execute-tests-ref.metadata.json
Labels: lgtm, approved, rehearsals-ack

#61086 [PERFSCALE-3594] Refactor udn-density-pods in Prow
  ci-operator/config/openshift-priv/ovn-kubernetes/openshift-priv-ovn-kubernetes-master.yaml
  ci-operator/config/openshift-priv/ovn-kubernetes/openshift-priv-ovn-kubernetes-release-4.18.yaml
  ci-operator/config/openshift-priv/ovn-kubernetes/openshift-priv-ovn-kubernetes-release-4.19.yaml
  ci-operator/config/openshift-priv/ovn-kubernetes/openshift-priv-ovn-kubernetes-release-4.20.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.18-nightly-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.19-nightly-x86.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.18.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.19.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.20.yaml
  ci-operator/step-registry/openshift-qe/udn-density-l2-pods/openshift-qe-udn-density-l2-pods-chain.metadata.json
  ci-operator/step-registry/openshift-qe/udn-density-l2-pods/openshift-qe-udn-density-l2-pods-chain.yaml
  ci-operator/step-registry/openshift-qe/udn-density-l2-pods/openshift-qe-udn-density-l2-pods-commands.sh
  ci-operator/step-registry/openshift-qe/udn-density-l2-pods/openshift-qe-udn-density-l2-pods-ref.yaml
  ci-operator/step-registry/openshift-qe/udn-density-l2-pods/openshift-qe-udn-density-l2-pods-workflow.metadata.json
  ci-operator/step-registry/openshift-qe/udn-density-l2-pods/openshift-qe-udn-density-l2-pods-workflow.yaml
  ci-operator/step-registry/openshift-qe/udn-density-l3-pods/OWNERS
  ci-operator/step-registry/openshift-qe/udn-density-l3-pods/openshift-qe-udn-density-l3-pods-chain.metadata.json
  ci-operator/step-registry/openshift-qe/udn-density-l3-pods/openshift-qe-udn-density-l3-pods-chain.yaml
  ci-operator/step-registry/openshift-qe/udn-density-l3-pods/openshift-qe-udn-density-l3-pods-workflow.yaml
  ci-operator/step-registry/openshift-qe/udn-density-pods/OWNERS
  ci-operator/step-registry/openshift-qe/udn-density-pods/openshift-qe-udn-density-pods-chain.metadata.json
  ci-operator/step-registry/openshift-qe/udn-density-pods/openshift-qe-udn-density-pods-chain.yaml
  ci-operator/step-registry/openshift-qe/udn-density-pods/openshift-qe-udn-density-pods-commands.sh
  ci-operator/step-registry/openshift-qe/udn-density-pods/openshift-qe-udn-density-pods-ref.metadata.json
  ci-operator/step-registry/openshift-qe/udn-density-pods/openshift-qe-udn-density-pods-ref.yaml
  ci-operator/step-registry/openshift-qe/udn-density-pods/openshift-qe-udn-density-pods-workflow.metadata.json
  ci-operator/step-registry/openshift-qe/udn-density-pods/openshift-qe-udn-density-pods-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#61260 hypershift: create separate techpreview job
  ci-operator/config/openshift/hypershift/openshift-hypershift-main.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#61522 MGMT-19902: Add assisted temporary images streams to QCI
  core-services/image-mirroring/_config.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference
