Repository openshift/release, pull requests merged in 2025-03, with the labels that each got.

#62253 [INTEROP-7913] OCP 4.19 expansion for Dev Spaces scenario.
  ci-operator/config/redhat-developer/devspaces-interop-tests/redhat-developer-devspaces-interop-tests-main__devspaces-ocp4.19-lp-interop.yaml
  ci-operator/jobs/redhat-developer/devspaces-interop-tests/redhat-developer-devspaces-interop-tests-main-periodics.yaml
  ci-operator/jobs/redhat-developer/devspaces-interop-tests/redhat-developer-devspaces-interop-tests-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#62254 [INTEROP-7913] OCP 4.19 expansion for GitOps 1.15 scenario.
  ci-operator/config/redhat-developer/gitops-operator/redhat-developer-gitops-operator-v1.15__gitops-ocp4.19-lp-interop.yaml
  ci-operator/jobs/redhat-developer/gitops-operator/redhat-developer-gitops-operator-v1.15-periodics.yaml
  ci-operator/jobs/redhat-developer/gitops-operator/redhat-developer-gitops-operator-v1.15-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#61910 update jboss-fuse Camel Quarkus for ocp 4.19
  ci-operator/config/jboss-fuse/camel-quarkus-openshift-interop/jboss-fuse-camel-quarkus-openshift-interop-main__camel-quarkus-ocp4.18-lp-interop.yaml
  ci-operator/config/jboss-fuse/camel-quarkus-openshift-interop/jboss-fuse-camel-quarkus-openshift-interop-main__camel-quarkus-ocp4.19-lp-interop.yaml
  ci-operator/jobs/jboss-fuse/camel-quarkus-openshift-interop/jboss-fuse-camel-quarkus-openshift-interop-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#62230 Update prow config to support `jira/valid-reference` label for main branch of openshift/ocp-release-operator-sdk
  core-services/prow/02_config/openshift/ocp-release-operator-sdk/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#62258 [INTEROP-7913] OCP 4.19 expansion for MTR 1.2 scenario.
  ci-operator/config/windup/windup-ui-tests/windup-windup-ui-tests-v1.2__mtr-ocp4.19-lp-interop.yaml
  ci-operator/jobs/windup/windup-ui-tests/windup-windup-ui-tests-v1.2-periodics.yaml
  ci-operator/jobs/windup/windup-ui-tests/windup-windup-ui-tests-v1.2-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#62262 Fix azure sp deprovision issue
  ci-operator/step-registry/azure/deprovision/sp-and-custom-role/azure-deprovision-sp-and-custom-role-commands.sh
Labels: lgtm, approved, rehearsals-ack

#62249 Increase HyperShift job timeouts
  core-services/prow/02_config/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#62138 OCM-14090 | update 4.18,4.17,4.16 and adjust the cron time for OSD with OCP e2e testing
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-stable.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#62142 OCPQE-26161: add chain openshift-e2e-test-clusterinfra-qe-regression
  ci-operator/step-registry/openshift/e2e/test/clusterinfra-qe/longrun/openshift-e2e-test-clusterinfra-qe-longrun-chain.yaml
  ci-operator/step-registry/openshift/e2e/test/clusterinfra-qe/openshift-e2e-test-clusterinfra-qe-ref.yaml
  ci-operator/step-registry/openshift/e2e/test/clusterinfra-qe/regression/OWNERS
  ci-operator/step-registry/openshift/e2e/test/clusterinfra-qe/regression/openshift-e2e-test-clusterinfra-qe-regression-chain.metadata.json
  ci-operator/step-registry/openshift/e2e/test/clusterinfra-qe/regression/openshift-e2e-test-clusterinfra-qe-regression-chain.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#62245 [openshift-psap/topsail] Use the prebuilt image for the jump-ci
  ci-operator/config/openshift-psap/topsail/openshift-psap-topsail-main__jump.yaml
  ci-operator/config/openshift-psap/topsail/openshift-psap-topsail-main__mac_ai.yaml
  ci-operator/config/openshift-psap/topsail/openshift-psap-topsail-main__macai.yaml
  ci-operator/jobs/openshift-psap/topsail/openshift-psap-topsail-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#62264 add ux-approved label to allowed labels list
  core-services/prow/02_config/_plugins.yaml
Labels: lgtm, approved, rehearsals-ack

#60262 mirror images with oc-mirror in upgrade job
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__amd64-nightly-4.19-upgrade-from-stable-4.18.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__amd64-stable-4.19-upgrade-from-stable-4.18.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19-periodics.yaml
  ci-operator/step-registry/cucushift/upgrade/mirror-images/by-oc-mirror/OWNERS
  ci-operator/step-registry/cucushift/upgrade/mirror-images/by-oc-mirror/cucushift-upgrade-mirror-images-by-oc-mirror-commands.sh
  ci-operator/step-registry/cucushift/upgrade/mirror-images/by-oc-mirror/cucushift-upgrade-mirror-images-by-oc-mirror-ref.metadata.json
  ci-operator/step-registry/cucushift/upgrade/mirror-images/by-oc-mirror/cucushift-upgrade-mirror-images-by-oc-mirror-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#62268 Run security scan for RHOSDT 3.5
  ci-operator/config/openshift/distributed-tracing-qe/openshift-distributed-tracing-qe-main__ocp-4.14-dast.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__upstream-ocp-4.15-amd64-aws.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__upstream-ocp-4.15-amd64-aws.yaml
  ci-operator/jobs/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#62277 Missed in removal of build10 config
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#60386 CM-424: [o/cert-manager-operator] moved e2e test cases for TechPreview features
  ci-operator/config/openshift/cert-manager-operator/openshift-cert-manager-operator-cert-manager-1.15.yaml
  ci-operator/config/openshift/cert-manager-operator/openshift-cert-manager-operator-master.yaml
  ci-operator/jobs/openshift/cert-manager-operator/openshift-cert-manager-operator-cert-manager-1.15-presubmits.yaml
  ci-operator/jobs/openshift/cert-manager-operator/openshift-cert-manager-operator-master-presubmits.yaml
Labels: lgtm, approved, lifecycle/stale, rehearsals-ack, jira/valid-reference

#62031 [openstack-k8s-operators] Add workflow for chainsaw tests
  ci-operator/config/openstack-k8s-operators/mariadb-operator/openstack-k8s-operators-mariadb-operator-main.yaml
  ci-operator/jobs/openstack-k8s-operators/mariadb-operator/openstack-k8s-operators-mariadb-operator-main-presubmits.yaml
  ci-operator/step-registry/openstack-k8s-operators/chainsaw/OWNERS
  ci-operator/step-registry/openstack-k8s-operators/chainsaw/openstack-k8s-operators-chainsaw-commands.sh
  ci-operator/step-registry/openstack-k8s-operators/chainsaw/openstack-k8s-operators-chainsaw-ref.metadata.json
  ci-operator/step-registry/openstack-k8s-operators/chainsaw/openstack-k8s-operators-chainsaw-ref.yaml
  ci-operator/step-registry/openstack-k8s-operators/test/build-chainsaw/OWNERS
  ci-operator/step-registry/openstack-k8s-operators/test/build-chainsaw/openstack-k8s-operators-test-build-chainsaw-workflow.metadata.json
  ci-operator/step-registry/openstack-k8s-operators/test/build-chainsaw/openstack-k8s-operators-test-build-chainsaw-workflow.yaml
  ci-operator/step-registry/openstack-k8s-operators/test/build-deploy-chainsaw/OWNERS
  ci-operator/step-registry/openstack-k8s-operators/test/build-deploy-chainsaw/openstack-k8s-operators-test-build-deploy-chainsaw-workflow.metadata.json
  ci-operator/step-registry/openstack-k8s-operators/test/build-deploy-chainsaw/openstack-k8s-operators-test-build-deploy-chainsaw-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#62218 ACM Obs: use ACM release 2.13 on main branch
  ci-operator/config/stolostron/multicluster-observability-operator/stolostron-multicluster-observability-operator-main.yaml
Labels: lgtm, approved, rehearsals-ack

#61657 SDN-5217: Add BGP jobs for 4.18 and dualstack
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.18.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.18__periodics.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.19.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.19__periodics.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.20.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master-presubmits.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.18-periodics.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.18-presubmits.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.19-periodics.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.19-presubmits.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.20-presubmits.yaml
  ci-operator/step-registry/baremetalds/e2e/ovn/bgp/pre/baremetalds-e2e-ovn-bgp-pre-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#62045 NETOBSERV-2129 expose ADDITIONAL_PARAMS var used for indexing
  ci-operator/step-registry/openshift-qe/cluster-density-v2/openshift-qe-cluster-density-v2-ref.yaml
  ci-operator/step-registry/openshift-qe/ingress-perf/openshift-qe-ingress-perf-ref.yaml
  ci-operator/step-registry/openshift-qe/node-density/openshift-qe-node-density-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#62281 Bump KDO, descheduler and OSSO ocp and go versions
  ci-operator/config/openshift/cluster-kube-descheduler-operator/openshift-cluster-kube-descheduler-operator-release-4.19.yaml
  ci-operator/config/openshift/cluster-kube-descheduler-operator/openshift-cluster-kube-descheduler-operator-release-4.20.yaml
  ci-operator/config/openshift/descheduler/openshift-descheduler-release-4.19.yaml
  ci-operator/config/openshift/descheduler/openshift-descheduler-release-4.20.yaml
  ci-operator/config/openshift/secondary-scheduler-operator/openshift-secondary-scheduler-operator-release-4.19.yaml
  ci-operator/config/openshift/secondary-scheduler-operator/openshift-secondary-scheduler-operator-release-4.20.yaml
Labels: lgtm, approved, rehearsals-ack

#62285 CM-424: [o/cert-manager-operator] Update filepath pattern for e2e-operator-tech-preview
  ci-operator/config/openshift/cert-manager-operator/openshift-cert-manager-operator-cert-manager-1.15.yaml
  ci-operator/config/openshift/cert-manager-operator/openshift-cert-manager-operator-master.yaml
  ci-operator/jobs/openshift/cert-manager-operator/openshift-cert-manager-operator-cert-manager-1.15-presubmits.yaml
  ci-operator/jobs/openshift/cert-manager-operator/openshift-cert-manager-operator-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#61747 OCPBUGS-50960: rename 'master' to 'main' for operator-framework-olm
  ci-operator/config/openshift-priv/operator-framework-olm/openshift-priv-operator-framework-olm-main.yaml
  ci-operator/config/openshift-priv/operator-framework-olm/openshift-priv-operator-framework-olm-main__periodics.yaml
  ci-operator/config/openshift/operator-framework-olm/openshift-operator-framework-olm-main.yaml
  ci-operator/config/openshift/operator-framework-olm/openshift-operator-framework-olm-main__okd-scos.yaml
  ci-operator/config/openshift/operator-framework-olm/openshift-operator-framework-olm-main__periodics.yaml
  ci-operator/jobs/openshift-priv/operator-framework-olm/openshift-priv-operator-framework-olm-main-postsubmits.yaml
  ci-operator/jobs/openshift-priv/operator-framework-olm/openshift-priv-operator-framework-olm-main-presubmits.yaml
  ci-operator/jobs/openshift/operator-framework-olm/openshift-operator-framework-olm-main-periodics.yaml
  ci-operator/jobs/openshift/operator-framework-olm/openshift-operator-framework-olm-main-postsubmits.yaml
  ci-operator/jobs/openshift/operator-framework-olm/openshift-operator-framework-olm-main-presubmits.yaml
Labels: lgtm, approved, jira/valid-bug, rehearsals-ack, jira/valid-reference

#61643 PODAUTO-308: add openshift/aws-karpenter-provider-aws configurations
  OWNERS_ALIASES
  ci-operator/config/openshift/aws-karpenter-provider-aws/OWNERS
  ci-operator/config/openshift/aws-karpenter-provider-aws/openshift-aws-karpenter-provider-aws-main.yaml
  ci-operator/jobs/openshift/aws-karpenter-provider-aws/OWNERS
  ci-operator/jobs/openshift/aws-karpenter-provider-aws/openshift-aws-karpenter-provider-aws-main-postsubmits.yaml
  ci-operator/jobs/openshift/aws-karpenter-provider-aws/openshift-aws-karpenter-provider-aws-main-presubmits.yaml
  core-services/prow/02_config/openshift/aws-karpenter-provider-aws/_pluginconfig.yaml
  core-services/prow/02_config/openshift/aws-karpenter-provider-aws/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#61355 oadp-operator: modify periodic run yo use ocp-4.19
  ci-operator/config/openshift/oadp-operator/openshift-oadp-operator-master__4.14.yaml
  ci-operator/config/openshift/oadp-operator/openshift-oadp-operator-master__4.16.yaml
  ci-operator/config/openshift/oadp-operator/openshift-oadp-operator-master__4.18.yaml
  ci-operator/config/openshift/oadp-operator/openshift-oadp-operator-master__4.19.yaml
  ci-operator/jobs/openshift/oadp-operator/openshift-oadp-operator-master-periodics.yaml
  ci-operator/jobs/openshift/oadp-operator/openshift-oadp-operator-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#62291 bump go to V1.23 for ALC subscription repo main, 2.13 and 2.12 releases
  ci-operator/config/stolostron/multicloud-operators-subscription/stolostron-multicloud-operators-subscription-main.yaml
  ci-operator/config/stolostron/multicloud-operators-subscription/stolostron-multicloud-operators-subscription-release-2.12.yaml
  ci-operator/config/stolostron/multicloud-operators-subscription/stolostron-multicloud-operators-subscription-release-2.13.yaml
Labels: lgtm, approved, rehearsals-ack

#60217 adding Gateway API conformance tests
  ci-operator/config/openshift/cluster-ingress-operator/openshift-cluster-ingress-operator-master.yaml
  ci-operator/jobs/openshift/cluster-ingress-operator/openshift-cluster-ingress-operator-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#61840 update stackrox for ocp 4.19
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-17-lp-interop.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-18-lp-interop.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-19-lp-interop.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#62247 Add RHDH upgrade test
  ci-operator/config/redhat-developer/rhdh/redhat-developer-rhdh-main.yaml
  ci-operator/jobs/redhat-developer/rhdh/redhat-developer-rhdh-main-periodics.yaml
  ci-operator/jobs/redhat-developer/rhdh/redhat-developer-rhdh-main-presubmits.yaml
  ci-operator/step-registry/redhat-developer/rhdh/upgrade/OWNERS
  ci-operator/step-registry/redhat-developer/rhdh/upgrade/nightly/OWNERS
  ci-operator/step-registry/redhat-developer/rhdh/upgrade/nightly/redhat-developer-rhdh-upgrade-nightly-commands.sh
  ci-operator/step-registry/redhat-developer/rhdh/upgrade/nightly/redhat-developer-rhdh-upgrade-nightly-ref.metadata.json
  ci-operator/step-registry/redhat-developer/rhdh/upgrade/nightly/redhat-developer-rhdh-upgrade-nightly-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#62314 [INTEROP-7920] Update weekly aws-ipi cron and watcher bot to 4.19.
  ci-operator/config/rhpit/.config.prowgen
  ci-operator/config/rhpit/interop-tests/rhpit-interop-tests-main__weekly_trigger.yaml
  ci-operator/jobs/rhpit/interop-tests/rhpit-interop-tests-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#62324 rhdh job update
  ci-operator/jobs/redhat-developer/rhdh/redhat-developer-rhdh-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#59806 Update test jobs for compliance operator to include testing for all ISC operators
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#62265 add 4.18 Self-managed HyperShift on Multi
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__multi-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#62271 add 418 baremetal mce
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#62338 USHIFT-4915: Reduce MicroShift 4.18 rebase frequency to Mondays and Thursdays
  ci-operator/config/openshift/microshift/openshift-microshift-release-4.18.yaml
  ci-operator/jobs/openshift/microshift/openshift-microshift-release-4.18-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#62329 Fix firefox installation error in quay-test-console images
  ci-operator/config/quay/quay-tests/quay-quay-tests-master.yaml
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__quay-newui-stress.yaml
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__quay-newui.yaml
Labels: lgtm, approved, tide/merge-method-squash, rehearsals-ack

#62322 [INTEROP-7913] OCP 4.19 expansion for Odo scenario.
  ci-operator/config/redhat-developer/odo/redhat-developer-odo-main__odo-ocp4.19-lp-interop.yaml
  ci-operator/jobs/redhat-developer/odo/redhat-developer-odo-main-periodics.yaml
  ci-operator/jobs/redhat-developer/odo/redhat-developer-odo-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#62327 Adjust hypershift-mce-aws-create
  ci-operator/step-registry/hypershift/mce/aws/conformance/hypershift-mce-aws-conformance-workflow.yaml
  ci-operator/step-registry/hypershift/mce/aws/create/hypershift-mce-aws-create-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#62339 Disable protection v1.0
  core-services/prow/02_config/openshift/multiarch-tuning-operator/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#62343 ossm: skip TestGateway/tagged integration test
  ci-operator/config/openshift-service-mesh/istio/openshift-service-mesh-istio-release-1.24.yaml
Labels: lgtm, approved, rehearsals-ack

#62336 add capability support for QE test job controller job
  ci-operator/config/openshift/release-tests/openshift-release-tests-master.yaml
  ci-operator/jobs/openshift/release-tests/openshift-release-tests-master-periodics.yaml
  ci-operator/jobs/openshift/release-tests/openshift-release-tests-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#62205 Adding egressip to e2e-ci
  ci-operator/config/cloud-bulldozer/e2e-benchmarking/cloud-bulldozer-e2e-benchmarking-master.yaml
  ci-operator/jobs/cloud-bulldozer/e2e-benchmarking/cloud-bulldozer-e2e-benchmarking-master-presubmits.yaml
  ci-operator/step-registry/cloud-bulldozer/e2e-benchmarking/egressip/OWNERS
  ci-operator/step-registry/cloud-bulldozer/e2e-benchmarking/egressip/cloud-bulldozer-e2e-benchmarking-egressip-commands.sh
  ci-operator/step-registry/cloud-bulldozer/e2e-benchmarking/egressip/cloud-bulldozer-e2e-benchmarking-egressip-ref.metadata.json
  ci-operator/step-registry/cloud-bulldozer/e2e-benchmarking/egressip/cloud-bulldozer-e2e-benchmarking-egressip-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#62333 Adjust hypershift-conformance to support multi-version test
  ci-operator/step-registry/hypershift/conformance/hypershift-conformance-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#62346 Disable protection
  core-services/prow/02_config/openshift/multiarch-tuning-operator/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#62345 Update blackbox_probe.yaml to fix alerts
  clusters/app.ci/openshift-user-workload-monitoring/blackbox_probe.yaml
Labels: lgtm, approved, rehearsals-ack

#62110 NO-ISSUE: ci-operator/config/openshift/api: Add dev-branch e2e-upgrade-out-of-change
  ci-operator/config/openshift/api/openshift-api-master.yaml
  ci-operator/jobs/openshift/api/openshift-api-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#62198 OU-549: UIPlugin Prow Updates for COO 1.1 release
  ci-operator/config/openshift/distributed-tracing-console-plugin/openshift-distributed-tracing-console-plugin-release-0.4.yaml
  ci-operator/config/openshift/logging-view-plugin/openshift-logging-view-plugin-release-6.1.yaml
  ci-operator/config/openshift/troubleshooting-panel-console-plugin/openshift-troubleshooting-panel-console-plugin-release-0.4.yaml
  ci-operator/jobs/openshift/distributed-tracing-console-plugin/openshift-distributed-tracing-console-plugin-release-0.4-postsubmits.yaml
  ci-operator/jobs/openshift/distributed-tracing-console-plugin/openshift-distributed-tracing-console-plugin-release-0.4-presubmits.yaml
  ci-operator/jobs/openshift/logging-view-plugin/openshift-logging-view-plugin-release-6.1-postsubmits.yaml
  ci-operator/jobs/openshift/logging-view-plugin/openshift-logging-view-plugin-release-6.1-presubmits.yaml
  ci-operator/jobs/openshift/troubleshooting-panel-console-plugin/openshift-troubleshooting-panel-console-plugin-release-0.4-postsubmits.yaml
  ci-operator/jobs/openshift/troubleshooting-panel-console-plugin/openshift-troubleshooting-panel-console-plugin-release-0.4-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#62278 NO-ISSUE: Avoid trigger 3 masters ZTP jobs on changes in /deploy/operator
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.10.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.11.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.12.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.13.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.9.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.10-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.11-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.12-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.13-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-ocm-2.9-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#62147 [INTEROP-7916] Expanding Distributed Tracing operators for OCP 4.19
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.19-lp-interop.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.19-lp-interop.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.19-lp-interop.yaml
  ci-operator/jobs/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main-periodics.yaml
  ci-operator/jobs/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main-periodics.yaml
  ci-operator/jobs/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main-periodics.yaml
  ci-operator/jobs/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#62344 MGMT-20007: Change OLM operator jobs to install OCP 4.18
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-cloud_hotfix_releases.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-cloud_hotfix_releases-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-periodics.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#62065 MULTIARCH-5196: p-px fix failure in the CI
  ci-operator/step-registry/upi/install/powervs/cluster/upi-install-powervs-cluster-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#62350 jira-lifecycle: add 4.18.z for 4.17
  core-services/jira-lifecycle-plugin/config.yaml
Labels: lgtm, approved, rehearsals-ack

#62129 [INTEROP-7917] OCP 4.19 expansion for CNV scenario.
  ci-operator/config/RedHatQE/interop-testing/.config.prowgen
  ci-operator/config/RedHatQE/interop-testing/RedHatQE-interop-testing-cnv-4.18__cnv-odf-ocp4.19-lp-interop.yaml
  ci-operator/jobs/RedHatQE/interop-testing/RedHatQE-interop-testing-cnv-4.18-periodics.yaml
  ci-operator/jobs/RedHatQE/interop-testing/RedHatQE-interop-testing-cnv-4.18-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#62229 Update ocp images on openshift-service-mesh organization to latest
  ci-operator/config/openshift-service-mesh/federation/openshift-service-mesh-federation-master.yaml
  ci-operator/config/openshift-service-mesh/istio/openshift-service-mesh-istio-master.yaml
  ci-operator/config/openshift-service-mesh/istio/openshift-service-mesh-istio-release-1.23.0-redhat.yaml
  ci-operator/config/openshift-service-mesh/istio/openshift-service-mesh-istio-release-1.23.yaml
  ci-operator/config/openshift-service-mesh/istio/openshift-service-mesh-istio-release-1.24.yaml
  ci-operator/config/openshift-service-mesh/sail-operator/openshift-service-mesh-sail-operator-main.yaml
  ci-operator/config/openshift-service-mesh/sail-operator/openshift-service-mesh-sail-operator-release-3.0.yaml
  ci-operator/jobs/openshift-service-mesh/sail-operator/openshift-service-mesh-sail-operator-main-presubmits.yaml
  ci-operator/jobs/openshift-service-mesh/sail-operator/openshift-service-mesh-sail-operator-release-3.0-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#62323 [INTEROP-7913] OCP 4.19 expansion for OpenJDK scenario.
  ci-operator/config/rh-openjdk/jdkContainerOcpTests/rh-openjdk-jdkContainerOcpTests-main__openjdk-ocp4.19-lp-interop.yaml
  ci-operator/jobs/rh-openjdk/jdkContainerOcpTests/rh-openjdk-jdkContainerOcpTests-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#61815 CNTRLPLANE-35: add periodic for 4.17 to 4.18 upgrade
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.18__periodics.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.19__periodics.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.18-periodics.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.19-periodics.yaml
  ci-operator/step-registry/hypershift/azure/aks/e2e/hypershift-azure-aks-e2e-workflow.yaml
  ci-operator/step-registry/hypershift/azure/run-e2e/hypershift-azure-run-e2e-commands.sh
  ci-operator/step-registry/hypershift/azure/run-e2e/hypershift-azure-run-e2e-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#62289 Add retries for image mirroring
  ci-operator/step-registry/ocm/ci/image-mirror/ocm-ci-image-mirror-commands.sh
Labels: lgtm, approved, rehearsals-ack

#62179 OCP_VERSION from candidate-4.18 to latest-4.18
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__metal-4.18-latest-x86.yaml
Labels: lgtm, approved, rehearsals-ack

#62358 jira-lifecycle-plugin: update release-4.17 dependencies
  core-services/jira-lifecycle-plugin/config.yaml
Labels: lgtm, approved, rehearsals-ack

#62360 Approval fix
  core-services/prow/02_config/redhat-performance/jetlag/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#61839 stackrox: expand testing on ocp4.18
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-18.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-4.6__ocp-4-18.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-4.7__ocp-4-18.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-x.y__ocp-4-18.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-postsubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-4.6-postsubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-4.6-presubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-4.7-postsubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-4.7-presubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-x.y-postsubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-x.y-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#62362 submariner-addon: Increase memory limit to 12G
  ci-operator/config/stolostron/submariner-addon/stolostron-submariner-addon-release-2.10.yaml
  ci-operator/config/stolostron/submariner-addon/stolostron-submariner-addon-release-2.11.yaml
  ci-operator/config/stolostron/submariner-addon/stolostron-submariner-addon-release-2.12.yaml
  ci-operator/config/stolostron/submariner-addon/stolostron-submariner-addon-release-2.13.yaml
  ci-operator/config/stolostron/submariner-addon/stolostron-submariner-addon-release-2.9.yaml
Labels: lgtm, approved, rehearsals-ack

#62300 OCPBUGS-52242: rename 'master' to 'main' for cloud-provider-openstack
  ci-operator/config/openshift-priv/cloud-provider-openstack/openshift-priv-cloud-provider-openstack-main.yaml
  ci-operator/config/openshift/cloud-provider-openstack/openshift-cloud-provider-openstack-main.yaml
  ci-operator/config/openshift/cloud-provider-openstack/openshift-cloud-provider-openstack-main__okd-scos.yaml
  ci-operator/jobs/openshift-priv/cloud-provider-openstack/openshift-priv-cloud-provider-openstack-main-postsubmits.yaml
  ci-operator/jobs/openshift-priv/cloud-provider-openstack/openshift-priv-cloud-provider-openstack-main-presubmits.yaml
  ci-operator/jobs/openshift/cloud-provider-openstack/openshift-cloud-provider-openstack-main-postsubmits.yaml
  ci-operator/jobs/openshift/cloud-provider-openstack/openshift-cloud-provider-openstack-main-presubmits.yaml
Labels: lgtm, approved, jira/valid-bug, rehearsals-ack, jira/valid-reference

#62351 OCPBUGS-52242: update merge-bot for rename of CPO master
  ci-operator/config/shiftstack/merge-bot/shiftstack-merge-bot-main.yaml
  ci-operator/jobs/shiftstack/merge-bot/shiftstack-merge-bot-main-periodics.yaml
Labels: lgtm, approved, jira/valid-bug, rehearsals-ack, jira/valid-reference

#62172 feat: add operator images to artifacts directory
  ci-operator/step-registry/osd/gather-extra/osd-gather-extra-commands.sh
Labels: lgtm, approved, rehearsals-ack

#62368 Extend `oc image mirror` retries
  ci-operator/step-registry/ocm/ci/image-mirror/ocm-ci-image-mirror-commands.sh
Labels: lgtm, approved, rehearsals-ack

#62373 NO-JIRA: hypershift: almost never run periodic e2es that run as payload jobs
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.14__periodics.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.15__periodics.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.16__periodics.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.17__periodics.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.18__periodics.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.19__periodics.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.14-periodics.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.15-periodics.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.16-periodics.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.17-periodics.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.18-periodics.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.19-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#61795 kueue: add e2e test
  ci-operator/config/openshift/kubernetes-sigs-kueue/openshift-kubernetes-sigs-kueue-main.yaml
  ci-operator/config/openshift/kubernetes-sigs-kueue/openshift-kubernetes-sigs-kueue-release-4.19.yaml
  ci-operator/config/openshift/kubernetes-sigs-kueue/openshift-kubernetes-sigs-kueue-release-4.20.yaml
  ci-operator/jobs/openshift/kubernetes-sigs-kueue/openshift-kubernetes-sigs-kueue-main-presubmits.yaml
  ci-operator/jobs/openshift/kubernetes-sigs-kueue/openshift-kubernetes-sigs-kueue-release-4.19-presubmits.yaml
  ci-operator/jobs/openshift/kubernetes-sigs-kueue/openshift-kubernetes-sigs-kueue-release-4.20-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#62226 aws only public subnets coverage
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__amd64-nightly-4.19-upgrade-from-stable-4.18.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.18.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.19.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19-periodics.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
  ci-operator/step-registry/aws/provision/tags-for-byo-vpc/aws-provision-tags-for-byo-vpc-commands.sh
  ci-operator/step-registry/aws/provision/tags-for-byo-vpc/aws-provision-tags-for-byo-vpc-ref.yaml
  ci-operator/step-registry/aws/provision/vpc/shared/aws-provision-vpc-shared-commands.sh
  ci-operator/step-registry/aws/provision/vpc/shared/aws-provision-vpc-shared-ref.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/byo-subnets/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/byo-subnets/cucushift-installer-rehearse-aws-ipi-byo-subnets-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/byo-subnets/cucushift-installer-rehearse-aws-ipi-byo-subnets-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/byo-subnets/deprovision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/byo-subnets/deprovision/cucushift-installer-rehearse-aws-ipi-byo-subnets-deprovision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/byo-subnets/deprovision/cucushift-installer-rehearse-aws-ipi-byo-subnets-deprovision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/byo-subnets/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/byo-subnets/provision/cucushift-installer-rehearse-aws-ipi-byo-subnets-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/byo-subnets/provision/cucushift-installer-rehearse-aws-ipi-byo-subnets-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/workers-marketplace/byo-subnets/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/workers-marketplace/byo-subnets/cucushift-installer-rehearse-aws-ipi-workers-marketplace-byo-subnets-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/workers-marketplace/byo-subnets/cucushift-installer-rehearse-aws-ipi-workers-marketplace-byo-subnets-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/workers-marketplace/byo-subnets/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/workers-marketplace/byo-subnets/provision/cucushift-installer-rehearse-aws-ipi-workers-marketplace-byo-subnets-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/workers-marketplace/byo-subnets/provision/cucushift-installer-rehearse-aws-ipi-workers-marketplace-byo-subnets-provision-chain.yaml
  ci-operator/step-registry/ipi/conf/aws/user-min-permissions/ipi-conf-aws-user-min-permissions-commands.sh
  ci-operator/step-registry/ipi/conf/aws/user-min-permissions/ipi-conf-aws-user-min-permissions-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#62340 OCM-14337:increase timeout for the rosacli supplemental job
  ci-operator/config/openshift/rosa/openshift-rosa-master__e2e.yaml
  ci-operator/jobs/openshift/rosa/openshift-rosa-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#62070 [azure] set correct subscription after login with sp
  ci-operator/step-registry/azure/cluster/public-to-private/azure-cluster-public-to-private-commands.sh
  ci-operator/step-registry/azure/deprovision/resourcegroup/azure-deprovision-resourcegroup-commands.sh
  ci-operator/step-registry/azure/deprovision/resourcegroup/cluster/azure-deprovision-resourcegroup-cluster-commands.sh
  ci-operator/step-registry/azure/deprovision/role-assignment/azure-deprovision-role-assignment-commands.sh
  ci-operator/step-registry/azure/deprovision/sp-and-custom-role/azure-deprovision-sp-and-custom-role-commands.sh
  ci-operator/step-registry/azure/provision/bastionhost/azure-provision-bastionhost-commands.sh
  ci-operator/step-registry/azure/provision/bastionhost/managed-identity/azure-provision-bastionhost-managed-identity-commands.sh
  ci-operator/step-registry/azure/provision/custom-role/azure-provision-custom-role-commands.sh
  ci-operator/step-registry/azure/provision/customer-managed-key/azure-provision-customer-managed-key-commands.sh
  ci-operator/step-registry/azure/provision/disk-encryption-set/assign-role/azure-provision-disk-encryption-set-assign-role-commands.sh
  ci-operator/step-registry/azure/provision/disk-encryption-set/azure-provision-disk-encryption-set-commands.sh
  ci-operator/step-registry/azure/provision/disk-encryption-set/day2/system-managed-key/azure-provision-disk-encryption-set-day2-system-managed-key-commands.sh
  ci-operator/step-registry/azure/provision/disk-encryption-set/grant-permission/azure-provision-disk-encryption-set-grant-permission-commands.sh
  ci-operator/step-registry/azure/provision/nat/azure-provision-nat-commands.sh
  ci-operator/step-registry/azure/provision/resourcegroup/azure-provision-resourcegroup-commands.sh
  ci-operator/step-registry/azure/provision/service-principal/hypershift/azure-provision-service-principal-hypershift-commands.sh
  ci-operator/step-registry/azure/provision/service-principal/minimal-permission/azure-provision-service-principal-minimal-permission-commands.sh
  ci-operator/step-registry/azure/provision/storage-account/azure-provision-storage-account-commands.sh
  ci-operator/step-registry/azure/provision/vault-key/azure-provision-vault-key-commands.sh
  ci-operator/step-registry/azure/provision/vnet-hypershift/azure-provision-vnet-hypershift-commands.sh
  ci-operator/step-registry/azure/provision/vnet/azure-provision-vnet-commands.sh
  ci-operator/step-registry/azure/provision/vnet/firewall-route/azure-provision-vnet-firewall-route-commands.sh
  ci-operator/step-registry/cucushift/installer/check/azure/bootstrap/cucushift-installer-check-azure-bootstrap-commands.sh
  ci-operator/step-registry/cucushift/installer/check/azure/confidential/cucushift-installer-check-azure-confidential-commands.sh
  ci-operator/step-registry/cucushift/installer/check/azure/cp/identity/cucushift-installer-check-azure-cp-identity-commands.sh
  ci-operator/step-registry/cucushift/installer/check/azure/cp/lb/probes/cucushift-installer-check-azure-cp-lb-probes-commands.sh
  ci-operator/step-registry/cucushift/installer/check/azure/cpms/cucushift-installer-check-azure-cpms-commands.sh
  ci-operator/step-registry/cucushift/installer/check/azure/des/cucushift-installer-check-azure-des-commands.sh
  ci-operator/step-registry/cucushift/installer/check/azure/destroy/dns/cucushift-installer-check-azure-destroy-dns-commands.sh
  ci-operator/step-registry/cucushift/installer/check/azure/disk/cucushift-installer-check-azure-disk-commands.sh
  ci-operator/step-registry/cucushift/installer/check/azure/fullyprivate/cucushift-installer-check-azure-fullyprivate-commands.sh
  ci-operator/step-registry/cucushift/installer/check/azure/internal-registry/cucushift-installer-check-azure-internal-registry-commands.sh
  ci-operator/step-registry/cucushift/installer/check/azure/multi-zones/cucushift-installer-check-azure-multi-zones-commands.sh
  ci-operator/step-registry/cucushift/installer/check/azure/nat-gateway/cucushift-installer-check-azure-nat-gateway-commands.sh
  ci-operator/step-registry/cucushift/installer/check/azure/networking-type/cucushift-installer-check-azure-networking-type-commands.sh
  ci-operator/step-registry/cucushift/installer/check/azure/osimage/cucushift-installer-check-azure-osimage-commands.sh
  ci-operator/step-registry/cucushift/installer/check/azure/private/cucushift-installer-check-azure-private-commands.sh
  ci-operator/step-registry/cucushift/installer/check/azure/publish-mixed/cucushift-installer-check-azure-publish-mixed-commands.sh
  ci-operator/step-registry/cucushift/installer/check/azure/storage-account/cucushift-installer-check-azure-storage-account-commands.sh
  ci-operator/step-registry/cucushift/installer/check/azure/storage-account/encryption/cucushift-installer-check-azure-storage-account-encryption-commands.sh
  ci-operator/step-registry/cucushift/installer/check/azure/ultrassd-disk/cucushift-installer-check-azure-ultrassd-disk-commands.sh
  ci-operator/step-registry/cucushift/installer/check/azure/usertags/cucushift-installer-check-azure-usertags-commands.sh
  ci-operator/step-registry/cucushift/installer/check/azure/vm-generation/cucushift-installer-check-azure-vm-generation-commands.sh
  ci-operator/step-registry/cucushift/installer/check/azure/vnet/nsg/cucushift-installer-check-azure-vnet-nsg-commands.sh
  ci-operator/step-registry/cucushift/installer/check/azure/vnet/tag/cucushift-installer-check-azure-vnet-tag-commands.sh
  ci-operator/step-registry/ipi/conf/azure/osimage/ipi-conf-azure-osimage-commands.sh
  ci-operator/step-registry/ipi/conf/azure/resourcegroup/assign-role/ipi-conf-azure-resourcegroup-assign-role-commands.sh
  ci-operator/step-registry/ipi/conf/azure/resourcegroup/ipi-conf-azure-resourcegroup-commands.sh
Labels: lgtm, approved, rehearsals-ack

#62204 print ccoctl log to see the details for debug
  ci-operator/step-registry/ipi/conf/azure/oidc-creds-provision/ipi-conf-azure-oidc-creds-provision-commands.sh
Labels: lgtm, approved, rehearsals-ack

#62382 Add quay 3.14 SDL testing
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__quay-sdl.yaml
  ci-operator/jobs/quay/quay-tests/quay-quay-tests-master-periodics.yaml
Labels: lgtm, approved, tide/merge-method-squash, rehearsals-ack

#62371 [INTEROP-7913] OCP 4.19 expansion for Data Grid scenario.
  ci-operator/config/infinispan/infinispan-operator/infinispan-infinispan-operator-stable__data-grid-ocp4.19-lp-interop.yaml
  ci-operator/jobs/infinispan/infinispan-operator/infinispan-infinispan-operator-stable-periodics.yaml
  ci-operator/jobs/infinispan/infinispan-operator/infinispan-infinispan-operator-stable-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#61989 [CLGOVNR-28] Add cloud-governance ecoeng tagging job
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__cloud-governance.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-periodics.yaml
  ci-operator/step-registry/openshift-qe/cloud-governance/OWNERS
  ci-operator/step-registry/openshift-qe/cloud-governance/tagging/OWNERS
  ci-operator/step-registry/openshift-qe/cloud-governance/tagging/openshift-qe-cloud-governance-tagging-commands.sh
  ci-operator/step-registry/openshift-qe/cloud-governance/tagging/openshift-qe-cloud-governance-tagging-ref.metadata.json
  ci-operator/step-registry/openshift-qe/cloud-governance/tagging/openshift-qe-cloud-governance-tagging-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#62359 collect observability must-gather after e2e fails
  ci-operator/config/stolostron/multicluster-observability-operator/stolostron-multicluster-observability-operator-main.yaml
Labels: lgtm, approved, rehearsals-ack

#61159 OCPQE-21261-Added sast scans(snyk) to repos as optional tests for pre…
  ci-operator/config/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-master.yaml
  ci-operator/config/openshift/cluster-api/openshift-cluster-api-release-4.19.yaml
  ci-operator/jobs/openshift/cluster-api-actuator-pkg/openshift-cluster-api-actuator-pkg-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api/openshift-cluster-api-release-4.19-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#62354 Mark ocp destroy post step as optional
  ci-operator/step-registry/stackrox/automation-flavors/ocp-4-crun-e2e/stackrox-automation-flavors-ocp-4-crun-e2e-workflow.yaml
  ci-operator/step-registry/stackrox/automation-flavors/ocp-4-e2e/stackrox-automation-flavors-ocp-4-e2e-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#62369 Use build cache in okd scos
  ci-operator/config/openshift/installer/openshift-installer-main__okd-scos.yaml
Labels: lgtm, approved, rehearsals-ack

#62401 NO-ISSUE: Fix triggeres in cloud_hotfix_releases branch in assisted-service
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-cloud_hotfix_releases.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-cloud_hotfix_releases-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#62402 kueue: switch to the right workdir before getting the SHA
  ci-operator/config/openshift/kubernetes-sigs-kueue/openshift-kubernetes-sigs-kueue-main.yaml
  ci-operator/config/openshift/kubernetes-sigs-kueue/openshift-kubernetes-sigs-kueue-release-4.19.yaml
  ci-operator/config/openshift/kubernetes-sigs-kueue/openshift-kubernetes-sigs-kueue-release-4.20.yaml
Labels: lgtm, approved, rehearsals-ack

#62429 Update instance types to standardize
  clusters/build-clusters/build06/ci-scheduling-webhook/ci-builds-worker-aarch64.yaml
  clusters/build-clusters/build06/ci-scheduling-webhook/ci-builds-worker-amd64.yaml
  clusters/build-clusters/build06/ci-scheduling-webhook/ci-longtests-worker-aarch64.yaml
  clusters/build-clusters/build06/ci-scheduling-webhook/ci-longtests-worker-amd64.yaml
  clusters/build-clusters/build06/ci-scheduling-webhook/ci-prowjobs-worker-aarch64.yaml
  clusters/build-clusters/build06/ci-scheduling-webhook/ci-prowjobs-worker-amd64.yaml
  clusters/build-clusters/build06/ci-scheduling-webhook/ci-tests-worker-aarch64.yaml
  clusters/build-clusters/build06/ci-scheduling-webhook/ci-tests-worker-amd64.yaml
  clusters/build-clusters/build07/ci-scheduling-webhook/ci-builds-worker-aarch64.yaml
  clusters/build-clusters/build07/ci-scheduling-webhook/ci-builds-worker-amd64.yaml
  clusters/build-clusters/build07/ci-scheduling-webhook/ci-longtests-worker-aarch64.yaml
  clusters/build-clusters/build07/ci-scheduling-webhook/ci-longtests-worker-amd64.yaml
  clusters/build-clusters/build07/ci-scheduling-webhook/ci-prowjobs-worker-aarch64.yaml
  clusters/build-clusters/build07/ci-scheduling-webhook/ci-prowjobs-worker-amd64.yaml
  clusters/build-clusters/build07/ci-scheduling-webhook/ci-tests-worker-aarch64.yaml
  clusters/build-clusters/build07/ci-scheduling-webhook/ci-tests-worker-amd64.yaml
  clusters/build-clusters/build09/ci-scheduling-webhook/ci-builds-worker-aarch64.yaml
  clusters/build-clusters/build09/ci-scheduling-webhook/ci-builds-worker-amd64.yaml
  clusters/build-clusters/build09/ci-scheduling-webhook/ci-longtests-worker-aarch64.yaml
  clusters/build-clusters/build09/ci-scheduling-webhook/ci-longtests-worker-amd64.yaml
  clusters/build-clusters/build09/ci-scheduling-webhook/ci-prowjobs-worker-aarch64.yaml
  clusters/build-clusters/build09/ci-scheduling-webhook/ci-prowjobs-worker-amd64.yaml
  clusters/build-clusters/build09/ci-scheduling-webhook/ci-tests-worker-aarch64.yaml
  clusters/build-clusters/build09/ci-scheduling-webhook/ci-tests-worker-amd64.yaml
  clusters/build-clusters/build11/ci-scheduling-webhook/ci-builds-worker-aarch64.yaml
  clusters/build-clusters/build11/ci-scheduling-webhook/ci-builds-worker-amd64.yaml
  clusters/build-clusters/build11/ci-scheduling-webhook/ci-longtests-worker-aarch64.yaml
  clusters/build-clusters/build11/ci-scheduling-webhook/ci-longtests-worker-amd64.yaml
  clusters/build-clusters/build11/ci-scheduling-webhook/ci-prowjobs-worker-aarch64.yaml
  clusters/build-clusters/build11/ci-scheduling-webhook/ci-prowjobs-worker-amd64.yaml
  clusters/build-clusters/build11/ci-scheduling-webhook/ci-tests-worker-aarch64.yaml
  clusters/build-clusters/build11/ci-scheduling-webhook/ci-tests-worker-amd64.yaml
Labels: lgtm, approved, rehearsals-ack

#62430 add rphillips to kubernetes-sigs-kueue
  ci-operator/config/openshift/kubernetes-sigs-kueue/OWNERS
Labels: lgtm, approved, rehearsals-ack

#61986 Adding workers-scale as a reusable step into self-managed AWS
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.16-nightly-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.17-nightly-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.18-nightly-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.19-nightly-x86.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-periodics.yaml
  ci-operator/step-registry/openshift-qe/workers-scale/OWNERS
  ci-operator/step-registry/openshift-qe/workers-scale/openshift-qe-workers-scale-commands.sh
  ci-operator/step-registry/openshift-qe/workers-scale/openshift-qe-workers-scale-ref.metadata.json
  ci-operator/step-registry/openshift-qe/workers-scale/openshift-qe-workers-scale-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#62355 The openshift/operator-lifecycle-manager repo uses main
  ci-operator/jobs/infra-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#61852 update AMQ Broker for ocp 4.19:
  ci-operator/config/rh-messaging-qe/claire/rh-messaging-qe-claire-amq-broker-lpt__amq-broker-ocp4.19-lp-interop.yaml
  ci-operator/jobs/rh-messaging-qe/claire/rh-messaging-qe-claire-amq-broker-lpt-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#61907 update amq-streams for ocp 4.19
  ci-operator/config/amq-streams-qe/strimzi-kafka-operator/amq-streams-qe-strimzi-kafka-operator-main__amq-streams-ocp4.19-lp-interop.yaml
  ci-operator/jobs/amq-streams-qe/strimzi-kafka-operator/amq-streams-qe-strimzi-kafka-operator-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#62348 stackrox: mirror 4.8 images
  core-services/image-mirroring/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#62328 [INTEROP-8078] OCP 4.19 expansion for Quay scenario.
  ci-operator/config/quay/quay-tests/.config.prowgen
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__ocp-419-quay.yaml
  ci-operator/jobs/quay/quay-tests/quay-quay-tests-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#62409 OCPBUGS-52382: Update merge-bot for rename of branch to main
  ci-operator/config/shiftstack/merge-bot/shiftstack-merge-bot-main.yaml
  ci-operator/jobs/shiftstack/merge-bot/shiftstack-merge-bot-main-periodics.yaml
Labels: lgtm, approved, jira/valid-bug, rehearsals-ack, jira/valid-reference

#62427 kueue: use src instead of the base image to get right SHA
  ci-operator/config/openshift/kubernetes-sigs-kueue/openshift-kubernetes-sigs-kueue-main.yaml
  ci-operator/config/openshift/kubernetes-sigs-kueue/openshift-kubernetes-sigs-kueue-release-4.19.yaml
  ci-operator/config/openshift/kubernetes-sigs-kueue/openshift-kubernetes-sigs-kueue-release-4.20.yaml
Labels: lgtm, approved, rehearsals-ack

#62435 updating openshift-preflight operator-sdk version to v1.39.1
  ci-operator/config/redhat-openshift-ecosystem/openshift-preflight/redhat-openshift-ecosystem-openshift-preflight-main__4.13.yaml
  ci-operator/config/redhat-openshift-ecosystem/openshift-preflight/redhat-openshift-ecosystem-openshift-preflight-main__4.18.yaml
Labels: lgtm, approved, rehearsals-ack

#62458 kueue: fix git command to get the right SHA value
  ci-operator/config/openshift/kubernetes-sigs-kueue/openshift-kubernetes-sigs-kueue-main.yaml
  ci-operator/config/openshift/kubernetes-sigs-kueue/openshift-kubernetes-sigs-kueue-release-4.19.yaml
  ci-operator/config/openshift/kubernetes-sigs-kueue/openshift-kubernetes-sigs-kueue-release-4.20.yaml
Labels: lgtm, approved, rehearsals-ack

#62461 kueue: export IMAGE_TAG to allow skopeo to inspect an image
  ci-operator/config/openshift/kubernetes-sigs-kueue/openshift-kubernetes-sigs-kueue-main.yaml
  ci-operator/config/openshift/kubernetes-sigs-kueue/openshift-kubernetes-sigs-kueue-release-4.19.yaml
  ci-operator/config/openshift/kubernetes-sigs-kueue/openshift-kubernetes-sigs-kueue-release-4.20.yaml
Labels: lgtm, approved, rehearsals-ack

#62335 upgrade golang to 1.23 for ocm
  ci-operator/config/stolostron/ocm/stolostron-ocm-backplane-2.8.yaml
Labels: lgtm, approved, rehearsals-ack

#62452 Update builds machinesets back to gp2 until the throughput is fixed
  clusters/build-clusters/01_cluster/ci-scheduling-webhook/ci-builds-worker-aarch64.yaml
  clusters/build-clusters/01_cluster/ci-scheduling-webhook/ci-builds-worker-amd64.yaml
  clusters/build-clusters/build06/ci-scheduling-webhook/ci-builds-worker-aarch64.yaml
  clusters/build-clusters/build06/ci-scheduling-webhook/ci-builds-worker-amd64.yaml
  clusters/build-clusters/build07/ci-scheduling-webhook/ci-builds-worker-aarch64.yaml
  clusters/build-clusters/build07/ci-scheduling-webhook/ci-builds-worker-amd64.yaml
  clusters/build-clusters/build09/ci-scheduling-webhook/ci-builds-worker-aarch64.yaml
  clusters/build-clusters/build09/ci-scheduling-webhook/ci-builds-worker-amd64.yaml
  clusters/build-clusters/build11/ci-scheduling-webhook/ci-builds-worker-aarch64.yaml
  clusters/build-clusters/build11/ci-scheduling-webhook/ci-builds-worker-amd64.yaml
Labels: lgtm, approved, rehearsals-ack

#61802 OCM-14121 | ci: clean the useless paramters
  ci-operator/step-registry/rosa/conf/idp/htpasswd/rosa-conf-idp-htpasswd-commands.sh
  ci-operator/step-registry/rosa/setup/readiness/cluster/rosa-setup-readiness-cluster-commands.sh
  ci-operator/step-registry/rosa/setup/readiness/cluster/rosa-setup-readiness-cluster-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#61859 Merge reuqest for adding ocm token of Insights Operator tests
  ci-operator/config/openshift/insights-operator/openshift-insights-operator-master.yaml
  ci-operator/config/openshift/insights-operator/openshift-insights-operator-release-4.14.yaml
  ci-operator/config/openshift/insights-operator/openshift-insights-operator-release-4.15.yaml
  ci-operator/config/openshift/insights-operator/openshift-insights-operator-release-4.16.yaml
  ci-operator/config/openshift/insights-operator/openshift-insights-operator-release-4.17.yaml
  ci-operator/config/openshift/insights-operator/openshift-insights-operator-release-4.18.yaml
Labels: lgtm, approved, rehearsals-ack

#62459 [INTEROP-7913] OCP 4.19 expansion for ODF scenario.
  ci-operator/config/red-hat-storage/ocs-ci/red-hat-storage-ocs-ci-master__odf-ocp4.19-lp-interop.yaml
  ci-operator/jobs/red-hat-storage/ocs-ci/red-hat-storage-ocs-ci-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#62361 jboss-fuse-camel-k-test-container ocp 4.19 updates
  ci-operator/config/jboss-fuse/camel-k-test-container/jboss-fuse-camel-k-test-container-main__camel-k-ocp4.19-lp-interop.yaml
  ci-operator/jobs/jboss-fuse/camel-k-test-container/jboss-fuse-camel-k-test-container-main-periodics.yaml
  ci-operator/jobs/jboss-fuse/camel-k-test-container/jboss-fuse-camel-k-test-container-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#61702 OCM-9873 | ci: enabled rosa-hcp-shared-vpc 4.18 jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-stable.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#62149 SSCSI-4: Make e2e job required for secrets-store-csi-driver
  ci-operator/config/openshift/secrets-store-csi-driver/openshift-secrets-store-csi-driver-main.yaml
  ci-operator/jobs/openshift/secrets-store-csi-driver/openshift-secrets-store-csi-driver-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#61652 CM-491: add the ability to install cert-manager operator from a custom catalog
  ci-operator/step-registry/cert-manager/custom-api-ingress-cert/cert-manager-custom-api-ingress-cert-chain.yaml
  ci-operator/step-registry/cert-manager/install/catalog/OWNERS
  ci-operator/step-registry/cert-manager/install/catalog/cert-manager-install-catalog-commands.sh
  ci-operator/step-registry/cert-manager/install/catalog/cert-manager-install-catalog-ref.metadata.json
  ci-operator/step-registry/cert-manager/install/catalog/cert-manager-install-catalog-ref.yaml
  ci-operator/step-registry/cert-manager/install/cert-manager-install-chain.metadata.json
  ci-operator/step-registry/cert-manager/install/cert-manager-install-chain.yaml
  ci-operator/step-registry/cert-manager/install/cert-manager-install-commands.sh
  ci-operator/step-registry/cert-manager/install/cert-manager-install-ref.yaml
  ci-operator/step-registry/cert-manager/install/operator/OWNERS
  ci-operator/step-registry/cert-manager/install/operator/cert-manager-install-operator-commands.sh
  ci-operator/step-registry/cert-manager/install/operator/cert-manager-install-operator-ref.metadata.json
  ci-operator/step-registry/cert-manager/install/operator/cert-manager-install-operator-ref.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/aks/hypershift/full-cert/guest/cucushift-installer-rehearse-azure-aks-hypershift-full-cert-guest-workflow.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#61821 OCPQE-28618: Onboard the agent-qe-infra repo
  ci-operator/config/openshift-eng/agent-qe-infra/OWNERS
  ci-operator/config/openshift-eng/agent-qe-infra/openshift-eng-agent-qe-infra-master.yaml
  ci-operator/jobs/openshift-eng/agent-qe-infra/OWNERS
  ci-operator/jobs/openshift-eng/agent-qe-infra/openshift-eng-agent-qe-infra-master-postsubmits.yaml
  ci-operator/jobs/openshift-eng/agent-qe-infra/openshift-eng-agent-qe-infra-master-presubmits.yaml
  core-services/prow/02_config/openshift-eng/agent-qe-infra/OWNERS
  core-services/prow/02_config/openshift-eng/agent-qe-infra/_pluginconfig.yaml
  core-services/prow/02_config/openshift-eng/agent-qe-infra/_prowconfig.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#62484 OCM-14336 | ci: Add gitlab.cee.redhat.com to cluster DNS
  clusters/build-clusters/common_managed/dns.yaml
Labels: lgtm, approved, rehearsals-ack

#62152 Move baremetal-qe-infra repo from openshift-qe to openshift-eng
  ci-operator/config/openshift-eng/baremetal-qe-infra/.config.prowgen
  ci-operator/config/openshift-eng/baremetal-qe-infra/OWNERS
  ci-operator/config/openshift-eng/baremetal-qe-infra/openshift-eng-baremetal-qe-infra-master.yaml
  ci-operator/config/openshift-eng/baremetal-qe-infra/openshift-eng-baremetal-qe-infra-monitoring.yaml
  ci-operator/config/openshift-eng/baremetal-qe-infra/openshift-eng-baremetal-qe-infra-staging.yaml
  ci-operator/jobs/openshift-eng/baremetal-qe-infra/OWNERS
  ci-operator/jobs/openshift-eng/baremetal-qe-infra/openshift-eng-baremetal-qe-infra-master-postsubmits.yaml
  ci-operator/jobs/openshift-eng/baremetal-qe-infra/openshift-eng-baremetal-qe-infra-master-presubmits.yaml
  ci-operator/jobs/openshift-eng/baremetal-qe-infra/openshift-eng-baremetal-qe-infra-monitoring-periodics.yaml
  ci-operator/jobs/openshift-eng/baremetal-qe-infra/openshift-eng-baremetal-qe-infra-staging-postsubmits.yaml
  ci-operator/jobs/openshift-eng/baremetal-qe-infra/openshift-eng-baremetal-qe-infra-staging-presubmits.yaml
  core-services/prow/02_config/openshift-eng/baremetal-qe-infra/OWNERS
  core-services/prow/02_config/openshift-eng/baremetal-qe-infra/_pluginconfig.yaml
  core-services/prow/02_config/openshift-eng/baremetal-qe-infra/_prowconfig.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#62080 Remove feature flag in hypershift aks presub for CAPZ
  ci-operator/config/openshift-priv/cluster-api-provider-azure/openshift-priv-cluster-api-provider-azure-master.yaml
  ci-operator/config/openshift-priv/cluster-api-provider-azure/openshift-priv-cluster-api-provider-azure-release-4.18.yaml
  ci-operator/config/openshift-priv/cluster-api-provider-azure/openshift-priv-cluster-api-provider-azure-release-4.19.yaml
  ci-operator/config/openshift-priv/cluster-api-provider-azure/openshift-priv-cluster-api-provider-azure-release-4.20.yaml
  ci-operator/config/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-master.yaml
  ci-operator/config/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-release-4.18.yaml
  ci-operator/config/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-release-4.19.yaml
  ci-operator/config/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-release-4.20.yaml
Labels: lgtm, approved, rehearsals-ack

#62167 Fix jetlag ci public vlan interface
  ci-operator/config/redhat-performance/jetlag/redhat-performance-jetlag-main.yaml
Labels: lgtm, approved, rehearsals-ack, network-access-rehearsals-ok

#62178 ocpbugs-51379: add hypershift presubmits
  ci-operator/config/openshift/console-operator/openshift-console-operator-main.yaml
  ci-operator/config/openshift/console-operator/openshift-console-operator-release-4.18.yaml
  ci-operator/config/openshift/console-operator/openshift-console-operator-release-4.19.yaml
  ci-operator/config/openshift/console-operator/openshift-console-operator-release-4.20.yaml
  ci-operator/jobs/openshift/console-operator/openshift-console-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/console-operator/openshift-console-operator-release-4.18-presubmits.yaml
  ci-operator/jobs/openshift/console-operator/openshift-console-operator-release-4.19-presubmits.yaml
  ci-operator/jobs/openshift/console-operator/openshift-console-operator-release-4.20-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#62486 Remove pre 4.18 jobs for the oadp-operator
  ci-operator/config/openshift/oadp-operator/openshift-oadp-operator-master__4.17.yaml
  ci-operator/config/openshift/oadp-operator/openshift-oadp-operator-oadp-1.4__4.14.yaml
  ci-operator/config/openshift/oadp-operator/openshift-oadp-operator-oadp-1.4__4.15.yaml
  ci-operator/config/openshift/oadp-operator/openshift-oadp-operator-oadp-1.4__4.16.yaml
  ci-operator/config/openshift/oadp-operator/openshift-oadp-operator-oadp-1.4__4.17.yaml
  ci-operator/jobs/openshift/oadp-operator/openshift-oadp-operator-master-periodics.yaml
  ci-operator/jobs/openshift/oadp-operator/openshift-oadp-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/oadp-operator/openshift-oadp-operator-oadp-1.4-periodics.yaml
  ci-operator/jobs/openshift/oadp-operator/openshift-oadp-operator-oadp-1.4-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#58920 HOSTEDCP-2180: add hypershift-aks-e2e as required presub for cloud-network-config-controller
  ci-operator/config/openshift/cloud-network-config-controller/openshift-cloud-network-config-controller-master.yaml
  ci-operator/config/openshift/cloud-network-config-controller/openshift-cloud-network-config-controller-release-4.18.yaml
  ci-operator/config/openshift/cloud-network-config-controller/openshift-cloud-network-config-controller-release-4.19.yaml
  ci-operator/jobs/openshift/cloud-network-config-controller/openshift-cloud-network-config-controller-master-presubmits.yaml
  ci-operator/jobs/openshift/cloud-network-config-controller/openshift-cloud-network-config-controller-release-4.18-presubmits.yaml
  ci-operator/jobs/openshift/cloud-network-config-controller/openshift-cloud-network-config-controller-release-4.19-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#62363 OpenStack: Add OpenShift version validation in openstack-provision-etcd-on-local-disk step
  ci-operator/step-registry/openstack/provision/etcd-on-local-disk/openstack-provision-etcd-on-local-disk-commands.sh
Labels: lgtm, approved, rehearsals-ack

#62233 USHIFT-5456: microshift add optional-skipped-rpms to rpm-install-aws
  ci-operator/config/openshift/microshift/openshift-microshift-release-4.19__periodics.yaml
  ci-operator/step-registry/openshift/microshift/infra/rpm-install-aws/openshift-microshift-infra-rpm-install-aws-commands.sh
  ci-operator/step-registry/openshift/microshift/infra/rpm-install-aws/openshift-microshift-infra-rpm-install-aws-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#62386 MULTIARCH-5196: p-px vpc public gateway create failure
  ci-operator/step-registry/upi/deprovision/powervs/cluster/upi-deprovision-powervs-cluster-commands.sh
  ci-operator/step-registry/upi/install/heterogeneous/vpc/upi-install-heterogeneous-vpc-commands.sh
  ci-operator/step-registry/upi/install/powervs/cluster/upi-install-powervs-cluster-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#62490 openstack: update tcib branches to track antelope
  ci-operator/config/openstack-k8s-operators/tcib/openstack-k8s-operators-tcib-antelope.yaml
  ci-operator/jobs/openstack-k8s-operators/tcib/openstack-k8s-operators-tcib-antelope-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#62455 MTA expansion for ocp 4.19
  ci-operator/config/konveyor/tackle-ui-tests/konveyor-tackle-ui-tests-release-0.6__mta-ocp4.19-lp-interop.yaml
  ci-operator/jobs/konveyor/tackle-ui-tests/konveyor-tackle-ui-tests-release-0.6-periodics.yaml
  ci-operator/jobs/konveyor/tackle-ui-tests/konveyor-tackle-ui-tests-release-0.6-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#62431 OCPBUGS-52391: rename 'master' to 'main' for machine-config-operator
  ci-operator/config/openshift-priv/machine-config-operator/openshift-priv-machine-config-operator-main.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-main.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-main__4.12-upgrade-from-stable-4.11.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-main__okd-scos.yaml
  ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-main__okd.yaml
  ci-operator/jobs/openshift-priv/machine-config-operator/openshift-priv-machine-config-operator-main-postsubmits.yaml
  ci-operator/jobs/openshift-priv/machine-config-operator/openshift-priv-machine-config-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-main-postsubmits.yaml
  ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-main-presubmits.yaml
Labels: lgtm, approved, jira/valid-bug, rehearsals-ack, jira/valid-reference

#61192 [PERFSCALE-3299] New self-scheduling step
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__metal-selfsched-x86.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-presubmits.yaml
  ci-operator/step-registry/openshift-qe/installer/bm/self-sched-terminate/OWNERS
  ci-operator/step-registry/openshift-qe/installer/bm/self-sched-terminate/openshift-qe-installer-bm-self-sched-terminate-chain.metadata.json
  ci-operator/step-registry/openshift-qe/installer/bm/self-sched-terminate/openshift-qe-installer-bm-self-sched-terminate-chain.yaml
  ci-operator/step-registry/openshift-qe/installer/bm/self-sched-terminate/openshift-qe-installer-bm-self-sched-terminate-commands.sh
  ci-operator/step-registry/openshift-qe/installer/bm/self-sched-terminate/openshift-qe-installer-bm-self-sched-terminate-ref.metadata.json
  ci-operator/step-registry/openshift-qe/installer/bm/self-sched-terminate/openshift-qe-installer-bm-self-sched-terminate-ref.yaml
  ci-operator/step-registry/openshift-qe/installer/bm/self-sched-terminate/openshift-qe-installer-bm-self-sched-terminate-workflow.metadata.json
  ci-operator/step-registry/openshift-qe/installer/bm/self-sched-terminate/openshift-qe-installer-bm-self-sched-terminate-workflow.yaml
  ci-operator/step-registry/openshift-qe/installer/bm/self-sched/OWNERS
  ci-operator/step-registry/openshift-qe/installer/bm/self-sched/openshift-qe-installer-bm-self-sched-chain.metadata.json
  ci-operator/step-registry/openshift-qe/installer/bm/self-sched/openshift-qe-installer-bm-self-sched-chain.yaml
  ci-operator/step-registry/openshift-qe/installer/bm/self-sched/openshift-qe-installer-bm-self-sched-commands.sh
  ci-operator/step-registry/openshift-qe/installer/bm/self-sched/openshift-qe-installer-bm-self-sched-ref.metadata.json
  ci-operator/step-registry/openshift-qe/installer/bm/self-sched/openshift-qe-installer-bm-self-sched-ref.yaml
  ci-operator/step-registry/openshift-qe/installer/bm/self-sched/openshift-qe-installer-bm-self-sched-workflow.metadata.json
  ci-operator/step-registry/openshift-qe/installer/bm/self-sched/openshift-qe-installer-bm-self-sched-workflow.yaml
Labels: lgtm, approved, tide/merge-method-squash, rehearsals-ack

#62404 Reverting change of removing the prow-jobfor the post-leading-zero-check and pre-leading-zero-check
  ci-operator/config/openshift/aws-vpce-operator/.config.prowgen
  ci-operator/config/openshift/aws-vpce-operator/openshift-aws-vpce-operator-main.yaml
  ci-operator/config/openshift/cert-manager-operator/.config.prowgen
  ci-operator/config/openshift/certman-operator/openshift-certman-operator-master.yaml
  ci-operator/config/openshift/custom-domains-operator/.config.prowgen
  ci-operator/config/openshift/custom-domains-operator/openshift-custom-domains-operator-master.yaml
  ci-operator/config/openshift/managed-cluster-validating-webhooks/.config.prowgen
  ci-operator/config/openshift/managed-cluster-validating-webhooks/openshift-managed-cluster-validating-webhooks-master.yaml
  ci-operator/config/openshift/managed-node-metadata-operator/.config.prowgen
  ci-operator/config/openshift/managed-node-metadata-operator/openshift-managed-node-metadata-operator-main.yaml
  ci-operator/config/openshift/managed-velero-operator/.config.prowgen
  ci-operator/config/openshift/managed-velero-operator/openshift-managed-velero-operator-master.yaml
  ci-operator/config/openshift/osd-cluster-ready/.config.prowgen
  ci-operator/config/openshift/osd-cluster-ready/openshift-osd-cluster-ready-master.yaml
  ci-operator/config/openshift/pagerduty-operator/.config.prowgen
  ci-operator/config/openshift/pagerduty-operator/openshift-pagerduty-operator-master.yaml
  ci-operator/jobs/openshift/aws-vpce-operator/openshift-aws-vpce-operator-main-postsubmits.yaml
  ci-operator/jobs/openshift/aws-vpce-operator/openshift-aws-vpce-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/certman-operator/openshift-certman-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/certman-operator/openshift-certman-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/custom-domains-operator/openshift-custom-domains-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/custom-domains-operator/openshift-custom-domains-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/managed-cluster-validating-webhooks/openshift-managed-cluster-validating-webhooks-master-postsubmits.yaml
  ci-operator/jobs/openshift/managed-cluster-validating-webhooks/openshift-managed-cluster-validating-webhooks-master-presubmits.yaml
  ci-operator/jobs/openshift/managed-node-metadata-operator/openshift-managed-node-metadata-operator-main-postsubmits.yaml
  ci-operator/jobs/openshift/managed-node-metadata-operator/openshift-managed-node-metadata-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/managed-velero-operator/openshift-managed-velero-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/managed-velero-operator/openshift-managed-velero-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/osd-cluster-ready/openshift-osd-cluster-ready-master-postsubmits.yaml
  ci-operator/jobs/openshift/osd-cluster-ready/openshift-osd-cluster-ready-master-presubmits.yaml
  ci-operator/jobs/openshift/pagerduty-operator/openshift-pagerduty-operator-master-postsubmits.yaml
  ci-operator/jobs/openshift/pagerduty-operator/openshift-pagerduty-operator-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#62448 oadp ocp 4.19 expansion
  ci-operator/config/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-main__oadp1.4-ocp4.19-lp-interop.yaml
  ci-operator/jobs/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-main-periodics.yaml
  ci-operator/jobs/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#62498 Adding chaos user tag
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__4.15-nightly.yaml
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__4.16-nightly-upgrade.yaml
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__4.16-nightly-x86-cpou-upgrade-4.14.yaml
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__4.16-nightly.yaml
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__4.17-nightly.yaml
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__4.18-nightly-upgrade.yaml
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__4.18-nightly-x86-cpou-upgrade-4.16.yaml
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__4.18-nightly.yaml
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__cr-4.17-nightly.yaml
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__cr-4.18-nightly.yaml
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__cr-4.19-nightly.yaml
Labels: lgtm, approved, rehearsals-ack

#62500 add `stability-fix-approved` label and restrict its use to `openshift-team-leads` and `openshift-staff-engineers`
  core-services/prow/02_config/_labels.yaml
  core-services/prow/02_config/_plugins.yaml
Labels: lgtm, approved, rehearsals-ack

#62426 OCPBUGS-52389: rename 'master' to 'main' for kubevirt-csi-driver
  ci-operator/config/openshift-priv/kubevirt-csi-driver/openshift-priv-kubevirt-csi-driver-main.yaml
  ci-operator/config/openshift/kubevirt-csi-driver/openshift-kubevirt-csi-driver-main.yaml
  ci-operator/config/openshift/kubevirt-csi-driver/openshift-kubevirt-csi-driver-main__okd-scos.yaml
  ci-operator/jobs/openshift-priv/kubevirt-csi-driver/openshift-priv-kubevirt-csi-driver-main-postsubmits.yaml
  ci-operator/jobs/openshift-priv/kubevirt-csi-driver/openshift-priv-kubevirt-csi-driver-main-presubmits.yaml
  ci-operator/jobs/openshift/kubevirt-csi-driver/openshift-kubevirt-csi-driver-main-postsubmits.yaml
  ci-operator/jobs/openshift/kubevirt-csi-driver/openshift-kubevirt-csi-driver-main-presubmits.yaml
Labels: lgtm, approved, jira/valid-bug, rehearsals-ack, jira/valid-reference

#62428 OCPBUGS-52390: rename 'master' to 'main' for machine-api-provider-openstack
  ci-operator/config/openshift-priv/machine-api-provider-openstack/openshift-priv-machine-api-provider-openstack-main.yaml
  ci-operator/config/openshift/machine-api-provider-openstack/openshift-machine-api-provider-openstack-main.yaml
  ci-operator/config/openshift/machine-api-provider-openstack/openshift-machine-api-provider-openstack-main__okd-scos.yaml
  ci-operator/jobs/openshift-priv/machine-api-provider-openstack/openshift-priv-machine-api-provider-openstack-main-postsubmits.yaml
  ci-operator/jobs/openshift-priv/machine-api-provider-openstack/openshift-priv-machine-api-provider-openstack-main-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-provider-openstack/openshift-machine-api-provider-openstack-main-postsubmits.yaml
  ci-operator/jobs/openshift/machine-api-provider-openstack/openshift-machine-api-provider-openstack-main-presubmits.yaml
Labels: lgtm, approved, jira/valid-bug, rehearsals-ack, jira/valid-reference

#62491 Sync Serverless CI config/
  ci-operator/config/openshift-knative/backstage-plugins/openshift-knative-backstage-plugins-release-v1.15__413.yaml
  ci-operator/config/openshift-knative/backstage-plugins/openshift-knative-backstage-plugins-release-v1.15__417.yaml
  ci-operator/config/openshift-knative/backstage-plugins/openshift-knative-backstage-plugins-release-v1.16__414.yaml
  ci-operator/config/openshift-knative/backstage-plugins/openshift-knative-backstage-plugins-release-v1.16__417.yaml
  ci-operator/config/openshift-knative/backstage-plugins/openshift-knative-backstage-plugins-release-v1.16__418.yaml
  ci-operator/config/openshift-knative/backstage-plugins/openshift-knative-backstage-plugins-release-v1.17__414.yaml
  ci-operator/config/openshift-knative/backstage-plugins/openshift-knative-backstage-plugins-release-v1.17__417.yaml
  ci-operator/config/openshift-knative/backstage-plugins/openshift-knative-backstage-plugins-release-v1.17__418.yaml
  ci-operator/config/openshift-knative/eventing/openshift-knative-eventing-release-v1.16__414.yaml
  ci-operator/config/openshift-knative/eventing/openshift-knative-eventing-release-v1.16__417.yaml
  ci-operator/config/openshift-knative/eventing/openshift-knative-eventing-release-v1.16__418.yaml
  ci-operator/config/openshift-knative/eventing/openshift-knative-eventing-release-v1.17__414.yaml
  ci-operator/config/openshift-knative/eventing/openshift-knative-eventing-release-v1.17__417.yaml
  ci-operator/config/openshift-knative/eventing/openshift-knative-eventing-release-v1.17__418.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#62463 Add configuration for compliance-operator 1.6 branch
  ci-operator/config/ComplianceAsCode/compliance-operator/ComplianceAsCode-compliance-operator-1.6.yaml
  ci-operator/jobs/ComplianceAsCode/compliance-operator/ComplianceAsCode-compliance-operator-1.6-postsubmits.yaml
  ci-operator/jobs/ComplianceAsCode/compliance-operator/ComplianceAsCode-compliance-operator-1.6-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#62391 add burner image for 419
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__images.yaml
Labels: lgtm, approved, rehearsals-ack

#62403 Adjust hypershift-mce-aws-conformance to support multi-version test
  ci-operator/step-registry/hypershift/conformance/hypershift-conformance-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#62342 CI implementation: Add EUS upgrade for HCP AWS
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly-4.16-eus-upgrade-from-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly-4.18-eus-upgrade-from-4.16.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#62466 aws - remove useless injected cli
  ci-operator/step-registry/aws/c2s/init-token-service/aws-c2s-init-token-service-commands.sh
  ci-operator/step-registry/aws/c2s/init-token-service/aws-c2s-init-token-service-ref.yaml
  ci-operator/step-registry/aws/c2s/instance-metadata/aws-c2s-instance-metadata-ref.yaml
  ci-operator/step-registry/aws/c2s/mirror-images/aws-c2s-mirror-images-ref.yaml
  ci-operator/step-registry/aws/cluster/public-to-private/aws-cluster-public-to-private-ref.yaml
  ci-operator/step-registry/aws/deprovision/iam-profile/aws-deprovision-iam-profile-ref.yaml
  ci-operator/step-registry/aws/deprovision/iam-role/aws-deprovision-iam-role-ref.yaml
  ci-operator/step-registry/aws/deprovision/kms-key/aws-deprovision-kms-key-ref.yaml
  ci-operator/step-registry/aws/deprovision/security-group/aws-deprovision-security-group-ref.yaml
  ci-operator/step-registry/aws/provision/bastionhost/aws-provision-bastionhost-ref.yaml
  ci-operator/step-registry/aws/provision/cco-manual-users/static/aws-provision-cco-manual-users-static-commands.sh
  ci-operator/step-registry/aws/provision/cco-manual-users/static/aws-provision-cco-manual-users-static-ref.yaml
  ci-operator/step-registry/aws/provision/iam-profile/aws-provision-iam-profile-ref.yaml
  ci-operator/step-registry/aws/provision/iam-role/aws-provision-iam-role-ref.yaml
  ci-operator/step-registry/aws/provision/iam-user/aws-provision-iam-user-ref.yaml
  ci-operator/step-registry/aws/provision/kms-key/aws-provision-kms-key-ref.yaml
  ci-operator/step-registry/aws/provision/security-group/aws-provision-security-group-ref.yaml
  ci-operator/step-registry/aws/provision/tags-for-byo-vpc/aws-provision-tags-for-byo-vpc-ref.yaml
  ci-operator/step-registry/aws/provision/tags-for-byo-vpc/ocm/pre/aws-provision-tags-for-byo-vpc-ocm-pre-ref.yaml
  ci-operator/step-registry/ipi/install/install/aws/ipi-install-install-aws-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#62472 Add config for odf-operator release-4.19 branch
  ci-operator/config/red-hat-storage/odf-operator/red-hat-storage-odf-operator-release-4.19.yaml
  ci-operator/jobs/red-hat-storage/odf-operator/red-hat-storage-odf-operator-release-4.19-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#62349 Revert "Disable protection"
  ci-operator/step-registry/multiarch/tuning-operator/deploy/multiarch-tuning-operator-deploy-commands.sh
  core-services/prow/02_config/openshift/multiarch-tuning-operator/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#62517 LOG-6838: use stable channel for COO
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly-openshift-logging-6.0.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__multi-stable-openshift-logging-6.0.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__multi-stable-openshift-logging-6.1.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-stable-openshift-logging-6.0.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-stable-openshift-logging-6.1.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__multi-stable-openshift-logging-6.0.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__multi-stable-openshift-logging-6.1.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__multi-stable-openshift-logging-6.2.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly-openshift-logging-6.1.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#62518 Update ODF test job to build and use CI-built odf-dependencies-bundle
  ci-operator/config/red-hat-storage/odf-operator/red-hat-storage-odf-operator-main.yaml
  ci-operator/config/red-hat-storage/odf-operator/red-hat-storage-odf-operator-release-4.18.yaml
  ci-operator/config/red-hat-storage/odf-operator/red-hat-storage-odf-operator-release-4.19.yaml
  ci-operator/jobs/red-hat-storage/odf-operator/red-hat-storage-odf-operator-main-presubmits.yaml
  ci-operator/jobs/red-hat-storage/odf-operator/red-hat-storage-odf-operator-release-4.18-presubmits.yaml
  ci-operator/jobs/red-hat-storage/odf-operator/red-hat-storage-odf-operator-release-4.19-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#62519 fix: correct PATH export to include the openshift-tests directory
  ci-operator/step-registry/hypershift/conformance/hypershift-conformance-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#62473 Add config for ocs-operator release-4.19 branch
  ci-operator/config/red-hat-storage/ocs-operator/red-hat-storage-ocs-operator-release-4.19.yaml
  ci-operator/jobs/red-hat-storage/ocs-operator/red-hat-storage-ocs-operator-release-4.19-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#62525 Setup teams allowed to re-run tests on the multiarch-tuning-operator
  core-services/prow/02_config/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#62534 [RHOAI] Refactor main configuration to apply with the new builds
  ci-operator/config/red-hat-data-services/notebooks/red-hat-data-services-notebooks-main.yaml
  ci-operator/jobs/red-hat-data-services/notebooks/red-hat-data-services-notebooks-main-postsubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#61819 OCPBUGS-48630: Add retry logic for mirror release in disconnected metal jobs
  ci-operator/step-registry/baremetalds/e2e/test/baremetalds-e2e-test-commands.sh
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, rehearsals-ack, jira/valid-reference

#62496 update stackrox test images to 0.4.8
  ci-operator/config/stackrox/scanner/stackrox-scanner-master.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-12.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-14-lp-interop.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-15-lp-interop.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-16-lp-interop.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-17-lp-interop.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-17.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-18-lp-interop.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-18.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-19-lp-interop.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-dev-preview.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-next-candidate.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-stable-scanner-v4-install.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies__ocp-4-12.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies__ocp-4-17.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies__ocp-4-18.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-x.y.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-x.y__ocp-4-12.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-x.y__ocp-4-18.yaml
Labels: lgtm, approved, rehearsals-ack

#62536 update: opendatahub-opreator uplift go version
  ci-operator/config/opendatahub-io/opendatahub-operator/opendatahub-io-opendatahub-operator-feature-operator-refactor.yaml
  ci-operator/config/opendatahub-io/opendatahub-operator/opendatahub-io-opendatahub-operator-incubation.yaml
  ci-operator/config/opendatahub-io/opendatahub-operator/opendatahub-io-opendatahub-operator-rhoai.yaml
Labels: lgtm, approved, rehearsals-ack

#62240 remove NetworkSegmentation featuregate as it is GA
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__aws-4.18-nightly-x86.yaml
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__aws-4.19-nightly-x86.yaml
  ci-operator/config/openshift-priv/ovn-kubernetes/openshift-priv-ovn-kubernetes-master.yaml
  ci-operator/config/openshift-priv/ovn-kubernetes/openshift-priv-ovn-kubernetes-release-4.18.yaml
  ci-operator/config/openshift-priv/ovn-kubernetes/openshift-priv-ovn-kubernetes-release-4.19.yaml
  ci-operator/config/openshift-priv/ovn-kubernetes/openshift-priv-ovn-kubernetes-release-4.20.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.18.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.19.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.20.yaml
Labels: lgtm, approved, rehearsals-ack

#62454 TALM: Add a new job to run `yamllint` only if `.tekton` folder is modified
  ci-operator/config/openshift-kni/cluster-group-upgrades-operator/openshift-kni-cluster-group-upgrades-operator-main.yaml
  ci-operator/jobs/openshift-kni/cluster-group-upgrades-operator/openshift-kni-cluster-group-upgrades-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#62464 jws ocp 4.19 expansion
  ci-operator/config/jws-qe/interop-ocp-ci/jws-qe-interop-ocp-ci-main__ocp-4.19-lp-interop.yaml
  ci-operator/jobs/jws-qe/interop-ocp-ci/jws-qe-interop-ocp-ci-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#62471 [INTEROP-7913] OCP 4.19 expansion for JBoss Fuse scenario.
  ci-operator/config/jboss-fuse/fuse-xpaas-qe-container/jboss-fuse-fuse-xpaas-qe-container-main__jboss-fuse-ocp4.19-lp-interop.yaml
  ci-operator/jobs/jboss-fuse/fuse-xpaas-qe-container/jboss-fuse-fuse-xpaas-qe-container-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#62497 HOSTEDCP-2210: Create CI config for hypershift-oadp-plugin repo
  ci-operator/config/openshift/hypershift-oadp-plugin/OWNERS
  ci-operator/config/openshift/hypershift-oadp-plugin/openshift-hypershift-oadp-plugin-main.yaml
  ci-operator/jobs/openshift/hypershift-oadp-plugin/OWNERS
  ci-operator/jobs/openshift/hypershift-oadp-plugin/openshift-hypershift-oadp-plugin-main-presubmits.yaml
  core-services/prow/02_config/openshift/hypershift-oadp-plugin/_pluginconfig.yaml
  core-services/prow/02_config/openshift/hypershift-oadp-plugin/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#62540 update: opendatahub-operator on ocp 4.17
  ci-operator/config/opendatahub-io/opendatahub-operator/opendatahub-io-opendatahub-operator-feature-operator-refactor.yaml
  ci-operator/config/opendatahub-io/opendatahub-operator/opendatahub-io-opendatahub-operator-incubation.yaml
  ci-operator/config/opendatahub-io/opendatahub-operator/opendatahub-io-opendatahub-operator-main.yaml
  ci-operator/config/opendatahub-io/opendatahub-operator/opendatahub-io-opendatahub-operator-rhoai.yaml
Labels: lgtm, approved, rehearsals-ack

#62469 [INTEROP-7913] OCP 4.19 expansion for JBoss EAP 7.4 and EAP XP.
  ci-operator/config/jboss-eap-qe/openshift-eap-tests/jboss-eap-qe-openshift-eap-tests-pit-7.4.x__eap-ocp4.19-lp-interop.yaml
  ci-operator/jobs/jboss-eap-qe/openshift-eap-tests/jboss-eap-qe-openshift-eap-tests-pit-7.4.x-periodics.yaml
  ci-operator/jobs/jboss-eap-qe/openshift-eap-tests/jboss-eap-qe-openshift-eap-tests-pit-7.4.x-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#62367 [INTEROP-8094] OCP 4.19 expansion for Cost Management scenario.
  ci-operator/config/insights-qe/iqe-cost-management-plugin/insights-qe-iqe-cost-management-plugin-master__ocp4.19-lp-interop.yaml
  ci-operator/jobs/insights-qe/iqe-cost-management-plugin/insights-qe-iqe-cost-management-plugin-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#62548 OVMS 2.19 update
  ci-operator/config/opendatahub-io/openvino_model_server/opendatahub-io-openvino_model_server-2025.0-release.yaml
  ci-operator/jobs/opendatahub-io/openvino_model_server/opendatahub-io-openvino_model_server-2025.0-release-postsubmits.yaml
  ci-operator/jobs/opendatahub-io/openvino_model_server/opendatahub-io-openvino_model_server-2025.0-release-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#62453 mtc ocp 4.19 expansion
  ci-operator/config/mtc-qe/mtc-e2e-qev2/mtc-qe-mtc-e2e-qev2-master__mtc1.8-ocp4.19-lp-interop.yaml
  ci-operator/jobs/mtc-qe/mtc-e2e-qev2/mtc-qe-mtc-e2e-qev2-master-periodics.yaml
  ci-operator/jobs/mtc-qe/mtc-e2e-qev2/mtc-qe-mtc-e2e-qev2-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack
