Repository openshift/release, pull requests merged in 2025-01, with the labels that each got.

#60238 Complete bumping HCO to golang 1.23
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-main__okd.yaml
Labels: lgtm, approved, rehearsals-ack

#59721 OCM-12112 | ci: create a new workflow for the private bastion
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18-periodics.yaml
  ci-operator/step-registry/rosa/lifecycle/private-advanced/OWNERS
  ci-operator/step-registry/rosa/lifecycle/private-advanced/rosa-lifecycle-private-advanced-workflow.metadata.json
  ci-operator/step-registry/rosa/lifecycle/private-advanced/rosa-lifecycle-private-advanced-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#60071 CORS-3404: CI profile - Configure IPV4Subnet to customize internal OVN network in BYOVPC
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__multi-nightly-4.18-upgrade-from-stable-4.18.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__multi-nightly-4.19-upgrade-from-stable-4.18.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__multi-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19-periodics.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/ovn/ipv4-subnet/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/ovn/ipv4-subnet/cucushift-installer-rehearse-aws-ipi-ovn-ipv4-subnet-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/ovn/ipv4-subnet/cucushift-installer-rehearse-aws-ipi-ovn-ipv4-subnet-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/ovn/ipv4-subnet/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/ovn/ipv4-subnet/provision/cucushift-installer-rehearse-aws-ipi-ovn-ipv4-subnet-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/ovn/ipv4-subnet/provision/cucushift-installer-rehearse-aws-ipi-ovn-ipv4-subnet-provision-chain.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#60022 MULTIARCH-4866: add more ci for control plane/infra machine type migration
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.18.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.19.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__multi-nightly.yaml
  ci-operator/jobs/openshift/multiarch/openshift-multiarch-master-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#60213 add tech preview support
  ci-operator/step-registry/openshift-extended/web-tests/openshift-extended-web-tests-commands.sh
  ci-operator/step-registry/openshift-extended/web-tests/openshift-extended-web-tests-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#60180 add hypershift from 4.17 to 4.19 upgrade job
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__amd64-nightly-4.19-upgrade-from-stable-4.17.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#60252 add info message in agent step
  ci-operator/step-registry/hypershift/mce/agent/info/hypershift-mce-agent-info-commands.sh
  ci-operator/step-registry/hypershift/mce/install/hypershift-mce-install-commands.sh
Labels: lgtm, approved, rehearsals-ack

#59318 [OCPQE-23477] - Hive workflow - Create hive cluster on AWS by MCE.
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-stable.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17-periodics.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/ovn/hive/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/ovn/hive/mce/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/ovn/hive/mce/cucushift-installer-rehearse-aws-ipi-ovn-hive-mce-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/ovn/hive/mce/cucushift-installer-rehearse-aws-ipi-ovn-hive-mce-workflow.yaml
  ci-operator/step-registry/hive/OWNERS
  ci-operator/step-registry/hive/mce/OWNERS
  ci-operator/step-registry/hive/mce/install/OWNERS
  ci-operator/step-registry/hive/mce/install/hive-mce-install-commands.sh
  ci-operator/step-registry/hive/mce/install/hive-mce-install-ref.metadata.json
  ci-operator/step-registry/hive/mce/install/hive-mce-install-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#59990 OCM-13147 | ci: remove case filter 'important'
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#60157 OCPQE-25970: Add Apiserver sno longduration test profile
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__arm64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#60264 Added new members to cherry-pick-approved label
  core-services/prow/02_config/openshift/cluster-node-tuning-operator/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#60143 MULTIARCH-5040: add pods labels validation for mto perfscale test
  ci-operator/config/openshift/multiarch-tuning-operator/openshift-multiarch-tuning-operator-main__ocp417.yaml
  ci-operator/step-registry/multiarch/tuning-operator/validate-pods-labels/OWNERS
  ci-operator/step-registry/multiarch/tuning-operator/validate-pods-labels/multiarch-tuning-operator-validate-pods-labels-commands.sh
  ci-operator/step-registry/multiarch/tuning-operator/validate-pods-labels/multiarch-tuning-operator-validate-pods-labels-ref.metadata.json
  ci-operator/step-registry/multiarch/tuning-operator/validate-pods-labels/multiarch-tuning-operator-validate-pods-labels-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#60265 Update golang to v1.23.4 on ci-tools build root
  clusters/build-clusters/build06/supplemental-ci-images/002_ci-tools-build-root-mabc.yaml
  clusters/build-clusters/build10/supplemental-ci-images/002_ci-tools-build-root-mabc.yaml
  clusters/build-clusters/build11/supplemental-ci-images/002_ci-tools-build-root-mabc.yaml
Labels: lgtm, approved, rehearsals-ack

#60176 OCPQE-26586: Remove cucushit cases in vSphere multi-vcenter profile
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__amd64-nightly.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#60269 [KMM] Bumping images to `go1.23`.
  ci-operator/config/rh-ecosystem-edge/kernel-module-management/rh-ecosystem-edge-kernel-module-management-main.yaml
Labels: lgtm, approved, rehearsals-ack

#60273 [KMM] Chaning the container image for the `lint` job.
  ci-operator/config/rh-ecosystem-edge/kernel-module-management/rh-ecosystem-edge-kernel-module-management-main.yaml
Labels: lgtm, approved, rehearsals-ack

#60173 MULTIARCH-4696: change to s922 and prefix that aligns with CI
  ci-operator/step-registry/upi/install/heterogeneous/powervs/upi-install-heterogeneous-powervs-commands.sh
  ci-operator/step-registry/upi/install/powervs/cluster/upi-install-powervs-cluster-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#60276 Update the openshift-monitoring config
  clusters/build-clusters/build09/openshift-monitoring/cluster-monitoring-config.yaml
Labels: lgtm, approved, rehearsals-ack

#60102 cri-o: update main job settings
  ci-operator/config/cri-o/cri-o/cri-o-cri-o-main.yaml
Labels: lgtm, approved, rehearsals-ack

#60278 Revert "[CVP-4352] Reduce cluster pool runningCount during December holidays"
  clusters/hosted-mgmt/hive/pools/cvp/cvp-fips-ocp-4-14-amd64-aws-eu-north-1_clusterpool.yaml
  clusters/hosted-mgmt/hive/pools/cvp/cvp-fips-ocp-4-15-amd64-aws-eu-west-1_clusterpool.yaml
  clusters/hosted-mgmt/hive/pools/cvp/cvp-fips-ocp-4-16-amd64-aws-us-west-1_clusterpool.yaml
  clusters/hosted-mgmt/hive/pools/cvp/cvp-fips-ocp-4-17-amd64-aws-us-east-1_clusterpool.yaml
  clusters/hosted-mgmt/hive/pools/cvp/cvp-fips-ocp-4-18-amd64-aws-us-east-2_clusterpool.yaml
  clusters/hosted-mgmt/hive/pools/cvp/cvp-ocp-4-12-amd64-aws-eu-west-3_clusterpool.yaml
  clusters/hosted-mgmt/hive/pools/cvp/cvp-ocp-4-13-amd64-aws-eu-central-1_clusterpool.yaml
  clusters/hosted-mgmt/hive/pools/cvp/cvp-ocp-4-14-amd64-aws-eu-north-1_clusterpool.yaml
  clusters/hosted-mgmt/hive/pools/cvp/cvp-ocp-4-15-amd64-aws-eu-west-1_clusterpool.yaml
  clusters/hosted-mgmt/hive/pools/cvp/cvp-ocp-4-16-amd64-aws-us-west-1_clusterpool.yaml
  clusters/hosted-mgmt/hive/pools/cvp/cvp-ocp-4-17-amd64-aws-us-east-1_clusterpool.yaml
  clusters/hosted-mgmt/hive/pools/cvp/cvp-ocp-4-18-amd64-aws-us-east-2_clusterpool.yaml
Labels: lgtm, approved, rehearsals-ack

#60163 update steps to deploy logging operators
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly-openshift-logging-5.6.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly-openshift-logging-5.7.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-openshift-logging-5.7.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly-openshift-logging-5.8.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-nightly-openshift-logging-5.7.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly-openshift-logging-5.8.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly-openshift-logging-6.0.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly-openshift-logging-5.8.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-nightly-openshift-logging-5.7.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly-openshift-logging-5.9.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__multi-nightly-openshift-logging-5.8.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__multi-stable-openshift-logging-6.0.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__multi-stable-openshift-logging-6.1.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly-openshift-logging-5.9.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-stable-openshift-logging-6.0.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-stable-openshift-logging-6.1.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__multi-stable-openshift-logging-6.0.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__multi-stable-openshift-logging-6.1.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly-openshift-logging-6.1.yaml
  ci-operator/step-registry/install-operators/README.md
  ci-operator/step-registry/install-operators/install-operators-commands.sh
  ci-operator/step-registry/operatorhub/subscribe/cluster-logging-operator/OWNERS
  ci-operator/step-registry/operatorhub/subscribe/cluster-logging-operator/operatorhub-subscribe-cluster-logging-operator-commands.sh
  ci-operator/step-registry/operatorhub/subscribe/cluster-logging-operator/operatorhub-subscribe-cluster-logging-operator-ref.metadata.json
  ci-operator/step-registry/operatorhub/subscribe/cluster-logging-operator/operatorhub-subscribe-cluster-logging-operator-ref.yaml
  ci-operator/step-registry/operatorhub/subscribe/elasticsearch-operator/OWNERS
  ci-operator/step-registry/operatorhub/subscribe/elasticsearch-operator/README.md
  ci-operator/step-registry/operatorhub/subscribe/elasticsearch-operator/operatorhub-subscribe-elasticsearch-operator-commands.sh
  ci-operator/step-registry/operatorhub/subscribe/elasticsearch-operator/operatorhub-subscribe-elasticsearch-operator-ref.metadata.json
  ci-operator/step-registry/operatorhub/subscribe/elasticsearch-operator/operatorhub-subscribe-elasticsearch-operator-ref.yaml
  ci-operator/step-registry/operatorhub/subscribe/loki-operator/OWNERS
  ci-operator/step-registry/operatorhub/subscribe/loki-operator/operatorhub-subscribe-loki-operator-commands.sh
  ci-operator/step-registry/operatorhub/subscribe/loki-operator/operatorhub-subscribe-loki-operator-ref.metadata.json
  ci-operator/step-registry/operatorhub/subscribe/loki-operator/operatorhub-subscribe-loki-operator-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#60251 OCPQE-26161: Add openshift-e2e-test-clusterinfra-qe step to run cluster infrastracutre team cases
  ci-operator/step-registry/openshift/e2e/test/qe/openshift-e2e-test-qe-chain.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#60120 OCPQE-27281: Update cluster infrastructure longduration jobs
  ci-operator/config/openshift/openshift-tests-private/.config.prowgen
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__multi-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#60281 Turning off always run for some runs
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#60260 enabel qe HO install TechPreviewNoUpgrade in 4.19
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__amd64-nightly.yaml
Labels: lgtm, approved, rehearsals-ack

#60284 [azure] disable encryptionAtHost for azure confidentialVM upgrade job
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly-4.18-upgrade-from-stable-4.18.yaml
Labels: lgtm, approved, rehearsals-ack

#60066 OCPQE-27761 Add 4.19 canary upgrade jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-nightly-4.17-upgrade-from-stable-4.16.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__multi-nightly-4.17-upgrade-from-stable-4.16.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__amd64-nightly-4.19-upgrade-from-stable-4.18.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__multi-nightly-4.19-upgrade-from-stable-4.18.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19-periodics.yaml
  ci-operator/step-registry/openshift/upgrade/qe/test/canary/openshift-upgrade-qe-test-canary-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#60294 Add a toleration on the build09 cluster-install
  clusters/_cluster-install/build09.yaml
Labels: lgtm, approved, rehearsals-ack

#60069 [INTEROP-7903] Serverless: Change cron expressions to prevent interop periodic jobs from bypassing weekly trigger job and running on scheduled date.
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main__ocp4.17-lp-rosa-classic.yaml
  ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main__ocp4.18-lp-interop.yaml
  ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#60298 lightspeed-operator: ignore renovate.json for E2E test
  ci-operator/config/openshift/lightspeed-operator/openshift-lightspeed-operator-main.yaml
  ci-operator/jobs/openshift/lightspeed-operator/openshift-lightspeed-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#60300 Fix ci-tools build root and the multiarch-builder controller
  clusters/build-clusters/build06/supplemental-ci-images/002_ci-tools-build-root-mabc.yaml
  clusters/build-clusters/build10/multi-arch-builder-controller/100_deploy.yaml
  clusters/build-clusters/build10/supplemental-ci-images/002_ci-tools-build-root-mabc.yaml
  clusters/build-clusters/build11/supplemental-ci-images/002_ci-tools-build-root-mabc.yaml
  core-services/image-mirroring/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#60301 chore: bump reference addon go version to 1.23
  ci-operator/config/openshift/reference-addon/openshift-reference-addon-main.yaml
Labels: lgtm, approved, rehearsals-ack

#60305 Increase storage for prometheusk8
  clusters/build-clusters/build06/openshift-monitoring/cluster-monitoring-config.yaml
Labels: lgtm, approved, rehearsals-ack

#60312 Fix presubmits for dpu operator make-e2e-tests that will allow tests …
  ci-operator/jobs/openshift/dpu-operator/openshift-dpu-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/dpu-operator/openshift-dpu-operator-release-4.16-presubmits.yaml
  ci-operator/jobs/openshift/dpu-operator/openshift-dpu-operator-release-4.17-presubmits.yaml
  ci-operator/jobs/openshift/dpu-operator/openshift-dpu-operator-release-4.18-presubmits.yaml
  ci-operator/jobs/openshift/dpu-operator/openshift-dpu-operator-release-4.19-presubmits.yaml
  ci-operator/jobs/openshift/dpu-operator/openshift-dpu-operator-release-4.20-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#60309 dont run e2e-aws-kubevirt automatically in ovnk
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master-presubmits.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.17-presubmits.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.18-presubmits.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.19-presubmits.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.20-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#60259 Remove unused build_root
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__multi-stable-openshift-logging-6.1.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-stable-openshift-logging-6.1.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__multi-stable-openshift-logging-6.1.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly-openshift-logging-6.1.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.14.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.15.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.16.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.17.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.18.yaml
Labels: lgtm, approved, rehearsals-ack

#60084 OCPERT-8 Add auto release jobs for 4.17
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__automated-release-stable-4.17-upgrade-from-stable-4.16.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__automated-release-stable-4.17-upgrade-from-stable-4.17.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__automated-release.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#60287 Update golang version
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.12-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.13-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.14-arm-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.14-lp-interop.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.14-lp-rosa-classic.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.14-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.15-ibm-z-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.15-lp-interop.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.15-lp-rosa-classic.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.15-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.16-ibm-p-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.16-lp-interop.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.16-lp-rosa-classic.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.16-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.17-lp-interop.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.17-lp-rosa-classic.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.17-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.18-lp-interop.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__upstream-ocp-4.13-amd64-aws-ipi-ovn-hypershift.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__upstream-ocp-4.14-amd64-gcp-ipi-ovn-ipsec.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__upstream-ocp-4.15-amd64-aws.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__upstream-ocp-4.16-amd64-aws-ipi-shared-vpc-phz-sts.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__upstream-upgrade-ocp-4.17-amd64-azure.yaml
Labels: lgtm, approved, rehearsals-ack

#60160 Implement UPI on baremetal compact profile
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__arm64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#60256 fix mto related jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__multi-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#60325 Add new steps of quay azure app registration and deletions
  ci-operator/step-registry/quay-tests/azure/OWNERS
  ci-operator/step-registry/quay-tests/azure/app-deletion/OWNERS
  ci-operator/step-registry/quay-tests/azure/app-deletion/quay-tests-azure-app-deletion-commands.sh
  ci-operator/step-registry/quay-tests/azure/app-deletion/quay-tests-azure-app-deletion-ref.metadata.json
  ci-operator/step-registry/quay-tests/azure/app-deletion/quay-tests-azure-app-deletion-ref.yaml
  ci-operator/step-registry/quay-tests/azure/app-registrations/OWNERS
  ci-operator/step-registry/quay-tests/azure/app-registrations/quay-tests-azure-app-registrations-commands.sh
  ci-operator/step-registry/quay-tests/azure/app-registrations/quay-tests-azure-app-registrations-ref.metadata.json
  ci-operator/step-registry/quay-tests/azure/app-registrations/quay-tests-azure-app-registrations-ref.yaml
Labels: lgtm, approved, tide/merge-method-squash, rehearsals-ack

#60110 Update interop jobs
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.14-lp-interop.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.14-lp-rosa-classic.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.15-lp-interop.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.15-lp-rosa-classic.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.16-lp-interop.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.16-lp-rosa-classic.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.17-lp-interop.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.17-lp-rosa-classic.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.14-lp-interop.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.14-lp-rosa-classic.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.15-lp-interop.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.15-lp-rosa-classic.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.16-lp-interop.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.16-lp-rosa-classic.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.17-lp-interop.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.17-lp-rosa-classic.yaml
  ci-operator/step-registry/distributed-tracing/tests/opentelemetry/downstream/distributed-tracing-tests-opentelemetry-downstream-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#60324 Update ocs-operator, golang, openshift versions
  ci-operator/config/red-hat-storage/ocs-operator/red-hat-storage-ocs-operator-main.yaml
Labels: lgtm, approved, rehearsals-ack

#60094 OCPERT-8 Enable 4.17 for QE job controller
  ci-operator/config/openshift/release-tests/openshift-release-tests-master.yaml
Labels: lgtm, approved, rehearsals-ack

#60319 Move private jobs to eco-ci-cd-private
  ci-operator/config/openshift-kni/eco-ci-cd-private/.config.prowgen
  ci-operator/config/openshift-kni/eco-ci-cd-private/OWNERS
  ci-operator/config/openshift-kni/eco-ci-cd-private/openshift-kni-eco-ci-cd-private-main__slcm-4.12.yaml
  ci-operator/config/openshift-kni/eco-ci-cd-private/openshift-kni-eco-ci-cd-private-main__slcm-gitlab-project2-site3.yaml
  ci-operator/config/openshift-kni/eco-ci-cd-private/openshift-kni-eco-ci-cd-private-main__slcm-lab.yaml
  ci-operator/jobs/openshift-kni/eco-ci-cd-private/OWNERS
  ci-operator/jobs/openshift-kni/eco-ci-cd-private/openshift-kni-eco-ci-cd-private-main-periodics.yaml
  ci-operator/jobs/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main-periodics.yaml
  core-services/prow/02_config/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#60332 [PERFSCALE-3630] New metal-perfscale-telco lease
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: lgtm, approved, rehearsals-ack

#60307 MULTIARCH-5196: updated parameters for tfvars
  ci-operator/step-registry/upi/install/powervs/cluster/upi-install-powervs-cluster-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#60330 Add '|| true' to prevent failure on destroy cluster agent command
  ci-operator/step-registry/hypershift/mce/agent/destroy/hypershift-mce-agent-destroy-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#60333 cnf-feature-deploy: extend test timeout
  ci-operator/config/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-master.yaml
Labels: lgtm, approved, rehearsals-ack

#58336 Adding gcp etcd fips profile
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__4.18-nightly.yaml
  ci-operator/jobs/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main-periodics.yaml
  ci-operator/step-registry/redhat-chaos/network-chaos/redhat-chaos-network-chaos-ref.yaml
  ci-operator/step-registry/redhat-chaos/node-disruptions/master-outage/redhat-chaos-node-disruptions-master-outage-ref.yaml
  ci-operator/step-registry/redhat-chaos/pod-network-chaos/redhat-chaos-pod-network-chaos-commands.sh
Labels: lgtm, approved, rehearsals-ack

#56755 S390x build publish
  ci-operator/config/opendatahub-io/odh-dashboard/opendatahub-io-odh-dashboard-main.yaml
  ci-operator/jobs/opendatahub-io/odh-dashboard/opendatahub-io-odh-dashboard-main-periodics.yaml
  ci-operator/step-registry/opendatahub-io/ci/s390x-build/OWNERS
  ci-operator/step-registry/opendatahub-io/ci/s390x-build/build-publish/OWNERS
  ci-operator/step-registry/opendatahub-io/ci/s390x-build/build-publish/opendatahub-io-ci-s390x-build-build-publish-workflow.metadata.json
  ci-operator/step-registry/opendatahub-io/ci/s390x-build/build-publish/opendatahub-io-ci-s390x-build-build-publish-workflow.yaml
  ci-operator/step-registry/opendatahub-io/ci/s390x-build/create/OWNERS
  ci-operator/step-registry/opendatahub-io/ci/s390x-build/create/opendatahub-io-ci-s390x-build-create-commands.sh
  ci-operator/step-registry/opendatahub-io/ci/s390x-build/create/opendatahub-io-ci-s390x-build-create-ref.metadata.json
  ci-operator/step-registry/opendatahub-io/ci/s390x-build/create/opendatahub-io-ci-s390x-build-create-ref.yaml
  ci-operator/step-registry/opendatahub-io/ci/s390x-build/dashboard/OWNERS
  ci-operator/step-registry/opendatahub-io/ci/s390x-build/dashboard/opendatahub-io-ci-s390x-build-dashboard-commands.sh
  ci-operator/step-registry/opendatahub-io/ci/s390x-build/dashboard/opendatahub-io-ci-s390x-build-dashboard-ref.metadata.json
  ci-operator/step-registry/opendatahub-io/ci/s390x-build/dashboard/opendatahub-io-ci-s390x-build-dashboard-ref.yaml
  ci-operator/step-registry/opendatahub-io/ci/s390x-build/delete/OWNERS
  ci-operator/step-registry/opendatahub-io/ci/s390x-build/delete/opendatahub-io-ci-s390x-build-delete-commands.sh
  ci-operator/step-registry/opendatahub-io/ci/s390x-build/delete/opendatahub-io-ci-s390x-build-delete-ref.metadata.json
  ci-operator/step-registry/opendatahub-io/ci/s390x-build/delete/opendatahub-io-ci-s390x-build-delete-ref.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#60235 [test] Add node-density-heavy for IBMCloud
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__ibmcloud-4.18-nightly-x86.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#60320 Update S2I golang to 1.22
  ci-operator/config/openshift/source-to-image/openshift-source-to-image-master.yaml
Labels: lgtm, approved, rehearsals-ack

#60018 OCPBUGS-46065: make ipsec jobs required for CNO
  ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-master.yaml
  ci-operator/jobs/openshift/cluster-network-operator/openshift-cluster-network-operator-master-presubmits.yaml
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, rehearsals-ack, jira/valid-reference

#59401 trust red-hat-konflux bot to trigger tests on automated konflux prs
  core-services/prow/02_config/stolostron/insights-client/_pluginconfig.yaml
  core-services/prow/02_config/stolostron/insights-metrics/_pluginconfig.yaml
  core-services/prow/02_config/stolostron/search-collector/_pluginconfig.yaml
  core-services/prow/02_config/stolostron/search-v2-api/_pluginconfig.yaml
  core-services/prow/02_config/stolostron/search-v2-operator/_pluginconfig.yaml
Labels: lgtm, approved, lifecycle/stale, rehearsals-ack

#60338 openstack-kuttl: support new init with minor updates
  ci-operator/step-registry/openstack-k8s-operators/kuttl/openstack-k8s-operators-kuttl-commands.sh
Labels: lgtm, approved, rehearsals-ack

#60271 hypershift aks e2e fix 4.19 periodic and e2e flag typo
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.19__periodics.yaml
  ci-operator/step-registry/hypershift/azure/run-e2e/hypershift-azure-run-e2e-commands.sh
Labels: lgtm, approved, rehearsals-ack

#60352 Set minCreationInterval to 2y for okd-scos 4.16 to stop generating releases
  core-services/release-controller/_releases/release-okd-scos-4.16.json
Labels: lgtm, approved, rehearsals-ack

#60279 Removing R4F4 from the reviewers and approvers list for the installer.
  ci-operator/config/openshift/installer/OWNERS
  ci-operator/jobs/openshift/installer/OWNERS
  ci-operator/step-registry/aws/provision/iam-user/minimal-permission/OWNERS
  ci-operator/step-registry/aws/provision/iam-user/minimal-permission/aws-provision-iam-user-minimal-permission-chain.metadata.json
  ci-operator/step-registry/ipi/conf/aws/user-min-permissions/OWNERS
  ci-operator/step-registry/ipi/conf/aws/user-min-permissions/ipi-conf-aws-user-min-permissions-ref.metadata.json
  ci-operator/step-registry/openshift/installer/OWNERS
  ci-operator/step-registry/openshift/installer/manifests/aws/edge-zones/openshift-installer-manifests-aws-edge-zones-ref.metadata.json
  ci-operator/step-registry/openshift/installer/manifests/aws/edge-zones/openshift-installer-manifests-aws-edge-zones-workflow.metadata.json
  ci-operator/templates/openshift/installer/OWNERS
  core-services/prow/02_config/openshift/installer/OWNERS
Labels: lgtm, approved, rehearsals-ack

#60356 [content-mirror] Removing the external liveness probe in favor of the internal logic
  clusters/build-clusters/common/release-controller/rpms-ocp-3.11.yaml
  clusters/build-clusters/common/release-controller/rpms-ocp-4.1.yaml
  clusters/build-clusters/common/release-controller/rpms-ocp-4.10.yaml
  clusters/build-clusters/common/release-controller/rpms-ocp-4.11.yaml
  clusters/build-clusters/common/release-controller/rpms-ocp-4.12.yaml
  clusters/build-clusters/common/release-controller/rpms-ocp-4.13.yaml
  clusters/build-clusters/common/release-controller/rpms-ocp-4.14.yaml
  clusters/build-clusters/common/release-controller/rpms-ocp-4.15.yaml
  clusters/build-clusters/common/release-controller/rpms-ocp-4.16.yaml
  clusters/build-clusters/common/release-controller/rpms-ocp-4.17.yaml
  clusters/build-clusters/common/release-controller/rpms-ocp-4.18.yaml
  clusters/build-clusters/common/release-controller/rpms-ocp-4.19.yaml
  clusters/build-clusters/common/release-controller/rpms-ocp-4.2.yaml
  clusters/build-clusters/common/release-controller/rpms-ocp-4.3.yaml
  clusters/build-clusters/common/release-controller/rpms-ocp-4.4.yaml
  clusters/build-clusters/common/release-controller/rpms-ocp-4.5.yaml
  clusters/build-clusters/common/release-controller/rpms-ocp-4.6.yaml
  clusters/build-clusters/common/release-controller/rpms-ocp-4.7.yaml
  clusters/build-clusters/common/release-controller/rpms-ocp-4.8.yaml
  clusters/build-clusters/common/release-controller/rpms-ocp-4.9.yaml
  hack/generators/release-controllers/content/art_rpm_mirroring_services.py
Labels: lgtm, approved, rehearsals-ack

#60065 OCPQE-27760 Add 4.18 canary upgrade jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly-4.18-upgrade-from-stable-4.17.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__multi-nightly-4.18-upgrade-from-stable-4.17.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#60351 Updating orion to latest version
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__write_jobs_to_gsheet.yaml
Labels: lgtm, approved, rehearsals-ack

#60291 with resource group id to avoid 'No resource group found' error
  ci-operator/step-registry/ibmcloud/provision/vpc/ibmcloud-provision-vpc-commands.sh
Labels: lgtm, approved, rehearsals-ack

#60342 OAPE-78: add techpreview periodics job for cpms-operator
  ci-operator/config/openshift/cluster-control-plane-machine-set-operator/openshift-cluster-control-plane-machine-set-operator-release-4.19__periodics.yaml
  ci-operator/jobs/openshift/cluster-control-plane-machine-set-operator/openshift-cluster-control-plane-machine-set-operator-release-4.19-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#59392 [IBMCloud] CORS-3364 e2e testing automation: Replace Terraform with CAPI Provider for IBM Cloud
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__amd64-nightly.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installation-nightly-4.19.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.19.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
  ci-operator/step-registry/cucushift/installer/check/ibmcloud/private/cucushift-installer-check-ibmcloud-private-commands.sh
  ci-operator/step-registry/ipi/install/install/ipi-install-install-commands.sh
Labels: lgtm, approved, rehearsals-ack

#60370 Increase the timeout for hypershift-mce-agent-destroy.
  ci-operator/step-registry/hypershift/mce/agent/destroy/hypershift-mce-agent-destroy-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#60367 Adjust mce-install OVERRIDE_HO_IMAGE's documentation
  ci-operator/step-registry/hypershift/mce/install/hypershift-mce-install-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#60373 [PERFSCALE-3630] New metal-perfscale-telco config
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__metal-telco-x86.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#60329 Update odf-operator CI golang & openshift versions
  ci-operator/config/red-hat-storage/odf-operator/red-hat-storage-odf-operator-main.yaml
Labels: lgtm, approved, rehearsals-ack

#60134 OCPQE-27908: refactor step registry structure and add unmanged tls cert step
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__ocp-417-quay.yaml
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__quay-operator-test.yaml
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__quay-upgrade.yaml
  ci-operator/jobs/quay/quay-tests/quay-quay-tests-master-periodics.yaml
  ci-operator/step-registry/quay-tests/deploy-quay-operator/OWNERS
  ci-operator/step-registry/quay-tests/deploy-quay-operator/quay-tests-deploy-quay-operator-commands.sh
  ci-operator/step-registry/quay-tests/deploy-quay-operator/quay-tests-deploy-quay-operator-ref.metadata.json
  ci-operator/step-registry/quay-tests/deploy-quay-operator/quay-tests-deploy-quay-operator-ref.yaml
  ci-operator/step-registry/quay-tests/deploy-registry-unmanged-tls/OWNERS
  ci-operator/step-registry/quay-tests/deploy-registry-unmanged-tls/quay-tests-deploy-registry-unmanged-tls-commands.sh
  ci-operator/step-registry/quay-tests/deploy-registry-unmanged-tls/quay-tests-deploy-registry-unmanged-tls-ref.metadata.json
  ci-operator/step-registry/quay-tests/deploy-registry-unmanged-tls/quay-tests-deploy-registry-unmanged-tls-ref.yaml
  ci-operator/step-registry/quay-tests/provisioning/OWNERS
  ci-operator/step-registry/quay-tests/provisioning/storage/OWNERS
  ci-operator/step-registry/quay-tests/provisioning/storage/odf/OWNERS
  ci-operator/step-registry/quay-tests/provisioning/storage/odf/quay-tests-provisioning-storage-odf-commands.sh
  ci-operator/step-registry/quay-tests/provisioning/storage/odf/quay-tests-provisioning-storage-odf-ref.metadata.json
  ci-operator/step-registry/quay-tests/provisioning/storage/odf/quay-tests-provisioning-storage-odf-ref.yaml
  ci-operator/step-registry/quay-tests/provisioning/tls/OWNERS
  ci-operator/step-registry/quay-tests/provisioning/tls/quay-tests-provisioning-tls-commands.sh
  ci-operator/step-registry/quay-tests/provisioning/tls/quay-tests-provisioning-tls-ref.metadata.json
  ci-operator/step-registry/quay-tests/provisioning/tls/quay-tests-provisioning-tls-ref.yaml
  ci-operator/step-registry/quay-tests/quay-operator-test/quay-tests-quay-operator-test-commands.sh
  ci-operator/step-registry/quay-tests/quay-operator-test/quay-tests-quay-operator-test-ref.yaml
  ci-operator/step-registry/quay-tests/quay-upgrade/quay-tests-quay-upgrade-commands.sh
  ci-operator/step-registry/quay-tests/quay-upgrade/quay-tests-quay-upgrade-ref.yaml
Labels: lgtm, approved, tide/merge-method-squash, rehearsals-ack, jira/valid-reference

#59426 Syn flood
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__4.18-nightly.yaml
  ci-operator/jobs/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main-presubmits.yaml
  ci-operator/step-registry/redhat-chaos/krkn-hub-prometheus-tests/redhat-chaos-krkn-hub-prometheus-tests-chain.yaml
  ci-operator/step-registry/redhat-chaos/syn-flood/OWNERS
  ci-operator/step-registry/redhat-chaos/syn-flood/prometheus-disruption/OWNERS
  ci-operator/step-registry/redhat-chaos/syn-flood/prometheus-disruption/redhat-chaos-syn-flood-prometheus-disruption-commands.sh
  ci-operator/step-registry/redhat-chaos/syn-flood/prometheus-disruption/redhat-chaos-syn-flood-prometheus-disruption-ref.metadata.json
  ci-operator/step-registry/redhat-chaos/syn-flood/prometheus-disruption/redhat-chaos-syn-flood-prometheus-disruption-ref.yaml
  ci-operator/step-registry/redhat-chaos/syn-flood/redhat-chaos-syn-flood-chain.metadata.json
  ci-operator/step-registry/redhat-chaos/syn-flood/redhat-chaos-syn-flood-chain.yaml
  ci-operator/step-registry/redhat-chaos/syn-flood/redhat-chaos-syn-flood-commands.sh
  ci-operator/step-registry/redhat-chaos/syn-flood/redhat-chaos-syn-flood-ref.metadata.json
  ci-operator/step-registry/redhat-chaos/syn-flood/redhat-chaos-syn-flood-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#60369 Adding slack notification when job is aborted
  ci-operator/config/rh-ecosystem-edge/nvidia-ci/.config.prowgen
  ci-operator/jobs/rh-ecosystem-edge/nvidia-ci/rh-ecosystem-edge-nvidia-ci-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#58414 Quarkus z-stream expansion for ocp 4.17
  ci-operator/config/quarkus-qe/quarkus-openshift-interop/quarkus-qe-quarkus-openshift-interop-main__quarkus-ocp4.17-lp-interop.yaml
  ci-operator/jobs/quarkus-qe/quarkus-openshift-interop/quarkus-qe-quarkus-openshift-interop-main-periodics.yaml
  ci-operator/jobs/quarkus-qe/quarkus-openshift-interop/quarkus-qe-quarkus-openshift-interop-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#59941 GitOps | Update branch for interop tests v1.15
  ci-operator/config/redhat-developer/gitops-operator/redhat-developer-gitops-operator-v1.14__gitops-ocp4.14-lp-interop.yaml
  ci-operator/config/redhat-developer/gitops-operator/redhat-developer-gitops-operator-v1.14__gitops-ocp4.15-lp-interop.yaml
  ci-operator/config/redhat-developer/gitops-operator/redhat-developer-gitops-operator-v1.14__gitops-ocp4.16-lp-interop.yaml
  ci-operator/config/redhat-developer/gitops-operator/redhat-developer-gitops-operator-v1.14__gitops-ocp4.17-lp-interop.yaml
  ci-operator/config/redhat-developer/gitops-operator/redhat-developer-gitops-operator-v1.15__gitops-ocp4.18-lp-interop.yaml
  ci-operator/jobs/redhat-developer/gitops-operator/redhat-developer-gitops-operator-v1.14-periodics.yaml
  ci-operator/jobs/redhat-developer/gitops-operator/redhat-developer-gitops-operator-v1.14-presubmits.yaml
  ci-operator/jobs/redhat-developer/gitops-operator/redhat-developer-gitops-operator-v1.15-periodics.yaml
  ci-operator/jobs/redhat-developer/gitops-operator/redhat-developer-gitops-operator-v1.15-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#59836 ovn-k, virt: add daily periodic jobs for GA feature
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.19__periodics.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.19-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#60394 Enable e2e-aks as required on OCP 4.18
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.18.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.18-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#60347 remove unsupported param for aro hcp deprovision
  ci-operator/step-registry/cucushift/installer/rehearse/azure/aks/hypershift/ephemeral-creds/deprovision/cucushift-installer-rehearse-azure-aks-hypershift-ephemeral-creds-deprovision-chain.yaml
  ci-operator/step-registry/hypershift/azure/destroy/hypershift-azure-destroy-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#60364 update olmv0 capability checking
  ci-operator/step-registry/enable-qe-catalogsource/disconnected/enable-qe-catalogsource-disconnected-commands.sh
  ci-operator/step-registry/enable-qe-catalogsource/enable-qe-catalogsource-commands.sh
Labels: lgtm, approved, rehearsals-ack

#60404 Bump up cli from 4.14 to 4.17 used in build farm upgrade
  ci-operator/jobs/infra-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#60398 OCPQE-27966: Refactor step registry code structure
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__ocp-417-quay.yaml
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__quay-operator-test.yaml
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__quay-upgrade.yaml
  ci-operator/step-registry/quay-tests/cucushift-installer-rehearse-aws-ipi-operator/quay-tests-cucushift-installer-rehearse-aws-ipi-operator-workflow.yaml
  ci-operator/step-registry/quay-tests/deprovisioning-aws-unmanaged-component/quay-tests-deprovisioning-aws-unmanaged-component-ref.metadata.json
  ci-operator/step-registry/quay-tests/provisioning-aws-unmanaged-component/quay-tests-provisioning-aws-unmanaged-component-ref.metadata.json
  ci-operator/step-registry/quay-tests/quay-operator-test/quay-tests-quay-operator-test-ref.metadata.json
  ci-operator/step-registry/quay-tests/quay-upgrade/quay-tests-quay-upgrade-ref.metadata.json
  ci-operator/step-registry/quay-tests/quay/OWNERS
  ci-operator/step-registry/quay-tests/quay/deploy-operator/OWNERS
  ci-operator/step-registry/quay-tests/quay/deploy-operator/quay-tests-quay-deploy-operator-commands.sh
  ci-operator/step-registry/quay-tests/quay/deploy-operator/quay-tests-quay-deploy-operator-ref.metadata.json
  ci-operator/step-registry/quay-tests/quay/deploy-operator/quay-tests-quay-deploy-operator-ref.yaml
  ci-operator/step-registry/quay-tests/quay/deploy-registry-unmanged-tls/OWNERS
  ci-operator/step-registry/quay-tests/quay/deploy-registry-unmanged-tls/quay-tests-quay-deploy-registry-unmanged-tls-commands.sh
  ci-operator/step-registry/quay-tests/quay/deploy-registry-unmanged-tls/quay-tests-quay-deploy-registry-unmanged-tls-ref.metadata.json
  ci-operator/step-registry/quay-tests/quay/deploy-registry-unmanged-tls/quay-tests-quay-deploy-registry-unmanged-tls-ref.yaml
  ci-operator/step-registry/quay-tests/resource/OWNERS
  ci-operator/step-registry/quay-tests/resource/deprovisioning/OWNERS
  ci-operator/step-registry/quay-tests/resource/deprovisioning/aws-unmanaged-component/OWNERS
  ci-operator/step-registry/quay-tests/resource/deprovisioning/aws-unmanaged-component/quay-tests-resource-deprovisioning-aws-unmanaged-component-commands.sh
  ci-operator/step-registry/quay-tests/resource/deprovisioning/aws-unmanaged-component/quay-tests-resource-deprovisioning-aws-unmanaged-component-ref.metadata.json
  ci-operator/step-registry/quay-tests/resource/deprovisioning/aws-unmanaged-component/quay-tests-resource-deprovisioning-aws-unmanaged-component-ref.yaml
  ci-operator/step-registry/quay-tests/resource/provisioning/OWNERS
  ci-operator/step-registry/quay-tests/resource/provisioning/aws-unmanaged-component/OWNERS
  ci-operator/step-registry/quay-tests/resource/provisioning/aws-unmanaged-component/quay-tests-resource-provisioning-aws-unmanaged-component-commands.sh
  ci-operator/step-registry/quay-tests/resource/provisioning/aws-unmanaged-component/quay-tests-resource-provisioning-aws-unmanaged-component-ref.metadata.json
  ci-operator/step-registry/quay-tests/resource/provisioning/aws-unmanaged-component/quay-tests-resource-provisioning-aws-unmanaged-component-ref.yaml
  ci-operator/step-registry/quay-tests/resource/provisioning/storage/OWNERS
  ci-operator/step-registry/quay-tests/resource/provisioning/storage/odf/OWNERS
  ci-operator/step-registry/quay-tests/resource/provisioning/storage/odf/quay-tests-resource-provisioning-storage-odf-commands.sh
  ci-operator/step-registry/quay-tests/resource/provisioning/storage/odf/quay-tests-resource-provisioning-storage-odf-ref.metadata.json
  ci-operator/step-registry/quay-tests/resource/provisioning/storage/odf/quay-tests-resource-provisioning-storage-odf-ref.yaml
  ci-operator/step-registry/quay-tests/resource/provisioning/tls/OWNERS
  ci-operator/step-registry/quay-tests/resource/provisioning/tls/quay-tests-resource-provisioning-tls-commands.sh
  ci-operator/step-registry/quay-tests/resource/provisioning/tls/quay-tests-resource-provisioning-tls-ref.metadata.json
  ci-operator/step-registry/quay-tests/resource/provisioning/tls/quay-tests-resource-provisioning-tls-ref.yaml
  ci-operator/step-registry/quay-tests/test/OWNERS
  ci-operator/step-registry/quay-tests/test/quay-operator/OWNERS
  ci-operator/step-registry/quay-tests/test/quay-operator/quay-tests-test-quay-operator-commands.sh
  ci-operator/step-registry/quay-tests/test/quay-operator/quay-tests-test-quay-operator-ref.metadata.json
  ci-operator/step-registry/quay-tests/test/quay-operator/quay-tests-test-quay-operator-ref.yaml
  ci-operator/step-registry/quay-tests/test/quay-upgrade/OWNERS
  ci-operator/step-registry/quay-tests/test/quay-upgrade/quay-tests-test-quay-upgrade-commands.sh
  ci-operator/step-registry/quay-tests/test/quay-upgrade/quay-tests-test-quay-upgrade-ref.metadata.json
  ci-operator/step-registry/quay-tests/test/quay-upgrade/quay-tests-test-quay-upgrade-ref.yaml
Labels: lgtm, approved, tide/merge-method-squash, rehearsals-ack, jira/valid-reference

#60115 Use Azure for hypershift-kubevirt for testing conformance/minimal
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.18__periodics.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.18-periodics.yaml
  ci-operator/step-registry/hypershift/kubevirt/azure/conformance/hypershift-kubevirt-azure-conformance-workflow.yaml
  ci-operator/step-registry/hypershift/kubevirt/install/hypershift-kubevirt-install-commands.sh
Labels: lgtm, approved, rehearsals-ack

#60410 Remove duplicate day2 jobs from OCP 4.18
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__multi-nightly-4.18-upgrade-from-stable-4.17.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__multi-nightly-4.18-upgrade-from-stable-4.18.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__multi-stable-4.18-upgrade-from-stable-4.17.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#60413 fix bug in #60291
  ci-operator/step-registry/ibmcloud/provision/vpc/ibmcloud-provision-vpc-commands.sh
Labels: lgtm, approved, rehearsals-ack

#60418 OpenShift Builds prow jobs for 1.3 version
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-build-docs-1.3.yaml
  ci-operator/jobs/openshift/openshift-docs/openshift-openshift-docs-build-docs-1.3-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#59866 scale up after install for 252 nodes aws ipsec jobs
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.18-nightly-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.19-nightly-x86.yaml
Labels: lgtm, approved, rehearsals-ack

#60055 Enable OSSM telemetry api tests
  ci-operator/config/openshift-service-mesh/istio/openshift-service-mesh-istio-master.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#60426 Add devfile team to QCI image pullers
  clusters/app.ci/assets/admin_qci-image-puller_rbac.yaml
Labels: lgtm, approved, rehearsals-ack

#60334 Enable OSSM pilot tests
  ci-operator/config/openshift-service-mesh/istio/openshift-service-mesh-istio-master.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#60400 update fast foward task for all ALC repos
  ci-operator/config/stolostron/applifecycle-backend-e2e/stolostron-applifecycle-backend-e2e-main.yaml
  ci-operator/config/stolostron/cluster-permission/stolostron-cluster-permission-main.yaml
  ci-operator/config/stolostron/multicloud-integrations/stolostron-multicloud-integrations-main.yaml
  ci-operator/config/stolostron/multicloud-operators-application/stolostron-multicloud-operators-application-main.yaml
  ci-operator/config/stolostron/multicloud-operators-channel/stolostron-multicloud-operators-channel-main.yaml
  ci-operator/config/stolostron/multicloud-operators-subscription/stolostron-multicloud-operators-subscription-main.yaml
  ci-operator/jobs/stolostron/applifecycle-backend-e2e/stolostron-applifecycle-backend-e2e-main-postsubmits.yaml
  ci-operator/jobs/stolostron/cluster-permission/stolostron-cluster-permission-main-postsubmits.yaml
  ci-operator/jobs/stolostron/multicloud-integrations/stolostron-multicloud-integrations-main-postsubmits.yaml
  ci-operator/jobs/stolostron/multicloud-operators-application/stolostron-multicloud-operators-application-main-postsubmits.yaml
  ci-operator/jobs/stolostron/multicloud-operators-channel/stolostron-multicloud-operators-channel-main-postsubmits.yaml
  ci-operator/jobs/stolostron/multicloud-operators-subscription/stolostron-multicloud-operators-subscription-main-postsubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#60424 HOSTEDCP-2041: change hypershift-aks-e2e as required presub for cluster-image-registry-operator.
  ci-operator/config/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-master.yaml
  ci-operator/config/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-release-4.18.yaml
  ci-operator/config/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-release-4.19.yaml
  ci-operator/jobs/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-release-4.18-presubmits.yaml
  ci-operator/jobs/openshift/cluster-image-registry-operator/openshift-cluster-image-registry-operator-release-4.19-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#59104 NO-JIRA: add 4.17 GCP Filestore WIF tests
  ci-operator/config/openshift/gcp-filestore-csi-driver-operator/openshift-gcp-filestore-csi-driver-operator-release-4.17.yaml
  ci-operator/jobs/openshift/gcp-filestore-csi-driver-operator/openshift-gcp-filestore-csi-driver-operator-release-4.17-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#60311 StackRox: Add new ibmcloudz image tag
  core-services/image-mirroring/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#60430 Skip istioctl unsupported commands tests for release-1.24
  ci-operator/config/openshift-service-mesh/istio/openshift-service-mesh-istio-release-1.24.yaml
Labels: lgtm, approved, rehearsals-ack

#60388 Adding aro 4.18 tests
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__4.17-nightly.yaml
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__4.18-nightly.yaml
  ci-operator/jobs/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#60407 Build Component repo's labling permissions update for new joiners
  core-services/prow/02_config/openshift/builder/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-openshift-controller-manager-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/openshift-apiserver/_pluginconfig.yaml
  core-services/prow/02_config/openshift/openshift-controller-manager/_pluginconfig.yaml
  core-services/prow/02_config/openshift/origin/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#60365 Netpol-v2: Weekly job
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.18-nightly-x86.yaml
  ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__aws-4.19-nightly-x86.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-periodics.yaml
  ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-presubmits.yaml
  ci-operator/step-registry/openshift-qe/netpol-v2/openshift-qe-netpol-v2-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#60392 OCPBUGS-48097: rename 'master' to 'main' for cluster-storage-operator
  ci-operator/config/openshift-priv/cluster-storage-operator/openshift-priv-cluster-storage-operator-main.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-main.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-main__okd-scos.yaml
  ci-operator/jobs/openshift-priv/cluster-storage-operator/openshift-priv-cluster-storage-operator-main-postsubmits.yaml
  ci-operator/jobs/openshift-priv/cluster-storage-operator/openshift-priv-cluster-storage-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-main-periodics.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-main-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-main-presubmits.yaml
Labels: lgtm, approved, jira/valid-bug, rehearsals-ack, jira/valid-reference

#60435 cnf-tests: use rhel9 as a base image for cnf-tests
  ci-operator/config/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-master.yaml
Labels: lgtm, approved, rehearsals-ack

#60450 Fix the quote on the skip tests list
  ci-operator/config/openshift-service-mesh/istio/openshift-service-mesh-istio-release-1.24.yaml
Labels: lgtm, approved, rehearsals-ack

#60448 Bump go versions for CVE fix
  ci-operator/config/stolostron/cluster-curator-controller/stolostron-cluster-curator-controller-backplane-2.4.yaml
  ci-operator/config/stolostron/cluster-image-set-controller/stolostron-cluster-image-set-controller-backplane-2.4.yaml
  ci-operator/config/stolostron/cluster-image-set-controller/stolostron-cluster-image-set-controller-backplane-2.5.yaml
  ci-operator/config/stolostron/cluster-image-set-controller/stolostron-cluster-image-set-controller-backplane-2.6.yaml
  ci-operator/config/stolostron/cluster-image-set-controller/stolostron-cluster-image-set-controller-backplane-2.7.yaml
  ci-operator/config/stolostron/cluster-image-set-controller/stolostron-cluster-image-set-controller-backplane-2.8.yaml
  ci-operator/config/stolostron/cluster-image-set-controller/stolostron-cluster-image-set-controller-main.yaml
  ci-operator/config/stolostron/provider-credential-controller/stolostron-provider-credential-controller-backplane-2.4.yaml
  ci-operator/config/stolostron/provider-credential-controller/stolostron-provider-credential-controller-backplane-2.5.yaml
  ci-operator/config/stolostron/provider-credential-controller/stolostron-provider-credential-controller-backplane-2.6.yaml
  ci-operator/config/stolostron/provider-credential-controller/stolostron-provider-credential-controller-backplane-2.7.yaml
  ci-operator/config/stolostron/provider-credential-controller/stolostron-provider-credential-controller-backplane-2.8.yaml
  ci-operator/config/stolostron/provider-credential-controller/stolostron-provider-credential-controller-main.yaml
Labels: lgtm, approved, rehearsals-ack

#56006 rename scanner-v4-tests to scanner-v4-install-tests
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-12.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-17.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-dev-preview.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-next-candidate.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-stable-scanner-v4-install.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-x.y.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-x.y__ocp-4-12.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-x.y__ocp-4-17.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-postsubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-presubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-x.y-postsubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-x.y-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#60289 Filter out storage cucushift cases in vSphere multi-vcenter profile
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__amd64-nightly.yaml
  ci-operator/step-registry/cucushift/e2e/cucushift-e2e-commands.sh
Labels: lgtm, approved, rehearsals-ack

#60436 Adjust the retry interval fo mce-install
  ci-operator/step-registry/hypershift/mce/install/hypershift-mce-install-commands.sh
  ci-operator/step-registry/hypershift/mce/install/hypershift-mce-install-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#60411 Update OMR 2.0.5 testing image
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__omr-ocp412-unreleased.yaml
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__omr-ocp413-unreleased.yaml
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__omr-ocp414-unreleased.yaml
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__omr-ocp415-unreleased.yaml
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__omr-ocp416-unreleased.yaml
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__omr-ocp417-unreleased.yaml
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__omr-ocp418-unreleased.yaml
Labels: lgtm, approved, rehearsals-ack

#60460 Add dependencies for cluster-proxy-addon image in test configurations
  ci-operator/config/stolostron/cluster-proxy-addon/stolostron-cluster-proxy-addon-backplane-2.4.yaml
  ci-operator/config/stolostron/cluster-proxy-addon/stolostron-cluster-proxy-addon-backplane-2.5.yaml
  ci-operator/config/stolostron/cluster-proxy-addon/stolostron-cluster-proxy-addon-backplane-2.6.yaml
  ci-operator/config/stolostron/cluster-proxy-addon/stolostron-cluster-proxy-addon-backplane-2.7.yaml
  ci-operator/config/stolostron/cluster-proxy-addon/stolostron-cluster-proxy-addon-backplane-2.8.yaml
Labels: lgtm, approved, rehearsals-ack

#60358 bump minor upgrade jobs for ovnk
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master__4.19-upgrade-from-stable-4.18.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.18__4.18-upgrade-from-stable-4.17.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master-presubmits.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.18-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#60432 Define INTERNAL_SSH_OPTS before we use it
  ci-operator/step-registry/baremetalds/devscripts/gather/baremetalds-devscripts-gather-commands.sh
Labels: lgtm, approved, rehearsals-ack

#60154 Remove temp permission `ec2:DescribeInstanceTypeOfferings`
  ci-operator/step-registry/ipi/conf/aws/user-min-permissions/ipi-conf-aws-user-min-permissions-commands.sh
Labels: lgtm, approved, rehearsals-ack

#60429 Move ZTP job to eco-ci-cd repo
  ci-operator/jobs/openshift-kni/eco-ci-cd-public/OWNERS
Labels: lgtm, approved, rehearsals-ack

#60472 Revert "`pj-rehearse`: remove kubeconfigs for build-farm clusters from secret"
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#60054 adding prow jobs for the ove docs
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-ove-docs-main.yaml
  ci-operator/jobs/openshift/openshift-docs/openshift-openshift-docs-ove-docs-main-presubmits.yaml
  ci-operator/step-registry/openshift-docs/portal/openshift-docs-portal-commands.sh
Labels: lgtm, approved, rehearsals-ack

#60473 enable backports for z-stream ODF
  core-services/jira-lifecycle-plugin/config.yaml
Labels: lgtm, approved, rehearsals-ack

#59183 co 4.18 support
  ci-operator/config/ComplianceAsCode/content/ComplianceAsCode-content-master__4.18.yaml
  ci-operator/jobs/ComplianceAsCode/content/ComplianceAsCode-content-master-periodics.yaml
  ci-operator/jobs/ComplianceAsCode/content/ComplianceAsCode-content-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#60471 Update users for restricted labels in baremetal repos
  core-services/prow/02_config/openshift/cluster-api-provider-baremetal/_pluginconfig.yaml
  core-services/prow/02_config/openshift/cluster-api-provider-metal3/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#60476 OCPBUGS-48220: rename 'master' to 'main' for ib-sriov-cni
  ci-operator/config/openshift-priv/ib-sriov-cni/openshift-priv-ib-sriov-cni-main.yaml
  ci-operator/config/openshift/ib-sriov-cni/openshift-ib-sriov-cni-main.yaml
  ci-operator/jobs/openshift-priv/ib-sriov-cni/openshift-priv-ib-sriov-cni-main-postsubmits.yaml
  ci-operator/jobs/openshift-priv/ib-sriov-cni/openshift-priv-ib-sriov-cni-main-presubmits.yaml
  ci-operator/jobs/openshift/ib-sriov-cni/openshift-ib-sriov-cni-main-postsubmits.yaml
  ci-operator/jobs/openshift/ib-sriov-cni/openshift-ib-sriov-cni-main-presubmits.yaml
Labels: lgtm, approved, jira/valid-bug, rehearsals-ack, jira/valid-reference, acknowledge-critical-fixes-only

#60477 OCPBUGS-48221: rename 'master' to 'main' for sriov-network-metrics-exporter
  ci-operator/config/openshift-priv/sriov-network-metrics-exporter/openshift-priv-sriov-network-metrics-exporter-main.yaml
  ci-operator/config/openshift/sriov-network-metrics-exporter/openshift-sriov-network-metrics-exporter-main.yaml
  ci-operator/jobs/openshift-priv/sriov-network-metrics-exporter/openshift-priv-sriov-network-metrics-exporter-main-postsubmits.yaml
  ci-operator/jobs/openshift-priv/sriov-network-metrics-exporter/openshift-priv-sriov-network-metrics-exporter-main-presubmits.yaml
  ci-operator/jobs/openshift/sriov-network-metrics-exporter/openshift-sriov-network-metrics-exporter-main-postsubmits.yaml
  ci-operator/jobs/openshift/sriov-network-metrics-exporter/openshift-sriov-network-metrics-exporter-main-presubmits.yaml
Labels: lgtm, approved, jira/valid-bug, rehearsals-ack, jira/valid-reference

#60478 OCPBUGS-48222: rename 'master' to 'main' for rdma-cni
  ci-operator/config/openshift-priv/rdma-cni/openshift-priv-rdma-cni-main.yaml
  ci-operator/config/openshift/rdma-cni/openshift-rdma-cni-main.yaml
  ci-operator/jobs/openshift-priv/rdma-cni/openshift-priv-rdma-cni-main-postsubmits.yaml
  ci-operator/jobs/openshift-priv/rdma-cni/openshift-priv-rdma-cni-main-presubmits.yaml
  ci-operator/jobs/openshift/rdma-cni/openshift-rdma-cni-main-postsubmits.yaml
  ci-operator/jobs/openshift/rdma-cni/openshift-rdma-cni-main-presubmits.yaml
Labels: lgtm, approved, jira/valid-bug, rehearsals-ack, jira/valid-reference

#60361 MULTIARCH-5196: x-px 4.19 is not using the correct installer
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.18.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.19.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#60454 NO-ISSUE: Consolidate catalogd and operator-controler upstream-e2e
  ci-operator/config/openshift/operator-framework-catalogd/openshift-operator-framework-catalogd-main.yaml
  ci-operator/config/openshift/operator-framework-catalogd/openshift-operator-framework-catalogd-release-4.19.yaml
  ci-operator/config/openshift/operator-framework-catalogd/openshift-operator-framework-catalogd-release-4.20.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#60479 OCPBUGS-48223: rename 'master' to 'main' for sriov-cni
  ci-operator/config/openshift-priv/sriov-cni/openshift-priv-sriov-cni-main.yaml
  ci-operator/config/openshift/sriov-cni/openshift-sriov-cni-main.yaml
  ci-operator/jobs/openshift-priv/sriov-cni/openshift-priv-sriov-cni-main-postsubmits.yaml
  ci-operator/jobs/openshift-priv/sriov-cni/openshift-priv-sriov-cni-main-presubmits.yaml
  ci-operator/jobs/openshift/sriov-cni/openshift-sriov-cni-main-postsubmits.yaml
  ci-operator/jobs/openshift/sriov-cni/openshift-sriov-cni-main-presubmits.yaml
Labels: lgtm, approved, jira/valid-bug, rehearsals-ack, jira/valid-reference

#60481 OCPBUGS-48225: rename 'master' to 'main' for sriov-network-device-plugin
  ci-operator/config/openshift-priv/sriov-network-device-plugin/openshift-priv-sriov-network-device-plugin-main.yaml
  ci-operator/config/openshift/sriov-network-device-plugin/openshift-sriov-network-device-plugin-main.yaml
  ci-operator/jobs/openshift-priv/sriov-network-device-plugin/openshift-priv-sriov-network-device-plugin-main-postsubmits.yaml
  ci-operator/jobs/openshift-priv/sriov-network-device-plugin/openshift-priv-sriov-network-device-plugin-main-presubmits.yaml
  ci-operator/jobs/openshift/sriov-network-device-plugin/openshift-sriov-network-device-plugin-main-postsubmits.yaml
  ci-operator/jobs/openshift/sriov-network-device-plugin/openshift-sriov-network-device-plugin-main-presubmits.yaml
Labels: lgtm, approved, jira/valid-bug, rehearsals-ack, jira/valid-reference

#60487 Fix timeout bug in PROW scripts
  ci-operator/step-registry/dpu-operator/e2e-tests-workflow/tests/dpu-operator-e2e-tests-workflow-tests-commands.sh
Labels: lgtm, approved, rehearsals-ack

#58916 HOSTEDCP-2042: add hypershift-aks-e2e as required presub for cluster-ingress-operator
  ci-operator/config/openshift/cluster-ingress-operator/openshift-cluster-ingress-operator-master.yaml
  ci-operator/config/openshift/cluster-ingress-operator/openshift-cluster-ingress-operator-release-4.18.yaml
  ci-operator/config/openshift/cluster-ingress-operator/openshift-cluster-ingress-operator-release-4.19.yaml
  ci-operator/jobs/openshift/cluster-ingress-operator/openshift-cluster-ingress-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-ingress-operator/openshift-cluster-ingress-operator-release-4.18-presubmits.yaml
  ci-operator/jobs/openshift/cluster-ingress-operator/openshift-cluster-ingress-operator-release-4.19-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#60441 chore(devfile): Devfile Registry OpenShift 4.16 testing
  ci-operator/config/devfile/registry/devfile-registry-main__v4.16.yaml
  ci-operator/jobs/devfile/registry/devfile-registry-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#60490 hosted-mgmt: use `4-stable` version_stream
  clusters/hosted-mgmt/hive/pools/ocp-release-4.18.0-ec.4-x86-64-for-4.18.0-0-to-4.19.0-0_clusterimageset.yaml
  clusters/hosted-mgmt/hive/pools/openshift-observability/obs-logging-ocp-4-18-amd64-aws-us-east-1_clusterpool.yaml
  clusters/hosted-mgmt/hive/pools/openstack-k8s-operators/openstack-k8s-operators-4-18-vexxhost-hybrid_clusterpool.yaml
  clusters/hosted-mgmt/hive/pools/rh-openshift-ecosystem/rhoe-ocp-4-18-amd64-aws-us-east-1_clusterpool.yaml
  clusters/hosted-mgmt/hive/pools/rh-openshift-ecosystem/rhoe-ocp-4-18-amd64-aws-us-east-2_clusterpool.yaml
Labels: lgtm, approved, rehearsals-ack

#60491 disable tcpdump collection for UPI jobs
  ci-operator/step-registry/upi/vsphere/pre/upi-vsphere-pre-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#60475 telco5g: Add option for additional BM in HCP jobs
  ci-operator/step-registry/telco5g/hcp-cluster-setup/telco5g-hcp-cluster-setup-commands.sh
  ci-operator/step-registry/telco5g/hcp-release-cluster/telco5g-hcp-release-cluster-commands.sh
Labels: lgtm, approved, rehearsals-ack

#60438 SPLAT-1666: aws/edge - add sample app deployment
  ci-operator/step-registry/edge-nodes/OWNERS
  ci-operator/step-registry/edge-nodes/deploy-app/OWNERS
  ci-operator/step-registry/edge-nodes/deploy-app/edge-nodes-deploy-app-commands.sh
  ci-operator/step-registry/edge-nodes/deploy-app/edge-nodes-deploy-app-ref.metadata.json
  ci-operator/step-registry/edge-nodes/deploy-app/edge-nodes-deploy-app-ref.yaml
  ci-operator/step-registry/openshift/e2e/aws/edge-zones/openshift-e2e-aws-edge-zones-workflow.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#60485 Add release files for IBIO backplane-2.8
  ci-operator/config/openshift/image-based-install-operator/openshift-image-based-install-operator-backplane-2.8.yaml
  ci-operator/jobs/openshift/image-based-install-operator/openshift-image-based-install-operator-backplane-2.8-periodics.yaml
  ci-operator/jobs/openshift/image-based-install-operator/openshift-image-based-install-operator-backplane-2.8-postsubmits.yaml
  ci-operator/jobs/openshift/image-based-install-operator/openshift-image-based-install-operator-backplane-2.8-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#60500 Update Quay 3.12.7 images for SDL testing
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__quay-sdl.yaml
Labels: lgtm, approved, rehearsals-ack

#60499 OCPQE-28015 - Add env var CUSTOM_OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE to easily run pre-merge testing for specific jobs
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-master__installer-rehearse-4.18.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-master-periodics.yaml
  ci-operator/step-registry/ipi/install/install/aws/ipi-install-install-aws-commands.sh
  ci-operator/step-registry/ipi/install/install/aws/ipi-install-install-aws-ref.yaml
  ci-operator/step-registry/ipi/install/install/in-bastion/ipi-install-install-in-bastion-commands.sh
  ci-operator/step-registry/ipi/install/install/in-bastion/ipi-install-install-in-bastion-ref.yaml
  ci-operator/step-registry/ipi/install/install/ipi-install-install-commands.sh
  ci-operator/step-registry/ipi/install/install/ipi-install-install-ref.yaml
  ci-operator/step-registry/mirror-images/by-oc-adm-in-bastion/mirror-images-by-oc-adm-in-bastion-commands.sh
  ci-operator/step-registry/mirror-images/by-oc-adm-in-bastion/mirror-images-by-oc-adm-in-bastion-ref.yaml
  ci-operator/step-registry/mirror-images/by-oc-adm/mirror-images-by-oc-adm-commands.sh
  ci-operator/step-registry/mirror-images/by-oc-adm/mirror-images-by-oc-adm-ref.yaml
  ci-operator/step-registry/mirror-images/by-oc-mirror/mirror-images-by-oc-mirror-commands.sh
  ci-operator/step-registry/mirror-images/by-oc-mirror/mirror-images-by-oc-mirror-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#60508 opendatahub/vllm: increase timeout for all builds
  ci-operator/config/opendatahub-io/vllm/opendatahub-io-vllm-ibm-dev.yaml
  ci-operator/config/opendatahub-io/vllm/opendatahub-io-vllm-main.yaml
  ci-operator/config/opendatahub-io/vllm/opendatahub-io-vllm-release.yaml
  ci-operator/jobs/opendatahub-io/vllm/opendatahub-io-vllm-ibm-dev-postsubmits.yaml
  ci-operator/jobs/opendatahub-io/vllm/opendatahub-io-vllm-main-postsubmits.yaml
  ci-operator/jobs/opendatahub-io/vllm/opendatahub-io-vllm-main-presubmits.yaml
  ci-operator/jobs/opendatahub-io/vllm/opendatahub-io-vllm-release-postsubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#60467 Add post check capability into baremetal-lab-ipi workflow
  ci-operator/step-registry/baremetal/lab/ipi/baremetal-lab-ipi-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#60514 [o/cert-manager-operator] update pipeline image tags to use v1.15.4
  ci-operator/config/openshift/cert-manager-operator/openshift-cert-manager-operator-cert-manager-1.15.yaml
  ci-operator/config/openshift/cert-manager-operator/openshift-cert-manager-operator-master.yaml
Labels: lgtm, approved, rehearsals-ack

#59094 Onboard new component data-plane-adoption
  ci-operator/config/openstack-k8s-operators/data-plane-adoption/OWNERS
  ci-operator/config/openstack-k8s-operators/data-plane-adoption/openstack-k8s-operators-data-plane-adoption-main.yaml
  ci-operator/jobs/openstack-k8s-operators/data-plane-adoption/OWNERS
  ci-operator/jobs/openstack-k8s-operators/data-plane-adoption/openstack-k8s-operators-data-plane-adoption-main-presubmits.yaml
  core-services/prow/02_config/openstack-k8s-operators/data-plane-adoption/_pluginconfig.yaml
  core-services/prow/02_config/openstack-k8s-operators/data-plane-adoption/_prowconfig.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#60492 Fix the context and simplified the code
  Makefile
  clusters/psi/Makefile
  clusters/psi/create_kubeconfig.sh
  hack/create_kubeconfig.sh
Labels: lgtm, approved, rehearsals-ack

#60228 create coo install step with conflux and update stage jobs
  ci-operator/config/rhobs/observability-operator/rhobs-observability-operator-main__ocp-4.12-coo.yaml
  ci-operator/config/rhobs/observability-operator/rhobs-observability-operator-main__ocp-4.13-coo.yaml
  ci-operator/config/rhobs/observability-operator/rhobs-observability-operator-main__ocp-4.14-coo.yaml
  ci-operator/config/rhobs/observability-operator/rhobs-observability-operator-main__ocp-4.15-coo.yaml
  ci-operator/config/rhobs/observability-operator/rhobs-observability-operator-main__ocp-4.16-coo.yaml
  ci-operator/config/rhobs/observability-operator/rhobs-observability-operator-main__ocp-4.17-coo.yaml
  ci-operator/step-registry/rhobs/konflux-catalogsource/OWNERS
  ci-operator/step-registry/rhobs/konflux-catalogsource/rhobs-konflux-catalogsource-commands.sh
  ci-operator/step-registry/rhobs/konflux-catalogsource/rhobs-konflux-catalogsource-ref.metadata.json
  ci-operator/step-registry/rhobs/konflux-catalogsource/rhobs-konflux-catalogsource-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#60521 Add build06 cluster-install and refactor some manifests
  clusters/_cluster-install/build02.yaml
  clusters/_cluster-install/build04.yaml
  clusters/_cluster-install/build06.yaml
  clusters/app.ci/dex/manifests.yaml
  clusters/build-clusters/build03/assets/quayio-pull-through-cache-icsp.yaml
  clusters/build-clusters/build04/assets/quayio-pull-through-cache-icsp.yaml
  clusters/build-clusters/build05/assets/quayio-pull-through-cache-icsp.yaml
  clusters/build-clusters/build06/openshift-monitoring/cluster-monitoring-config.yaml
  clusters/build-clusters/build09/assets/quayio-pull-through-cache-icsp.yaml
  clusters/build-clusters/build10/assets/quayio-pull-through-cache-icsp.yaml
Labels: lgtm, approved, rehearsals-ack

#60515 [CVP-4326] Add clusterpool configurations for OCP 4.19
  clusters/hosted-mgmt/hive/pools/cvp/cvp-fips-ocp-4-19-amd64-aws-us-west-2_clusterpool.yaml
  clusters/hosted-mgmt/hive/pools/cvp/cvp-ocp-4-19-amd64-aws-us-west-2_clusterpool.yaml
Labels: lgtm, approved, rehearsals-ack

#60455 PODAUTO-266: Update VPA-operator master config to 4.19
  ci-operator/config/openshift/vertical-pod-autoscaler-operator/openshift-vertical-pod-autoscaler-operator-master.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#60531 hypershift: release branches to use HO and e2 from main
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.18.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.19.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.20.yaml
Labels: lgtm, approved, rehearsals-ack

#60537 Mirror ART pushed base images to QCI
  core-services/image-mirroring/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#60535 ci-operator/jobs/OWNERS: staff engineer approvers
  OWNERS_ALIASES
  ci-operator/jobs/OWNERS
Labels: lgtm, approved, rehearsals-ack

#60538 add kueue operator prow jobs
  ci-operator/config/openshift/kueue-operator/OWNERS
  ci-operator/config/openshift/kueue-operator/openshift-kueue-operator-main.yaml
  ci-operator/jobs/openshift/kueue-operator/OWNERS
  ci-operator/jobs/openshift/kueue-operator/openshift-kueue-operator-main-presubmits.yaml
  core-services/prow/02_config/openshift/kueue-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/kueue-operator/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#60496 Update compliance-operator golang version to 1.23
  ci-operator/config/ComplianceAsCode/compliance-operator/ComplianceAsCode-compliance-operator-master.yaml
Labels: lgtm, approved, rehearsals-ack

#60527 OLMv1 downstreaming: ignore catalogd
  ci-operator/jobs/infra-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#60532 Update `policy-cli` fast-forwarding branch
  ci-operator/config/stolostron/policy-cli/stolostron-policy-cli-main.yaml
Labels: lgtm, approved, rehearsals-ack

#60539 Increase cluster resources for 4.14 & 4.15
  clusters/hosted-mgmt/hive/pools/openshift-observability/install-config-aws-2xlarge-us-east-2_secret.yaml
  clusters/hosted-mgmt/hive/pools/openshift-observability/obs-logging-ocp-4-14-0-amd64-aws-us-east-2_clusterpool.yaml
  clusters/hosted-mgmt/hive/pools/openshift-observability/obs-logging-ocp-4-15-0-amd64-aws-us-east-2_clusterpool.yaml
Labels: lgtm, approved, rehearsals-ack

#60526 NO-JIRA: feat: use different go version
  ci-operator/config/openshift/lvm-operator/openshift-lvm-operator-release-4.12.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#60546 Add self approval for eco-ci-cd
  core-services/prow/02_config/openshift-kni/eco-ci-cd/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack
