Repository openshift/release, pull requests merged in 2025-06, with the labels that each got.

#65076 Add assisted-common-gather in cert-rotation workflows
  ci-operator/step-registry/openshift/e2e/cert-rotation/conf/assisted-on-gcp/openshift-e2e-cert-rotation-conf-assisted-on-gcp-commands.sh
  ci-operator/step-registry/openshift/e2e/cert-rotation/conf/mirror/openshift-e2e-cert-rotation-conf-mirror-commands.sh
  ci-operator/step-registry/openshift/e2e/cert-rotation/shutdown/openshift-e2e-cert-rotation-shutdown-workflow.yaml
  ci-operator/step-registry/openshift/e2e/cert-rotation/shutdown/sno/openshift-e2e-cert-rotation-shutdown-sno-workflow.yaml
  ci-operator/step-registry/openshift/e2e/cert-rotation/suspend/openshift-e2e-cert-rotation-suspend-workflow.yaml
  ci-operator/step-registry/openshift/e2e/cert-rotation/suspend/sno/openshift-e2e-cert-rotation-suspend-sno-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#65552 [perf-scale-openshift-psap/cluster-pool] Set the pool size to 0
  clusters/hosted-mgmt/hive/pools/perf-scale-openshift-psap/cluster-pool-sno-4-16-amd64-aws-us-east-1_cluster-pool.yaml
Labels: lgtm, approved, rehearsals-ack

#65379 Update OTEl jobs to remove Jaeger installation
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__upstream-ocp-4.12-amd64-azure.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__upstream-ocp-4.18-amd64-gcp.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__upstream-ocp-4.19-amd64-aws.yaml
Labels: lgtm, approved, rehearsals-ack

#65493 SPLAT-2247: Enhanced vsphere check vcm command to only check status of leases it creates
  ci-operator/step-registry/ipi/conf/vsphere/check/vcm/ipi-conf-vsphere-check-vcm-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#65530 NO-ISSUE: (cleanup): Remove openshift-operator-framework-operator-controller-main__periodics since the latest release version has the same test
  ci-operator/config/openshift/operator-framework-operator-controller/openshift-operator-framework-operator-controller-main__periodics.yaml
  ci-operator/jobs/openshift/operator-framework-operator-controller/openshift-operator-framework-operator-controller-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#65559 Increase 4.13 fips pool size
  clusters/hosted-mgmt/hive/pools/cvp/cvp-fips-ocp-4-13-amd64-aws-eu-central-1_clusterpool.yaml
Labels: lgtm, approved, rehearsals-ack

#65550 METAL-1348: OFCIR manifests in master cluster
  clusters/master/ofcir-rbac.yaml
  clusters/master/ofcir-system.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#65566 Scale down 4.20 pools
  clusters/hosted-mgmt/hive/pools/cvp/cvp-fips-ocp-4-20-amd64-aws-eu-central-1_clusterpool.yaml
  clusters/hosted-mgmt/hive/pools/cvp/cvp-ocp-4-20-amd64-aws-eu-central-1_clusterpool.yaml
Labels: lgtm, approved, rehearsals-ack

#65524 NETOBSERV-2212: CatalogSrc env var
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__multi-nightly.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#65557 Forced gpc deprovision jobs to amd64 nodes
  ci-operator/jobs/infra-build-farm-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#65576 Block build02
  core-services/sanitize-prow-jobs/_clusters.yaml
Labels: lgtm, approved, rehearsals-ack

#65479 Add new slice for OEX AWS QE
  core-services/ci-secret-bootstrap/_config.yaml
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: lgtm, approved, rehearsals-ack

#65582 konflux: Collect Kueue related resources
  ci-operator/step-registry/redhat-appstudio/gather/redhat-appstudio-gather-commands.sh
Labels: lgtm, approved, rehearsals-ack

#65589 NO-ISSUE: Add assisted temporary images streams to QCI for seamless transition to ocm-2.15
  core-services/image-mirroring/_config.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#65593 add go mod vendor before make e2e-test
  ci-operator/step-registry/network-flow-matrix/tests/network-flow-matrix-tests-commands.sh
Labels: lgtm, approved, rehearsals-ack

#58792 stackrox: test scanner-v4 on perf&scale with acs nightly helm installs
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies__ocp-4-18.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-nightlies-postsubmits.yaml
  ci-operator/step-registry/stackrox/install-helm/stackrox-install-helm-commands.sh
  ci-operator/step-registry/stackrox/install-helm/stackrox-install-helm-ref.yaml
  ci-operator/step-registry/stackrox/perfscale/OWNERS
  ci-operator/step-registry/stackrox/perfscale/stackrox-perfscale-chain.metadata.json
  ci-operator/step-registry/stackrox/perfscale/stackrox-perfscale-chain.yaml
  ci-operator/step-registry/stackrox/perfscale/stackrox-perfscale-workflow.metadata.json
  ci-operator/step-registry/stackrox/perfscale/stackrox-perfscale-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#65558 Add recert release-4.19 config
  ci-operator/config/rh-ecosystem-edge/recert/rh-ecosystem-edge-recert-release-4.19.yaml
  ci-operator/jobs/rh-ecosystem-edge/recert/rh-ecosystem-edge-recert-release-4.19-periodics.yaml
  ci-operator/jobs/rh-ecosystem-edge/recert/rh-ecosystem-edge-recert-release-4.19-postsubmits.yaml
  ci-operator/jobs/rh-ecosystem-edge/recert/rh-ecosystem-edge-recert-release-4.19-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#65580 onboard stolostron/ocm 2.10
  ci-operator/config/stolostron/ocm/stolostron-ocm-backplane-2.10.yaml
  ci-operator/config/stolostron/ocm/stolostron-ocm-main.yaml
  ci-operator/jobs/stolostron/ocm/stolostron-ocm-backplane-2.10-postsubmits.yaml
  ci-operator/jobs/stolostron/ocm/stolostron-ocm-backplane-2.10-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#65621 Update machineset configs
  clusters/build-clusters/build04/ci-scheduling-webhook/ci-builds-worker-amd64.yaml
  clusters/build-clusters/build04/ci-scheduling-webhook/ci-longtests-worker-amd64.yaml
  clusters/build-clusters/build04/ci-scheduling-webhook/ci-prowjobs-worker-amd64.yaml
  clusters/build-clusters/build04/ci-scheduling-webhook/ci-tests-worker-amd64.yaml
  clusters/build-clusters/build04/openshift-machine-api/build04-g4f6n-infra-a_machineautoscaler.yaml
  clusters/build-clusters/build04/openshift-machine-api/build04-g4f6n-infra-a_machineset.yaml
  clusters/build-clusters/build04/openshift-machine-api/build04-g4f6n-infra-b_machineautoscaler.yaml
  clusters/build-clusters/build04/openshift-machine-api/build04-g4f6n-infra-b_machineset.yaml
  clusters/build-clusters/build04/openshift-machine-api/build04-g4f6n-infra-c_machineautoscaler.yaml
  clusters/build-clusters/build04/openshift-machine-api/build04-g4f6n-infra-c_machineset.yaml
Labels: lgtm, approved, rehearsals-ack

#65532 cincy: add downstream build to CI
  ci-operator/config/openshift/cincinnati/openshift-cincinnati-master.yaml
Labels: lgtm, approved, rehearsals-ack

#65573 OKD-253: Add dev-scripts base image needed for agent job
  ci-operator/config/openshift/release/openshift-release-master__okd-scos-4.20.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#65625 updating openshift-preflight operator-sdk version to v1.40.0
  ci-operator/config/redhat-openshift-ecosystem/openshift-preflight/redhat-openshift-ecosystem-openshift-preflight-main__4.13.yaml
  ci-operator/config/redhat-openshift-ecosystem/openshift-preflight/redhat-openshift-ecosystem-openshift-preflight-main__4.18.yaml
Labels: lgtm, approved, rehearsals-ack

#65634 METAL-1348: Update service with nodeSelector
  clusters/master/ofcir-system.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#65631 NO-ISSUE: start fast-forward for ocm-2.15 instead of ocm-2.14
  ci-operator/jobs/infra-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#65526 add checks and required env vars
  ci-operator/config/openshift-online/ocm-cluster-service/openshift-online-ocm-cluster-service-main.yaml
  ci-operator/jobs/openshift-online/ocm-cluster-service/openshift-online-ocm-cluster-service-main-presubmits.yaml
  ci-operator/step-registry/openshift-online/pr-check/OWNERS
  ci-operator/step-registry/openshift-online/pr-check/openshift-online-pr-check-commands.sh
  ci-operator/step-registry/openshift-online/pr-check/openshift-online-pr-check-ref.metadata.json
  ci-operator/step-registry/openshift-online/pr-check/openshift-online-pr-check-ref.yaml
  ci-operator/step-registry/openshift-online/run-integration-test-on-existing-environment/openshift-online-run-integration-test-on-existing-environment-commands.sh
Labels: lgtm, approved, rehearsals-ack

#65647 Fix machinesets mode for build04
  clusters/build-clusters/build04/assets/machine-configuration.yaml
Labels: lgtm, approved, rehearsals-ack

#65315 Adding missed parameters to admin_ack
  ci-operator/step-registry/cucushift/upgrade/retarget/cucushift-upgrade-retarget-commands.sh
  ci-operator/step-registry/cucushift/upgrade/toimage/cucushift-upgrade-toimage-commands.sh
Labels: lgtm, approved, rehearsals-ack

#65607 ofcir-acquire - retry for 15 minutes
  ci-operator/step-registry/ofcir/acquire/ofcir-acquire-commands.sh
Labels: lgtm, approved, rehearsals-ack

#65614 Update kubevirt-plugin e2e tests to node 18
  ci-operator/config/kubevirt-ui/kubevirt-plugin/kubevirt-ui-kubevirt-plugin-main.yaml
Labels: lgtm, approved, rehearsals-ack

#65653 setup image-mirroring for assisted-installer version v2.41
  core-services/image-mirroring/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#65128 [kubevirt-tekton-tasks] chore: bump ocp version to 4.19
  ci-operator/config/kubevirt/kubevirt-tekton-tasks/kubevirt-kubevirt-tekton-tasks-main.yaml
Labels: lgtm, approved, rehearsals-ack

#65648 OCPBUGS-57045: hypershift prow CI failed on the pull secret enablement
  ci-operator/step-registry/cucushift/hypershift-extended/enable-qe/pull-secret/cucushift-hypershift-extended-enable-qe-pull-secret-commands.sh
Labels: lgtm, approved, jira/valid-bug, rehearsals-ack, jira/valid-reference

#65407 CMP-3418: Update index image for file integrity operator test
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__amd64-nightly.yaml
  ci-operator/step-registry/file-integrity/konflux-catalogsource/file-integrity-konflux-catalogsource-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#65661 Add option to ignore known test failiures
  ci-operator/step-registry/telcov10n/verify-junit-reports/telcov10n-verify-junit-reports-commands.sh
  ci-operator/step-registry/telcov10n/verify-junit-reports/telcov10n-verify-junit-reports-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#65555 Bump jetlag version
  ci-operator/step-registry/openshift-qe/installer/bm/deploy/openshift-qe-installer-bm-deploy-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#65595 `secret-manager`: Fallback to local config in case of http error
  hack/gcp-secret-manager/util.py
Labels: lgtm, approved, rehearsals-ack

#65630 stackrox: perf&scale scanner-v4 @weekly
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies__ocp-4-18.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-nightlies-periodics.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-nightlies-postsubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#62898 OCPBUGS-53188: rename 'master' to 'main' for coredns
  ci-operator/config/openshift-priv/coredns/openshift-priv-coredns-main.yaml
  ci-operator/config/openshift/coredns/openshift-coredns-main.yaml
  ci-operator/config/openshift/coredns/openshift-coredns-main__okd-scos.yaml
  ci-operator/jobs/openshift-priv/coredns/openshift-priv-coredns-main-postsubmits.yaml
  ci-operator/jobs/openshift-priv/coredns/openshift-priv-coredns-main-presubmits.yaml
  ci-operator/jobs/openshift/coredns/openshift-coredns-main-postsubmits.yaml
  ci-operator/jobs/openshift/coredns/openshift-coredns-main-presubmits.yaml
Labels: lgtm, approved, jira/valid-bug, rehearsals-ack, jira/valid-reference

#65678 Upgrade logging operator to 6.2 channel
  clusters/build-clusters/common_ocp/openshift-logging-operator.yaml
Labels: lgtm, approved, rehearsals-ack

#65667 Fix the qe catalog overwriten issue
  ci-operator/step-registry/enable-qe-catalogsource/logging/enable-qe-catalogsource-logging-commands.sh
Labels: lgtm, approved, rehearsals-ack

#65659 add kubeburner image for 416
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16.yaml
Labels: lgtm, approved, rehearsals-ack

#65442 Adding number of nodes to 1
  ci-operator/step-registry/redhat-chaos/hog-scenarios/cpu/redhat-chaos-hog-scenarios-cpu-ref.yaml
  ci-operator/step-registry/redhat-chaos/hog-scenarios/io/redhat-chaos-hog-scenarios-io-ref.yaml
  ci-operator/step-registry/redhat-chaos/hog-scenarios/memory/redhat-chaos-hog-scenarios-memory-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#65686 secrets for aws-4 and aws-5
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#64519 add 4.19 Nutanix control plane test
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__nutanix-4.18-nightly-x86.yaml
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__nutanix-4.19-nightly-x86.yaml
  ci-operator/jobs/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#65609 Extend run_if_changed for ACS' scanner-v4-install test suite
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-12.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-18.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-stable-scanner-v4-install.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-x.y.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-x.y__ocp-4-12.yaml
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-x.y__ocp-4-18.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-presubmits.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-x.y-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#65680 updating openshift-preflight build image to go 1.24
  ci-operator/config/redhat-openshift-ecosystem/openshift-preflight/redhat-openshift-ecosystem-openshift-preflight-main__4.13.yaml
  ci-operator/config/redhat-openshift-ecosystem/openshift-preflight/redhat-openshift-ecosystem-openshift-preflight-main__4.18.yaml
Labels: lgtm, approved, rehearsals-ack

#65046 SPLAT-1650: test vmware journal capture
  ci-operator/step-registry/ipi/conf/vsphere/vcm/ipi-conf-vsphere-vcm-commands.sh
  ci-operator/step-registry/ipi/deprovision/vsphere/diags/ipi-deprovision-vsphere-diags-commands.sh
  ci-operator/step-registry/ipi/deprovision/vsphere/diags/vcm/ipi-deprovision-vsphere-diags-vcm-commands.sh
  ci-operator/step-registry/upi/conf/vsphere/vcm/upi-conf-vsphere-vcm-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#65692 perf tests for downstream 1.9 builds
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-netobserv-perf-tests__netobserv-aws-4.19-nightly-x86.yaml
Labels: lgtm, approved, rehearsals-ack

#65643 Scanner 2.37
  ci-operator/config/stackrox/scanner/stackrox-scanner-release-2.37.yaml
  ci-operator/jobs/stackrox/scanner/stackrox-scanner-release-2.37-postsubmits.yaml
  ci-operator/jobs/stackrox/scanner/stackrox-scanner-release-2.37-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#65320 To fix ACS dependency issue for interop testing.
  ci-operator/step-registry/stackrox/qa-e2e/stackrox-qa-e2e-commands.sh
Labels: lgtm, approved, rehearsals-ack

#65668 METAL-1440: keep-manifest-list when mirroring metal upgrade images
  ci-operator/step-registry/baremetalds/e2e/test/baremetalds-e2e-test-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#65671 add kubeburner image for 417
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17.yaml
Labels: lgtm, approved, rehearsals-ack

#65674 ci: Modify Dockerfile path
  ci-operator/config/openshift/jenkins/openshift-jenkins-release-rhel9.yaml
Labels: lgtm, approved, rehearsals-ack

#65703 Add build02 config for job ci-secret-bootstrap
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#65705 More configs for build02
  core-services/ci-secret-generator/_config.yaml
  core-services/prow/02_config/_plugins.yaml
  core-services/sanitize-prow-jobs/_config.yaml
  core-services/sync-rover-groups/_config.yaml
  docs/dptp-triage-sop/sync-rover-group.md
  hack/failover.sh
  hack/secrets.sh
Labels: lgtm, approved, rehearsals-ack

#65694 konflux: increase machine size in us-west-2
  clusters/hosted-mgmt/hive/pools/konflux/konflux-aws-us-west-2.yaml
Labels: lgtm, approved, rehearsals-ack

#65711 Add missing bootstrap config for build02
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#65561 CNTRLPLANE-939: cluster-authentication-operator: add TechPreview job to run e2e OIDC tests
  ci-operator/config/openshift-priv/cluster-authentication-operator/openshift-priv-cluster-authentication-operator-master.yaml
  ci-operator/config/openshift/cluster-authentication-operator/openshift-cluster-authentication-operator-master.yaml
  ci-operator/jobs/openshift-priv/cluster-authentication-operator/openshift-priv-cluster-authentication-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/cluster-authentication-operator/openshift-cluster-authentication-operator-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#65583 OCPQE-21175: Quay Bridge Operator Upgrade Prow testing
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__quay-upgrade.yaml
  ci-operator/jobs/quay/quay-tests/quay-quay-tests-master-periodics.yaml
  ci-operator/step-registry/quay-tests/test/quay-upgrade/quay-tests-test-quay-upgrade-commands.sh
  ci-operator/step-registry/quay-tests/test/quay-upgrade/quay-tests-test-quay-upgrade-ref.yaml
Labels: lgtm, approved, tide/merge-method-squash, rehearsals-ack, jira/valid-reference

#65628 kni:telco: skip running prow CI on konflux related changes only
  ci-operator/config/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-master.yaml
  ci-operator/config/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.12.yaml
  ci-operator/config/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.13.yaml
  ci-operator/config/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.14.yaml
  ci-operator/config/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.15.yaml
  ci-operator/config/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.16.yaml
  ci-operator/config/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.17.yaml
  ci-operator/config/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.18.yaml
  ci-operator/config/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.19.yaml
  ci-operator/jobs/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-master-presubmits.yaml
  ci-operator/jobs/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.12-presubmits.yaml
  ci-operator/jobs/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.13-presubmits.yaml
  ci-operator/jobs/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.14-presubmits.yaml
  ci-operator/jobs/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.15-presubmits.yaml
  ci-operator/jobs/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.16-presubmits.yaml
  ci-operator/jobs/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.17-presubmits.yaml
  ci-operator/jobs/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.18-presubmits.yaml
  ci-operator/jobs/openshift-kni/cnf-features-deploy/openshift-kni-cnf-features-deploy-release-4.19-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#65720 fix: konflux: use in-repo dockerfile
  ci-operator/config/konflux-ci/e2e-tests/konflux-ci-e2e-tests-main.yaml
Labels: lgtm, approved, rehearsals-ack

#65665 RHDH enhanced reporting for release-1.6
  ci-operator/config/redhat-developer/rhdh/redhat-developer-rhdh-release-1.6.yaml
  ci-operator/jobs/redhat-developer/rhdh/redhat-developer-rhdh-main-periodics.yaml
  ci-operator/jobs/redhat-developer/rhdh/redhat-developer-rhdh-release-1.6-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#65693 [o/cert-manager-operator] Add cert-manager-1.16 branch configs
  ci-operator/config/openshift/cert-manager-operator/openshift-cert-manager-operator-cert-manager-1.16.yaml
  ci-operator/jobs/openshift/cert-manager-operator/openshift-cert-manager-operator-cert-manager-1.16-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#65702 Update Tracing upstream jobs
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__upstream-ocp-4.12-amd64-azure.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__upstream-ocp-4.18-amd64-gcp.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__upstream-ocp-4.19-amd64-aws.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__upstream-ocp-4.12-amd64-azure.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__upstream-ocp-4.18-amd64-gcp.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__upstream-ocp-4.19-amd64-aws.yaml
  ci-operator/jobs/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main-presubmits.yaml
  ci-operator/step-registry/distributed-tracing/tests/opentelemetry/pre-upgrade/OWNERS
  ci-operator/step-registry/distributed-tracing/tests/opentelemetry/pre-upgrade/distributed-tracing-tests-opentelemetry-pre-upgrade-commands.sh
  ci-operator/step-registry/distributed-tracing/tests/opentelemetry/pre-upgrade/distributed-tracing-tests-opentelemetry-pre-upgrade-ref.metadata.json
  ci-operator/step-registry/distributed-tracing/tests/opentelemetry/pre-upgrade/distributed-tracing-tests-opentelemetry-pre-upgrade-ref.yaml
  ci-operator/step-registry/distributed-tracing/tests/opentelemetry/upstream/distributed-tracing-tests-opentelemetry-upstream-commands.sh
  ci-operator/step-registry/distributed-tracing/tests/tempo/pre-upgrade/OWNERS
  ci-operator/step-registry/distributed-tracing/tests/tempo/pre-upgrade/distributed-tracing-tests-tempo-pre-upgrade-commands.sh
  ci-operator/step-registry/distributed-tracing/tests/tempo/pre-upgrade/distributed-tracing-tests-tempo-pre-upgrade-ref.metadata.json
  ci-operator/step-registry/distributed-tracing/tests/tempo/pre-upgrade/distributed-tracing-tests-tempo-pre-upgrade-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#65726 add missing "q"
  ci-operator/jobs/infra-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#64079 CORENET-5694: Move ovn-kubernetes virt jobs to baremetalds to test it with dualstack
  ci-operator/config/openshift/origin/openshift-origin-main.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.20.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.20__periodics.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-main-presubmits.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master-presubmits.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.20-periodics.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.20-presubmits.yaml
  ci-operator/step-registry/kubevirt/install/kubevirt-install-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#65725 [KMM] Adding CI for the `release-2.4` branch.
  ci-operator/config/rh-ecosystem-edge/kernel-module-management/rh-ecosystem-edge-kernel-module-management-release-2.4.yaml
  ci-operator/jobs/rh-ecosystem-edge/kernel-module-management/rh-ecosystem-edge-kernel-module-management-release-2.4-postsubmits.yaml
  ci-operator/jobs/rh-ecosystem-edge/kernel-module-management/rh-ecosystem-edge-kernel-module-management-release-2.4-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#65730 cnf-network: update cron schedule
  ci-operator/config/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main__cnf-network-4.17.yaml
  ci-operator/jobs/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#64713 Bump merge-bot config for openstack repos
  ci-operator/config/shiftstack/merge-bot/shiftstack-merge-bot-main.yaml
  ci-operator/jobs/shiftstack/merge-bot/shiftstack-merge-bot-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#65738 [DPTP-4437] Consider key prefix as a filter to deprovision clusters
  core-services/ipi-deprovision/aws.sh
Labels: lgtm, approved, rehearsals-ack

#65721 Add OWNERS file at the root of Codeready-Toolchain
  ci-operator/config/codeready-toolchain/OWNERS
  ci-operator/jobs/codeready-toolchain/OWNERS
  core-services/prow/02_config/codeready-toolchain/OWNERS
Labels: lgtm, approved, rehearsals-ack

#65525 [cri-o/cri-o] Fix setup-periodic job
  ci-operator/config/cri-o/cri-o/cri-o-cri-o-main__periodics.yaml
  ci-operator/jobs/cri-o/cri-o/cri-o-cri-o-main-periodics.yaml
  ci-operator/step-registry/cri-o/setup/cri-o-setup-workflow.yaml
  ci-operator/step-registry/cri-o/setup/test/cri-o-setup-test-commands.sh
Labels: lgtm, approved, rehearsals-ack

#65745 Fix openshift-monitoring configs
  clusters/build-clusters/build02/openshift-monitoring/cluster-monitoring-config.yaml
  clusters/build-clusters/build04/openshift-monitoring/alertmanager-main_secret_template.yaml
  clusters/build-clusters/build04/openshift-monitoring/cluster-monitoring-config.yaml
  clusters/build-clusters/build04/openshift-monitoring/prow-rules_prometheusrule.yaml
Labels: lgtm, approved, rehearsals-ack

#65752 Fix a hardcoded region
  core-services/ipi-deprovision/aws.sh
Labels: lgtm, approved, rehearsals-ack

#65756 tidy cpou jobs and enable 4.20 test
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-nightly-4.17-cpou-upgrade-from-4.15.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__arm64-nightly-4.17-cpou-upgrade-from-4.15.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__multi-nightly-4.17-cpou-upgrade-from-4.15.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly-4.18-cpou-upgrade-from-4.15.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__arm64-nightly-4.18-cpou-upgrade-from-4.15.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__multi-nightly-4.18-cpou-upgrade-from-4.15.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__amd64-nightly-4.19-cpou-upgrade-from-4.16.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__amd64-nightly-4.19-cpou-upgrade-from-4.17.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__arm64-nightly-4.19-cpou-upgrade-from-4.16.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__arm64-nightly-4.19-cpou-upgrade-from-4.17.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__multi-nightly-4.19-cpou-upgrade-from-4.16.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__multi-nightly-4.19-cpou-upgrade-from-4.17.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__amd64-nightly-4.20-cpou-upgrade-from-4.18.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__arm64-nightly-4.20-cpou-upgrade-from-4.18.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__multi-nightly-4.20-cpou-upgrade-from-4.18.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#65514 mirror by oc adm updates
  ci-operator/step-registry/mirror-images/by-oc-adm-in-bastion/mirror-images-by-oc-adm-in-bastion-commands.sh
  ci-operator/step-registry/mirror-images/by-oc-adm/mirror-images-by-oc-adm-commands.sh
  ci-operator/step-registry/mirror-images/by-oc-adm/mirror-images-by-oc-adm-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#65758 Add dex for build02
  clusters/app.ci/dex/manifests.yaml
Labels: lgtm, approved, rehearsals-ack

#65506 SPLAT-2243:change the bastion.ign and image
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-main__installer-rehearse-4.18.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-main__installer-rehearse-4.20.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-main-periodics.yaml
  ci-operator/step-registry/ibmcloud/provision/bastionhost/ibmcloud-provision-bastionhost-commands.sh
  ci-operator/step-registry/ibmcloud/provision/resourcegroup/ibmcloud-provision-resourcegroup-commands.sh
  ci-operator/step-registry/ignition/bastionhost/ignition-bastionhost-commands.sh
  ci-operator/step-registry/mirror-images/by-oc-mirror/mirror-images-by-oc-mirror-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#65687 telco5g: Run all tests on SNO ZTP
  ci-operator/step-registry/telco5g/cnf/tests/telco5g-cnf-tests-commands.sh
Labels: lgtm, approved, rehearsals-ack

#65478 Wait for worker MCP to be updated before running RHEL worker upgrade
  ci-operator/step-registry/cucushift/chainupgrade/toimage/cucushift-chainupgrade-toimage-commands.sh
  ci-operator/step-registry/cucushift/upgrade/cpou/unpause-worker-mcp/cucushift-upgrade-cpou-unpause-worker-mcp-commands.sh
Labels: lgtm, approved, rehearsals-ack

#65767 Add several clusters to "make secret-config-updater"
  Makefile
Labels: lgtm, approved, rehearsals-ack

#65762 NO-ISSUE: Add rhel-9.6 as allowed OS for MicroShift clusterbot
  ci-operator/step-registry/openshift/microshift/clusterbot/openshift-microshift-clusterbot-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#65770 Update istio 1.26 builder image
  core-services/image-mirroring/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#65026 add aws mce job
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#65710 Update right cluster profile
  ci-operator/step-registry/baremetalds/two-node/arbiter/e2e-openshift-test-private-tests/baremetalds-two-node-arbiter-e2e-openshift-test-private-tests-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#65714 konflux: add community-catalog repository
  ci-operator/config/konflux-ci/community-catalog/OWNERS
  ci-operator/config/konflux-ci/community-catalog/konflux-ci-community-catalog-development.yaml
  ci-operator/jobs/konflux-ci/community-catalog/OWNERS
  ci-operator/jobs/konflux-ci/community-catalog/konflux-ci-community-catalog-development-presubmits.yaml
  core-services/prow/02_config/konflux-ci/community-catalog/_pluginconfig.yaml
  core-services/prow/02_config/konflux-ci/community-catalog/_prowconfig.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#65761 Fix for CI slack alerts
  ci-operator/step-registry/redhat-developer/rhdh/send/alert/redhat-developer-rhdh-send-alert-commands.sh
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#65779 Revert deprovision modifications
  core-services/ipi-deprovision/aws.sh
  core-services/ipi-deprovision/gcp.sh
Labels: lgtm, approved, rehearsals-ack

#65684 Drop backport-risk-assessed and cherry-pick-approved from origin
  core-services/prow/02_config/openshift/origin/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#65679 Update kubevirt-ui node version with tectonic-console-builder-v29
  ci-operator/config/kubevirt-ui/kubevirt-plugin/kubevirt-ui-kubevirt-plugin-main.yaml
Labels: lgtm, approved, rehearsals-ack

#65744 [cyborg]update the cyborg base image
  ci-operator/config/openshift-eng/cyborg/openshift-eng-cyborg-master.yaml
Labels: lgtm, approved, rehearsals-ack

#65784 TRT-2137: add telcov10n kpis as informing
  core-services/release-controller/_releases/priv/release-ocp-4.20.json
  core-services/release-controller/_releases/release-ocp-4.20.json
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#65789 Update build02 secret
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#65791 Update missing clusterautoscaler for new clusters
  clusters/build-clusters/build02/machineset/clusterautoscaler.yaml
  clusters/build-clusters/build04/machineset/clusterautoscaler.yaml
Labels: lgtm, approved, rehearsals-ack

#65742 cvo: run integration tests with make target
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-main.yaml
Labels: lgtm, approved, rehearsals-ack

#65792 OLS-1833: Create Prow jobs for openshift-docs branches for OLS release
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-lightspeed-docs-1.0.yaml
  ci-operator/jobs/openshift/openshift-docs/openshift-openshift-docs-lightspeed-docs-1.0-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#65799 fixing the configuration for NFD operator
  ci-operator/config/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-master.yaml
  ci-operator/config/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-release-4.20.yaml
Labels: lgtm, approved, rehearsals-ack

#65620 NO-ISSUE: Add CI configuration for IBIO backplane-2.10
  ci-operator/config/openshift/image-based-install-operator/openshift-image-based-install-operator-backplane-2.10.yaml
  ci-operator/jobs/openshift/image-based-install-operator/openshift-image-based-install-operator-backplane-2.10-periodics.yaml
  ci-operator/jobs/openshift/image-based-install-operator/openshift-image-based-install-operator-backplane-2.10-postsubmits.yaml
  ci-operator/jobs/openshift/image-based-install-operator/openshift-image-based-install-operator-backplane-2.10-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#65805 [KMM] Adding image-mirroring for 2.2, 2.3 and 2.4 releases.
  core-services/image-mirroring/edge-infrastructure/mapping_edge_infrastructure_kernel_module_management
Labels: lgtm, approved, rehearsals-ack

#65326 MGMT-20512: Remove 'net-suite' jobs
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.10.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.11.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.12.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.13.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.9.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-periodics.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-presubmits.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.10-periodics.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.10-presubmits.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.11-periodics.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.11-presubmits.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.12-periodics.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.12-presubmits.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.13-periodics.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.13-presubmits.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.9-periodics.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-release-ocm-2.9-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#65802 NO-ISSUE: Remove assisted temporary images streams
  core-services/image-mirroring/_config.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#65355 port olm stress job to 420
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#65763 Use custom default region rather than LEASED_RESOURCE
  ci-operator/step-registry/rosa/cluster/upgrade/hcp/rosa-cluster-upgrade-hcp-commands.sh
  ci-operator/step-registry/rosa/setup/cluster/list/rosa-setup-cluster-list-commands.sh
  ci-operator/step-registry/rosa/setup/readiness/cluster/rosa-setup-readiness-cluster-commands.sh
  ci-operator/step-registry/rosa/setup/readiness/day2-conf/rosa-setup-readiness-day2-conf-commands.sh
  ci-operator/step-registry/rosa/setup/rosa-setup-commands.sh
  ci-operator/step-registry/rosa/teardown/rosa-teardown-commands.sh
  ci-operator/step-registry/rosa/tests/pull-request/rosa-tests-pull-request-commands.sh
  ci-operator/step-registry/rosa/tests/rosa-tests-commands.sh
  ci-operator/step-registry/rosa/tests/runtime/day1-post/rosa-tests-runtime-day1-post-commands.sh
  ci-operator/step-registry/rosa/tests/runtime/day2/rosa-tests-runtime-day2-commands.sh
  ci-operator/step-registry/rosa/tests/runtime/destroy-post/rosa-tests-runtime-destroy-post-commands.sh
  ci-operator/step-registry/rosa/tests/runtime/destroy/rosa-tests-runtime-destroy-commands.sh
  ci-operator/step-registry/rosa/tests/runtime/destructive/rosa-tests-runtime-destructive-commands.sh
Labels: lgtm, approved, rehearsals-ack

#64956 Use ocm-backend-tests GCP day1 prepare for OCPE2E job
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19-periodics.yaml
  ci-operator/step-registry/ocm-api/OWNERS
  ci-operator/step-registry/ocm-api/lifecycle/OWNERS
  ci-operator/step-registry/ocm-api/lifecycle/ocm-api-lifecycle-workflow.metadata.json
  ci-operator/step-registry/ocm-api/lifecycle/ocm-api-lifecycle-workflow.yaml
  ci-operator/step-registry/ocm-api/setup/OWNERS
  ci-operator/step-registry/ocm-api/setup/ocm-api-setup-commands.sh
  ci-operator/step-registry/ocm-api/setup/ocm-api-setup-ref.metadata.json
  ci-operator/step-registry/ocm-api/setup/ocm-api-setup-ref.yaml
  ci-operator/step-registry/ocm-api/teardown/OWNERS
  ci-operator/step-registry/ocm-api/teardown/ocm-api-teardown-commands.sh
  ci-operator/step-registry/ocm-api/teardown/ocm-api-teardown-ref.metadata.json
  ci-operator/step-registry/ocm-api/teardown/ocm-api-teardown-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#65773 Remove UPGRADE_RHEL_WORKER_BEFOREHAND workaround in RHEL upgrade jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly-4.16-upgrade-from-stable-4.15.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-nightly-4.17-upgrade-from-stable-4.16.yaml
Labels: lgtm, approved, rehearsals-ack

#65794 Onboard build02 and build04 into rotation
  core-services/sanitize-prow-jobs/_clusters.yaml
Labels: lgtm, approved, rehearsals-ack

#65815 make jobs
  ci-operator/jobs/openshift-priv/multiarch-tuning-operator/openshift-priv-multiarch-tuning-operator-v0.9-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#65772 OCPQE-27646: addconnectedlabel
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__amd64-nightly.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#65833 Add capability intranet to build09
  core-services/sanitize-prow-jobs/_clusters.yaml
Labels: lgtm, approved, rehearsals-ack

#65830 chore: Update maven binary url and version
  ci-operator/config/openshift/jenkins-sync-plugin/openshift-jenkins-sync-plugin-master.yaml
  ci-operator/config/openshift/jenkins-sync-plugin/openshift-jenkins-sync-plugin-release-4.12.yaml
  ci-operator/config/openshift/jenkins-sync-plugin/openshift-jenkins-sync-plugin-release-4.13.yaml
  ci-operator/config/openshift/jenkins-sync-plugin/openshift-jenkins-sync-plugin-release-4.14.yaml
  ci-operator/config/openshift/jenkins-sync-plugin/openshift-jenkins-sync-plugin-release-4.15.yaml
  ci-operator/config/openshift/jenkins-sync-plugin/openshift-jenkins-sync-plugin-release-4.16.yaml
  ci-operator/config/openshift/jenkins-sync-plugin/openshift-jenkins-sync-plugin-release-4.17.yaml
  ci-operator/config/openshift/jenkins-sync-plugin/openshift-jenkins-sync-plugin-release-4.18.yaml
  ci-operator/config/openshift/jenkins-sync-plugin/openshift-jenkins-sync-plugin-release-4.19.yaml
  ci-operator/config/openshift/jenkins-sync-plugin/openshift-jenkins-sync-plugin-release-4.20.yaml
  ci-operator/config/openshift/jenkins-sync-plugin/openshift-jenkins-sync-plugin-release-4.21.yaml
Labels: lgtm, approved, rehearsals-ack

#65847 [DPTP-4437] Consider key prefix as a filter to deprovision clusters
  core-services/ipi-deprovision/aws.sh
Labels: lgtm, approved, rehearsals-ack

#65866 acm cluster-backup require konflux job on correct branch
  core-services/prow/02_config/stolostron/cluster-backup-operator/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#65870 disable build04 since it's not coming up.
  core-services/sanitize-prow-jobs/_clusters.yaml
Labels: lgtm, approved, rehearsals-ack

#65868 remove instaslice lint
  ci-operator/config/openshift/instaslice-operator/openshift-instaslice-operator-next.yaml
  ci-operator/jobs/openshift/instaslice-operator/openshift-instaslice-operator-next-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#65790 jira-lifecycle-plugin: enable bigquery
  clusters/app.ci/jira-lifecycle-plugin/deployment.yaml
Labels: lgtm, approved, rehearsals-ack

#65832 konflux: remove '/lgtm' from community-catalog
  core-services/prow/02_config/konflux-ci/community-catalog/_pluginconfig.yaml
  core-services/prow/02_config/konflux-ci/community-catalog/_prowconfig.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#65889 Add capability intranet to build09
  core-services/sanitize-prow-jobs/_clusters.yaml
Labels: lgtm, approved, rehearsals-ack

#65821 SPIRE-32: Bootstrap CI configs for ZMWIM repo
  ci-operator/config/openshift/zero-trust-workload-identity-manager/openshift-zero-trust-workload-identity-manager-main.yaml
  ci-operator/jobs/openshift/zero-trust-workload-identity-manager/openshift-zero-trust-workload-identity-manager-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#65846 MGDAPI-6669 RHOAM Go update to 1.23
  ci-operator/config/integr8ly/integreatly-operator/integr8ly-integreatly-operator-master.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#65839 ci: Mark Konflux CI test optional
  core-services/prow/02_config/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#65853 Enable TP on build02
  clusters/build-clusters/build02/assets/featuregate_cluster.yaml
Labels: lgtm, approved, rehearsals-ack

#65893 Fix release in OKD jobs
  ci-operator/config/openshift/release/openshift-release-master__okd-4.16-upgrade-from-okd-4.15.yaml
  ci-operator/config/openshift/release/openshift-release-master__okd-4.16.yaml
  ci-operator/config/openshift/release/openshift-release-master__okd-4.17-upgrade-from-okd-4.16.yaml
  ci-operator/config/openshift/release/openshift-release-master__okd-4.17.yaml
  ci-operator/config/openshift/release/openshift-release-master__okd-4.18-upgrade-from-okd-4.17.yaml
  ci-operator/config/openshift/release/openshift-release-master__okd-4.18.yaml
Labels: lgtm, approved, rehearsals-ack

#65841 Add Slack reporting for NTO for 4.18 and 4.19
  ci-operator/jobs/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-release-4.18-periodics.yaml
  ci-operator/jobs/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-release-4.19-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#65477 OVNK BGP: gather debug information through console
  ci-operator/config/openshift/origin/openshift-origin-main.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.18.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.19.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.20.yaml
  ci-operator/config/openshift/origin/openshift-origin-release-4.21.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.18.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.18__periodics.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.19.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.19__periodics.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.20.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.20__periodics.yaml
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.21.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master-periodics.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master-presubmits.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.18-periodics.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.18-presubmits.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.19-periodics.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.19-presubmits.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.20-periodics.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.20-presubmits.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.21-presubmits.yaml
  ci-operator/step-registry/baremetalds/devscripts/conf/featureset/OWNERS
  ci-operator/step-registry/baremetalds/devscripts/conf/featureset/baremetalds-devscripts-conf-featureset-commands.sh
  ci-operator/step-registry/baremetalds/devscripts/conf/featureset/baremetalds-devscripts-conf-featureset-ref.metadata.json
  ci-operator/step-registry/baremetalds/devscripts/conf/featureset/baremetalds-devscripts-conf-featureset-ref.yaml
  ci-operator/step-registry/baremetalds/e2e/ovn/bgp/dualstack-local-gw/OWNERS
  ci-operator/step-registry/baremetalds/e2e/ovn/bgp/dualstack-local-gw/baremetalds-e2e-ovn-bgp-dualstack-local-gw-workflow.metadata.json
  ci-operator/step-registry/baremetalds/e2e/ovn/bgp/dualstack-local-gw/baremetalds-e2e-ovn-bgp-dualstack-local-gw-workflow.yaml
  ci-operator/step-registry/baremetalds/e2e/ovn/bgp/dualstack/OWNERS
  ci-operator/step-registry/baremetalds/e2e/ovn/bgp/dualstack/baremetalds-e2e-ovn-bgp-dualstack-workflow.metadata.json
  ci-operator/step-registry/baremetalds/e2e/ovn/bgp/dualstack/baremetalds-e2e-ovn-bgp-dualstack-workflow.yaml
  ci-operator/step-registry/baremetalds/e2e/ovn/bgp/pre/baremetalds-e2e-ovn-bgp-pre-commands.sh
  ci-operator/step-registry/baremetalds/e2e/ovn/debug/OWNERS
  ci-operator/step-registry/baremetalds/e2e/ovn/debug/console-gather/OWNERS
  ci-operator/step-registry/baremetalds/e2e/ovn/debug/console-gather/baremetalds-e2e-ovn-debug-console-gather-commands.sh
  ci-operator/step-registry/baremetalds/e2e/ovn/debug/console-gather/baremetalds-e2e-ovn-debug-console-gather-ref.metadata.json
  ci-operator/step-registry/baremetalds/e2e/ovn/debug/console-gather/baremetalds-e2e-ovn-debug-console-gather-ref.yaml
  ci-operator/step-registry/baremetalds/e2e/ovn/debug/enable-console/OWNERS
  ci-operator/step-registry/baremetalds/e2e/ovn/debug/enable-console/baremetalds-e2e-ovn-debug-enable-console-commands.sh
  ci-operator/step-registry/baremetalds/e2e/ovn/debug/enable-console/baremetalds-e2e-ovn-debug-enable-console-ref.metadata.json
  ci-operator/step-registry/baremetalds/e2e/ovn/debug/enable-console/baremetalds-e2e-ovn-debug-enable-console-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#65256 [PERFSCALE-3938] Adding virt-udn-density-6nodes in daily 4.18 and 4.19
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__metal-4.18-latest-x86.yaml
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__metal-4.19-latest-x86.yaml
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__metal-dev-latest-x86.yaml
  ci-operator/step-registry/openshift-qe/virt-udn-density/openshift-qe-virt-udn-density-commands.sh
  ci-operator/step-registry/openshift-qe/virt-udn-density/openshift-qe-virt-udn-density-ref.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#65528 Bump devfile registry operator CI to use Go 1.22
  ci-operator/config/devfile/registry-operator/devfile-registry-operator-main__v4.15.yaml
  ci-operator/config/devfile/registry-operator/devfile-registry-operator-release-v0__v4.15.yaml
  ci-operator/jobs/devfile/registry-operator/devfile-registry-operator-release-v0-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#65928 ROX-29650: mirror stackrox image 0.4.9
  core-services/image-mirroring/_config.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#65883 CORS-3991: remove e2e from aws-private pre-submit jobs
  ci-operator/config/openshift-priv/installer/openshift-priv-installer-main.yaml
  ci-operator/config/openshift-priv/installer/openshift-priv-installer-release-4.20.yaml
  ci-operator/config/openshift-priv/installer/openshift-priv-installer-release-4.21.yaml
  ci-operator/config/openshift/installer/openshift-installer-main.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.19.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.20.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.21.yaml
  ci-operator/jobs/openshift-priv/installer/openshift-priv-installer-main-presubmits.yaml
  ci-operator/jobs/openshift-priv/installer/openshift-priv-installer-release-4.20-presubmits.yaml
  ci-operator/jobs/openshift-priv/installer/openshift-priv-installer-release-4.21-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-main-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.19-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.20-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.21-presubmits.yaml
  ci-operator/step-registry/cucushift/installer/check/aws/private/cucushift-installer-check-aws-private-commands.sh
  ci-operator/step-registry/cucushift/installer/check/aws/private/cucushift-installer-check-aws-private-ref.yaml
  ci-operator/step-registry/openshift/e2e/aws/private/OWNERS
  ci-operator/step-registry/openshift/e2e/aws/private/openshift-e2e-aws-private-workflow.metadata.json
  ci-operator/step-registry/openshift/e2e/aws/private/openshift-e2e-aws-private-workflow.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#65884 Apply new contract for AWS Marketplace
  ci-operator/step-registry/ipi/conf/aws/marketplace/ipi-conf-aws-marketplace-commands.sh
Labels: lgtm, approved, rehearsals-ack

#62056 OCPQE-20701: add ash job for pre-submit
  ci-operator/config/openshift/cloud-provider-azure/openshift-cloud-provider-azure-main.yaml
  ci-operator/config/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-master.yaml
  ci-operator/config/openshift/machine-api-provider-azure/openshift-machine-api-provider-azure-main.yaml
  ci-operator/jobs/openshift/cloud-provider-azure/openshift-cloud-provider-azure-main-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-master-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-provider-azure/openshift-machine-api-provider-azure-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#65974 Add platform to ossm-cluster-pool secret
  clusters/hosted-mgmt/hive/pools/openshift-service-mesh/install-config-aws-us-east-1_secret.yaml
Labels: lgtm, approved, rehearsals-ack

#65746 OSC downstream: upates to our azure e2e workflow
  ci-operator/config/openshift/sandboxed-containers-operator/openshift-sandboxed-containers-operator-devel__downstream-1.9-release-4.18.yaml
  ci-operator/step-registry/sandboxed-containers-operator/README.md
  ci-operator/step-registry/sandboxed-containers-operator/e2e/azure/sandboxed-containers-operator-e2e-azure-workflow.yaml
  ci-operator/step-registry/sandboxed-containers-operator/env-cm/sandboxed-containers-operator-env-cm-ref.yaml
  ci-operator/step-registry/sandboxed-containers-operator/ipi/OWNERS
  ci-operator/step-registry/sandboxed-containers-operator/ipi/azure-pre/OWNERS
  ci-operator/step-registry/sandboxed-containers-operator/ipi/azure-pre/sandboxed-containers-operator-ipi-azure-pre-chain.metadata.json
  ci-operator/step-registry/sandboxed-containers-operator/ipi/azure-pre/sandboxed-containers-operator-ipi-azure-pre-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#65807 HyperShift-ODF: Set subscription channel dynamically
  ci-operator/config/openshift/kubevirt-csi-driver/openshift-kubevirt-csi-driver-main.yaml
  ci-operator/config/openshift/kubevirt-csi-driver/openshift-kubevirt-csi-driver-release-4.19.yaml
  ci-operator/jobs/openshift/kubevirt-csi-driver/openshift-kubevirt-csi-driver-main-presubmits.yaml
  ci-operator/jobs/openshift/kubevirt-csi-driver/openshift-kubevirt-csi-driver-release-4.19-presubmits.yaml
  ci-operator/step-registry/hypershift/kubevirt/install/odf/hypershift-kubevirt-install-odf-commands.sh
  ci-operator/step-registry/hypershift/kubevirt/install/odf/hypershift-kubevirt-install-odf-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#65798 Ztp left shifting telco qe use add lvm recovery method
  ci-operator/step-registry/telcov10n/metal-single-node-spoke/site-config/deploy/telcov10n-metal-single-node-spoke-site-config-deploy-commands.sh
Labels: lgtm, approved, rehearsals-ack

#65273 AGENT-1213: Dev-scripts presubmit job for ISOBuilder
  ci-operator/config/openshift-metal3/dev-scripts/openshift-metal3-dev-scripts-master.yaml
  ci-operator/jobs/openshift-metal3/dev-scripts/openshift-metal3-dev-scripts-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#65978 [ODF] Enable backports for z-streams
  core-services/jira-lifecycle-plugin/config.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#65979 albo: Update owners for aws-load-balancer step
  ci-operator/step-registry/aws-load-balancer/OWNERS
  ci-operator/step-registry/aws-load-balancer/install-proxy/aws-load-balancer-install-proxy-workflow.metadata.json
  ci-operator/step-registry/aws-load-balancer/install-rosa/aws-load-balancer-install-rosa-workflow.metadata.json
  ci-operator/step-registry/aws-load-balancer/install/aws-load-balancer-install-workflow.metadata.json
  ci-operator/step-registry/aws-load-balancer/must-gather-rosa/aws-load-balancer-must-gather-rosa-ref.metadata.json
  ci-operator/step-registry/aws-load-balancer/post-install-rosa/aws-load-balancer-post-install-rosa-ref.metadata.json
  ci-operator/step-registry/aws-load-balancer/pre-install-rosa/aws-load-balancer-pre-install-rosa-ref.metadata.json
  ci-operator/step-registry/aws-load-balancer/pre-install/aws-load-balancer-pre-install-ref.metadata.json
  ci-operator/step-registry/aws-load-balancer/tag-vpc-subnets/aws-load-balancer-tag-vpc-subnets-ref.metadata.json
Labels: lgtm, approved, rehearsals-ack

#65984 Update image for Istio 1.26
  ci-operator/config/maistra/test-infra/maistra-test-infra-main.yaml
  core-services/image-mirroring/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#65954 Use tests-private-base 4.20 for 4.20 tests
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__images.yaml
Labels: lgtm, approved, rehearsals-ack

#65912 OCP-68346: test cluster name containing periods "."
  ci-operator/step-registry/cucushift/installer/rehearse/azure/cases/multi-clusters/same-subnets/provision/cucushift-installer-rehearse-azure-cases-multi-clusters-same-subnets-provision-commands.sh
Labels: lgtm, approved, rehearsals-ack

#65999 Promote image tests-private-ui in 4.20
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__images.yaml
Labels: lgtm, approved, rehearsals-ack

#66000 Use latest operator-sdk from each specific release
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18.yaml
Labels: lgtm, approved, rehearsals-ack

#66002 Enhance AMI post-check
  ci-operator/step-registry/cucushift/installer/check/aws/custom-ami/cucushift-installer-check-aws-custom-ami-commands.sh
Labels: lgtm, approved, rehearsals-ack

#65776 Create a script file to help us create CPOU upgrade jobs
  ci-operator/config/openshift/openshift-tests-private/tools/add_CPOU_upgrade_jobs.py
Labels: lgtm, approved, rehearsals-ack

#65812 Adding 4.20 rollback jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__amd64-rollback-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__amd64-rollback-stable.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#65987 [OSSM-9601] Add kiali 2.4 test images
  core-services/image-mirroring/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#66007 Openstack-test: Add tide config for release-4.19
  core-services/prow/02_config/openshift/openstack-test/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#65997 Remove duplicate resource requests e2e-aws
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-master.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.21.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.6.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.7.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.8.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.9.yaml
Labels: lgtm, approved, rehearsals-ack

#65590 [OCPQE-29845]Updated the logic for detecting the Windows machineset name based on the platform type.
  ci-operator/step-registry/cucushift/winc/prepare/OWNERS
  ci-operator/step-registry/cucushift/winc/prepare/cucushift-winc-prepare-commands.sh
  ci-operator/step-registry/cucushift/winc/prepare/cucushift-winc-prepare-ref.metadata.json
Labels: lgtm, approved, rehearsals-ack

#65993 remove dspo ci
  ci-operator/config/opendatahub-io/data-science-pipelines-operator/opendatahub-io-data-science-pipelines-operator-main.yaml
  ci-operator/jobs/opendatahub-io/data-science-pipelines-operator/opendatahub-io-data-science-pipelines-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack
