Repository openshift/release, pull requests merged in 2025-09, with the labels that each got.

#68621 ### Update openshift-kni/eco-ci-cd OWNERS
  ci-operator/config/openshift-kni/eco-ci-cd/OWNERS
Labels: lgtm, approved, rehearsals-ack

#68689 Add images for 4.21
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.21__images.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.21-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.21-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#68694 Add quay.io push images validation
  ci-operator/config/quay/quay-tests/quay-quay-tests-master.yaml
  ci-operator/step-registry/quay-tests/quayio/quay-tests-quayio-commands.sh
  ci-operator/step-registry/quay-tests/quayio/quay-tests-quayio-ref.yaml
Labels: lgtm, approved, tide/merge-method-squash, rehearsals-ack

#68601 CNTRLPLANE-1306: Call OTE in the ci in order to ensure that the tests will be executed
  ci-operator/config/openshift/cluster-config-operator/openshift-cluster-config-operator-main.yaml
  ci-operator/config/openshift/cluster-config-operator/openshift-cluster-config-operator-release-4.20.yaml
  ci-operator/config/openshift/cluster-config-operator/openshift-cluster-config-operator-release-4.21.yaml
  ci-operator/jobs/openshift/cluster-config-operator/openshift-cluster-config-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/cluster-config-operator/openshift-cluster-config-operator-release-4.20-presubmits.yaml
  ci-operator/jobs/openshift/cluster-config-operator/openshift-cluster-config-operator-release-4.21-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#68701 Improve quay.io push images testing by pushing more image tags
  ci-operator/step-registry/quay-tests/quayio/quay-tests-quayio-commands.sh
Labels: lgtm, approved, rehearsals-ack

#68582 Add Netlify preview configuration for Validated Patterns docs site
  ci-operator/config/validatedpatterns/docs/validatedpatterns-docs-main.yaml
  ci-operator/jobs/validatedpatterns/docs/validatedpatterns-docs-main-presubmits.yaml
  ci-operator/step-registry/validatedpatterns/OWNERS
  ci-operator/step-registry/validatedpatterns/build-docs/OWNERS
  ci-operator/step-registry/validatedpatterns/build-docs/validatedpatterns-build-docs-commands.sh
  ci-operator/step-registry/validatedpatterns/build-docs/validatedpatterns-build-docs-ref.metadata.json
  ci-operator/step-registry/validatedpatterns/build-docs/validatedpatterns-build-docs-ref.yaml
  ci-operator/step-registry/validatedpatterns/preview-comment/OWNERS
  ci-operator/step-registry/validatedpatterns/preview-comment/validatedpatterns-preview-comment-commands.sh
  ci-operator/step-registry/validatedpatterns/preview-comment/validatedpatterns-preview-comment-ref.metadata.json
  ci-operator/step-registry/validatedpatterns/preview-comment/validatedpatterns-preview-comment-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#68710 RHDH re-enable cron jobs and increase wait time for image
  ci-operator/config/redhat-developer/rhdh/redhat-developer-rhdh-release-1.6.yaml
  ci-operator/config/redhat-developer/rhdh/redhat-developer-rhdh-release-1.7.yaml
  ci-operator/jobs/redhat-developer/rhdh/redhat-developer-rhdh-release-1.6-periodics.yaml
  ci-operator/jobs/redhat-developer/rhdh/redhat-developer-rhdh-release-1.7-periodics.yaml
  ci-operator/step-registry/redhat-developer/rhdh/aks/helm/nightly/redhat-developer-rhdh-aks-helm-nightly-commands.sh
  ci-operator/step-registry/redhat-developer/rhdh/aks/operator/nightly/redhat-developer-rhdh-aks-operator-nightly-commands.sh
  ci-operator/step-registry/redhat-developer/rhdh/eks/helm/nightly/redhat-developer-rhdh-eks-helm-nightly-commands.sh
  ci-operator/step-registry/redhat-developer/rhdh/eks/operator/nightly/redhat-developer-rhdh-eks-operator-nightly-commands.sh
  ci-operator/step-registry/redhat-developer/rhdh/gke/helm/nightly/redhat-developer-rhdh-gke-helm-nightly-commands.sh
  ci-operator/step-registry/redhat-developer/rhdh/gke/operator/nightly/redhat-developer-rhdh-gke-operator-nightly-commands.sh
  ci-operator/step-registry/redhat-developer/rhdh/nightly/redhat-developer-rhdh-nightly-commands.sh
  ci-operator/step-registry/redhat-developer/rhdh/operator/nightly/redhat-developer-rhdh-operator-nightly-commands.sh
  ci-operator/step-registry/redhat-developer/rhdh/osd-gcp/nightly/redhat-developer-rhdh-osd-gcp-nightly-commands.sh
  ci-operator/step-registry/redhat-developer/rhdh/redhat-developer-rhdh-commands.sh
  ci-operator/step-registry/redhat-developer/rhdh/upgrade/nightly/redhat-developer-rhdh-upgrade-nightly-commands.sh
Labels: lgtm, approved, rehearsals-ack

#68478 Adding jobs for sail operator release-3.2 branch
  ci-operator/config/openshift-service-mesh/sail-operator/openshift-service-mesh-sail-operator-release-3.2__ocp-4.19.yaml
  ci-operator/config/openshift-service-mesh/sail-operator/openshift-service-mesh-sail-operator-release-3.2__ocp-4.20.yaml
  ci-operator/jobs/openshift-service-mesh/sail-operator/openshift-service-mesh-sail-operator-release-3.2-periodics.yaml
  ci-operator/jobs/openshift-service-mesh/sail-operator/openshift-service-mesh-sail-operator-release-3.2-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#68673 NO-JIRA: no longer perform `rebase` merging from `ocp` component repositories
  core-services/prow/02_config/openshift/appliance/_prowconfig.yaml
  core-services/prow/02_config/openshift/jenkins-client-plugin/_prowconfig.yaml
  core-services/prow/02_config/openshift/jenkins-openshift-login-plugin/_prowconfig.yaml
  core-services/prow/02_config/openshift/jenkins-sync-plugin/_prowconfig.yaml
  core-services/prow/02_config/openshift/operator-framework-catalogd/_prowconfig.yaml
  core-services/prow/02_config/openshift/operator-framework-operator-controller/_prowconfig.yaml
  core-services/prow/02_config/openshift/operator-framework-rukpak/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#68711 Fix Netlify Preview URL to show patternsdocs-pr instead of ID
  ci-operator/step-registry/validatedpatterns/preview-comment/validatedpatterns-preview-comment-commands.sh
Labels: lgtm, approved, rehearsals-ack

#68721 SPLAT-2477: fix broken upi-installer image refs
  ci-operator/step-registry/aws/provision/edge-zone-subnet/aws-provision-edge-zone-subnet-ref.yaml
  ci-operator/step-registry/ipi/aws/pre/edge-zones/opt-in/ipi-aws-pre-edge-zones-opt-in-ref.yaml
  ci-operator/step-registry/platform-external/cluster/aws/destroy/bootstrap/platform-external-cluster-aws-destroy-bootstrap-ref.yaml
  ci-operator/step-registry/platform-external/cluster/aws/destroy/platform-external-cluster-aws-destroy-ref.yaml
  ci-operator/step-registry/platform-external/cluster/aws/install/image/platform-external-cluster-aws-install-image-ref.yaml
  ci-operator/step-registry/platform-external/cluster/aws/install/platform-external-cluster-aws-install-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#68727 Use 4.21 images
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.21__images.yaml
Labels: lgtm, approved, rehearsals-ack

#68731 Point image latest tag to 4.21
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__images.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.21__images.yaml
Labels: lgtm, approved, rehearsals-ack

#68732 oadp azure secret to be available in ci-systems
  core-services/ci-secret-bootstrap/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#68608 Fix pprof logic
  ci-operator/step-registry/openshift-qe/cluster-density-v2/openshift-qe-cluster-density-v2-commands.sh
  ci-operator/step-registry/openshift-qe/crd-scale/openshift-qe-crd-scale-commands.sh
  ci-operator/step-registry/openshift-qe/crd-scale/openshift-qe-crd-scale-ref.yaml
  ci-operator/step-registry/openshift-qe/kube-burner-index/openshift-qe-kube-burner-index-commands.sh
  ci-operator/step-registry/openshift-qe/kube-burner-ingress-perf/openshift-qe-kube-burner-ingress-perf-ref.yaml
  ci-operator/step-registry/openshift-qe/netpol-v2/openshift-qe-netpol-v2-ref.yaml
  ci-operator/step-registry/openshift-qe/node-density-cni/openshift-qe-node-density-cni-commands.sh
  ci-operator/step-registry/openshift-qe/node-density-heavy/openshift-qe-node-density-heavy-commands.sh
  ci-operator/step-registry/openshift-qe/node-density/openshift-qe-node-density-commands.sh
  ci-operator/step-registry/openshift-qe/rds-core/openshift-qe-rds-core-commands.sh
  ci-operator/step-registry/openshift-qe/udn-density-pods/openshift-qe-udn-density-pods-commands.sh
  ci-operator/step-registry/openshift-qe/udn-density-pods/openshift-qe-udn-density-pods-ref.yaml
  ci-operator/step-registry/openshift-qe/virt-udn-density/openshift-qe-virt-udn-density-commands.sh
Labels: lgtm, approved, rehearsals-ack

#68597 [INTEROP-8438] Updating all ROSA HCP scenario configs to `ROSACLI_BUILD : latest`
  ci-operator/config/openshift-logging/extended-logging-tests-interop/openshift-logging-extended-logging-tests-interop-main__openshift-logging-hypershift-4.19-lp-rosa-hypershift.yaml
  ci-operator/config/openshift-pipelines/release-tests/openshift-pipelines-release-tests-release-v1.19__openshift-pipelines-ocp4.19-lp-rosa-hypershift.yaml
  ci-operator/config/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-release-4.19__ocp4.19-lp-rosa-hypershift.yaml
  ci-operator/config/redhat-developer/devspaces-interop-tests/redhat-developer-devspaces-interop-tests-main__devspaces-ocp4.19-lp-rosa-hypershift.yaml
  ci-operator/config/rhbk/sso-test/rhbk-sso-test-main__rhsso-product-ocp4.19-lp-rosa-hypershift.yaml
Labels: lgtm, approved, rehearsals-ack

#68696 Remove winc testing from 4.11-4.15 from Prow CI -2
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#68576 openshift-pr-mgr as trusted-app for payload plugin
  clusters/app.ci/prow/03_deployment/payload-testing-prow-plugin.yaml
Labels: lgtm, approved, rehearsals-ack

#68750 Adding istio jobs for release-1.27
  ci-operator/config/openshift-service-mesh/istio/openshift-service-mesh-istio-release-1.27.yaml
  ci-operator/jobs/openshift-service-mesh/istio/openshift-service-mesh-istio-release-1.27-postsubmits.yaml
  ci-operator/jobs/openshift-service-mesh/istio/openshift-service-mesh-istio-release-1.27-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#68719 SLCM remove the Gitlab API based job - no more useful
  ci-operator/config/openshift-kni/eco-ci-cd-private/openshift-kni-eco-ci-cd-private-main__slcm-4.12.yaml
  ci-operator/jobs/openshift-kni/eco-ci-cd-private/openshift-kni-eco-ci-cd-private-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#68437 Updating GCP custom-dns techpreview periodic job
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.19.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.20.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.21.yaml
Labels: lgtm, approved, rehearsals-ack

#68761 [release-controller] Bumping `oc` to `4.21`
  clusters/app.ci/release-controller/deploy-ocp-arm64-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-arm64-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-multi-2-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-multi-2-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-multi-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-multi-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-ppc64le-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-ppc64le-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-priv-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-s390x-controller.yaml
  clusters/app.ci/release-controller/deploy-ocp-s390x-priv-controller.yaml
  hack/generators/release-controllers/content/osd_rc_deployments.py
Labels: lgtm, approved, rehearsals-ack

#68766 NO-JIRA: cvo: remove no-qe/qe-approved merge criteria
  core-services/prow/02_config/openshift/cluster-version-operator/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#68769 lowercase flag
  ci-operator/step-registry/openshift-qe/node-density/openshift-qe-node-density-commands.sh
Labels: lgtm, approved, rehearsals-ack

#68768 Add test-infra jobs for 3.2 containers
  ci-operator/config/maistra/test-infra/maistra-test-infra-main.yaml
  ci-operator/jobs/maistra/test-infra/maistra-test-infra-main-postsubmits.yaml
  ci-operator/jobs/maistra/test-infra/maistra-test-infra-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#68718 Removing tests on 4.14 arm as the must-gather step is broken
  ci-operator/config/openshift-service-mesh/sail-operator/openshift-service-mesh-sail-operator-release-3.0__ocp-4.14.yaml
  ci-operator/jobs/openshift-service-mesh/sail-operator/openshift-service-mesh-sail-operator-release-3.0-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#64648 add ocm-sdk-go to prow
  ci-operator/config/openshift-online/ocm-sdk-go/OWNERS
  ci-operator/config/openshift-online/ocm-sdk-go/openshift-online-ocm-sdk-go-main.yaml
  ci-operator/jobs/openshift-online/ocm-sdk-go/OWNERS
  ci-operator/jobs/openshift-online/ocm-sdk-go/openshift-online-ocm-sdk-go-main-presubmits.yaml
  core-services/prow/02_config/openshift-online/ocm-sdk-go/OWNERS
  core-services/prow/02_config/openshift-online/ocm-sdk-go/_pluginconfig.yaml
  core-services/prow/02_config/openshift-online/ocm-sdk-go/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#68795 Updated branch protection rules for multicluster-role-assignment
  core-services/prow/02_config/stolostron/multicluster-role-assignment/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#68686 [art] validate if delivery repos exist in konflux-release-data
  OWNERS_ALIASES
  ci-operator/config/openshift-eng/ocp-build-data/OWNERS
  ci-operator/config/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.12.yaml
  ci-operator/config/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.13.yaml
  ci-operator/config/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.14.yaml
  ci-operator/config/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.15.yaml
  ci-operator/config/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.16.yaml
  ci-operator/config/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.17.yaml
  ci-operator/config/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.18.yaml
  ci-operator/config/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.19.yaml
  ci-operator/config/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.20.yaml
  ci-operator/config/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.21.yaml
  ci-operator/jobs/openshift-eng/ocp-build-data/OWNERS
  ci-operator/jobs/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.12-presubmits.yaml
  ci-operator/jobs/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.13-presubmits.yaml
  ci-operator/jobs/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.14-presubmits.yaml
  ci-operator/jobs/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.15-presubmits.yaml
  ci-operator/jobs/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.16-presubmits.yaml
  ci-operator/jobs/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.17-presubmits.yaml
  ci-operator/jobs/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.18-presubmits.yaml
  ci-operator/jobs/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.19-presubmits.yaml
  ci-operator/jobs/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.20-presubmits.yaml
  ci-operator/jobs/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.21-presubmits.yaml
  ci-operator/step-registry/ocp-art/OWNERS
  ci-operator/step-registry/ocp-art/ocp-art-workflow.metadata.json
  ci-operator/step-registry/ocp-art/ocp-art-workflow.yaml
  ci-operator/step-registry/ocp-art/validate/OWNERS
  ci-operator/step-registry/ocp-art/validate/delivery-repos/OWNERS
  ci-operator/step-registry/ocp-art/validate/delivery-repos/ocp-art-validate-delivery-repos-commands.sh
  ci-operator/step-registry/ocp-art/validate/delivery-repos/ocp-art-validate-delivery-repos-ref.metadata.json
  ci-operator/step-registry/ocp-art/validate/delivery-repos/ocp-art-validate-delivery-repos-ref.yaml
  ci-operator/step-registry/ocp-art/validate/ocp-art-validate-chain.metadata.json
  ci-operator/step-registry/ocp-art/validate/ocp-art-validate-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#68782 NO-JIRA: CVO: Disable `always_run` on the `e2e-agnostic-operator-devpreview` job
  ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-main.yaml
  ci-operator/jobs/openshift/cluster-version-operator/openshift-cluster-version-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#68789 CNF-19309: fix typo for approved label in ptp repos
  core-services/prow/02_config/openshift/linuxptp-daemon/_prowconfig.yaml
  core-services/prow/02_config/openshift/ptp-operator/_prowconfig.yaml
  core-services/prow/02_config/redhat-cne/cloud-event-proxy/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#68749 DPTP-4486: Add attribute version
  ci-operator/step-registry/send-results/to-reportportal/send-results-to-reportportal-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#68802 Using candidate channel to get 4.19.10 with a fix we need for cni
  ci-operator/config/openshift-service-mesh/istio/openshift-service-mesh-istio-release-1.27.yaml
Labels: lgtm, approved, rehearsals-ack

#68798 Revert qe labels requirement
  core-services/prow/02_config/openshift/cloud-provider-aws/_prowconfig.yaml
  core-services/prow/02_config/openshift/cloud-provider-azure/_prowconfig.yaml
  core-services/prow/02_config/openshift/cloud-provider-gcp/_prowconfig.yaml
  core-services/prow/02_config/openshift/cluster-api-provider-aws/_prowconfig.yaml
  core-services/prow/02_config/openshift/cluster-api-provider-azure/_prowconfig.yaml
  core-services/prow/02_config/openshift/cluster-api-provider-gcp/_prowconfig.yaml
  core-services/prow/02_config/openshift/cluster-api/_prowconfig.yaml
  core-services/prow/02_config/openshift/cluster-capi-operator/_prowconfig.yaml
  core-services/prow/02_config/openshift/cluster-cloud-controller-manager-operator/_prowconfig.yaml
  core-services/prow/02_config/openshift/cluster-control-plane-machine-set-operator/_prowconfig.yaml
  core-services/prow/02_config/openshift/cluster-machine-approver/_prowconfig.yaml
  core-services/prow/02_config/openshift/machine-api-operator/_prowconfig.yaml
  core-services/prow/02_config/openshift/machine-api-provider-aws/_prowconfig.yaml
  core-services/prow/02_config/openshift/machine-api-provider-azure/_prowconfig.yaml
  core-services/prow/02_config/openshift/machine-api-provider-gcp/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#68799 stackrox: increase max_concurrency for ocp-4-19-* to 6
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-postsubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#68762 Replace v14 on v19 in eclipse-che repositories
  ci-operator/config/eclipse-che/che-dashboard/eclipse-che-che-dashboard-main__v19.yaml
  ci-operator/config/eclipse-che/che-plugin-registry/eclipse-che-che-plugin-registry-main__v19.yaml
  ci-operator/config/eclipse-che/che-server/eclipse-che-che-server-main__v19.yaml
  ci-operator/jobs/eclipse-che/che-dashboard/eclipse-che-che-dashboard-main-presubmits.yaml
  ci-operator/jobs/eclipse-che/che-plugin-registry/eclipse-che-che-plugin-registry-main-presubmits.yaml
  ci-operator/jobs/eclipse-che/che-server/eclipse-che-che-server-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#68763 Add infrastructure secret collection
  core-services/sync-rover-groups/README.md
  core-services/sync-rover-groups/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#68776 setup assisted-installer version v2.45
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-v2.45.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-v2.45.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-v2.45.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-v2.45.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-v2.45-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-v2.45-presubmits.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-v2.45-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-v2.45-presubmits.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-v2.45-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-v2.45-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-v2.45-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-v2.45-presubmits.yaml
  core-services/prow/02_config/openshift/assisted-image-service/_prowconfig.yaml
  core-services/prow/02_config/openshift/assisted-installer-agent/_prowconfig.yaml
  core-services/prow/02_config/openshift/assisted-installer/_prowconfig.yaml
  core-services/prow/02_config/openshift/assisted-service/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#68808 remove the access-transparency-service repo from the openshift-priv whitelist
  core-services/openshift-priv/_whitelist.yaml
Labels: lgtm, approved, rehearsals-ack

#66930 [CSB] Update to version 4.10.6
  ci-operator/step-registry/csb/deploy-resources/csb-deploy-resources-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#68700 OADP: Do not use squash method for the repos with rebasebot
  core-services/prow/02_config/openshift/velero-plugin-for-aws/_prowconfig.yaml
  core-services/prow/02_config/openshift/velero-plugin-for-csi/_prowconfig.yaml
  core-services/prow/02_config/openshift/velero-plugin-for-legacy-aws/_prowconfig.yaml
  core-services/prow/02_config/openshift/velero-plugin-for-microsoft-azure/_prowconfig.yaml
  core-services/prow/02_config/openshift/velero/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#68814 CNF-19309: fix incorrect merge for ptp repo labels
  core-services/prow/02_config/openshift/linuxptp-daemon/_prowconfig.yaml
  core-services/prow/02_config/openshift/ptp-operator/_prowconfig.yaml
  core-services/prow/02_config/redhat-cne/cloud-event-proxy/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#68825 CNV-68108: Add new mirror image: hyperconverged-cluster-bundle:1.17.0-unstable
  clusters/app.ci/supplemental-ci-images/hyperconverged-cluster-bundle.yaml
  core-services/image-mirroring/_config.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#68753 add vsphere loaded upgrade 4.19 -> 4.20
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main_vsphere-4.20-nightly-x86-loaded-upgrade-from-4.19.yaml
  ci-operator/jobs/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main_vsphere-4.20-nightly-x86-loaded-upgrade-from-4.19-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#68835 switching rhoe cluster pools for 4.20 to m7i, since m8i isn't available
  clusters/hosted-mgmt/hive/pools/rh-openshift-ecosystem/install-config-4-20-amd64-aws-us-west-1_secret.yaml
  clusters/hosted-mgmt/hive/pools/rh-openshift-ecosystem/install-config-4-20-amd64-aws-us-west-2_secret.yaml
Labels: lgtm, approved, rehearsals-ack

#68837 Use the acs-perfscale channel
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/.config.prowgen
  ci-operator/config/stackrox/stackrox/.config.prowgen
  ci-operator/jobs/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main-periodics.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-nightlies-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#68817 Update Orion version
  ci-operator/step-registry/openshift-qe/orion/cluster-density/openshift-qe-orion-cluster-density-ref.yaml
  ci-operator/step-registry/openshift-qe/orion/crd-scale/openshift-qe-orion-crd-scale-ref.yaml
  ci-operator/step-registry/openshift-qe/orion/data-path/openshift-qe-orion-data-path-ref.yaml
  ci-operator/step-registry/openshift-qe/orion/node-density-cni/openshift-qe-orion-node-density-cni-ref.yaml
  ci-operator/step-registry/openshift-qe/orion/node-density/openshift-qe-orion-node-density-ref.yaml
  ci-operator/step-registry/openshift-qe/orion/virt-density/openshift-qe-orion-virt-density-ref.yaml
  ci-operator/step-registry/openshift-qe/orion/virt-udn-density/openshift-qe-orion-virt-udn-density-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#68667 feat: remove techpreview from tna agent installs
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.20.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.21.yaml
Labels: lgtm, approved, rehearsals-ack

#68779 adding openshift-preflight 4.20 job
  ci-operator/config/redhat-openshift-ecosystem/openshift-preflight/redhat-openshift-ecosystem-openshift-preflight-main__4.20.yaml
  ci-operator/jobs/redhat-openshift-ecosystem/openshift-preflight/redhat-openshift-ecosystem-openshift-preflight-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#68854 OCPBUGS-60839: Specify an InfraID for hypershift clusters created for conformance tests
  ci-operator/step-registry/hypershift/aws/create/hypershift-aws-create-chain.yaml
Labels: lgtm, approved, jira/valid-bug, rehearsals-ack, jira/valid-reference

#68864 Add one more hour to grace_period so that we have enought time for cleanup
  core-services/prow/02_config/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#68671 Regression test for aws ipsec test
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__aws-4.20-nightly-x86.yaml
  ci-operator/jobs/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#68793 CNTRLPLANE-945: cao: add 4.21 periodics for BYO OIDC feature
  ci-operator/config/openshift/cluster-authentication-operator/openshift-cluster-authentication-operator-release-4.21__periodics.yaml
  ci-operator/jobs/openshift/cluster-authentication-operator/openshift-cluster-authentication-operator-release-4.21-periodics.yaml
  ci-operator/jobs/openshift/cluster-authentication-operator/openshift-cluster-authentication-operator-release-4.21-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-authentication-operator/openshift-cluster-authentication-operator-release-4.21-presubmits.yaml
  ci-operator/step-registry/baremetalds/e2e/test/baremetalds-e2e-test-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#68871 Do not apply verified label to openshift/bpfman-operator
  core-services/verified/opt-out.yaml
Labels: lgtm, approved, rehearsals-ack

#68861 CNV-68108: Bump HCO to 1.17
  ci-operator/config/kubevirt/hyperconverged-cluster-operator/kubevirt-hyperconverged-cluster-operator-main.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#68881 Do not apply verified label to openshift/bpfman
  core-services/verified/opt-out.yaml
Labels: lgtm, approved, rehearsals-ack

#68713 OADP: Add aws-sno workflow
  ci-operator/config/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-main__oadp1.5-ocp4.19-aws-testing.yaml
  ci-operator/jobs/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-main-periodics.yaml
  ci-operator/step-registry/oadp/debug-wait/OWNERS
  ci-operator/step-registry/oadp/debug-wait/oadp-debug-wait-commands.sh
  ci-operator/step-registry/oadp/debug-wait/oadp-debug-wait-ref.metadata.json
  ci-operator/step-registry/oadp/debug-wait/oadp-debug-wait-ref.yaml
  ci-operator/step-registry/oadp/ipi/aws-sno-oadp-qe/OWNERS
  ci-operator/step-registry/oadp/ipi/aws-sno-oadp-qe/oadp-ipi-aws-sno-oadp-qe-workflow.metadata.json
  ci-operator/step-registry/oadp/ipi/aws-sno-oadp-qe/oadp-ipi-aws-sno-oadp-qe-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#68815 Set mapi vSphere vm-host zonal fs to tp
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-main.yaml
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-release-4.20.yaml
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-release-4.21.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-release-4.20-presubmits.yaml
  ci-operator/jobs/openshift/machine-api-operator/openshift-machine-api-operator-release-4.21-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#68811 add custom credencials to codeready-toolchain-toolchain-e2e-master.yaml
  ci-operator/config/codeready-toolchain/toolchain-e2e/codeready-toolchain-toolchain-e2e-master.yaml
Labels: lgtm, approved, rehearsals-ack

#68897 hypershift: skip tests on .gitignore changes
  ci-operator/config/openshift/hypershift/openshift-hypershift-main.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.20.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.21.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-main-presubmits.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.20-presubmits.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.21-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#68806 MGMT-21324: adding presubmit evaluation tests to assisted-service-mcp.
  ci-operator/config/openshift-assisted/assisted-service-mcp/openshift-assisted-assisted-service-mcp-master.yaml
  ci-operator/config/rh-ecosystem-edge/assisted-chat/rh-ecosystem-edge-assisted-chat-main.yaml
  ci-operator/jobs/openshift-assisted/assisted-service-mcp/openshift-assisted-assisted-service-mcp-master-presubmits.yaml
  ci-operator/step-registry/rh-ecosystem-edge/assisted-chat/test/rh-ecosystem-edge-assisted-chat-test-commands.sh
  ci-operator/step-registry/rh-ecosystem-edge/assisted-mcp/install/rh-ecosystem-edge-assisted-mcp-install-commands.sh
  ci-operator/step-registry/rh-ecosystem-edge/assisted-mcp/install/rh-ecosystem-edge-assisted-mcp-install-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#68892 openshift-logging: Replace Loki 3.5.3 by 3.5.4
  ci-operator/config/openshift/loki/openshift-loki-upstream-v3.5.4.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-upstream-v3.5.4-postsubmits.yaml
  ci-operator/jobs/openshift/loki/openshift-loki-upstream-v3.5.4-presubmits.yaml
  core-services/image-mirroring/openshift-logging/mapping_logging_loki_quay
Labels: lgtm, approved, rehearsals-ack

#68765 NO-JIRA: Make `verified` label green and add description
  core-services/prow/02_config/_labels.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#68887 SPLAT-2465: Added config for LB cpu and memory
  ci-operator/step-registry/upi/conf/vsphere/vcm/upi-conf-vsphere-vcm-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#68901 ccapio: updates CI jobs
  ci-operator/config/openshift/cluster-capi-operator/openshift-cluster-capi-operator-main.yaml
  ci-operator/jobs/openshift/cluster-capi-operator/openshift-cluster-capi-operator-main-presubmits.yaml
  core-services/pipeline-controller/config.yaml
  core-services/prow/02_config/openshift/cluster-capi-operator/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#68819 WINC-1454: WMCO branching 4.21
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-master.yaml
  ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.20.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#68916 installer: remove terraform jobs where not needed
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.19-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.20-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.21-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#68919 Modify Cluter Profile permission.
  ci-operator/step-registry/cluster-profiles/cluster-profiles-config.yaml
Labels: lgtm, approved, rehearsals-ack

#68853 Set kubeadmin password for console tests
  ci-operator/step-registry/openshift-extended/web-tests/openshift-extended-web-tests-commands.sh
  ci-operator/step-registry/openshift-extended/web-tests/openshift-extended-web-tests-ref.yaml
  ci-operator/step-registry/openshift/e2e/test/netobserv-qe/openshift-e2e-test-netobserv-qe-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#68905 remove verify label req where it doesn't make sense
  core-services/prow/02_config/operator-framework/operator-lifecycle-manager/_prowconfig.yaml
  core-services/prow/02_config/operator-framework/operator-registry/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#68704 Update golang version for openshift-managed-cluster-validating-webhooks
  ci-operator/config/openshift/managed-cluster-validating-webhooks/openshift-managed-cluster-validating-webhooks-master.yaml
Labels: lgtm, approved, rehearsals-ack

#68525 Improve user-metadata logic
  ci-operator/config/openshift-power-monitoring/kepler/openshift-power-monitoring-kepler-main__ocp4.18-perfscale.yaml
  ci-operator/config/openshift-power-monitoring/power-monitoring-operator/openshift-power-monitoring-power-monitoring-operator-v1alpha1__ocp4.18-perfscale.yaml
  ci-operator/step-registry/openshift-qe/cluster-density-v2/openshift-qe-cluster-density-v2-commands.sh
  ci-operator/step-registry/openshift-qe/cluster-density-v2/openshift-qe-cluster-density-v2-ref.yaml
  ci-operator/step-registry/openshift-qe/node-density-heavy/openshift-qe-node-density-heavy-commands.sh
  ci-operator/step-registry/openshift-qe/node-density-heavy/openshift-qe-node-density-heavy-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#65064 add ipsec udn loaded-upgrade jobs
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__aws-ipsec-4.19-nightly-x86-loaded-upgrade-from-4.18.yaml
  ci-operator/jobs/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main-presubmits.yaml
  ci-operator/step-registry/openshift-qe/udn-density-pods/openshift-qe-udn-density-pods-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#68885 Adjust the order of steps
  ci-operator/step-registry/openshift/e2e/test/clusterinfra-qe/regression/openshift-e2e-test-clusterinfra-qe-regression-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#68930 [crc-org/llama.cpp] Finalize the TOPSAIL testing launcher
  ci-operator/config/crc-org/llama.cpp/crc-org-llama.cpp-main.yaml
Labels: lgtm, approved, rehearsals-ack

#68939 Add benluddy to the openshift/kubernetes labelers list.
  core-services/prow/02_config/openshift/kubernetes/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#68896 configure the ocp-ci on the repo odh/odh-ide-extensions
  core-services/prow/02_config/opendatahub-io/odh-ide-extensions/_pluginconfig.yaml
  core-services/prow/02_config/opendatahub-io/odh-ide-extensions/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#68945 kueue-operator: remove 4.17 ci lane
  ci-operator/config/openshift/kueue-operator/openshift-kueue-operator-main.yaml
  ci-operator/jobs/openshift/kueue-operator/openshift-kueue-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#68918 Add arm64 cluster-pools
  clusters/hosted-mgmt/hive/pools/ocp-release-4.18.23-arm64-for-4.18.0-0-to-4.19.0-0_clusterimageset.yaml
  clusters/hosted-mgmt/hive/pools/ocp-release-4.19.10-arm64-for-4.19.0-0-to-4.20.0-0_clusterimageset.yaml
  clusters/hosted-mgmt/hive/pools/openshift-ci/ci-ocp-4-18-0-arm64-aws-us-east-1_clusterpool.yaml
  clusters/hosted-mgmt/hive/pools/openshift-ci/ci-ocp-4-19-0-arm64-aws-us-east-1_clusterpool.yaml
  clusters/hosted-mgmt/hive/pools/openshift-ci/install-config-aws-arm64-us-east-1_secret.yaml
Labels: lgtm, approved, rehearsals-ack

#68942 Add OSSM proxy jobs for 3.2
  ci-operator/config/openshift-service-mesh/proxy/openshift-service-mesh-proxy-release-1.27.yaml
  ci-operator/jobs/openshift-service-mesh/proxy/openshift-service-mesh-proxy-release-1.27-postsubmits.yaml
  ci-operator/jobs/openshift-service-mesh/proxy/openshift-service-mesh-proxy-release-1.27-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#68110 Add e2e for kueue on hypershift
  ci-operator/config/openshift/kueue-operator/openshift-kueue-operator-main.yaml
  ci-operator/config/openshift/kueue-operator/openshift-kueue-operator-release-1.0.yaml
  ci-operator/jobs/openshift/kueue-operator/openshift-kueue-operator-main-periodics.yaml
  ci-operator/jobs/openshift/kueue-operator/openshift-kueue-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/kueue-operator/openshift-kueue-operator-release-1.0-periodics.yaml
  ci-operator/jobs/openshift/kueue-operator/openshift-kueue-operator-release-1.0-presubmits.yaml
  ci-operator/step-registry/kueue-operator/dev-bundle/OWNERS
  ci-operator/step-registry/kueue-operator/dev-bundle/kueue-operator-dev-bundle-commands.sh
  ci-operator/step-registry/kueue-operator/dev-bundle/kueue-operator-dev-bundle-ref.metadata.json
  ci-operator/step-registry/kueue-operator/dev-bundle/kueue-operator-dev-bundle-ref.yaml
  ci-operator/step-registry/kueue-operator/dev-bundle/kueue-operator-dev-bundle.metadata.json
  ci-operator/step-registry/kueue-operator/test/e2e-dev-bundle/OWNERS
  ci-operator/step-registry/kueue-operator/test/e2e-dev-bundle/kueue-operator-test-e2e-dev-bundle-chain.metadata.json
  ci-operator/step-registry/kueue-operator/test/e2e-dev-bundle/kueue-operator-test-e2e-dev-bundle-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#68952 ART-14080: whitelist oadp-operator
  core-services/openshift-priv/_whitelist.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#68917 Bump orion version to v0.1.2
  ci-operator/step-registry/openshift-qe/orion/cluster-density/openshift-qe-orion-cluster-density-ref.yaml
  ci-operator/step-registry/openshift-qe/orion/crd-scale/openshift-qe-orion-crd-scale-ref.yaml
  ci-operator/step-registry/openshift-qe/orion/data-path/openshift-qe-orion-data-path-ref.yaml
  ci-operator/step-registry/openshift-qe/orion/node-density-cni/openshift-qe-orion-node-density-cni-ref.yaml
  ci-operator/step-registry/openshift-qe/orion/node-density/openshift-qe-orion-node-density-ref.yaml
  ci-operator/step-registry/openshift-qe/orion/openshift-qe-orion-commands.sh
  ci-operator/step-registry/openshift-qe/orion/virt-density/openshift-qe-orion-virt-density-ref.yaml
  ci-operator/step-registry/openshift-qe/orion/virt-udn-density/openshift-qe-orion-virt-udn-density-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#68940 Tmp disabling failing tests in istio release-1.27
  ci-operator/config/openshift-service-mesh/istio/openshift-service-mesh-istio-release-1.27.yaml
Labels: lgtm, approved, rehearsals-ack

#68757 KCCM: update OCP and adjacent operators versions
  ci-operator/config/openshift/cloud-provider-kubevirt/openshift-cloud-provider-kubevirt-main.yaml
  ci-operator/config/openshift/cloud-provider-kubevirt/openshift-cloud-provider-kubevirt-release-4.15.yaml
  ci-operator/config/openshift/cloud-provider-kubevirt/openshift-cloud-provider-kubevirt-release-4.16.yaml
  ci-operator/config/openshift/cloud-provider-kubevirt/openshift-cloud-provider-kubevirt-release-4.17.yaml
  ci-operator/config/openshift/cloud-provider-kubevirt/openshift-cloud-provider-kubevirt-release-4.18.yaml
  ci-operator/config/openshift/cloud-provider-kubevirt/openshift-cloud-provider-kubevirt-release-4.19.yaml
  ci-operator/config/openshift/cloud-provider-kubevirt/openshift-cloud-provider-kubevirt-release-4.20.yaml
  ci-operator/config/openshift/cloud-provider-kubevirt/openshift-cloud-provider-kubevirt-release-4.21.yaml
  ci-operator/step-registry/hypershift/kubevirt/baremetalds/conformance/hypershift-kubevirt-baremetalds-conformance-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#68957 cert-manager: add retry for getting the packagemanifest
  ci-operator/step-registry/cert-manager/install/operator/cert-manager-install-operator-commands.sh
Labels: lgtm, approved, rehearsals-ack

#68895 Exclude open-cluster-management-agent-addon pods from health checks
  ci-operator/step-registry/cucushift/hypershift-extended/health-check/cucushift-hypershift-extended-health-check-commands.sh
Labels: lgtm, approved, rehearsals-ack

#68886 [test] add IBM 4.20 control plane & node-density-heavy test
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__ibmcloud-4.20-nightly-x86.yaml
  ci-operator/jobs/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#68047 Remove interfaces vars from openshift-qe-installer-bm-deploy-commands.sh
  ci-operator/config/redhat-performance/jetlag/redhat-performance-jetlag-main.yaml
  ci-operator/jobs/redhat-performance/jetlag/redhat-performance-jetlag-main-presubmits.yaml
  ci-operator/step-registry/openshift-qe/cluster-health/openshift-qe-cluster-health-commands.sh
  ci-operator/step-registry/openshift-qe/installer/bm/deploy/openshift-qe-installer-bm-deploy-commands.sh
Labels: lgtm, approved, rehearsals-ack, network-access-rehearsals-ok

#68471 oadp-qe: add Azure testing 1.5 and ocp 4.19 config
  ci-operator/config/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-main__oadp1.5-ocp4.19-azure-testing.yaml
  ci-operator/jobs/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-main-periodics.yaml
  ci-operator/jobs/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#68884 USHIFT-6042: Bump build_root image for main branch
  ci-operator/config/openshift/microshift/openshift-microshift-main.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#68891 USHIFT-6043: Move 4.20 periodics to its own file
  ci-operator/config/openshift/microshift/openshift-microshift-release-4.20.yaml
  ci-operator/config/openshift/microshift/openshift-microshift-release-4.20__periodics.yaml
  ci-operator/jobs/openshift/microshift/openshift-microshift-release-4.20-periodics.yaml
  ci-operator/jobs/openshift/microshift/openshift-microshift-release-4.20-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#68937 Remove verified labels from bpfman repositories
  core-services/prow/02_config/openshift/bpfman-operator/_prowconfig.yaml
  core-services/prow/02_config/openshift/bpfman/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#68966 Disable OSSM failed tests to unblock the sync flow
  ci-operator/config/openshift-service-mesh/istio/openshift-service-mesh-istio-master.yaml
Labels: lgtm, approved, rehearsals-ack

#69007 OCP 4.20 Post Branching: Configure Jira Validation Criteria
  core-services/jira-lifecycle-plugin/config.yaml
Labels: lgtm, approved, rehearsals-ack

#69009 OCP 4.20 Post Branching: Configure Merge Blockers
  ci-operator/jobs/infra-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#68188 update ODF version from 4.20 to 4.19
  ci-operator/config/stolostron/policy-collection/stolostron-policy-collection-main__ocp4.19.yaml
  ci-operator/config/stolostron/policy-collection/stolostron-policy-collection-main__ocp4.20.yaml
Labels: lgtm, approved, rehearsals-ack

#68880 Remove --public-only from mce jobs below 4.19
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-nightly.yaml
  ci-operator/step-registry/hypershift/mce/aws/create/hypershift-mce-aws-create-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#69033 Stage.quay.io add new dedicated pushing images validation testing
  ci-operator/step-registry/quay-tests/stagequayio/quay-tests-stagequayio-commands.sh
  ci-operator/step-registry/quay-tests/stagequayio/quay-tests-stagequayio-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#69040 telcov10n: change hcp cnf jobs crons and remove 4.20 job
  ci-operator/config/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main__hcp-cnf-4.18.yaml
  ci-operator/config/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main__hcp-cnf-4.19.yaml
  ci-operator/config/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main__hcp-cnf-nrop-4.19.yaml
  ci-operator/config/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main__hcp-cnf-nrop-4.20.yaml
  ci-operator/jobs/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#68809 Adding lint, gencheck and unit test for istio master branch
  ci-operator/config/openshift-service-mesh/istio/openshift-service-mesh-istio-master.yaml
  ci-operator/jobs/openshift-service-mesh/istio/openshift-service-mesh-istio-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#68520 CCXDEV-15390: Add insights-runtime-extractor and on-demand-gathering test on bare metal
  ci-operator/config/openshift/insights-operator/openshift-insights-operator-release-4.20__periodics.yaml
  ci-operator/jobs/openshift/insights-operator/openshift-insights-operator-release-4.20-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#69042 disable build01 due to etcd issues
  core-services/sanitize-prow-jobs/_clusters.yaml
Labels: lgtm, approved, rehearsals-ack

#69050 allow ci-operator service account to get/list the cluster version config
  clusters/build-clusters/common/ci-operator/admin_ci-operator_rbac.yaml
Labels: lgtm, approved, rehearsals-ack

#69048 Adding logging 6.4 build
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-logging-docs-6.4.yaml
  ci-operator/jobs/openshift/openshift-docs/openshift-openshift-docs-logging-docs-6.4-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#68964 Onboard kubevirt-velero-plugin project.
  ci-operator/config/migtools/kubevirt-velero-plugin/OWNERS
  ci-operator/config/migtools/kubevirt-velero-plugin/migtools-kubevirt-velero-plugin-main.yaml
  ci-operator/jobs/migtools/kubevirt-velero-plugin/OWNERS
  ci-operator/jobs/migtools/kubevirt-velero-plugin/migtools-kubevirt-velero-plugin-main-postsubmits.yaml
  ci-operator/jobs/migtools/kubevirt-velero-plugin/migtools-kubevirt-velero-plugin-main-presubmits.yaml
  core-services/image-mirroring/konveyor/mapping_konveyor_latest
  core-services/prow/02_config/migtools/kubevirt-velero-plugin/OWNERS
  core-services/prow/02_config/migtools/kubevirt-velero-plugin/_pluginconfig.yaml
  core-services/prow/02_config/migtools/kubevirt-velero-plugin/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#69017 Added openshift-assisted/assisted-installer-ui
  core-services/openshift-priv/_whitelist.yaml
Labels: lgtm, approved, rehearsals-ack

#69083 ocp-build-data set as optional
  ci-operator/config/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.12.yaml
  ci-operator/config/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.13.yaml
  ci-operator/config/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.14.yaml
  ci-operator/config/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.15.yaml
  ci-operator/config/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.16.yaml
  ci-operator/config/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.17.yaml
  ci-operator/config/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.18.yaml
  ci-operator/config/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.19.yaml
  ci-operator/config/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.20.yaml
  ci-operator/config/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.21.yaml
  ci-operator/jobs/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.12-presubmits.yaml
  ci-operator/jobs/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.13-presubmits.yaml
  ci-operator/jobs/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.14-presubmits.yaml
  ci-operator/jobs/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.15-presubmits.yaml
  ci-operator/jobs/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.16-presubmits.yaml
  ci-operator/jobs/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.17-presubmits.yaml
  ci-operator/jobs/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.18-presubmits.yaml
  ci-operator/jobs/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.19-presubmits.yaml
  ci-operator/jobs/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.20-presubmits.yaml
  ci-operator/jobs/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.21-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#68987 update 421, 420 jobs to use kube:admin IDP temp
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.21__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.21__multi-nightly.yaml
Labels: lgtm, approved, rehearsals-ack

#69032 AUTH-574: Add OCP external oidc CI for multi-arch matrix
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.21__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/tools/generate-cron-entry.sh
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.21-periodics.yaml
  ci-operator/step-registry/idp/external-oidc/idp-external-oidc-commands.sh
  ci-operator/step-registry/idp/external-oidc/keycloak/server/idp-external-oidc-keycloak-server-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#69069 Update README.md
  core-services/openshift-priv/README.md
Labels: lgtm, approved, rehearsals-ack

#69092 openshift-appliance: change merge_method to squash
  core-services/prow/02_config/openshift/appliance/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#69108 grant aro-hcp-prow-ci group service account token access
  clusters/app.ci/gangway-tokens/aro-hcp-prow-ci/admin_rbac.yaml
  clusters/app.ci/prow/03_deployment/gangway.yaml
Labels: lgtm, approved, rehearsals-ack

#69110 MPIIT: Update Jira project for reporting failures
  ci-operator/config/RedHatQE/interop-testing/RedHatQE-interop-testing-master__cnv-odf-ocp-4.20-lp-interop.yaml
Labels: lgtm, approved, rehearsals-ack

#69097 [RHACS] [Docs] ROX-30831: Adding Prow CI for rhacs-docs-4.9 branch
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-rhacs-docs-4.9.yaml
  ci-operator/jobs/openshift/openshift-docs/openshift-openshift-docs-rhacs-docs-4.9-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#69113 CNTRLPLANE-1399: Move HyperShift AKS e2e to centralus instead of eastus2
  ci-operator/config/openshift/hypershift/openshift-hypershift-main.yaml
  ci-operator/step-registry/aks/provision/aks-provision-ref.yaml
  ci-operator/step-registry/hypershift/azure/aks/e2e/hypershift-azure-aks-e2e-workflow.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#68074 winc: use owner aliases in Nutanix steps
  ci-operator/step-registry/ipi/conf/nutanix/windows-machineset/OWNERS
  ci-operator/step-registry/ipi/conf/nutanix/windows-machineset/ipi-conf-nutanix-windows-machineset-ref.metadata.json
Labels: lgtm, approved, rehearsals-ack

#69124 Revert "ocp-build-data set as optional"
  ci-operator/config/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.12.yaml
  ci-operator/config/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.13.yaml
  ci-operator/config/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.14.yaml
  ci-operator/config/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.15.yaml
  ci-operator/config/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.16.yaml
  ci-operator/config/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.17.yaml
  ci-operator/config/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.18.yaml
  ci-operator/config/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.19.yaml
  ci-operator/config/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.20.yaml
  ci-operator/config/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.21.yaml
  ci-operator/jobs/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.12-presubmits.yaml
  ci-operator/jobs/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.13-presubmits.yaml
  ci-operator/jobs/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.14-presubmits.yaml
  ci-operator/jobs/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.15-presubmits.yaml
  ci-operator/jobs/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.16-presubmits.yaml
  ci-operator/jobs/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.17-presubmits.yaml
  ci-operator/jobs/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.18-presubmits.yaml
  ci-operator/jobs/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.19-presubmits.yaml
  ci-operator/jobs/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.20-presubmits.yaml
  ci-operator/jobs/openshift-eng/ocp-build-data/openshift-eng-ocp-build-data-openshift-4.21-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#67863 OCPBUGS-53196: rename 'master' to 'main' for network-tools
  ci-operator/config/openshift-priv/network-tools/openshift-priv-network-tools-main.yaml
  ci-operator/config/openshift/network-tools/openshift-network-tools-main.yaml
  ci-operator/config/openshift/network-tools/openshift-network-tools-main__okd-scos.yaml
  ci-operator/jobs/openshift-priv/network-tools/openshift-priv-network-tools-main-postsubmits.yaml
  ci-operator/jobs/openshift-priv/network-tools/openshift-priv-network-tools-main-presubmits.yaml
  ci-operator/jobs/openshift/network-tools/openshift-network-tools-main-postsubmits.yaml
  ci-operator/jobs/openshift/network-tools/openshift-network-tools-main-presubmits.yaml
Labels: lgtm, approved, jira/valid-bug, rehearsals-ack, jira/valid-reference

#69132 Increase large scale cadence
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__aws-4.20-nightly-x86.yaml
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__aws-4.21-nightly-x86.yaml
  ci-operator/jobs/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#69238 Remove 4.22 jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.22__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.22__arm64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.22__images.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.22__multi-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.22-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.22-postsubmits.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.22-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#69201 RHIDP-8793: Change SCALE_REPLICAS to separate SCALE_RHDH_REPLICAS and SCALE_RHDH_DB_REPLICAS
  ci-operator/config/redhat-performance/backstage-performance/redhat-performance-backstage-performance-main.yaml
  ci-operator/step-registry/redhat-performance/backstage-performance/scalability/redhat-performance-backstage-performance-scalability-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#69250 Remove 4.22 periodic jobs
  ci-operator/config/openshift-priv/cluster-authentication-operator/openshift-priv-cluster-authentication-operator-release-4.22__periodics.yaml
  ci-operator/config/openshift/aws-karpenter-provider-aws/openshift-aws-karpenter-provider-aws-release-4.22__periodics.yaml
  ci-operator/config/openshift/cluster-authentication-operator/openshift-cluster-authentication-operator-release-4.22__periodics.yaml
  ci-operator/config/openshift/cluster-control-plane-machine-set-operator/openshift-cluster-control-plane-machine-set-operator-release-4.22__periodics.yaml
  ci-operator/config/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.22__periodics.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.22__periodics.yaml
  ci-operator/config/openshift/microshift/openshift-microshift-release-4.22__periodics.yaml
  ci-operator/jobs/openshift-priv/cluster-authentication-operator/openshift-priv-cluster-authentication-operator-release-4.22-postsubmits.yaml
  ci-operator/jobs/openshift-priv/cluster-authentication-operator/openshift-priv-cluster-authentication-operator-release-4.22-presubmits.yaml
  ci-operator/jobs/openshift/aws-karpenter-provider-aws/openshift-aws-karpenter-provider-aws-release-4.22-periodics.yaml
  ci-operator/jobs/openshift/cluster-authentication-operator/openshift-cluster-authentication-operator-release-4.22-periodics.yaml
  ci-operator/jobs/openshift/cluster-authentication-operator/openshift-cluster-authentication-operator-release-4.22-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-authentication-operator/openshift-cluster-authentication-operator-release-4.22-presubmits.yaml
  ci-operator/jobs/openshift/cluster-control-plane-machine-set-operator/openshift-cluster-control-plane-machine-set-operator-release-4.22-periodics.yaml
  ci-operator/jobs/openshift/cluster-control-plane-machine-set-operator/openshift-cluster-control-plane-machine-set-operator-release-4.22-presubmits.yaml
  ci-operator/jobs/openshift/cluster-storage-operator/openshift-cluster-storage-operator-release-4.22-periodics.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.22-periodics.yaml
  ci-operator/jobs/openshift/microshift/openshift-microshift-release-4.22-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#69256 Adds cluster-capi-operator LGTM pipeline gate
  core-services/pipeline-controller/config.yaml
  core-services/pipeline-controller/lgtm-config.yaml
Labels: lgtm, approved, rehearsals-ack

#69260 CNTRLPLANE-1277: feat: enable KMS by default for Azure HyperShift e2e tests
  ci-operator/step-registry/hypershift/azure/run-e2e/hypershift-azure-run-e2e-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#69265 Fix CHECK_RELEASE in ironic/ironic-agent images 4.20
  ci-operator/config/openshift/ironic-agent-image/openshift-ironic-agent-image-release-4.20.yaml
  ci-operator/config/openshift/ironic-image/openshift-ironic-image-release-4.20.yaml
Labels: lgtm, approved, rehearsals-ack

#68872 Add job for OSC 1.10.z
  ci-operator/config/openshift/sandboxed-containers-operator/openshift-sandboxed-containers-operator-osc-release-v1.10.yaml
  ci-operator/jobs/openshift/sandboxed-containers-operator/openshift-sandboxed-containers-operator-osc-release-v1.10-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#69067 LOG-7685: Use Go 1.24 to build Loki Operator 6.3
  ci-operator/config/openshift/loki/openshift-loki-release-6.3.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#69274 USHIFT-6032: Disable MicroShift 4.15 CI jobs
  ci-operator/config/openshift/microshift/openshift-microshift-release-4.15.yaml
  ci-operator/jobs/openshift/microshift/openshift-microshift-release-4.15-periodics.yaml
  ci-operator/jobs/openshift/microshift/openshift-microshift-release-4.15-postsubmits.yaml
  ci-operator/jobs/openshift/microshift/openshift-microshift-release-4.15-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#68148 winc: use owner aliases in Windows steps
  ci-operator/step-registry/openshift/windows/OWNERS
  ci-operator/step-registry/openshift/windows/install-wmco/OWNERS
  ci-operator/step-registry/openshift/windows/install-wmco/openshift-windows-install-wmco-ref.metadata.json
  ci-operator/step-registry/openshift/windows/setup-wmco-konflux/OWNERS
  ci-operator/step-registry/openshift/windows/setup-wmco-konflux/openshift-windows-setup-wmco-konflux-ref.metadata.json
  ci-operator/step-registry/openshift/windows/winc-workflow/OWNERS
  ci-operator/step-registry/openshift/windows/winc-workflow/openshift-windows-winc-workflow-chain.metadata.json
  ci-operator/step-registry/windows/OWNERS
  ci-operator/step-registry/windows/ci/fastforward/windows-ci-fastforward-ref.metadata.json
  ci-operator/step-registry/windows/ci/fastforward/windows-ci-fastforward-workflow.metadata.json
  ci-operator/step-registry/windows/conf/operator/windows-conf-operator-ref.metadata.json
  ci-operator/step-registry/windows/e2e/operator/test/byoh/windows-e2e-operator-test-byoh-ref.metadata.json
  ci-operator/step-registry/windows/e2e/operator/test/mirror-images/OWNERS
  ci-operator/step-registry/windows/e2e/operator/test/mirror-images/windows-e2e-operator-test-mirror-images-ref.metadata.json
  ci-operator/step-registry/windows/e2e/operator/test/platform-none-vsphere/post/windows-e2e-operator-test-platform-none-vsphere-post-chain.metadata.json
  ci-operator/step-registry/windows/e2e/operator/test/platform-none-vsphere/pre/windows-e2e-operator-test-platform-none-vsphere-pre-chain.metadata.json
  ci-operator/step-registry/windows/e2e/operator/test/platform-none-vsphere/windows-e2e-operator-test-platform-none-vsphere-workflow.metadata.json
  ci-operator/step-registry/windows/e2e/operator/test/vsphere-disconnected/post/windows-e2e-operator-test-vsphere-disconnected-post-chain.metadata.json
  ci-operator/step-registry/windows/e2e/operator/test/vsphere-disconnected/pre/windows-e2e-operator-test-vsphere-disconnected-pre-chain.metadata.json
  ci-operator/step-registry/windows/e2e/operator/test/vsphere-disconnected/windows-e2e-operator-test-vsphere-disconnected-workflow.metadata.json
  ci-operator/step-registry/windows/e2e/operator/test/windows-e2e-operator-test-ref.metadata.json
  ci-operator/step-registry/windows/e2e/playbook/test/windows-e2e-playbook-test-ref.metadata.json
  ci-operator/step-registry/windows/unit/wicd/windows-unit-wicd-ref.metadata.json
Labels: lgtm, approved, rehearsals-ack

#69100 telco5g: Prepare deployments and tests for 4.21
  ci-operator/step-registry/telco5g/cnf/tests/telco5g-cnf-tests-commands.sh
  ci-operator/step-registry/telco5g/origin/tests/telco5g-origin-tests-commands.sh
Labels: lgtm, approved, rehearsals-ack

#69227 CNTRLPLANE-267: fix(hypershift): Enable manual jobs in branch protection
  ci-operator/config/openshift/hypershift/openshift-hypershift-main.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-main-presubmits.yaml
  core-services/prow/02_config/openshift/hypershift/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#69293 DPTP-4486: Exclude empty files
  ci-operator/step-registry/send-results/to-reportportal/send-results-to-reportportal-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#69301 Bump the resources for Tracing UI jobs
  ci-operator/config/openshift/distributed-tracing-console-plugin/openshift-distributed-tracing-console-plugin-main__upstream-amd64-aws.yaml
  ci-operator/config/openshift/distributed-tracing-console-plugin/openshift-distributed-tracing-console-plugin-release-0.3__upstream-amd64-aws.yaml
  ci-operator/config/openshift/distributed-tracing-console-plugin/openshift-distributed-tracing-console-plugin-release-0.4__upstream-amd64-aws.yaml
  ci-operator/config/openshift/distributed-tracing-console-plugin/openshift-distributed-tracing-console-plugin-release-1.0__upstream-amd64-aws.yaml
Labels: lgtm, approved, rehearsals-ack

#69300 keel deployments: add imagePullPolicy always
  clusters/app.ci/assets/admin_ci-images-mirror.yaml
  clusters/app.ci/assets/admin_qci-appci.yaml
  clusters/app.ci/assets/bugzilla-backporter.yaml
  clusters/app.ci/assets/docs.yaml
  clusters/app.ci/assets/dptp-controller-manager.yaml
  clusters/app.ci/assets/slack-bot.yaml
  clusters/app.ci/backport-verifier/deployment.yaml
  clusters/app.ci/ci-chat-bot/ci-chat-bot.yaml
  clusters/app.ci/ci-operator-configresolver/ci-operator-configresolver.yaml
  clusters/app.ci/ephemeral-cluster/10_deployment.yaml
  clusters/app.ci/jira-lifecycle-plugin/deployment.yaml
  clusters/app.ci/job-trigger-controller-manager/job-trigger-controller-manager_deploy.yaml
  clusters/app.ci/payload-testing-ui/payload-testing-ui.yaml
  clusters/app.ci/pod-scaler/pod-scaler-admission.yaml
  clusters/app.ci/pod-scaler/pod-scaler-ui.yaml
  clusters/app.ci/pod-scaler/pod-scaler.yaml
  clusters/app.ci/prow/03_deployment/payload-testing-prow-plugin.yaml
  clusters/app.ci/prow/03_deployment/publicize.yaml
  clusters/app.ci/prow/03_deployment/retester.yaml
  clusters/app.ci/repo-init/repo-init-apiserver.yaml
  clusters/app.ci/repo-init/repo-init-ui.yaml
  clusters/app.ci/result-aggregator/result-aggregator.yaml
  clusters/app.ci/vault/manifests.yaml
  clusters/app.ci/vault/secret-collection-manager.yaml
Labels: lgtm, approved, rehearsals-ack

#69303 cri-o/credential-provider: add prow config
  core-services/prow/02_config/cri-o/credential-provider/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#69306 Block build09
  core-services/sanitize-prow-jobs/_clusters.yaml
Labels: lgtm, approved, rehearsals-ack

#69281 no-jira: kube-scheduler-operator: increase e2e-aws-ovn-serial timeout to 5h
  ci-operator/config/openshift/cluster-kube-scheduler-operator/openshift-cluster-kube-scheduler-operator-master.yaml
  ci-operator/jobs/openshift/cluster-kube-scheduler-operator/openshift-cluster-kube-scheduler-operator-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#69134 Add CI and Prow configuration for openshift/mcs-ops
  ci-operator/config/openshift/mcs-ops/OWNERS
  ci-operator/config/openshift/mcs-ops/openshift-mcs-ops-main.yaml
  ci-operator/jobs/openshift/mcs-ops/OWNERS
  ci-operator/jobs/openshift/mcs-ops/openshift-mcs-ops-main-presubmits.yaml
  core-services/prow/02_config/openshift/mcs-ops/_pluginconfig.yaml
  core-services/prow/02_config/openshift/mcs-ops/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#69119 MON-4344: chore(openshift/monitoring): add jobs to run new cluster-monitoring-operator ginkgo tests
  ci-operator/config/openshift/cluster-monitoring-operator/openshift-cluster-monitoring-operator-main.yaml
  ci-operator/config/openshift/kube-state-metrics/openshift-kube-state-metrics-main.yaml
  ci-operator/config/openshift/kubernetes-metrics-server/openshift-kubernetes-metrics-server-main.yaml
  ci-operator/config/openshift/node_exporter/openshift-node_exporter-main.yaml
  ci-operator/config/openshift/openshift-state-metrics/openshift-openshift-state-metrics-main.yaml
  ci-operator/config/openshift/prom-label-proxy/openshift-prom-label-proxy-main.yaml
  ci-operator/config/openshift/prometheus-alertmanager/openshift-prometheus-alertmanager-main.yaml
  ci-operator/config/openshift/prometheus-operator/openshift-prometheus-operator-main.yaml
  ci-operator/config/openshift/prometheus/openshift-prometheus-main.yaml
  ci-operator/config/openshift/thanos/openshift-thanos-main.yaml
  ci-operator/jobs/openshift/cluster-monitoring-operator/openshift-cluster-monitoring-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/kube-state-metrics/openshift-kube-state-metrics-main-presubmits.yaml
  ci-operator/jobs/openshift/kubernetes-metrics-server/openshift-kubernetes-metrics-server-main-presubmits.yaml
  ci-operator/jobs/openshift/node_exporter/openshift-node_exporter-main-presubmits.yaml
  ci-operator/jobs/openshift/openshift-state-metrics/openshift-openshift-state-metrics-main-presubmits.yaml
  ci-operator/jobs/openshift/prom-label-proxy/openshift-prom-label-proxy-main-presubmits.yaml
  ci-operator/jobs/openshift/prometheus-alertmanager/openshift-prometheus-alertmanager-main-presubmits.yaml
  ci-operator/jobs/openshift/prometheus-operator/openshift-prometheus-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/prometheus/openshift-prometheus-main-presubmits.yaml
  ci-operator/jobs/openshift/thanos/openshift-thanos-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#69309 GitOps: Update master jobs to use 4.19
  ci-operator/config/redhat-developer/gitops-operator/redhat-developer-gitops-operator-master__v4.19.yaml
  ci-operator/jobs/redhat-developer/gitops-operator/redhat-developer-gitops-operator-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#69327 Revert "Block build09"
  core-services/sanitize-prow-jobs/_clusters.yaml
Labels: lgtm, approved, rehearsals-ack

#69298 DPTP-4486: More retry when got UnknownHostException
  ci-operator/step-registry/send-results/to-reportportal/send-results-to-reportportal-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#69332 [art] whitelist logging repos
  core-services/openshift-priv/_whitelist.yaml
Labels: lgtm, approved, rehearsals-ack

#69336 add specific version for orion
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-netobserv-perf-tests__netobserv-aws-4.20-nightly-x86.yaml
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-netobserv-perf-tests__netobserv-aws-4.21-nightly-x86.yaml
Labels: lgtm, approved, rehearsals-ack

#69115 CNTRLPLANE-945: Add 4.20 external oidc metal ipv6 periodics
  ci-operator/config/openshift/cluster-authentication-operator/openshift-cluster-authentication-operator-release-4.20__periodics.yaml
  ci-operator/jobs/openshift/cluster-authentication-operator/openshift-cluster-authentication-operator-release-4.20-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#68371 Add weekly oadp-cli test runs
  ci-operator/config/openshift/oadp-operator/openshift-oadp-operator-oadp-dev__4.19.yaml
  ci-operator/jobs/openshift/oadp-operator/openshift-oadp-operator-oadp-dev-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#69337 Search e2e use 2.15 integration pipeline for images
  ci-operator/config/stolostron/search-e2e-test/stolostron-search-e2e-test-main.yaml
Labels: lgtm, approved, rehearsals-ack

#69323 Search e2e tests run api/ui when appropriate
  ci-operator/config/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.11.yaml
  ci-operator/config/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.12.yaml
  ci-operator/config/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.13.yaml
  ci-operator/jobs/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.11-presubmits.yaml
  ci-operator/jobs/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.12-presubmits.yaml
  ci-operator/jobs/stolostron/search-e2e-test/stolostron-search-e2e-test-release-2.13-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#67336 OCPQE-30239: add step to check capi migration result
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__aws-4.20-nightly-x86.yaml
  ci-operator/step-registry/capi-migration-check/OWNERS
  ci-operator/step-registry/capi-migration-check/capi-migration-check-commands.sh
  ci-operator/step-registry/capi-migration-check/capi-migration-check-ref.metadata.json
  ci-operator/step-registry/capi-migration-check/capi-migration-check-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference
