Repository openshift/release, pull requests merged in 2025-07, with the labels that each got.

#66550 OCM-14122 | ci: Disable 4.14-4.17 job and update 4.19 job cadence
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#66544 OCPQE-30024: add qe-catalog for aws-short-cert-rotation-arm
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__multi-nightly.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#66401 Regression test for project deletion
  ci-operator/config/openshift/svt/openshift-svt-master__regression-aws-4.19-nightly-x86.yaml
  ci-operator/jobs/openshift/svt/openshift-svt-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#66545 Update Quay 3.15.0 API testing in Stage ENV
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__quay-api.yaml
  ci-operator/jobs/quay/quay-tests/quay-quay-tests-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#66397 COS-2902: Switch OKD to cs10 base images
  ci-operator/config/openshift/os/openshift-os-master__okd-scos.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#66581 BM CPT deploy sane defaults
  ci-operator/config/cloud-bulldozer/e2e-benchmarking/cloud-bulldozer-e2e-benchmarking-master.yaml
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__metal-4.14-nightly-x86.yaml
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__metal-4.15-nightly-x86.yaml
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__metal-4.16-nightly-x86.yaml
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__metal-4.17-nightly-x86.yaml
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__metal-4.18-nightly-x86.yaml
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__metal-4.19-nightly-x86.yaml
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__metal-rhoso-x86.yaml
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__metal-telco-x86.yaml
  ci-operator/config/redhat-performance/jetlag/redhat-performance-jetlag-main.yaml
  ci-operator/step-registry/openshift-qe/installer/bm/deploy/openshift-qe-installer-bm-deploy-ref.yaml
Labels: lgtm, approved, rehearsals-ack, network-access-rehearsals-ok

#66563 Ignore Azure/ARO-HCP from fast-forward
  ci-operator/jobs/infra-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#66583 OCPQE-30056: fix get openshift build
  ci-operator/step-registry/osd-ccs/cluster/provision/aws/osd-ccs-cluster-provision-aws-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#66157 Add sandboxed containers workflow to cluster-bot
  core-services/ci-chat-bot/workflows-config.yaml
Labels: lgtm, approved, rehearsals-ack

#66541 feat(STONEINTG-1193): decouple prow/ci jobs of integration-e2e
  ci-operator/config/konflux-ci/integration-service/OWNERS
  ci-operator/config/konflux-ci/integration-service/konflux-ci-integration-service-main.yaml
  ci-operator/jobs/konflux-ci/integration-service/OWNERS
  ci-operator/jobs/konflux-ci/integration-service/konflux-ci-integration-service-main-presubmits.yaml
  core-services/prow/02_config/konflux-ci/integration-service/_pluginconfig.yaml
  core-services/prow/02_config/konflux-ci/integration-service/_prowconfig.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#64768 rhdh-sealight-nighlty-job
  ci-operator/config/redhat-developer/rhdh/redhat-developer-rhdh-main.yaml
  ci-operator/jobs/redhat-developer/rhdh/redhat-developer-rhdh-main-periodics.yaml
  ci-operator/jobs/redhat-developer/rhdh/redhat-developer-rhdh-main-presubmits.yaml
  ci-operator/step-registry/redhat-developer/rhdh/nightly/redhat-developer-rhdh-nightly-commands.sh
Labels: lgtm, approved, rehearsals-ack

#66359 OSC downstream: add support for AWS
  ci-operator/config/openshift/sandboxed-containers-operator/openshift-sandboxed-containers-operator-devel__downstream-candidate.yaml
  ci-operator/config/openshift/sandboxed-containers-operator/openshift-sandboxed-containers-operator-devel__downstream-release.yaml
  ci-operator/jobs/openshift/sandboxed-containers-operator/openshift-sandboxed-containers-operator-devel-periodics.yaml
  ci-operator/step-registry/sandboxed-containers-operator/e2e/aws/OWNERS
  ci-operator/step-registry/sandboxed-containers-operator/e2e/aws/sandboxed-containers-operator-e2e-aws-workflow.metadata.json
  ci-operator/step-registry/sandboxed-containers-operator/e2e/aws/sandboxed-containers-operator-e2e-aws-workflow.yaml
  ci-operator/step-registry/sandboxed-containers-operator/peerpods/param-cm/sandboxed-containers-operator-peerpods-param-cm-commands.sh
Labels: lgtm, approved, rehearsals-ack

#66576 add aro-hcp dnf dep and clean up the configuration
  ci-operator/config/Azure/ARO-HCP/Azure-ARO-HCP-main.yaml
  ci-operator/config/Azure/ARO-HCP/Azure-ARO-HCP-main__periodic.yaml
  ci-operator/jobs/Azure/ARO-HCP/Azure-ARO-HCP-main-postsubmits.yaml
  ci-operator/jobs/Azure/ARO-HCP/Azure-ARO-HCP-main-presubmits.yaml
  ci-operator/step-registry/aro-hcp/provision/create-hcp-cluster/aro-hcp-provision-create-hcp-cluster-commands.sh
  ci-operator/step-registry/aro-hcp/provision/create-nodepool/aro-hcp-provision-create-nodepool-commands.sh
  ci-operator/step-registry/aro-hcp/provision/create-prereq-resources/aro-hcp-provision-create-prereq-resources-commands.sh
Labels: lgtm, approved, rehearsals-ack

#66617 stolostron/search Change target release for e2e tests
  ci-operator/config/stolostron/search-e2e-test/stolostron-search-e2e-test-main.yaml
Labels: lgtm, approved, rehearsals-ack

#66624 OCPCRT-402: Adding the 'Red Hat Partner' as an `allowed_security_levels`
  core-services/jira-lifecycle-plugin/config.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#66611 Update `policy-cli` fast-forward branch
  ci-operator/config/stolostron/policy-cli/stolostron-policy-cli-main.yaml
Labels: lgtm, approved, rehearsals-ack

#66622 OPRUN-3947: [operator-controller] - Default Catalog Tests should not have CI as optional
  ci-operator/config/openshift/operator-framework-operator-controller/openshift-operator-framework-operator-controller-main.yaml
  ci-operator/config/openshift/operator-framework-operator-controller/openshift-operator-framework-operator-controller-release-4.20.yaml
  ci-operator/config/openshift/operator-framework-operator-controller/openshift-operator-framework-operator-controller-release-4.21.yaml
  ci-operator/jobs/openshift/operator-framework-operator-controller/openshift-operator-framework-operator-controller-main-presubmits.yaml
  ci-operator/jobs/openshift/operator-framework-operator-controller/openshift-operator-framework-operator-controller-release-4.20-presubmits.yaml
  ci-operator/jobs/openshift/operator-framework-operator-controller/openshift-operator-framework-operator-controller-release-4.21-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#66631 adjust releases.latest to make sure it can be get 4.19.z-1
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__automated-release-stable-4.19-upgrade-from-stable-4.19.yaml
Labels: lgtm, approved, rehearsals-ack

#66484 add regression test OCP-40557
  ci-operator/config/openshift/svt/openshift-svt-master__regression-aws-4.19-nightly-x86.yaml
  ci-operator/jobs/openshift/svt/openshift-svt-master-presubmits.yaml
  ci-operator/step-registry/openshift/svt/regression/one/openshift-svt-regression-one-ref.yaml
  ci-operator/step-registry/openshift/svt/regression/openshift-svt-regression-commands.sh
  ci-operator/step-registry/openshift/svt/regression/openshift-svt-regression-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#66646 Block build09
  core-services/sanitize-prow-jobs/_clusters.yaml
Labels: lgtm, approved, rehearsals-ack

#65918 cert-rotation: improve CSR approval, retry mirroring
  ci-operator/step-registry/openshift/e2e/cert-rotation/conf/mirror/openshift-e2e-cert-rotation-conf-mirror-commands.sh
  ci-operator/step-registry/openshift/e2e/cert-rotation/prepare-for-shutdown/openshift-e2e-cert-rotation-prepare-for-shutdown-commands.sh
  ci-operator/step-registry/openshift/e2e/cert-rotation/shutdown/openshift-e2e-cert-rotation-shutdown-workflow.yaml
  ci-operator/step-registry/openshift/e2e/cert-rotation/suspend/openshift-e2e-cert-rotation-suspend-workflow.yaml
  ci-operator/step-registry/openshift/e2e/cert-rotation/test/openshift-e2e-cert-rotation-test-commands.sh
  ci-operator/step-registry/upi/gcp/nested/pre/upi-gcp-nested-pre-commands.sh
  ci-operator/step-registry/upi/gcp/nested/pre/upi-gcp-nested-pre-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#66160 USHIFT-5397: [QE] Replace MicroShift build images phase with dev scripts
  ci-operator/step-registry/openshift/microshift/infra/iso-build/openshift-microshift-infra-iso-build-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#66641 Add REDIS image to scan from Quay 3.14.3 Operator
  ci-operator/config/quay/quay-tests/quay-quay-tests-master__quay-sdl.yaml
Labels: lgtm, approved, rehearsals-ack

#66616 run ci tests for coo related release branches
  ci-operator/config/openshift/monitoring-plugin/openshift-monitoring-plugin-release-coo-0.4.yaml
  ci-operator/config/openshift/monitoring-plugin/openshift-monitoring-plugin-release-coo-0.5.yaml
  ci-operator/jobs/openshift/monitoring-plugin/openshift-monitoring-plugin-release-coo-0.4-presubmits.yaml
  ci-operator/jobs/openshift/monitoring-plugin/openshift-monitoring-plugin-release-coo-0.5-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#66568 MGMT-20671: Add workflow and jobs for heterogeneous ofcir cluster installation
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-assisted-version-placeholder.yaml
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-main__edge.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/step-registry/assisted/baremetal/test/assisted-baremetal-test-commands.sh
  ci-operator/step-registry/assisted/equinix/assisted-equinix-workflow.metadata.json
  ci-operator/step-registry/assisted/equinix/setup/assisted-equinix-setup-ref.metadata.json
  ci-operator/step-registry/assisted/equinix/setup/assisted-equinix-setup-ref.yaml
  ci-operator/step-registry/assisted/equinix/teardown/OWNERS
  ci-operator/step-registry/assisted/equinix/teardown/assisted-equinix-teardown-ref.metadata.json
  ci-operator/step-registry/assisted/equinix/teardown/assisted-equinix-teardown-ref.yaml
  ci-operator/step-registry/assisted/ofcir/baremetal/heterogeneous/OWNERS
  ci-operator/step-registry/assisted/ofcir/baremetal/heterogeneous/assisted-ofcir-baremetal-heterogeneous-workflow.metadata.json
  ci-operator/step-registry/assisted/ofcir/baremetal/heterogeneous/assisted-ofcir-baremetal-heterogeneous-workflow.yaml
  ci-operator/step-registry/assisted/ofcir/baremetal/heterogeneous/setup/OWNERS
  ci-operator/step-registry/assisted/ofcir/baremetal/heterogeneous/setup/assisted-ofcir-baremetal-heterogeneous-setup-commands.sh
  ci-operator/step-registry/assisted/ofcir/baremetal/heterogeneous/setup/assisted-ofcir-baremetal-heterogeneous-setup-ref.metadata.json
  ci-operator/step-registry/assisted/ofcir/baremetal/heterogeneous/setup/assisted-ofcir-baremetal-heterogeneous-setup-ref.yaml
  ci-operator/step-registry/assisted/ofcir/baremetal/heterogeneous/teardown/OWNERS
  ci-operator/step-registry/assisted/ofcir/baremetal/heterogeneous/teardown/assisted-ofcir-baremetal-heterogeneous-teardown-commands.sh
  ci-operator/step-registry/assisted/ofcir/baremetal/heterogeneous/teardown/assisted-ofcir-baremetal-heterogeneous-teardown-ref.metadata.json
  ci-operator/step-registry/assisted/ofcir/baremetal/heterogeneous/teardown/assisted-ofcir-baremetal-heterogeneous-teardown-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#65568 CORS-4069: Add test for nat gateway support
  ci-operator/config/openshift/installer/openshift-installer-main.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-main-presubmits.yaml
  ci-operator/step-registry/ipi/conf/azure/ipi-conf-azure-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#66138 AUTOSCALE-258: Scheduling rebasebot config for autoscaling karpenter-core
  ci-operator/config/openshift-eng/rebasebot/openshift-eng-rebasebot-main.yaml
  ci-operator/jobs/openshift-eng/rebasebot/openshift-eng-rebasebot-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#66614 Changing hypershift base domain depending on the account
  ci-operator/step-registry/hypershift/hostedcluster/create/hostedcluster/hypershift-hostedcluster-create-hostedcluster-commands.sh
  ci-operator/step-registry/hypershift/hostedcluster/create/hostedcluster/hypershift-hostedcluster-create-hostedcluster-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#64134 Adding zone outage for gcp
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__4.18-nightly.yaml
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__4.19-nightly.yaml
  ci-operator/step-registry/redhat-chaos/pvc-scenarios/prometheus-pod/redhat-chaos-pvc-scenarios-prometheus-pod-commands.sh
  ci-operator/step-registry/redhat-chaos/service-disruption/redhat-chaos-service-disruption-commands.sh
  ci-operator/step-registry/redhat-chaos/zone-outage/redhat-chaos-zone-outage-commands.sh
Labels: lgtm, approved, rehearsals-ack

#66643 NO-ISSUE: Get pmlogger and pmcd journal on start failure
  ci-operator/step-registry/openshift/microshift/infra/iso-build/openshift-microshift-infra-iso-build-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#66621 Clean up Kueue jobs
  ci-operator/config/openshift/kueue-operator/openshift-kueue-operator-release-1.0.yaml
  ci-operator/step-registry/kueue-operator/image-env-setup/kueue-operator-image-env-setup-ref.yaml
  ci-operator/step-registry/kueue-operator/image-patch/kueue-operator-image-patch-ref.yaml
  ci-operator/step-registry/kueue-operator/test/OWNERS
  ci-operator/step-registry/kueue-operator/test/e2e/OWNERS
  ci-operator/step-registry/kueue-operator/test/e2e/kueue-operator-test-e2e-chain.metadata.json
  ci-operator/step-registry/kueue-operator/test/e2e/kueue-operator-test-e2e-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#66669 add region to observability-aws-quota-slice
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: lgtm, approved, rehearsals-ack

#66670 OTA-1467 enable env UPGRADE_CCO_MANUAL_MODE: oidc for aws sts profile's in 4.19->4.20 upgrade ci jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__amd64-nightly-4.20-upgrade-from-stable-4.19.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__amd64-stable-4.20-upgrade-from-stable-4.19.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__arm64-nightly-4.20-upgrade-from-stable-4.19.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__arm64-stable-4.20-upgrade-from-stable-4.19.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__multi-nightly-4.20-upgrade-from-stable-4.19.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__multi-stable-4.20-upgrade-from-stable-4.19.yaml
Labels: lgtm, approved, rehearsals-ack

#66666 Fix calculation for tests failures/skipped
  ci-operator/step-registry/cucushift/e2e/cucushift-e2e-commands.sh
Labels: lgtm, approved, rehearsals-ack

#66677 NO-ISSUE: Fix typos
  ci-operator/step-registry/assisted/ofcir/baremetal/heterogeneous/assisted-ofcir-baremetal-heterogeneous-workflow.yaml
  ci-operator/step-registry/assisted/ofcir/baremetal/heterogeneous/setup/assisted-ofcir-baremetal-heterogeneous-setup-commands.sh
  ci-operator/step-registry/assisted/ofcir/baremetal/heterogeneous/setup/assisted-ofcir-baremetal-heterogeneous-setup-ref.yaml
  ci-operator/step-registry/assisted/ofcir/baremetal/heterogeneous/teardown/assisted-ofcir-baremetal-heterogeneous-teardown-commands.sh
  ci-operator/step-registry/assisted/ofcir/baremetal/heterogeneous/teardown/assisted-ofcir-baremetal-heterogeneous-teardown-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#66678 [KMM-Hub] Adding an `operator-hub-upgrade` job.
  ci-operator/config/rh-ecosystem-edge/kernel-module-management/rh-ecosystem-edge-kernel-module-management-main.yaml
  ci-operator/jobs/rh-ecosystem-edge/kernel-module-management/rh-ecosystem-edge-kernel-module-management-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#66659 Add network policies to AKS management cluster
  ci-operator/step-registry/aks/provision/aks-provision-commands.sh
Labels: lgtm, approved, rehearsals-ack

#66683 OPRUN-3975: [operator-controller]: Increase frequency of jobs to run catalogo tests to avoid false alarms
  ci-operator/config/openshift/operator-framework-operator-controller/openshift-operator-framework-operator-controller-release-4.17__periodics.yaml
  ci-operator/config/openshift/operator-framework-operator-controller/openshift-operator-framework-operator-controller-release-4.18__periodics.yaml
  ci-operator/config/openshift/operator-framework-operator-controller/openshift-operator-framework-operator-controller-release-4.19__periodics.yaml
  ci-operator/config/openshift/operator-framework-operator-controller/openshift-operator-framework-operator-controller-release-4.20__periodics.yaml
  ci-operator/jobs/openshift/operator-framework-operator-controller/openshift-operator-framework-operator-controller-release-4.17-periodics.yaml
  ci-operator/jobs/openshift/operator-framework-operator-controller/openshift-operator-framework-operator-controller-release-4.18-periodics.yaml
  ci-operator/jobs/openshift/operator-framework-operator-controller/openshift-operator-framework-operator-controller-release-4.19-periodics.yaml
  ci-operator/jobs/openshift/operator-framework-operator-controller/openshift-operator-framework-operator-controller-release-4.20-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#65562 `secret-manager`: Implement index secret
  hack/gcp-secret-manager/commands/create.py
  hack/gcp-secret-manager/commands/delete.py
  hack/gcp-secret-manager/commands/get_service_account.py
  hack/gcp-secret-manager/commands/list.py
  hack/gcp-secret-manager/commands/update.py
  hack/gcp-secret-manager/util.py
Labels: lgtm, approved, tide/merge-method-squash, rehearsals-ack

#66689 Temp mark datarouter image as optional
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__images.yaml
Labels: lgtm, approved, rehearsals-ack

#66693 Convert stage jobs to periodc jobs
  ci-operator/config/openshift/distributed-tracing-qe/openshift-distributed-tracing-qe-main__ocp-4.15-disconnected.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.12-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.14-arm-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.16-ibm-z-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.17-fips-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.17-ibm-p-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.19-stage.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.12-stage.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.14-arm-stage.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.15-ibm-z-stage.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.17-ibm-p-stage.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.18-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.12-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.14-arm-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.16-ibm-z-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.17-fips-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.17-ibm-p-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.19-stage.yaml
  ci-operator/jobs/openshift/distributed-tracing-qe/openshift-distributed-tracing-qe-main-periodics.yaml
  ci-operator/jobs/openshift/distributed-tracing-qe/openshift-distributed-tracing-qe-main-presubmits.yaml
  ci-operator/jobs/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main-periodics.yaml
  ci-operator/jobs/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main-periodics.yaml
  ci-operator/jobs/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main-periodics.yaml
  ci-operator/jobs/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#66696 rhdh-sealight-nighlty-job-update
  ci-operator/jobs/redhat-developer/rhdh/redhat-developer-rhdh-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#61849 OCPBUGS-51083: rename 'master' to 'main' for kubernetes-nmstate
  ci-operator/config/openshift-priv/kubernetes-nmstate/openshift-priv-kubernetes-nmstate-main.yaml
  ci-operator/config/openshift/kubernetes-nmstate/openshift-kubernetes-nmstate-main.yaml
  ci-operator/jobs/openshift-priv/kubernetes-nmstate/openshift-priv-kubernetes-nmstate-main-postsubmits.yaml
  ci-operator/jobs/openshift-priv/kubernetes-nmstate/openshift-priv-kubernetes-nmstate-main-presubmits.yaml
  ci-operator/jobs/openshift/kubernetes-nmstate/openshift-kubernetes-nmstate-main-periodics.yaml
  ci-operator/jobs/openshift/kubernetes-nmstate/openshift-kubernetes-nmstate-main-postsubmits.yaml
  ci-operator/jobs/openshift/kubernetes-nmstate/openshift-kubernetes-nmstate-main-presubmits.yaml
Labels: lgtm, approved, jira/valid-bug, rehearsals-ack, jira/valid-reference

#66702 oauth-proxy: add ibihim to backport-risk-assessed allowed_users
  core-services/prow/02_config/openshift/oauth-proxy/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#66707 adding bot for cnv
  core-services/prow/02_config/openshift/openshift-docs/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#66283 Upgrade devsandbox clusters to 4.19
  ci-operator/config/codeready-toolchain/host-operator/codeready-toolchain-host-operator-master.yaml
  ci-operator/config/codeready-toolchain/member-operator/codeready-toolchain-member-operator-master.yaml
  ci-operator/config/codeready-toolchain/registration-service/codeready-toolchain-registration-service-master.yaml
  ci-operator/config/codeready-toolchain/toolchain-e2e/codeready-toolchain-toolchain-e2e-master.yaml
  ci-operator/config/codeready-toolchain/workload-analyzer/codeready-toolchain-workload-analyzer-master.yaml
Labels: lgtm, approved, rehearsals-ack

#66703 adding jobs for the 3.1 OSSM docs
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-service-mesh-docs-3.1.yaml
  ci-operator/jobs/openshift/openshift-docs/openshift-openshift-docs-service-mesh-docs-3.1-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#66695 Move upstream tests to e2e chain
  ci-operator/config/openshift/kueue-operator/openshift-kueue-operator-release-1.0.yaml
  ci-operator/jobs/openshift/kueue-operator/openshift-kueue-operator-release-1.0-presubmits.yaml
  ci-operator/step-registry/kueue-operator/test/e2e/kueue-operator-test-e2e-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#66706 run search e2e api and ui tests only when pertinent changes
  ci-operator/config/stolostron/search-e2e-test/stolostron-search-e2e-test-main.yaml
  ci-operator/jobs/stolostron/search-e2e-test/stolostron-search-e2e-test-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#66721 chore: Update Dockerfile to compatible jdk21
  ci-operator/config/openshift/jenkins-client-plugin/openshift-jenkins-client-plugin-master.yaml
  ci-operator/config/openshift/jenkins-client-plugin/openshift-jenkins-client-plugin-release-4.12.yaml
  ci-operator/config/openshift/jenkins-client-plugin/openshift-jenkins-client-plugin-release-4.13.yaml
  ci-operator/config/openshift/jenkins-client-plugin/openshift-jenkins-client-plugin-release-4.14.yaml
  ci-operator/config/openshift/jenkins-client-plugin/openshift-jenkins-client-plugin-release-4.15.yaml
  ci-operator/config/openshift/jenkins-client-plugin/openshift-jenkins-client-plugin-release-4.16.yaml
  ci-operator/config/openshift/jenkins-client-plugin/openshift-jenkins-client-plugin-release-4.17.yaml
  ci-operator/config/openshift/jenkins-client-plugin/openshift-jenkins-client-plugin-release-4.18.yaml
  ci-operator/config/openshift/jenkins-client-plugin/openshift-jenkins-client-plugin-release-4.19.yaml
  ci-operator/config/openshift/jenkins-client-plugin/openshift-jenkins-client-plugin-release-4.20.yaml
  ci-operator/config/openshift/jenkins-client-plugin/openshift-jenkins-client-plugin-release-4.21.yaml
Labels: lgtm, approved, rehearsals-ack

#66726 Update Tracing CI jobs and steps to allow passing env vars from Gangway API.
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.12-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.14-arm-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.16-ibm-z-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.17-fips-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.17-ibm-p-stage.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.19-stage.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.12-stage.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.14-arm-stage.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.15-ibm-z-stage.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.17-ibm-p-stage.yaml
  ci-operator/config/openshift/jaegertracing-jaeger-operator/openshift-jaegertracing-jaeger-operator-main__jaeger-product-ocp-4.18-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.12-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.14-arm-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.16-ibm-z-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.17-fips-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.17-ibm-p-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.19-stage.yaml
  ci-operator/step-registry/distributed-tracing/install/disconnected/distributed-tracing-install-disconnected-commands.sh
  ci-operator/step-registry/distributed-tracing/install/disconnected/distributed-tracing-install-disconnected-ref.yaml
  ci-operator/step-registry/distributed-tracing/install/jaeger-konflux-catalogsource/distributed-tracing-install-jaeger-konflux-catalogsource-commands.sh
  ci-operator/step-registry/distributed-tracing/install/jaeger-konflux-catalogsource/distributed-tracing-install-jaeger-konflux-catalogsource-ref.yaml
  ci-operator/step-registry/distributed-tracing/install/otel-konflux-catalogsource/distributed-tracing-install-otel-konflux-catalogsource-commands.sh
  ci-operator/step-registry/distributed-tracing/install/otel-konflux-catalogsource/distributed-tracing-install-otel-konflux-catalogsource-ref.yaml
  ci-operator/step-registry/distributed-tracing/install/tempo-konflux-catalogsource/distributed-tracing-install-tempo-konflux-catalogsource-commands.sh
  ci-operator/step-registry/distributed-tracing/install/tempo-konflux-catalogsource/distributed-tracing-install-tempo-konflux-catalogsource-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#66712 revert: rename secret back to packet-ssh-key
  ci-operator/step-registry/baremetalds/packet/setup/baremetalds-packet-setup-commands.sh
Labels: lgtm, approved, rehearsals-ack

#66323 Integrate to ReportPortal
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20-periodics.yaml
  ci-operator/step-registry/cucushift/e2e/cucushift-e2e-commands.sh
  ci-operator/step-registry/junit2reportportal/OWNERS
  ci-operator/step-registry/junit2reportportal/junit2reportportal-commands.sh
  ci-operator/step-registry/junit2reportportal/junit2reportportal-ref.metadata.json
  ci-operator/step-registry/junit2reportportal/junit2reportportal-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#66424 sandboxed-containers: fix the pullspecs of the operator
  ci-operator/config/openshift/sandboxed-containers-operator/openshift-sandboxed-containers-operator-devel.yaml
  ci-operator/config/openshift/sandboxed-containers-operator/openshift-sandboxed-containers-operator-release-1.8.yaml
  ci-operator/jobs/openshift/sandboxed-containers-operator/openshift-sandboxed-containers-operator-release-1.8-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#66648 Removing from OWNERS ALIASES as using OWNERS file
  OWNERS_ALIASES
  ci-operator/config/codeready-toolchain/toolchain-e2e/OWNERS
  ci-operator/jobs/codeready-toolchain/toolchain-e2e/OWNERS
  core-services/prow/02_config/codeready-toolchain/toolchain-e2e/OWNERS
Labels: lgtm, approved, rehearsals-ack

#65774 METAL-989 METAL-990 baremetal Cluster API
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__multi-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20-periodics.yaml
  ci-operator/step-registry/baremetal/lab/capi/OWNERS
  ci-operator/step-registry/baremetal/lab/capi/baremetal-lab-capi-commands.sh
  ci-operator/step-registry/baremetal/lab/capi/baremetal-lab-capi-ref.metadata.json
  ci-operator/step-registry/baremetal/lab/capi/baremetal-lab-capi-ref.yaml
  ci-operator/step-registry/baremetal/lab/ipi/conf/virtual-media/baremetal-lab-ipi-conf-virtual-media-commands.sh
  ci-operator/step-registry/baremetal/lab/ipi/conf/virtual-media/baremetal-lab-ipi-conf-virtual-media-ref.yaml
  ci-operator/step-registry/baremetal/lab/ipi/install/baremetal-lab-ipi-install-chain.yaml
  ci-operator/step-registry/baremetal/lab/ipi/install/baremetal-lab-ipi-install-commands.sh
  ci-operator/step-registry/baremetal/lab/ipi/install/baremetal-lab-ipi-install-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#66496 OCPNODE-3415: Include Kueue periodic jobs
  ci-operator/config/openshift/kueue-operator/openshift-kueue-operator-release-1.0.yaml
  ci-operator/jobs/openshift/kueue-operator/openshift-kueue-operator-release-1.0-periodics.yaml
  ci-operator/step-registry/kueue-operator/image-patch/kueue-operator-image-patch-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#66748 Add Slack report for Tracing stage jobs and cleanup old interop jobs
  ci-operator/config/openshift/grafana-tempo-operator/.config.prowgen
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.14-lp-interop.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.14-lp-rosa-classic.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.15-lp-interop.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.15-lp-rosa-classic.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.16-lp-interop.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.16-lp-rosa-classic.yaml
  ci-operator/config/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main__tempo-product-ocp-4.17-fips-stage.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/.config.prowgen
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.14-lp-interop.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.14-lp-rosa-classic.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.15-lp-interop.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.15-lp-rosa-classic.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.16-lp-interop.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.16-lp-rosa-classic.yaml
  ci-operator/config/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main__opentelemetry-product-ocp-4.17-fips-stage.yaml
  ci-operator/jobs/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main-periodics.yaml
  ci-operator/jobs/openshift/grafana-tempo-operator/openshift-grafana-tempo-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main-periodics.yaml
  ci-operator/jobs/openshift/open-telemetry-opentelemetry-operator/openshift-open-telemetry-opentelemetry-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#66720 Add new release aws-observability-quota-slice
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: lgtm, approved, rehearsals-ack

#66773 BM CPT: change schedules
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__metal-4.16-nightly-x86.yaml
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__metal-4.17-nightly-x86.yaml
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__metal-4.19-nightly-x86.yaml
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__metal-rhoso-x86.yaml
  ci-operator/jobs/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main-periodics.yaml
  ci-operator/jobs/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#66783 Etcd defrag periodic
  ci-operator/jobs/infra-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#66795 search fix deploy-and-run-e2e job regex
  ci-operator/config/stolostron/search-e2e-test/stolostron-search-e2e-test-main.yaml
  ci-operator/jobs/stolostron/search-e2e-test/stolostron-search-e2e-test-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#66729 Excluding Mihawk0 (C155F2U33) from lease pool due to S2S migration
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: lgtm, approved, rehearsals-ack

#66800 LOG-7330: Add logging cluster pool for ocp 4.19
  clusters/hosted-mgmt/hive/pools/openshift-observability/obs-logging-ocp-4-19-amd64-aws-us-east-1_clusterpool.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#66774 STOR-2493: Filter 4.20 test cases automatically on capabilities
  ci-operator/step-registry/cucushift/e2e/cucushift-e2e-commands.sh
  ci-operator/step-registry/cucushift/e2e/devel/cucushift-e2e-devel-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#66809 Fix unbound variable PULL_NUMBER
  ci-operator/step-registry/junit2reportportal/junit2reportportal-commands.sh
Labels: lgtm, approved, rehearsals-ack

#66815 Skip must gather when tests are passed
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__amd64-nightly.yaml
  ci-operator/step-registry/junit2reportportal/junit2reportportal-commands.sh
Labels: lgtm, approved, rehearsals-ack

#65838 ci: Exlude .tekton dir from CI test trigger
  ci-operator/config/openshift/jenkins/openshift-jenkins-release-rhel8.yaml
  ci-operator/config/openshift/jenkins/openshift-jenkins-release-rhel9.yaml
  ci-operator/jobs/openshift/jenkins/openshift-jenkins-release-rhel8-presubmits.yaml
  ci-operator/jobs/openshift/jenkins/openshift-jenkins-release-rhel9-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#66690 use cluster-profile aws-observability for all logging AWS jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__multi-stable-openshift-logging-6.0.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__multi-stable-openshift-logging-6.2.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__arm64-stable-openshift-logging-6.3.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__multi-stable-openshift-logging-6.2.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__amd64-nightly-openshift-logging-6.3.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#66823 Removing NFD fallback Custom Catalog Source for 4.19 jobs
  ci-operator/config/rh-ecosystem-edge/nvidia-ci/rh-ecosystem-edge-nvidia-ci-main__4.19-stable.yaml
Labels: lgtm, approved, rehearsals-ack

#66768 [PERFSCALE-3994] OKD 4.20 deployments
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__aws-4.20-okd-x86.yaml
  ci-operator/jobs/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main-periodics.yaml
  ci-operator/jobs/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#66798 add some gathering steps for ARO-HCP
  ci-operator/config/Azure/ARO-HCP/Azure-ARO-HCP-main.yaml
  ci-operator/config/Azure/ARO-HCP/Azure-ARO-HCP-main__periodic.yaml
  ci-operator/step-registry/aro-hcp/provision/aro-hcp-gather-extra/OWNERS
  ci-operator/step-registry/aro-hcp/provision/aro-hcp-gather-extra/aro-hcp-provision-aro-hcp-gather-extra-commands.sh
  ci-operator/step-registry/aro-hcp/provision/aro-hcp-gather-extra/aro-hcp-provision-aro-hcp-gather-extra-ref.metadata.json
  ci-operator/step-registry/aro-hcp/provision/aro-hcp-gather-extra/aro-hcp-provision-aro-hcp-gather-extra-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#66852 ARO-HCP: remove plugins which are not needed
  core-services/prow/02_config/Azure/ARO-HCP/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#66851 aos-cd-jobs: Let mere bot only look at master
  core-services/prow/02_config/openshift-eng/aos-cd-jobs/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#66760 enable oauth related tests for agent runs on ppc64le
  ci-operator/step-registry/openshift/e2e/libvirt/conf/openshift-e2e-libvirt-conf-commands.sh
  ci-operator/step-registry/openshift/e2e/libvirt/conf/openshift-e2e-libvirt-conf-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#66711 OKD-245: Fix builds for aws-encryption-provider
  ci-operator/config/openshift/aws-encryption-provider/openshift-aws-encryption-provider-master__okd-scos.yaml
  ci-operator/jobs/openshift/aws-encryption-provider/openshift-aws-encryption-provider-master-postsubmits.yaml
  ci-operator/jobs/openshift/aws-encryption-provider/openshift-aws-encryption-provider-master-presubmits.yaml
Labels: rehearsals-ack, jira/valid-reference

#66862 Mark Security Profiles Operator e2e-flaky tests as optional
  ci-operator/config/openshift/security-profiles-operator/openshift-security-profiles-operator-konflux.yaml
  ci-operator/jobs/openshift/security-profiles-operator/openshift-security-profiles-operator-konflux-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#66709 Add churn to udn. fix some issues with configs
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#66871 Fix failingScenarios by excluding grep command
  ci-operator/step-registry/cucushift/e2e/cucushift-e2e-commands.sh
Labels: lgtm, approved, rehearsals-ack

#66865 Azure: fix role definition creation failure
  ci-operator/step-registry/azure/provision/custom-role/azure-provision-custom-role-commands.sh
Labels: lgtm, approved, rehearsals-ack

#66876 RHDH use old reporting for upgrade and auth-providers
  ci-operator/config/redhat-developer/rhdh/redhat-developer-rhdh-main.yaml
  ci-operator/config/redhat-developer/rhdh/redhat-developer-rhdh-release-1.6.yaml
  ci-operator/jobs/redhat-developer/rhdh/redhat-developer-rhdh-main-periodics.yaml
  ci-operator/jobs/redhat-developer/rhdh/redhat-developer-rhdh-release-1.6-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#66842 Trust Konflux bot in coreos projects
  core-services/prow/02_config/coreos/coreos-assembler/_pluginconfig.yaml
  core-services/prow/02_config/coreos/rhel-coreos-config/_pluginconfig.yaml
  core-services/prow/02_config/coreos/rpm-ostree/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#66864 origin: remove skip_if_only_changed from publicnet jobs
  ci-operator/config/openshift/origin/openshift-origin-main.yaml
Labels: lgtm, approved, rehearsals-ack

#66788 telco5g: Use 4.19 operators for 4.19 and above in HCP
  ci-operator/step-registry/telco5g/hcp-cluster-setup/telco5g-hcp-cluster-setup-commands.sh
Labels: lgtm, approved, rehearsals-ack

#66884 openshift-logging: Update image-mirroring configuration for 6.3 and 6.4
  core-services/image-mirroring/openshift-logging/mapping_logging_6_3_quay
  core-services/image-mirroring/openshift-logging/mapping_logging_fluentd_quay
  core-services/image-mirroring/openshift-logging/mapping_logging_kibana_quay
  core-services/image-mirroring/openshift-logging/mapping_logging_latest_quay
  core-services/image-mirroring/openshift-logging/mapping_logging_logfilemetricexporter_quay
Labels: lgtm, approved, rehearsals-ack

#66886 [crc-org/llama.cpp] Update from TOPSAIL main
  ci-operator/config/crc-org/llama.cpp/crc-org-llama.cpp-main.yaml
Labels: lgtm, approved, rehearsals-ack

#66888 Add 'run-integration-tests' label to opendatahub-io/opendatahub-operator repository
  core-services/prow/02_config/_labels.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#66878 oauth-server: add myself to backport-risk-assessed allowed_users
  core-services/prow/02_config/openshift/oauth-server/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#66847 No longer make Konflux jobs optional for LCA
  core-services/prow/02_config/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#66850 WINC-1367: add windows_exporter test jobs for release 4.14 to 4.19 branches
  ci-operator/config/openshift/prometheus-community-windows_exporter/openshift-prometheus-community-windows_exporter-release-4.14.yaml
  ci-operator/config/openshift/prometheus-community-windows_exporter/openshift-prometheus-community-windows_exporter-release-4.15.yaml
  ci-operator/config/openshift/prometheus-community-windows_exporter/openshift-prometheus-community-windows_exporter-release-4.16.yaml
  ci-operator/config/openshift/prometheus-community-windows_exporter/openshift-prometheus-community-windows_exporter-release-4.17.yaml
  ci-operator/config/openshift/prometheus-community-windows_exporter/openshift-prometheus-community-windows_exporter-release-4.18.yaml
  ci-operator/config/openshift/prometheus-community-windows_exporter/openshift-prometheus-community-windows_exporter-release-4.19.yaml
  ci-operator/jobs/openshift/prometheus-community-windows_exporter/openshift-prometheus-community-windows_exporter-release-4.14-presubmits.yaml
  ci-operator/jobs/openshift/prometheus-community-windows_exporter/openshift-prometheus-community-windows_exporter-release-4.15-presubmits.yaml
  ci-operator/jobs/openshift/prometheus-community-windows_exporter/openshift-prometheus-community-windows_exporter-release-4.16-presubmits.yaml
  ci-operator/jobs/openshift/prometheus-community-windows_exporter/openshift-prometheus-community-windows_exporter-release-4.17-presubmits.yaml
  ci-operator/jobs/openshift/prometheus-community-windows_exporter/openshift-prometheus-community-windows_exporter-release-4.18-presubmits.yaml
  ci-operator/jobs/openshift/prometheus-community-windows_exporter/openshift-prometheus-community-windows_exporter-release-4.19-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#66894 MCE hypershift addon 2.10
  ci-operator/config/stolostron/hypershift-addon-operator/stolostron-hypershift-addon-operator-backplane-2.10.yaml
  ci-operator/config/stolostron/hypershift-addon-operator/stolostron-hypershift-addon-operator-main.yaml
  ci-operator/jobs/stolostron/hypershift-addon-operator/stolostron-hypershift-addon-operator-backplane-2.10-postsubmits.yaml
  ci-operator/jobs/stolostron/hypershift-addon-operator/stolostron-hypershift-addon-operator-backplane-2.10-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#66900 stolostron/search-e2e Use dev stage pipeline
  ci-operator/config/stolostron/search-e2e-test/stolostron-search-e2e-test-main.yaml
Labels: lgtm, approved, rehearsals-ack

#66772 Update Custom DNS format
  ci-operator/step-registry/aws/provision/route53/public-record-sets/aws-provision-route53-public-record-sets-commands.sh
  ci-operator/step-registry/aws/provision/route53/public-record-sets/aws-provision-route53-public-record-sets-ref.yaml
  ci-operator/step-registry/gcp/provision/public-custom-dns/gcp-provision-public-custom-dns-commands.sh
  ci-operator/step-registry/gcp/provision/public-custom-dns/gcp-provision-public-custom-dns-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#66910 Update DT Konflux catatalogsource ICSP
  ci-operator/step-registry/distributed-tracing/install/otel-konflux-catalogsource/distributed-tracing-install-otel-konflux-catalogsource-commands.sh
  ci-operator/step-registry/distributed-tracing/install/tempo-konflux-catalogsource/distributed-tracing-install-tempo-konflux-catalogsource-commands.sh
Labels: lgtm, approved, rehearsals-ack

#66917 Fix missing params in jq command
  ci-operator/step-registry/junit2reportportal/junit2reportportal-commands.sh
Labels: lgtm, approved, rehearsals-ack

#66914 Add kubectl in PATH
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-master.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.21.yaml
Labels: lgtm, approved, rehearsals-ack

#66924 Exclude test results from junit_cypress-*.xml files
  ci-operator/step-registry/junit2reportportal/junit2reportportal-commands.sh
Labels: lgtm, approved, rehearsals-ack

#66658 fix isPreVersion bug in 4.17
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-main__installer-rehearse-4.17.yaml
  ci-operator/step-registry/mirror-images/by-oc-mirror/mirror-images-by-oc-mirror-commands.sh
Labels: lgtm, approved, rehearsals-ack

#66918 cluster-capi-operator: add techpreview micro upgrades jobs
  ci-operator/config/openshift/cluster-capi-operator/openshift-cluster-capi-operator-main.yaml
  ci-operator/config/openshift/cluster-capi-operator/openshift-cluster-capi-operator-release-4.20.yaml
  ci-operator/config/openshift/cluster-capi-operator/openshift-cluster-capi-operator-release-4.21.yaml
  ci-operator/jobs/openshift/cluster-capi-operator/openshift-cluster-capi-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/cluster-capi-operator/openshift-cluster-capi-operator-release-4.20-presubmits.yaml
  ci-operator/jobs/openshift/cluster-capi-operator/openshift-cluster-capi-operator-release-4.21-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#64412 Disable monitor test service-type-load-balancer-availability and skip etcd testcases
  ci-operator/step-registry/openshift/e2e/libvirt/conf/openshift-e2e-libvirt-conf-commands.sh
  ci-operator/step-registry/openshift/e2e/libvirt/test/openshift-e2e-libvirt-test-commands.sh
Labels: lgtm, approved, lifecycle/stale, rehearsals-ack

#66661 cnf network: setup phase-1 for 4.18 CI lane
  ci-operator/config/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main__cnf-network-phase1-4.18.yaml
  ci-operator/config/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main__cnf-network-phase2-4.18.yaml
  ci-operator/jobs/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main-periodics.yaml
  ci-operator/step-registry/telcov10n/functional/cnf-network/gather-artifacts-from-bastion/OWNERS
  ci-operator/step-registry/telcov10n/functional/cnf-network/gather-artifacts-from-bastion/telcov10n-functional-cnf-network-gather-artifacts-from-bastion-commands.sh
  ci-operator/step-registry/telcov10n/functional/cnf-network/gather-artifacts-from-bastion/telcov10n-functional-cnf-network-gather-artifacts-from-bastion-ref.metadata.json
  ci-operator/step-registry/telcov10n/functional/cnf-network/gather-artifacts-from-bastion/telcov10n-functional-cnf-network-gather-artifacts-from-bastion-ref.yaml
  ci-operator/step-registry/telcov10n/functional/cnf-network/store-artifacts-on-bastion/OWNERS
  ci-operator/step-registry/telcov10n/functional/cnf-network/store-artifacts-on-bastion/telcov10n-functional-cnf-network-store-artifacts-on-bastion-commands.sh
  ci-operator/step-registry/telcov10n/functional/cnf-network/store-artifacts-on-bastion/telcov10n-functional-cnf-network-store-artifacts-on-bastion-ref.metadata.json
  ci-operator/step-registry/telcov10n/functional/cnf-network/store-artifacts-on-bastion/telcov10n-functional-cnf-network-store-artifacts-on-bastion-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#66929 add 'run-integration-tests' label to prow plugin config
  core-services/prow/02_config/_plugins.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#66771 [INTEROP-8269] POC - ROSA HCP Testing for SSO operator
  ci-operator/config/rhbk/sso-test/rhbk-sso-test-main__rhsso-product-ocp4.18-lp-rosa-hypershift.yaml
  ci-operator/jobs/rhbk/sso-test/rhbk-sso-test-main-periodics.yaml
  ci-operator/jobs/rhbk/sso-test/rhbk-sso-test-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#66940 New metal-perfscale-osp cluster lease
  core-services/ci-secret-bootstrap/_config.yaml
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: lgtm, approved, rehearsals-ack

#64969 OCPEDGE-1784: test: change default lvms namespace
  ci-operator/config/openshift/lvm-operator/openshift-lvm-operator-main.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#66386 add cnv ocp 4.20 config
  ci-operator/config/RedHatQE/interop-testing/.config.prowgen
  ci-operator/config/RedHatQE/interop-testing/RedHatQE-interop-testing-master__cnv-odf-ocp4.20-lp-interop.yaml
  ci-operator/jobs/RedHatQE/interop-testing/RedHatQE-interop-testing-master-periodics.yaml
  ci-operator/jobs/RedHatQE/interop-testing/RedHatQE-interop-testing-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#65293 rosa upgrade jobs for perfscale release readiness
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__rosa-4.19-candidate-x86-loaded-upgrade-from-4.18.yaml
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__rosa_hcp-4.19-candidate-x86-loaded-upgrade-from-4.18.yaml
  ci-operator/jobs/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main-periodics.yaml
  ci-operator/jobs/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main-presubmits.yaml
  ci-operator/step-registry/rosa/cluster/upgrade/cluster/rosa-cluster-upgrade-cluster-commands.sh
  ci-operator/step-registry/rosa/cluster/upgrade/cluster/rosa-cluster-upgrade-cluster-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#66944 Add red-hat-konflux bot to list of trusted_apps for stolostron/console
  core-services/prow/02_config/stolostron/console/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#66848 No longer make Konflux jobs optional for TALM
  core-services/prow/02_config/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#66948 Append the other gsutil logs
  ci-operator/step-registry/junit2reportportal/junit2reportportal-commands.sh
Labels: lgtm, approved, rehearsals-ack

#66937 ROX-30071: Change fleetshard-operator Dockerfile location
  ci-operator/config/stackrox/acs-fleet-manager/stackrox-acs-fleet-manager-main.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#66955 Mirror go-toolset 1.24.4 image
  core-services/image-mirroring/_config.yaml
Labels: lgtm, approved, tide/merge-method-squash, rehearsals-ack

#66970 NO-ISSUE: Update build_root for USHIFT 4.20 periodics
  ci-operator/config/openshift/microshift/openshift-microshift-release-4.20__periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#66971 deploy latest toolchain resources
  ci-operator/config/codeready-toolchain/toolchain-e2e/codeready-toolchain-toolchain-e2e-master.yaml
Labels: lgtm, approved, rehearsals-ack

#66963 RHDH re-enable reporting for 1.5 and fix auth-providers links
  ci-operator/jobs/redhat-developer/rhdh/redhat-developer-rhdh-main-periodics.yaml
  ci-operator/jobs/redhat-developer/rhdh/redhat-developer-rhdh-release-1.5-periodics.yaml
  ci-operator/jobs/redhat-developer/rhdh/redhat-developer-rhdh-release-1.6-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#66973 Add installer/release to the owner of qe cloud cluster profiles
  ci-operator/step-registry/cluster-profiles/cluster-profiles-config.yaml
Labels: lgtm, approved, rehearsals-ack

#66893 ci-operator/sandboxed-containers-operator: update candidate job to 4.19
  ci-operator/config/openshift/sandboxed-containers-operator/openshift-sandboxed-containers-operator-devel__downstream-candidate.yaml
Labels: lgtm, approved, rehearsals-ack

#66979 Installer aro wrapper update golangci-lint
  ci-operator/config/openshift/installer-aro-wrapper/openshift-installer-aro-wrapper-release-4.14.yaml
Labels: lgtm, approved, rehearsals-ack

#65289 STOR-2463: Add build files for external-snapshot-metadata fork
  ci-operator/config/openshift/csi-external-snapshot-metadata/OWNERS
  ci-operator/config/openshift/csi-external-snapshot-metadata/openshift-csi-external-snapshot-metadata-main.yaml
  ci-operator/jobs/openshift/csi-external-snapshot-metadata/OWNERS
  ci-operator/jobs/openshift/csi-external-snapshot-metadata/openshift-csi-external-snapshot-metadata-main-postsubmits.yaml
  ci-operator/jobs/openshift/csi-external-snapshot-metadata/openshift-csi-external-snapshot-metadata-main-presubmits.yaml
  core-services/prow/02_config/openshift/csi-external-snapshot-metadata/OWNERS
  core-services/prow/02_config/openshift/csi-external-snapshot-metadata/_pluginconfig.yaml
  core-services/prow/02_config/openshift/csi-external-snapshot-metadata/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#66974 USHIFT-5620: Bare metal tests: lvm only for MicroShift 4.14 and 4.15
  ci-operator/step-registry/openshift/microshift/e2e/bare-metal-tests/openshift-microshift-e2e-bare-metal-tests-commands.sh
  ci-operator/step-registry/openshift/microshift/e2e/bare-metal-tests/openshift-microshift-e2e-bare-metal-tests-workflow.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#66966 [PERFSCALE-3728] Adjust okd 4.19 jobs
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__aws-4.19-okd-x86.yaml
  ci-operator/jobs/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#66985 Remove EO from CLO e2e image build
  ci-operator/config/openshift/cluster-logging-operator/openshift-cluster-logging-operator-master.yaml
  ci-operator/config/openshift/cluster-logging-operator/openshift-cluster-logging-operator-release-6.2.yaml
  ci-operator/config/openshift/cluster-logging-operator/openshift-cluster-logging-operator-release-6.3.yaml
Labels: lgtm, approved, rehearsals-ack

#66996 HyperShift: Fix hypershift-mce-kubevirt-gpu-conformance
  ci-operator/step-registry/hypershift/mce/kubevirt/gpu/nfd-operator/hypershift-mce-kubevirt-gpu-nfd-operator-commands.sh
Labels: lgtm, approved, rehearsals-ack

#66991 remove e2es from kueue main for now.
  ci-operator/config/openshift/kubernetes-sigs-kueue/openshift-kubernetes-sigs-kueue-main.yaml
  ci-operator/jobs/openshift/kubernetes-sigs-kueue/openshift-kubernetes-sigs-kueue-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#66377 CMP-3452: Add test jobs for e2e test purpose
  ci-operator/config/openshift/file-integrity-operator/openshift-file-integrity-operator-master__nightly-4.12.yaml
  ci-operator/config/openshift/file-integrity-operator/openshift-file-integrity-operator-master__nightly-4.13.yaml
  ci-operator/config/openshift/file-integrity-operator/openshift-file-integrity-operator-master__nightly-4.14.yaml
  ci-operator/config/openshift/file-integrity-operator/openshift-file-integrity-operator-master__nightly-4.15.yaml
  ci-operator/config/openshift/file-integrity-operator/openshift-file-integrity-operator-master__nightly-4.16.yaml
  ci-operator/config/openshift/file-integrity-operator/openshift-file-integrity-operator-master__nightly-4.17.yaml
  ci-operator/config/openshift/file-integrity-operator/openshift-file-integrity-operator-master__nightly-4.18.yaml
  ci-operator/config/openshift/file-integrity-operator/openshift-file-integrity-operator-master__nightly-4.19.yaml
  ci-operator/config/openshift/file-integrity-operator/openshift-file-integrity-operator-master__nightly-4.20.yaml
  ci-operator/config/openshift/file-integrity-operator/openshift-file-integrity-operator-release-4.10.yaml
  ci-operator/config/openshift/file-integrity-operator/openshift-file-integrity-operator-release-4.11.yaml
  ci-operator/config/openshift/file-integrity-operator/openshift-file-integrity-operator-release-4.4.yaml
  ci-operator/config/openshift/file-integrity-operator/openshift-file-integrity-operator-release-4.5.yaml
  ci-operator/config/openshift/file-integrity-operator/openshift-file-integrity-operator-release-4.6.yaml
  ci-operator/config/openshift/file-integrity-operator/openshift-file-integrity-operator-release-4.7.yaml
  ci-operator/config/openshift/file-integrity-operator/openshift-file-integrity-operator-release-4.8.yaml
  ci-operator/config/openshift/file-integrity-operator/openshift-file-integrity-operator-release-4.9.yaml
  ci-operator/jobs/openshift/file-integrity-operator/openshift-file-integrity-operator-master-periodics.yaml
  ci-operator/jobs/openshift/file-integrity-operator/openshift-file-integrity-operator-release-4.10-postsubmits.yaml
  ci-operator/jobs/openshift/file-integrity-operator/openshift-file-integrity-operator-release-4.10-presubmits.yaml
  ci-operator/jobs/openshift/file-integrity-operator/openshift-file-integrity-operator-release-4.11-postsubmits.yaml
  ci-operator/jobs/openshift/file-integrity-operator/openshift-file-integrity-operator-release-4.11-presubmits.yaml
  ci-operator/jobs/openshift/file-integrity-operator/openshift-file-integrity-operator-release-4.4-postsubmits.yaml
  ci-operator/jobs/openshift/file-integrity-operator/openshift-file-integrity-operator-release-4.4-presubmits.yaml
  ci-operator/jobs/openshift/file-integrity-operator/openshift-file-integrity-operator-release-4.5-postsubmits.yaml
  ci-operator/jobs/openshift/file-integrity-operator/openshift-file-integrity-operator-release-4.5-presubmits.yaml
  ci-operator/jobs/openshift/file-integrity-operator/openshift-file-integrity-operator-release-4.6-postsubmits.yaml
  ci-operator/jobs/openshift/file-integrity-operator/openshift-file-integrity-operator-release-4.6-presubmits.yaml
  ci-operator/jobs/openshift/file-integrity-operator/openshift-file-integrity-operator-release-4.7-postsubmits.yaml
  ci-operator/jobs/openshift/file-integrity-operator/openshift-file-integrity-operator-release-4.7-presubmits.yaml
  ci-operator/jobs/openshift/file-integrity-operator/openshift-file-integrity-operator-release-4.8-postsubmits.yaml
  ci-operator/jobs/openshift/file-integrity-operator/openshift-file-integrity-operator-release-4.8-presubmits.yaml
  ci-operator/jobs/openshift/file-integrity-operator/openshift-file-integrity-operator-release-4.9-postsubmits.yaml
  ci-operator/jobs/openshift/file-integrity-operator/openshift-file-integrity-operator-release-4.9-presubmits.yaml
  ci-operator/step-registry/file-integrity/konflux-catalogsource/file-integrity-konflux-catalogsource-commands.sh
  ci-operator/step-registry/file-integrity/konflux-catalogsource/file-integrity-konflux-catalogsource-ref.yaml
  ci-operator/step-registry/optional-operators/operator-sdk/non-ci-bundle-image/OWNERS
  ci-operator/step-registry/optional-operators/operator-sdk/non-ci-bundle-image/optional-operators-operator-sdk-non-ci-bundle-image-commands.sh
  ci-operator/step-registry/optional-operators/operator-sdk/non-ci-bundle-image/optional-operators-operator-sdk-non-ci-bundle-image-ref.metadata.json
  ci-operator/step-registry/optional-operators/operator-sdk/non-ci-bundle-image/optional-operators-operator-sdk-non-ci-bundle-image-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#66769 Disable cache for squid proxy
  ci-operator/step-registry/ignition/bastionhost/ignition-bastionhost-commands.sh
Labels: lgtm, approved, rehearsals-ack

#66969 Set default REPORTPORTAL_PROJECT to prow
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__arm64-nightly.yaml
  ci-operator/step-registry/junit2reportportal/junit2reportportal-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#66877 OCPQE-30168: Add private proxy rosa hcp jobs back in 4.17+
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#67004 Limit those tests jobs on clusters with capabilities intranet
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__arm64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#66998 Updates for OVMS-2025.2 release
  ci-operator/config/red-hat-data-services/openvino_model_server/red-hat-data-services-openvino_model_server-rhoai-2.23.yaml
  ci-operator/jobs/red-hat-data-services/openvino_model_server/red-hat-data-services-openvino_model_server-rhoai-2.23-postsubmits.yaml
  ci-operator/jobs/red-hat-data-services/openvino_model_server/red-hat-data-services-openvino_model_server-rhoai-2.23-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#67010 Update ipi-deprovision tools
  clusters/app.ci/ipi-deprovision/ipi-deprovision-bc.yaml
Labels: lgtm, approved, rehearsals-ack

#67016 fix: rhdh-test-instance new line char issue in duration
  ci-operator/step-registry/redhat-developer/rhdh-test-instance/redhat-developer-rhdh-test-instance-commands.sh
Labels: lgtm, approved, rehearsals-ack

#67015 Fix wrong cron string
  ci-operator/jobs/infra-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#66843 metallb-operator: bump sdk version
  ci-operator/config/openshift/metallb-operator/openshift-metallb-operator-main.yaml
Labels: lgtm, approved, rehearsals-ack

#67021 Fix ipi-deprovision image name
  clusters/app.ci/ipi-deprovision/ipi-deprovision-bc.yaml
Labels: lgtm, approved, rehearsals-ack

#66931 OPRUN-3963: openshift-operator: [OTE] add call to make verify
  ci-operator/config/openshift/operator-framework-operator-controller/openshift-operator-framework-operator-controller-main.yaml
  ci-operator/config/openshift/operator-framework-operator-controller/openshift-operator-framework-operator-controller-release-4.20.yaml
  ci-operator/config/openshift/operator-framework-operator-controller/openshift-operator-framework-operator-controller-release-4.21.yaml
  ci-operator/jobs/openshift/operator-framework-operator-controller/openshift-operator-framework-operator-controller-main-presubmits.yaml
  ci-operator/jobs/openshift/operator-framework-operator-controller/openshift-operator-framework-operator-controller-release-4.20-presubmits.yaml
  ci-operator/jobs/openshift/operator-framework-operator-controller/openshift-operator-framework-operator-controller-release-4.21-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#66945 start mechanism to launch ARO-HCP testing
  ci-operator/config/Azure/ARO-HCP/Azure-ARO-HCP-main.yaml
  ci-operator/config/Azure/ARO-HCP/Azure-ARO-HCP-main__periodic.yaml
  ci-operator/jobs/Azure/ARO-HCP/Azure-ARO-HCP-main-periodics.yaml
  ci-operator/jobs/Azure/ARO-HCP/Azure-ARO-HCP-main-presubmits.yaml
  ci-operator/step-registry/aro-hcp/tests/OWNERS
  ci-operator/step-registry/aro-hcp/tests/run-aro-hcp-tests/OWNERS
  ci-operator/step-registry/aro-hcp/tests/run-aro-hcp-tests/aro-hcp-tests-run-aro-hcp-tests-commands.sh
  ci-operator/step-registry/aro-hcp/tests/run-aro-hcp-tests/aro-hcp-tests-run-aro-hcp-tests-ref.metadata.json
  ci-operator/step-registry/aro-hcp/tests/run-aro-hcp-tests/aro-hcp-tests-run-aro-hcp-tests-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#66990 onboard kueue release 0.12 to prow
  ci-operator/config/openshift/kubernetes-sigs-kueue/openshift-kubernetes-sigs-kueue-release-0.12.yaml
  ci-operator/jobs/openshift/kubernetes-sigs-kueue/openshift-kubernetes-sigs-kueue-release-0.12-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#67036 cnf network: added 4.19 CI lane
  ci-operator/config/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main__cnf-network-phase1-4.19.yaml
  ci-operator/jobs/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main-periodics.yaml
  ci-operator/step-registry/telcov10n/functional/cnf-network/schedule-job/OWNERS
  ci-operator/step-registry/telcov10n/functional/cnf-network/schedule-job/telcov10n-functional-cnf-network-schedule-job-commands.sh
  ci-operator/step-registry/telcov10n/functional/cnf-network/schedule-job/telcov10n-functional-cnf-network-schedule-job-ref.metadata.json
  ci-operator/step-registry/telcov10n/functional/cnf-network/schedule-job/telcov10n-functional-cnf-network-schedule-job-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#67034 Update DNS to include machine C155F2U33
  clusters/build-clusters/build10/coredns/coredns_config.yaml
Labels: lgtm, approved, rehearsals-ack

#66112 Fix subscription not found issue in step upi-install-azure with mini-perm
  ci-operator/step-registry/azure/provision/service-principal/minimal-permission/azure-provision-service-principal-minimal-permission-commands.sh
Labels: lgtm, approved, rehearsals-ack

#67060 Send results to prow project in ReportPortal
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__arm64-nightly.yaml
Labels: lgtm, approved, rehearsals-ack

#67050 OCP 4.19 clusterpool for Serverless
  clusters/hosted-mgmt/hive/pools/serverless/serverless-ocp-4-19-amd64-aws-us-east-1_clusterpool.yaml
Labels: lgtm, approved, rehearsals-ack

#66922 Update ironic containers base images for OCP 4.20
  ci-operator/config/openshift/ironic-agent-image/openshift-ironic-agent-image-main.yaml
  ci-operator/config/openshift/ironic-agent-image/openshift-ironic-agent-image-main__prevalidation.yaml
  ci-operator/config/openshift/ironic-agent-image/openshift-ironic-agent-image-release-4.20.yaml
  ci-operator/config/openshift/ironic-agent-image/openshift-ironic-agent-image-release-4.20__prevalidation.yaml
  ci-operator/config/openshift/ironic-agent-image/openshift-ironic-agent-image-release-4.21.yaml
  ci-operator/config/openshift/ironic-image/openshift-ironic-image-main.yaml
  ci-operator/config/openshift/ironic-image/openshift-ironic-image-main__prevalidation.yaml
  ci-operator/config/openshift/ironic-image/openshift-ironic-image-release-4.20.yaml
  ci-operator/config/openshift/ironic-image/openshift-ironic-image-release-4.20__prevalidation.yaml
  ci-operator/config/openshift/ironic-image/openshift-ironic-image-release-4.21.yaml
Labels: lgtm, approved, rehearsals-ack

#67048 Adjust test frequency for fips-check jobs and file integrity operator jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#66665 RHOAIENG-28826: update opendatahub-io-notebooks-main.yaml
  ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-main.yaml
  ci-operator/jobs/opendatahub-io/notebooks/opendatahub-io-notebooks-main-postsubmits.yaml
  ci-operator/jobs/opendatahub-io/notebooks/opendatahub-io-notebooks-main-presubmits.yaml
Labels: lgtm, approved, tide/merge-method-squash, rehearsals-ack, jira/valid-reference

#67062 Sail operator: skip e2e test execution on PR with only changes on docs files
  ci-operator/config/openshift-service-mesh/sail-operator/openshift-service-mesh-sail-operator-main__ocp-4.18.yaml
  ci-operator/config/openshift-service-mesh/sail-operator/openshift-service-mesh-sail-operator-main__ocp-4.19.yaml
  ci-operator/jobs/openshift-service-mesh/sail-operator/openshift-service-mesh-sail-operator-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#67066 CNTRLPLANE-1113: Skip E2E job execution once renovate config is modified
  ci-operator/config/openshift/hypershift/openshift-hypershift-main.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-main__okd-scos.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#67072 Add steps to delete all tracked ARO-HCP resources on Azure
  ci-operator/step-registry/aro-hcp/provision/create-prereq-resources/aro-hcp-provision-create-prereq-resources-commands.sh
  ci-operator/step-registry/aro-hcp/provision/delete-all-tracked-hcp-clusters/OWNERS
  ci-operator/step-registry/aro-hcp/provision/delete-all-tracked-hcp-clusters/aro-hcp-provision-delete-all-tracked-hcp-clusters-commands.sh
  ci-operator/step-registry/aro-hcp/provision/delete-all-tracked-hcp-clusters/aro-hcp-provision-delete-all-tracked-hcp-clusters-ref.metadata.json
  ci-operator/step-registry/aro-hcp/provision/delete-all-tracked-hcp-clusters/aro-hcp-provision-delete-all-tracked-hcp-clusters-ref.yaml
  ci-operator/step-registry/aro-hcp/provision/delete-all-tracked-resource-groups/OWNERS
  ci-operator/step-registry/aro-hcp/provision/delete-all-tracked-resource-groups/aro-hcp-provision-delete-all-tracked-resource-groups-commands.sh
  ci-operator/step-registry/aro-hcp/provision/delete-all-tracked-resource-groups/aro-hcp-provision-delete-all-tracked-resource-groups-ref.metadata.json
  ci-operator/step-registry/aro-hcp/provision/delete-all-tracked-resource-groups/aro-hcp-provision-delete-all-tracked-resource-groups-ref.yaml
  ci-operator/step-registry/aro-hcp/provision/teardown-cluster/aro-hcp-provision-teardown-cluster-chain.yaml
Labels: lgtm, approved, rehearsals-ack

#67085 Revert "reduce the amount of resource slice requests for the aws account"
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: lgtm, approved, rehearsals-ack
