Repository openshift/release, pull requests merged in 2025-08, with the labels that each got.

#67690 Apply junit2reportportal to agent install workflows
  ci-operator/step-registry/cucushift/agent/oci/cucushift-agent-oci-workflow.yaml
  ci-operator/step-registry/cucushift/agent/vsphere/disconnected/dualstack/install/sno/cucushift-agent-vsphere-disconnected-dualstack-install-sno-workflow.yaml
  ci-operator/step-registry/cucushift/agent/vsphere/disconnected/install/compact/cucushift-agent-vsphere-disconnected-install-compact-workflow.yaml
  ci-operator/step-registry/cucushift/agent/vsphere/disconnected/install/day2/add-nodes/cucushift-agent-vsphere-disconnected-install-day2-add-nodes-workflow.yaml
  ci-operator/step-registry/cucushift/agent/vsphere/disconnected/install/ha/cucushift-agent-vsphere-disconnected-install-ha-workflow.yaml
  ci-operator/step-registry/cucushift/agent/vsphere/disconnected/install/sno/cucushift-agent-vsphere-disconnected-install-sno-workflow.yaml
  ci-operator/step-registry/cucushift/agent/vsphere/dualstack/install/compact/cucushift-agent-vsphere-dualstack-install-compact-workflow.yaml
  ci-operator/step-registry/cucushift/agent/vsphere/dualstack/install/day2/add-nodes/cucushift-agent-vsphere-dualstack-install-day2-add-nodes-workflow.yaml
  ci-operator/step-registry/cucushift/agent/vsphere/dualstack/install/ha/cucushift-agent-vsphere-dualstack-install-ha-workflow.yaml
  ci-operator/step-registry/cucushift/agent/vsphere/dualstack/install/sno/cucushift-agent-vsphere-dualstack-install-sno-workflow.yaml
  ci-operator/step-registry/cucushift/agent/vsphere/install/compact/cucushift-agent-vsphere-install-compact-workflow.yaml
  ci-operator/step-registry/cucushift/agent/vsphere/install/day2/add-nodes/cucushift-agent-vsphere-install-day2-add-nodes-workflow.yaml
  ci-operator/step-registry/cucushift/agent/vsphere/install/ha/cucushift-agent-vsphere-install-ha-workflow.yaml
  ci-operator/step-registry/cucushift/agent/vsphere/install/sno/cucushift-agent-vsphere-install-sno-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#67701 Apply junit2reportportal to baremetal lab workflows
  ci-operator/step-registry/baremetal/lab/agent/install/network/dynamic/baremetal-lab-agent-install-network-dynamic-workflow.yaml
  ci-operator/step-registry/baremetal/lab/agent/install/network/dynamic/day2/baremetal-lab-agent-install-network-dynamic-day2-workflow.yaml
  ci-operator/step-registry/baremetal/lab/agent/install/network/dynamic/disconnected/baremetal-lab-agent-install-network-dynamic-disconnected-workflow.yaml
  ci-operator/step-registry/baremetal/lab/agent/install/network/dynamic/disconnected/day2/baremetal-lab-agent-install-network-dynamic-disconnected-day2-workflow.yaml
  ci-operator/step-registry/baremetal/lab/agent/install/network/dynamic/ephemeral/baremetal-lab-agent-install-network-dynamic-ephemeral-workflow.yaml
  ci-operator/step-registry/baremetal/lab/agent/install/network/dynamic/ipv6/baremetal-lab-agent-install-network-dynamic-ipv6-workflow.yaml
  ci-operator/step-registry/baremetal/lab/agent/install/network/static/3-plus-1/baremetal-lab-agent-install-network-static-3-plus-1-workflow.yaml
  ci-operator/step-registry/baremetal/lab/agent/install/network/static/baremetal-lab-agent-install-network-static-workflow.yaml
  ci-operator/step-registry/baremetal/lab/agent/install/network/static/day2/baremetal-lab-agent-install-network-static-day2-workflow.yaml
  ci-operator/step-registry/baremetal/lab/agent/install/network/static/disconnected/baremetal-lab-agent-install-network-static-disconnected-workflow.yaml
  ci-operator/step-registry/baremetal/lab/agent/install/network/static/disconnected/day2/baremetal-lab-agent-install-network-static-disconnected-day2-workflow.yaml
  ci-operator/step-registry/baremetal/lab/agent/install/network/static/disconnected/proxy/baremetal-lab-agent-install-network-static-disconnected-proxy-workflow.yaml
  ci-operator/step-registry/baremetal/lab/agent/install/network/static/ephemeral/baremetal-lab-agent-install-network-static-ephemeral-workflow.yaml
  ci-operator/step-registry/baremetal/lab/agent/install/pxe/baremetal-lab-agent-install-pxe-workflow.yaml
  ci-operator/step-registry/baremetal/lab/agent/install/pxe/day2/baremetal-lab-agent-install-pxe-day2-workflow.yaml
  ci-operator/step-registry/baremetal/lab/agent/install/pxe/day2/disconnected/baremetal-lab-agent-install-pxe-day2-disconnected-workflow.yaml
  ci-operator/step-registry/baremetal/lab/agent/manual/baremetal-lab-agent-manual-workflow.yaml
  ci-operator/step-registry/baremetal/lab/agent/monitoring/baremetal-lab-agent-monitoring-workflow.yaml
  ci-operator/step-registry/baremetal/lab/ipi/baremetal-lab-ipi-workflow.yaml
  ci-operator/step-registry/baremetal/lab/ipi/disconnected/baremetal-lab-ipi-disconnected-workflow.yaml
  ci-operator/step-registry/baremetal/lab/ipi/external-lb/baremetal-lab-ipi-external-lb-workflow.yaml
  ci-operator/step-registry/baremetal/lab/ipi/virtual-media/baremetal-lab-ipi-virtual-media-workflow.yaml
  ci-operator/step-registry/baremetal/lab/ipi/virtual-media/ipv6/static/baremetal-lab-ipi-virtual-media-ipv6-static-workflow.yaml
  ci-operator/step-registry/baremetal/lab/sno/baremetal-lab-sno-workflow.yaml
  ci-operator/step-registry/baremetal/lab/upi/baremetal-lab-upi-workflow.yaml
  ci-operator/step-registry/baremetal/lab/upi/dual-stack/baremetal-lab-upi-dual-stack-workflow.yaml
  ci-operator/step-registry/baremetal/lab/upi/install/disconnected/baremetal-lab-upi-install-disconnected-workflow.yaml
  ci-operator/step-registry/baremetal/lab/upi/ipv6/static/baremetal-lab-upi-ipv6-static-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#67742 Fix attribute cloud_provider for powervs
  ci-operator/step-registry/junit2reportportal/junit2reportportal-commands.sh
Labels: lgtm, approved, rehearsals-ack

#67663 boskos: add OADP QE quota slice resources for cluster profile
  ci-operator/step-registry/cluster-profiles/cluster-profiles-config.yaml
  core-services/prow/02_config/_boskos.yaml
  core-services/prow/02_config/generate-boskos.py
Labels: lgtm, approved, rehearsals-ack

#67460 KATA-4005 md5sum for scratch rpm upload
  ci-operator/config/openshift/sandboxed-containers-operator/README.md
  ci-operator/config/openshift/sandboxed-containers-operator/openshift-sandboxed-containers-operator-devel__downstream-candidate.yaml
  ci-operator/config/openshift/sandboxed-containers-operator/openshift-sandboxed-containers-operator-devel__downstream-release.yaml
  ci-operator/step-registry/sandboxed-containers-operator/get-kata-rpm/sandboxed-containers-operator-get-kata-rpm-commands.sh
  ci-operator/step-registry/sandboxed-containers-operator/get-kata-rpm/sandboxed-containers-operator-get-kata-rpm-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#67732 openshift-psap/topsail: remove the rhoai tests
  ci-operator/config/openshift-psap/topsail/openshift-psap-topsail-main__rhoai.yaml
  ci-operator/jobs/openshift-psap/topsail/openshift-psap-topsail-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#67624 CORS-4027: Updating feature gate name to GCPClusterHostedDNSInstall
  ci-operator/config/openshift-priv/installer/openshift-priv-installer-main.yaml
  ci-operator/config/openshift-priv/installer/openshift-priv-installer-release-4.20.yaml
  ci-operator/config/openshift-priv/installer/openshift-priv-installer-release-4.21.yaml
  ci-operator/config/openshift/installer/openshift-installer-main.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.20.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.21.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__multi-nightly.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.20.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#67725 test ovn PR 2655, increase udn test churn duration
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-master.yaml
Labels: lgtm, approved, rehearsals-ack

#67504 [PERFSCALE-3245] Add hybrid worker scenario to jetlag CI
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__metal-x86.yaml
  ci-operator/jobs/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main-presubmits.yaml
  ci-operator/step-registry/openshift-qe/installer/bm/deploy/openshift-qe-installer-bm-deploy-commands.sh
  ci-operator/step-registry/openshift-qe/installer/bm/deploy/openshift-qe-installer-bm-deploy-ref.yaml
  ci-operator/step-registry/openshift-qe/installer/bm/foreman/openshift-qe-installer-bm-foreman-commands.sh
Labels: lgtm, approved, rehearsals-ack

#67755 chore: add additional reviewers and approvers to AKS OWNERS files
  ci-operator/step-registry/aks/OWNERS
  ci-operator/step-registry/aks/deprovision/OWNERS
  ci-operator/step-registry/aks/deprovision/aks-deprovision-ref.metadata.json
  ci-operator/step-registry/aks/provision/OWNERS
  ci-operator/step-registry/aks/provision/aks-provision-ref.metadata.json
Labels: lgtm, approved, rehearsals-ack

#67359 SPLAT-2340: Disable storage operator for hybrid env during install
  ci-operator/config/openshift-priv/installer/openshift-priv-installer-main.yaml
  ci-operator/config/openshift-priv/installer/openshift-priv-installer-release-4.20.yaml
  ci-operator/config/openshift-priv/installer/openshift-priv-installer-release-4.21.yaml
  ci-operator/config/openshift/installer/openshift-installer-main.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.20.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.21.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.20.yaml
  ci-operator/step-registry/ipi/install/vsphere/virt/ipi-install-vsphere-virt-commands.sh
  ci-operator/step-registry/ipi/install/vsphere/virt/ipi-install-vsphere-virt-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#67756 vsphere - vm host zonal, change to fs to tp
  ci-operator/config/openshift/installer/openshift-installer-main.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.18.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.19.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.20.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.21.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-main-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.18-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.19-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.20-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.21-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#67724 Updating orion version to v0.0.21
  ci-operator/step-registry/openshift-qe/orion/cluster-density/openshift-qe-orion-cluster-density-ref.yaml
  ci-operator/step-registry/openshift-qe/orion/crd-scale/openshift-qe-orion-crd-scale-ref.yaml
  ci-operator/step-registry/openshift-qe/orion/data-path/openshift-qe-orion-data-path-ref.yaml
  ci-operator/step-registry/openshift-qe/orion/node-density-cni/openshift-qe-orion-node-density-cni-ref.yaml
  ci-operator/step-registry/openshift-qe/orion/node-density/openshift-qe-orion-node-density-ref.yaml
  ci-operator/step-registry/openshift-qe/orion/openshift-qe-orion-commands.sh
  ci-operator/step-registry/openshift-qe/orion/virt-density/openshift-qe-orion-virt-density-ref.yaml
  ci-operator/step-registry/openshift-qe/orion/virt-udn-density/openshift-qe-orion-virt-udn-density-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#66980 CNTRLPLANE-945: Add presubmits to test ExternalOIDC payload tests in CI
  ci-operator/config/openshift/cluster-authentication-operator/openshift-cluster-authentication-operator-master.yaml
  ci-operator/jobs/openshift/cluster-authentication-operator/openshift-cluster-authentication-operator-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#67767 telcov10- Use llc-cnf instead of llc-cnf-tests
  ci-operator/step-registry/telco5g/cluster-setup/telco5g-cluster-setup-commands.sh
Labels: lgtm, approved, rehearsals-ack

#67657 NO-ISSUE: Change bundle jobs to set specific bundle rather than operators
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-cloud_hotfix_releases.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-cloud_hotfix_releases-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-periodics.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#67721 rename user-provisioned-dns to custom-dns
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__multi-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__multi-nightly.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/custom-dns/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/custom-dns/cucushift-installer-rehearse-gcp-ipi-custom-dns-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/custom-dns/cucushift-installer-rehearse-gcp-ipi-custom-dns-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/custom-dns/private/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/custom-dns/private/cucushift-installer-rehearse-gcp-ipi-custom-dns-private-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/custom-dns/private/cucushift-installer-rehearse-gcp-ipi-custom-dns-private-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/custom-dns/private/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/custom-dns/private/provision/cucushift-installer-rehearse-gcp-ipi-custom-dns-private-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/custom-dns/private/provision/cucushift-installer-rehearse-gcp-ipi-custom-dns-private-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/custom-dns/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/custom-dns/provision/cucushift-installer-rehearse-gcp-ipi-custom-dns-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/custom-dns/provision/cucushift-installer-rehearse-gcp-ipi-custom-dns-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/user-provisioned-dns/private/cucushift-installer-rehearse-gcp-ipi-user-provisioned-dns-private-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/user-provisioned-dns/private/provision/cucushift-installer-rehearse-gcp-ipi-user-provisioned-dns-private-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/user-provisioned-dns/provision/cucushift-installer-rehearse-gcp-ipi-user-provisioned-dns-provision-chain.metadata.json
Labels: lgtm, approved, rehearsals-ack

#67772 MULTIARCH-5196: increase the grace_period
  ci-operator/step-registry/upi/install/heterogeneous/powervs/upi-install-heterogeneous-powervs-ref.yaml
  ci-operator/step-registry/upi/install/heterogeneous/vpc/upi-install-heterogeneous-vpc-ref.yaml
  ci-operator/step-registry/upi/install/powervs/cluster/upi-install-powervs-cluster-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#67764 Aks-hcp-nodepool
  ci-operator/step-registry/aks/provision/aks-provision-commands.sh
  ci-operator/step-registry/aks/provision/aks-provision-ref.yaml
  ci-operator/step-registry/hypershift/azure/aks/e2e/hypershift-azure-aks-e2e-workflow.yaml
  ci-operator/step-registry/hypershift/azure/run-e2e/hypershift-azure-run-e2e-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#67771 oadp: update cluster profile from oadp-qe
  ci-operator/step-registry/cluster-profiles/cluster-profiles-config.yaml
Labels: lgtm, approved, rehearsals-ack

#67785 Adding opendatahub-tests image mirroring for 2.19 and 2.22 tags
  core-services/image-mirroring/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#67788 telco5g: Remove manual plan in CI jobs
  ci-operator/step-registry/telco5g/cluster-setup/telco5g-cluster-setup-commands.sh
  ci-operator/step-registry/telco5g/hcp-cluster-setup/telco5g-hcp-cluster-setup-commands.sh
Labels: lgtm, approved, rehearsals-ack

#67632 SPLAT-2345: Added ability to add multiple agnostic vm / nodes to vsphere mixed env
  ci-operator/step-registry/ipi/deprovision/vsphere/virt/ipi-deprovision-vsphere-virt-commands.sh
  ci-operator/step-registry/ipi/deprovision/vsphere/virt/ipi-deprovision-vsphere-virt-ref.yaml
  ci-operator/step-registry/ipi/install/vsphere/virt/ipi-install-vsphere-virt-commands.sh
  ci-operator/step-registry/ipi/install/vsphere/virt/ipi-install-vsphere-virt-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#67803 ci: increase hypershift AKS test frequency from 6h to 2h
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.20__periodics.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.20-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#67746 Add attribute architecture support for s390x
  ci-operator/step-registry/junit2reportportal/junit2reportportal-commands.sh
Labels: lgtm, approved, rehearsals-ack

#67787 only generate one installation test case in junit xml
  ci-operator/step-registry/junit2reportportal/junit2reportportal-commands.sh
Labels: lgtm, approved, rehearsals-ack

#67782 oadp: explicitly define the TEST_FOCUS variable
  ci-operator/config/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-main__oadp1.4-ocp4.17-lp-interop.yaml
  ci-operator/config/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-main__oadp1.4-ocp4.17-lp-rosa-classic.yaml
  ci-operator/config/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-oadp-1.4__oadp1.4-ocp4.18-lp-interop.yaml
  ci-operator/config/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-oadp-1.5__oadp1.5-ocp4.20-lp-interop.yaml
  ci-operator/jobs/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-main-periodics.yaml
  ci-operator/jobs/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-oadp-1.4-periodics.yaml
  ci-operator/jobs/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-oadp-1.5-periodics.yaml
  ci-operator/step-registry/oadp/execute-tests/oadp-execute-tests-commands.sh
Labels: lgtm, approved, rehearsals-ack

#67206 STOR-2374: Add aws efs single zone CI jobs
  ci-operator/config/openshift/csi-operator/openshift-csi-operator-main.yaml
  ci-operator/jobs/openshift/csi-operator/openshift-csi-operator-main-presubmits.yaml
  ci-operator/step-registry/aws/provision/vpc/shared/aws-provision-vpc-shared-commands.sh
  ci-operator/step-registry/aws/provision/vpc/shared/aws-provision-vpc-shared-ref.yaml
  ci-operator/step-registry/openshift/e2e/aws/csi/efs/openshift-e2e-aws-csi-efs-workflow.yaml
  ci-operator/step-registry/storage/create/csi-aws-efs/cross-account/storage-create-csi-aws-efs-cross-account-commands.sh
  ci-operator/step-registry/storage/create/csi-aws-efs/cross-account/storage-create-csi-aws-efs-cross-account-ref.yaml
  ci-operator/step-registry/storage/create/csi-aws-efs/storage-create-csi-aws-efs-commands.sh
  ci-operator/step-registry/storage/create/csi-aws-efs/storage-create-csi-aws-efs-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#67496 SPLAT-2136: CI implementation for Azure multiDisk support
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__multi-nightly.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-main__installer-rehearse-4.20.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20-periodics.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-main-periodics.yaml
  ci-operator/step-registry/cucushift/installer/check/azure/multidisk/OWNERS
  ci-operator/step-registry/cucushift/installer/check/azure/multidisk/cucushift-installer-check-azure-multidisk-commands.sh
  ci-operator/step-registry/cucushift/installer/check/azure/multidisk/cucushift-installer-check-azure-multidisk-ref.metadata.json
  ci-operator/step-registry/cucushift/installer/check/azure/multidisk/cucushift-installer-check-azure-multidisk-ref.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/multidisk/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/multidisk/cucushift-installer-rehearse-azure-ipi-multidisk-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/multidisk/cucushift-installer-rehearse-azure-ipi-multidisk-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/multidisk/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/multidisk/provision/cucushift-installer-rehearse-azure-ipi-multidisk-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/azure/ipi/multidisk/provision/cucushift-installer-rehearse-azure-ipi-multidisk-provision-chain.yaml
  ci-operator/step-registry/ipi/conf/azure/multidisk/ipi-conf-azure-multidisk-commands.sh
  ci-operator/step-registry/ipi/conf/azure/multidisk/ipi-conf-azure-multidisk-ref.yaml
  ci-operator/step-registry/ipi/install/install/ipi-install-install-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#67331 Stackrox: Add OCP 4.18,4.19 ppc64le targets and increase timeout.
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-periodics.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-presubmits.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#67819 [Streams for Apache Kafka] Add mapping for Streams 3.0.0 after release and remove older versions
  core-services/image-mirroring/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#67820 Set allow_skip_on_success to true for e2e-aws jobs
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-master.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.10.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.11.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.12.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.13.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.21.yaml
Labels: lgtm, approved, rehearsals-ack

#66984 Cluster deployment in NTO env - Prow
  ci-operator/config/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main__compute-nto.yaml
  ci-operator/jobs/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main-periodics.yaml
  ci-operator/step-registry/telcov10n/functional/OWNERS
  ci-operator/step-registry/telcov10n/functional/compute-nto/OWNERS
  ci-operator/step-registry/telcov10n/functional/compute-nto/clone-z-stream-issue/OWNERS
  ci-operator/step-registry/telcov10n/functional/compute-nto/clone-z-stream-issue/telcov10n-functional-compute-nto-clone-z-stream-issue-commands.sh
  ci-operator/step-registry/telcov10n/functional/compute-nto/clone-z-stream-issue/telcov10n-functional-compute-nto-clone-z-stream-issue-ref.metadata.json
  ci-operator/step-registry/telcov10n/functional/compute-nto/clone-z-stream-issue/telcov10n-functional-compute-nto-clone-z-stream-issue-ref.yaml
  ci-operator/step-registry/telcov10n/functional/compute-nto/config/OWNERS
  ci-operator/step-registry/telcov10n/functional/compute-nto/config/telcov10n-functional-compute-nto-config-commands.sh
  ci-operator/step-registry/telcov10n/functional/compute-nto/config/telcov10n-functional-compute-nto-config-ref.metadata.json
  ci-operator/step-registry/telcov10n/functional/compute-nto/config/telcov10n-functional-compute-nto-config-ref.yaml
  ci-operator/step-registry/telcov10n/functional/compute-nto/eco-gotests/OWNERS
  ci-operator/step-registry/telcov10n/functional/compute-nto/eco-gotests/telcov10n-functional-compute-nto-eco-gotests-commands.sh
  ci-operator/step-registry/telcov10n/functional/compute-nto/eco-gotests/telcov10n-functional-compute-nto-eco-gotests-ref.metadata.json
  ci-operator/step-registry/telcov10n/functional/compute-nto/eco-gotests/telcov10n-functional-compute-nto-eco-gotests-ref.yaml
  ci-operator/step-registry/telcov10n/functional/compute-nto/ocp-deploy/OWNERS
  ci-operator/step-registry/telcov10n/functional/compute-nto/ocp-deploy/telcov10n-functional-compute-nto-ocp-deploy-commands.sh
  ci-operator/step-registry/telcov10n/functional/compute-nto/ocp-deploy/telcov10n-functional-compute-nto-ocp-deploy-ref.metadata.json
  ci-operator/step-registry/telcov10n/functional/compute-nto/ocp-deploy/telcov10n-functional-compute-nto-ocp-deploy-ref.yaml
  ci-operator/step-registry/telcov10n/functional/compute-nto/ocp-setup/OWNERS
  ci-operator/step-registry/telcov10n/functional/compute-nto/ocp-setup/telcov10n-functional-compute-nto-ocp-setup-workflow.metadata.json
  ci-operator/step-registry/telcov10n/functional/compute-nto/ocp-setup/telcov10n-functional-compute-nto-ocp-setup-workflow.yaml
  ci-operator/step-registry/telcov10n/functional/compute-nto/reporter/OWNERS
  ci-operator/step-registry/telcov10n/functional/compute-nto/reporter/telcov10n-functional-compute-nto-reporter-commands.sh
  ci-operator/step-registry/telcov10n/functional/compute-nto/reporter/telcov10n-functional-compute-nto-reporter-ref.metadata.json
  ci-operator/step-registry/telcov10n/functional/compute-nto/reporter/telcov10n-functional-compute-nto-reporter-ref.yaml
  ci-operator/step-registry/telcov10n/functional/compute-nto/send-slack-notification/OWNERS
  ci-operator/step-registry/telcov10n/functional/compute-nto/send-slack-notification/telcov10n-functional-compute-nto-send-slack-notification-commands.sh
  ci-operator/step-registry/telcov10n/functional/compute-nto/send-slack-notification/telcov10n-functional-compute-nto-send-slack-notification-ref.metadata.json
  ci-operator/step-registry/telcov10n/functional/compute-nto/send-slack-notification/telcov10n-functional-compute-nto-send-slack-notification-ref.yaml
  ci-operator/step-registry/telcov10n/functional/compute-nto/setup-cluster-env/OWNERS
  ci-operator/step-registry/telcov10n/functional/compute-nto/setup-cluster-env/telcov10n-functional-compute-nto-setup-cluster-env-commands.sh
  ci-operator/step-registry/telcov10n/functional/compute-nto/setup-cluster-env/telcov10n-functional-compute-nto-setup-cluster-env-ref.metadata.json
  ci-operator/step-registry/telcov10n/functional/compute-nto/setup-cluster-env/telcov10n-functional-compute-nto-setup-cluster-env-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#63343 CLID-352: oc-mirror: add integration tests
  ci-operator/config/openshift/oc-mirror/openshift-oc-mirror-main.yaml
  ci-operator/jobs/openshift/oc-mirror/openshift-oc-mirror-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#67804 add teardown cleanup steps for e2es
  ci-operator/config/Azure/ARO-HCP/Azure-ARO-HCP-main.yaml
  ci-operator/config/Azure/ARO-HCP/Azure-ARO-HCP-main__periodic.yaml
Labels: lgtm, approved, rehearsals-ack

#67806 NO-JIRA: fix: update tnf lanes for 4.19
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.19.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#67829 Set nutanix-4.19-nightly-x86-control-plane-24nodes to always_run false in ocp-qe-perfscale-ci presubmits
  ci-operator/config/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main__nutanix-4.19-nightly-x86-loaded-upgrade-from-4.18.yaml
  ci-operator/jobs/openshift-eng/ocp-qe-perfscale-ci/openshift-eng-ocp-qe-perfscale-ci-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#67805 Add multi-channel ROSA version selection with fix
  ci-operator/step-registry/rosa/cluster/provision/rosa-cluster-provision-commands.sh
  ci-operator/step-registry/rosa/cluster/provision/rosa-cluster-provision-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#67867 Update ibm-roks-toolkit-base.yaml to use 8.10-1753978370
  clusters/app.ci/supplemental-ci-images/ibm-roks-toolkit-base/ibm-roks-toolkit-base.yaml
Labels: lgtm, approved, rehearsals-ack

#67691 CORS-3371: Updating feature gate name to GCPCustomAPIEndpointsInstall
  ci-operator/config/openshift-priv/installer/openshift-priv-installer-main.yaml
  ci-operator/config/openshift-priv/installer/openshift-priv-installer-release-4.20.yaml
  ci-operator/config/openshift-priv/installer/openshift-priv-installer-release-4.21.yaml
  ci-operator/config/openshift/installer/openshift-installer-main.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.20.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.21.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-main__installer-rehearse-4.20.yaml
  ci-operator/step-registry/openshift/e2e/gcp/custom-endpoints/openshift-e2e-gcp-custom-endpoints-workflow.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#65319 filter out sdn cases when cni is other
  ci-operator/step-registry/cucushift/e2e/cucushift-e2e-commands.sh
Labels: lgtm, approved, lifecycle/rotten, rehearsals-ack

#67871 DPTP-4486: Add env NO_REPORTPORTAL to determine whether to send results to ReportPortal
  ci-operator/step-registry/junit2reportportal/junit2reportportal-commands.sh
  ci-operator/step-registry/junit2reportportal/junit2reportportal-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#67834 GITOPS: enabling tests for v1.17 version
  ci-operator/config/redhat-developer/gitops-operator/redhat-developer-gitops-operator-v1.17.yaml
  ci-operator/config/redhat-developer/gitops-operator/redhat-developer-gitops-operator-v1.17__v4.14.yaml
  ci-operator/config/redhat-developer/gitops-operator/redhat-developer-gitops-operator-v1.17__v4.17.yaml
  ci-operator/jobs/redhat-developer/gitops-operator/redhat-developer-gitops-operator-v1.17-presubmits.yaml
  core-services/sanitize-prow-jobs/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#67398 telcov10n: add llc testing workflow and config
  ci-operator/config/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main__llc-cnf-4.19.yaml
  ci-operator/config/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main__llc-cnf-4.20.yaml
  ci-operator/jobs/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main-periodics.yaml
  ci-operator/step-registry/telcov10n/functional/llc-cnf/OWNERS
  ci-operator/step-registry/telcov10n/functional/llc-cnf/telcov10n-functional-llc-cnf-workflow.metadata.json
  ci-operator/step-registry/telcov10n/functional/llc-cnf/telcov10n-functional-llc-cnf-workflow.yaml
  ci-operator/step-registry/telcov10n/functional/llc-cnf/tests/OWNERS
  ci-operator/step-registry/telcov10n/functional/llc-cnf/tests/telcov10n-functional-llc-cnf-tests-commands.sh
  ci-operator/step-registry/telcov10n/functional/llc-cnf/tests/telcov10n-functional-llc-cnf-tests-ref.metadata.json
  ci-operator/step-registry/telcov10n/functional/llc-cnf/tests/telcov10n-functional-llc-cnf-tests-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#67883 NO-JIRA: Add LWS release-0.7.0 branch configurations
  ci-operator/config/openshift/kubernetes-sigs-lws/openshift-kubernetes-sigs-lws-release-0.7.0.yaml
  ci-operator/config/openshift/kubernetes-sigs-lws/openshift-kubernetes-sigs-lws-release-4.19.yaml
  ci-operator/config/openshift/kubernetes-sigs-lws/openshift-kubernetes-sigs-lws-release-4.21.yaml
  ci-operator/jobs/openshift/kubernetes-sigs-lws/openshift-kubernetes-sigs-lws-release-0.7.0-postsubmits.yaml
  ci-operator/jobs/openshift/kubernetes-sigs-lws/openshift-kubernetes-sigs-lws-release-0.7.0-presubmits.yaml
  ci-operator/jobs/openshift/kubernetes-sigs-lws/openshift-kubernetes-sigs-lws-release-4.19-postsubmits.yaml
  ci-operator/jobs/openshift/kubernetes-sigs-lws/openshift-kubernetes-sigs-lws-release-4.19-presubmits.yaml
  ci-operator/jobs/openshift/kubernetes-sigs-lws/openshift-kubernetes-sigs-lws-release-4.20-presubmits.yaml
  ci-operator/jobs/openshift/kubernetes-sigs-lws/openshift-kubernetes-sigs-lws-release-4.21-postsubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#67442 steps.osc: Documentation improvements
  ci-operator/step-registry/sandboxed-containers-operator/env-cm/sandboxed-containers-operator-env-cm-commands.sh
  ci-operator/step-registry/sandboxed-containers-operator/env-cm/sandboxed-containers-operator-env-cm-ref.yaml
  ci-operator/step-registry/sandboxed-containers-operator/get-kata-rpm/sandboxed-containers-operator-get-kata-rpm-ref.yaml
  ci-operator/step-registry/sandboxed-containers-operator/ipi/azure-pre/sandboxed-containers-operator-ipi-azure-pre-chain.yaml
  ci-operator/step-registry/sandboxed-containers-operator/peerpods/param-cm/sandboxed-containers-operator-peerpods-param-cm-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#67893 Update CCAPIO unit test memory and CPU limits
  ci-operator/config/openshift/cluster-capi-operator/openshift-cluster-capi-operator-main.yaml
  ci-operator/config/openshift/cluster-capi-operator/openshift-cluster-capi-operator-release-4.20.yaml
  ci-operator/config/openshift/cluster-capi-operator/openshift-cluster-capi-operator-release-4.21.yaml
Labels: lgtm, approved, rehearsals-ack

#67868 Revert "Add multi-channel ROSA version selection with fix (#67805)"
  ci-operator/step-registry/rosa/cluster/provision/rosa-cluster-provision-commands.sh
  ci-operator/step-registry/rosa/cluster/provision/rosa-cluster-provision-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#67014 OCPBUGS-59237: Remove the "experimental/reliability/minimal" TEST_SUITE from shiftstack periodic jobs
  ci-operator/config/shiftstack/ci/shiftstack-ci-release-4.20.yaml
  ci-operator/step-registry/openshift/e2e/openstack/external-lb/openshift-e2e-openstack-external-lb-workflow.yaml
  ci-operator/step-registry/openshift/e2e/openstack/proxy/openshift-e2e-openstack-proxy-workflow.yaml
  ci-operator/step-registry/openshift/e2e/openstack/singlestackv6/openshift-e2e-openstack-singlestackv6-workflow.yaml
Labels: lgtm, approved, jira/valid-bug, rehearsals-ack, jira/valid-reference

#67649 refine gcp private and custom-dns presubmit jobs
  ci-operator/config/openshift-priv/installer/openshift-priv-installer-main.yaml
  ci-operator/config/openshift-priv/installer/openshift-priv-installer-release-4.19.yaml
  ci-operator/config/openshift-priv/installer/openshift-priv-installer-release-4.20.yaml
  ci-operator/config/openshift-priv/installer/openshift-priv-installer-release-4.21.yaml
  ci-operator/config/openshift/installer/openshift-installer-main.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.19.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.20.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.21.yaml
  ci-operator/jobs/openshift-priv/installer/openshift-priv-installer-main-presubmits.yaml
  ci-operator/jobs/openshift-priv/installer/openshift-priv-installer-release-4.19-presubmits.yaml
  ci-operator/jobs/openshift-priv/installer/openshift-priv-installer-release-4.20-presubmits.yaml
  ci-operator/jobs/openshift-priv/installer/openshift-priv-installer-release-4.21-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-main-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.19-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.20-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.21-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#67910 hypershift: skip tests on gitlint and cursor config changes
  ci-operator/config/openshift/hypershift/openshift-hypershift-main.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.20.yaml
  ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.21.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-main-presubmits.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.20-presubmits.yaml
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-release-4.21-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#67899 gangway: update to latest images and use qci
  clusters/app.ci/prow/03_deployment/gangway.yaml
Labels: lgtm, approved, rehearsals-ack

#67658 add olmv1 orion to check the olmv1 performance
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20-periodics.yaml
  ci-operator/step-registry/openshift-qe/orion/olmv1/OWNERS
  ci-operator/step-registry/openshift-qe/orion/olmv1/openshift-qe-orion-olmv1-commands.sh
  ci-operator/step-registry/openshift-qe/orion/olmv1/openshift-qe-orion-olmv1-ref.metadata.json
  ci-operator/step-registry/openshift-qe/orion/olmv1/openshift-qe-orion-olmv1-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#67932 [INTEROP-8071] Update the slack reporting for the weekly ROSA HCP jobs
  ci-operator/jobs/openshift-logging/extended-logging-tests-interop/openshift-logging-extended-logging-tests-interop-main-periodics.yaml
  ci-operator/jobs/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-release-4.19-periodics.yaml
  ci-operator/jobs/redhat-developer/devspaces-interop-tests/redhat-developer-devspaces-interop-tests-main-periodics.yaml
  ci-operator/jobs/rhbk/sso-test/rhbk-sso-test-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#67921 add validations for release-4.20 branch in red-hat-storage
  core-services/jira-lifecycle-plugin/config.yaml
  core-services/prow/02_config/red-hat-storage/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#67816 oadp-qe: reset OADP_TEST_FOCUS after running kubevirt
  ci-operator/config/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-main__oadp1.5-ocp4.19-testing.yaml
  ci-operator/step-registry/oadp/execute-tests/oadp-execute-tests-commands.sh
  ci-operator/step-registry/oadp/ipi/aws-oadp-qe/oadp-ipi-aws-oadp-qe-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#67902 oadp-qe: update jobs to run on daily basis
  ci-operator/config/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-main__oadp1.5-ocp4.19-testing.yaml
  ci-operator/jobs/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#67598 OCPNODE-3492: Update the presubmit job of instaslice-operator to run on a multinode cluster
  ci-operator/config/openshift/instaslice-operator/openshift-instaslice-operator-next.yaml
  ci-operator/jobs/openshift/instaslice-operator/openshift-instaslice-operator-next-presubmits.yaml
  ci-operator/step-registry/openshift/instaslice-operator/e2e-sno/next/openshift-instaslice-operator-e2e-sno-next-ref.metadata.json
  ci-operator/step-registry/openshift/instaslice-operator/e2e-sno/openshift-instaslice-operator-e2e-sno-commands.sh
  ci-operator/step-registry/openshift/instaslice-operator/e2e-sno/openshift-instaslice-operator-e2e-sno-ref.metadata.json
  ci-operator/step-registry/openshift/instaslice-operator/e2e-sno/openshift-instaslice-operator-e2e-sno-ref.yaml
  ci-operator/step-registry/openshift/instaslice-operator/e2e/OWNERS
  ci-operator/step-registry/openshift/instaslice-operator/e2e/next/OWNERS
  ci-operator/step-registry/openshift/instaslice-operator/e2e/next/openshift-instaslice-operator-e2e-next-commands.sh
  ci-operator/step-registry/openshift/instaslice-operator/e2e/next/openshift-instaslice-operator-e2e-next-ref.metadata.json
  ci-operator/step-registry/openshift/instaslice-operator/e2e/next/openshift-instaslice-operator-e2e-next-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#67909 use golang 1.24 for acm business continuity repos
  ci-operator/config/stolostron/cluster-backup-operator/stolostron-cluster-backup-operator-main.yaml
  ci-operator/config/stolostron/cluster-backup-operator/stolostron-cluster-backup-operator-release-2.15.yaml
  ci-operator/config/stolostron/volsync-addon-controller/stolostron-volsync-addon-controller-main.yaml
  ci-operator/config/stolostron/volsync-addon-controller/stolostron-volsync-addon-controller-release-2.15.yaml
Labels: lgtm, approved, rehearsals-ack

#67800 Cerberus status
  ci-operator/step-registry/redhat-chaos/cerberus/redhat-chaos-cerberus-commands.sh
  ci-operator/step-registry/redhat-chaos/installer/aws/compact/redhat-chaos-installer-aws-compact-workflow.yaml
  ci-operator/step-registry/redhat-chaos/installer/aws/redhat-chaos-installer-aws-workflow.yaml
  ci-operator/step-registry/redhat-chaos/installer/aws/sdn/redhat-chaos-installer-aws-sdn-workflow.yaml
  ci-operator/step-registry/redhat-chaos/installer/azure/aro/upi/redhat-chaos-installer-azure-aro-upi-workflow.yaml
  ci-operator/step-registry/redhat-chaos/installer/azure/ipi/ovn/ipsec/redhat-chaos-installer-azure-ipi-ovn-ipsec-workflow.yaml
  ci-operator/step-registry/redhat-chaos/installer/azure/redhat-chaos-installer-azure-workflow.yaml
  ci-operator/step-registry/redhat-chaos/installer/gcp/ipi/ovn/etcd-encryption/fips/redhat-chaos-installer-gcp-ipi-ovn-etcd-encryption-fips-workflow.yaml
  ci-operator/step-registry/redhat-chaos/installer/gcp/ipi/ovn/ipsec/redhat-chaos-installer-gcp-ipi-ovn-ipsec-workflow.yaml
  ci-operator/step-registry/redhat-chaos/installer/gcp/redhat-chaos-installer-gcp-workflow.yaml
  ci-operator/step-registry/redhat-chaos/installer/ibmcloud/ipi/ovn/redhat-chaos-installer-ibmcloud-ipi-ovn-workflow.yaml
  ci-operator/step-registry/redhat-chaos/observer-stop/redhat-chaos-observer-stop-commands.sh
Labels: lgtm, approved, rehearsals-ack

#67937 Bump NE CoreDNS GCP serial timeout
  ci-operator/config/openshift/coredns/openshift-coredns-main.yaml
  ci-operator/jobs/openshift/coredns/openshift-coredns-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#67947 Fix reference of build04 in build02
  clusters/build-clusters/build02/cert-manager/README.md
Labels: lgtm, approved, rehearsals-ack

#67924 MG-46: [o/mg-operator] Add operator bundle build
  ci-operator/config/openshift/must-gather-operator/openshift-must-gather-operator-master.yaml
  ci-operator/config/openshift/must-gather-operator/openshift-must-gather-operator-release-4.20.yaml
  ci-operator/config/openshift/must-gather-operator/openshift-must-gather-operator-release-4.21.yaml
  ci-operator/jobs/openshift/must-gather-operator/openshift-must-gather-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/must-gather-operator/openshift-must-gather-operator-release-4.20-presubmits.yaml
  ci-operator/jobs/openshift/must-gather-operator/openshift-must-gather-operator-release-4.21-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#67944 core-services/ipi-deprovision: log installer version
  core-services/ipi-deprovision/aws.sh
  core-services/ipi-deprovision/gcp.sh
Labels: lgtm, approved, rehearsals-ack

#67808 bump e2e-benchmarking to 2.5.1
  ci-operator/step-registry/openshift-qe/cluster-density-v2/observer/openshift-qe-cluster-density-v2-observer-observer.yaml
  ci-operator/step-registry/openshift-qe/cluster-density-v2/openshift-qe-cluster-density-v2-ref.yaml
  ci-operator/step-registry/openshift-qe/conc-builds/openshift-qe-conc-builds-ref.yaml
  ci-operator/step-registry/openshift-qe/crd-scale/openshift-qe-crd-scale-ref.yaml
  ci-operator/step-registry/openshift-qe/ingress-perf/openshift-qe-ingress-perf-ref.yaml
  ci-operator/step-registry/openshift-qe/kube-burner-index/openshift-qe-kube-burner-index-ref.yaml
  ci-operator/step-registry/openshift-qe/kube-burner-ingress-perf/openshift-qe-kube-burner-ingress-perf-ref.yaml
  ci-operator/step-registry/openshift-qe/netpol-v2/openshift-qe-netpol-v2-ref.yaml
  ci-operator/step-registry/openshift-qe/network-perf/openshift-qe-network-perf-ref.yaml
  ci-operator/step-registry/openshift-qe/network-smoke/openshift-qe-network-smoke-ref.yaml
  ci-operator/step-registry/openshift-qe/network-vm-perf/openshift-qe-network-vm-perf-ref.yaml
  ci-operator/step-registry/openshift-qe/node-density-cni/openshift-qe-node-density-cni-ref.yaml
  ci-operator/step-registry/openshift-qe/node-density-heavy/openshift-qe-node-density-heavy-ref.yaml
  ci-operator/step-registry/openshift-qe/node-density/openshift-qe-node-density-ref.yaml
  ci-operator/step-registry/openshift-qe/rds-core/openshift-qe-rds-core-ref.yaml
  ci-operator/step-registry/openshift-qe/router-perf/openshift-qe-router-perf-ref.yaml
  ci-operator/step-registry/openshift-qe/udn-density-pods/openshift-qe-udn-density-pods-ref.yaml
  ci-operator/step-registry/openshift-qe/upgrade/openshift-qe-upgrade-ref.yaml
  ci-operator/step-registry/openshift-qe/virt-density/openshift-qe-virt-density-ref.yaml
  ci-operator/step-registry/openshift-qe/virt-udn-density/openshift-qe-virt-udn-density-ref.yaml
  ci-operator/step-registry/openshift-qe/web-burner/openshift-qe-web-burner-ref.yaml
  ci-operator/step-registry/openshift-qe/workers-scale/openshift-qe-workers-scale-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#67961 winc: use owner aliases in AWS steps
  ci-operator/step-registry/ipi/conf/aws/windows-machineset/OWNERS
  ci-operator/step-registry/ipi/conf/aws/windows-machineset/ipi-conf-aws-windows-machineset-ref.metadata.json
  ci-operator/step-registry/openshift/e2e/aws/windows-node/OWNERS
  ci-operator/step-registry/openshift/e2e/aws/windows-node/openshift-e2e-aws-windows-node-workflow.metadata.json
Labels: lgtm, approved, rehearsals-ack

#67965 cnf network: updated hypervisor server
  ci-operator/step-registry/telcov10n/functional/cnf-network/ocp-deploy/telcov10n-functional-cnf-network-ocp-deploy-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#67964 SDCICD-1597: Add ocm client secrets in cleanup jobs
  ci-operator/config/openshift/osde2e/openshift-osde2e-main.yaml
  ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#67948 remove the dependency between CONFIDENTIAL_COMPUTE and ON_HOST_MAINTENANCE
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/c3-metal/private/provision/cucushift-installer-rehearse-gcp-ipi-c3-metal-private-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/confidential-computing/provision/cucushift-installer-rehearse-gcp-ipi-confidential-computing-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/gcp/ipi/secureboot/confidential-computing/provision/cucushift-installer-rehearse-gcp-ipi-secureboot-confidential-computing-provision-chain.yaml
  ci-operator/step-registry/ipi/conf/gcp/confidential-computing/ipi-conf-gcp-confidential-computing-commands.sh
  ci-operator/step-registry/ipi/conf/gcp/confidential-computing/ipi-conf-gcp-confidential-computing-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#67392 Enhance HCP OCPE2E jobs: nightly/candidate and upgrade scenarios
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__amd64-nightly.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__amd64-stable.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__amd64-nightly.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.14-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.15-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.16-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.17-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19-periodics.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20-periodics.yaml
  ci-operator/step-registry/rosa/cluster/upgrade/hcp/rosa-cluster-upgrade-hcp-commands.sh
  ci-operator/step-registry/rosa/cluster/upgrade/hcp/rosa-cluster-upgrade-hcp-ref.yaml
  ci-operator/step-registry/rosa/setup/rosa-setup-commands.sh
  ci-operator/step-registry/rosa/setup/rosa-setup-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#67880 set default tp operator list
  ci-operator/step-registry/cucushift/ota/postupgrade/cucushift-ota-postupgrade-commands.sh
  ci-operator/step-registry/cucushift/ota/preupgrade/cucushift-ota-preupgrade-commands.sh
Labels: lgtm, approved, rehearsals-ack

#67968 DPTP-4486: Write attribute install_method when it's valid
  ci-operator/step-registry/junit2reportportal/junit2reportportal-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#67935 Update kiali test images
  core-services/image-mirroring/_config.yaml
Labels: lgtm, approved, rehearsals-ack

#67983 chore: add openshift-monitoring-bot as trusted bot on some Monitoring…
  core-services/prow/02_config/openshift/cluster-monitoring-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/kube-state-metrics/_pluginconfig.yaml
  core-services/prow/02_config/openshift/node_exporter/_pluginconfig.yaml
  core-services/prow/02_config/openshift/prom-label-proxy/_pluginconfig.yaml
  core-services/prow/02_config/openshift/prometheus-alertmanager/_pluginconfig.yaml
  core-services/prow/02_config/openshift/prometheus-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/prometheus/_pluginconfig.yaml
  core-services/prow/02_config/openshift/thanos/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#66408 IBM data volume provision
  ci-operator/config/redhat-chaos/prow-scripts/redhat-chaos-prow-scripts-main__4.19-nightly.yaml
  ci-operator/step-registry/ibmcloud/provision/blockstorage/OWNERS
  ci-operator/step-registry/ibmcloud/provision/blockstorage/ibmcloud-provision-blockstorage-commands.sh
  ci-operator/step-registry/ibmcloud/provision/blockstorage/ibmcloud-provision-blockstorage-ref.metadata.json
  ci-operator/step-registry/ibmcloud/provision/blockstorage/ibmcloud-provision-blockstorage-ref.yaml
  ci-operator/step-registry/ipi/conf/ibmcloud/ipi-conf-ibmcloud-commands.sh
  ci-operator/step-registry/ipi/conf/ibmcloud/ipi-conf-ibmcloud-ref.yaml
  ci-operator/step-registry/redhat-chaos/container-scenarios/etcd-hangup/redhat-chaos-container-scenarios-etcd-hangup-ref.yaml
  ci-operator/step-registry/redhat-chaos/node-disruptions/infra-outage/redhat-chaos-node-disruptions-infra-outage-ref.yaml
  ci-operator/step-registry/redhat-chaos/node-disruptions/master-outage/redhat-chaos-node-disruptions-master-outage-ref.yaml
  ci-operator/step-registry/redhat-chaos/node-disruptions/worker-outage/redhat-chaos-node-disruptions-worker-outage-ref.yaml
Labels: lgtm, approved, tide/merge-method-squash, rehearsals-ack

#67836 Increase timeout for ppc64le stackrox jobs
  ci-operator/config/stackrox/stackrox/stackrox-stackrox-master.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-periodics.yaml
  ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-presubmits.yaml
Labels: lgtm, approved, ok-to-test, rehearsals-ack

#68001 Added an etcd procedure
  docs/dptp-triage-sop/etcd-slowness.md
Labels: lgtm, approved, rehearsals-ack

#67998 A simple make jobs
  ci-operator/jobs/infra-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#67972 DPTP-4486: Customize test results in different projects
  ci-operator/step-registry/junit2reportportal/junit2reportportal-commands.sh
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#67548 [IBMCloud] add rerun in endpoint-gateway-create
  ci-operator/step-registry/ibmcloud/provision/vpc/endpoints-gateway/ibmcloud-provision-vpc-endpoints-gateway-commands.sh
Labels: lgtm, approved, rehearsals-ack

#67995 Sharding is not supported in 4.18, drop it from CAPZ
  ci-operator/config/openshift/cloud-network-config-controller/openshift-cloud-network-config-controller-release-4.18.yaml
  ci-operator/config/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-release-4.18.yaml
  ci-operator/jobs/openshift/cloud-network-config-controller/openshift-cloud-network-config-controller-release-4.18-presubmits.yaml
  ci-operator/jobs/openshift/cluster-api-provider-azure/openshift-cluster-api-provider-azure-release-4.18-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#68012 Add prow jobs for monitoring standalone main
  ci-operator/config/openshift/openshift-docs/openshift-openshift-docs-monitoring-docs-main.yaml
  ci-operator/jobs/openshift/openshift-docs/openshift-openshift-docs-monitoring-docs-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#68018 NO-ISSUE: Add missing periodic umlb vsphere job
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#67980 OCPNODE-3492: Presubmit job of instaslice-operator to run e2e on a multinode cluster
  ci-operator/config/openshift/instaslice-operator/openshift-instaslice-operator-next.yaml
  ci-operator/jobs/openshift/instaslice-operator/openshift-instaslice-operator-next-presubmits.yaml
  ci-operator/step-registry/openshift/instaslice-operator/e2e-sno/next/openshift-instaslice-operator-e2e-sno-next-ref.metadata.json
  ci-operator/step-registry/openshift/instaslice-operator/e2e-sno/openshift-instaslice-operator-e2e-sno-commands.sh
  ci-operator/step-registry/openshift/instaslice-operator/e2e-sno/openshift-instaslice-operator-e2e-sno-ref.metadata.json
  ci-operator/step-registry/openshift/instaslice-operator/e2e-sno/openshift-instaslice-operator-e2e-sno-ref.yaml
  ci-operator/step-registry/openshift/instaslice-operator/e2e/OWNERS
  ci-operator/step-registry/openshift/instaslice-operator/e2e/next/OWNERS
  ci-operator/step-registry/openshift/instaslice-operator/e2e/next/openshift-instaslice-operator-e2e-next-commands.sh
  ci-operator/step-registry/openshift/instaslice-operator/e2e/next/openshift-instaslice-operator-e2e-next-ref.metadata.json
  ci-operator/step-registry/openshift/instaslice-operator/e2e/next/openshift-instaslice-operator-e2e-next-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#67975 CNTRLPLANE-1248:[KAS]Call OTE in the ci in order to ensure that the tests will be executed always
  ci-operator/config/openshift/cluster-kube-apiserver-operator/openshift-cluster-kube-apiserver-operator-main.yaml
  ci-operator/config/openshift/cluster-kube-apiserver-operator/openshift-cluster-kube-apiserver-operator-release-4.20.yaml
  ci-operator/config/openshift/cluster-kube-apiserver-operator/openshift-cluster-kube-apiserver-operator-release-4.21.yaml
  ci-operator/jobs/openshift/cluster-kube-apiserver-operator/openshift-cluster-kube-apiserver-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/cluster-kube-apiserver-operator/openshift-cluster-kube-apiserver-operator-release-4.20-presubmits.yaml
  ci-operator/jobs/openshift/cluster-kube-apiserver-operator/openshift-cluster-kube-apiserver-operator-release-4.21-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#67637 cnf network: added 4.14 ci lane
  ci-operator/config/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main__cnf-network-4.14.yaml
  ci-operator/jobs/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main-periodics.yaml
  ci-operator/step-registry/telcov10n/functional/cnf-network/clone-z-stream-issue/telcov10n-functional-cnf-network-clone-z-stream-issue-commands.sh
  ci-operator/step-registry/telcov10n/functional/cnf-network/cnf-tests/telcov10n-functional-cnf-network-cnf-tests-commands.sh
  ci-operator/step-registry/telcov10n/functional/cnf-network/ocp-deploy/telcov10n-functional-cnf-network-ocp-deploy-commands.sh
  ci-operator/step-registry/telcov10n/functional/cnf-network/ocp-deploy/telcov10n-functional-cnf-network-ocp-deploy-ref.yaml
  ci-operator/step-registry/telcov10n/functional/cnf-network/switch-config/telcov10n-functional-cnf-network-switch-config-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#68024 Add last level cache test results to eco-ci-cd-notifications channel
  ci-operator/config/openshift-kni/eco-ci-cd/.config.prowgen
  ci-operator/jobs/openshift-kni/eco-ci-cd/openshift-kni-eco-ci-cd-main-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#68025 update the oc client tool on all ci-tools build root image builds
  clusters/build-clusters/build02/supplemental-ci-images/002_ci-tools-build-root-mabc.yaml
  clusters/build-clusters/build03/supplemental-ci-images/002_ci-tools-build-root-mabc.yaml
  clusters/build-clusters/build06/supplemental-ci-images/002_ci-tools-build-root-mabc.yaml
  clusters/build-clusters/build07/supplemental-ci-images/002_ci-tools-build-root-mabc.yaml
  clusters/build-clusters/build09/supplemental-ci-images/002_ci-tools-build-root-mabc.yaml
  clusters/build-clusters/build10/supplemental-ci-images/002_ci-tools-build-root-mabc.yaml
  clusters/build-clusters/build11/supplemental-ci-images/002_ci-tools-build-root-mabc.yaml
Labels: lgtm, approved, rehearsals-ack

#68028 Network Edge: bump timeout on serial jobs
  ci-operator/config/openshift/cluster-dns-operator/openshift-cluster-dns-operator-master.yaml
  ci-operator/config/openshift/router/openshift-router-master.yaml
  ci-operator/jobs/openshift/cluster-dns-operator/openshift-cluster-dns-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/router/openshift-router-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#68020 Revert "Disable build02"
  core-services/sanitize-prow-jobs/_clusters.yaml
Labels: lgtm, approved, rehearsals-ack

#66797 AUTOSCALE-256: add e2e-kwok karpenter core perioidic/presubmit test
  ci-operator/config/openshift/kubernetes-sigs-karpenter/openshift-kubernetes-sigs-karpenter-main.yaml
  ci-operator/jobs/openshift/kubernetes-sigs-karpenter/openshift-kubernetes-sigs-karpenter-main-periodics.yaml
  ci-operator/jobs/openshift/kubernetes-sigs-karpenter/openshift-kubernetes-sigs-karpenter-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#68027 Update config for tssc-cli/rhtap-cli rename
  ci-operator/config/redhat-appstudio/tssc-cli/OWNERS
  ci-operator/config/redhat-appstudio/tssc-cli/redhat-appstudio-tssc-cli-main.yaml
  ci-operator/jobs/redhat-appstudio/tssc-cli/OWNERS
  ci-operator/jobs/redhat-appstudio/tssc-cli/redhat-appstudio-tssc-cli-main-periodics.yaml
  ci-operator/jobs/redhat-appstudio/tssc-cli/redhat-appstudio-tssc-cli-main-postsubmits.yaml
  ci-operator/jobs/redhat-appstudio/tssc-cli/redhat-appstudio-tssc-cli-main-presubmits.yaml
  core-services/prow/02_config/redhat-appstudio/rhtap-cli/OWNERS copy
  core-services/prow/02_config/redhat-appstudio/tssc-cli/OWNERS
  core-services/prow/02_config/redhat-appstudio/tssc-cli/_pluginconfig.yaml
  core-services/prow/02_config/redhat-appstudio/tssc-cli/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#68040 [o/mg-operator] Move ci/validate -> ci/validate-boilerplate and mark as optional
  ci-operator/config/openshift/must-gather-operator/openshift-must-gather-operator-master.yaml
  ci-operator/config/openshift/must-gather-operator/openshift-must-gather-operator-release-4.20.yaml
  ci-operator/config/openshift/must-gather-operator/openshift-must-gather-operator-release-4.21.yaml
  ci-operator/jobs/openshift/must-gather-operator/openshift-must-gather-operator-master-presubmits.yaml
  ci-operator/jobs/openshift/must-gather-operator/openshift-must-gather-operator-release-4.20-presubmits.yaml
  ci-operator/jobs/openshift/must-gather-operator/openshift-must-gather-operator-release-4.21-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#67828 PERFSCALE-3645: Replace telco-bastion with ocp-qe-perfscale-ci image in openshift-qe bm steps
  ci-operator/step-registry/openshift-qe/installer/bm/foreman/openshift-qe-installer-bm-foreman-commands.sh
  ci-operator/step-registry/openshift-qe/installer/bm/foreman/openshift-qe-installer-bm-foreman-ref.yaml
  ci-operator/step-registry/openshift-qe/installer/bm/load-kubeconfig/openshift-qe-installer-bm-load-kubeconfig-commands.sh
  ci-operator/step-registry/openshift-qe/installer/bm/load-kubeconfig/openshift-qe-installer-bm-load-kubeconfig-ref.yaml
  ci-operator/step-registry/openshift-qe/installer/bm/ping/openshift-qe-installer-bm-ping-ref.yaml
  ci-operator/step-registry/openshift-qe/installer/bm/poweroff/openshift-qe-installer-bm-poweroff-commands.sh
  ci-operator/step-registry/openshift-qe/installer/bm/poweroff/openshift-qe-installer-bm-poweroff-ref.yaml
  ci-operator/step-registry/openshift-qe/installer/bm/self-sched-terminate/openshift-qe-installer-bm-self-sched-terminate-commands.sh
  ci-operator/step-registry/openshift-qe/installer/bm/self-sched-terminate/openshift-qe-installer-bm-self-sched-terminate-ref.yaml
  ci-operator/step-registry/openshift-qe/installer/bm/self-sched/openshift-qe-installer-bm-self-sched-commands.sh
  ci-operator/step-registry/openshift-qe/installer/bm/self-sched/openshift-qe-installer-bm-self-sched-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#68054 Disable OSSM Sail Ambient TestZtunnelSecureMetrics test
  ci-operator/config/openshift-service-mesh/istio/openshift-service-mesh-istio-master.yaml
Labels: lgtm, approved, rehearsals-ack

#67954 need to upgrade to Go 1.24 for Kubernetes API version v0.33.3
  ci-operator/config/openshift/cluster-samples-operator/openshift-cluster-samples-operator-main__okd-scos.yaml
Labels: lgtm, approved, rehearsals-ack

#67928 OCPQE-30469: Add ABI OVE workflow
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19__amd64-stable.yaml
  ci-operator/jobs/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.19-periodics.yaml
  ci-operator/step-registry/agent-qe/baremetal/OWNERS
  ci-operator/step-registry/agent-qe/baremetal/install/OWNERS
  ci-operator/step-registry/agent-qe/baremetal/install/ove/OWNERS
  ci-operator/step-registry/agent-qe/baremetal/install/ove/agent-qe-baremetal-install-ove-commands.sh
  ci-operator/step-registry/agent-qe/baremetal/install/ove/agent-qe-baremetal-install-ove-ref.metadata.json
  ci-operator/step-registry/agent-qe/baremetal/install/ove/agent-qe-baremetal-install-ove-ref.yaml
  ci-operator/step-registry/agent-qe/baremetal/install/ove/disconnected/OWNERS
  ci-operator/step-registry/agent-qe/baremetal/install/ove/disconnected/agent-qe-baremetal-install-ove-disconnected-chain.metadata.json
  ci-operator/step-registry/agent-qe/baremetal/install/ove/disconnected/agent-qe-baremetal-install-ove-disconnected-chain.yaml
  ci-operator/step-registry/agent-qe/baremetal/install/ove/disconnected/agent-qe-baremetal-install-ove-disconnected-workflow.metadata.json
  ci-operator/step-registry/agent-qe/baremetal/install/ove/disconnected/agent-qe-baremetal-install-ove-disconnected-workflow.yaml
  ci-operator/step-registry/agent-qe/baremetal/install/ove/disconnected/agent-tui/OWNERS
  ci-operator/step-registry/agent-qe/baremetal/install/ove/disconnected/agent-tui/agent-qe-baremetal-install-ove-disconnected-agent-tui-commands.sh
  ci-operator/step-registry/agent-qe/baremetal/install/ove/disconnected/agent-tui/agent-qe-baremetal-install-ove-disconnected-agent-tui-ref.metadata.json
  ci-operator/step-registry/agent-qe/baremetal/install/ove/disconnected/agent-tui/agent-qe-baremetal-install-ove-disconnected-agent-tui-ref.yaml
  ci-operator/step-registry/agent-qe/baremetal/install/ove/disconnected/assisted-ui/OWNERS
  ci-operator/step-registry/agent-qe/baremetal/install/ove/disconnected/assisted-ui/agent-qe-baremetal-install-ove-disconnected-assisted-ui-commands.sh
  ci-operator/step-registry/agent-qe/baremetal/install/ove/disconnected/assisted-ui/agent-qe-baremetal-install-ove-disconnected-assisted-ui-ref.metadata.json
  ci-operator/step-registry/agent-qe/baremetal/install/ove/disconnected/assisted-ui/agent-qe-baremetal-install-ove-disconnected-assisted-ui-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#67759 Many custom CRDs do not cause oc throttling errors
  ci-operator/config/openshift/svt/openshift-svt-master__regression-aws-4.19-nightly-x86.yaml
  ci-operator/jobs/openshift/svt/openshift-svt-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#67894 TRT-2226: Drop e2e-aws-ovn-edge-zones as required on origin
  ci-operator/config/openshift/origin/openshift-origin-main.yaml
  ci-operator/jobs/openshift/origin/openshift-origin-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#68068 Allow use of net_admin/net_raw for pods
  ci-operator/step-registry/openshift/cluster-bot/rbac/openshift-cluster-bot-rbac-commands.sh
  ci-operator/step-registry/openshift/e2e/netadmin-rbac/OWNERS
  ci-operator/step-registry/openshift/e2e/netadmin-rbac/openshift-e2e-netadmin-rbac-commands.sh
  ci-operator/step-registry/openshift/e2e/netadmin-rbac/openshift-e2e-netadmin-rbac-ref.metadata.json
  ci-operator/step-registry/openshift/e2e/netadmin-rbac/openshift-e2e-netadmin-rbac-ref.yaml
  clusters/build-clusters/common_except_app.ci/restricted-v2-plus-netadmin.yaml
Labels: lgtm, approved, rehearsals-ack

#67844 OCPBUGS-52248: rename 'master' to 'main' for cluster-capacity
  ci-operator/config/openshift-priv/cluster-capacity/openshift-priv-cluster-capacity-main.yaml
  ci-operator/config/openshift/cluster-capacity/openshift-cluster-capacity-main.yaml
  ci-operator/jobs/openshift-priv/cluster-capacity/openshift-priv-cluster-capacity-main-postsubmits.yaml
  ci-operator/jobs/openshift-priv/cluster-capacity/openshift-priv-cluster-capacity-main-presubmits.yaml
  ci-operator/jobs/openshift/cluster-capacity/openshift-cluster-capacity-main-postsubmits.yaml
  ci-operator/jobs/openshift/cluster-capacity/openshift-cluster-capacity-main-presubmits.yaml
Labels: lgtm, approved, jira/valid-bug, rehearsals-ack, jira/valid-reference

#68067 MULTIARCH-5196: increase grace_period to 4hrs
  ci-operator/step-registry/upi/install/heterogeneous/powervs/upi-install-heterogeneous-powervs-ref.yaml
  ci-operator/step-registry/upi/install/heterogeneous/vpc/upi-install-heterogeneous-vpc-ref.yaml
  ci-operator/step-registry/upi/install/powervs/cluster/upi-install-powervs-cluster-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#68075 SREP-1552: Mirror quay.io/redhat-services-prod/openshift/boilerplate:image-v8.1.0
  core-services/image-mirroring/_config.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#68022 kubevirt: ssp: add CI for branch: release-v0.24
  ci-operator/config/kubevirt/ssp-operator/kubevirt-ssp-operator-release-v0.24.yaml
  ci-operator/jobs/kubevirt/ssp-operator/kubevirt-ssp-operator-release-v0.24-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#68061 openshift-qe-installer-bm-prereqs: Wait for IDRAC to become unreachable afer reset
  ci-operator/step-registry/openshift-qe/installer/bm/prereqs/openshift-qe-installer-bm-prereqs-commands.sh
Labels: lgtm, approved, rehearsals-ack

#68072 chore(backstage-performance): switch to python 3.12 for runner image
  ci-operator/config/redhat-performance/backstage-performance/redhat-performance-backstage-performance-main.yaml
Labels: lgtm, approved, rehearsals-ack

#68065 Updates cloud-provider-gcp CI Jobs
  ci-operator/config/openshift/cloud-provider-gcp/openshift-cloud-provider-gcp-main.yaml
  ci-operator/jobs/openshift/cloud-provider-gcp/openshift-cloud-provider-gcp-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#67412 Fix 4.18 promotion for sriov projects
  ci-operator/config/openshift/ib-sriov-cni/openshift-ib-sriov-cni-release-4.18.yaml
  ci-operator/config/openshift/pf-status-relay-operator/openshift-pf-status-relay-operator-release-4.18.yaml
  ci-operator/config/openshift/pf-status-relay/openshift-pf-status-relay-release-4.18.yaml
  ci-operator/config/openshift/rdma-cni/openshift-rdma-cni-release-4.18.yaml
  ci-operator/config/openshift/sriov-cni/openshift-sriov-cni-release-4.18.yaml
  ci-operator/config/openshift/sriov-dp-admission-controller/openshift-sriov-dp-admission-controller-release-4.18.yaml
  ci-operator/config/openshift/sriov-network-device-plugin/openshift-sriov-network-device-plugin-release-4.18.yaml
  ci-operator/config/openshift/sriov-network-metrics-exporter/openshift-sriov-network-metrics-exporter-release-4.18.yaml
  ci-operator/config/openshift/sriov-network-operator/openshift-sriov-network-operator-release-4.18.yaml
  core-services/image-mirroring/openshift/mapping_origin_sriov-4_18
Labels: lgtm, approved, rehearsals-ack

#68059 MGMT-20910: Change assisted CI e2e jobs to install 4.20
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-main.yaml
  ci-operator/config/openshift/assisted-image-service/openshift-assisted-image-service-main__edge.yaml
  ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master__edge.yaml
  ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-master__edge.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/config/openshift/cluster-api-provider-agent/openshift-cluster-api-provider-agent-master.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-main-periodics.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-main-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-image-service/openshift-assisted-image-service-main-presubmits.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master-periodics.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master-presubmits.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-master-periodics.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-master-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-installer/openshift-assisted-installer-master-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-periodics.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-periodics.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-postsubmits.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#67903 CORENET-5066: add openshift-pr-manager bot as trusted for ovnk
  core-services/prow/02_config/openshift/ovn-kubernetes/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#68026 SPLAT-2418: Removed TEST_SKIPS for vsphere TP serial due to perma-failing e2e due to no found tests
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-main.yaml
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-release-4.20.yaml
  ci-operator/config/openshift/machine-api-operator/openshift-machine-api-operator-release-4.21.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#68099 NO-JIRA: Add ardaguclu as backport-risk-assessed label for oc
  core-services/prow/02_config/openshift/oc/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#68101 [OSP] add golang 1.23 image
  ci-operator/config/openstack-k8s-operators/openstack-k8s-operators-ci/openstack-k8s-operators-openstack-k8s-operators-ci-main.yaml
Labels: lgtm, approved, rehearsals-ack

#68066 CNTRLPLANE-777: Add-aks-419-informing
  core-services/release-controller/_releases/priv/release-ocp-4.19.json
  core-services/release-controller/_releases/release-ocp-4.19.json
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#68108 Remove blocking status from the power install analysis jobs during migration
  core-services/release-controller/_releases/priv/release-ocp-4.19-multi.json
  core-services/release-controller/_releases/priv/release-ocp-4.19-ppc64le.json
  core-services/release-controller/_releases/priv/release-ocp-4.20-multi.json
  core-services/release-controller/_releases/priv/release-ocp-4.20-ppc64le.json
  core-services/release-controller/_releases/release-ocp-4.19-multi.json
  core-services/release-controller/_releases/release-ocp-4.19-ppc64le.json
  core-services/release-controller/_releases/release-ocp-4.20-multi.json
  core-services/release-controller/_releases/release-ocp-4.20-ppc64le.json
Labels: lgtm, approved, rehearsals-ack

#67900 SPLAT-2389: Promoted vSphere multi disk to GA
  ci-operator/config/openshift-priv/installer/openshift-priv-installer-main.yaml
  ci-operator/config/openshift-priv/installer/openshift-priv-installer-release-4.20.yaml
  ci-operator/config/openshift-priv/installer/openshift-priv-installer-release-4.21.yaml
  ci-operator/config/openshift/installer/openshift-installer-main.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.20.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.21.yaml
  ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.20__amd64-nightly.yaml
  ci-operator/config/openshift/release/openshift-release-master__nightly-4.20.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#67943 no-jira: Add allowed users to whereabouts_cni
  core-services/prow/02_config/openshift/whereabouts-cni/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#68114 METAL-1525 Increase disk size to avoid DiskPressure
  ci-operator/step-registry/baremetalds/e2e/upgrade/ovn/ipv4/baremetalds-e2e-upgrade-ovn-ipv4-workflow.yaml
  ci-operator/step-registry/baremetalds/e2e/upgrade/ovn/ipv6/baremetalds-e2e-upgrade-ovn-ipv6-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#68117 oadp: update oadp version to 1.5.1-23
  ci-operator/config/oadp-qe/oadp-qe-automation/oadp-qe-oadp-qe-automation-main__oadp1.5-ocp4.19-testing.yaml
Labels: lgtm, approved, rehearsals-ack

#68133 MGMT-21459: temporarily stop nutanix jobs
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-assisted-version-placeholder.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-cloud_hotfix_releases.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-v2.42.yaml
  ci-operator/config/openshift/assisted-service/openshift-assisted-service-v2.43.yaml
  ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-assisted-version-placeholder-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-cloud_hotfix_releases-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-v2.42-presubmits.yaml
  ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-v2.43-presubmits.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-periodics.yaml
  ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#68136 Fixed some scripts to be in compliance with new shellcheck
  ci-operator/step-registry/azure/provision/service-principal/minimal-permission/azure-provision-service-principal-minimal-permission-commands.sh
  ci-operator/step-registry/cucushift/hypershift-extended/enable-qe/pull-secret/cucushift-hypershift-extended-enable-qe-pull-secret-commands.sh
  ci-operator/step-registry/cucushift/installer/check/vsphere/customized-resource/cucushift-installer-check-vsphere-customized-resource-commands.sh
  ci-operator/step-registry/cucushift/ota/postupgrade/cucushift-ota-postupgrade-commands.sh
  ci-operator/step-registry/cucushift/ota/preupgrade/cucushift-ota-preupgrade-commands.sh
  ci-operator/step-registry/cucushift/upgrade/setchannel/cucushift-upgrade-setchannel-commands.sh
  ci-operator/step-registry/cucushift/upgrade/toversion/cucushift-upgrade-toversion-commands.sh
  ci-operator/step-registry/distributed-tracing/install/disconnected/distributed-tracing-install-disconnected-commands.sh
  ci-operator/step-registry/gcp/deprovision/cco-manual-users/static/gcp-deprovision-cco-manual-users-static-commands.sh
  ci-operator/step-registry/gcp/deprovision/dns-peering-zone/sa/gcp-deprovision-dns-peering-zone-sa-commands.sh
  ci-operator/step-registry/gcp/deprovision/iam-creds-xpn-roles/gcp-deprovision-iam-creds-xpn-roles-commands.sh
  ci-operator/step-registry/gcp/provision/cco-manual-users/static/gcp-provision-cco-manual-users-static-commands.sh
  ci-operator/step-registry/gcp/provision/dns-peering-zone/sa/gcp-provision-dns-peering-zone-sa-commands.sh
  ci-operator/step-registry/gcp/provision/iam-creds-xpn-roles/gcp-provision-iam-creds-xpn-roles-commands.sh
  ci-operator/step-registry/hypershift/azure/create/nodepool/hypershift-azure-create-nodepool-commands.sh
  ci-operator/step-registry/ibmcloud/provision/vpc/endpoints-gateway/ibmcloud-provision-vpc-endpoints-gateway-commands.sh
  ci-operator/step-registry/ipi/conf/aws/sharednetwork/ipi-conf-aws-sharednetwork-commands.sh
  ci-operator/step-registry/ipi/conf/gcp/oidc-creds-provision/ipi-conf-gcp-oidc-creds-provision-commands.sh
  ci-operator/step-registry/openshift-extended/logging-test/disruptive/openshift-extended-logging-test-disruptive-commands.sh
  ci-operator/step-registry/openshift-extended/logging-test/openshift-extended-logging-test-commands.sh
  ci-operator/step-registry/openshift-extended/rosacli-tests/openshift-extended-rosacli-tests-commands.sh
  ci-operator/step-registry/openshift-extended/test/disasterrecovery/openshift-extended-test-disasterrecovery-commands.sh
  ci-operator/step-registry/openshift-extended/test/disruptive/openshift-extended-test-disruptive-commands.sh
  ci-operator/step-registry/openshift-extended/test/longduration/openshift-extended-test-longduration-commands.sh
  ci-operator/step-registry/openshift-extended/test/openshift-extended-test-commands.sh
  ci-operator/step-registry/openshift-extended/test/stresstest/openshift-extended-test-stresstest-commands.sh
  ci-operator/step-registry/openshift-extended/test/supplementary/openshift-extended-test-supplementary-commands.sh
  ci-operator/step-registry/openshift-extended/upgrade/post/openshift-extended-upgrade-post-commands.sh
  ci-operator/step-registry/openshift-extended/upgrade/pre-custom-cli/openshift-extended-upgrade-pre-custom-cli-commands.sh
  ci-operator/step-registry/openshift-extended/upgrade/pre/openshift-extended-upgrade-pre-commands.sh
  ci-operator/step-registry/openshift-qe/move-pods-infra/openshift-qe-move-pods-infra-commands.sh
  ci-operator/step-registry/osd-ccs/cluster/deprovision/gcp/iam-creds-xpn-roles/osd-ccs-cluster-deprovision-gcp-iam-creds-xpn-roles-commands.sh
  ci-operator/step-registry/osd-ccs/cluster/provision/gcp/osd-ccs-cluster-provision-gcp-commands.sh
  ci-operator/step-registry/redhat-chaos/pod-scenarios/etcd-disruption/redhat-chaos-pod-scenarios-etcd-disruption-commands.sh
  ci-operator/step-registry/redhat-chaos/pvc-scenarios/prometheus-pod/redhat-chaos-pvc-scenarios-prometheus-pod-commands.sh
  ci-operator/step-registry/redhat-chaos/service-disruption/redhat-chaos-service-disruption-commands.sh
  ci-operator/step-registry/redhat-chaos/zone-outage/redhat-chaos-zone-outage-commands.sh
  ci-operator/step-registry/upi/conf/vsphere/platform-external/upi-conf-vsphere-platform-external-commands.sh
  ci-operator/step-registry/upi/conf/vsphere/upi-conf-vsphere-commands.sh
  ci-operator/step-registry/upi/conf/vsphere/vcm/upi-conf-vsphere-vcm-commands.sh
  ci-operator/step-registry/upi/conf/vsphere/zones/upi-conf-vsphere-zones-commands.sh
  ci-operator/step-registry/windows/e2e/operator/test/mirror-images/windows-e2e-operator-test-mirror-images-commands.sh
Labels: lgtm, approved, rehearsals-ack

#68096 gather-extra: use correct container name for ovn-k in IC mode
  ci-operator/step-registry/gather/extra/gather-extra-commands.sh
  ci-operator/step-registry/redhat-appstudio/rhtap-gather/redhat-appstudio-rhtap-gather-commands.sh
Labels: lgtm, approved, rehearsals-ack

#68143 Remove konflux nightlies from gitops and 4.11 testing
  core-services/release-controller/_releases/priv/release-ocp-4.11-arm64.json
  core-services/release-controller/_releases/priv/release-ocp-4.11-multi.json
  core-services/release-controller/_releases/priv/release-ocp-4.11.json
  core-services/release-controller/_releases/release-konflux-ocp-4.12.json
  core-services/release-controller/_releases/release-konflux-ocp-4.13.json
  core-services/release-controller/_releases/release-konflux-ocp-4.14.json
  core-services/release-controller/_releases/release-konflux-ocp-4.15.json
  core-services/release-controller/_releases/release-konflux-ocp-4.16.json
  core-services/release-controller/_releases/release-konflux-ocp-4.17.json
  core-services/release-controller/_releases/release-konflux-ocp-4.18-arm64.json
  core-services/release-controller/_releases/release-konflux-ocp-4.18.json
  core-services/release-controller/_releases/release-konflux-ocp-4.19-arm64.json
  core-services/release-controller/_releases/release-konflux-ocp-4.19-multi.json
  core-services/release-controller/_releases/release-konflux-ocp-4.19.json
  core-services/release-controller/_releases/release-ocp-4.11-arm64.json
  core-services/release-controller/_releases/release-ocp-4.11-ci.json
  core-services/release-controller/_releases/release-ocp-4.11-multi.json
  core-services/release-controller/_releases/release-ocp-4.11.json
Labels: lgtm, approved, rehearsals-ack

#68146 allow TRT to delete PRPQRs
  clusters/app.ci/trt/admin_prpqr_rbac.yaml
Labels: lgtm, approved, rehearsals-ack

#68142 Update multiarch cron timings part 1
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.10.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.11-upgrade-from-nightly-4.10.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.11-upgrade-from-stable-4.10.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.11.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.12-upgrade-from-nightly-4.11.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.12-upgrade-from-stable-4.11.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.12.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.13-upgrade-from-nightly-4.12.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.13-upgrade-from-stable-4.12.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.13.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.9.yaml
  ci-operator/jobs/openshift/multiarch/openshift-multiarch-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#68112 SREP-1535 Update OPS SOP PR Check
  ci-operator/config/openshift/ops-sop/openshift-ops-sop-master.yaml
  ci-operator/jobs/openshift/ops-sop/openshift-ops-sop-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#68150 update the call interval from 5 to 15 minutes
  ci-operator/jobs/openshift/hypershift/openshift-hypershift-infra-periodics.yaml
Labels: lgtm, approved, rehearsals-ack

#68153 SREP-1535 Add Lint CI Job
  ci-operator/config/openshift/ops-sop/openshift-ops-sop-master.yaml
  ci-operator/jobs/openshift/ops-sop/openshift-ops-sop-master-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#68094 app.ci/gangway: add static token for oadp-dev group
  clusters/app.ci/gangway-tokens/oadp-dev/admin_rbac.yaml
  clusters/app.ci/prow/03_deployment/gangway.yaml
Labels: lgtm, approved, rehearsals-ack

#68125 Provide default value for logging-test
  ci-operator/step-registry/openshift-extended/logging-test/openshift-extended-logging-test-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#66644 [AWS] Custom DNS
  ci-operator/config/openshift/installer/openshift-installer-main.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.18.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.19.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.20.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.21.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-main__installation-nightly-4.19.yaml
  ci-operator/config/openshift/verification-tests/openshift-verification-tests-main__installation-nightly-4.20.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-main-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.18-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.19-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.20-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.21-presubmits.yaml
  ci-operator/jobs/openshift/verification-tests/openshift-verification-tests-main-periodics.yaml
  ci-operator/step-registry/aws/provision/bastionhost/aws-provision-bastionhost-commands.sh
  ci-operator/step-registry/aws/provision/private-custom-dns/OWNERS
  ci-operator/step-registry/aws/provision/private-custom-dns/aws-provision-private-custom-dns-commands.sh
  ci-operator/step-registry/aws/provision/private-custom-dns/aws-provision-private-custom-dns-ref.metadata.json
  ci-operator/step-registry/aws/provision/private-custom-dns/aws-provision-private-custom-dns-ref.yaml
  ci-operator/step-registry/aws/provision/public-custom-dns/OWNERS
  ci-operator/step-registry/aws/provision/public-custom-dns/aws-provision-public-custom-dns-commands.sh
  ci-operator/step-registry/aws/provision/public-custom-dns/aws-provision-public-custom-dns-ref.metadata.json
  ci-operator/step-registry/aws/provision/public-custom-dns/aws-provision-public-custom-dns-ref.yaml
  ci-operator/step-registry/cucushift/installer/check/aws/private/cucushift-installer-check-aws-private-commands.sh
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/custom-dns/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/custom-dns/cucushift-installer-rehearse-aws-ipi-custom-dns-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/custom-dns/cucushift-installer-rehearse-aws-ipi-custom-dns-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/custom-dns/private/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/custom-dns/private/cucushift-installer-rehearse-aws-ipi-custom-dns-private-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/custom-dns/private/cucushift-installer-rehearse-aws-ipi-custom-dns-private-workflow.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/custom-dns/private/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/custom-dns/private/provision/cucushift-installer-rehearse-aws-ipi-custom-dns-private-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/custom-dns/private/provision/cucushift-installer-rehearse-aws-ipi-custom-dns-private-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/custom-dns/provision/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/custom-dns/provision/cucushift-installer-rehearse-aws-ipi-custom-dns-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/custom-dns/provision/cucushift-installer-rehearse-aws-ipi-custom-dns-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/user-provisioned-dns/provision/cucushift-installer-rehearse-aws-ipi-user-provisioned-dns-provision-chain.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/ipi/user-provisioned-dns/provision/cucushift-installer-rehearse-aws-ipi-user-provisioned-dns-provision-chain.yaml
  ci-operator/step-registry/cucushift/installer/rehearse/aws/usgov/ipi/custom-dns/OWNERS
  ci-operator/step-registry/cucushift/installer/rehearse/aws/usgov/ipi/custom-dns/cucushift-installer-rehearse-aws-usgov-ipi-custom-dns-workflow.metadata.json
  ci-operator/step-registry/cucushift/installer/rehearse/aws/usgov/ipi/custom-dns/cucushift-installer-rehearse-aws-usgov-ipi-custom-dns-workflow.yaml
  ci-operator/step-registry/gcp/deprovision/public-dns-zone/record-sets/OWNERS
  ci-operator/step-registry/gcp/deprovision/public-dns-zone/record-sets/gcp-deprovision-public-dns-zone-record-sets-commands.sh
  ci-operator/step-registry/gcp/deprovision/public-dns-zone/record-sets/gcp-deprovision-public-dns-zone-record-sets-ref.metadata.json
  ci-operator/step-registry/gcp/deprovision/public-dns-zone/record-sets/gcp-deprovision-public-dns-zone-record-sets-ref.yaml
  ci-operator/step-registry/gcp/provision/public-dns-zone/record-sets/OWNERS
  ci-operator/step-registry/gcp/provision/public-dns-zone/record-sets/gcp-provision-public-dns-zone-record-sets-commands.sh
  ci-operator/step-registry/gcp/provision/public-dns-zone/record-sets/gcp-provision-public-dns-zone-record-sets-ref.metadata.json
  ci-operator/step-registry/gcp/provision/public-dns-zone/record-sets/gcp-provision-public-dns-zone-record-sets-ref.yaml
  ci-operator/step-registry/ipi/install/install/in-bastion/ipi-install-install-in-bastion-commands.sh
  ci-operator/step-registry/openshift/e2e/aws/custom-dns/OWNERS
  ci-operator/step-registry/openshift/e2e/aws/custom-dns/openshift-e2e-aws-custom-dns-workflow.metadata.json
  ci-operator/step-registry/openshift/e2e/aws/custom-dns/openshift-e2e-aws-custom-dns-workflow.yaml
Labels: lgtm, approved, rehearsals-ack

#68058 fix the operator group and openshift AI manifests on build09
  clusters/build-clusters/build09/openshift-ai/operator.yaml
  clusters/build-clusters/build09/openshift-ai/serverless.yaml
Labels: lgtm, approved, rehearsals-ack

#68162 NOJIRA: update image-registry prow config
  core-services/prow/02_config/openshift/cluster-image-registry-operator/_pluginconfig.yaml
  core-services/prow/02_config/openshift/image-registry/_pluginconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#68170 SREP-1200 Bootstrapping Configuration for rhobs/rhobs-synthetics-agent
  ci-operator/config/rhobs/rhobs-synthetics-agent/OWNERS
  ci-operator/config/rhobs/rhobs-synthetics-agent/rhobs-rhobs-synthetics-agent-main.yaml
  ci-operator/jobs/rhobs/rhobs-synthetics-agent/OWNERS
  ci-operator/jobs/rhobs/rhobs-synthetics-agent/rhobs-rhobs-synthetics-agent-main-presubmits.yaml
  core-services/prow/02_config/rhobs/rhobs-synthetics-agent/_pluginconfig.yaml
  core-services/prow/02_config/rhobs/rhobs-synthetics-agent/_prowconfig.yaml
Labels: lgtm, approved, tide/merge-method-squash, rehearsals-ack

#68145 MGMT-21239: moving the deploy script of assisted chat to it's source repo
  ci-operator/config/rh-ecosystem-edge/assisted-chat/rh-ecosystem-edge-assisted-chat-main.yaml
  ci-operator/step-registry/rh-ecosystem-edge/assisted-chat/install/rh-ecosystem-edge-assisted-chat-install-commands.sh
  ci-operator/step-registry/rh-ecosystem-edge/assisted-chat/install/rh-ecosystem-edge-assisted-chat-install-ref.yaml
  ci-operator/step-registry/rh-ecosystem-edge/assisted-chat/rh-ecosystem-edge-assisted-chat-workflow.yaml
  ci-operator/step-registry/rh-ecosystem-edge/assisted-chat/test/rh-ecosystem-edge-assisted-chat-test-ref.yaml
  ci-operator/step-registry/rh-ecosystem-edge/assisted-mcp/install/rh-ecosystem-edge-assisted-mcp-install-commands.sh
  ci-operator/step-registry/rh-ecosystem-edge/assisted-mcp/install/rh-ecosystem-edge-assisted-mcp-install-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#68176 SREP-1580 Add codecov.io CI jobs to rhobs-synthetics-agent
  ci-operator/config/rhobs/rhobs-synthetics-agent/rhobs-rhobs-synthetics-agent-main.yaml
  ci-operator/jobs/rhobs/rhobs-synthetics-agent/rhobs-rhobs-synthetics-agent-main-postsubmits.yaml
  ci-operator/jobs/rhobs/rhobs-synthetics-agent/rhobs-rhobs-synthetics-agent-main-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack

#68175 add keyvault name to ARO-HCP cluster creation
  ci-operator/step-registry/aro-hcp/provision/create-hcp-cluster/aro-hcp-provision-create-hcp-cluster-commands.sh
Labels: lgtm, approved, rehearsals-ack

#68183 update: go version to 1.24 on main branch
  ci-operator/config/opendatahub-io/opendatahub-operator/opendatahub-io-opendatahub-operator-main.yaml
Labels: lgtm, approved, rehearsals-ack

#68221 aws shared network: fix tag failure
  ci-operator/step-registry/ipi/conf/aws/sharednetwork/ipi-conf-aws-sharednetwork-commands.sh
Labels: lgtm, approved, rehearsals-ack

#68194 CNTRLPLANE-1260:[SA]Call OTE in the ci in order to ensure that the tests will be executed always
  ci-operator/config/openshift/service-ca-operator/openshift-service-ca-operator-main.yaml
  ci-operator/config/openshift/service-ca-operator/openshift-service-ca-operator-release-4.20.yaml
  ci-operator/config/openshift/service-ca-operator/openshift-service-ca-operator-release-4.21.yaml
  ci-operator/jobs/openshift/service-ca-operator/openshift-service-ca-operator-main-presubmits.yaml
  ci-operator/jobs/openshift/service-ca-operator/openshift-service-ca-operator-release-4.20-presubmits.yaml
  ci-operator/jobs/openshift/service-ca-operator/openshift-service-ca-operator-release-4.21-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#68138 OLS-1936 lightspeed-operator: golang 1.24 upgrades
  ci-operator/config/openshift/lightspeed-operator/openshift-lightspeed-operator-main.yaml
Labels: lgtm, approved, rehearsals-ack

#67437 Update COO jobs and steps to allow passing env vars from Gangway API
  ci-operator/config/rhobs/observability-operator/rhobs-observability-operator-main__amd64-ocp-4.12-azure.yaml
  ci-operator/config/rhobs/observability-operator/rhobs-observability-operator-main__amd64-ocp-4.13-azure.yaml
  ci-operator/config/rhobs/observability-operator/rhobs-observability-operator-main__amd64-ocp-4.14-azure.yaml
  ci-operator/config/rhobs/observability-operator/rhobs-observability-operator-main__amd64-ocp-4.15-azure.yaml
  ci-operator/config/rhobs/observability-operator/rhobs-observability-operator-main__amd64-ocp-4.17-gcp.yaml
  ci-operator/config/rhobs/observability-operator/rhobs-observability-operator-main__amd64-ocp-4.18-gcp.yaml
  ci-operator/config/rhobs/observability-operator/rhobs-observability-operator-main__amd64-ocp-4.19-gcp.yaml
  ci-operator/config/rhobs/observability-operator/rhobs-observability-operator-main__arm64-ocp-4.16-gcp.yaml
  ci-operator/step-registry/rhobs/konflux-catalogsource/rhobs-konflux-catalogsource-commands.sh
  ci-operator/step-registry/rhobs/konflux-catalogsource/rhobs-konflux-catalogsource-ref.yaml
Labels: lgtm, approved, rehearsals-ack

#68169 Onboard `smg247/ai-pr-timeline`
  ci-operator/config/smg247/ai-pr-timeline/OWNERS
  ci-operator/config/smg247/ai-pr-timeline/smg247-ai-pr-timeline-main.yaml
  ci-operator/jobs/smg247/ai-pr-timeline/OWNERS
  ci-operator/jobs/smg247/ai-pr-timeline/smg247-ai-pr-timeline-main-postsubmits.yaml
  ci-operator/jobs/smg247/ai-pr-timeline/smg247-ai-pr-timeline-main-presubmits.yaml
  core-services/prow/02_config/smg247/ai-pr-timeline/OWNERS
  core-services/prow/02_config/smg247/ai-pr-timeline/_pluginconfig.yaml
  core-services/prow/02_config/smg247/ai-pr-timeline/_prowconfig.yaml
Labels: lgtm, approved, rehearsals-ack

#68222 Update validate rover groups script
  hack/validate-rover-groups.sh
Labels: lgtm, approved, rehearsals-ack

#68263 Updated SE team for backport-risk-assessed label
  core-services/prow/02_config/_plugins.yaml
Labels: lgtm, approved, rehearsals-ack

#68204 RHDH Mapt adjustments
  ci-operator/config/redhat-developer/rhdh/redhat-developer-rhdh-main.yaml
  ci-operator/config/redhat-developer/rhdh/redhat-developer-rhdh-release-1.6.yaml
  ci-operator/config/redhat-developer/rhdh/redhat-developer-rhdh-release-1.7.yaml
  ci-operator/jobs/redhat-developer/rhdh/redhat-developer-rhdh-main-periodics.yaml
  ci-operator/jobs/redhat-developer/rhdh/redhat-developer-rhdh-release-1.6-periodics.yaml
  ci-operator/jobs/redhat-developer/rhdh/redhat-developer-rhdh-release-1.7-periodics.yaml
  ci-operator/step-registry/redhat-developer/rhdh/aks/mapt/create/redhat-developer-rhdh-aks-mapt-create-commands.sh
  ci-operator/step-registry/redhat-developer/rhdh/eks/mapt/create/redhat-developer-rhdh-eks-mapt-create-commands.sh
Labels: lgtm, approved, rehearsals-ack

#68152 NO-JIRA: Stabilize ARM/Multi Serial jobs
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.20.yaml
  ci-operator/config/openshift/multiarch/openshift-multiarch-master__nightly-4.21.yaml
  ci-operator/jobs/openshift/multiarch/openshift-multiarch-master-periodics.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#65994 CORENET-5066: add job to create automatic d/s merges for ovnk
  ci-operator/config/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.20__periodics.yaml
  ci-operator/jobs/openshift/ovn-kubernetes/openshift-ovn-kubernetes-release-4.20-periodics.yaml
  ci-operator/step-registry/github/OWNERS
  ci-operator/step-registry/github/downstream-sync/OWNERS
  ci-operator/step-registry/github/downstream-sync/github-downstream-sync-commands.sh
  ci-operator/step-registry/github/downstream-sync/github-downstream-sync-ref.metadata.json
  ci-operator/step-registry/github/downstream-sync/github-downstream-sync-ref.yaml
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#68235 STOR-2463: add csi-external-snapshot-metadata okd image and image mirroring
  ci-operator/config/openshift/csi-external-snapshot-metadata/openshift-csi-external-snapshot-metadata-main__okd-scos.yaml
  ci-operator/jobs/openshift/csi-external-snapshot-metadata/openshift-csi-external-snapshot-metadata-main-postsubmits.yaml
  ci-operator/jobs/openshift/csi-external-snapshot-metadata/openshift-csi-external-snapshot-metadata-main-presubmits.yaml
  core-services/image-mirroring/openshift/mapping_origin_scos-4_20
Labels: lgtm, approved, rehearsals-ack, jira/valid-reference

#68127 Add techPreview job with skipped tests for GCP custom-dns
  ci-operator/config/openshift/installer/openshift-installer-main.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.19.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.20.yaml
  ci-operator/config/openshift/installer/openshift-installer-release-4.21.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-main-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.19-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.20-presubmits.yaml
  ci-operator/jobs/openshift/installer/openshift-installer-release-4.21-presubmits.yaml
Labels: lgtm, approved, rehearsals-ack
